### ISSUE TITLE
Mouse selection from margin not working

### ISSUE THREAD

**Issue by JensMeinecke** [microsoft/terminal#6558] opened 2020-06-18 05:12 UTC
When using the mouse to select text in the console, the user has to be very careful when trying to select from the first character, as the 'margin' in the left is not considered selectable.

It would be nice if clicking within the (say left) margin and dragging to the right the characters from the first one will be selected.

As is, one has to move the mouse carefully onto the first character and then start dragging.

**Comment by DHowett** [comment] 2020-06-18 06:09
Thanks for the report! This is a /duplicate of #5626

**Closed by DHowett** 2020-06-18 06:09 UTC
Labels: Issue-Feature, Needs-Tag-Fix, Needs-Triage
