### ISSUE TITLE
Tab switching doesn't work correctly when using custom key bindings

### ISSUE THREAD

**Issue by sivadeilra** [microsoft/terminal#8290] opened 2020-11-16 18:47 UTC
# Environment

```none
Windows build number: 10.0.20257.1
Windows Terminal version (if applicable): 1.5.3142.0

Any other software?
```

# Steps to reproduce

Modify `settings.json` and add new key bindings for `nextTab` and `prevTab`, like so:

```
"actions": {
        { "command": { "action": "nextTab" }, "keys": "ctrl+pgdn" },
        { "command": { "action": "prevTab" }, "keys": "ctrl+pgup" }
}
```

Save these settings. Open 4 or 5 tabs. Now try to use Control+PgUp / Control+PgDown to cycle through the tabs. It doesn't work -- it gets "stuck" on just one or two of the tabs.

# Expected behavior

I expect that binding to nextTab / prevTab works. It used to work in older versions of Windows Terminal.

# Actual behavior

The tab switcher gets "stuck" on one or two tabs, and it won't switch to any others.

**Comment by Don-Vito** [comment] 2020-11-16 20:57
@sivadeilra - since like a duplicate of https://github.com/microsoft/terminal/issues/8247. A fix for it was already merged to master.

**Comment by zadjii-msft** [comment] 2020-11-17 12:31
Yep, this is a dupe. Thanks for the triage help @Don-Vito!

/dup #8247

**Closed by zadjii-msft** 2020-11-17 12:31 UTC
Labels: Needs-Tag-Fix, Needs-Triage
