### ISSUE TITLE
ESC cancels scroll-back and is sent to shell (?)

### ISSUE THREAD

**Issue by vefatica** [microsoft/terminal#14346] opened 2022-11-05 03:37 UTC
When a Windows Terminal shell pane is scrolled back, ESC cancels the scroll-back AND is also sent to the shell. For all my Windows shells, that wipes out any command line in progress.  Is that as desired?

Consider the scenario in which I'l composing a command and I want to see something from earlier in the session, so I scroll back.  Maybe I don't remember where I left off (so I don't want to just start typing), or the command line is not ready for pasting something I might have copied from the history.  It'd be nice to be able to get back to the command line with it intact.  ESC is my go-to key for such things.  Must ESC also go to the shell when it cancels scroll-back?  Is there another (harmless in all shells) keystroke I could use?

**Comment by carlos-zamora** [comment] 2022-11-07 21:41
You can already do this with <kbd>Ctrl+Shift+End</kbd> to  scroll to the bottom. We've noticed that this behavior is consistent with Gnome Terminal and XTerm.

Aside from that, potential ideas include:
- `scrollToBottom` action can be bound to `ESC`. We would need to add some functionality where if you're already at the bottom, the key chord gets passed through (i.e. "esc" passes to the shell when you're already at the bottom)
- `snapToInput` is a profile setting. We could modify that to include this kind of functionality? That seems like the wrong direction though.
None really sound enticing, tbh. Closing as by design.

**Closed by carlos-zamora** 2022-11-07 21:41 UTC
Labels: Needs-Triage, Needs-Tag-Fix
