### ISSUE TITLE
Terminal font loaded at very small scale.

### ISSUE THREAD

**Issue by kzhuangmc** [microsoft/terminal#5230] opened 2020-04-03 21:49 UTC
# Description of the new feature/enhancement
Feeling like the terminal row height could be reduced few pixels.
For comparison.
I have gnome terminal set up with font: Ubuntu Mono Regular, size 8
and windows terminal set up with font: Ubuntu Mono Regular: size 10.

First of all, despite these two terminals set with different font sizes, the font appears to be 
the same viewing size. The different is windows terminal with size 10 is taller than gnome terminal with font-size 8.

**Comment by kzhuangmc** [comment] 2020-04-03 21:49
![image](https://user-images.githubusercontent.com/44411075/78407747-5e056480-75ba-11ea-9e02-723b9b0a5ada.png)

**Comment by DHowett-MSFT** [comment] 2020-04-03 21:57
Those are definitely different sizes.

Can you put gnome-terminal size 8 and Windows Terminal size 8 next to eachother? Then, can you do the same thing for size 10?

**Comment by kzhuangmc** [comment] 2020-04-04 04:41
![image](https://user-images.githubusercontent.com/44411075/78418724-e81def00-75f3-11ea-85f0-c1a5593f4427.png)

**Comment by kzhuangmc** [comment] 2020-04-04 05:00
Per wikipedia, the font size 72 is roughly an inch. hence for size 8, it will be 1/9th of an inch.

![image](https://user-images.githubusercontent.com/44411075/78419059-92971180-75f6-11ea-815c-6f7d63ab3aa6.png)

**Comment by DHowett-MSFT** [comment] 2020-04-04 05:08
Then I'll need to know what your DPI is in Windows and in X11, because I'm willing to bet that our font size math isn't egregiously incorrect :smile:

**Comment by kzhuangmc** [comment] 2020-04-04 05:16
Well, how about side by side comparison between windows terminal vs Notepad?

![image](https://user-images.githubusercontent.com/44411075/78419245-cb37ea80-75f8-11ea-8d69-6abad0c9c663.png)

**Comment by DHowett-MSFT** [comment] 2020-04-04 05:22
Fair enough!

**Comment by parkovski** [comment] 2020-04-07 17:25
Worth noting that X11 uses 72 DPI by default and Windows uses 96 - could explain why saving screenshots that look the same size on the screen come out as different image sizes.

**Comment by DHowett-MSFT** [comment] 2020-04-07 17:57
This difference is likely to be caused by _hinting_. Different text rendering engines handle hinting differently.

If you compare a font that isn't hinted:

(terminal in the back, notepad in the front)

![image](https://user-images.githubusercontent.com/14316954/78702965-4a117980-78be-11ea-88b3-2fd7ff7b4957.png)

If I overlay them ...

![image](https://user-images.githubusercontent.com/14316954/78703003-57c6ff00-78be-11ea-9139-4bd320b5d303.png)

... the only difference is the subpixel antialiasing artifacts on the edges.

I'm going to mark this one as a /dupe of #1790 (sub #5093) because we're using that issue to track configurable font rendering knobs.

**Closed by DHowett-MSFT** 2020-04-07 17:57 UTC
Labels: Issue-Feature, Needs-Attention, Needs-Tag-Fix, Needs-Triage
