### ISSUE TITLE
'Open a new window' shortcut 

### ISSUE THREAD

**Issue by NeKJ** [microsoft/terminal#3144] opened 2019-10-10 10:05 UTC
I propose to add a new action with a shortcut: `Open New Window`, which will open a new WT window (a new WT process essentially).

I use this often as it is a standard feature of almost all other terminals in other OSes and DEs that I used. I often need to open a new terminal side-by-side with other open terminal windows, in order to view them in parallel (monitor logs with tail -f, work and orchestrate concurrently multiple machines and how they communicate together etc. and I'm sure that are countless other reasons for needing this).

Now, the way to open a new window in WT is either to raise my hand from the keyboard to grab (OMG, I know it's not important but I hate doing this) the mouse and hunt-and-peck the terminal icon in the taskbar to middle click it, or open the windows start menu and navigate through a charade of submenus in order to do it.

This is frustrating for me, wastes my time and makes me feel that "my hands are tight" while using WT, compared to any other terminal in any other OS that I use which is just a shortcut away taking a only the time of a blink of an eye.

Therefore I propose to implement this action and assign a shortcut to it (preferably `Ctrl+Shift+n`).

**Comment by DHowett-MSFT** [comment] 2019-10-10 19:35
This is a /dupe of #1051. Thanks for reporting it! You can also use <kbd>Win+R</kbd> `wt` to spawn a new instance.

**Closed by DHowett-MSFT** 2019-10-10 19:35 UTC
Labels: Issue-Feature, Needs-Tag-Fix, Needs-Triage

**Comment by NeKJ** [comment] 2019-10-11 03:04
Indeed. I apologize, I did try a search for dupes before, but I couldn't find any.

**Comment by chaoscreater** [comment] 2023-08-12 04:10
This still needs to be looked at.

If you have this setting configured like below:

![image](https://github.com/microsoft/terminal/assets/18227319/b1e6eed1-a4cf-4d18-aba3-ce80a901d0c0)

Then running pwsh or WT in the run box will always attach the new process as a tab in the same WT window. There's no way to get it to open another WT process in a separate window. 

Most of the time, I want the new instance behavior to be exactly like what's shown in the screenshot. However, there are occasional times where I want a completely separate window and there needs to be an action or shortcut to do this.
