### ISSUE TITLE
Terminal UI appears in German when using English UK as default

### ISSUE THREAD

**Issue by garetho-starwind** [microsoft/terminal#9466] opened 2021-03-12 10:44 UTC
# Environment

```none
Windows build number: Win32NT             10.0.19042.0 Microsoft Windows NT 10.0.19042.0
Windows Terminal version (if applicable): 1.6.10571.0

Any other software?
```

# Steps to reproduce

In the Windows "Preferred Languages" settings.
Set "English (United Kingdom)" as first option
Set "German (Germany)" as the second option

Launch Windows Terminal

# Expected behavior
Expected behaviour would be that all tool tips and messages would be in English
![image](https://user-images.githubusercontent.com/80518381/110929244-ab886680-831f-11eb-815a-0b1293202c14.png)

# Actual behavior

All of the Tool tips and messages are actually appearing in German
![image](https://user-images.githubusercontent.com/80518381/110929336-c5c24480-831f-11eb-8af1-f1e619ab2185.png)

NOTE: If you put "English (United States)" above "German (Germany)" in the Preferred languages then the tool tips and messages are as expected, so looks like just an issue with ignoring the "English (United Kingdom)" preference

**Comment by zadjii-msft** [comment] 2021-03-12 11:38
> NOTE: If you put "English (United States)" above "German (Germany)" in the Preferred languages then the tool tips and messages are as expected, so looks like just an issue with ignoring the "English (United Kingdom)" preference

Huh. I was gonna say that this sounds like a duplicate of #5497 (or at least, what that issue is tracking), but that's weird. 

@DHowett you're the loc expert - any idea why UK English doesn't work but US English does?

**Comment by DHowett** [comment] 2021-03-12 16:58
This is a weird and specific issue with language fallback that I don't totally understand.

The resource loader takes a set intersection of the user's preferred languages and the application's supported languages. When it does that, it is **very** specific and will only choose languages with a matching country code.

Here's what it looks like:

```
User Language List          Terminal Language
------------------          -----------------
English (UK) - en_GB        
German (Germany) - de_DE    de_DE
English (US) - en_US        en_US
```

There's no automatic fallback from en_GB to en_US. I also don't know if it would fall back from en_GB to just `en`. :|

**Comment by j4james** [comment] 2021-03-12 19:38
FYI, the problem of regional English variants not falling back to US English has been brought up several times before. For example, see #6943 and #6931. And there was at least one example of it in https://github.com/microsoft/terminal/issues/5497#issuecomment-628913822. I thought it was accepted that this was just the way Windows works.

**Comment by zadjii-msft** [comment] 2021-03-15 14:03
Alright well that answers my question. For the rest, I'll just direct this to the bucket we've been throwing this in previously

/dup #5497

Thanks everyone!

**Closed by zadjii-msft** 2021-03-15 14:03 UTC
Labels: Area-Localization, Needs-Tag-Fix, Needs-Triage, Product-Terminal
