### ISSUE TITLE
Some keys don't work with french keyboards

### ISSUE THREAD

**Issue by maxdr88** [microsoft/terminal#1752] opened 2019-07-01 13:05 UTC
# Environment

```none
Windows build number: [Version 10.0.18362.175]
Windows Terminal version: 0.2.1715.0
French azerty keyboard (but the issue might also concern qwerty keyboards)
```

# Steps to reproduce

Type symbols using key "Alt Gr", e.g. ~ # { [ | ` \ ^ @ ] } ¤

# Expected behavior

The symbols should be displayed as they are typed, as they do in any text field/editor.

# Actual behavior

The symbol displayed is the one that should have if the "Alt Gr" key wasn't pressed.

| char wanted | key(s) pressed | char displayed |
| ----------- | -------------- | -------------- |
| é           | é              | é              |
| "           | "              | "              |
| '           | '              | '              |
| (           | (              | (              |
| \-          | \-             | \-             |
| è           | è              | è              |
| _           | _              | _              |
| ç           | ç              | ç              |
| à           | à              | à              |
| )           | )              | )              |
| =           | =              | =              |
| $           | $              | $              |
| \-          | \-             | \-             |
| ~           | Alt Gr + é     | é              |
| \#          | Alt Gr + "     | "              |
| {           | Alt Gr + '     | '              |
| [           | Alt Gr + (     | (              |
| \|          | Alt Gr + -     | -              |
| \`          | Alt Gr + è     | è              |
| \\          | Alt Gr + \_    | \_             |
| ^           | Alt Gr + ç     | ç              |
| @           | Alt Gr + à     | à              |
| ]           | Alt Gr + )     | )              |
| }           | Alt Gr + =     | =              |
| ¤           | Alt Gr + $     | $              | #

**Comment by zadjii-msft** [comment] 2019-07-01 19:34
Please search before filing new issues. This is a _clear_ dupe of #521 which is pinned to the top of the repo.
![image](https://user-images.githubusercontent.com/18356694/60461821-4a813380-9c0d-11e9-8e1c-cdd58fac6608.png)

**Closed by zadjii-msft** 2019-07-01 19:34 UTC
Labels: Needs-Tag-Fix, Needs-Triage
