### ISSUE TITLE
Feature Request - Hide borders

### ISSUE THREAD

**Issue by fpqc** [microsoft/terminal#2939] opened 2019-09-27 14:37 UTC
Okay, first, I want to say, I'm not sure if this is equivalent to 

https://github.com/microsoft/terminal/issues/872

But it would be nice to be able to completely hide the window border that looks like

![image](https://user-images.githubusercontent.com/6083371/65777089-3e890d00-e13b-11e9-9621-eb8338a1f127.png)

What wasn't mentioned in the other topic was that even if we turn off ShowTabsInTitlebar, we still have a small border (which I'm still not a fan of):

![image](https://user-images.githubusercontent.com/6083371/65777630-4eedb780-e13c-11e9-8b22-b84b0205616a.png)

The issue I cited was closed without a clear (to me) resolution, and it's not clear if this feature might be implemented in a future version of Windows or if it's been completely abandoned, so if this is a duplicate, before closing it, could one of the devs clarify the situation?

What would be nice is maybe a hotkey to just hide the entire non-client area.  Support for this would also move toward quake-terminal support (which I guess isn't planned for 1.0).

**Comment by DHowett-MSFT** [comment] 2019-09-30 21:39
This is a dupe of (i-want-my-terminal-to-be-a-floating-box-i-cannot-interact-with), I just don't know the number right now.

**Comment by DHowett-MSFT** [comment] 2019-09-30 21:40
/dup #2238

Thanks @zadjii-msft

**Closed** 2019-09-30 21:40 UTC
Labels: Issue-Feature, Needs-Tag-Fix, Needs-Triage
