### ISSUE TITLE
Unexpected behavior of closeOnExit

### ISSUE THREAD

**Issue by tomasr** [microsoft/terminal#3869] opened 2019-12-06 14:35 UTC
# Environment

Windows 10 version 10.0.18362.0
Windows Terminal 0.7.3291.0
PowerShell Core version 6.2.3

# Steps to reproduce

Created a manual profile for PowerShell Core (as an automatic profile won't get added when it's installed as a dotnet global tool), like this:

```json
    {
      "guid": "{1ba0ecbe-ee5f-4f20-80fc-c7f3376445ca}",
      "name": "PowerShell Core",
      "commandline": "%USERPROFILE%\\.dotnet\\tools\\pwsh.exe",
      "startingDirectory": "%USERPROFILE%",
      "hidden": false,
      "fontFace": "Cascadia Mono PL",
      "fontSize": 13,
      "colorScheme": "Gruvbox Dark"
    }
```

Create a new PowerShell Core window, then run a native command (.exe) that takes a bit of time to run and then immediately hit `Ctrl+C`.

In my case, I've tested this running both java applications as well as `kubectl get pods --all-namespaces` for my kubernetes cluster.

# Expected behavior

I'd expect the native application to handle the `Ctrl+C`, terminate, and get back to the PowerShell Core prompt.

# Actual behavior

The entire Windows Terminal tab is getting killed, as if the shell had been terminated.

What appears to be going on here is related to the `closeOnExit` setting. My original profile used the default value for this, and apparently, Windows Terminal is mistaking the child process terminating due to `Ctrl+C` as the PowerShell Core shell terminating, so it's killing the tab window.

Setting `closeOnExit: false` seems to work around this, and lets the tab open, but the default behavior is very surprising, and seems like a bug tracking which process terminated.

**Comment by DHowett-MSFT** [comment] 2019-12-09 19:26
This looks like it is a bug in the dotnet global tool launcher. It isn't suppressing the _terminate_ event for <kbd>Ctrl+C</kbd>. You see this often in process launchers -- they don't cede full lifetime control to the spawned process.

I'd recommend filing this bug on dotnet upstream, because it will impact all dotnet global consumers.

FWIW: Windows Terminal tracks the console host (in versions <= 0.7) and the root process (in versions >= 8.0) -- if this mechanism fails, Windows' `CreateProcess` has gone terribly, horribly wrong and nothing on the system will work correctly. :smile:

**Comment by tomasr** [comment] 2019-12-09 19:50
I'm somewhat confused.... If the dotnet launcher is the problem, wouldn't I just end up with a dead shell when `closeOnExit: false`, then?

Or are you saying that the top-level process is the dotnet launcher, that is dying, but leaving the underlying powershell core process running attached to the same console?

**Comment by DHowett-MSFT** [comment] 2019-12-09 20:56
Er, sorry about that. The top-level process is the dotnet launcher, and that's the one that's exiting. With `closeOnExit: false`, is the shell actually _usable_ after you `^C` it?

**Comment by tomasr** [comment] 2019-12-09 21:02
Yep, perfectly usable. That's why I said it was the workaround I was currently using.

**Comment by DHowett-MSFT** [comment] 2019-12-09 21:09
_Fascinating._

**Comment by DHowett-MSFT** [comment] 2019-12-09 21:20
With our changes to `closeOnExit` in the upcoming 0.8 release, this'll actually get _worse._ Hmm. I'm going to reopen this for right now.

**Comment by DHowett-MSFT** [comment] 2019-12-10 21:17
I've filed an issue upstream on PowerShell here: https://github.com/PowerShell/PowerShell/issues/11314. It looks like they're ceding ownership of the console to whatever processes happen to be running, and because they are the actual root process, Terminal decides they've exited.

**Comment by tomasr** [comment] 2019-12-10 21:21
Thanks!

**Comment by SoraxOriginali** [comment] 2020-01-16 16:33
In the 0.8 release, instead of the tab closing, it now writes that the process exited and becomes unresponsive. Is this what you meant by worse @DHowett-MSFT ?

**Comment by DHowett-MSFT** [comment] 2020-01-16 16:39
Yep.

**Comment by tomasr** [comment] 2020-01-16 20:12
Can confirm it's definitely worse now.

Now it's broken with both `closeOnExit` enabled or disabled. ¯\_(ツ)_/¯

**Comment by DHowett-MSFT** [comment] 2020-01-17 02:01
Alas. If you're having an issue with the dotnet global version of PowerShell, pile on to https://github.com/PowerShell/PowerShell/issues/11314. If you're having an issue with Scoop, somebody will need to file the same exact issue on them. I don't use scoop, so I do not know anything about their issue process.

**Comment by bgshacklett** [comment] 2020-01-17 18:05
Scoop already has an issue, and are working towards a solution:
https://github.com/lukesampson/scoop/issues/3634

**Comment by Kirlac** [comment] 2020-01-23 02:52
I'm not sure how related this is, but I'm seeing the same exit behaviour with CMD and a batch script (v0.8.10091.0 - `closeOnExit` enabled). It seems like terminating the script with `^C` causes the console to get confused about what state things are in.

Minimal repro using simple infinite-loop batch script:

```
Microsoft Windows [Version 10.0.19041.21]
(c) 2019 Microsoft Corporation. All rights reserved.

C:\Users\Kirlac>more test.bat
@echo off

:Test
    echo test
    timeout 5 > NUL
    GOTO :Test

C:\Users\Kirlac>test.bat
test
test
test
^CTerminate batch job (Y/N)? y

C:\Users\Kirlac>exit

[process exited with code 3221225786]
```

The strange thing is if I do something other than `exit` immediately after killing the batch script this seems to resolve itself and the `exit` command starts working again.

eg. Using the same script as above but calling `cd` between `^C` and `exit`:

```
C:\Users\Kirlac>test.bat
test
test
^CTerminate batch job (Y/N)? y

C:\Users\Kirlac>cd
C:\Users\Kirlac

C:\Users\Kirlac>exit
```
At this point the terminal window closed as expected without the "process exited with code 3221225786" message.

**Comment by kolbeck** [comment] 2020-05-05 09:52
I have the same issue with PowerShell (dotnet global) 6.2.3:
`PowerShell 6.2.3
Copyright (c) Microsoft Corporation. All rights reserved.

https://aka.ms/pscore6-docs
Type 'help' to get help.

PS C:\Users\kolbe> ping 127.0.0.1

Pinging 127.0.0.1 with 32 bytes of data:
Reply from 127.0.0.1: bytes=32 time<1ms TTL=128

Ping statistics for 127.0.0.1:
    Packets: Sent = 1, Received = 1, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 0ms, Maximum = 0ms, Average = 0ms
Control-C

[process exited with code 3221225786]`

But not with PowerShell 7.0.0:
`PowerShell 7.0.0
Copyright (c) Microsoft Corporation. All rights reserved.

https://aka.ms/powershell
Type 'help' to get help.

PS C:\Users\kolbe> ping 127.0.0.1

Pinging 127.0.0.1 with 32 bytes of data:
Reply from 127.0.0.1: bytes=32 time<1ms TTL=128

Ping statistics for 127.0.0.1:
    Packets: Sent = 1, Received = 1, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 0ms, Maximum = 0ms, Average = 0ms
Control-C`

**Comment by DHowett-MSFT** [comment] 2020-05-05 17:06
This is a bug in the dotnet global wrapper that came with powershell 6. The wrapper is exiting when you press ^C, which takes the powershell process down at the same time. 

This is the same issue I linked upthread, https://github.com/PowerShell/PowerShell/issues/11314

**Comment by Dan-J-D** [comment] 2020-07-22 10:42
It is not just powershell, i was running cmd.
![image](https://user-images.githubusercontent.com/52302961/88167238-81decb80-cbe6-11ea-87c2-5c67981f4059.png)
Same thing happened to me when i tried to exit.

**Comment by Ennea** [comment] 2020-08-05 19:35
> It is not just powershell, i was running cmd.

I can confirm this happening. Also happens when, for example, using ping but aborting directly via CTRL-C, then using `exit`. Result is `[process exited with code 3221225786]`.

**Comment by Rezrazi** [comment] 2021-02-21 14:23
bumping this issue.

Any fixes considered for this in the roadmap ? This seems to be encountered only when using cmd shells, no issues with PS or WSL

**Comment by DHowett** [comment] 2021-02-21 23:11
There is nothing for us to fix here. Applications that mishandle Ctrl+C are terminated, as expected, and Terminal is telling you about those applications being terminated.

CMD exiting with an error code after an invalid command is also by design. 

Change the closeOnExit option to “always” if you don’t want to see those error codes.

**Comment by zadjii-msft** [comment] 2021-11-01 13:15
Looks like the upstream https://github.com/PowerShell/PowerShell/issues/11314 was fixed, so I'm gonna close this one out too. Thanks all!

**Closed by zadjii-msft** 2021-11-01 13:15 UTC
Labels: Product-Powershell, Issue-Bug, Area-TerminalConnection, Tracking-External
