### ISSUE TITLE
Blinking cursor shows up in TUI programs (where it shouldn't) in 1.13

### ISSUE THREAD

**Issue by rashil2000** [microsoft/terminal#12401] opened 2022-02-06 18:38 UTC
### Windows Terminal version

1.13.10336.0

### Windows build number

10.0.19044.1348

### Other Software

scoop install [vifm](https://vifm.info)

_and_

scoop install [ncspot](https://github.com/hrkfdn/ncspot)

### Steps to reproduce

Just launch the programs. See below.

![cursor](https://user-images.githubusercontent.com/46838874/152695110-7285ba2e-22dc-401b-a74d-5bd7a5553780.gif)

![cursor1c](https://user-images.githubusercontent.com/46838874/152696172-6c523a5d-3249-411e-81cf-0fdd34dfccce.gif)

### Expected Behavior

The cursor wasn't showing up (at all) in 1.12 Preview. It shouldn't appear.

### Actual Behavior

The cursor appears.

Possibly related - https://github.com/microsoft/terminal/issues/12372 ?

**Comment by lhecker** [comment] 2022-02-06 19:16
Can someone else reproduce this issue? I can't replicate it with vifm 0.12. (ncspot requires a spotify account.)
Neither rendering engine reproduces the issue for me.
Maybe this issue is specific to Windows 10? That seems a bit unlikely though...

**Comment by rashil2000** [comment] 2022-02-06 19:59
I should mention that I manually set TERM to xterm-256color (Neovim needs it to display titles). It was set with 1.12 too. 

(I can provide more details about my environment if required).

**Comment by elsaco** [comment] 2022-02-06 22:07
Demo on Windows 20H2 (10.0.19044.1466) and `vifm` with no customization:

https://user-images.githubusercontent.com/3933920/152703172-04e7f33f-0f47-4117-a14e-233866fc6209.mp4

@rashil2000 seems to be using a custom theme with `starship` prompt (judging by the look of it) that might affect his setup.

**Comment by rashil2000** [comment] 2022-02-07 03:36
I don't think it has anything to do with Starship. My settings.json profile ([here](https://github.com/rashil2000/dotfiles/blob/master/wt/settings.json)) launches Vifm/Ncspot directly, so it doesn't go through any shell. Nevertheless, I disabled Starship completely to test it, and issue still persists.

**Comment by rashil2000** [comment] 2022-02-07 03:42
Here's 1.13 and 1.12 running side-by-side:

![image](https://user-images.githubusercontent.com/46838874/152721027-f4ccbc05-cb7c-4807-ac62-57424f768cc8.png)

**Comment by rashil2000** [comment] 2022-02-07 03:44
My vifmrc is [here](https://github.com/rashil2000/dotfiles/blob/master/vifm/vifmrc)

**Comment by lhecker** [comment] 2022-02-07 15:42
I figured it out. Here's how to reproduce the issue:
* Download vifm: https://github.com/vifm/vifm/releases/download/v0.12/vifm-w64-se-0.12-binary.zip
* Create a `vifmrc` file inside the directory where vifm.exe is
* Add a single line: `highlight clear`
* Create a profile, which has vifm.exe as the command line

This issue doesn't occur when:
* Launched in Windows Terminal 1.12, or...
* Launched from cmd.exe or PowerShell

**Comment by rashil2000** [comment] 2022-02-07 16:03
> Launched from cmd.exe or PowerShell

Wow, you're right. I didn't test it from Cmd or PowerShell. Even Ncspot does not display the cursor when launched from the shell.

**Comment by elsaco** [comment] 2022-02-07 16:51
@rashil2000 matching your profile on Win 10, font include, did not repro on my box. This is for reference only and not trying to undermine your bug.

Profile used for testing:

```
      {
        "commandline": "vifm .",
        "fontFace": "VictorMono NF",
        "fontSize": 11,
        "fontWeight": "semi-bold",
        "colorScheme": "Tango Light",
        "padding": "16, 16, 16, 16",
        "scrollbarState": "hidden",
        "guid": "{9f44d682-c62b-40a3-a8f3-40996da15ef2}",
        "icon": "%UserProfile%\\Pictures\\Icons\\vifm.ico",
        "name": "Vifm"
      }
```


Sample vifm run:

https://user-images.githubusercontent.com/3933920/152833490-e1a09f1d-8e91-4e9e-8d8c-98b55590f2ce.mp4

**Comment by j4james** [comment] 2022-02-07 23:25
I think I might know what the problem is here.

There are two variables in the XtermEngine that track the cursor visibility for conpty: `_lastCursorIsVisible` indicates the last state of the cursor; and `_nextCursorIsVisible` indicates the state for the current frame. At the end of the frame, if there is a difference between `_lastCursorIsVisible` and `_nextCursorIsVisible`, we know we need to send a sequence either to show or hide the cursor.

The problem is that `_lastCursorIsVisible` is initialized as false, so if the cursor is hidden before the first frame is rendered, then we'll reach the end of the frame with both `_lastCursorIsVisible` and `_nextCursorIsVisible` as false. And that makes us think there is no need to send a _hide cursor_ sequence, because we think the cursor is already hidden. This can easily be fixed by initializing `_lastCursorIsVisible` to true.

What I don't understand, is why this would ever have worked. Unless it's a matter of timing, and in previous versions at least one frame would have been painted *before* the application had a chance to hide the cursor.

The other concern is that maybe `_lastCursorIsVisible` was intentionally set to false to guarantee that we send at least one _show cursor_ sequence on startup, in case the client terminal started with a hidden cursor? If that's the case then the `_lastCursorIsVisible` variable may need a third "unknown" state to start with.

**Comment by lhecker** [comment] 2022-02-08 00:22
@j4james You know what's funny? I was about to fix this issue and couldn't for my life replicate it anymore. Only 1 out of maybe 30 tabs of vifm show the cursor issue for me now - it's entirely random, proving that you're right. It's interesting this ever worked.

**Comment by j4james** [comment] 2022-02-08 01:23
FYI, I found that some of the time it might look like it was working at first - i.e. the cursor appeared to be hidden - but that was just because it was positioned off screen. The minute you did something that updated the status bar, it would end up moving the cursor somewhere that would make it visible.

**Closed** 2022-02-08 23:08 UTC
Labels: Area-VT, Issue-Bug, Needs-Triage, Product-Terminal, In-PR, Priority-2
