### ISSUE TITLE
Pressing F7 in Terminal running CMD brings up both the history AND a caret browsing message

### ISSUE THREAD

**Issue by miniksa** [microsoft/terminal#638] opened 2019-05-09 20:45 UTC
Pressing F7 in Windows Terminal DOS brings up both the history AND a caret browsing message

From MSFT: 21451221

**Comment by MeikTranel** [comment] 2019-06-13 19:58
Well it interrupts every F7 keypress. this is especially sad when moving to the WSL world where more rich terminal apps like htop are more common. Those apps rely on handling those keypresses by themselves.

**Comment by DHowett-MSFT** [comment] 2019-06-13 20:29
> especially sad
Well, it's a bug in an as-yet-unreleased product; there's a limit to its maximum sadness :smile:

**Comment by MeikTranel** [comment] 2019-06-13 20:33
of course 🤣🤣🤣 was just trying to provide some context. no worries 😉

**Comment by driver1998** [comment] 2019-06-15 05:56
Is this "caret browsing" in Windows Terminal actually works? Having a way to select text on keyboard similar to caret browsing sounds like a great idea.

**Comment by DHowett-MSFT** [comment] 2019-07-12 19:05
This is actually almost impossible to fix! Digging through the code for the Xaml platform keyboard handler, it intercepts F7 _before_ we're allowed to handle it (and reject its propagation.) The official recommendation from that team is to catch it in our island host's WM_KEYDOWN handler and synthesize it ourselves.

**Comment by DHowett-MSFT** [comment] 2019-07-15 02:00
It might be totally impossible with our architecture.

Our hosting window doesn't even receive a _win32 window message_ it can suppress or transform; everything is going straight into the Xaml Island's input site.

/cc @Austin-Lamb who once had an idea about how we could solve this.

Austin, should I file this one on microsoft-ui-xaml for when WinUI 3.0 is available? :smile:

**Comment by Austin-Lamb** [comment] 2019-07-15 16:57
@DHowett-MSFT - yeah, that'd be great if you could file an issue on microsoft-ui-xaml for a better way to suppress F7 caret browsing dialog when using islands.

**Comment by WayneDV** [comment] 2019-09-27 08:17
The problem is worsened by the fact that the "Do not ask me this again" option that it presents for your Caret Browsing choice is ignored between terminal close/launches

**Comment by zadjii-msft** [comment] 2020-01-22 18:11
(this is now tracking https://github.com/microsoft/microsoft-ui-xaml/issues/1873)

**Closed** 2020-03-05 20:35 UTC
Labels: Area-Input, In-PR, Issue-Bug, Priority-3, Product-Terminal, v1-Scrubbed
