### ISSUE TITLE
When searching for "wt.exe" in Windows Search Box, it crashes and returns an error.

### ISSUE THREAD

**Issue by TrevCan** [microsoft/terminal#8959] opened 2021-01-29 23:40 UTC
# Environment

```none
Microsoft Windows [Version 10.0.18363.1316]
Windows Terminal version (if applicable): 1.5.10271.0 (this is the one that appears on the Microsoft Store)

Any other software?
no
```

# Steps to reproduce
Open the windows search box (or just use [Windows Key] + S
type "wt.exe"
press enter

# Expected behavior
Should open the Windows Terminal

# Actual behavior
As shown on the screenshot below, it returns an error and does not open the app. The last version that was installed used to work just fine doing the instructions presented above.

![image](https://user-images.githubusercontent.com/44383325/106337640-50ab1c00-6257-11eb-9329-7380967fbb69.png)

# Other Information
Alternatively, if you try search for "wt.exe" on the Windows Powertoys search box it works. Apparently both searches point to different *.exes. The Powertoys search box points to `C:\Users\{USER_NAME}\AppData\Local\Microsoft\WindowsApps` and the default windows search box points to `C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_1.5.10271.0_x64__8wekyb3d8bbwe`.
**Also, if I just search in the Windows Default Search Box for "Windows Terminal" and press enter it works.**

**Comment by srdjanjovcic** [comment] 2021-02-01 17:57
I do not get error, but wt.exe stopped working -- it just flashes a bit and disappears. It breaks my shortcuts which use wt.exe to open given profile.

**Comment by zadjii-msft** [comment] 2021-02-01 22:03
@DHowett this one looks like it's also related to our recent deployment woes

**Comment by zadjii-msft** [comment] 2021-02-03 10:23
This looks a lot like #9017. I'm worried that your install is somehow fragmented, and the alias is pointing at the wrong exe. 

Could you share the output of the following two commands?
* `fsutil reparsepoint query C:\Users\{USER_NAME}\AppData\Local\Microsoft\WindowsApps\wt.exe`
* `fsutil reparsepoint query C:\Users\{USER_NAME}\AppData\Local\Microsoft\WindowsApps\Microsoft.WindowsTerminal_8wekyb3d8bbwe\wt.exe`

**Comment by TrevCan** [comment] 2021-02-03 15:01
sure,
- `fsutil reparsepoint query C:\Users\{USER_NAME}\AppData\Local\Microsoft\WindowsApps\wt.exe`


  ```
  Reparse Tag Value : 0x8000001b
  Tag value: Microsoft
  
  Reparse Data Length: 0x0000016a
  Reparse Data:
  0000:  03 00 00 00 4d 00 69 00  63 00 72 00 6f 00 73 00  ....M.i.c.r.o.s.
  0010:  6f 00 66 00 74 00 2e 00  57 00 69 00 6e 00 64 00  o.f.t...W.i.n.d.
  0020:  6f 00 77 00 73 00 54 00  65 00 72 00 6d 00 69 00  o.w.s.T.e.r.m.i.
  0030:  6e 00 61 00 6c 00 5f 00  38 00 77 00 65 00 6b 00  n.a.l._.8.w.e.k.
  0040:  79 00 62 00 33 00 64 00  38 00 62 00 62 00 77 00  y.b.3.d.8.b.b.w.
  0050:  65 00 00 00 4d 00 69 00  63 00 72 00 6f 00 73 00  e...M.i.c.r.o.s.
  0060:  6f 00 66 00 74 00 2e 00  57 00 69 00 6e 00 64 00  o.f.t...W.i.n.d.
  0070:  6f 00 77 00 73 00 54 00  65 00 72 00 6d 00 69 00  o.w.s.T.e.r.m.i.
  0080:  6e 00 61 00 6c 00 5f 00  38 00 77 00 65 00 6b 00  n.a.l._.8.w.e.k.
  0090:  79 00 62 00 33 00 64 00  38 00 62 00 62 00 77 00  y.b.3.d.8.b.b.w.
  00a0:  65 00 21 00 41 00 70 00  70 00 00 00 43 00 3a 00  e.!.A.p.p...C.:.
  00b0:  5c 00 50 00 72 00 6f 00  67 00 72 00 61 00 6d 00  \.P.r.o.g.r.a.m.
  00c0:  20 00 46 00 69 00 6c 00  65 00 73 00 5c 00 57 00   .F.i.l.e.s.\.W.
  00d0:  69 00 6e 00 64 00 6f 00  77 00 73 00 41 00 70 00  i.n.d.o.w.s.A.p.
  00e0:  70 00 73 00 5c 00 4d 00  69 00 63 00 72 00 6f 00  p.s.\.M.i.c.r.o.
  00f0:  73 00 6f 00 66 00 74 00  2e 00 57 00 69 00 6e 00  s.o.f.t...W.i.n.
  0100:  64 00 6f 00 77 00 73 00  54 00 65 00 72 00 6d 00  d.o.w.s.T.e.r.m.
  0110:  69 00 6e 00 61 00 6c 00  5f 00 31 00 2e 00 35 00  i.n.a.l._.1...5.
  0120:  2e 00 31 00 30 00 32 00  37 00 31 00 2e 00 30 00  ..1.0.2.7.1...0.
  0130:  5f 00 78 00 36 00 34 00  5f 00 5f 00 38 00 77 00  _.x.6.4._._.8.w.
  0140:  65 00 6b 00 79 00 62 00  33 00 64 00 38 00 62 00  e.k.y.b.3.d.8.b.
  0150:  62 00 77 00 65 00 5c 00  77 00 74 00 2e 00 65 00  b.w.e.\.w.t...e.
  0160:  78 00 65 00 00 00 30 00  00 00                    x.e...0...
  ```
- `fsutil reparsepoint query C:\Users\USER_NAME}\AppData\Local\Microsoft\WindowsApps\Microsoft.WindowsTerminal_8wekyb3d8bbwe\wt.exe`
```
Reparse Tag Value : 0x8000001b
Tag value: Microsoft

Reparse Data Length: 0x0000016a
Reparse Data:
0000:  03 00 00 00 4d 00 69 00  63 00 72 00 6f 00 73 00  ....M.i.c.r.o.s.
0010:  6f 00 66 00 74 00 2e 00  57 00 69 00 6e 00 64 00  o.f.t...W.i.n.d.
0020:  6f 00 77 00 73 00 54 00  65 00 72 00 6d 00 69 00  o.w.s.T.e.r.m.i.
0030:  6e 00 61 00 6c 00 5f 00  38 00 77 00 65 00 6b 00  n.a.l._.8.w.e.k.
0040:  79 00 62 00 33 00 64 00  38 00 62 00 62 00 77 00  y.b.3.d.8.b.b.w.
0050:  65 00 00 00 4d 00 69 00  63 00 72 00 6f 00 73 00  e...M.i.c.r.o.s.
0060:  6f 00 66 00 74 00 2e 00  57 00 69 00 6e 00 64 00  o.f.t...W.i.n.d.
0070:  6f 00 77 00 73 00 54 00  65 00 72 00 6d 00 69 00  o.w.s.T.e.r.m.i.
0080:  6e 00 61 00 6c 00 5f 00  38 00 77 00 65 00 6b 00  n.a.l._.8.w.e.k.
0090:  79 00 62 00 33 00 64 00  38 00 62 00 62 00 77 00  y.b.3.d.8.b.b.w.
00a0:  65 00 21 00 41 00 70 00  70 00 00 00 43 00 3a 00  e.!.A.p.p...C.:.
00b0:  5c 00 50 00 72 00 6f 00  67 00 72 00 61 00 6d 00  \.P.r.o.g.r.a.m.
00c0:  20 00 46 00 69 00 6c 00  65 00 73 00 5c 00 57 00   .F.i.l.e.s.\.W.
00d0:  69 00 6e 00 64 00 6f 00  77 00 73 00 41 00 70 00  i.n.d.o.w.s.A.p.
00e0:  70 00 73 00 5c 00 4d 00  69 00 63 00 72 00 6f 00  p.s.\.M.i.c.r.o.
00f0:  73 00 6f 00 66 00 74 00  2e 00 57 00 69 00 6e 00  s.o.f.t...W.i.n.
0100:  64 00 6f 00 77 00 73 00  54 00 65 00 72 00 6d 00  d.o.w.s.T.e.r.m.
0110:  69 00 6e 00 61 00 6c 00  5f 00 31 00 2e 00 35 00  i.n.a.l._.1...5.
0120:  2e 00 31 00 30 00 32 00  37 00 31 00 2e 00 30 00  ..1.0.2.7.1...0.
0130:  5f 00 78 00 36 00 34 00  5f 00 5f 00 38 00 77 00  _.x.6.4._._.8.w.
0140:  65 00 6b 00 79 00 62 00  33 00 64 00 38 00 62 00  e.k.y.b.3.d.8.b.
0150:  62 00 77 00 65 00 5c 00  77 00 74 00 2e 00 65 00  b.w.e.\.w.t...e.
0160:  78 00 65 00 00 00 30 00  00 00                    x.e...0...
```

**Comment by zadjii-msft** [comment] 2021-02-03 15:09
Curious. Those both point at the right version. So that's not the issue here...

When you search for `wt.exe` in the start menu, where does "Open file location" take you?
![image](https://user-images.githubusercontent.com/18356694/106766454-80637680-65ff-11eb-913f-e02ce0d9f60f.png)

**Comment by TrevCan** [comment] 2021-02-03 16:30
`C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_1.5.10271.0_x64__8wekyb3d8bbwe`

**Comment by TrevCan** [comment] 2021-02-16 19:16
Hello, it seems as if the issue is sort of worse now. I have updated to `Microsoft Windows 10 Home Version [10.0.18363 Build 18363]`, previously `Microsoft Windows [Version 10.0.18363.1316]` and when executing `wt.exe` from the Windows Search bar, the Windows Terminal launches, but without the correct fonts and the .exe is pointing to a new version 1.5.x at the path `C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_1.5.10411.0_x64__8wekyb3d8bbwe`. It seems that Windows confused itself when updating and apparently reinstalled the 1.5.x version. When I open the json settings, it just appears very different from the one I have on the 'normal' Windows Terminal. If I search for `Windows Terminal` from the search bar it loads with the correct fonts and my configuration is still there. Below you can see screenshots when executing the `wt.exe` command from the Windows Search bar and when executing the `Windows Terminal` app.

**`wt.exe`**
![image](https://user-images.githubusercontent.com/44383325/108110416-d6e99f80-7058-11eb-8d21-0bacbfdccf1f.png)


**`Windows Terminal (normal)`**
![image](https://user-images.githubusercontent.com/44383325/108110520-fbde1280-7058-11eb-8220-39cd8abb68bd.png)

(note: I blacked out my windows username and laptop name in case you see it any different).

**Comment by DHowett** [comment] 2021-02-16 19:22
Ugh, this is another shade of the same issue. Occasionally, running `wt` from the run dialog _spawns Terminal without its package context_ (!) which naturally uses a different settings file and stuff. Gahhhh. I wasn't aware this issue was prevalent on 18362/3.

**Comment by zadjii-msft** [comment] 2021-02-16 20:14
FYI this also got reported [on reddit](https://www.reddit.com/r/WindowsTerminal/comments/lkbzk4/start_windows_terminal_get_one_win_r_wt_get_other/), but I don't think OP ever ended up positing on GH

**Comment by zadjii-msft** [comment] 2021-02-26 12:55
FWIW, some internal users have had success "repairing" the Terminal app in the settings app. Not sure if that'll work in this case too. The internal thread is still ongoing unfortunately.

**Comment by TrevCan** [comment] 2021-02-26 18:15
Thanks for the info, but what do you mean by entering the settings app? You mean uninstalling the app and installing it again ?

**Comment by zadjii-msft** [comment] 2021-02-26 18:28
![repair-app](https://user-images.githubusercontent.com/18356694/109340026-191b9980-782e-11eb-9bca-9dabd92ba93c.gif)

**Comment by TrevCan** [comment] 2021-02-27 06:27
Unfortunately, it didn't work. It did not change anything I believe. Correct fonts and configurations are not loading and it still points to a different `.exe` file.

**Comment by fkalbe** [comment] 2021-03-04 16:08
Unfortunately, I'm facing the same issue as @TrevCan and repairing the Terminal app also didn't seem to change anything for me.  

```
Microsoft Windows [Version 10.0.18363.0]

Windows Terminal Version: 1.6.10571.0
```

I think the issue just emerged today, possibly after an automatic update through the Microsoft Store?

**Comment by DHowett** [comment] 2021-03-11 20:33
@fkalbe, @trevcan I'm gonna mark this as a /duplicate of #9452 -- I've got some instructions and a question in there, if you don't mind. :smile:

**Closed by DHowett** 2021-03-11 20:33 UTC
Labels: Culprit-Centennial, Needs-Attention, Needs-Tag-Fix
