### ISSUE TITLE
unexpected behaviour: Windows Terminal window cannot be dragged by mouse

### ISSUE THREAD

**Issue by Karl-WE** [microsoft/terminal#1500] opened 2019-06-23 23:24 UTC
# Environment

Windows build number: Windows 10 1903
Windows Terminal version (if applicable): 0.2.1715.0

# Steps to reproduce
you can only drag the window when clicking on the window title that is actually colored in Windows 10 color style ([1]marked green)
click on the window title ([1]marked red) you cannot move the window

![windows terminal drag window]
![1]
(https://user-images.githubusercontent.com/45657752/59983328-9258f700-961e-11e9-9522-357b93c911b0.png)

# Expected behavior
I expect that left mouse click and hold on the complete window title should allow dragging of the Windows Terminal window.

# Actual behavior
The left space this is reserved ([1]marked red) for new tabs or existing tabs (black) cannot be used to move the window

**Comment by peter-bertok** [comment] 2019-06-24 00:00
This is the first thing I noticed after installing.

**Comment by mikeyGlitz** [comment] 2019-06-24 00:10
The window can actually be dragged if you click in the empty space on the right of the title bar by the minimize, full screen, and close buttons
![image](https://user-images.githubusercontent.com/606924/59983952-ec43c780-95f2-11e9-9e66-25d281ee220d.png)

**Comment by F21** [comment] 2019-06-24 00:12
This seems to be a dupe of https://github.com/microsoft/terminal/issues/564

**Comment by Karl-WE** [comment] 2019-06-24 00:18
> This seems to be a dupe of #564

I agree. it is a dupe of #564. due to the term "tab-bar" which I understand as windows title I haven't noticed this.

**Comment by Karl-WE** [comment] 2019-06-24 00:18
> The window can actually be dragged if you click in the empty space on the right of the title bar by the minimize, full screen, and close buttons
> ![image](https://user-images.githubusercontent.com/606924/59983952-ec43c780-95f2-11e9-9e66-25d281ee220d.png)

I am fully aware about this. Thanks for your pic. Please check mine in return (link in OP)

**Comment by DHowett-MSFT** [comment] 2019-06-24 04:29
Closing as a dupe! Thanks for finding this one.

**Closed by DHowett-MSFT** 2019-06-24 04:29 UTC
Labels: Needs-Tag-Fix, Needs-Triage

**Comment by HBelusca** [comment] 2019-06-24 11:02
Duplicate of #1412, #1395 ; issue encompassed in #1375.
