### ISSUE TITLE
Add more flexibility to keybinding

### ISSUE THREAD

**Issue by danlikestocode** [microsoft/terminal#16864] opened 2024-03-12 02:04 UTC
# Description of the new feature/enhancement
Hey I love doing work on my windows machine! I just hate having to relearn shortcuts for stuff, and the tmux shortcuts are burned into my brain. I then went to keybind windows terminal in the same way as tmux, however you folks dont let windows terminal keybind things such as "ctrl+b+c"; which is not valid.

Please add this!

**Comment by j4james** [comment] 2024-03-12 10:45
I think this is actually a duplicate of issue #1334 (Support "Key Chords" in keybindings):

> many text editors support "key chords" where the chord is a combination of multiple keys pressed in sequence. For example, in Visual Studio, the default keybinding for "Comment Code" is the chord `[ctrl+c, ctrl+k]`.

**Comment by danlikestocode** [comment] 2024-03-14 03:09
ah yes i think it is also a duplicate, however key chords seem to encapsulate the feature that I am requesting if it would allow something like "ctrl+b+j" to be bound

**Comment by zadjii-msft** [comment] 2024-03-18 14:12
Yep this is definitely /dup #1334, thanks!

**Closed by zadjii-msft** 2024-03-18 14:12 UTC
Labels: Issue-Feature, Needs-Triage, Needs-Tag-Fix
