### ISSUE TITLE
vim，The word under the cursor is not visible

### ISSUE THREAD

**Issue by Tao-Wei** [microsoft/terminal#1510] opened 2019-06-24 05:46 UTC
I added the code in .vimrc:
```
let &t_SI.="\e[5 q"
let &t_SR.="\e[4 q"
let &t_EI.="\e[1 q"
```
cursor style can be changed but the word under the cursor is not visible 
![image](https://user-images.githubusercontent.com/46256982/59994229-af74e080-9685-11e9-84d5-a99d2d25d410.png)

**Comment by JushBJJ** [comment] 2019-06-24 14:13
That's just how terminal is I think, but you can change the cursor shape into a "emptyBox" (Referenced in https://github.com/microsoft/terminal/blob/master/doc/cascadia/SettingsSchema.md)

**Comment by Tao-Wei** [comment] 2019-06-25 06:09
It looks very uncomfortable. Is there any solution？

**Comment by benjif** [comment] 2019-06-27 07:19
The only current solution I could find is setting `cursorShape` to something other than "filledBox" in your config file (e.g. emptyBox, underScore, bar, or vintage).

**Comment by benjif** [comment] 2019-06-27 07:21
I believe the only current solution is changing cursorShape in your profiles.json,

**Comment by DHowett-MSFT** [comment] 2019-06-27 22:08
We'll need to look at different cursor color styles like "invert". This is, however, how some terminals just work.

**Comment by zadjii-msft** [comment] 2019-07-01 21:14
This seems related to #1356

**Comment by DHowett-MSFT** [comment] 2019-07-02 00:33
We should just call this a duplicate of #1356. Having configurable cursor styles/making invert work would be part of the same workitem.

**Closed by DHowett-MSFT** 2019-07-02 00:33 UTC
Labels: Needs-Tag-Fix, Needs-Triage
