### ISSUE TITLE
ColorTool doesn't work : Could not find or load "OneHalfLight"    (or else themes)

### ISSUE THREAD

**Issue by Mrxsnj** [microsoft/terminal#5218] opened 2020-04-02 05:04 UTC
# Environment

```none
Windows build number: 10.0.18363.0
Windows Terminal version (if applicable): 0.8.10261.0

Any other software?
Color Tool April 2019
```

# Steps to reproduce

![colortoolissue](https://user-images.githubusercontent.com/26734214/78212191-984f0300-74e1-11ea-912d-c0ca19dbcf5f.png)

# Expected behavior

Change the scheme
# Actual behavior

Could not find or load "OneHalfLight"

**Comment by barclay-reg** [comment] 2020-04-02 08:11
the help output from colortool (downloaded latest https://github.com/microsoft/terminal/releases/tag/1904.29002) does not match the help output from readme, maybe a newer version of colortool should be build?

**Comment by j4james** [comment] 2020-04-02 13:07
You need to include the file extension when specifying the scheme name, e.g.

    .\ColorTool.exe OneHalfLight.itermcolors

I think this is probably a duplicate of issue #770.

**Comment by zadjii-msft** [comment] 2020-04-02 13:28
Thanks for the triage @j4james!

/dupe #770

**Closed by zadjii-msft** 2020-04-02 13:28 UTC
Labels: Needs-Tag-Fix, Needs-Triage
