### ISSUE TITLE
URL highlight issues with emoji

### ISSUE THREAD

**Issue by ggnkua** [microsoft/terminal#11797] opened 2021-11-21 18:49 UTC
### Windows Terminal version

1.11.2921.0

### Windows build number

10.0.19043.1348

### Other Software

WSL 2 (using Ubuntu 20.04.2 LTS)

### Steps to reproduce

Open a wsl2 and paste the following line:

😃👍🕹🕹️  http://microsoft.com

In my machine I get:

![image](https://user-images.githubusercontent.com/5121492/142774913-f8035fcf-9d31-48d0-9169-6b6b12e2f0a0.png)

Notice the two spaces between `//` and `microsoft.com`. Sometimes those two spaces appear, some times they don't.

If I move the cursor and delete the two spaces, and then try to highlight the URL I get:

![image](https://user-images.githubusercontent.com/5121492/142774996-8cc140a4-1008-4c64-a0b8-100a00cf603f.png)

Trying to ctrl-click the URL gives:

![image](https://user-images.githubusercontent.com/5121492/142775025-83bd973b-1e79-41f6-a54c-465235df9cd9.png)

### Expected Behavior

The URL should appear without spaces, the URL should be underlined and clickable.

### Actual Behavior

The URL failed to highlight properly, and when ctrl-clicking it, it produced the error shown in the last screenshot in "steps to reproduce"

**Comment by j4james** [comment] 2021-11-21 19:16
This could probably be considered a duplicate of #8709. More fundamentally, though, I think the issue is that we can't handle characters outside the BMP which have a narrow width. I expect this will be solved by #8000.

**Comment by ggnkua** [comment] 2021-11-21 19:21
Oh gosh, so it has been reported already. I tried searching for an open issue but I wasn't sure how to search for it.

Should we close this as duplicate or leave open?

**Comment by j4james** [comment] 2021-11-21 23:38
Not to worry. Even if closed as a duplicate, it's good to have easily reproducible test cases like this to check whether a future fix is actually working as expected. One of the core devs will probably close this if they confirm it's definitely a dup.

**Comment by zadjii-msft** [comment] 2021-11-22 12:28
No worries, this definitely looks like /dup #8709, thanks!

**Closed by zadjii-msft** 2021-11-22 12:29 UTC
Labels: Needs-Triage, Needs-Tag-Fix
