### ISSUE TITLE
Unable to find the selected font "Cascadia Mono".

### ISSUE THREAD

**Issue by Flightkick** [microsoft/terminal#9375] opened 2021-03-04 12:21 UTC
# Environment

```none
Windows build number: Microsoft Windows NT 10.0.19042.0
Windows Terminal version: 1.6.10571.0
```

# Steps to reproduce
This 'happens on my machine', not sure if easily reproducible.
- Start Microsoft Terminal

# Expected behavior
Microsoft terminal opens on the default terminal

# Actual behavior
A pop-up is shown with the following error message:
![screenshot of the error message](https://user-images.githubusercontent.com/8693699/109962748-dc4b1900-7ceb-11eb-8e47-3144d737b01d.png)
Transcript:  
```none
Warning

Unable to find the selected font "Cascadia Mono".

"Consolas" has been selected instead.

Please either install the missing font or choose another one.
```

# Additional information
Other applications, Microsoft Word, Paint.NET, show the `Cascadia Mono` font and allow usage without any issues.

**Comment by Flightkick** [comment] 2021-03-04 12:23
Off course I think of a possible fix right after submitting the issue.

Starting Microsoft Terminal as Administrator once fixes the issue.
Subsequent runs as non-admin do not show the warning anymore.

Leaving the issue open so the maintainers can decide if this should be handled without the 'start as admin' workaround/fix.

**Comment by oskar** [comment] 2021-03-05 07:41
After upgrading to 1.6.10571.0, this happens to me as well. But starting as administrator does not help for me. Any other workaround?

**Comment by MuTLY** [comment] 2021-03-05 12:06
I'm experiencing the same behavior, this was not an issue until about a week ago. In my case, it is not finding the "Ubuntu Regular" font, and as you can see, the font is installed correctly.

![image](https://user-images.githubusercontent.com/777006/110113423-d740a500-7d91-11eb-84c6-209abf3d8e20.png)

![image](https://user-images.githubusercontent.com/777006/110113553-048d5300-7d92-11eb-82d6-436856f4dfb0.png)

![image](https://user-images.githubusercontent.com/777006/110113588-140c9c00-7d92-11eb-9c62-f7c5c007601a.png)

**Comment by zadjii-msft** [comment] 2021-03-05 12:14
Hey @miniksa can you take a look at this and #9157? We're seeing a pretty dramatic uptick in the number of these kinds of reports after adding the warning. Did we change anything about the font lookup when we added the dialog?

**Comment by grandslamjmh** [comment] 2021-03-05 14:10
I have a Similar experience but with the font "Cascadia Code PL". The message does not go away if Started as Administrator.

**Comment by Rod-in-NM** [comment] 2021-03-05 17:15
I've also having an issue with Windows Terminal not being able to find Cascadia Code PL. I've been using Cascadia Code PL for several months with no issues, now Windows Terminal can't find it.

**Comment by miniksa** [comment] 2021-03-05 18:26
> Hey @miniksa can you take a look at this and #9157? We're seeing a pretty dramatic uptick in the number of these kinds of reports after adding the warning. Did we change anything about the font lookup when we added the dialog?

I will not have the capacity to look at this for at least a week.

**Comment by fujiawei-dev** [comment] 2021-03-06 11:48
I am also suffering from this problem, after an automatic update via the Windows Store.

**Comment by Komic** [comment] 2021-03-06 15:39
Same thing here, Source Code Pro.

**Comment by BJGGut3** [comment] 2021-03-08 13:27
Same issue, Licudia Console.  Starting as Administrator does not fix the issue, either.  Version 1.6.10571.0 updated through the Windows Store.

**Comment by eturnq** [comment] 2021-03-08 15:52
"Install for all users" fixed this trouble for me.
![image](https://user-images.githubusercontent.com/17465060/110345195-f0e12700-7ff3-11eb-82ee-7e144694dfe1.png)

**Comment by MuTLY** [comment] 2021-03-08 16:30
> "Install for all users" fixed this trouble for me.
> ![image](https://user-images.githubusercontent.com/17465060/110345195-f0e12700-7ff3-11eb-82ee-7e144694dfe1.png)

I've tried that and it didn't make a difference. I even rebooted the computer after reinstalling the fonts using the "Install for all users" option. On startup, Windows Terminal still complains about a missing font that's not missing and can be used anywhere else on the system ("Ubuntu Regular", in my case).

**Comment by Xbuduo** [comment] 2021-03-09 09:20
The one installed from the store has no problem. But the one installed by scoop has the same issue.

**Comment by yikakia** [comment] 2021-03-09 15:33
Same happens to me at  
- version 1.6.10571.0

**Comment by WSLUser** [comment] 2021-03-10 15:29
I hit this issue today (don't know why not before now) but when I installed the Cascadia Code font directly to Windows, the error disappeared and the font appears as it should. It did appear to look like Consolas before doing this. So I think WT isn't reading the font files correctly from inside the msix package.

**Comment by hawko2600** [comment] 2021-03-11 05:33
I had the same issue with the Store version, using "Cascadia Code PL Regular" as the font.
If I remove the "Regular" from the font string text, I do not get the error dialogue and the font loads correctly.

**Comment by Rod-in-NM** [comment] 2021-03-11 15:41
I never had "Cascadia Code PL Regular" as the font, only "Cascadia Code PL". And I still get that error dialogue.

**Comment by lonelydev** [comment] 2021-03-12 00:01
I ran into a similar issue. I followed all sorts of instructions from various different posts online and I finally got powershell to recognize the right font but windows terminal would still not pick it up.
here is my powershell core rendering the font Space Mono for Powerline correctly.  
![image](https://user-images.githubusercontent.com/9505396/110870639-c7aaea00-82c4-11eb-9f5d-bb72126bdfe2.png)

A screenshot of the console's properties: 
![image](https://user-images.githubusercontent.com/9505396/110870706-e8733f80-82c4-11eb-8706-d9d0ca4528ed.png)

However, I tried the same in Windows Terminal and guess what?
![image](https://user-images.githubusercontent.com/9505396/110870740-fe810000-82c4-11eb-9eb9-32a437b7c944.png)

settings file:
![image](https://user-images.githubusercontent.com/9505396/110870776-0c368580-82c5-11eb-8210-ec56c6a97b1a.png)

I got lucky and got help from smart people online by posting this question on twitter -https://twitter.com/eakangk/status/1369949792034562048?s=20

And someone responded that I was using the full name of the font and not the short name. I quickly opened the modern font setting window and searched for the font 'space' and that was when I realised, I couldn't find it. 
![image](https://user-images.githubusercontent.com/9505396/110870932-528be480-82c5-11eb-8677-80cea334ac31.png)

However the same font would show up in the old schools c:\windows\fonts folder:
![image](https://user-images.githubusercontent.com/9505396/110870984-6c2d2c00-82c5-11eb-8824-ed9f712d0d8b.png)

This prompted me to think that maybe, i didn't really install it for all users. 
Luckily I had a clone of https://t.co/Xo6f5LikOV?amp=1 so I rightclicked the font and clicked install for all users. 
![image](https://user-images.githubusercontent.com/9505396/110871137-b7473f00-82c5-11eb-85d6-80dccda671da.png)

and guess what happened next? 
![image](https://user-images.githubusercontent.com/9505396/110871170-c928e200-82c5-11eb-9704-0776ed02f092.png)
it appeared in Font Settings!

I couldn't wait to open up my windows terminal to check how it looked like and... wait for it....
![image](https://user-images.githubusercontent.com/9505396/110871237-e958a100-82c5-11eb-9168-557acefa9ead.png)
it worked. 

Thank you everyone for the valuable suggestions and directing me to this issue here. i had almost given up on this back in January, thinking I was taking too long to set up a prompt.

**Comment by Rod-in-NM** [comment] 2021-03-12 14:50
@lonelydev, I just checked my C:\Windows\Font folder. I don't have any font there named `Space Mono for Powerline` there. In fact, I don't have any font there that starts with `Space Mono`. Should I try to find that and install it?

**Comment by lonelydev** [comment] 2021-03-12 15:31
@Rod-in-NM 
seems like you need powerline fonts from https://github.com/powerline/fonts
once you clone the repo to your pc, you can then choose to install the fonts you wish to Windows right clicking the font image and then clicking install for all users. 
![image](https://user-images.githubusercontent.com/9505396/110961738-0930a900-8348-11eb-89e9-fab760d5bee4.png)

That should get you the font you want. 
In my case, I configured my Windows Terminal to use Space Mono, so I only selectively installed that font and it started rendering correctly. 
![image](https://user-images.githubusercontent.com/9505396/110961727-0635b880-8348-11eb-98e2-bbd8b46fed15.png)

**Comment by Rod-in-NM** [comment] 2021-03-12 15:55
@lonelydev I've cloned that font repo. The I installed for all users these fonts:

- Space Mono Bold for Powerline
- Space Mono Bold Italic for Powerline
- Space Mono for Powerline
- Space Mone Italic for Powerline

I didn't think I needed the others.

This hasn't helped - I'm still getting that error message whenever I get into Windows Terminal

**Comment by lonelydev** [comment] 2021-03-12 15:58
you still getting 
![image](https://user-images.githubusercontent.com/9505396/110965010-b3f69680-834b-11eb-991c-3c717efe6277.png) ?
specifically `Space Mono for Powerline`?

**Comment by Rod-in-NM** [comment] 2021-03-12 16:10
No, I'm getting this error:

![Screenshot 2021-03-12 090914](https://user-images.githubusercontent.com/13875530/110966681-c1435f00-8312-11eb-8756-79d038bb1c35.png)

**Comment by lonelydev** [comment] 2021-03-12 16:17
hey @Rod-in-NM 
now that you have installed `Space Mono for Powerline` for all users, you should probably edit your Windows Terminal settings file to have `Space Mono for PowerLine` as the `fontFace` instead.
![image](https://user-images.githubusercontent.com/9505396/110967057-dd182680-834d-11eb-8bfc-068a87e230be.png)

However, if you prefer `Cascadia Code`, download it from https://github.com/microsoft/cascadia-code/releases
and do the same "Install for all users" for that one too. 

You can check if it has been installed properly by doing what I did, searching both c:\windows\fonts and also the font settings window as i posted here - https://github.com/microsoft/terminal/issues/9375#issuecomment-797136185

**Comment by kaovilai** [comment] 2021-03-15 07:00
Install for all users FTW!

**Comment by mmanueljoao** [comment] 2021-03-17 23:48
I'm having kind of the same problem but with another font not mentioned here. FiraCode Nerd Font.

![imagem](https://user-images.githubusercontent.com/6817527/111552782-ef91c600-877a-11eb-9fc5-a7170e942840.png)

It is both in the settings windows and the folder ... Although with different names BUT it doesn't finds it with neither.

![imagem](https://user-images.githubusercontent.com/6817527/111552855-1d770a80-877b-11eb-9d2e-51105b934aa9.png)

![imagem](https://user-images.githubusercontent.com/6817527/111552913-3b446f80-877b-11eb-884e-a3ae020efd0e.png)

**Comment by GenZmeY** [comment] 2021-03-19 12:57
I have the same problem (Windows Terminal v1.6.10571.0 and "Monospace Regular" font). Installing the font "for all users" doesn't solve the problem for me. Reinstalling windows terminal doesn't help either.

**But rolling back to the previous version (v1.5.10411.0) helped me.**

**Comment by amirhosseinmoezzi** [comment] 2021-03-24 07:31
It helped  >
https://github.com/microsoft/cascadia-code/releases

**Comment by jkingsman** [comment] 2021-03-31 00:28
As potentially helpful information, it worked when specifying a font family, but not when specifying a specific font -- in this case, `Hasklig` worked fine but `Hasklig Light` (or any `Hasklig $variation`) did not.

![image](https://user-images.githubusercontent.com/2365891/113073132-6072ae00-917d-11eb-86aa-67d8ce735d50.png)

**Comment by miniksa** [comment] 2021-03-31 18:21
Sorry it took me a bit but I'm looking today.

**Comment by miniksa** [comment] 2021-03-31 23:07
Okay.

Here's my plan:
- A. I'm going to remove the string comparison test as a way of triggering this dialog box. Instead, I'm going to make the font resolution code return a bool or some sort of indicator when it decides to try the hardcoded font list (Consolas). The dialog will only pop if that flag is set. This should eliminate the scenario where the proposed name was close enough for DirectWrite to resolve it to ONE of the font's known names and we give a really dumb pop up because the string doesn't match in case (or otherwise exactly)
- B. I'm going to add a small amount of retry resolution in the font fallback routine (prior to the previous flagging) that will trim off, word by word from the tail, the phrase that you've given us as the font and ask DirectWrite to try again. That will crudely resolve the case where people are specifying weight or other suffixes and we fall back to Consolas and show the annoying dialog. 
- C. In the future, we'll perhaps try to parse weight suffixes out of the specified font name and transform them into weight values or something more complicated. Backlog item.
- D. For the cases where the font is somehow installed but is not turning up in the system font cache, I'm generally going to have to defer to the OS side bug. I'm not supposed to really be able to do anything if the system can't figure out the difference between per user and per system installs or mushes up the status of fonts registered by installed packages.
- E. In the future, we'll try to have a fallback font loader that will at least attempt to get the Cascadia variants out of our own package by direct file open if the rest of the system font resolution chokes. Backlog item.

The first two (A and B) are what I want to send as a PR for this bug.
I'll file or find and link the backlog ones (C and E).
And I'll try to file or find and link the OS issue as well (D).

Finally, @DHowett and I have an alternative/interim solution:
1. @DHowett plans to pull the dialog from stable so it at least stops annoying people and is easy to service
2. @DHowett and I agree that if we reach the end of April and my proposed fixes get into people's hands and this is still a noisy issue... then we are going to yeet the entire dialog into space and note that it can only return once we have code that can better understand the text string for the font (like parsing out the weight as I said above.)

Questions, comments, concerns... let me know. Otherwise just give me a thumbs up and give me a chance to get it done. Thanks.

**Comment by matthewbarreiro** [comment] 2021-04-05 16:30
I also experienced this issue when installing Terminal with Scoop, but not with the MS store version. 

I found a related open request on the scoop-extras bucket: [[Request] Add default font Cascadia-Mono to the Windows Terminal manifest #5783 ](https://github.com/lukesampson/scoop-extras/issues/5783)

**Comment by drl-max** [comment] 2021-04-07 16:08
@Xbuduo, @matthewbarreiro, and to anyone who used `scoop` to install Terminal, I resolved this "Cascadia Mono" font issue by also installing the `cascadia-code` package. It requires an admin prompt and the `nerd-fonts` bucket.

1. Open terminal as Administrator
2. Run `scoop bucket add nerd-fonts`
3. Run `scoop install cascadia-code`

Hope that helps.

**Comment by miniksa** [comment] 2021-04-07 16:59
I have done A, B, and E in the linked PR #9734.

I will still generate a follow up for C.

On the OS side (part D), we have identified a bug with package installation and the font paths in the registry and have the relevant teams committed to fixing it.

**Closed** 2021-04-08 17:49 UTC
Labels: Area-Fonts, In-PR, Issue-Bug, Priority-2, Product-Terminal, zStable-Service-Consider

**Comment by sigoden** [comment] 2021-04-22 02:26
open Windows Terminal Settings,  add/change fontFace setting
```
{
    "profiles": {
         "defaults":  {
                "fontFace": "Consolas"  //  edit here
```

**Comment by brucek2** [comment] 2021-06-04 22:41
This just started happening to me today (wasn't happening yesterday or for weeks before.) In my case the missing font is "Cascadia Mono". I can't think of any update, config change, or anything else that should have triggered a change.

**Comment by softwrx** [comment] 2021-06-05 17:00
It started happening to me today. Weeks no issues then all of WSL linux sessions closed, about 8 of them, **_while they were running tasks and without notifying me or giving me the option to delay/cancel/not update at this time!_**  This is a very very bad update procedure as it closed active SSH connections in all of these. Fortunately I started the critical jobs via screen. 

Apps, especially terminal apps, that can be open for extended periods of time while running long-running jobs should not silently just close and update in the middle of the night. 

As near as I can tell an update was applied and my terminal is now 1.9.1523. Not happy that it silently updated and closed my active sessions. And now I have the missing font error too. Which I did not have before. In fact everything had been working very well before. Now it's having problems. Very annoying.

**Comment by softwrx** [comment] 2021-06-05 17:09
As annoying as it was, I normally do not reboot because I might have things going for several days, I closed everything down and rebooted and it appears the error with the font has gone away.

So this "update" not only closed all my active terminal sessions without warning in the middle of the night, it also forced a reboot to fix this error. 

Lest I only complain - I realize this is a preview release, so some hiccups are to be expected. I was caught off guard by the sudden closing and update without warning though. That's not good.

Other than this one issue, the preview version has been working great. My only issue is an apparent lack of a keyboard shortcut to start a new terminal window. The preview has otherwise been very useful. The terminal preview, along with WSL, has enabled my switch from Mac to Windows as I live in various unix/linux terminals most of the day with my job. Good job on it.

**Comment by bikeoid** [comment] 2021-06-06 14:08
I finally solved the problem with losing active terminal sessions from an automatic update by disabling automatic updates for Windows Apps.   I just got the missing "Cascadia Mono" bug today also.

**Comment by softwrx** [comment] 2021-06-06 14:12
> 
> 
> I finally solved the problem with losing active terminal sessions from an automatic update by disabling automatic updates for Windows Apps. I just got the missing "Cascadia Mono" bug today also.

Thanks @bikeoid , good idea. thuogh I'd prefer to just disable it for the terminal and not all apps. i'll look it up and see if the options are that granular.

**Comment by rcarde** [comment] 2021-06-07 05:38
> Lest I only complain - I realize this is a preview release, so some hiccups are to be expected. I was caught off guard by the sudden closing and update without warning though. That's not good.

@softwrx I had the same issue and I'm running 1.8.1521.0 which, as far as I know, if not pre-release.   So I think the update process is borked.

**Comment by crash-horror** [comment] 2021-06-07 06:18
Well, resetting the app, and unticking all fonts, chose cascadia code did it for me. You got limited selection ofc

**Comment by stefanwendelmann** [comment] 2021-06-07 12:40
Had to 

1. Close Terminal 
2. Install font from https://github.com/microsoft/cascadia-code/releases for all users
2. kill the explorer.exe process (from Task Manager)
3. start the explorer.exe process  (from Task Manager)
4. Start Terminal

And the error was gone.

**Comment by ghylander** [comment] 2021-06-08 06:30
I know the issue is closed, but i had it happen today for the very first time ever, couldnt find cascadia mono, on v1.8.1521.0
"repaired" the app from the windows 10 settings menu, restarted terminal and it worked

**Comment by kusma** [comment] 2021-06-08 08:58
I just triggered the same issue, but sadly "repairing" the app did nothing for me. I'm using 1.8.1521.0.

**Comment by kusma** [comment] 2021-06-08 09:02
I can also add that the font (Cascadia Mono) is installed and works fine in other applications.

**Comment by magosla** [comment] 2021-06-09 09:05
Repairing the App did work for me

**Comment by SteveALee** [comment] 2021-06-10 09:56
This is a "Me too" posts but adding that in Windows terminal "about" the version is "1.8.1521.0" but latest release is only "v1.8.1444.0". huh? Deployment issues? Time to repoen this issue?

**Comment by DHowett** [comment] 2021-06-10 13:19
Please refer to the body of the first post in this issue.
