### ISSUE TITLE
Specify tab header width in profiles.json

### ISSUE THREAD

**Issue by maciejpankanin** [microsoft/terminal#3792] opened 2019-12-01 08:53 UTC
# Description of the new feature/enhancement
The ability to set something like minimal tab width or to set all tabs to have same width.

![Adnotacja 2019-12-01 094904](https://user-images.githubusercontent.com/33896387/69911754-74d75700-1420-11ea-829b-9f6cd5b07c45.png)

**Comment by nishp77** [comment] 2019-12-02 01:21
I would like to just that let's make the tab header width the maximum tabrow that covers till. As we add tabs we divide the total distance by the number of tabs into equal portions.

**Comment by DHowett-MSFT** [comment] 2019-12-02 16:33
This is a /dupe of #597. Thanks!

**Closed** 2019-12-02 16:33 UTC
Labels: Issue-Feature, Needs-Tag-Fix, Needs-Triage
