### ISSUE TITLE
ssh newline problem

### ISSUE THREAD

**Issue by CatCatCatDog** [microsoft/terminal#8278] opened 2020-11-15 07:40 UTC
Windows terminal 1.4.3141.0
Windows 10 64bit 2004 (OS Build 19041.630)

What am i wrong? newline not work, If I open file and out from file. 
only bug occur, on rmote Linux. not WSL

![newline_problem](https://user-images.githubusercontent.com/23658192/99179455-481b6d00-2761-11eb-9aca-b803d46f9119.png)

**Comment by jdebp** [comment] 2020-11-15 19:36
You should show the result of running the `stty -a` command on the remote system at this point.  That's simple enough that you should be able to type it in without it being echoed back to you.

If it shows that the line discipline has local echo turned off with `-echo`, as it almost certainly will, then this is _not a problem with Windows Terminal_ in any way and Windows Terminal is working as designed.  This local echo mechanism is implemented in the line discipline in the kernel of the operating system on the remote host, _not_ in Windows Terminal on your local machine.

People have been getting their terminals into this state by turning local echo off in their line disciplines, on Unix operating systems, since before Windows NT even existed.  This and the "staircase effect" are two of the situations that are well-known and highly recognizable to long-time Unix and Linux-based operating system terminal users.  You need to look to what you are doing _on the remote host_ to its terminal line discipline, which isn't within the purview of a Windows Terminal bug report.

**Comment by DHowett** [comment] 2020-11-16 03:03
Thanks for the report! This is an upstream issue in Win32-OpenSSH (/dup https://github.com/PowerShell/Win32-OpenSSH/issues/1253), fixed in https://github.com/PowerShell/openssh-portable/pull/426

**Comment by DHowett** [comment] 2020-11-16 03:03
In short, exiting an alternate buffer or doing anything that might change the screen size (up to and including "launching a new SSH session") may cause output to be duplicated.

**Closed by DHowett** 2020-11-16 03:03 UTC
Labels: Needs-Author-Feedback, Needs-Tag-Fix, Needs-Triage
