### ISSUE TITLE
Windows Terminal goes blank after some random time running

### ISSUE THREAD

**Issue by javad94** [microsoft/terminal#2948] opened 2019-09-28 00:52 UTC
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18362.356]
Windows Terminal version (if applicable): 0.5.2661.0
```

# Steps to reproduce
1. run Windows Terminal 

# Expected behavior
Windows Terminal should work normally and get input.

# Actual behavior
Windows Terminal goes blank and not show the terminal or get any input.

![image](https://user-images.githubusercontent.com/7765309/65809175-631ace80-e1a7-11e9-8cfc-35864ec7380c.png)

**Comment by encladeus** [comment] 2019-09-28 06:52
This is probably a dupe of #2733.

**Comment by javad94** [comment] 2019-09-28 18:55
Yes, it is. sorry for duplicate.

**Comment by DHowett-MSFT** [comment] 2019-09-28 19:08
Thanks!

**Closed by DHowett-MSFT** 2019-09-28 19:08 UTC
Labels: Needs-Tag-Fix, Needs-Triage
