### ISSUE TITLE
conpty exhibits pathological performance on scrolling region redraw (repaints entire screen)

### ISSUE THREAD

**Issue by izghitu** [microsoft/terminal#7019] opened 2020-07-22 20:07 UTC
# Environment

```
Windows build number: Win32NT             10.0.18362.0 Microsoft Windows NT 10.0.18362.0
Windows Terminal version (if applicable): latest

```

# Steps to reproduce

ssh into a remote host, execute a command that spits a lot of output

# Expected behavior

In putty when the connection to a remote host is slow and a command spits a lot of output and that output comes back in frames(due to the slow connection) then I can just fine switch between SCREEN tabs. In windows terminal this is not possible. I am not even able to switch between tabs of the windows terminal until the command previous executed does not finish its output.

# Actual behavior

Need to wait for full command output before I can do anything else in the windows terminal.

**Comment by jblaine** [comment] 2020-08-05 13:45
Same.

Terminal is unusable in any situation where using "ssh <hostname>" and a lot of output is generated rapidly. All hell breaks loose, Terminal becomes unresponsive, then shows a little more, than becomes unresponsive, etc. I have confirmed that this does not happen using Windows 10 ssh and CMD.EXE. Maybe this is an issue with ConHost and not Terminal? I don't know, but it should be very easy for the developers to replicate.

**Comment by jblaine** [comment] 2020-08-05 13:58
@izghitu I believe your report is a duplicate of https://github.com/microsoft/terminal/issues/6258 which is specifically about Ctrl-C but I am sure that same situation applies to any control sequence, like those used in GNU screen.

**Comment by zadjii-msft** [comment] 2020-08-05 14:28
@izghitu Which `ssh` are you using? The `ssh.exe` that ships with Windows, or one from WSL (or some other one)? And which version?

Also `latest` doesn't really help as a version number, because at the time of your post, `latest` could have either meant 1.0, 1.1, or 1.2, depending if you were on the preview or release builds, and if you had gotten the release that shipped on the 22nd. Which WT version number exactly?

@jblaine this doesn't _really_ sound like it's related to Ctrl+C to me at all. Here OP is just trying to switch tabs in `screen`, which isn't working (and is reasonable if the output is being heavily buffered), nor is switching Terminal tabs (which is really quite surprising)

**Comment by izghitu** [comment] 2020-08-05 14:35
@zadjii-msft I use the ssh.exe that ships with WIndows. Its location is:
```
C:\\Windows\\System32\\OpenSSH\\ssh.exe
```

The version of the WT is **Version: 1.1.2021.0**

**Comment by zadjii-msft** [comment] 2020-08-05 14:52
Some other questions from #7191:

* Does this repro **without** `tmux`/`screen` running on the remote host?
* Does this repro with the `ssh` from a WSL distro?
* More insane - if you run `wsl.exe ssh.exe <args to ssh...>` inside a legacy powershell/cmd window, does the same issue repro? This will cause wsl to create a conpty to host `ssh.exe`, which could help identify if the issue is conpty vs something else.

**Comment by jblaine** [comment] 2020-08-05 15:56
@zadjii-msft My hour of testing showed the following for what I'm experiencing.

Windows build number: Microsoft Windows [Version 10.0.18363.959]
Windows Terminal version (if applicable): 1.1.2021.0

Windows 10 native ssh client
Remote Linux host running either tmux or GNU screen, multiple versions all work to reproduce issue

Connect via Windows 10 ssh (under Terminal) to a remote host. At the remote host, run a new screen or tmux session OR re-attach to an existing one. Generate a lot of output from a shell in one of the screen or tmux windows. Terminal crawls in batches of text displayed and often becomes unresponsive for periods of time. In my particular case, I am using a Terminal profile with `commandLine` of `"ssh <my args>"`

The same behavior can be seen in a WSL distro using the distro's SSH connected to the remote host + attach to screen + cat big file.

It does **not** happen when running a bare CMD.EXE (outside of Terminal) and then `wsl.exe ssh.exe <args to ssh...>` + screen resume + cat big file.

After digging around in the open issues here and finding some other issue about slow rendering when colors are at play, I even tested when TERM=vt100 on the remote end and all coloring turned off. The performance issue still exists in that case, so it does not seem to have to do anything with that other color perf. issue.

**Comment by zadjii-msft** [comment] 2020-08-05 16:11
> It does **not** happen when running a bare CMD.EXE (outside of Terminal) and then `wsl.exe ssh.exe <args to ssh...>` + screen resume + cat big file.

Well that pretty specifically rules out a whole bunch of possible sources of this issue actually. That narrows it down to _specifically_ the Terminal, and rules out conpty, `ssh.exe`, and `screen` as possible sources of error. 

That being said, I wonder what about the terminal is causing the stuttering. XAML? DX? Scrollbar updating?

Does setting `"historySize":0` in your profile help at all? That'll disable scrollback, but might help narrow it down further. 

There are also a [pair of global renderer settings](https://docs.microsoft.com/en-us/windows/terminal/customize-settings/global-settings#rendering-settings) that might be able to help rule out DX. Does setting either of these to `true` in the global settings (outside of a profile) change anything?
* `experimental.rendering.forceFullRepaint`
* `experimental.rendering.software`

**Comment by jblaine** [comment] 2020-08-05 16:40
No, none of those helped.

**Comment by lucastheisen** [comment] 2020-08-05 16:40
Not sure how related this is to this _exact_ issue, but output seems rather slow in general.  I was working to confirm @jblaine 's findings and tried this quick benchmark from 3 different terminals: `time bash -c "for i in {1..1000000}; do echo \$i; done;"` It shows an order of magnitude slowdown for this terminal:

microsoft terminal:
```text
real    2m53.944s
user    0m15.734s
sys     0m33.375s
```

wsltty:
```text
real    0m25.828s
user    0m7.188s
sys     0m6.781s
```

mobaxterm:
```text
real    0m29.078s
user    0m4.203s
sys     0m5.219s
```

**Comment by zadjii-msft** [comment] 2020-08-05 16:50
@lucastheisen That's actually something we're dealing with primarily over in #3075, but also in a [bunch of different places](https://github.com/microsoft/terminal/issues?q=is%3Aissue+label%3AArea-Performance+is%3Aopen). I'd keep an eye on that one 😉

**Comment by jblaine** [comment] 2020-08-13 00:13
This should be reopened, please

**Comment by DHowett** [comment] 2020-08-13 00:51
Thanks. Our bot should be taught to recognize any commenter who can provide additional information.

One more question - are you using a status line in screen or tmux?

**Comment by jblaine** [comment] 2020-08-13 05:02
Thanks @DHowett. Yes, I do use a statusline in screen. My tmux testing was only for this issue. I don't use tmux in my daily life.

**Comment by DHowett** [comment] 2020-08-13 05:04
Okay, excellent. Thanks. 

We have a pathological redraw case when there are sub-full-screen scrolling regions active (like, where there’s a status line). We end up retransmitting the entire contents of the screen _for every line_ between the backend and frontend processes in Terminal. The contention on the output queue bogs down the input queue.

**Comment by DHowett** [comment] 2020-08-13 05:05
I believe we have another version of this lying around somewhere, so I’ll assign myself to deduplicate.

**Comment by zadjii-msft** [comment] 2020-10-23 01:54
Just messaged Dustin about this - turns out there's _not_ another dupe for this one! _This is now the tracking thread for this issue_. Thanks!

**Comment by zadjii-msft** [comment] 2022-06-14 11:32
Wait this might actually be #5228 after all. Or, at least, should be tracked as part of it. @DHowett back me up?

**Comment by zadjii-msft** [comment] 2023-09-29 14:52
I'm pretty sure this is /dup #%228 after all.

**Closed by zadjii-msft** 2023-09-29 14:52 UTC
Labels: Area-Performance, Product-Conpty, Issue-Bug, Priority-2

**Comment by Eyalm321** [comment] 2026-06-10 02:14
Fresh data on this issue from Windows 11 24H2 (OS build 26100, in-box conhost 10.0.26100.1), measured while investigating throughput of a ConPTY-based terminal. Three results that seem worth putting on the record — including one suggesting this is **already fixed in this repo, just not serviced to the in-box host**.

### 1. The in-box conhost still has the pathological repaint — inflation = rows repainted

A child streaming plain lines inside an `ESC[1;20r` scroll region: conhost re-renders the region on every scrolled line. Measured master-side VT inflation equals the number of rows repainted, and conhost generates repaint VT at a roughly constant ~25–29 MB/s, so the child is backpressured to `ceiling ÷ inflation`:

| host | case | grid | child-side MB/s | master bytes (2 MB payload) | inflation |
|---|---|---|---:|---:|---:|
| in-box 10.0.26100.1 | `ESC[1;20r` region | 120×30 | 1.20 | 40.72 MB | **20.4×** |
| in-box | `ESC[1;20r` region | 120×40 | 0.72 | 80.27 MB | **40.1×** |
| in-box | same lines, no region | 120×30 | 6.19 | 2.00 MB | 1.0× |
| in-box | region taller than grid (invalid → ignored) | 120×10 | 7.60 | 2.00 MB | 1.0× |

The only delta between the slow and fast cases is the DECSTBM prologue; the line content is identical.

### 2. OpenConsole 1.24 does NOT have the repaint — i.e. this appears fixed, just not in-box

Same repro against the sideloaded redistributable pair (`Microsoft.Windows.Console.ConPTY` 1.24.260512001; host identity verified mid-run — the pty host child process is `OpenConsole.exe 1.24.2605.12001`): **1.0× inflation** on the scroll-region case (8.00 MB in → 8.00 MB out, byte-for-byte). So the VtEngine-removal era work (#17510) appears to have fixed exactly what this issue describes — but every ConPTY consumer that doesn't sideload the NuGet pair (i.e., nearly all of them) still gets the in-box behavior above.

**Ask: could this be reopened to track servicing the fix into the in-box conhost** (or could the team confirm the servicing plan)? Sideloading (discussion #17608) is a workaround each app must discover and ship on its own.

(Also tested explicitly, for the record: passing `PSEUDOCONSOLE_PASSTHROUGH_MODE` (0x8) to `CreatePseudoConsole` — measured no-op on both hosts, consistent with #1173 / #1985 being closed.)

### 3. A possibly separate 1.24 observation: deferred flush under sustained output

While verifying, the 1.24 host (headless ConPTY use) buffered the child's raw VT without backpressure and delivered it only when the child *paused*: a phased workload (2 MB of region-scroll → 3 s idle → marker → exit) shows 0 bytes on the master while the child streams, with the full 2 MB arriving during the idle; under continuous output it flushed only at child exit (8 MB in one burst). If that's unexpected rather than by-design pacing, happy to file it separately with the repro.

### Repro

Self-contained Rust probe (portable-pty 0.9): spawns `node <script>` in a ConPTY, measures child-side input rate vs master-side bytes (the inflation factor), and reports which conpty host it loaded. It runs fully headless — one note for anyone reproducing: with `PSEUDOCONSOLE_INHERIT_CURSOR` the host emits nothing until the terminal answers the initial `ESC[6n` query, so the probe replies `ESC[1;1R`.

- Probe: https://github.com/Eyalm321/hyperpanes/tree/main/rs/spikes/conpty-probe
- Raw runs: https://github.com/Eyalm321/hyperpanes/tree/main/rs/spikes/conpty-probe/results
- Full write-up: https://github.com/Eyalm321/hyperpanes/blob/main/docs/conpty-passthrough-investigation.md

Related: #17510, #1173, #1985, discussion #17608.

**Comment by lhecker** [comment] 2026-06-10 13:08
@Eyalm321 do you have a tl;dr? The AI copy/pasta is rather uncondensed, if you know what I mean. :/

**Comment by Eyalm321** [comment] 2026-06-10 13:20
> [@Eyalm321](https://github.com/Eyalm321) do you have a tl;dr? The AI copy/pasta is rather uncondensed, if you know what I mean. :/

 There are two separate bugs, both involving Windows' ConPTY but otherwise unrelated:

  1. Slow scrolling output (#7019) — the conhost in current Windows redraws the whole scroll region on
  every line, so streaming output is very slow. This one is fixed in the newer 1.24 console, just not
  shipped into Windows yet. We work around it by bundling the 1.24 files with our app.
  2. Slow startup — when a terminal first attaches, the console asks it a couple of questions and waits
  ~1 second each if nobody answers, which delayed our shell from starting. The 1.24 console does not
  fix this — it actually asks one extra question, so it's a touch worse. We fixed it ourselves by
  answering those questions instantly (startup went 2121ms → 142ms).

**Comment by DHowett** [comment] 2026-06-10 16:44
I'm sorry. When we backport something into existing versions of Windows, it needs to be contained by feature flagging conditionals. The architectural shift in ConPTY as of 1.22 is too broad for us to adequately contain. Use the NuGet package; it updates way faster than Windows.

> We fixed it ourselves by answering those questions

That is the purpose of the questions. If you have the ability to answer them, _answer them._ If you do not have the ability to answer them, you won't be able to answer any application-originated requests either... and that would mean you are not a terminal emulator. 🙂

**Comment by lhecker** [comment] 2026-06-10 21:51
> This one is fixed in the newer 1.24 console, just not shipped into Windows yet. We work around it by bundling the 1.24 files with our app.

It's good to know that the first issue was fixed in 1.24. However, it has nothing to do with this issue in particular, since 1.24 is much more recent. As Dustin alluded to, the actual bug fix was in 1.22 where we fundamentally rewrote how ConPTY works.

> when a terminal first attaches, the console asks it a couple of questions and waits ~1 second each if nobody answers

More specifically, it sends you a DA1 request, which you're expected to respond to, because you're using a PTY, not just setting up any random pipes. It waits 3s for a response. It's not multiple queries with 1s waits each.

@DHowett a few weeks ago I've actually come around this and changed my stance. I would prefer if we changed the behavior such that we defer the DA1 query until as late as possible. We can safely do this, because passthrough-mode ConPTY already injects VT sequences into stdout irrespective of the VT parser state. So, if we additionally inject a late DA1 query only when we have to, we don't make it any worse.
I consider this an important improvement because setting up ConPTY for trivial terminal apps (such as grep.exe) is rather annoying right now and a "user dissat" (where user = me, lol).

**Comment by DHowett** [comment] 2026-06-10 22:03
@lhecker how many of those queries are _required_ and how many are for doing optimizations? Because perhaps we could make the _responses_ late binding rather than the requests - we just issue a request and IF we get a response we adjust ourselves appropriately.

**Comment by lhecker** [comment] 2026-06-10 22:11
If cursor inheritance is disabled, the only query we do is DA1 for "optimizing" the ScrollRect API (it's just optimizing it, but also essential to support Unicode fwiw). Doing the query late is IMO preferable because it makes the stdout on startup completely silent, but I wouldn't mind your approach either.
