### ISSUE TITLE
Weird characters when pasting in WIndows Terminal

### ISSUE THREAD

**Issue by speller** [microsoft/terminal#10572] opened 2021-07-07 09:14 UTC
### Windows Terminal version (or Windows build number)

1.8.1521.0, 10.0.21390.2025

### Steps to reproduce

When I run the following command in Ubuntu 20 from under Windows Terminal:

```
docker run -ti --name gcloud-config gcr.io/google.com/cloudsdktool/cloud-sdk:alpine gcloud auth login
```

I'm getting the following input when pasting the key:

```
Go to the following link in your browser:

    https://accounts.google.com/o/oauth2/auth?response_type=code&client_id=<long URL>

Enter verification code: ^[[200~<real pasted text>^[[201~
```

The command fails to process this input. I'm pasting the `<real pasted text>` but it is actually entered enveloped by  `^[[200~` and `^[[201~` symbols.

```
ERROR: gcloud crashed (InvalidGrantError): (invalid_grant) Malformed auth code.
```

How to fix that?

### Expected Behavior

Command works

### Actual Behavior

Command fails

**Comment by skyline75489** [comment] 2021-07-07 09:21
Interesting report! This is caused by "bracketed paste mode" (see #395), which is only enabled after the shell/application deliberately asks the terminal to enable this feature. 

For more context, what is the shell you're using?

**Comment by speller** [comment] 2021-07-07 09:57
I started a new shell tab window and it worked as expected so I can not reproduce it now.... 
I'm using the `bash` shell but the script's shebang is `#!/usr/bin/env sh`. I tried to add `printf "\e[?2004l"` or `set enable-bracketed-paste off` to my script but it didn't help.

**Comment by zadjii-msft** [comment] 2021-07-07 19:37
skyline75489 is right, those characters are the bracketed paste sequences. 

>  so I can not reproduce it now....

Well shucks. I'm gonna close this for now - if you run into a way to reliably reproduce this, feel free to comment here and we can reopen.

**Closed by zadjii-msft** 2021-07-07 19:37 UTC
Labels: Needs-Tag-Fix, Needs-Triage

**Comment by ivsanro1** [comment] 2023-03-08 10:09
One hacky workaround to disable bracketed paste in the current terminal (the one in which you'll be running the gcloud auth command) is to run:

```bash
printf '\e[?2004l'
```

And then the sequences `^[[200~` and `^[[201~` should not appear anymore when pasting

**Comment by Artim96** [comment] 2023-07-30 21:11
I'm surprised this couldn't be reproduced. This has been a problem for me since day one of using the Terminal. It doesn't happen when using e.g. PowerShell or CMD through it, but any Linux shell will do that, unless you e.g. paste the text into emacs or the sorts. It also doesn't matter if it's the local Debian WSL or any Linux system accessed through ssh. Using Ctrl+Shift+V instead of using Ctrl+V as some recommend doesn't help, as I don't use anything else. And going to each systems ~/.inputrc to enter "set enable-bracketed-paste off" isn't really an option and shouldn't be the solution, as it very much seems to be a fault of the Terminal app. Maybe @zadjii-msft can re-open this issue, as it's very much reproducible and should finally be fixes after so many years.

**Comment by ersjim** [comment] 2023-11-20 16:47
For me it only happens when I ssh into another linux server from WSL.

**Comment by bessone** [comment] 2024-11-07 17:42
From a few days the same thing as @christosg88 has happened to me, via terminal with PowerShell I open an ssh session on remote linux machines and the paste has this behavior.
But only for a couple of days, before it always worked. Has there been any update to terminal or SSH/Powershell?

**Comment by bessone** [comment] 2024-11-07 17:52
Small update: I tried in terminal with WSL and it works, so surely the problem is not with terminal, but with openssh of powershell.
