### ISSUE TITLE
Windows terminal crashes when typing "exit" after "ping"!

### ISSUE THREAD

**Issue by issa-yousef** [microsoft/terminal#9465] opened 2021-03-12 04:13 UTC
# Environment

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Windows Terminal version (if applicable):

Any other software?
```

# Steps to reproduce

# Expected behavior

# Actual behavior

**Comment by issa-yousef** [comment] 2021-03-12 04:14
I am having an issue where if I issue "ping x" command then "ctrl+c" then "exit", it will show following error: "[process exited with code 3221225786]"

**Comment by jdebp** [comment] 2021-03-12 06:48
That is not an error.  That is Windows Terminal reporting the exit status of the program that was running, without closing the window.  This is configurable behaviour, and behaviour that one can find in a few other terminal emulators.  This is also a duplicate of #4573.

**Comment by zadjii-msft** [comment] 2021-03-12 11:33
Yep, this is exactly by design. Please make sure to [search for existing issues](https://github.com/microsoft/terminal/issues?q=is%3Aissue+%22process+exited+with+code%22) before filing a new issue. 

/dup #4573

**Closed by zadjii-msft** 2021-03-12 11:33 UTC
Labels: Needs-Tag-Fix, Needs-Triage
