### ISSUE TITLE
PS 7 prompt does not render properly with shell integration profile code

### ISSUE THREAD

**Issue by StevenBucher98** [microsoft/terminal#17231] opened 2024-05-09 16:49 UTC
### Windows Terminal version

1.22.1271.0 

### Windows build number

10.0.22635.0

### Other Software

PowerShell 7.4.2

### Steps to reproduce

Include this code in your pwsh Profile https://learn.microsoft.com/en-us/windows/terminal/tutorials/shell-integration#powershell-pwshexe

### Expected Behavior

Prompt is always rendered and available

### Actual Behavior

Prompt does not show up until a character is typed
![WTShellInteractionBug](https://github.com/microsoft/terminal/assets/20605456/9d0b8151-dfd4-4337-af35-332277052cf7)

**Comment by yak1ex** [comment] 2024-05-09 18:24
I observed the similar issue in:
Windows Terminal Version: 1.21.240506002-preview (this is v1.21.1272.0)
PSVersion: 5.1.19041.4291
with shell integration & Set-PSReadLineOption -PredictionViewStyle ListView

Might it be "1.22.1271.0" was wrong version description?
An actual similar issue is https://github.com/microsoft/terminal/issues/17204,
and it was stated to be closed by https://github.com/microsoft/terminal/pull/17212

I have not confirmed yet.

**Comment by zadjii-msft** [comment] 2024-05-09 18:32
Yea this is a /duplicate of #17204. Thanks all!

**Closed** 2024-05-09 18:32 UTC
Labels: Issue-Bug, Needs-Triage
