### ISSUE TITLE
Terminal doesn't render light arc characters well

### ISSUE THREAD

**Issue by willmcgugan** [microsoft/terminal#6708] opened 2020-06-28 14:34 UTC
# Environment

```none

Windows Terminal
Version: 1.0.1401.0

Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.18363.0 Microsoft Windows NT 10.0.18363.0
```

# Steps to reproduce

Windows terminal doesn't render unicode box drawing ["light arc"](https://www.fileformat.info/info/unicode/char/256d/index.htm) characters very well. The don't quite align and are not anti-aliased.

# Expected behavior

This is on iTerm on OSX. Other terminals are similar...

<img width="106" alt="Screen Shot 2020-06-28 at 14 30 43" src="https://user-images.githubusercontent.com/554369/85950329-0164dc00-b954-11ea-9867-f5ffccc7bdc4.png">

# Actual behavior

<img width="106" alt="Screen Shot 2020-06-28 at 14 30 05" src="https://user-images.githubusercontent.com/554369/85950316-f90ca100-b953-11ea-8df8-e42605bfab4e.png">

A fairly minor issue I know! I use these characters a lot to render boxes with rounded edges.

**Comment by j4james** [comment] 2020-06-28 17:00
This was previously discussed in https://github.com/microsoft/terminal/issues/5897#issuecomment-628447641, so I suspect it'll be covered by that issue.

**Comment by DHowett** [comment] 2020-06-29 18:08
Yep. I'm gonna close this one out as a /dupe of #5897 -- we'll make sure we get it at the same time

**Closed by DHowett** 2020-06-29 18:08 UTC
Labels: Needs-Tag-Fix, Needs-Triage
