### ISSUE TITLE
Why can't I change the starting directory of Ubuntu in the Windows terminal in WSL?

### ISSUE THREAD

**Issue by CymraegKid** [microsoft/terminal#17707] opened 2024-08-13 07:00 UTC
### Windows Terminal version

1.20.11781.0

### Windows build number

10.0.22631.3880

### Other Software

WSL
UBUNTU

### Steps to reproduce

I change the starting directory setting of ubuntu

![TKQm3mJj](https://github.com/user-attachments/assets/0b5ba40d-55e7-45f5-a12b-88298a894d4d)

### Expected Behavior

Instantly getting to C disk after opening ubuntu terminal

### Actual Behavior

Always getting to the home directory after opening whatever the starting directory i specified in the settings.

![изображение](https://github.com/user-attachments/assets/91971a4d-8760-44df-afdc-1cd2676191cc)

If i change C:\ to /mnt/c/ i get the error after openint ubuntu: [error 2147942667 (0x8007010b) when launching ubuntu2404.exe'] Could not access starting directory "/mnt/c/"

**Comment by carlos-zamora** [comment] 2024-08-14 21:44
Thanks for filing. Marking this as a /dup of #12961. Even though the title doesn't sound the same, it's definitely the same root cause. 😊

**Closed** 2024-08-14 21:44 UTC
Labels: Issue-Bug
