### ISSUE TITLE
Certain Unicode Characters Cause Tmux Status Line to Wrap in Windows Terminal

### ISSUE THREAD

**Issue by 58bits** [microsoft/terminal#5973] opened 2020-05-18 18:05 UTC
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.19041.264]
Windows Terminal version: https://github.com/microsoft/terminal/releases/tag/v0.11.1333.0 
Tmux: 2.6
```

# Steps to reproduce

https://github.com/gpakosz/.tmux/issues/355  - tmux configuration with special unicode glyph causing status line to wrap. `tmux_conf_theme_prefix='⌨'   # U+2328` - with prefix key press detection in status line using - `#{?client_prefix,$tmux_conf_theme_prefix,}` 

# Expected behavior

The right status line should not be pushed right by one character after the prefix key is pressed, and the single unicode 'keyboard' character above is displayed on the status line.

# Actual behavior

Prior to the Windows Terminal v0.11.1333.0 release - `#{?client_prefix,$tmux_conf_theme_prefix,}` setting in status_right was working fine - showing the little keyboard symbol when the tmux prefix key was pressed. However, what's happening now is that status_right is being pushed to the right by a single character, causing the entire status line to wrap, and the tmux window / pane to shift up a line. https://github.com/gpakosz/.tmux/issues/355 shows before and after screenshots.

**Comment by DHowett** [comment] 2020-05-18 18:26
This was a /dupe of #5941, fixed in #5934

**Closed by DHowett** 2020-05-18 18:26 UTC
Labels: Needs-Tag-Fix, Needs-Triage
