### ISSUE TITLE
Make exit code behavior more disacoverable

### ISSUE THREAD

**Issue by superm1** [microsoft/terminal#10798] opened 2021-07-26 21:00 UTC
# Description of the new feature/enhancement
When a process exits with a return code while closing a terminal, the following message shows up (assuming exit 130)
```
[process exited with code 130]
```

It's difficult to know what this means, especially if it's while closing a pane.  If a process returns an exit code that is non zero, I can't figure out how to get rid of that pane now.  Example:
![image](https://user-images.githubusercontent.com/494526/127058330-e5de5f43-7fb2-45f9-b812-79722ce383ed.png)

This inevitably leads eventually to https://github.com/microsoft/terminal/issues/5214

# Proposed technical implementation details (optional)
Add a clearer message why this happened, and how to change it.
```
Process exited with code 130, to adjust what happens with non-zero exit codes visit Settings->Foo->bar
```

Then in the GUI add a new option that will control adding
```
"closeOnExit": "always"
```

**Comment by skyline75489** [comment] 2021-07-27 03:51
>Add a clearer message why this happened, and how to change it.

Cool idea :) /cc @cinnamon-msft 

> Then in the GUI add a new option that will control adding

This exists already.

**Comment by superm1** [comment] 2021-07-27 13:14
> 
> This exists already.

TIL.  It's on a per-OS-profile basis.

**Comment by zadjii-msft** [comment] 2021-08-02 13:15
I'm okay with adding something like 

> to adjust what happens with non-zero exit codes visit Settings->Foo->bar. Read more at \<link-to-the-docs....\>

But only in the scenario where it's only displayed the first time it happens, because otherwise I feel like it just adds noise. Fortunately, with #8324, we can actually do this. Thanks for the idea!

**Comment by Toxic-Waste-** [comment] 2021-08-06 09:00
it's this by design? I have ran into this issue aswell, I use terminal to connect to multiple servers, and especially when I want to close a pane I split before to check something extra, I want the pane to close when I exit the session.

Now it seems to be stuck and I can't get my screenspace back. I also have no way of closing that pane without closing the entire tab, that can't be by design?

Example (obfuscated IP and username information for obvious reasons):
![pane not closing](https://user-images.githubusercontent.com/11042823/128485524-919f6dc3-1842-429e-9da8-225c177fee8c.png)

Or should I create a seperate issue for this?

**Comment by Toxic-Waste-** [comment] 2021-08-06 09:01
it's this by design? I have ran into this issue aswell, I use terminal to connect to multiple servers, and especially when I want to close a pane I split before to check something extra, I want the pane to close when I exit the session.

Now it seems to be stuck and I can't get my screenspace back. I also have no way of closing that pane without closing the entire tab, that can't be by design?

Example (obfuscated IP and username information for obvious reasons):
![pane not closing](https://user-images.githubusercontent.com/11042823/128485720-9b436171-e860-4d97-819b-8e01c51c2fd2.png)

Or should I create a seperate issue for this?

**Comment by DHowett** [comment] 2021-08-06 15:40
> would be nice if it closed by design when you exit an SSH session for example :)

Definitely! That's why we made this configurable with the `closeOnExit` key (or the profile setting about what to do when the connected application exits! It's in the Advanced tab on the profile page.)

**Comment by Don-Vito** [comment] 2021-09-02 21:54
> 
> I'm okay with adding something like
> 
> > to adjust what happens with non-zero exit codes visit Settings->Foo->bar. Read more at <link-to-the-docs....>
> 
> But only in the scenario where it's only displayed the first time it happens, because otherwise I feel like it just adds noise. Fortunately, with #8324, we can actually do this. Thanks for the idea!

@zadjii-msft - how do you envision the UX of this. I believe it should be a TeachingTip rather then printing some text into the terminal. Especially if we want the user to dismiss it explicitly so we won't show it again.

**Closed** 2021-09-10 17:16 UTC
Labels: Area-User Interface, Product-Terminal, Issue-Task, In-PR
