### ISSUE TITLE
win32 input mode: Keyboard number pad not working for Vim in terminal version 1.1

### ISSUE THREAD

**Issue by Muhimen123** [microsoft/terminal#7080] opened 2020-07-26 05:53 UTC
After updating the windows terminal to version 1.1 from Microsoft store, my number pad isn't functioning properly. However, this only happens when I use nvim in the terminal. For other stuffs, it works just fine. At first I thought it's the problem with the nvim I am working with so I reinstalled it but the problem still stayed. I also tried another keyboard and the same problem occurs.

# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18362.959]
Windows Terminal version (if applicable): 1.1

Other software: Neovim version 0.4.3
```

# Steps to reproduce
- Install Neovim(nvim) in windows using `choco`.
- Open up any file and try to write some number using the **number pad**

# Expected behavior
As I type digits using the **number pad**, the numbers should get properly displayed or typed in the file

# Actual behavior
While in `insert` mode of nvim, if I press **0** from the number pad if gets out from the insert mode and takes me into `command`.

**Comment by DHowett** [comment] 2020-07-26 06:09
Does your number pad work if you run nvim _outside of Windows Terminal_, from a standard console window?

**Comment by Muhimen123** [comment] 2020-07-26 06:28
I tried it in windows command prompt and it works fine.

**Comment by zadjii-msft** [comment] 2020-07-27 12:08
As a workaround, can you see what happens if you put the following setting at the root of your settings file?

```json
"experimental.input.forceVT": true,
```

**Comment by Muhimen123** [comment] 2020-07-28 09:04
@zadjii-msft Thanks, It's working now.

**Comment by DHowett** [comment] 2020-07-31 00:55
Triaged into backlog as a bug. The only difference between the numberpad 0 in WT and Conhost is that in WT it's missing the `NUM_LOCK` flag. If NeoVim requires this (which it shouldn't), we'll need to figure out how to generate it.

**Comment by DHowett** [comment] 2020-07-31 00:59
Actually, I'm recanting this. It's by design.

I just checked in vim on my own machine, and vim switches between replace and insert mode _in the traditional console_ when you press VK_NUMPAD0. All the way back to the 2017 versions of Windows.

This is happening in Terminal now because before 1.1, Terminal pretended that the two different versions of 0 on your keyboard were the same thing. Now it knows they're different. `input.forceVT` makes it pretend they're the same.

**Closed by DHowett** 2020-07-31 00:59 UTC
Labels: Area-Input, Issue-Bug, Product-Terminal
