### ISSUE TITLE
Draft 2019-09 schemas are not yet fully supported terminal in settings,json

### ISSUE THREAD

**Issue by uditswaroopa** [microsoft/terminal#7683] opened 2020-09-20 05:17 UTC
Everything was fine till yesterday, today all of a sudden I noticed my custom windows terminal theme showed just two colors the primary background color and font color as white for every word. Then I hover over my settings.json file I saw warning popping up in 
$schemas: "https://aka.ms/terminal-profiles-schema" with warning "Draft 2019-09 schemas are not yet fully supported terminal"

Everything is working fine except some words are not highlighted in a different color, which earlier was working fine. 
![{66D477C5-C6BD-4F94-9373-DA06E95EAF9F}](https://user-images.githubusercontent.com/65483816/93694875-aeec2380-fb2e-11ea-8561-eb059252850d.png)

**Comment by leguminosa** [comment] 2020-09-20 10:19
I also face the same issue,

My problem is that my font (MesloLGS NF) is not rendered (I suppose it revert back to Consolas instead)
![image](https://user-images.githubusercontent.com/38403278/93709032-3fddf180-fb65-11ea-85ac-48e7c7cfb812.png)
doesn't matter where I put the fontFace (in global or in ubuntu profile) it still doesn't work

until today it still working
![image](https://user-images.githubusercontent.com/38403278/93709047-597f3900-fb65-11ea-9db0-5185163b84ea.png)

**Comment by DHowett** [comment] 2020-09-21 18:51
The schema error has no bearing on whether Terminal actually supports your settings. Can you share the rest of your `settings.json` and tell us what versions of what software you're using? It would be great to know _who is printing the colored words_ and _what version it is_ and _how you launched it_ and _what the profile configuratio n is_.

**Comment by DHowett** [comment] 2020-09-21 18:51
If I had to guess, I'd say you are using Windows PowerShell x86 and running into #7418. Don't make me guess.

**Comment by KalleOlaviNiemitalo** [comment] 2020-09-21 18:52
The schema was upgraded to draft 2019-09 in <https://github.com/microsoft/terminal/commit/06b50b47ca7701fd4c47bc424d810dd205596e95> (<https://github.com/microsoft/terminal/pull/6891>), presumably to allow `"deprecated": true` in the `rowsToScroll` property.

This rationale in the commit message looks odd, though:

> I have not removed it from the schema, as I do not want to mark folks'
> settings files invalid to a strict schema parser.

Because the `#/definitions/Globals` schema has `"additionalProperties": true`, I would expect validators to tolerate the `rowsToScroll` property in settings files even if it were removed from the schema.

**Comment by DHowett** [comment] 2020-09-21 18:55
Fair.

It's also been a year, so I'm surprised that our modern auto-updating text editor still carps about it. 😀

**Comment by uditswaroopa** [comment] 2020-09-22 04:54
@DHowett You are correct while I am using Powershell syntax highlighting is working fine but it is not the case for other like Ubuntu, Cmd and Azure 
here is my settings.json file

// This file was initially generated by Windows Terminal 1.2.2381.0
// It should still be usable in newer versions, but newer versions might have additional
// settings, help text, or changes that you will not see unless you clear this file
// and let us generate a new one for you.

// To view the default settings, hold "alt" while clicking on the "Settings" button.
// For documentation on these settings, see: https://aka.ms/terminal-documentation
{
    "$schema": "https://aka.ms/terminal-profiles-schema",
    "defaultProfile": "{2c4de342-38b7-51cf-b940-2309a097f518}",
    "copyOnSelect": true,
    "copyFormatting": false,
    "profiles":
    {
        "list":
        [
            {
                "guid": "{2c4de342-38b7-51cf-b940-2309a097f518}",
                "hidden": false,
                "name": "Ubuntu",
                "source": "Windows.Terminal.Wsl",
                "colorScheme": "Andromeda",
                "startingDirectory": "C:/Users/UDIT SWAROOPA/OneDrive/UNIX"
            },
            {
                "guid": "{61c54bbd-c2c6-5271-96e7-009a87ff44bf}",
                "name": "Windows PowerShell",
                "commandline": "powershell.exe",
                "hidden": false
            },
            {
                "guid": "{0caa0dad-35be-5f56-a8ff-afceeeaa6101}",
                "name": "Command Prompt",
                "commandline": "cmd.exe",
                "hidden": false
            },
            {
                "guid": "{b453ae62-4e3d-5e58-b989-0a998ec441b8}",
                "hidden": false,
                "name": "Azure Cloud Shell",
                "source": "Windows.Terminal.Azure"
            }
        ]
    },
    "schemes": [
        {
            "name": "Andromeda",
            "black": "#090300",
            "red": "#db2d20",
            "green": "#01a252",
            "yellow": "#fded02",
            "blue": "#01a0e4",
            "purple": "#a16a94",
            "cyan": "#b5e4f4",
            "white": "#a5a2a2",
            "brightBlack": "#5c5855",
            "brightRed": "#e8bbd0",
            "brightGreen": "#3a3432",
            "brightYellow": "#4a4543",
            "brightBlue": "#807d7c",
            "brightPurple": "#d6d5d4",
            "brightCyan": "#cdab53",
            "brightWhite": "#f7f7f7",
            "background": "#090300",
            "foreground": "#a5a2a2"
          }
    ],
    "keybindings":
    [
        { "command": {"action": "copy", "singleLine": false }, "keys": "ctrl+c" },
        { "command": "paste", "keys": "ctrl+v" },
        { "command": "find", "keys": "ctrl+shift+f" },
        { "command": { "action": "splitPane", "split": "auto", "splitMode": "duplicate" }, "keys": "alt+shift+d" }
    ]
}

**Comment by DHowett** [comment] 2020-09-22 04:56
The default shell in Ubuntu, `bash`, does not support syntax highlighting. Neither does CMD! you need to have a shell that supports syntax highlighting, like `fish` or `zsh`+a syntax plugin.

**Comment by uditswaroopa** [comment] 2020-09-23 11:26
No, that is not the case as earlier it was working earlier and I have not done any changes in seeting see I have screenshoot
![554c1262-1751-48b6-829c-d68444f2c577](https://user-images.githubusercontent.com/65483816/94006613-b70dc280-fdbd-11ea-91a0-324c0fc57cf9.jpg)

**Comment by DHowett** [comment] 2020-09-23 16:17
I'm not seeing any syntax highlighting. That's just a colored prompt.

Can you share a screenshot of what it looks like now, when it is not working?

**Comment by uditswaroopa** [comment] 2020-09-23 20:04
yeah I mean color prompt I am sorry, here is a screenshot of what is looking right now
![image](https://user-images.githubusercontent.com/65483816/94063671-10014900-fe06-11ea-89c6-868f9feeacd9.png)

**Comment by WSLUser** [comment] 2020-09-24 15:18
So the schema error pops up regardless if you have a default settings.json or a customized one. I'm not sure why it shows up but might be VS Code related since it wasn't an issue before. I can also confirm the color prompt issue as well. That may be better filed separately though.

**Comment by KalleOlaviNiemitalo** [comment] 2020-09-24 15:27
> I'm not sure why it shows up but might be VS Code related since it wasn't an issue before.

I guess the schema warnings started on 14 July 2020 when <https://github.com/microsoft/terminal/pull/6891> was merged, even for those users who did not install newer versions of Windows Terminal.

Related: <https://github.com/microsoft/vscode/issues/98724>

**Comment by zadjii-msft** [comment] 2020-09-29 03:55
Alright so the schema thing seems like a red herring to me. That's not going to be the cause of the colors not working in the terminal. Looks like for whatever reason, you color scheme isn't getting applied. 

@uditswaroopa What version of the terminal are you using?

**Comment by uditswaroopa** [comment] 2020-09-29 11:04
I don't think so the schema is not applying because the schema is working fine when I am in Powershell, also I made no changes with the settings.json file this warning popped up all of a sudden. Btw this is my version 1.3.2651.0

**Comment by KalleOlaviNiemitalo** [comment] 2020-09-29 11:48
@uditswaroopa, you could try changing to `"$schema": "https://github.com/microsoft/terminal/blob/e504bf21402bca34e45863370aad9fefd543c292/doc/cascadia/profiles.schema.json"`. That was the last version before the schema was upgraded to draft 2019-09. If you change the schema URL like that, I think it will avoid the <q>Draft 2019-09 schemas are not yet fully supported</q> warning in Visual Studio Code but will not restore the prompt colors of Ubuntu in Windows Terminal. That would prove these are two separate problems.

Regarding the prompt colors, I think the `PS1` shell variable is not set correctly. Login scripts should normally set it. Please run these commands in `bash`, to show some relevant values:

```bash
declare -p BASH_VERSION PS1 TERM
echo $-
```

**Comment by zadjii-msft** [comment] 2020-09-29 12:08
Wait lets make sure to clear something up: "schema" != "scheme".

"schema" refers to the json schema, which provides some metadata on the json settings that editors like VsCode can use to provide error checking and autocomplete.

"scheme" refers to "color scheme", as in the set of colors that the Terminal uses to draw text with. 

I concur with @KalleOlaviNiemitalo - could you run those commands?

**Comment by uditswaroopa** [comment] 2020-09-29 16:04
Hello, @KalleOlaviNiemitalo thanks for the light on the issue the warning has gone which proves both are different issues. 
I am uploading a screenshot of the commands you mentioned,
![image](https://user-images.githubusercontent.com/65483816/94583815-8507cf00-029b-11eb-9f20-9c3cd2df1bdc.png)

**Comment by DHowett** [comment] 2020-10-01 00:13
![image](https://user-images.githubusercontent.com/189190/94752307-af12cd00-033f-11eb-9e5f-d4a9326f62a7.png)


It looks like you're hitting this particularly nasty bit of Debian's default bash configuration:

```
# set a fancy prompt (non-color, overwrite the one in /etc/profile)
# but only if not SUDOing and have SUDO_PS1 set; then assume smart user.
if ! [ -n "${SUDO_USER}" -a -n "${SUDO_PS1}" ]; then
  PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w\$ '
fi
```

"non-color".
Something changed about your shell initialization, which isn't something Terminal (or really WSL!) controls.

It might be worthwhile to run `bash -ilx` and inspecting the output to determine why `color_terminal` isn't being detected in `~/.bashrc`.

Alternatively, you may have added a `.profile` or `.bash_profile` or changed how your shell starts to strip off the `--login` or `--interactive` arguments.

It's complicated, for sure, but not something Terminal broke.

**Closed by DHowett** 2020-10-01 00:13 UTC
Labels: Needs-Attention, Needs-Tag-Fix, Needs-Triage

**Comment by fxzxmic** [comment] 2021-06-23 14:00
Just change `https://aka.ms/terminal-profiles-schema` to `https://json-schema.org/draft/2020-12/schema#`, probably because `https://aka.ms/terminal-profiles-schema` is not updated.

**Comment by KalleOlaviNiemitalo** [comment] 2021-06-23 14:27
@fxzxmic do you mean you have `"$schema": "https://json-schema.org/draft/2020-12/schema#"` in your settings.json file? If so, that seems a bad idea to me, because settings.json is not a schema document.

**Comment by WSLUser** [comment] 2021-06-23 14:35
Set schema in settings.json to `"$schema": "https://raw.githubusercontent.com/microsoft/terminal/main/doc/cascadia/profiles.schema.json"`
`https://json-schema.org/draft/2020-12/schema#` exists there.

**Comment by fxzxmic** [comment] 2021-06-23 14:36
@KalleOlaviNiemitalo In fact, I just answered the author's questions, and I didn't study the deep technical details. After all, for warnings that just need to be removed from VSCODE, this is only the result of the URL not being updated in time.

**Comment by fxzxmic** [comment] 2021-06-23 14:38
> Set schema in settings.json to `"$schema": "https://raw.githubusercontent.com/microsoft/terminal/main/doc/cascadia/profiles.schema.json"`
> `https://json-schema.org/draft/2020-12/schema#` exists there.

You can do that too, but the URL is too long. 🤣

**Comment by WSLUser** [comment] 2021-06-23 14:39
It's just a copy and paste.....plus that ensures you get the latest updates for the schema, in case the shortened URL isn't updated. For example, I made an update yesterday that shows there now.

**Comment by DHowett** [comment] 2021-06-23 15:47
> @DHowett Hope this link `https://aka.ms/terminal-profiles-schema` can be updated.

Hmm. This link is supposed to track the state of the schema at the time that we made the stable release. I can backport the schema version change to it, but I cannot wholesale update it to be the latest version as it would contain settings that do not work in (current stable version) 1.8.

**Comment by fxzxmic** [comment] 2021-06-23 16:09
> > @DHowett Hope this link `https://aka.ms/terminal-profiles-schema` can be updated.
> 
> Hmm. This link is supposed to track the state of the schema at the time that we made the stable release. I can backport the schema version change to it, but I cannot wholesale update it to be the latest version as it would contain settings that do not work in (current stable version) 1.8.

Does that mean it also contains settings that don't work in version 1.9? Because it's the same in 1.9 and 1.8.
https://github.com/microsoft/terminal/blob/fd06b0ce60a21473e6d0ee4756e1b46c6e80c90d/doc/cascadia/profiles.schema.json#L3
https://github.com/microsoft/terminal/blob/6617eb33ac640fcebad520bd94e53c11cf2e05fe/doc/cascadia/profiles.schema.json#L3
But for VScode, it needs `https://json-schema.org/draft/2020-12/schema#`. So is VScode too far ahead?

**Comment by DHowett** [comment] 2021-06-23 16:11
That just means that we didn't get a fix for us using an unacceptable version of the json-schema draft schema in time for 1.9. :smile:

**Comment by arunsingh28** [comment] 2021-12-23 22:41
this link not working in my system still showing the wired icon

<img width="863" alt="Screenshot 2021-12-24 041032" src="https://user-images.githubusercontent.com/48112517/147297057-89ad1d84-13cf-40bf-8dea-ab3055977da5.png">
s

**Comment by DHowett** [comment] 2021-12-24 02:58
@arunsingh28 that doesn't appear to be an issue with the schema, which is what this topic is about. 

That appears to be an issue with you entering a `bash`-specific command in PowerShell.
