### ISSUE TITLE
Please, add support to add whole background opacity without changing text opacity

### ISSUE THREAD

**Issue by effolkronium** [microsoft/terminal#4435] opened 2020-02-01 13:31 UTC
# Description of the new feature/enhancement

# Proposed technical implementation details (optional)

Make the same as "Opacity" settings in placin cmd.exe. But this setting changes text opacity as well. Please, add separate settings for text (foreground) and background opacity

**Comment by effolkronium** [comment] 2020-02-01 13:32
what? i just wrote a bunch of text. but there is only one part of it. stupid github

**Comment by effolkronium** [comment] 2020-02-01 13:33
but it is enough

**Comment by DHowett-MSFT** [comment] 2020-02-03 06:33
Thanks for the request! This is a /dupe of #603

**Closed by DHowett-MSFT** 2020-02-03 06:33 UTC
Labels: Issue-Feature, Needs-Tag-Fix, Needs-Triage
