### ISSUE TITLE
Some emojis are displaying wrong

### ISSUE THREAD

**Issue by belarusaed** [microsoft/terminal#14348] opened 2022-11-05 21:51 UTC
### Windows Terminal version

1.15.2875.0

### Windows build number

10.0.22621.0

### Steps to reproduce

Some emojis, those made of other emojis, like 👨‍👩‍👧‍👦 are displaying incorrect.
Also, it doesn't display handshake emojis with different skin tones (e.g. 🫱🏼‍🫲🏽) properly.

### Actual Behavior

Demo: https://youtu.be/f6Bqx-FTByo

**Comment by lhecker** [comment] 2022-11-07 14:01
This appears to be a duplicate of #8000.

**Closed** 2022-11-07 14:30 UTC
Labels: Issue-Bug, Needs-Triage
