### ISSUE TITLE
Slow text rendering through SSH and tmux with a lot of text output

### ISSUE THREAD

**Issue by NielsH** [microsoft/terminal#3501] opened 2019-11-09 12:11 UTC
# Environment

```none
Windows build number: [Version 10.0.19008.1000]
Windows Terminal version (if applicable): 0.6.2951.0

Any other software?
Ubuntu 18.04.3 LTS through WSL v2 / Windows Build 19008
```

# Steps to reproduce

1. Use ssh to connect to a linux server through the Terminal App running Ubuntu with WSL v2.
2. Start tmux on the linux server you are connected to through SSH
3. Run `find /`
4. Wait a few seconds (5-10)
5. Attempt to CTRL+C

# Expected behavior

I expect that immediately, or after a few seconds at most, the CTRL+C command interupts the command and scrolling output from the find command in the terminal.

# Actual behavior

It seems that the terminal is unable to handle the fast/large amount of text output from the find command. Looking at the time that tmux shows in the bottom-right of the screen, it can be minutes "behind" in rendering the text output.

Other notes:
* Running in tmux locally, without going through SSH, it takes ~2 seconds for a CTRL+C to come through
* Running without tmux locally, without going through SSH, CTRL+C is immediate
* Running without tmux but with SSH, executing a find on a remote linux server, it takes about 5-7 seconds for the CTRL+C to come through.

So it seems only the combination of being connected to another server through SSH, running a tmux there, and then having a lot of text output causes the issue where the terminal is very far (minutes) behind with rendering the text output.

**Comment by egmontkob** [comment] 2019-11-09 13:31
This is probably the same as #3075.

The more of network, ssh, tmux etc. you have, the larger the buffer between `find` as it emits the data and Terminal as it reads it. Ctrl+C is probably immediately sent to `find` and it immediately terminates, but there's still a lot of data in these buffers that are yet to be processed by the Terminal.

**Comment by zadjii-msft** [comment] 2019-11-11 20:48
This also has flavors of #1064. Considering this is close enough to the others, let's just call this /dupe of #3075. Thanks!

**Closed by zadjii-msft** 2019-11-11 20:48 UTC
Labels: Needs-Tag-Fix, Needs-Triage
