### ISSUE TITLE
Set 'Default terminal application' to Windows Terminal break 'Get-Credential' cmdlets in Windows PowerShell

### ISSUE THREAD

**Issue by doggy8088** [microsoft/terminal#15878] opened 2023-08-25 06:42 UTC
### Windows Terminal version

1.17.11461.0

### Windows build number

10.0.19045.3324

### Steps to reproduce

1. Configure `Default terminal application` from `Let Windows decide` to `Windows Terminal`.

    ![image](https://github.com/microsoft/terminal/assets/88981/b9b5b29d-f221-4605-9bf1-444d0537d56a)

2. Open Windows PowerShell (5.1.19041.3031)

    ![image](https://github.com/microsoft/terminal/assets/88981/80248396-3e5d-4fab-843f-2a952f879341)

3. Execute `Get-Credential` cmdlet

    ```ps1
    Get-Credential -Message "AzureAD Login" -UserName "user@example.com"
    ```

    I expected to show up **Windows PowerShell credential request.** window, but it doesn't.

    ![image](https://github.com/microsoft/terminal/assets/88981/5aeddad8-ed97-4a66-9529-fcc114b31abf)

4. If I open another new tab with Windows PowerShell, the problem solved.

    ![image](https://github.com/microsoft/terminal/assets/88981/4dcd19e5-4212-4882-80c5-279a3da31bdd)

### Expected Behavior

I expected to show up **Windows PowerShell credential request.** window, but it doesn't.

### Actual Behavior

The first Windows PowerShell session in the Windows Terminal window will not be able to execute `Get-Credential` correctly. There is no error occurred. I also tried `Get-Credential -Message "AzureAD Login" -UserName "user@example.com" -Verbose` command. It still nothing show up.

**Comment by lhecker** [comment] 2023-08-25 16:27
Hey! Thanks for the report, but this is a duplicate of #14119. It contains more information about why this happens as well as workarounds for the issue. /dup #14119

**Closed** 2023-08-25 16:27 UTC
Labels: Issue-Bug, Needs-Triage
