### ISSUE TITLE
Maximized terminal windows have a 1px border (preventing easy access to all title bar controls)

### ISSUE THREAD

**Issue by a1291762** [microsoft/terminal#9090] opened 2021-02-09 23:46 UTC
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.19042.746]
Windows Terminal version (if applicable): 1.5.10271.0
```

# Steps to reproduce

Maximize the terminal window.
Attempt to interact with any of the controls on the top of the window - tabs, +, v (dropdown), even the window controls (min, max, close).

# Expected behavior

All of these should work when the mouse is at the top of the screen (known as "infinite height", since the user does not need to accurately position the mouse vertically, just jam it up to the top of the screen).

# Actual behavior

There's a 1px border preventing interacting with any of these controls.
The user must move the mouse down slightly in order to click on anything.

**Comment by DHowett** [comment] 2021-02-10 00:10
Thanks for the report. This looks like a /duplicate of #7422!

**Comment by PankajBhojwani** [comment] 2021-02-10 00:10
dup [#7422](https://github.com/microsoft/terminal/issues/7422)

**Closed** 2021-02-10 00:10 UTC
Labels: Needs-Tag-Fix, Needs-Triage
