### ISSUE TITLE
Terminal Solarized Dark background matches brightBlack causing hidden argument text

### ISSUE THREAD

**Issue by DepthDeluxe** [microsoft/terminal#6208] opened 2020-05-26 16:32 UTC
# Environment

```none
Windows build number: Win32NT             10.0.18363.0 Microsoft Windows NT 10.0.18363.0
Windows Terminal version (if applicable): 1.0.1401.0
```
I am running Powershell 7.0 in the terminal but I verified that this behavior also exists in older versions of Powershell.

# Steps to reproduce
1. Delete existing settings.json to fill in with default settings.
2. Set the Powershell config to use the "Solarized Dark" theme.
3. Open a new instance of Powershell in terminal and type `testing123 -XYZ`, the `-XYZ` portion will not be shown.

# Expected behavior
I would expect to see "-XYZ" to still be visible.  Perhaps it would be better to have command line arguments highlighted in white.

![image](https://user-images.githubusercontent.com/4984331/82926196-af373200-9f33-11ea-9b22-bc2fed54e1d8.png)

# Actual behavior
The `-XYZ` text will not be shown as it is the same color as the background.  I have verified this by overriding the "brightBlack" solarized theme color to any other color and it shows up.

![image](https://user-images.githubusercontent.com/4984331/82926009-654e4c00-9f33-11ea-984a-e32ff63b5487.png)

**Comment by j4james** [comment] 2020-05-26 19:20
Yeah, unfortunately the _Solarized_ color schemes are just not very good, and I think at this point everyone is regretting including them by default. See #4047, #2622, #4794, #4818, #5896, and  #6061.

**Comment by skyline75489** [comment] 2020-05-26 22:09
I used to love Solarized Dark and spent my time with it. Now it’s just kinda boring and also problematic. 

Hey this would make a good rap song, if Eminem ever wanna rap about terminal color scheme.

**Comment by zadjii-msft** [comment] 2020-05-27 20:05
Yea I'm gonna close this as a dupe of the above threads. I agree with everyone - I liked Solarized at one point in the past, and I feel like I see it _everywhere_, but yea it's been nothing but trouble.

/dup #4047, #2622, #4794, #4818, #5896, and #6061

**Closed by zadjii-msft** 2020-05-27 20:05 UTC
Labels: Needs-Tag-Fix, Needs-Triage
