### ISSUE TITLE
Feature Request: Ability to group and sectionize machines

### ISSUE THREAD

**Issue by Pantastisch** [microsoft/terminal#2216] opened 2019-08-03 12:20 UTC
# Description of the new feature/enhancement
The ability to group or sectionize machines would be a nice feature to organize your machines and consoles.

See (1) for grouping example
See (2) and (3) for section example

![image](https://user-images.githubusercontent.com/45369229/62411837-943caf80-b5f9-11e9-8d4e-1a486c113b08.png)

Thanks!

**Comment by zadjii-msft** [comment] 2019-08-05 13:54
This is going to be a dupe of #1571

**Closed by zadjii-msft** 2019-08-05 13:54 UTC
Labels: Issue-Feature, Needs-Tag-Fix, Needs-Triage
