### ISSUE TITLE
Show window size when resizing window

### ISSUE THREAD

**Issue by Maselko** [microsoft/terminal#9266] opened 2021-02-24 12:29 UTC
# Description of the new feature/enhancement

It would be nice to have option to see the window size (like columns x lines) while changing window size.

**Comment by j4james** [comment] 2021-02-24 19:55
This looks like a duplicate of issue #2833.

**Comment by zadjii-msft** [comment] 2021-02-24 20:07
It sure is!


/dup #2833

**Closed by zadjii-msft** 2021-02-24 20:07 UTC
Labels: Issue-Feature, Needs-Tag-Fix, Needs-Triage
