### ISSUE TITLE
Alt button not working

### ISSUE THREAD

**Issue by K1LLER0M** [microsoft/terminal#1777] opened 2019-07-02 15:27 UTC
After trying to use vim in the terminal to write a C program I realized that the Alt button does not work ( At least in AZERTY keyboard layout ) so I can't write neither `` [ backticks ] nor # [ hash symbol ]

**Comment by zadjii-msft** [comment] 2019-07-02 15:28
Please try searching, this is a dupe of #521 which is pinned to the top of the repo.

**Closed by zadjii-msft** 2019-07-02 15:28 UTC
Labels: Needs-Tag-Fix, Needs-Triage

**Comment by K1LLER0M** [comment] 2019-07-02 15:29
Oops, I didn't notice that, thanks
