### ISSUE TITLE
Suggestion: Allow user defined labels for WSL windows/tabs.

### ISSUE THREAD

**Issue by edburns** [microsoft/terminal#4418] opened 2020-01-30 21:48 UTC
# Description of the new feature/enhancement

Your program starting to compare favorably to iTerm2 on Mac, but here is one small request: allow the user to specify the tab label for WSL tabs.

Apparently this is possible for some non-WSL tabs, as shown in [issue 1868](https://github.com/microsoft/terminal/issues/1868) but it is not apparent how to set the tab label for WSL tabs.

This feature is useful if you have many different terminal windows open and need to keep track of what you are doing in each one.

# Proposed technical implementation details (optional)

Here's how iTerm2 does it.  YMMV.

* Command i.
* A window appears with keyboard focus automatically on the field you need to change to set the label, and the current value is highlighted, for easy replacement.
* Type in the new value.  As you type, the new value shows up on the window title bar, character by character.
* Dismiss the window.

**Comment by DHowett-MSFT** [comment] 2020-01-31 03:04
I think is is a /dupe of #1079. Thanks!

**Closed by DHowett-MSFT** 2020-01-31 03:04 UTC
Labels: Issue-Feature, Needs-Tag-Fix, Needs-Triage

**Comment by edburns** [comment] 2020-01-31 17:10
Thanks @DHowett .  I swear I looked for an existing issue!
