### ISSUE TITLE
keybindings marked deprecated in preview $schema

### ISSUE THREAD

**Issue by xudyang1** [microsoft/terminal#17919] opened 2024-09-12 17:32 UTC
### Windows Terminal version

1.22.2362.0

### Windows build number

10.0.19045.0

### Steps to reproduce

1. Open windows terminal settings.json.
2. See a record with key "keybindings", and value of an array of `{ "id": "...", "keys": "key..." }`.
3. Remove the keybindings record
4. Open command palette by `ctrl+shift+p`
5. Notice that settings.json has been updated and contains a new keybindings record.

![image](https://github.com/user-attachments/assets/5eb9c258-e4e0-436b-ae75-9290d89b7e1f)

### Expected Behavior

No deprecated keybindings generated.

### Actual Behavior

Always updates settings.json automatically.

**Comment by zadjii-msft** [comment] 2024-09-14 10:55
That's actually by design. `keybindings` is coming back to the settings in 1.22. 

what isn't by design is that the link in the `$schema` hasn't been redirected to the preview branch yet. Our bad! @nguyen-dows can you update that aka.ms link then close this out?

**Comment by xudyang1** [comment] 2024-09-15 18:00
> That's actually by design. `keybindings` is coming back to the settings in 1.22.
> 
> what isn't by design is that the link in the `$schema` hasn't been redirected to the preview branch yet. Our bad! @nguyen-dows can you update that aka.ms link then close this out?

I have updated the issue title.

**Comment by DHowett** [comment] 2024-09-16 17:00
Thanks. I just redirected the schema links. Sorry for the delay.

**Closed by DHowett** 2024-09-16 17:00 UTC
Labels: Issue-Docs, Needs-Triage
