### ISSUE TITLE
Unicode neutral characters width

### ISSUE THREAD

**Issue by kghost** [microsoft/terminal#42] opened 2017-12-23 18:41 UTC
As [Unicode TR11](http://unicode.org/reports/tr11/) suggested, all neutral characters map to halfwidth or narrow characters.

According to [EastAsianWidth](http://unicode.org/Public/UNIDATA/EastAsianWidth.txt) following characters are neutral:

✖ 0x2716
✚ 0x271A
✭ 0x272D
✹ 0x2739

so they should be halfwidth or narrow, but is rendered full-width in CMD.exe, which is causing terminal disarrangement.

Your Windows build number:  (Type `ver` at a Windows Command Prompt)

Microsoft Windows [Version 10.0.16299.125]

**Comment by ExE-Boss** [comment] 2019-09-25 14:15
Duplicate of #2066?

**Comment by zadjii-msft** [comment] 2021-11-22 14:18
This looks like it was fixed at some point in the past - unsure when precisely:
```
printf "foo\u2716bar\nfoo\u271abar\nfoo\u272dbar\nfoo\u2739bar\n"
```
![image](https://user-images.githubusercontent.com/18356694/142877249-5d9e9541-6623-4ad6-b1ee-ab3f17c993f5.png)

**Closed by zadjii-msft** 2021-11-22 14:18 UTC
Labels: Product-Conhost, Area-Rendering, Area-Output, Issue-Bug
