### ISSUE TITLE
White screen with "initialCols" & "initialRows" set large value

### ISSUE THREAD

**Issue by yx91490** [microsoft/terminal#3423] opened 2019-11-03 06:11 UTC
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18362.418]
Windows Terminal version :  0.6.2951.0
White screen when  drag the window with large "initialCols" & "initialRows" set(e.g. 110 * 30).
```

# Steps to reproduce

set "initialCols" to 110, and set  "initialRows"  to 30, then drag a new opened window.

# Expected behavior

normally show.

# Actual behavior

terminal  screen be white when I open a window and drag it, but when I maximize it, it recover to normal.
![terminal_bug](https://user-images.githubusercontent.com/8814185/68081120-b4bc1600-fe43-11e9-95d3-6a8ce4d4ee6e.png)

**Comment by DHowett-MSFT** [comment] 2019-11-04 20:34
This looks like a /dupe of #3065.

**Closed by DHowett-MSFT** 2019-11-04 20:34 UTC
Labels: Needs-Tag-Fix, Needs-Triage

**Comment by yx91490** [comment] 2019-11-05 09:14
more information: if set "initialCols" , "initialRows" to (90,25), this problem will not appear.
