### ISSUE TITLE
可以添加非acrylic透明度或者模糊程度的选项吗？(Can you add options for non-ACRYLIC transparency or degree of blur option?)

### ISSUE THREAD

**Issue by Salted-Fish-Swimming** [microsoft/terminal#7547] opened 2020-09-06 06:45 UTC
# Description of the new feature/enhancement

&emsp;   可以添加非acrylic透明度或者模糊程度的选项吗？我是一名初学者，需要经常性的查看文档或对着教程敲击命令，原生的powershell窗口和wsl窗口能很好的满足我的需求。我将需要查看的文档放在后面，将终端放在前面，就能在终端里不停的操作而不需要频繁的按`alt + c`来切换窗口，但windows terminal不行。

### translation from youdao:
&emsp;  Can you add options for non-ACRYLIC transparency or degree of blur?As a beginner, I need to constantly check documents or type commands into tutorials. The native PowerShell window and WSL window are good for my needs.I put the document I need to view in the back and the terminal in the front, so That I can operate continuously in the terminal without needing to frequently press 'Alt + C' to switch Windows, but Windows Terminal does not work.

可以看到背后的内容(You can see what's behind it)
<img src = "https://user-images.githubusercontent.com/62016442/92319612-eba71d80-f04c-11ea-94bd-45eec740069d.png" width = 70% hight = 70%/>

不能看到背后的内容(You can't see what's behind it)
<img src = "https://user-images.githubusercontent.com/62016442/92319615-ed70e100-f04c-11ea-9caf-1b71f10b24b1.png" width = 70% hight = 70%/>

**Comment by j4james** [comment] 2020-09-06 12:57
I think this is a duplicate of issue #603.

**Comment by DHowett** [comment] 2020-09-08 17:04
It sure is. Thanks you!

/dup #603.

**Closed** 2020-09-08 17:04 UTC
Labels: Issue-Feature, Needs-Tag-Fix, Needs-Triage
