### ISSUE TITLE
Feature Request: Add "RUNAS" option to tabs

### ISSUE THREAD

**Issue by xpwn3rx** [microsoft/terminal#1053] opened 2019-05-29 15:21 UTC
# Summary of the new feature/enhancement

In our environment, we routinely need to run things as different user accounts (typically as our elevated domain admin accounts). It would be extremely useful to be able to right click on the terminal type list when launching a new tab and then run as another user/administrator.

# Proposed technical implementation details (optional)

I'd like to have the option to right click a new tab option and then launch as administrator or as another user, but have the window appear in the same grouping. Having them in a separate window is not the goal.

**Comment by zadjii-msft** [comment] 2019-05-29 15:31
Yea this is going to be a dupe of the discussion in #1032

**Closed** 2019-05-29 15:31 UTC
Labels: Issue-Feature, Needs-Tag-Fix, Needs-Triage, Product-Meta, Resolution-Duplicate

**Comment by xpwn3rx** [comment] 2019-05-30 19:35
> Yea this is going to be a dupe of the discussion in #1032

Thanks, I searched but didn't find that. I see why since the syntax didn't match, sorry for the spam. If I could implement myself, I'd give it a shot and share, but I'm way outside my level of expertise with smaller c# apps and I pretty much only do WinForm.
