### ISSUE TITLE
how to config the starting directory for ubuntu

### ISSUE THREAD

**Issue by jiaqidegege** [microsoft/terminal#2849] opened 2019-09-23 09:46 UTC
I have got WSL2 installed. When I boot ubuntu in the terminal, it's default starting directory is %USERPROFILE%, what should I do to set the ubuntu root directory as the starting directory,I've tried to set it to '/' ,but not help.
![image](https://user-images.githubusercontent.com/31435549/65416236-04adc300-de2a-11e9-9d32-c50ae3c5dec8.png)

**Comment by Biswa96** [comment] 2019-09-23 12:20
In the `commandLine`, append `--cd` option with the Windows style folder name.

**Comment by Biswa96** [comment] 2019-09-23 12:22
In the `commandLine`, append `--cd` option with the Windows style folder name. Fro example, here it will be `wsl.exe -d Ubuntu --cd "C:\Users\jiaqidegege"`.

**Comment by zadjii-msft** [comment] 2019-09-23 13:18
This is a dupe of so very many issues, please search before filing.  `startingDirectory` needs to be a Windows path. I'd recommend setting it to `//wsl$/Ubuntu/home/username`

**Closed** 2019-09-23 21:20 UTC
Labels: Issue-Docs, Needs-Tag-Fix, Needs-Triage, Resolution-Duplicate
