### ISSUE TITLE
Rearrange terminal tabs with keyboard

### ISSUE THREAD

**Issue by reckoner** [microsoft/terminal#7676] opened 2020-09-18 21:27 UTC
# Description of the new feature/enhancement

Currently, it is *only* possible to rearrange open tabs with the mouse.  How about allowing 
these tabs to be rearranged by using only the keyboard?

**Comment by DHowett** [comment] 2020-09-18 22:51
Thanks for the request! This looks like a probable duplicate of #3593

**Closed by DHowett** 2020-09-18 22:51 UTC
Labels: Issue-Feature, Needs-Tag-Fix, Needs-Triage
