### ISSUE TITLE
'Open in Terminal' not appearing in Windows Explorer context menu

### ISSUE THREAD

**Issue by CodeGenStudio** [microsoft/terminal#16236] opened 2023-10-27 16:03 UTC
### Windows Terminal version

1.18.2822.0

### Windows build number

10.0.19045.3570

### Steps to reproduce

No steps, just install, uninstall, reinstall.

### Expected Behavior

Right clicking in any folder in Explorer should show 'Open in Terminal'

### Actual Behavior

I've installed Terminal from the MS Store as well as via the bundle in the releases page. However, the 'Open in Terminal' option does not appear in Explorer when I right click a folder. I've also install Terminal on another PC and it is showing up there, but not on my current PC.

I've tried following some tutorials to manually add it in regedit but they do not work. If someone can point out on how to go about adding the context menu to Explorer it would be much appreciated, as I can easily load projects into terminal without having to cd to it each time.

Thank you.

**Comment by CodeGenStudio** [comment] 2023-11-12 18:36
Hate to be that guy, but I assume this is being looked into during the next phase? (Based on the current tags)

**Comment by zadjii-msft** [comment] 2023-11-13 14:10
Nope. Backlog is for "things that we should get to eventually, but don't have in a particular milestone". I'm not even sure this is something that _we_ can fix, either. I must've missed the triage meeting where we stuck this on the backlog. 

There've been threads about this in the past, where for some reason, the Store & file explorer seem to lose the registration for our shell context menus. It's been terribly unreliable. 

There's a very dumb question: have you restarted since re-installing the Terminal/? Explorer is weird about context menu entries sometimes. I think it caches the context menu entries. (`taskkill /f /im explorer.exe && explorer.exe` might also work without a full reboot)

Other things that might be relevant:
* Right clicking on the directory _background_ is sorta busted on Windows 10. I believe you _need_ to right click on an actual file.
* Same thing with directly on drives (e.g. `c:\`)


If that all doesn't work, we might need you to send feedback using the Feedback Hub and the "Desktop Environment > Right-click context menu" category:
![image](https://github.com/microsoft/terminal/assets/18356694/db94bd30-8b6f-4b12-92b6-c564a049df2f)

If you "share" that feedback here, I can make sure it gets promoted internally

**Comment by CodeGenStudio** [comment] 2023-11-13 18:56
I actually did do a restart after re-installing, but that did not do anything. I will retry tho, including the `taskkill` command as well - if they don't solve this I'll submit a report via Feedback Hub. Either way, I'll make sure to provide an update. Preciate the support

**Comment by 3052** [comment] 2023-11-13 19:33
having same problem here. how is this still an issue? its literally one registry key. @zadjii-msft can you at least provide a REG file here so we can manually fix it?

**Comment by zadjii-msft** [comment] 2023-11-13 20:03
FWIW, we don't use a .reg file to install these shell extensions. We're leveraging the built-in support in MSIX packages for declaring your shell extensions. I honestly don't know how it gets hooked up from the manifest to the actual context menu. If I did, then it'd be pretty easy to write a script for us to look if we're still even registered

**Comment by 3052** [comment] 2023-11-13 20:07
OK you say that, but as you said YOU don't even know how it works, and you work for Microsoft. with all due respect that is embarrassing. is the registry key no longer an option? if so, an old working option is better than a fancy broken option.

**Comment by 3052** [comment] 2023-11-13 20:13
OK got it working. first DONT download the MsixBundle, it does stupid stuff with the installation. the terminal gets installed to some weird folder with extreme security settings. I cant mess with it even as an admin. instead just get the dumb zip file, like this:

<https://github.com/microsoft/terminal/releases/download/v1.18.2822.0/Microsoft.WindowsTerminal_1.18.2822.0_x64.zip>

extract to wherever, for example:

~~~
C:\terminal-1.18.2822.0
~~~

then save the below as INSTALL.REG:

~~~
Windows Registry Editor Version 5.00
[HKEY_CLASSES_ROOT\Directory\background\shell\terminal\command]
@="C:\\terminal-1.18.2822.0\\WindowsTerminal.exe"
~~~

done. Microsoft making stuff WAY harder than it needs to be.

**Comment by DHowett** [comment] 2023-11-13 21:32
Two notes about 3052's solution:

1. It will work for the MSIX version of Terminal if you change the path to `%LOCALAPPDATA%\Microsoft\WindowsApps\wt.exe`
2. You do not need to change the global `startingDirectory` setting if you add `-d "%V\."` to the commandline. That will reduce the impact of this change to only the launched terminal profile rather than all terminal profiles.

**Comment by 3052** [comment] 2023-11-13 23:17
@zadjii-msft are you new at this? why can you just attach a REG file, or paste in a reg format as I did? or  paste some powershell commands to modify the registry? you almost seem to be going out of your way to use the most inconvenient format

**Comment by DHowett** [comment] 2023-11-14 01:28
@3052 Please follow this repository's Code of Conduct.

**Comment by 3052** [comment] 2023-11-14 01:42
@DHowett was that really needed? the comment was deleted like an hour ago, for good reason. please dont make trouble where there is none.

**Comment by DHowett** [comment] 2023-11-14 01:47
> @DHowett was that really needed? the comment was deleted like an hour ago, for good reason. please dont make trouble where there is none.

Yes, it was. I received two e-mail notifications for two separate comments which have since been deleted. **I was willing to let the first one slide,** and I am only warning you for the second.

Deleting a comment doesn't really let you un-say whatever was in it.

**Comment by 3052** [comment] 2023-11-20 03:54
no feedback is needed here. this is a known and long standing issue thats not been fixed. bad bot.

**Comment by 3052** [comment] 2023-11-20 15:30
@zadjii-msft cant you just reproduce the issue yourself? if not, then it makes sense to request this information. my understanding is that this is a known and long standing issue, so we are well past the point of needing to verify that its valid and/or reproducible.

**Comment by zadjii-msft** [comment] 2023-11-20 17:09
I sure can't! Hence why I'm asking for help 😉

**Comment by 3052** [comment] 2023-11-20 18:08
@zadjii-msft Iooked through your previous comments in this thread, and I don't see anything to that effect. sorry if I missed it. so assuming that you CANNOT repro the issue, can you give more info about YOUR environment? what Windows are you on, what version/file of terminal did you download? nothing wrong in attacking the problem from both ends, but that can only happen if the people say "it works for me" also provide context.

**Comment by 3052** [comment] 2023-11-24 19:33
no feedback is needed. this is an easily reproducible problem

**Comment by CodeGenStudio** [comment] 2023-11-24 20:17
After trying all the suggested solutions it still does not work - HOWEVER, the context menu does appear when I right click a directory. Never noticed this until now so I'm not exactly sure which solution at least made this work, if it wasn't working before. 

Anyway this is much faster than cd manually, although right clicking in the empty space would be more ideal.

@3052 I understand your frustration but you don't have to be so rude. @zadjii-msft I didn't mean to start trouble, just couldn't find an issue regarding this mentioned previously. Appreciate all the support from you guys till now.

Let me know if you guys have any other suggestions.

**Comment by zadjii-msft** [comment] 2023-12-04 16:04
@3052 Since you're hitting this too, we could always use feedback from you as well. That would be better than posting comments and then deleting them to keep the thread alive. 

I firmly suspect that this is an OS-side bug, not something in the Terminal codebase. I further suspect that this is something that was fixed in Windows 11 (since I know there was quite a few bugfixes for the way File Explorer loaded shell extensions in 22000). However, the only way for us to be sure is with logs, that Feedback Hub would capture, that we can then share with the OS shell folks and have them investigate. 

> HOWEVER, the context menu does appear when I right click a directory

This SPECIFICALLY makes me think what you're seeing here is something like #10119. Honestly, we should probably just de-dupe this to that thread. 

<other notes>

* MSFT:18029514 got backported to Windows 10 in MSFT:29893761, in the 2021.04 C servicing release

**Comment by zadjii-msft** [comment] 2023-12-04 16:27
I'm not trying to confirm the issue - it's been plenty confirmed. I'm trying to gather diagnostics from users who are repro'ing this bug, so that our internal partners (who aren't reproing it) can try to investigate.

**Comment by 3052** [comment] 2023-12-04 16:41
I think time would be better spent in the other issue. its older and has more participants

**Comment by zadjii-msft** [comment] 2023-12-04 21:21
Yea, that seems sensible here. Let's merge the threads.

/dup #10119

**Closed as completed by zadjii-msft** 2023-12-04 21:21 UTC
Labels: Resolution-Duplicate, Issue-Bug, Product-Terminal, Priority-2, Culprit-Centennial

**Comment by danny-dang** [comment] 2024-07-28 12:18
I solved this by upgrading to Windows 11, and then download the new Terminal app from Appstore.

**Comment by AAUCrisp** [comment] 2024-11-20 14:38
> I solved this by upgrading to Windows 11, and then download the new Terminal app from Appstore.

I specifically "downgraded" from Windows 11 on my machine, because of **so many** things I disliked there.
I seem to be in the minority here, but Windows 11 is almost WinXP unstable, and generally feels sluggish for reasons I can't seem to figure out.
And no... my computer is not ancient (7800X3D, 7900XTX and 32GB 7200MT/s RAM, running off of a PCIe 4.0 M.2)


But yeah.
I have this context menu issue too.
Works when right-clicking folders, but doesn't when using "background click" context menu.

**Comment by NazmusSayad** [comment] 2026-02-20 21:39
I have this on the desktop canvas.. but not on the folder

<img width="620" height="764" alt="Image" src="https://github.com/user-attachments/assets/6f580815-7f39-4680-be09-160c1ce4dda9" />

<img width="710" height="722" alt="Image" src="https://github.com/user-attachments/assets/226c9743-6030-4e7a-a225-df2c51d3b4fd" />

**Comment by Danny-Devito-GB** [comment] 2026-08-08 22:42
Why has this issue been marked as closed?

I am still getting this issue
