### ISSUE TITLE
Sometimes, terminal is not responsive to mouse events

### ISSUE THREAD

**Issue by Vyber90** [microsoft/terminal#5642] opened 2020-04-29 10:14 UTC
Once I left the terminal opened for a while, I can notice that the terminal is not responsive to mouse events anymore, and the mouse pointer design keeps on _horizontal movement_ mode (the pointer with two arrows, one to the left, the other to the right).
The mouse is useless in any button of the terminal (since buttons to child windows or alert boxes), though they all work correctly (when key-stroking at least).
I do not think I could give any more details (reproduction, for example), and I did my best to explain the error itself, but if any of you guys think you actually need more information, I will give it to you as well and fast as possible.

**Comment by Vyber90** [comment] 2020-04-29 11:24
Update: the mouse pointer design is not always the _horizontal move_ one. It varies depending on the border you hover when entering the window (entering from sides will make the cursor a _horizontal moving_, while entering from below makes it a _vertical moving_ and entering from the status bar, over the window, will make it stay as an _arrow pointer_ unless there is a tab. In that case it will make it an _horizontal move_ cursor).

**Comment by zadjii-msft** [comment] 2020-04-29 12:35
@Vyber90 any chance you're using PowerToys?

**Comment by Vyber90** [comment] 2020-04-29 12:40
I use PowerToys, but I do not let it run in the background for performance reasons. Only for PowerRename.
My WT version is 0.11.1121.0

**Comment by ScatteredRay** [comment] 2020-05-06 20:45
I'm actually having the same and persistent problem right now. It is happening on a newly opened terminal, and persists even after opening. For me it's the vertical move drag mouse.

Afaik I am not using PowerToys. I'm running version 0.11.1191.0 distributed from the windows store.

**Comment by ScatteredRay** [comment] 2020-05-06 20:48
I guess an additional difference in my case is the entire terminal seems to be also un-responsive to keyboard input. I can drag the window from the title bar, but none of the title-bar buttons work, nor does right-clicking do anything.

**Comment by sqeezy** [comment] 2020-05-11 15:10
I have the same problem. The whole window doesn't respond to mouse actions other than dragging via the title bar. Closing power toys and restarting the terminal solves the problem.

**Comment by DHowett-MSFT** [comment] 2020-05-15 01:11
@ScatteredRay that sounds like #4448, actually. We're working with the input team to track that one down.

@Vyber90 even though you're not running PowerToys constantly, i'd be interested to see if upgrading it to >=0.17 helps you.

**Comment by Vyber90** [comment] 2020-05-15 09:25
@DHowett-MSFT I just observed that, if I do not use PowerToys at all, the Terminal's window works correctly as far as I am concerned. With PT 0.17 it works properly too.

By the way, I am that guy who sent you the diagnostics report about some keyboard problems in order to not make a whole new GitHub issue. Actually, it seems like there were mouse problems in the beginning, but now they got replaced by keyboard troubles.

**Comment by DHowett-MSFT** [comment] 2020-05-15 21:58
Thanks for that repro, by the way. The Windows team is, as you might imagine, busy with some conference stuff... but we'll be able to get to it soon.

Thanks for confirming about PT as well. Gonna close this one out as a duplicate of the other issue we're using to track "powertoys blows up terminal".

/dup #3325.

**Closed by DHowett-MSFT** 2020-05-15 21:58 UTC
Labels: Area-Input, Needs-Attention, Needs-Tag-Fix, Needs-Triage, Product-Terminal
