### ISSUE TITLE
Mouse scrolling is not working for fullscreen CLI apps

### ISSUE THREAD

**Issue by tomsri01** [microsoft/terminal#14431] opened 2022-11-23 19:29 UTC
### Windows Terminal version

1.15.2875.0

### Windows build number

10.0.22621 Build 22621

### Other Software

Ubuntu 20.04 WSL
GNU bash, version 5.0.17(1)-release (x86_64-pc-linux-gnu)
xterm-256color (Also tried screen-256color)
less 551 (GNU regular expressions)

PowerShell 7.3.0
more command

### Steps to reproduce

Try to use touchpad or a regular mouse scroll to navigate within fullscreen apps like manpages or less.

### Expected Behavior

Mouse scroll should work to move app content when opening full screen apps (i.e when alternate buffer should be used) such as manpages and less.

### Actual Behavior

Mouse scroll does not work when using full screen app like manpages and less but works fine for VIM

Side note scrolling works as intended with VS Codes terminal so I doubt there is anything wrong with the shell configs..

**Comment by DHowett** [comment] 2022-11-23 21:18
Thanks for filing! I bet this is because we don't enable "Alternate(-screen) scroll mode" by default.

If it works in vim, but not in less/man (which uses less)... I'm going to call it a /duplicate of #13187!

**Closed by DHowett** 2022-11-23 21:18 UTC
Labels: Issue-Bug, Needs-Triage

**Comment by tomsri01** [comment] 2022-11-29 01:24
> Thanks for filing! I bet this is because we don't enable "Alternate(-screen) scroll mode" by default.
> 
> If it works in vim, but not in less/man (which uses less)... I'm going to call it a /duplicate of #13187!

How is alternate scroll enabled if it is not on by default?
