### ISSUE TITLE
Crash opening new cmd.exe tab and closing by typing exit + ENTER

### ISSUE THREAD

**Issue by larsch** [microsoft/terminal#3801] opened 2019-12-02 13:43 UTC
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18362.295]
Windows Terminal version (if applicable):  0.7.3291.0
```

# Steps to reproduce

1. With blank profile, change default shell to cmd.exe
2. Start Terminal
3. Create new tab (Ctrl+Shift+T)
4. Type `exit`, press ENTER 

# Expected behavior

Tab closes, leaving the original tab open.

# Actual behavior

Terminal disappears, closing all tabs.

# Additional info

- Pressing Ctrl+Shift+W closes the tab without crash.
- I can't reproduce with PowerShell as default shell
- I can't reproduce on another PC running Microsoft Windows [Version 10.0.18362.476] (I do not know that the triggering difference is).
- Creating a new profile with `"commandline": "cmd.exe /c dir c:\\",` or `"commandline": "cmd.exe /k exit"` also often crashes Terminal.
- Creating a profile with another executable, e.g. `"commandline": "ls c:\\temp"` does not appear to crash Terminal. So it seems related to `cmd.exe`.

**Comment by zadjii-msft** [comment] 2019-12-02 14:10
I think I have an idea of what's causing this, though the quickest way for me to be sure is if you could file feedback with the Feedback Hub app, so I can get a stack trace and verify.

/feedback

Thanks!

**Comment by larsch** [comment] 2019-12-02 14:35
I have attempted to submit issue via Feedback Hub.

**Comment by zadjii-msft** [comment] 2019-12-02 14:41
@larsch can you make sure to click on "Share my feedback" and _paste the link here_ so I can actually look it up? Thanks :)

**Comment by larsch** [comment] 2019-12-02 14:52
https://aka.ms/AA6q5mw

**Comment by zadjii-msft** [comment] 2019-12-02 21:21
(It was mentioned in triage that this might have something to do with us taking a weak ref to a `TermControl` and when the control goes away, we don't revoke our event handlers correctly. I don't totally remember, but I don't think that note was added here, so I'm adding what I can)

**Comment by mwidmann** [comment] 2019-12-05 07:43
As #3829 could be related, here's my Feedback https://github.com/microsoft/terminal/issues/3829#issuecomment-562008244

**Comment by DHowett-MSFT** [comment] 2019-12-05 20:54
This looks like a /dupe of #3776.

**Closed by DHowett-MSFT** 2019-12-05 20:54 UTC
Labels: Needs-Attention, Needs-Tag-Fix, Needs-Triage
