### ISSUE TITLE
Scroll with Touchpad 

### ISSUE THREAD

**Issue by massgh** [microsoft/terminal#3888] opened 2019-12-09 05:02 UTC
# TouchPad Scrolling in Terminal
You have keybinding **Ctrl+Shift+Up/Down** for scrolling up/down through terminal. What if we can scroll using TouchPad like we do in other applications. How to bind a swipe gesture of TouchPad to scroll through terminal?

# Proposed technical implementation details (optional)

**Comment by DHowett-MSFT** [comment] 2019-12-09 05:17
You're supposed to be able to. You are hitting a /dupe of #979.

**Closed by DHowett-MSFT** 2019-12-09 05:17 UTC
Labels: Issue-Feature, Needs-Tag-Fix, Needs-Triage
