### ISSUE TITLE
Authentication failed to Azure for Azure Cloud Shell

### ISSUE THREAD

**Issue by sakaldeepyadav** [microsoft/terminal#6038] opened 2020-05-20 14:06 UTC
Authentication failed to Azure Cloud Shell on Windows Terminal. I have tried different accounts. I am able to authenticate using the same credentials on normal PowerShell but it fails on here as below. 
![image](https://user-images.githubusercontent.com/34697487/82455639-1162e380-9aab-11ea-8b1b-ba86dac60659.png)

# Environment

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Windows Terminal version (if applicable):

Any other software?
```

# Steps to reproduce

# Expected behavior

# Actual behavior

**Comment by johnem-msft** [comment] 2020-05-20 19:30
I'm seeing this too ... but when I perform a task like: az account list I get output making think that it is really connected .... (or is this just cach'd info?)

**Comment by sakaldeepyadav** [comment] 2020-05-20 19:56
az account list does give output but if you run az vm list then you won't get anything so it giving cached info.

Tried authenticating many time but no luck.

**Comment by DHowett** [comment] 2020-05-21 01:10
Thanks for reporting this! It looks like this has the same root cause as #2371 (we're not handling one of the azure shell messages properly), so I'm going to close it as a duplicate.

/dup #2371.

**Closed by DHowett** 2020-05-21 01:10 UTC
Labels: Needs-Tag-Fix, Needs-Triage
