### ISSUE TITLE
Document how to contribute translation fixes

### ISSUE THREAD

**Issue by Vampire** [microsoft/terminal#15288] opened 2023-05-04 14:22 UTC
It is unclear how to contribute translation fixes.
In the repository it seems only the English resources are present.
So one could of course open an issue with the suggested change.
But at least it would be nice to somewhere see the localized strings in batch instead of just accidentally stumbling over a strange translation.
For example if you see something that looks strange, it would be good to see what the resource key is to see the original text to better understand what the proper translation would be.

And if it is not possible to access those translation resources, it would at least be nice to have this documented somewhere like e.g. in `CONTRIBUTING.md`.

**Comment by zadjii-msft** [comment] 2023-05-04 15:35
Ah. How I wish that were an easy question.

We straight up don't even know if we can accept community contributions to our translations currently. This comment: https://github.com/microsoft/terminal/issues/10667#issuecomment-1095579029 has the most up to date thoughts on the matter. 

If we do figure out a way to accept them, you can bet that we'll document it. But for the time being, I'm gonna close this as a dupe of that thread, for "figure out how to enable community translation fixes" 😄

/dup #10667

**Closed** 2023-05-04 15:35 UTC
Labels: Issue-Docs, Needs-Triage, Needs-Tag-Fix
