### ISSUE TITLE
Automatic dark/light theme switching according to OS

### ISSUE THREAD

**Issue by xmha97** [microsoft/terminal#6491] opened 2020-06-13 14:34 UTC
Hello,
Please add below feature:
- Automatic dark/light theme switching according to OS

In VSCode I can enable this feature using:
```
window.autoDetectColorScheme
```

![image](https://user-images.githubusercontent.com/23485114/84571001-fa5f9a80-ada5-11ea-9cd7-dfd8cbe2f1c3.png)

Idea for Windows Terminal:
![image](https://user-images.githubusercontent.com/23485114/84571393-17956880-ada8-11ea-8ec5-4b94c1659324.png)

**Comment by j4james** [comment] 2020-06-13 16:15
I think this is a duplicate of #1230.

**Comment by xmha97** [comment] 2020-06-13 18:02
> 
> 
> I think this is a duplicate of #1230.

No, My issue isn't about a bug. It is about a new feature.

**Comment by greg904** [comment] 2020-06-13 18:06
If you set "theme" in the config file to "system", it's supposed to work, but right now I think it doesn't work because of that bug.

**Comment by DHowett** [comment] 2020-06-13 18:08
So, this needs #1230 to work properly but it _isn’t_ 1230 alone. There’s also a request that the `colorScheme` be theme switchable :)

**Comment by j4james** [comment] 2020-06-13 18:22
Ah, OK. I get it now. That's a neat idea. But do you not then need some way to specify your preferred light color scheme (or vice versa)? Or does it auto detect it based on the name?

**Comment by DHowett** [comment] 2020-06-13 18:26
Yeah, that’s a good question :) Probably warrants at least a mini-spec. There’s also a request for focused/unfocused configuration, so I am a bit concerned about adding another dimension to the config matrix.

**Comment by cscorley** [comment] 2020-06-14 00:15
The VS Code implementation in the example has up to four "colorScheme" specifications:

![image](https://user-images.githubusercontent.com/112752/84581715-4ca6b880-adb2-11ea-9220-bfebb7aa4c78.png)

It is a bit verbose, but is much more flexible than requiring a scheme to define both a dark and a light (or high contrast!) variant.  For example, I like Dracula at night but it does not define a light variant, so I use Quiet Light during the day.

**Comment by mateuszdrab** [comment] 2020-06-24 14:43
Is there a reason why the terminal's title bar does not inherit the Windows accent color where all the other windows do?

Guess this is due to the fact that it's some custom code handling the title bar rendering due to tabs.

**Comment by TBBle** [comment] 2020-06-24 16:10
Title Bar colouring is also what I think @DHowett was referring to earlier, probably #4862

**Comment by mateuszdrab** [comment] 2020-06-24 17:09
You know what even be better? Running an elevated session within your existing terminal window 😄

That one might be difficult to achieve technically due to the various isolations at OS level when it comes to handing admin privileges. It would however, be of great use to me as I normally need one elevated and one non elevated session of powershell.

**Comment by DHowett** [comment] 2020-06-24 17:10
Yeah, let’s not pollute this request with the discussion of mixed elevation, which you can absolutely find a place for elsewhere in our issue tracker.

**Comment by ChristAlbert** [comment] 2020-08-25 20:11
Isn't this a duplicate of  #4066?

**Comment by zadjii-msft** [comment] 2020-08-25 20:21
@ChristAlbert good find! It totally is. Thanks for digging that out of our backlog!

/dup #4066

**Closed** 2020-08-25 20:22 UTC
Labels: Area-User Interface, Help Wanted, Issue-Feature, Product-Terminal

**Comment by electronic-dk** [comment] 2020-08-25 20:27
@zadjii-msft I thought #4066 spoke about the color profile specifically, while this ticket is about the terminal theme itself (dynamic change without having to restart the terminal). Are these 2 aspects planned to be implemented in scope of one ticket?

**Comment by zadjii-msft** [comment] 2020-08-25 20:30
From the way I understand it:
* #1230 covers: "When I set the `theme` to `system`, the `RequestedTheme` of the Terminal should update when I change my system theme"
* #4066 is "I want to change color scheme based off the current `RequestedTheme` of the Terminal application"

**Comment by b-hayes** [comment] 2021-03-22 22:37
Waiting for this feature. Currently, every time I change to dark/light mode I have to open my terminal config file and comment/uncomment my light colour scheme manually. And yes you would need to set a preferred light scheme, every other application I use does it a similar way.
The smart ones just remember what colour scheme was active last time you were in light/dark mode.

**Comment by TBBle** [comment] 2021-03-23 08:10
@b-hayes Yup, that's being tracked in #4066.

**Comment by Msouza91** [comment] 2023-12-05 11:18
> Waiting for this feature. Currently, every time I change to dark/light mode I have to open my terminal config file and comment/uncomment my light colour scheme manually. And yes you would need to set a preferred light scheme, every other application I use does it a similar way. The smart ones just remember what colour scheme was active last time you were in light/dark mode.

I've setup a cron job using sed and some tricks to change between a light and dark theme, the job runs every 29 minutes and checks if the sun is up using hdate.
https://pastebin.com/LPc2Fe0h

It is a bit hacky, but works, I've setup the terminal to start up with user login.

**Comment by zadjii-msft** [comment] 2023-12-05 12:36
Or, y'know, this feature was added to the Terminal a couple releases back: https://learn.microsoft.com/en-us/windows/terminal/customize-settings/profile-appearance#color-scheme

```json
"colorScheme":
{
    "light": "One Half Light",
    "dark": "One Half Dark",
},
```

**Comment by Msouza91** [comment] 2023-12-05 20:59
> Or, y'know, this feature was added to the Terminal a couple releases back: https://learn.microsoft.com/en-us/windows/terminal/customize-settings/profile-appearance#color-scheme
> 
> ```json
> "colorScheme":
> {
>     "light": "One Half Light",
>     "dark": "One Half Dark",
> },
> ```

I didn't look too much into it, I couldn't be arsed to read the whole thread so I made a quick hack for it, thanks for showing me this. Now it syncs perfectly with Night Light settings and Auto Dark Mode.

**Comment by Kellen-Stuart** [comment] 2024-04-27 15:43
I don't know why but mine just stays on dark no matter what. 

```
"profiles": 
    {
        "defaults": 
        {
            "colorScheme": {
                "dark": "Ayu Dark",
                "light": "Ayu Light"
            },
            "font": 
            {
                "size": 16.0
            }
        },
        "list": 
        ...
```

**Comment by adityamwagh** [comment] 2024-05-11 18:00
@Kellen-Stuart We need to see your complete config file to point out the issue.

**Comment by zadjii-msft** [comment] 2024-05-13 11:33
I'm guessing it's your `theme` setting. That needs to be set to `default` (or, "use windows theme") to allow the _app_ to switch between themes, so that the scheme can match the app's _theme_.
