### ISSUE TITLE
Bug Report: Unintended text updating

### ISSUE THREAD

**Issue by RosalesJ** [microsoft/terminal#2060] opened 2019-07-22 15:28 UTC
# Environment

```none
Windows build number: 18362.239
Windows Terminal version: Latest from the microsoft store
```

# Steps to reproduce
Open an application like ranger and browse around.

# Expected behavior
Only the intended text updates.

# Actual behavior
The intended area updates, but other areas update too garbling the UI.

### Ranger:
![](https://user-images.githubusercontent.com/17154302/61557588-9ec04c00-aa32-11e9-9b91-121f911e5734.gif)

### Emacs:
![](https://user-images.githubusercontent.com/17154302/61557851-4f2e5000-aa33-11e9-9dd9-4ec77a5cb756.gif)

**Comment by zadjii-msft** [comment] 2019-07-22 19:31
What distro are you running, and could you share the output of `infocmp`?

**Comment by RosalesJ** [comment] 2019-07-24 12:58
I'm running Debian. Here's the ouptut of ```infocmp```: [output.txt](https://github.com/microsoft/terminal/files/3426851/output.txt).
At the time the issue was with the terminal only, it worked fine on both ```wsl.exe``` and ```conhost.exe```. However when I tried to replicate the issue again today I'm no longer able to replicate it on windows temrinal. Maybe a restart had something to do with it.

**Comment by johnmorrisbeck** [comment] 2019-07-26 14:20
I've had some issues with emacs in the last 24 hours. I had three erc buffers open and my terminal rendering was way off. It printed a newline character but jumped to the beginning of the terminal emulator on the left side and not to the middle of the buffer.

My guess is that terminal/conhost2 has a special case in which a newline will always jump to the beginning of the terminal emmulator line and not to the beginning of the multiplexed terminal line.

In terms of newline windows terminal should always default to the ansi compliant way of moving the cursor and printing.

Furthermore, some programs have different issues with ansi-compliance. It is important to prioritize them from most used to least.

Vim and emacs are some of these. They need the terminal to be rendered absolutely properly because of the insane style of text editing they both do.

The best program to look to in terms of ansi compliant terminals is probably tmux. tmux it not a terminal emmulator per se but it gets everything right in terms of how it renders things.

**Comment by miniksa** [comment] 2019-08-01 21:49
The OP issue is no longer reproducing. Closing.

**Closed** 2019-08-01 21:49 UTC
Labels: Area-VT, Issue-Bug, Product-Conhost, Resolution-No-Repro

**Comment by zadjii-msft** [comment] 2019-08-01 21:53
For the record, there is another issue tracking the emacs issue - #1474 is _probably_ the issue you're describing.
