### ISSUE TITLE
C# Console CursorTop is not calculated as same as native windows cmd

### ISSUE THREAD

**Issue by MohammadMD1383** [microsoft/terminal#10063] opened 2021-05-09 18:47 UTC
### Windows Terminal version (or Windows build number)

Windows10 - 20H2 - 19042.964

### Steps to reproduce

1. write this program in c#
```csharp
using System;
using static System.Console;

namespace ConsoleApp
{
	internal static class Program
	{
		public static void Main()
		{
			Write("Hello World");
			ClearLine(CursorTop);
			SetCursorPosition(0, CursorTop - 1); // exception here
		}

		private static void ClearLine(int lineNumber)
		{
			SetCursorPosition(0, lineNumber);
			Write("".PadRight(WindowWidth));
		}
	}
}
```
2. compile
3. run it from windows terminal powershell using `.\ConsoleApp.exe`

### Expected Behavior

it should fill the current line with white space and then **because the white spaces count is equal to windows width, after the last white space the cursor should move to next line**
then by setting cursor top to `cursor top - 1` it shouldn't throw any exception.

I tested this in `cmd` and `powershell` and there was no problem.

### Actual Behavior

after last white space cursor doesn't go to next line so it throws exception.
![image](https://user-images.githubusercontent.com/69088224/117583427-61074880-b11c-11eb-9385-5d7bef9ee00d.png)

**Comment by LuanVSO** [comment] 2021-05-09 21:27
> then by setting cursor top to cursor top - 1 it shouldn't throw any exception.

it should if cursortop ==0
reflow only enters in action if you print WindowWidth+1

**Comment by MohammadMD1383** [comment] 2021-05-10 05:45
@LuanVSO I tested in cmd and powershell _(their own window)_ and after printing space in count of `windowWidth` the cursor moved to next line

**Comment by LuanVSO** [comment] 2021-05-10 19:03
oh, now i remember. this is the exact wrap bug, yeah there's a duplicate of this issue around here somewhere.

**Comment by j4james** [comment] 2021-05-10 20:22
This is probably because Windows Terminal has `ENABLE_VIRTUAL_TERMINAL_PROCESSING` on by default, while conhost has it disabled. So in Windows Terminal you get the delayed wrap effect expected by VT applications, while in conhost the wrap will occur as soon as a character is output in the last column.

**Comment by DHowett** [comment] 2021-05-13 19:59
Yep, James has the right of it here. For an application that relies on specific console modes being set (sorry- line wrapping behavior unfortunately requires specific modes) our recommendation is that it set those modes on startup.

**Closed by DHowett** 2021-05-13 19:59 UTC
Labels: Issue-Question, Needs-Tag-Fix, Needs-Triage, Product-Terminal

**Comment by DHowett** [comment] 2021-05-13 20:01
*OH*, And there's a great discussion about this in /dup #8312
