### ISSUE TITLE
Terminal crushes when opening on second screen

### ISSUE THREAD

**Issue by IlanVivanco** [microsoft/terminal#3703] opened 2019-11-26 15:28 UTC
The app is working fine on the main screen, but as soon as I move it to the second screen is crushes suddenly.

# Environment

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Windows Terminal version (if applicable):

Any other software?
```

# Steps to reproduce

# Expected behavior

# Actual behavior

**Comment by arjunbasnet** [comment] 2019-11-26 16:29
Similar issue with
Windows Terminal (Preview)
Version 0.6.2951

**Comment by IlanVivanco** [comment] 2019-11-26 16:38
> Similar issue with
> Windows Terminal (Preview)
> Version 0.6.2951

Yes, I forgot to mention it, using the same Terminal version as @arjunbasnet.
Windows 10 Home 1903 Version
Build 18362.476

**Comment by j4james** [comment] 2019-11-26 16:41
Probably a duplicate of #3303.

**Comment by zadjii-msft** [comment] 2019-11-26 16:41
Thanks for the report! This is actually something that's already being tracked by another issue:

/dup #3303

Please make sure to search when filing new issues. Thanks!

**Closed by zadjii-msft** 2019-11-26 16:42 UTC
Labels: Needs-Tag-Fix, Needs-Triage
