### ISSUE TITLE
focusMode option for launchMode setting

### ISSUE THREAD

**Issue by Memphizzz** [microsoft/terminal#7825] opened 2020-10-04 23:35 UTC
# Description of the new feature/enhancement
Besides having maximized and fullscreen, would it be possible to please also have the option to start the terminal in FocusMode?

# Proposed technical implementation details (optional)

**Comment by zadjii-msft** [comment] 2020-10-05 08:53
Yes yes yes. I could have swore I already filed this one - this is something I've been wanting to do. Thanks!

**Comment by Don-Vito** [comment] 2020-10-10 04:40
Duplicate of https://github.com/microsoft/terminal/issues/7124

**Closed** 2020-10-14 22:19 UTC
Labels: Area-Settings, In-PR, Issue-Task, Product-Terminal
