### ISSUE TITLE
Tabs are 1 pixels short of the top of the window in full screen on a 2 screen setup

### ISSUE THREAD

**Issue by lukaseder** [microsoft/terminal#9000] opened 2021-02-02 10:54 UTC
# Environment

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Microsoft Windows [Version 10.0.19042.746]

Windows Terminal version (if applicable):
1.5.10271.0

Any other software?
Running git-bash in terminal, not sure if this is relevant
```

# Steps to reproduce

Use a 2-screen setup similar to the one I've shown below. Put terminal in full screen mode like any other application

# Expected behavior

I can move my mouse to the top of the screen and still activate a tab

# Actual behavior

The tabs are just 1 px short of the top of the window (and thus of the screen), so I have to aim better, which is annoying. Here's a screen capture:

![tabs](https://user-images.githubusercontent.com/734593/106589990-f1962180-654c-11eb-8619-c766af2ebe89.gif)

Perhaps, this has something to do with my particular 2-screen setup, which you can see here:

**Screen 1**

![image](https://user-images.githubusercontent.com/734593/106590140-168a9480-654d-11eb-9217-7304f4f5e85a.png)

**Screen 2**

![image](https://user-images.githubusercontent.com/734593/106590192-22765680-654d-11eb-9e35-06018c3b21ed.png)

Other tabbed applications, like Google Chrome, don't suffer from this. Also, when I use the terminal on my main screen in this setup, in full screen mode, then I don't have this problem.

**Comment by zadjii-msft** [comment] 2021-02-02 12:33
Yea, that looks like a bug to me. Thanks!

**Comment by Don-Vito** [comment] 2021-02-02 19:58
Sounds very similar to https://github.com/microsoft/terminal/issues/7422 and https://github.com/microsoft/terminal/issues/8363

**Comment by DHowett** [comment] 2021-02-04 01:39
In fact, I'd call it a /dupe of #7422. Thanks!

**Closed by DHowett** 2021-02-04 01:39 UTC
Labels: Area-User Interface, Help Wanted, Issue-Bug, Needs-Triage, Priority-3, Product-Terminal
