### ISSUE TITLE
Equals Sign Not Rendering in Powershell Core Tabs

### ISSUE THREAD

**Issue by iUnknwn** [microsoft/terminal#3573] opened 2019-11-14 01:18 UTC
# Environment

```none
Windows build number: 10.0.18363.0
Windows Terminal version (if applicable): 0.6.2951.0

Any other software? PowerShell 6. 

PSVersionTable:
Name                           Value
----                           -----
PSVersion                      6.2.3
PSEdition                      Core
GitCommitId                    6.2.3
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```

# Steps to reproduce
The equals sign does not appear in certain operations in PowerShell core windows.

Typing: `$a = 4` results in this:
![image](https://user-images.githubusercontent.com/1129122/68818151-e8afec00-0638-11ea-925c-c9d7b14aad08.png)

They render normally as part of strings:
![image](https://user-images.githubusercontent.com/1129122/68818203-15640380-0639-11ea-9205-a46e6a285ae8.png)

# Expected behavior
The equals sign renders normally, as it does on non-pwsh Windows.

The same input in the Powershell tab works normally:
![image](https://user-images.githubusercontent.com/1129122/68818233-30cf0e80-0639-11ea-8b39-6d8a11d90f16.png)

Additional Notes:
Changing the font settings appeared to have no effect. For reference, here is the entry for Powershell Core in my settings.json:

```
        {
            "guid": "{574e775e-4f2a-5b96-ac1e-a2962a402336}",
            "hidden": false,
            "name": "PowerShell Core",
            "source": "Windows.Terminal.PowershellCore",
            "colorScheme": "Solarized Dark",
            "fontFace": "Cascadia Code",
            "fontSize": 10,
            "cursorShape": "bar"
        }
```

**Comment by DHowett-MSFT** [comment] 2019-11-14 01:57
This is, you might be puzzled to learn, a /dupe of #293 and #2054 (although instead of Light/brightWhite it's Dark/brightBlack)

**Closed by DHowett-MSFT** 2019-11-14 01:57 UTC
Labels: Needs-Tag-Fix, Needs-Triage
