### ISSUE TITLE
Windows 11 context menu

### ISSUE THREAD

**Issue by MuhammetEminCakir** [microsoft/terminal#13562] opened 2022-07-21 21:13 UTC
### Windows Terminal version

1.15.2002.0

### Windows build number

10.0.22622.436

### Steps to reproduce

1.First time right click to desktop

### Expected Behavior

Terminal option always visible in Windows 11 context menu

### Actual Behavior

When it is opened for the first time, 
Terminal option does not visible in Windows 11 context menu for dektop (it works properly for folders)

https://user-images.githubusercontent.com/64583157/180315031-39a122ac-6d06-4ee3-a741-928f5e75c970.mp4

(Blue mean: right click/ Yellow mean: left click)

**Comment by zadjii-msft** [comment] 2022-07-21 21:53
I'm guessing you have PowerToys installed? Which PowerToys version?

**Comment by MuhammetEminCakir** [comment] 2022-07-21 22:35
> I'm guessing you have PowerToys installed? Which PowerToys version?

Latest version 0.60.1

**Comment by BTCHSXR** [comment] 2022-07-22 07:55
I have a similar problem. When I right-click to desktop, the terminal option is always visible in Windows 11 context menu and it works in any anywhere ***but desktop***.

It looks like this.
![GIF 2022-7-22 15-37-05](https://user-images.githubusercontent.com/20433038/180390166-ba9b32b9-dbe1-4aab-bcb9-d824dbd252e2.gif)

+ The problem seems to appear after installing Windows update KB5015732.
+ This bug ***may not*** be caused by Windows Terminal because I'm using an older version 1.14.1963.0

**Comment by huohaodong** [comment] 2022-07-22 12:54
I saw a [previous discussion](https://github.com/microsoft/terminal/issues/13523) about this problem, it seems like this problem is caused by some new features of the latest [PowerToys](https://github.com/microsoft/PowerToys). However, I encountered the same problem **without** powertoys been installed. 

Windows Terminal does not appear in the context menu when I right click on the desktop for the first time, it will appear in the next few right clicks. However, after just a few seconds without right clicking the desktop, the 'Open in Terminal' option disappeared. This problem only occurs when the context menu is opened on the desktop.

- Windows 11 Build 22621.232
- Window Terminal Version 1.14.1862.0

**Comment by zadjii-msft** [comment] 2022-07-22 15:17
Yea ultimately, I suspect this is either: 
* #13523 for the powertoys related issue
* #11839 which was tracking an internal issue about context menu not always working for the desktop background. If you don't have PowerToys installed, then I suspect you're hitting a variant of this one. That was supposed to be fixed in OS builds >22598.200, but you never know. 

If you are hitting this, I'd recommend filing feedback using the Feedback Hub, under the "Desktop Environment > Right Click Context Menu" area.

![image](https://user-images.githubusercontent.com/18356694/179498580-8c24c5bf-b740-4bab-943a-a88ca40ffbfa.png)

I'm not sure there's much we can do to investigate here, but getting this to the team that owns the context menus might help the investigation. If you "Share" the `aka.ms` link to that feedback here, I can make sure to follow the internal bug that gets generated. Thanks!

**Closed by zadjii-msft** 2022-07-22 15:17 UTC
Labels: Issue-Bug, Needs-Triage, Needs-Attention, Needs-Tag-Fix

**Comment by jasonkrasavage** [comment] 2023-02-06 19:25
I'm confused why all of these issues (this one, [#11839](https://github.com/microsoft/terminal/issues/11839) , [#13523](https://github.com/microsoft/terminal/issues/13523) have been closed. Did this problem move internally, I think maybe I saw a note about that? 

I've already submitted feedback for this. But I have this issue with and without PowerToys and/or OneDrive installed etc. The problem is not intermittent and it's very repeatable. Fresh install of Windows OS Build 22000.1455 and Windows Terminal. You **_have_** to right click directly ON a folder to get the context menu to show, which is not the expected behavior here, right?

Like in Win10, we should be able to enter a folder, and click anywhere in the background of that folder to see the "Open in Terminal" context menu.

**Comment by icedterminal** [comment] 2023-04-09 10:16
Yeah this is still an issue. These shouldn't be closed or resolved.

I purchased a new motherboard and needed to reinstall Windows. Have lost access to Terminal from right clicking anywhere. It randomly disappeared. I have tried removing and reinstalling OneDrive, Terminal and PowerToys to no avail.

![image](https://user-images.githubusercontent.com/4755734/230767116-54bcd358-9555-4d9c-9a71-51db5ef0c616.png)

**Comment by guzelonur** [comment] 2024-01-23 13:47
I don't know if this is irrelevant but, I noticed when I right click to show context menu **for the first time**, AMD Adrenalin Software entry is not shown. However if I right click **again** (second time), AMD Adrenalin Software appears with this **next click**.

The behaviour is similar with Terminal issue in this thread, so it must be something related to Windows context menu entry initialaztion or its timing does matter?
