### ISSUE TITLE
Feature Request - Most Recently Used (MRU) Tabs

### ISSUE THREAD

**Issue by strickdd** [microsoft/terminal#2350] opened 2019-08-08 15:29 UTC
# Description of the new feature/enhancement

It would be nice to have the ctrl + tab and ctrl + shift + tab to cycle through most recently used (MRU) order. This option is available in almost all tabbed based products (except Chrome :( ). At the very least it is an option that can be enabled if not already the default behavior. 

If I have three tabs open and focus tab 2 then tab 0, pressing ctrl + tab should take me to tab 2. Pressing it again should take me back to tab 0. Holding ctrl and pressing tab twice should focus tab 1. (This is all assuming zero-based indexing of tabs as documented in the profiles.json file) Using the ctrl + shift + tab should focus the last (oldest) focused tab currently open.

# Proposed technical implementation details (optional)

I would imagine a circularly linked list may be appropriate.

**Comment by zadjii-msft** [comment] 2019-08-08 15:33
This is a dupe of #973

**Closed by zadjii-msft** 2019-08-08 15:33 UTC
Labels: Issue-Feature, Needs-Tag-Fix, Needs-Triage
