### ISSUE TITLE
Drop Down Windows Terminal

### ISSUE THREAD

**Issue by ABOhiccups** [microsoft/terminal#6344] opened 2020-06-04 03:49 UTC
Can you make Drop Down feature for Windows Terminal? (Similar to Drop Down Terminal on Linux that I'm using)

![Drop-Down Terminal](https://user-images.githubusercontent.com/17691106/83712883-c097d280-a5f4-11ea-8eb5-c2020ae87e1a.png)

**Comment by skyline75489** [comment] 2020-06-04 04:52
We have #653 for this.

**Comment by zadjii-msft** [comment] 2020-06-04 12:25
Yep, this is definitely a /dupe of #653.

**Closed by zadjii-msft** 2020-06-04 12:25 UTC
Labels: Issue-Feature, Needs-Tag-Fix, Needs-Triage
