### ISSUE TITLE
Window background is broken after resizing

### ISSUE THREAD

**Issue by Alvin-Seville** [microsoft/terminal#7225] opened 2020-08-08 07:50 UTC
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.19041.388]
Windows Terminal version (if applicable): 1.1.2021.0
```

# Steps to reproduce

- Open Windows Terminal.
- Open About window.
- Enlarge Windows Terminal window.
![image](https://user-images.githubusercontent.com/42812113/89705286-b27e6f00-d921-11ea-9b64-91df4e10255e.png)

# Expected behavior

Properly resized background.

# Actual behavior

Broken background.

**Comment by shashank333** [comment] 2020-08-08 12:00
hmm even i have the same issue

**Comment by DHowett** [comment] 2020-08-08 23:17
Thanks for the report! This is a /duplicate of #2380 and it has its roots in the UI toolkit we are using ☹️

**Closed by DHowett** 2020-08-08 23:17 UTC
Labels: Needs-Tag-Fix, Needs-Triage
