### ISSUE TITLE
Cannot handle linefeed correctly

### ISSUE THREAD

**Issue by hez2010** [microsoft/terminal#3338] opened 2019-10-26 03:41 UTC
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18362.418]
Windows Terminal version (if applicable): All
```

# Steps to reproduce

1. Write some characters with linefeed in the notepad, such as:
```
a
b
c
d
e
```

2. Copy them
3. Open Windows Terminal and launch WSL
```
wsl
```
4. use `cat` command to write into a text file:
```
cat > test.txt << EOF
```
5. Paste the copied characters into the terminal

# Expected behavior

```
PS C:\Users\hez20> wsl
hez2010@DESKTOP-CD2C52F:/mnt/c/Users/hez20$ cd ~
hez2010@DESKTOP-CD2C52F:~$ cat > test.txt << EOF
> a
> b
> c
> d
> e
> f
```

# Actual behavior
```
PS C:\Users\hez20> wsl
hez2010@DESKTOP-CD2C52F:/mnt/c/Users/hez20$ cd ~
hez2010@DESKTOP-CD2C52F:~$ cat > test.txt << EOF
> a
>
> b
>
> c
>
> d
>
> e
>
> f
```

Each linefeed was repeated twice.

**Comment by j4james** [comment] 2019-10-26 11:52
I think this is a duplicate of #1091.

**Comment by DHowett-MSFT** [comment] 2019-10-26 17:38
It absolutely is a /dupe of #1091. Thanks, @j4james!

**Closed by DHowett-MSFT** 2019-10-26 17:38 UTC
Labels: Needs-Tag-Fix, Needs-Triage
