### ISSUE TITLE
WT_VERSION Environment Variable

### ISSUE THREAD

**Issue by tracker1** [microsoft/terminal#6798] opened 2020-07-06 15:01 UTC
In addition to the WT_PROFILE_ID and WT_SESSION, would be nice to see a WT_VERSION environment variable as well... this could be used to allow some level of feature detection in order to allow some more advanced features without complex interrogation.

Such as with #204 when implemented, such as via [supports-hyperlinks](https://github.com/jamestalmage/supports-hyperlinks)

**Comment by zadjii-msft** [comment] 2020-07-06 15:16
This feels like the wrong solution to this problem IMO. When the Terminal does eventually get hyperlink support, it will come first through the Windows Console. In that case, both the console and the Terminal will support hyperlinks, but if people rely on the presence of `WT_VERSION`, then the console will incorrectly be detected as _not_ supporting hyperlinks.

**Comment by DHowett** [comment] 2020-07-06 17:04
Yeah, I'm going to NAK this one hard. It's also somewhat of a /duplicate of #1040 :smile:

**Closed by DHowett** 2020-07-06 17:04 UTC
Labels: Issue-Feature, Issue-Question, Needs-Tag-Fix, Needs-Triage, Product-Terminal
