### ISSUE TITLE
Fluent buttons, menus and Right-click context menu

### ISSUE THREAD

**Issue by SpiderFlashMello61319** [microsoft/terminal#5615] opened 2020-04-28 11:10 UTC
# Description of the new feature/enhancement 
1. Right-click should open a fluent context menu with various options like `Copy`, `Paste`, `Select all`, `New tab`, `Settings`, etc., instead of just pasting as a context menu has various other options too.
2. The profile-choosing dropdown button and new tab button don't have `RevealBrush`. The profiles dropdown menu does not have `AcrylicBrush` and `RevealBrush` applied.

# Proposed technical implementation details  
Simple XAML is enough for `Acrylic` and `Reveal` brushes. A fluent context menu has to be created with options mentioned above (options may vary).

**Comment by mdtauk** [comment] 2020-04-28 11:16
This context menu should also include the pane commands
"Split Vertically" and "Split Horizontally"

**Comment by zadjii-msft** [comment] 2020-04-28 12:44
Largely, this issue is a duplicate of #3337, so I'll direct discussion to that thread. Thanks!

/dup #3337

**Closed by zadjii-msft** 2020-04-28 12:44 UTC
Labels: Issue-Feature, Needs-Tag-Fix, Needs-Triage
