### ISSUE TITLE
"Open in Windows Terminal" only works in context menus of Explorer directory entries, but not in Explorer background and desktop context menus

### ISSUE THREAD

**Issue by necrosisy** [microsoft/terminal#14979] opened 2023-03-11 06:27 UTC
### Windows Terminal version

1.16.10261.0

### Windows build number

10.0.19044.0

### Steps to reproduce

1. Install Windows Terminal in Store
2. Check whether the context menus at Directory Entry, Desktop, Background are displayed normally
3. Found that "Open in Windows Terminal" can only be displayed normally in Directory Entry

### Expected Behavior

"Open in Windows Terminal" should also show in Desktop and Background

### Actual Behavior

![image](https://user-images.githubusercontent.com/122260380/224468931-38121031-ed1d-4729-a61b-ddabfd858585.png)
![image](https://user-images.githubusercontent.com/122260380/224468946-1bc2483f-73ec-41ed-8a0e-9548108b4ef1.png)
![image](https://user-images.githubusercontent.com/122260380/224468949-fe20b6f3-e5e3-4932-b76f-59a7e1dd251b.png)

"Open in Windows Terminal" is only displayed in the context menu of directory entries

**Comment by necrosisy** [comment] 2023-03-11 06:30
I also checked the related registry entries, hope that helps

![image](https://user-images.githubusercontent.com/122260380/224469041-bc4a530c-38e1-410b-ae32-66f7f18f8f89.png)
![image](https://user-images.githubusercontent.com/122260380/224469050-a05cd032-cb21-440c-80d1-15a149805932.png)
![image](https://user-images.githubusercontent.com/122260380/224469057-d22ed9c7-3bd1-4697-8eee-ab851d8407bf.png)
![image](https://user-images.githubusercontent.com/122260380/224469072-34d30c1e-9e66-4e3d-b83d-6719a77bd11a.png)

**Comment by necrosisy** [comment] 2023-03-11 06:34
I guess it has something to do with the registry value under the `HKEY_CLASSES_ROOT\PackagedCom\ClassIndex\{9F156763-7844-4DC4-B2B1-901F640F5155}` path

**Comment by necrosisy** [comment] 2023-03-11 06:50
#10119

**Comment by zadjii-msft** [comment] 2023-03-12 12:05
Thanks for the report! I'm pretty sure this is a dupe of one of 

* #10694
* #10496
* #10119

though, I need to go do some diligence and de-dupe those too. Thanks!

/dup #10694 #10496 #10119

**Closed** 2023-03-12 12:05 UTC
Labels: Issue-Bug, Needs-Triage

**Comment by knownbyfew** [comment] 2024-01-26 17:56
Did you ever manage to fix it?
