### ISSUE TITLE
Drag-Drop file not working with initial/default tab

### ISSUE THREAD

**Issue by deoradh** [microsoft/terminal#4654] opened 2020-02-20 05:44 UTC
# Environment

```none
Windows build number: 10.0.18363.0
Windows Terminal version (if applicable): 0.9.433.0

Any other software? No
```

# Steps to reproduce

1. Start WT, allow first tab to auto-create
2. Attempt to drag file to first tab, note inability to drop, and no "Copy as path" tooltip
3. Create new tab
4. Attempt to drag file to new tab, note "Copy as path" works
5. Delete first tab
6. Create new tab of same profile as the default
7. Attempt to drag file to each tab, note "Copy as path" works for each

# Expected behavior

"Copy as path" works for all tabs, including the default

# Actual behavior

"Copy as path" appears to not work for the initial, default tab.  This does not appear to be a matter of the invoked host (eg, cmd vs PS Core), but behaves like the default tab is simply not registered as a drop target.

**Comment by DHowett-MSFT** [comment] 2020-02-20 18:23
I can't reproduce this, even relaunching terminal 10 times. Is there anything else unusual about your environment?

**Comment by deoradh** [comment] 2020-02-20 18:32
Nope.. I'm not even on any insider rings.  I was dragging the same file each time.  It was repeatable on my machine across restarts of terminal.

It's not reproducing this morning.

One change since last night:  My default profile is Powershell Preview.  When it was reproducing I was on preview 3.  Since that time I updated to rc2 and juggled some profiles around while I looked at the generator support (nice, btw.. but could use some docs for the user).  

Perhaps that had an effect.

**Comment by zadjii-msft** [comment] 2020-02-20 20:13
@deoradh Any chance what you're seeing is actually #4567? That might explain why it seems so random.

@DHowett-MSFT I'm considering pulling #2606 into 1.0 if that's the case. #4567 seems like a much easier/trivial way to hit that bug, and might be worth pulling forward. Thoughts?

**Comment by DHowett-MSFT** [comment] 2020-02-20 20:16
Oh! Great pull!

**Comment by deoradh** [comment] 2020-02-20 20:29
@zadjii-msft -- It's uncertain.

I can repro #2606/#4567, but I cannot state that this was the same.  It *is* possible:  My PS startup spews a bunch of text at the start, so I may have found myself dragging to the bottom of the window, where the cursor was, and so by chance never seeing what happens if I was in the upper portion of the pane.  But it doesn't explain the impression that this was resolving for all subsequent tabs opened.

But at this point, it looks like I can only give the impression.  I can't repro it anymore except for the known bug. (Count this as a vote for pulling forward, anyway.)

**Comment by DHowett-MSFT** [comment] 2020-03-18 00:17
@deoradh thanks again -- I know we're not a hundred percent sure if it's the same bug, but for now I'm going to track them together. It seems like we _the platform_ (not the Terminal, unfortunately) may have a hit-testing issue in general.

Closing this one in favor of talking about it in #2606. Since 2606 may require changes to Windows, it might not make it for 1.0 -- we're only as agile as our slowest component :smile:

**Closed by DHowett-MSFT** 2020-03-18 00:17 UTC
Labels: Area-User Interface, Needs-Attention, Needs-Tag-Fix, Needs-Triage, Product-Terminal
