### ISSUE TITLE
apt install output is not being pushed into scroll back in windows terminal

### ISSUE THREAD

**Issue by LuanVSO** [microsoft/terminal#7687] opened 2020-09-20 19:33 UTC
# Environment

```none
Windows build number: [10.0.19042.508]
Windows Terminal version (if applicable):1.3.2382.0

Any other software?
wsl pengwin apt zsh
```

# Steps to reproduce

1. sudo apt install gcc

# Expected behavior

output is pushed to scroll back normally
# Actual behavior

when the `Progress: [ 1%] [#...` shows up at the bottom of the viewport, lines at the top stop being pushed into scroll back

maybe similar to https://github.com/microsoft/terminal/issues/111#issuecomment-406360334

**Comment by DHowett** [comment] 2020-09-20 19:54
I believe apt uses a scrolling region to render its progress bar; this is a likely /dupe of #3673.

**Closed by DHowett** 2020-09-20 19:54 UTC
Labels: Needs-Tag-Fix, Needs-Triage
