### ISSUE TITLE
Configuration file on network share (homedrive)

### ISSUE THREAD

**Issue by ThiloL** [microsoft/terminal#8112] opened 2020-10-30 13:25 UTC
# Description of the new feature/enhancement

Please add the ability to put the settings.json file to a network share (maybe homedrive) to use the same file from different workstations

# Proposed technical implementation details (optional)

You could add a command line parameter to set the configuration file path (i. e. network share/unc path).

**Comment by zadjii-msft** [comment] 2020-10-30 13:41
Thanks for the suggestion! I think largely, this is a duplicate of the discussion we're having in #2303. Or, at least, that's the issue that we've been using for tracking "I want to specify another file to read settings from".

/dup #2303

**Closed by zadjii-msft** 2020-10-30 13:41 UTC
Labels: Issue-Feature, Needs-Tag-Fix, Needs-Triage
