### ISSUE TITLE
Windows Terminal theme does not change during the run

### ISSUE THREAD

**Issue by xmha97** [microsoft/terminal#6275] opened 2020-05-30 18:34 UTC
Hi,
Windows Terminal theme does not change during the run
![Windows Terminal](https://user-images.githubusercontent.com/23485114/83336547-a47cf400-a2c9-11ea-9dd7-67f41dafe25d.png)

**Comment by j4james** [comment] 2020-05-31 01:05
This sounds like a duplicate of #1230.

**Closed** 2020-05-31 02:39 UTC
Labels: Needs-Tag-Fix, Needs-Triage
