### ISSUE TITLE
Close tab shortcut (Ctrl+F4) doesn't work if window focus is not on title bar

### ISSUE THREAD

**Issue by ThomsonTan** [microsoft/terminal#8585] opened 2020-12-14 17:51 UTC
# Environment

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
10.0.19042.685
Windows Terminal version (if applicable):
Latest preview.

Any other software?
```

# Steps to reproduce
1. Click `+` in the title bar to create a new tab in Windows Terminal.
2. Press Ctrl+F4 to close the tab.

# Expected behavior
The newly created tab is closed after Ctrl+F4.

# Actual behavior
Nothing changed and the new tab still exists.

Seems Ctrl+F4 to close tab window only works if the tab/title bar has Window focus. For example, it works if I click tab title before pressing Ctrl+F4.

**Comment by DHowett** [comment] 2020-12-14 18:13
So, this is a weird thing. That binding's not supposed to work unless you go into your settings and explicitly bind it yourself. That it _does_ work anywhere without it being bound explicitly is the bug I'd rather fix. :smile:

**Comment by zadjii-msft** [comment] 2020-12-15 10:59
I wonder if XAML is providing the <kbd>Ctrl+F4</kbd> keybinding themselves... Oh they are!

https://github.com/microsoft/microsoft-ui-xaml/blob/309c88f81cf23802d6406b452e4381fc9b4e9de1/dev/TabView/TabView.cpp#L38-L43

That's certainly interesting. 

I'd say in general, if you want <kbd>Ctrl+F4</kbd> to work to close a tab, I'd add a keybinding for it, since it's not bound by default. That would look something like
```json
{ "keys": "ctrl+f4", "action": "closePane" }
```

(we use `closePane` because it's more versatile than `closeTab` - it will close the tab if you only have one open tab, and work to close the pane if you have multiple panes)

**Comment by Lindsay-Needs-Sleep** [comment] 2021-02-04 00:32
@zadjii-msft Thanks for the tip!  Unfortunately it doesn't seem to work for me. :/

![image](https://user-images.githubusercontent.com/51773923/106827199-a3187e00-6645-11eb-84ff-9e35aecde584.png)


Like @ThomsonTan said, if I click on the tab head first, ctrl+f4 works.

Interestingly, ctrl+shift+w works like I wish ctrl+f4 did.

ctrl+tab also switches the tabs as expected (without having to click on the tab heads first. :S)

**Comment by zadjii-msft** [comment] 2021-02-04 11:31
I don't know what I was thinking closing this. Maybe because I was triaging at 5am?

Yea, we should unbind that from the TabView, so that Ctrl+F4 works in both the terminal content _and_ in the tab view.

Now, how we remove that keybinding from the TabView is another question entirely.

**Comment by elouanKeryell-Even** [comment] 2021-03-16 10:34
Witnessing the same issue as ThomsonTan

**Comment by zadjii-msft** [comment] 2021-03-16 10:36
@elouanKeryell-Even  If you'd like to "+1" this feature, the best way to do that is by hitting the 👍 button on this issue

![image](https://user-images.githubusercontent.com/18356694/96140789-ef3c8880-0ec5-11eb-82e0-30ce4977b9a7.png)

That way, you avoid unnecessarily pinging everyone following this thread. Thanks!

**Comment by elouanKeryell-Even** [comment] 2021-03-16 10:40
As a work-around, is there a key bind to "focus tab bar"?

That way I could do:

- key bind "focus tab bar"
- key bind "close tab" (ctrl+f4)

... without using the mouse

**Comment by zadjii-msft** [comment] 2021-03-16 10:44
> is there a key bind to "focus tab bar"?

Not currently, and outside the context of this bug, I'm not sure there's really a use case for that. I think it'd just be easier to solve the underlying bug then add the workaround 😉

**Comment by elouanKeryell-Even** [comment] 2021-03-16 10:50
@zadjii-msft ok thx, I think I'm gonna stick with the default WSL2 terminal for now, but I will check again Windows Terminal when this issue is solved :)

Have a good day

**Comment by DHowett** [comment] 2021-03-16 15:50
@elouanKeryell-Even If I may point out... the default WSL console host _also does not support <kbd>Ctrl+F4</kbd>_. What specifically about this key binding is holding you back?

Just to be clear: you can keybind ctrl+f4 to "`closeTab`", and you can use the `nextTab`/`prevTab` key bindings to navigate tabs without interacting with the tab bar.

What specific thing do you need to focus the tab bar for?

**Comment by zadjii-msft** [comment] 2021-03-16 15:56
HOLY GOSH.

The whole thesis of this bug is premised on a typo.

The keybinding should be 

```json
        { "keys": "ctrl+f4", "command": "closePane" },
```

`command`. Not `action`.

That works perfectly fine in the terminal today. That's what I get for triaging at 5am.

**Closed by zadjii-msft** 2021-03-16 15:56 UTC
Labels: Area-Settings, Help Wanted, Issue-Bug, Priority-2, Product-Terminal

**Comment by SGM3** [comment] 2021-04-19 21:13
Using Version: 1.7.1033.0

Not sure whether it was intended or not but there is a tooltip over the the tab's [X] button that say closing is Ctrl + F4, but on a fresh install of the above, its not there.

Was able to add the command in the JSON file and then it works perfectly.

**Comment by basic-settings** [comment] 2021-09-20 05:48
> Not sure whether it was intended or not but there is a tooltip over the the tab's [X] button that say closing is Ctrl + F4, but on a fresh install of the above, its not there.

Can confirm the above, the tooltip says it on a fresh install but it's not functional without the focus. Adding the "closeTab" binding works.

**Comment by lackovic** [comment] 2023-01-18 09:07
> there is a tooltip over the the tab's [X] button that say closing is Ctrl + F4, but on a fresh install of the above, its not there.

I confirm that this is still there. Should the tooltip not be displayed if the relative configuration does not exist?

**Comment by Gorschel** [comment] 2023-04-20 12:16
just fix the tool tip description for the "close Tab" [x] button to "CTRL+SHIFT+W" and this shouldnt be an issue any longer. 
But please consoder sticking to standard hotkey conventions like switching through the tabs with CTRL+PGUP/DOWN
