### ISSUE TITLE
Temporary freeze on close

### ISSUE THREAD

**Issue by runemoberg** [microsoft/terminal#5165] opened 2020-03-29 10:20 UTC
# Environment

```none
Windows build number: 10.0.18363.0
Windows Terminal version (if applicable):  0.10.781.0

ssh.exe:  7.7.2.1
```

# Steps to reproduce

1. Start ssh.exe against any ssh host
2. While at the login prompt, simply close the tab

# Expected behavior

Tab either closes immediately OR terminal lets me interact with other tabs while waiting for ssh.exe to clean up.

# Actual behavior

ssh.exe lingers for about 5 seconds. During these five seonds the terminal window freezes and no interaction with other tabs is possible.

Pressing ctrl+c first will terminate ssh.exe immediately, so the issue doesn't manifest itself then. If I had completed the login first, then I'd also avoid this phenomena.

**Comment by DHowett-MSFT** [comment] 2020-04-03 06:20
Thanks for the report! This is a /dupe of #1996, which we have a couple ideas on how to solve. Right now, we're serially waiting for a tab to close in all cases, when we could probably wait only in the full application teardown case (or hand its connection off to a background thread for summary destruction.) We used to murder processes instantly when you closed the tab, but that turned out to be really bad.

**Closed by DHowett-MSFT** 2020-04-03 06:20 UTC
Labels: Needs-Tag-Fix, Needs-Triage
