### ISSUE TITLE
Maximized Windows Terminal interferes with display of auto-hidden Windows Taskbar

### ISSUE THREAD

**Issue by harp-intel** [microsoft/terminal#13679] opened 2022-08-05 00:05 UTC
### Windows Terminal version

1.15.2002.0

### Windows build number

10.0.19044.1826

### Steps to reproduce

1. Configure Windows taskbar to auto-hide.
2. Start Windows Terminal.
3. Maximize Windows Terminal.
4. Note that moving mouse pointer to edge of screen where taskbar would normally appear does not un-hide taskbar.

Additional configuration information (not sure if relevant):
- Failure occurs on laptop with or without 2nd monitor connected. 
- Failure occurs when Windows Terminal is maximized on laptop screen.
- Failure does NOT occur when Windows Terminal is maximized on 2nd monitor.
- Taskbar configured to display only on laptop screen.
- Taskbar positioned at bottom of laptop screen.

### Expected Behavior

Taskbar is shown when mouse pointer is moved to edge of screen.

### Actual Behavior

Taskbar is not shown (un-hidden) when mouse pointer is moved to edge of screen.

**Comment by zadjii-msft** [comment] 2022-08-10 21:48
As noted in #11789

> See also: #4857
> 
> > Note to future code archeologists: This doesn't seem to work for fullscreen on the _primary_ display. However, testing a bunch of other apps with fullscreen modes and an auto-hiding taskbar has shown that _none_ of them reveal the taskbar from fullscreen mode. This includes Edge, Firefox, Chrome, Sublime Text, Powerpoint - none seemed to support this.
> > This does however work fine for maximized

That mentions fullscreen specifically, not maximized. Not sure if that's the same root cause at this time.

**Comment by bortlicenseplates** [comment] 2022-10-26 09:48
I'm having the same issue as described above. I've noticed that it only happens when the title bar is hidden

![image](https://user-images.githubusercontent.com/5849767/197994592-0a50e557-b96b-4269-9c98-9f93c163a725.png)

**Comment by TomasChmelik** [comment] 2022-12-06 05:51
Also experiencing, version 1.15.2875.0. Workaround disabling "Hide the title bar" worked, but it leaves me with unsightly and useless title bar. Changing Windows scaling didn't work.

**Comment by zadjii-msft** [comment] 2023-05-03 21:50
@ekoschik Hey, you're the User32 wizard, is this the auto-hide taskbar thing we were talking about like a month ago?

**Comment by zadjii-msft** [comment] 2023-05-03 21:51
`NonClientIslandWindow::_OnNcCalcSize` makes me think that _yes_, the tabs in the titlebar do have some effect here

**Comment by ekoschik** [comment] 2023-05-07 21:41
@zadjii-msft yes, this is the auto-hide taskbar problem I was referring to before, which should be fixed by the [code in _OnNcCalcSize](https://github.com/microsoft/terminal/blob/ae7595b8e13d4764f4db7b4060eaf57d1b4ee82e/src/cascadia/WindowsTerminal/NonClientIslandWindow.cpp#L634) under the comment `// GH#1438 - Attempt to detect if there's an autohide taskbar`.

Some additional info in case its helpful.

- 'Fullscreen' is not a Win32 state, like Maximized/Minimized. Instead, the system treats a window that covers its monitor to be fullscreen. When a window is fullscreen, the taskbar on that monitor moves below the fullscreen window (by making itself not topmost), which allows fullscreen videos, remote desktop, etc, to cover the taskbar (without being topmost themselves).

- Auto hide taskbar changes the work area to the monitor rect (as if there was no taskbar). This means that maximized windows are larger than the monitor rect. By default, windows maximize to the work area expanded by the resize borders, which is smaller than the monitor rect if there is a taskbar but larger than the monitor rect without a taskbar. A transparent taskbar window sits at the bottom 2px of the monitor, which allows it to be invoked by receiving mouse input.

- Traditional maximized windows have a title bar (and fullscreen windows do not), and this distinction is used by the fullscreen detection to differentiate maximized/fullscreen windows. Terminal can hide its taskbar using WM_NCCALCSIZE, but this makes the client rect (when maximized on an auto hide taskbar) cover the monitor rect. And this fools the fullscreen detection into thinking the window is fullscreen.

- The workaround added to _OnNcCalcSize detects this case and adjusts the client rect to make it NOT cover the monitor, which fixes invoking the auto hide taskbar. This causes a few pixels un-drawn below the window (and this is visible to the user since they can see through to the windows/background image behind the maximized Terminal window).

- This workaround will not be needed in future OS releases, see PR 8684017 in the OS repo.

**Comment by zadjii-msft** [comment] 2023-05-12 15:40
Right on, thanks for the comprehensive summary ☺

**Closed by zadjii-msft** 2023-05-12 15:40 UTC
Labels: Issue-Bug, Needs-Tag-Fix, Area-Windowing

**Comment by ValZapod** [comment] 2023-05-13 07:20
There is now (since KB5022913 for 11 22H2) 2 pixels white line in maximised view, because hidden taskbar two pixels are now gone.

**Comment by HattDroid** [comment] 2023-12-16 13:15
> @zadjii-msft yes, this is the auto-hide taskbar problem I was referring to before, which should be fixed by the [code in _OnNcCalcSize](https://github.com/microsoft/terminal/blob/ae7595b8e13d4764f4db7b4060eaf57d1b4ee82e/src/cascadia/WindowsTerminal/NonClientIslandWindow.cpp#L634) under the comment `// GH#1438 - Attempt to detect if there's an autohide taskbar`.
> 
> Some additional info in case its helpful.
> 
>     * 'Fullscreen' is not a Win32 state, like Maximized/Minimized. Instead, the system treats a window that covers its monitor to be fullscreen. When a window is fullscreen, the taskbar on that monitor moves below the fullscreen window (by making itself not topmost), which allows fullscreen videos, remote desktop, etc, to cover the taskbar (without being topmost themselves).
> 
>     * Auto hide taskbar changes the work area to the monitor rect (as if there was no taskbar). This means that maximized windows are larger than the monitor rect. By default, windows maximize to the work area expanded by the resize borders, which is smaller than the monitor rect if there is a taskbar but larger than the monitor rect without a taskbar. A transparent taskbar window sits at the bottom 2px of the monitor, which allows it to be invoked by receiving mouse input.
> 
>     * Traditional maximized windows have a title bar (and fullscreen windows do not), and this distinction is used by the fullscreen detection to differentiate maximized/fullscreen windows. Terminal can hide its taskbar using WM_NCCALCSIZE, but this makes the client rect (when maximized on an auto hide taskbar) cover the monitor rect. And this fools the fullscreen detection into thinking the window is fullscreen.
> 
>     * The workaround added to _OnNcCalcSize detects this case and adjusts the client rect to make it NOT cover the monitor, which fixes invoking the auto hide taskbar. This causes a few pixels un-drawn below the window (and this is visible to the user since they can see through to the windows/background image behind the maximized Terminal window).
> 
>     * This workaround will not be needed in future OS releases, see PR 8684017 in the OS repo.

Would it please be possible to have this code only triggered with a user settings such as something like "ignore taskbar status", "ignore hidden taskbar" or similar?
The fact the app drawing space is reduced when a hidden taskbar is detected can be super detrimental in some screen resolutions and font sizes combination and makes some terminal app lose a whole row. And of course it also leaves an empty line at the bottom, that with bright wallpapers can be very disturbing.
It would be great if this would be an option and that one would not have to remove the code and recompile the app just to avoid this "feature" that for most is actually a bug.

Thank you guys! 👍
