### ISSUE TITLE
Changing Ubuntu WSL starting directory keeps it set to the defualt

### ISSUE THREAD

**Issue by AlikanakelaKarwowski** [microsoft/terminal#2743] opened 2019-09-13 01:31 UTC
When editing the the settings, I have tried to chang the default starting directory for the Ubuntu WSL Terminal profile as follows
`"startingDirectory": "/mnt/D/Folder/SubFolder/",`
and while it doesnt cause any issues or causes the Terminal to resort to default configuration, it does not set the default starting directory to the specified path.

Also it seems that most settings for the profile do literally nothing when changing them, from color, to acrylic or scheme settings.

Note: changing the setting for power shell, cmd, of Kali-Linux does work and change things respectively

**Comment by zadjii-msft** [comment] 2019-09-13 15:44
`startingDirectory` Should be a _windows_ path, not a *nix path. Try `D:\Folder\SubFolder` instead.

Could you be specific which settings don't seem to work for that profile? Maybe share the profile from the `profiles.json` file?

**Comment by bitcrazed** [comment] 2019-09-13 22:59
@zadjii-msft Just checked into this & verified that, yes, specifying a Windows path does work, and for WSL distros, specifying a Windows-relative path to a distro also works. 

For example, `\\\\wsl$\Ubuntu\home\\rich\\` opens my Ubuntu home folder! 😁

**Comment by DHowett-MSFT** [comment] 2019-09-14 16:38
This is a duplicate of another bug in the db somewhere. We need to clarify in the documentation that `startingDirectory` is a _Windows_ path, and since Terminal doesn't actually know anything about the connected application on the other end we can't assume that it's WSL and do path translation and all that stuff.

It's gotta be a Windows path. :smile:

I'm re-tagging this with `Issue-Docs`

**Comment by MEXdave1997** [comment] 2019-09-19 16:10
I am working on submitting a PR to add that bit of detail, if that is alright with everyone.

**Comment by DHowett-MSFT** [comment] 2019-09-19 16:17
Sure!

**Comment by MEXdave1997** [comment] 2019-09-19 16:20
PR is up! #2813

**Closed** 2019-09-19 16:24 UTC
Labels: Area-Settings, In-PR, Issue-Docs, Product-Terminal

**Comment by contento** [comment] 2019-11-06 20:57
> @zadjii-msft Just checked into this & verified that, yes, specifying a Windows path does work, and for WSL distros, specifying a Windows-relative path to a distro also works.
> 
> For example, `\\\\wsl$\Ubuntu\home\\rich\\` opens my Ubuntu home folder! 😁

You may want to use `wsl -l` first, in order to determine which Ubuntu version you are running.
For example:
`"startingDirectory": "\\\\wsl$\\Ubuntu-18.04\\home\\[linux-user]"`

**Comment by jgroom33** [comment] 2020-02-09 16:20
non-escaped also works:

```json
"startingDirectory" : "//wsl$/Ubuntu-18.04/home/<user>"
```

**Comment by Boobies** [comment] 2020-02-27 01:02
For me, this is what I get in the default profile for Debian:

            "startingDirectory" : "\\\\wsl$\\Debian\\home\\<user>",

and it doesn't even work properly. The path I get /mnt/c/Users/<CurrentWindowsUser>. If I don't use the Terminal Preview, it takes me to the proper home directory. So maybe the defaults are all messed up in this JSON provided.

**Comment by MEXdave1997** [comment] 2020-02-27 06:13
@Boobies weirdly enough, I've used `"startingDirectory": "\\\\wsl$\\Ubuntu\\home\\[linux username]"` in my config for a while now with no issue. Could there be any other setting that might be conflicting with it?

**Comment by jgroom33** [comment] 2020-02-27 13:54
use non-windows directory slashes:

```json
"startingDirectory" : "//wsl$/Ubuntu-18.04/home/<user>"
```

**Comment by amykapernick** [comment] 2020-02-27 22:52
I've tried all of these and it still seems to be defaulting to `c/Users/{user}` as well. Any suggestions?

**Comment by kybrdbnd** [comment] 2020-03-01 14:33
> I've tried all of these and it still seems to be defaulting to `c/Users/{user}` as well. Any suggestions?

start by using this -> `//wsl$/Ubuntu/` and then recursively find the directory where you want to go. 
If you wanna change drives like go to D:/ its not picking up, moreover you can change to your starting directory whose write access is done by root. Check the folder permission also by using `ls -l` if its root it can be your startingDirectory else not possible right now

**Comment by tnguyen14** [comment] 2020-03-30 14:31
@bitcrazed 
> For example, \\\\wsl$\Ubuntu\home\\rich\\ opens my Ubuntu home folder! 😁

I did this, and it works for me, but now I get this message every time I create a new window

```
wslpath: '\\wsl$\WLinux\home\tnguyen14'
CMD.EXE was started with the above path as the current directory.
UNC paths are not supported.  Defaulting to Windows directory.
C:\Users\NguyenTri
```

It still cd to the right directory though. Is this error message expected? Any way I can fix it?

**Comment by zadjii-msft** [comment] 2020-03-30 14:43
@tnguyen14 what `commandline` are you using to launch `wsl`?

**Comment by tnguyen14** [comment] 2020-03-30 16:50
@zadjii-msft The Windows Terminal app - is that what you meant?

**Comment by zadjii-msft** [comment] 2020-03-30 16:51
I meant the `commandline` in your `profiles.json` file - could you share that with me?

**Comment by tnguyen14** [comment] 2020-03-30 16:55
It's not specified. Here's the profile object:

```
        {
            "guid": "{7f586916-8357-53d4-bb2b-ca96f639898a}",
            "hidden": false,
            "name": "WLinux",
            "source": "Windows.Terminal.Wsl",
            "fontSize": 10,
            "fontFace": "SauceCodePro NF",
            "startingDirectory": "//wsl$/WLinux/home/tnguyen14",
            "padding": "0, 0, 0, 0"
        },
```

**Comment by zadjii-msft** [comment] 2020-03-30 17:01
Okay, well that's exactly what I'd expect that to look like. I'm not sure why that error message is getting displayed, but you might be able to get answers over at https://github.com/microsoft/WSL

**Comment by DHowett-MSFT** [comment] 2020-03-30 17:15
This is because `wslu`, the WSL integration bridge that ships with Ubuntu, is running `cmd.exe` on startup. There's nothing we can do about that. This will happen any time WSL is started outside of the Windows filesystem.

**Comment by DHowett-MSFT** [comment] 2020-03-30 17:16
More info here: https://github.com/microsoft/terminal/issues/4214

**Comment by tnguyen14** [comment] 2020-03-30 18:34
@DHowett-MSFT Interesting. I don't see if from windows when I use other terminal apps, like wsltty or the default Pengwin app - is that launched differently somehow?

**Comment by DHowett-MSFT** [comment] 2020-03-30 18:36
Depends. What do you get when you run `pwd` immediately after launching it in those other applications?

**Comment by tnguyen14** [comment] 2020-03-30 18:40
the regular linux `/home/myuser` path.
I know for the wsltty app, the "Target" property of the launcher is set to this value:

```
C:\Users\NguyenTri\AppData\Local\wsltty\bin\mintty.exe --WSL= --configdir="C:\Users\NguyenTri\AppData\Roaming\wsltty" -~ 
```

**Comment by tnguyen14** [comment] 2020-03-31 13:54
@DHowett-MSFT do you know if that same behavior can be replicated?

**Comment by wmertens** [comment] 2020-04-02 05:07
@DHowett-MSFT you said
> since Terminal doesn't actually know anything about the connected application on the other end we can't assume that it's WSL and do path translation and all that stuff.

But that doesn't make sense because Terminal knows to start WSL with the correct container purely based on the UUID (I presume?), there is nothing else in the entry that says which WSL container to open, and I can actually change the name and the path. Here's my Ubuntu install, I can say it's Alpine and it will still load Ubuntu with the correct path, but I can't say `//wsl/$/Whatever` so it needs to be the name of an existing install:

```json
      {
        "guid": "{2c4de342-38b7-51cf-b940-2309a097f518}",
        "hidden": false,
        "name": "Whatever",
        "startingDirectory": "//wsl$/Alpine/home/wmertens/",
        "source": "Windows.Terminal.Wsl"
      }
```

**Comment by mbursill** [comment] 2020-04-20 14:47
I edited `.bashrc` and added `cd ~` to the end. Good enough for my needs.

**Comment by trialuser** [comment] 2020-04-25 00:18
> 
> 
> I edited `.bashrc` and added `cd ~` to the end. Good enough for my needs.

sometimes it makes your work uncomfortable, because `cd ~` will be executed each time when you run .bashrc (e.g. with `sudo username` or just `bash`). For example, when you are in some specific directory switch between different shells - you will be moved to the home directory once you run bash :|

**Comment by krlinus** [comment] 2020-04-26 17:27
> > I edited `.bashrc` and added `cd ~` to the end. Good enough for my needs.
> 
> sometimes it makes your work uncomfortable, because `cd ~` will be executed each time when you run .bashrc (e.g. with `sudo username` or just `bash`). For example, when you are in some specific directory switch between different shells - you will be moved to the home directory once you run bash :|

Instead of ~/.bashrc it can be put in /etc/bashrc or /etc/bash.bashrc (whichever is present) if it is sourced less often

**Comment by frencojobs** [comment] 2020-05-03 14:52
> I edited `.bashrc` and added `cd ~` to the end. Good enough for my needs.

In my case, this causes problems with installed packages exported in `.bashrc` using `$HOME`. For example, I exported flutter in my `.bashrc` like, 
```bash
export PATH="$PATH:$HOME/flutter/bin"
```
and if I added, `cd ~` to the file, the flutter command won't work.

**Comment by thelazyanalyst** [comment] 2020-05-24 13:10
> 
> 
> @DHowett-MSFT you said
> 
> > since Terminal doesn't actually know anything about the connected application on the other end we can't assume that it's WSL and do path translation and all that stuff.
> 
> But that doesn't make sense because Terminal knows to start WSL with the correct container purely based on the UUID (I presume?), there is nothing else in the entry that says which WSL container to open, and I can actually change the name and the path. Here's my Ubuntu install, I can say it's Alpine and it will still load Ubuntu with the correct path, but I can't say `//wsl/$/Whatever` so it needs to be the name of an existing install:
> 
> ```json
>       {
>         "guid": "{2c4de342-38b7-51cf-b940-2309a097f518}",
>         "hidden": false,
>         "name": "Whatever",
>         "startingDirectory": "//wsl$/Alpine/home/wmertens/",
>         "source": "Windows.Terminal.Wsl"
>       }
> ```

This fixed my issue. Thank you.

**Comment by udithaMee** [comment] 2020-07-03 12:26
For Ubuntu 20.04 WSL2  In the terminal settings JSON file add   "startingDirectory": "//wsl$/Ubuntu-20.04/home/<Your Ubuntu Username>"
      {
            "guid": "{07b52e3e-de2c-5db4-bd2d-ba144ed6c273}",
            "hidden": false,
            "name": "Ubuntu-20.04",
            "source": "Windows.Terminal.Wsl",
            "startingDirectory": "//wsl$/Ubuntu-20.04/home/<Your Ubuntu Username>"
          }

**Comment by dgp1130** [comment] 2020-07-15 02:24
Just to point out a mistake I made that I haven't seen posted here, I renamed my distro from `Ubuntu-20.04` to `Ubuntu`. So I presumed the path would also be just `Ubuntu`. I tried:

```
//wsl$/Ubuntu/home/<username>
```

But this did not work. Instead I still needed to include the version number:

```
//wsl$/Ubuntu-20.04/home/<username>
```

The second "directory" in the path is apparently **not** the name of your distro. I'm not entirely sure where it comes from, but it seems I still had the default value from the install.

**Comment by RaviiKmr** [comment] 2020-07-15 06:18
> 
> 
> Just to point out a mistake I made that I haven't seen posted here, I renamed my distro from `Ubuntu-20.04` to `Ubuntu`. So I presumed the path would also be just `Ubuntu`. I tried:
> 
> ```
> //wsl$/Ubuntu/home/<username>
> ```
> 
> But this did not work. Instead I still needed to include the version number:
> 
> ```
> //wsl$/Ubuntu-20.04/home/<username>
> ```
> 
> The second "directory" in the path is apparently **not** the name of your distro. I'm not entirely sure where it comes from, but it seems I still had the default value from the install.

Yes, this worked. I've included version name and now it's working fine.

**Comment by DHowett** [comment] 2020-07-15 06:23
Oh gosh, that’s a really big gotcha. Thanks for pointing that out.

Yeah, the distro name is the system’s name for it; whichever one comes out of `wsl.exe -l`

**Comment by amaria** [comment] 2020-07-20 16:09
Also, if you have mapped a network drive to \\wsl$ use the drive name/letter. Otherwise none of these suggestions will work.

**Comment by kvietmeier** [comment] 2020-07-20 17:01
I have tried all of those and still getting Windows home directory.
`        {
            //WSL
            "guid": "{69b4a9a7-42eb-457e-b4eb-9c6bef28aa4d}",
            "hidden": false,
            "name": "Ubuntu",
            "source": "Windows.Terminal.Wsl",
            "colorScheme" : "One Half Dark",
            "startingDirectory": "//wsl$/Ubuntu/home/karlv"
        },
`
WSL 2.0 with Ubuntu 20.04 installed from the Windows Store.  Could it be the GUID?  

`karlv@MININT-J0FCRPR:/mnt/c/Users/kavietme$`

**Comment by DHowett** [comment] 2020-07-20 17:08
I'm guessing that if you run `wsl -l`, your distribution isn't named `Ubuntu` or `Ubuntu-20.04`?

**Comment by ddamjengi1020** [comment] 2020-07-22 11:38
`"startingDirectory": "\\\\wsl$\\Ubuntu\\home\\juno"`
It's working on my WSL2 Ubuntu 20.04 LTS

**Comment by jcgoble3** [comment] 2020-07-22 16:56
`"startingDirectory": "//wsl$/Ubuntu/home/<username>",` is what worked for me (Ubuntu 20.04). This was driving me crazy because I open and close the terminal frequently, but with WSL 2 on Windows 20H2 beta, merely loading the prompt in a mounted Windows filesystem takes over a minute, but I work exclusively in the Linux filesystem, so I was constantly having to wait for the prompt to load just so I could `cd` to my Linux home directory.

**Comment by Slingx** [comment] 2020-08-14 17:33
> //wsl$/Ubuntu-20.04/home/Your Ubuntu Username

this worked!!!! tysm

**Comment by Herbert256** [comment] 2020-09-11 08:19
late to the party, I did below once and after that all feature sessions are started in the linux home directory instead of the windows home directory

echo "cd ~" >> ~/.profile

**Comment by mcandre** [comment] 2020-10-22 23:45
Some blogs provide incorrect instructions, such as adding an Ubuntu version prefix. Combined with Windows Terminal silently failing in the event that such a path is invalid.

**Comment by ad-on-is** [comment] 2020-11-01 10:04
If you're using the new `--mount` option and have symlinked your user-directory to that mount, you need something like this: `"startingDirectory" : "//wsl$/<distro>/mnt/wsl/PHYSICALDRIVE<x>p<x>/<folder>"`

**Comment by thehaystacker** [comment] 2020-11-16 09:04
You have to set this in the profile list object

    ```
"profiles":
    {
        "defaults":
        {
            // Put settings here that you want to apply to all profiles.
        },
        "list":
        [
            {
                "guid": "{c6eaf9f4-32a7-5fdc-b5cf-066e8a4b1e40}",
                "hidden": false,
                "name": "Ubuntu-18.04",
                "source": "Windows.Terminal.Wsl",
                "startingDirectory": "D:\\projects"
            }
        ]
    },
```

**Comment by lalilulelost** [comment] 2021-01-15 03:57
> non-escaped also works:
> 
> ```json
> "startingDirectory" : "//wsl$/Ubuntu-18.04/home/<user>"
> ```

This worked for me. If I may ask, what kind of syntax is that for the path? With the "wsl" and dollar sign starting it. Is there some name for it? It reminds me of how URIs start with a protocol such as `<protocol>://address.something` and so on

**Comment by jcgoble3** [comment] 2021-01-15 04:09
The path beginning with `//` is how Windows indicates a reference to another system, with the first path element being the name of that system. The system can be a network server, LAN share, or in this case, WSL. The dollar sign isn't special in the syntax, but just happens to be how the WSL system is named for the path purposes (probably done to prevent collisions with any existing systems that might be named `wsl`.

**Comment by bitcrazed** [comment] 2021-01-15 17:04
@lalilulelost The path you're referring to is a fully qualified UNC (Universal Naming Convention) path. More info here: https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file

**Comment by w4zz** [comment] 2021-01-22 19:37
I think some of the issues people are having is confusing windows username with linux username which you see in the linuxuser@ubuntu:/mnt/c/Users/windowsUserName$ - in order to get the startingDirectory to work you have to use your distros username and not the windows one.

`"startingDirectory": "\\\\wsl$\\Ubuntu-20.04\\home\\linuxUser",`

**Comment by fschuetz04** [comment] 2021-03-04 08:53
To get the full correct path, simply open a WSL session, go to your future starting directory (e.g. `cd ~`), and then type `wslpath -w .` to translate the current WSL path to a Windows one. To put it in the configuration, each \ has to be escaped with another \ or be replaced with a /.

Example output of `wslpath -w .`: `\\wsl$\Ubuntu-20.04\home\bob`

In the configuration file: `"startingDirectory": "\\\\wsl$\\Ubuntu-20.04\\home\\bob"`
Or: `"startingDirectory": "//wsl$/Ubuntu-20.04/home/bob"`

**Comment by visma-henriklarsen** [comment] 2021-03-27 22:34
> You have to set this in the profile list object
> 
> ```
> "profiles":
> {
>     "defaults":
>     {
>         // Put settings here that you want to apply to all profiles.
>     },
>     "list":
>     [
>         {
>             "guid": "{c6eaf9f4-32a7-5fdc-b5cf-066e8a4b1e40}",
>             "hidden": false,
>             "name": "Ubuntu-18.04",
>             "source": "Windows.Terminal.Wsl",
>             "startingDirectory": "D:\\projects"
>         }
>     ]
> }
> ```

In my case I had to use forward slashes in StartingDirectory, like:
"startingDirectory": "D://projects"

**Comment by mrzlanx532** [comment] 2021-03-28 09:44
If the methods above don't work (like for me), do this:
Add to the end `.bashrc` file: `cd ~`. 

From Windows environment:
1. execute `wsl`
2. execute `cd ~ && echo 'cd ~' >> .bashrc`

**Comment by ednl** [comment] 2021-07-02 09:28
Reading every message here FINALLY gave me the hint https://github.com/microsoft/terminal/issues/2743#issuecomment-593103843 why it wasn't working for me: the home directory needs to have read/execute access for group/others. Strange, because the root user should have access anyway, right?

I always do ```chmod -R go-rwx ~``` and that bit me here. It is now fixed after ```chmod go+rx ~``` and WSL starts up in my Linux home directory again.

**Comment by SGarcia710** [comment] 2021-07-23 01:47
> The problem isn't the documentation, it's the default JSON provided. That's why everyone keeps complaining about the same thing. Here's mine:
> 
> ```
>         "startingDirectory" : "\\\\wsl$\\Debian\\home\\<linuxuser>"
> ```
> 
> which instead takes me to `/mnt/c/Users/<windowsuser>`. So it looks like that string is entirely ignored and a default that has nothing to do with it is picked. It's not even the same username.

This one worked for me, just editing the JSON file

**Comment by ajfpay** [comment] 2021-08-06 01:42
> non-escaped also works:
> 
> ```json
> "startingDirectory" : "//wsl$/Ubuntu-18.04/home/<user>"
> ```

Yeah this work

**Comment by Rmlyy** [comment] 2021-11-23 18:19
Adding `cd` in `.bashrc` seems to work.

**Comment by yorkshire-pudding** [comment] 2021-12-09 11:09
> > non-escaped also works:
> > ```json
> > "startingDirectory" : "//wsl$/Ubuntu-18.04/home/<user>"
> > ```
> 
> Yeah this work

worked for me too

**Comment by jetersen** [comment] 2021-12-31 00:07
Today after reinstalling Ubuntu 20.04

I had to use on Windows 10 21H2 (Build 19044.14.15)
```
"startingDirectory": "/home/<user>"
```

Which is GREAT 👏

**Comment by oguzcandemircan** [comment] 2022-01-03 12:26
> > > non-escaped also works:
> > > ```json
> > > "startingDirectory" : "//wsl$/Ubuntu-18.04/home/<user>"
> > > ```
> > 
> > 
> > Yeah this work
> 
> worked for me too

worked for me too

**Comment by ray-x** [comment] 2022-01-04 00:55
> 

__

> Today after reinstalling Ubuntu 20.04
> 
> on Windows 10 21H2 (Build 19044.1415) I had to use
> 
> ```json
> "startingDirectory": "/home/<user>"
> ```
> 
> Which is GREAT 👏

Same here, if set to `//wsl$/Ubuntu/home/<user>`  I will start from root folder

**Comment by riker09** [comment] 2022-01-21 07:05
I have Windows 10 Version 20H2 - Build 19042.1415 and had to use `/home/<user>` where `<user>` needed to be replaced with the actual user name. All other solutions provided above did not work for me. I have only Ubuntu installed inside WSL.

**Comment by zadjii-msft** [comment] 2022-01-21 14:14
Okay lemme clear this up before there's more confusion. This ISN'T something that came with a Windows update, this is a Terminal change in 1.12. 

In 1.12, you should be able to use `/home/<user>` as the `startingDirectory`, and the Terminal should automatically promote that to the correct path. Unfortunately, that came at a cost - there's a bug in 1.12 where `//wsl$/Ubuntu/home/<user>` paths will be treated as `/`. That's fixed in #12102. (`\\wsl$\Ubuntu\home\<user>` with backslashes should still work)

**Comment by wolf99** [comment] 2022-02-02 17:09
My work laptop just updated from 1909 to 20H2 (upgrades are controlled by policy, thus the reason for not being on a newer version or having updated sooner).
Previously the following had worked just fine to start WT in `~` : `"startingDirectory" : "/wsl$/Ubuntu/home/emoltob"`
After the upgrade WT started in `/`, I assume it was then ignoring this setting as somehow invalid.
Changing to the following solved this: `"startingDirectory" : "\\\\wsl$\\Ubuntu\\home\\emoltob"`

Yes, these two seem basically equivalent. Yet the latter works while the former is apparently now ignored.

**Comment by zadjii-msft** [comment] 2022-02-02 17:13
@wolf99 what you're seeing is exactly what I've described in https://github.com/microsoft/terminal/issues/2743#issuecomment-1018540758

**Comment by wolf99** [comment] 2022-02-02 17:17
Mmm I'm not on 1.12 yet though as I do not use the pre release versions. I am still on 1.11. Are you saying this change was also present in 1.11 ?

**Comment by MorpH2k** [comment] 2022-02-03 14:25
I worked my way through this whole thread and it took me a while to realize that Windows Terminal has been updated. I added the line to the Json file and it only half worked, changing the starting directory from my Windows user folder to root. 

Going into the settings under Ubuntu and setting the Starting directory option to \\wsl$\Ubuntu\home\username\ works but not when using /

**Comment by AnimeshRy** [comment] 2022-02-08 19:02
> > 
> 
> __
> 
> > Today after reinstalling Ubuntu 20.04
> > on Windows 10 21H2 (Build 19044.1415) I had to use
> > ```json
> > "startingDirectory": "/home/<user>"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Which is GREAT 👏
> 
> Thanks! Same here, if set to `//wsl$/Ubuntu/home/<user>` I will start from root folder

This worked finally!

**Comment by mcandre** [comment] 2022-02-21 23:27
Something recently changed and now WSL starts with a WSL root working directory instead of the correct WSL HOME working directory.

**Comment by barcellos-pedro** [comment] 2022-03-09 12:25
> > > 
> > 
> > 
> > __
> > > Today after reinstalling Ubuntu 20.04
> > > on Windows 10 21H2 (Build 19044.1415) I had to use
> > > ```json
> > > "startingDirectory": "/home/<user>"
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Which is GREAT 👏
> > 
> > 
> > Thanks! Same here, if set to `//wsl$/Ubuntu/home/<user>` I will start from root folder
> 
> This worked finally!

That worked for me! Thanks! 💖

**Comment by mbowolick** [comment] 2022-03-13 06:13
A lot of the paths here didn't work for me. `\\wsl$\Ubuntu\home\<user>` worked for me where `<user>` is the name of your Linux user.

**Comment by cjens00** [comment] 2022-04-23 21:58
> If the methods above don't work (like for me), do this: Add to the end `.bashrc` file: `cd ~`.
> 
> From Windows environment:
> 
> 1. execute `wsl`
> 2. execute `cd ~ && echo 'cd ~' >> .bashrc`

Thank you. This is what I was looking for (works well enough).

**Comment by kwint** [comment] 2022-11-25 10:20
I still can't get this to work as expected. I want the default folder to be `~/code`. So my starting dir is set to: `\\wsl$\Ubuntu-22.04\home\kwint\code` but this just opens the home folder and not the code folder. 

Afaik I don't have any cd ~ in my .bashrc or equivalent

**Comment by Nick-Hope** [comment] 2023-12-26 18:14
> non-escaped also works:
> 
> ```json
> "startingDirectory" : "//wsl$/Ubuntu-18.04/home/<user>"
> ```

`//wsl$/Ubuntu/home/<user>` worked for me but I also had to change my Command line in the settings from `ubuntu.exe` to `wsl.exe -d Ubuntu`.

**Comment by kevgilmore** [comment] 2024-01-09 00:23
> Today after reinstalling Ubuntu 20.04
> 
> on Windows 10 21H2 (Build 19044.1415) I had to use
> 
> ```json
> "startingDirectory": "/home/<user>"
> ```
> 
> Which is GREAT 👏

this gave me error

```
[error 2147942667 (0x8007010b) when launching `ubuntu.exe']
Could not access starting directory "/home/kev/code"
```
