### ISSUE TITLE
Windows terminal pops up sometime with certain codes on my old laptop(windows 11 ) recently installed.

### ISSUE THREAD

**Issue by joyal0** [microsoft/terminal#14447] opened 2022-11-27 09:28 UTC
I face this situation many a times when i start my laptop recently, I have these contents pop up in 2 seperate powershell admin terminals. I got it installed by a friend of mine.

```
750XXXA1-7XXX-4XXX-9C6C-202XXXFC10B9

Resolve-DnsName : wmail-endpoint.com : DNS name does not exist
At line:9 char:16
+         $dns = Resolve-DnsName -Name $hostname -Type 'TXT'
+                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (wmail-endpoint.com:String) [Resolve-DnsName], Win32Exception
    + FullyQualifiedErrorId : DNS_ERROR_RCODE_NAME_ERROR,Microsoft.DnsClient.Commands.ResolveDnsName

Resolve-DnsName : bideo-blog.com : DNS server failure
At line:9 char:16
+         $dns = Resolve-DnsName -Name $hostname -Type 'TXT'
+                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (bideo-blog.com:String) [Resolve-DnsName], Win32Exception
    + FullyQualifiedErrorId : RCODE_SERVER_FAILURE,Microsoft.DnsClient.Commands.ResolveDnsName

Resolve-DnsName : privatproxy-blog.com : DNS server failure
At line:9 char:16
+         $dns = Resolve-DnsName -Name $hostname -Type 'TXT'
+                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (privatproxy-blog.com:String) [Resolve-DnsName], Win32Exception
    + FullyQualifiedErrorId : RCODE_SERVER_FAILURE,Microsoft.DnsClient.Commands.ResolveDnsName

Resolve-DnsName : privatproxy-cdn.com : DNS name does not exist
At line:9 char:16
+         $dns = Resolve-DnsName -Name $hostname -Type 'TXT'
+                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (privatproxy-cdn.com:String) [Resolve-DnsName], Win32Exception
    + FullyQualifiedErrorId : DNS_ERROR_RCODE_NAME_ERROR,Microsoft.DnsClient.Commands.ResolveDnsName

Resolve-DnsName : ahoravideo-chat.com : DNS name does not exist
At line:9 char:16
+         $dns = Resolve-DnsName -Name $hostname -Type 'TXT'
+                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (ahoravideo-chat.com:String) [Resolve-DnsName], Win32Exception
    + FullyQualifiedErrorId : DNS_ERROR_RCODE_NAME_ERROR,Microsoft.DnsClient.Commands.ResolveDnsName

Resolve-DnsName : fairu-blog.xyz : DNS name does not exist
At line:9 char:16
+         $dns = Resolve-DnsName -Name $hostname -Type 'TXT'
+                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (fairu-blog.xyz:String) [Resolve-DnsName], Win32Exception
    + FullyQualifiedErrorId : DNS_ERROR_RCODE_NAME_ERROR,Microsoft.DnsClient.Commands.ResolveDnsName
```

```
Resolve-DnsName : ahoravideo-cdn.xyz : DNS name does not exist
At line:9 char:16
+         $dns = Resolve-DnsName -Name $hostname -Type 'TXT'
+                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (ahoravideo-cdn.xyz:String) [Resolve-DnsName], Win32Exception
    + FullyQualifiedErrorId : DNS_ERROR_RCODE_NAME_ERROR,Microsoft.DnsClient.Commands.ResolveDnsName

```

AND

```
`32XXX7C1-6XXX-4XXX-A0AX-C8B8XXX58567
Resolve-DnsName : wmail-endpoint.com : DNS name does not exist
At line:9 char:16
+         $dns = Resolve-DnsName -Name $hostname -Type 'TXT'
+                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (wmail-endpoint.com:String) [Resolve-DnsName], Win32Exception
    + FullyQualifiedErrorId : DNS_ERROR_RCODE_NAME_ERROR,Microsoft.DnsClient.Commands.ResolveDnsName

Resolve-DnsName : bideo-blog.com : DNS server failure
At line:9 char:16
+         $dns = Resolve-DnsName -Name $hostname -Type 'TXT'
+                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (bideo-blog.com:String) [Resolve-DnsName], Win32Exception
    + FullyQualifiedErrorId : RCODE_SERVER_FAILURE,Microsoft.DnsClient.Commands.ResolveDnsName

Resolve-DnsName : privatproxy-blog.com : DNS server failure
At line:9 char:16
+         $dns = Resolve-DnsName -Name $hostname -Type 'TXT'
+                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (privatproxy-blog.com:String) [Resolve-DnsName], Win32Exception
    + FullyQualifiedErrorId : RCODE_SERVER_FAILURE,Microsoft.DnsClient.Commands.ResolveDnsName

Resolve-DnsName : privatproxy-cdn.com : DNS name does not exist
At line:9 char:16
+         $dns = Resolve-DnsName -Name $hostname -Type 'TXT'
+                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by 237dmitry** [comment] 2022-11-27 12:31
I think you need to find the powershell script (or script-block) that runs when the laptop starts up.
Enter in pop-up terminal window (if it stayed open):

```powershell
$error[0].InvocationInfo
```

**Comment by j4james** [comment] 2022-11-27 19:57
I'm no expert on the subject, but it looks to me like you could have some form of malware on your computer. Just based on the domain names used, it sounds like the cryptocurrency stealing script described in this article:

https://www.pluribus-one.it/company/blog/84-cybersecurity/150-detecting-powershell-cryptostealer

Although it's possible there are other forms of malware using the same DGA algorithm they're discussing. I would recommend you get someone to look at your computer that knows something about security.

**Comment by elsaco** [comment] 2022-11-27 20:47
`autoruns` from Sysinternals suite (Microsoft utilities) will show your current auto-start applications:

https://learn.microsoft.com/en-us/sysinternals/downloads/autoruns

See what's hijacked. On the positive side not resolving those name means no payload can be downloaded to your notebook.

**Comment by j4james** [comment] 2022-11-27 21:07
> On the positive side not resolving those name means no payload can be downloaded to your notebook.

@elsaco I thought that at first too. But that article made it sound like the script tries a bunch of different domain names, and it's expected that some of them would fail to resolve. So I suspect it might still be possible that one or more of them have actually resolved successfully. Either way, I'd want to get that computer cleaned ASAP.

**Comment by zadjii-msft** [comment] 2022-11-28 12:45
Yea, this is definitely just caused by some external script that might have been trying to run secretly in the background before, but is appearing in a visible Terminal window now. 

Definitely get that PC checked out.

**Closed** 2022-12-05 16:03 UTC
Labels: Resolution-External, Needs-Author-Feedback, Needs-Triage, No-Recent-Activity, Needs-Tag-Fix

**Comment by Vyxxxx** [comment] 2022-12-17 23:12
How exactly do I remove this from my PC myself?

**Comment by SaintlySinner** [comment] 2023-01-23 01:28
I've been having the same exact issue, and am more that willing to participate if that means fixing the issue.

What the best way to go about posting a new thread that basically says "you see this link? Read through it, that's what's going down." cuz even the DNS host names that pop up in my terminal are the same hosts as this guy got.

**Comment by CAGAR-1** [comment] 2023-01-23 08:48
machkne ko ho testo randi ko xoro aaija srijanchowk ko ho

**Comment by dj-sash** [comment] 2023-02-18 04:57
Hi. Can we get a solution for that please?

**Comment by jmdv-es** [comment] 2023-02-24 17:16
Also happened to me today:

`Resolve-DnsName : wmail-endpoint.com : El nombre DNS no existe
En línea: 8 Carácter: 16
+         $dns = Resolve-DnsName -Name $hostname -Type 'TXT'
+                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (wmail-endpoint.com:String) [Resolve-DnsName], Win32Exception
    + FullyQualifiedErrorId : DNS_ERROR_RCODE_NAME_ERROR,Microsoft.DnsClient.Commands.ResolveDnsName

Resolve-DnsName : wmail-blog.com : Error de servidor DNS
En línea: 8 Carácter: 16
+         $dns = Resolve-DnsName -Name $hostname -Type 'TXT'
+                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (wmail-blog.com:String) [Resolve-DnsName], Win32Exception
    + FullyQualifiedErrorId : RCODE_SERVER_FAILURE,Microsoft.DnsClient.Commands.ResolveDnsName

Resolve-DnsName : wmail-chat.com : Error de servidor DNS
En línea: 8 Carácter: 16
+         $dns = Resolve-DnsName -Name $hostname -Type 'TXT'
+                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (wmail-chat.com:String) [Resolve-DnsName], Win32Exception
    + FullyQualifiedErrorId : RCODE_SERVER_FAILURE,Microsoft.DnsClient.Commands.ResolveDnsName

Resolve-DnsName : bideo-blog.com : Error de servidor DNS
En línea: 8 Carácter: 16
+         $dns = Resolve-DnsName -Name $hostname -Type 'TXT'
+                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (bideo-blog.com:String) [Resolve-DnsName], Win32Exception
    + FullyQualifiedErrorId : RCODE_SERVER_FAILURE,Microsoft.DnsClient.Commands.ResolveDnsName

Resolve-DnsName : privatproxy-blog.com : Error de servidor DNS
En línea: 8 Carácter: 16
+         $dns = Resolve-DnsName -Name $hostname -Type 'TXT'
+                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (privatproxy-blog.com:String) [Resolve-DnsName], Win32Exception
    + FullyQualifiedErrorId : RCODE_SERVER_FAILURE,Microsoft.DnsClient.Commands.ResolveDnsName

Resolve-DnsName : privatproxy-cdn.com : Error de servidor DNS
En línea: 8 Carácter: 16
+         $dns = Resolve-DnsName -Name $hostname -Type 'TXT'
+                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (privatproxy-cdn.com:String) [Resolve-DnsName], Win32Exception
    + FullyQualifiedErrorId : RCODE_SERVER_FAILURE,Microsoft.DnsClient.Commands.ResolveDnsName

Resolve-DnsName : ahoravideo-chat.com : Error de servidor DNS
En línea: 8 Carácter: 16
+         $dns = Resolve-DnsName -Name $hostname -Type 'TXT'
+                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (ahoravideo-chat.com:String) [Resolve-DnsName], Win32Exception
    + FullyQualifiedErrorId : RCODE_SERVER_FAILURE,Microsoft.DnsClient.Commands.ResolveDnsName

Resolve-DnsName : fairu-blog.xyz : El nombre DNS no existe
En línea: 8 Carácter: 16
+         $dns = Resolve-DnsName -Name $hostname -Type 'TXT'
+                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (fairu-blog.xyz:String) [Resolve-DnsName], Win32Exception
    + FullyQualifiedErrorId : DNS_ERROR_RCODE_NAME_ERROR,Microsoft.DnsClient.Commands.ResolveDnsName

Resolve-DnsName : fairu-cdn.xyz : El nombre DNS no existe
En línea: 8 Carácter: 16
+         $dns = Resolve-DnsName -Name $hostname -Type 'TXT'
+                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (fairu-cdn.xyz:String) [Resolve-DnsName], Win32Exception
    + FullyQualifiedErrorId : DNS_ERROR_RCODE_NAME_ERROR,Microsoft.DnsClient.Commands.ResolveDnsName

Resolve-DnsName : bideo-blog.xyz : El nombre DNS no existe
En línea: 8 Carácter: 16
+         $dns = Resolve-DnsName -Name $hostname -Type 'TXT'
+                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (bideo-blog.xyz:String) [Resolve-DnsName], Win32Exception
    + FullyQualifiedErrorId : DNS_ERROR_RCODE_NAME_ERROR,Microsoft.DnsClient.Commands.ResolveDnsName

Resolve-DnsName : bideo-schnellvpn.xyz : El nombre DNS no existe
En línea: 8 Carácter: 16
+         $dns = Resolve-DnsName -Name $hostname -Type 'TXT'
+                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (bideo-schnellvpn.xyz:String) [Resolve-DnsName], Win32Exception
    + FullyQualifiedErrorId : DNS_ERROR_RCODE_NAME_ERROR,Microsoft.DnsClient.Commands.ResolveDnsName

Resolve-DnsName : privatproxy-chat.xyz : El nombre DNS no existe
En línea: 8 Carácter: 16
+         $dns = Resolve-DnsName -Name $hostname -Type 'TXT'
+                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (privatproxy-chat.xyz:String) [Resolve-DnsName], Win32Exception
    + FullyQualifiedErrorId : DNS_ERROR_RCODE_NAME_ERROR,Microsoft.DnsClient.Commands.ResolveDnsName

Resolve-DnsName : ahoravideo-blog.xyz : El nombre DNS no existe
En línea: 8 Carácter: 16
+         $dns = Resolve-DnsName -Name $hostname -Type 'TXT'
+                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (ahoravideo-blog.xyz:String) [Resolve-DnsName], Win32Exception
    + FullyQualifiedErrorId : DNS_ERROR_RCODE_NAME_ERROR,Microsoft.DnsClient.Commands.ResolveDnsName

Resolve-DnsName : ahoravideo-chat.xyz : El nombre DNS no existe
En línea: 8 Carácter: 16
+         $dns = Resolve-DnsName -Name $hostname -Type 'TXT'
+                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (ahoravideo-chat.xyz:String) [Resolve-DnsName], Win32Exception
    + FullyQualifiedErrorId : DNS_ERROR_RCODE_NAME_ERROR,Microsoft.DnsClient.Commands.ResolveDnsName

Resolve-DnsName : ahoravideo-cdn.xyz : El nombre DNS no existe
En línea: 8 Carácter: 16
+         $dns = Resolve-DnsName -Name $hostname -Type 'TXT'
+                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (ahoravideo-cdn.xyz:String) [Resolve-DnsName], Win32Exception
    + FullyQualifiedErrorId : DNS_ERROR_RCODE_NAME_ERROR,Microsoft.DnsClient.Commands.ResolveDnsName`

**Comment by jnvsonu52** [comment] 2023-03-20 09:37
I receive this same error today! Please someone tell us how to resolve this issue.

**Comment by Schalasoft** [comment] 2023-04-16 05:58
90% sure it is this: https://www.reddit.com/r/PowerShell/comments/zxguan/what_does_this_cmdlet_do_is_this_a_virusworm/

MalwareBytes should find it. If not find it in task manager by looking for an oddly named powershell file being run, check the ".ps1" file and its obfuscated, nuke it.

**Comment by carrierxx** [comment] 2023-04-16 20:25
It's a PowerShell.agent trojan. Kaspersky virus removal tool will clean it. Worked for me.

**Comment by Logappradeep-M** [comment] 2023-05-11 01:47
Hello. 
How to fix the issue
Windows terminal pops up sometime with certain codes on my laptop
Can we get a solution for that please?

**Comment by DHowett** [comment] 2023-05-11 03:33
We do not control what runs inside a console window (or a terminal window.) Please reach out to your IT administrator, the support center for your driver provider, or your nearest malware author depending on what the contents of the window say.
