### ISSUE TITLE
Windows Terminal doesn't allow Far Manager to handle Gr keys correctly

### ISSUE THREAD

**Issue by awson** [microsoft/terminal#13417] opened 2022-07-02 08:07 UTC
### Windows Terminal version

Both 1.13 and 1.14 preview

### Windows build number

10.0.22621.105

### Other Software

Far Manager 3.0.5866.0

### Steps to reproduce

Run Far Manager in Windows Terminal.

Press numpad `+` or `-` or `*`.

### Expected Behavior

Expect selection/deselection dialog appearance or toggle selection action.

### Actual Behavior

`+` or `-` or `*` is printed on command line.

**Comment by 237dmitry** [comment] 2022-07-02 10:07
There is not physical keyboard with full set of keys on my laptop . But  these hotkeys work with osk.exe (on-screen keyboard).
```
wt  1.14.1452.0
far 3.0.5988.0 x64
```

**Comment by lhecker** [comment] 2022-07-06 13:16
(FYI to others: `Gr` is `Ctrl` or `AltGr`. `+`/`-`/`*` are numpad keys.)

I can't reproduce the issue either using a ISO QWERTZ 105 keyboard (one that has a dedicated numpad).

**Comment by awson** [comment] 2022-07-07 02:59
> (FYI to others: `Gr` is `Ctrl` or `AltGr`. `+`/`-`/`*` are numpad keys.)
> 
> I can't reproduce the issue either using a ISO QWERTZ 105 keyboard (one that has a dedicated numpad).

Thanks, I've updated the description.

**Comment by awson** [comment] 2022-07-07 03:14
After 1 day attempt to use windows 11, I reverted back to 10 but didn't try the new terminal yet.

Now I've tried and see no problem.

Should I close this?

**Comment by zadjii-msft** [comment] 2022-07-26 10:59
Huh so, AltGr in Terminal on Windows 10 works fine, but not on Windows 11? That's definitely curious, but I'm not sure we'd be able to make more progress investigating without a live repro. I say we close this out for now - if this comes back when you update to Windows 11, then we can reopen and investigate more. Thanks!

**Closed by zadjii-msft** 2022-07-26 10:59 UTC
Labels: Issue-Bug, Needs-Triage, Needs-Tag-Fix

**Comment by eaexo** [comment] 2024-10-22 11:32
@zadjii-msft  I have the same issue on windows 11, Ctrl + ^ is expected to bring far manager to the root of the drive, but it is not working

**Comment by zadjii-msft** [comment] 2024-10-22 14:04
@eaexo I'd recommend filling out a new issue - this one's quite stale at this point. Thanks!
