### ISSUE TITLE
Menu, intuitive clipboard handling, settings dialog, find - all missing

### ISSUE THREAD

**Issue by Hermholtz** [microsoft/terminal#5064] opened 2020-03-21 21:41 UTC
# Description of the new feature/enhancement

Apart from profile list dropdown there's no menu whatsoever, for example from which I could select "Cut", "Copy", "Paste", "Select all", "Tools/Profiles", "Tools/Options" and more.

Configuring settings by editing JSON is so trendy (after 2010) but rubbish way of configuring software. I'm not opting into learning all possible configuration options. Either enrich default config file with all settings in comment so I can use them without searching the entire internet, or even better provide a dialog to configure it using mouse. It used to be easy to develop in the past, hope it's still like that.

There's no context menu when I select a portion of text and right click. Lame, but ok, for now.

It's not possible (or I can't discover how) to find text in terminal / in the scrollback buffer.

# Proposed technical implementation details (optional)

Look at Ubuntu terminal for settings dialog, context menu, features and general look and feel. Look at PuTTY for settings and menu. This thing here is written by 200 people intensely for more than half a year and yay we have tabs! But beyond that it's not too far from cmd.exe...

**Comment by DHowett-MSFT** [comment] 2020-03-21 22:19
Thanks for the suggestions!

Just a couple notes:
> written by 200 people intensely

The core team is four engineers; we're making the best of the absolute onslaught of feature requests we get here on a daily basis, so I'm going to point you to the existing issues for the ones you want. Subscribe to them for updates and click the :+1: button to lodge your support.

* Settings UI: #1564 
* Context menu: #3789 (on tab/application) and #3337 (in terminal)
* Find: press <kbd>Ctrl+Shift+F</kbd>

In light of that, I'm going to close this out out as a /dupe of #1564 #3789 and #3337.

**Closed by DHowett-MSFT** 2020-03-21 22:19 UTC
Labels: Issue-Feature, Needs-Tag-Fix, Needs-Triage
