### ISSUE TITLE
LInks (hyperlinks)

### ISSUE THREAD

**Issue by NathanCrotty** [microsoft/terminal#6119] opened 2020-05-21 23:53 UTC
In the [promotional](https://youtu.be/8gw0rXPMMPE?t=26) video for Windows terminal, it shows clickable links. I can't seem to get this working in my terminal. Is this an up and coming feature? I hope this comes as an update.

**Comment by DHowett** [comment] 2020-05-22 00:31
Thanks for the request! This is a /dupe of #574, which is on our backlog.

**Closed by DHowett** 2020-05-22 00:31 UTC
Labels: Issue-Feature, Needs-Tag-Fix, Needs-Triage
