### ISSUE TITLE
Hiding a command by setting its name to `null` doesn't work properly

### ISSUE THREAD

**Issue by DHowett** [microsoft/terminal#8402] opened 2020-11-25 20:26 UTC
> The documentation here states that assigning the value `null` to an action's `"name"` field will remove it from the command palette. As of version 1.4.3141.0 (the latest stable release at this writing), following these instructions has no discernible effect.
> _from @atimholt_

> Hmm. @carlos-zamora did we break some nullable settings in 1.4? This is before the JsonUtils changes in 1.5...
We should make sure we have tests covering this. 
> _from @DHowett_

From https://github.com/MicrosoftDocs/terminal/issues/189

**Comment by Don-Vito** [comment] 2020-12-03 08:00
@zadjii-msft - where was this filtering initially?

**Comment by carlos-zamora** [comment] 2020-12-03 19:39
Oh man. I completely missed responding to this in the docs repo. My bad!

@Don-Vito If you want to take a closer look at this, I'd guess the following places might be a good start:
- GlobalAppSettings::LayerJson() - we take the json and update our KeyMapping ([link](https://github.com/microsoft/terminal/blob/8d26f452784cead9fdc353211d3d66d7c27f1fc9/src/cascadia/TerminalSettingsModel/GlobalAppSettings.cpp#L305))
- KeyMapping::LayerJson() - we update our keymapping with each command/action ([link](https://github.com/microsoft/terminal/blob/8d26f452784cead9fdc353211d3d66d7c27f1fc9/src/cascadia/TerminalSettingsModel/KeyMappingSerialization.cpp#L95))

**Comment by DHowett** [comment] 2020-12-03 19:39
It is less likely that this is related to key bindings and more likely that it is related to not-key-bindings.

**Comment by Don-Vito** [comment] 2020-12-03 19:43
> 
> 
> Oh man. I completely missed responding to this in the docs repo. My bad!
> 
> @Don-Vito If you want to take a closer look at this, I'd guess the following places might be a good start:
> 
>     * `GlobalAppSettings::LayerJson()` - we take the json and update our KeyMapping ([link](https://github.com/microsoft/terminal/blob/8d26f452784cead9fdc353211d3d66d7c27f1fc9/src/cascadia/TerminalSettingsModel/GlobalAppSettings.cpp#L305))
> 
>     * `KeyMapping::LayerJson()` - we update our keymapping with each command/action ([link](https://github.com/microsoft/terminal/blob/8d26f452784cead9fdc353211d3d66d7c27f1fc9/src/cascadia/TerminalSettingsModel/KeyMappingSerialization.cpp#L95))

@carlos-zamora - yep.. I looked there earlier today.. but didn't find any special  treatment for name equals null.. neither in the latest version nor in the previous version.. so I was wondering if I am looking at the correct place or the filtering out done somewhere later on.

**Comment by Don-Vito** [comment] 2020-12-09 20:22
@zadjii-msft , @carlos-zamora - on the de-serialization level I see a special handling for null only for action name, and not command name as appears in documentation.
I looked in the history as well.. but didn't find any reference to command name even in the first commit that the palette was introduced. Any chance that the filtering was somewhere else?

**Comment by DHowett** [comment] 2020-12-09 20:47
So, the hiding probably happens when we request the name and it comes back as `null`, rather than during deserialization.

**Comment by Don-Vito** [comment] 2020-12-09 20:57
> 
> 
> So, the hiding probably happens when we request the name and it comes back as `null`, rather than during deserialization.

When we request the name it might be too late to hide, because at this stage if the "name" didn't exist we will use the one generated from the args. I consider to take an older release and debug it. I just wondered if @zadjii-msft could possibly remember where this filtering was.

**Comment by Don-Vito** [comment] 2020-12-10 18:44
@DHowett - apparently it is a duplicate of https://github.com/microsoft/terminal/issues/7441 from August. I suggest to track that task and close this one.

**Comment by zadjii-msft** [comment] 2020-12-11 14:30
Hey good call! Thanks for helping clean up the repo.

/dup #7441

**Closed by zadjii-msft** 2020-12-11 14:30 UTC
Labels: Area-CmdPal, Area-Settings, Issue-Bug, Needs-Triage, Priority-2, Product-Terminal
