### ISSUE TITLE
Open with Windows Terminal in the context menu

### ISSUE THREAD

**Issue by max-programming** [microsoft/terminal#6389] opened 2020-06-07 04:04 UTC
# Description of the new feature/enhancement
I like how Visual Studio Code and Git Bash have "open with" in the context menu so that we can open up any folder. It'll be nice if we also have that feature in the Windows Terminal.
![image](https://user-images.githubusercontent.com/51731966/83960023-b8b08a80-a8a1-11ea-8f73-aca2ca51c32d.png)
Like this

# Proposed technical implementation details (optional)
The user can open any folder with just right-clicking and clicking open with Windows Terminal. So that the user does not need to first open it up, then navigate to that folder via `cd folder`

It would be amazing if we have the open with command in the right-click context menu.

**Comment by DHowett** [comment] 2020-06-07 04:30
Thanks! This is a /dupe of #1060

**Comment by DHowett** [comment] 2020-06-07 04:31
That feature was just implemented and should be available soon

**Closed by DHowett** 2020-06-07 04:30 UTC
Labels: Issue-Feature, Needs-Tag-Fix, Needs-Triage

**Comment by max-programming** [comment] 2020-06-07 04:33
oh. Thanks

**Comment by SoulReaver-SS** [comment] 2020-06-17 06:24
@DHowett do we have ETA on the "soon"?
