### ISSUE TITLE
Arrow keys not working on Touchscreen (on-screen) keyboard

### ISSUE THREAD

**Issue by joscdk** [microsoft/terminal#7495] opened 2020-09-01 16:16 UTC
# Environment

```none
Windows build number: 10.0.20201.0
Windows Terminal version (if applicable): 1.3.2382.0
```

# Steps to reproduce
1. Open Windows Terminal Pre release on a computer with touch screen.
2. Popup the "on-screen" keyboard
3. Set the keyboard to "full size", to get arrow keys
4. Enter a command, try to click arrow left/right
5. Run the command and click up

This is tested both in PowerShell and WSL 2 through Windows Terminal

# Expected behavior

I would expect the arrow keys to work, for example for going back in command history, or to use arrow keys in Vim or similar.

# Actual behavior

The arrow keys is not working, nothing happens when you click them. You can try to open e.g. Windows PowerShell directly, where it will work.

**Comment by j4james** [comment] 2020-09-01 19:06
FWIW, the arrow keys on the on-screen keyboard work fine for me. I'm using the same terminal version as you, but I'm still on Windows build 10.0.18362.959 (I doubt that makes any difference though).

This might be a bit difficult to do if you only have the on-screen keyboard, but can you try holding down both <kbd>Alt</kbd> keys when opening a new tab - that should give you an extra debug pane that shows the input/output control sequences seen by the terminal. If you can get that working, see what shows up in that debug view when pressing the arrow keys.

**Comment by joscdk** [comment] 2020-09-01 21:08
@j4james hmm think you might have a point regarding the Windows version actually. I just tried the same on another machine running the same version of Windows, it still didn't work.
I then tried on my work laptop, running an older version of Windows 10 (19042.487) there the touch keyboard worked fine with arrow keys.

However on the newer windows versions, it works in PowerShell plain and not in Windows Terminal, so still think the issue is somewhere here, but at least it narrowed it down a bit.

I tried holding down both Alt keys, and it just opened a new pane, and not a new tab (no debug settings), is there another way to get the debug info, so i can try providing some more details? (Tried taking the default settings and still the same).

**Comment by DHowett** [comment] 2020-09-02 23:37
Oh, you will need to set the global setting `debugFeaturesEnabled` to `true` for the double-Alt thing to work. Sorry about that 😅

**Comment by codeman38** [comment] 2020-09-07 16:16
I'm also experiencing this issue on Windows 10 19041.450 - the arrow keys and Delete key in the on-screen keyboard seem to do nothing in Terminal version 1.2.2381.0.

Holding down both Alt keys on my physical keyboard while opening a tab just opens a new pane in the current tab, even if I've added `"debugFeaturesEnabled": true` to my config.

**Comment by j4james** [comment] 2020-09-07 19:26
I just checked my settings now, and I think it's actually meant to be `"debugFeatures": true`. Sorry about the confusion.

**Comment by joscdk** [comment] 2020-09-07 19:57
@j4james oh perfect, that worked. When i generally press the onboard keyboard, debug data is printed out. However when i press the arrow keys, nothing is printed. Based on what @codeman38 was writing, the same thing happens when clicking "Delete".

If you want a screen recording of it, just say so :)

**Comment by j4james** [comment] 2020-09-08 13:58
Thanks for the info. I don't think the screen recording will be necessary. I'm not sure what the problem is, though. It sounds like we might not be receiving keyboard events for those keys which would be weird. Hopefully one of the core devs will have a better idea of what is going wrong.

**Comment by Alovchin91** [comment] 2020-09-09 15:02
Got the same problem with arrow keys on my Surface Pro X.

Windows version: 10.0.19041.508
Terminal version: 1.2.2381.0 (Microsoft Store)

**Comment by AJFirewolf** [comment] 2020-09-12 02:54
Experiencing the same issue on my Surface Pro 7. On-screen arrow and delete keys do not respond in Windows Terminal. They behave as expected in other programs including native PowerShell and CMD.
Windows Terminal Version: 1.2.2381.0
Windows 10 Home 19041.508

**Comment by MohsenFayyaz89** [comment] 2020-09-12 04:25
Same here with Surface Pro 7, the on-screen arrow, and delete keys don't respond.

Windows 10 Home 18363,1082
Windows Terminal: 1.2.2381.0

**Comment by codeman38** [comment] 2020-09-14 14:47
Wondering whether #7438 (failure with virtual arrow keys via keyboard remapping) might be related to this - it feels extremely similar, and seems to have started failing around the same time.

**Comment by itskenny0** [comment] 2020-09-18 15:11
Same issue on my Lumia 950 XL running WT 1.2.200825001-release1.2 on Windows 10 Pro 19041.488.

**Comment by zadjii-msft** [comment] 2020-09-18 16:15
> on my Lumia 950 XL running WT

![image](https://user-images.githubusercontent.com/18356694/93620756-217ac900-f9a0-11ea-838f-7970832cd715.png)

![image](https://user-images.githubusercontent.com/18356694/93620789-2ccdf480-f9a0-11ea-8a85-d23af7f581ac.png)

**Comment by itskenny0** [comment] 2020-09-21 11:08
@zadjii-msft https://github.com/WOA-Project/WOA-Deployer-Lumia

**Comment by zadjii-msft** [comment] 2020-09-29 03:12
Huh, this is super bizarre. I wonder if this only repros on devices without a physical keyboard. The on-screen keyboard works fine for me on 1.4.x, and 10.0.20222.1001, but I'm on a Surface Laptop. 

I'll dig out my old surface pro 3 and see if that repros this.

**Comment by joscdk** [comment] 2020-09-29 06:46
@zadjii-msft even if i attach my keyboard to my surface go but uses the on-screen keyboard, it is the same :) .. I tried digging into the code, but didn't have enough free time to try debugging it unfortunately :/

**Comment by zadjii-msft** [comment] 2020-10-01 22:14
Huh so I just tested this out, and it's the damnedest thing. The on screen keyboard works just fine on both my SP3 and slaptop. HOWEVER, the arrow keys on the _touch_ keyboard on my SP3  don't work. I'm not sure how to get the touch keyboard to appear on my slaptop however.

@DHowett does someone on the team have a work surface pro that we could assign this bug to them? Is rather not try and install VS on that old SP3 lol.

My guess is the touch keyboard sends keys with scancode=0

**Comment by zadjii-msft** [comment] 2020-10-01 22:32
Oh how ho, I found a way!

https://support.microsoft.com/en-us/help/4028719/windows-10-open-the-touch-keyboard#:~:text=Select%20the%20Touch%20keyboard%20icon,d%20like%20to%20enter%20text.&text=If%20you're%20not%20seeing,select%20Show%20touch%20keyboard%20button.

I can debug this on my slaptop now 😊

**Comment by 2fst4u** [comment] 2020-10-25 03:47
Looks like you're already onto this but I'm just here after googling for a solution after my Surface Go's keyboard broke and I couldn't use my onscreen arrows 😂.

It would be awesome to get them working.

**Closed** 2020-10-27 19:06 UTC
Labels: Area-Input, Help Wanted, In-PR, Issue-Bug, Priority-2, Product-Terminal
