### ISSUE TITLE
Titlebar design

### ISSUE THREAD

**Issue by Mystic8b** [microsoft/terminal#6384] opened 2020-06-06 13:55 UTC
# Description of the new feature/enhancement
Titlebar looks frankly bad. It’s so bad that I’m ready to use alternative terminals where the mouse doesn’t work in mc, etc., but it’s not painful for my eyes to look at them.

And if you turn on the acrylic - it gets even worse. Titlebar doesn't mix with absolutely anything! It should have the same color (and transparency if enabled) as the main window.

![image](https://user-images.githubusercontent.com/35394377/83945954-8f96e800-a816-11ea-9beb-d37d47062e18.png)

Are you planning to do something with this?

**Comment by j4james** [comment] 2020-06-06 16:47
Having the titlebar match the main window color is covered by issue #3774. The rounded corners on the tabs are apparently the new standard for the Windows UI (see issue #3084). I'm not exactly sure what you're asking about the tab color, but I believe there are already issues discussing options for configuring tab colors.

In you aren't aware, Github has a search box (in the top left of the interface) which you can use to look for existing issues that may already cover the feature you are requesting.

**Comment by Mystic8b** [comment] 2020-06-06 17:01
Sorry, I tried to find a similar issue, but failed.
[This](https://github.com/microsoft/terminal/issues/3774#issuecomment-609408305) option looks fantastic, I really hope that it will be so, plus when you turn on the acrylic, the effect should also apply to titlebar. I will be just happy. I look forward to it.
Thank.

**Comment by j4james** [comment] 2020-06-06 17:12
> [This](https://github.com/microsoft/terminal/issues/3774#issuecomment-609408305) option looks fantastic, I really hope that it will be so, plus when you turn on the acrylic, the effect should also apply to titlebar.

I believe the plan is to have this work with acrylic as well. Issue #4744 covered the technical enhancement needed to make that happen.

**Comment by Mystic8b** [comment] 2020-06-06 17:15
I really hope so.
Thanks again for your time.

**Comment by DHowett** [comment] 2020-06-06 20:14
Thanks for voicing your concern, and thanks James for first line triage. In general, we aren’t going to keep issues open that are just discussion magnets (and asking “are you planning to do anything about this?” without too much constructive content is definitely argument bait)... so I’m gonna close this out as a /dupe of #1375; that issue is where we have been concentrating the multiple hundreds of comments, complaints and concerns about our UI.

**Closed by DHowett** 2020-06-06 20:14 UTC
Labels: Issue-Feature, Needs-Tag-Fix, Needs-Triage
