### ISSUE TITLE
Allow defining menu item actions for right click on terminal tab (paste, splitPane, etc)

### ISSUE THREAD

**Issue by nlaredo** [microsoft/terminal#8703] opened 2021-01-04 21:49 UTC
# Description of the new feature/enhancement
Allow defining menu item actions for right click on terminal tab (paste, splitPane, etc)

# Proposed technical implementation details (optional)
Allow user to add actions to the menu that currently pops up when a tab is right clicked (currently Color, Rename Tab, Close) and show any key bound to the action as well, for example:

```
"Paste          ctrl+v"
"Find           ctrl+shift+f"
"splitPane      alt+shift+d"
```

This will allow the user to bind actions to menu items (automatically created for any command in the actions section of the config) to reclaim key sequences like ctrl+v for other tasks and use the right click menu to accomplish the same task while the configured command is bound to some undesirable key sequence like shift+insert.   It will also provide an easy quick reference to the configured key bindings for the user.

**Comment by zadjii-msft** [comment] 2021-01-05 17:40
You know, there's gotta be a dupe of this somewhere on the repo. I've already mentioned doing this in a spec, so it's definitely a good idea. I think I mentioned it in #7175 and  #5888.  If I can't find the dupe, we can just use this thread to track it.

**Comment by Don-Vito** [comment] 2021-01-05 18:43
@zadjii-msft - we also had this discussion: https://github.com/microsoft/terminal/issues/8318#issuecomment-730307702.

**Comment by DHowett** [comment] 2021-01-28 02:18
Found it! /dup #1912! It was the original request for a context menu, and I think it is the appropriate place to track a _customizable_ one since we absolutely do have a plain one today.

**Closed by DHowett** 2021-01-28 02:18 UTC
Labels: Area-Settings, Issue-Feature, Needs-Triage, Product-Terminal
