### ISSUE TITLE
razzle doesn't support VS 2017 Professional

### ISSUE THREAD

**Issue by f0ff886f** [microsoft/Terminal#484] opened 2019-05-07 09:19 UTC
`razzle.cmd` only checks Community and Enterprise paths of VS2017 to find `msbuild`.

Simply adding another two `if` blocks for checking `%ProgramFiles%\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\Bin\msbuild.exe` and `%ProgramFiles(x86)%\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\Bin\msbuild.exe` fixes the issue.

**Comment by DHowett-MSFT** [comment] 2019-05-09 04:02
This'll be fixed by #606, so I'm going to close it as a duplicate of some of the other razzle.cmd issues for consolidation. #583 #474 #591 #436

**Closed by DHowett-MSFT** 2019-05-09 04:02 UTC
