### ISSUE TITLE
Can not type anything

### ISSUE THREAD

**Issue by Slighti** [microsoft/terminal#7402] opened 2020-08-25 19:55 UTC
I'm on latest win10 2004 release, I can't write anything.

**Comment by zadjii-msft** [comment] 2020-08-25 20:20
By any chance, do you have the "Touch Keyboard and Handwriting Panel Service" disabled?

**Comment by Slighti** [comment] 2020-08-26 10:31
> By any chance, do you have the "Touch Keyboard and Handwriting Panel Service" disabled?

Just enabled but still same

**Comment by zadjii-msft** [comment] 2020-08-26 11:09
@Slighti Did you reboot your machine after re-enabling the service?

**Comment by Slighti** [comment] 2020-08-26 18:47
> @Slighti Did you reboot your machine after re-enabling the service?

same

**Comment by zadjii-msft** [comment] 2020-08-27 00:55
Alright well, can we get some additional information:

* what version of the Terminal are you using?
* Can you not type in one specific shell in the Terminal, or are all tabs affected?
* Can you type in the vintage console? i.e. `cmd.exe`, `powershell.exe`, or `wsl.exe`?
* Can you type in any other UWP applications, like the Calculator, Feedback Hub?

**Comment by flocc** [comment] 2020-08-27 06:21
Same here,
>     * what version of the Terminal are you using?
1.2.2381.0
>     * Can you not type in one specific shell in the Terminal, or are all tabs affected?
all shells are affected
>     * Can you type in the vintage console? i.e. `cmd.exe`, `powershell.exe`, or `wsl.exe`?
yes
>     * Can you type in any other UWP applications, like the Calculator, Feedback Hub?
yes

**Comment by Slighti** [comment] 2020-08-27 12:25
I can not enable that service, I can set automatic start but can't enable

**Comment by Slighti** [comment] 2020-08-27 12:39
did much thing which I'm not sure but succesfull, I can type finally :)

**Comment by zadjii-msft** [comment] 2020-08-27 12:54
Alright well, since there's nothing else to follow up on here, I'm gonna close this as a dupe of #4448. Thanks for following up!

**Closed by zadjii-msft** 2020-08-27 12:54 UTC
Labels: Needs-Attention, Needs-Tag-Fix, Needs-Triage
