### ISSUE TITLE
Terminal force closes with ssh session and multiple screens

### ISSUE THREAD

**Issue by ihor-sviziev** [microsoft/terminal#3385] opened 2019-10-31 08:18 UTC
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18362.449]
Windows Terminal version (if applicable): 0.6.2951.0
```
Link to Feedback: https://aka.ms/AA6f0m9

# Prerequisites 
1. 3 monitors, 1st and 2nd -with Full HD resolution and 100% scaling, 3rd - 2550x1440 and 150% scaling
2. Installed Ubuntu 18.04 WSL

# Steps to reproduce
1. Open WSL Ubuntu 18.04 in Windows Terminal, keep it in screen 1 or 2 (with 100% scaling)
2. connect to via ssh to any server (tried to connect to Amazon Linux)
3. Move Windows Terminal to 3rd screen (with 150% scaling)
4. Wait 3 seconds
5. Move Windows Terminal to 2nd screen (with 100% scaling)

# Expected behavior
Loading indicator is shown, in few seconds terminal is closed

# Actual behavior
Terminal should continue working without any issues

Note: on "Ubuntu 18.04 LTS" app this issue isn't reproducing

**Comment by benfulton** [comment] 2019-10-31 18:33
I can reproduce this with two monitors and without connecting via ssh. I have Ubuntu 18.04 as my default terminal.

**Comment by DHowett-MSFT** [comment] 2019-10-31 19:41
This sounds like a /dupe of #3303. Thanks!

**Closed by DHowett-MSFT** 2019-10-31 19:41 UTC
Labels: Needs-Tag-Fix, Needs-Triage
