### ISSUE TITLE
Install  Oh My Posh error:  Oh My Posh is unable to download and store the latest version and The term 'Set-PoshPrompt' is not recognized as a name of a cmdlet, function, script      | file, or executable program

### ISSUE THREAD

**Issue by thanhkt07** [microsoft/terminal#11942] opened 2021-12-15 08:28 UTC
I have install git-posh and oh-my-posh:
`Install-Module git-posh -Scope CurrentUser -Force`
`Install-Module oh-my-posh -Scope CurrentUser -Force`
This is $PROFILE:
![image](https://user-images.githubusercontent.com/89201988/146150806-91c6ddf1-92e4-4a6f-9f97-b0224fc58a04.png)
This is error:
![image](https://user-images.githubusercontent.com/89201988/146150884-149a58e3-b132-4de2-9312-06351880a919.png)

**Comment by thanhkt07** [comment] 2021-12-15 12:47
> Which version of oh-my-posh are you using? This is kinda the inverse of #9237. You may want to try `Set-Theme` instead of `Set-PoshPrompt`.
> 
> There's also a TON of discussion over on our docs repo: https://github.com/MicrosoftDocs/terminal/issues?q=is%3Aissue+label%3Apowerline+

I want to fix the first error:  Oh My Posh is unable to download and store the latest version

**Comment by thanhkt07** [comment] 2021-12-15 13:14
I install oh-my-posh version 2.0.412 and i fix the second error.
The first error is very suck

**Comment by zadjii-msft** [comment] 2021-12-15 14:01
Is your current account an admin account? Did you try running `Import-Module oh-my-posh` as an admin?

**Comment by lujomu** [comment] 2021-12-22 08:02
Got the same error.

In my case the problem is, I have the PSCX module (https://github.com/Pscx/Pscx) installed, which exports its own 'Expand-Archive' command and occludes the built-in one from the Microsoft.PowerShell.Archive module.

    PS D:> Get-Command 'Expand-Archive'
    
    CommandType     Name                Version    Source
    -----------     ----                -------    ------
    Cmdlet          Expand-Archive      3.3.2      Pscx

Apparently the name clash will be resolved int the next release (https://github.com/Pscx/Pscx/blob/master/ReleaseNotes.txt).

In the meantime, importing the Microsoft.PowerShell.Archive module right before invoking/importing oh-my-posh should work around this issue.

**Closed** 2021-12-29 19:01 UTC
Labels: Issue-Docs, Needs-Author-Feedback, Needs-Triage, No-Recent-Activity, Needs-Tag-Fix
