### ISSUE TITLE
Bug Report - FarManager Mouse events issue

### ISSUE THREAD

**Issue by Viaun** [microsoft/terminal#1975] opened 2019-07-15 12:43 UTC
# Environment
Terminal Version: 0.2.1831.0
Windows 10 Enterprise V1903, OS build 18362.30,
FarManager 3.0 build 5354 x64

# Steps to reproduce
1. Open FarManager in Windows Terminal.
2. Press 'Ctrl+o' to switch to panel view.
3. Try to click with mouse on files or folders elements.

# Expected behavior
FarManager should get onClick event end perform some action (open clicked folder/file)

# Actual behavior
Caret is placing in a clicked place but FarManager doesn't take any action.

**Comment by zadjii-msft** [comment] 2019-07-15 18:45
This is going to be a dupe of #545.

**Closed** 2019-07-16 19:00 UTC
Labels: Needs-Triage, Resolution-Duplicate

**Comment by d3x0r** [comment] 2020-11-06 17:48
This isn't fixed though; apparently it wasn't a duplicate.  Reading #545 I only see support for WSL terminals; FAR is a windows console app; I also have an editor (EFTE) which also doesn't get mouse input when run in microsoft terminal.

**Comment by DHowett** [comment] 2020-11-06 18:20
Apologies -- we mistargeted the dupe here. It's actually #376, which tracks getting _windows_ applications that require mouse input working.
