### ISSUE TITLE
Drag and drop files does not work in right/bottom areas with >100% DPI scaling

### ISSUE THREAD

**Issue by jingyu9575** [microsoft/terminal#4567] opened 2020-02-13 18:45 UTC
# Environment

```none
Windows build number: 10.0.18363.0
Windows Terminal version (if applicable): 0.9.433.0

Any other software?: No
```

# Steps to reproduce

1. In Windows display settings, select 150% DPI scaling;
2. Drag a file to the terminal, at the bottom or right inside the window.

# Expected behavior

Tooltip shows "copy path to file". The file path is inputed.

# Actual behavior

Nothing. Tooltip shows "🚫". This screenshot was made with a CI build right after  drag/drop was implemented, but the same behavior happens in today's release.

On my system with 150% DPI scaling, the size of the acceptable area seems to be `1/(150%)` of the window (similar to #2606). Also, some bottom area in the tabs is (incorrectly) acceptable to drops, and the height seems to be also `1/(150%)` of the tab bar. Therefore I suspect some code is checking the acceptable area but is missing a `DPI/96` factor.

![Screenshot](https://user-images.githubusercontent.com/8923139/73556567-f747bb80-444f-11ea-98e4-51f8114e1162.gif)

**Comment by DHowett-MSFT** [comment] 2020-02-14 01:01
This looks _suspiciously_ like #2606... It looks like they both deal with xaml control hit-testing zones! So alike they are that I'm going to call this one a /dupe of #2606. :smile:

Thanks for the report!

**Closed by DHowett-MSFT** 2020-02-14 01:01 UTC
Labels: Needs-Tag-Fix, Needs-Triage
