### ISSUE TITLE
WSL terminal not available sometimes in "New Tab" dropdown on start-up

### ISSUE THREAD

**Issue by ophers** [microsoft/terminal#7199] opened 2020-08-06 12:38 UTC
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18363.959]
Windows Terminal version (if applicable): 1.1.2021.0

Any other software? Yes
Ubuntu-20.04
```

# Steps to reproduce

Start-up Windows Terminal normally, i.e. Click on the pinned Task-Bar icon

# Expected behavior

The "New Tab" dropdown should list "Ubuntu-20.04"

# Actual behavior

The "New Tab" dropdown doesn't list "Ubuntu-20.04". To get it listed I need to perform the following:
1. Open Settings, i.e. from the dropdown menu.
    Visual Studio opens with the settings.json file.
2. Make a benign change, i.e. add a space and delete it, and save.
3. Now Windows Terminal lists "Ubuntu-20.04" under the "New Tab" dropdown (no closing reopening necessary).

**Comment by LuanVSO** [comment] 2020-08-06 23:58
this repro to me if I open wt when WSL is booting up

**Comment by zadjii-msft** [comment] 2020-08-07 13:29
Yea, we're definitely getting some recurring issues where if WSL is slow to start up, the profiles aren't detected correctly. Maybe there's a better way we can do the auto-detection than using `wsl -l`, because that seems pretty fragile. 

There's more info in #6946, including some workarounds you can use.

@benhillis is there any way that we could get the list of WSL distros without having to wait for the WSL service to start?

**Comment by DHowett** [comment] 2020-08-13 01:24
Yanking triage. This isn't something readily fixable, but... here's a thought.

@zadjii-msft what if we cache the output of the most successful run of wsl.exe (heck, we could even use JSON) and use that _if and only if_ it doesn't respond? That way we get a continuity behavior and don't run the risk of leaving dead/old WSL installations in the list...

**Comment by zadjii-msft** [comment] 2020-08-13 13:57
Wait but, what would happen of the _very first_ launch after a user installs WSL and a distro? We'd have nothing cached, WSL wouldn't be running yet, so this "cache" wouldn't have any distros listed, and it wouldn't help. 

Or if someone closes the terminal, closes all their WSL instances, then uninstalls one, and reboots. The WSL service isn't running, but our cache still has the uninstalled distro listed, so we can't trust that.

**Comment by DHowett** [comment] 2020-08-13 14:35
The cache isn’t used “when WSL isn’t running”, it’s used when WSL doesn’t respond to our request for distros in a timely manner. It seems to do that reasonably often, judging by these reports. In the vast majority of cases, it would operate just like it does today: `wsl -l` would not spontaneously hang, and it would return the distribution list and we wouldn’t even hit the fallback list.

**Comment by DHowett** [comment] 2020-08-13 14:36
So it’s less of a cache and more of a “last known good state, please use in case of emergency.” If the user _just installed_ a distribution and WSL is unable to enumerate it, I’d venture that they have MUCH bigger problems than “terminal can’t find it.” 😄

**Comment by zadjii-msft** [comment] 2020-10-19 17:09
As noted in #7965, this might actually be #6160. @DHowett thoughts on resolving as a dupe?

**Comment by vadimkantorov** [comment] 2020-10-19 17:09
@zadjii-msft pointed me to this issue (mine was duplicate). duplicating my comment/proposal here :)

Duplicate of #6160?

It could be that just CPU is busy: I'm loading a big Chrome process at the same time. But even if CPU is buys / WSL is slow to respond, it should not throw this error or discard a profile from the list (even if WSL is slow or does not respond). Maybe it should ask the user if I want to retry or maybe show some welcome "no terminal opened" screen instead (e.g. Speed Dial like in browsers)

**Closed** 2021-08-24 13:10 UTC
Labels: Issue-Bug, Area-Settings, Product-Terminal, In-PR, Priority-2
