### ISSUE TITLE
Consider making Windows Terminal the default terminal in Windows

### ISSUE THREAD

**Issue by nitishvijai** [microsoft/terminal#7277] opened 2020-08-13 18:56 UTC
# Description of the new feature/enhancement

By including Windows Terminal by default in Windows 10 and making it the default, this will be less of a hassle for developers. Especially considering that they currently have to download it from GitHub or the Store, it will take less time if Terminal is included by default in Windows.

# Proposed technical implementation details (optional)

By including Windows Terminal by default, CMD and PowerShell can still be kept in Windows (albeit used only for batch scripts, etc.), now that their functionality is in Windows Terminal.

**Comment by DHowett** [comment] 2020-08-13 19:00
Thanks for the request. This is a /duplicate of #492.

(Windows Terminal is not a replacement for CMD, but that is beside the point.)

**Closed by DHowett** 2020-08-13 19:00 UTC
Labels: Issue-Feature, Needs-Tag-Fix, Needs-Triage
