### ISSUE TITLE
Prompt issue after invoking "clearBuffer"

### ISSUE THREAD

**Issue by elsaco** [microsoft/terminal#11592] opened 2021-10-23 20:16 UTC
### Windows Terminal version (or Windows build number)

Windows Terminal Preview ver. 1.12.2931.0

### Other Software

Windows 10 ver. 10.0.19043.0
git ver. 2.33.0.windows.2

### Steps to reproduce

1. add an unbound key cord to settings.json and enable clearBuffer (crtl+shift+k in this case)

```
        {
           "command":
           {
             "action": "clearBuffer",
             "clear": "all"
           },
           "keys": "ctrl+shift+k"
          
        }
```

2. fill buffer then invoke clearBuffer

### Expected Behavior

1. buffer cleared (it works!)

### Actual Behavior

1. after clearing the buffer the prompt is at the top of tab, however next input is shown at the bottom of tab.
2. not git related as it happens with other commands

Example:

https://user-images.githubusercontent.com/3933920/138570174-62dbf11b-3d1f-4a66-927e-d0a7f2e7c3cf.mp4

**Comment by pcbeard** [comment] 2021-11-23 16:36
Just reproduced this issue myself using the [preview build](https://www.microsoft.com/store/apps/9n8g5rfz9xk3?cid=storebadge&ocid=badge). Clearly the cursor position isn't being reset.

**Comment by DHowett** [comment] 2021-11-23 16:56
PowerShell caches the cursor position every time it displays the prompt, and then after we reset the screen it _moves the cursor back_. This is effectively a /duplicate of https://github.com/PowerShell/PSReadLine/issues/964

**Closed by DHowett** 2021-11-23 16:56 UTC
Labels: Needs-Triage, Needs-Tag-Fix

**Comment by pcbeard** [comment] 2021-11-23 17:03
Interestingly enough, if you use the "cls" command in PowerShell or cmd, the right thing happens.

**Comment by DHowett** [comment] 2021-11-23 17:21
@pcbeard indeed. Since `cls` (or `Clear-Host`) is implemented by PowerShell¹, it executes between prompts. Once it returns, it caches the new correct position. Under the hood, Terminal is pretty much doing exactly the same thing: emitting a sequence that requests that the screen be cleared².

Unfortunately, applications aren't designed to _receive_ this sequence, only to send it. PowerShell doesn't actually handle `\e[2J` as input -- if you send it, it's not going to do anything with it. This is true of other shells, as well--bash, cmd (especially), fish, ...--as they do not expect to receive the "Erase in Display" control sequence as input. It's officially "not their job" to handle it, and so handle it they don't.

It turns out that there's no general way to tell an application that its screen has been cleared and that it needs to recalculate any positions it might have stored³. ☹️ 

¹ This issue doesn't seem to exist in cmd; it doesn't track the cursor position!
² To a rough first approximation.
³ @zadjii-msft . . . what if we pretend the window size changed when we Clear Buffer? How crazy would that be? It might also fix vim (!) though admittedly, I expect that one of the eight layers between us and vim would filter out a `SIGWINCH` where the sizes _haven't actually changed_...

**Comment by zadjii-msft** [comment] 2021-11-23 17:33
> what if we pretend the window size changed when we Clear Buffer? How crazy would that be? It might also fix vim (!) though admittedly, I expect that one of the eight layers between us and vim would filter out a `SIGWINCH` where the sizes _haven't actually changed_...

as someone who's written a _lot_ of our code that filters out size changes when the sizes haven't actually changed, ~I'd expect that it would get filtered~

Actually who am I kidding. Considering the number of times I have had to write that code, I'd reckon there's a good opening here that might just work
