### ISSUE TITLE
keep the same path after switching from powershell to command prompt

### ISSUE THREAD

**Issue by Cortana-117** [microsoft/terminal#11774] opened 2021-11-17 21:36 UTC
# Description of the new feature/enhancement

# Proposed technical implementation details (optional)

When I open PowerShell by right-clicking in a folder, it opens in that path, but then when i switch to Command Prompt, it starts from User folder.

I want Windows Terminal to keep the same path after opening Command Prompt or other terminals from the tabs and not switch to their default path. so if i'm working with PowerShell in a specific directory and then open CMD from the same Terminal window, I want PowerShell to pass the current working directory to the CMD.

at least provide this as an option in Windows Terminal settings.

I'm using Windows 11 insider beta and the built-in Windows Terminal 

Thanks

**Comment by zadjii-msft** [comment] 2021-11-17 22:52
Amassing notes here before the end of the day:

* https://github.com/microsoft/terminal/issues/3158#issuecomment-764003033
* #10940
* #8933
* #9991
* #10614
* https://github.com/microsoft/terminal/issues/10105#issuecomment-842231981


I'll come through and turn that into an actual reply tomorrow morning

**Comment by aungthanlwin** [comment] 2021-11-17 23:08
There is a workaround for this. You can use the "." (dot) notation to pass the current working directory to command prompt. For example, when you're in windows powershell, you can start command prompt with the command  "start cmd ."

**Comment by tajetaje** [comment] 2021-11-19 02:08
> There is a workaround for this. You can use the -d option and "." (dot) notation to pass the current working directory to command prompt. For example, when you're in windows powershell, you can start command prompt with the command “wt -w 0 -p “Command Prompt” -d .” or "start cmd ."

I think OP is referring to opening new profiles after running windows terminal from file explorer's context menu

**Comment by zadjii-msft** [comment] 2021-11-23 22:00
Okay, so lemme get this stright

1. You right click in explorer (in `c:\foo`), and "open Windows Terminal here"
2. You get a PowerShell tab in `c:\foo`
3. You open a new Command Prompt tab, via the new tab menu or the command palette or whatever
4. it opens in `whatever cmd.exe's startingDirectory is set to`

and you want step 4 to open in `c:\foo`. Originally, I thought we were tracking this in #8933, but that only applied when the `startingDirectory` is set to `.`. 

Now, I think you're going to have to do the [OSC9;9 thing](https://github.com/MicrosoftDocs/terminal/pull/449/files) to emit the working directory, and then wait for #10232 to allow opening a tab/pane with the same directory, but a different profile. 

Do I have that right? If so, I'm gonna call this one a duplicate of #10232.

**Comment by Cortana-117** [comment] 2021-11-24 11:06
> Okay, so lemme get this stright
> 
> 1. You right click in explorer (in `c:\foo`), and "open Windows Terminal here"
> 2. You get a PowerShell tab in `c:\foo`
> 3. You open a new Command Prompt tab, via the new tab menu or the command palette or whatever
> 4. it opens in `whatever cmd.exe's startingDirectory is set to`
> 
> and you want step 4 to open in `c:\foo`. Originally, I thought we were tracking this in #8933, but that only applied when the `startingDirectory` is set to `.`.
> 
> Now, I think you're going to have to do the [OSC9;9 thing](https://github.com/MicrosoftDocs/terminal/pull/449/files) to emit the working directory, and then wait for #10232 to allow opening a tab/pane with the same directory, but a different profile.
> 
> Do I have that right? If so, I'm gonna call this one a duplicate of #10232.

Yes you got it right, I want it exactly like that.
thank you

**Comment by zadjii-msft** [comment] 2021-11-24 12:59
Awesome, thanks!

/dup #10232

**Closed by zadjii-msft** 2021-11-24 13:00 UTC
Labels: Issue-Feature, Needs-Triage, Needs-Attention, Needs-Tag-Fix
