### ISSUE TITLE
Updated while it was running, lost a lot of my work.

### ISSUE THREAD

**Issue by revantjhalani** [microsoft/terminal#10398] opened 2021-06-10 19:05 UTC
### Windows Terminal version (or Windows build number)

1.8.1521.0

### Steps to reproduce

IT UPDATED AUTOMATICALLY 

### Actual Behavior

The terminal updated and all my tabs with multiple builds going on, all closed

**Comment by j4james** [comment] 2021-06-10 21:20
This problem is being tracked in issue #3915. There's also a comment there explaining how you can run the app without using the Microsoft Store.

**Comment by skyline75489** [comment] 2021-06-10 23:12
Thanks guys for the report. sorry for the inconvenience caused by forcefully close your terminal.

I’ll close this issue and redirect the discussions to #3915.

**Closed by skyline75489** 2021-06-10 23:12 UTC
Labels: Needs-Tag-Fix, Needs-Triage
