### ISSUE TITLE
Support for "session"

### ISSUE THREAD

**Issue by dov** [microsoft/terminal#9197] opened 2021-02-18 08:15 UTC
# Description of the new feature/enhancement

Mostly, when I run terminal I start with opening a fixed set of tabs, each in a different directory, and each with a different a different title. I'd like a way to automize this.

# Proposed technical implementation details (optional)

I suggest that you add to Terminal command line an option to take a json file with the requested layout.

**Comment by skyline75489** [comment] 2021-02-18 08:24
Would you be satisfied by the solution mentioned in https://github.com/microsoft/terminal/issues/9101#issuecomment-777034523 ?

**Comment by dov** [comment] 2021-02-18 08:36
> Would you be satisfied by the solution mentioned in [#9101 (comment)](https://github.com/microsoft/terminal/issues/9101#issuecomment-777034523) ?

That indeed looks promising! It is not clear whether it is possible to do a cd to a different directory through that approach though.

**Comment by skyline75489** [comment] 2021-02-18 08:58
That's largely related to the shells. For example with `pwsh.exe` you can use:

```text
wt new-tab pwsh.exe -WorkingDirectory D:
```

**Comment by skyline75489** [comment] 2021-02-18 09:01
By the `wt` way is actually working with 1.5. You'll need to wait for 1.6 to use the `startupActions`. Follow #756 for future updates on this topic.

**Comment by zadjii-msft** [comment] 2021-02-18 12:16
So for reference, I like to do like the following each time I boot up the Terminal in the morning:

```json
{ "command": { "action": "wt", "commandline": "new-tab --title OpenConsole cmd.exe /k #work 15 ; split-pane -s .30 --title OpenConsole cmd.exe /k #work 15 ; split-pane  -s .25 -H cmd.exe /k media ; new-tab --title \"Symbols Script\" powershell dev\\symbols.ps1 ; new-tab -p \"Ubuntu 18.04\" ; new-tab -p \"microsoft/Terminal\" ; sp -V -p \"microsoft/Terminal\" ; sp -H -p \"microsoft/Terminal\" ; focus-tab -t 0" }, "name": "Good Morning" },

```

(you could probably make it shorter by replacing `new-tab`/`split-pane` with `nt`/`sp`, respectively).

I add that to the `keybindings`/`actions`. This creates a new command in the [Command Palette](https://docs.microsoft.com/en-us/windows/terminal/command-palette) named "Good Morning". That opens up a few tabs & panes, running various build environments. I like having it in a command rather than `startupActions`, because I only really want this in _one_ terminal window, not _every single one I launch_. It's personal taste. 

You could repeat this for multiple different "session"s if you wanted. That way you could have layouts pre-defined for various different dev environments. 

We're also tracking adding commands to the new tab dropdown in #1571. Largely, I'm going to call this ask a duplicate of both #756 and #1571. 

/dup #756
/dup #1571

**Closed by zadjii-msft** 2021-02-18 12:16 UTC
Labels: Issue-Feature, Needs-Tag-Fix, Needs-Triage
