### ISSUE TITLE
No "Open in Windows" Terminal for the Desktop

### ISSUE THREAD

**Issue by Zingam** [microsoft/terminal#7230] opened 2020-08-09 06:42 UTC
One would expect to have this option for the Desktop (folder) tool. It isn't available in the right-click menu even when Shift+Right Click (only `Open Power Shell window here` and `Open Linux shell here` - Windows Terminal could have also an option to disable these other options when it is installed too).

**Comment by zadjii-msft** [comment] 2020-08-10 13:11
I wonder if this isn't related to #6414. Maybe the desktop is just treated as a "directory background", which we had to disable...

If it's not, then good catch on this not working on the Desktop!

**Comment by DHowett** [comment] 2020-08-10 19:19
This is, unfortunately, a /duplicate of #6414. Sorry!

**Closed by DHowett** 2020-08-10 19:20 UTC
Labels: Area-ShellExtension, Issue-Bug, Needs-Triage, Priority-3, Product-Terminal
