### ISSUE TITLE
Windows Terminal Preview consistently crashes when closing panes in certain layouts

### ISSUE THREAD

**Issue by itszn** [microsoft/terminal#17354] opened 2024-06-02 00:27 UTC
### Windows Terminal version

1.21.1272.0

### Windows build number

Microsoft Windows [Version 10.0.22631.3672]

### Other Software

```
> wsl --version
WSL version: 2.1.5.0
Kernel version: 5.15.146.1-2
WSLg version: 1.0.60
MSRDC version: 1.2.5105
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22631.3672

> wsl --list
Windows Subsystem for Linux Distributions:
Ubuntu-20.04 (Default)
```
`OpenSSH_8.2p1 Ubuntu-4, OpenSSL 1.1.1f  31 Mar 2020` running inside WSL connecting to my host

### Steps to reproduce

Crash report:
https://aka.ms/AAqonu3

# Reproduce

Open a new fresh terminal session. Then split once vertically. Then split the new pane vertically again. Now the middle pane will crash when closed and crash the whole terminal.

https://github.com/microsoft/terminal/assets/1857794/a7500464-875b-4584-a55c-cdf4d9cfa597

# My Experience With The Bug

Very often, when using the terminal, I end up with several terminal panes which are in this state, such that when they are closed they crash the entire terminal.

This seems to only happen when they are in certain positions, ie have a pane on either side, and if I close the ones around it, it often fixes itself.

In this video I am showing how exiting specific panes will crash the terminal, while exiting the other panes does not crash it.

I also show how closing enough of the other panes fixes the issue, and also moving the pane to a new tab fixes the issue (for that single pane).

https://github.com/microsoft/terminal/assets/1857794/de269f33-e399-4ae3-a6f3-943fb8ebafe6

Also bc the state of the panes is saved on close, when I reopen the terminal, it reloads the last save (which was last time it closed cleanly). This ends up opening a new pane in the same positions as the old ones, and once again the same pane position ends up in this crashing state every single time.

### Expected Behavior

I expect that the whole terminal doesn't crash when I close a single pane.

### Actual Behavior

The whole terminal crashes when I close these specific panes.

**Comment by brookst** [comment] 2024-06-03 00:14
Can confirm, closing the middle split:
> Faulting application name: WindowsTerminal.exe, version: 1.21.2405.6002, time stamp: 0x66396ac3
> Faulting module name: TerminalApp.dll, version: 1.21.2405.6002, time stamp: 0x66396a58
> Exception code: 0xc0000005
> Fault offset: 0x0000000000010f54
> Faulting process ID: 0x0x52A0
> Faulting application start time: 0x0x1DAB549726C9AFD
> Faulting application path: C:\Program Files\WindowsApps\Microsoft.WindowsTerminalPreview_1.21.1272.0_x64__8wekyb3d8bbwe\WindowsTerminal.exe
> Faulting module path: C:\Program Files\WindowsApps\Microsoft.WindowsTerminalPreview_1.21.1272.0_x64__8wekyb3d8bbwe\TerminalApp.dll
> Report ID: 7f826e57-c0ad-4dd5-9f5f-46d62706697e
> Faulting package full name: Microsoft.WindowsTerminalPreview_1.21.1272.0_x64__8wekyb3d8bbwe
> Faulting package-relative application ID: App
> Bucket ID:	6f6826e3bae54d4d9e605254efe4edfc (2188839943657549308)

**Comment by TGThorax** [comment] 2024-06-05 08:23
Same with newer version (About page says 1.21.1382.0):

> Faulting application name: WindowsTerminal.exe, version: 1.21.2405.17002, time stamp: 0x66479c70
Faulting module name: TerminalApp.dll, version: 1.21.2405.17002, time stamp: 0x66479c03
Exception code: 0xc0000005
Fault offset: 0x0000000000010f54
Faulting process id: 0x0x65F0
Faulting application start time: 0x0x1DAB720B652D59B
Faulting application path: C:\Program Files\WindowsApps\Microsoft.WindowsTerminalPreview_1.21.1382.0_x64__8wekyb3d8bbwe\WindowsTerminal.exe
Faulting module path: C:\Program Files\WindowsApps\Microsoft.WindowsTerminalPreview_1.21.1382.0_x64__8wekyb3d8bbwe\TerminalApp.dll
Report Id: a9475c0d-472f-4556-8868-9670850e4e8f
Faulting package full name: Microsoft.WindowsTerminalPreview_1.21.1382.0_x64__8wekyb3d8bbwe
Faulting package-relative application ID: App

**Comment by lhecker** [comment] 2024-06-05 16:02
I'm fairly certain that this is a duplicate of #17305. That user also reported that opening 3 panes and closing the middle one crashes the application. It was recently fixed in the Canary build.
(However, it also caused a regression unfortunately. That one was also fixed recently, but it'll probably take a few more hours until that's in the Canary build too.)

**Comment by carlos-zamora** [comment] 2024-07-10 21:43
Thanks for filing! Closing as a /dup of #17305.

**Closed** 2024-07-10 21:44 UTC
Labels: Issue-Bug
