### ISSUE TITLE
MSbuild crashes when run inside terminal

### ISSUE THREAD

**Issue by gilknyaz** [microsoft/terminal#16489] opened 2023-12-21 14:13 UTC
### Windows Terminal version

1.18.3181

### Windows build number

10.0.22621.0

### Other Software

MSBuild (VS 2022)

### Steps to reproduce

1. Open the Developer Command Prompt for VS 2022 profile.
2. go to a C# solution folder
3. Run MSbuild to compile. (Or run msbuild /t:Restore to restore some nuget packages)

### Expected Behavior

MSbuild to succeed

### Actual Behavior

MSBuild starts working but stops very early. No error is written to the console.
In Event Viewer -> Application, the following error appears:

Faulting application name: MSBuild.exe, version: 17.8.3.51904, time stamp: 0xe31ab667
Faulting module name: combase.dll, version: 10.0.22621.2792, time stamp: 0xd9671289
Exception code: 0xc0000409
Fault offset: 0x00000000001522b2
Faulting process id: 0x0x6380
Faulting application start time: 0x0x1DA34154F6EE43B
Faulting application path: C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\amd64\MSBuild.exe
Faulting module path: C:\WINDOWS\System32\combase.dll
Report Id: 4af61e29-3040-4862-b67c-0fb2c7a14aef
Faulting package full name: Microsoft.WindowsTerminal_1.18.3181.0_x64__8wekyb3d8bbwe
Faulting package-relative application ID: App

**Comment by zadjii-msft** [comment] 2024-01-03 15:48
@rainersigwald any ideas? Or any idea how to investigate? Does this work just fine in the vintage console/?

**Comment by rainersigwald** [comment] 2024-01-04 22:37
I haven't heard of this before. Since you have VS installed, you might be able to get more information by setting the environment variable `MSBUILDDEBUGONSTART=1` before running MSBuild, which should pop up a JIT debugger prompt. Then the crash might have a bit more actionable information?

**Comment by zadjii-msft** [comment] 2024-01-10 22:25
@rainersigwald Hey can you investigate this more on your side? Or move this to the msbuild repo? I can't imagine that this is something that is really caused by Terminal code... but if this is something that explodes in msbuild cause we're running, I think you'd be best equipped to find out why

**Comment by rainersigwald** [comment] 2024-01-10 22:52
This issue was moved to dotnet/msbuild#9626

**Comment by rainersigwald** [comment] 2024-01-10 22:52
@zadjii-msft I copied this to dotnet/msbuild, feel free to close this one.

**Closed** 2024-01-10 22:55 UTC
Labels: Resolution-External, Issue-Bug, Needs-Triage
