### ISSUE TITLE
Windows Terminal incorrectly shows user `SYSTEM` not the actual Username? (Incorrect `%USERNAME%` in `PROMPT`)

### ISSUE THREAD

**Issue by tDwtp** [microsoft/terminal#11831] opened 2021-11-26 20:32 UTC
### Windows Terminal version

1.11.2921.0

### Windows build number

10.0.19043.1348

### Steps to reproduce

1. Set the registry key `PROMPT` of type `REG_EXPAND_SZ` under `HKCU\Environment` to anything containing `%USERNAME%`
1. Open Windows Terminal ('Open as Administrator' not necesary)

More information on #11830

### Expected Behavior

Show the username in prompt of Windows Terminal.

### Actual Behavior

Shows SYSTEM insted of the username in prompt of Windows Terminal.

**Comment by tDwtp** [comment] 2021-11-26 20:34
More information ( original #11830 ):
I've tried to set up my terminal to look a little different. (`$E[1;32m%USERNAME%@%COMPUTERNAME%$E[0;37m:$E[33m$+$E[1;34m$P$E[0;37m$$ $E[0m` to be exact.) I edited the `PROMPT` and noticed in order to let the username show up I had to use the registry.

In the classical `CMD.EXE` it looks as expected, but for a while now I am using Windows Terminal.  
And here are the results:
```
Microsoft Windows [Version 10.0.19043.1348]
(c) Microsoft Corporation. Alle Rechte vorbehalten.

SYSTEM@HOME:C:\Users\tDwtp$ REG QUERY HKCU\Environment /F PROMPT /T REG_EXPAND_SZ

HKEY_CURRENT_USER\Environment
    PROMPT    REG_EXPAND_SZ    $E[1;32m%USERNAME%@%COMPUTERNAME%$E[0;37m:$E[33m$+$E[1;34m$P$E[0;37m$$ $E[0m

Suchvorgang abgeschlossen: 1 übereinstimmende Zeichenfolge(n) gefunden.

SYSTEM@HOME:C:\Users\tDwtp$ SET PROMPT
PROMPT=$E[1;32mSYSTEM@HOME$E[0;37m:$E[33m$+$E[1;34m$P$E[0;37m$$ $E[0m

SYSTEM@HOME:C:\Users\tDwtp$ whoami
home\tdwtp

SYSTEM@HOME:C:\Users\tDwtp$ 
```

As you can see, it shows SYSTEM as the user. Kinda funny, but also a little discomforting. The last time I started up a console as SYSTEM was on Windows XP.

The PROMPT broken down: ([explanation of ANSI Escape Codes here](https://en.wikipedia.org/wiki/ANSI_escape_code))
| String | Description |
|:------ |:----------- |
| `$E[1;32m` | set the color to bright green |
| `%USERNAME%` `@` `%COMPUTERNAME%` | show *&lt;user&gt;@&lt;host&gt;*<br/>(`%USERNAME%` is the problem here) |
| `$E[0;37m` `:` | show a (dark-)white *colon* `:` |
| `$E[33m` `$+`| show *how many directories are pushed via `PUSHD`* in (still dark-)yellow |
| `$E[1;34m` `$P` | show the *current path* in a (light-)blue |
| `$E[0;37m` `$$ ` | show a (dark-)white *dollar sign* `$` |
| `$E[0m` | revert back to a dark-white color for text. (`COLOR` will not work with this!) |

**Comment by elsaco** [comment] 2021-11-26 22:45
@tDwtp use `setx` to setup a persistent prompts for your `cmd`:

`setx PROMPT "$E[1;32m%USERNAME%@%COMPUTERNAME%$E[0;37m:$E[33m$+$E[1;34m$P$E[0;37m$$ $E[0m"
`

To set it for everyone use `setx PROMPT /M <your-prompt-string-here>`

Easier, and safer, than messing with the registry!

**Comment by tDwtp** [comment] 2021-11-27 01:00
@elsaco TBH, I dealt with the Registry so many times. This (*serious*) advise is for people that dont know how to read up on sideeffects of the particular Keys.
No worries, I know what I am doing when messing with the registry (and how to recover it \:p)

**Comment by elsaco** [comment] 2021-11-27 01:59
@tDwtp I don't doubt your ability to handle the registry hives. The reason I've mentioned `setx` is because  it is the proper tool to create or modify environment variables. `setx` is adding the same registry key as you mentioned above, but with a twist. And it works!

It is of type `REG_SZ` and does not need to expand any references. Here's sample `PROMPT` reg entry after using `setx`:

`"PROMPT"="$E[1;32mtux@ELEVEN$E[0;37m:$E[33m$+$E[1;34m$P$E[0;37m$$ $E[0m"
`

and `cmd` prompt in WT:

```
Microsoft Windows [Version 10.0.22000.348]
(c) Microsoft Corporation. All rights reserved.

tux@ELEVEN:C:\Users\tux$

```

I don't have the knowledge how the `%username%` is being expanded when added manually to the `PROMPT` reg key.

**Comment by tDwtp** [comment] 2021-11-27 02:16
I guess I shoud have kept silent. It is kinda stupid to argue over registry vs tool.
*however* Having a non expandable string (or hardcoded) is definetly *not* what i want.

#### So back to the main issue. 
Terminal still shows `SYSTEM` when using `%USERNAME%` So there seems to something that is not quite right. Maybe it has to do with how Windows starts UWP apps? (&lt;&lt;&lt; my best guess) I think at least some investigation should be done. I am just not an expert on UWP Apps and barely get in touch with them.

My best guess is that UWP apps (or apps form the Store in general) get their environment downgraded/expanded/overwritten after some verification process where the environment is passed down from. I am currently reading that up and would like to know if someone knows where the documentation is for that (if any) or if I have to poke around in that department.

AFAIK Win32 just start in the context of a normal user creates a environment from there. If `runas` is used, it lets SYSTEM start the process (here this prompt would also show `SYSTEM` as expected btw).

**Comment by eryksun** [comment] 2021-11-27 03:39
This is due to getting a new environment block via WinAPI `CreateEnvironmentBlock()`. Here's a simple reproducer in Python:

```python
from winreg import *
from win32profile import CreateEnvironmentBlock
key = OpenKey(HKEY_CURRENT_USER, 'Environment', access=KEY_ALL_ACCESS)
prev = QueryValueEx(key, 'PROMPT')
SetValueEx(key, 'PROMPT', 0, REG_EXPAND_SZ, '%USERNAME%')
token = -4 # GetCurrentProcessToken() pseudohandle
try:
    environ = CreateEnvironmentBlock(token, False)
finally:
    SetValueEx(key, 'PROMPT', 0, prev[1], prev[0])
```
```none
>>> environ['PROMPT']
'SYSTEM'
```
It's a function of when the "USERNAME" value is updated with the volatile value for the current session. I've stepped through this in detail [here](https://github.com/microsoft/terminal/issues/9741#issuecomment-815420501). Due to the fixed initialization order, user `REG_EXPAND_SZ` variables cannot reliably refer to other user `REG_EXPAND_SZ` variables or volatile variables such as "USERNAME".

The same problem is observed with "runas.exe" for the exact same reason, assuming `/env` isn't used. It has nothing to do the secondary logon service running as "SYSTEM".

**Comment by zadjii-msft** [comment] 2021-11-29 14:50
Well, that sure is a comprehensive answer. I'm gonna link this to #9741, but that sounds like it's understood, if albeit _weird_. Thanks!

**Closed by zadjii-msft** 2021-11-29 14:50 UTC
Labels: Needs-Triage, Needs-Tag-Fix

**Comment by tDwtp** [comment] 2021-11-29 20:14
Thanks @eryksun That was a good explanation.
Rather interesting, but I just wonder how `CMD.EXE` expands correctly?

Also @zadjii-msft thank you for closing , I did not have the time to do so (until now).

**Comment by eryksun** [comment] 2021-11-30 02:15
> Rather interesting, but I just wonder how `CMD.EXE` expands correctly?

Do you mean when you run cmd.exe from Explorer? cmd.exe is a command-line interface (CLI) shell that uses a console for standard I/O. Since Explorer has no console session that can be inherited, cmd.exe (like any other console application) allocates a new console session. This gets hosted by an instance of conhost.exe, which also provides a builtin terminal user interface when it's not running in headless mode (i.e. pseudoconsole mode, or the simple `CREATE_NO_WINDOW` mode). 

Regarding the environment, the difference is that running cmd.exe from Explorer simply inherits Explorer's environment, whereas Windows Terminal spawns cmd.exe with a fresh environment that's created via `CreateEnvironmetBlock()`. The question then is why Explorer's environment is different. The answer is that Explorer uses the shell API's undocumented function `RegenerateUserEnvironment()`, which, compared to `CreateEnvironmentBlock()`, initializes the environment using a significantly different sequence and selectively inherits more from the current environment.

**Comment by zadjii-msft** [comment] 2024-07-17 14:46
(looks like if you're seeing this after 1.18, you're probably hitting: https://github.com/microsoft/terminal/issues/16200)
