### ISSUE TITLE
People think the Color Scheme editor will change the current colors

### ISSUE THREAD

**Issue by tony-stines** [microsoft/terminal#9775] opened 2021-04-11 10:02 UTC
### Windows Terminal version (or Windows build number)

10.0.21354 (Dev)

### Steps to reproduce

1. Launch Terminal
2. Open Settings
3. Color Schemes
4. Select another color scheme from combo
5. Click to Save
6. Reopen Settings -> Color Scheme didn't applied

### Actual Behavior

Color Scheme.

**Comment by DHowett** [comment] 2021-04-11 16:01
What terminal version.

**Comment by spncrhrstn** [comment] 2021-04-14 18:10
I'm seeing this issue as well. Just updated to v1.7.1033.0 (the new release). No matter what I try, I can't seem to apply a color scheme using the new Settings UI. It gets reset back to Campbell on each relaunch.

**Comment by miwojc** [comment] 2021-04-16 07:06
Same issue. Version: 1.7.1033.0

**Comment by zadjii-msft** [comment] 2021-04-20 14:10
Wait HOLD UP.

Are you going to the "Color Schemes" page
![image](https://user-images.githubusercontent.com/18356694/115410049-eea7e600-a1b7-11eb-825c-c12ca8a3535c.png)

or are you changing the "color scheme" of a given profile:
![image](https://user-images.githubusercontent.com/18356694/115410168-05e6d380-a1b8-11eb-8a19-45f7acf4c6d1.png)


The first page is used for _editing the color scheme itself_. The second is for changing the appearance of the selected profile. The dropdown on the Color Schemes page is just used for _selecting which scheme you want to edit_. It doesn't apply that scheme to any profiles.

**Comment by spncrhrstn** [comment] 2021-04-20 15:50
@zadjii-msft You're totally correct, now that I've taken a look into that. Gotta say though, it's definitely confusing on first use. I would assume that the Color schemes page is for selecting a default color scheme for all profiles (and yes you could edit the colors as well). Then you can go into individual profiles and override to a different color scheme.

Perhaps it just needs some some clarification on what the Coloring schemes page does. Maybe selecting a default color scheme would be better suited under Appearance (if setting a default color scheme is a goal).

**Comment by miwojc** [comment] 2021-04-20 18:38
Is it possible to change default theme that would apply to all profiles like via settings.json?

**Comment by DHowett** [comment] 2021-04-20 18:54
> Is it possible to change default theme that would apply to all profiles like via settings.json?

/cc @cinnamon-msft

**Comment by zadjii-msft** [comment] 2021-04-20 18:57
I'll make sure to pass that feedback along to the UI designers (and my "I" I mean @cinnamon-msft 😋)

I'll close the rest of this discussion about setting the default for all profiles as a /duplicate of #9539 - we're generally having that discussion in that thread.

**Comment by zadjii-msft** [comment] 2022-01-10 22:59
We're reopening this, because it's come up a bunch of times now. The design clearly needs some improvement in this regard.

TODO:
* [ ] Do a competitive analysis, see what other terminals do for this UX. Clearly, we're doing something misleading

Ideas:

* Just get rid of the scheme editor entirely, replace it with a ContentDialog in the Profiles>Appearances page
* Maybe we should add a button to the color schemes page that says something like "Apply this scheme to all profiles". 
* Alternatively, we could add some help text to the top/bottom like "Trying to change the color scheme for a particular profile? Go change '[Profile > Appearance > Color scheme](in-app link to default appearances)'"


There were other suggestions too, just logging before 5pm.

**Comment by zadjii-msft** [comment] 2022-08-29 11:47
Punting this for a release, since we feel like this wasn't wholly addressed in #13269

**Closed** 2022-08-31 21:15 UTC
Labels: Issue-Feature, Product-Terminal, In-PR, Priority-2, Area-Settings UI
