### ISSUE TITLE
tooltip: 2 tooltips are visible when hover on Close button 

### ISSUE THREAD

**Issue by Thrillseekr** [microsoft/terminal#16700] opened 2024-02-10 18:32 UTC
### Windows Terminal version

1.18.10301.0

### Windows build number

10.0.19045.3996

### Steps to reproduce

Hover Mouse on Close button, you will see 2 `Close` tooltip texts.
Whereas on Minimixe and Maximize button has only 1 tooltip text.

### Expected Behavior

There should be only one Tooltip Text on Close Button, as like present in Minimize and Maximize button tooltip.

### Actual Behavior

On Hovering on Close button, 2 tooltip texts are visible.

![Screenshot (90)](https://github.com/microsoft/terminal/assets/118781875/cdabfc58-a239-4185-8f89-3a4856eb0c18)

![Screenshot (92)](https://github.com/microsoft/terminal/assets/118781875/30317c67-a0a0-4cb7-915a-9c39d9c68eaa)

@DHowett , @lhecker , @zadjii-msft , @
 I'm a newbie in open source and I want to work on this issue, could you please provide the required files to be look upon.

**Comment by lhecker** [comment] 2024-02-12 14:18
This is indeed a duplicate of #12882 and so I'll be closing your issue for now. You can comment on #12882 if you'd like to work on it. 🙂

> [...] could you please provide the required files to be look upon.

That said, I don't think anyone of us knows exactly where this issue occurs. @zadjii-msft has speculated in #12882 that it likely regressed in #11680 and so you'd have to look at the differences in that PR.

**Closed by lhecker** 2024-02-12 14:18 UTC
Labels: Issue-Bug, Needs-Triage
