### ISSUE TITLE
Weird behaviour when font size up and down in WSL

### ISSUE THREAD

**Issue by skyline75489** [microsoft/terminal#5666] opened 2020-04-30 11:55 UTC
# Environment

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd] 1909
Windows Terminal version (if applicable): From 0.10 to latest master

Any other software?
```

# Steps to reproduce

I was playing around since we fixed #5479 recently. But I found that the content became weird and duplicate when I'm scaling font up & down.

Originaly there's only one prompt line. Scale the font to a very large one (I mean large enough to trigger line wraps) and down. Repeat.

# Expected behavior

Well, anything less confusing would be good.

# Actual behavior

After a couple of times, you got something like this:

![图片](https://user-images.githubusercontent.com/4710575/80707071-f2140e80-8b1b-11ea-864a-5b31ec422be8.png)

![图片](https://user-images.githubusercontent.com/4710575/80707131-140d9100-8b1c-11ea-95d4-45401590fef4.png)

I can only reproduce this in WSL. Distro does not seem to matter.

**Comment by skyline75489** [comment] 2020-04-30 12:03
I'm not really concerned about the issue itself. I mean, it would appear very few people would actually do this in real life. What concerns me is the underlying issue that may affects other things. And I don't really get it why Powershell & cmd are exempt from this behaviour.

**Comment by zadjii-msft** [comment] 2020-04-30 13:06
So I'm thinking this is _definitely_ a /dupe of #5450, and I'm thinking honestly that both of these are related to #3088

This seems less like it's something we're doing, but more an artifact of how `bash` handles reprinting it's prompt. Compare `gnome-terminal` with `conhost`:

![image](https://user-images.githubusercontent.com/18356694/80713420-0672ef80-8ab9-11ea-8a09-9329a09502df.png)

As soon as the prompt wraps onto a _third_ line, you `bash` seems to handle unwrapping particularly poorly.

**Closed by zadjii-msft** 2020-04-30 13:06 UTC
Labels: Needs-Tag-Fix, Needs-Triage
