### ISSUE TITLE
Nerd Font Icons Not Displaying Right Size in Windows Terminal Preview

### ISSUE THREAD

**Issue by edmund-leibert** [microsoft/terminal#14390] opened 2022-11-14 19:40 UTC
### Windows Terminal version

1.15.2875.0

### Windows build number

10.0.22621.0

### Other Software

- **Powershell Preview** (Version: 7.3.0-rc1)
   - [GitHub](https://github.com/PowerShell/PowerShell)
- **Oh-My-Posh** (Version: 12.13.3)
   - [GitHub](https://github.com/JanDeDobbeleer/oh-my-posh)
   - [Website](https://ohmyposh.dev/)
- **Caskaydia Cove Nerd Font**
   - [Website](https://www.nerdfonts.com/font-downloads)

### Steps to reproduce

1. First download and install **Windows Terminal Preview** from the Microsoft Store. ([Microsoft Store Page of Windows Terminal Preview](https://www.microsoft.com/store/productId/9N8G5RFZ9XK3))
2. Download and install **Powershell Preview** by downloading the .msi from the Powershell GitHub page. [Powershell GitHub](https://github.com/PowerShell/PowerShell).
3. Install **Oh-My-Posh** via Winget. To do so... 
   - Open a **PowerShell Preview** prompt in **Windows Terminal Preview**.
   - Run the following command: `winget install JanDeDobbeleer.OhMyPosh -s winget`.
   - Now configure **Oh My Posh** to use the "_Clean Detailed_" theme. To do so, run the following command: `oh-my-posh init pwsh --config "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/clean-detailed.omp.json" | Invoke-Expression`.
4. Now open another **Powershell Preview** prompt in **Windows Terminal**.
   - Now configure Oh My Posh to use the "Clean Detailed" theme. To do so, run the following command: `oh-my-posh init pwsh --config "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/clean-detailed.omp.json" | Invoke-Expression`.
5. Compare the **Oh My Posh** prompt on **Windows Terminal** to the Oh My Posh prompt on **Windows Terminal Preview**.

### (!) Note
The **Oh My Posh** theme used, terminal font used, or even font size, has _no_ direct effect on this bug in **Windows Terminal Preview**. This bug persists across _all_ **Oh My Posh** themes, set terminal fonts, etc.

Take a particular look at the following character/gylphs...
- nf-mdi-microsoft (f871)
- nf-oct-terminal (f489)
- nf-mdi-memory (f85a)
- nf-mdi-heart (f7d0)
- nf-mdi-home (f7db)

I recommend using [nerdfonts.com/cheat-sheet](https://www.nerdfonts.com/cheat-sheet) to see these icons.

### Expected Behavior

I am expecting _all_ Nerd Fonts' characters/glyphs to be displayed in the correct size. In other words, I am expecting to them to be displayed as seen correctly in **Windows Terminal**.

Refer to the image below. Notice how in **Windows Terminal**, all the characters/glyphs are displayed in the same size. In contrast, **Windows Terminal Preview** displays the characters/glyphs smaller.

**Windows Terminal** 
![image](https://user-images.githubusercontent.com/43337293/201743744-80886837-5cb0-4d34-bd4f-4a12ce7b8627.png)

### Actual Behavior

Refer to the images below. Notice how in **Windows Terminal**, all the characters/glyphs are displayed in the same size. In contrast, **Windows Terminal Preview** displays some of the characters/glyphs smaller.

**Windows Terminal** 
![image](https://user-images.githubusercontent.com/43337293/201743744-80886837-5cb0-4d34-bd4f-4a12ce7b8627.png)
**Windows Terminal Preview**
![image](https://user-images.githubusercontent.com/43337293/201744169-ca52f0bb-f071-44ea-b267-4ad869a0b73f.png)

**Comment by DHowett** [comment] 2022-11-14 19:41
Thanks for the report!

This is a /duplicate of #14022, which is rooted in our renderer being more strict about font widths whereas Nerd Fonts somewhat expects glyphs to be drawn _outside_ their cells. :smile:

**Closed by DHowett** 2022-11-14 19:41 UTC
Labels: Issue-Bug, Needs-Triage

**Comment by edmund-leibert** [comment] 2022-11-14 19:46
> Thanks for the report!
> 
> This is a /duplicate of #14022, which is rooted in our renderer being more strict about font widths whereas Nerd Fonts somewhat expects glyphs to be drawn _outside_ their cells. 😄

Oh okay, thank you! Apologies for the duplicate report. Was trying to find this issue beforehand. Take care. :)
