### ISSUE TITLE
no one found the dark theme selected tab color is not comfortable?

### ISSUE THREAD

**Issue by xinkunZ** [microsoft/terminal#7131] opened 2020-07-31 06:46 UTC
* In most cases, the selected color should be brighter, but the terminal does not follow this

![image](https://user-images.githubusercontent.com/7759897/89008022-7c972480-d33c-11ea-92ec-e3656a394393.png)

* light theme works well
![image](https://user-images.githubusercontent.com/7759897/89008215-df88bb80-d33c-11ea-81de-40a37474bbb6.png)

**Comment by zadjii-msft** [comment] 2020-07-31 12:42
Thanks for the suggestion! Largely, this is a duplicate of discussion that's happening over in #1375. There's also a bunch of proposals of ways to configure this being discussed over in #3327. 

/dup #1375

**Closed by zadjii-msft** 2020-07-31 12:42 UTC
Labels: Issue-Feature, Needs-Tag-Fix, Needs-Triage
