### ISSUE TITLE
Broken buttons in title bar after maximisation with three tabs open

### ISSUE THREAD

**Issue by SKyletoft** [microsoft/terminal#4395] opened 2020-01-29 09:00 UTC
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18362.592]
Windows Terminal version (if applicable): Version: 0.8.10261.0
Hardware: Surface Pro 6, i7/16GB/512GB

Any other software? No
```

# Steps to reproduce

Open terminal
Open two tabs, three total (no more or less)
Maximise
De-maximise (window, not minimise)

# Expected behavior

Window returns to how it looked before, with working minimise/maximise/close buttons in the title bar

# Actual behavior

Minimise/Maximise/Close buttons have half-sized and misaligned hitboxes and the window can no longer be dragged/moved

Before:
![image](https://user-images.githubusercontent.com/45131343/73341837-be57ed00-427d-11ea-9f71-8ce2bc1af4ed.png)
After:
![image](https://user-images.githubusercontent.com/45131343/73341863-cb74dc00-427d-11ea-88e4-f32bccf0438e.png)

**Comment by DHowett-MSFT** [comment] 2020-01-31 07:00
Thanks for the report! I think this is a /dupe of #4288

**Closed by DHowett-MSFT** 2020-01-31 07:00 UTC
Labels: Needs-Tag-Fix, Needs-Triage
