### ISSUE TITLE
Is there any convenient way to modify the terminal's encoding?

### ISSUE THREAD

**Issue by stdmkmehp** [microsoft/terminal#17273] opened 2024-05-15 11:45 UTC
# Description of the new feature/enhancement

When I use ssh to connect to remote server in terminal, it is frequent to switch encoding between gbk and utf-8. But it seams that there is no way to do it. This matter is causing me a lot of distress. Plz help me!

# Proposed technical implementation details (optional)

**Comment by lhecker** [comment] 2024-05-15 18:16
I'd love to help but can you please write more about what you mean? Ideas:
* Are you trying to remotely connect to a Windows or Linux system?
* How are you trying to switch the encoding?
* What exactly breaks?
* Can you give us steps so that we can reproduce your issue?

**Comment by stdmkmehp** [comment] 2024-05-16 05:07
I'm try to remotely connect to a Linux system which has env LC_ALL=C. When I do shell cmd with "cat file", the terminal shows garbled characters. The file is encoded with gbk，but it seams that terminal shows as utf-8.
To reproduce the issue, you can cat file_enc_with_gbk.txt. On my terminal, it comes with 
![image](https://github.com/microsoft/terminal/assets/23132434/f411b1ff-1f82-485c-866f-ab6062eb9469)
Obviously it is not what i want. 

I have used Xshell before, which can provide a dropdown menu to switch the terminal's encoding. If the file is encode with gbk, I just need switch the terminal's encoding to gbk. If the file is encode with utf-8, I just need switch the terminal's encoding to utf-8. Buf the Windows terminal seems take a default encoding utf-8, and do not support to switch.


[file_enc_with_gbk.txt](https://github.com/microsoft/terminal/files/15329820/file_enc_with_gbk.txt)

**Comment by lhecker** [comment] 2024-05-16 14:38
> I'm try to remotely connect to a Linux system which has env LC_ALL=C.

`LC_ALL=C` in practice tells your system that you want to use ASCII. At a minimum, I would recommend setting it to `zh_CN.UTF-8` if possible, or some other variant, to get Unicode support. Of course there's also `zh_CN.GBK` if you really need GBK encoding anywhere, but I'd recommend against using GKB long term, because it's not Unicode which makes exchanging text difficult.

> Buf the Windows terminal seems take a default encoding utf-8, and do not support to switch.

Not quite. You're right in that we don't support switching the encoding (codepage) via a setting. #15678 tracks this feature request. I think it makes sense for us to have such a setting, because Gnome Terminal, Apple's Terminal, and many others got it as well.

However, I believe your issue is because Windows' OpenSSH doesn't support switching the encoding. See here: https://github.com/PowerShell/Win32-OpenSSH/issues/1855#issuecomment-988977866 I can't imagine that this is an inherent limitation and I'm pretty sure support for other encodings could be added to OpenSSH. However, such work doesn't seem to be currently planned.

**Comment by carlos-zamora** [comment] 2024-06-12 21:23
Thanks for filing! Regarding what Leonard said above, we're going to close this as a /dup of https://github.com/PowerShell/Win32-OpenSSH/issues/1855.

**Closed** 2024-06-12 21:23 UTC
Labels: Issue-Feature, Needs-Attention, Needs-Tag-Fix
