### ISSUE TITLE
Please do not close when a task is running

### ISSUE THREAD

**Issue by AnikHasibul** [microsoft/terminal#1888] opened 2019-07-09 05:44 UTC
I have vim open, accidentally I clicked the close button. And it's gone! :(

Can you please warn me if I have any running task (except shell) in any of the tabs?

**Comment by DHowett-MSFT** [comment] 2019-07-09 05:56
Duplicate of #1864, please search before reporting!

**Closed by DHowett-MSFT** 2019-07-09 05:56 UTC
Labels: Needs-Tag-Fix, Needs-Triage
