### ISSUE TITLE
windows min/max buttons layout error

### ISSUE THREAD

**Issue by dacapoday** [microsoft/terminal#4310] opened 2020-01-21 01:55 UTC
# Environment

```none
Windows build number: 10.0.18362.0 Microsoft Windows NT 10.0.18362.0
Windows Terminal version (if applicable): Windows Terminal (Preview) Version: 0.8.10091.0
```

# Steps to reproduce
1. open Terminal
2. open new tab of ssh
3. window maximization
4. cancel window maximization

# Expected behavior
windows min/max buttons as usual.

# Actual behavior
![Snipaste_2020-01-21_09-49-57](https://user-images.githubusercontent.com/9378047/72768955-00f14800-3c34-11ea-8454-01908bdf3da7.png)
![Snipaste_2020-01-21_09-50-10](https://user-images.githubusercontent.com/9378047/72768960-0484cf00-3c34-11ea-934a-c31e7254298a.png)
![Snipaste_2020-01-21_09-50-19](https://user-images.githubusercontent.com/9378047/72768952-fd5dc100-3c33-11ea-9bda-299b8fed93ff.png)

**Comment by DHowett-MSFT** [comment] 2020-01-21 08:29
What is your display scaling set to?

**Comment by JekRock** [comment] 2020-01-21 09:30
I've stumbled upon the same issue. It's described [here](https://github.com/microsoft/terminal/issues/4288)
I have 2 displays. One with 100% scaling and one with 125%. The issue is reproducible on both displays

**Comment by zadjii-msft** [comment] 2020-01-21 16:02
@JekRock You're correct, this does look like an exact dupe of that issue. We'll use that thread to continue discussion. Thanks!

/dup #4288

**Closed** 2020-01-21 16:02 UTC
Labels: Needs-Author-Feedback, Needs-Tag-Fix, Needs-Triage
