### ISSUE TITLE
Shortcut load depends on selected Language

### ISSUE THREAD

**Issue by MianenCZ** [microsoft/terminal#4735] opened 2020-02-27 09:33 UTC
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18362.657]
Windows Terminal version (if applicable): 0.9.433.0
```

# Steps to reproduce

I have this shortcuts define in my config:
``` json
{
        "command": "splitHorizontal",
        "keys": [ "alt+shift+(" ]
      },
      {
        "command": "splitVertical",
        "keys": [ "alt+shift+)" ]
      },
```
I have English US Keyboard or Czech Programing Keyboard
 - Shortcur worksas expected (Pressing "alt+shift+9/0" do a split)

I have Czech QUERTY Keyboard
 - Shortcuts do not workd "alt+shift+("  do nothing (As expected, cause the layout of keyboard is different )
 - **Then I switch to US Keyboard or Czech Programing Keyboard**
 - Shortcut do not work,  "alt+shift+("  do nothing (Pressing "alt+shift+9/0" do nothing)

**Comment by DHowett-MSFT** [comment] 2020-02-28 02:43
So, behind the scenes keyboard shortcuts are bound to "keyboard key identifiers". The determination of what those key identifiers are happens when the settings file is loaded.

I bet that this is a /dupe of #1125 -- not because of environment variables, but because "keyboard" is one of the settings Windows sends out a broadcast notification for.

**Closed by DHowett-MSFT** 2020-02-28 02:43 UTC
Labels: Needs-Tag-Fix, Needs-Triage
