### ISSUE TITLE
Wrong icon gets rendered when directly running apps in terminal (double click exe to open terminal tab).

### ISSUE THREAD

**Issue by AraHaan** [microsoft/terminal#13111] opened 2022-05-16 05:13 UTC
### Windows Terminal version

1.13.10984.0

### Windows build number

10.0.22000.0

### Other Software

My Discord Bot v2.1.100.

On my Discord bot, it is designed to have an application icon. However when Windows Terminal is configured to be the default console host, all terminal tabs do not render the application icon when you directly double click it's executable file to run it.

### Steps to reproduce

1. Build an .NET Console application with an *.ico file for the program's icon, then double click the built output so it launches in Windows Terminal.

### Expected Behavior

For the icon of the application to be rendered on the tab. On MacOS it renders the icon just fine, however that is in Apple's terminal.

### Actual Behavior

A different icon is rendered and is provided from the OS or some other application instead?

**Comment by zadjii-msft** [comment] 2022-05-16 10:45
Huh. Coulda swore we were tracking this somewhere, but doesn't look like it. #10669 looks vaguely related, but that's not it. 

For this to work, we'd probably need to some set of:
* #9458
* #1504

we need to bothe be able to get the info on what the icon was supposed to be, and the ability to turn icons in dll's and exe's into XAML icons.

**Comment by AraHaan** [comment] 2022-05-16 14:23
Cant one use the Windows API to obtain the icon information from the program that terminal is about to run (when it determines the program is about to execute directly) in order to use that information to simulate a profile with the icon?

**Comment by zadjii-msft** [comment] 2022-05-16 14:51
Yea probably. Trick there is converting the `HANDLE` that returns into something that can be used as the source for a XAML icon. If you can figure that out, the rest of this probably isn't too hard to wire up.

**Comment by DHowett** [comment] 2022-05-16 15:47
@zadjii-msft I'm comfortable calling this a dupe of both of those issues. The description for "pass LNK/EXE data" suggests making a fake runtime profile for the handed-off application, and part of that would be making sure it's got the right icon. We do both, we get icons!

/dup #9458 #1504

**Comment by DHowett** [comment] 2022-05-16 15:48
(Thanks for the report @arahaan!)

**Closed by DHowett** 2022-05-16 15:47 UTC
Labels: Issue-Bug, Area-User Interface, Product-Terminal, Priority-3, Area-DefApp
