### ISSUE TITLE
Need an API to set TabColor

### ISSUE THREAD

**Issue by BobFrankston** [microsoft/terminal#15005] opened 2023-03-16 20:39 UTC
# Description of the new feature/enhancement
There is an API to set the window title (ui.RawUI.WindowTitle). There should be a way to set the TabColor programmatically. It can be done with WT but only when spawning a new window.

# Proposed technical implementation details (optional)
I presume the underlying mechanisms are there, but it just lacks an API akin to that for WindowTitle.

**Comment by lhecker** [comment] 2023-03-16 23:03
I believe this is a duplicate of #14910. You can try it out by running the command mentioned here in PowerShell: https://github.com/microsoft/terminal/discussions/14903#discussioncomment-5104434

**Comment by BobFrankston** [comment] 2023-03-17 00:03
Thanks. I'd close this, but it would still be nice to have it in the API to be uniform.

**Closed** 2023-03-17 00:30 UTC
Labels: Issue-Feature, Needs-Triage, Needs-Tag-Fix

**Comment by BobFrankston** [comment] 2023-03-17 01:18
I want to make sure we're using the same terms.

There is an ambiguity between PowerShell as a console and PowerShell as a programming language. I have .ps1 files associated with pwsh, so I can run them in a cmd window in Windows Terminal. And it works fine to set the title. But the escape sequences only work in a PowerShell tab but not a cmd tab.

 I want to make sure I properly understand this.
 
  $host.ui.RawUI.WindowTitle = "hello"
  
seems to be associated with conhost since it works for any tab, whereas the escape sequence only works for a PowerShell tab.

So this is indeed a conhost request though I just happen to be using pwsh rather than a BAT file.

**Comment by j4james** [comment] 2023-03-19 22:34
@BobFrankston Those escape sequences will work from any shell in Windows Terminal, but it's a little more complicated in a cmd shell or BAT file because it's not as easy to get an `ESC` character. From the cmd prompt you would need to type <kbd>Ctrl</kbd>+<kbd>[</kbd> to generate `ESC`. You also need to be aware that the `|` character is reserved, so that has to be prefixed with `^|`.

As a complete example, you can set the tab to white on red as follows:

1. Type `echo `
2. Press <kbd>Ctrl</kbd>+<kbd>[</kbd>
3. Type `[2;15;1,^|`
4. Press <kbd>Return</kbd>

What you should see at the prompt would be something like this:

![image](https://user-images.githubusercontent.com/4181424/226213915-a233a487-6c46-45b6-b95f-28d7ed4b59b2.png)

To achieve the same thing with a BAT file, you'd need a way to get the `ESC` character into the file, which you can do like this:

1. Type `echo `
2. Press <kbd>Ctrl</kbd>+<kbd>[</kbd>
3. Type `> tabcolor.bat`
4. Press <kbd>Return</kbd>

At that point, if you edit the `tabcolor.bat` file in something like notepad, you'll see a `◻` glyph which is the `ESC`. If you prefix that with `echo ` and add `[2;15;1,^|` on the end, you'll have a BAT file that sets the tab color.

**Comment by BobFrankston** [comment] 2023-03-19 23:34
You're right -- don't know why my earlier tests were off, but this works in Typescript.
```
 console.log("\x1b[2;5;82,|");
```
and pwsh
```
echo "$([char]27)[2;15;6,|"
```

One thing that made the bat file example a challenge is that it is not at all obvious that ^[ meant control -- even though I've used that notation for half a century (no exaggeration - the early days of Emacs).  And ^| is not control? The other complicating factor is a plethora of examples that didn't seem consistent.

### **So, please, is there a URL to the documentation on this?** 

The RGB examples in https://github.com/microsoft/terminal/discussions/14903 don't seem to work.

**Comment by j4james** [comment] 2023-03-20 00:57
> And ^| is not control?

No. Visually it may look the same as a control character, but it's two separate characters: `^` and `|`.

> So, please, is there a URL to the documentation on this?

If you meant the `^` escaping syntax for the cmd shell, I found some old documentation on the subject [here](https://learn.microsoft.com/en-us/previous-versions//cc723564(v=technet.10)). Search for `carat` to find the relevant section.

If you mean the escape sequences for changing the tab color, they aren't covered in the Windows Terminal documentation yet. But `DECAC` and `DECCTR` are standard DEC sequences which you can find documented in the DEC VT520 manual (see [here](https://www.manualslib.com/manual/1200903/Digital-Equipment-Vt520.html?page=170) and [here](https://www.manualslib.com/manual/1200903/Digital-Equipment-Vt520.html?page=272)). And `OSC 4` is an XTerm sequence which you can find documented [here](https://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h4-Operating-System-Commands:OSC-Ps;Pt-ST:Ps-=-4;c;spec.123F). The only thing specific to the Windows Terminal implementation is the assignment of palette entries 263 and 264 to the tab colors.

> The RGB examples in https://github.com/microsoft/terminal/discussions/14903 don't seem to work.

If you've been using the `DECAC` sequence to change the tab color, make sure that you've set that back to the default values (with ``echo "`e[2;263;264,|"``), before attempting the RGB examples. Alternatively you could just open a new terminal tab first.

**Comment by BobFrankston** [comment] 2023-03-20 01:50
Thanks.

I understand I should wait, but one problem with software is the incremental reward of figuring out each puzzle.

I don't think I need to tell you about all the ambiguities in the examples and  [2 vs ]4 vs. ... and all those color indexes.

So I'll wait till I can find simple documentation for using RGB values for the foreground, background, tabs etc.
