### ISSUE TITLE
Animated backgrounds cause crashes for some people

### ISSUE THREAD

**Issue by Trundlore** [microsoft/terminal#1590] opened 2019-06-25 08:47 UTC
# Environment

Windows build number: Microsoft Windows [Version 10.0.18922.1000]
Windows Terminal version (if applicable): 0.2.1715.0

Any other software?
WSL but applies for cmd, powershell, pscore

# Steps to reproduce

set background image to animated gif using value: 

```
"backgroundImage" : "C:/users/<username>/AppData/Local/Packages/Microsoft.WindowsTerminal_8wekyb3d8bbwe/RoamingState/unicorn.gif",
"useAcrylic" : false
"backgroundImageStretchMode" : "uniformToFill",
```

open created console

# Expected behavior

console runs with animated background playing.
(identical steps on colleagues 1903 builds works as expected)

# Actual behavior

animated image begins to play for ~2 seconds and then console exits.
event log shows event id 1000

Faulting application name: WindowsTerminal.exe, version: 1.0.1906.20005, time stamp: 0x5d0c1459
Faulting module name: TerminalControl.dll, version: 1.0.1906.20005, time stamp: 0x5d0c138b
Exception code: 0xc0000005
Fault offset: 0x0000000000026c0c
Faulting process ID: 0x4e28
Faulting application start time: 0x01d52b2ff8bfae18
Faulting application path: C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_0.2.1715.0_x64__8wekyb3d8bbwe\WindowsTerminal.exe
Faulting module path: C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_0.2.1715.0_x64__8wekyb3d8bbwe\TerminalControl.dll
Report ID: bb1148df-bbb0-41b9-9a52-390469ea14d3
Faulting package full name: Microsoft.WindowsTerminal_0.2.1715.0_x64__8wekyb3d8bbwe
Faulting package-relative application ID: App

**Comment by DHowett-MSFT** [comment] 2019-06-27 23:01
Can you share the image that's causing you trouble? We've never seen this. Thanks!

**Comment by Shorotshishir** [comment] 2019-06-28 10:53
I have tried to reproduce your issue, with  `.json` pattern for fileDirectory too, but couldn't reproduce any error. I tried on multiple file locations too.
Windows Version 10.0.18362.175

https://imgur.com/a/tEo8Xwp

**Comment by Trundlore** [comment] 2019-07-02 15:53
Thanks for trying to recreate.
I can confirm it happens on two of my computers now and have had an insider update since too.
I have tried the following images
https://66.media.tumblr.com/6153c19fb7cb6b8de0ae90d191ea5609/tumblr_oswpvscnYJ1vtwln5o1_500.gif
http://i.imgur.com/zwoU4OP.gif
https://cdn.dribbble.com/users/130603/screenshots/2290997/lukeboba_02.gif

and a few others.

the current profile i have added for the tardis one is:
{
            "acrylicOpacity" : 0.85000002384185791,
            "background" : "#012456",
            "backgroundImage" : "C:/Users/peter/OneDrive/Documents/WindowsTerminal/TimeVortex.gif",
            "backgroundImageOpacity" : 0.69999998807907104,
            "backgroundImageStretchMode" : "uniformToFill",
            "closeOnExit" : false,
            "colorScheme" : "Solarized Dark",
            "commandline" : "powershell.exe",
            "cursorColor" : "#00FF00",
            "cursorHeight" : 25,
            "cursorShape" : "vintage",
            "fontFace" : "Fira Code",
            "fontSize" : 12,
            "guid" : "{718035bd-bfa4-4553-9042-d63091e2480d}",
            "historySize" : 9001,
            "icon" : "C:/Users/peter/OneDrive/Documents/WindowsTerminal/Tardis-Icon.png",
            "name" : "PowerShell Tardis",
            "padding" : "0, 0, 0, 0",
            "snapOnInput" : true,
            "startingDirectory" : "%USERPROFILE%",
            "useAcrylic" : false
        },

**Comment by DHowett-MSFT** [comment] 2019-07-25 21:58
Hey we can't reproduce this. If you see this again, would you mind grabbing the "Windows Error Reporting" event from your event log? It will contain an identifier we can use to look up your crash.

**Comment by DHowett-MSFT** [comment] 2020-01-28 22:31
Haven't seen this in the wild in a long time. Closing no-repro. Feel free to reopen!

**Closed by DHowett-MSFT** 2020-01-28 22:31 UTC
Labels: Area-TerminalControl, Issue-Bug, Needs-Repro, Product-Terminal, Severity-Crash
