### ISSUE TITLE
If existing tabs exceed the windows size, new ones are not visible anymore, therefore not easily interactable with

### ISSUE THREAD

**Issue by IustinMicu** [microsoft/terminal#3143] opened 2019-10-10 07:07 UTC
# Environment

Windows build number: 18362
OS version: 10.0.18362
Powershell Core version: 6.2.3
Windows Terminal version: 0.5.2762.0

# Steps to reproduce

Open new tabs until they exceed the edge of the titlebar

# Expected behavior

- Existing tabs should be resized so all of them can be visible on the titlebar.
Or
- The tabs that exceed the titlebar edge should be aggregated in a single tab which:
   * is positioned to the right of the titlebar
   * in it`s title has a value that represent the number of aggregated tabs
   * when clicked on it, opens a dropdown with the aggregated tabs and the user is able to select 
      and switch to one of those

# Actual behavior

The tabs that exceed the edge of the window, are not visible.
They are only selectable with shortcuts, but you would have to remember their position or guess it, which is very unproductive.

**Comment by j4james** [comment] 2019-10-10 16:27
Probably a duplicate of #857, which should be fixed by PR #3027.

**Comment by DHowett-MSFT** [comment] 2019-10-10 16:30
Indeed! Thanks. Definite /dupe of #857.

**Closed by DHowett-MSFT** 2019-10-10 16:30 UTC
Labels: Needs-Tag-Fix, Needs-Triage
