### ISSUE TITLE
Two displays, different resolution results in wrong dimensions for maximized window

### ISSUE THREAD

**Issue by felipezacani** [microsoft/terminal#2116] opened 2019-07-26 12:45 UTC
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18362.239]
Windows Terminal version (if applicable): 0.2.1831.0

Any other software?
```

# Steps to reproduce
Using two displays with different resolutions (1366x768 and 2560x1440), maximize the terminal window in the smaller display/resolution.

# Expected behavior
A maximized window should be the exact display/resolution size.

# Actual behavior
The terminal window resizes about 20 pixels outside the display area when maximized on the smaller display. Maybe its a little bit more on the left side.

**Comment by zadjii-msft** [comment] 2019-07-26 13:10
This is a dupe of #1055, which was fixed by #1921

**Closed by zadjii-msft** 2019-07-26 13:10 UTC
Labels: Needs-Tag-Fix, Needs-Triage
