### ISSUE TITLE
Closing a PowerShell pane over a CMD pane that covers the view with text locks UI thread

### ISSUE THREAD

**Issue by richardszalay** [microsoft/terminal#2433] opened 2019-08-14 23:18 UTC
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18362.175]
Windows Terminal version (if applicable):0.3.2171.0
```

# Steps to reproduce

Forgive the title - I couldn't think of a good way of articulating it

1. Set the default profile to PowerShell
2. Create a cmd tab
3. Press enter until the text covers most of the screen
4. Split the view horizontally
5. Close the bottom pane

Does **not** repro if:

* The primary tab's text does not fill the screen
* The secondary/bottom pane is not PowerShell
* The primary/top pane is Ubuntu/WSL, and exhibits a [different bug](https://github.com/microsoft/terminal/issues/2432) if the primary/top pane is PowerShell
* The bottom/PowerShell pane loses focus (either to an external window or to the top pane)

# Expected behavior

The pane closes

# Actual behavior

The UI thread hangs. Screenshots:

![pane-crash-1](https://user-images.githubusercontent.com/229467/63062746-4f8c0f00-bf3d-11e9-9db8-acc523e1b353.png)

![pane-crash-2](https://user-images.githubusercontent.com/229467/63062748-5155d280-bf3d-11e9-9e59-e66e8ee6f7e4.png)

![pane-crash-3](https://user-images.githubusercontent.com/229467/63062753-531f9600-bf3d-11e9-98aa-4c498e40b2b6.png)

**Comment by richardszalay** [comment] 2019-08-15 00:29
Some quick debugging on this shows that it's blocked waiting for `ConhostConnection._hJob.reset()` in `ConhostConnection::Close`

**Comment by DHowett-MSFT** [comment] 2019-08-15 04:43
This is a duplicate of #2248, then. :smile:

**Closed by DHowett-MSFT** 2019-08-15 04:43 UTC
Labels: Needs-Tag-Fix, Needs-Triage

**Comment by richardszalay** [comment] 2019-08-15 04:45
Touché
