### ISSUE TITLE
Neovim Cursor Flickers from Block to Bar running in MS Terminal under Tmux

### ISSUE THREAD

**Issue by mebaran** [microsoft/terminal#5180] opened 2020-03-30 17:25 UTC
# Environment

```none
Windows build number: 10.0.19041.172
Windows Terminal version (if applicable):  0.10.781.0

Other software:
Debian WSL2 running tmux
```

# Steps to reproduce

1. Start tmux
2. Start neovim (nvim -u NORC)
3. Enter insert mode
4. Watch cursor flicker between block and thin line  

# Expected behavior
Cursor should remain a line and not flicker. (this is the behavior in WSLtty)

# Actual behavior
Cursor flickers between block and line.

**Comment by DHowett-MSFT** [comment] 2020-03-30 17:52
This doesn't seem to reproduce with stock configs of tmux and neovim on Debian:

![image](https://user-images.githubusercontent.com/14316954/77944913-9a605a00-7274-11ea-941d-4868437e1daf.png)

no cursor flickering here.

**Comment by mebaran** [comment] 2020-03-31 16:34
Thank you for investigating this.  To reproduce please run the following before to recreate the cursor flicker:

tmux set -g status-right %H:%M:%S
tmux set -g status-interval 1

That seems to cause the cursor flicker issues.  The flicker seems to occur in tandem with tmux rewriting the status bar (if you set the interval to 5, the cursor will flicker every 5s).  I can confirm the same issue doesn't happen in a mintty based terminal.

**Comment by DHowett-MSFT** [comment] 2020-03-31 18:35
You know what, this looks like it's probably because we typoed the escape sequence that turns off the cursor. tmux and vim "fight" over the cursor, but tmux turns it off before it writes out the status line.

This is incidentally fixed by #5181 (ref #3093)

**Comment by mebaran** [comment] 2020-03-31 22:39
That sounds like exactly what is happening.  Let me know if I can help test a beta build or when this makes it to a release.

**Closed** 2020-04-09 00:06 UTC
Labels: Area-VT, In-PR, Issue-Bug, Product-Conpty

**Comment by mebaran** [comment] 2020-05-09 15:46
This bug does not seem fixed in the latest release.  Possible to reopen?

From about this is my version:
Windows Terminal
Version: 0.11.1121.0

**Comment by mariuskimmina** [comment] 2021-09-26 06:55
Doesn't look fixed to me either, when I am in Insert mode in Neovim (with tmux) the cursor is flickering between line mode and block mode.
This does not happen if I use alacritty instead of the Windows Terminal. 

Version; 1.11.2421.0
