### ISSUE TITLE
Allow terminal to open in admin by default

### ISSUE THREAD

**Issue by rohit21agrawal** [microsoft/terminal#2082] opened 2019-07-25 00:00 UTC
Currently i configure cmd.exe and pwsh.exe as taskbar shortcuts and i can configure these shortcuts to always run in admin mode when i open them.

Is is possible to do the same for the terminal app? Not sure if this is possible since it is a store app, and not a win32 app, but it would be really convenient if i didn't have to right click a couple of times and then select Run as Administrator every time i launch the terminal.

**Comment by havidarou** [comment] 2019-07-25 07:57
+1

**Comment by scheffler** [comment] 2019-07-25 11:54
+1

**Comment by zadjii-msft** [comment] 2019-07-25 13:21
First off, please don't reply "+1" to issues. There's a perfectly good +1 button here: 
![image](https://user-images.githubusercontent.com/18356694/61877141-00aa0700-aeb4-11e9-8b6d-9e78acc94846.png)

Secondly, this is a dupe of #632

**Closed by zadjii-msft** 2019-07-25 13:21 UTC
Labels: Needs-Tag-Fix, Needs-Triage

**Comment by scheffler** [comment] 2019-07-25 13:36
I appreciate that you're likely responding to a lot of issues; however, this was my first foray into this community and I was following what appeared to be a pattern from a prior poster.

If you want to foster community, responses like yours are unwelcome.
________________________________

**Comment by escalonn** [comment] 2019-08-03 17:20
Not a duplicate. #632 concerns profiles running as admin by default. This issue concerns the whole app launching as admin by default, whether in itself or via some kind of configured shortcut file.
