### ISSUE TITLE
Paste swallows newlines from the web... Gitlab

### ISSUE THREAD

**Issue by rayfoss** [microsoft/terminal#5736] opened 2020-05-04 16:45 UTC
I'm pasting some code from gitlab, but the new lines are missing... ending up is a garbled mess.... what's going on?

When I paste from the notepad, everything works as expected

Reproduction:
1. Go to: https://gitlab.com/olaris/ffmpeg-static/-/blob/master/build.sh
2. Copy the first 10 lines, in view or edit mode
3. paste into nano

Watch a garbled mess

**Comment by zadjii-msft** [comment] 2020-05-04 16:47
What version of the Terminal are you running? 

What application are you running in the Terminal that you're trying to paste into?

Could you share some screenshots perhaps?

**Comment by DHowett-MSFT** [comment] 2020-05-04 16:48
In addition, do you mean “when I paste it into notepad and then copy it again and paste it into Terminal”?

I’ve never had good luck pasting content directly from GitHub or GitLab.

**Comment by DHowett-MSFT** [comment] 2020-05-04 16:48
(In any application.)

**Comment by rayfoss** [comment] 2020-05-04 17:00
Updated my reproduction in original post... I'm used to it working pretty well under Ubuntu/mac/Fedora.  with iTerm, Gnome terminal and Terminator. Looks like a workaround is to show the raw file.

**Comment by DHowett-MSFT** [comment] 2020-05-04 17:14
So, I copied this from here:

![image](https://user-images.githubusercontent.com/14316954/80993438-e9f3f180-8def-11ea-96b7-b13a083b7026.png)


to here...

![image](https://user-images.githubusercontent.com/14316954/80993411-e06a8980-8def-11ea-8c62-25f71cb94288.png)


So I've got to ask for more info: _what version of nano?_ _are you using WSL? gow? cygwin?_

**Comment by rayfoss** [comment] 2020-05-04 21:10
WSL Debian, I don't recall ever using terminal for any other shell

**Comment by DHowett-MSFT** [comment] 2020-05-05 01:32
Okay, this one doesn't have a great resolution. When we take text off the clipboard, we replace `\r\n` with `\r`. This is correct (and this is how a bunch of other terminal emulators do paste manipulation as well.)

There's an additional wrinkle, though.

_nano interprets `\r` as the *[J]ustify (^J)* command._

It looks like this works on other terminals because nano also requests "bracketed paste" mode. When bracketed paste is supported, it can know that content is coming in off the clipboard and suppress the justify action.

This'll be a /dupe of #395 with a little bit of nano flair thrown in.

**Closed by DHowett-MSFT** 2020-05-05 01:32 UTC
Labels: Needs-Attention, Needs-Tag-Fix, Needs-Triage
