### ISSUE TITLE
win11开始菜单右键Windows终端不能运行

### ISSUE THREAD

**Issue by qihs97** [microsoft/terminal#13347] opened 2022-06-21 11:32 UTC
win11开始菜单右键Windows终端不能运行，无响应

**Comment by zadjii-msft** [comment] 2022-06-21 11:58
Sorry, you'll have to give us more information. What OS build are you using, which Terminal version, how did you install the Terminal, etc. This sounds like an issue that's been reported in a bunch of other threads:

* #13108
* #13046
* #12249

et. al.

I'm assuming it's a duplicate of one of those.

**Comment by qihs97** [comment] 2022-06-21 13:07
Yep，I met the same problem as #13108<https://github.com/microsoft/terminal/issues/13108> .
My Windows specification:
版本       Windows 11 家庭中文版
版本       21H2
安装日期       ‎2021/‎12/‎19
操作系统版本       22000.739
序列号    PF3BLWCG
体验       Windows 功能体验包 1000.22000.739.0
Edition Windows 11 Home
Version 21H2
Installed on ‎2021/‎12/‎19
OS build 22000.739
Experience Windows Feature Experience Pack 2021/‎12/‎19
Windows Terninal Version: 1.13.1143


发件人: Mike Griese ***@***.***>
发送时间: 2022年6月21日 19:59
收件人: microsoft/terminal ***@***.***>
抄送: qihs97 ***@***.***>; Author ***@***.***>
主题: Re: [microsoft/terminal] win11开始菜单右键Windows终端不能运行 (Issue #13347)


Sorry, you'll have to give us more information. What OS build are you using, which Terminal version, how did you install the Terminal, etc. This sounds like an issue that's been reported in a bunch of other threads:

  *   #13108<https://github.com/microsoft/terminal/issues/13108>
  *   #13046<https://github.com/microsoft/terminal/issues/13046>
  *   #12249<https://github.com/microsoft/terminal/issues/12249>

et. al.

I'm assuming it's a duplicate of one of those.

**Comment by zadjii-msft** [comment] 2022-06-21 13:39
Thanks for confirming!

/dup #13108

**Closed by zadjii-msft** 2022-06-21 13:39 UTC
Labels: Needs-Triage, Needs-Attention, Needs-Tag-Fix
