### ISSUE TITLE
How soon can it be used in Windows 1803?

### ISSUE THREAD

**Issue by lsongseven** [microsoft/terminal#3285] opened 2019-10-22 07:10 UTC
# Description of the new feature/enhancement
My windows version is 1803, but I want to try this cool terminal. So how soon can it come into reality?

# Proposed technical implementation details (optional)

**Comment by MitchTalmadge** [comment] 2019-10-22 07:31
Probably never unless some of the new features of 1903 (like XAML Islands) get ported to the older versions, which may never happen.

For more reasons see this comment: 

https://github.com/microsoft/terminal/issues/2480#issuecomment-523020964

**Comment by DHowett-MSFT** [comment] 2019-10-22 18:23
Sorry. ☹️ I'm closing this as a /dupe of #2480 as suggested by @MitchTalmadge. Thanks, Mitch!

**Closed by DHowett-MSFT** 2019-10-22 18:23 UTC
Labels: Issue-Feature, Needs-Tag-Fix, Needs-Triage
