### ISSUE TITLE
Fonts with programming ligatures show weird behavior

### ISSUE THREAD

**Issue by MCorzo** [microsoft/Terminal#514] opened 2019-05-07 15:10 UTC
When fonts with programming ligatures is used, a weird behavior is show if write some characters at first, for example with [FiraCode](https://github.com/tonsky/FiraCode).

![image](https://user-images.githubusercontent.com/12452450/57310925-47a40f80-70b0-11e9-93a3-2cc251c618d6.png)

![image](https://user-images.githubusercontent.com/12452450/57310942-512d7780-70b0-11e9-94d3-5a57d5832d0e.png)

**Comment by zadjii-msft** [comment] 2019-05-07 15:14
I mean, isn't that how ligatures normally work? They can't really tell the difference between `system32>=some_cmd` and `if (system32>=foo)`

**Comment by puco** [comment] 2019-05-07 16:18
Well, but maybe there should be some stop-character (by default?) that prevents a ligature in this case

**Comment by zadjii-msft** [comment] 2019-05-07 16:22
@puco Is there such a character?

If there is, then you could definitely add it to your prompt, with `PROMPT $p$g<whatever the char is>`.

However, that doesn't really seem like it's a solution that'll work for all cases

**Comment by RichiCoder1** [comment] 2019-05-07 17:55
I think you can use: https://en.wikipedia.org/wiki/Zero-width_non-joiner

**Comment by vapier** [comment] 2019-05-07 20:01
fonts are free to define any arbitrary ligatures they want, so if you were to try to use a ZWNJ character to defeat the ligatures, then you'd have to insert them between every single character.  which would probably then break logic related to graphemes when formed by multiple characters (e.g. separate jamo in korean hangul which should be presented as a single glyph).

in css, there is a [font-variant-ligatures: none](https://developer.mozilla.org/en-US/docs/Web/CSS/font-variant-ligatures) that you can use to disable ligature usage during font rendering.  i'd assume that whatever font rendering engine used by the terminal would have a similar knob that could be turned ...

**Comment by RichiCoder1** [comment] 2019-05-07 20:03
To be clear, I was suggesting zwnj for the end of prompt by default. It would absolutely be a bad idea to use to remove ligatures everywhere.

**Comment by zadjii-msft** [comment] 2019-05-07 20:05
>  i'd assume that whatever font rendering engine used by the terminal would have a similar knob that could be turned ...

I believe this _is_ something we could work with. I believe @miniksa already has a list of renderer knobs he's thinking about exposing as settings

**Comment by Tyriar** [comment] 2019-05-08 15:15
This looks as designed to me, trying to do some trickery with ZWJ that only works in Windows Terminal sounds like the wrong direction. If you use ligatures and hit this often you should probably just change your prompt.

**Comment by DHowett-MSFT** [comment] 2019-05-08 15:29
what if we broke ligatures when we were overlaying the COOKED_READ data? That would solve it for CMD specifically ...

________________________________

**Comment by zadjii-msft** [comment] 2019-05-08 15:40
@DHowett-MSFT that's not a terrible idea, but I'm not sure how we could render that without sticking a fake ZWNJ in the buffer, or rendering that ZWNJ via conpty. It's certainly something that could be investigated, but I don't have high hopes it would work easily

**Comment by miniksa** [comment] 2019-05-13 23:23
OK. This weird behavior, as is, is by design. I've created two follow-on issues to dig into the different proposals here as they're separate concerns. I'll close this one as is so other complaints can be duped here.

**Closed by miniksa** 2019-05-13 23:23 UTC
Labels: Area-Fonts, Area-Rendering, Issue-Question, Resolution-By-Design

**Comment by Luuk34** [comment] 2020-04-27 15:47
'Resolutin-By-Design'..... LOL,   Design must be .... 👎

**Comment by zadjii-msft** [comment] 2020-04-27 15:58
@Luuk34 This is literally the design of how ligatured fonts work. If you don't like ligatured fonts, then you're free to 
* pick any of the gazillions of fonts that are out there that _don't_ have liagtured glyphs
* wait for the next release to come out where we switch to "Cascadia Mono" (without ligatures) instead of "Cascadia Code" (with ligatures) (see #5505)
* Help us implement settings for disabling ligatures #759 

but comments like "Design must be .... 👎" aren't really constructive here.

**Comment by NicTanghe** [comment] 2020-06-21 15:18
How is it not constructive when someone gives you the most valuable information.
It pops up in a lot of different places.
From the second any other party has any responsibility Microsoft's approach has classically been its fully up to them to resolve any issues especially if it's regarding customizing aesthetics>

All that is being asked is an exception in code that states.

```
IF 
$path + >+ = 
Don`t
Use the code to render ligatures on  + > = 
```

And of course a toggle switch because people who know what they are doing don't want permanent decisions  made for them.

Please don't view  negative feedback as unconstructive.
