### ISSUE TITLE
Reduce tab area so it is easier to drag the window

### ISSUE THREAD

**Issue by gabog** [microsoft/terminal#2062] opened 2019-07-22 17:04 UTC
# Summary of the new feature/enhancement

Currently it is only possible to drag the terminal window by clicking on the (small) empty space between the + sign and the minimize/maximize buttons.

![image](https://user-images.githubusercontent.com/12264946/61650029-ba209680-ac80-11e9-9345-98f594d0ed16.png)

This is a bit confusing and I find myself trying to drag the window by clicking on the huge white space between the last tab and the + button:

![image](https://user-images.githubusercontent.com/12264946/61650076-d91f2880-ac80-11e9-828c-07eb702ed7ba.png)

# Proposed technical implementation details

It would be nice if the Terminal window would behave like Edge or Chrome where the + button is right near the last tab and you can drag the window by clicking on the empty space between the + symbol and the minimize button:

Edge:
![image](https://user-images.githubusercontent.com/12264946/61650185-213e4b00-ac81-11e9-82fb-2cac1ab914ae.png)

Chrome:
![image](https://user-images.githubusercontent.com/12264946/61650214-3024fd80-ac81-11e9-8345-e157e1f78869.png)

**Comment by JushBJJ** [comment] 2019-07-22 17:12
Duplicate of #564

**Comment by JushBJJ** [comment] 2019-07-22 17:13
It will be fixed in Preview 2.
https://github.com/microsoft/terminal/pull/1948

**Closed** 2019-07-22 17:42 UTC
Labels: Issue-Feature, Needs-Tag-Fix, Needs-Triage
