### ISSUE TITLE
enter_insert_mode / exit_insert_mode not respected (bug?)

### ISSUE THREAD

**Issue by Dweeberly** [microsoft/terminal#8600] opened 2020-12-16 18:16 UTC
# Environment

```
OS Name:                   Microsoft Windows 10 Enterprise
OS Version:                10.0.18363 N/A Build 18363
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Member Workstation
Ubuntu (wsl2): Linux d10c167 4.19.128-microsoft-standard #1 SMP Tue Jun 23 12:58:10 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
Windows Terminal: 1.4.3243.0
```

Any other software?
```
No
```
# Steps to reproduce
I'm not sure if I should call this a bug, a feature request or working as designed.  I couldn't find a definitive list of terminal capabilities and the terminfo docs I found were not as clear as I would have liked.  In this case it appears that the enter_insert_mode and exit_insert_mode capabilities are not supported.  See SO https://superuser.com/questions/1603309/vi-command-line-editing-insert-mode-overwrite/1610427#1610427 for additional detail.

In a Ubuntu (terminfo) environment you can see it with the following commands:
```
> echo -n "aaa";tput cub1;tput ich1;echo "b"
aaba
> echo -n "aaa";tput cub1;tput smir;echo "b";tput rmir
aab
```
if smir/rmir were respected I would expect to see both result strings equal to each other.

# Expected behavior
I would expect that when the terminal receives the smir/im (enter_insert_mode) sequence that it would insert characters at the current cursor position until a rmir/ei (exit_insert_mode) sequence is received.

# Actual behavior
smir/im (enter_insert_mode) appears to be ignored and characters entered begin overwriting at the current cursor position.

**Comment by DHowett** [comment] 2020-12-16 18:30
This sounds like a /duplicate of #1947. We're working on it :smile:

**Closed by DHowett** 2020-12-16 18:30 UTC
Labels: Needs-Tag-Fix, Needs-Triage
