### ISSUE TITLE
Extra console window after usage of command line in Far Manager

### ISSUE THREAD

**Issue by shvez** [microsoft/terminal#4655] opened 2020-02-20 07:13 UTC
hi, there.

thank you for great product

I'm using WT version 0.9.433.0
I managed to add Far manager to list of consoles using official documentation 

When I open it and execute 'dir' command new external console window gets open.
after that it starts to be possible to scroll panels in far (this does not happen if far start from CMD)

# Environment

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Windows Terminal version (if applicable):

Any other software?
```

# Steps to reproduce

# Expected behavior

# Actual behavior

**Comment by DHowett-MSFT** [comment] 2020-02-20 18:21
What version of Far manager? I cannot reproduce this with 3.0b5225, a version I had laying around.
If this changed between Far manager versions, it is probably a Far regression...

**Comment by shvez** [comment] 2020-02-21 10:32
@DHowett-MSFT 
Far manager: Far Manager, version 3.0.0.5511 x64

**Comment by DHowett-MSFT** [comment] 2020-02-21 22:16
Sorry, can you clarify the behavior further? Even with 3.0.0.5511 I cannot get an _external_ console window to appear, even if I follow your steps exactly.

 Are you referring to the behavior where Far disappears (turns black), then reappears, and the response from dir reappears when you scroll up?

**Comment by shvez** [comment] 2020-03-24 08:22
sorry for delay.
I hoped I will be able to capture video using xbox toolbar, but now it captures only one window

I removed terminal and installed last version. I have inserted configuration for far manager. I took config snippet from your docs
here it is
```
        {
          "name": "Far",
          "commandline": "C:\\_Work_\\_Tools_\\Far\\Far.exe",
          "startingDirectory": "%USERPROFILE%",
          "useAcrylic": false
        }
```

now after opening far I do not do anything and new console window just appears in letf top corner of the screen. I took snapshot
With red arrows I marked console window itself and terminal Icon in task bar. you may see there that there are two windows there.

![image](https://user-images.githubusercontent.com/7521076/77403454-ed3f9a80-6db8-11ea-90c5-f600e29eac33.png)

Far manager still has version 3.0.0.5511 x64

**Comment by DHowett-MSFT** [comment] 2020-03-24 17:59
Can you use [Process Explorer](https://docs.microsoft.com/en-us/sysinternals/downloads/process-explorer)'s Find tool to pinpoint the owner of that window, and its commandline? I still can't repro :( sorry.

### find tool

![image](https://user-images.githubusercontent.com/14316954/77460612-91781000-6dbe-11ea-9fba-da5a5a5645f4.png)


Drag it over the window you're curious about; hover over the process's entry in the list

![image](https://user-images.githubusercontent.com/14316954/77460587-84f3b780-6dbe-11ea-827a-6da4d6324958.png)

**Comment by shvez** [comment] 2020-03-26 11:44
here it is:
![image](https://user-images.githubusercontent.com/7521076/77643397-f1f68100-6f67-11ea-8b34-49d1cbdcec06.png)

**Comment by shvez** [comment] 2020-03-26 11:57
I think I found reason for this issue. I believe that it is because of installed ConEmu plugin

if I use clean install of far it does not create new console window although issue with dir still there. after its usage you may scroll far panels up and down using mouse wheel

**Comment by zadjii-msft** [comment] 2020-03-26 12:49
Thanks for following up! Since this window is being created by the ConEmu plugin, I'm gonna close this as external ☺️

**Closed by zadjii-msft** 2020-03-26 12:49 UTC
Labels: Needs-Attention, Needs-Tag-Fix, Needs-Triage

**Comment by psvz** [comment] 2022-11-12 15:41
after recent windows update FAR starts inside separate CMD inside Powershell shit.
