### ISSUE TITLE
Unable to run pwsh in Cloud Shell

### ISSUE THREAD

**Issue by Agazoth** [microsoft/terminal#4694] opened 2020-02-22 12:49 UTC
When running pwsh in Cloud Shell i get this wierd jibberish:

```powershell
axel@Azure:~$ pwsh
PowerShell 7.0.0-rc.2
Copyright (c) Microsoft Corporation. All rights reserved.

https://aka.ms/powershell
Type 'help' to get help.

   A new PowerShell preview release is available: v7.0.0-rc.3
   Upgrade now, or check out the release page at:
     https://aka.ms/PowerShell-Release?tag=v7.0.0-rc.3


MOTD: Scripts installed with 'Install-Script' can be run from the shell

VERBOSE: Authenticating to Azure ...
VERBOSE: Building your Azure drive ...
Loading personal and system profiles took 3858ms.
Azure:/
PS Azure:\>
���~@@�a�@@@@@@@@@@@@@@@@@@�Y��@@@@@@@@@@iles took 3858msk@l@w@{@5@|@o@@@@�����������������������������m@s@c@o@r@l@i@b@��~@@@@@@@@��@ @@�]b3@@��@ @@�MY�@@��X�@@��23@@���~@@��X�@@053@@053@@���~@@��23@@@ ^CAzure:/
PS Azure:\> axel@Azure:~$
```
and it just returns to Bash

**Comment by DHowett-MSFT** [comment] 2020-02-24 07:52
This should be way, way better with the merge of #4652, but .. I've never seen this particular version of this bug. It looks like it's printing arbitrary memory from the powershell process (evidenced by the `m.s.c.o.r.l.i.b.` in the output), which is just something Terminal cannot cause o_O

It might be worth filing a feedback item inside the azure portal -- though perhaps this is a general powershell 7.0 on linux bug. Might be good to ask there, too.

If this happens every time in Terminal, but _never_ from shell.azure.com, I'll be quite surprised.

For now, I'm inclined to mark it as a partial duplicate of #2267 (the real reason we couldn't use pwsh in AzCs) and partial external issue.

**Closed by DHowett-MSFT** 2020-02-24 07:52 UTC
Labels: Needs-Tag-Fix, Needs-Triage

**Comment by Agazoth** [comment] 2020-02-24 08:49
This actually only happens in Terminals and very consistently. I never have the same issue in shell.azure.com.

I use AOBO to log on to different tenants. I guess that could have some effect on this.
