### ISSUE TITLE
Bug Report: "PowerShell has stopped working" error after closing the Terminal app

### ISSUE THREAD

**Issue by wozniakpawel** [microsoft/terminal#2269] opened 2019-08-05 20:38 UTC
# Environment

Windows build number: 10.0.18362.239
Windows Terminal version (if applicable): 0.3
Relatively clean OS, Ubuntu and WSL installed.

# Steps to reproduce

1. Open the Terminal app
2. Close the Terminal app

Only happens when the terminal is closed and PS is the active tab. Does not happen if Ubuntu or command line is the active tab or if I close a PS tab but Terminal app stays open.

# Expected behavior

I expect it to close with no errors

# Actual behavior

An error pops out telling me that "PowerShell has stopped working" as in the screenshot.
"Standard" PowerShell works just fine.

<img width="265" alt="PowerShell has stopped working error in Terminal" src="https://user-images.githubusercontent.com/29314003/62493451-0f07f500-b7c9-11e9-83de-13369874dac3.png">

**Comment by DHowett-MSFT** [comment] 2019-08-05 21:20
Duplicate of #2185. Fixed, but not in the v0.3 release.

**Closed by DHowett-MSFT** 2019-08-05 21:20 UTC
Labels: Needs-Tag-Fix, Needs-Triage
