### ISSUE TITLE
Run many tabs from .bat file

### ISSUE THREAD

**Issue by itamardavidyan** [microsoft/terminal#3913] opened 2019-12-11 09:14 UTC
Now I use run.bat like this:
```
cd C:\code\repo
start cmd.exe /k "ng serve xxx-svc --port=7700"
start cmd.exe /k "ng serve yyy-svc --port=7701"
start cmd.exe /k "ng serve zzz-svc --port=7702"
...
...
```

I want all the services to open in the same wt.exe window. there is an option to do it?

**Comment by zadjii-msft** [comment] 2019-12-11 13:41
Hey thanks for the suggestion! We're actually working on a design for this feature currently! You can follow it's progress over in #3495. With the proposed design, you'll be able to run the following:

```
wt new-tab "ng serve xxx-svc --port=7700" ; new-tab "ng serve yyy-svc --port=7701" ; new-tab "ng serve zzz-svc --port=7702"
```

or even:
```
wt "ng serve xxx-svc --port=7700" ; "ng serve yyy-svc --port=7701" ; "ng serve zzz-svc --port=7702"
```

to achieve what you're looking for.

Largely, this is a /dupe of #607 and #756

**Closed by zadjii-msft** 2019-12-11 13:41 UTC
Labels: Needs-Tag-Fix, Needs-Triage
