### ISSUE TITLE
Enable launching of any terminal profile directly from taskbar (and not just the default profile)

### ISSUE THREAD

**Issue by imbaig-ms** [microsoft/terminal#6667] opened 2020-06-24 22:01 UTC
# Description of the new feature/enhancement
I have several terminal profiles created, and my typical workflow is as follows:
1) Launch WindowsTerminal, which launches the terminal selected in the default profile.
2) Launch my custom terminal from the dropdown selections (or use the Ctrl-Shift-x shortcuts).

My request here is to make the available profiles accessible from the taskbar, on right-click. Here's an example of how this may look:

![image](https://user-images.githubusercontent.com/52172156/85632010-5f7b8180-b62b-11ea-95e7-804f3e91ddba.png)

# Proposed technical implementation details (optional)

**Comment by DHowett** [comment] 2020-06-24 22:03
Thanks for the request! This is a /dupe of #576.

**Closed by DHowett** 2020-06-24 22:03 UTC
Labels: Issue-Feature, Needs-Tag-Fix, Needs-Triage

**Comment by imbaig-ms** [comment] 2020-06-24 22:34
> Thanks for the request! This is a /dupe of #576.

Great!
