### ISSUE TITLE
Graphical issue with Windows Terminal

### ISSUE THREAD

**Issue by yosefahab** [microsoft/terminal#9637] opened 2021-03-27 10:19 UTC
Text starts pixelating/bleeding over time when running windows terminal, i can confirm it happens with all color schemes.
Maximising/minimising the window resets the text back to the original colors but then it reoccurs again.
I've attached 2 screenshots of the terminal to compare it before waiting a couple of seconds and after waiting, notice how the colors become brighter and pixelated
![WT2](https://user-images.githubusercontent.com/61936188/112717613-93efd700-8ef6-11eb-8672-1f9046928a6b.png)

![WT1](https://user-images.githubusercontent.com/61936188/112717609-905c5000-8ef6-11eb-810e-1767da302d8d.png)

**Comment by j4james** [comment] 2021-03-27 12:56
Have you tried different antialiasing options? See the documentation here:
https://docs.microsoft.com/en-us/windows/terminal/customize-settings/profile-advanced#text-antialiasing

Also, it would be helpful if you mention the version of Windows Terminal that you're using.

**Comment by j4james** [comment] 2021-03-27 13:08
You may also want to try the experimental rendering settings to see if they help in any way.
https://docs.microsoft.com/en-us/windows/terminal/customize-settings/rendering

**Comment by yosefahab** [comment] 2021-03-27 13:20
> You may also want to try the experimental rendering settings to see if they help in any way.
> https://docs.microsoft.com/en-us/windows/terminal/customize-settings/rendering

i've tested different antialiasing options but it doesnt seem to affect is, however adding ("experimental.rendering.forceFullRepaint": true ) seems to fix it.

Any idea why this problem is caused in the first place?

**Comment by j4james** [comment] 2021-03-27 13:38
> Any idea why this problem is caused in the first place?

My understanding was that option was added to work around problems with certain display drivers. You can read more about it in PR #5853.

**Comment by DHowett** [comment] 2021-03-28 04:06
Yep! Thanks @j4james! This is a /duplicate of #5759. There is an antialiasing setting for some Intel cards that causes it to _melt_ Terminal’s display.

**Closed by DHowett** 2021-03-28 04:06 UTC
Labels: Needs-Tag-Fix, Needs-Triage
