### ISSUE TITLE
Clicking on link in JSON object adds trailing double-quote

### ISSUE THREAD

**Issue by heidemn-faro** [microsoft/terminal#17468] opened 2024-06-24 11:29 UTC
### Windows Terminal version

1.20.11381.0

### Windows build number

10.0.19045.4412

### Other Software

Ubuntu 20.04.6 LTS

### Steps to reproduce

1. Run in Bash:

```
echo '{"deepLink":"https://httpbin.org/"}'
```

2. Click on the link, either in the commandline or in the output.
   (Note how the highlighting of the link is correct, and is inconsistent with the link which will be opened.)

![image](https://github.com/microsoft/terminal/assets/66078329/72e02003-43cf-42d2-bb3f-99c78b1bdf0c)

### Expected Behavior

This link is opened:
`https://httpbin.org/`

### Actual Behavior

This link is opened (with trailing double-quote):
`https://httpbin.org/%22`

![image](https://github.com/microsoft/terminal/assets/66078329/c792d59d-a73b-4b54-82a5-6fd14dc8efb3)

**Comment by heidemn-faro** [comment] 2024-06-24 11:41
Thanks @KalleOlaviNiemitalo . Didn't find it since it's already closed...

**Comment by linyue0103** [comment] 2024-06-24 12:11
the decouraged apartment will disappeared in url website and document will closed by time

**Comment by DHowett** [comment] 2024-06-26 21:24
Thanks for filing! This is a /dupe of #17323.

@heidemn-faro We close bugs to track when they were committed to the main branch as a rule, only because it's strictly easier at release time than keeping track of the three active release channels. :)

**Closed** 2024-06-26 21:24 UTC
Labels: Issue-Bug, Needs-Triage

**Comment by linyue0103** [comment] 2024-06-27 11:16
accompiant



---- Replied Message ----
| From | ***@***.***> |
| Date | 06/27/2024 05:25 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [microsoft/terminal] Clicking on link in JSON object adds trailing double-quote (Issue #17468) |

Hi! We've identified this issue as a duplicate of another one that already exists on this Issue Tracker. This specific instance is being closed in favor of tracking the concern over on the referenced thread. Thanks for your report!
