### ISSUE TITLE
Malformed paste on Cmder/ConEmu

### ISSUE THREAD

**Issue by Apjue** [microsoft/terminal#191] opened 2018-05-23 15:44 UTC
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)

Microsoft Windows [version 10.0.17134.48]

* What you're doing and what's happening: (Copy & paste specific commands and their output, or include screen shots)

(I am using Cmder v1.3.5, itself being a wrapper around ConEmu)
I'm copying some text into a bash.exe tab, for example `dircolors --print-database > ~/.mydircolors` and pasting it into Cmder

* What's wrong / what should be happening instead:

The paste is malformed, for example I only have `dircolors` when pasting the command above
This problem only occurs when using bash.exe in Cmder, when using wslbridge* the paste is okay

*: This is wslbridge task command:
`
set "PATH=%ConEmuBaseDirShort%\wsl;%PATH%" & %ConEmuBaseDirShort%\conemu-cyg-64.exe --wsl -cur_console:pm:/mnt
`

(See also https://github.com/Maximus5/ConEmu/issues/1314)

When pasting the same text into bash.exe without Cmder (standard windows's cmd), everything is fine
I don't know if I should create the issue here or on ConEmu's github, but the issue I linked is a bit dead

I can use wslbridge task (the "connector") but it behaves weirdly, I would like to stay with bash

**Comment by zadjii-msft** [comment] 2018-05-23 15:52
> When pasting the same text into bash.exe without Cmder (standard windows's cmd), everything is fine

Then this definitely sounds like an issue with ConEmu then :) I'd follow up either on that issue or file a new one on the conemu repo, whetever's in line with their contribution policies.

**Comment by Maximus5** [comment] 2018-05-23 19:51
It's not a ConEmu issue, but definitely a conhost and WinAPI problem.
I've reported this several times by mail to console team but it's still there.

Brief:
1. ConEmu calls WriteConsoleInput to put text into conhost input buffer. There is no another way to do that.
2. I don't know what does WSL/Bash, but when it runs directly in ConEmu (without wslbridge) input is *always* malformed.

With connector - everything is OK.
ConEmu uses the same method to transfer text.
I see only one conclusion from these facts.

**Comment by miniksa** [comment] 2018-05-23 19:53
@Maximus5, can you bump the mail thread? I'm sorry if you sent it to us in mail and we lost track of it.

**Comment by miniksa** [comment] 2018-05-23 20:02
I think I found the mail thread. Is this Maximus5/ConEmu#760? I think I filed that as MSFT:8105691. 
It is still on our backlog, we just haven't had time for it yet.

**Comment by Maximus5** [comment] 2018-05-23 21:20
Yes, I meant that report.
Well, with WSL/Bash things become much worse, because only part of posted text reaches Linux application.

**Comment by Maximus5** [comment] 2018-05-23 22:04
I'm really sorry, but I just realised that @S6066 uses old ConEmu build (18.02.06).
And there was fixed issue https://github.com/Maximus5/ConEmu/issues/1545.
Malformed output was result of immediate reject from WriteConsoleInput if any item from lpBuffer has EventType=0.
Perhaps, this issue should be closed indeed.

**Comment by S6066** [comment] 2018-05-24 17:50
I should have updated before creating the issues, sorry.
Does it mean it can be closed?

**Comment by DHowett** [comment] 2018-05-25 00:51
If you've updated and the issue no longer reproduces, then yes.

**Comment by miniksa** [comment] 2019-05-18 04:34
Closing as this appears to have solved itself over time.

**Closed by miniksa** 2019-05-18 04:34 UTC
Labels: Area-Interaction, Issue-Bug, Product-Conhost, Resolution-External
