### ISSUE TITLE
Broadcast keyboard input in multiple split pane

### ISSUE THREAD

**Issue by bhowmickkrishnendu** [microsoft/terminal#14306] opened 2022-10-29 17:27 UTC
In and out best split pane features is yet to introduce. Broadcast keyboard input option not available in windows terminal split pane.  Every split pane need to enter sperate input till now. When we connect to deploy same configuration to different  server console, it will help us make our job easy.

**Comment by j4james** [comment] 2022-10-29 17:39
I think what you're requesting is already being tracked in issue #2634.

**Comment by bhowmickkrishnendu** [comment] 2022-10-29 18:03
> I think what you're requesting is already being tracked in issue #2634.

@j4james Is it going introduce in next update ?

**Comment by j4james** [comment] 2022-10-29 18:43
> @j4james Is it going introduce in next update ?

No, I don't think so. If you look at the "Milestone" indicator on that issue, you can see it's set to "Backlog". That means there are no immediate plans to implement it.

**Comment by lhecker** [comment] 2022-10-30 13:04
I believe James is right: This is a /duplicate of #2634.

**Closed** 2022-10-30 13:04 UTC
Labels: Needs-Triage, Needs-Tag-Fix
