### ISSUE TITLE
Terminal crashes when second-last tab is closed and alwaysShowTabs is false

### ISSUE THREAD

**Issue by TBBle** [microsoft/terminal#3652] opened 2019-11-21 06:24 UTC
# Environment

```none
Windows build number: Microsoft Windows NT 10.0.18362.0
Windows Terminal version (if applicable): 0.6.2951.0

Any other software?
```

# Steps to reproduce

1 Set the following global settings in profile.json
```json
    "alwaysShowTabs": false,
    "showTabsInTitlebar": false,
```

2 Start Terminal
 * No tab bar visible

3 _Control-Shift-t_ to create a new tab
 * Here it's PowerShell Core, but reproduces with git-bash for example
 * Tab bar becomes visible here.
 * Switching between tabs here does not affect the outcome.

4 Type `exit` to terminate the currently-visible shell
 * Middle-clicking the active tab also works. Middle-clicking the *other* tab does not reproduce.
 * If extra shells were opened, this doesn't reproduce, it seems to only happen when the tab bar is hidden as part of closing the current tab.
 * Setting close-on-exit means this doesn't reproduce until the tab is closed, so not related to the shell process terminating.

# Expected behavior

* Current tab closes
* Tab bar disappears
* Other tab is usable.

# Actual behavior

* Current tab closes
* Tab bar disappears
* (!!) Other tab content is visible, but cursor is not flashing and input is not handled
* (!!) A few seconds later, the application crashes, logged in Event Viewer:

```
Faulting application name: WindowsTerminal.exe, version: 1.0.1910.22001, time stamp: 0x5daf7ab2
Faulting module name: TerminalControl.dll, version: 1.0.1910.22001, time stamp: 0x5daf7988
Exception code: 0xc0000005
Fault offset: 0x0000000000008268
Faulting process ID: 0x2bec
Faulting application start time: 0x01d5a030043b34f4
Faulting application path: C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_0.6.2951.0_x64__8wekyb3d8bbwe\WindowsTerminal.exe
Faulting module path: C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_0.6.2951.0_x64__8wekyb3d8bbwe\TerminalControl.dll
Report ID: eb98c87f-b71c-4108-97b3-626d6a0af7f1
Faulting package full name: Microsoft.WindowsTerminal_0.6.2951.0_x64__8wekyb3d8bbwe
Faulting package-relative application ID: App
```

I have raised a Feedback Hub issue, but it has not yet appeared in "My feedback". I'll update this ticket once it's showing up (it said it would take a few minutes, but now it shows nothing...)

**Comment by DHowett-MSFT** [comment] 2019-11-21 20:37
I'm marking this one for feedback until we get that link. Thanks!

**Comment by TBBle** [comment] 2019-11-22 05:35
My original feedback never appeared, so I recreated it on another machine: https://aka.ms/AA6p585

Here is the Application Error in Event Viewer. It looks the same as the one from my other machine
```
Faulting application name: WindowsTerminal.exe, version: 1.0.1910.22001, time stamp: 0x5daf7ab2
Faulting module name: TerminalControl.dll, version: 1.0.1910.22001, time stamp: 0x5daf7988
Exception code: 0xc0000005
Fault offset: 0x0000000000008268
Faulting process ID: 0x4144
Faulting application start time: 0x01d5a0f636dc63b3
Faulting application path: C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_0.6.2951.0_x64__8wekyb3d8bbwe\WindowsTerminal.exe
Faulting module path: C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_0.6.2951.0_x64__8wekyb3d8bbwe\TerminalControl.dll
Report ID: af74987f-91be-4e0f-913b-8fa7701c124e
Faulting package full name: Microsoft.WindowsTerminal_0.6.2951.0_x64__8wekyb3d8bbwe
Faulting package-relative application ID: App
```

**Comment by DHowett-MSFT** [comment] 2019-11-25 20:12
Based on the signature, this looks like a /dupe of #2947. Thanks for the report!

**Closed by DHowett-MSFT** 2019-11-25 20:12 UTC
Labels: Needs-Attention, Needs-Tag-Fix, Needs-Triage
