### ISSUE TITLE
Initial window height calculation regression

### ISSUE THREAD

**Issue by mcpiroman** [microsoft/terminal#3472] opened 2019-11-07 19:35 UTC
Initial window height is off by titlebar height. This got regressed by #3394 in:

https://github.com/microsoft/terminal/blob/357e835f5d37492812e33eac1dd995232c19de63/src/cascadia/WindowsTerminal/AppHost.cpp#L197-L210

That also blocks #3181 which relys on this size calculation.

# Steps to reproduce
1. Set `fontSize` to 50
2. Set `initialRows` to 2
3. Launch terminal

# Expected behavior

2 rows should fit in the window

# Actual behavior

About 1.5 of a row fits.

cc @greg904.

**Comment by greg904** [comment] 2019-11-07 19:57
Are you sure it's a regression? I just tried with 6f36f8b (before the PR was merged) and the size is also incorrect.

Before the PR, it was calling `GetFrameMargins` to calculate the size which looks like it includes the title bar's height because it calls `GetDragAreaRect` and adds the height to the result BUT during my debugging I found that during the initialization, the drag bar is not set yet so `GetDragAreaRect` returns 0 so `GetFrameMargins` doesn't include the title bar.

**Comment by zadjii-msft** [comment] 2019-11-07 20:43
For the record, I don't _believe_ this regressed. I thought it was always broken 😝

**Comment by zadjii-msft** [comment] 2019-11-07 20:50
Also, I think this one is probably a /dupe of #2061

**Closed by zadjii-msft** 2019-11-07 20:51 UTC
Labels: Area-User Interface, Issue-Bug, Needs-Triage, Product-Terminal

**Comment by mcpiroman** [comment] 2019-11-08 07:42
Ah ok then, sorry for my accusement. My PR stopped working after I merged with this one because of removed GetDragArea, but I didn't realized it wasn't working with initial sizing before. As to solving this problem, #3182 might help.
