### ISSUE TITLE
Open multiple default profiles

### ISSUE THREAD

**Issue by jdhitsolutions** [microsoft/terminal#5891] opened 2020-05-13 20:47 UTC
# Description of the new feature/enhancement
I did a user group presentation last night on getting started with Windows Terminal. One of the attendees had a question that I thought would make a good enhancement.  Is there a way to have more than one default profile? In other words, when I open WT I'd like to have 2 specific tabs open. As far as I can tell this isn't possible now.

# Proposed technical implementation details (optional)

It seems the easiest solution would be to enable the `defaultProfile` to include a list of default profiles. Maybe something like this:

```json
    "defaultProfile": [
        "list": {
             "{993855ad-b0eb-4f3d-8370-1a8d5b53abb5}"
        },
        {
        "{c6783a98-47d9-4610-bc68-7a3f909e94fb}"
        }
```

**Comment by DHowett-MSFT** [comment] 2020-05-14 01:31
Thanks for the request! This is a /dupe of #756.

**Closed by DHowett-MSFT** 2020-05-14 01:31 UTC
Labels: Issue-Feature, Needs-Tag-Fix, Needs-Triage
