### ISSUE TITLE
Windows Clipboard History conflicts with Windows Terminal

### ISSUE THREAD

**Issue by mohamedmansour** [microsoft/terminal#3176] opened 2019-10-13 08:42 UTC
Pressing Win+V on Windows 10 (to access your clipboard history) doesn't allow you to use your keyboard to navigate the clipboard. The Windows Terminal intercepts all keystrokes, not allowing Windows Clipboard History to be keyboard accessible.

The expected behaviour is when the user presses Win+V, Windows Terminal should not intercept keystrokes, and allow Windows Clipboard History to do its job with Keyboard

**Comment by DHowett-MSFT** [comment] 2019-10-14 19:52
This has hints of #459 in it (it looks like cloud clipboard is using an IME now?) but broadly it seems to be something they're doing wrong. Now, critically, when you _select_ something from cloud clipboard their inflexibility in what an application should use as its "paste" key binding will make it so that you can't even _paste_ the selected entry...

**Comment by DHowett-MSFT** [comment] 2020-01-13 18:00
Since the IME landed, I can't reproduce this any more. Pasting still doesn't work, but that's not part of the original report. :smile:

**Closed by DHowett-MSFT** 2020-01-13 18:00 UTC
Labels: Area-TerminalControl, Help-Wanted, Issue-Bug, Product-Terminal, Resolution-External
