### ISSUE TITLE
Scrolling speed with mouse is too quick

### ISSUE THREAD

**Issue by sovaska** [microsoft/terminal#3340] opened 2019-10-26 14:21 UTC
Speed is much quicker than with any of other applications in my Lenovo and Dell laptops. Scrolling speed should be slower, or there should be a way to adjust the speed in configuration.

**Comment by j4james** [comment] 2019-10-26 17:07
This might be a duplicate of #1066.

**Comment by sovaska** [comment] 2019-10-26 17:15
Thanks, sounds similar!

**Comment by DHowett-MSFT** [comment] 2019-10-26 18:07
It sure is! Thanks, James! /dup #1066.

**Closed by DHowett-MSFT** 2019-10-26 18:07 UTC
Labels: Needs-Tag-Fix, Needs-Triage
