### ISSUE TITLE
No "Run As administrator" when pinned to taskbar - right click menu

### ISSUE THREAD

**Issue by merlinbeedell** [microsoft/terminal#7893] opened 2020-10-12 09:47 UTC
# Environment

```none
Windows build number: 10.0.19041.0
Windows Terminal version (if applicable):  1.3.2651.0

Any other software?
```

# Steps to reproduce

Pin the WT to the taskbar.  Right-click the taskbar icon so it could be 'run as administrator' but option is not provided.

# Expected behavior

Right-Click menu to provide a "Run as administrator" option, same as it does in the Start panel.

# Actual behavior

Provides only Start / Unpin / Close options

**Comment by skyline75489** [comment] 2020-10-12 10:07
There's #7715 that's tracking this.

**Comment by KalleOlaviNiemitalo** [comment] 2020-10-12 12:15
If you first right-click the taskbar icon of Windows Terminal, and next right-click the "Windows Terminal" item in the menu that pops up, then you should get a second menu that includes "Open" and "Run as Administrator". This behaviour is consistent with the Skype and Teams apps.

<https://github.com/microsoft/terminal/issues/7715> requests "Run as Administrator" for each profile, not for the whole app.

**Comment by zadjii-msft** [comment] 2020-10-12 22:38
Yea, I'm gonna close this as "by design". The Terminal is consistent with other applications on Windows, even Spotify, WinDbg and Firefox all have the "run as administrator" as a subsequent right-click on the taskbar.

**Closed** 2020-10-12 22:38 UTC
Labels: Needs-Tag-Fix, Needs-Triage, Resolution-By-Design
