### ISSUE TITLE
Grouping of panes?

### ISSUE THREAD

**Issue by tomuxi** [microsoft/terminal#6791] opened 2020-07-05 19:02 UTC
It would be great if it was possible to group selected panes into a single input target, similar to e.g. Terminator's grouping mechanism.

**Comment by KalleOlaviNiemitalo** [comment] 2020-07-05 21:11
This looks like a duplicate of <https://github.com/microsoft/terminal/issues/2634>.

**Comment by DHowett** [comment] 2020-07-06 02:28
Yep! Thanks @KalleOlaviNiemitalo 

/dup #2634

**Closed by DHowett** 2020-07-06 02:28 UTC
Labels: Needs-Tag-Fix, Needs-Triage
