### ISSUE TITLE
Installer issue using msix 

### ISSUE THREAD

**Issue by gbargsley** [microsoft/terminal#4503] opened 2020-02-07 18:59 UTC
# Environment

```none
Windows build number: Microsoft Windows NT 10.0.18363.0
Windows Terminal version (if applicable):

Any other software?
```

# Steps to reproduce

Running latest msix installer and progress stops at 16% and no further info displayed. 

# Expected behavior

# Actual behavior

**Comment by DHowett-MSFT** [comment] 2020-02-07 21:02
This is probably actually a /dupe of #3097

**Comment by DHowett-MSFT** [comment] 2020-02-07 21:32
Since it looks like (from your comment on 3097) this _isn't_ a correct resolution, I'm going to reopen this bug for now.

Is there anything else interesting about your environment? Are you isolated from the Windows Store? Can you run the following (from powershell?)

```
PS> Get-AppxPackage Microsoft.VCLibs.140.00.UWPDesktop
```

Are you using any third-party antivirus/quarantine software?

**Comment by gbargsley** [comment] 2020-02-07 21:43
Ok, I am on a corporate security protected laptop.  I run the msix with my administrator account and also the install to UWDesktop. Our policy block MS App store, so that is why I am using the msix.

We use McAfee and CylanceProtect and possible some other security prevention software.

I ran the code you suggested and nothing happened.  I also ran a get-apppackagelog after trying with choco but get same reference to dll and framework.
[output.txt](https://github.com/microsoft/terminal/files/4173048/output.txt)

**Comment by DHowett-MSFT** [comment] 2020-02-07 21:48
Thanks for this!

based on these lines;

```
2/7/2020 1:24:04 PM       628          Windows cannot install package Microsoft.WindowsTerminal_0.8.10261.0_x64__8wekyb3d8bbwe because this package depends on a framework
                                       that could not be found. Provide the framework "Microsoft.VCLibs.140.00.UWPDesktop" published by "CN=Microsoft Corporation,
                                       O=Microsoft Corporation, L=Redmond, S=Washington, C=US", with neutral or x64 processor architecture and minimum version
                                       14.0.27323.0, along with this package to install. The frameworks with name "Microsoft.VCLibs.140.00.UWPDesktop" currently installed
                                       are: {Microsoft.VCLibs.140.00.UWPDesktop_14.0.26905.0_x64__8wekyb3d8bbwe}
```

and

```
PS C:\Users\admin_gb> Get-AppxPackage Microsoft.VCLibs.140.00.UWPDesktop
PS C:\Users\admin_gb> Get-AppxPackage Microsoft.VCLibs.140.00.UWPDesktop
```

that UWPDesktop package never actually got installed. There's this redistributable `.exe`, but after it's installed it puts a few appx files on disk that _unfortunately_ need to be manually installed. It's not the best situation, which is why we're tracking #3097 and a discussion with the team that _owns_ that redistributable.

**Comment by DHowett-MSFT** [comment] 2020-02-07 21:50
I just tried an install from `"C:\program files (x86)\microsoft sdks\Windows Kits\10\ExtensionSDKs\Microsoft.VCLibs.Desktop\14.0\Appx\Retail\x64\Microsoft.VCLibs.x64.14.00.Desktop.appx"` -- it looks like that did give me the right/expected version...

**Comment by gbargsley** [comment] 2020-02-07 22:11
I see this when running the appx you point to.  But I cannot enable the sideload because I cannot figure out how to open settings as an admin account to make the change.

![image](https://user-images.githubusercontent.com/169602/74069618-6c713e80-49c4-11ea-843c-8306d5e0a4cb.png)

**Comment by DHowett-MSFT** [comment] 2020-02-10 20:28
I actually don't know how to install that package if you need to enable sideloading. I thought you needed to enable sideloading to install Terminal using MSIX as well ...

That said: for now it will suffice to unzip the x64 part of Windows Terminal (the msixbundle is just a zip file) and use WindowsTerminal.exe. We're investigating alternative deployment mechanisms that'll be more appropriate for enterprise users in #1386.

Since sideloading applications isn't allowed on your machine, and we're at our heart a sideloadable application, I.. don't see how I can really avoid resolving this bug as "duplicate" and "can't fix" ☹️

**Comment by gbargsley** [comment] 2020-02-10 20:57
That worked.  I was able to open WindowsTerminal.exe after extracting the CascadiaPackage_0.8.10261.0_x64.msix package.

Thanks

**Comment by DHowett-MSFT** [comment] 2020-02-13 08:22
Thanks for letting me know. Since it does look like a sideloading/distribution issue, I am going to instead call it a /dupe of #1386: we know we need to improve the story here, and this is just another piece of evidence.

**Closed by DHowett-MSFT** 2020-02-13 08:22 UTC
Labels: Needs-Attention, Needs-Repro, Needs-Triage

**Comment by WSLUser** [comment] 2020-02-14 14:52
> or now it will suffice to unzip the x64 part of Windows Terminal (the msixbundle is just a zip file) and use WindowsTerminal.exe. 

@DHowett I would like to point out (I can file a bug for this if needed) that following these steps prevents Windows Terminal from detecting the presence of PS Core. I can enter `pwsh` from Windows Powershell but I preferably would like to see it still auto-detect it. I know v9 added better Powershell support but not sure if that would include this particular "install" method.
