### ISSUE TITLE
IntuneWinAppUtil crashes

### ISSUE THREAD

**Issue by sikkepitje** [microsoft/terminal#4498] opened 2020-02-07 08:55 UTC
![2020-02-06 15_56_32-Paul @ Stichting Voortgezet Onderwijs Kennemerland ‎- OneNote](https://user-images.githubusercontent.com/14176764/74013354-90b12900-498c-11ea-9289-df1b09a3f75c.png)

# Environment

 Microsoft Windows NT 10.0.18363.0
Windows Terminal (Preview) Version: 0.8.10261.0
IntuneWinappUtil.exe 

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Windows Terminal version (if applicable):

Any other software?
```

# Steps to reproduce

Running IntuneWinAppUtil on a ridiculously large installation folder 4,4 GB

# Expected behavior

Expected behavior is finishing and completing the job. 

# Actual behavior

Actual behavior is borking with an error code. 

==== Run 1 ====
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6

PS C:\Users\p.wiegmans> cd 'C:\_MijnData_\Advanced Installer\'
PS C:\_MijnData_\Advanced Installer> intunewinapputil
Please specify the source folder: l2s-alles-in-een-setupfiles
Please specify the setup file: l2s-alles-in-een.msi
Please specify the output folder: output2
Do you want to specify catalog folder (Y/N)?n
Validating parameters
Validated parameters with 12 milliseconds
Compressing the souce folder 'l2s-alles-in-een-setupfiles' to 'C:\Users\p.wiegmans\AppData\Local\Temp\140c12bd-9e6d-474f-8c7b-c8dc3cf50ab2\IntuneWinPackage\Contents\l2s-alles-in-een.intunewin'
Calculated size for folder 'l2s-alles-in-een-setupfiles' is 4795335168 with 3 milliseconds
Compressed folder 'l2s-alles-in-een-setupfiles' successfully with 265366 milliseconds
Checking file type
Checked file type with 102 milliseconds
Encrypting file 'C:\Users\p.wiegmans\AppData\Local\Temp\140c12bd-9e6d-474f-8c7b-c8dc3cf50ab2\IntuneWinPackage\Contents\l2s-alles-in-een.intunewin'
'C:\Users\p.wiegmans\AppData\Local\Temp\140c12bd-9e6d-474f-8c7b-c8dc3cf50ab2\IntuneWinPackage\Contents\l2s-alles-in-een.intunewin' has been encrypted successfully with 32533 milliseconds
Computing SHA256 hash for C:\Users\p.wiegmans\AppData\Local\Temp\140c12bd-9e6d-474f-8c7b-c8dc3cf50ab2\IntuneWinPackage\Contents\a060d543-0efd-4f40-aaac-6bd67f1dab38
Computed SHA256 hash for 'C:\Users\p.wiegmans\AppData\Local\Temp\140c12bd-9e6d-474f-8c7b-c8dc3cf50ab2\IntuneWinPackage\Contents\a060d543-0efd-4f40-aaac-6bd67f1dab38' with 90012 milliseconds
Computing SHA256 hash for C:\Users\p.wiegmans\AppData\Local\Temp\140c12bd-9e6d-474f-8c7b-c8dc3cf50ab2\IntuneWinPackage\Contents\l2s-alles-in-een.intunewin

                        ========                  ]   62%
System.ArgumentOutOfRangeException: De waarde moet groter zijn dan of gelijk zijn aan nul en minder zijn dan de buffergrootte van de console in die dimensie.
Parameternaam: targetTop
Werkelijke waarde was 62.
   bij System.Console.MoveBufferArea(Int32 sourceLeft, Int32 sourceTop, Int32 sourceWidth, Int32 sourceHeight, Int32 targetLeft, Int32 targetTop, Char sourceChar, ConsoleColor sourceForeColor, ConsoleColor sourceBackColor)
   bij Microsoft.Management.Service.IntuneWinAppUtil.LogUtil.PrintProgress(AppContext context)
   bij Microsoft.Management.Service.IntuneWinAppUtil.LogUtil.WriteLine(AppContext context, String text)
   bij Microsoft.Management.Service.IntuneWinAppUtil.PackageUtil.CreatePackage(String folder, String setupFile, String outputFolder, String catalogFolder)
   bij Microsoft.Management.Service.IntuneWinAppUtil.Program.Main(String[] args)
PS C:\_MijnData_\Advanced Installer>

==== Run 2 ====
Microsoft Windows [Version 10.0.18363.592]
(c) 2019 Microsoft Corporation. Alle rechten voorbehouden.

C:\Users\p.wiegmans>cd "\_MijnData_\Advanced Installer"

C:\_MijnData_\Advanced Installer>intunewinapputil -s L2S-Alles-in-een-SetupFiles -c L2S-alles-in-een.msi -o output2
The setup file you specified cannot be accessed.

C:\_MijnData_\Advanced Installer>intunewinapputil -s L2S-Alles-in-een-SetupFiles -c L2S-Alles-in-een-SetupFiles\L2S-Alles-in-een.msi -o output2
The setup file you specified cannot be accessed.

C:\_MijnData_\Advanced Installer>intunewinapputil -s L2S-Alles-in-een-SetupFiles -c L2S-Alles-in-een-SetupFiles\L2S-Alles-in-een.msi -o output2
The setup file you specified cannot be accessed.

C:\_MijnData_\Advanced Installer>intunewinapputil
Please specify the source folder: l2s-alles-in-een-setupfiles
Please specify the setup file: l2s-alles-in-een.msi
Please specify the output folder: output3
Do you want to specify catalog folder (Y/N)?n
Validating parameters
Validated parameters with 13 milliseconds
Compressing the souce folder 'l2s-alles-in-een-setupfiles' to 'C:\Users\p.wiegmans\AppData\Local\Temp\912b8e00-dac8-420e-b005-0ff70c516a2b\IntuneWinPackage\Contents\l2s-alles-in-een.intunewin'
Calculated size for folder 'l2s-alles-in-een-setupfiles' is 4795335168 with 7 milliseconds
Compressed folder 'l2s-alles-in-een-setupfiles' successfully with 321059 milliseconds

                                                  ]   22%
System.ArgumentOutOfRangeException: De waarde moet groter zijn dan of gelijk zijn aan nul en minder zijn dan de buffergrootte van de console in die dimensie.
Parameternaam: targetTop
Werkelijke waarde was 56.
   bij System.Console.MoveBufferArea(Int32 sourceLeft, Int32 sourceTop, Int32 sourceWidth, Int32 sourceHeight, Int32 targetLeft, Int32 targetTop, Char sourceChar, ConsoleColor sourceForeColor, ConsoleColor sourceBackColor)
   bij Microsoft.Management.Service.IntuneWinAppUtil.LogUtil.PrintProgress(AppContext context)
   bij Microsoft.Management.Service.IntuneWinAppUtil.LogUtil.WriteLine(AppContext context, String text)
   bij Microsoft.Management.Service.IntuneWinAppUtil.PackageUtil.CreatePackage(String folder, String setupFile, String outputFolder, String catalogFolder)
   bij Microsoft.Management.Service.IntuneWinAppUtil.Program.Main(String[] args)

C:\_MijnData_\Advanced Installer>

**Comment by sikkepitje** [comment] 2020-02-07 08:57
aaaand this runs fine in an ordinary Windows PowerShell or CMD window.

**Comment by sikkepitje** [comment] 2020-02-07 09:03
![2020-02-07 10_02_05-Window](https://user-images.githubusercontent.com/14176764/74015503-05866200-4991-11ea-86e7-5ae337031cd0.png)

**Comment by sikkepitje** [comment] 2020-02-07 09:05
For all those of you who are non-Dutch: The translation is 
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the buffer size of the console in that dimension.
Parameter name: targetTop
Actual value was 62

**Comment by DHowett-MSFT** [comment] 2020-02-07 17:11
This looks like a /dupe of #4361, which seems to happen when an application tries to write outside the boundaries of a console. That's not actually legal.

**Closed by DHowett-MSFT** 2020-02-07 17:11 UTC
Labels: Needs-Tag-Fix, Needs-Triage
