### ISSUE TITLE
Terminal runs at 60Hz

### ISSUE THREAD

**Issue by ismaeelakram** [microsoft/terminal#5662] opened 2020-04-30 03:19 UTC
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18363.778]
Windows Terminal version (if applicable): 0.11.121.0

Any other software?
```

# Steps to reproduce

Run Terminal on 144Hz Monitor.

# Expected behavior

Terminal should run smoothly and cursor should move at 144hz.

# Actual behavior

Terminal runs at 60Hz and cursor looks choppy compared to normal.

**Comment by mendhak** [comment] 2020-04-30 07:29
Possible duplicate of:  https://github.com/microsoft/terminal/issues/649

**Comment by zadjii-msft** [comment] 2020-04-30 11:16
Sure sounds like it to me. Thanks @mendhak!

/dupe #649

**Closed by zadjii-msft** 2020-04-30 11:16 UTC
Labels: Needs-Tag-Fix, Needs-Triage
