### ISSUE TITLE
Touchpad scrolling not possible

### ISSUE THREAD

**Issue by Paul-Weisser** [microsoft/terminal#979] opened 2019-05-24 14:45 UTC
# Environment

Windows build number: Microsoft Windows [Version 10.0.18898.1000]
Windows Terminal version (if applicable): pulled and built today (WindowsTerminalDev_0.0.1.0_x64__8wekyb3d8bbwe)

# Steps to reproduce

Not entirely sure if this is intended behaviour or an issue to other users but I am not able to scroll through the new terminal with my touchpad on my Notebook (Alienware).

It works with my mouse but not with the touchpad. I can scroll through the native console/ poweshell though. Can somebody reproduce this?

# Expected behavior

That I can scroll through the curren window-history using two-finger-touch on the touchpad.

# Actual behavior

It wont scroll.

**Comment by zadjii-msft** [comment] 2019-05-24 14:50
Can you try setting a breakpoint in `TermControl::_MouseScrollHandler` to see if that's getting hit?

Two-finger scrolling works just fine with my surfacebook, so I'm thinking that it's something specific to your device.

**Comment by Paul-Weisser** [comment] 2019-05-24 15:32
Okay I'm starting to feel a little stupid. I cleaned the solution and build CascadiaPackage on Debug x64 with the breakpoints in `TermControl::_MouseScrollHandler` but it wont stop there.

I need a little help how to get VS (2019) stopping at this class...

**Comment by DHowett-MSFT** [comment] 2019-05-24 16:00
You might be in need of [this debugging doc](https://github.com/microsoft/terminal/blob/master/doc/Debugging.md).

**Comment by zadjii-msft** [comment] 2019-05-24 16:03
Maybe try something that you can be sure is hitting, like `TermControl::_KeyDownHandler`

**Comment by Paul-Weisser** [comment] 2019-05-24 23:22
Thanks @DHowett-MSFT, missed that one!

But now with a working debug-mode there are several memory-violation-exceptions popping by twinapi.appcore.dll which my VS for some reason wont ignore...
So I am not able to reach the breakpoints...

![grafik](https://user-images.githubusercontent.com/34196171/58360801-f3a87180-7e8a-11e9-8452-9c6c4a6655ea.png)

Since it seems like nobody else is having these issues I will let it be and accept the fact, that something is wrong with my maschine. But I think its still interesting, that the new terminal is the only app where I am unable to scroll with two fingers.

**Comment by rehnarama** [comment] 2019-05-26 10:58
I have this issue as well though!

My touchpad uses the Synaptics ClickPad drivers, not microsoft precision drivers, perhaps there is an issue there?

**Comment by rehnarama** [comment] 2019-05-26 11:01
After some debugging:

> Can you try setting a breakpoint in `TermControl::_MouseScrollHandler` to see if that's getting hit?
> 
> Two-finger scrolling works just fine with my surfacebook, so I'm thinking that it's something specific to your device.

The PointerWheelChanged handler bound to TermControl::_MouseScrollHandler is never called.


> Maybe try something that you can be sure is hitting, like `TermControl::_KeyDownHandler`
All other pointer handlers (and key handlers) work as expected.

**Comment by Paul-Weisser** [comment] 2019-05-26 13:07
@rehnarama
I tried both, Microsoft and synaptics drivers
Maybe it's an locale issue (I'm on a German locale)
Since there have been other issues regarding locale and getting user-input right?

**Comment by rehnarama** [comment] 2019-05-27 14:50
> @rehnarama
> I tried both, Microsoft and synaptics drivers
> Maybe it's an locale issue (I'm on a German locale)
> Since there have been other issues regarding locale and getting user-input right?

Could be!

I've just now noticed that, when disabling "Scroll Inactive Windows" in settings, the scrolling with an external mouse becomes unreliable as well! With unreliable I mean it works sometimes (when hovering over rendered text?), and then suddenly stops working (usually when trying to scroll empty area, but not always).

Since scrolling inactive windows doesn't work with synaptics drivers, it might be a focusing issue of some sorts? Or perhaps turning off "Scroll Inactive Windows" setting would be a seperate issue?

**Comment by zadjii-msft** [comment] 2019-05-28 13:47
I _really_ doubt that locale would affect mouse input, but I guess I'm not an expert in the input stack. 

The "scroll inactive windows think" might be a good lead on tracking this bug down though. Considering I don't believe anyone on the dev team has a device this is reproing on, the more help we can get the better :)

**Comment by Paul-Weisser** [comment] 2019-05-28 15:41
I can't dig into this for the next four weeks...
If nobody else fixes this until then I will have a closer look (after I fixed the weird memory access violation...)

**Comment by DHowett-MSFT** [comment] 2019-06-01 00:29
Hey, I think the memory access violation is a bad interaction with Visual Studio.

Can you go into Options, search for `xaml`, and turn off live Xaml UI/visual tree debugging? It'll unload the "UWP Tap," which seems to cause an access violation for _some people_ during startup.

**Comment by Paul-Weisser** [comment] 2019-06-01 07:31
@DHowett-MSFT Thanks! That totally worked!👍

Now I could reproduce the behaviour @rehnarama was experiencing.

**Comment by dkter** [comment] 2019-06-05 23:45
My touchpad (Alps drivers) doesn't work either.

Then again, neither does my mouse scroll wheel. Maybe something's wrong with my build.

**Comment by Navino16** [comment] 2019-06-26 08:12
Hello,

I can't scroll with my touchpad (Synaptics) also but I can scroll with other mouse.
If you need more info, let me know

**Comment by Paul-Weisser** [comment] 2019-06-27 23:22
Tracking this issue down I found [this issue](https://github.com/microsoft/microsoft-ui-xaml/issues/760)  in the microsoft/microsoft-ui-xaml repo.
It seems like we got a similar problem here, but I can't say for sure since I don't know enough about our architecture. @zadjii-msft could you please confirm that the structure of the new terminal would apply to this? Thanks!

**Comment by zadjii-msft** [comment] 2019-07-01 13:44
That looks like it's the root cause of the issue at hand here. I'm going to close this issue as a dupe of that XAML issue. 

When microsoft/microsoft-ui-xaml#760 is fixed, this should be fixed for us.

**Comment by Austin-Lamb** [comment] 2019-07-02 21:03
@zadjii-msft - unfortunately the fix for Microsoft-ui-xaml#760 won't fix this for Terminal.  That fix will only help ScrollViewer controls, but Terminal will need to implement its own scrolling as you're drawing your own stuff and doing your own scrolling in the Terminal app code.  I recommend reactivating this issue.

**Comment by DHowett-MSFT** [comment] 2019-07-02 21:10
I thought we might actually be using ScrollViewer, but it turns out we don't.

**Comment by Paul-Weisser** [comment] 2019-07-04 21:11
So, I'm not sure how to fix this.

If I decrypted this right we are just listening for the `PointerWheelChanged`-event in the `_root` ´Controls::Grid´, which is an implementation of `Windows::UI::Xaml::Controls::IGrid`, but this never gets called from my touchpad.

So if the Microsoft-ui-xaml#760-fix really isn't fixing this we would need to write a new mousewheel-input-handler...

**Comment by Escapingbug** [comment] 2019-07-30 15:24
Same issue here. And my mouse wheel not working as well as I tested (develop build on master branch, not sure if other branches have fixed this).
I did set up a breakpoint at `_MouseWheelHandler` and found out when `ctrl` is hold, it is actually called. But without `ctrl` holding, it is not even called.

It really seems to be an ui or xaml related issue..

**Comment by Uxorious** [comment] 2019-08-31 19:04
Also not working on HP Spectre x360.

**Comment by nishp77** [comment] 2019-09-19 03:43
I'm sure the scrolling either on the touchpad or using a mouse doesn't get detected in most of the laptops and compusters

**Comment by joshschmelzle** [comment] 2019-09-21 17:18
I also have this issue with both theTrackPad and TrackPoint on a Lenovo T450 touchpad (Synaptics drivers).

**Comment by pamtbaau** [comment] 2019-09-21 18:28
Scrolling with touchpad **does** work when in selection mode (left touchpad button pressed).

**Comment by dkter** [comment] 2019-09-21 23:58
> 
> 
> Scrolling with touchpad **does** work when in selection mode (left touchpad button pressed).

It doesn't for me.

**Comment by foehnair** [comment] 2019-09-25 03:11
Synaptics trackpad scrolling does not work. Mouse middle-button scrolling works.

**Comment by DerAlbertCom** [comment] 2019-10-09 15:05
Just for Information, I have a Precision Touch Pad (Dell XPS 15, 9560), I think with Microsoft Precision Driver. Two finger Scrolling works fine. Also scrolling with a Surface Sculpt Mouse works fine (no Driver o additional Software installed). I don't press additional Keys.  V0.5.2762.0

**Comment by NoSoup** [comment] 2019-10-17 19:54
I'm also having this issue where my touchpad or external mouse will not scroll up.  It works for a while if I restart my computer, but then suddenly it stops working. I noticed that all UWP apps have the same problem (my Start Menu, Weather app etc). Once scrolling stops working on one of them, it stops on all UWP-based applications.  This has been an issue on every computer I've used, so it doesn't seem to be based on specific hardware.  My current set up is a Dell XPS 17 and a Logitech MX Master 2s, scrolling stops working on both the touchpad and mouse at the same time when it happens.  I haven't been able to figure out what triggers it, because some days i'll make it half way through the day before it stops working and the only fix is to reboot.

**Comment by mysticatea** [comment] 2019-10-29 10:32
I have encountered likely this problem. I'm using [ThinkPad Compact USB Keyboard with TrackPoint](https://support.lenovo.com/ro/ro/solutions/pd026745) and the TrackPoint doesn't scroll Windows Terminal (Preview). For a reference, TrackPoint works fine on cmd.exe, Windows PowerShell, and Visual Studio Code's integrated terminal.

- Windows 10 1903 (18362.418)
- Windows Terminal (Preview) 0.6.2951.0

**Comment by fourpastmidnight** [comment] 2019-11-08 05:00
I'm using a Clevo P370EM with a Synaptics touchpad. I also cannot scroll using two-finger scrolling or edge scrolling.

**Comment by c0zy** [comment] 2019-11-14 11:46
When holding left shift key, scrolling works with external mouse. CTRL key zooms in or out with external mouse wheel.
I work from a desktop computer and not laptop with english-us locale

**Comment by dkter** [comment] 2019-11-17 20:21
>When holding left shift key, scrolling works with external mouse. 

I can confirm this. `TermControl::_MouseWheelHandler` is only called if Ctrl or Shift (or both) are pressed (other modifiers don't affect it). This is the case for both my touchpad and my USB mouse scroll wheel.

**Comment by dkter** [comment] 2019-11-17 22:01
Same behaviour on the new TabView. Scrolling normally doesn't do anything, while Shift-scrolling works (Ctrl-scrolling also doesn't work, but I haven't tested if the handler is being called yet). This leads me to believe it could be a WinUI bug...

**Comment by Uxorious** [comment] 2019-11-28 17:21
No touchpad scrolling is working for me.
And on the latest version, the scrollbar on the right doesn't work either :-(

**Comment by fourpastmidnight** [comment] 2019-11-28 18:32
I’ve had instances where the scroll bar stopped working, too, though the scroll arrows still worked. I believe it you change tabs or open a new console tab, the scroll bar starts working again.

Sent from my Windows 10 phone

**Comment by dkter** [comment] 2019-11-28 18:34
@fourpastmidnight I've had this issue as well, but I can't tell if it's related.

**Comment by waelkdouh** [comment] 2019-12-12 21:32
> I have a surfacebook and scrolling is not working using external surface mouse or the trackpad.

Turns out the culprit was an app I had installed on my machine called x-mouse

**Comment by dkter** [comment] 2019-12-12 21:36
> Turns out the culprit was an app I had installed on my machine called x-mouse

This was my issue as well

**Comment by shivasurya** [comment] 2019-12-13 18:18
any updates please

**Comment by zadjii-msft** [comment] 2019-12-13 18:34
@shivasurya When we have updates to share, we'll make sure to post in the thread. I don't believe there's anyone on the team with hardware that repros this currently, so if someone in the community could help contribute a fix for this, we'd certainly appreciate it. As it currently stands, we'll make sure to get this fixed before the 1.0 release of the terminal, but we don't have a more specific timeframe set.

**Comment by jsnfwlr** [comment] 2019-12-16 22:08
> Turns out the culprit was an app I had installed on my machine called x-mouse

To keep X-Mouse and still allow scroll in Microsoft Terminal, just disable "Make scroll wheel scroll window under cursor" in the X-Mouse settings.

**Comment by wisammechano** [comment] 2019-12-28 17:35
I am also having this issue my laptop is HP Omen with windows 10 pro. The touchpad 2-finger scrolling is not working. Synaptics touchpad.

The only way to scroll is using ctrl+up,down

**Comment by Ade-Joshe** [comment] 2020-02-19 19:52
this issue has been pending for quite some time now, I would really appreciate a fix.
In the main time, I just go with ctrl + shift + up/down key.


Better than nothing

**Comment by DHowett-MSFT** [comment] 2020-02-24 08:08
#4700 came with a report that scrolling doesn't work in Store, either. Is anyone else here seeing the same behavior?

**Comment by rehnarama** [comment] 2020-02-24 16:47
> 
> 
> #4700 came with a report that scrolling doesn't work in Store, either. Is anyone else here seeing the same behavior?

Nope, not here at least. Scrolling works fine in Store with my touchpad, but does not work in Terminal.

**Comment by nishp77** [comment] 2020-02-25 05:40
everyone who has issues on trying to scroll i would say check out again. My problem is fixed

**Comment by NoSoup** [comment] 2020-02-26 14:14
> 
> 
> #4700 came with a report that scrolling doesn't work in Store, either. Is anyone else here seeing the same behavior?

Scrolling works for me in both the store and the terminal when I reboot, but after a random amount of time, they both stop working (including the Start menu, and any other application built off the same platform). I'm starting to think it might be my antivirus because it will affect all computers where I work, and the only thing in common is the antivirus between them. We don't use anything like x-mouse, and all computers have the "Scroll inactive windows when I hover over them" setting enabled.  Once it stops working, nothing seems to fix it other than a reboot. I've tried removing the mouse, adding it back, changing the mouse, closing and reopening the terminal, killing and relaunching explorer.exe, disabling the scroll inactive windows setting then reenabling it. Nothing other than a reboot seems to fix it.

**Comment by vangorden** [comment] 2020-02-26 20:34
> 
> 
> > #4700 came with a report that scrolling doesn't work in Store, either. Is anyone else here seeing the same behavior?
> 
> Scrolling works for me in both the store and the terminal when I reboot, but after a random amount of time, they both stop working (including the Start menu, and any other application built off the same platform). I'm starting to think it might be my antivirus because it will affect all computers where I work, and the only thing in common is the antivirus between them. We don't use anything like x-mouse, and all computers have the "Scroll inactive windows when I hover over them" setting enabled. Once it stops working, nothing seems to fix it other than a reboot. I've tried removing the mouse, adding it back, changing the mouse, closing and reopening the terminal, killing and relaunching explorer.exe, disabling the scroll inactive windows setting then reenabling it. Nothing other than a reboot seems to fix it.

My issue sounds very different from yours. Scrolling works perfectly everywhere except in Windows Terminal where two finger scrolling has never worked (mouse wheel works fine). I suspect it is related to the way the Synaptic touchpad reports scroll events. I'm using an HP Spectre x360.

**Comment by NoSoup** [comment] 2020-03-02 18:26
> 
> 
> > > #4700 came with a report that scrolling doesn't work in Store, either. Is anyone else here seeing the same behavior?
> > 
> > 
> > Scrolling works for me in both the store and the terminal when I reboot, but after a random amount of time, they both stop working (including the Start menu, and any other application built off the same platform). I'm starting to think it might be my antivirus because it will affect all computers where I work, and the only thing in common is the antivirus between them. We don't use anything like x-mouse, and all computers have the "Scroll inactive windows when I hover over them" setting enabled. Once it stops working, nothing seems to fix it other than a reboot. I've tried removing the mouse, adding it back, changing the mouse, closing and reopening the terminal, killing and relaunching explorer.exe, disabling the scroll inactive windows setting then reenabling it. Nothing other than a reboot seems to fix it.
> 
> My issue sounds very different from yours. Scrolling works perfectly everywhere except in Windows Terminal where two finger scrolling has never worked (mouse wheel works fine). I suspect it is related to the way the Synaptic touchpad reports scroll events. I'm using an HP Spectre x360.

So I found the issue with my scrolling.  We use a Java based application that's causing the issue.  If I close that application I can scroll in the terminal, store, and Start Menu, but it happens to be an application that I use for most of the day, so I never closed it before to test.

**Comment by msbrunoalves** [comment] 2020-03-11 17:49
I think this is the same issue I've had with different programs over the years. Synaptics drivers implement scrolling in a different way than they should, I've had issues with VM's and some random specific apps that wouldn't scroll with the touchpad.
It really shouldn't be an issue for the terminal though, Powershell and CMD standalone scroll with no issues, so I'm guessing the Terminal app handles scrolling in a different way.

**Comment by tukusejssirs** [comment] 2020-03-17 09:19
This affects me on Win10 Build 18363.720 and Windows Terminal v0.9.433.0.

I cannot scroll using mouse (but I can scroll other windows), I wish I could scroll at least with <kbd>Shift</kbd>+<kbd>PgUp</kbd> and <kbd>Shift</kbd>+<kbd>PgDn</kbd> (I still need to check if there is a keybinding `command` to set the shortcuts for it).

Currently, the only way to scroll the output is using the the mouse clicking of the scrollbar.

**Comment by wolf99** [comment] 2020-03-19 07:56
Doesn't work for me either.

Terminal 0.10.761.0
Windows: 1909 (18363.720)


This hasn't worked for me since I first installed WT last year. Mouse wheel scrolling hasn't worked either (haven't tried that with the 0.10 release yet though), is there a separate issue for mouse wheel scrolling or should that be covered here also?

**Comment by zadjii-msft** [comment] 2020-03-19 12:48
@wolf99 I'm _sure_ that there's another issue that's tracking the mouse scrolling not working, but this one isn't it. I fortunately have a personal HP laptop that repros this bug with it's touchpad, so I'm going to be using that to debug and investigate. However, I'd doubt that this investigation would also apply to all mouse devices. I don't want you thinking that resolving _this_ issue will _also_ fix your mouse issue.

**Comment by wolf99** [comment] 2020-03-19 12:54
@zadjii-msft Just tried 0.10 release with mouse, it's working now! 😄 
Glad you're able to repro the track pad issue as it is affecting a lot of people by the look of this issue.

**Comment by zadjii-msft** [comment] 2020-03-24 16:06
Oh no this is horrifying.

This might not apply super broadly, but this is what I've found with my investigation this morning. I've got a HP Spectre 2017 x360 that I use at home, with a touchpad using the synaptics drivers. 

From what I can tell, the Synaptics touchpads don't support "Scroll inactive windows" _at all_. `notepad.exe`, the Settings app, nothing. Even with "Scroll inactive windows when I hover over them" enabled.
![image](https://user-images.githubusercontent.com/18356694/77447498-be77f300-6dbd-11ea-941c-06697b59f4f5.png). I'm positive that the trackpad is the problem here, because using an external mouse works fine for both scrolling inactive windows and the Terminal on this laptop.

Turns out, this is a [very broad problem](https://www.google.com/search?client=firefox-b-1-d&q=synaptics+inactive+window). Even info from [3 years ago](https://superuser.com/questions/1127755/scroll-inactive-windows-when-i-hover-over-them-not-working-with-every-applicat) points at solutions that are decades old (and not verified).

What does this have to do with the Terminal?

As it turns out, XAML Islands, which we're using to host our XAML content (read: the entire UI), uses an _inactive_ HWND to host the XAML content. So we're never even getting the mouse events in `TermControl::_MouseScrollHandler`. This issue is more specifically being tracked by https://github.com/microsoft/terminal/issues/2606 and https://github.com/microsoft/microsoft-ui-xaml/issues/2101. I'm betting that this is also going to be the root cause of this issue here. 

I'm going to investigate if our root HWND gets the trackpad scrolling events that the XAML Island is ignoring. Maybe I can manually forward them to the XAML island somehow? I'm not overly optimistic at this point. 

/cc @Austin-Lamb @ocalvo

**Comment by pamtbaau** [comment] 2020-03-24 17:14
@zadjii-msft, I'm using a Lenovo B590 using Synaptics Touchpad v7.5 drivers.

notepad.exe scrolls fine. In fact, every app scrolls fine, except Microsoft Terminal...

Any other app you would like me to test?

**Comment by Uxorious** [comment] 2020-03-24 17:22
FYI: A few releases back, it started working for me on an HP Spectre x360 with Synaptics drivers.
I can also scroll background/inactive windows.

**Comment by dkter** [comment] 2020-03-24 17:33
@pamtbaau 

> notepad.exe scrolls fine.

does it scroll when you have another window in the foreground? (i.e. open two windows side by side, then try to scroll the inactive one.)

**Comment by pamtbaau** [comment] 2020-03-24 17:52
@dkter, @zadjii-msft  🤦‍♂ You're right, it doesn't work...

**Comment by Uxorious** [comment] 2020-03-24 17:55
Huh that is really interesting.
For me it works sometimes - but it depends on what the FOREGROUND app is.

For example, I tried it earlier with Outlook in the foreground and Notepad in the background.
That worked.

But when I received this last mail, I tried it again. This time with Chrome/Gmail in the foreground.
This does NOT work.

**Comment by msbrunoalves** [comment] 2020-03-24 18:14
> 
> 
> Oh no this is horrifying.
> 
> This might not apply super broadly, but this is what I've found with my investigation this morning. I've got a HP Spectre 2017 x360 that I use at home, with a touchpad using the synaptics drivers.
> 
> From what I can tell, the Synaptics touchpads don't support "Scroll inactive windows" _at all_. `notepad.exe`, the Settings app, nothing. Even with "Scroll inactive windows when I hover over them" enabled.
> ![image](https://user-images.githubusercontent.com/18356694/77447498-be77f300-6dbd-11ea-941c-06697b59f4f5.png)
> I'm positive that the trackpad is the problem here, because using an external mouse works fine for both scrolling inactive windows and the Terminal on this laptop.
> 
> Turns out, this is a [very broad problem](https://www.google.com/search?client=firefox-b-1-d&q=synaptics+inactive+window). Even info from [3 years ago](https://superuser.com/questions/1127755/scroll-inactive-windows-when-i-hover-over-them-not-working-with-every-applicat) points at solutions that are decades old (and not verified).
> 
> What does this have to do with the Terminal?
> 
> As it turns out, XAML Islands, which we're using to host our XAML content (read: the entire UI), uses an _inactive_ HWND to host the XAML content. So we're never even getting the mouse events in `TermControl::_MouseScrollHandler`. This issue is more specifically being tracked by #2606 and [microsoft/microsoft-ui-xaml#2101](https://github.com/microsoft/microsoft-ui-xaml/issues/2101). I'm betting that this is also going to be the root cause of this issue here.
> 
> I'm going to investigate if our root HWND gets the trackpad scrolling events that the XAML Island is ignoring. Maybe I can manually forward them to the XAML island somehow? I'm not overly optimistic at this point.
> 
> /cc @Austin-Lamb @ocalvo

That probably explains why scroll doesn't work with VMWare or Virtualbox either

**Comment by mquevill** [comment] 2020-03-25 13:51
> Huh that is really interesting.
> For me it works sometimes - but it depends on what the FOREGROUND app is.
> 
> For example, I tried it earlier with Outlook in the foreground and Notepad in the background.
> That worked.
> 
> But when I received this last mail, I tried it again. This time with Chrome/Gmail in the foreground.
> This does NOT work.

I have the same behavior on my system. Scrolls fine with the touchpad while inactive when Settings is in the foreground; does not scroll when Chrome is in the foreground.

When the window is active, my touchpad will not scroll at all. Mouse wheel works fine (in all cases). But I have never run into issues with any other applications with my touchpad (granted, it's an older model).

Windows Terminal 0.10.781.0
Windows 10 Pro 1909 (18363.720)
Synaptics Driver 19.2.17.55

**Comment by zadjii-msft** [comment] 2020-03-25 13:55
Thanks for the clarification everyone! It seems like on my machine, I can also repro this behavior where different foreground apps change whether an inactive window can be scrolled or not. This is an incredibly peculiar bug, which might be partially related to this. I'm still trying to work on a workaround, but we'll see if that's possible or not :/

**Comment by Paul-Weisser** [comment] 2020-03-25 23:53
@zadjii-msft Just checked out the branch you referenced. Looks promising! Fixes this issue for me 👍

BTW: Props to your commit messages 🥇

**Closed** 2020-04-01 16:58 UTC
Labels: Area-TerminalControl, Help-Wanted, In-PR, Issue-Bug, Priority-1, Product-Terminal, v1-Scrubbed

**Comment by wolf99** [comment] 2020-04-01 20:58
Props on the effort here @zadjii-msft !
I look forward to this landing on my machine 👨‍💻

**Comment by mysticatea** [comment] 2020-04-23 03:13
I have confirmed that my [ThinkPad Compact USB Keyboard with TrackPoint](https://support.lenovo.com/ro/ro/solutions/pd026745) can scroll Windows Terminal. Thank you very much!

**Comment by waelkdouh** [comment] 2020-04-23 03:16
It now works on my surface book. Thanks.

**Comment by wolf99** [comment] 2020-05-02 19:26
Can confirm this is working on my HP Envy. Thanks!
