### ISSUE TITLE
Feature Request: custom tab name

### ISSUE THREAD

**Issue by talbaumel** [microsoft/terminal#1638] opened 2019-06-26 10:39 UTC
Hi, can you add an option to replace the tab name from the full path to a custom string the user can edit?

Thanks, great job

**Comment by DerekZA** [comment] 2019-06-26 11:37
+1 great idea

**Comment by JushBJJ** [comment] 2019-06-26 12:35
Duplicate of #608

**Comment by HiWilliam** [comment] 2019-06-26 14:04
great idea!,the tab name is too long

**Comment by DHowett-MSFT** [comment] 2019-06-26 14:58
Yeah that’s a dupe. Thanks @JushBJJ

**Closed by DHowett-MSFT** 2019-06-26 14:58 UTC
Labels: Issue-Feature, Needs-Tag-Fix, Needs-Triage
