### ISSUE TITLE
Unicode characters not displaying properly in local WSL, not displaying at all over SSH

### ISSUE THREAD

**Issue by pyr0ball** [microsoft/terminal#6318] opened 2020-06-02 21:16 UTC
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18363.836]`
```
Any other software?
```none
Windows Subsystem for Linux
Ubuntu 20.04
```

# Steps to reproduce

## Local issue
Try echoing a special unicode character, using escape format:
`echo -e '\u23ba'`

output shows an unknown character box
![image](https://user-images.githubusercontent.com/8482805/83570119-5a1e9180-a4da-11ea-8b4b-3fbf3542fc94.png)

## Remote Issue

SSH to a remote system, and run the same command, and the output is blank:
![image](https://user-images.githubusercontent.com/8482805/83570262-9651f200-a4da-11ea-8622-298636b8b24c.png)

# Expected behavior

Correct behavior can be observed when I SSH to the same server using PuTTY:
![image](https://user-images.githubusercontent.com/8482805/83570378-c26d7300-a4da-11ea-98aa-e8b24387e373.png)

## Explanation / Steps already taken to resolve

I use a number of special characters in my bash scripts and they are all currently not being displayed properly. I'm aware of #190 being in the backlog, but I believe the issue I'm experiencing is slightly different.

Firstly none of the available fonts in the terminal properties seem to be able to display unicode characters, even ones I've confirmed do have the special characters available by looking through Windows' Font settings.

Secondly, I haven't come across any issues or other posts on google where SSH sessions simply don't display unicode at all.

Any help would be appreciated!

**Comment by WSLUser** [comment] 2020-06-02 22:14
So you should to the Release page of this repo or to the Store and install Windows Terminal, which does support emoji and other unicode characters. That will be the first thing asked for you to try before troubleshooting.

**Comment by pyr0ball** [comment] 2020-06-03 00:14
Good to know, thank you

**Comment by DHowett** [comment] 2020-06-03 00:26
So, yeah, there's a couple things at play here. The vintage Windows Console host doesn't support font fallback, or a great number of things that are necessary to display glyphs for these things. It _will_, in the fullness of time -- the renderer used in Terminal was originally built in conhost, and it still mostly works there. We're getting there, inch by inch.

Terminal is where much of the investment is, right now. Any improvements there will flow back to Windows, given time.

This is a /dupe of #190, but not for the reasons you might have expected. No font fallback = no glyph. If you're using Win32-OpenSSH, they have some of their own Unicode handling issues. We're working with them to make sure that's not the case. :smile:

**Closed by DHowett** 2020-06-03 00:26 UTC
Labels: Needs-Tag-Fix, Needs-Triage

**Comment by pyr0ball** [comment] 2020-06-03 02:38
@DHowett okidokie! Thanks I learned something today 😄

**Comment by pyr0ball** [comment] 2020-06-03 02:47
@DHowett Sorry for the pings, but I did go and try this again with Terminal

good news is local echo is doing what it's supposed to:
![image](https://user-images.githubusercontent.com/8482805/83589991-a9c88180-a509-11ea-8745-aa449aa9096e.png)

bad news is, remote echo still is not:
![image](https://user-images.githubusercontent.com/8482805/83590028-bb118e00-a509-11ea-8bea-13ecd1b4dee0.png)

I'm using Ubuntu 20.04 through WSL, so I'm not sure if the OpenSSH issues mentioned earlier would apply here

**Comment by islwx** [comment] 2021-10-05 13:51
> @DHowett Sorry for the pings, but I did go and try this again with Terminal
> 
> good news is local echo is doing what it's supposed to: ![image](https://user-images.githubusercontent.com/8482805/83589991-a9c88180-a509-11ea-8745-aa449aa9096e.png)
> 
> bad news is, remote echo still is not: ![image](https://user-images.githubusercontent.com/8482805/83590028-bb118e00-a509-11ea-8bea-13ecd1b4dee0.png)
> 
> I'm using Ubuntu 20.04 through WSL, so I'm not sure if the OpenSSH issues mentioned earlier would apply here

I encountered the same problem. I found a solution in the community of Ubuntu,  you can refer to it:

1. https://askubuntu.com/questions/144235/locale-variables-have-no-effect-in-remote-shell-perl-warning-setting-locale-f/144448#144448
2. https://askubuntu.com/questions/421878/terminal-ssh-doesnt-display-utf-correctly
Commenting out `SendEnv LANG LC_*` in the WSL `/etc/ssh/ssh_config` file fixed everything.
