### ISSUE TITLE
Missing font after system reboot

### ISSUE THREAD

**Issue by Domain** [microsoft/terminal#4543] opened 2020-02-12 04:02 UTC
# Environment

```none
Windows build number: Microsoft Windows [版本 10.0.18363.628]
Windows Terminal version (if applicable): 0.8.10261.0

Any other software? No
```

# Steps to reproduce

I use Cascadia Code PL font:
`"defaults": {
            "fontFace": "Cascadia Code PL",
            "suppressApplicationTitle": true
        },`

And it works well after saving the config file. But after system reboot, the font seems missing. I have to reinstall the font to make it work in terminal.

# Expected behavior

![image](https://user-images.githubusercontent.com/903197/74301889-7f528d00-4d8f-11ea-9c95-d324b78028c0.png)

# Actual behavior

The font seems missing in terminal:
![image](https://user-images.githubusercontent.com/903197/74301563-701f0f80-4d8e-11ea-92d4-4e4465371527.png)
But it works well in VS:
![image](https://user-images.githubusercontent.com/903197/74301600-875dfd00-4d8e-11ea-9d7d-15460602c877.png)
And can be found in the system fonts folder:
![image](https://user-images.githubusercontent.com/903197/74301776-1bc85f80-4d8f-11ea-9c9a-44fd55cd2133.png)

**Comment by DHowett-MSFT** [comment] 2020-02-12 21:08
Thanks for the info! This looks like a /dupe of #3257

**Closed by DHowett-MSFT** 2020-02-12 21:08 UTC
Labels: Needs-Tag-Fix, Needs-Triage
