### ISSUE TITLE
Any character requiring Alt Gt not being inserted correctly on German keyboard layout

### ISSUE THREAD

**Issue by mwidmann** [microsoft/Terminal#487] opened 2019-05-07 10:14 UTC
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)

Microsoft Windows [Version 10.0.18362.86]

* What's wrong / what should be happening instead:

When the tab is running a `wsl` (Debian or Ubuntu) task any character requiring Alt Gr on the German Keyboard layout (~, @, |, etc.) don't get printed at all, besides `\` which gets printed as `<ffffffff>`

When the tab is running `cmd.exe` or `powershell.exe` the regular value of the key is returned as if Alt Gr wasn't pressed at all.

**Comment by johanlindfors** [comment] 2019-05-07 15:27
Same with Swedish keyboard layout, but I can't get the `\` either.

**Comment by zadjii-msft** [comment] 2019-05-07 16:30
This looks like a dupe of #521 to me.

**Closed** 2019-05-07 16:31 UTC
Labels: Resolution-Duplicate

**Comment by Eliaxs1900** [comment] 2019-06-18 14:17
it's not only on German Layout, in Spanish layout i can' use.
I see something curious, if y press AltGr + plus one number, and them (without pres AltGR) another number. The last number appears X times

**Comment by neo-clon** [comment] 2019-06-25 16:48
Only works on US Keyboard
