### ISSUE TITLE
Unable to fully scroll down when shrunk

### ISSUE THREAD

**Issue by Reelix** [microsoft/terminal#3306] opened 2019-10-24 07:28 UTC
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18362.418]
Windows Terminal version (if applicable): Version: 0.6.2951.0
```

# Steps to reproduce

1.) Set the initialRows value to 30, and open a new wt instance
2.) Shrink the window to approximately half the size vertically (Drag the bottom up)
3.) Spam a few invalid commands (asd, \<Enter\>, asd, \<Enter\>, asd, \<Enter\>, asd, \<Enter\>, asd, \<Enter\>, asd, \<Enter\>) until the scrollbar appears (It will appear later than expected)
4.) Note that you unable to scroll to the current input location

# Expected behavior
You are able to scroll to the current input location

# Actual behavior
You are unable to scroll to the current input location without resizing. The scrollbar also only appears when the lines exceed the initialRows value and ignore the actual window height. 

Similar to https://github.com/microsoft/terminal/issues/1494, but that one deals more with the scroll bar not working at all more so than the scrollbar scrolling to the incorrect location / appearing later than expected.

**Comment by DHowett-MSFT** [comment] 2019-10-24 19:42
This looks like a /dupe of #1494.

**Closed by DHowett-MSFT** 2019-10-24 19:42 UTC
Labels: Needs-Tag-Fix, Needs-Triage
