### ISSUE TITLE
Output of command in command prompt wrong...

### ISSUE THREAD

**Issue by Luuk34** [microsoft/terminal#2684] opened 2019-09-06 08:00 UTC
Windows Terminal 0.4.2382.0
Windows 10

```

# Steps to reproduce

RUN 'Windows Terminal' with two command-prompts.
Run next command in both prompt (simultanuously)
for /l %f in (1,1,100000) do @echo abcdefghijklmnopqrstuvwxyz %f      

In de output of the first screen the 'wrong output' is found.
(not neccesarily at the point given in the example)

# Expected behavior

correct output,
100000 lines containing the alphabet, with a number at the end of the line.

# Actual behavior

In the first tab, something like this is seen:
abcdefghijklmnopqrstuvwxyz 98810
abcdefghijklmnopqrstuvwxyz 98811
abcdefghijklmnopqrstuvwxyz 98812
abcdefghijklmnopqrstuvwxyz 98813
abcdefghijklmnopqrstuvwxyz 98814
abcdefghijklmnopqrstuvwxyz 98815
]0;CMD - echo  abcdefghiz 98816
                         abcdefghijklmnopqrstuvwxyz 98817
abcdefghijklmnopqrstuvwxyz 98818
abcdefghijklmnopqrstuvwxyz 98819
abcdefghijklmnopqrstuvwxyz 98820
abcdefghijklmnopqrstuvwxyz 98821
abcdefghijklmnopqrstuvwxyz 98822
abcdefghijklmnopqrstuvwxyz 98823
abcdefghijklmnopqrstuvwxyz 98824
abcdefghijklmnopqrstuvwxyz 98825

**Comment by hoxha-saber** [comment] 2019-09-08 00:58
![Old But Gold 2019-09-07 20-45-08_Trim](https://user-images.githubusercontent.com/26442377/64481789-cec5d900-d1b1-11e9-9a74-0d4127a3ab31.gif)

Yep, happens when for me too. Although it wasn't the case when when I ran normal command prompt (without windows terminal). In the gif, you can see the tabTitle changes as well as they keep on shrinking and growing.

**Comment by encladeus** [comment] 2019-09-08 10:03
@hoxha-saber With reference to the tabTitle changes that you reference above, this issue is raised in issue #2645. Your gif is the best illustration, so far, of that tabTitle issue.

**Comment by DHowett-MSFT** [comment] 2019-10-14 20:14
This was actually a /dupe of #3108.

**Closed** 2019-10-14 20:14 UTC
Labels: Area-TerminalControl, Issue-Bug, Product-Terminal
