### ISSUE TITLE
Off by one rendering of the current text in the prompt

### ISSUE THREAD

**Issue by KirillOsenkov** [microsoft/terminal#8711] opened 2021-01-05 23:08 UTC
# Environment

```none
Windows build number: Version 10.0.19042.685
Windows Terminal version (if applicable): 1.4.3243.0
```

# Steps to reproduce

I wasn't able to reproduce at will but I've seen this a few times

# Expected behavior

Things work as expected

# Actual behavior

Current prompt text is rendered one line below where it's supposed to be
![TerminalOffByOne](https://user-images.githubusercontent.com/679326/103709609-c7f6d400-4f67-11eb-96e4-71798901bdd5.gif)

I have no idea how to investigate or reproduce this, but I'm filing this to raise awareness that the issue exists, and will probably be very difficult to hunt down.

If you have any tips on the steps I could do to debug this next time I see this, I'd be happy to try them out.

**Comment by zadjii-msft** [comment] 2021-01-06 14:11
Shockingly, I think we've seen this before. #6546 is tracking just about the same bug, and some other related ones are in #5800. I get something like this every so often, but it's terribly hard to track down. 

If you had consistent repro steps, that would probably be the most useful thing. Unfortunately, this kind of bug is really hard to debug once it's already happened - it's usually best to get a trace of it _starting_ to happen. However, without consistent repro steps, it's incredibly hard to get such a trace 😕 

I'm gonna close this as a /dupe of #6546, but please hop on that thread if you do find a consistent repro!

**Closed by zadjii-msft** 2021-01-06 14:11 UTC
Labels: Needs-Tag-Fix, Needs-Triage
