### ISSUE TITLE
Active terminal does not get focus when window gets focus

### ISSUE THREAD

**Issue by patriksvensson** [microsoft/terminal#522] opened 2019-05-07 16:20 UTC
**Your Windows build number:**
10.0.18362.86

**What you're doing and what's happening:**

1. Open Windows Terminal
2. Start PowerShell console.
2. Make sure that the window have lost focus
3. Click on the window to focus the application
4. Start writing
5. Input is not sent to the active console

**What's wrong / what should be happening instead:**
Input should be sent to the active console.

**Comment by zadjii-msft** [comment] 2019-05-07 18:29
Where _specifically_ are you clicking to focus the window?

I'm seeing that clicking in the main part of the terminal window (with the text) works to send focus, but clicking anywhere in the tab row does _not_ focus the terminal control

**Comment by patriksvensson** [comment] 2019-05-07 20:51
@zadjii-msft Yes. I realized it only occurs when clicking the tab row. However, is this by design?

Btw, before I forget; I really love what you're doing with this project! The Windows Terminal is super fast!

**Comment by zadjii-msft** [comment] 2019-05-07 20:54
That's good to know! Makes fixing it a lot easier. It's definitely not by design, I just need to know what UI element we need to eat the focus from :P

Thanks for the kind words! We're really happy to be able to make this for the community (and ourselves :P)

**Comment by carlos-zamora** [comment] 2019-05-10 16:36
Found a few scenarios to lose focus (I suspect these to be basically the same problem):
1. Clicking tabs:
    - Repro:
        - Open a tab w/ CTRL+T (focus should be ok for now)
        - Click on the tab you're using (focus should be lost)
    - Interestingly, if you then press the left arrow key, you switch to the tab on the left. BUT, if you press the left arrow key again, you are now moving around in the terminal control for the tab you just focused on.
2. Clicking the drop-down menu:
    - Repro:
        - Click drop-down menu (focus is now on menu. Arrow keys let you explore that. Typing does not go to term control [bug?])
        - Click drop-down menu again to close it (focus is now stuck in tab control again. Same as extra bullet point in scenario 1)

**Comment by Borkason** [comment] 2019-11-11 17:44
This also happens with

```
Windows build number: 10.0.19018.0
Windows Terminal version (if applicable): 0.6.2951.0
```

When the Terminal regains focus by either clicking the title bar, any tab or the app icon in the task bar, then only the window is focused, not the active terminal, preventing you to type text into it.

**Comment by zadjii-msft** [comment] 2019-11-11 17:53
Hey wadda ya know, this might just be related to #1205, which I just started on this morning. I'll make sure to include these scenarios in my investigations.

**Comment by khowling** [comment] 2019-11-13 23:20
Moved to Windows terminal this week, loving it, but this is my biggest user-experience issue.  I need to retrain my brain.  Windows has trained me the safe way to focus any command window is by clicking the title-bar then the cursor will be in the correct place so i can type.  I've typed so many characters into the ether this week

**Closed** 2019-11-18 21:41 UTC
Labels: Area-Interaction, In-PR, Issue-Bug, Product-Terminal

**Comment by nickcano** [comment] 2020-01-05 04:26
I'm still experiencing this issue. Exactly as described here and in #3609. Just switched to terminal hoping to make it my main, but this is really messing with me. My version:

```
Windows Terminal (Preview)
Version: 0.7.3451.0
```

I'm on 1903 (Build 18362.535)

**Comment by DJackman123** [comment] 2020-01-07 23:21
Confirming that it's still happening for me as well.  Looks like issue #3609 is still open and addressing this problem.

**Comment by KuroshM** [comment] 2022-10-17 06:36
I have version 1.15.2712.0 and opening a new tab (Ctrl+Shift+T ) does not gain focus until clicked on the window area.

**Comment by charliefortner** [comment] 2022-11-01 21:07
Problem persists in version 1.15.2874.0
I launch Terminal from Start Menu and then must click the window for it to gain focus. I've tried Alt+Tab to switch away and then back to the Terminal window, but it still won't get focus so I can type.

**Comment by zadjii-msft** [comment] 2022-11-02 12:10
If you're seeing this on 1.15+, you're probably seeing #13388, not this thread. I'm gonna lock this thread as out-of-date. The root cause here was addressed a couple years ago. Let's track the new regression in the new thread. Thanks!
