### ISSUE TITLE
Option to Reconnect the session (Ctrl+R)

### ISSUE THREAD

**Issue by jbl241987** [microsoft/terminal#7580] opened 2020-09-09 16:16 UTC
# Description of the new feature/enhancement
If a session expires and disconnect (For example an SSH session to remote server), then there should be an option to reconnect just using keyboard functions.
 It is much easier to use some keyboard combination to reconnect to the disconnected session in the same pane than open duplicate pane or new pane.

# Proposed technical implementation details (optional)
I think ctrl+r should just reconnect to the session window which is open but disconnected from remote server.

ctrl+r to reconnect to a session.

**Comment by DHowett** [comment] 2020-09-10 00:47
Thanks for the request! This looks like a /duplicate of #4772. :smile:

**Closed by DHowett** 2020-09-10 00:47 UTC
Labels: Issue-Feature, Needs-Tag-Fix, Needs-Triage
