### ISSUE TITLE
Features restored to defaults when unfocused

### ISSUE THREAD

**Issue by angelog0** [microsoft/terminal#18222] opened 2024-11-20 08:34 UTC
### Windows Terminal version

1.22.241118002-preview

### Windows build number

10.0.19045.5131

I would WT semitransparent when unfocused, so I added to `defaults` this

```
"defaults":
{
   "unfocusedAppearance":
   {
    "opacity": 50
   },
...
}
```

Without the above option, when unfocused WT conserve all features of the current profile (color scheme, cursor shape etc.). With the above code, when unfocused WT is semitransparent but `colorScheme` etc are restored to default for each profile. This is a bit annoying because one should add for each profile something like:

```
...
"colorscheme": mycolors
...
// For each profile
"unfocusedAppearance":
   {
    "colorScheme": mycolors
   },
```

Why does WT not conserve those features when one uses the `unfocusedAppearance` option?

**Comment by carlos-zamora** [comment] 2024-11-21 00:07
Thanks for filing! This is actually by design. Here's a comment that provides some more details: https://github.com/microsoft/terminal/issues/14337#issuecomment-1306244206

Marking this as a /dup of #14337

**Closed** 2024-11-21 00:07 UTC
Labels: Issue-Bug, Needs-Triage

**Comment by angelog0** [comment] 2024-11-23 15:23
At the end I added

```
"unfocusedAppearance":
                {
                    "colorScheme": "My_Colors",
                    "opacity": 75
                }
```

for each shell I use (MSYS2, WSL, DOS, PS..) but it flickers when there are more tabs and one switches between them. This does not occurs with MinTTY, for example. The flicker is a bit annoying so I reverted the changes in settings.json...
