### ISSUE TITLE
Incorrect keycode for "CTRL+H" in Windows Terminal

### ISSUE THREAD

**Issue by skywind3000** [microsoft/terminal#5957] opened 2020-05-18 03:36 UTC
# Environment

```none
Windows: 
Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.18363.0 Microsoft Windows NT 10.0.18363.0

Vim.exe: 8.2.701
```

# Steps to reproduce

1. start "cmd.exe" in windows terminal.
2. run vim.exe (https://github.com/vim/vim-win32-installer/releases)
3. input "iaaaaaaa" to enter insert mode and append some characters.
4. press "CTRL+h" several times

# Expected behavior

The previous "aaaaa" should get deleted (CTRL+H in vim's insert mode will delete previous character), just like running vim.exe in the traditional `cmd.exe` window.

# Actual behavior

![图片](https://user-images.githubusercontent.com/3035071/82171493-12084800-98fa-11ea-97e8-a9eca3c77df9.png)

"CTRL+h" inserts some strange characters: "ÎzÎzÎzÎzÎzÎzÎz"

after some inspection, I located the difference, if I use `getch` in `msvcrt.dll` to display keycode: 

1. Run cmd.exe directly:

```none
D:\>python -c "import msvcrt;print(msvcrt.getch())"
b'\x08'                   <--- press CTRL+H

D:\>python -c "import msvcrt;print(msvcrt.getch())"
b'\x08'                   <--- press BackSpace
```

Both "CTRL+H" and "BackSpace" are `b'\x08'`, vim.exe works fine with it .

2. Run cmd.exe in Windows Terminal:

```none
D:\>python -c "import msvcrt;print(msvcrt.getch())"
b'\x7f'                   <--- press CTRL+H

D:\>python -c "import msvcrt;print(msvcrt.getch())"
b'\x08'                   <--- press BackSpace
```

Now, "CTRL+H" becomes `b'\x7f'` in Windows Terminal, which is different from running cmd.exe directly without windows terminal, and that difference breaks some terminal softwares like vim.exe .

**Comment by skywind3000** [comment] 2020-05-18 03:52
I checked with WSL in Windows Terminal:

![图片](https://user-images.githubusercontent.com/3035071/82172661-63fe9d00-98fd-11ea-8f33-3768a26efb67.png)

It works as expected, "CTRL+H" sends 0x08 and "BackSpace" sends 0x1f. This is what most linux terminal do. 

But why "CTRL+H" behave differently with cmd.exe ??

**Comment by tasogare3710** [comment] 2020-05-18 16:07
I'm not sure, but there may be this issue with app that uses PDCurses.

@skywind3000

> But why "CTRL+H" behaves differently with cmd.exe ??

In the old days, no backspace key on keyboard, and ctrl + H (^H) was used to input the control character backspace(08).

The control key is a key for input control characters.

**Comment by DHowett** [comment] 2020-05-18 23:51
So, yes. We placed the Windows encoding for <kbd>Ctrl+H</kbd> on the sacrificial altar when we fixed <kbd>Ctrl+Backspace</kbd>. We've got plans in the works that'll make this better.

Thanks.

**Comment by DHowett** [comment] 2020-05-18 23:53
For reference, this will be part of #4999.

**Comment by skywind3000** [comment] 2020-05-19 06:49
In the xterm standard:

- CTRL+H is `0x08`.
- BackSpace is `0x1f`.
- CTRL+BackSpace is `0x1f`.

![图片](https://user-images.githubusercontent.com/3035071/82293867-cfb93680-99df-11ea-93d0-b1e48597e64c.png)

They won't conflict with each other.

**Comment by DHowett** [comment] 2020-05-19 06:58
?

I just used xterm 351 and pressed <kbd>Backspace</kbd>, <kbd>Ctrl+H</kbd> and <kbd>Ctrl+Backspace</kbd>.

![image](https://user-images.githubusercontent.com/189190/82294684-6267c000-9963-11ea-95aa-3093c9a3dd4f.png)

They have the same encoding.

**Comment by skywind3000** [comment] 2020-05-19 07:59
@DHowett 

Thanks for including this in milestone 1.1,   

@tasogare3710 ,

Vim doesn't require PDCurses, it uses Win32 console APIs directly. You may say PDCurses and old console apps have bugs for this, but why `getch` in msvcrt.dll can't produce the same keycode for `CTRL+H` ?

Try this:

    python -c "import msvcrt;print(msvcrt.getch())"

and press CTRL+H.

At least, Windows Terminal should not break msvcrt, isn't it ?

**Comment by skywind3000** [comment] 2020-05-19 08:09
@DHowett , the xterm app you are using are too old, you can try Putty, MinTTY, iterm2, terminal.app.

Most modern terminal apps send `0x08` for CTRL+H, `0x7f` for BackSpace by default, and they provide options for customizing:

XShell's default:

![图片](https://user-images.githubusercontent.com/3035071/82300939-2166be80-99ea-11ea-817c-27d910bbdb94.png)

PuTTY's default:

![图片](https://user-images.githubusercontent.com/3035071/82301050-48bd8b80-99ea-11ea-904c-9d3b40310f3f.png)

Terminal.app's default:

![图片](https://user-images.githubusercontent.com/3035071/82301274-9639f880-99ea-11ea-9a90-1231b509a5f9.png)

iTerm2's default:

![图片](https://user-images.githubusercontent.com/3035071/82301321-a520ab00-99ea-11ea-871c-662899922447.png)


I think I made my point.

**Comment by DHowett** [comment] 2020-05-19 14:59
@skywind3000 None of those configures what _ctrl+backspace_ does, which is the issue we are discussing. I know that _backspace_ is configurable.

**Comment by GoodClover** [comment] 2020-06-02 11:22
I tested this running cmd prompt in Windows Terminal, thought it might be useful here.

That keyboard section of the table is what I typed.

The common section of the table is what is "correct" for that keycode - not necacerily the most common usage.

  Keyboard | Decimal | Hex |    Binary | Unicode   | Common
---------: | ------: | --: | --------: | --------- | ----------------------------------------
 Backspace |       8 |   8 |      1000 | Backspace | Backspace, ^h
        ^? |       8 |   8 |      1000 | Backspace | Backspace, ^h
        ^h |     127 |  7F |   1111111 | Delete    | Delete, ^?
    Delete |     330 | 14A | 101001010 | Ŋ         | LATIN CAPITAL LETTER ENG
^Backspace |     127 |  7F |   1111111 | Delete    | Delete, ^?
   ^Delete |     527 | 20F | 100000111 | ȏ         | LATIN SMALL LETTER O WITH INVERTED BREVE

Following the pattern that ^a ^b ^c are 0x1 0x2 and 0x3, I would assume that ^h would be 0x8, it is not.

^h should be identical to Backspace.

These kinds of "errors" appear to happen with other keys as well. This isn't always a bad thing as keyboards keys meanings do evolve over time. And for correct usage the key may have to change what it represents.

However here is what I think the "correct" table would be:

 Keyboard | Decimal | Hex |  Binary | Unicode   | Common
--------: | ------: | --: | ------: | --------- | -------------
Backspace |       8 |   8 |    1000 | Backspace | Backspace, ^h
       ^? |     127 |  7F | 1111111 | Delete    | Delete ^?
       ^h |       8 |   8 |    1000 | Backspace | Backspace, ^h
   Delete |     127 |  7F | 1111111 | Delete    | Delete ^?

^Backspace and ^Delete don't have a standard for what the should be as far as I know.

**Comment by skywind3000** [comment] 2020-06-02 15:05
objection, I use CTRL+h and BackSpace in vim for different purpose, their can't share the same keycode. BackSpace uses 127 by default in many modern terminals.

**Comment by GoodClover** [comment] 2020-06-02 15:51
> This isn't always a bad thing as keyboards keys meanings do evolve over time. And for correct usage the key may have to change what it represents.

I didn't mean that it should be backspace I was just saying that due to the way the Control key works Ctrl+H ends up being hex 8 which is back space. The ctrl key wasn't intended to be used the way it is today and that causes issues. It was intended for entering control codes.


If you look at [Unicode chart 0](https://www.unicode.org/charts/PDF/U0000.pdf)
Backspace has the code 0x8.

Now look at this:
| Keyboard | Hex | Hex Meaning      |
| ---------- | ----: | ------------------ |
| ^A           |   01 | Start of Heading |
| ^B           |   02 | Start of Text         |
| ^C           |   03 | End of Text          |
| ^D           |   04 | End of Transmission |

See the pattern?
Following this ^H would be 08
But this would cause issues as that means Backspace and that character is still in common usage.
Therefore:
^H has been replaced with 7f (127) meaning delete.
^? has been replaced with 08 (8) meaning backspace.
Delete has been replaced with 14a (330) meaning "Ŋ".
Etcetera.

To make it clear:
^H *literally* means backspace.
^H and ^? have been swapped.

Another example if you need it:
^I (i not L) is 9
9 means Horizontal Tabulation (Known as tab).
Try it, ^I will usually give you a tab.

**Comment by GoodClover** [comment] 2020-06-02 16:02
Though of something. Here it is:
Imagine each letter being replaced by its place in the alphabet.
e.g A=1, B=2, C=3
Now to get that letter in ASCII/Unicode you add 64 (1000000) to it.
To get it lowercase add 96 (1100000) (another 32) to it.
Using that number by itself gives you a control code.
To get this control code your press the (guess what!) control key.

This causes issues using Ctrl for shortcuts as you don't want the control code as the key does, you want your shortcut.
A lot of control codes aren't used anymore so its usually ok though.
For the ones that do cause issues they get re-wired sometimes. (Like ^H and ^J) to other symbols that don't really get used (Like ȑ and ȏ).

I'm not saying this is the right thing to do, but it's what is done.

**Comment by BDisp** [comment] 2021-05-31 20:55
A single sample which fail with `Windows Terminal` (`PowerShell`,` cmd` and `Windows PowerShell`) but not will fail if using `WSL` inside `Windows Terminal`. Using the dotnet "`System.Console.ReadKey`", pressing the `Enter` key, the `ConsoleKeyInfo` returns the right information, using `PowerShell` or `cmd`, without using the `Windows Terminal`, i.e `Key = ConsoleKey.Enter` and `KeyChar = 13'\r'`. But using the `Windows Terminal` the information is `Key = 0` and `KeyChar = 13'\r'`, which is interpreted as` Ctrl + M`, because as the `Key = 0` is assumed there was pressed the Control key and 13 is the index starting from `1 to 26` (`A to Z`), which is `'M'`. The `WSL` inside the `Windows Terminal` is working as expected. Why the `ConsoleKey.Enter` is not passed to the `Windows`, inside the `Windows Terminal`, as same it is passed to `WSL`?

**Comment by Toxic-Waste-** [comment] 2021-07-30 09:13
Is there a fix or a way to remap this in the future planned?

I wanted to switch over to Windows Terminal as my main terminal client, but unfortunately this breaks my ability to use backspace on our Huawei routers over Telnet. When I am able to reconfigure it (like PuTTY using Control-?(127) instead of Control-H, the backspace works fine in the Huawei  SSH connections.

Any update on this?

**Comment by calledback** [comment] 2021-08-18 13:36
Hi, I had the same problem and solved it using this custom setting:

`{ "command": { "action": "sendInput", "input": "\b" }, "keys": "backspace" }`

**Comment by calledback** [comment] 2021-08-18 13:38
> Is there a fix or a way to remap this in the future planned?
> 
> I wanted to switch over to Windows Terminal as my main terminal client, but unfortunately this breaks my ability to use backspace on our Huawei routers over Telnet. When I am able to reconfigure it (like PuTTY using Control-?(127) instead of Control-H, the backspace works fine in the Huawei telnet connections.
> 
> Any update on this?

Hi, I had the same problem and solved it using this custom setting:

`{ "command": { "action": "sendInput", "input": "\b" }, "keys": "backspace" }`

**Comment by sgk** [comment] 2021-08-18 16:24
Oh, I didn't know that such simple setting can solve the problem. I added the following lines in my settings.json, and works fine.

```
{ "command": { "action": "sendInput", "input": "\b" }, "keys": "backspace" },
{ "command": { "action": "sendInput", "input": "\u007f" }, "keys": "delete" }
```

**Comment by Toxic-Waste-** [comment] 2021-08-19 07:44
> 
> 
> > Is there a fix or a way to remap this in the future planned?
> > I wanted to switch over to Windows Terminal as my main terminal client, but unfortunately this breaks my ability to use backspace on our Huawei routers over Telnet. When I am able to reconfigure it (like PuTTY using Control-?(127) instead of Control-H, the backspace works fine in the Huawei telnet connections.
> > Any update on this?
> 
> Hi, I had the same problem and solved it using this custom setting:
> 
> `{ "command": { "action": "sendInput", "input": "\b" }, "keys": "backspace" }`

Not all heroes wear capes, you are my hero today sir :)

**Comment by xoofx** [comment] 2021-12-31 16:32
> @skywind3000 None of those configures what _ctrl+backspace_ does, which is the issue we are discussing. I know that _backspace_ is configurable.

I have a question for Unix folks: Is it important that `CTRL+Backspace` maps to `\x8` or could it map to e.g `\x17` (so `CTRL+W`,  Backword) in the specific case of Windows Terminal? (when the console is configured with `ENABLE_VIRTUAL_TERMINAL_INPUT`, see #4949). Seems that many terminals don't allow to remap `CTRL+Backspace` anyway...

**Comment by MattBDev** [comment] 2022-06-14 13:17
> > Is there a fix or a way to remap this in the future planned?
> > I wanted to switch over to Windows Terminal as my main terminal client, but unfortunately this breaks my ability to use backspace on our Huawei routers over Telnet. When I am able to reconfigure it (like PuTTY using Control-?(127) instead of Control-H, the backspace works fine in the Huawei telnet connections.
> > Any update on this?
> 
> Hi, I had the same problem and solved it using this custom setting:
> 
> `{ "command": { "action": "sendInput", "input": "\b" }, "keys": "backspace" }`

Unfortunately using this command with PowerShell or cmd.exe will remove the entire word when using backspace instead of removing one character at a time. Not exactly ideal. If only we could configure the backspace command per profile instead of globally.

**Comment by unphased** [comment] 2022-08-17 04:14
I came here because I use Ctrl+H to move to the left pane in tmux and vim, and I use Ctrl+Backspace to delete a word backwards. I am used to making adjustments to ensure that all three work. 

The way to make this work for Windows Terminal (which is growing so well and I no longer try to run Alacritty on windows anymore, and haven't ran Putty in years) to be consistent with what I believe to be the ideal modern Linux and BSD mapping of these keys: 

```
	{ "command": { "action": "sendInput", "input": "\u007f" }, "keys": "backspace" },
	{ "command": { "action": "sendInput", "input": "\u001b\u007f" }, "keys": "ctrl+backspace" }
```

**Comment by zadjii-msft** [comment] 2022-09-02 14:35
just as a tldr: Seems like this thread forked off to track a different issue. Originally, it was tracking that Ctrl+H _didn't_ behave as expected in `vim.exe`. It wouldn't backspace characters. That was before win32-input-mode. Now it does the right thing, which is still weird and not exactly what everyone expects. 

See also:
* #4999
* #13894

**Comment by skywind3000** [comment] 2022-09-02 14:43
this can be closed now, Ctrl+h works fine in vim now.

**Closed** 2022-09-02 14:43 UTC
Labels: Product-Conpty, Area-Input, Issue-Bug, Priority-2
