### ISSUE TITLE
strange behaviour with pasting some RtoL text

### ISSUE THREAD

**Issue by burito** [microsoft/terminal#1217] opened 2019-06-12 13:26 UTC
# Environment

```none
Microsoft Windows [Version 10.0.18362.175]
Windows Terminal version (if applicable):
1580c1e0934f7b04dcd420df051f8604df04c670
```

# Steps to reproduce

paste in the text on the next line
```
ڰ,  ڱ,	ڲ
```
# Expected behavior

Said text to be pasted

# Actual behavior

<img width="137" alt="Annotation 2019-06-12 225130" src="https://user-images.githubusercontent.com/218841/59354643-a4a47c80-8d64-11e9-91d5-5706c367716a.png">

**Comment by DHowett-MSFT** [comment] 2019-06-13 21:53
Looks like a dupe of #538. Thanks!

**Closed by DHowett-MSFT** 2019-06-13 21:53 UTC
Labels: Needs-Tag-Fix, Needs-Triage
