### ISSUE TITLE
ssh-keygen hangs when run from PowerShell 7.1.1 in Windows Terminal, cannot repro with new tabs

### ISSUE THREAD

**Issue by sba923** [microsoft/terminal#8814] opened 2021-01-18 10:10 UTC
# Environment

```none
Windows build number: 10.0.18363.1256
Windows Terminal version (if applicable): 1.4.3243.0

PowerShell 7.1.1

C:\WINDOWS\System32\OpenSSH\ssh-keygen.exe
Product version: 'OpenSSH_7.7p1 for Windows'
```

# Steps to reproduce

Run `C:\WINDOWS\System32\OpenSSH\ssh-keygen.exe`

# Expected behavior

Input should be possible at the following prompt

`Enter file in which to save the key (C:\Users\sbarizien/.ssh/id_rsa):`

# Actual behavior

No input is possible, the `ssh-keygen.exe` process needs to be terminated.

This behavior cannot be reproduced:
1. in PowerShell 7.1.1 not running within Windows Terminal
2. in other / new Windows Terminal tabs running PowerShell 7.1.1
3. in Windows PowerShell 5.1 running within Windows Terminal
4. on another machine running Windows 10 build 19042.746

So there is something special about this particular instance of PowerShell 7.1.1 running in that particular Windows Terminal tab.

I can keep that tab open as long as needed in order to diagnose the issue.

**Comment by zadjii-msft** [comment] 2021-01-20 22:58
Hmm, this looks quite a bit like #7467, though that issue says it was fixed in 8.1. Could you test the latest version of `ssh-keygen`?

**Comment by sba923** [comment] 2021-01-21 09:24
Where should I get pre-built binaries of OpenSSL 8.4 for 64-bit Windows 10 from?

**Comment by zadjii-msft** [comment] 2021-01-21 11:00
https://github.com/PowerShell/Win32-OpenSSH/releases

**Comment by sba923** [comment] 2021-01-21 11:03
Issue repro'ed with `C:\OpenSSH-Win64\8.1.0.0p1-Beta\OpenSSH-Win64\ssh-keygen.exe` (MD5 = `301109080A5B375B34D4898EB9321C25`)

**Comment by sba923** [comment] 2021-01-26 09:44
I hate to say, but I had to reboot my PC... so the issue isn't there anymore...

**Comment by zadjii-msft** [comment] 2021-01-26 11:26
Ah. Well that's nice an annoying. I'd guess that this wasn't something that was caused by the Terminal if it went away after a reboot. 

Since #7467 is so similar, I'm gonna close this as a dupe. Maybe in the future, someone will figure out what happened here. 

Thanks for following up!

/dup #7467

**Closed by zadjii-msft** 2021-01-26 11:26 UTC
Labels: Needs-Attention, Needs-Tag-Fix, Needs-Triage

**Comment by sba923** [comment] 2021-03-19 11:18
Just experienced the **exact same issue** with `netsh` launched from PowerShell 7.1.3 running in a Windows Terminal Preview 1.7.572.0 tab. In another (new) tab, the issue cannot be repro'ed.
