### ISSUE TITLE
Titlebar/tabs not responsive

### ISSUE THREAD

**Issue by nitishvijai** [microsoft/terminal#4552] opened 2020-02-12 19:44 UTC
# Environment

```none
Windows build number: 10.0.19559.0
Windows Terminal version (if applicable): 0.8.10261.0

Any other software?
Windows Subsystem for Linux (Ubuntu)
```

# Steps to reproduce

Open Windows Terminal. For me, PowerShell opened by default.

# Expected behavior

Clicking on the Add button should add a new tab, the dropdown button should open a list of terminals, and clicking on one of the caption buttons should either close, minimize, or maximize the window.

# Actual behavior

When clicking on the add button, dropdown button, or one of the caption buttons (close, minimize, maximize), nothing happens. I can still drag the window around the screen, but the titlebar is not responsive. I cannot add a new tab or select a different terminal.

**Comment by DHowett-MSFT** [comment] 2020-02-12 19:45
Are you using PowerToys/

**Comment by nitishvijai** [comment] 2020-02-12 19:47
Yes, I am using PowerToys version 0.14.1.0.

**Comment by DHowett-MSFT** [comment] 2020-02-12 19:47
In that case, this is a /dupe of #3325. Thanks!

**Closed by DHowett-MSFT** 2020-02-12 19:48 UTC
Labels: Needs-Attention, Needs-Tag-Fix, Needs-Triage

**Comment by crutkas** [comment] 2020-02-13 16:04
@ nitishvijai can you get it to happen without PT running?

**Comment by nitishvijai** [comment] 2020-02-13 16:07
@crutkas Yes, I closed PowerToys and the titlebar started working again. Could it be an issue with FancyZones?

**Comment by crutkas** [comment] 2020-02-13 16:43
Any chance you can email me, would love to debug this with you. I can’t repo it directly. Only can cause a freeze via the outlined method in the other bug which can be reproduced without PT installed. Crutkas@microsoft.com
