### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by acworkma** [microsoft/terminal#1684] opened 2019-06-27 21:50 UTC
# Environment

```none
Windows build number: [run "ver" at a command prompt]
Version 10.0.18362.175
Windows Terminal version (if applicable):
0.2.1715.0
Any other software?
```

# Steps to reproduce
Start a new Linux tab

# Expected behavior

Should start in users home directory. Just like when launching Ubuntu Bash. 

# Actual behavior

Starting in /mnt/c/WINDOWS/system32
![image](https://user-images.githubusercontent.com/15241126/60303276-38448400-98f3-11e9-86ef-d189d31c9cce.png)

**Comment by miniksa** [comment] 2019-06-27 22:18
This is a dupe of #592.

**Closed by miniksa** 2019-06-27 22:18 UTC
Labels: Needs-Tag-Fix, Needs-Triage, Resolution-Duplicate
