### ISSUE TITLE
Unicode observations on stdin & stdout

### ISSUE THREAD

**Issue by sipsorcery** [microsoft/terminal#3786] opened 2019-11-30 12:02 UTC
It's nice to see that unicode handling on stdin and stdout is improving from the old Windows Console. 

The tests below were done using:
- Windows 10 Pro 10.0.1.19033 Build 19033
- Windows Terminal Preview v0.7.3291.0
- Font: cascadia

The test steps were:
1. Paste `Run🏃` to the command prompt,
2. Hit Enter
3. Press the Up Arrow

![cmd_run](https://user-images.githubusercontent.com/197660/69900259-0aafab00-1369-11ea-9dc6-43d0081ff7c1.png)

![ps_run](https://user-images.githubusercontent.com/197660/69900271-26b34c80-1369-11ea-9e21-0d4f6900c175.png)

![wsl_run](https://user-images.githubusercontent.com/197660/69900286-3e8ad080-1369-11ea-8a04-03c000239638.png)

**Comment by j4james** [comment] 2019-11-30 16:15
I suspect there may be two separate issues here, because each shell has its own command line editor. For PowerShell, this problem was previously reported in issue #1503. For the cmd shell, I think it's a limitation of the COOKED_READ implementation, and the way it handles surrogate pairs. I couldn't find an existing issue for that, but it's possible it could be addressed by #780.

**Comment by DHowett-MSFT** [comment] 2019-12-02 20:56
I'm taking the baton here to find the dupes. Thanks @j4james for 1503. :smile:

**Comment by zadjii-msft** [comment] 2021-12-09 16:38
You know, he never did find those dupes 😛 

I'll go with #1503 since that's basically the root cause here. Thanks!  /dup #1503

**Closed by zadjii-msft** 2021-12-09 16:38 UTC
Labels: Needs-Tag-Fix
