### ISSUE TITLE
Erratic behavior when using input methods

### ISSUE THREAD

**Issue by Knowif** [microsoft/terminal#5282] opened 2020-04-08 05:42 UTC
# Environment

```none
Windows build number: Microsoft Windows [版本 10.0.18363.720]
Windows Terminal version (if applicable): 0.10.781.0

Any other software? no
```

# Steps to reproduce

Open a terminal with Chinese IME on. Now type any pinyin, e.g. "shili" ("example"), and you see the characters suggested by the IME.

![](https://github.com/Knowif/Repo-Demo/blob/master/%E6%89%B9%E6%B3%A8%202020-04-08%20132257.png?raw=true)

(The cursor bar should appear on the right side as mentioned in issue #3730, but it's a minor bug.)

Then hit backspace 5 times to clear the input.

# Expected behavior

What you just typed in the IME should be deleted and the IME suggestion box should be closed. There shouldn't be any side effects.

# Actual behavior

The suggestion box closes, but an unexpected "s" remains. What's more, while English input is still fine, you're *no longer able to use IME to type in this terminal window*: the suggestion box works but nothing appears in the terminal. 

![image](https://user-images.githubusercontent.com/26539617/78748159-de9ed900-799d-11ea-95a8-499c10a8951c.png)

This also happens when you interrupt the IME, for example by clicking elsewhere, before accepting the characters.

**Comment by skyline75489** [comment] 2020-04-08 08:43
This is a known issue. Related to #5054 and #5110 .

**Comment by Knowif** [comment] 2020-04-08 09:21
@skyline75489 Thanks for replying! I see now it's a duplicate of #5054 and there seems to be already a fix (#5109). The first-letter thing still exists, though. I'm just a student and I haven't studied much of the source code, but I think I'll fork the repo and try to build and understand it in case my computer hardware permits.

**Comment by skyline75489** [comment] 2020-04-08 10:58
@Knowif Glad to hear that. A good practice before submitting an issue would be checking if there's any duplicate. Contributing is also welcomed.

**Comment by zadjii-msft** [comment] 2020-04-08 13:38
Thanks for the triage pass @skyline75489! 

@Knowif since you're thinking this looks like a dupe of #5054, I'm going to resolve this issue as such. If this ends up coming back after 0.11 comes out, then feel free to ping us here and we can re-open to continue the investigation. Thanks!

/dupe #5054

**Closed by zadjii-msft** 2020-04-08 13:38 UTC
Labels: Needs-Tag-Fix, Needs-Triage
