### ISSUE TITLE
We might need another dependency for MIDI support

### ISSUE THREAD

**Issue by zadjii-msft** [microsoft/terminal#13252] opened 2022-06-08 21:49 UTC
~Promoted from a Teams thread. Tracking here so we don't lose it. ~

Notes from @DHowett:
> @j4james handled this for us, by adding a package dependency on `GmDls`. We need to make sure that when Terminal is installed, users get access to it. I am somewhat concerned about what this means for Inbox Terminal, though: It costs us 3MB on disk which will be aggressively counted against us by Windows Perf Gates
> I looked at the code that loads gm.dls and it seems like it was never updated to consider Centennial apps. If a process has "strong identity" (a package), it forces a catalog enumeration to find the GmDls package. We might be able to defray the cost of pulling in a second copy of gm.dls to the Windows image by giving it the ability to "fail over" to the system32 one.

**Comment by zadjii-msft** [comment] 2022-06-09 17:18
Plan of record right now is to stash this behind velocity, so it only ships in Preview (and critically, not in the OS-side build). That way we can get a little longer window on figuring out how we want to resolve this.

**Comment by phil-blain** [comment] 2022-06-09 18:00
Hi, I just tried to compile Terminal from 4e20a8631cbb5b20defe549a0e75bc7719969bee and installing it from a loose package as detailed in https://github.com/microsoft/terminal/blob/main/doc/building.md. 

I can confirm that installing the loose package fails for me with (pardon my French!)
~~~
Add-AppxPackage : Deployment failed with HRESULT: 0x80073CF3, Échec des mises à jour, de la dépendance ou de la validation des conflits du package.
Windows ne peut pas installer le package WindowsTerminalDev_0.0.1.0_x64__8wekyb3d8bbwe, car ce package dépend d’une infrastructure qui n’a pas pu être trouvée. Indiquez
l’infrastructure «Microsoft.Midi.GmDls» publiée par «CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US», avec une architecture neutre ou de
processeur x64 et la version minimale 1.0.0.0, en plus de ce package à installer. Les infrastructures avec le nom «Microsoft.Midi.GmDls» installées actuellement sont
Windows ne peut pas installer le package WindowsTerminalDev_0.0.1.0_x64__8wekyb3d8bbwe, car ce package dépend d’une infrastructure qui n’a pas pu être trouvée. Indiquez
l’infrastructure «Microsoft.Midi.GmDls» publiée par «CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US», avec une architecture neutre ou de
processeur x64 et la version minimale 1.0.0.0, en plus de ce package à installer. Les infrastructures avec le nom «Microsoft.Midi.GmDls» installées actuellement sont: {}
NOTE: For additional information, look for [ActivityId] 92e6da5a-7c16-0002-9b44-ea92167cd801 in the Event Log or use the command line Get-AppPackageLog -ActivityID
92e6da5a-7c16-0002-9b44-ea92167cd801
At line:1 char:1
+ Add-AppxPackage -Path ..\loose\AppxManifest.xml -Register -ForceUpdat ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (C:\Users\me...ppxManifest.xml:String) [Add-AppxPackage], IOException
    + FullyQualifiedErrorId : DeploymentError,Microsoft.Windows.Appx.PackageManager.Commands.AddAppxPackageCommand
~~~

I'm currently building from `9dca6c27eeeb4371c87cdc553d01b8876d028d21^` (i.e. 7dbe741e1) just to confirm that 9dca6c27eeeb4371c87cdc553d01b8876d028d21 is  indeed is the culprit, but since I found this issue in the meantime I'm pretty sure now :P

**Comment by DHowett** [comment] 2022-06-09 19:07
Curious. That package should be available on your system, @phil-blain, somewhere in `C:\Program Files (x86)`. It comes with the Windows SDK or one of the extension SDKs that ships with Visual Studio...

**Comment by phil-blain** [comment] 2022-06-09 20:00
It is indeed in `C:\Program Files (x86)\Microsoft SDKs\Windows Kits\10\ExtensionSDKs\Microsoft.Midi.GmDls\10.0.22000.0`. Maybe the installation does not work because it is not listed as a `PackageDependency` in the genereated `AppxManifest.xml` ?

**Comment by j4james** [comment] 2022-07-07 10:24
@DHowett FYI, I've been playing around with an alternate implementation that uses DirectSound to generate the audio in place of Midi. Would it be worthwhile submitting a PR with that change, or do you have other plans for resolving this?

**Comment by DHowett** [comment] 2022-07-08 18:27
_Huh,_ that seems like it might be a good way out of this! We wouldn't need to ship another package dependency...

I don't have any concrete plans that will resolve the `GmDls` package in the near future. My plans are more like, "Fix this in Windows 18 by getting the owner to let me move around some of their code," which would never be serviceable to earlier versions of Windows. :(

**Comment by j4james** [comment] 2022-07-08 21:43
> which would never be serviceable to earlier versions of Windows. :(

OK, that's a deciding factor for me. I'll try and put together a PR this weekend.

**Closed** 2022-07-14 11:33 UTC
Labels: Area-VT, Issue-Bug, Product-Terminal, In-PR, Priority-0
