### ISSUE TITLE
Missing Files

### ISSUE THREAD

**Issue by Tembocs** [microsoft/terminal#828] opened 2019-05-15 18:53 UTC
I'm trying to build Windows Terminal from command line using VS 2017 on Windows 10 x64 insider, build 18362.86. I kept getting the error below even after installing all the VS 2017 components that have something to do with C++ and .Net. From the error message it seems the build surprisingly involves VS 2019 (which I have installed as well). My expectation is VS 2019 should not be involved as I use VS 2017 command line.  I then decided to install all the components that have something to do with C++ and .Net for VS 2019. I still get the same error message. 

My steps for building:
1. Clone the repo from github
2. Do `git submodule update --init --recursive`
3. Do `.\tools\razzle.cmd`
4. Do `bcz`

What am I missing? The error message is as below:
`C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v150\Microsoft.CppCommon.targets(2128,3): error MSB4019: The imported project "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\WindowsXaml\v15.0\Microsoft.Windows.UI.Xaml.Cpp.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk. [c:\Users\Tembo\Desktop\qnd\cpp\Terminal10\src\cascadia\TerminalSetting\TerminalSettings.vcxproj]`

**Comment by oising** [comment] 2019-05-15 18:59
duplicate of #489 

Please take a look at our "build problems" megathread.

**Closed by oising** 2019-05-15 18:59 UTC

**Comment by binarycrusader** [comment] 2019-05-19 04:53
For the record, I encountered this only when trying to use the razzle script and 'bz' alias to build.  I was able to resolve this by using the "Repair" option for VS2017 in the Visual Studio Installer.
