### ISSUE TITLE
Bug Report - Font Ligatures interact with the shell prompt

### ISSUE THREAD

**Issue by tensor-programming** [microsoft/terminal#938] opened 2019-05-22 10:45 UTC
# Environment
Windows 1903
Fira Code with Font Ligatures enabled

# Steps to reproduce
Use a font with font ligatures and type `-` or `=` as your first character.

# Expected behavior

I would expect the prompt not to interact with the characters.  In `c:\projects\>` the `>` symbol should not connect with any font ligatures. 

# Actual behavior
The `>` symbol combines to create font ligatures. 

The behavior is shown in the below images:
![font-ligatures-error-1](https://user-images.githubusercontent.com/22513880/58168814-2a00a980-7c5d-11e9-9715-8450d8f7d3ba.png)
![font-ligatures-error-2](https://user-images.githubusercontent.com/22513880/58168822-2cfb9a00-7c5d-11e9-8d83-0d617506bb57.png)

**Comment by mdtauk** [comment] 2019-05-22 10:50
The Prompt should really be self contained.  Maybe the settings screen should provide a visual way to choose your own prompt, if you wanted to use CharacterMap to insert a character, or a ligature sequence that wont combine with characters after it.

**Comment by tensor-programming** [comment] 2019-05-22 10:55
Yes, this is what I am thinking as well.  Decoupling the prompt from the inputted text to allow for different options.  Then maybe custom prompts would also be possible.

**Comment by HBelusca** [comment] 2019-05-22 13:02
Would inserting an (invisible) zero-width unicode space character after the end of the prompt fix the problem?

**Comment by tensor-programming** [comment] 2019-05-22 17:24
You could fix the problem with a break character of any kind.  Ligatures are combinations of unicode characters to build symbols and they are a part of the font.

**Comment by glen-84** [comment] 2019-05-22 18:06
Duplicate of #514.

**Closed** 2019-05-22 18:26 UTC
Labels: Needs-Tag-Fix, Needs-Triage
