### ISSUE TITLE
Program does not stop when windows terminal is closed.

### ISSUE THREAD

**Issue by kotenok2000** [microsoft/terminal#12236] opened 2022-01-24 13:58 UTC
### Windows Terminal version

1.11.3471.0

### Windows build number

10.0.22000.434

### Other Software

Lela chess zero chess engine
https://github.com/LeelaChessZero/lc0/releases/tag/v0.28.2

### Steps to reproduce

Use this guide 
https://github.com/LeelaChessZero/lc0/wiki/Getting-Started
start lc0-training client

Close windows terminal after lc0.exe has started.

### Expected Behavior

Lc0-training-client exits, just like with windows console host.

### Actual Behavior

lc0-training-client.exe continues to run.

**Comment by 237dmitry** [comment] 2022-01-24 14:30
> start lc0-training client

This starts process in its own window. Try `start /b`

**Comment by kotenok2000** [comment] 2022-01-24 14:38
It happens even when i open lc0-training client from windows explorer
i didn't mean that i used start command.

**Comment by kotenok2000** [comment] 2022-02-07 14:51
Can you fix it?

**Comment by zadjii-msft** [comment] 2022-02-07 17:17
Probably. We just need some time to investigate. Good chance this is a duplicate of #4564, but we'll need to confirm once that gets fixed.

**Comment by lhecker** [comment] 2022-12-13 01:31
Oh, #13586 seems like a duplicate of this one. Oh well, I'll close this issue in favor of #13586 then, since I've already responded there.

**Closed by lhecker** 2022-12-13 01:31 UTC
Labels: Product-Conpty, Area-Server, Issue-Bug, Product-Terminal, Priority-2
