### ISSUE TITLE
Windows Terminal Preview cannot restore default settings

### ISSUE THREAD

**Issue by obhasqr** [microsoft/terminal#14794] opened 2023-02-06 08:26 UTC
### Windows Terminal version

1.17.1023

### Windows build number

10.0.22000.1516

### Steps to reproduce

I installed the Windows Terminal stable (1.15.3466.0) and preview  (1.17.1023) releases from the MS store. 
When I follow the steps in the [docs](https://learn.microsoft.com/en-us/windows/terminal/troubleshooting#how-do-i-reset-my-settings-in-windows-terminal-back-to-the-default-settings) to restore the Windows Terminal Preview to default settings, it always resets to the stable version's settings instead of the default settings

### Expected Behavior

Reset settings back to the original default settings.

### Actual Behavior

Stable version's settings are used.

**Comment by obhasqr** [comment] 2023-02-08 02:51
Hi @lhecker, thanks for your reply, the steps you provided worked. If this is works as design, I would like an update to the docs.

**Comment by carlos-zamora** [comment] 2023-02-08 22:40
Thanks for the feedback. We're gonna mark this as a duplicate of #947 since that's tracking adding this kind of thing to the Settings UI.

With regards to updating the docs, we think it would be better in the long run to expose this via the UI rather than documenting the internals of settings parsing.

/dup #947

**Closed** 2023-02-08 22:40 UTC
Labels: Issue-Bug, Needs-Triage
