### ISSUE TITLE
Taskbar quick actions

### ISSUE THREAD

**Issue by SilvanKohler** [microsoft/terminal#3186] opened 2019-10-14 10:51 UTC
# Description of the new feature/enhancement

if you right-click on the icon in the taskbar the menu shows only "unpin from taskbar". It would be nice if there are the terminals that are in the settings described.

How it looks now:
![image](https://user-images.githubusercontent.com/40068335/66744502-e3665280-ee7c-11e9-882c-2f51f8066fe1.png)

How I think it is better:
![taskbar](https://user-images.githubusercontent.com/40068335/66746107-3d691700-ee81-11e9-92d6-536316a7d441.png)

# Proposed technical implementation details (optional)

**Comment by DHowett-MSFT** [comment] 2019-10-14 19:39
Hey, thanks! This is a /dupe of #576 (needs #607)

**Closed by DHowett-MSFT** 2019-10-14 19:39 UTC
Labels: Issue-Feature, Needs-Tag-Fix, Needs-Triage
