### ISSUE TITLE
Allow us to remove the ui completly and just use keyboardshortcuts.

### ISSUE THREAD

**Issue by NicTanghe** [microsoft/terminal#4515] opened 2020-02-10 11:15 UTC
Allow user to remove the ugly ui/ tittlebar/tabbar

# Proposed technical implementation details (optional)
Just make a toggle in settings that can disable all the code painting the ui. (its fucking eazy and should be first thing you did if it isn't eazy u fucked up)

NOTE UI FOR new tabs and close is for dumbfucks. these people don't use the commandline so we don't need a fucking ui. Just allow us to turn it of. we can move the window with windowskey + arrows and powertoys.

**Comment by DHowett-MSFT** [comment] 2020-02-10 14:52
Couple things:

1. The work required here makes this a /dupe of #2238. Thanks for the suggestion!
2. Please make sure to follow our [code of conduct](https://opensource.microsoft.com/codeofconduct/).

**Closed by DHowett-MSFT** 2020-02-10 14:52 UTC
Labels: Issue-Feature, Needs-Tag-Fix, Needs-Triage
