### ISSUE TITLE
clear command - Windows Terminal in VSCode

### ISSUE THREAD

**Issue by dash-mode** [microsoft/terminal#1291] opened 2019-06-16 22:10 UTC
# About the device
<img width="283" alt="VSCode version" src="https://user-images.githubusercontent.com/32212134/59569990-2515f680-905f-11e9-9751-b0bc090008d8.png">

# Summary of the bug
I deployed the windows terminal dev build and then started working on a separate project on VScode. I opened the VScode terminal and then after typing a couple of commands, I hit clear
<img width="960" alt="app js - factbotAzure - Visual Studio Code 6_16_2019 5_43_18 PM" src="https://user-images.githubusercontent.com/32212134/59570061-314e8380-9060-11e9-8a25-0fbe705f10c1.png">
After hitting clear, the cursor just moves to the top, but the contents of the terminal aren't cleared. In fact, everytime I write a command after clearing, it just writes over the previous command as if it were an empty line. 
<img width="960" alt="app js - factbotAzure - Visual Studio Code 6_16_2019 5_44_01 PM" src="https://user-images.githubusercontent.com/32212134/59570105-fc8efc00-9060-11e9-86c9-0478cc1b6a56.png">

I am not sure if this is a bug in VSCode or the windows terminal, so I have posted this issue in the vscode github page too.

**Comment by DHowett-MSFT** [comment] 2019-06-18 00:42
I can't get VSCode _or_ putty-wincon to reproduce this behavior. Would you mind running `clear|xxd` and pasting the output here?

VSCode and putty-wincon are using the same technology under the hood. If I can't get it to reproduce in putty-wincon, chances are it's a VSCode issue ... but if I can't get it to reproduce in VSCode, I'm questioning whether I'm doing the right thing.

**Comment by dash-mode** [comment] 2019-06-18 11:53
`clear|xxd` command ran in VSCode
<img width="449" alt="Annotation 2019-06-18 075241" src="https://user-images.githubusercontent.com/32212134/59679929-2d288000-919e-11e9-88d2-427c823aff6f.png">

**Comment by zadjii-msft** [comment] 2019-06-18 16:17
@dash-mode did you enable conpty in VSCode, or are you still using winpty?

I believe the setting is `"terminal.integrated.windowsEnableConpty": true`

**Comment by dash-mode** [comment] 2019-06-18 16:58
@zadjii-msft 
Yes, it is enabled.
<img width="796" alt="Annotation 2019-06-18 125701" src="https://user-images.githubusercontent.com/32212134/59703791-afc63500-91c8-11e9-91a1-f42c755f26c1.png">

**Comment by dash-mode** [comment] 2019-06-18 19:38
https://github.com/microsoft/vscode/issues/72130
Similar issue being tackled here. ^
I also wanted to point out that I am not facing this issue in my mac. This is happening in my windows machine,

**Comment by Tyriar** [comment] 2019-06-19 03:25
This is already fixed in v1.36, see https://github.com/microsoft/vscode/issues/72130#issuecomment-503390207 for the details.

In the future issues in VS Code's terminal should be created over on [microsoft/vscode](https://github.com/Microsoft/vscode) as there's many different parts that things can go wrong and I like to avoid getting the console team involved until I'm pretty sure conpty/conhost is the cause.

**Comment by DHowett-MSFT** [comment] 2019-06-19 03:25
Thanks again, @Tyriar!

**Closed** 2019-06-19 03:25 UTC
Labels: Area-Output, Issue-Bug, Needs-Repro, Product-Conpty

**Comment by dash-mode** [comment] 2019-06-19 12:04
> This is already fixed in v1.36, see [microsoft/vscode#72130 (comment)](https://github.com/microsoft/vscode/issues/72130#issuecomment-503390207) for the details.
> 
> In the future issues in VS Code's terminal should be created over on [microsoft/vscode](https://github.com/Microsoft/vscode) as there's many different parts that things can go wrong and I like to avoid getting the console team involved until I'm pretty sure conpty/conhost is the cause.

Hey @Tyriar . I did post the exact same issue in microsoft/vscode/issues/75607 . But I have closed it now since it has been fixed. Thanks
