### ISSUE TITLE
希望可以加入从屏幕顶部quake式向下滑动的打开方式

### ISSUE THREAD

**Issue by meichangliang** [microsoft/terminal#5010] opened 2020-03-19 06:06 UTC
就类似于 cmder 的这个功能:
![图片](https://user-images.githubusercontent.com/24769632/77036519-5191e100-69ea-11ea-97a5-bae6304bd606.png)
按下一个快捷键就从屏幕点高端滑下来,再按一下就收回去,而且是窗口置顶状态,实在是太方便了,

希望 windows terminal  也可以实现这样的功能!

**Comment by gschizas** [comment] 2020-03-19 09:11
As far as I can tell, they are asking about the "quake mode", which was coverd in https://github.com/microsoft/terminal/issues/653

**Comment by meichangliang** [comment] 2020-03-19 09:16
> As far as I can tell, they are asking about the "quake mode", which was coverd in #653
You're right, but it's not exactly the same ;  Kind of like deepin for thor mode  terminal

**Comment by skyline75489** [comment] 2020-03-19 09:58
Yeah I can confirm this is duplicate of #653 .

**Comment by zadjii-msft** [comment] 2020-03-19 12:45
Thanks for the help triaging!

/dup #653

**Closed by zadjii-msft** 2020-03-19 12:45 UTC
Labels: Issue-Feature, Needs-Tag-Fix, Needs-Triage

**Comment by gschizas** [comment] 2020-03-19 12:57
> > As far as I can tell, they are asking about the "quake mode", which was coverd in #653

> You're right, but it's not exactly the same ;  Kind of like deepin for thor mode  terminal

![image](https://user-images.githubusercontent.com/598065/77069740-aa18ac80-69f1-11ea-8fde-e02cc78fcaeb.png)

The part you highlighted (and the functionality) points exactly to Quake mode terminal..
