### ISSUE TITLE
Create tab from outside command

### ISSUE THREAD

**Issue by giggio** [microsoft/terminal#969] opened 2019-05-24 00:57 UTC
## Summary of the new feature/enhancement

The Windows Terminal should support opening tabs from commands that come from outside its GUI. We should be able to run, for example, `Terminal --run powershell.exe --cwd c:\myproject`  from anywhere and a new tab would be added to the Terminal, current working directory would be `c:\myproject` and `powershell.exe` would be the shell. If the Terminal was not running, then it would start and create only that tab.

My main use case for this is to use it with the Visual Studio extension [Open Command Line](https://marketplace.visualstudio.com/items?itemName=MadsKristensen.OpenCommandLine). I could then click on any directory on VS and ask it to open that directory on the new Terminal.

Conemu already supports this with `-run`: https://conemu.github.io/en/ConEmuArgs.html

**Comment by DHowett-MSFT** [comment] 2019-05-24 01:10
Thanks for the request! This is a duplicate of #607.

**Closed by DHowett-MSFT** 2019-05-24 01:10 UTC
Labels: Issue-Feature, Needs-Tag-Fix, Needs-Triage
