### ISSUE TITLE
Scrollback not rewrapped on resize

### ISSUE THREAD

**Issue by egmontkob** [microsoft/terminal#3491] opened 2019-11-08 21:42 UTC
# Environment

```none
Windows build number: 10.0.18362.0
Windows Terminal version (if applicable): 0.6.2951.0

Any other software?
```

# Steps to reproduce

- produce more than a screenful of data, e.g. `cat` a file, or `ssh` to a Linux box and then:

      seq -f 'the quick brown fox jumps over the lazy dog %.f' 100

- narrow the window so that the onscreen parts begin to wrap

- optionally widen it back

- scroll back

# Expected behavior

The entire scrollback should be rewrapped, just like the onscreen bits.

# Actual behavior

Each line of the scrollback is truncated to the narrow width.

**Comment by zadjii-msft** [comment] 2020-01-15 21:32
Hey so I'm sorting through some of our open issues, and it turns out this one's a /dupe of #1465.

Thanks for the report though! I'm hoping to get to this one (and a bunch of the related ones) this-ish month

**Closed by zadjii-msft** 2020-01-15 21:32 UTC
Labels: Area-Output, Area-TerminalControl, Issue-Bug, Priority-1, Product-Terminal
