### ISSUE TITLE
Cannot type chinese characters.

### ISSUE THREAD

**Issue by yx91490** [microsoft/terminal#2694] opened 2019-09-08 04:49 UTC
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18362.295]
Windows Terminal version :  0.4.2382.0
Input method: the system defaut microsoft pinyin input method.
```

# Steps to reproduce

always.

# Expected behavior
the input method can switch to chinese mode, and can type chinese characters.

# Actual behavior
the input method  is always in english mode, and cannot type chinese characters .

**Comment by j4james** [comment] 2019-09-08 15:10
This sounds like it might be a duplicate of issue #2213.

**Comment by yx91490** [comment] 2019-09-09 08:05
> This sounds like it might be a duplicate of issue #2213.

oh, yes.

**Closed** 2019-09-09 08:05 UTC
Labels: Needs-Tag-Fix, Needs-Triage
