### ISSUE TITLE
Drag tab outside window to create new window (ala chrome/firefox)

### ISSUE THREAD

**Issue by jwlodek** [microsoft/terminal#8598] opened 2020-12-16 16:40 UTC
# Description of the new feature/enhancement

I really enjoy the feature in browsers where I can easily create a new window that holds the current tab by dragging it outside the current window. It would be nice if terminal allowed the same functionality, where dragging a tab outside of the open terminal window creates a new terminal instance with the selected tab. GIF below demonstrates what I mean

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/29227305/102378075-66a89a00-3f93-11eb-9de8-4c66d7596a58.gif)

**Comment by Don-Vito** [comment] 2020-12-16 16:50
@jwlodek - this looks as a duplicate of https://github.com/microsoft/terminal/issues/1256 which is handled as a part of https://github.com/microsoft/terminal/issues/5000

**Comment by zadjii-msft** [comment] 2020-12-16 16:52
Sure is, thanks @Don-Vito 

/dup #1256

**Closed by zadjii-msft** 2020-12-16 16:52 UTC
Labels: Issue-Feature, Needs-Tag-Fix, Needs-Triage
