### ISSUE TITLE
Fullscreen is not working in second screen

### ISSUE THREAD

**Issue by nntantidakis** [microsoft/terminal#1300] opened 2019-06-17 18:25 UTC
# Environment

Windows build number: Microsoft Windows [Version 10.0.18362.175]
Windows Terminal version 0.0.1.0

# Steps to reproduce

I am using 2 screens with the same resolution(1080p). When i drag the terminal to the secondary display, the boundaries gets out of screen. For example see attached photos below

# Expected behavior

This behavior is from my main display
![image](https://user-images.githubusercontent.com/37312505/59627215-5cab9e00-9146-11e9-9334-716d8acf317d.png)

# Actual behavior

This is from my secondary display(notice that everything is dragged outside of my monitor pixels, even the text and some portion of the tabs).
![image](https://user-images.githubusercontent.com/37312505/59627241-6c2ae700-9146-11e9-810c-b80f9a476ad0.png)

**Comment by DHowett-MSFT** [comment] 2019-06-18 00:43
Duplicate of #1055.

**Closed by DHowett-MSFT** 2019-06-18 00:43 UTC
Labels: Needs-Tag-Fix, Needs-Triage
