### ISSUE TITLE
Cannot load PSReadline module..

### ISSUE THREAD

**Issue by Grace2705** [microsoft/terminal#7484] opened 2020-08-31 19:00 UTC
Anytime i open windows terminal i get Cannot load PSReadline module.  Console is running without PSReadline.
I tried runing the Get-Module PSReadline, but it doesn't do anything

**Comment by KalleOlaviNiemitalo** [comment] 2020-09-01 18:56
If you are using Windows Terminal Preview 1.3 and 32-bit PowerShell 5.1, then this could be a duplicate of <https://github.com/microsoft/terminal/issues/7418>.

To confirm, what are the values of the following variables in your PowerShell session?

```
$PSHome
$PSVersionTable
$Env:PSModulePath
```

**Closed** 2020-09-09 07:00 UTC
Labels: Needs-Author-Feedback, Needs-Tag-Fix, Needs-Triage, No-Recent-Activity
