### ISSUE TITLE
Lines of text copied from GitHub Desktop, paste into PowerShell 7.02 WT in reverse order

### ISSUE THREAD

**Issue by ianpottinger** [microsoft/terminal#6719] opened 2020-06-29 23:09 UTC
For instance, copying

      "PerformanceCounters": {
        "scheduledTransferPeriod": "PT1M",
        "PerformanceCounterConfiguration": [
          {
            "counterSpecifier": "\\Processor Information(_Total)\\% Processor Time",
            "sampleRate": "PT1M"

becomes

>>             "sampleRate": "PT1M"
>>             "counterSpecifier": "\\Processor Information(_Total)\\% Processor Time",
>>           {
>>         "PerformanceCounterConfiguration": [
>>         "scheduledTransferPeriod": "PT1M",
>>       "PerformanceCounters": {

**Comment by DHowett** [comment] 2020-06-29 23:15
I believe this is a /dupe of #5821

**Closed by DHowett** 2020-06-29 23:15 UTC
Labels: Needs-Tag-Fix, Needs-Triage
