### ISSUE TITLE
Split window key binding 

### ISSUE THREAD

**Issue by nishp77** [microsoft/terminal#3768] opened 2019-11-28 18:18 UTC
# Environment

Windows build number: 1909
Windows Terminal version (if applicable): v0.7.3291.0

# Steps to reproduce

Just simply start the windows terminal app and make sure that the keybinding for splitting panes horizontally is 'Alt+Shift+-' and vertically 'Alt+Shift+=' 

# Expected behavior

If you use the left Shift key of the keyboard it works but if you use the right Shift key it doesn't work

# Actual behavior

 Both 'Shift' keys should work

**Comment by mdtauk** [comment] 2019-11-28 18:30
Could we get Pane splitting as options in a Right Click menu?

**Comment by j4james** [comment] 2019-11-28 20:53
@nishp77 The inability to recognise the right shift key may be related to issue #337.

@mdtauk That sounds like an unrelated feature request. You should probably raise that as a separate issue, assuming one doesn't already exist.

**Comment by nishp77** [comment] 2019-11-28 21:31
i'm sorry everyone but i never restart my laptop but the issue is solved

**Comment by j4james** [comment] 2019-11-28 22:06
@nishp77 If you can't reproduce it any more, I think you can probably close the issue yourself.

**Closed** 2019-11-29 02:42 UTC
Labels: Needs-Tag-Fix, Needs-Triage, Resolution-No-Repro
