### ISSUE TITLE
Saving settings does not work for fonts.

### ISSUE THREAD

**Issue by 0wwafa** [microsoft/terminal#18029] opened 2024-10-10 22:07 UTC
This is a report of 2 different bugs:

Version 1.21.2701.0

1) go to to settings >> default >> appearance >> Font face

2) if I enable "Show all fonts" and then click the name of the font face,   terminal  CRASHES.

3) If I select any font and the click SAVE, the font rever to the previous one  or to the default.

--- work around ---
I manually edited the settings.json file and it works.

```
    "profiles": 
    {
        "defaults": 
        {
            "font": 
            {
                "face": "Consolas"
            }
        },
        "list": 
        [
            {
                "commandline": "%SystemRoot%\\System32\\cmd.exe",
                "guid": "{0caa0dad-35be-5f56-a8ff-afceeeaa6101}",
                "hidden": false,
                "name": "Command Prompt"
            },
            {
                "font": 
                {
                    "face": "DejaVu Sans Mono",
                    "size": 16
                },
                "guid": "{2c4de342-38b7-51cf-b940-2309a097f518}",
                "hidden": false,
                "name": "Ubuntu",
                "source": "Windows.Terminal.Wsl"
            },
```

So the problem is somewhere else!

**Comment by DHowett** [comment] 2024-10-10 22:58
Thanks! These both have the same root cause, which we've fixed with /dup #17987

**Closed** 2024-10-10 22:59 UTC
Labels: Needs-Tag-Fix
