### ISSUE TITLE
Feature Request: make the terminal be used as external terminal for VS Code

### ISSUE THREAD

**Issue by alt3r3dgd** [microsoft/terminal#2900] opened 2019-09-25 12:39 UTC
# Description of the new feature/enhancement
I want to use WT as an external terminal for VS Code, but when I set it, the terminal just opens without running my programs. Seems like this is not implemented, so yes, why not to implement it?

# Proposed technical implementation details (optional)

**Comment by zadjii-msft** [comment] 2019-09-25 13:06
How does VS launch the terminal? Can you specify your own commandline args for the external terminal?

For the record, this sounds like it's something that'll _just work_ once #607 is implemented. However, I'd like to have some additional detail to make sure that's all that is needed.

**Comment by alt3r3dgd** [comment] 2019-09-25 13:45
> 
> 
> How does VS launch the terminal? Can you specify your own commandline args for the external terminal?
> 
> For the record, this sounds like it's something that'll _just work_ once #607 is implemented. However, I'd like to have some additional detail to make sure that's all that is needed.

Oh, I thought, I needed to only type "wt.exe" into "terminal.external.windowsExec", because the default cmd works without without any args. I'm gonna try it with the args and respond you asap.

**Comment by alt3r3dgd** [comment] 2019-09-25 13:49
Ohh, it doesn't support command line args _(sorry for being so stupid)_
But I tried it with "wt --profile cmd --connection debugger".

**Comment by DHowett-MSFT** [comment] 2019-09-26 04:58
I’m closing this as a duplicate of 607.

**Closed by DHowett-MSFT** 2019-09-26 04:58 UTC
Labels: Issue-Question, Needs-Attention, Needs-Tag-Fix, Needs-Triage
