### ISSUE TITLE
drop-down terminal window with hotkey

### ISSUE THREAD

**Issue by Peterinor** [microsoft/terminal#5576] opened 2020-04-26 04:03 UTC
it's a very nice to make terminal window roll down/up from the top of screen with hotkey like Yakuake(https://kde.org/applications/system/org.kde.yakuake)

**Comment by skyline75489** [comment] 2020-04-26 04:25
Pretty sure this is #653

**Comment by zadjii-msft** [comment] 2020-04-27 13:25
Yep this is definitely a /duplicate of #653. Thanks for helping with the triage @skyline75489 ☺️

**Closed** 2020-04-27 13:27 UTC
Labels: Issue-Feature, Needs-Tag-Fix, Needs-Triage
