### ISSUE TITLE
Holding a command key (Ctrl,Shift,Alt) does not pass through to FAR Manager

### ISSUE THREAD

**Issue by Euan-McVie** [microsoft/terminal#4446] opened 2020-02-03 10:28 UTC
# Environment

```none
Windows build number: 10.0.18363.0
Windows Terminal version (if applicable): 0.8.10261.0
Far Manager v3.0 build 5511 x64 - [Download](https://www.farmanager.com/download.php?l=en)
```

# Steps to reproduce

1. Install Far and add a profile:
```
{
  "guid": "{a6736d6e-1927-48be-8366-0ea3fe505d70}",
  "name": "Far Manager 3 x64",
  "commandline": "C:/Program Files/Far Manager/Far.exe"
},
```
2. Open Far tab in Windows terminal
3. Press and hold one of the command keys (Ctrl or Alt or Shift)
4. Nothing happens

# Expected behavior

Holding one of the command keys changes the visible options displayed to the user along the bottom of the screen. Each option is then selected using the function keys.

No keys pressed:
![image](https://user-images.githubusercontent.com/5442901/73645354-09ec0b80-466f-11ea-8a15-b13214fe5e8e.png)

Ctrl key:
![image](https://user-images.githubusercontent.com/5442901/73645437-34d65f80-466f-11ea-8b8d-4e988a96999f.png)

Shift key:
![image](https://user-images.githubusercontent.com/5442901/73645525-5fc0b380-466f-11ea-82c8-38e47155fc3f.png)

Alt key:
![image](https://user-images.githubusercontent.com/5442901/73645736-cb0a8580-466f-11ea-9c53-8c766c5c7fdf.png)

# Actual behavior

The key presses are ignored so it is not possible to review the options. 
Note that pressing the combination of the command key and function key does correctly result in the action, you just have to memorise all the options.

**Comment by DHowett-MSFT** [comment] 2020-02-03 18:17
Alas, this is also going to be a /dupe of #879.

**Comment by DHowett-MSFT** [comment] 2020-02-03 18:17
#4334 is _very similar_ and was also a duplicate.

**Closed by DHowett-MSFT** 2020-02-03 18:17 UTC
Labels: Needs-Tag-Fix, Needs-Triage

**Comment by unxed** [comment] 2023-04-05 09:03
win32-input-mode support also added to the Linux Far Manager port: https://github.com/elfmz/far2l/pull/1581
