### ISSUE TITLE
Terminal shouldn't be offered as an option in the context menu for Quick Access background

### ISSUE THREAD

**Issue by zadjii-msft** [microsoft/terminal#12578] opened 2022-02-25 14:32 UTC
From MSFT:37831236

> When I right-click on the background of File Explorer "Quick Access," Terminal shouldn't be offered as an option because it doesn't do anything there

Presumably we can filter if we're visible based on the path that was provided to us.

**Comment by zadjii-msft** [comment] 2022-02-25 18:51
From internal mail:


> So, in their `IExplorerCommand::GetState`, I think they could have a check for that against the `IShellItemArray` that gets passed in.

```c++
bool IsFileSystemItem(IShellItem* shellItem)
{
    SFGAOF attributes;
    return (shellItem->GetAttributes(SFGAO_FILESYSTEM, &attributes) == S_OK);
}
```

We may also want to compare notes with MSFT:36909951

**Comment by Shomnipotence** [comment] 2022-02-26 01:56
Open with... dialog cannot choose the All the Apps from Microsoft Store

**Comment by zadjii-msft** [comment] 2022-08-18 11:48
Lol the bot thought that it should comment here because of the revert 😅 

I'm reopening this cause we reverted this to fix #13523. I think there's an OS bug, at least on Windows 11, that doesn't let us know the difference between "My PC" and the desktop background. Both show up with an empty array and a null path from explorer. So that's useless.

**Comment by zadjii-msft** [comment] 2022-08-22 21:42
Upstream issue is now MSFT:41029797

**Comment by leejy12** [comment] 2022-09-07 03:15
Regarding https://github.com/microsoft/terminal/issues/13523 

The reason that "Open in Terminal" isn't shown consistently when desktop is right clicked is that on Windows 11, the default context menu is made of fancy XAML controls, and the Window Class name of the foreground window is sometimes reported as `XamlExplorerHostIslandWindow`, not `Progman` or `WorkerW`.

In `OpenTerminalHere::_GetPathFromExplorer()`, I think we can add an additional check to work around this issue.

```
if (0 == StrCmp(szName, L"WorkerW") ||
    0 == StrCmp(szName, L"Progman") ||
    0 == StrCmp(szName, L"XamlExplorerHostIslandWindow"))
```


From https://github.com/microsoft/terminal/pull/13206#issuecomment-1217094214
> Okay I'm pretty sure this caused #13523. Turns out that there's a non-zero rate of the shell giving us 0 items in the array. I can check for that easy enough, but it seems like still returning ECS_HIDDEN for that results in the menu entry not always appearing for the desktop.
> 
> I'll need to noodle more

Is there a way to reproduce the case where `psiItemArray` is not `nullptr` but `psiItemArray->GetCount` returns 0? (I assume this is why `OpenTerminalHere::GetState()` was crashing often). I've never succeeded in observing this behavior.


Also, the [PR](https://github.com/microsoft/terminal/pull/13206) that originally fixed this issue was reverted in the internal repo, right? Will the revert make its way to this public repo?

**Comment by DHowett** [comment] 2022-09-07 15:40
> Also, the https://github.com/microsoft/terminal/pull/13206 that originally fixed this issue was reverted in the internal repo, right? Will the revert make its way to this public repo?

This PR was made against and merged into the public repository. There is no private/internal copy of the Windows Terminal source -- we handle it all right out here in the open! :smile:

**Comment by leejy12** [comment] 2022-09-07 17:06
> Edited to correct for me having misread your question. The commit that reverts it is https://github.com/microsoft/terminal/commit/2d00432dab82f1d46d8cdc9176d5e3e6f34f753a on release-1.14 and https://github.com/microsoft/terminal/commit/76daf71cf96f81a6e0589bdef4f01d325c7e7847 on release-1.15. We kept it on in main so we could have builds to repro the issue with.

Thanks for the clarification!

> Good find on the `Xaml...Window` thing! Do you think that the rest of the explorer lookup logic will work with that HWND as well?

I think so. Even when the context menu is open in Explorer, the foreground window's class name is always reported as `CabinetWClass`.

**Closed** 2022-09-21 17:41 UTC
Labels: Help Wanted, Issue-Bug, Product-Terminal, In-PR, Priority-3, Area-ShellExtension
