### ISSUE TITLE
Show up Administer: at some place when terminal starts with Administer mode

### ISSUE THREAD

**Issue by SJang1** [microsoft/terminal#2396] opened 2019-08-12 02:16 UTC
Terminal ver. 0.3.2171.0

When setted a tab title, even if terminal is on Administer Mode, I couldn't know of this is an Administer mode or not.

It had Administer: at the front of the title of the tab when there is no tabtitle settings, somewhere needs to show up that Terminal is on Administer Mode.

**Comment by zadjii-msft** [comment] 2019-08-12 12:33
That's just how `tabTitle` works unfortunately. It's going to override whatever the console application wants to set it to, because the console application is responsible for the "Administrator" bit, not the Terminal application.

* This will likely be improved by #2373
* Having a dynamically-formatted title is #1320 
* Having some of UI element to indicate the terminal is elevated is #1939 

So I'm gonna close this as a collective dupe of those 3.

**Closed by zadjii-msft** 2019-08-12 12:33 UTC
Labels: Needs-Tag-Fix, Needs-Triage
