### ISSUE TITLE
Can't paste into to Terminal from Cloud Clipboard

### ISSUE THREAD

**Issue by gulshanmudgal** [microsoft/terminal#4184] opened 2020-01-12 07:10 UTC
# Environment

```none
Windows build number: Windows 10 V1909(Build No: 18363.535)
Windows Terminal version (if applicable): V 0.7

Any other software?
```

# Steps to reproduce
1. Copy text from an app/window using <kbd>CTRL</kbd>+<kbd>C</kbd>
1. Open Windows Terminal and select a Cmd/Ubuntu profile
1. Hit <kbd>WIN</kbd>+<kbd>V</kbd> to paste text from Cloud Clipboard
1. Cloud Clipboard's text entry selection window appears
1. Select a text entry (e.g. previously copied text) to paste into Terminal

# Expected behavior
The selected entry's text is pasted into Terminal

# Actual behavior
* CMD: `^V` is pasted
* Ubuntu: No text, or `^V` is pasted

> Note: This works in PowerShell 7.0!

**Comment by zadjii-msft** [comment] 2020-01-13 15:45
This bug makes me cry.

I've been trying for a while now to get a more universal way of getting the cloud clipboard (the <kbd>win+v</kbd> dialog) to work with applications. Right now, it literally just sends a <kbd>ctrl+v</kbd> keystroke to the target window. If for whatever reason <kbd>ctrl+v</kbd> isn't the keybinding for paste in that application, then the cloud clipboard simply doesn't work. Case in point: running `wsl` in `conhost.exe`, that just doesn't work with the cloud clipboard. 

It doesn't look like there's a dupe for this issue so I'll leave it open. Also related is #322. Also, cc @bitcrazed

**Comment by bitcrazed** [comment] 2020-01-13 20:23
I'll re-awaken that thread with the Cloud Clipboard team.

**Comment by bitcrazed** [comment] 2020-01-13 20:38
Updated @gulshanmudgal's description to be a little more thorough and accurate

**Comment by DHowett-MSFT** [comment] 2020-01-13 20:55
On second thought, we're going to make this one a /dupe of #322. It's easier for us to track this way. Thanks!

**Closed by DHowett-MSFT** 2020-01-13 20:55 UTC
Labels: Area-User Interface, Issue-Bug, Priority-3, Product-Terminal
