### ISSUE TITLE
Option to disable ctrl + scroll => change font size

### ISSUE THREAD

**Issue by autoantwort** [microsoft/terminal#5708] opened 2020-05-02 23:47 UTC
# Description of the new feature/enhancement
Add a option to disable ctrl + scroll => change font size. I use Windows Terminal from a mac with remote desktop. When I scroll the scrolling always have inertia, so when I scroll to the end of the terminal the scrolling will continue for a short time in the background. When I then want to kill the program with `ctrl + c` I change the font size...

# Proposed technical implementation details (optional)
Add a option to the settings where I can disable ctrl + scroll => change font size (from my experience this is always not usable when using a touchpad, so maybe disable that by default when a user uses a touchpad)

**Comment by j4james** [comment] 2020-05-03 01:12
This is possibly a duplicate of #3793.

**Comment by autoantwort** [comment] 2020-05-03 11:07
> This is possibly a duplicate of #3793.

Yeah its similar. There the application sets the `ENABLE_EXTENDED_FLAGS` and the `ENABLE_MOUSE_INPUT`Flag. I always want to turn off this change font size feature via a setting, not only when these flags are enabled. If this is what he want, than this is a duplicate.

**Comment by zadjii-msft** [comment] 2020-05-04 14:13
It's either a dup of #3793, or possibly more closely a dupe of #1553. One way or another, this is something that we're already tracking. Thanks for the report!

/dup #1553

**Closed by zadjii-msft** 2020-05-04 14:13 UTC
Labels: Issue-Feature, Needs-Tag-Fix, Needs-Triage
