### ISSUE TITLE
RightAlt-letter on Czech keyboard doesn't work

### ISSUE THREAD

**Issue by tomasherceg** [microsoft/terminal#820] opened 2019-05-15 13:01 UTC
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
10.0.18362.113

* What you're doing and what's happening: (Copy & paste specific commands and their output, or include screenshots)
I am using the Czech keyboard. We write some characters like `|` by pressing `RightAlt-W`. There are more characters like that, all are accessible using Right Alt.

* What's wrong / what should be happening instead:
When I press the shortcut, no character is written in the output.

**Comment by mKay00** [comment] 2019-05-15 13:07
Duplicate of #521

**Closed** 2019-05-16 21:55 UTC
Labels: Resolution-Duplicate
