### ISSUE TITLE
can not type into terminal and settings from menu opens stardog studio

### ISSUE THREAD

**Issue by mxdog** [microsoft/terminal#7481] opened 2020-08-31 14:12 UTC
NOTE : the core issue here is the key conflict  ( ctrl + ) to open settings  I only report the keyboard because i see another one down the list ..so is a confirmation if nothing else 

# Environment

Windows build number: Microsoft Windows [Version 10.0.19041.450]
Windows Terminal version (if applicable):1.3.2382.0
the keyboard is using an pc/2 port and not an usb if that could be an issue but does work in all other apps and terminals i.e. cmd and powersehell  and wsl 

Any other software?
Stardog Studio  for some reason when using the settings menu/settings .......stardog studio opens with a settings tab and then i get a  telemetry warning popup and a java error when i click the link for preferences  ( pretty sure thats all stardog stuff ) the SD server is disabled so I am not sure what or how that DB admin program is getting opened ? 

# Steps to reproduce
open terminal program
try to type 
from menu/down-arrow/open settings another app opens 

# Expected behavior
for keyboard to work in app,
get the terminal settings dialog and not a random program opening 
as a note stardog studio does have a hotkey ctrl+ to open the preferences tab in THAT program.

# Actual behavior
no text or keyboard input to program
stardog studio opens

**Comment by WSLUser** [comment] 2020-08-31 14:58
You need to switch your default json editor. At worst, that means Notepad, which is default if nothing else that handles json is installed. You could also try a text editor such as Notepad ++, VSCode, CodeWriter, etc. or an IDE (will be slower to load up) such as Visual Studio. You can configure the default json editor in Settings - Apps - App Execution Aliases.

**Comment by skyline75489** [comment] 2020-09-01 08:51
Sadly there's currently no such thing as ` terminal settings dialog`. You can subscribe to #1564 if you are interested. Until that's done, the default text editor for JSON would be used for editing settings.

**Comment by mxdog** [comment] 2020-09-01 16:51
Ok... the menu/settings opening starlabs thing was just the app opening a .json like WSLUser pointed out.  I did not think of that at the time ( no clue what was going on ) 

And the other issue ( keyboard not working in terminal ) is already reported in another post.  but if anyone needs any info let me know

**Comment by DHowett** [comment] 2020-09-02 23:36
Thanks for the confirmations! I'll close this as a /duplicate of #1564 for the settings dialog and #4448 for the keyboard problem.

**Closed by DHowett** 2020-09-02 23:36 UTC
Labels: Needs-Tag-Fix, Needs-Triage
