### ISSUE TITLE
偶发的中文显示异常

### ISSUE THREAD

**Issue by zhixiangjoy** [microsoft/terminal#3812] opened 2019-12-03 03:14 UTC
# Environment

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Windows Terminal version (if applicable):

Any other software?
```
```
Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.18363.0 Microsoft Windows NT 10.0.18363.0
```

# Steps to reproduce

# Expected behavior

```
# background
可以使用selectionBackground（在配置文件级别）（＃3471）设置所选内容的背景色
```
# Actual behavior

As shown below. (forgive my pool english)
When I use vim eidt a text in windows terminal(Version: 0.7.3291.0
), input the follow text.In some cases, an exception is triggered. The chinese font size is not correct. 
![terminal](https://user-images.githubusercontent.com/15685217/70017393-ed274f00-15bd-11ea-822e-2ba2fe29a14c.gif)

**Comment by mkitzan** [comment] 2019-12-03 04:17
This behavior is so strange. There's a duplicate issue tracking this bug #2191

**Comment by zadjii-msft** [comment] 2019-12-03 13:54
Huh. that certainly is odd. I'd frankly be _shocked_ if this wasn't the same root cause as #2191, since they're generally manifesting in the same way. I'm going to close this as a dupe but thanks for the report!

/dup #2191

**Closed by zadjii-msft** 2019-12-03 13:54 UTC
Labels: Needs-Tag-Fix, Needs-Triage

**Comment by transtone** [comment] 2019-12-08 13:10
根本不是偶发，也不只是中文会这样。一行里的文字过长，字体就会变的很小。

![image](https://user-images.githubusercontent.com/46688/70389780-08032480-19ff-11ea-8c4f-f8763e90c824.png)
