### ISSUE TITLE
Pasting to tab title leaking to terminal input

### ISSUE THREAD

**Issue by pszlazak** [microsoft/terminal#16205] opened 2023-10-20 20:25 UTC
### Windows Terminal version

1.18.2822.0

### Windows build number

10.0.22621.0

### Other Software

N/A

### Steps to reproduce

* copy some text to the clipboard
* paste it to tab tile **using keyboard shortcut** `Ctrl+v`

### Expected Behavior

Clipboard content pasted only to tab title.

### Actual Behavior

Clipboard content will be pasted to tab title and to terminal input as shown here: https://i.imgur.com/UlFcGNe.gif

Remark: if clipboard is pasted using right click and context menu, it works OK.

**Comment by Shivansh20128** [comment] 2023-10-21 07:50
Hi  @pszlazak,
The issue you are talking about is not a bug but rather a feature to make things easier for developers.  the behavior you described is due to a feature called "injection" in Windows Terminal. This feature allows you to paste text into the title bar and automatically sends that text to the command prompt as well. It's designed to make it convenient for users to rename the terminal while also executing a command.
As you said, if the clipboard is pasted using the right-click and context menu, it works fine.
However, if you want to use keyboard shortcut keys, here is a way to avoid pasting clipboard text at both places:

1. Click on the down arrow in the title bar and select "Settings." You should be able to find a "Settings.json" file.
2. Inside the file, you should be able to find
{
            "command": "paste",
            "keys": "ctrl+v"
}
in the "actions" key.
3. This setting defines the shortcut to paste inside the terminal. Since Windows also pastes the clipboard text using Ctrl+v, when some text is pasted into the terminal title using Ctrl+v, it gets pasted into the title due to Windows-defined settings as well as inside the terminal due to the setting defined in this "Settings.json" file.
4. To avoid pasting text at both places, modify this file and change the shortcut key from "ctrl+v" to some other key combination that does not clash with any other shortcut keys. 
5. Save the file and close and open the terminal again.

You should now be able to paste the copied text into the terminal title using "ctrl+v" and into the terminal using the new key combination you defined in the "Settings.json" file.
Thank You

**Comment by pszlazak** [comment] 2023-10-22 19:39
If this is a feature it became present in [v1.12.10334.0](https://github.com/microsoft/terminal/releases/tag/v1.12.10334.0). Earlier it was not there. This is the first stable version of v1.12.
Previous released preview version [v1.12.3472.0](https://github.com/microsoft/terminal/releases/download/v1.12.3472.0/Microsoft.WindowsTerminalPreview_1.12.3472.0_8wekyb3d8bbwe.msixbundle) still does not have this feature.

I don't see this feature being announced in release notes of [v1.12.10334.0](https://github.com/microsoft/terminal/releases/tag/v1.12.10334.0).

It was added by one of following commits: https://github.com/microsoft/terminal/compare/v1.12.3472.0...v1.12.10334.0

**Comment by Shivansh20128** [comment] 2023-10-23 19:00
Okay. It may be a bug.
But I still feel that the current behavior is obvious because when we select the title, we are also selecting the whole terminal. And then when we press Ctrl+v, the text gets pasted in the title because of the default setting of the operating system, as well as inside the terminal because of the setting we have defined in the Settings.json file for the terminal.

**Comment by zadjii-msft** [comment] 2023-10-24 14:00
I'm certain this isn't by design. Pretty sure #14669 has a fix for this, which should be tracked in /dup #14381. Thanks!

**Closed by zadjii-msft** 2023-10-24 14:00 UTC
Labels: Issue-Bug, Needs-Triage
