### ISSUE TITLE
Lost history

### ISSUE THREAD

**Issue by KanDisheng** [microsoft/terminal#3163] opened 2019-10-12 04:47 UTC
# Environment

```none
Windows build number: 10.0.18362.0
Windows Terminal version: 0.5.2762.0
```

# Steps to reproduce

Just keep typing.

# Expected behavior

Keep the history.

# Actual behavior

Lost the history. See the GIF file:

![terminal](https://user-images.githubusercontent.com/1520283/66694992-812b1780-eced-11e9-891b-da2042021203.gif)

**Comment by DHowett-MSFT** [comment] 2019-10-14 20:45
This is actually a duplicate of PowerShell/PSReadline#724.

**Closed by DHowett-MSFT** 2019-10-14 20:45 UTC
Labels: Needs-Tag-Fix, Needs-Triage
