### ISSUE TITLE
Not responding trying to close an connected ssh tag

### ISSUE THREAD

**Issue by LasSino** [microsoft/terminal#2093] opened 2019-07-25 14:24 UTC
# Environment

```none
Windows build number: [版本 10.0.18362.239]
Windows Terminal version (if applicable):Windows Terminal (Preview) Version: 0.2.1831.0 (Microsoft Store build)

Any other software?
OpenSSH client: OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5
```
# Steps to reproduce

1.Start an ssh session in a tab(current or new would do) with RSA certificate identification.
2.Close the tab while the ssh is still connected.

# Expected behavior

The tab should be closed.

# Actual behavior

The Terminal stops responding and then the typical Windows messagebox for 
![Annotation 2019-07-25 222312](https://user-images.githubusercontent.com/34049745/61882333-e2cbb900-af2a-11e9-9cc3-09088a59fcd5.jpg)
unresponding apps will show.

**Comment by zadjii-msft** [comment] 2019-07-25 14:29
This looks like a dupe of #1445 to me

**Comment by LasSino** [comment] 2019-07-25 14:43
> This looks like a dupe of #1445 to me

Well, the behaviors aren't identical.
The problem you mentioned concerns closing the old tab, but in this case it's closing the current tab.
And a subtle feature in the case is that a ssh session **logged in with password** can be correctly closed, but a ssh session **with RSA certificate** will cause the problem.

Maybe they share the same defected code actually, but I'm not totally inside of this.
Anyway thanks and hope you go smooth debugging！

**Closed** 2019-07-26 15:01 UTC
Labels: Needs-Triage, Resolution-Duplicate
