### ISSUE TITLE
Can quit git diff after the first page

### ISSUE THREAD

**Issue by metin** [microsoft/terminal#3828] opened 2019-12-04 05:31 UTC
It gets stuck when hitting `q` in the middle of a `git diff` operation. It is fine if I quit in the first page. It is also fine if I keep paginating until end of the diff.

# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18362.476]
Windows Terminal version (if applicable):   0.7.3291.0


Any other software?
Git for windows: git version 2.24.0.windows.2

```

# Steps to reproduce

1. `cd` to any git repository that has as much changes as it could cause pagination.
2. type `git diff` and you should see something like this. at this stage you could quit by typing `q`

![image](https://user-images.githubusercontent.com/28767/70231765-079f2b00-176c-11ea-9633-103b1e30dd94.png)

3. Hit space to go to next page
4. Hit `q` and it will get stuck and never quit 
![image](https://user-images.githubusercontent.com/28767/70231693-df173100-176b-11ea-87a7-0629c4dad4d2.png)

# Expected behavior

It shoul always quit from diff even I am in the middle.
# Actual behavior
It gets stuck if I hit `q` in the middle of diff

**Comment by DHowett-MSFT** [comment] 2019-12-04 19:25
And just to confirm, this _does not_ happen when you're using a standard `cmd` window?

**Comment by metin** [comment] 2019-12-05 05:07
@DHowett-MSFT correct. standard `cmd` is just fine

**Comment by egmontkob** [comment] 2019-12-05 09:29
@metin Offtopic comment:

I couldn't help but notice that the screenshots contain "com.accenture.[...]", suggesting that perhaps you show tiny fragments of company confidential source code. If that's the case, no matter how tiny and probably unusable this code on its own is, you'd probably better replace them by showing some open source code fragment (e.g. Windows Terminal's source, diffing between two existing commits – which could even help Microsoft developers reproduce the issue).

If you show public source code then ignore this message and sorry for the noise.

I'm deleting this very comment now.

**Comment by DHowett-MSFT** [comment] 2019-12-05 20:50
None of us can reproduce this, which is curious. I've tagged it up with Needs-Repro.

**Comment by metin** [comment] 2019-12-23 08:48
Looks like it was related to the version of git. Just upgraded to a newer version and looks like it works
This is the version I am using.
```
git version 2.24.1.windows.2
```

**Comment by DHowett-MSFT** [comment] 2019-12-23 09:09
Great, thanks for following up! I’ll close this for now.

**Closed by DHowett-MSFT** 2019-12-23 09:09 UTC
Labels: Area-TerminalControl, Help-Wanted, Issue-Bug, Needs-Repro, Product-Terminal

**Comment by JohnCgp** [comment] 2022-07-11 08:38
I started getting this recently with `git version 2.27.0.windows.1`, haven't consciously updated. A workaround I've found is <kbd>Shift</kbd>+<kbd>Q</kbd>, courtesy of [this SO answer](https://stackoverflow.com/a/17718995).

**Comment by zakeryooo** [comment] 2022-07-28 09:04
@JohnCgp did you ever manage to work out what was causing this for you? I don't know of a consistent way to reproduce it but about 30% of the time I can't quit a git diff in terminal.

**Comment by JohnCgp** [comment] 2022-07-28 09:06
No, not yet, and it's very frustrating. If I'm doing a lot of diffing I end up opening `gitk` after the third tab hangs.

**Comment by zakeryooo** [comment] 2022-07-28 09:44
That's unfortunate. I've had this problem for months, and as you say, it's really frustrating, you can force quit out with CTRL + Pause but then git diff is broken for the rest of the session. 

Surprised more people aren't having this issue... it happens on all 3 of my dev machines, even on a fresh Windows install with only git / terminal installed. I ended up resorting to a 3rd party diff/merge tool, I'd prefer to use the default console one but this bug messes with my workflow

**Comment by zadjii-msft** [comment] 2022-07-28 11:57
Last time we saw this, it was related to the git version. I suspect this is a regression upstream, in msys (probably? I don't fully understand the dependency chain from msys->git). Anyone look for issues on their issue tracker?

**Comment by JohnCgp** [comment] 2022-07-29 07:46
> Last time we saw this, it was related to the git version.  I suspect this is a regression upstream, in msys

The issue I'm encountering isn't Git related. It started happening to me on Git 2.27.0, which I installed in 2020, from one day to the next. My Git installation is manually managed by myself, but my organization pushes Windows updates to my computer - I suspect it's a regression via Windows update. It happens in Command Prompt, Terminal, and regular PowerShell (5.1).

**Comment by bdun** [comment] 2022-10-01 20:07
This looks like a new windows 10 issue.  This started occurring after a windows update.

If I kill the git process in task manager and then try `git diff` again then this time it locks up from the start as well as all other commands.

```
git --version
git version 2.36.1.windows.1
```

Same issue in power shell, and cmd prompt, in both VScode and terminal.

**Comment by saste** [comment] 2023-05-07 12:24
Occurring here as well, after a windows update.
```
PS> git --version
git version 2.40.1.windows.1

PS> [System.Environment]::OSVersion.Version

Major  Minor  Build  Revision
-----  -----  -----  --------
10     0      19045  0
```

Previousely I was using an older git version, updated with the hope to fix the issue. Also the SHIFT+q workaround does not work (what I do is to kill the tab and create a new one).

**Comment by saste** [comment] 2023-05-08 08:08
From this thread:
https://groups.google.com/g/git-for-windows/c/hHzDoeVLHSI

it looks like the issue might be related to third party software interfering with the git/shell communication.

**Comment by alberto-ingenito** [comment] 2024-07-18 13:48
Anyone is still experiencing the same problem in Win 11? I am using last Git version

**Comment by JohnCgp** [comment] 2024-12-06 11:00
Following up after a couple of years (!) My machine was upgraded to Windows 11 and I haven't encountered this issue since.

> From this thread: https://groups.google.com/g/git-for-windows/c/hHzDoeVLHSI
> 
> it looks like the issue might be related to third party software interfering with the git/shell communication.

This seems the likely root issue. I suspect the third party security software on my machine has had updates to it which no longer cause the freezing.
