### ISSUE TITLE
版本升级(0.11.1121.0)之后，凭什么把我的默认终端改成PowerShell

### ISSUE THREAD

**Issue by hd19861028** [microsoft/terminal#5521] opened 2020-04-24 04:17 UTC
# Environment

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Windows Terminal version (if applicable):

Any other software?
```

# Steps to reproduce

# Expected behavior

# Actual behavior

**Comment by hd19861028** [comment] 2020-04-24 04:18
Environment
Microsoft Windows [版本 10.0.18363.720]

**Comment by dexjq23** [comment] 2020-04-24 06:12
Duplicate of #5458

**Comment by DHowett-MSFT** [comment] 2020-04-24 06:29
Thank you @dexjq23 

/dup #5458

**Closed by DHowett-MSFT** 2020-04-24 06:30 UTC
Labels: Needs-Tag-Fix, Needs-Triage
