### ISSUE TITLE
[1.21.1094 Canary] Terminal hangs and crashes when closed.

### ISSUE THREAD

**Issue by AvogatoWizardWhisker** [microsoft/terminal#17112] opened 2024-04-23 18:45 UTC
### Windows Terminal version

1.21.1094

### Windows build number

10.0.26200.5001

### Steps to reproduce

- Open Terminal.
- Do so work with the command linen with multiple tabs open.
- Close window.

https://github.com/microsoft/terminal/assets/89489853/a87d0331-e845-483d-b36c-9f5c86b5b5b8

### Expected Behavior

Terminal with multiple or single tabs should close normally.

### Actual Behavior

At a rare circumstance, Terminal hangs for a moment then crashes. The following files are my current for Terminal Canary. I hope that helps.

[state.json](https://github.com/microsoft/terminal/files/15081395/state.json)

[settings.json](https://github.com/microsoft/terminal/files/15081394/settings.json)

**Comment by carlos-zamora** [comment] 2024-04-25 20:55
Thanks for filing! Even if you can't reproduce it on demand, can you file feedback via feedback hub for us just to get it in the system /?

**Comment by AvogatoWizardWhisker** [comment] 2024-04-25 21:02
Certainly. Although the build has now been updated to version `1.21.1153.0`, it's unclear if the issue still exists. I'll go ahead and report this in the Feedback Hub regardless.

**Comment by carlos-zamora** [comment] 2024-05-01 21:15
Cool! Sorry to do this a week late, but when you do, can you share that feedback hub link with us? Thanks!

**Comment by AvogatoWizardWhisker** [comment] 2024-05-03 10:21
Sure thing
https://aka.ms/AAq9yye

![image](https://github.com/microsoft/terminal/assets/89489853/a2022738-8940-4eaf-b8db-91b456bb45ef)

**Comment by lhecker** [comment] 2024-05-03 14:26
Do you remember when the crash happened last time and how do you know that it was a crash? Unless I'm mistaken, there aren't any Windows Terminal crash reports for your device, nor anything related inside your feedback data that indicates a Windows Terminal crashed in recent times.
(If anyone else on the team got time, it'd be nice if you could double check me.)

**Comment by AvogatoWizardWhisker** [comment] 2024-05-03 16:51
I first experienced this crash issue since 20th April. It was indeed a crash right after i checked in Windows' Reliability History. I wanted to send a dump file or anything containing errors and such but it didn't generate any file. 

![image](https://github.com/microsoft/terminal/assets/89489853/e74b1bd2-bcbd-4da6-8fb8-34dd9c496f64)

Same story with Event Viewer
![image](https://github.com/microsoft/terminal/assets/89489853/7897df38-109c-4a30-9a1f-19448590e33a)

**Comment by carlos-zamora** [comment] 2024-05-08 21:40
> I'm now in version 1.21.1201.0. For now, the terminal doesn't crash at close. It appears it has been fixed. Especially with the duplicate tab issue mentioned.

Great! Thanks for working with us. Closing since it appears fixed 😊

**Closed by carlos-zamora** 2024-05-08 21:40 UTC
Labels: Issue-Bug, Severity-Crash, Needs-Triage, Needs-Attention
