### ISSUE TITLE
Add the ability to move between splits with only ctrl + tab

### ISSUE THREAD

**Issue by yassinebridi** [microsoft/terminal#4302] opened 2020-01-20 03:38 UTC
# Description of the new feature/enhancement
The ability to move between terminal splits with only ctrl + tab(Terminator style)

# Proposed technical implementation details (optional)

**Comment by j4james** [comment] 2020-01-20 21:44
Isn't this a duplicate of #2871?

**Comment by DHowett-MSFT** [comment] 2020-01-21 08:29
It sure is! Thanks. /dup #2871

**Closed by DHowett-MSFT** 2020-01-21 08:29 UTC
Labels: Area-User Interface, Issue-Task, Needs-Triage, Product-Terminal
