### ISSUE TITLE
Tab element can be focused instead of shell

### ISSUE THREAD

**Issue by AeliusSaionji** [microsoft/terminal#5980] opened 2020-05-19 03:33 UTC
# Environment

```none
Windows build number: 10.0.18363.0
Windows Terminal version (if applicable):  0.11.1333.0
```

# Issue

The terminal's tab element is allowed to have focus, thus taking focus away from the shell. I'm not sure if this serves any purpose, but I somehow trigger this state often. Ideally, the tab element just should not be allowed to take focus away from the shell.

# Reproduce

Click on the active tab. Now, you cannot type into the shell, until you click the element containing the shell.

Thank you!

**Comment by DHowett** [comment] 2020-05-19 06:23
> I'm not sure if this serves any purpose

Being able to place focus into the tab strip is important for accessibility and screen readers!

At the same time, this is a /dupe of #3609 which we want to fix :smile:

**Closed by DHowett** 2020-05-19 06:23 UTC
Labels: Needs-Tag-Fix, Needs-Triage
