### ISSUE TITLE
Windows Terminal appears in the wrong language

### ISSUE THREAD

**Issue by theking2** [microsoft/terminal#12075] opened 2021-12-31 17:26 UTC
### Windows Terminal version

Version: 1.11.3471.0

### Windows build number

22000.376

### Steps to reproduce

On an English language system set the region to a non regional format for instance German (Switzerland)

### Expected Behavior

Windows Terminal follows the system language

### Actual Behavior

Windows Terminal appears in German. All other OS-relevant UI (Start menu, Settings etc.) is still in English.

See this: [Get operating system language in c#](https://stackoverflow.com/questions/5710127/get-operating-system-language-in-c-sharp/27642206#27642206)

**Comment by 237dmitry** [comment] 2021-12-31 17:44
![Screenshot 2021-12-31 204312](https://user-images.githubusercontent.com/78153320/147834404-d47516f5-2850-457c-9186-6731e90bf74a.png)

**Comment by theking2** [comment] 2022-01-01 08:23
Thanks, but system default would be English in my case, wouldn't it?.

**Comment by theking2** [comment] 2022-01-01 08:53
In my case:

Installed Culture Info: en-US
Current UI Culture Info: en-US
Current Culture Info: de-CH

To be in sync with the rest of the OS it would make most sense to choose Current UI Culture.

**Comment by 237dmitry** [comment] 2022-01-01 09:48
There is the list to choose UI-language.

**Comment by theking2** [comment] 2022-01-02 07:37
Sure. I should rephrase: "System language" is not correctly establish. It used Current Culture where Current UI culture would be more appropriate.

**Comment by 237dmitry** [comment] 2022-01-02 13:49
> "System language" is not correctly establish.

I think it depends on the version of Windows, more precisely on the language of the system that was chosen at the stage of downloading the image file. For example, I installed the English version, but then I chose my native culture (datetime format, currency, numbers). Not because I like English, but the UI is better displayed than translated one, this is my personal opinion.

**Comment by zadjii-msft** [comment] 2022-01-03 12:03
Part of this is the fact that the Termnial isn't translated to de-CH. I believe we do have a de-DE translation, which I would have _assumed_ that the OS would have picked before falling back to en-US, but I might be wrong there. Lemme pull up the mail thread from a few months back. 

See also #10667

**Comment by zadjii-msft** [comment] 2022-01-03 12:07
Oh actually, this might just be a /duplicate of #9466

> This is a weird and specific issue with language fallback that I don't totally understand.
> 
> The resource loader takes a set intersection of the user's preferred languages and the application's supported languages. When it does that, it is **very** specific and will only choose languages with a matching country code.
> 
> There's no automatic fallback from en_GB to en_US. I also don't know if it would fall back from en_GB to just `en`. :|


Presumably, same deal for `de_CH` not falling back to `de_DE` 😕

**Closed by zadjii-msft** 2022-01-03 12:07 UTC
Labels: Needs-Triage, Needs-Tag-Fix
