### ISSUE TITLE
Black background in WSL when running `less` command

### ISSUE THREAD

**Issue by luckytoilet** [microsoft/terminal#3951] opened 2019-12-13 05:39 UTC
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18363.476]
```

# Steps to reproduce

1. Open `bash`
2. Run `less some-file.txt`
3. Scroll down a few lines
4. Scroll back up a few lines

# Expected behavior

`less` works normally:

![image](https://user-images.githubusercontent.com/123435/70771947-f7c1b100-1d40-11ea-95d7-4c233983d93d.png)

# Actual behavior

The background is black when I scroll up:

![image](https://user-images.githubusercontent.com/123435/70771631-c98fa180-1d3f-11ea-95d6-403b7c9868a6.png)

**Comment by j4james** [comment] 2019-12-14 13:36
Assuming you've got that black on white color scheme by changing the default foreground and background colors, then this issue was probably fixed by PR #2987 - the fix is just not available in the main Windows build yet. I can reproduce the problem when using the conhost build that comes with Windows, but it's fixed when testing a version built from the latest source.

Bottom line is this is probably a duplicate of #832 / #2702.

**Comment by DHowett-MSFT** [comment] 2019-12-16 20:40
Thanks @j4james! I'm gonna close this as a /dupe of #2702.

**Closed by DHowett-MSFT** 2019-12-16 20:41 UTC
Labels: Area-VT, Issue-Bug, Needs-Triage, Priority-3, Product-Conhost

**Comment by pothitos** [comment] 2021-07-09 14:31
A simple workaround is to set in the `Properties` window to set the `Colors` > `Screen Background` to be the same with the `Terminal` > `Use Separate Background` color. You may need to temporarily set the corresponding checkbox to set the latter color.
