### ISSUE TITLE
Undercurl color separator inconsistent

### ISSUE THREAD

**Issue by matrdr** [microsoft/terminal#18000] opened 2024-10-06 09:41 UTC
### Windows Terminal version

1.23.2701.0, also 1.20.11781.0

### Steps to reproduce

Open WSL.
Try the following commands:
```
echo -e "Text is \e[38:2::255:0:0m\e[58:2::0:255:0m\e[4:3mundercurled\e[59m\e[4;0m."
```
```
echo -e "Text is \e[38;2;255;0;0m\e[58:2::0:255:0m\e[4:3mundercurled\e[59m\e[4;0m."
```
```
echo -e "Text is \e[38;2;255;0;0m\e[58;2;0;255;0m\e[4:3mundercurled\e[59m\e[4;0m."
```

You will see that the first two commands set the text color to red and the underline color to green. But the final command does not.

![image](https://github.com/user-attachments/assets/49d000a4-f5c2-46e1-8238-00589b8d443a)

### Expected Behavior

I would expect the way that I set color to the text or to the underline work in the same way.

### Actual Behavior

Setting the text color with the `\e[38` escape sequence takes the RGB color option separated by colons as well as semicolons. For the underline color only the colon option seems to work.

The documentation only mentions the semicolon option (the one that does not work for underline).

I compared this to the behavior of the xfce4-terminal. This one prints red text with green undercurl for all three commands.

**Comment by DHowett** [comment] 2024-10-06 13:18
Thanks! This is a /duplicate of #17426

**Comment by DHowett** [comment] 2024-10-06 13:19
Maybe that didn’t trigger the bot. Let’s try again.

/dup #17426

**Closed** 2024-10-06 13:19 UTC
Labels: Issue-Bug
