### ISSUE TITLE
Mouse wheel doesn't scroll when terminal launched as "ubuntu"

### ISSUE THREAD

**Issue by wigster** [microsoft/terminal#137] opened 2018-03-15 12:37 UTC
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
16299.309

* What you're doing and what's happening: (Copy & paste specific commands and their output, or include screen shots)

- Launch wsl terminal as Ubuntu from Start Menu
- output anything longer than the terminal window.
- try scrolling with mouse wheel

* What's wrong / what should be happening instead:

The view does not scroll up. If I launch cmd/powershell first and then Ubuntu, scrolling works as it should. Also dragging with the scroll bar works fine.

**Comment by wigster** [comment] 2018-03-15 15:25
Edit: I've just discovered scrolling works when the console window is *inactive*, but stops to scroll when activated.

**Comment by zadjii-msft** [comment] 2018-03-15 16:47
My guess is that for one reason or another, the buffer height got set to the window height for your ubuntu shortcut. Try changing the "Screen Buffer Height" of the ubuntu command prompt to something like 9001.

![image](https://user-images.githubusercontent.com/18356694/37477746-b0b319e0-2835-11e8-9f2d-e7dff1d3c299.png)
![image](https://user-images.githubusercontent.com/18356694/37477776-bf6b1d66-2835-11e8-90ac-851425b2b562.png)

That should make the scroll bar re-appear.

**Comment by wigster** [comment] 2018-03-15 17:42
The scroll bar is there and I can scroll with it ok. The thing that is broken is scrolling using the *mouse wheel*, but it is only broken if the windows is active.

(The buffer is 3000 lines, so it's ok)

**Comment by zadjii-msft** [comment] 2018-03-15 17:45
What's in your `.bashrc`? Does pressing Ctrl+V (from the prompt), then scrolling echo anything to the input? It sounds like VT mouse mode might have gotten enabled for you.

Curious that the scrolling works when the windos is inactive, that might be a hole in the implementation

**Comment by wigster** [comment] 2018-03-15 18:04
I've not touched .bashrc. It's just

[.bashrc.txt](https://github.com/Microsoft/console/files/1816548/default.bashrc.txt)

Ubuntu straight installed from the Store.

**Comment by zadjii-msft** [comment] 2018-03-15 18:31
Well that's certainly curious. I have no idea why this would be happening. Does opening a mouse mode application like tmux, vim, or screen and closing it fix it? (each one has different steps for enabling mouse-mode).

Or, try executing `echo -e "\033[?1000l\033[?1002l\033[?1005l\033[?1006l"` - that should turn off any mouse mode if it's set.

I don't really know how else to debug this - it's particularly odd in that it happens with a fresh Ubuntu install and a new console window. That makes it particularly hard to recreate.

**Comment by wigster** [comment] 2018-03-19 08:59
Hi,

I've tried the echo command and it didn't fix it. Also running tmux and exiting has no effect.

I will add that the behaviour is the same with the precision touchpad in my surface book: two-finger scroll only works when the window is inactive.

**Comment by zadjii-msft** [comment] 2018-03-19 21:07
Oof. That's not great. I have no idea what's causing this now, sorry :/. 

If anyone can get me steps that can reproduce this problem, that'd be greatly appreciated.

**Comment by jeffreykaufman** [comment] 2018-10-13 22:10
@zadjii-msft I'm having this issue as well - fresh install of Windows 10 Pro, Ubuntu installed directly from the Microsoft Store, and scrolling does not work. It doesn't work in any program that uses the native MS-DOS emulator window.

**Comment by zadjii-msft** [comment] 2018-10-15 15:30
@jeffreykaufman does this only repro for you with active (focused) console windows? 

If you try scrolling with another input method, does it work? For example, does scrolling with the touchscreen work?

Could you post screenshots of the "Properties" pages? Specifically the options and layout pages? You can open them up by right clicking the title bar and selecting "Properties":

![image](https://user-images.githubusercontent.com/18356694/46960954-89a62f00-d054-11e8-99c2-7f89043efcae.png)

**Comment by exal99** [comment] 2018-11-09 16:57
I am having the same problem but strangely enough the scroll wheel works fine as long as I don't have the window selected. But as soon as I bring the window into the foreground the scroll wheel stops working.

**Comment by wigster** [comment] 2018-11-13 09:17
So to update: I am on build 17763.107, Ubuntu 18.04 on Surface Book 2 and this is still happening.

It is possible to scroll with touch (which activates the window), but not with the touchpad or the scroll wheel of an external mouse while the window is active.

 I'm attaching my console properties. 

![ubuntuconsoleprops1](https://user-images.githubusercontent.com/10956987/48402886-00eee180-e72d-11e8-8798-96286e9901fc.jpg)
![ubuntuconsoleprops2](https://user-images.githubusercontent.com/10956987/48402888-00eee180-e72d-11e8-80f0-53838b939732.jpg)

**Comment by exal99** [comment] 2019-01-07 11:34
@wigster Could you please be more specific? Did you delete the entire HKEY_CURRENT_USER/Console/C:_Program Files_...ubuntu.exe?

**Comment by exal99** [comment] 2019-01-07 11:38
Okay I seem to have solved it as well. For me I only had to change the options (I turned QuickEdit Mode on) and then the scrolling worked again. I then turned QuickEdit back off and scrolling still worked.

**Comment by mdizzy** [comment] 2019-09-03 22:01
> Just experienced this issue in the native Ubuntu terminal, as well as a random change of the font size to a much smaller font. Enabling _Quick Edit_ mode restored the scrolling functionality. Doesn't appear to be related to the Terminal app, but no idea why this stopped working.

How do you enable quick edit?

**Comment by coupez** [comment] 2019-09-09 00:04
I cannot scroll in any shell in Windows Terminal. Not Powershell, not CMD, not Ubuntu. I can move up and down using ctrl+shift+arrow up. When I open Powershell or Ubuntu by itself, scrolling works.

**Comment by TeamDman** [comment] 2019-10-06 20:27
Holding shift and scrolling on the window seems to work for me :/

**Comment by AlessandroVol23** [comment] 2019-11-04 14:21
> Just experienced this issue in the native Ubuntu terminal, as well as a random change of the font size to a much smaller font. Enabling _Quick Edit_ mode restored the scrolling functionality. Doesn't appear to be related to the Terminal app, but no idea why this stopped working.

I have the same problem and I am not sure how to enable quick edit. Tried it with setting a Reg Key in `HKEY_CURRENT_USER\Console\C:_Program Files_WindowsApps_CanonicalGroupLimited.Ubuntu18.04.../QuickEdit` with type DWORD -> 1

But it didn't work. 

It works for other shells such as PowerShell.

**Comment by suikki** [comment] 2020-09-01 15:11
I can confirm that disabling quick edit also breaks scrolling. Also why is there no context menu when quick edit mode is not on?

**Comment by zadjii-msft** [comment] 2021-02-09 17:03
Hey so, this looks like it's an understood problem now. Disabling quick edit in the vintage console will break scrolling in WSL (as well as disable the context menu, because that's _what quick edit does_).

That's super weird, but understood, with an easy fix. Re-enable quick-edit mode. I'm gonna close this out. Thanks!

**Closed by zadjii-msft** 2021-02-09 17:03 UTC
Labels: Area-Interaction, Help Wanted, Issue-Bug, Needs-Repro, Product-Conhost

**Comment by suikki** [comment] 2021-02-10 18:54
> (as well as disable the context menu, because that's _what quick edit does_).

What I meant that for me there is no context menu in the Ubuntu terminal regardless if quick edit is enabled or disabled. Normally if I disable quick edit, I can use the context menu. Also enabling quick edit is not a valid fix as I absolutely don't want to use it.

**Comment by Aissam-gif** [comment] 2021-03-01 19:11
Actually none of these changes fixed the problem for me , instead i found that i can scroll with "Fn" key + Arrow(Up or Down) hoping to get any other suggestions  . Thanks !
