### ISSUE TITLE
I modified the custom color scheme, but it doesn’t seem to take effect

### ISSUE THREAD

**Issue by zhaoyankai1996** [microsoft/terminal#9745] opened 2021-04-08 00:20 UTC
### Windows Terminal version (or Windows build number)

1.6.10571.0

### Steps to reproduce

Only the modification did not take effect

### Actual Behavior

Only the modification did not take effect

![4PIAX6_}2%FSFQB~{YA{65B](https://user-images.githubusercontent.com/74690909/113950125-38511200-9843-11eb-9654-bb3ee6a12698.png)
![ZB$X6)ISVIVOFMF`5I1)GY1](https://user-images.githubusercontent.com/74690909/113950144-3f782000-9843-11eb-9e60-e7ac572f382f.png)

**Comment by skyline75489** [comment] 2021-04-08 02:34
Can you add a screenshot of the terminal? Both before & after using the color scheme.

**Comment by zhaoyankai1996** [comment] 2021-04-08 09:25
![B6%U5$%GVV9 @`@} KFAYVQ](https://user-images.githubusercontent.com/74690909/114002182-39a82c00-988f-11eb-8e36-412395ef16ad.png)
It's the same before and after the modification, except for color matching, it seems that other effects can be used!

**Comment by skyline75489** [comment] 2021-04-08 09:56
You should use **colorScheme**, not **colorSchemes**:

```diff
- "colorSchemes": "3024Day",
+ "colorScheme": "3024Day",
```

**Comment by grabthar** [comment] 2021-04-12 21:37
I can confirm the issue on this version 1.6.10571.0
```
            {
                "guid": "{63e31163-583f-5850-9c1e-24e227dd2da9}",
                "hidden": false,
                "name": "PowerShell (dotnet global)",
                "source": "Windows.Terminal.PowershellCore",
                "colorscheme": "Campbell Powershell"
            },
Doesn't apply restarting wt doesn't fix. I still have a black terminal when it should be blue.
Color are only applied by the palette
```

**Comment by skyline75489** [comment] 2021-04-12 23:30
@grabthar the default Campbell theme actually have black background. Try a different color scheme, maybe?

**Comment by grabthar** [comment] 2021-04-13 17:23
This is the "Campbell Powershell" it's blue the "Campbell" is black, i'm not wrong
![image](https://user-images.githubusercontent.com/56052/114594464-90e23e00-9c8d-11eb-824a-d1e6d78ff150.png)

**Comment by zadjii-msft** [comment] 2021-04-13 17:36
@grabthar You've seemingly got a totally different issue than OP. OP's issue was that they were using `colorSchemes` instead of `colorScheme`. 

* Do you have anything in the `defaults` object under `profiles`? 
* Could you try adding a new profile like the following to your settings:
```json
        {
            "name": "PowerShell Test",
            "commandline": "%SystemRoot%\\System32\\WindowsPowerShell\\v1.0\\powershell.exe",
            "colorScheme": "Campbell Powershell"
        },
```

I just want to check if there's something special about your `PowerShell (dotnet global)` profile here, or something broader

**Comment by DHowett** [comment] 2021-04-13 17:46
![image](https://user-images.githubusercontent.com/189190/114597341-47c2c780-9c56-11eb-92d4-acf71f4c8e5a.png)


could it be the lowercase `s` in `Scheme`?

**Comment by grabthar** [comment] 2021-04-13 17:46
This one work it's strange!
This one won't
```
            {
                // Make changes here to the cmd.exe profile.
                "guid": "{0caa0dad-35be-5f56-a8ff-afceeeaa6101}",
                "name": "Invite de commandes",
                "commandline": "cmd.exe",
                "hidden": false,
                "colorScheme": "Campbell Powershell"
            },
```

**Comment by zadjii-msft** [comment] 2021-04-13 17:54
Thanks for following up!

Since both yours and OP's issues are resolved, I'm gonna go ahead and close this issue out.

**Closed by zadjii-msft** 2021-04-13 17:54 UTC
Labels: Needs-Author-Feedback, Needs-Tag-Fix, Needs-Triage
