### ISSUE TITLE
Windows Terminal 1.1 breaks WinCompose input

### ISSUE THREAD

**Issue by mordquist** [microsoft/terminal#7089] opened 2020-07-27 12:17 UTC
# Environment

```none
Windows build number: 10.0.19041.0
Windows Terminal version (if applicable): 1.1.2021.0

Any other software?
Ubuntu 20.04 LTS (WSL2)
WinCompose v0.9.4 (https://github.com/samhocevar/wincompose/releases/tag/v0.9.4)
```

# Steps to reproduce

1. Start WinCompose and Windows Terminal (cmd, powershell, or WSL does not matter)
2. Input any character using the WinCompose compose key
    e.g. `rightAlt` + `o` `a`

# Expected behavior

The correct character ('å' in the above example) is sent to the terminal.

# Actual behavior

Seemingly no character is sent, at least nothing is displayed.

Probably related  to #6309 as setting `"experimental.input.forceVT": true` gives the expected behavior.

**Comment by DHowett** [comment] 2020-07-27 22:08
Huh. This doesn't exactly work in the traditional console either, and it was somewhat of a fluke that it worked in WT. It _should_, though.

This is what I get if I peek at the key events coming out of WC into the traditional console:

```
v 001 0010 002a 0000 ^@   00000010
^ 001 0010 002a 0000 ^@   00000000
v 001 0000 0000 00f6 �    00000000
^ 001 00e7 0000 00f6 �    00000000
^ 001 004f 0018 006f o    00000000
```

and here's what I'm getting over the tap:

`␛[255;0;0;1;16;1_␛[255;0;0;0;16;1_`

that 255 definitely ain't right

**Comment by samhocevar** [comment] 2020-11-26 11:27
So, how should a third-party application send Unicode characters to Windows Terminal if `SendInput()` no longer works by default?

**Comment by lhecker** [comment] 2020-11-26 13:41
As far as I can see, this issue was fixed in #7900. I'll close this issue for now as WinCompose works just fine on my end with the latest WT version.

The good thing is that I now finally understood, why we've been receiving weird key events, containing invalid scan codes, for third party applications employing `SendInput`: WT doesn't correctly use `TranslateMessage(Ex)`.

**Closed by lhecker** 2020-11-26 13:41 UTC
Labels: Area-Input, Issue-Bug, Priority-1, Product-Terminal

**Comment by mordquist** [comment] 2020-11-30 11:15
I can confirm that it works for me as well on Terminal 1.4 even with `"experimental.input.forceVT"` unset.

**Comment by smooth038** [comment] 2023-04-15 20:33
I don't know if maybe this problem got recently reintroduced, but WinCompose currently does not work with any window terminal on my machine (cmd, powershell or windows terminal). When typing `rightAlt` `'` `a`, it just outputs `'a` and the compose key is ignored.

I tried the `"experimental.input.forceVT"` setting, but it doesn't seem to do anything. 

Can anyone else reproduce this?

**Comment by smooth038** [comment] 2023-04-15 21:04
I just found the problem. It didn't work because I was running the terminals in administrator mode, but WinCompose does not have admin privileges. When WinCompose is run as admin, everything works fine.
