### ISSUE TITLE
Passing paramter to wt command to open different tab than default

### ISSUE THREAD

**Issue by 4k3or3et** [microsoft/terminal#3339] opened 2019-10-26 08:09 UTC
Hi Guys

is there a way of passing paramtetr to wt command so Windows Terminal would start with different tab than the default?

For example:

wt {guid}

If not i would like to propose feature request.

Thank you.

**Comment by j4james** [comment] 2019-10-26 17:11
If I've understood you correctly, I think this is essentially the same feature request as #607.

**Comment by DHowett-MSFT** [comment] 2019-10-26 17:38
Yep! This is a /dupe of #607. Thanks!

**Closed by DHowett-MSFT** 2019-10-26 17:38 UTC
Labels: Issue-Feature, Needs-Tag-Fix, Needs-Triage
