### ISSUE TITLE
Cannot display long Kubernetes token without truncation

### ISSUE THREAD

**Issue by komodovaran** [microsoft/terminal#7082] opened 2020-07-26 15:06 UTC
# Environment

```
Windows Terminal version 1.0.1811.0
Powershell Version 7.0.3
```

# Steps to reproduce 
Kubernetes relies on an extremely long token (like 900 characters) to be copy-pasted into the browser window to open up a dashboard. When this token is generated through Windows Terminal, it is cut off at the window width.

It does, however, work with the Powershell standalone terminal, where no truncation occurs. Instead, a horizontal scrollbar appears.

Other things in Windows Terminal are not cut off, such as `echo extremelylongstring`, but are wrapped.

**Comment by DHowett** [comment] 2020-07-26 18:00
So, this is pretty weird. We wrap _by default_, unless an application explicitly requests that we truncate. I bet the runtime Kubernetes is using has never been vetted to work with a locked console buffer (which is a completely valid way to configure the windows console...)

**Comment by DHowett** [comment] 2020-07-27 22:16
Would you mind sharing a screenshot or a snippet of text that's related to the token? I'd like to figure out where in the K8s source it's being printed and what they're doing wrong.

In general, applications that attempt to add a horizontal scroll bar to WT are just not going to work. They're explicitly trying to break line wrapping, and that's really just them telling you that it's _their computer_, not yours, where you get the final say.

**Comment by komodovaran** [comment] 2020-07-28 16:01
I dug around a bit in the scripts and it seems Kubernetes is not to blame. Actually, this PowerShell is:
`[Console]::BufferWidth = $long_text+10; Write-Host $long_text`

And then output with Write-Host. This bypasses line-wrapping, and therefore breaks in Windows Terminal.

**Comment by DHowett** [comment] 2020-07-31 01:06
Unfortunately, if Kubernetes is relying on the ability to set the buffer size to be an absurd width they're going to need to not do that :smile:

This may just be a duplicate of #5094, with the added bonus that the application has an annoying behavior if you reject its resize request.

**Closed** 2020-08-07 07:00 UTC
Labels: Needs-Author-Feedback, Needs-Tag-Fix, Needs-Triage, No-Recent-Activity
