### ISSUE TITLE
Terminal is blank after returning to it after a while

### ISSUE THREAD

**Issue by DrDinosaur** [microsoft/terminal#3261] opened 2019-10-20 04:34 UTC
# Environment

```
Windows build number: Microsoft Windows [Version 10.0.18963.1000]
Windows Terminal version (if applicable): 0.5.2762.0
```

# Steps to reproduce

1. Launch WSL terminal
2. Use other applications like a web browser
3. Go back to the WSL terminal

# Expected behavior

See a working terminal with all the past text output

# Actual behavior

The area where you would expect to see the terminal output is completely blank (black). Not sure how to reproduce this consistently, seems to happen at random. Looks like it can go back to normal after a bit (a minute?) of waiting. 

Might be @2733

**Comment by DHowett-MSFT** [comment] 2019-10-21 19:41
Yeah, looks like a /dupe of #2733. Thanks for finding it!

**Closed by DHowett-MSFT** 2019-10-21 19:41 UTC
Labels: Needs-Tag-Fix, Needs-Triage
