### ISSUE TITLE
The fade size of the dialog background does not change after resizing the window

### ISSUE THREAD

**Issue by satken2** [microsoft/terminal#8496] opened 2020-12-04 16:21 UTC
# Environment

```none
Windows build number....: 10.0.18362.1082
Windows Terminal version: 1.4.3243.0
```

# Steps to reproduce

1. Open terminal
![bug1](https://user-images.githubusercontent.com/33207653/101182612-a917d000-3691-11eb-90b4-5e7862e2030c.png)

2. Open some dialog (e.g. pasting multiple lines)
![bug2](https://user-images.githubusercontent.com/33207653/101182689-c3ea4480-3691-11eb-9257-9cef2b037131.png)

3. Close the dialog and then resize the window (larger size)

4. Reopen some dialog
![bug3](https://user-images.githubusercontent.com/33207653/101182741-db293200-3691-11eb-8fb3-511bd03555a8.png)

# Expected behavior

The fade of the dialog background expands to the same size as the main window.

# Actual behavior

The fade size of the dialog background does not change from the first time.
I assume once a dialog is opened, the fade size is fixed.

**Comment by DHowett** [comment] 2020-12-05 01:40
Thanks for the report! This is a /duplicate of #2380, which is a bit out of our hands. Sorry.

**Closed by DHowett** 2020-12-05 01:40 UTC
Labels: Needs-Tag-Fix, Needs-Triage
