### ISSUE TITLE
Tabs are stuck scrolling even though there is room to show them all

### ISSUE THREAD

**Issue by JayAllison** [microsoft/terminal#3655] opened 2019-11-21 13:59 UTC
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18363.476]
Windows Terminal version (if applicable): 0.6.2951.0


Any other software?
```

# Steps to reproduce

I am using a Microsoft Surface Pro 7, along with a Surface dock and two external monitors. I expect that this issue is related to scaling (a common problem in my setup).

My Surface's display is set to 200% scaling, while my two external monitors are set to 100% scaling.

As I dock and undock, lock and unlock, throughout the day, Terminal can get into some funny visual states. Usually I can get everything working again by "restoring" (Windows + Down) and "maximizing" (Windows + Up), but today when I did that I cannot see all of my tabs without scrolling (see screenshot), even though there is plenty of space to display them.

# Expected behavior

I would expect that all of the tabs are visible next to each other, since there is enough room to display them. 

# Actual behavior

I have 4 tabs open, but only one is showing; I have to scroll to see the rest of them.

![image](https://user-images.githubusercontent.com/1233907/69343656-9de33500-0c33-11ea-8e28-0113001b2ed1.png)

I later found that if I close one of the tabs, all of the others will suddenly become visible. I didn't try adding a tab, but that might fix it, too?

**Comment by zadjii-msft** [comment] 2019-11-21 14:21
Thanks for the report! This looks like a /dupe of #3300, with also some flavors of #3648 in it. I'll direct discussion to those threads.

**Closed by zadjii-msft** 2019-11-21 14:21 UTC
Labels: Needs-Tag-Fix, Needs-Triage
