### ISSUE TITLE
Create an ARGS or commandLineARGs property in settings profile, separate from commandLine property

### ISSUE THREAD

**Issue by brwilkinson** [microsoft/terminal#7801] opened 2020-10-01 18:45 UTC
### Description of the new feature/enhancement

Create an ARGS or commandLineARGs property in settings profile, separate from commandLine property

Example: If I want to run powershell from the store, I want to pass some args, however not hard code the pwsh.exe path, which would change frequently as the Store app was upgraded. However my args are static.

![commandLineARGs](https://user-images.githubusercontent.com/3605266/94850045-38c3a880-03db-11eb-94f7-fc7faaa53a36.png)

For backwards compatibility, perhaps combine the commandLineArgs with commandline for the implementation.

**Comment by WSLUser** [comment] 2020-10-02 15:24
You're looking for something like https://github.com/microsoft/terminal/pull/7348

**Comment by brwilkinson** [comment] 2020-10-02 15:59
@WSLUser  It doesn't look similar to this particular request, unless I am missing something ?

**Comment by WSLUser** [comment] 2020-10-02 18:13
You need nested argument support. This was already done for the Command Palette so something similar is needed for the settings.

**Comment by WSLUser** [comment] 2020-10-02 18:15
Though now that I think about it, you should be able to do it now using escape characters. Just make .ps1 and set the commandline to run it.

**Comment by DHowett** [comment] 2020-10-02 18:15
@brwilkinson sorry; @WSLUser may not have interpreted your request properly. I think this sounds a lot more like #5571 -- specifically https://github.com/microsoft/terminal/issues/5571#issuecomment-622186456. It has more to do with _profiles_ than _commands_, and escape characters (????) won't help whatsoever and just seem like a term related to terminals.

**Comment by WSLUser** [comment] 2020-10-02 18:17
I've removed my comments. I still think it could be scripted out.

**Comment by brwilkinson** [comment] 2020-10-02 18:28
@DHowett yes that is the one . . . specifically #issuecomment-622166445

![image](https://user-images.githubusercontent.com/3605266/94957325-69bae080-04a2-11eb-9560-d2879ecebd08.png)

**Comment by DHowett** [comment] 2020-10-02 21:19
Thanks for confirming! I'll mark this one as a /duplicate of #5571 and link them up so we make sure we get this use case. :smile:

**Closed by DHowett** 2020-10-02 21:19 UTC
Labels: Issue-Feature, Needs-Tag-Fix, Needs-Triage
