### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by happy2code** [microsoft/terminal#1578] opened 2019-06-25 05:44 UTC
# Environment
Windows build number: Microsoft Windows [Version 10.0.18922.1000]
Windows Terminal version (if applicable): 0.2.1715.0
Any other software? - None

# Steps to reproduce
Open Terminal from the Start Menu. Try to open 'Settings' from menu or 'Ctrl + ,'

# Expected behavior
The settings screen should open and present itself.

# Actual behavior
Absolutely nothing is happening. It is as if I did not try to open settings at all.

**Comment by Shorotshishir** [comment] 2019-06-25 05:56
Duplicate of #1460 . Please refer to the linked issue. Thank you

**Closed** 2019-06-25 06:18 UTC
Labels: Needs-Tag-Fix, Needs-Triage
