### ISSUE TITLE
typing in arabic problem 

### ISSUE THREAD

**Issue by Yanar-AlDaghestani** [microsoft/terminal#1592] opened 2019-06-25 09:12 UTC

**Comment by Yanar-AlDaghestani** [comment] 2019-06-25 09:13
if I open the terminal on power shell and type in Arabic I can not see what I am typing

**Comment by JushBJJ** [comment] 2019-06-25 11:28
I dont think the terminal supports arbic text yet unfortunately.

**Comment by Yanar-AlDaghestani** [comment] 2019-06-25 13:27
I do not want to support arabic but it allows me to type and the text is not showen correctly

**Comment by iamjmat** [comment] 2019-06-25 16:26
@Yanar-AlDaghestani  Can you give the following command "chcp 1256" and then check if the arabic characters are shown properly?

**Comment by Rrogntudju** [comment] 2019-06-26 00:08
There are 2 issues:
1)The arabic characters are displayed to the left of the cursor instead of the right. So they start to appear over the prompt and messed the display.
2) The spacing between characters is too wide so they don't appear attached.
![arabic](https://user-images.githubusercontent.com/25694410/60141762-bb939780-9784-11e9-923d-38e0a313f96b.PNG)

**Comment by miniksa** [comment] 2019-06-27 22:23
Dupe of #538.

**Closed by miniksa** 2019-06-27 22:23 UTC
Labels: Needs-Tag-Fix, Needs-Triage
