### ISSUE TITLE
Unable to move window with mouse when "grabing area" is out of the screen

### ISSUE THREAD

**Issue by weyou** [microsoft/terminal#13121] opened 2022-05-18 10:17 UTC
### Windows Terminal version

1.12.10983.0

### Windows build number

10.0.22000.675

### Steps to reproduce

1. Launch the Windows Terminal
2. Move the window to the right egde of the screen
3. Click "+" to open a new tab

### Expected Behavior

There should be a way to move the window with mouse when the "grabing area" is out of the screen.
For example, press "Ctrl" and click any position in the terminal and drag the winow. 

### Actual Behavior

I cannot move the terminal window with mouse in this case.

The only workarounds are:
1. Close one of the tabs then move the window with mouse 
2. Or trigger the system menu with "Alt+Space" and select "Move"

**Comment by DHowett** [comment] 2022-05-18 17:04
Thanks for the request! You can move the window with <kbd>Windows+Left</kbd> (or similar). Otherwise, this is a /duplicate of #539 :)

**Closed by DHowett** 2022-05-18 17:04 UTC
Labels: Issue-Bug, Needs-Triage, Needs-Tag-Fix
