### ISSUE TITLE
Build Issues

### ISSUE THREAD

**Issue by TanishShinde** [microsoft/terminal#977] opened 2019-05-24 13:57 UTC
Build Issues
The Build For Terminal Not Working Please Help

**Comment by dlong11** [comment] 2019-05-24 14:01
@TanishShinde Posting the errors can help people diagnose the issue.

**Comment by sergiipopov** [comment] 2019-05-24 14:18
Severity	Code	Description	Project	File	Line	Suppression State
Error	C2561	 'winrt::TerminalApp::implementation::App::_ShowOkDialog': function must return a value	TerminalApp	C:\work\terminal\src\cascadia\TerminalApp\App.cpp	196	
Error	C2065	 'await': undeclared identifier	TerminalApp	C:\work\terminal\src\cascadia\TerminalApp\App.cpp	214	
Error	C2146	 syntax error: missing ';' before identifier 'dialog'	TerminalApp	C:\work\terminal\src\cascadia\TerminalApp\App.cpp	214	
Error	C2065	 'LaunchSettings': undeclared identifier	TerminalApp	C:\work\terminal\src\cascadia\TerminalApp\App.cpp	388	
Error	MSB3030	Could not copy the file "C:\work\terminal\x64\Release\TerminalApp.dll" because it was not found.	CascadiaPackage	C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\DesktopBridge\Microsoft.DesktopBridge.targets	469	
Error	C2065	 'LaunchSettings': undeclared identifier	TerminalApp	C:\work\terminal\src\cascadia\TerminalApp\App.cpp	815

**Comment by zadjii-msft** [comment] 2019-05-24 14:47
Have you tried a clean build?

Have you tried a nuget restore? 

This sounds like the cppwinrt package is out of date, since they changed the behavior of `await` with 2.0.

**Comment by zadjii-msft** [comment] 2019-05-24 14:54
Now that I have some more info, this is a dupe of #974.

**Closed by zadjii-msft** 2019-05-24 14:54 UTC
Labels: Area-Build, Issue-Question, Needs-Author-Feedback, Needs-Triage, Product-Meta

**Comment by uk0** [comment] 2019-05-28 08:32
deal all this release Now !! https://github.com/uk0/microsoft-terminal-release
