### ISSUE TITLE
Slow performance and higher CPU usage

### ISSUE THREAD

**Issue by hyphenistic** [microsoft/terminal#9264] opened 2021-02-24 04:41 UTC
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.19042.804]
Windows Terminal version (if applicable): 1.5.10411.0

Any other software?
```

# Steps to reproduce

Open up a WSL terminal and let this run for a day: while true; do echo -e -n "\`date\`\r"; sleep 1; done

# Expected behavior

The current date / time should display and then get overwritten every second.

# Actual behavior

The date / time is displayed and gets overwritten every second.  After doing this for 24 hours (maybe less), the terminal instance becomes very slow and uses up more CPU than necessary.  Split the window and typing in the other pane is slowed down a bit.  Open another tab and typing is slowed down.  Closing the window is the only way to resolve the issue so far.

The command above is not the actually command I'm doing.  I'm actually running an rsync in the while loop.  I'm using \r as I don't need the scroll back buffer for this command.  I only need the current status.  My theory is that even though \r clears the line, it's getting recorded in the buffer.  Over time the buffer gets so big everything slows down.  I'm trying the same command with with \n now to see if it behaves the same.  I will report back my findings in a day or so.

**Comment by WSLUser** [comment] 2021-02-24 17:12
Are you using WSL2? Have you tried this without Windows Terminal and get different results?

**Comment by hyphenistic** [comment] 2021-02-25 02:35
I am not running WSL2.  I have not tried this without Windows Terminal.  It's been almost 24 hours and the same command using \n instead of \r is not causing any problems.

**Comment by ssc-boreus** [comment] 2021-02-25 11:08
I have a similar issue with WSL2. Usually I let Windows Terminal run for weeks with multiple different tabs, some of which accumulate a long history of commands and shell output.

A fresh instance of "WindowsTerminal.exe" will sit at 0% CPU while idle, but after a week of usage it now sits at 4% CPU idle. The highest I observed via TaskManager before restarting the terminal was a constant 10% CPU while all tabs were sitting completely idle on a shell prompt.

Opening a fresh tab and then closing all other old tabs does NOT lower the CPU usage. I have to completely close and re-open the Windows Terminal.

**Comment by ssc-boreus** [comment] 2021-02-25 11:12
At least for my case it seems to be related to https://github.com/microsoft/terminal/issues/7710

**Comment by zadjii-msft** [comment] 2021-02-25 13:31
Yea, this sounds exactly like #7710. We don't really have any idea what causes it. #9006 is similar too. The absolute worst part of this is how inconsistent the repro is - I had this happen to me once, but never again on any subsequent terminals. 

For now, I'm gonna close this as a /dupe of #7710 to try and keep the discussion contained. Thanks!

**Closed by zadjii-msft** 2021-02-25 13:31 UTC
Labels: Needs-Tag-Fix, Needs-Triage
