### ISSUE TITLE
Feature Request - Run As (other user)

### ISSUE THREAD

**Issue by cybrtitan** [microsoft/terminal#2200] opened 2019-08-01 22:10 UTC
I work in an environment where we are not allowed to log on as administrator accounts we must Shift click -> "Run as" to use any admin privileges.

Currently the Win Terminal only supports run as Administrator but in order to use this daily I need to be able to run this as an arbitrary user. To this date I don't think I have seen any UWP support this and thus it might not be possible. 

Bonus : It would be even better if I could launch each tab as different users while having the settings and core UI under my user. 

Thanks in advance

P.S. I hate the security policy

**Comment by miniksa** [comment] 2019-08-01 22:20
I understand that this is a nuance in what you're asking for, but it's the same background work and complexity as #146 so I'm resolving it as a duplicate of that.

**Closed by miniksa** 2019-08-01 22:20 UTC
Labels: Area-Interop, Issue-Feature, Product-Terminal

**Comment by cybrtitan** [comment] 2019-08-01 22:25
oh I wouldn't have considered it a sudo but i guess it kind of is, but also sudo is closer to run as administrator which is supported?

Thanks

**Comment by DHowett-MSFT** [comment] 2019-08-01 22:26
There's a nuance here: `run as administrator` works at the toplevel, but `run as...` doesn't, and that's because we're packaged as a Windows Store application. That's good feedback we can give them.

**Comment by cybrtitan** [comment] 2019-08-01 22:34
I would be curious to know if this is even possible with a UWP as most are installed per user not per machine and thus it probably doesn't exist under that user's context most of the time. 
This is how I came to the tabbed idea as the underlying bits to that are installed in every context to my understanding.
