### ISSUE TITLE
Bug Report - Chinese input method failed

### ISSUE THREAD

**Issue by weichzh** [microsoft/terminal#2460] opened 2019-08-17 09:27 UTC
# Environment

```none
10.0.18362.0
Windows Terminal (Preview)
Version: 0.3.2171.0
Microsoft Pinyin IME or other Chinese IME
```

# Steps to reproduce

Just use a Chinese IME, then type.
Win + . can't print any symbol.

# Expected behavior

the console should print Chinese characters.

# Actual behavior

just print latin letters.

**Comment by TayYuanGeng** [comment] 2019-08-17 12:55
This is similar to #2459

**Comment by zadjii-msft** [comment] 2019-08-17 14:07
This is also a dupe of #2213

**Closed by zadjii-msft** 2019-08-17 14:07 UTC
Labels: Needs-Tag-Fix, Needs-Triage
