### ISSUE TITLE
Feature request: drag tags to adjust order

### ISSUE THREAD

**Issue by Jarvis73** [microsoft/terminal#851] opened 2019-05-16 12:00 UTC
Drag tags to adjust order just like in browser, is it possible?

**Comment by mKay00** [comment] 2019-05-16 12:09
You mean tabs and this is a dupe of #443

**Comment by mdtauk** [comment] 2019-05-16 12:09
This is something that should be in the TabView control.  The version currently used in the Windows Terminal, is an initial version and so it should develop further as WinUI 2.2 is developed.

**Closed** 2019-05-16 13:59 UTC
