### ISSUE TITLE
Unable to move window

### ISSUE THREAD

**Issue by DanMcLaughlin** [microsoft/terminal#1412] opened 2019-06-22 14:07 UTC
# Environment

```
Windows 10.0.18362.175
Terminal version 0.2.1715.0
```

# Steps to reproduce

Just run the application. Happens to all instances. 

# Expected behavior

Can move the window! :)

# Actual behavior

 
Every window is locked to it's starting position. Can be resized however. Not sure what else I can provide, I have a triple screen setup on a 1080Ti, configuration 1920x1920 - 3440x1400 - 1920x1920 (the square monitors are the unusual Eizo ones). I'm not running any special display tools other than the LG screen split which is set to off. Setting it on (enables window snapping to various configurations to manage the desktop) other windows start snapping when moved, except terminal which still can't be moved.

**Comment by NEXUS2345** [comment] 2019-06-22 14:09
I have experienced similar, however, found the solution was to use the area of the bar indicated in this picture: 
![image](https://user-images.githubusercontent.com/4030870/59964945-b1149c00-94ff-11e9-8161-53bacd4988b3.png)

**Comment by mrmlnc** [comment] 2019-06-22 14:10
Looks like duplicate for #564.

**Comment by DanMcLaughlin** [comment] 2019-06-22 14:14
Yes, thanks @NEXUS2345 and @mrmlnc, the problem is you can't drag from the tab bar. I'll predict a lot of people will stumble on this, natural inclination is to grab that big tab section and not recognize what is happening.

**Comment by copdips** [comment] 2019-06-23 16:34
What I found is that the terminal reserves this blank area only for dragging window, which looks like a little bit strange.

**Comment by HBelusca** [comment] 2019-06-24 11:02
Duplicate of #1395 ; issue encompassed in #1375.

**Comment by DHowett-MSFT** [comment] 2019-06-24 16:10
That' right. Thanks @HBelusca!

**Closed by DHowett-MSFT** 2019-06-24 16:10 UTC
Labels: Needs-Tag-Fix, Needs-Triage

**Comment by jaywclark** [comment] 2019-07-15 16:54
> I have experienced similar, however, found the solution was to use the area of the bar indicated in this picture:
> ![image](https://user-images.githubusercontent.com/4030870/59964945-b1149c00-94ff-11e9-8161-53bacd4988b3.png)

Doh! I was dog-cussing this app for a day until i ran across this post. Thank you.
