### ISSUE TITLE
C1 control characters detection breaks output (regression)

### ISSUE THREAD

**Issue by alabuzhev** [microsoft/terminal#10310] opened 2021-06-02 02:02 UTC
### Windows Terminal version (or Windows build number)

1.9.1445.0

### Steps to reproduce

Compile and run the following code:
```C
#include <windows.h>

int main()
{
	const char data[] = "\x80\x81\x82\x83\x84\x85\x86\x87\x88\x89\x8A\x8B\x8C\x8D\x8E\x8F\x90\x91\x92\x93\x94\x95\x96\x97\x98\x99\x9A\x9B\x9C\x9D\x9E\x9F";
	wchar_t buffer[sizeof(data)];
	if (!MultiByteToWideChar(1252, MB_USEGLYPHCHARS, data, -1, buffer, sizeof(buffer)))
	{
		printf("%d\n", GetLastError());
	}

	DWORD n;
	WriteConsoleW(GetStdHandle(STD_OUTPUT_HANDLE), buffer, sizeof(buffer) / sizeof(wchar_t), &n, 0);

	printf("\n\n");

	for (int i = 0; i != sizeof(data) - 1; ++i)
	{
		if (buffer[i] == (unsigned char)data[i])
		{
			printf("%04X not converted\n", (unsigned char)data[i]);
		}
	}
}
```

### Expected Behavior

`€‚ƒ„…†‡ˆ‰Š‹ŒŽ‘’“”•–—˜™š›œžŸ` or something similar, depending on your output codepage

### Actual Behavior

`€‚ƒ„…†‡ˆ‰Š‹Œ` - most of the characters are missing.

After f91b53d5fdc5b20387e297357668f5f14a795d4c the whole range 0x80 - 0x9F is [considered control characters](https://github.com/microsoft/terminal/blob/f91b53d5fdc5b20387e297357668f5f14a795d4c/src/terminal/parser/stateMachine.cpp#L92).

[The comment above](https://github.com/microsoft/terminal/blob/f91b53d5fdc5b20387e297357668f5f14a795d4c/src/terminal/parser/stateMachine.cpp#L78-L84) boldly claims that
> *"we do not need to worry about confusion whether a single byte, for example, \x9b in a single-byte stream represents a C1 CSI or some other glyph, because by the time we get here, everything is Unicode. Knowing whether a single-byte \x9b represents a single-character C1 CSI or some other glyph is handled by MultiByteToWideChar before we get here (if the stream was not already UTF-16). For instance, in CP_ACP, if a \x9b shows up, it will get converted to \x203a. So, if we get here, and have a \x009b, we know that it unambiguously represents a C1 CSI"*

, but that is simply not true: as the example code above demonstrates, \x81, \x8D, \x8F, \x90, and \x9D are not handled by MultiByteToWideChar (at least in codepage 1252 ANSI - Latin I, hopefully popular enough), so no, not everything is Unicode by the time we get here, and no, we do need to worry about such confusion and implement a proper check to avoid breaking existing applications.

**Comment by skyline75489** [comment] 2021-06-02 02:40
I think https://github.com/microsoft/terminal/issues/7854#issuecomment-705235345 explains this.

**Comment by DHowett** [comment] 2021-06-02 02:48
@skyline75489 has the right of it. Those characters are unspecified in 1252. They are control character after f91b53d, but _they were control characters before that, too_.

What is a well-meaning application doing printing things outside of its codepage’s codepoint coverage?

**Comment by alabuzhev** [comment] 2021-06-02 03:02
The application basically outputs a file picked by the user using a codepage picked by the user.

If that behaviour is now by design - ok.
Although it would be nice to either mention that is the comment or remove that MultiByteToWideChar-inspired motivation altogether in favour of something like `0x80 - 0x9F are control codes now. Deal with it.` to avoid further confusions.

**Comment by alabuzhev** [comment] 2021-06-02 16:18
A few more thoughts:

- https://en.wikipedia.org/wiki/C0_and_C1_control_codes:
> Except for SS2 and SS3 in EUC-JP text, and NEL in text transcoded from EBCDIC, the 8-bit forms of these codes are **almost never used**. CSI, DCS and OSC are used to control text terminals and terminal emulators, but almost always by using their 7-bit escape code representations. Their ISO/IEC 2022 compliant single-byte representations are invalid in UTF-8, and the UTF-8 encodings of their corresponding codepoints are two bytes long like their escape code forms (for instance, CSI at U+009B is encoded as the bytes 0xC2, 0x9B in UTF-8), so there is no advantage to using them rather than the equivalent two-byte escape sequence. When these codes appear in modern documents, web pages, e-mail messages, etc., **they are usually intended to be printing characters at that position in a proprietary encoding such as Windows-1252 or Mac OS Roman that use the C1 codes to provide additional graphic characters**.

- Windows _does_ allow 0x80 - 0x9F in filenames. You can literally create a file named "", type `dir`, sit back and watch the world burn:

![image](https://user-images.githubusercontent.com/11453922/120514484-3def5200-c3c5-11eb-971d-36e33a341444.png)
![image](https://user-images.githubusercontent.com/11453922/120515567-53b14700-c3c6-11eb-891f-3eead29924eb.png)

Don't ask "but why?" - users can, so they will.
And incorrect codepage conversions are still a thing, especially during processing of various metadata. There are lots and lots of weird file names in the wild.

Sanitising *file names*, *everywhere*, [even in scenarios not related to outputting anything](https://github.com/microsoft/terminal/issues/10312) for the sake of the feature that is "almost never used"... 🤔
Supposedly sooner or later C1 will make it into the conhost and this is where the fun begins.

**Comment by j4james** [comment] 2021-06-02 21:31
Note that your test case won't be interpreted as control characters in conhost (even the very latest build), because you have to have the `ENABLE_VIRTUAL_TERMINAL_PROCESSING` mode set for this functionality to apply. In Windows Terminal that's enabled by default, so if you don't want VT controls processed in WT I think you have to explicitly disable that mode.

That said, the cmd shell does enable VT mode, so control characters in a filename could be an issue there. Somebody already raised that in issue #10069, which I misdiagnosed as a conpty problem, but I've just checked with a recent OpenConsole build and can reproduce the issue there too. So that issue should probably be reopened - it's not a dup of #4363.

However, note that this has been an issue long before PR #7340, because we already supported the 8-bit CSI control before then. PR #7340 just added more controls.

**Comment by j4james** [comment] 2021-10-31 01:50
@DHowett If we want to try and do something about this, I have a proposal that I think might make most people happy.

1. We start with C1 controls disabled by default. They're not particularly useful in UTF-8, and it's unlikely anyone is expecting a random subset of them to work in the unmapped portions of the DOS/Windows code pages.
2. If ISO-2022 mode is requested, that's when we enable the C1 support in the parser, since that's the one time they're actually likely to be needed.
3. Optionally add support for the `DECAC1` (Accept C1 Controls) escape sequence, so they can also be manually enabled in the UTF-8 codepage, in case anyone actually does need that.

Hopefully this will cut down on the bug reports, without actually losing any significant functionality.

It's also worth mentioning that XTerm doesn't support C1 controls in UTF-8 either, so it's unlikely to cause compatibility issues with Linux apps. While there are a few Linux terminals that do support UTF-8 C1 (VTE being the most well known), I think they're probably in the minority.

Anyway, I don't feel that strongly about this either way, but I'd be happy to put together a PR if you like the idea.

**Comment by DHowett** [comment] 2021-11-01 22:30
@j4james I'm _totally_ on board with this proposal. I love it.

The only thing that gives me pause (and it is not enough pause for me to care) is that I _think_ we supported one C1 control when we initially went open-source, and I somewhat wondered if there was a reason we chose to support that one. It's likely a "this one seems common, maybe we should support it we guess?" situation.

**Comment by DHowett** [comment] 2021-11-01 22:31
I'll probably prepare this one for isolated ingestion into Windows so it can be released in a servicing update. :smile: Folks may eventually be more broadly upset that conhost is "acting weird" and "displaying corrupt text" and "stole my keys."

**Comment by j4james** [comment] 2021-11-02 01:37
> The only thing that gives me pause (and it is not enough pause for me to care) is that I _think_ we supported one C1 control when we initially went open-source, and I somewhat wondered if there was a reason we chose to support that one. It's likely a "this one seems common, maybe we should support it we guess?" situation.

At the time you went open-source, there were only 5 supported sequences that could potentially have been implemented as C1 as far as I could see: `HTS`, `RI`, `CSI`, `OSC`, and `ST`. Of those five, `HTS` and `RI` aren't handled at the `StateMachine` level, so I can understand why they might not even have been considered.

That leaves `CSI`, `ST`, and `OSC`, the first two of which were actually supported as C1 controls. So the odd one out is `OSC`, which is kind of weird, because the only time you would use `ST` is when coupled with `OSC`. But the bottom line is that you supported almost all of the controls at the state machine level that were implemented at that time.

What's giving me pause now, though, is I just went to dig up an issue I remembered from the VTE tracker, where they were considering removing their C1 handling, thinking it would support this decision, but they ultimately chose not to (this was issue [209](https://gitlab.gnome.org/GNOME/vte/-/issues/209)). Ironically they cited the Windows support of C1 as one of the reasons for keeping it.

It wasn't just the fact that they chose to keep it, though, but they linked to a [bug report in Alacritty](https://github.com/alacritty/alacritty/issues/3105) where Fedora was using an OSC sequence with a C1 control, and since Alacritty didn't support C1, it got a bunch of garbage output on the screen. So that is a situation we could end up facing as well.

That said, I think this particular case only arose because Alacritty was started from a VTE shell, and was misrecognized as VTE because the VTE_VERSION environment variable was set. So I still think we are more likely to get bug reports from having C1 enabled by default, than we will if we remove it, but I don't want to pretend there are no downsides.

**Comment by alabuzhev** [comment] 2021-11-05 10:58
Guys, any recommendations which characters should be used for C1 replacement?
For C0 it's what [MB_USEGLYPHCHARS](http://archives.miloush.net/michkap/archive/2005/02/26/381020.html) does, but, as far as I see, there's no established equivalent for C1.
I've tried to just remap them to a private range (E080 - E09F), but it looks like the host [has performance issues with some of those](https://github.com/FarGroup/FarManager/issues/469), at least with E098.

**Closed** 2021-11-17 23:40 UTC
Labels: Product-Conhost, Needs-Triage, Needs-Tag-Fix, In-PR
