### ISSUE TITLE
New tabs inherit the environment of the Terminal process instead of the user default environment.

### ISSUE THREAD

**Issue by yitzhaks** [microsoft/terminal#4545] opened 2020-02-12 10:45 UTC
# Environment

```none
Windows build number: 10.0.19559.0
Windows Terminal version (if applicable): 0.8.10261.0
```

# Steps to reproduce

1. In a terminal tab, run any command that modified the user/system environment (e.g. SETX).

# Expected behavior

When opening a new tab, the environment should reflect the change made in step 1.

# Actual behavior

The environment doesn't reflect the change made in step 1.
I assume this is because `CreateProcessW` is called with `lpEnvironment == nullptr` which means `the new process uses the environment of the calling process`.

This is frustrating since if one makes a change to the user/system environment, one needs to close all Terminal tabs (or start a new Terminal) to get a tab that reflects said change.

**Comment by DHowett-MSFT** [comment] 2020-02-13 08:16
This is a /dupe of #1125 (but really, it's badly-named: it means "terminal should do the environment thing properly". Sorry about that!)

**Comment by DHowett-MSFT** [comment] 2020-02-13 08:16
Thanks for the CreateProcess info. :smile:

**Closed by DHowett-MSFT** 2020-02-13 08:16 UTC
Labels: Needs-Tag-Fix, Needs-Triage

**Comment by yitzhaks** [comment] 2020-02-13 09:12
Thanks for pointing me to the dupe. I searched before opening this issue, but didn't use the right terms to find #1125.
