### ISSUE TITLE
Missing the occasional row or column of pixels -- possible DPI issue?

### ISSUE THREAD

**Issue by scottmcm** [microsoft/terminal#10311] opened 2021-06-02 03:20 UTC
### Windows Terminal version (or Windows build number)

1.8.1444.0

### Steps to reproduce

Have output in the terminal.

I suspect this is DPI related, as I have the following set:

![image](https://user-images.githubusercontent.com/18526288/120419106-4efe7b80-c351-11eb-8176-6c99ded6881a.png)

### Expected Behavior

Font rendering is consistent in all rows and columns, and matches legacy terminal:

![image](https://user-images.githubusercontent.com/18526288/120418880-dd263200-c350-11eb-9335-141ad22c04b5.png)

### Actual Behavior

![image](https://user-images.githubusercontent.com/18526288/120419045-270f1800-c351-11eb-875b-2d30702fc281.png)

(I promise that's unmodified except for adding the arrows in mspaint.)

**Comment by skyline75489** [comment] 2021-06-03 03:19
I remember there's a dup issue for rendering issues caused by custom DPI but I couldn't find it...

**Comment by skyline75489** [comment] 2021-06-03 09:31
The support for custom DPI is currently not that good atm. You'll be fine if you're using 150% or 200%, but there might be some rendering glitches (for example #4591) if you're using 114% (really?) or something like that.

**Comment by DHowett** [comment] 2021-06-03 22:47
This does look like a /duplicate of #4591; thanks for bringing this up!

**Closed by DHowett** 2021-06-03 22:47 UTC
Labels: Needs-Triage, Resolution-Duplicate

**Comment by scottmcm** [comment] 2021-06-03 23:08
> if you're using 114% (really?) or something like that.

Yes.  I set the DPI to what the screen's DPI *actually is*, whether in Windows or GNOME or ...

(Was the "(really?)" necessary?  It doesn't seem unreasonable to expect a "modern" terminal application to be doing DPI correctly.)

**Comment by skyline75489** [comment] 2021-06-04 10:20
@scottmcm Sorry for the vibe of my response if that made you uncomfortable. Yeah it's totally reasonable to expect Windows Terminal to be handling DPI correctly. Just that terminal is still a rather "young" project comparing to the other competitors. There's a lot of things need polishing right now.

I speak for my own and not my company. Also I'm *not* part of the dev team of the terminal.
