### ISSUE TITLE
Consider adding right-click new terminal options when Terminal icon is on the taskbar

### ISSUE THREAD

**Issue by djk2004** [microsoft/terminal#1842] opened 2019-07-05 18:04 UTC
# Summary of the new feature/enhancement
When certain applications are on the taskbar, right-clicking their icons shows additional special menu options (ex: VS Code provides options to open recently opened files, workspaces, etc., calculator has a _tasks_ section, to open the calculator in standard, programming, etc. modes, Outlook has a menu to create new tasks, emails, etc.).  It would be convenient to include similar functionality for Terminal, so that a user could open a new Terminal window that is not the configured default.

For example, if a user's default is Ubuntu 18.04, and the user needs to open a Powershell window, then the user could simply right-click the taskbar icon, and the menu would allow opening Terminal directly to either Powershell or any of the other terminal options.  This interaction would prevent a user from having to open with a fresh Ubuntu terminal, then open a Powershell window (by either navigating to the menu or using keyboard shortcuts), and closing the unwanted Ubuntu terminal.

# Proposed technical implementation details (optional)
Add menu contributions to the normal default right-click taskbar menu, which allows a user to open Terminal directly into any one of the configured terminal options.

**Comment by DHowett-MSFT** [comment] 2019-07-05 18:06
Duplicate of #576.

**Closed by DHowett-MSFT** 2019-07-05 18:06 UTC
Labels: Issue-Feature, Needs-Tag-Fix, Needs-Triage
