### ISSUE TITLE
Scroll back in tmux works when pre-output the buffer 

### ISSUE THREAD

**Issue by takizo** [microsoft/terminal#4563] opened 2020-02-13 09:06 UTC
Good day everyone, I am running latest version of Windows Terminal. 

When SSH into server and running tmux. I cannot scroll back up (normal pane scroll) to view the output, but if I sort of pre-output before launching tmux, it works. 

I am not sure is this a bug or config I am missing. My tmux.conf don't have special setting, just as below

```
set -g prefix C-a
set -g default-shell /usr/local/bin/bash
set -g terminal-overrides 'xterm*:smcup@:rmcup@'
set -g default-terminal "screen-256color"
set-window-option -g automatic-rename on
```

I have record the screen video here https://www.youtube.com/watch?v=jDYW_paU3No

**Comment by DHowett-MSFT** [comment] 2020-02-13 17:21
I think this is a /dupe of #381 (Terminal doesn't know Tmux has switched to a mode that shouldn't have scrollback because we never tell it)

**Closed by DHowett-MSFT** 2020-02-13 17:21 UTC
Labels: Needs-Tag-Fix, Needs-Triage

**Comment by takizo** [comment] 2020-02-14 03:01
> I think this is a /dupe of #381 (Terminal doesn't know Tmux has switched to a mode that shouldn't have scrollback because we never tell it)

Thanks. I will share the video in the thread.
