### ISSUE TITLE
Right-click opened Terminal window does not release folder handle after navigated away

### ISSUE THREAD

**Issue by coreocto** [microsoft/terminal#13793] opened 2022-08-20 15:29 UTC
### Windows Terminal version

1.14.2281.0

### Windows build number

10.0.19044.1889

### Steps to reproduce

1. Create a new folder with arbitrary name. E.g. `sample`.
2. Using `Windows Explorer`, navigate into this `sample` folder. Open a `Windows Terminal` with right-click context menu.
3. Close the `Windows Explorer` window.
4. Switch back to the `Terminal` window, navigate away from this folder. E.g. `cd ..`.
5. Execute `rmdir sample` within the same `Terminal`. You should get an error of `The process cannot access the file because it is being used by another process.`.
6. Close the `Terminal` window and try to delete that folder again. You should now able to get rid of it without issues.

### Expected Behavior

The folder handle should get released once navigated away.

### Actual Behavior

Get an error of `The process cannot access the file because it is being used by another process.`.

**Comment by j4james** [comment] 2022-08-20 15:50
I think this is probably a duplicate of #5506.

**Closed** 2022-08-20 22:11 UTC
Labels: Issue-Bug, Needs-Triage, Needs-Tag-Fix

**Comment by coreocto** [comment] 2022-08-20 22:14
@j4james My bad, will follow that issue instead.
