### ISSUE TITLE
Precision touchpad scrolling (maybe Direct Manipulation API)

### ISSUE THREAD

**Issue by Tarik02** [microsoft/terminal#1980] opened 2019-07-15 19:15 UTC
### NOTE: This feature is addition to #1066

# Summary of the new feature/enhancement

Scrolling with (precision) touchpad is very convenient but only if application responds to scroll event instantly. This can be observed in Microsoft Edge, vscode, JetBrains IDEs (Smooth Scrolling option).

I think that Windows Terminal should have option to enable scrolling not line by line but pixel by pixel.

**Comment by DHowett-MSFT** [comment] 2019-07-15 21:22
This seems like a duplicate of #1400, actually! Thanks!

**Closed by DHowett-MSFT** 2019-07-15 21:22 UTC
Labels: Issue-Feature, Needs-Tag-Fix, Needs-Triage
