### ISSUE TITLE
File doesn't unlock after directory change

### ISSUE THREAD

**Issue by SaviPrograms** [microsoft/terminal#15580] opened 2023-06-20 15:27 UTC
### Windows Terminal version

1.17.11461.0

### Windows build number

10.0.22621.0

### Steps to reproduce

1. Open folder (eg. from icon context menu)
2. cd into parent directory
3. try to delete last visited folder

### Expected Behavior

File should be removed, or some other error should be displayed

### Actual Behavior

Issued command results in error, informing about lack of access to file ("File is locked by another process"). Happens both in PowerShell and CMD.

**Comment by zadjii-msft** [comment] 2023-06-20 15:59
This should be fixed in 1.18, the #15280 change I believe

**Comment by lhecker** [comment] 2023-06-20 15:59
Yep, this is a duplicate of #5506. /dup #5506
You can install "Windows Terminal Preview" from the app store to test it out!

**Closed** 2023-06-20 15:59 UTC
Labels: Issue-Bug, Needs-Triage
