### ISSUE TITLE
WSL Instances not respecting startingDirectory at first

### ISSUE THREAD

**Issue by blacklightpy** [microsoft/terminal#7272] opened 2020-08-13 10:49 UTC
# Environment

```none
Windows build number: 20185
Windows Terminal version (if applicable): 1.1.2021.0 (it was a problem before too)

Any other software?
Ubuntu on WSL2
```

# Steps to reproduce

Start Ubuntu from Windows Terminal profile
After the distro has booted up, close the tab and start it again

Here's my profile:

>         {
>             "guid": "{2c4de342-38b7-51cf-b940-2309a097f518}",
>             "startingDirectory": "//wsl$/Ubuntu/home/jyothish",
>             "hidden": false,
>             "name": "Ubuntu",
>             "source": "Windows.Terminal.Wsl"
>          }

(I had added the startingDirectory myself to get it to start in ~ and the rest were auto-generated and unmodified)

# Expected behavior

Ubuntu always respects startingDirectory

# Actual behavior

It does not respect startingDirectory for the first launch, but only for subsequent launches. It starts at /mnt/c/Users/Blacklight first and then when I close the tab and again launch a WSL instance again, it starts in ~ (/home/jyothish).

Additional Notes:

Also when WSL is not in use for a certain period of time (about one hour or so) the instance supposedly shuts down and starting it again would make it launch at /mnt/c/Users/Blacklight. I noticed this because when WSL is not active, I can't access the files from the Linux section in Windows Explorer (which was introduced in build 19603, basically //wsl/Ubuntu - which is slightly confusing because I expected //wsl$/Ubuntu to be the address but it was just //wsl/Ubuntu but both of them work anyways). So I was using some files from my browser and when I went up a directory after a while it showed file or resource not found. This is a problem related to WSL but I just thought of mentioning it here.

**Comment by DHowett** [comment] 2020-08-13 23:39
Partial /duplicate of #7197 -- thanks for the report! I'm going to merge these so we can track them more easily. We've got a number of other reports that are circling this one so we're going to try to knock them all out at the same time.
Seems likely that relying on the //wsl$ path to be up before WSL is is a non-starter!

**Closed by DHowett** 2020-08-13 23:39 UTC
Labels: Needs-Tag-Fix, Needs-Triage
