### ISSUE TITLE
Windows 10 openssh + vim scrollback issue

### ISSUE THREAD

**Issue by eugenov** [microsoft/terminal#8020] opened 2020-10-23 07:20 UTC
# Environment

```none
Microsoft Windows [Version 10.0.20241.1000]
Windows Terminal Preview v1.4.2652.0
OpenSSH_for_Windows_8.1p1, LibreSSL 3.0.2
```

# Steps to reproduce
1. run Windows Terminal (or Preview)
2. ssh to remote host
3. open file with vim, navigate through file
4. close vim (":q" :))
5. scroll up
5. see remains of opened file replaced all scrollback buffer (previous output) - not OK
# Expected behavior
1. run Powershell
2. ssh to remote host
3. open file with vim, navigate through file
4. close vim (":q" :))
5. scroll up
5. see only previous output, no signs of opened file in vim - it's OK
# Actual behavior
as you can see in "reproduce" section.

**Comment by DHowett** [comment] 2020-10-23 08:25
Thanks for the report! This is a /duplicate of #381. Terminal does not know that vim is using the “alternate screen” which does not have scrollback.

**Closed by DHowett** 2020-10-23 08:25 UTC
Labels: Needs-Tag-Fix, Needs-Triage

**Comment by chenzhiwei** [comment] 2021-07-28 02:05
Not only `vim`, all other applications like `less` and `man` which use alternate screen will also have such issue.

Hope this can be fixed asap.
