### ISSUE TITLE
Terminal can't be indexed by powertoys

### ISSUE THREAD

**Issue by DH-Illidan** [microsoft/terminal#12406] opened 2022-02-07 01:25 UTC
### Windows Terminal version

1.12.10334.0

### Windows build number

10.0.19043.0

### Steps to reproduce

press `alt + space`.
enter `terminal`

### Expected Behavior

I can see *Terminal* in the list as early release.

### Actual Behavior

I can't see *Terminal* in the list.

**Comment by DHowett** [comment] 2022-02-07 04:02
This is a /duplicate of https://github.com/microsoft/PowerToys/issues/16118

**Closed by DHowett** 2022-02-07 04:02 UTC
Labels: Needs-Triage, Needs-Tag-Fix

**Comment by DHowett** [comment] 2022-02-07 04:07
(Thanks got the report!)
