### ISSUE TITLE
CascadiaPackage installation error

### ISSUE THREAD

**Issue by KiYugadgeter** [microsoft/terminal#1170] opened 2019-06-08 06:28 UTC
I have tried install Windows terminal that build myself.
However it has failed.

Error said: 
The package or bundle is not digitally signed or its signature is corrupted.

How do I try Windows Terminal?

Note that all workloads that require to build are installed and run on Windows 10 18362.145

**Comment by zadjii-msft** [comment] 2019-06-10 13:08
I'm guessing you're trying to build from the commandline, not from VS. 

Did you try looking in the megathread (#489) of all build & installation issues? I found [this comment](https://github.com/microsoft/terminal/issues/489#issuecomment-496170540) in that thread that probably has the answer you're looking for.

I'm closing as a dupe of#489.

**Closed by zadjii-msft** 2019-06-10 13:08 UTC
Labels: Needs-Tag-Fix, Needs-Triage

**Comment by KiYugadgeter** [comment] 2019-06-17 01:14
How I do sign my build with Visual Studio 2019 (not commandline)

**Comment by zadjii-msft** [comment] 2019-06-18 15:13
@KiYugadgeter why would you need to sign the build with VS? I think it'll let you deploy it locally without signing the package...
