### ISSUE TITLE
pasting with 1.7.572.0 preview and fish causes strange behavior

### ISSUE THREAD

**Issue by KotlinIsland** [microsoft/terminal#9517] opened 2021-03-17 00:26 UTC
This doesn't happen in 1.6.10517.0 or when i switch to bash.
# Environment

```none
Windows build number: Win32NT             10.0.18363.0 Microsoft Windows NT 10.0.18363.0
Windows Terminal version (if applicable): 1.7.572.0

Any other software? Ubuntu-20.04, fish version 3.2.0
```

# Steps to reproduce
paste a command into wt eg `echo foo`

# Expected behavior

command is pasted as is

# Actual behavior
`foo^[[201~echo foo` appears on the line and the `foo^[[201~` part isn't able to be backspaced.

**Comment by DHowett** [comment] 2021-03-17 02:04
It looks like fish is requesting bracketed paste mode, but cannot handle bracketed paste mode.

It has asked us to include `\e[200~` and `\e[201~` so it knows where your pasted content started and ended, and we have done as it asked.

**Comment by skyline75489** [comment] 2021-03-17 02:25
I can't repro this locally with stock fish configuration. Is there any special configuration you're using that might relate to this?

**Comment by KotlinIsland** [comment] 2021-03-17 03:08
![image](https://user-images.githubusercontent.com/65446343/111408933-c09b3600-8721-11eb-940d-4f94ef5b8751.png)
Colleague also experiencing the exact same behavior.

**Comment by skyline75489** [comment] 2021-03-17 03:18
Yeah this is caused by #9034, which as @DHowett pointed out, is actually the *correct* thing to do. What's weird is that somehow fish does not handle the bracketed paste response correctly. So we need to know what's wrong on the fish side.

**Comment by skyline75489** [comment] 2021-03-17 03:25
OK after upgrading fish to 3.2.0 I can repro this locally. This is indeed a shell issue. See https://github.com/fish-shell/fish-shell/issues/7770 . This should be fixed in 3.2.1 according to that thread.

**Comment by skyline75489** [comment] 2021-03-17 03:30
Meanwhile, you may choose to *downgrade* fish using:

```text
sudo apt install fish=3.1.0-1.2 fish-common=3.1.0-1.2
```

This fixes the issue for me.

**Comment by DHowett** [comment] 2021-03-17 03:41
@skyline75489 thanks so much!

/dup https://github.com/fish-shell/fish-shell/issues/7770

**Closed by DHowett** 2021-03-17 03:41 UTC
Labels: Needs-Tag-Fix, Needs-Triage
