### ISSUE TITLE
TabSwitcher stay on top and I need to click on the window to be able to type anything

### ISSUE THREAD

**Issue by Nordes** [microsoft/terminal#8319] opened 2020-11-18 15:00 UTC
# Environment
Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.19042.0 Microsoft Windows NT 10.0.19042.0

Windows Terminal - Version: 1.4.3141.0

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Windows Terminal version (if applicable):

Any other software?
```

# Steps to reproduce
When doing tabbing, it sometimes happens:

- Ctrl+Tab (basically sometime randomly)

# Expected behavior
Switch tab without having the tabswitcher overlay staying on top

# Actual behavior
The tabswitcher stay stuck on top (overlay) and I am not able to type anything. Even when I hit escape key, it does not disable the tab switcher. It requires me to do a mouse click. You can see on below picture that the focus is lost from the terminal (no caret flashing)

![image](https://user-images.githubusercontent.com/446572/99546992-0703a280-2985-11eb-8d10-480016b08e68.png)

**Comment by zadjii-msft** [comment] 2020-11-18 15:24
The tab switcher _should_ dismiss itself when the <kbd>ctrl</kbd> key is released, does it not? If it doesn't, what keyboard layout are you using? And are you perhaps using Sticky Keys?

(For the record, you can disable the tab switcher entirely with `"useTabSwitcher": false` in the root of your settings)

**Comment by Nordes** [comment] 2020-11-18 15:33
The keyboard I use is the **Logi MX Keys** (Logitech wireless keyboard). Also, the sticky key is off in my windows settings. 

The "ctrl+tab" key usually works, but it happens "sometimes" that the overlay with the tab names remains there. It happened to me a few times already, but it's not like it's every time.

For now, I will disable the tabswitcher for now. Thank's for giving the option.

**Comment by DHowett** [comment] 2020-11-20 03:27
@Don-Vito do you think this is related to the fix you made earlier?

**Comment by Don-Vito** [comment] 2020-11-20 05:51
@DHowett - my fix was only for custom bindings, so I guess it is something else.

**Comment by electronic-dk** [comment] 2020-11-20 09:44
I've also faced this issue several times on a dell 7400 laptop. I have English (US) and Russian layouts on the keyboard, but I couldn't pinpoint anything specific that causes such behavior.

**Comment by Don-Vito** [comment] 2020-11-20 09:58
@electronic-dk - few questions:
1. does it happen to you in the same version of Terminal as in the original post?
2. Does it happen randomly or you can reproduce it? 
3. Are  you using Ctrl+Tab or some custom binding.
4. Does it happen if you are holding Ctrl for a while or it happens even for a single navigation 
5. Is it always happening for the last tab?

**Comment by electronic-dk** [comment] 2020-11-20 10:54
@Don-Vito 

1. The version is the same Version: 1.4.3141.0 I don't think I've seen this issue before the 1.4 update
2. It's been happening randomly. Unfortunately, I don't have a reliable way of reproducing it at the moment, I'll keep experimenting and let you know if I can reproduce the issue reliably. I noticed that a somewhat reproducible way to get the tab switcher to stuck is to open 3 - 4 tabs, switch between then several times quickly, then close all the tabs but one, open a new tab and try to switch to the previous tab. The content of the tabs seems unimportant since I was able to reproduce it with both powershell and ubuntu in WSL2 tabs.
3. I'm using the default Ctrl+Tab binding
4. I'm pretty sure it happens for single navigations as well
5. I don't think it's been happening for any specific tab

In general, it seems that the tab switcher gets stuck after I make several quick changes between tabs, the next switch after that sometimes is stuck.
Sorry for the somewhat vague description, I'd love to give you a more elaborate explanation, but I don't have any :( 
Please, let me know if I can give you any more info.

**Comment by Don-Vito** [comment] 2020-11-20 11:13
> @Don-Vito 
> 
> 1. The version is the same Version: 1.4.3141.0 I don't think I've seen this issue before the 1.4 update
> 2. It's been happening randomly. Unfortunately, I don't have a reliable way of reproducing it at the moment, I'll keep experimenting and let you know if I can reproduce the issue reliably. I noticed that a somewhat reproducible way to get the tab switcher to stuck is to open 3 - 4 tabs, switch between then several times quickly, then close all the tabs but one, open a new tab and try to switch to the previous tab. The content of the tabs seems unimportant since I was able to reproduce it with both powershell and ubuntu in WSL2 tabs.
> 3. I'm using the default Ctrl+Tab binding
> 4. I'm pretty sure it happens for single navigations as well
> 5. I don't think it's been happening for any specific tab
> 
> In general, it seems that the tab switcher gets stuck after I make several quick changes between tabs, the next switch after that sometimes is stuck.
> Sorry for the somewhat vague description, I'd love to give you a more elaborate explanation, but I don't have any :( 
> Please, let me know if I can give you any more 

Thanks! Your description is very insightful. Especially the fact that a prior fast modification triggers this defect more often. It can be a strong indicator for some sort of race condition between the switcher and the tabs row. I will try to reproduce again, but this time with your hints.

**Comment by Don-Vito** [comment] 2020-11-20 14:18
@electronic-dk - updating that thanks to you hints I was able to reproduce it in a release version, but debugging the release with windbg is not of much fun. Trying to reproduce it with dev version.

**Comment by Don-Vito** [comment] 2020-11-20 16:00
So... I am only 90% sure if it is exactly the same, but I was able to deterministically reproduce a significant issue with tab creation / closing while tab switcher is open for a while.
 
I know that in the original issue the tab switcher does not remain open for a long time, but I believe it can still be related due to the asynchronous nature of tab creation / deletion. I mean in this case it must be a race between tab switcher being open and the async logic of tab closing applied. 

So here how it goes:
![PaletteLostFocus](https://user-images.githubusercontent.com/4639110/99821038-31f31f80-2b5a-11eb-951b-eb107b00bade.gif)

@zadjii-msft - could it regress with all the palette rendering optimizations?

**Comment by Don-Vito** [comment] 2020-12-09 23:21
@DHowett - Now that #8355 is merged this hopefully should be resolved as well. Even in the race scenario, the switcher will be either focused and navigable or unfocused and collapsed.

**Comment by DHowett** [comment] 2020-12-11 19:44
Fingers crossed!

**Closed by DHowett** 2020-12-11 19:44 UTC
Labels: Area-User Interface, Help Wanted, Issue-Bug, Priority-2, Product-Terminal
