### ISSUE TITLE
cannot input Simplified Chinese...

### ISSUE THREAD

**Issue by zpd2009** [microsoft/terminal#3701] opened 2019-11-26 12:53 UTC
# Description of the new feature/enhancement

# Proposed technical implementation details (optional)

**Comment by cjc7373** [comment] 2019-11-26 13:22
duplicate of #2213

**Comment by zadjii-msft** [comment] 2019-11-26 13:29
Thanks for the report! @cjc7373 is correct, this is in fact a duplicate of the aforementioned issue. Please refer to that thread for more information.

/dup #2213

**Closed by zadjii-msft** 2019-11-26 13:29 UTC
Labels: Issue-Feature, Needs-Tag-Fix, Needs-Triage
