### ISSUE TITLE
Feature Request: Specific Azure Tenant per Cloud Shell profile

### ISSUE THREAD

**Issue by yaakov-h** [microsoft/terminal#6018] opened 2020-05-20 06:10 UTC
I belong to multiple Azure tenancies / Azure ADs, and when I open a Cloud Shell profile it asks every time which one I want to log in to, like so:

> Tenant 0: First Tenant (tenant1.com.au)
Tenant 1: Second Tenant (tenant2.com.au)
Please enter the desired tenant number.
Enter n to login with a new account
Enter r to remove the above saved connection settings.
\>

I think it would be great if I could specify the tenant in the profile (as defined in settings.json) so that I can open a Cloud Shell directly using `wt` or the new-tab UI and have it connect automatically to the Azure tenant that I want.

I would expect to be able to do something like this to skip the tenancy selection dialog:

```
{
    "guid": "{b453ae62-4e3d-5e58-b989-0a998ec441b8}",
    "hidden": false,
    "name": "Azure Cloud Shell (Tenant1)",
    "source": "Windows.Terminal.Azure",
    "tenant": "{my-first-azure-ad-tenant-guid-here}"
},
{
    "guid": "{b453ae62-4e3d-5e58-b989-0a998ec441b8}",
    "hidden": false,
    "name": "Azure Cloud Shell (Tenant2)",
    "source": "Windows.Terminal.Azure",
    "tenant": "{my-second-azure-ad-tenant-guid-here}"
}
```

(probably with different profile GUIDs though, I guess)

**Comment by zadjii-msft** [comment] 2020-05-20 12:34
This sounds like a great idea. I'd think that this is sorta related to #5311, but probably different enough. We should probably get a spec going for outlining some improvements to the ACS connection.

**Comment by DHowett** [comment] 2020-05-21 22:57
Thanks for the request! I think this is a /dupe of #5311, though with more information. I'm going to move your comment over there.

**Closed by DHowett** 2020-05-21 22:57 UTC
Labels: Area-AzureShell, Issue-Task, Needs-Triage, Product-Terminal
