### ISSUE TITLE
Windows Terminal: Loss of Mouse Interactivity (PowerToys)

### ISSUE THREAD

**Issue by hectormz** [microsoft/terminal#6120] opened 2020-05-21 23:58 UTC
# Environment

```none
Windows build number: [Version 10.0.19041.264]
Windows Terminal version (if applicable): 1.0.1401.0

Any other software?
```

# Steps to reproduce

This seems to happen when I leave Windows Terminal running long enough. I haven't been able to nail down the exact situation that leads to it happening. I started noticing this recently, which may be due to a new problem, or just more use of Windows Terminal. 

I'm certain that leading up to the unresponsiveness, my machine has been locked and/or asleep at some point. But I have put my computer asleep, or locked it without reproducing the problem.

# Expected behavior

Normal mouse interactivity.

# Actual behavior

At least once a day now, my Windows Terminal become unresponsive to mouse interactions. This includes selecting text, pasting text with right click, clicking tabs and dropdown menu, minimize/maximizing the window etc. The only mouse interaction that works is grabbing the title bar and moving the window.

I am seeing this behavior with Windows Terminal, but I have a feeling it might be UWP related. I don't (knowingly) use many UWPs, but when the Windows Terminal is like this, I've tested the Microsoft Store application as well. I'm able to minimize/maximize Microsoft Store, but cannot drag it around via the title bar. When Windows Terminal is behaving properly, the Microsoft Store is fine.

When Windows Terminal has been misbehaving, I've opened Windows Terminal (Preview), and it was acting similarly unresponsive.

This issue is not resolved by closing and reopening Windows Terminal. I have to restart my computer to fix it.

If I can provide any more info, or narrow down what leads to this happening, I'll report back.

**Comment by DHowett** [comment] 2020-05-22 00:31
Do you have PowerToys installed?

**Comment by DHowett** [comment] 2020-05-22 00:32
(This could be a XAML platform bug -- that's the only thing in common between that set of applications. _Hmm._)

**Comment by hectormz** [comment] 2020-05-22 00:35
@DHowett Yes, I updated to PowerToys `v0.18.0` this week. Before that, I was several versions behind (`v0.13.0`).

Do you think that's involved? Would closing PowerToys when this issue happens fix it?

**Comment by DHowett** [comment] 2020-05-22 00:38
It's worth a shot!

**Comment by hectormz** [comment] 2020-05-22 00:44
I'll report back. 

You made me wonder if this could be caused by FancyZones use, but that didn't cause any issues yet.

**Comment by softwarenerd** [comment] 2020-05-22 02:21
I am experiencing this, too. It's random and happens when Windows Terminal has been running for a little while. I always have two Windows PoweShell tabs open  There are no steps to reproduce this other than to start Windows Terminal and open two Windows PoweShell tabs.

**Comment by Domain** [comment] 2020-05-22 09:38
I have the same issue. And when I exit PowerToys, it works fine now.

**Comment by zadjii-msft** [comment] 2020-05-22 11:46
@softwarenerd do you have powertoys installed as well?

@crutkas We're still seeing some intermittent mouse issues with the Terminal and PowerToys, even on updated versions of PowerToys, anything we can do to get logging from these users to debug?

**Comment by softwarenerd** [comment] 2020-05-22 16:20
@crutkas I don't.

**Comment by hectormz** [comment] 2020-05-23 18:23
@zadjii-msft @crutkas @DHowett 

This morning I lost mouse function again.

Closing PowerToys did the trick. I closed it and all was fine again. I opened PowerToys again and it's still fine.

**Comment by crutkas** [comment] 2020-05-23 19:02
@hectormz. Did you drag the window with fancyzones at any time before?

**Comment by hectormz** [comment] 2020-05-23 19:06
@crutkas I did drag other windows into FancyZones last night, but not Terminal.

 Last night everything was okay, and computer was asleep over night. Some time after waking the computer today and doing work, I noticed Terminal not responding again.

**Comment by muzzar78** [comment] 2020-05-25 02:46
I have experienced the same issue and it occurred when I unlocked my laptop from sleep. I had two tabs open and I don't have powertoys installed. If I right click close from the taskbar, I get close tabs dialogue but it is unresponsive too. This has happened several times over the last month (both prior to v1 and now on v1).

![image](https://user-images.githubusercontent.com/13233154/82773450-6fb20c80-9e85-11ea-951b-953f7f18aaa6.png)

Killing the windowsterminal process and relaunching resolves the issue.

**Comment by crutkas** [comment] 2020-05-25 03:18
@muzzar78 do you have PowerToys installed?

**Comment by muzzar78** [comment] 2020-05-25 06:19
> @muzzar78 do you have PowerToys installed?

No, I don't.

**Comment by SergioMorchon** [comment] 2020-05-26 11:24
I also don't have Power Toys installed, and experience the same issue.
Also to close it, even if I right-click on the task bar icon with the mouse, anc select "Close", the terminal shows the dialog (that warns about having multiple tabs that will be closed) but if I click over the dialog buttons, it just do nothing.
I have to close it from the Windows task manager

**Comment by ihor-sviziev** [comment] 2020-05-26 12:04
I also getting issue with dialog on Ubuntu 20.04 WSL2 with following command:
```bash
HEIGHT=0
WIDTH=0
dialog \
    --backtitle "System Information" \
    --title "Menu" \
    --clear \
    --cancel-label "Exit" \
    --menu "Please select:" $HEIGHT $WIDTH 4 \
    "1" "Display System Information" \
    "2" "Display Disk Space" \
    "3" "Display Home Space Utilization"
```

It just stops reacting on mouse clicks just after few clicks to different options. Also I hadn't this issue on Terminal Preview versions.
Windows Terminal Version: 1.0.1401.0
Windows Version 2004 (OS Build 19041.264)

**Comment by arntj** [comment] 2020-05-27 15:21
I'm having the same issue. When it happens, it persists when I close and re-open Terminal. But if I shut down Powertools, then it disappears.

I also noticed that if I run Terminal as administrator while PowerTools is running then I get this notification:
![image](https://user-images.githubusercontent.com/7281836/83039484-88195700-a03e-11ea-9eec-3387023a719d.png)

**Comment by sam-cross** [comment] 2020-05-27 18:48
I have the same issue. Exiting PowerToys restores functionality - Terminal doesn't even need to be restarted after PowerToys is exited.

**Comment by leandrowilliam** [comment] 2020-05-28 16:32
I have the same issue... But when I close PowerToys it run good again without restarting the Terminal. The issued started with the _v0.18.1_ of powerToys, that ask to intall/update the netFramework too

**Comment by crutkas** [comment] 2020-05-28 16:47
> I'm having the same issue. When it happens, it persists when I close and re-open Terminal. But if I shut down Powertools, then it disappears.
> 
> I also noticed that if I run Terminal as administrator while PowerTools is running then I get this notification:
> ![image](https://user-images.githubusercontent.com/7281836/83039484-88195700-a03e-11ea-9eec-3387023a719d.png)

If terminal is run as admin, we can't resize the terminal window since PT runs at a lower permission.  This is PowerToys telling you 'hey, you're in a state odd stuff may happen'

**Comment by sam-cross** [comment] 2020-05-28 22:39
> This is PowerToys telling you 'hey, you're in a state odd stuff may happen'

This is interesting! However, (to the best of my knowledge) this issue isn't caused by running an elevated instance of Terminal. I think the same thing happens with regular permissions.

**Comment by crutkas** [comment] 2020-05-28 22:52
> This is interesting! However, (to the best of my knowledge) this issue isn't caused by running an elevated instance of Terminal. I think the same thing happens with regular permissions.

this dialog is all about making users aware that FancyZones can't resize elevated apps.  This GH issue and that are unrelated.  Just wanted to clarify that.

**Comment by zadjii-msft** [comment] 2020-06-23 14:46
I've _finally_ gotten a live repro of this on my machine. I'm on PT 0.18.0, but I'm certainly not about to update until we attempt to debug this. Now I'm just waiting on @crutkas to wake up and sign in 😜 

CRAZILY, I've found an interesting piece of the puzzle - this only repros on my primary, high-DPI display. Both my external monitors are 96DPI, and if I drag the Terminal window to those displays, it works like a charm. I'm getting very similar behavior with the XAML Studio app, so I'd bet there's a weird interaction with XAML islands here.

**Comment by zadjii-msft** [comment] 2020-06-24 14:53
Hey all, just a follow up on this thread - if you're hitting this, could you try providing any of the following information:
* Are you using the Terminal on a high DPI display? 
  - If so, and if possible, does dragging the window to a 100% scaling display magically restore mouse functionality to the Terminal?
* Does the PowerToys settings app similarly not respond to mouse input?
* Do you have the Shortcut Guide enabled in PowerToys?
  - If so, does it actually work if you long press <kbd>Win</kbd>?
* By any chance, did you recently uninstall any sort of IME (like a Chinese/Japanese/Korean language IME)?

I just hit this yesterday, and although we don't have exact repro steps yet, we're trying to figure out anything that could be useful. 

See also:
* https://github.com/microsoft/PowerToys/issues/4360
* https://github.com/microsoft/PowerToys/issues/3833
* https://github.com/microsoft/PowerToys/issues/3250
* https://github.com/microsoft/PowerToys/issues/3090
* (this list is not comprehensive)

If you're experiencing this, and you can interact with the PowerToys settings app (you might need to drag it to another monitor), then
* can you fix the issue by disabling "Shortcut Guide" in PowerToys?

**Comment by hectormz** [comment] 2020-06-27 01:28
So, I just encountered this again (since you posted this @zadjii-msft ).
I normally am using my laptop which has a high DPI display, which is off, and is connected to a high DPI monitor. (Scaling is set to recommended 250%)

I was using my laptop without an external monitor and couldn't interact with Windows Terminal with mouse.

I opened the powertoys settings, but couldn't click anything. But I do have the shortcut guide enabled, and it did come up after holding `Win` key.

After this, I went back to PowerToys settings which were now working, and I went back to Windows Terminal which was also back to normal. Seemingly just from bringing up the shortcut guide.

I have not uninstalled any IME to my knowledge.

**Comment by masterashu** [comment] 2020-06-30 04:15
I had this same issue with Windows Terminal Version: 1.0.1401.0. I also experienced loss of mouse interactivity in the Twitter PWA Store app.

**Comment by crutkas** [comment] 2020-06-30 04:21
> I had this same issue with Windows Terminal Version: 1.0.1401.0. I also experienced loss of mouse interactivity in the Twitter PWA Store app.

Do you have PowerToys installed. If so what is enabled.

**Comment by masterashu** [comment] 2020-06-30 04:25
Yes Powertoys (v0.18.2) is installed. The enable features are: Image Resizer, Power Rename, and PowerToys Run.

**Comment by crutkas** [comment] 2020-06-30 06:21
> Yes Powertoys (v0.18.2) is installed. The enable features are: Image Resizer, Power Rename, and PowerToys Run.

But not shortcut guide or fancyzones?  Interesting

**Comment by mike-loux-planview** [comment] 2020-07-24 13:44
> Hey all, just a follow up on this thread - if you're hitting this, could you try providing any of the following information:
> 
> * Are you using the Terminal on a high DPI display?

Don't know - Samsung 27" curved 1080p gaming monitor.  

>   
>   * If so, and if possible, does dragging the window to a 100% scaling display magically restore mouse functionality to the Terminal?

Dragging it to an identical, non-primary display does restore functionality.

> * Similarly, are you using the Terminal on your primary display?

It's considered display #2 by the system (LT screen is #1), but it IS my main display.

>   
>   * If so, and if possible, does dragging the window to another display magically restore mouse functionality to the Terminal?

It does indeed.

> * Does the PowerToys settings app similarly not respond to mouse input?

Yup.  It sure doesn't.

> * Do you have the Shortcut Guide enabled in PowerToys?

Yup.

>   
>   * If so, does it actually work if you long press Win?

It did - did not try this again.

> * By any chance, did you recently uninstall any sort of IME (like a Chinese/Japanese/Korean language IME)?

No.

> 
> I just hit this yesterday, and although we don't have exact repro steps yet, we're trying to figure out anything that could be useful.
> 
> See also:
> 
> * [microsoft/PowerToys#4360](https://github.com/microsoft/PowerToys/issues/4360)
> * [microsoft/PowerToys#3833](https://github.com/microsoft/PowerToys/issues/3833)
> * [microsoft/PowerToys#3250](https://github.com/microsoft/PowerToys/issues/3250)
> * [microsoft/PowerToys#3090](https://github.com/microsoft/PowerToys/issues/3090)
> * (this list is not comprehensive)
> 
> If you're experiencing this, and you can interact with the PowerToys settings app (you might need to drag it to another monitor), then
> 
> * can you fix the issue by disabling "Shortcut Guide" in PowerToys?

Yup.  That did the trick.  I use Mouse in Windows Terminal for selecting text in PS several hundred times a day, so this is a good workaround for me.  Thank you!

**Comment by matteocontrini** [comment] 2020-08-08 19:08
Just happened to me.

> Are you using the Terminal on a high DPI display?

No, but the resolution is 2560x1080



> Similarly, are you using the Terminal on your primary display?

Yes



>   If so, and if possible, does dragging the window to another display magically restore mouse functionality to the Terminal?

I can't test unfortunately



> Does the PowerToys settings app similarly not respond to mouse input?

Yes, it **doesn't** respond to mouse input



> Do you have the Shortcut Guide enabled in PowerToys?

Yes



> If so, does it actually work if you long press Win?

No, it doesn't



> By any chance, did you recently uninstall any sort of IME (like a Chinese/Japanese/Korean language IME)?

No

**Comment by zadjii-msft** [comment] 2020-08-17 13:58
Oh my goodness, would you look at that. There's also #3325 which is another (much older) thread about this exact same issue. Maybe we should close this thread and link the two up?

**Comment by vlovich** [comment] 2020-11-14 20:46
For me, dragging to a second monitor fixes it but it's still broken on the primary monitor when I drag it back. Turning off the powertoys shortcut guide re-enabled mouse again for me in the broken terminal.

**Comment by zadjii-msft** [comment] 2021-01-29 15:44
You know what, I'm just gonna close this in favor of #3325, to try and keep the discussion in one place. Thanks!

**Closed by zadjii-msft** 2021-01-29 15:44 UTC
Labels: Area-Input, Issue-Bug, Priority-1, Product-Terminal

**Comment by julie777** [comment] 2022-10-08 22:26
I just discovered the same issue. I am running fancy zones. If I use the windows key shortcut to move the terminal to a different location the mouse works. If I use the shortcut to move it back the mouse stops working.

**Comment by endrelovas** [comment] 2023-07-04 06:05
Did anyone got a resolution to this? I do not have Powertoys installed. Never had. Killing the process won't help. Dragging to another screen won't help. No high res. Nothing fancy here except for oh-my-posh.
