### ISSUE TITLE
ubuntu 18.04 bash between originate one and terminal one behave quite different

### ISSUE THREAD

**Issue by tlsalex** [microsoft/terminal#3683] opened 2019-11-24 04:27 UTC
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18362.476]
Windows Terminal version (if applicable): Windows Terminal (Preview) Version: 0.5.2762.0

software from Microsoft Store :  Ubuntu 18.04

```

# Steps to reproduce

1. Launch ubuntu 18.04 bash inside terminal. and create a new file and edit it by using "vi config"
2. Launch ubuntu 18.04 bash separately. and create a new file and edit it by using "vi config"
3. open a json file (no matter use a notepad or notepad ++ or other text tool)
4. copy a slice of json code and paste into the config file in step 1 and step 2.

# Expected behavior
The code format(layout) is the same as the originate file.

# Actual behavior
Please see bellow picture for more clear explanation.
1. The code in the originate bash is quite normal
2. But the code in the terminal bash is quite different, bellow each line of code has an empty line.
3. If I copy code from a json file that originate from linux , will not have this issue in terminal bash.
4. But I work under windows , always create text(config) file under windows environment and always copy text from notepad.

![compare](https://user-images.githubusercontent.com/36788337/69489594-9df26780-0eb5-11ea-8219-a0bc5431bc00.PNG)
![wrong_format](https://user-images.githubusercontent.com/36788337/69489596-a2b71b80-0eb5-11ea-9f29-d8f10ded4028.png)

**Comment by j4james** [comment] 2019-11-24 11:26
I think this might be a duplicate of #1091. If so, it should be fixed in the next preview release.

**Comment by zadjii-msft** [comment] 2019-11-25 13:52
Thanks for the report! I'd agree with @j4james, this looks just like /dup #1091.

**Closed by zadjii-msft** 2019-11-25 13:52 UTC
Labels: Needs-Tag-Fix, Needs-Triage
