### ISSUE TITLE
Midnight commander displays visual artifacts

### ISSUE THREAD

**Issue by BladeMF** [microsoft/terminal#2087] opened 2019-07-25 08:46 UTC
# Environment

```
Windows build number: Microsoft Windows [Version 10.0.18362.239]
Windows Terminal version (if applicable): 0.2.1831.0
```

# Steps to reproduce

Open a session to one of the WSL containers. Open midnight commander and start scrolling with the arrows and tab between panes.

# Expected behavior

No additional characters appearing and disappearing. No changes to the borders.

# Actual behavior
Visual artifcats that don't seem to depend on the selected font. Both screensohts use different fonts - one is Inconsolata LGC, the other is Consolas. What seem to suffer the most are the borders. 

![image](https://user-images.githubusercontent.com/12109622/61859667-3e695880-aed1-11e9-9ec2-fa7e1698f581.png)

![image](https://user-images.githubusercontent.com/12109622/61859681-432e0c80-aed1-11e9-9d80-207b95a9ea99.png)

This is a screenshot from the current cmd connecting to the same container for reference:
![image](https://user-images.githubusercontent.com/12109622/61859972-d6674200-aed1-11e9-8d8b-951797fdd354.png)

**Comment by egmontkob** [comment] 2019-07-25 12:20
Hi,

This looks like a duplicate of #1991.

**Comment by BladeMF** [comment] 2019-07-25 14:26
Yes, the artifact look the same and in the same place. I did not do any special settings though, if that matters.

**Comment by zadjii-msft** [comment] 2019-07-25 14:50
Thanks for the report and special thanks to @egmontkob for finding the dupe :) Since it's a dupe I'll go ahead and close it.

**Closed by zadjii-msft** 2019-07-25 14:50 UTC
Labels: Needs-Triage, Resolution-Duplicate
