### ISSUE TITLE
Error 9009 when exit after an invalid command

### ISSUE THREAD

**Issue by josecuevas72** [microsoft/terminal#6518] opened 2020-06-15 17:19 UTC
After executing an invalid command and then execute exit command, it gives this error: [Proceso terminado con el código 9009]

Microsoft Windows [Versión 10.0.19041.329]
(c) 2020 Microsoft Corporation. Todos los derechos reservados.

C:\Users\User>lñkjasdf
"lñkjasdf" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.

C:\Users\User>exit

[proceso terminado con el código 9009]

**Comment by DHowett** [comment] 2020-06-15 17:23
Hey there! This is, unfortunately, by design; it's highly conserved across different types of shells (bash, zsh, powershell and CMD all do the same thing) and the behavior of not closing the tab is in line with Ubuntu's terminal: https://github.com/microsoft/terminal/issues/4223#issuecomment-574834181

**Closed by DHowett** 2020-06-15 17:23 UTC
Labels: Needs-Tag-Fix, Needs-Triage
