### ISSUE TITLE
Build Failed

### ISSUE THREAD

**Issue by esarearthur** [microsoft/Terminal#596] opened 2019-05-08 19:26 UTC
Build FAILED.

"C:\Users\Ronald Arthur\Documents\Drone Technologies\Terminal\openconsole.sln" (Build target) (1) ->
"C:\Users\Ronald Arthur\Documents\Drone Technologies\Terminal\src\host\exe\Host.EXE.vcxproj.metaproj" (default target) (2) ->
"C:\Users\Ronald Arthur\Documents\Drone Technologies\Terminal\src\host\exe\Host.EXE.vcxproj" (default target) (4) ->
"C:\Users\Ronald Arthur\Documents\Drone Technologies\Terminal\src\server\lib\server.vcxproj" (default target) (13) ->
(Lib target) ->
  ApiMessageState.obj : warning LNK4221: This object file does not define any previously undefined public symbols, so it will not be used by any link operation that consumes this library [C
:\Users\Ronald Arthur\Documents\Drone Technologies\Terminal\src\server\lib\server.vcxproj]

"C:\Users\Ronald Arthur\Documents\Drone Technologies\Terminal\openconsole.sln" (Build target) (1) ->
"C:\Users\Ronald Arthur\Documents\Drone Technologies\Terminal\src\host\exe\Host.EXE.vcxproj.metaproj" (default target) (2) ->
"C:\Users\Ronald Arthur\Documents\Drone Technologies\Terminal\src\host\exe\Host.EXE.vcxproj" (default target) (4) ->
"C:\Users\Ronald Arthur\Documents\Drone Technologies\Terminal\src\terminal\adapter\lib\adapter.vcxproj" (default target) (14) ->
  tracing.obj : warning LNK4221: This object file does not define any previously undefined public symbols, so it will not be used by any link operation that consumes this library [C:\Users\
Ronald Arthur\Documents\Drone Technologies\Terminal\src\terminal\adapter\lib\adapter.vcxproj]
  telemetry.obj : warning LNK4221: This object file does not define any previously undefined public symbols, so it will not be used by any link operation that consumes this library [C:\User
s\Ronald Arthur\Documents\Drone Technologies\Terminal\src\terminal\adapter\lib\adapter.vcxproj]

"C:\Users\Ronald Arthur\Documents\Drone Technologies\Terminal\openconsole.sln" (Build target) (1) ->
"C:\Users\Ronald Arthur\Documents\Drone Technologies\Terminal\src\host\ft_uia\Host.Tests.UIA.csproj.metaproj" (default target) (34) ->
"C:\Users\Ronald Arthur\Documents\Drone Technologies\Terminal\src\host\ft_uia\Host.Tests.UIA.csproj" (default target) (37) ->
(PostBuildEvent target) ->
  C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(5158,5): error MSB3073: The command "copy C:\Users\Ronald Arthur\
Documents\Drone Technologies\Terminal\\dep\WinAppDriver\* C:\Users\Ronald Arthur\Documents\Drone Technologies\Terminal\\bin\x64\Debug\\" exited with code 1. [C:\Users\Ronald Arthur\Document
s\Drone Technologies\Terminal\src\host\ft_uia\Host.Tests.UIA.csproj]

"C:\Users\Ronald Arthur\Documents\Drone Technologies\Terminal\openconsole.sln" (Build target) (1) ->
"C:\Users\Ronald Arthur\Documents\Drone Technologies\Terminal\src\cascadia\TerminalCore\lib\TerminalCore-lib.vcxproj.metaproj" (default target) (41) ->
"C:\Users\Ronald Arthur\Documents\Drone Technologies\Terminal\src\cascadia\TerminalSettings\TerminalSettings.vcxproj" (default target) (42) ->
(PreBuildEvent target) ->
  C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(128,5): error MSB3073: The command " [C:\Users\Ronald Arthur\Document
s\Drone Technologies\Terminal\src\cascadia\TerminalSettings\TerminalSettings.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(128,5): error MSB3073:         if not exist C:\Users\Ronald Arthur\Docu
ments\Drone Technologies\Terminal\x64\Debug\TerminalSettings mkdir C:\Users\Ronald Arthur\Documents\Drone Technologies\Terminal\x64\Debug\TerminalSettings [C:\Users\Ronald Arthur\Documents\
Drone Technologies\Terminal\src\cascadia\TerminalSettings\TerminalSettings.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(128,5): error MSB3073:        [C:\Users\Ronald Arthur\Documents\Drone T
echnologies\Terminal\src\cascadia\TerminalSettings\TerminalSettings.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(128,5): error MSB3073: :VCEnd" exited with code 3. [C:\Users\Ronald Art
hur\Documents\Drone Technologies\Terminal\src\cascadia\TerminalSettings\TerminalSettings.vcxproj]

"C:\Users\Ronald Arthur\Documents\Drone Technologies\Terminal\openconsole.sln" (Build target) (1) ->
"C:\Users\Ronald Arthur\Documents\Drone Technologies\Terminal\src\cascadia\TerminalControl\TerminalControl.vcxproj.metaproj" (default target) (43) ->
"C:\Users\Ronald Arthur\Documents\Drone Technologies\Terminal\src\cascadia\TerminalConnection\TerminalConnection.vcxproj" (default target) (44) ->
  C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(128,5): error MSB3073: The command " [C:\Users\Ronald Arthur\Document
s\Drone Technologies\Terminal\src\cascadia\TerminalConnection\TerminalConnection.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(128,5): error MSB3073:         if not exist C:\Users\Ronald Arthur\Docu
ments\Drone Technologies\Terminal\x64\Debug\TerminalConnection mkdir C:\Users\Ronald Arthur\Documents\Drone Technologies\Terminal\x64\Debug\TerminalConnection [C:\Users\Ronald Arthur\Docume
nts\Drone Technologies\Terminal\src\cascadia\TerminalConnection\TerminalConnection.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(128,5): error MSB3073:        [C:\Users\Ronald Arthur\Documents\Drone T
echnologies\Terminal\src\cascadia\TerminalConnection\TerminalConnection.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(128,5): error MSB3073: :VCEnd" exited with code 3. [C:\Users\Ronald Art
hur\Documents\Drone Technologies\Terminal\src\cascadia\TerminalConnection\TerminalConnection.vcxproj]

    3 Warning(s)
    3 Error(s)

**Comment by zadjii-msft** [comment] 2019-05-08 19:27
I'm pretty sure this is a dupe of #438

**Closed by zadjii-msft** 2019-05-08 19:28 UTC
