### ISSUE TITLE
Can't scroll

### ISSUE THREAD

**Issue by letanloc1998** [microsoft/terminal#2203] opened 2019-08-02 04:55 UTC
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18362.239]
Windows Terminal version (if applicable):

Any other software?
```

# Steps to reproduce
Can't scroll

# Expected behavior
Can scroll

# Actual behavior
Can't scroll

**Comment by zadjii-msft** [comment] 2019-08-02 13:44
You're going to have to give us more info here. Is this in the console window (cmd.exe, powershell.exe, wsl.exe) or the Windows Terminal?

What command are you running that you can't scroll the output of.

Are you using a mouse, a trackpad, touch?

There's literally no info here, so I'm closing this until I get some information we can work with. If I get some repro steps, I'll re-open this.

**Closed by zadjii-msft** 2019-08-02 13:44 UTC
Labels: Needs-Tag-Fix, Needs-Triage

**Comment by mkielar** [comment] 2019-08-09 22:16
I can reproduce this on `0.3.2171.0`
I'm using a Dell XPS from 2010 with Synaptics Touchpad. Scrolling works only if i move the cursor to right edge of the window, so that I make the scroll bar appear, then click & drag on the scrollbar.

However, when I try to do _double-finger_ scroll on the touchpad, then no luck. Tried with `wsl` and `powershell`, both do not work.

**Comment by archongum** [comment] 2019-08-28 02:01
- Windows 10 build 18965.1000
- WT 0.4.2382.0

Can scroll using mouse or touchpad without WT which opening by `ctrl + R` then `powshell` or `cmd` or `bash`.

Can't scroll using mouse or touchpad with WT but scroll bar works.

(I notice this issue since WT first preview release, but I don't use WT at work so I didn't report this)

![Snipaste_2019-08-28_09-58-50](https://user-images.githubusercontent.com/20929338/63820060-748b7380-c97a-11e9-8e63-0a2e84dc0740.jpg)

**Comment by archongum** [comment] 2019-08-28 14:06
@zadjii-msft I just tried install WT in my other PC and mouse scrolling works. Maybe I try re-install for my problematical PC first.

**Comment by archongum** [comment] 2019-10-25 08:11
For posterity's sake: My problem solved as https://github.com/microsoft/terminal/issues/2594#issuecomment-546244116
