### ISSUE TITLE
Setting a font in settings.json

### ISSUE THREAD

**Issue by jromero2k** [microsoft/terminal#6285] opened 2020-06-01 01:16 UTC
# Environment

Windows build number: Version 10.0.18363.778
Windows Terminal version (if applicable): 1.0.1401.0

# Steps to reproduce

1. Install `ttc-iosevka-curly-3.1.0.zip` fonts in Windows
2. Verify it works properly in any other app
3. In `settings.json`, set `"fontFace": "Iosevka Term Curly Light"`

# Expected behavior

`Iosevka Term Curvy Light` is selected as active font, or some kind of error is reported so user can know what's that Terminal didn't like

# Actual behavior

Terminal reverts to the default (non-ligature) font, without any explanation (or logging that I know of)

**Comment by skyline75489** [comment] 2020-06-01 05:12
The reason why it uses the default font would likely be that the font name is not recognized. Yeah you're right. There's currently no explanation when this happens. Seems a little confusing.

**Comment by jromero2k** [comment] 2020-06-01 05:19
As far as I can tell, `Iosevka Term Curly Light` is the proper name for the font, at least as reported by `Settings|Font settings` in Windows.. 

Having `
"fontFace": "Iosevka Term Curly" 
"fontWeight": "200"
` like in VSCode would be even better, but that's not available (yet?)

**Comment by WSLUser** [comment] 2020-06-02 16:36
fontWeight will be in Preview (it's in master if you want to build it).

**Comment by DHowett** [comment] 2020-06-05 01:41
I believe the root of the issue is that we specify font _family_ names and call them font _faces_. For now, `fontFace: Iosevka Term Curly` should suffice, and font weight will come out soon. For fixing the root cause, /dup #1163.

**Closed by DHowett** 2020-06-05 01:41 UTC
Labels: Needs-Tag-Fix, Needs-Triage
