### ISSUE TITLE
A scrollbar has gaps in Terminal, but is correct in Console

### ISSUE THREAD

**Issue by mobluse** [microsoft/terminal#8614] opened 2020-12-18 16:03 UTC
# Environment

```none
Windows build number: Win32NT             10.0.19042.0 Microsoft Windows NT 10.0.19042.0
Windows Terminal version (if applicable): 1.4.3243.0 from Microsoft Store

Any other software? Windows Console (included in Windows 10)
```

# Steps to reproduce

Start Windows Terminal (defaults to PowerShell) and Windows PowerShell (that runs in Windows Console) and log in using `ssh` in PowerShell to a Raspberry Pi with BOINC and `boinctui` and run that in each.   

# Expected behavior

That the scrollbar should be without gaps in Terminal like it is in Console. Console here:
![pi@aeblapi1_ ~ 2020-12-18 16_24_42](https://user-images.githubusercontent.com/5777329/102633774-2c84f700-4151-11eb-8e3d-e95553540087.png)
(The Xbox Game Bar using Alt+Win+PrtSc cut out the lower part of the Window with the status bar, but it is there in reality.)
# Actual behavior

The scrollbar has gaps in Terminal. Terminal with original settings (generated by Windows Terminal 1.4.3141.0) here:
![pi@aeblapi1_ ~ 2020-12-18 16_23_55](https://user-images.githubusercontent.com/5777329/102633901-5d652c00-4151-11eb-8637-127fd4d53d3e.png)

**Comment by zadjii-msft** [comment] 2020-12-18 16:18
This almost certainly has to do with the way we're scaling box-drawing characters. I'm sure there's a dupe somewhere, @miniksa can you help find it?

**Comment by j4james** [comment] 2020-12-18 22:28
I believe #5816 was originally where the remaining vertical banding issues were being tracked, but that was later marked as dupe of #6161, which covers a broader range of concerns with the block and box-drawing characters.

**Comment by zadjii-msft** [comment] 2020-12-21 12:18
Okay yep, that's the one I was thinking of. Thanks!

/dup #6161

**Closed by zadjii-msft** 2020-12-21 12:18 UTC
Labels: Needs-Tag-Fix, Needs-Triage
