### ISSUE TITLE
Neovim view doesn't adapt on window resizing

### ISSUE THREAD

**Issue by mattiatomeo** [microsoft/terminal#3263] opened 2019-10-20 10:48 UTC
# Environment

```none
Windows build number: 10.0.18362.0
Windows Terminal version: 0.5.2762.0

Neovim version: 0.4.2
```

# Steps to reproduce

Open neovim from the terminal, then change the size of the window.

# Expected behavior

I expect that neovim view adapt with the new window size

# Actual behavior

If I open neovim and I change the window size, neovim view is extended only respect to the horizontal direction. 

![resizing-shortcut](https://media.giphy.com/media/lmw6mwroynSfDR4Je8/giphy.gif)
![resizing-no-shortcut](https://media.giphy.com/media/h3jNcGKjapKBiJsUae/giphy.gif)

This issue happens only by using Windows Terminal. If I use Powershell, everything works as expected.

**Comment by DHowett-MSFT** [comment] 2019-10-23 20:13
This strikes me as being a neovim issue. I wonder how they're checking for resizing events?

Actual normal plain _vim_ works just fine for me. Does it work for you?

**Comment by mattiatomeo** [comment] 2019-10-23 22:21
I tried with vim, and resizing works fine.

**Comment by parkovski** [comment] 2019-10-26 03:34
I think this is the libuv bug. I patched mine and it works fine - see https://github.com/parkovski/libuv/commit/c71c31816ecf9a1b3b41c2b500b0976aad7aea0b which I really should send a PR for.

**Comment by zadjii-msft** [comment] 2019-10-28 13:57
I'm gonna close this as it seems the issue is upstream. Thanks for investigating @parkovski!

**Closed by zadjii-msft** 2019-10-28 13:57 UTC
Labels: Needs-Attention, Needs-Tag-Fix, Needs-Triage

**Comment by jantari** [comment] 2020-02-23 15:26
I am not sure this really is (only) a neovim issue, because it does not happen in conhost, only wt.  
If it turns out wt is not innocent in this, I feel like this is a must-fix before v1.0 GA.

See:
![animation-smaller2](https://user-images.githubusercontent.com/25607767/75114749-0853a900-5659-11ea-8fa5-53de7664e8a6.gif)

**Comment by npaulcarlson** [comment] 2020-09-23 20:35
This should not be closed. I'm having the same issue at the moment. See the screencapture from @jantari 

Here's nvim's internal doc on how it gets window-size:
![neovim_window-size_doc](https://user-images.githubusercontent.com/68175317/94065759-6340b080-fda0-11ea-9edc-4f668c067f7b.png)

**Comment by jantari** [comment] 2020-09-24 07:56
@npaulcarlson Whether it is a WT issue or not, I'm not qualified to say. But I can give you the tip that it works fine with the 0.5.0 prerelease versions of neovim. I'm using `NVIM v0.5.0-558-g6d1404faf` specifically right now and this problem is fixed there. You just cannot use 0.4.3 (and I don't know about the recently-released stable 0.4.4 as I haven't tried it)

**Comment by fabiomarreco** [comment] 2020-11-12 22:04
@jantari is correct. It works on v0.5.*, but it does not work on 0.4.4

**Comment by bradphelan** [comment] 2021-06-18 16:12
Can verify that installing the 0.5 beta fixes the problem

```
choco install neovim --pre 
```

on windows
