### ISSUE TITLE
Not Able to Change Font

### ISSUE THREAD

**Issue by MeRahulAhire** [microsoft/terminal#3250] opened 2019-10-18 20:22 UTC
how the heck im able to change the font preference to get my zsh terminal work flawlessly with agnoster theme

**Comment by bitcrazed** [comment] 2019-10-18 20:27
Please complete the issue template when submitting issues - the template gives us some of the info we need to provide useful responses.

For example:

What version of the Terminal are you running, and on what OS version?
What are you seeing (annotated screenshots help)
What do you expect to see (again, annotated screenshots help)
How do we easily repro the problem you're seeing?

**Comment by DHowett-MSFT** [comment] 2019-10-21 19:46
This could be a /dupe of #3257.

**Closed by DHowett-MSFT** 2019-10-21 19:46 UTC
Labels: Area-Fonts, Area-Rendering, Needs-Author-Feedback, Needs-Tag-Fix
