### ISSUE TITLE
Cannot input characters from Windows+.

### ISSUE THREAD

**Issue by leduyquang753** [microsoft/terminal#3042] opened 2019-10-03 09:37 UTC
# Environment

```Windows 10
Windows build number: 18875
Windows Terminal version (if applicable): 0.5.2681.0
```

# Steps to reproduce

1. Open any console in Terminal.
2. Press `Windows+.`.
3. Try inputting characters from the selection panel by clicking on them.

# Expected behavior

Clicked characters should be entered into the console window.

# Actual behavior

The characters are not entered into the console window.

**Comment by zadjii-msft** [comment] 2019-10-03 13:41
Thanks for the report! This is actually a duplicate of #2213, which covers not only the CJK IME's, but also the <kbd>Win+.</kbd> "emoji" IME. 

/dup #2213

**Closed by zadjii-msft** 2019-10-03 13:41 UTC
Labels: Needs-Tag-Fix, Needs-Triage
