### ISSUE TITLE
Terminal does not regenerate files; causes crash-on-start

### ISSUE THREAD

**Issue by mburszley** [microsoft/terminal#5417] opened 2020-04-19 20:58 UTC
# Environment

```none
Windows build number: 10.0.18363.0
Windows Terminal version (if applicable): v0.10

Any other software?
```

# Steps to reproduce

Remove the `LocalState` folder:

```powershell
Remove-Item -Path "${Env:LOCALAPPDATA}\Packages\Microsoft.WindowsTerminal_8wekyb3d8bbwe\LocalState" -Recurse -Force
```

# Expected behavior

`LocalState` should regenerate.  I wanted to refresh my `profiles.json` and assumed that Terminal would create a new default.

# Actual behavior

Without `LocalState\profiles.json`, Terminal just crashes on start even when trying to use `wt -h`.

**Comment by DHowett-MSFT** [comment] 2020-04-19 22:18
Huh, good catch. I don't think applications are supposed to be run with their entire package config directories deleted . . . can you see if making a new `LocalState` directory fixes it?

**Comment by DHowett-MSFT** [comment] 2020-04-19 22:19
(Those directories are really owned by the system, technically, and we're to live _inside_ them)

**Comment by mburszley** [comment] 2020-04-19 22:33
@DHowett-MSFT The only file there was `profiles.json` so I figured it was safe in case other files got generated.  Recreating it does appear to resolve the problem and `profiles.json` appears.

**Comment by DHowett-MSFT** [comment] 2020-04-24 01:06
So, I've got some bad news: _terminal already tries to make the settings folder if it's been deleted._ We ask the system where it's supposed to be, then make it if it doesn't exist (even if it does, honestly.)

https://github.com/microsoft/terminal/blob/a76cee1d98c4368815013eaccc09c6f0d3fe62e9/src/cascadia/TerminalApp/CascadiaSettingsSerialization.cpp#L839-L855

I might just have to close this one out as "by design, external" ☹️
Sorry. The app platform isn't terrifically robust here.

**Closed by DHowett-MSFT** 2020-04-24 01:06 UTC
Labels: Area-Settings, Issue-Bug, Product-Terminal, Severity-Crash
