### ISSUE TITLE
Command Prompt text becomes black when scrolling

### ISSUE THREAD

**Issue by miniksa** [microsoft/terminal#799] opened 2019-05-14 22:28 UTC
Ported from customer feedback bug MSFT:21393297.

I haven't reproduced or investigated this yet.

> 1. use command prompt enough to get multiple pages of text
> 2. scroll up to previous text
> when scrolling up, some of the text will become black, making it unreadable. Scrolling back down may or may not bring it back. Highlighting the black space shows the text exists and will bring it back to white on black.

**Comment by zadjii-msft** [comment] 2022-08-16 11:25
Hey so we ported this out of the OS issue tracker like, 3 years ago. It was specifically referencing the vintage console window, not the Terminal window. That being said, we haven't gotten more reports of this for the _console_ since then. There also wasn't more info in the original issue (internally) which we could really use to investigate. 

I'm inclined to close this out. Niksa can veto if he wants.

**Closed** 2022-08-23 16:03 UTC
Labels: Product-Conhost, Needs-Repro, Area-Rendering, Issue-Bug, Needs-Author-Feedback, No-Recent-Activity

**Comment by nbstrong** [comment] 2022-08-24 19:55
Be awesome if this could be re-opened.

I am also getting this issue with Windows Terminal when running command prompt.

Specifically I have 999999 history size. I am outputting a ton of data from a python script to the terminal screen. When the script is done if I try to scroll up to view the data, the terminal window goes black.

If I hit enter, the data re-appears but I cannot scroll up.

**Comment by nbstrong** [comment] 2022-08-24 19:58
Furthermore, CLS to clear the screen crashes Windows Terminal.

**Comment by zadjii-msft** [comment] 2022-08-24 20:04
@nbstrong Can you file a new issue actually? This one was ported from an internal database like, years ago, and ultimately probably has a different root cause. There's a couple other threads that sound familiar on the repo, #13499 comes to mind. 

A screen recording might also be helpful here.

Thanks!
