### ISSUE TITLE
Add Padding to the backgroundImage suite of configuration settings

### ISSUE THREAD

**Issue by JimF42** [microsoft/terminal#9150] opened 2021-02-13 18:49 UTC
# Description of the new feature/enhancement
I use the `backgroundImage` and `backgroundImage..`. set of configuration settings, but I would also like to see a setting like `backgroundImagePadding...` (or Margin, or some such).

Yes, this is purely an aesthetic request as the point of the Padding would be to keep the icon off the edges the the screen

# Proposed technical implementation details (optional)
I don't have a single implementation in mind, but I can see it going two different ways. A set of four new fields like:

```
"backgroundImagePaddingLeft" : nnn,
"backgroundImagePaddingTop" : nnn,
"backgroundImagePaddingRight" : nnn,
"backgroundImagePaddingBottom" : nnn
```

Or, it could be implemented like this
```
"backgroundImagePadding" : {
    "Left": nnn,
    "Top": nnn,
    "Right": nnn,
    "Bottom": nnn
}
```

Of course, "backgroundImageAlignment" would take precedent, then the padding would be applied. If all the padding values were to be supplied (Left, Top, Right, Bottom), then at most only 2 values would be used. For example, if the alignment was bottomRight, then the Left and Top values would be ignored.

Honestly, I don't know how padding will be applied if the alignment is Center.

Finally, I also don't know what a good unit would be for the padding values. Perhaps a generic unit like WPF uses by default.

**Comment by DHowett** [comment] 2021-02-13 21:10
Thanks for the request. This looks like a /duplicate of #1726 + #2370 (combined)

**Closed by DHowett** 2021-02-13 21:10 UTC
Labels: Issue-Feature, Needs-Tag-Fix, Needs-Triage
