### ISSUE TITLE
Sometimes terminal isn't rendering after maximize from taskbar

### ISSUE THREAD

**Issue by Mart-Bogdan** [microsoft/terminal#3692] opened 2019-11-25 13:13 UTC
Terminal isn't drawing correctly after maximize from minimized state sometimes. Not 100% of cases.

# Environment

```none
Windows build number: Version 10.0.18362.476
Windows Terminal version (if applicable): 0.6.2951.0

Using it for WSL 1
```

# Steps to reproduce

1. minimize terinal
2. expand terminal

# Expected behavior

terminal being drawn correctly:
![image](https://user-images.githubusercontent.com/775038/69543060-7377db80-0f95-11ea-8b9b-a376f683085a.png)

# Actual behavior

content of the background window is being painted (in this case Desktop)
![image](https://user-images.githubusercontent.com/775038/69543230-d1a4be80-0f95-11ea-9922-5e4e75d7d4b0.png)

If I resize the window it goes back to the norm.

**Comment by Mart-Bogdan** [comment] 2019-11-25 13:14
Parts of screenshot ar blurred for privacy, the actual app wasn't blurring content of background window, just rendered header bar, and not rendered content.

**Comment by DHowett-MSFT** [comment] 2019-11-25 20:08
This one looks like a /dupe of #3446. Thanks!

**Closed by DHowett-MSFT** 2019-11-25 20:08 UTC
Labels: Needs-Tag-Fix, Needs-Triage
