### ISSUE TITLE
Feature Request > Tab Switching

### ISSUE THREAD

**Issue by ProHackTech** [microsoft/terminal#2222] opened 2019-08-03 17:24 UTC
# Description of the new feature/enhancement
Allow the users to switch tabs easily like in Edge or other applications that allow multiple tabs. It will be very helpful to be able to switch tabs. This is possible in many linux terminals and helps with activity management, where the user drags the tabs that have long lasting processes to the end.
Following image describes the feature:

<img src="https://media.giphy.com/media/eMsFXurPjebO1700am/giphy.gif" alt="Tab Switching Demonstration">

# Proposed technical implementation details (optional)
When there is a mouse down event on a tab and the the mouse key is left, then allow the user to switch tabs when mouse is moved. GIF image attached for demonstration.

**Comment by Johannestegner** [comment] 2019-08-03 19:07
A feature request for the same functionality have been posted here: #2215

**Comment by DHowett-MSFT** [comment] 2019-08-05 04:57
This is a duplicate of #973.

**Closed by DHowett-MSFT** 2019-08-05 04:57 UTC
Labels: Issue-Feature, Needs-Tag-Fix, Needs-Triage
