### ISSUE TITLE
Sometimes there is "Open with windows-terminal" when I right-click a folder but sometimes there isn't

### ISSUE THREAD

**Issue by 1900011604** [microsoft/terminal#7536] opened 2020-09-04 15:43 UTC
I installed windows terminal on Microsoft Store on Win 10 2004 (latest)

there is "Open with windows-terminal" when I right-click a folder

re-installed Win 10 2004 --> install windows terminal on Microsoft Store

there isn't "Open with windows-terminal" when I right-click a folder

![image](https://user-images.githubusercontent.com/65082432/92258271-2738cf00-ef09-11ea-9d0f-82a3ebfd07eb.png)

**Comment by 1900011604** [comment] 2020-09-04 15:47
As I installed it via MS Store, there is no "ADD TO PATH" for me to choose

**Comment by DHowett** [comment] 2020-09-09 00:18
Is there a difference if you right-click in the empty space (background) or on a folder icon?

![image](https://user-images.githubusercontent.com/189190/92539724-2f3d8b00-f1f7-11ea-82a0-05abeb4e8be3.png)

![image](https://user-images.githubusercontent.com/189190/92539747-411f2e00-f1f7-11ea-8398-0923e2fa15c9.png)

**Comment by 1900011604** [comment] 2020-09-09 02:01
yes yes you got the point!

**Comment by DHowett** [comment] 2020-09-10 01:25
Thank you! This is a /duplicate of #6414. We had to remove the option sometimes because of a Windows bug. 😦

**Closed by DHowett** 2020-09-10 01:25 UTC
Labels: Needs-Attention, Needs-Tag-Fix, Needs-Triage
