### ISSUE TITLE
Uninstalling Windows Terminal removes context menu entries for Windows Terminal Preview

### ISSUE THREAD

**Issue by microrache** [microsoft/terminal#10681] opened 2021-07-16 07:22 UTC
### Windows Terminal version (or Windows build number)

1.9.1942.0

### Other Software

Windows Terminal Preview 1.10.1933.0

### Steps to reproduce

I installed both, Windows Terminal (v1.9.1942.0) and Windows Terminal Preview (v1.10.1933.0). After uninstalling Windows Terminal (by right-click in start menu -> Uninstall), I miss all the Windows Explorer context menu entries for Windows Terminal Preview. 

### Expected Behavior

Only the context menu entries for Windows Terminal should have been removed.

### Actual Behavior

All context menu entries for both, Windows Terminal and Windows Terminal Preview, have been removed.

**Comment by DHowett** [comment] 2021-07-22 20:15
Thanks for the report! This looks like either highly related to or a /duplicate of #9857

**Closed by DHowett** 2021-07-22 20:16 UTC
Labels: Needs-Tag-Fix, Needs-Triage, Product-Terminal
