### ISSUE TITLE
Bug Report: Option not working? 

### ISSUE THREAD

**Issue by stark-zhang** [microsoft/terminal#2469] opened 2019-08-18 14:26 UTC
# Environment
 
Windows 10 Pro 18956 Insider Preview

# Steps to reproduce

The option **"closeOnExit"** will be invalid with only a tab running, and it could be reproduce with multi-tabs running occationally.

# Expected behavior
Fix it
# Actual behavior

There is an option named "closeOnExit", but it seems to be invalid after inputting `exit` command, and the windows would not be closed. 

Following content is a part of my configuration file about powershell, it might help you to resolve it.

```json
{
            "startingDirectory": "%USERPROFILE%",
            "guid": "{95e05ea2-6bad-4896-bcdf-a4f96c885cc8}",
            "name": "PowerShell",
            "background": "#002731",
            "colorscheme": "Campbell",
            "historySize": 9001,
            "snapOnInput": true,
            "cursorColor": "#FFFFFF",
            "cursorShape": "bar",
            "commandline": "powershell.exe",
            "fontFace": "Consolas",
            "fontSize": 12,
            "acrylicOpacity": 0.5,
            "useAcrylic": true,
            "closeOnExit": true,
            "padding": "0, 0, 0, 0",
            "icon": "ms-appdata:///roaming/icons/powershell_32px.png"
        }
```

**Comment by zadjii-msft** [comment] 2019-08-19 14:09
Okay I'm going to need an actual walkthrough of repro steps, and expected/actual behavior. Right now it's really hard to understand what you're doing and what's wrong vs what's expected. For example:

### Repro steps
1. set `closeOnExit` to true for the "powershell" profile
2. Open a powershell tab
3. type exit

### Expected Behavior
The tab closes

### Actual Behavior
The entire UI hangs.

###### (if what you're trying to report is _exactly_ what I've described above, then this is a dupe of #2185.)

**Comment by stark-zhang** [comment] 2019-08-21 22:59
Okay, you are right, I am confused by this problem
When will you fix it?

**Closed** 2019-08-22 21:56 UTC
Labels: Needs-Attention, Needs-Tag-Fix, Needs-Triage
