### ISSUE TITLE
Windows terminal + WSL2 should render symbols that kind.sigs.k8s.io properly

### ISSUE THREAD

**Issue by pasoni** [microsoft/terminal#3141] opened 2019-10-10 00:00 UTC
<img width="365" alt="windows-terminal-with-kind" src="https://user-images.githubusercontent.com/45770325/66528613-725a2000-eab5-11e9-839f-7b2cad40dc10.png">

# Environment

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
19000.1000.amd64fre.vb_release_base.191007-1444

Windows Terminal version (if applicable):
  Windows Terminal (Preview)
  Version: 0.5.2762.0


Any other software?
```
WSL2 
Ubuntu 18.04
kind setup using https://kind.sigs.k8s.io/

# Steps to reproduce
Set up WSL2
Setup kind
and create cluster using "kind create cluster"

# Expected behavior
Windows Terminal should render symbols and fonts correctly

# Actual behavior
Windows Terminal renders image icon at the end of 1st line small and with big ?

**Comment by DHowett-MSFT** [comment] 2019-10-10 00:16
@pasoni Copying from the internal thread on the matter:

> include a simplified repro of the issue (by capturing the glyph or something into a file and type/catting it back out)?

This bug report isn't very helpful without us being able to tell what you're printing to the screen. Installing `kind`, whatever it is, is a pretty big ask. :smile:

**Comment by j4james** [comment] 2019-10-10 09:09
Here are a couple of examples I found that didn't work:

* U+1F5BC `🖼` (Framed Picture)
* U+1F579 `🕹️` (Joystick)

If you make the font size really large, it looks like it is actually showing the correct character, just very small, and then also followed by the replacement character `�`. So maybe this is related to #900.

**Comment by DHowett-MSFT** [comment] 2019-10-10 19:39
Thanks @j4james for digging up the codepoints. This does look like a /dupe of #900.

**Closed by DHowett-MSFT** 2019-10-10 19:39 UTC
Labels: Needs-Tag-Fix, Needs-Triage
