### ISSUE TITLE
Underline ANSI escape sequence does not work with space before reset sequence

### ISSUE THREAD

**Issue by patriksvensson** [microsoft/terminal#6976] opened 2020-07-20 00:28 UTC
I've noticed that using ANSI escape sequence `ESC[4mFOO ESC[0m` does not underline the text as expected. 
If I remove the space before the reset code `ESC[0m`, it works as expected.

This works as expected in `cmd.exe`/`powershell.exe` (which I assume both uses conhost), `conemu` and `cmder`.

# Environment

```none
Windows build number: Microsoft Windows NT 10.0.19041.0
Windows Terminal version (if applicable): 1.0.1811.0
```

# Steps to reproduce

1. Open PowerShell console in Windows Terminal
2. Run `Write-Host "$([char]27)[1mBold$([char]27)[0m $([char]27)[4mUnderline$([char]27)[0m Normal"`
    *This underlines the text "Underline" as expected.*
3. Run `Write-Host "$([char]27)[1mBold $([char]27)[0m$([char]27)[4mUnderline$([char]27)[0m Normal"`
    *This fails with underlining the text.*

They say that a picture is worth a thousand words, so here's a screenshot as well of the repro.

![image](https://user-images.githubusercontent.com/357872/87888639-45686f80-ca2e-11ea-93e8-9190ca76ec54.png)

# Expected behavior

In the third step in the repro, I would expect the text `Underline` to be underlined.

# Actual behavior

The text `Underline` is not underlined.

**Comment by DHowett** [comment] 2020-07-20 00:33
I _believe_ this was fixed in #6506 (I know it says color, but it applies to all attributes.). I can't reproduce this, or a very similar vim issue (changing colors/changing rendition but not toggling underline turned underline off), after 6506 with the about-to-come-out 1.2 previe

**Comment by DHowett** [comment] 2020-07-20 00:34
If you can build from source, would you mind validating that? If not, no big deal :smile:

**Comment by DHowett** [comment] 2020-07-20 00:35
(For now, /dup #3076)

**Closed by DHowett** 2020-07-20 00:35 UTC
Labels: Needs-Author-Feedback, Needs-Tag-Fix, Needs-Triage

**Comment by patriksvensson** [comment] 2020-07-20 00:39
@DHowett I can reproduce #3076 (which have been fixed) so hopefully, that fix will fix my problem. I will build Windows Terminal from the source tomorrow and verify it.

![image](https://user-images.githubusercontent.com/357872/87889485-2835a000-ca32-11ea-9959-c7183bfc3ad3.png)
