### ISSUE TITLE
Starting directory + other

### ISSUE THREAD

**Issue by ssccoouutt** [microsoft/terminal#4035] opened 2019-12-21 15:07 UTC
When I set 'startingDirectory' to 'null' (to open the folders directory by Ctrl+L -> wt.exe, except the 'Run' (Win+R) option), I noticed that when I just start wt.exe (from Start Menu or taskbar), it opens in 'C:\WINDOWS\System32' directory. 
The question is how can I cause the wt open the '%USERPROFILE%' directory, both open the folder directions by Ctrl+L -> wt.exe?

**Comment by mkitzan** [comment] 2019-12-27 21:17
This might be a duplicate of #878. @ssccoouutt, could you check that issue?

**Comment by zadjii-msft** [comment] 2019-12-30 15:21
Yea this is definitely a dupe of #878, and there's more details in #3547 as well. Thanks!

/dupe #878

**Closed by zadjii-msft** 2019-12-30 15:21 UTC
Labels: Issue-Feature, Needs-Tag-Fix, Needs-Triage
