### ISSUE TITLE
Can't type inside Windows Terminal PowerShell or Command Prompt

### ISSUE THREAD

**Issue by scotto88** [microsoft/terminal#7855] opened 2020-10-07 22:25 UTC
# Environment

```none
Windows build number:   Windows 10 Pro - 2004 | OS build:  19041.508
Windows Terminal version (if applicable):  1.3.2651.0

Any other software?
```

# Steps to reproduce

Can't type inside Windows Terminal PowerShell or Command Prompt
# Expected behavior

Should show the text characters I typed with my keyboard.

# Actual behavior

No text characters are displaying. Just the blinking cursor.

**Comment by DHowett** [comment] 2020-10-07 23:22
Have you disabled the "Touch Keyboard and Handwriting Panel Service"?

**Comment by scotto88** [comment] 2020-10-08 13:11
Yes, that service is showing Disabled.

**Comment by scotto88** [comment] 2020-10-08 13:28
I changed the service to Startup type: Manual and rebooted. I am now able to type in Windows Terminal. The service is "Touch Keyboard and Handwriting Panel Service" is showing running.

**Comment by DHowett** [comment] 2020-10-09 01:13
Thank you! This is a /duplicate of #4448.

**Closed by DHowett** 2020-10-09 01:13 UTC
Labels: Needs-Attention, Needs-Tag-Fix, Needs-Triage

**Comment by secretgspot** [comment] 2021-11-30 05:03
This is BS, why do I need to have "Touch Keyboard and Handwriting Panel Service" when I don't use touch or pen on my PC and my mouse/keyboard should be sufficient!  Is there some sort of malware/spyware running with "Touch Keyboard and Handwriting Panel Service" that it must work in order to capture my keystrokes and passwords?!

**Comment by zadjii-msft** [comment] 2021-11-30 12:18
Read that instead as the "Touch, Keyboard, and Handwriting Panel Service". It's responsible for shuttling input to applications on Windows. #9890 has more info on the inner working of what's going on there.
