### ISSUE TITLE
ASCII control characters/sequences in WSL Ubuntu

### ISSUE THREAD

**Issue by fatherofinvention** [microsoft/terminal#4072] opened 2019-12-28 19:02 UTC
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18363.535]
Windows Terminal version (if applicable): Version: 0.7.3451.0

Any other software?
Ubuntu: 18.04.3 LTS
Python: 3.6
VIT: 2.0
```

# Steps to reproduce

- Install Ubuntu 18.04.3 LTS from Microsoft Store
- Install Task Warrior
- Install VIT 2.0 (which is using the SI control character for formatting)

# Expected behavior

The SI character would render properly instead of an empty rectangle.

# Actual behavior

The attached screenshot shows how the [Shift In control character](https://en.wikipedia.org/wiki/Shift_Out_and_Shift_In_characters) is rendering in WSL Ubuntu, specifically inside of [Vit ](https://github.com/scottkosty/vit) which is written in Python running in Windows Terminal. The font in use is [Ubuntu Mono](https://fonts.google.com/specimen/Ubuntu+Mono).

`SI (0x0F, ^O) activates the G0 character set;`
[Source](http://man7.org/linux/man-pages/man4/console_codes.4.html)

I am not sure if this is a WSL issue, a Terminal issue, a code page issue, a font issue, or a Python issue. I am hoping someone more knowledgeable can comment on whether this is a fundamental limitation of WSL's support of control characters or if this can be resolved by changing a setting. I have tried numerous monospace fonts without any luck.

![SI-control-characters](https://user-images.githubusercontent.com/24985048/71548000-7bdc8100-295c-11ea-8ab8-cbd48f394436.jpg)

Thank you.

**Comment by DHowett-MSFT** [comment] 2019-12-28 19:28
This sounds like a /dupe of #3487

**Closed by DHowett-MSFT** 2019-12-28 19:28 UTC
Labels: Needs-Tag-Fix, Needs-Triage
