### ISSUE TITLE
When starting Azure Cloud Shell no "number" shows up to enter into devicelogin page

### ISSUE THREAD

**Issue by sloethen** [microsoft/terminal#3854] opened 2019-12-05 20:09 UTC
When I start a cloud shell session, the terminal tab prompts me with a message saying...

Got to this page, type in this number, you have 15 minutes...

but the number is blank.   Is there a setting I am missing?  is this a know issue?

**Comment by DHowett-MSFT** [comment] 2019-12-05 20:14
You may need to start the ACS connection with a wider window; sorry! This'll be addressed by /dup #780 (weird enough)

**Comment by DHowett-MSFT** [comment] 2019-12-05 20:14
(Root cause: the text gets cut off at the right edge of the window, and cannot be restored by resizing.)

**Closed by DHowett-MSFT** 2019-12-05 20:14 UTC
Labels: Needs-Tag-Fix, Needs-Triage

**Comment by sloethen** [comment] 2019-12-05 20:18
yep, that fixed it.  can I assume this is in the issue list to fix?
