### ISSUE TITLE
You have to double hit the key to get the chinese punctuation corretly in vim/neovim in this terminal!

### ISSUE THREAD

**Issue by zyy1998** [microsoft/terminal#4500] opened 2020-02-07 11:39 UTC
# Environment

```none
Windows build number: Microsoft Windows NT 10.0.18362.0
Windows Terminal version: v0.8.10261.0 and 2019/6/21 published on MS-Store
NeoVim version: 0.4.3
Input method editor: Microsoft Pinyin
```

# Steps to reproduce
1. Install vim/neovim
2. Open powershell in the terminal and type `nvim test.md`
3. Switch to Chinese input method editor
4. Feel free to type some Chinese punctuation like `，。？！（）` and you'll get what I say

# Expected behavior
If I just write in English in the terminal, it performs pretty well. And I have tested it in cmder and nvim-qt.exe, have no problem.
![20200207184039](https://user-images.githubusercontent.com/23515803/74022936-81a49800-49d9-11ea-9e77-70b370bdbac0.png)
_( BTW, nvim-qt is not a terminal actually )_

![20200207185123](https://user-images.githubusercontent.com/23515803/74023546-e3b1cd00-49da-11ea-9eb6-73842ea99a19.png)

# Actual behavior
In windows terminal, whatever I use nvim in powershell or vim in WSL bash, I have to hit the key twice in order to input the Chinese punctuation. So I pretty sure it's a bug of windows terminal.

More interested, you need not have to hit the same key twice, just hit whatever first and then hit what you want to input, it seems that the first key has been eaten by terminal.

Most interested is: I clicked some emoji in MS pinyin with the mouse, but it did not appear here immediately., when I typed some Chinese ( **NOT ENGLISH** ), all the emojis swarm into my terminal.

![20200207193010](https://user-images.githubusercontent.com/23515803/74026261-c4b63980-49e0-11ea-8f72-d782b4fb9251.png)

**Comment by DHowett-MSFT** [comment] 2020-02-07 17:10
Thanks for the report! This sounds like a /dupe of #3745

**Closed by DHowett-MSFT** 2020-02-07 17:10 UTC
Labels: Needs-Tag-Fix, Needs-Triage
