### ISSUE TITLE
Any Azure Pipeline CI build available?

### ISSUE THREAD

**Issue by warrenbuckley** [microsoft/Terminal#497] opened 2019-05-07 13:10 UTC
Rather than getting people to clone the repository and manually build this, that seems to require VS2017 & NOT VS2019 along with some other tooling/workflows installed too.

It would be great to have a link of a nightly or similar from Azure Pipelines of this pre-built for us, so we can download it without needing to re-install VS2017 etc..

**Comment by ptrstpp950** [comment] 2019-05-07 13:30
I'm trying to set up a build for a few hours - without luck yet :)

**Comment by nikanorov** [comment] 2019-05-07 13:37
It is could be build with VS2019. Check this: https://github.com/microsoft/Terminal/issues/461#issuecomment-489984588

**Comment by nikanorov** [comment] 2019-05-07 14:01
@warrenbuckley I'm all for it too! I do not know a lot about UWP and appx distribution options, maybe this is the reason we should wait for MS Store preview build.

**Comment by arukaen** [comment] 2019-05-07 14:23
+1 for pre-built packages. I don't really want to install a bunch of build tools just to try the new terminal. For that I stay on my Ubuntu desktop.

**Comment by vatsalyagoel** [comment] 2019-05-07 14:25
It is possible to install apps files outside of the store. The only problem is that the code will be signed using a self signed cert thus can't really be trusted

**Comment by zadjii-msft** [comment] 2019-05-07 14:33
Dupe of #468.
### There are no binaries to download quite yet. 

The Windows Terminal is in the _very early_ alpha stage, and not ready for the general public quite yet. If you want to jump in early, you can try building it yourself from source. 

Otherwise, you'll need to wait until Mid-June for an official preview build to drop.

**Closed** 2019-05-07 14:33 UTC
Labels: Resolution-Answered, Resolution-Duplicate
