### ISSUE TITLE
Windows Terminal Preview does not work with Visual Studio 2019.

### ISSUE THREAD

**Issue by TomsProject** [microsoft/terminal#10974] opened 2021-08-18 13:33 UTC
### Windows Terminal version (or Windows build number)

1.10.1933.0

### Other Software

Microsoft Visual Studio Enterprise 2019 16.10.3

### Steps to reproduce

Create a new VS C++ Console project. 
![image](https://user-images.githubusercontent.com/44722363/129904100-b49b8090-afca-4ec1-a5e9-7b553704875e.png) Click the Local Windows Debugger Button.
![image](https://user-images.githubusercontent.com/44722363/129906620-543db5d5-4d5a-4e05-87a2-3e496cfbacfd.png)
Close the tab with the X.
![image](https://user-images.githubusercontent.com/44722363/129906717-f5578656-fe42-43b2-bd43-6244631bbe09.png)
Click the Local Windows Debugger Button again.
Then VS will show this message box.
![image](https://user-images.githubusercontent.com/44722363/129906834-0c2efc5f-80cf-43d8-864a-c7430b056e5d.png)
In the output field, it says.
已退出，返回值为 -1073741502 (0xc0000142) 'DLL Initialization Failed'。
If I click the Local Windows Debugger Button again, this message keeps showing.

### Expected Behavior

Normally run the app again.

### Actual Behavior

An alert message box was shown.

**Comment by arsdever** [comment] 2021-10-17 16:10
Hi. I just faced the same issue. More details about what happened. In my case, I installed the `Preview` version of the terminal today (it's version `1.11.2731.0`). Then I set the `Default terminal application` to `Windows Terminal Preview` and started debugging in the `Visual Studio 2022` (not sure if the version matters, I'm using `Community` edition). In the beginning it opened a new terminal window and started debugging there, which is fine, but I wanted it to open a new tab in the already open window. So I head over to the settings and set the `New instance behavior` to `Attach to the most recently used window` and then tried to debug in VS and it started failing to start a terminal with an error code `0xc0000142`. I tried to switch back the `New instance behavior` to `Create a new window`, but the error message remains there.

I did some experiments, and my findings are the following. Once you log in you have 1 possibility to get the debug action work in the windows terminal. No matter what option you have chosen for the `New instance behavior`. Once you close the tab, debugging from VS won't work for terminal. Signing-out/in helps, but again, only for the first time.

**Comment by arsdever** [comment] 2021-10-17 16:17
Seems like a duplicate of https://github.com/microsoft/terminal/issues/10453

**Comment by deiruch** [comment] 2021-10-21 19:34
I can repro the issue with VIsual Studio 2022, and Terminal 1.11.2921.0 as well. Out of the box, only by changing the default terminal app to Terminal, and without changing any other configuration options.

@arsdever Might be, but the problem is the other way round. Here, the first launch works but subsequent launches fail.

**Comment by miniksa** [comment] 2021-11-03 22:49
> I was just playing around and found something interesting. So when you close the console window after the debugging session was finished (either you pressed stop in the VS, or you closed the separate GUI window which terminates the process, or your program finished) you are able to rerun. But once you close the terminal window while debugger is running, the issue appears. This might be helpful when debugging.

That should be very helpful indeed. Sorry, still swamped with other tasks. I took a week off as vacation and I've been behind ever since.

**Comment by arsdever** [comment] 2021-11-10 13:38
Since the feature this bug is referring to is included in the `Terminal v1` doesn't it make sense to deliver this bugfix for `v1` as well? I'm asking since this task is put into `v2` milestone.

**Comment by Dimension4** [comment] 2021-12-14 07:40
Just ran into the same problem with VS 2019 (16.11.7) and Terminal Preview 1.12.2931.0. I ran into this without having a debugger attached. I opened my C++ project and hit ctrl+F5 (start without debugging). The first time it worked but after that I have to restart VS to get it working again. 

I have quake mode running in the background, maybe it's related to that?

**Comment by egortech** [comment] 2021-12-24 02:02
Yes, I can also reproduce. I noticed that when problems occur, the VsDebugConsole process still exists and can spin one CPU core. If you kill that process, debug start normally without needing VS restart.

**Comment by zadjii-msft** [comment] 2022-01-31 22:59
Good news everyone!

I think this was actually fixed on the VS side!

https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes#release-notes-icon-visual-studio-2019-version-16119-newestreleaseicon

> Fixed an issue with being unable to debug applications multiple times when Windows Terminal is used as the default terminal.

From internal notes: 
> This fix was also included in 16.7.24, 16.9.16 and 15.9.43. 

This should be fixed, with a VS update. Thanks everyone!

**Closed by zadjii-msft** 2022-01-31 22:59 UTC
Labels: Issue-Bug, Product-Terminal, Priority-2, Area-DefApp
