### ISSUE TITLE
🛰 emoji renders too small

### ISSUE THREAD

**Issue by ZoeyR** [microsoft/terminal#3559] opened 2019-11-13 18:25 UTC
# Environment

```none
Windows build number: 18363.418
Windows Terminal version (if applicable):

Any other software?
```

# Steps to reproduce

enter the "🛰" character into the terminal (you will need a patched version of conhost that has the emoji fix).

# Expected behavior
Emoji should be rendered at full size.

# Actual behavior
Emoji is rendered at half scale:
![image](https://user-images.githubusercontent.com/8010244/68792249-e5b9f900-0642-11ea-8447-afee536b2433.png)

**Comment by DHowett-MSFT** [comment] 2019-11-13 18:32
This seems like a /dupe of #900.

**Closed by DHowett-MSFT** 2019-11-13 18:32 UTC
Labels: Needs-Tag-Fix, Needs-Triage
