### ISSUE TITLE
Additional Shell Types (Telnet/SSH/COM/etc)

### ISSUE THREAD

**Issue by LeeThompson** [microsoft/terminal#3874] opened 2019-12-06 21:31 UTC
It would seem natural to add more types to Terminal.

- Telnet Client
- SSH Client
- COM Terminal

For an added bonus, allow attaching WMI remote command prompt.

Other ideas:

- Network Shell (netsh)
- Disk Partition Shell

Essentially all of the interactive command line tools should have direct tab support in Terminal making it truly the 'go to' place for working with command lines on Windows.

**Comment by roysubs** [comment] 2019-12-08 12:16
Agree with this very much. It doesn't need to be as over the top as ConEmu or anything, but it should be extensible via the JSON and be able to connect via SSH (even if that's via a putty wrapper) to other Linux systems.

Oh, and one maybe missing from the OP list, I hope that it also supports:
• WSL Shell (regardless of Linux flavour).

**Comment by DHowett-MSFT** [comment] 2019-12-08 18:33
What is a WSL shell that exists regardless of “Linux flavor”? a WSL inherently requires a distribution or some other container. Terminal already supports that.

For SSH, we ship `ssh.exe` inbox in Windows, which you can use as the `commandline` of a profile.

For everything else, this is a /dupe of #1280.

**Closed by DHowett-MSFT** 2019-12-08 18:33 UTC
Labels: Issue-Feature, Needs-Tag-Fix, Needs-Triage
