### ISSUE TITLE
"Open Terminal Here" does not focus the Terminal windows

### ISSUE THREAD

**Issue by lllopo** [microsoft/terminal#6611] opened 2020-06-20 07:27 UTC
# Environment

Microsoft Windows [Version 10.0.19041.329]
Windows Terminal Preview
Version: 1.1.1671.0

# Steps to reproduce

1. Open windows explorer
2. Right click on a folder
3. Select "Open in Windows Terminal"

# Expected behavior

A Windows Terminal windows is opened and get's focused / comes to foreground

# Actual behavior

A Windows Terminal windows is opened, but appears behind the windows explorer window, which remains focused.

**Comment by zadjii-msft** [comment] 2020-06-22 14:10
I don't doubt this is a real bug, but I couldn't get it to happen in the last 10 Terminals I spawned using the shortcut. We'll probably need someone else on the dev team to be able to repro this 😕

**Comment by lllopo** [comment] 2020-06-22 18:10
@zadjii-msft I hope you mange to reproduce it somehow at some moment, as it is very annoying. Here a small demo :

![ezgif-6-62d50b430593](https://user-images.githubusercontent.com/5485902/85321080-c6365900-b4cc-11ea-89ae-1ea78c403277.gif)

**Comment by DHowett** [comment] 2020-06-25 18:19
Ugh, another papercut from MSIX.

Thanks.

**Comment by lllopo** [comment] 2020-07-23 07:51
The latest 1.2.2022.0 seems to fix this for me.

**Comment by OMA2k** [comment] 2020-11-08 20:40
I'm getting a similar behaviour when doing the opposite operation, i.e: If I type "start nameOfFolder" in the Terminal window, then Explorer opens with that folder but it appears BEHIND the Terminal, instead of in the front! This must be some issue with this Terminal, because it doesn't happen with the regular Command Prompt nor with the regular PowerShell window.

**Comment by KalleOlaviNiemitalo** [comment] 2020-11-08 21:52
@OMA2k, the problem with "start nameOfFolder" may be <https://github.com/microsoft/terminal/issues/2988>.

**Comment by siolfyr** [comment] 2022-05-09 17:32
For me, in Windows 11, this is always the behavior. No matter how I open Windows Terminal, it is never focused until I click on it.

**Comment by dbechrd** [comment] 2022-08-21 01:02
This also happens to me on Windows 11 when opening from start menu via keyboard. Extremely annoying as that's the fastest way to open it by far.

**Comment by nomius** [comment] 2022-08-26 11:06
> This also happens to me on Windows 11 when opening from start menu via keyboard. Extremely annoying as that's the fastest way to open it by far.

Same happens here.

**Comment by zadjii-msft** [comment] 2022-08-26 15:24
@dbechrd & @nomius You're probably seeing #13388 - this thread is specific to launching via the context menu. I know that sounds like nitpicking, but I think I have an idea what's causing #13388, while I'm pretty sure whatever the root cause of this thread is out of our immediate control.

**Comment by zadjii-msft** [comment] 2023-02-06 13:21
This might have just been fixed on it's own by Windows 11. I'm certainly not seeing this on 25294. I'd have basically no way of knowing if the fix got backported to win10 branches - @lllopo You still seeing this/?

**Comment by lllopo** [comment] 2023-02-06 13:51
@zadjii-msft Now that you mention it - it seems fixed for me too (I'm still on Win10).

**Comment by soredake** [comment] 2023-06-08 09:03
Works fine in windows 11 as of today.

**Comment by lhecker** [comment] 2023-08-30 22:07
Thanks for filing the issue. It seems to be fixed (or at least better) now, so I'll go ahead and close this. We still have "Windows Terminal not being in the foreground" issues in general, like when you open it via the start menu sometimes, etc., but those issues are already being tracked elsewhere.

**Closed by lhecker** 2023-08-30 22:07 UTC
Labels: Help Wanted, Issue-Bug, Needs-Attention, Product-Terminal, Priority-3, Area-ShellExtension

**Comment by carodgers** [comment] 2023-12-06 20:37
Wanted to add that I learned one way to toggle this behavior on/off.

If I open Ubuntu in WSL, and then separately click "Open in Terminal" from an Explorer folder window, the Terminal window opens behind the folder window and does not get focus. But if I close all instances of Ubuntu and try again, Terminal appears in front of the folder window and gets focus.
