### ISSUE TITLE
Want to open the Terminal in current folder from right click menu.

### ISSUE THREAD

**Issue by taneemishere** [microsoft/terminal#8920] opened 2021-01-28 06:19 UTC
# Description of the new feature/enhancement
There should be an option for ```Open Terminal Here``` in the right click menu a.k.a Context Menu. Same as when I right click in a folder, and if Visual Studio is installed it shows option ```Open in Visual Studio```, also if we install the Git Bash also it allows us to open that specific folder in the Bash Terminal right from the Context Menu or right click menu.

**Comment by KalleOlaviNiemitalo** [comment] 2021-01-28 10:41
This seems a duplicate of <https://github.com/microsoft/terminal/issues/6414>, which was already fixed. The fix is in [v1.6.10272.0](https://github.com/microsoft/terminal/releases/tag/v1.6.10272.0) but the binaries have not been released yet.

**Comment by zadjii-msft** [comment] 2021-01-28 12:08
Sure is, thanks!

/dup #6414
/dup #1060

**Closed by zadjii-msft** 2021-01-28 12:08 UTC
Labels: Issue-Feature, Needs-Tag-Fix, Needs-Triage

**Comment by pownas** [comment] 2021-01-28 13:27
I found this guide for that: 
https://dev.to/priyaranjankumar/how-to-add-open-windows-terminal-in-context-menu-36ni

I hope that version [v1.6.10272.0](https://github.com/microsoft/terminal/releases/tag/v1.6.10272.0) will solve this alot nicer with a supported settings and not one of all this web regex hacks. 😀
(or atleast a supported regex hack in the program😉 )

**Comment by taneemishere** [comment] 2021-01-28 15:19
@pownas Thanks for the help, really it means a lot to me as it was something I really want to be in the menu!
