### ISSUE TITLE
Windows Terminal Preview Version: 1.17.1023 does not automatically create a profile for PowerShell 7.4.0-preview.3

### ISSUE THREAD

**Issue by sba923** [microsoft/terminal#15341] opened 2023-05-12 18:44 UTC
### Windows Terminal version

1.17.1023

### Windows build number

10.0.22621.0

### Other Software

PowerShell 7.4.0-preview.3 installed from PowerShell-7.4.0-preview.3-win-x64.msi

### Steps to reproduce

1. Install PowerShell 7.4.0-preview.3 from PowerShell-7.4.0-preview.3-win-x64.msi
2. close Windows Terminal
3. launch Windows Terminal

### Expected Behavior

A new profile for PowerShell 7.4.0-preview.3 should be created

### Actual Behavior

No profile is created -- settings.json remains unchanged 
[settings.zip](https://github.com/microsoft/terminal/files/11466923/settings.zip)

**Comment by DHowett** [comment] 2023-05-12 18:48
If you previously had a PowerShell Preview version installed, and launched terminal + saved your settings without it, you're probably seeing #14061

What happens if you delete `state.json` from the same folder as `settings.json`?

**Comment by sba923** [comment] 2023-05-12 18:54
Bingo! I deleted both `state.json` and `elevated-state.json` (JIC) and the profile got created:

<img width="214" alt="image" src="https://github.com/microsoft/terminal/assets/12860484/63855fea-48c0-4c2d-a96c-3c18fca5e8eb">

[settings.zip](https://github.com/microsoft/terminal/files/11466963/settings.zip)

**Comment by DHowett** [comment] 2023-05-12 18:58
Perfect, thanks! This is definitely a /duplicate of #14061.

**Closed** 2023-05-12 18:58 UTC
Labels: Issue-Bug, Needs-Triage, Needs-Attention
