### ISSUE TITLE
Access violation observed

### ISSUE THREAD

**Issue by ariccio** [microsoft/terminal#10399] opened 2021-06-10 19:50 UTC
### Windows Terminal version (or Windows build number)

Microsoft Windows [Version 10.0.19042.867]

### Steps to reproduce

Unknown

### Expected Behavior

No crash

### Actual Behavior

Suspected access violation, windbg `analyze -v` here:

```

Microsoft (R) Windows Debugger Version 10.0.19041.685 AMD64
Copyright (c) Microsoft Corporation. All rights reserved.


Loading Dump File [C:\Users\Lucius Riccio\AppData\Local\CrashDumps\WindowsTerminal.exe.31724.dmp]
User Mini Dump File with Full Memory: Only application data is available


************* Path validation summary **************
Response                         Time (ms)     Location
Deferred                                       _NT_SYMBOL_PATH=SRV*C:\symbols*https://msdl.microsoft.com/download/symbols
Deferred                                       SRV*C:\symbols*https://chromium-browser-symsrv.commondatastorage.googleapis.com
Deferred                                       SRV*C:\symbols*https://download.amd.com/dir/bin
Deferred                                       SRV*C:\symbols*https://driver-symbols.nvidia.com/
Deferred                                       SRV*C:\symbols*https://software.intel.com/sites/downloads/symbols/
Symbol search path is: _NT_SYMBOL_PATH=SRV*C:\symbols*https://msdl.microsoft.com/download/symbols;SRV*C:\symbols*https://chromium-browser-symsrv.commondatastorage.googleapis.com;SRV*C:\symbols*https://download.amd.com/dir/bin;SRV*C:\symbols*https://driver-symbols.nvidia.com/;SRV*C:\symbols*https://software.intel.com/sites/downloads/symbols/
Executable search path is: 
Windows 10 Version 19042 MP (8 procs) Free x64
Product: WinNt, suite: SingleUserTS
19041.1.amd64fre.vb_release.191206-1406
Machine Name:
Debug session time: Wed Jun  9 16:14:15.000 2021 (UTC - 4:00)
System Uptime: 20 days 23:36:25.455
Process Uptime: 0 days 0:00:41.000
................................................................
................................................................
.....
Loading unloaded module list
...
This dump file has an exception of interest stored in it.
The stored exception information can be accessed via .ecxr.
(7bec.7bf0): Access violation - code c0000005 (first/second chance not available)
For analysis of this file, run !analyze -v
Windows_UI_Xaml!WindowsGraphicsDeviceManager::WaitForInitializationThreadCompletion+0x1f:
00007ff8`188b9abf 48397910        cmp     qword ptr [rcx+10h],rdi ds:00000000`00000010=????????????????
0:000> !analyze -v
*******************************************************************************
*                                                                             *
*                        Exception Analysis                                   *
*                                                                             *
*******************************************************************************


KEY_VALUES_STRING: 1

    Key  : AV.Dereference
    Value: NullClassPtr

    Key  : AV.Fault
    Value: Read

    Key  : Analysis.CPU.Sec
    Value: 6

    Key  : Analysis.DebugAnalysisProvider.CPP
    Value: Create: 8007007e on PK1Y1FE-LJR14

    Key  : Analysis.DebugData
    Value: CreateObject

    Key  : Analysis.DebugModel
    Value: CreateObject

    Key  : Analysis.Elapsed.Sec
    Value: 31

    Key  : Analysis.Memory.CommitPeak.Mb
    Value: 341

    Key  : Analysis.System
    Value: CreateObject

    Key  : Timeline.OS.Boot.DeltaSec
    Value: 1812985

    Key  : Timeline.Process.Start.DeltaSec
    Value: 41


NTGLOBALFLAG:  400

PROCESS_BAM_CURRENT_THROTTLED: 0

PROCESS_BAM_PREVIOUS_THROTTLED: 0

APPLICATION_VERIFIER_FLAGS:  0

CONTEXT:  (.ecxr)
rax=0000000000000000 rbx=000000cc994fe630 rcx=0000000000000000
rdx=0000070000000700 rsi=0000000000000000 rdi=000000cc994fe140
rip=00007ff8188b9abf rsp=000000cc994fe860 rbp=000000cc994fe999
 r8=000002c63a234120  r9=000002c63911f650 r10=00000fff03165986
r11=4554401005111555 r12=000002c633233910 r13=0000000000000000
r14=0000000000000000 r15=0000000000000000
iopl=0         nv up ei pl zr na po nc
cs=0033  ss=002b  ds=002b  es=002b  fs=0053  gs=002b             efl=00010244
Windows_UI_Xaml!WindowsGraphicsDeviceManager::WaitForInitializationThreadCompletion+0x1f:
00007ff8`188b9abf 48397910        cmp     qword ptr [rcx+10h],rdi ds:00000000`00000010=????????????????
Resetting default scope

EXCEPTION_RECORD:  (.exr -1)
ExceptionAddress: 00007ff8188b9abf (Windows_UI_Xaml!WindowsGraphicsDeviceManager::WaitForInitializationThreadCompletion+0x000000000000001f)
   ExceptionCode: c0000005 (Access violation)
  ExceptionFlags: 00000001
NumberParameters: 2
   Parameter[0]: 0000000000000000
   Parameter[1]: 0000000000000010
Attempt to read from address 0000000000000010

PROCESS_NAME:  WindowsTerminal.exe

READ_ADDRESS:  0000000000000010 

ERROR_CODE: (NTSTATUS) 0xc0000005 - The instruction at 0x%p referenced memory at 0x%p. The memory could not be %s.

EXCEPTION_CODE_STR:  c0000005

EXCEPTION_PARAMETER1:  0000000000000000

EXCEPTION_PARAMETER2:  0000000000000010

STACK_TEXT:  
000000cc`994fe860 00007ff8`188b97d2 : 00000000`00000000 00000000`00000000 00000000`00000100 00000000`00000000 : Windows_UI_Xaml!WindowsGraphicsDeviceManager::WaitForInitializationThreadCompletion+0x1f
000000cc`994fe8c0 00007ff8`188b8540 : 00000700`00000700 00007ff8`4437239e 00000000`00000000 000002c6`3a502400 : Windows_UI_Xaml!WindowsGraphicsDeviceManager::WaitForD3DDependentResourceCreation+0x12
000000cc`994fe8f0 00007ff8`18a9fea4 : 4327ffff`fffff200 00000000`00000001 00000700`00000700 00000000`00000000 : Windows_UI_Xaml!CCoreServices::GetMaxTextureSize+0x2c
000000cc`994fe920 00007ff8`18a9ed45 : 000002c6`332756e0 00000700`00000700 00000000`00000000 00007ff8`44386947 : Windows_UI_Xaml!CLoadedImageSurface::IsVirtualPossible+0x30
000000cc`994fe950 00007ff8`18a9e8a0 : 00000700`00000700 000002c6`391e8300 000002c6`3a234120 000002c6`3a252a10 : Windows_UI_Xaml!CLoadedImageSurface::StartDecodingHelper+0x6d
000000cc`994fea00 00007ff8`18a9e848 : 000000cc`00000000 000002c6`3a234198 00000000`00000010 000000cc`994feb18 : Windows_UI_Xaml!CLoadedImageSurface::StartFinalSizeDecoding+0x3c
000000cc`994fea30 00007ff8`1892e2e9 : 00000000`00000000 00007ff8`189a8ce9 00000000`00000000 00000000`00000088 : Windows_UI_Xaml!CLoadedImageSurface::OnImageViewUpdated+0x38
000000cc`994fea60 00007ff8`1892e258 : 000002c6`3911f670 000000cc`994feae0 000002c6`3911f650 00000000`00000000 : Windows_UI_Xaml!ImageViewBase::TriggerViewUpdated+0x61
000000cc`994fea90 00007ff8`1892e386 : 000002c6`3a219550 000002c6`3a2a10f0 000000cc`994feb20 00000000`00000000 : Windows_UI_Xaml!ImageMetadataViewImpl::SetEncodedImageData+0x50
000000cc`994feac0 00007ff8`18b0d2f0 : 000002c6`3a2a0bb0 00000000`00000000 000002c6`3a2a0bb0 00000000`00000000 : Windows_UI_Xaml!ImageCache::SetEncodedImageData+0x86
000000cc`994feb00 00007ff8`18b0d23e : 000002c6`3a2a0bb0 00000000`00000000 000002c6`3a2a0250 000000cc`994fec00 : Windows_UI_Xaml!ImageCache::GotDownloadResponse+0x88
000000cc`994feb50 00007ff8`18b162e7 : 000002c6`3a219550 000002c6`3a2a0250 000000cc`994fec28 000000cc`994fec08 : Windows_UI_Xaml!ImageCacheDownloadResponseTask::Execute+0x2e
000000cc`994feb80 00007ff8`18b0c233 : 00000000`00000000 00000000`00000000 000000cc`994fec40 000002c6`332a2e90 : Windows_UI_Xaml!ImageCacheDownloadCallbackMarshaller::GotResponse+0x97
000000cc`994febc0 00007ff8`18b23f0e : 000002c6`00040007 00007ff8`00000001 000002c6`3a2195a0 00000000`00000000 : Windows_UI_Xaml!CDownloader::CreateUnsecureDownloadRequest+0x1b3
000000cc`994fec80 00007ff8`18896a2b : 000002c6`3a502510 000000cc`994fed20 000002c6`3a5024c0 000002c6`39190640 : Windows_UI_Xaml!CommonBrowserHost::UnsecureDownload+0x4e
000000cc`994fecc0 00007ff8`188965da : 000002c6`3a219550 000002c6`3a2195a0 000002c6`3a219550 000002c6`391beae0 : Windows_UI_Xaml!CCoreServices::UnsecureDownloadFromSite+0x12b
000000cc`994fed50 00007ff8`1892d24e : 000002c6`3a219550 00000000`00000000 000002c6`39190a00 00000000`00000000 : Windows_UI_Xaml!ImageCache::Download+0xbe
000000cc`994fedc0 00007ff8`1892cfc1 : 00000000`00000000 000002c6`39197b90 000002c6`39190a00 000002c6`391beae0 : Windows_UI_Xaml!ImageCache::ProcessDecodeRequests+0x9e
000000cc`994fedf0 00007ff8`18899e27 : 00000000`00000000 000002c6`33275a50 000002c6`332756e0 00000000`00000000 : Windows_UI_Xaml!ImageTaskDispatcher::Execute+0xe1
000000cc`994fee20 00007ff8`189f47c6 : 00000000`00000000 000000cc`994fef20 00000000`00000000 00000000`00000000 : Windows_UI_Xaml!CCoreServices::ResetCoreWindowVisualTree+0x233
000000cc`994fee70 00007ff8`18a50cb2 : 00000000`00000000 00000000`00000000 000002c6`33274ae0 000002c6`33274cc0 : Windows_UI_Xaml!CommonBrowserHost::ResetVisualTree+0x46
000000cc`994feea0 00007ff8`18a4fbb5 : 00000000`00000000 00007ff8`18aea100 000000cc`994fef20 00000000`00000000 : Windows_UI_Xaml!CJupiterControl::ResetVisualTree+0x3a
000000cc`994feed0 00007ff8`18a50e3a : 00000000`00000000 000000cc`994fef40 00000000`00000000 00000000`00000000 : Windows_UI_Xaml!DirectUI::DXamlCore::CommonShutdown+0xb9
000000cc`994fef40 00007ff8`18a52165 : 000002c6`33274ae0 00000000`00000000 000002c6`33274ae0 000002c6`34f81410 : Windows_UI_Xaml!DirectUI::DXamlCore::DeinitializeInstance+0x15a
000000cc`994fef70 00007ff8`1931c944 : 00000000`00000000 000002c6`33274ae0 000002c6`34f81410 000002c6`33274ae0 : Windows_UI_Xaml!DirectUI::DXamlCore::Deinitialize+0x85
000000cc`994fefa0 00007ff8`1931d2c3 : 000002c6`3a258600 000002c6`33274ae0 000002c6`39170f00 00000000`b6c2d748 : Windows_UI_Xaml!DirectUI::WindowsXamlManager::XamlCore::Close+0xfc
000000cc`994fefe0 00007ff8`45c07406 : 000002c6`3a258600 00000000`00000000 000002c6`3330ab00 00000000`0000007f : Windows_UI_Xaml!Microsoft::WRL::Details::DelegateArgTraits<long (__cdecl Windows::System::IDispatcherQueueHandler::*)(void)>::DelegateInvokeHelper<Microsoft::WRL::Implements<Microsoft::WRL::RuntimeClassFlags<2>,Windows::System::IDispatcherQueueHandler,Microsoft::WRL::FtmBase>,<lambda_6689f931d1d2ff748962254369ea1967> &,-1>::Invoke+0x13
000000cc`994ff010 00007ff8`45bd53db : 000002c6`3330ba50 000002c6`39170f00 000002c6`3330ba50 000002c6`39170f00 : CoreMessaging!Windows::System::DispatcherQueue::DeferInvokeCallback+0x16
000000cc`994ff040 00007ff8`45bc9c34 : 0000ad48`fe76e03f 000002c6`3330bca0 000002c6`39170f00 000002c6`390c7260 : CoreMessaging!Microsoft__CoreUI__Dispatch__TimeoutHandler$CallbackThunk+0x11b
000000cc`994ff0c0 00007ff8`45bc94de : 000002c6`390c7260 000002c6`390fc820 000002c6`390c7260 00000000`00000000 : CoreMessaging!Microsoft::CoreUI::Dispatch::DeferredCall::Callback_Dispatch+0x2c4
000000cc`994ff180 00007ff8`45bd996b : 00000000`00000007 00000000`00000003 00000000`00000003 00000000`00000007 : CoreMessaging!Microsoft::CoreUI::Dispatch::DeferredCallDispatcher::Callback_OnDispatch+0x15e
000000cc`994ff1f0 00007ff8`45bd8e26 : 80000022`00000000 00000000`00000000 000002c6`33310b30 000002c6`332679b0 : CoreMessaging!Microsoft::CoreUI::Dispatch::EventLoop::Callback_RunCoreLoop+0x6fb
000000cc`994ff320 00007ff8`45bd7061 : 000002c6`332679b0 000002c6`33313250 00000000`00220eba 00000000`00000000 : CoreMessaging!Microsoft::CoreUI::Dispatch::UserAdapter::OnUserDispatch+0x1d6
000000cc`994ff410 00007ff8`45bd6e83 : 00000000`00000005 000002c6`33313250 00000000`0000c128 00000000`40000c02 : CoreMessaging!Microsoft::CoreUI::Dispatch::UserAdapter_DoWork+0xf1
000000cc`994ff4f0 00007ff8`4ad5e858 : 00000000`00000001 00000000`00000000 00000000`00000001 00000000`00000001 : CoreMessaging!Microsoft::CoreUI::Dispatch::UserAdapter_WindowProc+0xa3
000000cc`994ff570 00007ff8`4ad5e299 : 00000000`00003dff 00007ff8`45bd6de0 00000000`00590dc2 000002c6`00000060 : user32!UserCallWinProcCheckWow+0x2f8
000000cc`994ff700 00007ff8`3195150b : 00007ff8`45bd6de0 000002c6`33228818 000002c6`33225630 00007ff8`4b1147cd : user32!DispatchMessageWorker+0x249
000000cc`994ff780 00007ff8`31953979 : 00000000`00590dc2 000000cc`994ff918 00000000`00000000 00000000`00000004 : Microsoft_Toolkit_Win32_UI_XamlHost+0x150b
000000cc`994ff810 00007ff6`c702787c : 000000cc`994ff918 00000000`00000000 00000000`00000000 00000000`00000000 : Microsoft_Toolkit_Win32_UI_XamlHost+0x3979
000000cc`994ff840 00007ff6`c70257de : 00000000`00000000 00000000`00000005 00000000`00000000 00000000`00000000 : WindowsTerminal+0x787c
000000cc`994ff880 00007ff6`c70348f2 : 00000000`00000005 00000000`00000000 00000000`00000000 00000000`00000000 : WindowsTerminal+0x57de
000000cc`994ffa30 00007ff8`494d7034 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : WindowsTerminal+0x148f2
000000cc`994ffa70 00007ff8`4b142651 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : kernel32!BaseThreadInitThunk+0x14
000000cc`994ffaa0 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : ntdll!RtlUserThreadStart+0x21


FAULTING_SOURCE_LINE:  onecoreuap\windows\dxaml\xcp\components\graphics\windowsgraphicsdevicemanager.cpp

FAULTING_SOURCE_FILE:  onecoreuap\windows\dxaml\xcp\components\graphics\windowsgraphicsdevicemanager.cpp

FAULTING_SOURCE_LINE_NUMBER:  17

SYMBOL_NAME:  Windows_UI_Xaml!WindowsGraphicsDeviceManager::WaitForInitializationThreadCompletion+1f

MODULE_NAME: Windows_UI_Xaml

IMAGE_NAME:  Windows.UI.Xaml.dll

STACK_COMMAND:  ~0s ; .ecxr ; kb

FAILURE_BUCKET_ID:  NULL_CLASS_PTR_READ_c0000005_Windows.UI.Xaml.dll!WindowsGraphicsDeviceManager::WaitForInitializationThreadCompletion

OS_VERSION:  10.0.19041.1

BUILDLAB_STR:  vb_release

OSPLATFORM_TYPE:  x64

OSNAME:  Windows 10

FAILURE_ID_HASH:  {e25e17fd-3d34-febf-009a-64ef61c97fd8}

Followup:     MachineOwner
---------

```

**Comment by zadjii-msft** [comment] 2021-07-06 14:13
Okay so, you did _something_, and it crashed. Unfortunately, I'm not really sure how we can investigate that...

Does this happen consistently? Or is an an intermittent failure? Does this happen on launch, or while the Terminal is already running?

The stack looks like it's somewhere in XAML. Do you have an image set as a background for one of your profiles?

**Comment by ariccio** [comment] 2021-07-06 15:56
> Okay so, you did something, and it crashed. Unfortunately, I'm not really sure how we can investigate that...

Hey, I don't blame ya. But if we're gonna write code in C++, mysterious nullptr derefs are the price we pay 🤷‍♂️. All I can say is that it definitely did happen, so there is a bug of some kind there, and somebody else will hit it too at some point. Reporting it gives you something, and means I can follow up if/when I see it again.

> Do you have an image set as a background for one of your profiles?

Eh? Do you mean a background image for the terminal, or my desktop background? None for the terminal. I have solid black as the desktop background.

**Comment by ariccio** [comment] 2021-07-06 15:57
Oh, and I haven't seen it since.

**Comment by zadjii-msft** [comment] 2021-07-06 16:18
> Do you mean a background image for the terminal, or my desktop background?

I meant for the terminal, so that rules that out.



> I can follow up if/when I see it again ... Oh, and I haven't seen it since.

Then I think I'm just going to close this for now, since it seems like it was a one-off crash. If this ever does become more frequent or reproducible, then we can re-open with more info.

**Closed by zadjii-msft** 2021-07-06 16:18 UTC
Labels: Needs-Attention, Needs-Tag-Fix, Needs-Triage
