### ISSUE TITLE
Impossible to set custom tab color after setting it to black

### ISSUE THREAD

**Issue by ItsMeSousuke** [microsoft/terminal#7948] opened 2020-10-16 14:46 UTC
# Environment

```none
Windows build number: Win32NT, 10.0.18362.0 Microsoft Windows NT 10.0.18362.0
Windows Terminal version (if applicable): 1.3.2651.0
```

# Steps to reproduce

1. Right click on tab and select _Color..._
1. Click _Custom_
1. Click _More_
1. Remove value from hex code field, tab background is set to black
1. Try to pick any color from color picker

# Expected behavior

User should be able to pick new color from color picker.

# Actual behavior

Tab color is black and can't be change by picking color from color picker, it can be only change by selecting one from predefined list or by setting any other color hex code other than black
![image](https://user-images.githubusercontent.com/13621655/96272672-b76d3800-0fce-11eb-9e16-d6197b2b27b0.png)

**Comment by alannt777** [comment] 2020-10-16 14:54
I can repro it:

![image](https://user-images.githubusercontent.com/67918878/96273911-83edd600-0fed-11eb-8402-3a9da57e1a45.png)

**Comment by alannt777** [comment] 2020-10-17 02:20
I think this is an issue with the XAML ColorPicker control. Because I was able to reproduce this issue in XAML Controls Gallery

![image](https://user-images.githubusercontent.com/67918878/96326320-50429880-104d-11eb-8d89-fc32ddf6d2fd.png)

And a little more closer look:

![image](https://user-images.githubusercontent.com/67918878/96326340-694b4980-104d-11eb-9a25-aa3aeb38e121.png)

**Comment by alannt777** [comment] 2020-10-17 14:12
This is what I think is the reason why this is not working
---
![Look at this](https://user-images.githubusercontent.com/67918878/96326340-694b4980-104d-11eb-9a25-aa3aeb38e121.png)

Look at the slider. It is set to black. So if you change the color using that rainbow like thing, that slider is still at black.
You have to move the slider in order for it to work (and I have confirmed it).

This also explains why the color changes successfully when you choose a preset color or you give another hex value.

The funny thing is that Windows Terminal does not have this slider

This is probably because

The one with the slider:

![image](https://user-images.githubusercontent.com/67918878/96339185-9d0b8b00-10b0-11eb-9c6c-a4b1ed85b6ff.png)

The one that Windows Terminal be likely be using:

![image](https://user-images.githubusercontent.com/67918878/96339213-d9d78200-10b0-11eb-8cb1-c598d98ecad5.png)

**Comment by alannt777** [comment] 2020-10-17 14:27
cc @DHowett @zadjii-msft

**Comment by alannt777** [comment] 2020-10-19 08:46
GIFing this problem:

(Sorry for my extremely bad GIFs. Especially the ColorPicker control 🤢)

The problem:

![The problem](https://user-images.githubusercontent.com/67918878/96421881-f55b9d80-1214-11eb-8f04-c81482947d64.gif)

Demonstrating the problem and a possible fix in XAML Studio:

![potential-fix](https://user-images.githubusercontent.com/67918878/96422065-2dfb7700-1215-11eb-8da1-fae215383f17.gif)

I think we can fix this by enabling Color Slider in the ColorPicker control.

I would like to make a PR on this if you agree on this fix (only if this fix is going to be as easy as I did in XAML Studio)

**Comment by WSLUser** [comment] 2020-10-19 13:15
Is there an existing issue in https://github.com/microsoft/microsoft-ui-xaml/issues? This seems like a good workaround to add but ultimately this is a bug with the XAML framework and should be addressed by the WINUI team.

**Comment by zadjii-msft** [comment] 2020-10-19 13:32
Yea, I think it's fine to fix locally for the Terminal with enabling the color slider, but I agree, we should file a follow-up on the WinUI repo that WSLUser linked.

**Comment by alannt777** [comment] 2020-10-19 13:33
@zadjii-msft I will take up this isse

**Comment by alannt777** [comment] 2020-10-19 13:33
Just point me to the right XAML file.

**Comment by zadjii-msft** [comment] 2020-10-19 13:36
https://github.com/microsoft/terminal/blob/master/src/cascadia/TerminalApp/ColorPickupFlyout.xaml

**Comment by alannt777** [comment] 2020-10-19 13:38
PR on the way

**Comment by alannt777** [comment] 2020-10-19 13:43
@zadjii-msft 

PR ready to be reviewed -> #7963

**Comment by WSLUser** [comment] 2020-10-19 14:20
So I did check and there isn't an existing issue on the WinUI repo. Please create a ticket and link to it here. The PR should be considered a workaround, not a "fix" and so this issue should be closed when we pick up a version of MUX with the fix. We should add the `upstream-issue` and `workaround-available` tags for tracking/visibility.

**Closed** 2020-10-23 20:18 UTC
Labels: Area-User Interface, Easy Starter, Help Wanted, In-PR, Issue-Bug, Priority-3, Product-Terminal

**Comment by zadjii-msft** [comment] 2020-10-23 20:28
I've filed https://github.com/microsoft/microsoft-ui-xaml/issues/3476 upstream, but I'm okay leaving this issue closed, because frankly, the picker is better off _with_ the color slider  visible. That makes it possible to pick both a lightness and a hue, which greatly increases the range of easily accessible tab colors.

Thanks for the investigation @alannt777!
