### ISSUE TITLE
1.16 Preview: Incorrect Nerd Font rendering:  double-sized characters are reduced 

### ISSUE THREAD

**Issue by 237dmitry** [microsoft/terminal#13988] opened 2022-09-14 08:33 UTC
### Windows Terminal version

1.16.2524.0

### Windows build number

10.0.22000.0

### Other Software

pwsh 7.2.6

### Steps to reproduce

Double-sized symbols reduced to single-sized. This behavior does not depend on whether Atlas engine is enabled or not.

![Screenshot 2022-09-14 110951](https://user-images.githubusercontent.com/78153320/190100665-5b63b00c-2a47-4d6a-81e8-139f25322596.png)

### Expected Behavior

Correct font rendering

### Actual Behavior

Incorrect font rendering. It's horrible. The default console looks much better.

**Comment by lhecker** [comment] 2022-09-14 13:22
This is a duplicate of #6864. I'll post an explanation and my current thoughts about this topic there.
/dup #6864

**Closed** 2022-09-14 13:22 UTC
Labels: Issue-Bug, Needs-Triage, Needs-Tag-Fix

**Comment by 237dmitry** [comment] 2022-09-14 21:03
> This behavior does not depend on whether Atlas engine is enabled or not.

I overlooked the moment that the option changed its name and moved from the category of experimental. Since I'm editing settings.json in the editor or directly from the pwsh I did not take these changes into account and Atlas stayed enable.
