### ISSUE TITLE
Windows Terminal crashing on neofetch.

### ISSUE THREAD

**Issue by hardwareadictos** [microsoft/terminal#4318] opened 2020-01-21 13:23 UTC
# Environment

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Windows Terminal version (if applicable):

PS C:\WINDOWS\system32> [Environment]::OSVersion

Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.18363.0 Microsoft Windows NT 10.0.18363.0

Windows Terminal Version: v0.8.10091.0 (issue seems not present on  0.7.3451.0 and previous ones).

Any other software?

WSL

```

# Steps to reproduce

Just opening a Windows Terminal and launching neofetch on a WSL instance (not happening on WSL if i use distros consoles).

# Expected behavior

Launching neofetch or invoking neofetch from scripts without Windows Terminal crashing.

# Actual behavior

Terminal crashing on launching neofetch.

Launching neofetch makes windows terminal to crash, i know its a fancy software (neofetch) but that could be caused by some special characters combined on a string, so could happen on more usage scenarios. Would be great to take a look at it for stability reasons.

neofetch git: https://github.com/dylanaraps/neofetch

**Comment by electronic-dk** [comment] 2020-01-21 13:43
Seems like a dupe of https://github.com/microsoft/terminal/issues/4254

**Comment by zadjii-msft** [comment] 2020-01-21 14:00
This is absolutely a /dupe of #4254. Thanks!

**Closed by zadjii-msft** 2020-01-21 14:00 UTC
Labels: Needs-Tag-Fix, Needs-Triage

**Comment by hardwareadictos** [comment] 2020-01-21 20:42
thanks and sorry, seems i didnt search enough :)
