### ISSUE TITLE
Unable to open new tabs or select other options on 0.7.3451.0

### ISSUE THREAD

**Issue by Sparker0i** [microsoft/terminal#4040] opened 2019-12-22 08:46 UTC
# Environment

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd] Windows 10 18363 x64
Windows Terminal version (if applicable): 0.7.3451.0

Any other software? Maybe Powertoys but I don't see why that should affect
```

# Steps to reproduce

1. Open Windows Terminal
2. Try opening a new tab
# Expected behavior

New tab should open
# Actual behavior

New tab wont open. There's no hover effect around the + button, or even the drop down button. We can't even minimize, maximise or close using the buttons on the tab bar. None of them get highlighted on hover. 
Keyboard shortcuts work however..

**Comment by mkitzan** [comment] 2019-12-27 21:10
Doesn't repro for me. Could you post some screen caps or something a little more to go on? Sounds like it's related to the `TabView` ui xaml element though.

**Comment by zadjii-msft** [comment] 2019-12-30 16:07
@Sparker0i Could you just quick test if uninstalling powertoys fixes this? WE do some real weird stuff with our window frame, and I'd be curious to know if Powertoys doesn't play nice with that. 

If not, we're probably going to need an in-house repro to be able to investigate this further unfortunately.


Does resizing the window fix these buttons? This is totally spitballing - I really don't know how this might happen.

**Comment by Sparker0i** [comment] 2019-12-31 10:34
Yes, uninstalling Powertoys latest fixed this. I am not sure why but earlier versions of Terminal used to work well with Powertoys

**Comment by DHowett-MSFT** [comment] 2020-01-06 20:38
This looks like a /dupe of #3325.

**Closed by DHowett-MSFT** 2020-01-06 20:38 UTC
Labels: Area-User Interface, Issue-Bug, Needs-Attention, Needs-Triage, Priority-3, Product-Terminal
