### ISSUE TITLE
why we cant scroll on laptop

### ISSUE THREAD

**Issue by sonick13** [microsoft/terminal#4261] opened 2020-01-16 15:02 UTC
can you fix it

**Comment by zadjii-msft** [comment] 2020-01-16 15:26
Please search for issues before filing new ones, and make sure to use the issue template when you do. This _sounds_ like a duplicate of #979, but I can't really tell because you haven't really provided any info for me to work with.

/dup #979.

**Closed by zadjii-msft** 2020-01-16 15:26 UTC
Labels: Needs-Tag-Fix, Needs-Triage
