### ISSUE TITLE
New split screen opens with default terminal, not the current terminal.

### ISSUE THREAD

**Issue by nashidfarhad** [microsoft/terminal#4293] opened 2020-01-19 05:17 UTC
# Environment

```none
Windows build number: 10.0.19041.21
Windows Terminal version (if applicable): 0.8.10091.0
Any other software?
```

# Steps to reproduce
- open terminal
- open a new tab with a different shell (e.g. WSL)
- in the new tab press either `Alt` + `Shft` + `+` or `Alt` + `Shft` + `-` to split 

# Expected behavior

The new split screen should should spawn with the same shell from where the command was invoked. So, if the spit command was press in a WSL window, the new split should be WSL. If it was invoked from a Powershell window, the new split screen should open a Powershell window.

# Actual behavior

The new split opens with the source in the `defaultProfile` in settings. If the default profile points to Powershell, the new split will be Powershell, even if the windows that was split was different (e.g. WSL)

**Comment by DHowett-MSFT** [comment] 2020-01-19 07:59
Hi there! Thanks for the request. This is a /dupe of #1756.

**Closed by DHowett-MSFT** 2020-01-19 07:59 UTC
Labels: Needs-Tag-Fix, Needs-Triage
