### ISSUE TITLE
Crash when middle-clicking tab several times too quickly

### ISSUE THREAD

**Issue by fearthecowboy** [microsoft/terminal#2293] opened 2019-08-06 15:37 UTC
# Environment
```none
Windows build number: Microsoft Windows [Version 10.0.18921.1000]
Windows Terminal version (if applicable): 0.3
```
# Steps to reproduce
Open Several tabs. 
Quickly hit middle button on a tab (that is not the last one) several times

# Expected behavior
No Crash

# Actual behavior
Crash

It doesn't happen with the last tab -- the last tab disappears too quickly to hit it again.

With tabs that aren't the last, the hit looks like it goes to the tab that slides over, but it's not ready for it?

**Comment by zadjii-msft** [comment] 2019-08-06 15:48
This looks like a dupe of #2248 to me

**Closed by zadjii-msft** 2019-08-06 15:48 UTC
Labels: Needs-Tag-Fix, Needs-Triage
