### ISSUE TITLE
How to use ConPTY API to resize the console correctly?

### ISSUE THREAD

**Issue by martincohen** [microsoft/terminal#1156] opened 2019-06-06 09:32 UTC
I'm missing documentation/guidance on how to deal with resizing the window from embedded terminal I'm adding to my application. There's `ResizePseudoConsole` function, that also seems to cause reflow of the buffer (assuming this is taken care of by conhost).

In the terminal codein this repo, I saw you are also sending `\x1b[7t` after calling `ResizePseudoConsole` through the pipe to the child process. Is this a requirement?

Is there a way to know that the child process has acknowledged the new size? Currently there's a bit of time in which the app keeps sending commands with old size before it picks up the information from the input (but it might be an issue of how I buffer stuff). However a general guidance of how the resize process should work would be very helpful.

**Comment by zadjii-msft** [comment] 2019-06-06 13:16
I'd say you're doing it the right way. 

Because conpty is effectively rendering the buffer contents, it's entirely possible that you're sending a resize with `ResizePseudoConsole` before/during a previous frame, and conpty will just keep on finishing that frame before rendering the resized contents.

The resizing in conpty has always been a little wonky, partially because of the re-rendering that we need to do, and partially because of the reflowing that conhost does. When I get the chance, I really want to dive in and make sure there's not a better way to handle the resizing.

Is there a specific issue you're seeing with the resize?

**Comment by martincohen** [comment] 2019-06-07 09:14
@zadjii-msft I've tried `vim.exe` (few years old version) to test my terminal emulator and it rendered correctly, but it didn't react to resize. There was clearly something that reflowed the screen (I assume it was `conhost`) however it treated the contents as if it was a continuous text (which is normal). I got Vim to reflow by typing something. So I tried sending `\x1b[7t` immediately after resize but it didn't do anything.

I guess this is an issue in vim which is probably not checking for window being resized. However it got me thinking whether it's not a bug in my resize implementation and realized the docs don't provide info on how to do it properly, they don't even mention `\x1b[7t`.

**Comment by zadjii-msft** [comment] 2019-06-07 12:42
Yea the `7t` thing was a bit of a hack to get conpty working at the start. Before it was really polished, it was a handy helper to force the repaint, but I don't think it should _really_ be necessary anymore.

@DHowett-MSFT do you know more about any vim.exe issues via conpty? I know that's your daily driver

**Comment by DHowett-MSFT** [comment] 2019-06-10 21:18
I only started using vim on Windows as of 7.x, and I believe most of its weird console issues have been ... ignored long enough that they've become "expected behavior". Given that this looks like a client application issue, I'm going to close it _answered_. Feel free to reopen if you have additional questions or if this response is insufficient.

**Closed by DHowett-MSFT** 2019-06-10 21:18 UTC
Labels: Issue-Question, Needs-Attention, Needs-Tag-Fix, Needs-Triage, Product-Conpty
