### ISSUE TITLE
Windows Console doesn't support Unicode out of the box

### ISSUE THREAD

**Issue by barrytang** [microsoft/terminal#13680] opened 2022-08-05 02:14 UTC
# Description of the new feature/enhancement

This [suggestion](https://developercommunity.visualstudio.com/t/%E3%83%87%E3%83%90%E3%83%83%E3%82%B0%E5%AE%9F%E8%A1%8C%E3%81%A7Shift_JIS%E3%81%AB%E3%81%AA%E3%81%84%E6%96%87%E5%AD%97%E3%81%8C%E8%A1%A8%E7%A4%BA%E3%81%95%E3%82%8C%E3%81%BE%E3%81%9B%E3%82%93/10001821#TPIN-N10088478-N10090272) is originated from https://developercommunity.visualstudio.com. 

Right now, Windows Console doesn't support Unicode by default for English OS. To make it work, the app needs to either set output encoding to UTF8 or configure Windows Console properties to UTF8. Even after doing so, some Unicode still won't get rendered correctly because Windows Console doesn't support font-fallback as explained [here](https://devblogs.microsoft.com/commandline/windows-command-line-unicode-and-utf-8-output-text-buffer/#console-built-in-a-pre-unicode-dawn). 

# Proposed technical implementation details (optional)

It would be great to enable an out-of-the-box console experience that supports Unicode for customers.

**Comment by 237dmitry** [comment] 2022-08-05 04:53
I think this is rather OS wide settings

![Screenshot 2022-08-05 075031](https://user-images.githubusercontent.com/78153320/183004029-022ccdf1-10fc-4bba-833c-9981c4dbd317.png)

**Comment by zadjii-msft** [comment] 2022-08-05 18:09
Yea, I'm not sure that's something we'll be able to change in any short order. **Using the console APIs in a client application to specifically request CP_UTF8 is the best way to do this**. 

There's a collection of issues here to follow:
 
* #1802 might make this better for the Terminal in the future. We can use the Terminal to opt applications in to UTF8 as the default codepage. We'd have a setting within Terminal to opt out of this support. That would alieviate the need to call `SetConsole*CP` for any apps that are being run in the Terminal. 
* #8000 and #190 are generally tracking any other work to be done to better support the breadth of unicode in the buffer, in input and output. 
* #10478 should have largely mitigated any unicode rendering issues in the vintage console, as far as I'm aware. Conhost will still be subject to issues that would arise from the buffer not supporting full unicode (as tracked above)
  * This PR should be available in SV2 builds of Windows 11 (e.g. >22000.000), but I don't know the first build number it appeared in. 

I'm gonna collectively resolve this as a dupe of those conversations. Thanks!
/dup #1802 #8000 #190 #10478

**Closed by zadjii-msft** 2022-08-05 18:09 UTC
Labels: Issue-Feature, Needs-Triage, Needs-Tag-Fix

**Comment by asmichi** [comment] 2022-08-15 09:47
Sorry for posting in a closed issue.

> Using the console APIs in a client application to specifically request CP_UTF8 is the best way to do this.

I agree and that's the very reason Visual Studio should do that. Therefore the original [suggestiion](https://developercommunity.visualstudio.com/t/%E3%83%87%E3%83%90%E3%83%83%E3%82%B0%E5%AE%9F%E8%A1%8C%E3%81%A7Shift_JIS%E3%81%AB%E3%81%AA%E3%81%84%E6%96%87%E5%AD%97%E3%81%8C%E8%A1%A8%E7%A4%BA%E3%81%95%E3%82%8C%E3%81%BE%E3%81%9B%E3%82%93/10001821#TPIN-N10088478-N10090272) should be reopened -- Visual Studio should have the ability to emulate a `chcp`ed console for debug execution. 
(It's not normal for the debugee to set the code page since (IMO) console programs should respect the current code page. We normally do `chcp.com <codepage>` and then run a program when we want the program to obey a specific code page.)

Well, when the world is like "There is only one true console code page -- UTF-8", the problem itself disappears. If that is our direction, yeah, #1802 is it.
