### ISSUE TITLE
Rendering Slowness when Terminal is active window and hardware rendering is used

### ISSUE THREAD

**Issue by miketheitguy** [microsoft/terminal#11256] opened 2021-09-17 06:47 UTC
### Windows Terminal version (or Windows build number)

22458.1000, 1.11.2421.0

### Steps to reproduce

Open the Windows Terminal, move mouse around or drag the window around.

### Expected Behavior

Expected behavior is that both the mouse cursor and dragging the terminal window is as smooth as other open windows.

### Actual Behavior

Terminal rendering performance is slow. When Terminal is the active window, my mouse cursor appears to stutter when moving it. When I select any other active window, everything moves smoothly as expected. This also manifests when the terminal is dragged around via its title bar.

This does not occur when Software Rendering is enabled. To make some basics easier, I've included my msinfo32 info to help show what kind of system I've got.

I'm running 2x 4K screens. One is 120Hz, the other is 60Hz. I've attempted to drop the 120Hz to 60Hz to see if maybe the refresh mismatch on the dual monitors was the issue--that didn't fix it. This occurred on the public released Nvidia drivers as well, and is not limited to the current beta 510 series driver.

[msinfo32.txt](https://github.com/microsoft/terminal/files/7183236/msinfo32.txt)

**Comment by miketheitguy** [comment] 2021-09-17 06:49
https://aka.ms/AAdu0um

I've also left feedback on feedback hub for this issue as well.

**Comment by dougestey** [comment] 2021-09-17 15:47
I have this issue as well, but only in 1.11.xx (not the current 1.10.xx release.) Using GSYNC @ 120hz / NVIDIA RTX 3070.

It's a duplicate of https://github.com/microsoft/terminal/issues/649 most likely (and unfortunately.)

I also notice the issue in Slack's store app (and not the standalone desktop app, oddly.) So maybe it's not an Electron-specific bug after all...

**Comment by miketheitguy** [comment] 2021-09-17 15:56
Oh wonderful. Yeah it sounds like it's an issue that they're working on. I hadn't thought about it being related to g-sync; but it makes sense.

**Comment by miniksa** [comment] 2021-09-17 15:57
Yeah... we've been trying a dozen different things to get around this. Please try the GSYNC thing and if that does it, I'll resolve as dupe.

**Comment by miniksa** [comment] 2021-09-17 16:15
/dup #649 

(until proven otherwise for reactivation)

**Closed by miniksa** 2021-09-17 16:15 UTC
Labels: Resolution-Duplicate, Area-Rendering, Issue-Bug, Product-Terminal
