### ISSUE TITLE
Windows terminal crashes when moving to another monitor

### ISSUE THREAD

**Issue by LuckyGinger** [microsoft/terminal#3525] opened 2019-11-11 18:18 UTC
# Environment
Microsoft Windows [Version 10.0.18362.418]

# Steps to reproduce
Open windows terminal and move it with cursor to a new screen in a dual screen setup. Specifically from a 4k to 1080p monitor. 

# Expected behavior
The windows terminal window should move to the other screen.

# Actual behavior
The window when moved to the other screen freezes and then crashes. 

Note: It works if the windows terminal window starts and is maximised on the first monitor and then is win+shift+arrowed to the other monitor. No crash but if it is not maximized and either moved by way of win+shift+arrows OR cursor drag then it crashes.

**Comment by zadjii-msft** [comment] 2019-11-11 18:23
Please make sure to search for duplicates before filing new issues. This is almost a word-for-word duplicate of #3303.

/dup #3303
/dup #2277

Thanks!

**Closed by zadjii-msft** 2019-11-11 18:23 UTC
Labels: Needs-Tag-Fix, Needs-Triage
