### ISSUE TITLE
Unable to start the app, already tried reset, terminate and re-installing the app

### ISSUE THREAD

**Issue by santaji1986** [microsoft/terminal#16294] opened 2023-11-11 12:37 UTC
![image](https://github.com/microsoft/terminal/assets/5300159/25137ebb-d40e-4880-846e-cd045e2b74e2)

**Comment by Xrmastrer55** [comment] 2023-11-11 21:51
im quite new to this all
but have you altered the system at all 
clean up programs, deleteing software of windows, an os change or running as VM ect

**Comment by Xrmastrer55** [comment] 2023-11-11 21:57
> im quite new to this all but have you altered the system at all clean up programs, deleteing software of windows, an os change or running as VM ect

if your running as a vm if so where if you are running it off the windows 11 pro software try factory reseting the vm if your on vurtualbox i cant help you. im new so i might be wrong

**Comment by santaji1986** [comment] 2023-11-11 22:17
I am running the latest windows 10 os on my HP laptop. Not using VM, I have not updated any system files/settings.
I have the exact same issue with PhoneLink app as well.
I have tried to re-install few times but no success with both the apps.

**Comment by Zeroes1** [comment] 2023-11-12 16:08
@santaji1986 try not UWP app, like Microsoft.WindowsTerminalPreview_1.19.2831.0_x64.zip

**Comment by santaji1986** [comment] 2023-11-12 16:55
This is a workaround but I have exactly the same issue with "Phone Link" and "Intel(R) Management and Security Status".

**Comment by lhecker** [comment] 2023-11-15 12:23
This issue is a duplicate of #5764, which is also closed, since it's quite likely the same root cause as other related startup issues. This is a Windows issue, which we don't track in this repository, but we've escalated it internally before. I'm unsure what the state of it is, but I feel like we've seen less reports about it on Windows 11.

On a personal note, if I were to encounter this issue one day, I'd set up Windows from scratch and I recommend you to do the same. This warning is always a sign that your Windows installation is in some form of an unrecoverable, broken state.

/dup #5764

**Closed by lhecker** 2023-11-15 12:23 UTC
Labels: Resolution-Duplicate
