### ISSUE TITLE
Light schemes are unusable: bold text is white

### ISSUE THREAD

**Issue by mscha** [microsoft/terminal#6283] opened 2020-05-31 16:00 UTC
# Environment

```none
Windows build number: 10.0.19041.264
Windows Terminal version (if applicable): 1.0.1401.0

Any other software?
```

# Steps to reproduce

Configure a WSL profile to use a light color scheme, e.g. Solarized Light.
Open that profile.
Output some bold text, e.g.:

    echo `tput bold`Hello`tput sgr0` World

# Expected behavior

Ideally, the output should be:
**Hello** World
with “Hello” in bold.  But as long as bold fonts are not supported, it should be emphasized using a slightly different color.

# Actual behavior

The word “Hello” is white, and therefore basically invisible.  “World” is written in the standard text color.

The “bold color” logic currently assumes that white is a reasonable “bold” color for the standard text color.  This might be true on most dark schemes, but not on light schemes.

**Comment by fishfacemcgee** [comment] 2020-06-03 17:10
There are similar readability issues on Solarized Dark, too:

Solarized Dark:

![image](https://user-images.githubusercontent.com/1767723/83666775-79c9be80-a59b-11ea-9dfe-1b6c77c2540a.png)

Solarized Light:

![image](https://user-images.githubusercontent.com/1767723/83666802-85b58080-a59b-11ea-8aba-ed0c785e84c8.png)

**Comment by Artoria2e5** [comment] 2020-06-03 18:44
This is related to #109. Instead of turning bold into the bright colors, they should have a (default, IMO) option for actual bold text. There's also missing support for italics, underline, etc.

**Comment by DHowett** [comment] 2020-06-03 18:46
![image](https://user-images.githubusercontent.com/189190/83676654-e17a0c80-a58f-11ea-964e-0d99c8952002.png)


but your point stands

**Comment by j4james** [comment] 2020-06-05 00:54
I think this particular issue is more a duplicate of #5682. Regardless of whether we add support for a bold font face, our handling of bright default colors could do with some work. That could include making use of the bold color when the color scheme provides one, or a fallback that just fabricates a brighter version of the default foreground color. At the moment the bright default combo only works if the default color matches one of the first 8 palette entries.

**Comment by zadjii-msft** [comment] 2020-06-05 12:24
Yea, this largely seems like it's discussion that's better suited in #5682. Thanks all!

/dup #5682

**Closed by zadjii-msft** 2020-06-05 12:24 UTC
Labels: Needs-Tag-Fix, Needs-Triage
