### ISSUE TITLE
Show processes in the "Do you want to close all tabs" dialog

### ISSUE THREAD

**Issue by AVDAIN** [microsoft/terminal#5065] opened 2020-03-22 03:10 UTC
# Description of the new feature/enhancement
**If you try to close all processes, the processes should appear in the "Do you want to close all tabs" dialog. This feature can help many developers to solve problems faster.**

# Proposed technical implementation details (optional)
![Anmerkung 2020-03-22 040652](https://user-images.githubusercontent.com/47790579/77241485-ff6fdc00-6bf2-11ea-8066-fd4f5cb761ec.png)

**Comment by DHowett-MSFT** [comment] 2020-03-24 00:08
Yes, this is a great idea. Putting it on the backlog. :smile:

**Comment by Qantex** [comment] 2020-03-25 18:50
Hello @DHowett ,

- **thanks, I also think it's a good idea! 😁**

With kind regards
**Michael**

**Comment by carlos-zamora** [comment] 2020-05-12 22:30
When #5301 goes in, this should be added to it too.

**Comment by carlos-zamora** [comment] 2020-05-12 22:32
The issue mentions listing the attached _processes_, wouldn't it be easier and more clear to present the "tab titles" of each attached TermControl?

**Comment by DHowett-MSFT** [comment] 2020-05-12 22:39
I think processes is more reasonable. Consider.

I run "long_running_server.exe" from powershell, but my tab still says powershell. I care very much, and I want terminal to say "You're about to close *long_running_server.exe*!"

**Comment by carlos-zamora** [comment] 2020-05-12 23:38
In that case, I'm gonna be a bit selfish here and add this into the v2 milestone because that sounds _awesome_! Idk the kind of work involved though haha

**Comment by AVDAX** [comment] 2020-05-13 00:40
@carlos-zamora Thanks, I also think this is a great idea. :)

**Comment by zadjii-msft** [comment] 2022-08-15 11:46
Hey I'm just strolling through the backlog and noticed this is a /dupe of #6549. This one was filed first, but the other has a LOT more notes in it. So I'm gonna use that one to track. Thanks!

**Closed by zadjii-msft** 2022-08-15 11:46 UTC
Labels: Help Wanted, Area-User Interface, Area-TerminalConnection, Product-Terminal, Issue-Task
