### ISSUE TITLE
Opening a tab for PowerShell Core fails with 0x800700c1

### ISSUE THREAD

**Issue by DigiBanks99** [microsoft/terminal#7195] opened 2020-08-06 03:34 UTC
# Environment

```none
Windows build number: 10.0.19041.0
Windows Terminal version (if applicable): 1.1.2021.0

Any other software:
- Visual Studio Community 2019 - 16.7
- Visual Studio Code - 1.47.3
- Cmder - 180626
```

# Steps to reproduce

1. Reset `settings.json` to `defaults.json`.
2. Open the `PowerShell` tab. **Note: Not Windows PowerShell**.

# Expected behavior

The PowerShell Core terminal is opened without reporting an error or at least gives a more descriptive and useful error message.

# Actual behavior

Receive the following error: `[error 0x800700c1 when launching 'C:\Program Files\PowerShell\7\pwsh.exe']`

![image](https://user-images.githubusercontent.com/235971/89487598-31e73380-d7a6-11ea-8cea-0e4eb1821138.png)

**Comment by KalleOlaviNiemitalo** [comment] 2020-08-06 15:37
0x800700c1 is HRESULT_FROM_WIN32(ERROR_BAD_EXE_FORMAT), "%1 is not a valid Win32 application."

Giving "a more descriptive and useful error message" is <https://github.com/microsoft/terminal/issues/7186>. However, ERROR_BAD_EXE_FORMAT seems a bit of a special case because the error message contains "%1". Possible ways to implement:

* Recognize ERROR_BAD_EXE_FORMAT and display a custom message, instead of calling FormatMessage.
* Recognize ERROR_BAD_EXE_FORMAT and replace "%1" with the path.
* Always replace "%1" with the path, no matter what the error code is. But what to do if there is "%2" as well?
* Display the "%1" as is.

I wonder what caused the error in the first place. IIRC, ERROR_BAD_EXE_FORMAT is usually caused by trying to run a 64-bit program on a 32-bit system, but that seems unlikely here because the PowerShell installer should have failed in that case. Are you able to run `C:\Program Files\PowerShell\7\pwsh.exe` if you don't use Windows Terminal?

**Comment by DigiBanks99** [comment] 2020-08-07 04:49
Yes, I can start up PowerShell Core by using Win+R and pasting `C:\Program Files\PowerShell\7\pwsh.exe`.

**Comment by DHowett** [comment] 2020-08-13 01:29
This is wild! And if you run `pwsh.exe` from cmd.exe _inside windows terminal_, does it work?

Just to confirm: other profiles work fine, right?

**Comment by DigiBanks99** [comment] 2020-08-13 04:07
Yes, it starts up fine from `cmd.exe` or `Windows PowerShell` from within the terminal. I'm getting the same issue with `Azure Cloud Shell`:

`[error 0x800700c1 when launching `C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_1.1.2021.0_x64__8wekyb3d8bbwe\TerminalAzBridge.exe']`

**Comment by zadjii-msft** [comment] 2020-08-19 21:43
@DigiBanks99 how did you install the Terminal? The Store, `winget`, `choco`, `scoop`, something else? And what architecture is your PC? 

Also how did you install powershell 7?

**Comment by DigiBanks99** [comment] 2020-08-21 03:29
I installed both the Terminal from the Windows Store and I installed PowerShell 7 via the `PowerShell-7.0.3-win-x64.msi` downloaded from the GitHub release page.

My CPU architecture is x64. I'm using Windows 10 Home on version 2004.

**Comment by dc-rose** [comment] 2020-09-11 13:24
I have exactly the same issue in most respects, the error reported is exactly the same and I can open in all the ways described with the same results. I am not sure if this is relevant but the install was a bit odd. I had powershell preview installed from store (7.1.0-preview.6) it told me that there was an update available and then I updated it via powershell, but I can't remember or find the blog post that it came from and rather than updating preview it installed another powershell  7.0.3 (not exactly an update and not the preview version) but my fault for not understanding the command I was entering. So Windows Terminal was already installed some time ago was working fine and then out of the blue I open another powershell tab and the error described happens and yes I can open it all the other ways but windows terminal is dead to powershell. Any help apreciated.

**Comment by DigiBanks99** [comment] 2020-10-13 03:40
Any news?

**Comment by KalleOlaviNiemitalo** [comment] 2020-10-13 06:48
Two Process Monitor traces of `pwsh.exe` being run by Windows Terminal and by `cmd.exe` might help track down the cause, more so than tracing through CreateProcess with a debugger. Such traces would contain personal information though, e.g. in values of environment variables, so perhaps you'd better compare them yourself than post them in public. The following Process Monitor filter might be suitable:

| Column | Relation | Value | Action |
| --- | --- | --- | --- |
| Process Name | is | WindowsTerminal.exe | Include |
| Process Name | is | pwsh.exe | Include |
| Process Name | is | TerminalAzBridge.exe | Include |
| Event Class | is | Process | Include |
| Event Class | is | Profiling | Exclude |

**Comment by DHowett** [comment] 2020-10-23 02:02
Marking this as feedback for the procmon trace. Thanks @KalleOlaviNiemitalo

**Comment by DigiBanks99** [comment] 2020-10-27 05:58
I'm not sure I understand what you are asking me to do?

**Comment by zadjii-msft** [comment] 2020-10-27 07:39
@KalleOlaviNiemitalo Could you help walk @DigiBanks99 through the process of grabbing a procmon race? I'm not as familiar with procmon so I'm not totally sure how to do it myself 😆

**Comment by Lyt99** [comment] 2020-11-02 17:51
I just encountered the same problem, and I found a file named **'Program'** in my C:\, which seemed to be executed instead of pwsh.exe, then I deleted it and it works fine now.
I tested with creating an executable file C:\Program.exe, and it has been run by terminal
this should be an issue when execute a file with path containing space

**Comment by DigiBanks99** [comment] 2020-11-03 03:06
Thank you! This was exactly my problem. I wonder what put that file there in the first place? Having deleted the C:\Program file fixed my issue. 😊

**Closed** 2020-11-03 03:06 UTC
Labels: Needs-Attention, Needs-Tag-Fix, Needs-Triage

**Comment by LucaSkywaIker** [comment] 2021-01-24 17:58
Wtf is this "Program" File??? Thanks this fixed the problem for me too.

**Comment by AymericG** [comment] 2021-05-24 01:13
Same, I deleted the C:\Programs file and it solved my problem.

**Comment by Robert-lintun** [comment] 2021-07-13 07:54
> I just encountered the same problem with 1.3.2651.0, and I found a file named **'Program'** in my C:\, which seemed to be executed instead of pwsh.exe, then I deleted it and it works fine now.
> I tested with creating an executable file C:\Program.exe, and it has been run by terminal
> this should be an issue when execute a file with path containing space

Seriously?  Thanks for the tips, it fixes my issue.
