### ISSUE TITLE
Bug: Terminal not responding when closing

### ISSUE THREAD

**Issue by azandrew-sidoine** [microsoft/terminal#1667] opened 2019-06-27 09:18 UTC
I just downloaded the preview terminal from microsoft store and each time i tries to close a tab, the terminl just stop responding

**Comment by mrbaranovskiy** [comment] 2019-06-27 11:16
The same.

**Comment by miniksa** [comment] 2019-06-27 22:37
Dupe of #1533

**Closed by miniksa** 2019-06-27 22:37 UTC
Labels: Needs-Tag-Fix, Needs-Triage
