### ISSUE TITLE
Performance regression in latest release

### ISSUE THREAD

**Issue by slurps-mad-rips** [microsoft/terminal#3857] opened 2019-12-05 22:34 UTC
# Environment

```none
Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.18362.0 Microsoft Windows NT 10.0.18362.0
```

Additional information as this might be hardware related:
```none
Gigabyte GV-N 1 1080XTREME-8GD running GeForce Game Ready Driver Version 441.41 at stock settings
2 ViewSonic XG2703-GS at 144hz refresh rate
```

# Steps to reproduce

Open Windows Terminal

# Expected behavior

Refresh rate would stay stable on the initial monitor at 144hz, and drop to a reduced number when focus is given to another monitor as is the current behavior for all other apps. Instead, correct behavior for refresh rate occurs when focus is taken away from Windows Terminal.

# Actual behavior

Refresh rate appears to drop to 30hz in the worst case. My 18K DPI mouse becomes sluggish and almost unresponsive. I have to up the DPI to a ludicrous amount briefly to get the same movement, however rendering becomes an obvious issue, as the mouse will "jump" when moved quickly instead of smoothly transitioning.

# Final Notes

(Breaking from the template a bit to add some additional info)

I noticed that when I click to select text like I might in the powershell core command, the cursor will continue to blink. This did not happen in 0.6 AFAIK. I also was able to confirm this is related to Windows Terminal because
1) Powershell core 6.2 does *not* exhibit this behavior
2) Powershell core when launched via gvim 8's `:term` command does not exhibit this behavior.

My suspicions are that the cursor blinking is responsible for this, however I do not have access to Windows Insider and cannot run a WPR to detect the issue.

Lastly I am *well* aware this is a very bizarre corner case. I mentioned the exact hardware as very recently the video card I have was exhibiting strange behavior in recent games like Jedi Fallen Order, and this behavior seems *specific* to this one video card.

**Comment by DHowett-MSFT** [comment] 2019-12-09 20:37
This looks like it might be a /dupe of #649. Thanks for the report!

**Closed by DHowett-MSFT** 2019-12-09 20:37 UTC
Labels: Needs-Tag-Fix, Needs-Triage
