### ISSUE TITLE
Don't seem to have mouse input to scroll or place cursor in WSL.  (when using Micro text editor for example)

### ISSUE THREAD

**Issue by MostHated** [microsoft/Terminal#667] opened 2019-05-10 15:51 UTC
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)  

Microsoft Windows [Version 10.0.18362.30]

* What's wrong / what should be happening instead:

Hello,  
I can't seem to be able to send mouse input through the terminal, such as when using the Micro text editor (typically I use it when SSH'd into a GCP Ubuntu server). Using the standard Win10 terminal, using "Ubuntu",  or something like ConEmu set to start WSL it works fine to be able to scroll up or down or physically click somewhere within Micro and the cursor will then actually move to the location I clicked instead of having to use the arrow keys to move there. It seems I am only able to mark/highlight text within the Casacadia terminal, but not the text within the actual text editor in which  I am using through SSH. 

Is there a setting or something that I am missing that needs to be enabled, or is this just something that is not added / enabled yet within the new terminal system?

**Comment by zadjii-msft** [comment] 2019-05-10 15:54
This is a dupe of #545

**Closed by zadjii-msft** 2019-05-10 15:54 UTC
