### ISSUE TITLE
Dragging tabs when run as admin crashes Windows Terminal

### ISSUE THREAD

**Issue by driver1998** [microsoft/terminal#4583] opened 2020-02-14 09:45 UTC
# Environment

```none
Windows build number: 10.0.19564.1000
Windows Terminal version (if applicable): 0.9.433.0


Any other software?
```

# Steps to reproduce

Run Windows Terminal as administrator.
Drag the tabs around and try to reorder them.

# Expected behavior
Be able to reorder the tabs.

# Actual behavior
The app crashes.

**Comment by electronic-dk** [comment] 2020-02-14 11:49
Dupe of https://github.com/microsoft/terminal/issues/3581

**Comment by DHowett-MSFT** [comment] 2020-02-14 17:58
Indeed! Thanks. /dup #3581

**Closed by DHowett-MSFT** 2020-02-14 17:58 UTC
Labels: Needs-Tag-Fix, Needs-Triage
