### ISSUE TITLE
korean input buffer is not shown (buffer position is wierd) after some commands

### ISSUE THREAD

**Issue by JuhoKang** [microsoft/terminal#13820] opened 2022-08-23 05:21 UTC
### Windows Terminal version

1.14.1963.0

### Windows build number

10.0.22000.856

### Other Software

any shell (not because of software)

### Steps to reproduce

use some kind of command which has multi line output in shell. I captured some gifs to help you

**example 1 (cmd)**
![cmd](https://user-images.githubusercontent.com/4745294/186074829-04cf2425-7a44-40b0-b469-e71d3ddd8b80.gif)

**example 2 (ubuntu 20.04)**
![ubuntu](https://user-images.githubusercontent.com/4745294/186075892-05a0e12f-7043-4230-b534-e111c170b5b0.gif)

*more info*

As I tried to reproduce the problem I found that after the multi line output in shell the buffer position is not matching well.
You can see in **example2** the position of buffer is below the view.

### Expected Behavior

you can see the korean buffer in the correct position

### Actual Behavior

after a multi line output command. the buffer position is wierd

**Comment by leejy12** [comment] 2022-08-23 09:28
I can reproduce this in Terminal version 1.15.2284.0, Windows Build 22622.575.

This occurs when the output overfills(?) the screen buffer and it scrolls down.
See https://streamable.com/30yx6j

Also, it seems that the more the screen scrolls, the greater the position difference

**Comment by j4james** [comment] 2022-08-23 09:39
I think this is probably the same issue as #13769. There's a fix committed which should be available in the next servicing release.

**Comment by zadjii-msft** [comment] 2022-08-23 10:31
Yea, I'm gonna call this a dupe until proven otherwise. Thanks!

/dup #13769

**Closed by zadjii-msft** 2022-08-23 10:31 UTC
Labels: Issue-Bug, Needs-Triage, Needs-Tag-Fix
