### ISSUE TITLE
The interface cannot be scrolled while running certain commands (e.g., Telnet)

### ISSUE THREAD

**Issue by byyxx128** [microsoft/terminal#14310] opened 2022-10-30 04:10 UTC
### Windows Terminal version
1.15.2875, 1.16.2642.0

### Windows build number
10.0.22000, 10.0.22623

### Steps to reproduce
1. Start Windows Terminal.
2. Type and run `telnet` command.
3. Continue running some commands to fill the screen.
4. Try scrolling the interface.

### Here I use the traditional console (`Command Prompt`) to show you what should be expected. 👇
![Expected](https://user-images.githubusercontent.com/20079289/198862113-8fca6a96-23cd-4556-ba17-6a76954ee2e8.gif)
### Here I use the latest `Windows Terminal` to show you what actually behaved. 👇
![Actual](https://user-images.githubusercontent.com/20079289/198862131-f1fd0f69-76fa-4ee5-b4f9-bc49323e870f.gif)
### The interface cannot be scrolled. 👆

**Comment by lhecker** [comment] 2022-10-30 13:09
This sounds like a /duplicate of #6056. Please let me know if you think this is incorrect. 🙂

**Closed by lhecker** 2022-10-30 13:09 UTC
Labels: Issue-Bug, Needs-Triage
