### ISSUE TITLE
About and Close all dialogs do not correctly show all UI elements

### ISSUE THREAD

**Issue by encladeus** [microsoft/terminal#5195] opened 2020-03-31 16:39 UTC
# Environment

```none
Windows build number: [10.0.18363.720]
Windows Terminal version: latest unreleased build from master

Any other software? No
```

# Steps to reproduce

1. Windows default app mode: light
2. Windows terminal requestedTheme: dark
3. Open **About** or **Close all** dialog
4. Observe not all graphical elements are visible
  a. On the **About** dialog, hover over a hyperlink and observe it disappear
  b. On the **Close all** dialog, observe that the **Cancel** button is not visible (but is active because it Cancels when clicking the area where the button is located.

# Expected behavior

1. **About** dialog: Can see the hyperlink when hovering over it with mouse cursor
2. **Close all** dialog: Can see the **Cancel** button.

# Actual behavior

1. **About** dialog: Cannot see the hyperlink when hovering over it with mouse cursor

![help](https://user-images.githubusercontent.com/8571098/78051634-e3e49e00-7375-11ea-8433-fa24f3bdd594.jpg)

2. **Close all** dialog: Cannot see the **Cancel** button.

![close-all](https://user-images.githubusercontent.com/8571098/78051667-ef37c980-7375-11ea-8d37-5640dc83b738.jpg)

**Comment by DHowett-MSFT** [comment] 2020-03-31 18:25
Just to confirm: this _doesn't_ happen in v0.10 from the store?

**Comment by encladeus** [comment] 2020-03-31 19:05
Correct, this does **not** happen in v0.10 from the store.

**Comment by carlos-zamora** [comment] 2020-03-31 19:06
Tested v0.10.781.0, this does not occur there.
But it does occur on https://github.com/microsoft/terminal/commit/ca6b54e6526396c2367ccf5022429499b45c90b8

**Comment by DHowett-MSFT** [comment] 2020-04-03 00:45
I'm gonna mark this as a /dupe of #3654, since it's the same root cause and solution.

**Closed by DHowett-MSFT** 2020-04-03 00:45 UTC
Labels: Area-User Interface, In-PR, Issue-Bug, Needs-Attention, Priority-1, Product-Terminal
