### ISSUE TITLE
JAWS reads entire window over SSH when typing into nano

### ISSUE THREAD

**Issue by adns44** [microsoft/terminal#16734] opened 2024-02-18 08:41 UTC
### Windows Terminal version

1.20.240129003-preview 

### Windows build number

10.0.22631.3007

### Other Software

JAWS: 2024.2312.53
Win32-OpenSSH: v9.5.0.0p1-Beta
Debian: 12.5
gnu nano: 7.2

### Steps to reproduce

Open a Debian SSH host with ssh.exe from WT with JAWS.
`ssh user@host`
Open nano and start typing.
`nano testfile`

### Expected Behavior

Normal text writing and reading as in a normal editor, like notepad.exe on my local computer.

### Actual Behavior

When I press any letter or symbol to write into the file, JAWS always starts to reread the entire window. I have same experience when I press CTRL+x or other combo. JAWS not reads only the new changed information, instead reads the entire screen.
I have the same experience in VI. Because it does not have head, I hear only the written letters.

**Comment by lhecker** [comment] 2024-02-19 23:14
Since you've given the bot a thumbs up, I'm assuming you agree that this is a duplicate of #14583. I'll be closing this issue then. 🙂 I'm sorry that this doesn't work very well in terminals today. But it is our intention to improve the situation at some point. See #14342 for instance.

/dup #14583

**Closed** 2024-02-19 23:14 UTC
Labels: Issue-Bug
