### ISSUE TITLE
Acrylic does not work in Dev 11 22509.1000

### ISSUE THREAD

**Issue by maisondasilva** [microsoft/terminal#11880] opened 2021-12-04 18:14 UTC
### Windows Terminal version

1.11.2921.0

### Windows build number

11 22509.1000

### Expected Behavior

In Version 22000.348 and terminal 1.11.2921.0 work

Terminal acrilicy and tabs

### Actual Behavior

Terminal and tabs not acrilicy

**Comment by KodiakAS** [comment] 2021-12-05 05:23
Same problem here, and all acrylic effect seems to be disabled in  **Windows 11 22509.1000**, such as the acrylic theme of Intel graphics control panel

**Comment by PhyX-Meow** [comment] 2021-12-06 08:26
Same here, arcylic effect of steam++ also not working.

**Comment by alterseries83** [comment] 2021-12-06 10:21
Same here.

**Comment by zadjii-msft** [comment] 2021-12-06 12:35
Just to make sure, does acrylic work in ~Calculator, or the Start Menu?~ 


er, strike that. Those were updated to use Mica in Windows 11, not acrylic. I'm not sure there are any other built in apps that feature acrylic anymore... Could you try installing the [Xaml Control Gallery](https://www.microsoft.com/en-us/p/xaml-controls-gallery/9msvh128x2zt#activetab=pivot:overviewtab), and navigate to the "Styles > Acrylic" page, and then scroll down to the Custom Acrylic Background Brush sample, and see if that sample has working HostBackdrop acrylic?

see also: https://github.com/microsoft/terminal/wiki/Frequently-Asked-Questions-(FAQ)#why-does-acrylic-not-work


It's very possible this is an OS bug in 22509.1000, but I wanna make sure we've confirmed that the bug is system-wide and not just in the Terminal

**Comment by zadjii-msft** [comment] 2021-12-06 12:45
MSFT:37279273 has links to a PILE of related bugs that got filed in the last two weeks. Looks like this is a known bug! Since this one seems to have a lot of traction, I'll leave it open, but this looks like it's outside the Terminal codebase. I'll let people know when there's something to share. Thanks!

**Comment by maisondasilva** [comment] 2021-12-06 12:57
@zadjii-msft Thank update

**Comment by PhyX-Meow** [comment] 2021-12-06 13:05
@zadjii-msft 
No, it's completely black.
![image](https://user-images.githubusercontent.com/17513581/144851105-f2d25b94-83aa-49c1-9c62-fb3cc8be4e8c.png)

**Comment by arthurfiorette** [comment] 2021-12-06 17:39
Same here, seems that only the acrylic effect stopped working.

**Comment by zadjii-msft** [comment] 2021-12-06 18:20
FWIW we don't need anymore "same here" comments at this point. It's a known issue, and we're following up with the rendering team internally.

**Comment by zadjii-msft** [comment] 2021-12-06 20:08
Looks like the root cause bug was MSFT:37081096, and that one should be fixed in 22515.1000.rs_prerelease.211201-1418. I don't think that's quite flowed out to Insiders yet, but should be out soon<sup>TM</sup>

**Comment by maisondasilva** [comment] 2021-12-08 23:34
@zadjii-msft Problem fix in Dev 22518.1000

**Comment by PhyX-Meow** [comment] 2021-12-09 07:49
Confirm fixed in Dev 22518.1000.

**Comment by zadjii-msft** [comment] 2021-12-09 14:05
Good enough for me, thanks all!

**Closed by zadjii-msft** 2021-12-09 14:05 UTC
Labels: Resolution-External, Needs-Triage, Needs-Tag-Fix, Tracking-External
