### ISSUE TITLE
Commandline argument split-pane subcommand sometimes doesn't work when preceded by a focus-tab subcommand

### ISSUE THREAD

**Issue by slangreck** [microsoft/terminal#5357] opened 2020-04-15 05:53 UTC
# Environment

```none
Windows build number: Version 10.0.18362.752
Windows Terminal version (if applicable): 0.10.781.0
```

# Steps to reproduce

Create a shortcut with this target: `%LOCALAPPDATA%\Microsoft\WindowsApps\wt.exe ; new-tab ; focus-tab -t 0 ; split-pane`. Repeatedly open and close the terminal using this shortcut.

# Expected behavior

The terminal should open with two tabs, the first tab should be focused and split in two.

# Actual behavior

The split-pane often doesn't do anything. The terminal just opens with two tabs and the first tab focused, but no split pane visible. This doesn't always happen. If it happens I can close the terminal and open the shortcut again and it will eventually work.

**Comment by DHowett-MSFT** [comment] 2020-04-15 05:56
This sounds like a /dupe of #4430, which is fixed for 0.11

**Closed by DHowett-MSFT** 2020-04-15 05:56 UTC
Labels: Needs-Tag-Fix, Needs-Triage
