### ISSUE TITLE
background colors extend to end of line when window is resized

### ISSUE THREAD

**Issue by loganfred** [microsoft/terminal#11936] opened 2021-12-13 20:29 UTC
If alternate background colors are used at the end of the printed line, resizing the window will cause the colors to propagate to the full extent of the window. This happens even when the background color is explicitly reset with whitespace characters that use the default color.

The expected behavior is that the color will continue to be confined to the correct string when the window is resized. This works as expected when the color change is in the middle of the line.

I have observed this issue in C# console applications and Powershell 7.2.0 (pictured). Windows Terminal Version: 1.11.2921.0. 

![image](https://user-images.githubusercontent.com/24829027/145882418-3b92c18e-c947-490c-9400-c7feb2837047.png)

pictured code:

```powershell
Write-Host "Resizing this window does not " -NoNewLine ;`
Write-Host " FAIL " -ForegroundColor White -BackgroundColor Red -NoNewLine ; `
Write-Host "`t"
```

**Comment by DHowett** [comment] 2021-12-13 20:41
Thanks for the report! This is a /dupe of #32, one of our oldest issues.

**Closed by DHowett** 2021-12-13 20:41 UTC
Labels: Needs-Triage, Needs-Tag-Fix
