### ISSUE TITLE
Disable color/use grayscale only

### ISSUE THREAD

**Issue by Masterxilo** [microsoft/terminal#11881] opened 2021-12-04 18:42 UTC
# Description of the new feature/enhancement

There should be a way to completely disable colored output, such that windows Terminal renders only in grayscale, potentially only in black & white.

This makes for a more distraction-free experience, especially with some TUIs that overuse color and for people with color vision impairments.

Changing the 8 predefined colors to shades of gray does not accomplish this if the CLI program uses RGB extended-ANSI escape sequences. Since programs can ignore the TERM environment variable, changing that to a terminal that would not support the given escape codes does not stop some programs from outputting them, and Windows Terminal also is unaware of  TERM.

# Proposed technical implementation details (optional)

A new settings property in the json settings structure toggles grayscale/black-white mode.

During translation of ANSI escape sequences to actual per-character attributes, if the no-color attribute is set, convert the color that would be used to grayscale.

Alternatively, while rendering, convert all the color to grayscale.

The Windows 10 builtin fullscreen color filter can be used, but that applies to all programs. Could also propose to Microsoft to make this color filtering a per-program option...

**Comment by j4james** [comment] 2021-12-04 19:12
This looks like a duplicate of #3066.

**Comment by elsaco** [comment] 2021-12-05 21:54
[$NO_COLOR](https://no-color.org/)

**Comment by zadjii-msft** [comment] 2021-12-06 14:25
Yep, this looks like /dup #3066.

A temporary workaround might be using the [Grayscale](https://github.com/microsoft/terminal/blob/main/samples/PixelShaders/Grayscale.hlsl) shader, but that has a bit of a perf hit on less performant machines.

**Closed by zadjii-msft** 2021-12-06 14:26 UTC
Labels: Issue-Feature, Needs-Triage, Needs-Tag-Fix
