### ISSUE TITLE
scroll speed is too fast on the touchpad

### ISSUE THREAD

**Issue by LuanVSO** [microsoft/terminal#3666] opened 2019-11-22 05:25 UTC
# Environment

```none
Windows build number:Microsoft Windows NT 10.0.18363.0
Windows Terminal version (if applicable):0.6.2951.0

Any other software?
no
```

# Steps to reproduce

on a touchpad capable device try scroll using the 2 finger gesture on any terminal
 with some lines on the buffer
# Expected behavior

an slow by line scrolling like on conhost.exe

# Actual behavior

1st - it is too sensitive,  milimeters of movement on the touchpad is enough to go  all the way up or down on the buffer
2nd - it scrolls 4 lines at a time instead of 1 line

**Comment by j4james** [comment] 2019-11-22 18:45
Sounds like a duplicate of #1066.

**Comment by DHowett-MSFT** [comment] 2019-11-22 20:56
Sure is! /dup #1066.

**Closed by DHowett-MSFT** 2019-11-22 20:56 UTC
Labels: Needs-Tag-Fix, Needs-Triage
