### ISSUE TITLE
Cannot copy multibyte characters properly via OSC 52

### ISSUE THREAD

**Issue by amaya382** [microsoft/terminal#7857] opened 2020-10-08 03:02 UTC
# Environment

```none
Windows build number: 10.0.19041.0
Windows Terminal version (if applicable): 1.3.2651.0

Any other software?
WSL2 (20200824 build of Ubuntu 18.04 LTS)
```

# Steps to reproduce

* Open WSL2 shell
* Execute `printf "\x1b]52;;%s\x1b\\" "$(printf '👍' | base64)"` (`U+1F44D`)

# Expected behavior

`👍` in my clipboard.

# Actual behavior

`ð` in my clipboard.

It looks just a garbled string.
garbled string check -> https://onlineutf8tools.com/convert-ascii-to-utf8?input=ð

# Additional Information
Directly copying by right click on WT performs expected behavior.

I'm ready to fix this issue.

**Comment by DHowett** [comment] 2020-10-09 01:13
Thanks for the report! This is a /duplicate of #7819 (which I will rename)

**Closed by DHowett** 2020-10-09 01:13 UTC
Labels: Needs-Tag-Fix, Needs-Triage

**Comment by amaya382** [comment] 2020-10-09 03:20
I couldn't find it because I searched by `OSC` :joy:, thank you for renaming it.
