### ISSUE TITLE
PSReadLine errors on paste of long code 

### ISSUE THREAD

**Issue by dkcecil** [microsoft/terminal#3427] opened 2019-11-04 00:55 UTC
# Environment

```none
Windows build number: 10.0.19013.0
Windows Terminal version (if applicable):0.6.2951.0

Any other software? PSReadLine 2.0.0
```

# Steps to reproduce

Copy a PowerShell function at least twice the height of the terminal window to the clipboard. Right-mouse click paste the code in to terminal.

# Expected behavior

The pasted function works as expected.

# Actual behavior

The terminal window content area "flashes".  Somewhere along the way an error appears--usually, but not always, after a closing brace (}).  The error is, reported in red text, "Oops, something went wrong...Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new".  The issues happens on PS 5.1 and PS 6.

Pasting the same code in to a non-terminal PS 5.1 works as expected with the same version of PSReadLine.

![Error](https://user-images.githubusercontent.com/46634177/68094989-a259d080-fe73-11e9-9478-21f75569f0db.PNG)

**Comment by zadjii-msft** [comment] 2019-11-04 19:52
summoning @lzybkr and @stevel-msft

**Comment by SteveL-MSFT** [comment] 2019-11-04 20:02
This has been fixed in PSReadLine 2.0.0-beta5 (run: install-module psreadline -allowprerelease -force).  We haven't checked it into Windows yet, waiting til we get to GA (not Beta).

**Comment by DHowett-MSFT** [comment] 2019-11-04 20:26
@SteveL-MSFT do you happen to have the number for the upstream PSReadline bug?

**Comment by SteveL-MSFT** [comment] 2019-11-05 23:15
@DHowett-MSFT if you mean in VSO, there isn't one opened yet.  We've been making tactical fixes in WinPS fork of PSRL as needed.

**Comment by DHowett-MSFT** [comment] 2019-11-05 23:20
Alright, fair enough. I was thinking about one on GitHub so we could direct users there :)

**Comment by SteveL-MSFT** [comment] 2019-11-06 18:21
I guess you could say this is a dupe of https://github.com/PowerShell/PSReadLine/issues/1112.  Can't find the original issue.

**Comment by msftrncs** [comment] 2019-11-07 00:15
Note that there are still some errors that will be received while pasting in Windows Terminal even with PSReadLine 2.0.0-beta5.

https://github.com/PowerShell/PSReadLine/issues/1081 has some more on this.  There are two or three different exception reports you may receive (at least in beta5) in this situation of pasting text in to Windows Terminal.  They would all be remedied if the CTRL-ENTER pasting problem was fixed.

**Comment by DHowett-MSFT** [comment] 2019-11-07 00:26
Which it is, as of today!

**Comment by DHowett-MSFT** [comment] 2019-11-07 00:32
In light of that, I’m doing to close this as partially a /dupe of #1091 and partially an external bug.

**Closed by DHowett-MSFT** 2019-11-07 00:32 UTC
Labels: Issue-Bug, Needs-Tag-Fix, Product-Powershell, Product-Terminal, Tracking-External
