### ISSUE TITLE
Display "find" matches in the scrollbar 

### ISSUE THREAD

**Issue by rkeithhill** [microsoft/terminal#8631] opened 2020-12-21 03:28 UTC
# Description of the new feature/enhancement

VSCode has this nice feature where find "matches" are displayed by a certain color (brown here) in the scrollbar e.g.:

![image](https://user-images.githubusercontent.com/5177512/102736140-744a8080-4301-11eb-8f16-dc4f689a3a00.png)

This instantly lets the user know where in the overall file the matches are.  IMO this is even more useful in a console with a large scrollback buffer (10000 lines).  The example above also shows a mini-map to the left of the scrollbar that also shows matches but I think that would cut into the console too much.

# Proposed technical implementation details (optional)

First, while the find dialog is open, ensure the entire scrollbar is visible (not just the little sliver that shows when you're not hovering over the scrollbar).  Second, for every match, display a horizontal line of a discernable color that corresponds to each match location in the scrollback buffer.

**Comment by skyline75489** [comment] 2020-12-21 03:32
#3920 might has some of the feature included.

**Comment by zadjii-msft** [comment] 2020-12-21 12:23
I'm gonna narrow this down to just the scrollbar highlighting, since #6319 is already tracking the "number of matches". Thanks!

**Comment by j4james** [comment] 2020-12-21 23:14
See also #1527 and #2226, which cover similar issues.

**Comment by DHowett** [comment] 2021-01-28 02:20
Actually, yeah, I'm inclined to call this a /dupe of #1527. Thanks for digging, James!

**Closed by DHowett** 2021-01-28 02:20 UTC
Labels: Area-TerminalControl, Area-User Interface, Issue-Feature, Needs-Triage, Product-Terminal
