### ISSUE TITLE
Vim normal mode cursor not present

### ISSUE THREAD

**Issue by kipdec** [microsoft/terminal#7233] opened 2020-08-10 14:44 UTC
# Environment

```none
Windows build number: Win32NT 10.0.18363.0
Windows Terminal version (if applicable): 1.0

Any other software?
Vim
```

# Steps to reproduce

1. Install vim (https://www.vim.org/download.php)
2. Launch Vim from windows terminal: `vim test.txt`

# Expected behavior

- Vim should display a blocky, blinking cursor. See the attached screenshot of powershell running this command. 
<img width="602" alt="vimcursor" src="https://user-images.githubusercontent.com/25524688/89795516-bb1fa280-dae5-11ea-884a-e3c31e6da219.PNG">

# Actual behavior

- Vim displays as if it is in insert mode with a thin cursor despite being in normal mode. See the attached screenshot of Windows terminal running this command. 
<img width="563" alt="vimcursorwindowsterminal" src="https://user-images.githubusercontent.com/25524688/89795535-c07ced00-dae5-11ea-910c-7c1724157650.PNG">

**Comment by skyline75489** [comment] 2020-08-11 04:12
I don't know if you're comfortable with the solution but you can change the cursor style using:

```json
{
        "cursorShape": "filledBox"
}
```

**Comment by kipdec** [comment] 2020-08-11 14:18
Thanks for the help. That changes the cursor style to the expected filled box, but it doesn't change to the expected style in insert mode. The "|".

**Comment by AndysonDK** [comment] 2020-08-17 16:35
You might find a solution here: 
1. https://github.com/microsoft/terminal/issues/4335#issuecomment-577365966
2. https://github.com/microsoft/terminal/issues/4335#issuecomment-670801129

**Comment by DHowett** [comment] 2020-08-21 01:27
So, this is largely a /duplicate of #4335. There's a lot you can do to configure the cursor using the escape sequences documented in those comments, but by and large vim using the Windows cursor Api is just something we're not going to be able to support fully. Once they make the move to VT, we'll be golden.

**Closed by DHowett** 2020-08-21 01:27 UTC
Labels: Needs-Tag-Fix, Needs-Triage
