### ISSUE TITLE
Please add support to Windows server 2019, Version #1909

### ISSUE THREAD

**Issue by 9527KGG** [microsoft/terminal#4416] opened 2020-01-30 18:20 UTC
# Description of the new feature/enhancement

Please add support to Windows server 2019, Version #1909

(https://docs.microsoft.com/en-us/windows-server/get-started/windows-server-release-info)

Windows server does not have Windows store. So provide a way to make it working. 

Thanks.

**Comment by j4james** [comment] 2020-01-30 19:00
I think this might be a duplicate of #1386.

**Comment by DHowett-MSFT** [comment] 2020-01-30 20:26
Sure is! /dup #1386. Thanks!

Additional info:
https://github.com/microsoft/terminal/issues/1643#issuecomment-505971691 https://github.com/microsoft/terminal/issues/1909#issuecomment-510042323 https://github.com/microsoft/terminal/issues/841#issuecomment-492940388 https://github.com/microsoft/terminal/issues/498#issuecomment-490091740 https://github.com/microsoft/terminal/issues/1893#issuecomment-509728952

**Closed by DHowett-MSFT** 2020-01-30 20:26 UTC
Labels: Issue-Feature, Needs-Tag-Fix, Needs-Triage
