### ISSUE TITLE
Ability to set background opacity

### ISSUE THREAD

**Issue by Sahil2004** [microsoft/terminal#5237] opened 2020-04-04 08:54 UTC
At present I am able to set "backgroundImageOpacity" but  I need ability to set background opacity with the default color of the command prompt (i.e. Black) without making it appear gray!

**Comment by j4james** [comment] 2020-04-04 10:27
Is this different from #5145?

**Comment by Sahil2004** [comment] 2020-04-05 05:52
> Is this different from #5145?

Yes it is different from #5145 because I want to have a background opacity like in the picture below. This background opacity means that with the default background color of the terminal (like black in cmd) we can see the apps or desktop below the terminal with an opacity.
![image](https://user-images.githubusercontent.com/40143545/78467870-118f6580-772f-11ea-8b9a-a8389bdeceb2.png)

**Comment by j4james** [comment] 2020-04-05 09:56
Note that you can already get a form of window transparency with the `useAcrylic` and `acrylicOpacity` parameters (see the [Schema Documentation](https://github.com/microsoft/terminal/blob/master/doc/cascadia/SettingsSchema.md) for more details). But if you don't like the acrylic blurred effect, then the feature you're probably asking for is #603.

**Comment by colonelchlorine** [comment] 2020-04-05 13:58
Looks like a duplicate of that ticket. Subscribing in that one and giving it a thumbs up. I see it's on "Terminal Backlog" ... sounds ominous ;)

**Comment by DHowett-MSFT** [comment] 2020-04-05 23:12
Yep, this is a /dupe of #603 -- we're not prioritizing it for version 1.0, but we absolutely think it's valuable and want to nail it at some point. 

I just marked it `Help-Wanted`--it's a small token, and doesn't mean _too_ much because we're all community-driven--which should tell people that we'd welcome contributions :smile:

When we initially specified acrylic, we wanted to expand it to some sort of "material gallery" -- glass, diffuse perspex, acrylic, all sorts of fun things. This would be on the glassier side of material.

**Closed by DHowett-MSFT** 2020-04-05 23:12 UTC
Labels: Needs-Tag-Fix, Needs-Triage
