### ISSUE TITLE
Add command line flag to start in focus mode

### ISSUE THREAD

**Issue by lumlune** [microsoft/terminal#7875] opened 2020-10-09 22:47 UTC
# Description of the new feature/enhancement

#6804 made it possible to strip the terminal of window decorations with the `toggleFocusMode` command.

It would be nice to invoke the terminal with this behavior already applied.

# Proposed technical implementation details

A simple command line flag like:

```
wt.exe --focus-mode
```

to simplify the process:

```
wt.exe
*wait for terminal window to open*
*open command palette or press keybinding to start focus mode*
```

**Comment by alannt777** [comment] 2020-10-10 02:55
Duplicate of #7825

**Comment by alannt777** [comment] 2020-10-10 02:56
Being tracked in #4632

**Comment by Don-Vito** [comment] 2020-10-10 04:38
> 
> 
> Duplicate of #7825

@alannt777 - I am not sure this is exact duplicate: in this ticket there is a request for command line argument, while in https://github.com/microsoft/terminal/issues/7825 the request is for launchMode setting (the fix for which is in PR: https://github.com/microsoft/terminal/pull/7873)

**Comment by alannt777** [comment] 2020-10-10 04:42
@Don-Vito 

In #4632 
>  Add command-line option start terminal in focus mode (after/during #7825)

**Comment by Don-Vito** [comment] 2020-10-10 04:47
> 
> 
> @Don-Vito
> 
> In #4632
> 
> > Add command-line option start terminal in focus mode (after/during #7825)

@alannt777 - absolutely agree, that https://github.com/microsoft/terminal/issues/4632 mentions a command-line option, and this one is definitely duplicate to it.

Just mentioned that this is not duplicate of https://github.com/microsoft/terminal/issues/7825 (so this one will not be closed by mistake when https://github.com/microsoft/terminal/issues/7825 gets closed).

**Closed** 2020-10-10 05:25 UTC
Labels: Issue-Feature, Needs-Tag-Fix, Needs-Triage
