### ISSUE TITLE
Missing cmd shortcuts in Terminal

### ISSUE THREAD

**Issue by jcdiprose** [microsoft/terminal#4253] opened 2020-01-16 02:00 UTC
Ctrl+A: Selects all text on the current line. Press Ctrl+A again to select all text in the CMD buffer.
Shift+Left Arrow/Right Arrow: Extend current selection by one character to the left or right.
Shift+Ctrl+Left Arrow/Right Arrow: Extend current selection by one word to the left or right.
Shift+Arrow Up/Arrow Down: Extend current selection by one line up or down. The selection extends to the same position in the previous or next line as the position of the insertion point in the current line.
Shift+Home: Extend current selection to the beginning of a command. Press Shift+Home again to include the path (e.g., C:\Windows\system32) in the selection.
Shift+End: Extend current selection to the end of the current line.
Ctrl+Shift+Home/End: Extent current selection to the beginning or end of the screen buffer (respectively).
Shift+Page Up/Page Down: Extend current selection by one page up or down.

**None of these work**

**Comment by carlos-zamora** [comment] 2020-01-16 21:17
> Shift+Left Arrow/Right Arrow: Extend current selection by one character to the left or right.
> Shift+Ctrl+Left Arrow/Right Arrow: Extend current selection by one word to the left or right.
> Shift+Arrow Up/Arrow Down: Extend current selection by one line up or down. The selection extends to the same position in the previous or next line as the position of the insertion point in the current line.
> Shift+End: Extend current selection to the end of the current line.
> Ctrl+Shift+Home/End: Extent current selection to the beginning or end of the screen buffer (respectively).
> Shift+Page Up/Page Down: Extend current selection by one page up or down.

These are a part of #715. You can hop on for a further discussion there or in the spec (#2840) if you're interested.


> Ctrl+A: Selects all text on the current line. Press Ctrl+A again to select all text in the CMD buffer.
> Shift+Home: Extend current selection to the beginning of a command. Press Shift+Home again to include the path (e.g., C:\Windows\system32) in the selection.

These particular commands are a little tricky. CMD uses CookedRead so it's aware of what is in the command line itself (as opposed to the buffer). That's why the first time these are pressed, the commands are highlighted appropriately. I think these will be an issue given the current implementation/spec so they need to be addressed properly in #2840. @DHowett-MSFT any ideas on how to get around this issue?

**Comment by DHowett-MSFT** [comment] 2020-01-23 23:44
Shift+Home is part of conhost's cooked_read implementation. There's nothing Terminal can do to mimic the behavior there. I believe we have a duplicate of that issue; have you seen it?

**Comment by jcdiprose** [comment] 2020-01-23 23:55
Nice to know clearing the line with shift and home or end works, I am in no sense competent at cmd just thought I'd share my experiences using terminal over it and my message highlighted the issues I had. Terminal is great and mostly beneficial for me with the multiple tabs, can't go without it now. Thanks

**Comment by tedhudek** [comment] 2020-01-29 00:13
Would this issue include ctrl+backspace?  I realized I use this all the time in PowerShell cmd but it doesn't work in Terminal.  I don't see a setting for "delete previous word" in default settings.  Please let me know if I should open a separate issue to request that.  Thank you!

**Comment by jcdiprose** [comment] 2020-01-29 00:37
Ctrl + backspace is one of my main issues and would be great

**Comment by tedhudek** [comment] 2020-01-29 00:40
You can do it in two keystrokes (ctrl+left arrow, ctrl+del) but it's hard to retrain the muscle memory :)

**Comment by DHowett-MSFT** [comment] 2020-01-29 00:42
As of 0.8.10261.0, ctrl+backspace definitely works in terminal in cmd.

**Comment by jcdiprose** [comment] 2020-01-29 00:44
Good to know, thanks, I guess an update is in order

**Comment by DHowett-MSFT** [comment] 2020-03-06 00:13
I believe most of these are covered by the other issues mentioned. Thanks for the request!

**Closed by DHowett-MSFT** 2020-03-06 00:13 UTC
Labels: Needs-Tag-Fix, Needs-Triage
