### ISSUE TITLE
Feature Request - add git bash 

### ISSUE THREAD

**Issue by crazyhappygame** [microsoft/terminal#2454] opened 2019-08-16 18:38 UTC
# Description of the new feature/enhancement
Please add support for git bash https://git-scm.com/downloads

# Proposed technical implementation details (optional)
It is added automatically if git is installed in default folder

p.s.:
I tried below configuration but most of commands git status, git log do not work - lines are not displayed
```
        {
            "acrylicOpacity" : 0.5,
            "closeOnExit" : true,
            "colorTable" : 
            [
                "#000000",
                "#000000",
                "#000000",
                "#000000",
                "#000000",
                "#000000",
                "#000000",
                "#000000",
                "#000000",
                "#000000",
                "#000000",
                "#000000",
                "#000000",
                "#000000",
                "#000000",
                "#000000"
            ],
            "commandline" : "C:\\Program Files\\Git\\bin\\bash.exe",
            "cursorColor" : "#FFFFFF",
            "cursorShape" : "bar",
            "fontFace" : "Consolas",
            "fontSize" : 10,
            "guid" : "{12b5ab39-a22b-42b2-a72c-e3a23132c3b9}",
            "historySize" : 9001,
            "icon" : "C:\\Program Files\\Git\\mingw64\\share\\git\\git-for-windows.ico",
            "name" : "Git Bash",
            "padding" : "0, 0, 0, 0",
            "snapOnInput" : true,
            "startingDirectory" : "%HOMEDRIVE%%HOMEPATH%",
            "useAcrylic" : false
        }
```

**Comment by crazyhappygame** [comment] 2019-08-16 18:45
With below config git bash works fine for me. But any way it would be nice to have native support
```
    {
        "acrylicOpacity": 0.5,
        "background": "#012456",
        "closeOnExit": true,
        "colorScheme": "Solarized Dark",
        "commandline": "C:\\Program Files\\Git\\bin\\bash.exe",
        "cursorColor": "#FFFFFF",
        "cursorShape": "bar",
        "fontFace": "Consolas",
        "fontSize": 10,
        "guid": "{72a69aca-322e-465d-a799-1d64dff65269}",
        "historySize": 9001,
        "icon": "C:\\Program Files\\Git\\git-bash.png",
        "name": "Git Bash",
        "padding": "0, 0, 0, 0",
        "snapOnInput": true,
        "startingDirectory": "%USERPROFILE%",
        "useAcrylic": false
      }
```

**Comment by zadjii-msft** [comment] 2019-08-16 19:28
This is a dupe of #1394

**Closed by zadjii-msft** 2019-08-16 19:28 UTC
Labels: Issue-Feature, Needs-Tag-Fix, Needs-Triage

**Comment by diligamer** [comment] 2020-01-16 21:06
The code above no longer works as of 0.8

**Comment by DHowett-MSFT** [comment] 2020-01-16 22:01
_Can you share exactly how it doesn't work?_
