### ISSUE TITLE
Tabs can be invisible even when scrolled into view

### ISSUE THREAD

**Issue by rennex** [microsoft/terminal#3151] opened 2019-10-11 10:43 UTC
# Environment

```none
Windows build number: Version 10.0.18990.1
Windows Terminal version: 0.5.2762.0
```

# Steps to reproduce

1. Open a couple more tabs than what fits in the window
2. Scroll the tab bar to see the new tabs

# Expected behavior

Tabs should not be invisible.

# Actual behavior

Some tabs are invisible, and one tab may be cut off. See the screenshot; the empty space between the last tab (which is cut off) and the "plus" button contains one invisible tab.

![image](https://user-images.githubusercontent.com/449856/66645441-1bc32200-ec2c-11e9-9fd0-4f77068e05ad.png)

Resizing the window even a little makes the tabs appear.

**Comment by DHowett-MSFT** [comment] 2019-10-11 15:39
Thanks for the report! This is a /dupe of #857

**Closed by DHowett-MSFT** 2019-10-11 15:39 UTC
Labels: Needs-Tag-Fix, Needs-Triage

**Comment by rennex** [comment] 2019-10-11 21:22
Yes, I see someone later mentioned invisible tabs in that other issue as well.
