### ISSUE TITLE
Maximize and minimize window buttons incorrect rendering

### ISSUE THREAD

**Issue by JekRock** [microsoft/terminal#4288] opened 2020-01-18 12:08 UTC
# Environment

```none
Windows build number: 10.0.18363.0
Windows Terminal version (if applicable):0.8.10091.0
```

# Steps to reproduce

1. Minimize the Windows Terminal window
2. Open enough terminal tabs to fill tabs space without tabs being resized.
3. Maximize the Windows Terminal window with the window maximize button.
4. Minimize the Windows Terminal window with the window minimize button.
5. Get an incorrect rendering of the minimize and maximize buttons.

On step 2 you will probably need to play with the Windows Terminal window size to reproduce the issue. For some window sizes, it renders normally and for some not. If you add too many terminal tabs the issue is not reproducible.

# Expected behavior

Normal rendering of the window minimize and maximize buttons after minimizing the Windows Terminal window

# Actual behavior

See attached screenshots.
![image](https://user-images.githubusercontent.com/5882133/72663459-b2f1ff80-39fb-11ea-9dcf-2bc9a423e47f.png)
![image](https://user-images.githubusercontent.com/5882133/72663470-c9985680-39fb-11ea-883a-5c781926e60a.png)
![image](https://user-images.githubusercontent.com/5882133/72663479-d9179f80-39fb-11ea-8504-c83ad35e4878.png)

**Comment by zadjii-msft** [comment] 2020-01-21 16:02
_from #4310_:

@DHowett-MSFT 
> What is your display scaling set to?

@JekRock 
> I've stumbled upon the same issue. It's described [here](https://github.com/microsoft/terminal/issues/4288)
> I have 2 displays. One with 100% scaling and one with 125%. The issue is reproducible on both displays

**Comment by DHowett-MSFT** [comment] 2020-01-23 23:49
It looks like we're not placing the drag cutout in the right place. Might be part of #1625.

**Comment by DHowett-MSFT** [comment] 2020-01-23 23:49
v0.10 justification: it's experience-breaking.

**Comment by DHowett-MSFT** [comment] 2020-03-02 19:21
I'm going to call this a "bug class" and merge it with /dup #4166 - "we are not sizing the drag bar properly all the time"

**Comment by greg904** [comment] 2020-03-06 23:48
@zadjii-msft

This was marked duplicate of #4166 and #4166 was closed but I can still reproduce this bug on master (cc35c83e) on my 100% dpi displays (maybe it was not a dup and it has nothing to do with DPI!).

steps:
![test](https://user-images.githubusercontent.com/56923875/76131079-609d8a00-600d-11ea-93d8-a46d44868b4e.gif)

**Comment by zadjii-msft** [comment] 2020-03-09 13:54
Okay yea I can re-activate this one and make sure this gets fixed too. 

Thanks for the diligence @greg904!

**Closed** 2020-03-09 17:54 UTC
Labels: Area-User Interface, In-PR, Issue-Bug, Priority-2, Product-Terminal, v1-Scrubbed
