### ISSUE TITLE
Ability to switch text wrapping off

### ISSUE THREAD

**Issue by marveloo** [microsoft/terminal#6730] opened 2020-06-30 16:11 UTC
# Description of the new feature/enhancement

I made a Windows terminal profile for MySQL command line interface. The problem is that each time I do `select * from table_with_many_columns` I get a result which is unreadable because of text wrapping which is always on in Windows terminal. Therefore we need an ability to turn it off. 

# Proposed implementation details

The good old Command Prompt window allows us to switch text wrapping off as well as set screen buffer width to a value of our choice (e.g. `2000`) via window properties. Windows terminal needs similar configuration settings which could be set for different terminal profiles independently.

If Windows terminal were able to to deal with screen buffer width automatically (without having to set it explicitly), it would be even better.

As a bonus request, the ability to toggle text wrapping mode with a hot key in any window/tab would be welcome too.

**Comment by j4james** [comment] 2020-06-30 17:21
This has been requested before, but the answer was that it's not going to be supported in Windows Terminal. Sorry. For more details, see issue https://github.com/microsoft/terminal/issues/1860#issuecomment-509311231.

**Comment by marveloo** [comment] 2020-06-30 23:00
I am sorry to sound daft, as I clearly don't understand something here, but why is Windows terminal unable to load a wide window (of fixed width) behind the scenes with only a part of the window visible to the user and a horizontal scrollbar to move that window from side to side? The shell itself may not even be aware of me staring at it throw a smaller size window. In other words all this thing could be implemented on the UI part only by letting the shell think that I am on a wider window than it actually is.

**Comment by DHowett** [comment] 2020-06-30 23:36
I'm going to close this one out as a /duplicate of #1860 and address your question there :smile:

**Closed by DHowett** 2020-06-30 23:36 UTC
Labels: Issue-Feature, Needs-Tag-Fix, Needs-Triage
