### ISSUE TITLE
Terminal opens and then immediately crashes

### ISSUE THREAD

**Issue by MikeRomaa** [microsoft/terminal#16730] opened 2024-02-17 17:26 UTC
### Windows Terminal version

1.19.10302.0

### Windows build number

10.0.22635.0

### Steps to reproduce

1. Open Powershell or WSL with Windows Terminal set as the default terminal application.
2. Crash 💥

### Actual Behavior

When I attempt to open Powershell or a WSL shell through Terminal (as shown in the video below), the Terminal briefly opens and then crashes.

If I try to open the Terminal application directly, where Powershell is my default, then it doesn't even open.

https://github.com/microsoft/terminal/assets/19419678/aec79e1a-2a30-4313-9858-c4eadc45ce8f

**Comment by MikeRomaa** [comment] 2024-02-17 17:26
https://aka.ms/AAp5jzy

**Comment by MikeRomaa** [comment] 2024-02-17 17:28
I've also noticed that the behavior is very inconsistent. Sometimes I can open Terminal with the executable and it will work just fine, but as soon as I try to open a new tab it crashes.

**Comment by lws123321** [comment] 2024-02-19 02:15
Yes, it will crash whenever I open a new tab or split a pane.

**Comment by DanielYang59** [comment] 2024-02-19 02:24
I'm having some similar issue here, which seems to be preventing WSL2 from starting directly through the APP icon (not sure though) [WSL issue #11176](https://github.com/microsoft/WSL/issues/11176).

Not sure what is the reason though.

![terminal](https://github.com/microsoft/terminal/assets/80093591/e0660e01-c1b1-4773-8a11-390fb74d8377)

**Comment by Penguin-SAMA** [comment] 2024-02-19 06:29
the same

**Comment by lws123321** [comment] 2024-02-19 06:56
It seems that the problem occurred after updating to version 1.19.10302.0,  I have not reproduced this problem on other computers using version 1.18.10301.0.

**Comment by lws123321** [comment] 2024-02-19 07:02
I tried rolling back the version to 1.18.10301 and it was no problem
![image](https://github.com/microsoft/terminal/assets/71438345/9201eb6c-97db-4e84-a326-100538d439d2)

**Comment by zadjii-msft** [comment] 2024-02-19 12:21
At least for @MikeRomaa, it looks like you have MacType installed. There's a known bug in mactype that can cause crashes in the Terminal. Fortunately, they have already fixed it - I'd go update mactype. 

* your bucket was `24b90891-d74d-e874-c85b-28c1195c615f` "INVALID_POINTER_READ_c0000005_MacType64.Core.dll!Unknown"
* #15792
* /dup https://github.com/snowie2000/mactype/pull/938
* see also https://github.com/snowie2000/mactype/issues/607
* fix is in https://github.com/snowie2000/mactype/releases/tag/v1.2023.5.31

----

If there's anyone in this thread that's _not_ using mactype, then I suggest you file a new issue, with a feedback hub crash trace and a aka.ms link to that feedback so we can investigate. Thanks!

**Closed by zadjii-msft** 2024-02-19 12:21 UTC
Labels: Issue-Bug, Needs-Triage

**Comment by lws123321** [comment] 2024-02-20 00:50
Yes, I also use macType. After I upgraded the version to v1.2023.5.31, I upgraded again and used Terminal 1.19.10302 and it no longer crashed.

**Comment by DanielYang59** [comment] 2024-02-20 14:35
Thanks @zadjii-msft, could confirm this issue is gone after removal of MacType (decide to remove it because it doesn't seem to be actively maintained 😞 ).
