### ISSUE TITLE
Font Cascadia Mono cannot be found

### ISSUE THREAD

**Issue by Dany-HBK** [microsoft/terminal#16194] opened 2023-10-19 05:28 UTC
Since today (there was an app update) on starting Windows Terminal there pops up a warning, that the font Cascadia Mono could not be found and it would use Consolas instead. I should re-install it or change it (which I don't know where as I could not find a setting).
Opening Powershell directly, there is no such warning and the set font is indeed Consolas.

**Comment by lhecker** [comment] 2023-10-19 11:01
When submitting issues, please use the issue templates. If you don't know which one to use, use "Bug report".

I'll mark this as a /duplicate of #16058. In the meantime you can work around this issue by running this in an Admin cmd prompt or PowerShell window:
```
sc stop fontcache
sc start fontcache
```

**Closed** 2023-10-19 11:03 UTC
Labels: Needs-Tag-Fix
