### ISSUE TITLE
Bug Report - terminal tabs

### ISSUE THREAD

**Issue by nodew** [microsoft/terminal#1662] opened 2019-06-27 03:34 UTC
I just installed terminal preview version on my PC.
Some problems on tab operation:
1. The tab's UX behavior is strange. Even I just open only one tab, it take the white place which not needed. it's hard to drag the window around. 
2. Besides, another strange behevior is, if I open mulitple tabs, I can't see all the tabs I open, because they are hidden.
3. The tab show full path of cmd or powershell exec path as title, it's not a necessary, since the icon is different, instead, we can use the command it's running or user customized name.

Expection:
What edge do is great, you can drag a new window from a tab, you can see the preview when hover, more, you can set the tabs aside, and recover them if needed.

**Comment by bwahacker** [comment] 2019-06-27 14:14
Agreed; it's hard to move the window, hard to change the window width, etc.  Tab bar crammed into the window title bar is just too dense.

**Comment by miniksa** [comment] 2019-06-27 22:41
1. Dupe of #564 
2. Dupe of #857 
3. Dupe of #608 

And your entire series of complaining is a dupe to #1375.

Please search before filing. Please read the stickied issues before filing. Please file one bug per issue.

**Closed by miniksa** 2019-06-27 22:41 UTC
Labels: Needs-Tag-Fix, Needs-Triage
