### ISSUE TITLE
Many emojis and other non-ascii characters are having troubles to be shown

### ISSUE THREAD

**Issue by AmyrAhmady** [microsoft/terminal#4512] opened 2020-02-09 11:36 UTC
Hello there, today I finally wanted to try new windows terminal, for a project that has emojis in it and I found this terminal very suitable for this, but I'm kinda having some problems with it, Emojis aren't shown as it should, many of them are shown as question marks, some work
but here's the interesting part, if current window gets updated (like resizing it), everything suddenly works and those question marks turn into emojis
here's a GIF to show what I'm currently experiencing:
![2](https://user-images.githubusercontent.com/34688664/74101277-6ce91100-4b4d-11ea-8226-8e1a0889d283.gif)

# Environment
Microsoft Windows [Version 10.0.18363.592]
Windows Terminal version: Latest from MS Store (0.8.10261.0)

# Steps to reproduce
No clue, asked a few friends and some where experiencing the same issue as mine, it's more like default thing for us.

# Expected behavior
Showing emojis without any issue

# Actual behavior
printing out question marks

**Comment by j4james** [comment] 2020-02-09 13:41
This sounds like a duplicate of #1503 and/or #529.

**Comment by AmyrAhmady** [comment] 2020-02-09 13:55
seems like it, this works for me as well :
https://github.com/microsoft/terminal/issues/1503#issuecomment-571154874

**Comment by theuserbl** [comment] 2020-02-09 14:26
It is also interesting, which files are displayed with emojis.

notepad.exe can create text files in "UTF-16 LE" (little endian), "UTF-16 BE" (big endian), "ANSI", "UTF-8" and "UTF-8 with BOM" (with Byte Order Mark).
Only the unicode formats (UTF) can save emojis.

`.... Windows PowerShell ... cmd ... Ubuntu 19.10 Terminal .. PowerShell 6.2.4 on Ubuntu`
`UTF-8 ........... no ...... no .............. yes ................... yes .............`
`UTF-8 with BOM .. yes ..... no .............. yes ................... yes .............` 
`UTF-16 LE ....... yes ..... yes ............. no .................... yes .............`
`UTF-16 BE ....... yes ..... no .............. no .................... yes .............`

With Ubuntu I don't mean WSL. Its the complete Ubuntu on VirtualBox.

**Comment by j4james** [comment] 2020-02-09 15:03
@theuserbl FYI, you can get better results displaying UTF-8 files in the cmd shell by changing the codepage to UTF-8 (with `chcp 65001`).

**Comment by zadjii-msft** [comment] 2020-02-10 15:35
@cinnamon-msft @miniksa I think for 1.0, we'll need to have a doc that outlines where emoji will and won't work in the Terminal. Like enumerate the fact that the `cmd` (et. al) cooked read won't support it, but ubuntu/wsl in general will. I think this might help stem the flow of "emoji doesn't work" issues, if we had a doc pointing to various scenarios and _why_ they don't work.

**Comment by DHowett-MSFT** [comment] 2020-02-10 20:16
I'm going to close this one as a /dupe of #1503, which i've renamed to contain a bit more information.

**Closed by DHowett-MSFT** 2020-02-10 20:17 UTC
Labels: Needs-Tag-Fix, Needs-Triage
