### ISSUE TITLE
Feature Request - Tab design with minimum width

### ISSUE THREAD

**Issue by cloudrex** [microsoft/terminal#3266] opened 2019-10-20 16:38 UTC
# Description of the new feature/enhancement
When opening a new CMD tab, the width of the tab is small due to the name of the prompt being small "cmd." This makes it a little uncomfortable, and if the tabs were to have a minimum width it would give it more space, specially when you're blazing through tabs and don't want to accidentally close the tab.

I think that the minimum width I highlited below would be way better than the smaller CMD tab.

![image](https://user-images.githubusercontent.com/41349879/67162865-8237f680-f336-11e9-856c-42b40159f92e.png)

**Comment by DHowett-MSFT** [comment] 2019-10-21 19:39
This is a /dupe of #597. Thanks!

**Closed by DHowett-MSFT** 2019-10-21 19:39 UTC
Labels: Issue-Feature, Needs-Tag-Fix, Needs-Triage
