### ISSUE TITLE
PowerToy FancyZone Support

### ISSUE THREAD

**Issue by fpiscite** [microsoft/terminal#3191] opened 2019-10-14 15:33 UTC
It would be nice if the terminal would support the FancyZones Powertoy published by MS.

I would like to be able to "shift" drag the window and have it SNAP to the various zones in my desktop. Other "apps" seem to work with it (like Sticky Notes).

**Comment by DHowett-MSFT** [comment] 2019-10-14 17:39
This is a /dupe of #2905, which is actually a dupe of microsoft/PowerToys#209

**Closed** 2019-10-14 17:40 UTC
Labels: Issue-Feature, Needs-Tag-Fix, Needs-Triage
