### ISSUE TITLE
[crash] Right-click-on-tab menu is unstable

### ISSUE THREAD

**Issue by pstaag** [microsoft/terminal#8985] opened 2021-02-01 07:44 UTC
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.19042.746]
Windows Terminal version (if applicable): 1.5.10271.0

Any other software?
```

# Steps to reproduce
1. Right click on an open Tab
2. Move the mouse cursor slowly downward from the first menu entry down to the last.
3. Move the mouse cursor slowly upward again from the last menu entry up to the first.
4. Move the mouse cursor *faster* downward from the first menu entry down to the last.
5. Move the mouse cursor *faster* upward again from the last menu entry up to the first.
(step 4 and 5 may need to be repeated a few times.)
6. Boom. Crash.

What you want to achieve, I think, is that you want the *Close...* submenu to be rendered once, and removed again. And after that, you want the mouse pointer to trigger the Ux-thing that once again renders the menu while you move the cursor fast enough that it's actually not rendered because the mouse cursor has already passed the *Close...* menu option.

# Expected behavior

Normal menu rendering without a crash.

# Actual behavior

Possible to crash the app by moving the mouse cursor up and down above the menu.

**Comment by rashil2000** [comment] 2021-02-01 07:56
Can confirm this. I only needed to do step 4-5 once.

**Comment by zadjii-msft** [comment] 2021-02-01 11:26
This is a duplicate of #8238, which we're tracking reverting in #8944. Thanks!

/dup #8238

**Closed by zadjii-msft** 2021-02-01 11:26 UTC
Labels: Needs-Tag-Fix, Needs-Triage
