### ISSUE TITLE
Feature Request: ctrl + ` to bring terminal to the foreground

### ISSUE THREAD

**Issue by HIMISOCOOL** [microsoft/terminal#1937] opened 2019-07-12 03:36 UTC
# Summary of the new feature/enhancement
My most used feature of Cmder is the shortcut to bring Cmder to the foreground whether it is minimized or just in the background and then minimize it when it is open.
by default that's ctrl + ` 
It overrides a few programs because the key combo is no longer passed through to the current foreground task, notably Vscode wont toggle console because Cmder captures it, which is a desirable outcome for me.

**Comment by amithegde** [comment] 2019-07-13 08:59
see #653

**Comment by amithegde** [comment] 2019-07-13 09:00
I replaced VSCode shortcut to `Alt+~`

**Comment by DHowett-MSFT** [comment] 2019-07-13 19:16
This'll be a duplicate of 653. Thanks!

**Closed by DHowett-MSFT** 2019-07-13 19:16 UTC
Labels: Issue-Feature, Needs-Tag-Fix, Needs-Triage
