### ISSUE TITLE
how  can i merge two terminal windows into one ?

### ISSUE THREAD

**Issue by meteordragon** [microsoft/terminal#6988] opened 2020-07-21 10:21 UTC
two windows
![image](https://user-images.githubusercontent.com/34377397/88042588-c0d93680-cb7e-11ea-805f-c7fd8d7a2be7.png)
into one
![image](https://user-images.githubusercontent.com/34377397/88042688-e8c89a00-cb7e-11ea-9b7e-5306529e49a3.png)

**Comment by KalleOlaviNiemitalo** [comment] 2020-07-21 12:19
This is a duplicate of <https://github.com/microsoft/terminal/issues/1256>.

**Comment by zadjii-msft** [comment] 2020-07-21 12:53
Sure is!

/dup #1256

**Closed by zadjii-msft** 2020-07-21 12:53 UTC
Labels: Issue-Docs, Needs-Tag-Fix, Needs-Triage
