### ISSUE TITLE
Terminal: Implement a settings screen

### ISSUE THREAD

**Issue by ExE-Boss** [microsoft/terminal#2436] opened 2019-08-15 12:30 UTC
## Description of the new feature/enhancement
Currently, the **Settings** button opens `profiles.json` in a text editor.

This is not only bad UX, but it’s also error prone due to JSON’s strict syntax and no error recovery.

## Proposed technical implementation details
The **Settings** button would either open a settings tab (like **VS Code**), or a settings window (like **conhost.exe**).

This new **Settings Editor** would provide a more user‑friendly approach to editing `profiles.json`, with the option to open it directly in a text editor when truly needed.

## Additional notes
**Visual Studio Code** has started doing this [as the default since version 1.27](https://code.visualstudio.com/updates/v1_27#_settings-editor), and I expect the **Windows Terminal** to eventually do the same.

**Comment by zadjii-msft** [comment] 2019-08-15 12:48
This is a dupe of #1564.

**Closed by zadjii-msft** 2019-08-15 12:48 UTC
Labels: Issue-Feature, Needs-Tag-Fix, Needs-Triage
