### ISSUE TITLE
Some glyphs in Nerd Fonts are rendered with wrong widths

### ISSUE THREAD

**Issue by benfowler** [microsoft/terminal#11769] opened 2021-11-16 22:29 UTC
### Windows Terminal version

1.12.2931.0

### Windows build number

10.0.19042.0

### Other Software

* Font: CaskaydiaCove Nerd Font

### Steps to reproduce

1. Open Windows Terminal Preview with a clean configuration
2. Obtain the "CaskaydiaCove Nerd Font" (patched stock Windows Terminal font), and install it via `choco install cascadia-code-nerd-font`
3. Output the characters onto the console. I've made the attached text file to do a minimal reproduction of this issue: [break_tmux_nf_glyph_broken_under_msterm.txt](https://github.com/microsoft/terminal/files/7550146/break_tmux_nf_glyph_broken_under_msterm.txt)
    - `nf-mdi-play` (f909) and `nf-mdi-stop` (f9da). Character width, cell width get confused, especially depending on what character follows 'odd' character, and how many there are on a given line.
    - **NOTE**: Other glyphs, e.g.   `nf-custom-folder-github` (e5fd) **render correctly**
    - For more information on Nerd Font glyphs, see the [Nerd Font Cheat Sheet](https://www.nerdfonts.com/cheat-sheet)

### Expected Behavior

Correct rendering of widths of Nerd Font glyphs, as far as I can tell.

![screenshot-nf-glyphs-correct-alacritty](https://user-images.githubusercontent.com/1638317/142074933-5d9deceb-0507-4355-b05c-c50b063998fe.png)

This screenshot has been generated using Alacritty, but I also tried this out on Kitty and Mac Terminal (MacOS) and got the same expected behaviour.

I've added a second screenshot of Windows Terminal Preview rendering the same text file, with **Cascadia Mono"", to demonstrate how the ostensibly-correct rendering of these glyphs appears to adhere to what Windows Terminal would do with the stock (unpatched) font's glyphs for the same code points:

![screenshot-nf-glyphs-STOCK-Cascadia-winterm](https://user-images.githubusercontent.com/1638317/142075205-35bd4452-8997-4ec1-af6e-cd32b629a205.png)

### Actual Behavior

Result of outputting test text file in Windows Terminal:

![screenshot-nf-glyphs-wrong-winterm](https://user-images.githubusercontent.com/1638317/142075639-5f075e27-9983-40a9-b123-ab9080daf23e.png)

Even if the characters are 'wide' in the unpatched font, these glyphs are not rendered wide in patched ('Nerd Font') fonts.

Good (Alacritty and other terminal emulators):

![bar-good-alacritty](https://user-images.githubusercontent.com/1638317/142076233-8cf1eeb3-8fcc-4ac2-a8a5-af7d385c24a9.png)

Bad (Windows Terminal Preview):

![bar-bad-windows-terminal-pre](https://user-images.githubusercontent.com/1638317/142076259-60810630-088c-4015-944d-6b702c6f5a3e.png)

**Comment by DHowett** [comment] 2021-11-16 22:45
Curious. I bet if you select one of the NF characters that is rendering incorrectly, it will select _as-if_ it was two columns wide (it will likely cover the 6, but when you copy it the 6 will not be present)

This is probably because of how we're batching text to push over to DirectWrite, coupled with the fact that the NF Patcher _does not insert correct glyph advances_. Other terminals are cell-based, rather than run-based, which makes up for deficient font data.

We're working on a new text rendering engine. I suspect it would help here, even if it made other things slightly worse.

I also believe there's a duplicate for this bug somewhere on the backlog. I'll try to find it. :smile:

**Comment by benfowler** [comment] 2021-11-17 00:24
Thanks! That's indeed exactly what happens.

Trying this out -- if I immediately copy the arrow character onto the clipboard, and then paste it straight back, the cursor advances as if it occupied two cells:

![paste1](https://user-images.githubusercontent.com/1638317/142086865-56c31362-3302-413d-b248-6498b851f066.png)

but then if I immediately type some additional characters, the output character cells seem to lose sync with the cursor:

![paste2](https://user-images.githubusercontent.com/1638317/142086881-0e8c2e3c-90c6-4043-8b18-1e6b5ed9d91c.png)

I wasn't going to mention that, but wanted to keep this report focused. Happily, it seems that this behaviour is already thoroughly understood.

I'm completely happy to close this bug report if this is already covered elsewhere.

**Comment by benfowler** [comment] 2021-11-17 00:28
For any passers-by, [this writeup about Nerd Fonts and glyph advance behaviour](https://github.com/mintty/mintty/issues/1104?page=2) is a really interesting read.

**Comment by benfowler** [comment] 2021-11-17 00:42
@DHowett I had noticed that the troublesome glyphs reside outside the BMP private use area (U+E000–U+F8FF), and was going to do some testing or delve into the code when time permits, in case that was a factor. 

From my own testing, this doesn't appear to happen to _all_ Nerd Font glyphs, only some. I use other code points, and the problematic ones happen to be in the Material Design icons range, per the [glyph range allocations documented on this page](https://github.com/ryanoasis/nerd-fonts/wiki/Glyph-Sets-and-Code-Points) on the NF Wiki.

**Comment by zadjii-msft** [comment] 2021-11-17 11:59
Maybe one of:
* #6864
* #6738
* #8993 (probably not)

**Comment by DHowett** [comment] 2021-11-17 21:43
Yep, this is definitely a /duplicate of #6864. @benfowler, thanks for all the additional info!

For the record, here's what it looks like in the new rendering engine:

![image](https://user-images.githubusercontent.com/189190/142287189-7313aa13-27ef-4321-8987-a80f4eaa18c4.png)

(Centered, rather than left-aligned, as the glyph is intended to occupy two cells. That's likely to be negotiable.)

**Closed by DHowett** 2021-11-17 21:43 UTC
Labels: Area-Fonts, Needs-Triage, Product-Terminal, Needs-Tag-Fix
