### ISSUE TITLE
Windows terminal launched with admin rights crashes while dragging a tab

### ISSUE THREAD

**Issue by oclaw** [microsoft/terminal#4059] opened 2019-12-25 20:15 UTC
# Environment

```
Windows 10 1909
Windows build number: 18363.535
Windows Terminal version: 0.7.3451.0
```

# Steps to reproduce
1. Launch Windows Terminal with admin rights.
2. Try to drag opened tab.

# Expected behavior
Tab is dragged 

# Actual behavior
Windows terminal crashes

**Comment by electronic-dk** [comment] 2019-12-26 08:45
Looks like a dupe of https://github.com/microsoft/terminal/issues/3581

**Comment by DHowett-MSFT** [comment] 2019-12-26 08:51
Yep! Thanks. /dup #3581

**Closed by DHowett-MSFT** 2019-12-26 08:51 UTC
Labels: Needs-Tag-Fix, Needs-Triage
