### ISSUE TITLE
Classic scrollbar

### ISSUE THREAD

**Issue by Funtime60** [microsoft/terminal#14968] opened 2023-03-08 07:16 UTC
# Description of the new feature/enhancement

Currently the scrollbar is really small, rounded, and moves on the X axis when hovered. This makes using it with a mouse more difficult. I'd appreciate if it could have an option more consistent with the rest of Windows which is more user friendly.

![image](https://user-images.githubusercontent.com/24595923/223645053-4f21a6e1-eaa8-44a2-a5c6-72e07f2bf168.png)
![image](https://user-images.githubusercontent.com/24595923/223645303-9e7ce340-82cf-42d7-8a26-458ea02e561f.png)
vs
![image](https://user-images.githubusercontent.com/24595923/223646117-4f2adeb9-f865-43bc-8356-3df242ce007a.png)
![image](https://user-images.githubusercontent.com/24595923/223646366-83ebae20-3277-4a8d-bfea-a4ce039901bb.png)

**Comment by zadjii-msft** [comment] 2023-03-08 11:32
Thanks for the suggestion! We're trying to conform to the rest of the modern UI guidelines, so we're probably not going to add support for a legacy ComCtl-style scrollbar anytime soon. However, you may be interested in the `"scrollbarState": "always"` setting that was added in 1.17 (#14047). This forces the scrollbar to always be in the "expanded" state, kinda like a comctl scrollbar:

![image](https://user-images.githubusercontent.com/18356694/223702093-c5ebcf35-4826-4c04-8991-b373ed79c18d.png)

Does that seem like an acceptable solution/?

**Comment by ForbiddenEra** [comment] 2023-03-18 11:52
> Thanks for the suggestion! We're trying to conform to the rest of the modern UI guidelines, so we're probably not going to add support for a legacy ComCtl-style scrollbar anytime soon. However, you may be interested in the `"scrollbarState": "always"` setting that was added in 1.17 (#14047). This forces the scrollbar to always be in the "expanded" state, kinda like a comctl scrollbar:
> 
> ![image](https://user-images.githubusercontent.com/18356694/223702093-c5ebcf35-4826-4c04-8991-b373ed79c18d.png)
> 
> Does that seem like an acceptable solution/?

This doesn't seem too bad; I'm fine with this as it's hardly different from a standard scrollbar; the issue I was previously had was the `visible` setting only having a tiny line as the scroll bar - and it seems now that when I grab that line it does expand but I'm not sure I recall this happening before, I could be wrong.

I was going to suggest that perhaps it should expand on hover instead of when grabbing but I just noticed it does indeed expand on hover too albeit with a delay; might be nice to have this delay configurable, even if only in the json.

I also feel like it seems weird that when it's in it's thinner/smaller state but scrolled all the way down that there's a space between the bottom of the line and the bottom of the window; one would presumably assume that this is in order to leave space for the down arrow when expanded, except I've also noticed (at least with my DPI/resolution settings) that there's a few px difference between the bottom of the line and the bottom of it when expanded with the expanded version actually being a few pixels lower.

I'm not sure if there's anything that can be done with this due to UI guidelines etc but I constantly subconsciously feel like I'm not always scrolled down completely, even though I'm aware of the issue.

I also wonder about the possibility of expanding to the full size when scrolling with a mouse wheel or otherwise.. Again, I'm not sure if this has been improved recently but it does seem easier to grab now but I seem to remember times where it wasn't so easy to grab and often I start scrolling with the wheel and then sometimes realize that using the wheel isn't going to work out to reach what I'm looking for and then end up grabbing the handle and I could be wrong but I feel like I remember there were times where I ended up selecting text or something because my click didn't land on the like 4px wide bar.

I also wonder if these settings could be worded better or something. Perhaps `always` should be `expanded` (or at least listed as "Always Expanded" in UI) and `minimized` or something for `visible`.

I'd perhaps also suggest an auto-hide option where nothing is visible unless you scroll; perhaps showing the minimized version on scroll wheeling and then the expanded version on hovering or something. Of course, this could potentially have issues unless there's a reserved gutter for the scroll bar which seemingly defeats the purpose of hiding other than aesthetics (although the only real functional reason I can see is perhaps getting 1 more character of width)

If I'm not hallucinating improvements than that's great and seems to help; as I said I previously remember being frustrated trying to scroll or grab the line and miss it; I'm not sure I even recall ever seeing it actually 'expand' with up/down arrows as well but that seems to be the behavior now.

So while I was originally +1 for this, I think the `always` setting you showed might be kind of what the OP was looking for; however in his screenshots, even when it's expanded, it seems he's still only getting the narrow line as the handle in the gutter, whereas in my testing just now, the handle is fully wide when expanded (whether by hover or `always` setting) - if the OP is only seeing the line when expanded and the expanded view is the same whether hovered or set to `always` then perhaps they won't be satisfied; I'm not sure if that's a Windows-version issue or a configuration issue.

This is what I see when set to `visible`:
![image](https://user-images.githubusercontent.com/7980490/226103387-ffe02326-6ba2-4158-9011-9346648c917c.png)

Then if I hover over the gutter, or set to `always`:
![image](https://user-images.githubusercontent.com/7980490/226103461-425d9531-f678-4f4d-b6a3-951ecc0aac5f.png)

I also swear I just saw a third, intermediate state that seemed to happen when hovering over the gutter but not over the handle where the width was somewhere between the first and second sizes but still showed the arrows and gutter area; I reproduced this a few times, then went to screenshot it to show here, and now I can't reproduce it - all I've done is take a screenshot and alt-tab into mspaint to crop it and alt-tab back to firefox. No settings changes, opening or closing of windows or anything. Weird, but when it happened the handle was definitely wider than the OP's last image, though it wasn't quite as wide as the gutter until I either grabbed it or hovered the actual handle, though the fact I can't reproduce something I swear I just saw a few seconds ago is driving me mental, LOL

I can say I've never seen a state where the arrows were visible and the handle wasn't and wider than the size that's shown when not expanded like the OPs last pic.

I imagine that if the OP could hover or set it to `always` and see what I see in my 2nd pic that they might be satisfied.

**Comment by zadjii-msft** [comment] 2023-03-27 14:51
Hey all, our bot's been acting up the last few weeks. This issue has been marked as requiring author feedback, but hasn't had any activity in the last week. We're gonna close it to tidy up. Feel free to continue the discssion in the comments - we can always reopen if new information comes to light. Thanks!

**Closed** 2023-03-27 14:51 UTC
Labels: Issue-Feature, Resolution-Fix-Available, Needs-Author-Feedback, Needs-Triage, Needs-Tag-Fix

**Comment by zadjii-msft** [comment] 2023-03-27 14:55
Hey all, our bot's been acting up the last few weeks. This issue has been marked as requiring author feedback, but hasn't had any activity in the last week. We're gonna close it to tidy up. Feel free to continue the discssion in the comments - we can always reopen if new information comes to light. Thanks!
