### ISSUE TITLE
Is it possible to allow users to set the line spacing and word spacing of text?

### ISSUE THREAD

**Issue by Allen-c-HE** [microsoft/terminal#15114] opened 2023-04-05 04:44 UTC
# Text is displayed too crowded and it is easy to get visually strained. It can be much better if there is an option to set the line spacing and word spacing.

#

**Comment by lhecker** [comment] 2023-04-05 11:30
This is a duplicate of #3498. It's already been implemented but hasn't been released yet. You can subscribe to that issue to get a notification by our bot once it has been released.

![image](https://user-images.githubusercontent.com/2256941/230067848-30dd1b1d-eee3-4530-b081-31024df5d111.png)

/dup #3498

**Closed** 2023-04-05 11:31 UTC
Labels: Issue-Feature, Needs-Triage, Needs-Tag-Fix
