### ISSUE TITLE
Settings / Startup / Launch Parameters / Launch Position doesn't allow Negative values

### ISSUE THREAD

**Issue by internayt** [microsoft/terminal#15832] opened 2023-08-14 20:48 UTC
# Description of the new feature/enhancement
Currently, the Launch Position doesn't allow negative values.
I have a 3 monitor setup with the middle monitor as monitor 1.
I have "cmd" setup with defaults to set Left (X) as -1924, which works great as the window comes up on my left monitor all they way to the edge.

Please allow negative values for X in Launch Position.

**Comment by zadjii-msft** [comment] 2023-08-14 22:01
Methinks this is #15656:

> I don't think this needs to be a feature request - this is probably just a bug report 😜 `--pos` with a negative number absolutely _should_ work! Our psychic debugging guess is that the arg parser we're using is treating `--pos -100,-200` as a different option entirely, rather than a value for the `--pos` arg.

**Comment by lhecker** [comment] 2023-08-15 10:24
@zadjii-msft But, this issue is about the settings UI not supporting negative numbers, I think. There, it doesn't work either (= separate issue).

**Comment by zadjii-msft** [comment] 2023-08-15 10:32
Ho boy it doesn't work in the SUI either? Jeez 🤦 

> **Note**
> ## Walkthrough

Yep, these guys:
https://github.com/microsoft/terminal/blob/b556594793006ba49934d9e5291cbf235e18b4b3/src/cascadia/TerminalSettingsEditor/Launch.xaml#L239-L254

use this style

https://github.com/microsoft/terminal/blob/b556594793006ba49934d9e5291cbf235e18b4b3/src/cascadia/TerminalSettingsEditor/Launch.xaml#L26-L32

and that's got a minimum of 1. 

Should be easy enough to make a duplicate of that style, but for `LaunchPositionNumberBoxStyle`, and with a different minimum.

**Comment by codecruisedor** [comment] 2023-09-06 04:25
Hello @zadjii-msft , @lhecker , I would like to work on this.

A few questions:
1) We have to implement two things, One is a new style `LaunchPositionNumberBoxStyle` in the settings UI. Another is allowing negative x and y in the argument parser so that it allows negative numbers in the `--pos` argument. **Is my understanding correct?**
2) What should be the minimum value in the new `LaunchPositionNumberBoxStyle`..? 

Thank you.

**Comment by zadjii-msft** [comment] 2023-09-06 13:47
@codecruisedor 

1. Yea, there's two parts, but for the sake of _this_ thread, I'd just focus on the Settings UI bit. #15656 is tracking the commandline parsing one, and that seems... well quite a bit weirder. 
2. I agree with lhecker. INT_MAX for all I know. I'm sure there's _technically_ a smarter value out there to use for "the largest/smallest possible window coordinate", but I'm not sure we _need_ to be that precise.

**Closed** 2023-09-07 21:30 UTC
Labels: Help Wanted, Issue-Bug, Product-Terminal, In-PR, Priority-2, good first issue, Area-Settings UI
