### ISSUE TITLE
Font is blurry

### ISSUE THREAD

**Issue by pnstickne** [microsoft/terminal#5820] opened 2020-05-08 23:14 UTC
The font is blurry and is either not configurable or not easily configurable.

Windows Terminal - Version: 0.11.1251.0

Terminal - looks over-aliased (read: _really bad_)

![image](https://user-images.githubusercontent.com/1430176/81456452-2bb1ce80-9147-11ea-9449-f6eb18493e05.png)

ConEmu - looks decent with subpixel (?) aliasing

![image](https://user-images.githubusercontent.com/1430176/81456442-20f73980-9147-11ea-8e0e-80455601c810.png)

"**Old**" Command Prompt is okay. Just a bad rendering in Terminal.

![image](https://user-images.githubusercontent.com/1430176/81456584-b5fa3280-9147-11ea-9f45-89e10ad9d4d4.png)

**Comment by DHowett-MSFT** [comment] 2020-05-08 23:21
This looks like a /dupe of #5759.

Let me guess: Intel HD graphics?

**Closed by DHowett-MSFT** 2020-05-08 23:21 UTC
Labels: Needs-Tag-Fix, Needs-Triage

**Comment by pnstickne** [comment] 2020-05-08 23:24
> This looks like a /dupe of #5759.
> 
> Let me guess: Intel HD graphics?

Intel something.. probably GPU issue/setting then from reading the other.
