### ISSUE TITLE
"You are about to close a read-only terminal" popup does not appear if I select "Close Tab" from the menu again

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [microsoft/terminal#9502] opened 2021-03-15 10:08 UTC
# Environment

```none
Windows build number: 10.0.19042.867
Windows Terminal version (if applicable): Preview 1.7.572.0
```

# Steps to reproduce

1. Start a new session, e.g. Command Prompt.
2. Press Ctrl+Shift+P to open the command palette, and choose "Toggle pane read-only mode". A lock icon appears in the tab header.
3. Right-click the tab header. A menu opens.
4. Select "Close Tab" from the menu. A warning pops up: "You are about to close a read-only terminal. Do you wish to continue?"
5. Click "Cancel".
6. Right-click the tab header again. A menu opens.
7. Select "Close Tab" from the menu.

# Expected behavior

The same warning should pop up again.

# Actual behavior

The warning does not pop up and the tab does not close.

# Notes

If you try to close the pane by pressing Ctrl+Shift+W or choosing "Close pane" from the command palette, then that pops up the warning each time.

Related to <https://github.com/microsoft/terminal/issues/6981>.

**Comment by KalleOlaviNiemitalo** [comment] 2021-03-15 10:21
TerminalPage::_ShowCloseReadOnlyDialog is called from two functions:

- `winrt::Windows::Foundation::IAsyncAction TerminalPage::_RemoveTab(winrt::TerminalApp::TabBase tab)`
  <https://github.com/microsoft/terminal/blob/89c9e6db847ed7f262d1f5a7f972ef004320ff6e/src/cascadia/TerminalApp/TerminalPage.cpp#L1292>
- `winrt::fire_and_forget TerminalPage::_CloseFocusedPane()`
  <https://github.com/microsoft/terminal/blob/89c9e6db847ed7f262d1f5a7f972ef004320ff6e/src/cascadia/TerminalApp/TerminalPage.cpp#L1689>

TerminalPage::_RemoveTab is called from three functions:

- `void TerminalPage::_RemoveTabViewItem(const MUX::Controls::TabViewItem& tabViewItem)`
  <https://github.com/microsoft/terminal/blob/89c9e6db847ed7f262d1f5a7f972ef004320ff6e/src/cascadia/TerminalApp/TerminalPage.cpp#L1280>
- `void TerminalPage::_CloseFocusedTab()`
  <https://github.com/microsoft/terminal/blob/89c9e6db847ed7f262d1f5a7f972ef004320ff6e/src/cascadia/TerminalApp/TerminalPage.cpp#L1667>
- `winrt::fire_and_forget TerminalPage::_CloseFocusedPane()`
  <https://github.com/microsoft/terminal/blob/89c9e6db847ed7f262d1f5a7f972ef004320ff6e/src/cascadia/TerminalApp/TerminalPage.cpp#L1713>

TerminalPage::_RemoveTabViewItem and TerminalPage::_CloseFocusedTab discard the IAsyncAction returned by TerminalPage::_RemoveTab, instead of awaiting it. Does that cause the coroutine to be aborted so that some cleanup is skipped?

**Comment by zadjii-msft** [comment] 2021-03-15 11:50
_Huh_. That's weird. Not totally sure _why_, but that's definitely happening. Thanks! 

/cc @Don-Vito this seems like the kind of thing that interests you 😋

**Comment by KalleOlaviNiemitalo** [comment] 2021-03-15 13:00
If discarding the IAsyncAction really causes this, then can the compiler be made to warn about such usage, perhaps by making C++/WinRT emit `[[nodiscard]]` somewhere?

**Comment by Don-Vito** [comment] 2021-03-21 08:42
@zadjii-msft - please assign to me :smile:
@KalleOlaviNiemitalo  - thanks for the research (congrats for the profile picture!)

**Comment by Don-Vito** [comment] 2021-03-21 09:06
So the problem is that click on the "close tab" goes directly for the tab->rootPane->Close(), rather than asking the TerminalPage to remove the tab (which is not very successful design decision IMHO). Unfortunately, Pane::Close sets isClosing to true, even if the closing is dismissed, and as a result the next invocations of Pane::Close do nothing:
```
void Pane::Close()
{
    // We should not set the Pane to closing state if Closing is dismissed.
    if (!_isClosing.exchange(true))
    {        
        _ClosedHandlers(nullptr, nullptr);
    }
}
```

**Closed** 2021-03-22 20:48 UTC
Labels: Area-User Interface, Help Wanted, Issue-Bug, Priority-2, Product-Terminal, Resolution-Fix-Committed
