### ISSUE TITLE
Azure Cloud Shell does not displays the code requested by the Azure portal

### ISSUE THREAD

**Issue by TonyHenrique** [microsoft/terminal#3333] opened 2019-10-25 21:18 UTC
# Environment

```none
Windows build number: 10.0.18362.418
Windows Terminal version: 0.6.2951.0
```

# Steps to reproduce

Open the new Windows Terminal (Preview), then click on Azure Cloud Shell Menu (Ctrl + Shift + 4)
![image](https://user-images.githubusercontent.com/6307623/67605033-95423080-f753-11e9-9b61-3014f91718ed.png)

# Expected behavior

A shell logged into my Azure Portal.

# Actual behavior

When I try to open the Azure Cloud Shell, it does not displays the code requested by the Azure portal:
![image](https://user-images.githubusercontent.com/6307623/67604901-3e3c5b80-f753-11e9-93cc-0c5fb33a9241.png)

**Comment by DHowett-MSFT** [comment] 2019-10-26 18:10
This is an unfortunate consequence of #780 -- since the line doesn't wrap appropriately at the righthand side of the screen, the device code is cut off (permanently). You should be able to work around this by making sure Terminal is as wide as it can get before launching an Azure session.

Sorry about that. It's somewhat of a silly bug to have in 2019.

**Comment by DHowett-MSFT** [comment] 2019-10-29 20:12
Thinking about it more, this is just a full-on /dupe of #780. Thanks!

**Closed by DHowett-MSFT** 2019-10-29 20:12 UTC
Labels: Area-AzureShell, Issue-Bug, Product-Terminal
