### ISSUE TITLE
The copied text is not fully pasted

### ISSUE THREAD

**Issue by majonga88** [microsoft/terminal#3790] opened 2019-11-30 23:47 UTC
Hi folks,

I experienced an issue with copy/paste feature.

# Environment

Windows build number: 10.0.18363 N/A Build 18363
Windows Terminal version : 0.7.3291.0

# Steps to reproduce

On WSL 1 tab (Ubuntu distro), i create a file `touch test.txt` in the home path, when edit the file like this : `vi test.txt ` and i would like to copy/paste the following text :

```
module.exports = {
  async rewrites() {
    return [
      // Basic `path-to-regexp` usage
      // Query object shape: { id: string }
      { source: "/user/:id", destination: "/user_profile" },

      // Optional Language
      // Query object shape: { lang?: string }
      { source: "/:lang(en|es)?/about", destination: "/about" },

      // Advanced rewrite
      // Query object shape: { id: string } (in addition to dynamic route param)
      { source: "/u/:id", destination: "/user/:id" }
    ];
  }
};
```

# Expected behavior

The beginning of the copied text should be not missing.

![image](https://user-images.githubusercontent.com/46779480/69907319-952cf480-13d3-11ea-87ff-440e993a90f6.png)

# Actual behavior

The beginning of the copied text is missing. 

![image](https://user-images.githubusercontent.com/46779480/69907314-66af1980-13d3-11ea-8134-742f77cffd4d.png)

Thank you guys for your help !

**Comment by DHowett-MSFT** [comment] 2019-11-30 23:57
Since you're using vi, and you are pasting code directly, it looks like `m` `o` `d` `u` `l` `e` `.` `e` `x` `p` `o` are being interpreted as vi normal-mode commands. You're issuing the following commands:

* `mo` - set mark `o`
* `du` - delete, something
* `l` - move right
* `e` - move to end of word
* `s.` - substitute a single character with `.`
* `e` - as above
* `x` - delete one character (probably the `.` you just added)
* `p` - paste whatever's in your yank buffer (probably `labels:`) from the first line
* `o` - insert a new line below the current line, enter insert mode

Once you're in insert mode, the rest of your paste goes in unharmed.

1. This is 100% expected behavior for pasting raw text into vim. Press `i` before pasting to paste code.
2. Vi/vim support automatic detection of pastes, but requesting that makes this a /dupe of #395.

**Closed by DHowett-MSFT** 2019-11-30 23:58 UTC
Labels: Needs-Tag-Fix, Needs-Triage

**Comment by majonga88** [comment] 2019-12-01 00:09
@DHowett-MSFT Thanks for the answer ! 🍻
