### ISSUE TITLE
Windows Terminal not consistent to load fonts.

### ISSUE THREAD

**Issue by drocha87** [microsoft/terminal#6365] opened 2020-06-05 11:27 UTC
# Environment
```none
Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.18363.0 Microsoft Windows NT 10.0.18363.0
```

# Steps to reproduce

# Expected behavior
When I open windows terminal, I expect my font "fontFace": "Cascadia Code PL"  to be loaded .

# Actual behavior
Sometimes when I open windows terminal I don't have my font loaded but other time it's loaded normally. 

This is my configuration
```
{
            "guid": "{574e775e-4f2a-5b96-ac1e-a2962a402336}",
            "hidden": false,
            "name": "PowerShell Core",
            "source": "Windows.Terminal.PowershellCore",
	    "colorScheme": "Dracula",
	    "fontFace": "Cascadia Code PL",
	    "fontSize": 11,
	    "scrollbarState": "hidden"
}
```

**Comment by DHowett** [comment] 2020-06-10 01:07
I believe this is a /dupe of #3257, which we've as yet been unable to figure out.

**Closed by DHowett** 2020-06-10 01:07 UTC
Labels: Needs-Tag-Fix, Needs-Triage
