### ISSUE TITLE
can not drag a file to windows terminal

### ISSUE THREAD

**Issue by xspeed1989** [microsoft/terminal#1077] opened 2019-05-31 09:27 UTC
can not drag a file to windows terminal

**Comment by Summon528** [comment] 2019-05-31 11:33
probably #904

**Comment by zadjii-msft** [comment] 2019-05-31 12:41
Yea, without a more complete description of the expected behavior, I'm gonna go ahead and close this as a dupe of #904.

**Closed by zadjii-msft** 2019-05-31 12:41 UTC
Labels: Needs-Tag-Fix, Needs-Triage
