### ISSUE TITLE
WSL terminal crashes when using tmux

### ISSUE THREAD

**Issue by Luiscri** [microsoft/terminal#2610] opened 2019-08-29 22:15 UTC
If I open a tmux session and then use the shortcut "Ctrl+b + %" to add a new vertical window it displays properly. However if I maximize the terminal and then minimize it again to its original size the terminal will freeze for a second and then close without appearing any error message.

This behaviour only happens with vertical windows, and not with horizontal ones.

I don't know if it's a problem of the WSL terminal or tmux itself. I'm new to developping in Windows, so where can I find the log or any information to let you know what is happening with the terminal?

EDIT: I just find out that it happens with tmux and only when you minimize back to its size a terminal which contains many lines or rows. For example if I go to /usr/bin/ and type "ls -l" all the content will show in screen; if I maximize the window then minimize it back to its default size it will crash and close without showing any error. If I do the same operation out of tmux, it displays without any error.

**Comment by jasonxoc** [comment] 2019-08-31 09:19
tmux works fine for me... the font spacing is driving me nuts though.  There's a space between my nerdfont glyphs that's driving me a little crazy... 
![tmux](https://user-images.githubusercontent.com/595326/64061916-839a3d80-cb95-11e9-83e8-50924f505a46.png)

But this is a MASSIVE improvement over what was there.
![nerdfonts-tmux](https://user-images.githubusercontent.com/595326/64061940-b93f2680-cb95-11e9-9793-a49d3c6169be.png)
Is what it should be.

**Comment by jasonxoc** [comment] 2019-08-31 09:27
Allthough, the terminal is REALLY slow, like typing on a 9600 baud modem connection while attached to the tmux session. I'm going to compile tmux 3.0 and see if it's still slow and debug it. I'll open a bug on another thread if I figure anything out. I'm curious is luis has that same experience too...

**Comment by jasonxoc** [comment] 2019-08-31 09:40
For reference I was unable to duplicate this crash this with both a horizontal tmux split and a vertical tmux split. TMUX 2.1 - Terminal Version: 0.4.2382.0 which I got from the MS store. Probably should have started with this but it's insane to me to be able to work in windows comfortably, got carried away. btw the screenshot is from one of my repos, I didn't have my laptop handy. I wasn't trying to point out the icons just illustrating the contrast in font rendering.

**Comment by DHowett-MSFT** [comment] 2019-09-03 01:46
I've seen reports of (and encountered myself) crashes when printing any "ambiguous width" characters, but _only_ when I've closed at least one tab. Is that the case here?

**Comment by Luiscri** [comment] 2019-09-03 12:39
> 
> 
> I've seen reports of (and encountered myself) crashes when printing any "ambiguous width" characters, but _only_ when I've closed at least one tab. Is that the case here?

No it isn't. This crash happens with only creating a vertical window in tmux and maximing and minimizing back the terminal. Maybe the extra tmux window could be considered as "ambiguous width" character.

**Comment by jasonxoc** [comment] 2019-09-03 15:06
Luis: What version of tmux?

**Comment by Luiscri** [comment] 2019-09-03 15:19
I'm using:

- tmux 2.6
- Microsoft Windows [Version 10.0.18362.329]

**Comment by jasonxoc** [comment] 2019-09-03 15:31
I'll try 2.6 when I get home and let you know if I can reproduce that crash. I still need to compile 3.0. I think it's challenging because it's not just the version of the terminal emulation application, it's the version of the all of the libraries tied to your linux distro, then the WSL translation, then the application. So something that could be a bug in any of those layers only comes to the surface because you have a usable terminal emulator in windows. In any case, I'll dump out everything on my setup when I get home so you can at least work in a sane environment.

**Comment by Luiscri** [comment] 2019-09-03 16:22
I understand what you say. Could you tell me a combination which apparently doesn't give any problem?

I'm also using Ubuntu 18.04 dowloaded from the Microsoft Store

**Comment by jasonxoc** [comment] 2019-09-04 03:21
Luis:  
Windows 10 Home version: 1903 OS build: 18362.295

tmux 2.1

`NAME="Ubuntu"                                                                                                                                   VERSION="16.04.4 LTS (Xenial Xerus)"                                                                                                            ID=ubuntu                                                                                                                                       ID_LIKE=debian                                                                                                                                  PRETTY_NAME="Ubuntu 16.04.4 LTS"                                                                                                                VERSION_ID="16.04"                                                                                                                              HOME_URL="http://www.ubuntu.com/"                                                                                                               SUPPORT_URL="http://help.ubuntu.com/"                                                                                                           BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"                                                                                              VERSION_CODENAME=xenial                                                                                                                         UBUNTU_CODENAME=xenial   `

I hope this works for you man, I tested all splits, switching layouts within splits, maximizing / minimizing the term and its not crashing on me. I spent some time navigating with multiple sessions and it's all working... just slowly. 

I'll let you know if I get anything else interesting. Good luck man, let me know if I missed anything. 

J

**Comment by drk-mtr** [comment] 2019-09-07 13:04
I can't reproduce this on the following:

tmux 2.8
Windows Terminal 0.4.2382.0
Ubuntu 19.04
Windows 10 1903

I get strange glyph issues described above on my work PC but not home PC and I can't work out why!

**Comment by Luiscri** [comment] 2019-09-10 14:17
Here it is the shortcut to the Feedback Hub issue: https://aka.ms/AA60xiv

**Comment by jimf5** [comment] 2019-10-21 20:24
I do not experience exactly such an issue. I faced with suddenly windows terminal closing when I'm using tmux in WSL. Usually, it happens on quite long sessions - more than one day.  tmux server continues work in this case. With Command Prompt the result is the same.

**Comment by DHowett-MSFT** [comment] 2019-11-18 21:01
This seems to have been fixed with 0.6. Let me know if not.

**Closed by DHowett-MSFT** 2019-11-18 21:01 UTC
Labels: Area-Quality, Issue-Bug, Needs-Attention, Product-Terminal, Severity-Crash

**Comment by jimf5** [comment] 2019-11-18 22:15
It seems so.

**Comment by IUJakob** [comment] 2024-01-29 09:45
If it was gone, it is now back
```
$ wsl --version
WSL-version: 2.0.14.0
Kerneversion: 5.15.133.1-1
WSLg-version: 1.0.59
MSRDC-version: 1.2.4677
Direct3D-version: 1.611.1-81528511
DXCore-version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows-version: 10.0.19045.3930
```

**Comment by zadjii-msft** [comment] 2024-01-29 12:06
@IUJakob This thread is more than 4 years old. If you're seeing something like this, it's surely a different root cause. You should file a new issue.
