### ISSUE TITLE
Unicode box-drawing characters are not rendered in Consolas when font.size < 8

### ISSUE THREAD

**Issue by sxlijin** [microsoft/terminal#12678] opened 2022-03-12 02:10 UTC
### Windows Terminal version

1.11.3471.0

### Windows build number

10.0.22000.0

### Steps to reproduce

Configure the terminal profile's appearance to use `"font": { "face": "Consolas", "size": 8, "weight": "medium" }` (this also reproduces with lower font weights), then print any light box-drawing characters, e.g. `echo ─│┄┆┈┊┌┐└┘├┤┬┴` will do the trick. 

Then `Ctrl -` to shrink the font size and `Ctrl =` to increase the font size

https://user-images.githubusercontent.com/512410/157999767-dd43c290-e803-4a66-ac5f-7a78c48e2752.mp4

### Expected Behavior

Light-width box drawing characters should be visible.

### Actual Behavior

Light-width box drawing characters disappear.

**Comment by zadjii-msft** [comment] 2022-03-15 09:51
In [the past](https://github.com/microsoft/terminal/issues/11376#issuecomment-931172407), we've previously marked this as a combined duplicate of  #7927, #5897 (see for example https://github.com/microsoft/terminal/issues/5897#issuecomment-803492674), and possibly also #6161.

/dup #7927
/dup #5897
/dup #6161

Thanks!

**Closed by zadjii-msft** 2022-03-15 09:51 UTC
Labels: Issue-Bug, Needs-Triage, Needs-Tag-Fix
