### ISSUE TITLE
WSL Ubuntu, cannot copy-paste correctly in nano or vim editor

### ISSUE THREAD

**Issue by nntantidakis** [microsoft/terminal#1299] opened 2019-06-17 15:10 UTC
# Environment

Windows build number: Microsoft Windows [Version 10.0.18362.175]
Windows Terminal version (if applicable):0.0.1.0

# Steps to reproduce

Login to WSL, use nano to edit a file, mark a text that has at least a linebreak, and paste it on another line. For example in my local Deb Mirror, i mark this
![image](https://user-images.githubusercontent.com/37312505/59615267-e3528200-912a-11e9-9422-cfe4ee58acb8.png)

# Expected behavior
The expectet behavior like wsl command line, would be to paste the text exactly as copied with right click on the selected one, with all line-breaks
![image](https://user-images.githubusercontent.com/37312505/59616899-016db180-912e-11e9-9e0d-124975392fef.png)

# Actual behavior
The actual behavior is that it copies it without preserving any linebreak and tries to do it in one line
![image](https://user-images.githubusercontent.com/37312505/59615381-109f3000-912b-11e9-82d2-4d2a74045d22.png)
![image](https://user-images.githubusercontent.com/37312505/59615416-1c8af200-912b-11e9-8282-e54d4fd87a71.png)
![image](https://user-images.githubusercontent.com/37312505/59615433-26acf080-912b-11e9-9872-57847fdea5d4.png)

**Comment by zadjii-msft** [comment] 2019-06-18 15:20
@carlos-zamora might have thoughts here.

IIRC you can copy without trailing whitespace by holding shift when you right click. 

There's also a _lot_ of discussion on handling copy/paste behavior in various threads. I believe #1091 is the megathread for that.

**Comment by nntantidakis** [comment] 2019-06-18 15:27
This megathread is referred to pasting a text, this bug is referred while copying it. I forgot to mention that if you select and rightclick the text(copy) and paste it on notepad, it has the exactly same result. So its not a paste problem
![image](https://user-images.githubusercontent.com/37312505/59697446-7f958b00-91f6-11e9-9f3a-5edf74f501ea.png)

However if i copy a clean text from original wsl bash.exe, and paste it another problem occurs, it duplicates the breaklines
![image](https://user-images.githubusercontent.com/37312505/59697532-a5229480-91f6-11e9-904c-f2f49b75b150.png)

**Comment by DHowett-MSFT** [comment] 2019-06-18 21:40
This looks like a dupe of both #1073 #1091.

**Closed by DHowett-MSFT** 2019-06-18 21:40 UTC
Labels: Needs-Tag-Fix, Needs-Triage
