### ISSUE TITLE
"Quake style" slide down feature (just like ConEmu Terminal)

### ISSUE THREAD

**Issue by mkanet** [microsoft/terminal#6780] opened 2020-07-03 23:09 UTC
(An optional feature while Terminal is docked)

When Terminal is started/opened, the window to slide down from the desktop border.  When Terminal is closed, the window will slide up.  

![Quake-Style](https://user-images.githubusercontent.com/811008/86500479-3010f700-bd46-11ea-8f41-4c399211a4f0.gif)

**Comment by j4james** [comment] 2020-07-03 23:21
This sounds like a duplicate of issue #653.

**Comment by zadjii-msft** [comment] 2020-07-06 13:07
Yep, thanks for the triage @j4james!

/dup #653

**Closed by zadjii-msft** 2020-07-06 13:07 UTC
Labels: Issue-Feature, Needs-Tag-Fix, Needs-Triage
