### ISSUE TITLE
Bug Report - Moving window by clicking in titlebar

### ISSUE THREAD

**Issue by Calkines** [microsoft/terminal#1696] opened 2019-06-28 15:01 UTC
# Environment

Windows build number: Microsoft Windows [versão 10.0.18362.175]
Windows Terminal version (if applicable): Preview 0.2.1715.0

# Steps to reproduce

1. Open Terminal.
2. Left click over title bar, left side of plus sing. (Between title of open tab and plus sign)
3. Try to move window.

# Expected behavior

1. After click, windows should moved.

# Actual behavior

1. Nothing is happing.

**Comment by miniksa** [comment] 2019-06-28 16:41
Your issue is a duplicate of #564 and is referenced in the pinned issue #1375.

Please search the database before filing a new issue.

Thanks for your feedback, I am closing this issue as it is a duplicate.

**Closed by miniksa** 2019-06-28 16:41 UTC
Labels: Needs-Tag-Fix
