### ISSUE TITLE
Feature Request > Allow right click options for each tab

### ISSUE THREAD

**Issue by ProHackTech** [microsoft/terminal#2224] opened 2019-08-03 17:49 UTC
# Description of the new feature/enhancement

Allow the user to access multiple options for each tab if right click is performed on any tab. Right click menu can have features such as closing the tab, opening the tab in a seperate terminal instance, changing tab configurations etc.

# Proposed technical implementation details (optional)

If the user performs right mouse click on any tab, there will be a popup menu (context menu?) with feature options for that tab.

**Comment by DHowett-MSFT** [comment] 2019-08-05 04:50
Duplicate of #1912.

**Closed by DHowett-MSFT** 2019-08-05 04:50 UTC
Labels: Issue-Feature, Needs-Tag-Fix, Needs-Triage
