### ISSUE TITLE
Drag problem

### ISSUE THREAD

**Issue by amm-uit-2017** [microsoft/terminal#1524] opened 2019-06-24 10:02 UTC
Dragging should be efficient in anywhere in the menu bar like all other text editors. The tab window should be dragged out to create a new window.

**Comment by yuri-wisestamp** [comment] 2019-06-24 10:25
Experiencing this as well. Not cool.

**Comment by HBelusca** [comment] 2019-06-24 11:01
Duplicate of #1516, #1500, #1412, #1395 ; issue encompassed in #1375.

**Comment by DHowett-MSFT** [comment] 2019-06-24 16:10
That's right. Thanks @HBelusca!

**Closed by DHowett-MSFT** 2019-06-24 16:10 UTC
Labels: Needs-Tag-Fix, Needs-Triage
