### ISSUE TITLE
Latest update and tmux / characters smeared down rightmost column

### ISSUE THREAD

**Issue by cerebrate** [microsoft/terminal#2889] opened 2019-09-25 07:21 UTC
# Environment

```none
Windows build number: 18990
Windows Terminal version (if applicable): 0.5.2661.0

Any other software?

tmux 2.8
```

# Steps to reproduce

1. Install Windows Terminal 0.5.2661.0 on a machine where tmux 2.8 has been installed and displaying correctly with previous Windows Terminal releases.
2. Open a WSL shell in a Terminal tab, inside _tmux_.
3. Run any command which displays text wide enough to use the rightmost column of the screen. For the example screenshots below, I used _env_.
4. After observing initial behavior, clear the screen with _clear_ .

# Expected behavior

Clean display of command output without character smear; all characters removed when screen cleared.

# Actual behavior

On initial run of the command in step 3, the rightmost character of the last line to contain one is "smeared" down the screen until another rightmost character replaces it, thus:

![terminal-smear](https://user-images.githubusercontent.com/371623/65578017-a02e5900-df3a-11e9-991e-a20496d0fb91.jpg)

![terminal-smear-2](https://user-images.githubusercontent.com/371623/65578188-ea173f00-df3a-11e9-90b8-9c97c7069c64.jpg)

When the screen is subsequently cleared, all characters displayed in this column remain visible:

![terminal-smear-clear](https://user-images.githubusercontent.com/371623/65578215-f8655b00-df3a-11e9-958f-ea4a37d986c2.jpg)

Thus far, I have only been able to reproduce this behavior inside a tmux session, although it was not observed until the latest Windows Terminal update. Additionally, I was using Cascadia Code as my terminal font also previous to that upgrade, without problems.

**Comment by BartXZX** [comment] 2019-09-25 08:36
I'm also seeing this in `less` and `vi`.

**Comment by daviox** [comment] 2019-09-25 10:47
It seems that CMD and OpenSSH sessions are affected too, at least in my case.
![Column clearing issue in CMD](https://user-images.githubusercontent.com/25099832/65593252-5e300200-df90-11e9-9b34-d245126716ad.gif)
```
Windows Version: 1903, build 18362
Windows Terminal Version: 0.5.2661.0
---
Terminal Font: Fira Code
```

**Comment by j4james** [comment] 2019-09-25 11:21
This is likely a duplicate of #2878, which has only just been fixed yesterday.

**Comment by zadjii-msft** [comment] 2019-09-25 12:56
Yep that looks like a dupe to me. Thanks!

/dup #2878

**Closed** 2019-09-25 12:56 UTC
Labels: Needs-Tag-Fix, Needs-Triage
