### ISSUE TITLE
Top of window border loses color after focus mode/full-screen

### ISSUE THREAD

**Issue by vefatica** [microsoft/terminal#10052] opened 2021-05-07 18:38 UTC
### Windows Terminal version (or Windows build number)

WindowsTerminal: 1.8.1092.0

### Steps to reproduce

1. Enable a keystroke for toggling focus mode; e.g., {"command": "toggleFocusMode", "keys": "shift+f11"},
2. Enter focus mode (tabs and title hidden)
3. Go to full-screen (Alt+Enter)
4. Return from full-screen (Alt+Enter)
5. Left-click the desktop
6. Left-click in WT

### Expected Behavior

WT's border (accent color) should be intact.

### Actual Behavior

After steps 5 and 6, WT has lost the accent color of its top border ...

Normal (magenta-ish accent):
![image](https://user-images.githubusercontent.com/61856645/117493415-f51cb880-af40-11eb-9870-a3f40926c255.png)
After step 5 (window inactive):
![image](https://user-images.githubusercontent.com/61856645/117493495-0bc30f80-af41-11eb-9a9a-56f2f638ac9c.png)
After step 6 (window active):
![image](https://user-images.githubusercontent.com/61856645/117493532-19789500-af41-11eb-8052-b8f9138fd906.png)

**Comment by zadjii-msft** [comment] 2021-05-11 12:34
Meh, I could have sworn there was a dupe for this.

Oh nevermind, the "dupe" was

> KNOWN ISSUE: Upon resizing the NCIW, the top frame margin disappears, making that border disappear entirely. 6356aaf has a bunch of WIP work for me trying to fix that, but I couldn't get it quite right.

in #6804.

**Comment by marbaa** [comment] 2021-05-12 14:11
Windows 10 has few years old bug that top border of any window has different color than the rest of borders. Maybe it is affecting here Terminal as well.

**Comment by zadjii-msft** [comment] 2021-08-18 21:45
You know what, this might just be one of those things that's "fixed in Windows 11". I can't get this to repro any longer - I'm guessing with all the DWM work they've done, they fixed the root cause. 

It'd be neigh impossible to track down which change was the individual one that did it, and I'd reckon it'd be similarly impossible for us to backport the fix to win10, considering the breadth of DWM changes.

**Closed** 2022-01-04 11:40 UTC
Labels: Resolution-Fix-Available, Issue-Bug, Area-User Interface, Product-Terminal, Priority-3

**Comment by vefatica** [comment] 2022-01-04 15:35
I can no longer reproduce it using

Microsoft Windows 10 Pro for Workstations
10.0.19044.1415 (2009, 21H2)
Windows Terminal Preview 1.12.3472.0

**Comment by vefatica** [comment] 2022-01-04 15:44
And I CAN reproduce it with

Microsoft Windows 10 Pro for Workstations
10.0.19044.1415 (2009, 21H2)
Windows Terminal 1.11.3471.0
