### ISSUE TITLE
Windows Terminal refusing to open with no visual feedback

### ISSUE THREAD

**Issue by RVFET** [microsoft/terminal#16263] opened 2023-11-05 16:00 UTC
### Windows Terminal version

1.18.2822.0

### Windows build number

10.0.22000.1848

### Steps to reproduce

I downloaded it through winget (using CMD). Command I ran : `winget install Microsoft.WindowsTerminal`

### Expected Behavior

Run with no issues, open normally

### Actual Behavior

Not opening, not saying anything at all, no error popups, no confirmation dialogs, not "opening and closing immediately". Just does not do anything at all.
When I checked "Windows Event Logs" I could see the cause, the log looks as follows:
```
Faulting application name: WindowsTerminal.exe, version: 1.18.2310.9002, time stamp: 0x65248b0f
Faulting module name: dcomp.dll, version: 10.0.22621.1778, time stamp: 0x830223ed
Exception code: 0xc0000005
Fault offset: 0x0000000000092244
Faulting process id: 0x0x250C
Faulting application start time: 0x0x1DA0FFE088FD00A
Faulting application path: C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_1.18.2822.0_x64__8wekyb3d8bbwe\WindowsTerminal.exe
Faulting module path: C:\Windows\System32\dcomp.dll
Report Id: 7b41473e-1bfe-40d5-bde1-c837d3335246
Faulting package full name: Microsoft.WindowsTerminal_1.18.2822.0_x64__8wekyb3d8bbwe
Faulting package-relative application ID: APP
```

**Comment by zadjii-msft** [comment] 2023-11-06 11:20
Can you try to get this repro'd with the Feedback Hub taking a recording? Alas, I can't find your dump on the backend from what you've shared, but the feedback hub link should help. 

/feedback


FWIW there is a `dcomp.dll` crash tracked in MSFT:40378391. That one was fixed in 2022, but all the details in there are _very_ Xbox specific. Maybe this is a fresh crash bucket in the Terminal that is wrongly getting bucketed to that bug.

**Comment by zadjii-msft** [comment] 2023-11-06 11:24
(looks like the bot's dead?)

Hi there!<br><br>Can you please send us feedback with the [Feedback Hub](https://support.microsoft.com/en-us/windows/send-feedback-to-microsoft-with-the-feedback-hub-app-f59187f8-8739-22d6-ba93-f66612949332) with this issue? Make sure to click the "Start recording" button, then reproduce the issue before submitting the feedback. Once it's submitted, paste the link here so we can more easily find your crash information on the back end?<br><br>Thanks!<br><br>![image](https://user-images.githubusercontent.com/18356694/140811502-a068f78b-89d2-4587-925a-73e19652b830.png)<br><br>![image](https://user-images.githubusercontent.com/18356694/140811557-cdc22a0f-fa6a-4f6a-953e-73b51f5548a3.png)<br><br>![image](https://user-images.githubusercontent.com/18221333/62478649-6de55400-b760-11e9-806e-5aab7e085a9f.png)

**Comment by Kristina-Pianykh** [comment] 2023-11-07 20:52
Confirming the issue.
When I try to open the Terminal from Power Shell by running `wt`, I get

```
PS C:\Users\pianykri> wt
Program 'wt.exe' failed to run: The file cannot be accessed by the systemAt line:1 char:1
+ wt
+ ~~.
At line:1 char:1
+ wt
+ ~~
    + CategoryInfo          : ResourceUnavailable: (:) [], ApplicationFailedException
    + FullyQualifiedErrorId : NativeCommandFailed
```

From the Run Window:
![Screenshot 2023-11-07 214615](https://github.com/microsoft/terminal/assets/51445294/234828e9-f5dd-4067-9473-7406caa5ec68)

The `wt.exe` file is on my PATH (located at `%USERPROFILE%\AppData\Local\Microsoft\WindowsApps`)

**Comment by Kristina-Pianykh** [comment] 2023-11-07 21:17
The issues was resolved by reinstalling the Windows Terminal. The current version is `1.18.2822.0` and it opens as intended.

**Closed** 2023-11-15 02:16 UTC
Labels: Issue-Bug, Needs-Author-Feedback, Needs-Triage, No-Recent-Activity
