### ISSUE TITLE
Screen readers don't speak available options in interactive prompts

### ISSUE THREAD

**Issue by daniel-montalvo** [microsoft/terminal#15653] opened 2023-07-04 11:48 UTC
Tested with latest versions of JAWS, NVDA, and Narrator. Not sure if this is a global issue. My specific use case here is with the `gh run view` command from GH CLI.

1. Check out a repo where you know you have several workflow runs available for testing
2. In the terminal, type `gh run view`
3. The terminal outputs a list of runs that you can view. Up and down arro keys would move you through the available options. Typing will filter out the results based on what you typed. Enter will select the currently keyboard focused option.

When using a screen reader and pressing up and down arrow keys, the whole terminal output is spoken instead of the option that is selected.
I would expect screen readers to be able to speak and braille whatever option is selected as the user moves up and down through the interactive prompt results.

**Comment by lhecker** [comment] 2023-07-05 09:47
This is a known issue (unfortunately). There's no robust solution for this at the moment and there has been a lack of interest among pretty much all terminals to fix this over the past decades. We've begun working on it in #14342, but it's progressing slowly. The issue is effectively a duplicate of #13666. /dup #13666

**Closed** 2023-07-05 09:47 UTC
Labels: Needs-Triage, Needs-Tag-Fix
