### ISSUE TITLE
[Render Bug] Green vertical lines between glyphs using PL fonts

### ISSUE THREAD

**Issue by SHJordan** [microsoft/terminal#11835] opened 2021-11-27 14:00 UTC
### Windows Terminal version

1.11.2921.0

### Windows build number

10.0.22000.0

### Other Software

PowerShell 7.2.0

### Steps to reproduce

open up wt.
set font to something with powerlines, like MesloLGM NF
set fontsize to anything (i tried from 9 to 14)
install and run oh-my-posh to see glyph corruption.

### Expected Behavior

![image](https://user-images.githubusercontent.com/884602/143684601-bb47cd09-ae38-4bdf-abea-ae9ef54776d2.png)

no malformed green line on ubuntu terminal between system logo and right white arrow glyph

### Actual Behavior

![2021-11-27 (4)](https://user-images.githubusercontent.com/884602/143684523-7040ade5-f719-4269-8d88-7874884e430b.png)
Green line between windows glyph and right white arrow glyph.

This is a continuation of the issue started here:
https://github.com/JanDeDobbeleer/oh-my-posh/issues/1332

**Comment by j4james** [comment] 2021-11-27 17:06
This looks like a duplicate of #8993.

**Comment by zadjii-msft** [comment] 2021-11-29 12:33
Yep, thanks!

/dup #8993

**Closed by zadjii-msft** 2021-11-29 12:33 UTC
Labels: Needs-Triage, Needs-Tag-Fix
