### ISSUE TITLE
Duplicate tabs on the same dir

### ISSUE THREAD

**Issue by victorananias** [microsoft/terminal#3403] opened 2019-11-01 12:31 UTC
Is it possible to duplicate tabs as on linux terminals?

On gnome term I can use ctrl+shift+t and it duplicates the current tab on the same directory while ctrl+t opens a new tab.

**Comment by zadjii-msft** [comment] 2019-11-01 13:00
Thanks for the suggestion! We really like the idea, but unfortunately, we're not sure that it's actually technically possible on Windows, and even if it is, it very likely might not work the way people is hoping most of the time. There's a ton of discussion in the linked threads:

https://github.com/microsoft/terminal/issues/1756#issuecomment-520048598
https://github.com/microsoft/terminal/issues/2315#issuecomment-519317472
https://github.com/microsoft/terminal/issues/1536#issuecomment-519107586
https://github.com/microsoft/terminal/issues/2427#issuecomment-523005110

I'm going to close this as a dupe of the master thread tracking this, #1437

/dup #1437 #1731 #2427 #3010

**Closed by zadjii-msft** 2019-11-01 13:00 UTC
Labels: Issue-Feature, Needs-Tag-Fix, Needs-Triage
