### ISSUE TITLE
Add backgroundImageSize attribute to console settings

### ISSUE THREAD

**Issue by miguelusque** [microsoft/terminal#6994] opened 2020-07-21 20:11 UTC
# Description of the new feature/enhancement

When setting a background image, it might happen that the resolution of the image does not match your expectations.

As a workaround, we can always resize the image with an external tool, but it would be great if we could specify the image width and height.

The value of width and height might be absolute or relative to the console size.

# Proposed technical implementation details (optional)

**Comment by DHowett** [comment] 2020-07-27 22:46
Thanks for the request! This is a /duplicate of #2370.

**Closed by DHowett** 2020-07-27 22:46 UTC
Labels: Issue-Feature, Needs-Tag-Fix, Needs-Triage
