### ISSUE TITLE
When typing so fast in remote server, the input will replacement the following characters.

### ISSUE THREAD

**Issue by leyafo** [microsoft/terminal#6329] opened 2020-06-03 12:55 UTC
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.19041.264]
Windows Terminal version (if applicable): 1.0.1401.0

Any other software?
ssh 
```

# Steps to reproduce
use ssh login another server. Typing fast  will replacement the following characters.
1. Login another linux server through SSH.
2. Type any characters in command line.
3. Type [ctrl+a] and type characters fast again.

# Expected behavior

# Actual behavior

**Comment by zadjii-msft** [comment] 2020-06-03 13:27
@leyafo Does this repro in the legacy console (`cmd.exe` or `powershell.exe`)? Are you using `ssh.exe` that ships with Windows, or the `ssh` that comes with a linux distro?

**Comment by DHowett** [comment] 2020-06-03 19:04
Are you using an IME?

**Comment by leyafo** [comment] 2020-06-04 02:32
> @leyafo Does this repro in the legacy console (`cmd.exe` or `powershell.exe`)? Are you using `ssh.exe` that ships with Windows, or the `ssh` that comes with a linux distro?

I have tested cmd.exe and wsl, the bug will occured. The server OS is freebsd.

**Comment by leyafo** [comment] 2020-06-04 02:33
> IME

I don't know, How can I confirmed this?

**Comment by DHowett** [comment] 2020-06-26 01:43
OH! I just realized you said it was _freebsd_! This is a /dupe of #1947. Really sorry about the late response.

**Closed by DHowett** 2020-06-26 01:43 UTC
Labels: Needs-Attention, Needs-Tag-Fix, Needs-Triage
