### ISSUE TITLE
Please add the "Default Maximize" option

### ISSUE THREAD

**Issue by richpurnellai** [microsoft/terminal#2088] opened 2019-07-25 09:25 UTC
# Summary of the new feature/enhancement

I like to see a more complete, better-style print on the screen. So every time I have to manually maximize the window. Is there a way to maximize the default window? If not, could you add this option?

# Proposed technical implementation details (optional)

Add an option like `"defaultSize": "maximize"` to the configuration file.

**Comment by zadjii-msft** [comment] 2019-07-25 13:09
This is a dupe of #288

**Closed by zadjii-msft** 2019-07-25 13:09 UTC
Labels: Issue-Feature, Needs-Tag-Fix, Needs-Triage
