### ISSUE TITLE
Toggle mode to allow for sending input to all panes (focus all panes)

### ISSUE THREAD

**Issue by GalDevel** [microsoft/terminal#8696] opened 2021-01-03 23:06 UTC
# Description of the new feature/enhancement

Hey, I would love to have the ability to focus all panes, or more precisely, to be able to toggle a mode which enables me to send the same keyboard input to all panes in the current tab.

I will greatly benefit from the feature as I regularly connect to multiple servers using SSH and perform the same task on each of them.

# Proposed technical implementation details (optional)

I have looked a bit inside the WT code, it seems to me that implementing this feature would require sending the keyboard messages to every non-focused pane, as the current controls implementation using WinRT only allows for 1 control to be in focus.

**Comment by DHowett** [comment] 2021-01-03 23:21
Thanks! This is a /duplicate of #2634.

**Closed by DHowett** 2021-01-03 23:21 UTC
Labels: Issue-Feature, Needs-Tag-Fix, Needs-Triage
