### ISSUE TITLE
After entering the font, a black color block will appear when rolling back

### ISSUE THREAD

**Issue by qinshuze** [microsoft/terminal#17928] opened 2024-09-16 05:04 UTC
### Windows Terminal version

1.22.2362.0

### Windows build number

10.0.19045.4894

### Steps to reproduce

1. Open Windows Terminal
![image](https://github.com/user-attachments/assets/4b21ef9b-97e7-417f-93fa-1132b86a4a65)

2. Enter any character
![image](https://github.com/user-attachments/assets/21085b5a-e2f7-49f2-90a1-c226b45dc246)

3. Press the backspace key on the keyboard
![image](https://github.com/user-attachments/assets/439d7689-3f78-4057-8031-28fd947af857)

### Expected Behavior

Do not show any color blocks

### Actual Behavior

Black color blocks appeared

**Comment by lhecker** [comment] 2024-09-16 10:05
This is an intentional regression we introduced to make many other major improvements possible, including sixels. It was removed in #17666. The issue happens because Windows 10 ships with PowerShell 6 and PSReadLine 2.0.0-beta3, which contains a bug where the attributes are incorrect. The issue was fixed in this PR that ships with Windows 11: https://github.com/PowerShell/PSReadLine/pull/1626

There's two ways to fix this issue:
* (Recommended) You can install the newer PowerShell 7 here: https://learn.microsoft.com/en-us/powershell/scripting/install/installing-powershell-on-windows
  If you don't have `winget` installed or don't want to use it, I recommend [downloading the MSI package](https://learn.microsoft.com/en-us/powershell/scripting/install/installing-powershell-on-windows?view=powershell-7.4#msi).
* Alternatively, you can run `Install-Module PSReadLine` and restart all of your PowerShell tabs. If the command fails, it may be necessary to add a `-Force` parameter.

**Comment by lhecker** [comment] 2024-09-16 10:05
I'll be closing this issue for now. If you think I made a mistake or if you have any questions, please feel free to ask here!

**Closed by lhecker** 2024-09-16 10:05 UTC
Labels: Issue-Bug, Needs-Triage
