### ISSUE TITLE
Enabling "Disable Scroll-Forward" causes incorrect display of vertical scrollbar

### ISSUE THREAD

**Issue by rivy** [microsoft/terminal#2449] opened 2019-08-16 01:23 UTC
# Environment

```none
Microsoft Windows [Version 10.0.18362.239]
```

# Steps to reproduce

In a standard CMD console window, from the properties dialog:

1. Terminal ~ ENABLE "Disable Scroll-Forward"
1. Layout ~ decrease "Screen Buffer Size / Height" to be equal to "Window Size / Height"

# Expected behavior

The vertical scrollbar should disappear.

# Actual behavior

The vertical scrollbar remains, fully or partially obscuring the last column of text characters (depending on font/size?).

![Screenshot](https://user-images.githubusercontent.com/80132/63137052-45e4c480-bf9a-11e9-8403-e0b9628a50cd.png)

The obscuring behavior can be seen on the longer lines in the screenshot.

**Comment by rivy** [comment] 2019-08-16 01:28
Parenthetically, I'm trying to enable a work-around for this bug for [`less`](https://github.com/rivy/less), but I see no way to detect the "Disable Scroll-Forward" feature.

Is there any way to detect whether this or other features are enabled?

**Comment by DHowett-MSFT** [comment] 2019-08-16 04:39
This bug aside, the better way for `less` to ensure that there is no scrollbar (or one doesn't take up active screen space) is for it to use the (xterm) _alternate buffer_. That thing is really cool: it snapshots the display state, contents, etc. and switches the terminal emulator to a new pristine empty buffer that has no history and cannot scroll. When you exit the alt buffer, everything that was being displayed before snaps right back into place and overwrites the application's output.

**Comment by DHowett-MSFT** [comment] 2019-08-16 04:39
It's also a little more "standards-compliant" than `SetConsoleActiveScreenBuffer`.

**Comment by rivy** [comment] 2019-08-18 15:21
@DHowett-MSFT , thanks. I'll look into it.

I've hacked a work-around, for the time being, by just increasing the screen buffer vertical size by window size + one to force a scrollbar. All characters are displayed and the application function is unaffected, even if the scrollbar is redundant.

**Comment by rivy** [comment] 2022-10-13 03:52
This, after 3+ years, seems to be a `won't-fix`.
Please re-open elsewhere if/when you want to fix it.

**Comment by DHowett** [comment] 2022-10-13 16:48
I'm sorry about that. In the time since this was filed, I believe we improved the "disable scroll-forward" feature (which we had been calling "virtual bottom") in a number of ways... but none of those changes are, or will be, released to Windows 10. We never found a specific cause for this, nor did we get a strong local repro (which is puzzling)...

I'd love to know if it's still happening. I also respect that you may not want to engage with us about that any longer :smile:

**Comment by j4james** [comment] 2022-10-16 01:46
@DHowett I can reproduce this (on Windows 10), but it looks to me like it might be a bug in the scrollbar implementation itself. Quoting the documentation [here](https://learn.microsoft.com/en-us/windows/win32/controls/about-scroll-bars#scroll-bar-visibility):

> The system also hides and disables a standard scroll bar if you specify a page size that includes the entire scroll range of the scroll bar.

But that doesn't seem to be the case. I can get it to work if I manually hide the scrollbar when we're setting the scroll range, and the page size is greater than the max value (i.e. it includes the entire range). So something like this:

```cpp
const auto scrollBarVisible = static_cast<int>(pageSize) <= maxSize;
ShowScrollBar(_hWnd, isVertical ? SB_VERT : SB_HORZ, scrollBarVisible);
```

inserted in the `Window::UpdateScrollBar` method here:

https://github.com/microsoft/terminal/blob/6567201e0e1e72f82bfd3b565a8c3cb95ef2a75d/src/interactivity/win32/window.cpp#L890-L898

I'm not sure if that's exactly what we want, or there's a better way of fixing it, but that at least feels like an improvement.

If this is a Windows bug though, and it has already been fixed in Windows 11, then I assume there is no point in trying to fix it in our code (assuming Windows 10 isn't getting updates anymore).

**Comment by DHowett** [comment] 2022-10-17 21:24
@j4james, I'm more than happy to take your suggestion on a fix for this! It does still reproduce in Windows 11 conhost. Thanks for investigating. :smile:

(We may want to make certain that `scrollBarVisible` is actually `TRUE` or `FALSE`; I've seen Win32 APIs get up to no good when confronted with non-Win32-BOOL booleans.)

**Comment by j4james** [comment] 2022-10-17 22:00
> EDIT: (Ah, that parameter controls _redraw_, not visibility. Hmm.)

@DHowett Just to be clear, I wasn't suggesting changing the final parameter of the `SetScrollInfo` call (that's the _redraw_ flag). I'm suggesting adding an additional call to [`ShowScrollBar`](https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-showscrollbar).

**Comment by DHowett** [comment] 2022-10-17 22:05
Oh. Derp. Sorry :smile:

**Comment by DHowett** [comment] 2022-11-03 22:45
I'm totally on board with this fix. Thank you for investigating it!

**Closed** 2022-11-10 15:17 UTC
Labels: Product-Conhost, Area-Output, Issue-Bug, Area-User Interface, In-PR
