### ISSUE TITLE
actually there are 4 tabs, but only 3 tabs are displayed in the title bar!!!

### ISSUE THREAD

**Issue by oceanMIH** [microsoft/terminal#2632] opened 2019-09-01 03:56 UTC
actually there are 4 tabs, but only 3 tabs are displayed in the title bar!!!
![image](https://user-images.githubusercontent.com/28834785/64071571-8721e780-ccaf-11e9-93cd-9371b52e3dd3.png)

**Comment by encladeus** [comment] 2019-09-01 07:03
This is a duplicate of #857.

**Comment by DHowett-MSFT** [comment] 2019-09-03 01:51
/dup #857

Thanks @encladeus!

**Closed** 2019-09-03 01:51 UTC
Labels: Needs-Tag-Fix, Needs-Triage
