### ISSUE TITLE
Java terminal app doesn't scan Cyrillic script.

### ISSUE THREAD

**Issue by kamiQQ** [microsoft/terminal#11168] opened 2021-09-07 15:13 UTC
### Windows Terminal version (or Windows build number)

<b>Windows Terminal Version: 1.9.1942.0</b>

### Other Software

- <b>Visual Studio Code</b> Version: <b>1.60.0</b>
- OS Version: <b>Windows 10 Pro</b> 10.0.19043 Build 19043
- <b>Debugger for Java</b> Version: <b>0.35.0</b>
- <b>Visual Studio Code</b>  Encoding: <b>UTF-8</b>
- Windows <b>Encoding: UTF-8</b>

### Steps to reproduce

1. Copy and paste the following code.
`import java.util.Scanner;`
`class App {`
    `public static void main(String[] args) {`
         `Scanner input = new Scanner(System.in);`
          `String wordCyrillic = input.nextLine();//!Привет`
          `String wordLatin = input.nextLine(); //!hello`
          `System.out.println("we print: " + wordCyrillic);`
          `System.out.println("we print: " + wordLatin);`
          `System.out.println("we print: " + "\u26a1\u2661");`
          `System.out.println("we print: " + "Привет");`
     `}`
`}`
2. Run this code, inputting commented data(or use random Cyrillic letters).
3. You will get such output:
![Screenshot (22)](https://user-images.githubusercontent.com/85038072/132366102-70f21f47-ede7-4b2c-8377-7a1122f33abc.png)

### Expected Behavior

I expect it to scan the Cyrillic script properly as the Ubuntu terminal does.
![Screenshot (23)](https://user-images.githubusercontent.com/85038072/132367456-4d8dfa8d-5f6d-4b27-af67-9d9645456af2.png)

### Actual Behavior

Terminal doesn't scan the Cyrillic script at all.

**Comment by DHowett** [comment] 2021-09-07 16:37
This looks like a problem in the Windows version of Java? Your screenshots illustrate that the Console and Terminal _are_ properly passing input to Java when it is running under WSL (so: Linux java works fine! :smile:)... so it seems like this is a "Java on Windows" bug.

You may need to file this upstream with them.

**Comment by kagu-tsuchi** [comment] 2021-09-07 19:01
>so: Linux java works fine! 😄)... so it seems like this is a "Java on Windows" bug.
> 
> You may need to file this upstream with them.

Thanks for the quick reply, I can assume it's just a Java bug, but it does work fine in Eclipse/IntelliJ terminal. 

By the way, as you can see on screenshot n.2 it doesn't really work correctly under WSL Ubuntu.
(Has some problems on "we print: " line n.2)

![Screenshot (25)](https://user-images.githubusercontent.com/85038072/132396793-8f81b665-0e60-4a51-972e-191211594076.png)

**Comment by ianjoneill** [comment] 2021-09-07 21:01
I think this is probably related to / the same as #4551.

See a screenshot of it working below if you echo the Cyrillic text and then pipe it into the Java process (I removed the reading of the Latin string for ease of demo).

![image](https://user-images.githubusercontent.com/5821575/132410211-7f978c95-d741-4ebc-93c4-0a6fc2cb49b8.png)

Source:

```java
import java.nio.charset.StandardCharsets;
import java.util.Arrays;
import java.util.Scanner;

public class App {

  public static void main(String[] args) {
    Scanner input = new Scanner(System.in);
    String wordCyrillic = input.nextLine();//!Привет
    System.out.println("we print: " + wordCyrillic);
    System.out.println("Expected bytes " + Arrays.toString("!Привет ".getBytes(StandardCharsets.UTF_8)));
    System.out.println("Got bytes " + Arrays.toString(wordCyrillic.getBytes(StandardCharsets.UTF_8)));
    System.out.println("we print: " + "\u26a1\u2661");
    System.out.println("we print: " + "Привет");
  }
}


```

**Comment by ianjoneill** [comment] 2021-09-08 08:13
Java does use `ReadFile()` under the hood to read from standard-in.

Standard-in is defined as a `FileInputStream` with a file descriptor of 0.
https://github.com/openjdk/jdk11u/blob/63fc945c1d4cdc893d89796804acfe0ce9341860/src/java.base/share/classes/java/lang/System.java#L1970-L1973

`FileInputStream.readBytes()` is implemented natively here:
https://github.com/openjdk/jdk11u/blob/63fc945c1d4cdc893d89796804acfe0ce9341860/src/java.base/share/native/libjava/FileInputStream.c#L69-L73

Which in turn calls another native method:
https://github.com/openjdk/jdk11u/blob/63fc945c1d4cdc893d89796804acfe0ce9341860/src/java.base/share/native/libjava/io_util.c#L73-L123

On line 109, it calls `IO_Read()`, which is `#define`d in a header to map to the function `handleRead()`:
https://github.com/openjdk/jdk11u/blob/63fc945c1d4cdc893d89796804acfe0ce9341860/src/java.base/windows/native/libjava/io_util_md.h#L86

Which is implemented using `ReadFile()`:
https://github.com/openjdk/jdk11u/blob/63fc945c1d4cdc893d89796804acfe0ce9341860/src/java.base/windows/native/libjava/io_util_md.c#L477-L500

**Comment by DHowett** [comment] 2021-09-16 19:58
Thanks for all the comprehensive investigating! :smile: I'm going to call this a /dupe of #4551.

**Closed by DHowett** 2021-09-16 19:58 UTC
Labels: Needs-Triage, Needs-Tag-Fix
