### ISSUE TITLE
[Quake mode] Suggested tray improvements

### ISSUE THREAD

**Issue by htcfreek** [microsoft/terminal#13795] opened 2022-08-20 17:54 UTC
# Description of the new feature/enhancement

For a newby it is very hard to control/use quake mode windows. Improving the quake mode try icon menu by adding the following features would help here:
1. Add button to close quake mode back to normal.
2. Add menu to switch between tabs in quake window. (Otherwise you can't change them without knowing the shortcut.)
3. Add button to exit wt.

# Proposed technical implementation details (optional)

_nothing_

**Comment by zadjii-msft** [comment] 2022-08-22 11:41
This is broadly a /dupe of #10448

**Closed by zadjii-msft** 2022-08-22 11:41 UTC
Labels: Issue-Feature, Needs-Triage, Needs-Tag-Fix
