### ISSUE TITLE
Icon property should load asset from binary

### ISSUE THREAD

**Issue by LoadLibrary** [microsoft/terminal#3237] opened 2019-10-17 17:32 UTC
# Description of the new feature/enhancement

Windows Terminal allows creating new terminal entries with its JSON file configuration. One of the properties of the terminal entry is Icon that allows an arbitrary image being shown alongside the new terminal name.

Currently the Icon property seems to accept only images encoded as PNGs or JPGs. The Icon property should be capable of showing an asset from a binary as well. Think about how icons are storage as resources in .exe and .dll files. Since a binary might have multiple assets (user32.dll for example), asset number could be defined after a comma (just like shell does).

This would be useful, for example, for having different icons for Visual Studio Native Tools 2019 and 2017 consoles. Currently I have to find and download the PNGs for the VS logos instead of grabbing from the .exes.

# Proposed technical implementation details (optional)

The final JSON could look like as follows:
{
      // Visual Studio 2019 x64 Native Tools
      "guid": "{6277D459-07EF-4AE4-91DF-A7ED9EB95EF6}",
      "name": "VS2019 x64",
      "commandline": "cmd.exe /k \"C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Enterprise\\VC\\Auxiliary\\Build\\vcvars64.bat\"",
      "hidden": false,
      "icon":  "\"C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Enterprise\\Common7\\IDE\\devenv.exe,0\""
    },
    {
      // Visual Studio 2017 x64 Native Tools
      "guid": "{9A014D1D-85D7-4470-8178-4369B5D31A76}",
      "name": "VS2017 x64",
      "commandline": "cmd.exe /k \"C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Enterprise\\VC\\Auxiliary\\Build\\vcvars64.bat\"",
      "hidden": false,
"icon":  "\"C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Enterprise\\Common7\\IDE\\devenv.exe,0\""
    },

**Comment by DHowett-MSFT** [comment] 2019-10-17 17:47
Hey, thanks for the request! This is actually a /dupe of #1504 :smile:

**Closed by DHowett-MSFT** 2019-10-17 17:47 UTC
Labels: Issue-Feature, Needs-Tag-Fix, Needs-Triage
