### ISSUE TITLE
Default tab title is super-long, only 3 tabs fit the screen

### ISSUE THREAD

**Issue by vadimkantorov** [microsoft/terminal#3947] opened 2019-12-13 02:38 UTC
On the most recent version from Releases:

![image](https://user-images.githubusercontent.com/1041752/70765017-1dab7d80-1d62-11ea-9818-598002e6d6cb.png)

I'm sure there are reasons why it's like this, but it renders tabs unusable for me in the current state: only three tabs fit the screen at a time.

Yes, I realize this has been discussed before and all previous issues were closed, with issue authors often disagreeing with their closing (sometimes a minor related cause was dealt with, but the original issue still stands). Please feel free to close this as well if the whole long default tab title affair is decided WONTFIX.

Yes, I realize one can probably configure the tab title, but I don't consider this as a valid argument. IMO having to configure such a basic thing is a show-stopper when trying out a new terminal.

The screen is a Surface Pro 7 screen if it matters.

**Comment by DHowett-MSFT** [comment] 2019-12-13 03:29
Two things, actually:
1. that tab title was generated by your shell, and is configurable in yuor shell's startup scripts (for bash, that's probably `/etc/profile`). you can actually configure it to contain anything you want, which is really cool. I know you already enumerated this as an option, but it really is the "best" fix ;P
2. not all previous issues were closed, actually: this is largely a /dupe of #597 (which is very much still open) :smile:

**Closed by DHowett-MSFT** 2019-12-13 03:29 UTC
Labels: Needs-Tag-Fix, Needs-Triage

**Comment by vadimkantorov** [comment] 2019-12-13 04:46
1. Well, then please put it in Top of readme, in a popping message box, tooltip or whatever popping into eyes. If I happen to have a long username and a long computer name, Windows Terminal is taxing me by a lot of time figuring out how to reset this. Of course I realize that current tab title is provided by the bash profile, but I don’t think the tab title is informative

2. I hope that 2 is resolved before 1.0 release

**Comment by vadimkantorov** [comment] 2019-12-13 04:50
Sorry, https://github.com/microsoft/terminal/issues/597 is vague. It starts by asking for min-width. Then someone suggests it would be good to have max-width, but it is not clearly stated in the OP.

Could you please keep this issue open until something in the underlying tab control gets fixed and then the user-facing problem described in this issue (https://github.com/microsoft/terminal/issues/597 is more about impl details) has an official default solution?

**Comment by vadimkantorov** [comment] 2019-12-13 05:01
https://github.com/microsoft/terminal/pull/3876 Work seems actively progressing, I hope it gets merged before 1.0 and equal mode is enabled by default. Pretty much everyone would be surprised that WT doesn’t handle tabs like web browser or supports only three tabs visible (without having to reset bash profile env variables)

**Comment by navossoc** [comment] 2019-12-13 05:23
@vadimkantorov Yes, I agree, three tabs is really bad...
Also if you maximize the window you can't get pass of three tabs (which really sucks).

Until #3876 was not merged, I did override the title of the tab on the terminal settings, using `name` and `suppressApplicationTitle` properties on `profiles` array.

![image](https://user-images.githubusercontent.com/2457338/70771160-e1baed00-1d4e-11ea-9a15-926fd6c3684d.png)

For now, I can have at least 7 tabs.
This was the easiest and cleanly way I found to do that.

I hope this be addressed.
