### ISSUE TITLE
Taskbar Peek (or Terminals title), show if Terminals is elevated.

### ISSUE THREAD

**Issue by jefflord** [microsoft/terminal#13241] opened 2022-06-07 15:45 UTC
# Description of the new feature/enhancement

It would be great if the Windows Peek feature could be able to let us know if Terminals is elevated. I usually have an elevated and non-elevated terminal and you cannot tell which is which from the Peek:

![image](https://user-images.githubusercontent.com/4396667/172421763-e2b191b0-9544-4869-922a-7502fdf9bc02.png)

# Proposed technical implementation details (optional)

I understand this is likely a "Windows" or "Taskbar" thing to do graphically, so options might be limited. Perhaps as a start, add a new option/setting under Appearance which could be something like "Prefix application title with '🛡' if Terminals is elevated."

I know that cmd and powershell might also "be involved..." since you _could_ do this:

$host.ui.RawUI.WindowTitle = "🛡 : My title"

Also, cmd already prefixes the title with "Administrator"... Since all the things that Terminals might host have different rules, and so do Taskbar... the suggested option might be a good "global" option?

Thanks,
Jeff

**Comment by jefflord** [comment] 2022-06-08 13:44
> Another graphical idea is to color the terminal tab switch area differently for elevated process. This could allow to quicker visually perceive the difference

Actually, this is not a thing because all of the tabs are elevated or not. If Terminals could have elevated and non-elevated tabs (which would be great), then what you suggest would be perfect. 

Until then, we need to run two instances of Terminals. And when Terminals window is visible you can tell it's elevated by the shield icon in the title:
![image](https://user-images.githubusercontent.com/4396667/172631646-66ce0cb7-0294-4942-9a5e-a79edba7f26a.png)

You cannot tell which is elevated by just looking at the Taskbar Peek area:
![image](https://user-images.githubusercontent.com/4396667/172632020-b731c9ab-c6b8-4c92-9dfa-a0a278fac63e.png)

**Comment by zadjii-msft** [comment] 2022-06-08 17:03
To try and de-dupe some conversation here:
* We're tracking "use some variables to format the tab title" in #1320. I could imagine something like `titleFormat: "{elevatedShield} {title}"` to say "I want the shield emoji in the title when running elevated". That seems like the most flexible way to do something like this.
* We're tracking "different schemes / themes" in #8311. That should cover both styling the titlebar different, and the individual tabs as well. 
* There's also #3637 for switching which profiles are visible when elevated or not. That feels more hacky. That would be more like "I have a cmd profile that's got a black BG, and an elevated CMD profile that's got a red BG. Only one is visible at a time". That honestly just feels clunky. 

I think overall it looks like what you're looking for is best served by #1320, so I'm gonna close this one as a dupe of that. Thanks! 

/dup #1320

**Closed by zadjii-msft** 2022-06-08 17:03 UTC
Labels: Issue-Feature, Needs-Triage, Needs-Tag-Fix
