### ISSUE TITLE
Feature Request: Command to grant administrator permission by the terminal.

### ISSUE THREAD

**Issue by LeonanCS** [microsoft/terminal#3289] opened 2019-10-22 14:05 UTC
<h1>Description of the new feature/enhancement</h1>
Possibility of being able to elevate to administrator privileges through a command in the terminal, as it works in the linux systems for example. It is counterproductive to have to open new instances to gain access to administrator privilege.

**Comment by DHowett-MSFT** [comment] 2019-10-22 18:22
This is very much a /dupe of #1032. Thanks!

**Closed by DHowett-MSFT** 2019-10-22 18:22 UTC
Labels: Issue-Feature, Needs-Tag-Fix, Needs-Triage
