### ISSUE TITLE
Choose language in settings.json

### ISSUE THREAD

**Issue by Geobert** [microsoft/terminal#5497] opened 2020-04-23 13:54 UTC
# Description of the new feature/enhancement

Localization feature is great, well done! :D 

But I'd like to keep english for all my dev tools even if my language is not English in Windows input.

# Proposed technical implementation details (optional)

I don't know if it's possible, couldn't find a configuration key for it, but a settings.json key called `"language"` with a value like "en-EN" to set the wanted language would be nice.

**Comment by DHowett-MSFT** [comment] 2020-04-24 01:02
Thanks for the request! Marked this one into the backlog. It turns out there's an API to override the preferred languages on an app-by-app basis, but it suggests that we should absolutely not call it every time we launch. How strange.

**Comment by huoyaoyuan** [comment] 2020-05-02 10:12
I'd rather like there to be an entry in **Windows Settings** to select preferred language per-app.

**Comment by Geobert** [comment] 2020-05-02 11:20
Or just follow Windows display language instead of input language? My windows is displaying en-GB and input is fr-FR. Terminal is displaying French.

**Comment by DHowett-MSFT** [comment] 2020-05-02 17:12
@Geobert as far as I can tell, Termimal uses the order of your “preferred language” list in the language settings. It’s the same list that other applications use to determine their _disply_ languages. Can you share a screenshot of that settings page?

**Comment by Geobert** [comment] 2020-05-02 17:19
@DHowett-MSFT : thanks for your answer! French is indeed the first in the list, but my OS still display English

**Comment by DHowett-MSFT** [comment] 2020-05-02 18:53
Ah! Thanks for the info.

Unfortunately, this is by design -- the settings application has a separate section for the _operating system_ display language and the preferred language list.

![image](https://user-images.githubusercontent.com/14316954/80873173-8b9e0600-8c6b-11ea-97bf-b37c20f42a51.png)

**Comment by Geobert** [comment] 2020-05-02 21:34
OH just discovered that I can put English first and still have french as default input x)

Thank you!

**Comment by greggman** [comment] 2020-05-08 06:18
I'm confused. AFAIK Windows Terminal does not respect the language setting in the OS. Is that intentional? I have Japanese input enabled but my OS is set to English. 100% of my apps show an English UI and so does windows. Well, it was 100%. Only Windows Terminal is showing a Japanese UI in the drop down menu.

Is that not a bug, doing something different than all other windows software?

Of course an option to override it is fine but it seems like the default should match other software

**Comment by DHowett-MSFT** [comment] 2020-05-08 06:20
@greggman Terminal is following your system’s “preferred language order.” If your preferred language order says you prefer Japanese, Terminal will be in Japanese. 

More info here: https://github.com/microsoft/terminal/issues/5497#issuecomment-622998246

**Comment by DHowett-MSFT** [comment] 2020-05-08 06:21
(This _is_ the language setting in the OS. You can drag and drop the entries to change the order. All universal and modern store deployed apps follow this order.)

**Comment by greggman** [comment] 2020-05-08 06:29
Weird. Strange. I use no other apps that seem to respect that setting but I guess I just don't use any apps that do. The OS itself is in English. If I wanted everything in Japanese I'd set the OS to Japanese. Oh well, windows is full of language bugs and trying to work around them all is exhausting

Sorry for the misunderstanding.

**Comment by DHowett-MSFT** [comment] 2020-05-08 06:32
I do find it strange that there’s the “OS Language”, which dictates ... well, the OS but also _literally all other applications_, and the preferred language list that’s respected by modern packaged applications.

It gets even weirder if you use unpackaged Terminal: suddenly it _doesn’t_ use the preferred language list. I haven’t been able to determine what language it chooses- perhaps the “OS Language?”

Madness.

**Comment by Ludorg** [comment] 2020-05-14 22:14
> I'm confused. AFAIK Windows Terminal does not respect the language setting in the OS. Is that intentional? I have Japanese input enabled but my OS is set to English. 100% of my apps show an English UI and so does windows. Well, it was 100%. Only Windows Terminal is showing a Japanese UI in the drop down menu.

I had the same issue with French input. All the OS is configured in English and other apps are in english also (even the ones from Microsoft Store). Only Windows Terminal was (note the past, as I found a workaround) in French. To fix this, I opened Language Settings panel. A message in yellow showed me a warning about "group related languages".
![0-before](https://user-images.githubusercontent.com/3078575/81991124-d1ca7080-9640-11ea-918b-4db917b74919.jpg)

By clicking the button and relaunching Windows Terminal, all was correct with menu in English.
![1-after](https://user-images.githubusercontent.com/3078575/81991134-d5f68e00-9640-11ea-9880-67bf14d8a474.jpg)

**Comment by harrym124** [comment] 2020-05-20 10:58
The fix described in the above comment worked for me. Maybe the developers should study why it works, rather than closing all related issues.

My issue above for the same problem was closed by the developer DHowett with the following comment, which shows a basic misunderstanding of the difference in Windows between language and region ids.

> In short: terminal is following the windows operating system’s “preferred language list”. This is an ordered list of what languages you want Modern applications to use. This is also what the store, calculator, photos, etc. use. This is the display language for apps.

In my case, the entire Windows uses English, which is both the display language and the keyboard language. I have set the Formats option in "Control Panel -> Region -> Formats" to French in order to use the Euro symbol rather than the dollar.

Windows Terminal just uses the wrong system id. As a developer I once did the same mistake, but then I studied the question and corrected the mistake.

**Comment by fishie** [comment] 2020-05-30 11:51
Ah, the comments above explain why my Windows Terminal is in Japanese. I agree with the comments above that Windows is full of language bugs, or at least quirks. This is my "Preferred languages" list: 
![image](https://user-images.githubusercontent.com/674959/83327140-09106280-a27a-11ea-8a0f-5bb086c297fd.png)
As the text in the picture explains: "Apps and websites will appear in the first language in the list that they support", means that my Windows Terminal is in Japanese. Although my Windows is in English.

So basically I could  add English as a preferred language with Swedish locale so everything is in English and remove Swedish as a preferred language or add English but keep Swedish if I wanted my apps to be in Swedish but then I would end up with a redundant keyboard option that I would never use. I'll go for everything in English. It is unfortunate that I can't seem to have a Swedish Windows with Swedish as my preferred language while having apps that don't support Swedish fall back to English without a redundant keyboard option.

Sorry for the off-topic discussion. This is Windows issue, not a Windows Terminal issue. But this thread helped me a lot to understand what is going on with my Windows Terminal language.

**Comment by patrikhuber** [comment] 2020-07-15 16:01
I am having the same bug, see my description and screenshots in #6931.

A language setting in Windows Terminal would be nice - but primarily there is a bug at work here that should be fixed. Windows Terminal should respect the Windows System language, and it does not. See my screenshots in #6931.

@Ludorg's "fix" of pressing "Group related languages" sort-of "fixed" the problem half-way for me: The menu is English now but it still says "Eingabeaufforderung" (German).

![image](https://user-images.githubusercontent.com/4967343/87567557-4c088700-c6bc-11ea-9a37-aa202cc07be5.png)

Also I don't get why "Group related languages" "fixed" it because both **before**, my Windows display language was English:

![image](https://user-images.githubusercontent.com/4967343/87567660-78240800-c6bc-11ea-8c4f-efc65f8ed3a3.png)

As well as afterwards...:
![image](https://user-images.githubusercontent.com/4967343/87567705-84a86080-c6bc-11ea-9424-36369b8cec20.png)

This doesn't seem Windows Terminal specific though. I noticed now my Calculator is English too, whereas before it (wrongly) was German suddenly, after some of the previous Windows Updates. So it looks like this is a broader Windows Store issue - Windows Store at its finest - not adhering to the Windows display language. The whole OS adheres to that, Windows Store apps do not.

**Comment by DHowett** [comment] 2020-07-15 16:53
The key here is this:

![image](https://user-images.githubusercontent.com/189190/87572598-a4219800-c680-11ea-9f4f-61dbe90a090e.png)

Unfortunately, it's worded poorly given that it's directly under the part that says this...

![image](https://user-images.githubusercontent.com/189190/87572631-b3084a80-c680-11ea-8445-d3f72f9dfc3f.png)

Now, what's probably happened is that Terminal ships with its packaged language set to `en-US`, not `en-SV`... but your **preferred language order** looks like this to all modern applications:

* en-SV
* de-SV
* en-UK

since de* is the first one of those that actually _exists_ in the terminal package, it's the one that was getting selected. Curious why it didn't fall through to en-UK, though.

As for why your menu still says Command Prompt in German, that's because your initial install chose that lanugage and it's embedded in your settings file. Delete the name from settings.json and it'll revert to English.

**Comment by hSATAC** [comment] 2020-08-19 03:54
+1 to this. Especially with the `commandPalette` feature is released, it's important for devs to stick with Eng so we can speed up.

**Comment by kard02** [comment] 2020-10-30 09:37
I want to add onto this issue. I have 2 languages installed: Polish and German. German is not a language I am comfortable with, but I needed German keyboard layout for something. As of today, Polish is not a supported language, so Windows Terminal defaulted to German. This is yet another reason to have language selection (I am forced to install English language for now).

**Comment by hangyu-feng** [comment] 2020-11-06 22:04
Definitely useful to select a language for windows terminal! command palette is not that usable without English

**Comment by el-schneider** [comment] 2020-11-11 20:42
I also need the command palette to be in english but my system is not

**Comment by baypon** [comment] 2021-03-07 18:02
The "wrong language" bug - described in many already closed issues - still persist. 
Note, that I am using the only still open issue to report the bug: but for me it comes in Russian on a Polish OS.

I do not know where Terminal gets its language settings, but apparently if it lacks something, it uses the developer's native tongue - thats my guess.


Terminal reported version: `Windows Terminal Preview Версия: 1.7.572.0` on the Polish language OS
```
Wersja	Windows 10 Home
Wersja	20H2
Zainstalowano dnia	‎02.‎03.‎2021
Kompilacja systemu operacyjnego	19042.844
Możliwości	Windows Feature Experience Pack 120.2212.551.0
```

**Comment by zadjii-msft** [comment] 2021-03-25 20:55
A coworker pointed me at [`ApplicationLanguages.PrimaryLanguageOverride`](https://docs.microsoft.com/en-us/uwp/api/windows.globalization.applicationlanguages.primarylanguageoverride?view=winrt-19041), which might be exactly the API we're looking for here.

**Comment by gyorokpeter** [comment] 2021-04-26 18:59
I have the same problem. I have Hungarian, Chinese and Arabic keyboards set up but the latter two are only for typing practice on Duolingo and I don't intend them to be used for the display language of anything, and yet Terminal has all the menus in Chinese. I would like to change it to either Hungarian or English.

**Comment by DHowett** [comment] 2021-04-26 19:05
@gyorokpeter and you have "chinese" higher in your language preference list than English or Hungarian?

**Comment by gyorokpeter** [comment] 2021-04-27 06:24
@DHowett I don't have English on the list at all. There is no point since any other keyboard can do the same characters plus more.

**Comment by NiKiZe** [comment] 2021-05-05 22:44
I would say that any app that does not allow to change the language - if it supports multiple languages - has a bug.

I prefer apps to be in the native language, of the developer, as long as I understand that language, I have multiple apps that is for Swedish audience, And there I want that, for all other apps I do not want Swedish but rather English, and now I end up with this single app that suddenly is in Japanese

**Comment by lhecker** [comment] 2021-06-01 17:58
I began working on this in my spare time and got to a point where I could finish this up within a day.
I'll probably open a PR soon-ish.

**Comment by crramirez** [comment] 2021-06-02 09:53
@DHowett but you cannot pack the resources for English (en) instead of English US (en-us)? This is very common in most localization libraries

**Comment by DHowett** [comment] 2021-06-02 23:10
That's a good question. It would probably be good if we did that -- but I was worried about changing the filenames (or, paths) which might force the Windows localization team to re-localize everything. I'll reach out to somebody over there to see if we're clear to dot hat.

**Closed** 2021-06-10 23:24 UTC
Labels: Area-Settings, Help Wanted, In-PR, Issue-Feature, Product-Terminal

**Comment by lhecker** [comment] 2021-06-10 23:49
Unless any major issues turn up with the PR that was just merged, it'll be released in the near future.

Unfortunately I was unable to elegantly solve one bug though:
If you switch the language, you'll have to restart the application to take full effect, as existing, visible UI elements won't be updated with the newly selected language. But I figured it might be better to get this feature out sooner rather than later, since it certainly can be a bit of a pain if an application's language can't be changed. 🙂 I'm creating follow-up issues for this particular bug soon. Let me know if you find anything else!

**Comment by gyorokpeter** [comment] 2021-07-09 22:28
Is this released already? If so how to confirm if I have the version that has the change and how to actually change the language?

**Comment by DHowett** [comment] 2021-07-09 22:29
This will be released in the upcoming Preview release, 1.10.

**Comment by wengm** [comment] 2021-08-04 08:07
I would say that the issue here is caused by that Windows Terminal is not internationalized enough.
The solution or workaround is easy, for example, to use English as GUI language: install English language package and move it more front place until Windows Terminal can display in English.

Not tried preview version v1.10.1933.0. If it's possible to change GUI language by settings.json, it would be perfect.

**Comment by NiKiZe** [comment] 2021-08-04 10:26
> I would say that the issue here is caused by that Windows Terminal is not internationalized enough.
> The solution or workaround is easy, for example, to use English as GUI language: install English language package and move it more front place until Windows Terminal can display in English.
> 
> Not tried preview version v1.10.1933.0. If it's possible to change GUI language by settings.json, it would be perfect.

So you are saying that I need to move my preferences around and restart applications and system to get my apps in the language that I prefer to have them in?

Just stop make assumptions! I want some apps in English, other in Swedish, and some in Japanese, at the same time I don't want to change system language or settings at all. I would even say that Windows has a privacy bug that reveils this list to apps even if I don't want it to.

**Comment by cawoodm** [comment] 2021-08-28 11:50
I have an English PC (Windows 10 English) no German anywhere except my keyboard format and region (I live in Switzerland) and Windows Terminal is convinced I want it to be in German. Why? Every other piece of SW I run is in English. Something's not right here.

**Comment by cawoodm** [comment] 2021-08-28 11:51
Ah we CAN change it now. I am using 1.10 and it was set to "Use system default" and was in German so something ain't right...

**Comment by DHowett** [comment] 2021-08-30 17:20
@cawoodm Can you share a screenshot of the "preferred language" list in your system settings? We've been told of a few issues with "split" languages being in the wrong places in the list (like: "English (US)", "German (Germany)", "English (Germany)"). It seems like when the language is present in the list twice and there's a different language between them, the OS doesn't handle it particularly well.

**Comment by cawoodm** [comment] 2021-08-31 18:02
Oh dear - German is first. I swear I keep changing it to English and it switches back again. Nevertheless I feel WT is betting on the wrong horse here - if my Windows UI is EN then default to EN not this preferred language browser stuff. IMHO of course.

![image](https://user-images.githubusercontent.com/498834/131553215-e82bdf2c-90c3-4399-99b3-7899e0f25203.png)

**Comment by Ali-Hussein-dev** [comment] 2022-03-25 21:37
bad UX

**Comment by DHowett** [comment] 2022-03-25 21:38
> bad UX

If you have an actionable suggestion on how we could improve the language switcher experience inside Terminal, that would be much more useful than... this. :)
