### ISSUE TITLE
Window restore issue when running terminal elevated

### ISSUE THREAD

**Issue by lupinitylabs** [microsoft/terminal#13711] opened 2022-08-09 19:00 UTC
### Windows Terminal version

1.14.1962.0

### Windows build number

10.0.19044.1826

### Steps to reproduce

Open terminal in elevated mode (run as administrator). Minimize it by clicking the app on the taskbar, then try to restore the window by clicking on it again:

https://user-images.githubusercontent.com/17774818/183739867-de6c85b7-2622-4995-8943-a9b42302e707.mp4

### Expected Behavior

I would expect the app window to restore after clicking, regardless whether it was run elevated or not.

### Actual Behavior

Restoring the window works if not run as administrator, but it does not work when run as administrator.

**Comment by DHowett** [comment] 2022-08-09 19:44
Thanks for the report! This looks like a /duplicate of #13589, which is fixed pending release.

**Closed** 2022-08-09 19:44 UTC
Labels: Issue-Bug, Needs-Triage, Needs-Tag-Fix

**Comment by lupinitylabs** [comment] 2022-08-09 22:00
Actually it looks like an exact duplicate of #13592. Sorry, and thanks!
