### ISSUE TITLE
abort() has been called when I'm launching WindowsTerminal.exe

### ISSUE THREAD

**Issue by leonle9527** [microsoft/Terminal#473] opened 2019-05-07 07:45 UTC
![image](https://user-images.githubusercontent.com/46466849/57282211-2ad30080-70df-11e9-9681-922fed7f42eb.png)

**Comment by NyaMisty** [comment] 2019-05-07 07:58
duplicate of #426

**Comment by DHowett-MSFT** [comment] 2019-05-07 14:13
Closed as a duplicate of #426.

**Closed by DHowett-MSFT** 2019-05-07 14:13 UTC
