### ISSUE TITLE
Cursor block doesn't show the character underneath

### ISSUE THREAD

**Issue by tudorprodan** [microsoft/terminal#4786] opened 2020-03-03 10:11 UTC
![image](https://user-images.githubusercontent.com/1012368/75765193-082d6a80-5d37-11ea-9d91-bc191a5d9cb0.png)

I've searched for a `"cursorColor": "inverse"` option or something similar, haven't found one.

Please close if this is expected behaviour for some reason.

**Comment by j4james** [comment] 2020-03-03 11:02
I believe this is a duplicate of #1203.

**Comment by tudorprodan** [comment] 2020-03-03 12:06
> I believe this is a duplicate of #1203.

Yep, it's a duplicate of #1203

**Closed** 2020-03-03 13:51 UTC
Labels: Needs-Tag-Fix, Needs-Triage
