### ISSUE TITLE
Mouse judder / low screen refresh rate when the app window is open

### ISSUE THREAD

**Issue by nicebyte** [microsoft/terminal#9166] opened 2021-02-15 04:36 UTC
# Environment

Microsoft Windows [Version 10.0.18363.1379]
Windows Terminal Version 1.5

Dual monitor setup:

Monitor 1: ASUS ROG Swift PG279Q 27"  high refresh rate monitor (165Hz), plugged into DisplayPort
Monitor 2: Viewsonic VX2453MH-LED 60Hz monitor, plugged into HDMI

Both monitors connected via KVM switch.

# Steps to reproduce

Launch Windows Terminal on Monitor 1 or drag pre-existing window from Monitor 2 to Monitor 1.

# Expected behavior

No perceptible change in monitor refresh rate occurs.

# Actual behavior

Refresh rate of the 165Hz monitor appears to be lowered considerably. Previously, it used to be so bad I could actually see the image flicker. Now it's not as bad (no visible flicker), but I can feel a marked difference when moving the mouse around (anywhere on the affected screen, not just within the  borders of the terminal window) - without the Windows Terminal active, the movement is smooth and fast, with the terminal present on-screen, there's a lot of judder when moving the pointer around.

Switching to a different window or minimizing the terminal window removes these symptoms.

**Comment by DHowett** [comment] 2021-02-15 19:25
This looks like a /duplicate of #649. Verdict is, "nvidia and other GPU manufacturer software mis-detects Terminal as a game, and you need to add an exclusion to the nvidia/whatever control panel."

**Closed by DHowett** 2021-02-15 19:25 UTC
Labels: Needs-Tag-Fix, Needs-Triage
