### ISSUE TITLE
Disable use of bright colors for bold text

### ISSUE THREAD

**Issue by maggu** [microsoft/terminal#3613] opened 2019-11-18 10:14 UTC
# Description of the new feature/enhancement

The OS X Terminal has a setting for “Use bright colors for bold text”. If it is **disabled** I always get normal colors for bold text, which I have found to be quite useful for readability on a terminal with bright background (which I personally prefer).

I can of course change the color scheme, which solves the issue locally. However, when I connect to a Linux server with ssh, it has a color scheme of its own. (Which I can also change, but it would be more practical if the terminal were able to handle it.)

Perhaps some time after Windows Terminal is able to display actual bold text?

**Comment by egmontkob** [comment] 2019-11-18 11:59
#include "#2916"

**Comment by DHowett-MSFT** [comment] 2019-11-18 20:47
@egmontkob thanks for connecting these up! This is, more correctly, a /dupe of #109 (although right now it points at the wrong product :smile:)

**Closed by DHowett-MSFT** 2019-11-18 20:47 UTC
Labels: Issue-Feature, Needs-Tag-Fix, Needs-Triage
