### ISSUE TITLE
Request: Right-click menu inside TerminalControl (w/ Copy & Paste?)

### ISSUE THREAD

**Issue by ianceicys** [microsoft/terminal#3337] opened 2019-10-26 02:00 UTC
I use cmd.exe's right-click on the menu bar to Select All, Mark, Find, Copy, and Paste. I would like Windows Terminal to support a similar feature. 
Conhost.exe
![image](https://user-images.githubusercontent.com/3976990/67612708-d85fcc00-f772-11e9-8830-a50e1e8007c7.png)
I also get the right mouse button on WSL's Ubuntu console. 
![image](https://user-images.githubusercontent.com/3976990/67612732-42787100-f773-11e9-9e20-f31e3cb278b9.png)

**Comment by zadjii-msft** [comment] 2019-10-28 14:07
Seems vaguely related to #1912 as well.

This might require some more detailed design discussion. For example, if you right click on the titlebar (when tabs aren't in the titlebar), then it makes sense that these options would apply only to the active tab/pane. Start a selection in the current tab, copy the current tab's selected text, etc. 

What about if you right-click on a tab that's not focused? Would "copy" there copy the text from the unfocused tab?

Would "find" still bring up the search dialog for the currently focused pane?

**Comment by jdrch** [comment] 2020-03-11 14:34
Same request here. Not having a right-click menu seriously reduces Terminal's usability compared to MobaXterm on Windows and Konsole in KDE on Linux.

**Comment by cor3ntin** [comment] 2020-03-20 08:56
Yes, please! 
Here is what it looks like in Konsole, it is incredibly useful 

![image](https://user-images.githubusercontent.com/1409019/77149057-13033180-6a91-11ea-97f1-fe44546aebf3.png)

**Comment by jdrch** [comment] 2020-03-20 16:03
@cor3ntin Literally this a million times over. That's what an actually useful terminal app is supposed to do/look like.

**Comment by DHowett-MSFT** [comment] 2020-03-20 16:16
You don’t need to throw shade to make your point.

**Comment by jdrch** [comment] 2020-03-20 20:39
@DHowett-MSFT I'm just being honest. There's a reason I have Terminal installed but still use MobaXTerm, even for my WSL instances. Stuff like lack of right-click really diminishes the usefulness of a terminal emulator to me. If I said otherwise I'd be lying. 🤷‍♂️

**Comment by SFM61319** [comment] 2020-04-28 18:08
[This terminal](https://github.com/felixse/FluentTerminal "Fluent terminal") is a highly customizable UWP app that also has a context menu and looks cleaner and better than the official Windows Terminal app. I was thinking why don't we take that app as an "inspiration"?

**Comment by DHowett-MSFT** [comment] 2020-04-28 18:09
@SFM61319 Thanks for sharing a link to fluentterm on multiple bug reports on our repo. We'll take it into consideration.

**Comment by mdtauk** [comment] 2020-04-28 20:39
This context menu should also include the pane commands
"Split Vertically" and "Split Horizontally"

**Comment by jdrch** [comment] 2020-04-28 20:51
@mdtauk Which other terminal apps have that feature? Just curious. Most multiplexing is done server-side via `byobu`, `tmux`, or something similar.

**Comment by mdtauk** [comment] 2020-04-28 20:52
@jdrch the feature is there, however it can only be used via keyboard shortcuts.

**Comment by jdrch** [comment] 2020-04-28 20:53
@mdtauk Ah. TIL!

**Comment by zadjii-msft** [comment] 2020-04-28 20:55
@jdrch [Hyper](https://github.com/zeit/hyperterm/pull/693), [Terminator](https://gnometerminator.blogspot.com/p/introduction.html), Windows Terminal (see #1000), [iterm2](https://osxdaily.com/2011/01/03/split-terminal-mac-iterm2/)

**Comment by mdtauk** [comment] 2020-04-28 20:55
> @mdtauk Ah. TIL!

This is why I think the feature needs more UI awareness

**Comment by SFM61319** [comment] 2020-04-29 14:47
Also, the profile menu and the buttons don't look much "fluent". Please add some `AcrylicBrush` and `RevealBrush` brushes to those for a more fluent effect.

**Comment by zadjii-msft** [comment] 2020-04-29 14:58
@SFM61319 The discussion of where to use acrylic and where not to isn't really on-topic for this thread - I've moved the discussion over to #1375

**Comment by helenol** [comment] 2020-05-11 12:28
Since the issue https://github.com/microsoft/terminal/issues/3424, asking to be able to disable paste on right-click, was closed as a duplicate of this issue, I would like to bring that up as a separate issue (that is much easier to address) here. *PLEASE* allow me to disable this functionality in the settings. 

I am constantly accidentally pasting my clipboard into the terminal while trying to do something else, which is going to force me to switch back to ConEmu where I can disable this functionality.
Since there's already settings for copy on select and key bindings for copy-paste, **please please please** make this feature turn-off-able too.

**Comment by DHowett-MSFT** [comment] 2020-05-12 01:49
So, we're tracking the ability to fully customize what happens when you click in #1553. As part of that work, we'll of course make sure you can turn off all right-click actions.

**Comment by vwheeler63** [comment] 2020-08-10 17:39
There is another issue related to this that I think is even more important than neat features: right-click paste can be dangerous or even catastrophic when working in a source-code environment -- I just had it happen to me that a series of lines pasted into a command window (which is why I did a search and found this issue) -- I'm very glad it is on the table.  I'm just glad the (unintentional) paste didn't delete or alter any files.  (This would be a really insidious way for a hacker to ruin a PC too with the right commands snuck onto the clipboard.)  I am aware there is a way to warn before multi-line pasting, which is what I am going to look up now.

In any case, I wanted to reinforce the importance of this one:  I believe it is critical to making Windows Terminal safe to use in a source-code environment, where I would very much like to prevent any pasting unless I hit Shift-Ins or Ctrl-V or other bound key sequence to do it.  Thanks!!

**Comment by jdrch** [comment] 2020-08-10 17:59
> right-click paste can be dangerous or even catastrophic when working in a source-code environment

Good to know. Hadn't considered that!

> I am aware there is a way to warn before multi-line pasting, which is what I am going to look up now.

MobaXterm will warn you if there's an `Enter` (or newline) included in the paste that might cause the resulting line to execute.

**Comment by juvtib** [comment] 2020-08-31 17:36
I'm excited by Terminal. But I'm not willing to use it until I can disable right-click paste. I don't want to dump a bunch of unknown text or commands into a live terminal just because of a stray mouse click.

**Comment by vwheeler63** [comment] 2020-08-31 18:24
> 
> 
> I'm excited by Terminal. But I'm not willing to use it until I can disable right-click paste. I don't want to dump a bunch of unknown text or commands into a live terminal just because of a stray mouse click.

I did find something that mitigates this problem enough for me to start using it:  the global setting

"multiLinePasteWarning": true, 

at least prevents any commands from executing unintentionally, since it looks for line-feeds in the clipboard contents and requires a confirmation before it pastes.  However, I'm anxious to see an ability to turn paste-on-right-click feature off or ONLY paste with Ctrl-Ins or other configured key mappings.

**Comment by mangelozzi** [comment] 2020-09-07 12:59
`"multiLinePasteWarning": true,` is not a fix for me cause I am often pasting multi-line text into VIM.

**Comment by drewhemm** [comment] 2020-09-07 16:31
I wonder where the right-click immediately pastes behaviour originally started? The same behaviour is present in Visual Studio Code's integrated terminal in Windows, but not in Linux.

**Comment by juvtib** [comment] 2020-09-07 19:28
> 
> 
> I wonder where the right-click-immediately-pastes behaviour originally started? The same behaviour is present in Visual Studio Code's integrated terminal in Windows, but not in Linux.

I know it from [Console Window Host](https://www.howtogeek.com/howto/4996/what-is-conhost.exe-and-why-is-it-running/). Right-click paste has been the *default* option there for as long as I can remember. But all console shortcuts have a shortcut property that allows you to disable 'Quick Edit Mode'. I assume the Terminal team picked the default behavior to start with.

**Comment by ViniDalvino** [comment] 2020-11-05 16:36
An right click menu like linux terminal would be amazing! It would avoid accidently pasting stuff and it would make it more conveinient to copy and paste stuff into the terminal. ![](https://i.imgur.com/bf3qcLU.png)

**Comment by lobosan** [comment] 2020-12-26 22:48
any alternative for this?

**Comment by guoqiao** [comment] 2021-07-22 11:15
> @mdtauk Which other terminal apps have that feature? Just curious. Most multiplexing is done server-side via `byobu`, `tmux`, or something similar.

1. Splitting screen is super useful to me, I do it all the time in daily work,  especially we now have large monitorers.
2. I normally work on Ubuntu with Terminator, the main reason is because is has `Horizontal Split` and `Vertical Split` plus icons in right click context menu. Having them in menu is helpful so I don't need to remember the shortcuts. Havign the icons is also helpful,  since when you say "Horizontal Split" (or "Vertical Split") , it is actually confusing:  are you spliting a new window in the horizontal direction(口|口), or you mean the split line is is horizontal (曰)? The icons make you understand it without thinking.

**Comment by davidwales** [comment] 2022-02-17 02:12
It would be really nice to be able to right-click a pane to close it.

**Comment by zadjii-msft** [comment] 2022-03-28 19:12
misc notes from last week:

* Some of these actions should only appear when text is selected.
  * how? 
  * How do we feed the selected text into the action in the menu?
  * There are some notes in #5916 
* I want to be able to right-click search for some text, but again, that requires parsing the action at time of invoke, because the action name would be dependent on the selected text? (some notes in #10175)
* I want to be able to right click a selection and save that as a `sendInput` action _with that text_. That's crazy. 
* "Open Current Directory" or "Copy current path" actions would require that a path had been set by the shell

**Comment by WaitingForGuacamole** [comment] 2022-05-26 12:49
So, noticing that this issue was opened 2-1/2 years ago, and that functionality is being mentioned/consolidated into it, can we get some visibility into where it sits in the roadmap - that is, when will it come out of planning and go into development?

**Comment by zadjii-msft** [comment] 2022-10-31 19:44
FWIW I hacked this together during the hackathon before leave. I left it in `dev/migrie/f/3337-just-for-funsies`. I think it still needs some cleanup before real review, **but I think someone from the community could probably get it across the finish line**. 

Dustin and I talked about how we might want to make this a bonafide part of TermControl itself - like, anyone who uses a UWP XAML TermControl should be able to get this menu. 

Of course, that would require more refactoring to get it so things like Copy, Paste, Find are always in the menu, and then the menu is given to the app layer to allow additional entries to be added. 

The other weird trick is that the Copy/Paste/Find actions in the menu would need to be wired up in whoever is hosting the control. All that seems like more work than it's worth right now to get this out in an experimental form. I'll punt that discussion to #6999

**Comment by zadjii-msft** [comment] 2023-01-29 15:34
More notes 

![image](https://user-images.githubusercontent.com/18356694/215336360-1bd50789-3b53-42ef-bb1c-8fb549b639e3.png)

Do something like this. 

* [ ] `TermControl` should have a `ContextFlyout` property, which is a `CommandBarFlyout`. 
* [ ] The `TerminalPage` can add an `Opening` handler to that `ContextFlyout`. 
* [ ] In that `Opening` handler, the page can add commands it wants to customize the control with. 
* [ ] Copy, paste, find are always in the menu.
* [ ] `SplitPane`, `DuplicateTab`, `ClosePane`, `CloseTab` all get added as needed.
* [ ] In the sample for `RichTextBox`, there's a separate `SelectionFlyout`. That doesn't seem like a bad idea, honestly. 
  * [ ] Only put copy/find in those commands
  * [ ] Only put `SearchWeb` in there

**Closed** 2023-03-17 18:54 UTC
Labels: Issue-Feature, Area-User Interface, Product-Terminal, In-PR

**Comment by zadjii-msft** [comment] 2023-03-21 11:01
That just merged on Friday - it's only available in `main` currently. It'll be a while before 1.18 comes out with this.

**Comment by isayakmondal** [comment] 2023-03-21 11:13
> That just merged on Friday - it's only available in `main` currently. It'll be a while before 1.18 comes out with this.

In the mean time can I change the behavior of the right click or disable to completely?

**Comment by zadjii-msft** [comment] 2023-03-21 11:19
Nope, sorry.

**Comment by frisedel** [comment] 2024-03-04 08:58
so a year has passed, and it seems that the context menu should be in the preview version.
however, I can't get it to work.
any suggestions on how to do that? the option is not the settings

**Comment by zadjii-msft** [comment] 2024-03-04 12:05
It's not in the settings UI anywhere, but you can add it in to the settings manually, with 

```
"experimental.rightClickContextMenu": true,
```

under any profile

**Comment by jdrch** [comment] 2024-03-04 23:12
> under any profile

Where is this located again? Dumb question, sorry.

**Comment by Neme12** [comment] 2024-03-05 16:27
What version is `experimental.rightClickContextMenu` available in? I have version 1.19.10573.0 and setting this in settings.json has no effect.

**Comment by Neme12** [comment] 2024-03-05 16:30
Oh I see, it's a per-profile setting. I learned about the setting here: https://learn.microsoft.com/en-us/windows/terminal/customize-settings/interaction - there, it says the settings on that page belong to the root of settings.json.
![image](https://github.com/microsoft/terminal/assets/11444821/44c60c2f-b6a9-434e-aebf-e35a989060f1)

**Comment by jdrch** [comment] 2024-04-22 03:15
> It's not in the settings UI anywhere, but you can add it in to the settings manually, with
> 
> ```
> "experimental.rightClickContextMenu": true,
> ```
> 
> under any profile

Hey @zadjii-msft I added it to my `%LOCALAPPDATA%\Packages\Microsoft.WindowsTerminalPreview_8wekyb3d8bbwe\LocalState\settings.json` as:

```
{
    "$help": "https://aka.ms/terminal-documentation",
    "$schema": "https://aka.ms/terminal-profiles-schema-preview",
    "experimental.rightClickContextMenu": true,
```

But when I right-click in Terminal Preview it just spits out the setting every time I click, resulting in a command prompt that looks like this:

`> "experimental.rightClickContextMenu": true"experimental.rightClickContextMenu": true"experimental.rightClickContextMenu": true`

Any ideas?

**Comment by jdrch** [comment] 2024-04-22 03:18
Update: follow [these instructions](https://winaero.com/windows-terminal-preview-1-18-adds-tab-tearout-portable-mode-and-more/) to add `"experimental.rightClickContextMenu": true` to `%LOCALAPPDATA%\Packages\Microsoft.WindowsTerminalPreview_8wekyb3d8bbwe\LocalState\settings.json`

I did the above and it worked just fine.

**Comment by frisedel** [comment] 2024-04-22 08:28
> Update: follow [these instructions](https://winaero.com/windows-terminal-preview-1-18-adds-tab-tearout-portable-mode-and-more/) to add `"experimental.rightClickContextMenu": true` to `%LOCALAPPDATA%\Packages\Microsoft.WindowsTerminalPreview_8wekyb3d8bbwe\LocalState\settings.json`
> 
> I did the above and it worked just fine.

the instructions described in the link was the exact instructions given by @zadjii-msft

**Comment by jdrch** [comment] 2024-04-22 13:02
> > Update: follow [these instructions](https://winaero.com/windows-terminal-preview-1-18-adds-tab-tearout-portable-mode-and-more/) to add `"experimental.rightClickContextMenu": true` to `%LOCALAPPDATA%\Packages\Microsoft.WindowsTerminalPreview_8wekyb3d8bbwe\LocalState\settings.json`
> > 
> > I did the above and it worked just fine.
> 
> the instructions described in the link was the exact instructions given by @zadjii-msft 

Not to me. They didn't specify where the `settings.json` file is or exactly where in the file to put the line. All he said was to put the line in the file. If you put it at the beginning as his instructions read, the feature doesn't work.

Details matter.

**Comment by frisedel** [comment] 2024-04-22 13:46
Read it again, he specified to put it in/under any profile

**Comment by zadjii-msft** [comment] 2024-05-28 14:24
Note to self: write the spec for #1553, so that we can make this (context menu) the default.
