### ISSUE TITLE
"Default Terminal" mysteriously doesn't work at all - boots up the vintage console instead

### ISSUE THREAD

**Issue by ghost** [microsoft/terminal#11529] opened 2021-10-18 14:25 UTC
### Windows Terminal version (or Windows build number)

1.11.2731.0

### Steps to reproduce

When I made the MS terminal preview the default terminal then I clicked on the Save button and then opened Run and typed cmd. It opened the original Command Prompt window

### Expected Behavior

I expected that it would open the MS Terminal Preview

### Actual Behavior

It opens the original cmd

**Comment by BajajAditya123** [comment] 2021-10-19 11:27
OS Bulid - 22000.258
![image](https://user-images.githubusercontent.com/84385465/137900401-a143bf00-73f6-4cae-88c5-c8802ae0a4f5.png)
x64

**Comment by BajajAditya123** [comment] 2021-10-19 11:41
@zadjii-msft

**Comment by happybear88** [comment] 2021-10-21 12:49
Please stop spamming the thread  --Vadim SterkinBlog: https://www.outsidethebox.ms/ From: BajajAditya123Sent: Thursday, October 21, 2021 15:47To: microsoft/terminalCc: happybear88; CommentSubject: Re: [microsoft/terminal] Default Terminal Bug (Issue ***@***.*** ?????—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zadjii-msft** [comment] 2021-10-21 14:02
Hokay, so while we don't think this was fixed in 1.12, there should be some additional logging that might be useful. To get these logs, I'm gonna need you to follow a couple steps:

1. Download the [`Terminal.wprp` file from our repo](https://github.com/microsoft/terminal/blob/main/src/Terminal.wprp) somewhere on your PC. For example, let's put the file at `C:\path\to\Terminal.wprp`
2. Setup Windows Terminal Preview as the default terminal application. You can do this in the Console Property sheet, the Settings app, the Terminal Settings UI, anywhere, doesn't matter. It just needs to be set to Windows Terminal Preview, so we get the diagnostics from 1.12.
3. (Preferably, close all other Terminal & console windows. That'll make the logging less noisy).
4. From an elevated commandline, run:
```
wpr -start C:\path\to\Terminal.wprp!Defterm.Verbose
```
5. Try launching `powershell.exe` or `cmd.exe`. Could be from the Start Menu, the Run Dialog, anywhere. Doesn't matter. (It'll pop up in the vintage console window, but that's fine. We want to find out why that happened.)
6. Go back to the elevated commandline window and run:
```
wpr -stop defterm-trace.etl
```
7. Take the `defterm-trace.etl` file, and send it to me (my email is on my GH profile). 


HOPEFULLY, the logging we added in #11537 should help clue us in as to why this is failing.

**Comment by BajajAditya123** [comment] 2021-10-21 14:44
ok I will try that

**Comment by zadjii-msft** [comment] 2021-10-21 15:59
Derp. Not enough coffee. Try it again, with `wpr -stop C:\defterm-trace.etl`

**Comment by BajajAditya123** [comment] 2021-10-21 16:02
![image](https://user-images.githubusercontent.com/84385465/138314914-150af617-7129-4271-8351-9517418473ef.png)

**Closed as completed** 2021-10-26 19:08 UTC
Labels: Resolution-Fix-Committed, Issue-Bug, Needs-Triage, Needs-Attention, Product-Terminal, Priority-1, Area-DefApp

**Comment by eryksun** [comment] 2021-10-30 08:48
> We're thinking there's some dependent c runtime dll that might not necessarily be installed by default

This was an easy fix for my vanilla test VM. I just had to install the Visual C++ Redistributable, which installed the required "vcruntime140.dll" file to the system directory. This C runtime DLL is actually beside "OpenConsoleProxy.dll" in the Windows Terminal Preview directory in "%ProgramFiles%\\WindowsApps", but I suppose the COM host doesn't load "OpenConsoleProxy.dll" using the flag `LOAD_LIBRARY_SEARCH_DLL_LOAD_DIR`.

**Comment by brialmsft** [comment] 2021-11-01 22:06
COM uses LOAD_WITH_ALTERED_SEARCH_PATH, which should be able to resolve dependencies DLLs adjacent to the main DLL being loaded by LoadLibraryEx.

**Comment by brialmsft** [comment] 2021-11-01 22:24
Oh right, this was failing in the context of proxy/stub creation, wasn't it? In that case, the issue is likely the fact that proxy/stub DLLs exposed by MSIX packages aren't actually loaded from the real location within the package root, they're copied to an alternate location. This is because the security configuration on package roots doesn't necessarily let processes outside of the package execute the package's binaries. So we copy the proxy/stub DLLs to a location with more appropriate security configuration, without their dependencies, which is what causes the dependencies to not resolve.

Bottom-line: it is virtuous to make sure MSIX proxy/stub DLLs have minimal dependencies.
