### ISSUE TITLE
Touchpad scrolling too fast -- should act in precision mode

### ISSUE THREAD

**Issue by SJang1** [microsoft/terminal#1066] opened 2019-05-30 13:37 UTC
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18898.1000], Microsoft Windows [Version 10.0.18908.1000] (both)
Windows Terminal version (if applicable): commit d24d647 and even before.

PC Info: Samsung NT901X5L
```

# Steps to reproduce

Just scroll (up and down) by touchpad. (two-hand scrolling)
That's all.

# Expected behavior

Smooth scrolling

# Actual behavior

Terminal scrolls too fast.

**Comment by zadjii-msft** [comment] 2019-05-30 14:19
I mean, I guess we could figure out how to configure how much we scroll by when the user scrolls. That seems like it should be something the system configures however. 

Maybe we just need to look up some value from the system to determine how much to scroll by.

**Comment by DHowett-MSFT** [comment] 2019-05-30 21:43
We should probably do line-by-line scrolling on touchpads to mimic precision scrolling. We should almost certainly make sure velocity coasting works when we do this.

**Comment by warpdesign** [comment] 2019-06-22 21:29
Same problem here on a Surface Book.

I think it should be possible to scroll by as little as one line if movement is very small.

Also, having some kind of velocity and not have the scrolling immediately stop as soon as the user stops scrolling would make the Terminal app behave more like other (UWP) apps.

**Comment by ZZYSonny** [comment] 2019-08-04 15:13
Both line by line and pixel by pixel are pretty nice for me. Pixel by pixel is "nicer" but smooth scroll could result in a efficiency problem in terminal.

For now I think we should fix scroll too fast problem. The gesture to scroll a few lines in a browser could scroll an entire page in Windows Terminal, which makes the scrolling process unreadable and hard to locate. Probably do some translation, like scrolling one line in windows terminal = scrolling some lines in UWP. At least make it slower.

**Comment by Gavin110** [comment] 2019-09-14 16:16
i think its scroll fast，Seriously affect user experience！！

**Comment by PaulBendall** [comment] 2019-10-31 12:14
Any update on this issue? Its been listed for a while and makes terminal a pretty poor experience on laptops with touchpads include Microsoft's own Surface range (e.g Surface Book 2)

**Comment by zadjii-msft** [comment] 2019-10-31 12:28
@PaulBendall Nope. We'll make sure to post on this thread when we do find some time to address it. It's marked for "Terminal 1.0", so we plan on fixing this before the 1.0 release, but we don't have a more specific timetable than that. If someone's passionate about this bug and wants to take a crack at fixing it themselves, we'd be more than happy to review a PR from the community 😊

**Comment by jboeshart** [comment] 2019-11-15 03:57
Upvote on this, touchpad scrolling on Surface Book 2 (and would assume other Surface devices) is really bad.

**Comment by piratetub** [comment] 2019-11-17 10:22
I have a precision Touchpad and I can vouch that the scrolling is so fast that I can't use _Windows Terminal_ with my Touchpad at all. I have to rely on a touchscreen to scroll.
Also, the general scrolling behavior does not adhere to the general UWP scrolling behavior- no smooth scrolling. The team should consider changing the behavior to at least match the classic console's, which is usable at the least.

**Comment by hannesne** [comment] 2019-11-27 00:58
I've done a pull request to make the number of lines that is scolled at a time configurable in the settings file. Default was previously hard coded at 4, with a todo in the comment. On my Surfacebook I set it to 1 and it works real nice. Pull Request is #3575 Incidentally setting the number of lines to scroll to a negative value enables reverse scrolling.

**Comment by ovcharik** [comment] 2019-12-04 20:40
Not sure that is still relevant. But as temponary solution it is possible use [AutoHotkey](https://www.autohotkey.com/) script.

https://gist.github.com/ovcharik/20af27323514fcf2b116f9cfaad420f4

**Comment by davidwparker** [comment] 2019-12-27 17:19
Nice PR @hannesne - is there any update on this? I'm assuming (due to holidays, etc), the earliest we would see this would be next year?

**Comment by zadjii-msft** [comment] 2019-12-30 15:23
@davidwparker Correct - I don't think we're planning on shipping an update _today_, so it's definitely not landing till the next decade :P

**Comment by hannesne** [comment] 2020-01-05 08:01
@davidwparker   PR only needs approval from @carlos-zamora, before being merged.

**Comment by joeyaiello** [comment] 2020-01-13 19:20
Just wanted to pile on that, while setting the number of lines on scroll is very helpful, smooth scrolling (a la what I get in most browsers) is what I'm really looking for. Touchpad/scroll wheel is a bigger deal for me than touchscreen, but that would be sweet too.

**Comment by DHowett-MSFT** [comment] 2020-01-13 19:44
Yes, we just need somebody who knows anything about the direct input/direct manipulation APIs to take a crack at it :smile:

**Comment by AjawadMahmoud** [comment] 2020-01-15 13:36
So, this didn't make it in v0.8 arrived today. Can we expect it with next release?

**Comment by DHowett-MSFT** [comment] 2020-01-15 17:08
If a bug is open and doesn’t contain a comment from the bot indicating that a fix is available in a specific release, a fix is not available in that release.

As a workaround, you can set the global `rowsToScroll` property in your `profiles.json` to approximate precision scrolling. 1 seems like a nice value.

**Comment by Fedorov113** [comment] 2020-01-22 12:15
@DHowett-MSFT I can confirm that setting `rowsToScroll` to 1 works as a workaround. Waiting for the proper fix.

**Comment by Jewsh-S** [comment] 2020-02-18 22:04
This is great!  Just wanted to say thanks and that I personally really appreciate this.

**Closed** 2020-02-19 03:04 UTC
Labels: Area-TerminalControl, Help-Wanted, Issue-Bug, Issue-Task, Priority-3, Product-Terminal, v1-Scrubbed
