### ISSUE TITLE
Attempting to split pane through command palette crashes Windows Terminal when in settings.

### ISSUE THREAD

**Issue by inlitum** [microsoft/terminal#13528] opened 2022-07-18 02:24 UTC
### Windows Terminal version

1.13.11431.0

### Windows build number

10.0.19044.1766

### Steps to reproduce

1. Open Settings
2. Open command palette with keyboard shortcut ([ctrl + shift + p] in my case)
3. Search "split"
4. Select "Split pane, split: <any>"

### Expected Behavior

A new settings to be opened in parallel to the existing settings. 
This way I can edit similar settings at the same time.

### Actual Behavior

Windows Terminal crashes

**Comment by zadjii-msft** [comment] 2022-07-18 11:39
> ### Expected Behavior
> A new settings to be opened in parallel to the existing settings. This way I can edit similar settings at the same time.

Alas, that's probably not something which will land for quite some time now - we'd have to land #997 first


<hr>

As far as the crash is concerned, I can't repro this on 1.15 or 1.14. Can you check out one of those builds off our [Releases](https://github.com/microsoft/terminal/releases) page/? We may have coincidentally fixed this.

**Comment by ianjoneill** [comment] 2022-07-18 12:51
I fixed this in #13172 - this is a dupe of #13166

**Closed** 2022-07-18 21:34 UTC
Labels: Issue-Bug, Needs-Author-Feedback, Needs-Triage, Needs-Tag-Fix
