### ISSUE TITLE
Korean input is acting wierd

### ISSUE THREAD

**Issue by JuhoKang** [microsoft/terminal#4311] opened 2020-01-21 01:57 UTC
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18362.592]
Windows Terminal version (if applicable): Windows Terminal (Preview) Version: 0.8.10091.0
```

# Steps to reproduce

Type Korean in terminal

ex) Type 안녕하세요 with the keyboard

reproduce gif.

![koreannotnormal](https://user-images.githubusercontent.com/4745294/72769037-a7414b80-3c3c-11ea-9fdb-a5738c724175.gif)

# Expected behavior

show 안녕하세요 on the terminal

# Actual behavior

shows 안녀ㄴ녕하ㅎ하셍세세요요

**Comment by zadjii-msft** [comment] 2020-01-21 20:35
Thanks for the bug report with the clear repro in the gif! This looks to me like a duplicate of another issue on our tracker, so I'll redirect discussion to that thread.

/dup #4226

**Closed by zadjii-msft** 2020-01-21 20:35 UTC
Labels: Needs-Tag-Fix, Needs-Triage
