### ISSUE TITLE
offline install support!

### ISSUE THREAD

**Issue by jliu666** [microsoft/terminal#1405] opened 2019-06-22 12:19 UTC
In some place, I can't connect to windows app store. Such as in my company!

**Comment by cup** [comment] 2019-06-22 12:46
https://github.com/microsoft/terminal/issues/1386

**Comment by zadjii-msft** [comment] 2019-06-22 13:45
Closing as a dupe of #1386

**Closed by zadjii-msft** 2019-06-22 13:45 UTC
Labels: Issue-Feature, Needs-Tag-Fix, Needs-Triage

**Comment by SJang1** [comment] 2019-06-22 14:17
BTW for now if you are hurry for that, you can build it from source.

**Comment by jliu666** [comment] 2019-06-22 14:43
> BTW for now if you are hurry for that, you can build it from source.

I am just a Java/bash developer. It's difficult for me to build if from source.

**Comment by cup** [comment] 2019-06-25 00:00
https://github.com/microsoft/terminal/issues/1386

https://github.com/microsoft/terminal/issues/1405
https://github.com/microsoft/terminal/issues/1480
https://github.com/microsoft/terminal/issues/1483
https://github.com/microsoft/terminal/issues/1541

**Comment by johan-boule** [comment] 2020-12-20 20:48
Microsoft has locked the related issue #1386. We are invited to not further discuss or complain about it.

**Comment by DHowett** [comment] 2020-12-20 21:42
If there is meaningful discussion still to be had on 1386 (complaints do not count as meaningful discussion), I would be surprised. That issue has accumulated all available knowledge on how people feel about the issue. 

Did you want to add your voice?

What did you want to say?
