### ISSUE TITLE
Enable a command to run as Administrator

### ISSUE THREAD

**Issue by okantmav** [microsoft/terminal#7068] opened 2020-07-25 05:08 UTC
# Enable a solution into the terminal to run it from an **elevated command shell** (cmd/powershell).

### I forget to run the terminal as admin, I think many people do it.

# Proposed technical implementation details

It could great to use hot key to select "user " or "admin" shell.

`{ "command": "RunAsAdmin", "keys": "ctrl+shift+a" }`

The issue of forget to run the terminal as "admin":

"You may experience errors - many functions/packages require admin rights. Only advanced users should run choco w/out an
 elevated shell. When you open the command shell, you should ensure hat you do so with "Run as Administrator" selected. If you are attempting to use Chocolatey in a non-administrator setting, you must select a different location other than the default install location."

This message is frequent, so I should to close the terminal and open it again as "admin".

**Comment by dafzor** [comment] 2020-07-26 09:13
See issue #146. In the meantime you have a great solution with [gsudo](https://github.com/gerardog/gsudo).

Personally I've set up my powershell profile to override all chocolatey alias with:
```powershell
function choco { gsudo choco @args }
```

**Comment by skyline75489** [comment] 2020-07-27 11:26
I’m so happy to learn that there’s gsudo. It feels super elegant to me. I’m a little surprised that no one mentions gsudo in #146.

**Comment by dafzor** [comment] 2020-07-27 11:45
The allow elevation issue and it's variants keeps getting duplicate reports. So there's nuggets of information spread all over the place (I learned about gsudo on one of them)

**Comment by zadjii-msft** [comment] 2020-07-27 12:37
There's also #632/#1032/#5000 tracking the mixed elevation of tabs, so I'm gonna close this as a collective dupe of all those threads.

/dup #146 #632 #1032 #5000

**Closed by zadjii-msft** 2020-07-27 12:37 UTC
Labels: Issue-Feature, Needs-Tag-Fix, Needs-Triage
