### ISSUE TITLE
Close all tabs popup resizing problem

### ISSUE THREAD

**Issue by m2a9x45** [microsoft/terminal#5252] opened 2020-04-06 03:09 UTC
# Environment

```none
Windows build number: 10.0.18362.720
```

# Steps to reproduce

- Open more than one tab in the terminal. 
- Resize the terminal to it's smallest size horizontally. 
- Then close the terminal. 
- The "do you want to close all tabs" popup should appear. 
- Finally resize the window horizontal again.

# Expected behavior

The close all tabs popup should resize with the window. 
### Starting point 
<img src="https://i.imgur.com/FjRG83F.png"></img>
### Resized terminal 
<img src="https://i.imgur.com/6blG094.png"></img>
### Close all tabs popup
<img src="https://i.imgur.com/dZlugKC.png"></img>
### Resized with close all tabs popup open
<img src="https://i.imgur.com/K643Xrj.png"></img>

# Actual behavior

Once the "do you want to close all tabs" popup appears and you resize the terminal. The popup stays at the size it was when it opened. And doesn't resize to fit the window.

**Comment by DHowett-MSFT** [comment] 2020-04-07 17:43
Thanks! This is a /dupe of #2380

**Closed by DHowett-MSFT** 2020-04-07 17:43 UTC
Labels: Needs-Tag-Fix, Needs-Triage
