### ISSUE TITLE
Updating GPU driver may cause lockup

### ISSUE THREAD

**Issue by sundhaug92** [microsoft/terminal#15917] opened 2023-08-31 18:06 UTC
### Windows Terminal version

1.17.11461.0

### Windows build number

10.0.22621.2215

### Other Software

Including for completeness
GeForce Experience 3.27.0.112
Nvidia GeForce Game Ready driver (updated to): 537.13

### Steps to reproduce

Have WT running (having it minimized or in the background may be required), update GPU driver, try to bring the window to the foreground after the update completes.

### Expected Behavior

For it to continue working, possibly after a redrawing

### Actual Behavior

The existing window became completely non-responsive and had to be forcefully terminated using task manager.
One attempt to re-open the app caused it to do this: 
![image](https://github.com/microsoft/terminal/assets/519283/634b9301-dc52-4625-95c6-27ff4dca4e3a). 
After some retries it eventually started working

**Comment by lhecker** [comment] 2023-08-31 19:55
This may be a duplicate of #15553. Do you happen to have any dumps in `%LOCALAPPDATA%\CrashDumps`? If so, would you be willing to share them with us?

**Comment by sundhaug92** [comment] 2023-09-03 21:21
> This may be a duplicate of #15553. Do you happen to have any dumps in `%LOCALAPPDATA%\CrashDumps`? If so, would you be willing to share them with us?

I have crashdumps for other programs there, not for wt

**Comment by zadjii-msft** [comment] 2023-09-06 21:36
> One attempt to re-open the app caused it to do this:
> [image]

This is _super interesting_. There's literally no tabs in that window - somehow a window was created _without a tab_?? Does clicking on the new tab button in that transparent window create a new tab?

**Comment by carlos-zamora** [comment] 2023-09-06 21:36
Thanks for the bug report! We're going to mark this as a /dup of #15553 because we suspect that updating the GPU driver is the issue here. If we find that they're different, we'll de-dup the bugs.

**Closed** 2023-09-06 21:36 UTC
Labels: Issue-Bug

**Comment by sundhaug92** [comment] 2023-09-07 22:36
> > One attempt to re-open the app caused it to do this:
> > [image]
> 
> This is _super interesting_. There's literally no tabs in that window - somehow a window was created _without a tab_?? Does clicking on the new tab button in that transparent window create a new tab?

IIRC that's what I ended up doing, at that point it started working normally again
