### ISSUE TITLE
Add padding property to background image

### ISSUE THREAD

**Issue by jt-github** [microsoft/terminal#6578] opened 2020-06-18 19:55 UTC
For those of us that like to have a little icon as a background to help remind us of which tab we're in, the `backgroundImage`, `backgroundImageAlignment` (I prefer `topRight`), and `backgroundImageStretchMode` (I prefer `none`) are perfect.  That sort of thing is usually desirable for images that fill up the whole pane, but smaller images that live somewhere other than the center of the pane are forced to slam up against the edges.

I propose a new property to allow adding a little space between the image and the edges of the pane:
`backgroundImagePadding`

**Comment by DHowett** [comment] 2020-06-18 23:46
Thanks for the request! This sounds like a /duplicate of #2620 to me, so I'm gonna close it out. I think this use case would totally be subsumed by offsetX/offsetY :smile:

**Closed by DHowett** 2020-06-18 23:46 UTC
Labels: Needs-Tag-Fix, Needs-Triage

**Comment by jt-github** [comment] 2020-06-19 17:17
Thanks for the quick action and for finding that this is a duplicate, @DHowett, and yes, the offsets would handle this nicely.
