### ISSUE TITLE
Windows Terminal must be restarted to learn about new WSL distros.

### ISSUE THREAD

**Issue by Hoikas** [microsoft/terminal#7595] opened 2020-09-10 16:00 UTC
# Environment

```none
Windows build number: 10.0.19042.0
Windows Terminal version (if applicable): 1.2.2381.0
```

# Steps to reproduce
- Open Windows Terminal.
- Install **new** WSL distro from Windows Store.
- Open "profiles" in Windows Terminal.

# Expected behavior
- The new WSL distro should appear in the list of profiles.

# Actual behavior
- The new WSL distro does **not** appear in the list of profiles.
- Windows Terminal must be completely restarted to receive the new distro, causing a massive context-shift time sink.

**Comment by WSLUser** [comment] 2020-09-11 16:15
I'll note a workaround is using RaftforWSL by WhiteWater Foundry. Since that's a paid solution though, perhaps someone could write a FOSS equivalent of this feature request.

**Comment by DHowett** [comment] 2020-09-25 01:55
This is, unfortunately, true. WSL does not send out a notification that we can listen for when a new distribution is installed, so we have no way of knowing when to run an update.

@benhillis do you have any ideas what we could do here?

**Comment by DHowett** [comment] 2020-09-25 01:55
(Resolving this as "sadly by design" today.)

**Closed by DHowett** 2020-09-25 01:55 UTC
Labels: Needs-Tag-Fix, Needs-Triage
