### ISSUE TITLE
Deleting Profile Causes Odd Blue Bar Animation on Settings Page

### ISSUE THREAD

**Issue by krixano** [microsoft/terminal#10631] opened 2021-07-12 14:36 UTC
### Windows Terminal version (or Windows build number)

1.8.1521.0

### Steps to reproduce

I've found a separate problem with that blue bar animation when deleting a profile.

When you select the last profile and delete it, the blue bar jumps farther up than it needs to be and animates down toward the menu item that was before the deleted profile.

I have since found out that this only happens when deleting the *last* profile.

### Expected Behavior

The blue bar should probably just instantly jump to the previous menu item.

### Actual Behavior

When you click to delete a profile, the blue bar jumps far above where it's supposed to be, and then starts animating downward.

https://user-images.githubusercontent.com/4098042/125306232-a6025380-e2f4-11eb-9e7f-5348d7d65ce6.mp4

**Comment by Don-Vito** [comment] 2021-08-13 05:25
Cannot reproduce this behavior in the latest build. Wondering if it is resolved or there is some missing part of the setup:
![OddBlueBar](https://user-images.githubusercontent.com/4639110/129308961-ff345632-7ae1-4efa-8174-0672391196c4.gif)

**Comment by krixano** [comment] 2021-08-14 00:50
Looks like it's *almost* fixed in the latest stable version (1.9.1942.0). But it's still subtly there: 

https://user-images.githubusercontent.com/4098042/129429650-6db3d8f5-6e4b-485c-86bc-c30deeb25125.mp4

**Comment by zadjii-msft** [comment] 2022-01-21 15:27
Looks like this is fixed with Controlsv2, which should be landing in #11720

**Closed** 2022-01-28 00:40 UTC
Labels: Help Wanted, Issue-Bug, Area-User Interface, Product-Terminal, In-PR, Priority-3, Area-Settings UI
