### ISSUE TITLE
Windows Terminal is stuck -- can not view the shell , can not be closed, can not be moved

### ISSUE THREAD

**Issue by tlsalex** [microsoft/terminal#3221] opened 2019-10-16 11:55 UTC
# Environment

```none
Win32NT             10.0.18362.0 Microsoft Windows NT 10.0.18362.0
Windows Terminal (Preview)
Version: 0.5.2762.0
```

# Steps to reproduce

enable openssh client in windows. Start Windows Terminal, it will start the default shell (powershell) , use ssh client connect to a remote ssh server, e.g ssh root@myhost .
wait for the ssh connection until it is timeout (let's say no keep alive package is sent by server or client)

# Expected behavior

if the ssh connection is timeout , I can see what happen within the shell, e.g 
[root@myhost ~]# Connection to myhost closed by remote host.
Connection to myhost closed.

# Actual behavior
After the ssh connection is timeout. The whole windows terminal is stuck, you can not move windows terminal , you can not see what's happen within the shell , but you just can see the background of you desktop. I event can not close windows terminal. I have to click the + button to start a new shell, then I can get back the control fo windows terminal.

![stuck](https://user-images.githubusercontent.com/36788337/66916799-93d78080-f04e-11e9-8267-d898ba8feb8f.PNG)

**Comment by skycommand** [comment] 2019-10-20 13:59
Same issue as #3261 and #3253. Should be merged, IMHO.

**Comment by DHowett-MSFT** [comment] 2019-10-21 19:42
Yeah, looks like a /dupe of #2733. Thanks for finding it!

**Closed by DHowett-MSFT** 2019-10-21 19:42 UTC
Labels: Needs-Tag-Fix, Needs-Triage
