### ISSUE TITLE
Emacs M-S-RET (Alt-Shift-Enter) key not working inside the terminal

### ISSUE THREAD

**Issue by jiucenglou** [microsoft/terminal#9080] opened 2021-02-09 04:07 UTC
# Environment

```none
Windows build number: [Version 10.0.19042.789]
Windows Terminal version (if applicable): 1.5.10271.0

Any other software?
Ubuntu-18.04
emacs-nox inside Ubuntu-18.04
```

# Steps to reproduce

run emacs blank.org -q
press `<Alt>-<Shift>-<Enter>` 
press `<F1>` k  `<Alt>-<Shift>-<Enter>` 

# Expected behavior

press `<Alt>-<Shift>-<Enter>`  should fills `* TODO` in the Emacs window
press `<F1>` k  `<Alt>-<Shift>-<Enter>`  should shows info about `<M-S-RET>` in the Emacs buffer

# Actual behavior

press `<Alt>-<Shift>-<Enter>`  fills `* ` in the Emacs window
press `<F1>` k  `<Alt>-<Shift>-<Enter>`  shows info about `<M-RET>` in the Emacs buffer

# settings.json
```
        // 2021/1-28: for Emacs
        // { "command": {"action": "copy", "singleLine": false }, "keys": "ctrl+c" },
        // { "command": "paste", "keys": "ctrl+v" },
        { "command": "unbound", "keys": "alt+left" },
        { "command": "unbound", "keys": "alt+right" },
        { "command": "unbound", "keys": "alt+up" },
        { "command": "unbound", "keys": "alt+down" },
        { "command": "unbound", "keys": "alt+enter" },
```

**Comment by zadjii-msft** [comment] 2021-02-09 11:04
Curiously, it looks like `gnome-terminal` doesn't support M-S-Ret either. Is there a terminal you know that _does_ support that keybinding? In that terminal, could you run `showkey -a` and press <kbd>Alt+Shift+Enter</kbd> and share what's output? Should be something like
![image](https://user-images.githubusercontent.com/18356694/107354819-3e6d8100-6a94-11eb-8442-fe4341d3e877.png)

**Comment by jiucenglou** [comment] 2021-02-09 11:37
> Curiously, it looks like `gnome-terminal` doesn't support M-S-Ret either. Is there a terminal you know that _does_ support that keybinding? In that terminal, could you run `showkey -a` and press Alt+Shift+Enter and share what's output? Should be something like
> ![image](https://user-images.githubusercontent.com/18356694/107354819-3e6d8100-6a94-11eb-8442-fe4341d3e877.png)

I just tried and realized that not any one on my PC supports M-S-Ret.... :D

**Comment by zadjii-msft** [comment] 2021-02-09 11:40
Ah, so maybe this is just one of those keybindings that doesn't work in terminal at all then 🤔 There are a few other's like that - terminal input is just sometimes weird like that. 

Since this isn't something that's expected to work in other terminals, I'm just going to close this one as by design. Sound good?

**Closed by zadjii-msft** 2021-02-09 11:40 UTC
Labels: Area-Input, Needs-Attention, Needs-Tag-Fix, Needs-Triage, Product-Terminal
