### ISSUE TITLE
Windows/tabs created with "wt new-tab COMMAND" start with the title of the default Terminal profile, not the COMMAND name

### ISSUE THREAD

**Issue by metathinker** [microsoft/terminal#6776] opened 2020-07-03 17:20 UTC
### Environment

**Windows build number:** Windows 10 ver. 2004 build 19041.329
**Windows Terminal version (if applicable):** 1.1.1812.0

### Steps to reproduce

1. While Terminal is closed, delete or rename your `settings.json` file, causing Terminal to revert to the default settings under which the built-in Windows PowerShell profile for Terminal `{61c54bbd-c2c6-5271-96e7-009a87ff44bf}` is the default one.
1. Run this command: `wt.exe C:\Windows\System32\robocopy.exe`

### Expected behavior

The title of the Terminal tab created is "C:\Windows\System32\robocopy.exe" or similar.

### Actual behavior

The title of the Terminal tab created is "Windows PowerShell".
(If you watch Task Manager or another process listing, you can see that no PowerShell process was ever started.)

**Comment by DHowett** [comment] 2020-07-10 00:49
So, this one is weird... I'm not sure how we should handle it. I'm not certain setting the commandline to be the title is the right thing to do.

A profile is closer to a shell link than an unjacketed command. A console console host started from a LNK inherits the _stem name_ of the LNK file, not the commandline string stored inside it. However, there's no true provision for taking a LNK and "running a different command" with it. . . except `STARTF_TITLEISLINKNAME`. Spawning a console process with one commandline but another [profile equivalent] specified in its startup info results in the same behavior as reported here.

I'm inclined to call it by design. What do you think?

**Comment by metathinker** [comment] 2020-07-10 00:57
Those are all good points you've made. My point of view, though, is that I'm not specifying a profile name on the `wt` command line, I'm specifying a command to run. So the analogy between a Terminal profile and a console app shortcut/.lnk file is not something I think of at all. And if I look for the window I just created, I don't expect it to have the title of a shell or app I never actually launched, which is the case now since the profile name is being picked up. 

Hence, I would not be happy with a design of Terminal that incorporates the current behavior. We can certainly try to come up with something that we're both happy with, though.

**Comment by zadjii-msft** [comment] 2021-07-19 20:34
Okay, we think this is a good idea, especially in the context of defterm, #9458, #10669

**Comment by zadjii-msft** [comment] 2021-07-21 16:24
I'm moving this back out to "v2.0". We'll do this in tandem with the change for #10669, because doing that all at once is a good story we can sell. They don't really make sense one at a time.

**Comment by DHowett** [comment] 2021-08-23 19:42
This was fixed in #10998. Th
anks!

**Closed by DHowett** 2021-08-23 19:42 UTC
Labels: Issue-Bug, Product-Terminal, Priority-2, Area-Commandline, this-will-be-a-breaking-change

**Comment by DHowett** [comment] 2021-08-23 19:53
(We took the path of making the title match the first segment of the command, and are decoupling profile choice at the same time. We'll work on pulling icons and stuff out if necessary later. Changing the profile is a breaking change, the rest are new fun features.)
