### ISSUE TITLE
Windows Terminal doesn't show dynamic content when transparency is enabled

### ISSUE THREAD

**Issue by SehiiRohoza** [microsoft/terminal#14280] opened 2022-10-21 17:01 UTC
### Windows Terminal version

1.15.2875.0

### Steps to reproduce

1. Turn on transparency
2. Play video or dynamically updated log file in another window
3. Look on the dynamic content via transparent Widows Terminal and find that it's not updating accordingly

### Expected Behavior

Widows Terminal should allows me to see updated content from the background application when transparency is enabled. 

### Actual Behavior

Windows Terminal shows only static picture when transparency is enabled.

**Comment by DHowett** [comment] 2022-10-21 17:33
Two additional questions:

1. What version of Windows are you on? I see that you did not include it in the original issue.
2. What application is behind Terminal?

Some applications detect that there is a window in front of them and stop updating (or update more slowly.) This is by design for those applications, and Terminal cannot trick then into updating.

**Comment by SehiiRohoza** [comment] 2022-10-21 17:47
> Two additional questions:
> 
> 1. What version of Windows are you on? I see that you did not include it in the original issue.
> 2. What application is behind Terminal?
> 
> Some applications detect that there is a window in front of them and stop updating (or update more slowly.) This is by design for those applications, and Terminal cannot trick then into updating.

Please find more information below:
1. I'm using Windows 11 21H2
2. For example Google Chrome with a tab showing Google Cloud Platform running some build in Cloud Build or streaming Cloud Logging a ton of logs I'd like to see when doing something in Windows Terminal with GCP resources.

**Comment by DHowett** [comment] 2022-10-21 17:53
Thanks!

Somebody filed a similar bug in #14059 and found the "magic words" to configure Chrome to ignore occlusion. They also followed up with instructions for Firefox. Both of those fixed start here: https://github.com/microsoft/terminal/issues/14059#issuecomment-1255772563

I'm gonna call this a /duplicate of #14059, with fixed noted. 😄

**Closed by DHowett** 2022-10-21 17:53 UTC
Labels: Issue-Bug, Needs-Triage, Needs-Attention
