### ISSUE TITLE
Pasting "." (dots) result in ^[On in zsh shell

### ISSUE THREAD

**Issue by Ansuel** [microsoft/terminal#16725] opened 2024-02-16 14:44 UTC
### Windows Terminal version

1.20.10303.0

### Windows build number

10.0.26058.1000

### Steps to reproduce

1. Install Ubuntu 22.04.3 LTS from store
2. Open Ubuntu and setup (I used ansuel as username)
3. sudo apt install zsh
4. zsh
5. Enter 2 (Populate your zshrc with ...)
6. Copy a string with a dot (`"hello."`)
7. Paste the string in terminal
8. Notice the string `"hello^[On"`

### Expected Behavior

Text is correctly pasted
![image](https://github.com/microsoft/terminal/assets/20289090/fea1a429-1aec-48f6-a097-0470562b5fb2)

### Actual Behavior

Text is not correctly pasted
![image](https://github.com/microsoft/terminal/assets/20289090/a95f14d6-5a18-47b8-abf4-2f5a3c580ca7)

**Comment by j4james** [comment] 2024-02-16 21:14
This is essentially a duplicate of #16654.
For more details on what exactly is happening when you paste, see the discussion in #16713.

**Comment by Ansuel** [comment] 2024-02-16 23:21
@j4james thanks for pointing this out. Reading it it seems it will be fixed in later release so again thanks for the comments.

**Comment by zadjii-msft** [comment] 2024-02-19 12:07
/dup #16654

thanks!

**Closed by zadjii-msft** 2024-02-19 12:07 UTC
Labels: Issue-Bug, Needs-Triage
