### ISSUE TITLE
Terminal crashes in WSL2 when typing exit directly after a sudo statement in second tab

### ISSUE THREAD

**Issue by mwidmann** [microsoft/terminal#3829] opened 2019-12-04 06:07 UTC
# Environment

```none
Windows build number: Version 10.0.19033.1
Windows Terminal version (if applicable): 0.7.3291.0


Any other software?
Ubuntu 18.04.3 LTS running in WSL2
```

# Steps to reproduce

I have the Ubuntu installation in WSL2 set up as the default profile

1. open terminal (or have it running)
2. open a second tab
3. execute any command as sudo, e.g. `sudo hwclock -s` for synchronizing the clock
4. enter the sudo password
5. type `exit`

# Expected behavior

the tab closes, the other sessions stay open.

# Actual behavior

the terminal crashes.

[https://i.imgur.com/nbg76pn.gifv](https://i.imgur.com/nbg76pn.gifv)

**Comment by DHowett-MSFT** [comment] 2019-12-04 19:24
I believe this is the same as #3801 ...
but will you send us some /feedback

**Comment by mwidmann** [comment] 2019-12-05 07:31
I guess, the issue is the same as in #3801 Here's my feedback https://aka.ms/AA6r4za

**Comment by krisavi** [comment] 2019-12-05 16:22
> I guess, the issue is the same as in #3801 Here's my feedback https://aka.ms/AA6r4za

Linking to 3rd party feedback seems to be a bad practice as not everyone can read the response there:
![image](https://user-images.githubusercontent.com/1912568/70253549-b438d700-1783-11ea-9947-419a960b77f3.png)
That for example with a company account.

**Comment by DHowett-MSFT** [comment] 2019-12-05 16:26
@krisavi thanks for the info. This feedback workflow does suffice for our purposes as Microsoft, but it can be somewhat annoying for others :smile:

**Comment by DHowett-MSFT** [comment] 2019-12-05 20:48
Confirmed as a /dupe of #3801. Thanks for the feedback item!

**Closed by DHowett-MSFT** 2019-12-05 20:49 UTC
Labels: Needs-Attention, Needs-Tag-Fix, Needs-Triage
