### ISSUE TITLE
Allow command line(s) without specifying the executable

### ISSUE THREAD

**Issue by rubinusp** [microsoft/terminal#7289] opened 2020-08-14 05:12 UTC
Right now, the `commandline` setting of Profile is only for executable. It has been a trick to add command lines as arguments to the executable. But it adds higher complexity to the whole statement. For those profiles that have source, it is nice if `commandline` functions as the launching command lines without specifying the executable. It is a useful feature to automatically set up and open a docker environment in the terminal, or switching as admin.  

**Example**
{
                "guid": "{2c4de342-38b7-51cf-b940-2309a097f518}",
                "hidden": false,
                "name": "Ubuntu",
                "source": "Windows.Terminal.Wsl",
		"colorScheme": "UbuntuLegit",
                "commandline": "sudo -s"
}

This will automatically launch the shell as the root user.

**Comment by DHowett** [comment] 2020-08-18 23:13
Thanks for the request! This is largely a /duplicate of #5528/#5571 so I'd like to consolidate discussion there.

**Closed by DHowett** 2020-08-18 23:13 UTC
Labels: Issue-Feature, Needs-Tag-Fix, Needs-Triage
