### ISSUE TITLE
IME mode changed at startup in Google Japanese Input

### ISSUE THREAD

**Issue by kzrnm** [microsoft/terminal#14407] opened 2022-11-18 13:53 UTC
### Windows Terminal version

1.15.2874.0

### Windows build number

10.0.19045.0

### Other Software

Google 日本語入力 (2.28.4650.0)

### Steps to reproduce

Start Windows Terminal with Japanese IME.

### Expected Behavior

Google IME selects `直接入力`(Direct input) mode.
MS IME  selects `半角英数字/直接入力`(Direct input) mode.

### Actual Behavior

Google IME selects `半角英数`(English input with IME) mode.
MS IME  selects `半角英数字/直接入力`(Direct input) mode.

**Comment by zadjii-msft** [comment] 2022-11-18 15:58
Hmm. linking threads:

* #13398 - I thought we fixed this one...
* #13678
* #13681
* #13805

**Comment by weiqi-chen** [comment] 2022-11-20 16:07
Not only Japanese, but also Chinese.
Microsoft never test before releasing its software...

![issue](https://user-images.githubusercontent.com/6562920/202912680-76f246a9-9c2b-4d1b-9f88-3e575cc8ad5c.gif)

**Comment by yonta** [comment] 2022-11-22 03:18
Same issue is reported at Gborad Help.
https://support.google.com/gboard/thread/180438722/windows-terminal-%E8%B5%B7%E5%8B%95%E6%99%82%E3%81%AE-%E5%85%A5%E5%8A%9B%E6%96%B9%E6%B3%95-%E3%81%AB%E9%96%A2%E3%81%99%E3%82%8B%E4%B8%8D%E5%85%B7%E5%90%88?hl=ja

Expert says that Microsft IME has one state "半角英数字/直接入力" (direct input) but Google Japanese Input and Legacy Microsoft IME has "半角英数" (English input) and "直接入力" (direct input) as separated state.

> 補足情報として
現行の Microsoft IME は機能が少なく「半角英数字/直接入力」が一つの状態となっています。
Google 日本語入力や、以前のバージョンの Microsoft IME においては、「半角英数」「直接入力」が別の状態として存在しています。

I think Windows Terminal incorrectly specifies input method at startup.

**Comment by cumet04** [comment] 2022-12-26 03:46
I have same issue, and [v1.14.186](https://github.com/microsoft/terminal/releases/tag/v1.14.1861.0) reproduces the issue but  [v1.13.1143](https://github.com/microsoft/terminal/releases/tag/v1.13.11431.0) doesn't.

**Comment by carlos-zamora** [comment] 2023-01-25 23:03
Marking this as a feature. We've had reports in the past of users wanting this kind of behavior. Sounds like the right path forward is to make this a configurable setting.

**Comment by ikeyan** [comment] 2023-06-07 06:01
Original issue #12731 says:

> Personally I just want Windows Terminal to have English input mode on startup like what conhost does, so I can type in commands immediately.

So the author expected that users could immediately start typing commands at startup, but this is hampered by this issue.

**Comment by weiqi-chen** [comment] 2023-06-07 07:02
> Original issue #12731 says:
> 
> > Personally I just want Windows Terminal to have English input mode on startup like what conhost does, so I can type in commands immediately.
> 
> So the author expected that users could immediately start typing commands at startup, but this is hampered by this issue.

I add two keyboard layout, one is english, another one is chinese. If I need to input english / chinese, I use `Alt + Shift` to switch the keyboard。 When I fell like to use Chinese keyboard to type english and chinese, I would use `Shift` key to enable/disable Chinese Pinyin. I don't like it that Windows Terminal do it(switch to english) every single time after I pressing Enter key, even I don't need to switch to english.

**Comment by siketyan** [comment] 2023-06-08 08:48
I now think this can be considered as Google IME's issue.
In #13028, changing CoreTextInputScope once Windows Terminal is loaded.
The InputScope does not mean IME should be turned on or off on the text input, so the decision is delegated to IMEs.

In Microsoft IME, CoreTextInputScope::AlphanumericHalfWidth is mapped to Direct Input mode, so it is okay for us.

But in Google IME or Mozc, the scope is mapped to Alphanumeric mode with IME on, causing this issue. It is documented in Mozc repository:
https://github.com/google/mozc/blob/master/docs/design_doc/input_scope.md

Quote:

| InputScope | Expected Input Mode |
|:-----------|:--------------------|
| `IS_URL`, `IS_EMAIL_USERNAME`, `IS_EMAIL_SMTPEMAILADDRESS`, `IS_DIGITS`, `IS_NUMBER`, `IS_PASSWORD`, `IS_TELEPHONE_FULLTELEPHONENUMBER`, `IS_TELEPHONE_COUNTRYCODE`, `IS_TELEPHONE_AREACODE`, `IS_TELEPHONE_LOCALNUMBER`, `IS_TIME_FULLTIME`, `IS_TIME_HOUR`, `IS_TIME_MINORSEC` | Direct Mode (IME Off) |
| `IS_ALPHANUMERIC_HALFWIDTH` | Halfwidth Alphanumeric Mode (IME On) |

As described above, Google IME and Mozc consider IME should be turned on in text inputs with AlphanumericHalfWidth scope.

I am not familier with UWP, but isn't there a way to turn IME off without depending on the InputScope?

**Comment by gexgd0419** [comment] 2024-02-20 01:56
I tested the built-in CJK IMEs in Windows XP, 7, and 11.

## Chinese IME

Windows XP's version: "IME off" and "IME on, but English mode" are different states. When the IME is on, you can switch between Chinese/English with Shift keys, but when the IME is off you can't. Other than that, those two modes are similar: both modes just pass the English key input without interception, similar to "direct input".

Windows 7's version: those two modes are merged. "Turning off IME" is interpreted as "switching to English mode". And when the IME is in English mode, it will report that it is off.

Windows 11's version: "Turning off IME" is interpreted as "switching to English mode". However, the IME always reports that it is on.

Some third-party Chinese IMEs follow the XP's behavior. If they are turned off, they behave as if they are "disabled": the IME bar is hidden, and you cannot use Shift keys or other hot keys to bring them back, until you switch to another IME then switch back.

## Japanese IME

Windows XP's version: "IME off" and "IME on, but half-width alphanumeric mode" are different states. "IME off" is also known as the "direct input" mode. In half-width alphanumeric mode, English input is not converted, but is still intercepted.

Windows 7/11's version: those two modes are merged. There's no "direct input" mode anymore, only "half-width alphanumeric" mode. When in this mode, the IME reports that it is off.

## Korean IME

Windows XP's version: reports that it is on or off depending on whether it's in Korean mode, but you cannot turn it on or off. You have to change the conversion mode.

Windows 7's version: reports that it is on or off depending on whether it's in Korean mode. Turning it on or off appears to change its state, but in fact the mode is not changed.

Windows 11's version: reports that it is on or off depending on whether it's in Korean mode. You can turn the IME on or off to switch between Korean/English mode. (But sometimes it doesn't work)

## Conclusion

If the user is using Chinese or Korean IME, the [conversion mode](https://learn.microsoft.com/en-us/windows/win32/intl/ime-conversion-mode-values) should be changed. This can be done via [ImmSetConversionStatus](https://learn.microsoft.com/en-us/windows/win32/api/imm/nf-imm-immsetconversionstatus), or sending a [WM_IME_CONTROL](https://learn.microsoft.com/en-us/windows/win32/intl/wm-ime-control) with wParam = `IMC_SETCONVERSIONMODE (0x2)` to the IME window returned from [ImmGetDefaultIMEWnd](https://learn.microsoft.com/en-us/windows/win32/api/imm/nf-imm-immgetdefaultimewnd).

If the user is using Japanese IME, the IME should be turned off. This can be done via [ImmSetOpenStatus](https://learn.microsoft.com/en-us/windows/win32/api/imm/nf-imm-immsetopenstatus), or sending a WM_IME_CONTROL with wParam = `IMC_SETOPENSTATUS (0x6)` to the IME window.

It seems that there isn't a corresponding InputScope value for the "IME off" state, though.

**Comment by yukawa** [comment] 2024-03-13 20:49
A Google Japanese Input / Mozc maintainer here.

If you are/were using Google Japanese Input for Windows and had been affected by this particular issue with Google Japanese Input, it should no longer happen with Google Japanese Input version `2.29.5268.100` or later, which contains the following commit.

 * https://github.com/google/mozc/commit/58a3c22383f6d6f987a7a28a4b6a7fe1d9ac992e

As far as Google Japanese Input is concerned, I believe no further changes in the Windows Terminal side is needed.

Just for your reference, here are currently released versions as of writing.
 * Google Japanese Input for Windows stable channel: `2.29.5374.100`
 * Google Japanese Input for Windows dev channel: `2.29.5370.0`

**Comment by PseudoResonance** [comment] 2024-03-13 23:44
The latest update seems to have fixed the issue for me, however the "About Google Japanese Input" page is blank, so I'm not sure what version I'm on... I was on 2.28 previously which I downloaded about 2 weeks ago. Thank you for the heads up!
![image](https://github.com/microsoft/terminal/assets/7216500/889a4e0d-2056-40fb-a4f2-f9fabd084534)

**Comment by vyv03354** [comment] 2024-03-13 23:58
> The latest update seems to have fixed the issue for me, however the "About Google Japanese Input" page is blank, so I'm not sure what version I'm on...

Me too, it's probably because your (and my) system is using Dark Mode. The dialog uses system-default text color (white in Dark Mode) with custom background, I guess.

**Comment by vyv03354** [comment] 2024-03-14 00:00
You can verify the version by converting the word "ばーじょん" on Google Japanese Input.

**Comment by yukawa** [comment] 2024-03-14 06:25
> The latest update seems to have fixed the issue for me, however the "About Google Japanese Input" page is blank, so I'm not sure what version I'm on... (Edit: Using the method below, I see it's 2.29.5370) I was on 2.28 previously which I downloaded about 2 weeks ago. Thank you for the heads up! ![image](https://private-user-images.githubusercontent.com/7216500/312651280-889a4e0d-2056-40fb-a4f2-f9fabd084534.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzOTc3MDEsIm5iZiI6MTcxMDM5NzQwMSwicGF0aCI6Ii83MjE2NTAwLzMxMjY1MTI4MC04ODlhNGUwZC0yMDU2LTQwZmItYTRmMi1mOWZhYmQwODQ1MzQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMxNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMTRUMDYyMzIxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTllYmQxNDcyMDEyN2JmMGNkNjA4MGY5M2YxYWE0YmNiYzJkNzM4NDVjY2U1NDA4ODE5YmFlNjdjZDY0ZDA3YSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.WCcU5jn5w0N5qZP_GvdF5hbBXXgEeYWfjQ3R_T2OI1I)

Sorry about the trouble. I've filed the following issue to keep track of the above issue.
* https://github.com/google/mozc/issues/897

Thanks!

**Closed** 2024-04-18 18:18 UTC
Labels: Issue-Feature, Help Wanted, Product-Terminal, Needs-Tag-Fix, In-PR, Area-i18n

**Comment by lhecker** [comment] 2024-04-18 21:24
We just published a major update to our IME implementation in the nightly Canary branch. It was rewritten from the ground up and has tons of improvements! If you're interested in trying it out, you can get it here: https://aka.ms/terminal-canary-installer
If you already have the Canary build installed, you can use this link to force an update.

If you encounter any issues or have any suggestions, or if you simply like/dislike the changes, please let us know! Thank you for bearing with us. 😊
