### ISSUE TITLE
Characters overlap sometimes with colored characters

### ISSUE THREAD

**Issue by palapapa** [microsoft/terminal#16078] opened 2023-10-01 11:13 UTC
### Windows Terminal version

1.17.11461.0

### Windows build number

19045.3448

### Other Software

WSL 2

### Steps to reproduce

This bug happens quite randomly, but I have noticed that it happens the most when there is colored text. The below screenshot is one example. You can see the colon after my username and the last dollar sign overlap with other characters. The font used is Monocraft, but this happens with almost any font, including the built-in ones.
![圖片](https://github.com/microsoft/terminal/assets/61058728/d4fe5815-b87e-41ca-aa68-8c217fd2a53d)
The prompt string is `${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ `
Steps to reproduce:
1. Login to WSL.
2. `cd` to a relatively long path while having a colored prompt string. The longer the path, the more obvious the overlapping is.
3. Observe that some characters overlap with other characters.

Note that this doesn't only happen to prompt strings. I've also noticed this happening, for example, when installing npm packages when the output has colored text. Also, note that `echo`ing that prompt string with colors directly doesn't cause this bug.

### Expected Behavior

The characters don't overlap.

### Actual Behavior

The characters overlap.

**Comment by lhecker** [comment] 2023-10-01 15:58
If you update Windows Terminal to 1.18, you can open the settings dialog (Ctrl+,) and navigate to the Rendering section on the left. There should be a toggle labeled with "AtlasEngine". If you enable it and restart the application it should be fixed. Let me know if that worked for you!

(AtlasEngine will be the default text renderer in a future version.)

**Comment by palapapa** [comment] 2023-10-01 16:33
Downloaded 1.18.2681.0 and it still looks the same.

**Comment by lhecker** [comment] 2023-10-01 16:38
Hmm I didn't quite expect that… What's your display scale, font family and font size? I'll try to reproduce it locally.

**Comment by palapapa** [comment] 2023-10-01 16:46
I am not sure what you meant by display scale so here's the whole settings.json:
```json
{
    "$help": "https://aka.ms/terminal-documentation",
    "$schema": "https://aka.ms/terminal-profiles-schema",
    "actions": 
    [
        {
            "command": "paste",
            "keys": "ctrl+v"
        },
        {
            "command": 
            {
                "action": "copy",
                "singleLine": false
            },
            "keys": "ctrl+c"
        },
        {
            "command": "find",
            "keys": "ctrl+shift+f"
        },
        {
            "command": 
            {
                "action": "splitPane",
                "split": "auto",
                "splitMode": "duplicate"
            },
            "keys": "alt+shift+d"
        }
    ],
    "alwaysShowTabs": true,
    "autoHideWindow": false,
    "copyFormatting": "none",
    "copyOnSelect": false,
    "defaultProfile": "{61c54bbd-c2c6-5271-96e7-009a87ff44bf}",
    "experimental.rendering.forceFullRepaint": false,
    "experimental.rendering.software": false,
    "firstWindowPreference": "defaultProfile",
    "focusFollowMouse": true,
    "language": "en-US",
    "launchMode": "maximized",
    "newTabMenu": 
    [
        {
            "type": "remainingProfiles"
        }
    ],
    "profiles": 
    {
        "defaults": 
        {
            "adjustIndistinguishableColors": "indexed",
            "antialiasingMode": "grayscale",
            "backgroundImage": null,
            "bellStyle": "none",
            "colorScheme": "One Half Dark",
            "cursorShape": "bar",
            "elevate": false,
            "experimental.retroTerminalEffect": false,
            "font": 
            {
                "face": "Monocraft",
                "size": 11.0,
                "weight": "normal"
            },
            "intenseTextStyle": "all",
            "opacity": 100,
            "padding": "8",
            "useAcrylic": true,
            "useAtlasEngine": true
        },
        "list": 
        [
            {
                "commandline": "%SystemRoot%\\System32\\WindowsPowerShell\\v1.0\\powershell.exe -nologo",
                "guid": "{61c54bbd-c2c6-5271-96e7-009a87ff44bf}",
                "hidden": false,
                "name": "Windows PowerShell"
            },
            {
                "commandline": "%SystemRoot%\\System32\\cmd.exe",
                "guid": "{0caa0dad-35be-5f56-a8ff-afceeeaa6101}",
                "hidden": false,
                "name": "Command Prompt"
            },
            {
                "guid": "{b453ae62-4e3d-5e58-b989-0a998ec441b8}",
                "hidden": false,
                "name": "Azure Cloud Shell",
                "source": "Windows.Terminal.Azure"
            },
            {
                "guid": "{2c4de342-38b7-51cf-b940-2309a097f518}",
                "hidden": true,
                "name": "Ubuntu",
                "source": "Windows.Terminal.Wsl"
            },
            {
                "guid": "{51855cb2-8cce-5362-8f54-464b92b32386}",
                "hidden": false,
                "name": "Ubuntu",
                "source": "CanonicalGroupLimited.Ubuntu_79rhkp1fndgsc"
            },
            {
                "guid": "{2ece5bfe-50ed-5f3a-ab87-5cd4baafed2b}",
                "hidden": false,
                "name": "Git Bash",
                "source": "Git"
            }
        ]
    },
    "schemes": 
    [
        {
            "background": "#0E1019",
            "black": "#232323",
            "blue": "#008DF8",
            "brightBlack": "#444444",
            "brightBlue": "#0092FF",
            "brightCyan": "#67FFF0",
            "brightGreen": "#ABE15B",
            "brightPurple": "#9A5FEB",
            "brightRed": "#FF2740",
            "brightWhite": "#FFFFFF",
            "brightYellow": "#FFD242",
            "cursorColor": "#FF0018",
            "cyan": "#00D8EB",
            "foreground": "#FFFAF4",
            "green": "#8CE10B",
            "name": "Argonaut",
            "purple": "#6D43A6",
            "red": "#FF000F",
            "selectionBackground": "#002A3B",
            "white": "#FFFFFF",
            "yellow": "#FFB900"
        },
        {
            "background": "#101116",
            "black": "#101116",
            "blue": "#00B0FF",
            "brightBlack": "#686868",
            "brightBlue": "#6871FF",
            "brightCyan": "#60FDFF",
            "brightGreen": "#5FFA68",
            "brightPurple": "#D682EC",
            "brightRed": "#FF6E67",
            "brightWhite": "#FFFFFF",
            "brightYellow": "#FFFC67",
            "cursorColor": "#76FF9F",
            "cyan": "#76C1FF",
            "foreground": "#00A2FF",
            "green": "#00FF9C",
            "name": "Blue Matrix",
            "purple": "#D57BFF",
            "red": "#FF5680",
            "selectionBackground": "#C1DEFF",
            "white": "#C7C7C7",
            "yellow": "#FFFC58"
        },
        {
            "background": "#0C0C0C",
            "black": "#0C0C0C",
            "blue": "#0037DA",
            "brightBlack": "#767676",
            "brightBlue": "#3B78FF",
            "brightCyan": "#61D6D6",
            "brightGreen": "#16C60C",
            "brightPurple": "#B4009E",
            "brightRed": "#E74856",
            "brightWhite": "#F2F2F2",
            "brightYellow": "#F9F1A5",
            "cursorColor": "#FFFFFF",
            "cyan": "#3A96DD",
            "foreground": "#CCCCCC",
            "green": "#13A10E",
            "name": "Campbell",
            "purple": "#881798",
            "red": "#C50F1F",
            "selectionBackground": "#FFFFFF",
            "white": "#CCCCCC",
            "yellow": "#C19C00"
        },
        {
            "background": "#012456",
            "black": "#0C0C0C",
            "blue": "#0037DA",
            "brightBlack": "#767676",
            "brightBlue": "#3B78FF",
            "brightCyan": "#61D6D6",
            "brightGreen": "#16C60C",
            "brightPurple": "#B4009E",
            "brightRed": "#E74856",
            "brightWhite": "#F2F2F2",
            "brightYellow": "#F9F1A5",
            "cursorColor": "#FFFFFF",
            "cyan": "#3A96DD",
            "foreground": "#CCCCCC",
            "green": "#13A10E",
            "name": "Campbell Powershell",
            "purple": "#881798",
            "red": "#C50F1F",
            "selectionBackground": "#FFFFFF",
            "white": "#CCCCCC",
            "yellow": "#C19C00"
        },
        {
            "background": "#282C34",
            "black": "#282C34",
            "blue": "#61AFEF",
            "brightBlack": "#5A6374",
            "brightBlue": "#61AFEF",
            "brightCyan": "#56B6C2",
            "brightGreen": "#98C379",
            "brightPurple": "#C678DD",
            "brightRed": "#E06C75",
            "brightWhite": "#DCDFE4",
            "brightYellow": "#E5C07B",
            "cursorColor": "#FFFFFF",
            "cyan": "#56B6C2",
            "foreground": "#DCDFE4",
            "green": "#98C379",
            "name": "One Half Dark",
            "purple": "#C678DD",
            "red": "#E06C75",
            "selectionBackground": "#FFFFFF",
            "white": "#DCDFE4",
            "yellow": "#E5C07B"
        },
        {
            "background": "#FAFAFA",
            "black": "#383A42",
            "blue": "#0184BC",
            "brightBlack": "#4F525D",
            "brightBlue": "#61AFEF",
            "brightCyan": "#56B5C1",
            "brightGreen": "#98C379",
            "brightPurple": "#C577DD",
            "brightRed": "#DF6C75",
            "brightWhite": "#FFFFFF",
            "brightYellow": "#E4C07A",
            "cursorColor": "#4F525D",
            "cyan": "#0997B3",
            "foreground": "#383A42",
            "green": "#50A14F",
            "name": "One Half Light",
            "purple": "#A626A4",
            "red": "#E45649",
            "selectionBackground": "#FFFFFF",
            "white": "#FAFAFA",
            "yellow": "#C18301"
        },
        {
            "background": "#002B36",
            "black": "#002B36",
            "blue": "#268BD2",
            "brightBlack": "#073642",
            "brightBlue": "#839496",
            "brightCyan": "#93A1A1",
            "brightGreen": "#586E75",
            "brightPurple": "#6C71C4",
            "brightRed": "#CB4B16",
            "brightWhite": "#FDF6E3",
            "brightYellow": "#657B83",
            "cursorColor": "#FFFFFF",
            "cyan": "#2AA198",
            "foreground": "#839496",
            "green": "#859900",
            "name": "Solarized Dark",
            "purple": "#D33682",
            "red": "#DC322F",
            "selectionBackground": "#FFFFFF",
            "white": "#EEE8D5",
            "yellow": "#B58900"
        },
        {
            "background": "#FDF6E3",
            "black": "#002B36",
            "blue": "#268BD2",
            "brightBlack": "#073642",
            "brightBlue": "#839496",
            "brightCyan": "#93A1A1",
            "brightGreen": "#586E75",
            "brightPurple": "#6C71C4",
            "brightRed": "#CB4B16",
            "brightWhite": "#FDF6E3",
            "brightYellow": "#657B83",
            "cursorColor": "#002B36",
            "cyan": "#2AA198",
            "foreground": "#657B83",
            "green": "#859900",
            "name": "Solarized Light",
            "purple": "#D33682",
            "red": "#DC322F",
            "selectionBackground": "#FFFFFF",
            "white": "#EEE8D5",
            "yellow": "#B58900"
        },
        {
            "background": "#000000",
            "black": "#000000",
            "blue": "#3465A4",
            "brightBlack": "#555753",
            "brightBlue": "#729FCF",
            "brightCyan": "#34E2E2",
            "brightGreen": "#8AE234",
            "brightPurple": "#AD7FA8",
            "brightRed": "#EF2929",
            "brightWhite": "#EEEEEC",
            "brightYellow": "#FCE94F",
            "cursorColor": "#FFFFFF",
            "cyan": "#06989A",
            "foreground": "#D3D7CF",
            "green": "#4E9A06",
            "name": "Tango Dark",
            "purple": "#75507B",
            "red": "#CC0000",
            "selectionBackground": "#FFFFFF",
            "white": "#D3D7CF",
            "yellow": "#C4A000"
        },
        {
            "background": "#FFFFFF",
            "black": "#000000",
            "blue": "#3465A4",
            "brightBlack": "#555753",
            "brightBlue": "#729FCF",
            "brightCyan": "#34E2E2",
            "brightGreen": "#8AE234",
            "brightPurple": "#AD7FA8",
            "brightRed": "#EF2929",
            "brightWhite": "#EEEEEC",
            "brightYellow": "#FCE94F",
            "cursorColor": "#000000",
            "cyan": "#06989A",
            "foreground": "#555753",
            "green": "#4E9A06",
            "name": "Tango Light",
            "purple": "#75507B",
            "red": "#CC0000",
            "selectionBackground": "#FFFFFF",
            "white": "#D3D7CF",
            "yellow": "#C4A000"
        },
        {
            "background": "#300A24",
            "black": "#171421",
            "blue": "#0037DA",
            "brightBlack": "#767676",
            "brightBlue": "#08458F",
            "brightCyan": "#2C9FB3",
            "brightGreen": "#26A269",
            "brightPurple": "#A347BA",
            "brightRed": "#C01C28",
            "brightWhite": "#F2F2F2",
            "brightYellow": "#A2734C",
            "cursorColor": "#FFFFFF",
            "cyan": "#3A96DD",
            "foreground": "#FFFFFF",
            "green": "#26A269",
            "name": "Ubuntu-ColorScheme",
            "purple": "#881798",
            "red": "#C21A23",
            "selectionBackground": "#FFFFFF",
            "white": "#CCCCCC",
            "yellow": "#A2734C"
        },
        {
            "background": "#000000",
            "black": "#000000",
            "blue": "#000080",
            "brightBlack": "#808080",
            "brightBlue": "#0000FF",
            "brightCyan": "#00FFFF",
            "brightGreen": "#00FF00",
            "brightPurple": "#FF00FF",
            "brightRed": "#FF0000",
            "brightWhite": "#FFFFFF",
            "brightYellow": "#FFFF00",
            "cursorColor": "#FFFFFF",
            "cyan": "#008080",
            "foreground": "#C0C0C0",
            "green": "#008000",
            "name": "Vintage",
            "purple": "#800080",
            "red": "#800000",
            "selectionBackground": "#FFFFFF",
            "white": "#C0C0C0",
            "yellow": "#808000"
        },
        {
            "background": "#010C18",
            "black": "#0B3B61",
            "blue": "#1376F9",
            "brightBlack": "#63686D",
            "brightBlue": "#388EFF",
            "brightCyan": "#FF6AD7",
            "brightGreen": "#74FFD8",
            "brightPurple": "#AE81FF",
            "brightRed": "#FF54B0",
            "brightWhite": "#60FBBF",
            "brightYellow": "#FCF5AE",
            "cursorColor": "#38FF9D",
            "cyan": "#FF5ED4",
            "foreground": "#ECDEF4",
            "green": "#52FFD0",
            "name": "coolnight",
            "purple": "#C792EA",
            "red": "#FF3A3A",
            "selectionBackground": "#38FF9C",
            "white": "#16FDA2",
            "yellow": "#FFF383"
        }
    ],
    "showTabsInTitlebar": true,
    "showTerminalTitleInTitlebar": false,
    "tabWidthMode": "equal",
    "theme": "dark",
    "themes": [],
    "useAcrylicInTabRow": false,
    "windowingBehavior": "useAnyExisting"
}
```

**Comment by palapapa** [comment] 2023-10-04 05:21
I noticed that this bug doesn't occur on my laptop. Maybe it's because my laptop screen is in 1080p while my desktop's screen is in 4K.

**Comment by lhecker** [comment] 2023-10-04 10:56
The display scale can be found in the "Settings" app under System > Display:
![image](https://github.com/microsoft/terminal/assets/2256941/9f7bf92e-f25b-46a9-b8e3-90ae991bd94b)

Going by your settings file and the screenshot you shared above, I figured you're using 100% scale. To reproduce your screenshot above, I've turned your prompt into a printf:
```bash
printf "\n\033[01;32mpalapapa@palapapa\033[00m:\033[01;34m/mnt/d/Desktop/Assembly/Hw\033[00m$\n\n"
```

With AtlasEngine disabled, it reproduces your screenshot almost perfectly:
![image](https://github.com/microsoft/terminal/assets/2256941/4efee55a-7c34-4714-bac0-f8767a934792)

(There are some subtle differences because you might not yet be using Monocraft v3 that was released recently, or because our ClearType settings differ. Those also affect grayscale rendering.)

As I already suspected, the issue is fixed if AtlasEngine is enabled:
![image](https://github.com/microsoft/terminal/assets/2256941/c6ccef06-0d1c-4941-acfa-efa03e52b5e7)

If you don't like the glyph distance you can install Windows Terminal Preview. On first launch it'll copy our existing settings from non-Preview. Open the settings file (Ctrl+Shift+,) and merge this in:
```json
{
    "profiles":
    {
        "defaults":
        {
            "font":
            {
                "cellWidth": "8pt"
            }
        }
    }
}
```

The `cellWidth` field supports the CSS specifiers `px`, `pt`, `%` and `ch`. There's also a corresponding `cellHeight` field.

Let me know if that doesn't work for you.

**Closed by lhecker** 2023-10-04 10:56 UTC
Labels: Issue-Bug, Needs-Triage, Needs-Attention

**Comment by palapapa** [comment] 2023-10-04 15:49
Enabling AtlasEngine does fix it. It is just that you need to restart the terminal for it to take effect, but the settings page doesn't tell you about that. I didn't restart so I thought it didn't work.

Also for some reason installing the newer Monocraft versions causes severe aliasing(not sure whether that's what you should call it) where some strokes are thinner and some others are thicker, as shown in your screenshot. Windows Terminal also doesn't think that the newer versions of Monocraft are monospaced fonts. I have always been using Monocraft 1.4 and Windows Terminal correctly recognizes it as a monospaced font. However, the same aliasing effect is also visible in VSCode, for example, so I think it might be an issue with the font itself.
