### ISSUE TITLE
Bug: For multi-byte characters like Chinese, some output encodings can cause incorrect text rendering.

### ISSUE THREAD

**Issue by abgox** [microsoft/terminal#18242] opened 2024-11-24 03:51 UTC
### Windows Terminal version

1.21.3231.0

### Windows build number

10.0.22635.0

### Other Software

PowerShell

### Steps to reproduce

- I cleared the contents of `$profile`，and added a test function in `$profile`.

  ```powershell
  function test-render() {
      $text = @("你好你好你好", "😄😎🤔")

      $buffer = $Host.UI.RawUI.NewBufferCellArray($text, 'Cyan', 'Black')
      $Host.UI.RawUI.SetBufferContents($Host.UI.RawUI.CursorPosition, $buffer)

      $null = $host.UI.RawUI.ReadKey() # Suspend the process for easy observation
  }
  ```

- There are two text rendering issues here.

---

1. Emoji does not render properly in `Windows Terminal Preview`, but it works fine in ohter terminals like `Windows Terminal`,`Tabby`,`Hyper`.

> [!NOTE]
>
> I'm in China, so the encoding of `Windows Terminal (Preview)` is automatically changed to `GB2312`.
>
> But ohter terminals like `Tabby` and `Hyper` are using `UTF8` encoding.

![Image](https://github.com/user-attachments/assets/8aa000d0-216e-4450-a8a6-a6be38867732)

![Image](https://github.com/user-attachments/assets/02b73675-4cf7-4320-8525-6ad1cc8060c3)

---

2. When the output encoding is switched to `UTF8`, `Windows Terminal (Preview)` has unexpected behavior in rendering Chinese or other multi-byte characters, but it works fine in other terminals like `Tabby`,`Hyper`.

> [!NOTE]
>
> other terminals like `Tabby`,`Hyper` works fine because they always use `UTF8` encoding.

![Image](https://github.com/user-attachments/assets/e11089b3-f7c6-45e9-b256-c4a60e2ae3fe)

![Image](https://github.com/user-attachments/assets/f5dc9b50-1ca6-4832-995d-3dc4b86117e8)

- I switched to `UTF8` with this regional setting.

   ![Image](https://github.com/user-attachments/assets/525bf03c-2c2b-4ae4-b530-51507ca9e57c)

### Expected Behavior

1. Emoji can render properly in `Windows Terminal Preview`.
2. For multi-byte characters like Chinese, render it correctly and should not add spaces by mistake.

### Actual Behavior

1. Emoji can't render properly in `Windows Terminal Preview`.
2. For multi-byte characters like Chinese, spaces are added incorrectly.

**Comment by lhecker** [comment] 2024-11-26 13:59
The `BufferCell` type that you're using was never specified whether it supports "surrogate pairs" or not (which is what your 3 emojis use). The truth is, that it never actually supported them properly, it simply worked for `SetBufferContents` coincidentally, because there was no input validation. You could write _anything_ into the text buffer, even completely bogus codepoints and it would just work. Now we validate all inputs and so this doesn't work anymore. `BufferCell` now only supports UCS2, which is all it ever properly supported.

The only APIs that support writing Unicode to the console are `WriteConsoleW`, as well as `WriteFile` and `WriteConsoleA` with `SetConsoleOutputCP(CP_UTF8)`.

You can read more about our breaking changes here and the reason for doing them: https://github.com/microsoft/terminal/wiki/Console:-Potential-Breaking-Changes
The one that affects you is the first bullet point (`CHAR_INFO`).

Please let me know if you have any questions!

**Comment by abgox** [comment] 2024-11-27 06:32
> 2. When the output encoding is switched to UTF8, Windows Terminal (Preview) has unexpected behavior in rendering Chinese or other multi-byte characters, but it works fine in other terminals like Tabby,Hyper.

- So for the second question, is there any relevant reason or solution?

**Comment by lhecker** [comment] 2024-11-27 15:42
We don't just maintain Windows Terminal but also all other parts of the console subsystem of Windows. One such component is "ConPTY" which is a translation layer from traditional console APIs like `SetConsoleCursorPosition` (= `$Host.UI.RawUI.CursorPosition`) to more modern VT sequences (= ``"`e[${y};${x}H"``). This translation layer is used by Tabby and Hyper, but also by Windows Terminal.

The difference now is that Windows Terminal always bundles the latest version of ConPTY, while Tabby and Hyper use whatever version Windows comes with (which may be a few years behind). If you update to Windows 11 24H2 (build 26100) your Windows should have a version of ConPTY that performs input validation and then Tabby/Hyper will show the same issue.

**Comment by abgox** [comment] 2024-11-28 02:28
Oh, it will be difficult to render multibyte text such as Chinese characters via `$Host.UI.RawUI.SetBufferContents()` in the future.

**Comment by lhecker** [comment] 2024-12-02 15:14
> Oh, it will be difficult to render multibyte text such as Chinese characters via `$Host.UI.RawUI.SetBufferContents()` in the future.

Chinese should mostly work, since all of the important characters are in the BMP (basic multilingual plane). Characters that aren't are in the CJK Unified Ideographs Extension B through I (= historic Chinese) and the Enclosed Ideographic Supplement blocks.
But generally speaking, it would indeed be a good idea to migrate over to using VT sequences. It allows you to use arbitrary Unicode and is also significantly faster.

**Comment by carlos-zamora** [comment] 2024-12-04 22:58
Thanks for filing. Closing as "by design" due to Leonard's comments above.

**Closed by carlos-zamora** 2024-12-04 22:58 UTC
Labels: Issue-Bug, Needs-Triage
