### ISSUE TITLE
Windows Terminal Crashes when dragged to another monitor on a multimonitor system (Windows Insider Fast Ring)

### ISSUE THREAD

**Issue by JustinGrote** [microsoft/terminal#3539] opened 2019-11-12 18:09 UTC
# Environment

```none
Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.19018.0 Microsoft Windows NT 10.0.19018.0
```

# Steps to reproduce
I deleted the profile to recreate automatically to make sure it isn't a profile specific issue
On a multimonitor system, drag the terminal to another monitor and it crashes 

# Expected behavior
It drags OK

# Actual behavior

It crashes.

# Application Log Error

```
Fault bucket 1825715257189852845, type 5
Event Name: MoAppCrash
Response: Not available
Cab Id: 0

Problem signature:
P1: Microsoft.WindowsTerminal_0.6.2951.0_x64__8wekyb3d8bbwe
P2: praid:App
P3: 1.0.1910.22001
P4: 5daf7ab2
P5: StackHash12_611
P6: 0.0.0.0
P7: 00000000
P8: 88000fa8
P9: 0
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERA4BB.tmp.mdmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERA577.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERA598.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERA5A0.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERA5C0.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Microsoft.Window_819db56bc4a492bff4a9ca442ef8eebdb785ee_b251fdb8_2f5cebaf-7a47-4e07-b4ec-1aafd5d9cfbd

Analysis symbol: 
Rechecking for solution: 0
Report Id: d505dbdd-8398-4675-88be-2782a51f89ee
Report Status: 2147487744
Hashed bucket: 1c6494429e7d3de659563e5a75cfe6ad
Cab Guid: 0

---
Faulting application name: WindowsTerminal.exe, version: 1.0.1910.22001, time stamp: 0x5daf7ab2
Faulting module name: KERNELBASE.dll, version: 10.0.19018.1, time stamp: 0xece648ff
Exception code: 0xc000027b
Fault offset: 0x000000000010ab6c
Faulting process id: 0x278c
Faulting application start time: 0x01d59983f7240a48
Faulting application path: C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_0.6.2951.0_x64__8wekyb3d8bbwe\WindowsTerminal.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: d505dbdd-8398-4675-88be-2782a51f89ee
Faulting package full name: Microsoft.WindowsTerminal_0.6.2951.0_x64__8wekyb3d8bbwe
Faulting package-relative application ID: App
```

**Comment by zadjii-msft** [comment] 2019-11-12 18:26
Thanks for the report! There's already a duplicate of this issue with a nearly word-for-word matching title: /dup #3303

Please make sure to search before filing new issues ☺️

**Closed by zadjii-msft** 2019-11-12 18:26 UTC
Labels: Needs-Tag-Fix, Needs-Triage

**Comment by JustinGrote** [comment] 2019-11-12 19:33
I 100% missed it @zadjii-msft, sorry for the dupe.
