### ISSUE TITLE
Bug Report: Initial settings - Power Shell 6 detected even if not present

### ISSUE THREAD

**Issue by Forinil** [microsoft/terminal#1673] opened 2019-06-27 14:49 UTC
# Environment

```none
Windows build number: 10.0.18362.175
Windows Terminal version (if applicable): from Windows Store

Any other software?
PowerShell Core 7 preview
```

# Steps to reproduce

Install Windows Terminal on Windows without PowerShell Core 6, but with PowerShell Core 7 installed.
Run Windows Terminal.

# Expected behavior

Windows Terminal opens with either PowerShell Core 7 or Windows PowerShell or cmd as the default console.

# Actual behavior

Windows Terminal crashes.

# Reason for the crash

The `profile.json` file contains entry for PowerShell 6 Core set as default console.

**Comment by WSLUser** [comment] 2019-06-27 17:34
PS6Core is supposed to replace Windows Powershell as the Powershell that ships with Windows since there's a compatibility module to ensure Windows specific modules can be accessed (though still alittle buggy at this time in my experience). CMD would probably be the best default for now since you can quickly switch to Powershell or other shells/terminals.

**Comment by miniksa** [comment] 2019-06-27 22:37
Dupe of #1399.

**Closed by miniksa** 2019-06-27 22:37 UTC
Labels: Needs-Tag-Fix, Needs-Triage
