### ISSUE TITLE
CONHOST fonts problem

### ISSUE THREAD

**Issue by 0wwafa** [microsoft/terminal#18042] opened 2024-10-13 16:24 UTC
Not only the unicode fonts don't show all characters but look at this:

![Image](https://github.com/user-attachments/assets/5c140227-155d-4b99-80c5-f57aa42bd0b1)

Can anyone tell me what can cause this?

I am even using another version of conhost (the original of 2019 in the windows recovery disk)

The problem is *NOT* conhost itself but something in the system that has been modified by some recent update.

Can someone please help me understand this?

In CONHOST in the image above the font is wrong and the size is like it has a different dpi

Look at this... again: putty and notepad are correct.

![Image](https://github.com/user-attachments/assets/ec85fe01-f123-449f-b003-77b67383d8f4)

**Comment by 0wwafa** [comment] 2024-10-13 16:51
And also in microsoft edge.
![Image](https://github.com/user-attachments/assets/bcc937ba-ea8c-4daf-aa7b-2d946c12ff2e)

Can someone *please* help me?

**Comment by DHowett** [comment] 2024-10-13 19:14
It’s the weekend for us Microsoft folks. Most of my team doesn’t work weekends!

You appear to be having a systemwide problem that isn’t directly associated with the console. Can you roll back the update and file feedback in the Feedback Hub?

**Comment by DHowett** [comment] 2024-10-13 19:16
As a note: conhost currently-and pretty much always has–measures font sizes in pixels (cell height) whereas almost all other applications measure font sizes in points. 16 in conhost will be smaller than 16 in Notepad and Edge, as 16 in conhost means “make the cell height 16 pixels”

This is a fairly well-known quirk of the console on Windows that we aren’t planning on changing.

**Comment by 0wwafa** [comment] 2024-10-14 03:43
> Size difference aside (see the next comment for details), you appear to be having a systemwide font problem that isn’t directly associated with the console. Can you roll back the update and file feedback in the Feedback Hub?

No problem for the size.. glad to know isn't related to my  problem. But I hace no font issue. At least I am pretty sure something else prevent the fonts to work correctly in SOME but not all programs.
But I don't see any relevant log in event viewer nor in process monitor (I posted it in another issue) perhaps I can't see it.
I wish to dig the cause instead of performing an in-place upgrade/repair. My system is quite customized and I don't want to set everything up again. Also I am on a metered connection and I will have to reupdate everything. I wish to find a fix. I bet is some permission or some other program interfering.

**Comment by 0wwafa** [comment] 2024-10-14 11:10
I fixed one of the TWO problems, now unicode works in chrome and anywhere except conhost running bash.exe.

![Image](https://github.com/user-attachments/assets/15399ff9-99b7-4934-b660-321102956bf9)

**Comment by 0wwafa** [comment] 2024-10-14 11:20
Second update: also `openconsole bash.exe` now works!
![Image](https://github.com/user-attachments/assets/0fb373cb-d88f-4b5e-bf38-750d8ee5ab38)

The windows 10 conhost.exe instead still works only with cascadia.
Any Idea what it can be?

if YOU do: `c:\windows\system32\conhost.exe bash ~`  does unicode works with all unicode fonts?

**Comment by lhecker** [comment] 2024-10-14 12:16
I'm happy to hear that you could resolve your font issue, although it's unclear to me why it broke in the first place. I was under the impression that it still worked when you filed #18024. That aside...

> The problem is NOT conhost itself but something in the system that has been modified by some recent update.

We know, because we maintain conhost and told you that we didn't ship any conhost updates. I'm not sure why you continue to not believe us.

> The windows 10 conhost.exe instead still works only with cascadia.

To repeat what I said in #18024:
* Braille glyphs are U+2800..U+28FF
  * Consolas does **NOT** contain braille glyphs: https://www.fileformat.info/info/unicode/font/consolas/list.htm
  * Source Code Pro does **NOT** contain braille glyphs: https://www.fileformat.info/info/unicode/font/source_code_pro/list.htm
  * Lucida Console does **NOT** contain braille glyphs: https://www.fileformat.info/info/unicode/font/lucida_console/list.htm
  * DejaVu Sans Mono does **NOT** contain braille glyphs: https://www.fileformat.info/info/unicode/font/dejavu_sans_mono/list.htm
  * Cascadia **DOES** contain braille glyphs: https://github.com/microsoft/cascadia-code/blob/a0f40c6fcae6440d6b6b063b2c16c23051fb056e/sources/CascadiaCode-Regular.ufo/glyphs/blank-braille.glif
* "Font fallback" is required if a font does not contain a glyph
  * conhost does **NOT** support font fallback (on Windows 10)
  * OpenConsole **DOES** support font fallback
  * Putty **DOES** support font fallback
  * Notepad **DOES** support font fallback

Conclusion: If you use Windows 10 conhost with braille glyphs but your font does not support braille glyphs they will shop us as `?` symbols.

Do you have any other questions that aren't related to font fallback and those `?` symbols?

**Comment by lhecker** [comment] 2024-10-14 12:21
I should add: We are just roughly ~2 developers on this project right now and have >100M users to support. If your issue is not caused by conhost then we must close it to focus on those people that have an issue that is caused by it.
Currently it appears you don't have an issue caused by conhost, because the lack of font fallback is known and has been fixed in Windows 11.

**Comment by 0wwafa** [comment] 2024-10-15 18:58
> Conclusion: If you use Windows 10 conhost with braille glyphs but your font does not support braille glyphs they will shop us as `?` symbols.
> 
> Do you have any other questions that aren't related to font fallback and those `?` symbols?

Yes. But just so you know, NPM uses braille unicode for the loading animation.
And NPM is quite spread.

The dots in the braille unicode are useful for many thing (but also a lot of other characters are missing without the fallback.

IMHO conhost should support font fallback as even NOTEPAD does.

**Comment by 0wwafa** [comment] 2024-10-16 15:49
> I'm happy to hear that you could resolve your font issue, although it's unclear to me why it broke in the first place. 

No Idea.. I noticed last week, what I was busy on a project... yesterday I dug in the problem and finally solved it.
Now all fonts are ok (there were no missing fonts before, but some registry keys got corrupted/missing somehow).
So I checked a few font related keys in registry then copied from another system, then reinstalled all fonts and finally did an sfc /scannow and dism  restorehealth...

**Comment by 0wwafa** [comment] 2024-10-16 16:20
@lhecker   after some more testing, everything is "sort of" working in OpenConsole.exe.

The only things I dont understand are:

1) Why SF Mono does not show up (it does in other apps including mintty and pterm)

2) why the cursor sometimes "ghosts" on previous lines (expecially when using openconsole.exe to run bash.exe)

**Comment by lhecker** [comment] 2024-10-16 17:01
> Why SF Mono does not show up (it does in other apps including mintty and pterm)

I suspect you may still have a corrupted font database. You should make sure that your font exists in `C:\Windows\Fonts`. The `%LOCALAPPDATA%\Microsoft\Windows\Fonts` folder should be entirely empty. Afterwards, I'd uninstall the affected fonts and reinstall them.

> why the cursor sometimes "ghosts" on previous lines (expecially when using openconsole.exe to run bash.exe)

That's probably a legitimate bug in our text renderer. We can continue talking about it over in #18038.

I'll be closing this issue for now, as there's nothing we can do about font fallback on Windows 10 at the moment. We can continue talking in #18038 about the cursor ghosting, and in #18044 about replacing conhost with OpenConsole.

**Closed by lhecker** 2024-10-16 17:01 UTC
Labels: Needs-Triage, Needs-Tag-Fix
