### ISSUE TITLE
Feature Request -Drag and Drop Path Support-

### ISSUE THREAD

**Issue by dan2600** [microsoft/terminal#2424] opened 2019-08-14 02:17 UTC
# Description of the new feature/enhancement

Add drag and drop file path support. Dragging a file onto the console copies the path to the current cursor location.

# Proposed technical implementation details (optional)

This should be possible using the windows API, implement DragAcceptFiles and use the WM_DROPFILES message. Implementation would be to receive the drop files message and copy the dropped file(s) path(s) to the current cursor location in the terminal.

**Comment by zadjii-msft** [comment] 2019-08-14 12:21
This is a dupe of #904

**Closed by zadjii-msft** 2019-08-14 12:21 UTC
Labels: Issue-Feature, Needs-Tag-Fix, Needs-Triage
