### ISSUE TITLE
1 pixel gap around window prevents mouse from interacting with control buttons (minimize, maximize, close)

### ISSUE THREAD

**Issue by chrismarts** [microsoft/terminal#7422] opened 2020-08-26 21:46 UTC
# Environment

```none
Windows build number: Win32NT, 10.0.19042.0 Microsoft Windows NT 10.0.19042.0
Windows Terminal version (if applicable): 1.1.2233.0
```

# Steps to reproduce

1. Maximize the window.
2. Move the mouse to the very top right corner of the screen and click to close the window.

# Expected behavior

Correct/typical behavior (e.g. for File Explorer, Edge, UWP apps, etc...) is that the mouse interacts with the window control buttons (minimize, maximize, close) when touching the top edge of the screen, or the top right corner. Meaning, the mouse can be put into the very top right corner of the screen, and when clicking, the close button is engaged and the window closes. For the Windows Terminal, there seems to be a 1pixel "gap" along the top/sides of the window that prevents this from working.

# Actual behavior

The close button does not go into a hover state with the mouse located there and the window does not close.

See example where mouse cursor is at top right corner of the screen but the close button is not "lit up" red:

![mouse-cursor-in-top-right-corner](https://user-images.githubusercontent.com/650202/91360208-468f7800-e7f6-11ea-9a9d-9405730bea29.png)

I see this on some apps here and there -- Nitro PDF is another example.

**Comment by DHowett** [comment] 2020-08-27 18:32
Repro notes: looks like it doesn't happen on 100% scale displays but it **does** on my 150 when I move it from my 100.

**Comment by chrismarts** [comment] 2020-08-28 07:45
Ah great thinking. My repro/screenshot comes from a 225% scaled 4K monitor.

**Comment by chrismarts** [comment] 2020-09-02 14:01
I'm now not seeing this in v 1.2.2381.0. Not sure if it's fixed, or whether the issue may be transient.

**Comment by itshoro** [comment] 2020-09-08 18:55
![image](https://user-images.githubusercontent.com/15874697/92516433-818da480-f215-11ea-8fb7-f333246b3281.png)

Still present for me. 100% Scaling on my monitor, v1.3.2382.0

**Comment by xnoreq** [comment] 2020-11-22 14:40
Same problem here.
It happens on a secondary 1080p monitor that extends the main 1440p monitor, both 100% scaling.

The issue also exists for the tabs, see #8363.

**Comment by Don-Vito** [comment] 2020-11-22 14:42
> 
> 
> Same problem here.
> It happens on a secondary 1080p monitor that extends the main 1440p monitor, both 100% scaling.
> 
> The issue also exists for the tabs, see #8363.

The weird part is that I am is exactly with the same setup, and cannot reproduce it no matter what 😊

**Comment by bazzilic** [comment] 2021-05-07 06:42
I still have this issue. Could be a thing with multiple monitors with diff scaling, here are my settings:

<details><summary>Monitor 1</summary>

![image](https://user-images.githubusercontent.com/1805832/117407984-e4207700-af41-11eb-9273-9f8aeb30ca6f.png)

</details>

<details><summary>Monitor 2</summary>

![image](https://user-images.githubusercontent.com/1805832/117408041-f39fc000-af41-11eb-9553-e947d2a20e36.png)

</details>

**Comment by avanishsubbiah** [comment] 2021-05-14 01:11
I'm having this issue with a single 3440x1440 monitor with 100% scale.

**Comment by campbellkerr** [comment] 2021-05-26 03:43
I was able to replicate this issue, and managed to "fix" it. 

If I maximise the window on my main monitor (LEFT, 3), all is well. If I maximise it on my secondary monitor (RIGHT, 2), the problem occurs. 

Scaling is set to 100% for both monitors. 

![image](https://user-images.githubusercontent.com/38451588/119599256-fb0f0680-be27-11eb-919e-647adb8240fa.png)

I found by "rearranging" monitor 2 to the same "height" as monitor 3, the Close button lights up now at the edge of both screens.

![image](https://user-images.githubusercontent.com/38451588/119599440-5a6d1680-be28-11eb-8f0f-a3ffd601affd.png)

**Comment by KalleOlaviNiemitalo** [comment] 2021-05-26 08:18
I have 1920×1080 on display 1, 1920×1080 on display 3 (the main display), and 1280×1024 on display 2; 100% scale in each. It was very difficult to align the top edges of the displays just right in the Settings app, which tends to snap the bottom edges instead. I was finally able to do it by dragging display 2 above display 3 and then moving it with the arrow keys. I can now click Windows Terminal tabs on each display with no gap.

![image](https://user-images.githubusercontent.com/46201428/119625999-71edd480-be13-11eb-9f6b-e8f5db028a44.png)

If I move display 2 higher up, then displays 1 and 3 get a gap.

So, I imagine something compares the top Y coordinate of the window to 0 and not to what is in [MONITORINFO](https://docs.microsoft.com/windows/win32/api/winuser/ns-winuser-monitorinfo).

**Comment by devhl-labs** [comment] 2021-06-06 17:35
I have something similar. My left two monitors have the gap, and the third monitor (which is portrait) does not have the gap.

**Comment by zadjii-msft** [comment] 2021-07-14 15:52
Okay, I finally found a configuration that works for me to repro this. For me, it's all three aligned exactly on the top, side-by-side. And it only repros on monitor 2. Weird.

**Comment by devhl-labs** [comment] 2021-07-14 16:25
Hope you can fix it. It's annoying to switch tabs and start typing commands only to find you didn't actually switch tabs.

**Comment by zadjii-msft** [comment] 2021-07-14 21:03
Okay, there's an absolute hack of a fix in 37fbeab22. That's absolutely not right though. In that commit, I just move the xaml island up one pixel when we're maximized. That seems to allow the island to receive the mouse events we'd expect, but it definitely cuts off one pixel of the top of the tab row. IMO, it's not _that_ bad, but I'd rather have the _right_ solution. At this point I think I'm out of ideas. 

@greg904 has worked in this area of code before - any ideas what might be going on here?

Also, @ocalvo and @Austin-Lamb do a lot of XAML Islands work, in case they've ever seen anything like this before. 

And lastly, @ekoschik because he knows these kinds of things in and out.

**Comment by zadjii-msft** [comment] 2021-07-15 15:51
Okay, I'm officially out of ideas now.

The top pixel of the `TabViewItem`'s and the `SplitButton` is _never_ clickable in the Terminal. Never. No idea why, but it just isn't. Not only that, but I can't repro that in the scratch app with the roughly same XAML as in the Terminal. Even when the window isn't maximized, that pixel seemingly isn't clickable for those buttons/tabs. \<conjecture>I'm assuming the same is true of the `MinMaxCloseControl`, though that's always drawn at the full height of the titlebar, so I'm thinking that the "dead pixel" is actually up in the border pixel (when windowed), so it's not an issue.\</conjecture>

**Comment by zadjii-msft** [comment] 2021-07-15 16:00
screenshots:

![image](https://user-images.githubusercontent.com/18356694/125819241-97ccac8b-0069-4a93-9139-57450bc281bb.png)
_enhance_
![image](https://user-images.githubusercontent.com/18356694/125819276-192976e1-21d0-4714-bc49-495f9cc6af31.png)


As you can see, the window isn't even maximized. The split button and the tab view are aligned on the top. You can see that the pointer is pointed at a pixel that's within the bounds of the split button, but the button doesn't think it's hovered.

**Closed** 2021-07-28 22:15 UTC
Labels: Area-User Interface, Help Wanted, In-PR, Issue-Bug, Priority-3, Product-Terminal
