### ISSUE TITLE
Run Command Prompt / Powershell as Administrator

### ISSUE THREAD

**Issue by Adamo2499** [microsoft/terminal#6886] opened 2020-07-12 18:12 UTC
Maybe add option to run Powershell or Command Prompt as Administator? Default it would start as normal user, but in dropdown menu would be an option: "Run as Administrator"

**Comment by LuanVSO** [comment] 2020-07-12 18:18
Duplicate of #632 and #4217

**Closed** 2020-07-12 21:01 UTC
Labels: Issue-Feature, Needs-Tag-Fix, Needs-Triage
