### ISSUE TITLE
Support for picture

### ISSUE THREAD

**Issue by ViniDalvino** [microsoft/terminal#9702] opened 2021-04-04 00:54 UTC
# Description of the new feature/enhancement
Support for pictiure. I would like to be able to display image in the terminal like iterm can do.

Here is how it look in iterm:
![image](https://user-images.githubusercontent.com/37189791/113495287-95a13800-94be-11eb-95da-1888f176c218.png)

# Proposed technical implementation details (optional)
Follow the same implementation that iterm  do ¯\\_(ツ)_/¯. here is the source code of iterm https://github.com/gnachman/iTerm2

**Comment by KalleOlaviNiemitalo** [comment] 2021-04-04 05:39
<https://github.com/microsoft/terminal/issues/5746> seems to cover this.

**Comment by skyline75489** [comment] 2021-04-04 06:55
I’d like to point out, due to licensing issue, we literally can’t “follow the same implementation that iterm do”. This project is MIT-licensed while iTerm2 is GPL-licensed.

Even if we can, the architectural differences between these two projects is just enormous. There are tons of work needs to be done for it to happen.

**Comment by DHowett** [comment] 2021-04-04 16:56
Is it possible for you to produce a request that does not contain lewd anime women? 🤨

**Comment by DHowett** [comment] 2021-04-04 16:57
But yes, this is a /duplicate of #5746

**Closed by DHowett** 2021-04-04 16:57 UTC
Labels: Issue-Feature, Needs-Tag-Fix, Needs-Triage
