### ISSUE TITLE
Windows Terminal v1.1.2233.0 disappears leaving all processes intact

### ISSUE THREAD

**Issue by qm2k** [microsoft/terminal#7345] opened 2020-08-19 11:57 UTC
# Environment

```none
Windows build number: 10.0.19041.0
Windows Terminal version (if applicable): 1.1.2233.0

Any other software?
```
I'm using [git bash](https://git-scm.com/download/win) as shell, but I don't think it's relevant.

# Steps to reproduce

Keep Windows Terminal started for days with multiple tabs and some processes running inside (e.g. normal use mode).

# Expected behavior

Windows Terminal not disappearing. As a workaround (since the problem may recur), if it closes it allows me to access all of my earlier started processes again after I restart the app.

# Actual behavior

Windows Terminal disappears at some time while I'm not using my computer, leaving all started processes intact. When I relaunch it the Task Manager shows my previously started processes (immediate siblings only, not processes started from these processes) under the newly opened window, but the window itself only shows one default tab:
![image](https://user-images.githubusercontent.com/13719792/90624354-7f40b780-e220-11ea-8b03-83cd38b1e9fc.png)
![image](https://user-images.githubusercontent.com/13719792/90624387-8b2c7980-e220-11ea-9805-be753bccb853.png)

The symptoms are exactly repeating those described in #3253 that was supposed to be fixed in v0.7.3291.0

**Comment by zadjii-msft** [comment] 2020-08-19 20:37
Well that's definitely unexpected. Especially the fact that Task manager can figure out that those child processes should be re-parented to the Windows Terminal package - if the original process were truly killed and cleaned up, then you'd imagine that there'd be no way of determining that. 

Does this always take multiple days to reproduce? Or is there something that you can do to trigger this behavior on demand?

**Comment by qm2k** [comment] 2020-08-20 08:26
> Does this always take multiple days to reproduce? Or is there something that you can do to trigger this behavior on demand?

It happened twice already. I found both corresponding windows log events. Previous time was 30/07/2020 04:27:26 and I was definitely not present at the computer. Yesterday it happened on 09:25 and I might have been present but I don't remember anything unusual (I'm using multiple desktops so it took me some time to notice that the terminal window missing). According to logs there was no windows update at the time, and automatic suspend on mains power was disabled (and I definitely did not wake the computer up, only unlocked the screen).

Here's the last event (also [.xml and .evtx](https://github.com/microsoft/terminal/files/5101711/1002_ApplicationHang.zip)):
> The program WindowsTerminal.exe version 1.1.2007.20001 stopped interacting with Windows and was closed. To see if more information about the problem is available, check the problem history in the Security and Maintenance control panel.
>  Process ID: 52ec
>  Start Time: 01d6724a7dc40bd8
>  Termination Time: 4294967295
>  Application Path: C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_1.1.2021.0_x64__8wekyb3d8bbwe\WindowsTerminal.exe
>  Report Id: 8a097a96-a30a-4804-b26e-61e690adf68a
>  Faulting package full name: Microsoft.WindowsTerminal_1.1.2021.0_x64__8wekyb3d8bbwe
>  Faulting package-relative application ID: App
>  Hang type: Quiesce
>

**Comment by qm2k** [comment] 2020-08-20 08:39
Just noticed that versions in the version I'm currently running (1.1.2233.0, also latest in Microsoft Store) and the version in the event viewer do not match. Also found the following [events from WindowsUpdateClient](https://github.com/microsoft/terminal/files/5101770/WindowsUpdateClient.zip):
> Logged: 19/08/2020 09:24:30
> Installation Started: Windows has started installing the following update: 9N0DX20HK701-Microsoft.WindowsTerminal

> Logged: 19/08/2020 09:25:14
> Installation Successful: Windows successfully installed the following update: 9N0DX20HK701-Microsoft.WindowsTerminal

There was no system update, but apparently an app update happend sometime around the crash. Looks highly suspicious.

**Comment by DHowett** [comment] 2020-08-20 23:30
We've seen an uptick in these issues very recently--about 7 days since we released the last update. I'm starting to become convinced that this _is_ because of the update (and not the other way around.) Thanks for the info above ^

I had a colleague help me look at dumps from these hangs, and it looks like they happen predominantly when the "do you want to close all tabs?" dialog is open.

Here's my theory:

1. The store decides there's been an update available for long enough
2. It asks Terminal to exit nicely
3. Terminal resists, and says "i've got tabs open -- at least let the user confirm it"
4. _With or without an answer_, this looks like Terminal is another intransigent application that needs to be put down, and so it gets terminated and _blamed_ for "hanging".

This is a place where the platform treats us like a "store-managed" application, where we're really not.

I'm tentatively closing this as a /duplicate of #6726. Thanks for following up :smile:

**Closed by DHowett** 2020-08-20 23:30 UTC
Labels: Needs-Attention, Needs-Tag-Fix, Needs-Triage, Product-Terminal, Severity-Crash
