### ISSUE TITLE
Support for running Exchange Management Shell

### ISSUE THREAD

**Issue by InsomniacsDream** [microsoft/terminal#3572] opened 2019-11-14 00:57 UTC
It would be great to be able to add MS Exchange Shell to Terminal to manage On-Prem exchange.

**Comment by zadjii-msft** [comment] 2019-11-14 14:09
I think this might unfortunately be a /dupe of #1785. It looks like the way the MS Exchange Shell works is fairly incompatible with the way the Terminal launches applications. From that thread:

https://github.com/microsoft/terminal/issues/1785#issuecomment-509060477
> 
> This might just boil down to #492. It looks like `appref-ms` shortcuts are another type of ClickOnce application, which means their launch _must_ be brokered through another process (internet explorer, windows shell, etc.) Right now, we can't support hooking the launch of another console application through a broker.

#1785 (and this issue) will work once we've added support for #492. I've also got mail out to the owners of Exchange Management Shell, hopefully we might be able to find a workaround.

I'm going to close this for now, as a dupe of that other thread. If I hear anything back that's usable as a workaround, I'll make sure to reply here ☺️

**Closed by zadjii-msft** 2019-11-14 14:10 UTC
Labels: Needs-Tag-Fix, Needs-Triage
