### ISSUE TITLE
Opening "About" crashes the terminal

### ISSUE THREAD

**Issue by Cry0nicS** [microsoft/terminal#4234] opened 2020-01-15 11:35 UTC
# Environment

```none
Windows build number:  Win32NT             10.0.18362.0 Microsoft Windows NT 10.0.18362.0
Windows Terminal version (if applicable):0.8.10091.0

Any other software?
I have Windows Terminal installed via `scoop`
```

# Steps to reproduce

1. Open Windows Terminal
2. Click on `About` under the "arrow" menu.
# Expected behavior
I expect to see _some_ information about the application.

# Actual behavior

The application just crashes without any message or alike.
Here's a quick video about it: https://imgur.com/phob2O1

For what is worth, I didn't have this issue with the previous version of WT.

**Comment by zadjii-msft** [comment] 2020-01-15 14:14
Thanks for the report! Would you mind capturing this crash with the Feedback Hub, so we can try and figure out the root cause? /feedback

**Comment by Cry0nicS** [comment] 2020-01-15 14:35
@zadjii-msft I _think_ I did. I added a link to this issue in the description.

**Comment by zadjii-msft** [comment] 2020-01-15 14:51
@Cry0nicS Could you post the aka.ms link to the feedback item that's generated by clicking this button:
![image](https://user-images.githubusercontent.com/18356694/72443522-018d6880-3774-11ea-9acd-3ee167715990.png)

That's usually the easiest way for us to drill in on the specific item

**Comment by Cry0nicS** [comment] 2020-01-15 15:47
@zadjii-msft I guess first time I couldn't do this because I wasn't logged in.

Anyway, here it is: https://aka.ms/AA704rx
Let me know if it helps or if there's anything else I can provide.

**Comment by DHowett-MSFT** [comment] 2020-01-24 18:11
I've pulled off the Triage tag and moved this into the v0.10 milestone. It still Needs-Repro, though, since none of us can get this to happen. Thanks for the report!

**Comment by bartlibert** [comment] 2020-02-11 11:30
I have this issue as well, vs debugger give the following info (don't know it if helps): 

Unhandled exception at 0x00007FFE4AC22EC0 (Windows.UI.Xaml.dll) in WindowsTerminal.exe: 0xC000027B: An application-internal exception has occurred (parameters: 0x000001D4EE280440, 0x0000000000000005). occurred

**Comment by DHowett-MSFT** [comment] 2020-02-27 22:45
> installed via scoop

Wait a second. Scoop installs WT by extracting the zip, which is not supported. This causes an application name lookup failure.

I'm reprioritizing this out of version 1.0 for the use of an alternative installation method. Sorry.

**Comment by DHowett-MSFT** [comment] 2020-02-27 22:45
Actually, closing as not supported.

**Closed by DHowett-MSFT** 2020-02-27 22:45 UTC
Labels: Area-User Interface, Help-Wanted, Issue-Bug, Needs-Repro, Priority-1, Product-Terminal, Severity-Crash
