### ISSUE TITLE
Conhost.exe CRASH when changing zoom with mouse cursor

### ISSUE THREAD

**Issue by rdstevens** [microsoft/terminal#3245] opened 2019-10-18 15:55 UTC
Using Windows Store version 0.5.2762.0

Zipped DMP file attached.

[conhost.exe.21732.dmp.zip](https://github.com/microsoft/terminal/files/3744760/conhost.exe.21732.dmp.zip)

**Comment by DHowett-MSFT** [comment] 2019-12-02 20:38
This may be a /dupe of #1856.

**Closed by DHowett-MSFT** 2019-12-02 20:38 UTC
Labels: Area-Output, Issue-Bug, Product-Conpty, Severity-Crash
