### ISSUE TITLE
Running as a default terminal causes app to create terminal window

### ISSUE THREAD

**Issue by Mayhem93** [microsoft/terminal#11627] opened 2021-10-27 07:54 UTC
### Windows Terminal version (or Windows build number)

10.0.22000.0, 1.11.2921.0

### Other Software

CoolerMaster MasterPlus (I couldn't find any version string :( but it's a 2-3 week old fresh install)

### Steps to reproduce

Make Windows Terminal the default terminal.

Install CoolerMaster MasterPlus (I don't think it's a requirement to have any of their hardware to use it) and on every reboot there's a service called MPService that starts a process with a console host attached:
![image](https://user-images.githubusercontent.com/705289/139022471-22714d58-c136-489b-95c0-096aff50c7b0.png)

Then a windows terminal window appears:
![image](https://user-images.githubusercontent.com/705289/139022587-05633505-f90c-4903-a76f-7c854e7f6ff5.png)

And every time I close it (obviously the process ends) the service restarts the program (so the only way to get rid of this is to stop the service).

### Expected Behavior

Expected behavior should be the same when conhost was the default console terminal (no window creation, the program ran in the background)

### Actual Behavior

The terminal window appears every time this service runs the said program instead of having it in the background somehow.

**Comment by Eveldee** [comment] 2021-11-04 11:46
Same issue using [Syncthing](https://github.com/syncthing/syncthing), their doc recommends to create a startup task with options to disable the console: `"C:\Program Files\Syncthing\syncthing.exe" -no-console -no-browser` but on Windows 11 using Windows Terminal as default makes the console **window visible** instead of hiding it (works perfectly with conhost as default).

![Syncthing](https://user-images.githubusercontent.com/28998091/140308244-099a8465-cb40-4e12-8033-04799a191c78.png)

**Comment by silverqx** [comment] 2022-01-29 16:12
I have the same issue with more apps, eg Qt Maintenace Tool for windows opens a visible terminal, I let know about other apps when I discover which one opens these terminals.

**Comment by silverqx** [comment] 2022-02-20 12:59
Ok, after a few weeks of use I can tell that the `Qt Maintenance tool` is only one application that opens a visible terminal window, I'm pretty sure that wterm behaves correctly and this will be `Qt Maintenance Tool` problem. Personally, I have not observed any wrong behavior of the wterm. 😁

**Comment by silverqx** [comment] 2022-02-20 13:02
There still can be a problem that is described in this issue, I have not tested it with `CoolerMaster MasterPlus` like is described in the first post, but I have tested with dozens of applications that I'm using.

**Comment by Mayhem93** [comment] 2022-02-20 14:21
I just realized the issue in my case is not present anymore. I don't know at what version it was fixed because I had conhost as default and somehow it automatically changed it to windows terminal without me knowing.

**Comment by zadjii-msft** [comment] 2022-05-02 17:09
Okay, I can confirm that this is seemingly fixed for CoolerMaster. Impossible to say if it was due to an OS-side defterm fix, a Terminal-side fix, or a CoolerMaster-side one.

The `ShowWindow` thing should have been fixed by #12515

Anything else that's in this bucket seems like it's probably a variant of /dup #12154. I'm gonna keep using that one to track it, since that's a little more narrowed down to the root cause. 

Thanks all!

**Closed by zadjii-msft** 2022-05-02 17:09 UTC
Labels: Issue-Bug, Product-Terminal, Priority-1, Area-DefApp
