### ISSUE TITLE
Feature Request Make the Terminal accessible outside of the Windows 10 Store

### ISSUE THREAD

**Issue by DonPavlov** [microsoft/terminal#1938] opened 2019-07-12 09:36 UTC
# Summary of the new feature/enhancement

App is accessible outside of the Windows Store to Download as an .exe File
Because of company policies i can never use this app will working. An Environment where i will definetly need to have this app.

# Proposed technical implementation details (optional)

The app can be installed as an .exe setup which auto updates.

**Comment by zadjii-msft** [comment] 2019-07-12 14:26
This is a dupe of #1386. 

For the record, we do have releases available on our [releases](https://github.com/microsoft/terminal/releases) page.

**Closed by zadjii-msft** 2019-07-12 14:26 UTC
Labels: Issue-Feature, Needs-Tag-Fix, Needs-Triage
