### ISSUE TITLE
error 0x80070002 - register windows.sharedFonts file not found

### ISSUE THREAD

**Issue by viper2pt0** [microsoft/terminal#3194] opened 2019-10-14 19:44 UTC
# Environment
Microsoft Windows [Version 10.0.18362.356]

# Steps to reproduce
Attempting to install via the Chocolatey package (pre-built msxibundle)

# Expected behavior
Install Succeeds

# Actual behavior
Install gets to 89% and then fails with the following message:
`error 0x80070002: While processing the request, the system failed to register the windows.sharedFonts extension due to the following error: The system cannot find the file specified.`

There is no reference to which file it is looking for.

**Comment by DHowett-MSFT** [comment] 2019-10-14 20:09
That's not great. Have you made any changes to your system -- added/removed any components that might be related to fonts, rendering, installation, packages, or the like?

Thanks.

**Comment by viper2pt0** [comment] 2019-10-15 13:33
Not to my knowledge.  Its a corporate managed device, I know the windows store has been disabled/removed.  Could that be something?

**Comment by Maattcc** [comment] 2019-10-15 21:29
Launch Run prompt by pressing Windows key + R together.

In Run, type diskmgmt.msc, press Enter.

In Disk Management, drag the right line of the Status column to expand it. Now, look which partition is marked as Primary Partition. Right-click this partition as click Make Partition As Active.

If a pop-up asking to confirm appears**,** click Yes or OK.

if still error try more methodshttps://geeksadvice.com/fix-error-code-0x80070002-on-windows/

**Comment by DHowett-MSFT** [comment] 2019-10-15 22:13
@maattcc Thanks for contributing a solution -- it looks like, broadly, asking people to change their partition settings to fix an application deployment issue (because it has the same error code (which is a generic error code) as this issue) is going to cause more harm than good... so I deleted yuor comment. Sorry!

**Comment by DHowett-MSFT** [comment] 2019-10-23 20:27
This seems like a windows store package deployment issue; would you mind filing feedback in the category _Install and Update / App installation issues_ and reproducing the failure?

Thanks!

**Closed by DHowett-MSFT** 2019-10-23 20:27 UTC
Labels: Needs-Attention, Needs-Tag-Fix, Needs-Triage

**Comment by einarhauks** [comment] 2019-12-17 17:59
I'm also having this issue. Any resolution yet?

**Comment by alanwhited-trwd** [comment] 2019-12-18 15:11
I'm also having this issue, logs attached.
[terminal_output.txt](https://github.com/microsoft/terminal/files/3979031/terminal_output.txt)
[chocolatey.log](https://github.com/microsoft/terminal/files/3979033/chocolatey.log)

**Comment by zeusbaba** [comment] 2020-01-09 07:56
i'm also having this issue with the same error log. 
p.s. this is also corporate laptop

**Comment by bmaehr** [comment] 2020-03-18 18:31
Solved exactly the same error by installing it NOT as admin.

**Comment by yann-f** [comment] 2020-06-03 19:55
Hi there,
I'm having this issue too on a corporate laptop : I've tried with and elevated ps prompt (wich use a different account because users haven't administrators rights) with no luck. The same without admin rights ...
At last, i tried while logged on with an administrator account and the installation complete successfully. I needed to reboot before using it with my account.

WIN+R and wt

**Comment by TBBle** [comment] 2021-03-07 22:52
Pinging off https://github.com/microsoft/terminal/issues/4217#issuecomment-712545620, I have two corporate machines on the same AD, which has a group policy that enforces elevation be run as a separate user, e.g., my_account.privileged, and on those two machines, running in an elevated Microsoft Powershell session:
```
Add-AppxPackage -Register 'C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_1.6.10571.0_x64__8wekyb3d8bbwe\AppxManifest.xml'  -DisableDevelopmentMode
```
one happily installed Windows Terminal to my high-priv account, and one failed with this error.

Since I've installed off Windows Store, I don't have a chocolatey package cache lying around so I cannot use yann-f's solution above (https://github.com/microsoft/terminal/issues/3194#issuecomment-638427795). I'm unaware of a Windows Store command-line API, and since I can only get to this account by elevation, I don't think I can run Windows Store on that account unless I log into the computer as the high-priv account (which I'm not going to do).

Did anyone ever lodge this issue to the Windows Store? Since I'm trying to register an already-installed package, not install something off the store, I'm not totally sure they'd accept my feedback as valid.

On the plus side, I have a simple repro-case if there's anything I can capture from Event Viewer etc. to dig into the failure itself.

**Comment by MrDaGree** [comment] 2022-03-28 17:59
For those that use Chocolatey and have the same issue I found that changing the last line of the upstream package from `Add-AppxPackage` to `DISM.EXE /Online /Add-ProvisionedAppxPackage /PackagePath:$fileName /SkipLicense` and updating the uninstall to `Get-AppxProvisionedPackage -online | where-object {$_.packagename -like "*WindowsTerminal*"} | Remove-AppxProvisionedPackage -online -allusers` fixed my issues

**Comment by spotlight2001** [comment] 2023-01-30 09:12
@MrDaGree I do have the same problem. Where can I find the file to be edited?

**Comment by draeath** [comment] 2023-02-08 15:27
We have a user who's running into this as well and we've no idea how to apply this fix either, @MrDaGree 

It would be very helpful if you could suggest how one would go about "changing the last line of the upstream package."

**Comment by MrDaGree** [comment] 2023-02-08 19:33
@spotlight2001 @draeath it was requiring changing the chocolatey install script and repackaging it. It was only possible if you have a custom repo

**Comment by TheMcSebi** [comment] 2023-08-25 15:56
> Solved exactly the same error by installing it NOT as admin.

Solved the issue for me as well.
Using a corporate device with LTSC 21H2 and no store.
