### ISSUE TITLE
[IDEA] context menus for taskbar and pinned start menu tile

### ISSUE THREAD

**Issue by maximousblk** [microsoft/terminal#5831] opened 2020-05-10 17:56 UTC
# Description of the new feature/enhancement

It would be really convenient to have a context menu for the pinned taskbar icon and pinned start menu tile. Think of it similar to chrome's context menu. when you right click on the taskbar icon of chrome it contains some shortcuts to different pages and incognito tab. Similarly in windows terminal, it would have shortcuts to all the profiles and settings.

This would make it much quicker to launch a no-default profile if you have a quick task. Otherwise, you would have to open your default profile and the select from the dropdown.

# Proposed technical implementation details (optional)

I don't really know how to implement it. You could take inspiration from chromium itself for how do they do it.

Here is a concept if you would like a visual:

![Ultra-HD@2x](https://user-images.githubusercontent.com/28438021/81506657-8dc02e80-9315-11ea-8795-41ecae3e8b0f.png)

It's a 2 min edit but you get the idea...

**Comment by DHowett-MSFT** [comment] 2020-05-10 18:17
Thanks for the request! This is a /dupe of #576

**Closed by DHowett-MSFT** 2020-05-10 18:18 UTC
Labels: Issue-Feature, Needs-Tag-Fix, Needs-Triage
