### ISSUE TITLE
Windows Terminal crash when background image path contains tilde

### ISSUE THREAD

**Issue by patriksvensson** [microsoft/terminal#4002] opened 2019-12-17 17:22 UTC
# Environment

```none
Windows build number: Microsoft Windows NT 10.0.19041.0
Windows Terminal version (if applicable): 0.7.3451.0
```

# Steps to reproduce

In `profiles.json` under a profile, add a background image path that references the home directory `~`.

```json
{
    ...
    "profiles": [
        {
            "name": "Windows PowerShell",
            "backgroundImage": "~/Pictures/Console/PowerShell.png",
        }
    ...
}
```

# Expected behavior

Should not crash. Should show the expected background image.

# Actual behavior

Windows Terminal crash at startup.

**Comment by DHowett-MSFT** [comment] 2019-12-19 20:41
This looks like a /dupe of #2329, which we'll reopen. They're largely the same bug caused by the same issue somewhere in XAML land.

**Closed by DHowett-MSFT** 2019-12-19 20:41 UTC
Labels: Needs-Tag-Fix, Needs-Triage

**Comment by mkitzan** [comment] 2019-12-19 20:45
@DHowett-MSFT I'm not sure if this is a dup since a tilde in the icon path doesn't crash WT. Very weird.

**Comment by DHowett-MSFT** [comment] 2019-12-19 22:55
@mkitzan I believe they are, but for reasons I didn't quite explain up front. :smile: Invalid resource paths to images (or all types) that end up getting displayed on a XAML surface end up running through the internet resource downloader somewhere deep in, uh, _internet explorer libraries_. Depending on where the image would have appeared in the visual tree, the exception caused by failing to load it can come out of different places.
Sometimes, it'll come right out when you try to create the image resource. Other times, it'll only come out when you attempt to navigate to a screen that contains that resource.
Since icons and backgrounds are just stuck into image views at the end of the day, I _believe_ they're the same issue.

**Comment by mkitzan** [comment] 2019-12-19 23:17
That makes a lot more sense. The image loading relation definitely is a key link between the two. Thanks for the explanation! Internet explorer libraries... I'm both horrified and intrigued.

**Comment by patriksvensson** [comment] 2019-12-23 08:48
@DHowett-MSFT Ah, I was looking for dupes before posting this but couldn't find any. Sorry! 😅

**Comment by DHowett-MSFT** [comment] 2019-12-23 09:09
Ah, don’t worry about that: we reopened a closed bug as the duplicate of this one, and I don’t expect people to find those as readily. :)
