### ISSUE TITLE
Can't launch maximized terminal in a specific folder (wt -M -d c:\ does not work)

### ISSUE THREAD

**Issue by richardthombs** [microsoft/terminal#7644] opened 2020-09-16 11:21 UTC
# Environment

```none
Windows build number: 10.0.19042.508
Windows Terminal version (if applicable): 1.2.2381.0
```

# Steps to reproduce

Try to launch a maximized terminal in a specific directory:

`wt -M -d c:\`

# Expected behavior

A maximized terminal window with C:\ as the working directory should open

# Actual behavior

A popup error is displayed: "The following argument was not expected: -M"

![image](https://user-images.githubusercontent.com/1511599/93330395-a0dc9100-f816-11ea-8597-1d794c3b2b55.png)

**Comment by DHowett** [comment] 2020-09-16 17:06
Whoops! Thanks for the report. This is a /duplicate of #7318 (more info https://github.com/microsoft/terminal/issues/7318#issuecomment-675038522)

**Closed by DHowett** 2020-09-16 17:06 UTC
Labels: Needs-Tag-Fix, Needs-Triage
