### ISSUE TITLE
Windows Terminal minimizes on launch if set as default terminal application

### ISSUE THREAD

**Issue by abitofmaya** [microsoft/terminal#10451] opened 2021-06-18 04:05 UTC
### Windows Terminal version (or Windows build number)

10.0.21390.1 1.9.1523.0

### Steps to reproduce

1. Set Windows Terminal as the default terminal application
2. Start Command Prompt or Powershell

### Expected Behavior

Launch Windows Terminal with the window in focus

### Actual Behavior

Windows Terminal starts and minimizes but if an instance is already running, works as expected

**Comment by skyline75489** [comment] 2021-06-18 06:09
This could be #10292 or #10386

**Comment by DHowett** [comment] 2021-06-21 15:59
Thanks! Yeah, this is a /duplicate of #10386

**Closed by DHowett** 2021-06-21 15:59 UTC
Labels: Needs-Tag-Fix, Needs-Triage
