### ISSUE TITLE
Some newlines appear to be broken

### ISSUE THREAD

**Issue by DHowett-MSFT** [microsoft/terminal#4107] opened 2020-01-03 22:09 UTC
As an example, the one you see when PowerShell starts up:

## bad
![image](https://user-images.githubusercontent.com/14316954/71752084-96b66600-2e32-11ea-931d-319e06661b2f.png)

## good
![image](https://user-images.githubusercontent.com/14316954/71752088-9b7b1a00-2e32-11ea-89fd-f15f05707e88.png)

**Comment by DHowett-MSFT** [comment] 2020-01-03 22:10
Looks like only WT...

**Comment by zadjii-msft** [comment] 2020-01-04 22:41
Is this a recent regression? I would have thought it might be #3271 but that hasn't merged yet.

**Comment by DHowett-MSFT** [comment] 2020-01-04 23:08
Very. The current selfhost build from 12/31 does not exhibit this issue. Maybe related to the audit mode refactoring?

**Comment by j4james** [comment] 2020-01-05 02:35
I believe the problem is in the `TerminalDispatch::CursorPosition` method here:
https://github.com/microsoft/terminal/blob/d711d731d7d00259b2e0fe5847928c9f1c1121ed/src/cascadia/TerminalCore/TerminalDispatch.cpp#L40-L44

If the `SizeTToShort` calls succeed, then the `FAILED` tests are going to be false, and the `RETURN_BOOL_IF_FALSE` will force the method to abort.

**Comment by DHowett-MSFT** [comment] 2020-01-05 05:20
Oof. Thanks.

**Closed** 2020-01-06 22:45 UTC
Labels: Area-VT, In-PR, Issue-Bug, Product-Terminal, Severity-Blocking
