### ISSUE TITLE
Feature Request: Double click selects the word

### ISSUE THREAD

**Issue by diegostammer** [microsoft/terminal#2112] opened 2019-07-26 02:22 UTC
# Summary of the new feature/enhancement

Double click selects and copies the word.

# Proposed technical implementation details (optional)

When double clicking on a word it should be selected and also copied to the clipboard.
The word should be selected from/to any white space or special character.

**Comment by zadjii-msft** [comment] 2019-07-26 12:07
This is a dupe of #988, which was fixed in #1197.

**Closed** 2019-07-26 12:08 UTC
Labels: Issue-Feature, Needs-Triage, Resolution-Duplicate
