### ISSUE TITLE
Application terminates on wheel-clicking a tab

### ISSUE THREAD

**Issue by smdonoghue** [microsoft/terminal#1588] opened 2019-06-25 08:34 UTC
# Environment

```none
Windows build number: 10.0.18362.175
Windows Terminal version (if applicable): 0.2.1715.0
```

# Steps to reproduce

Wheel-click a tab within Windows Terminal.

# Expected behavior

Close the tab or whatever the intending behaviour is by design.

# Actual behavior

Application becomes unresponsive for a matter of seconds and forcibly terminates.

**Comment by carlos-zamora** [comment] 2019-06-25 23:26
Duplicate of #1380

**Closed by carlos-zamora** 2019-06-25 23:26 UTC
Labels: Area-CodeHealth, Issue-Bug, Product-Terminal, Resolution-Duplicate, Severity-Crash
