### ISSUE TITLE
Hide "open in windows terminal" options in right-click menu

### ISSUE THREAD

**Issue by daimaxiaxie** [microsoft/terminal#9902] opened 2021-04-20 03:18 UTC
# Now the installer(v1.7) will forcefully appear "open in windows terminal" in menu. But I think it’s better to appear on the shift + right-click menu. I can't find a way to achieve it, so I hope the program can provide such an option.

# no implementation details

**Comment by KalleOlaviNiemitalo** [comment] 2021-04-20 04:39
This may be a duplicate of <https://github.com/microsoft/terminal/issues/6113>. That one already has the pull request <https://github.com/microsoft/terminal/pull/9358> implementing it but perhaps they want to add a configuration option before merging.

**Comment by zadjii-msft** [comment] 2021-04-20 11:06
Thanks for the suggestion! Please make sure to search for duplicates when filing new issues. This is already being tracked by another issue on our repo - please refer to #6113 for more discussion.

/dup #6113 
/dup #8105

**Closed by zadjii-msft** 2021-04-20 11:06 UTC
Labels: Issue-Feature, Needs-Tag-Fix, Needs-Triage
