### ISSUE TITLE
Powershell inside Windows Terminal Asian font copy issue

### ISSUE THREAD

**Issue by arnabanimesh** [microsoft/terminal#10315] opened 2021-06-03 09:45 UTC
### Windows Terminal version (or Windows build number)

10.0.19042.985, 1.8.1444.0

### Other Software

PowerShell Core 7.1.3

### Steps to reproduce

1. Copy this text: `話　E`
2. Paste it inside Powershell Core 7.1.3 inside Windows Terminal
3. The space-like character in the middle gets omitted while pasting. It works fine in standalone PowerShell Coreor cmd.
4. If the filename contains these characters then it gets impossible to match unless I copy that space like character separately.PowerShell

### Expected Behavior

The copied text should match the pasted text

### Actual Behavior

The space-like character gets omitted from the string causing differences between copied and pasted text

**Comment by DHowett** [comment] 2021-06-03 22:46
Thanks for the report! This is a /duplicate of #9052, which is fixed in 1.9-preview. :smile:

**Closed by DHowett** 2021-06-03 22:46 UTC
Labels: Needs-Tag-Fix, Needs-Triage
