### ISSUE TITLE
Copy & paste on Windows Terminal output with tab characters result in unexpected behaviour of results in text editors

### ISSUE THREAD

**Issue by EduardoZimelewicz** [microsoft/terminal#2656] opened 2019-09-04 12:29 UTC
# Environment

```none
Windows build number: 10.0.18362.295
Windows Terminal version (if applicable): 0.4.2382.0
Ansible version: 2.5.1
```

# Steps to reproduce

Through ansible-vault commands for encrypting specific variables, we should be able to copy and paste the generated key and encrypted value as the outputted in the terminal. It looks like that windows terminal is adding some characters at the beginning of each line.

```bash
sudo ansible-vault encrypt_string --vault-password-file ~/.ansible_dep_pwd 'value_encrypted' --name 'key'
```

# Expected behavior

The paste result to any code editor or text processor should be like this:

![image](https://user-images.githubusercontent.com/1844840/64254431-c2adf300-cef5-11e9-8d3a-ddc933f1d24d.png)

# Actual behavior

The current result of the paste it's actually like this:

![image](https://user-images.githubusercontent.com/1844840/64254535-01dc4400-cef6-11e9-9efa-5e1c19dea7f2.png)

It looks like multiple tabs or spaces are being added and copy with, generating weird spaced results.

Thanks everyone for having a look at this, great stuff with the terminal and keep the good work!

**Comment by zadjii-msft** [comment] 2019-09-04 12:31
@carlos-zamora 

I know this is a dupe of another copy-paste bug, but I'm not sure which one. Carlos will though :)

**Comment by DHowett-MSFT** [comment] 2019-09-04 22:48
I think this is just #2324.

/dup #2324

**Closed** 2019-09-04 22:48 UTC
Labels: Needs-Tag-Fix, Needs-Triage
