### ISSUE TITLE
Windows Terminal 0.7 immediately crashes on startup

### ISSUE THREAD

**Issue by johnc44** [microsoft/terminal#3747] opened 2019-11-27 15:41 UTC
# Environment

Microsoft Windows [Version 10.0.18363.476]
Windows Terminal 0.7

# Steps to reproduce

Start Windows Terminal.

# Expected behavior

Was hoping the application would open..

# Actual behavior

The terminal icon appears in the start bar, then a moment later it disappears.  The application never starts.

I've been using Windows Terminal for the last few versions and it's been fine.  I upgraded to 0.7 today and now it no longer opens.  I tried uninstalling and reinstalling it.  I also tried explicitly removing profile.json, because i had previously changed it.

I've also tried rebooting.

**Comment by zadjii-msft** [comment] 2019-11-27 15:45
Thanks for the report! Would you mind filing a report with the feedback hub so we can get a stack trace and see what's going on?

/feedback

**Comment by johnc44** [comment] 2019-11-27 15:56
That was quick!  I've submitted something through feedback hub now.  I didn't realise it could be used for things like this.

**Comment by zadjii-msft** [comment] 2019-11-27 16:04
@johnc44 Could you share the `aka.ms` link from the "Share my feedback" button here? I can't look it up without that unfortunately 🤣

**Comment by johnc44** [comment] 2019-11-27 16:09
Oops, sorry - https://aka.ms/AA6ptgu

**Comment by Viruslav** [comment] 2019-11-27 19:01
I have almost the same issue/crash - the window shows as a non-transparent single color rectangle and then disappears. I tried resetting and reinstalling but nothing helped. I tried on 2 very different devices and it was the same. I already submitted a feedback in the Feedback Hub but unfortunately I didn't include a stack trace.

**Comment by zhoupro** [comment] 2019-11-28 03:34
Same problem

**Comment by Ma5ker** [comment] 2019-11-28 08:32
Same problem,Microsoft Windows [Version 10.0.18363.476]

**Comment by johnc44** [comment] 2019-11-28 10:33
Just noticed that I do get a single colour rectangle as per @Viruslav - I just didn't notice it yesterday.

**Comment by gregmuellegger** [comment] 2019-11-28 10:49
Same problem here.

**Comment by a-wasilewski** [comment] 2019-11-28 15:11
Same here. Updated today and app crashes after start. Only single grey color and then window immediately closed.
I updated through MS Store.

**Comment by owennewo** [comment] 2019-11-28 17:42
Something to try...
Delete your terminal settings file (make a backup first!).

My settings file is below but there is a hash in the directory name so yours will probably be different:
`<User>\AppData\Local\Packages\Microsoft.WindowsTerminal_8wekyb3d8bbwe\LocalState\profiles.json
`
My guess is that will get you up on your feet and you could play around with introducing parts of the old file to see what is causing the crash.

**Comment by Viruslav** [comment] 2019-11-28 18:21
I use custom scaling set at 160% on both PCs.

**Comment by owennewo** [comment] 2019-11-28 22:57
It would be useful to know if original poster has custom scaling.  If so this issue can be marked as duplicate of #3749.  It's entirely possible there is more than one reason for startup....

**Comment by elangelo** [comment] 2019-11-29 08:11
I have the same
tried deleting the appdata folder and i have no custom scaling set.

**Comment by johnc44** [comment] 2019-11-29 08:14
@owennewo  Yes, I have custom scaling set to 135%, mirrored displays.  (

I've already tried deleting profile.json which didn't help.

**Comment by marknelson** [comment] 2019-11-29 22:30
this is my first install - i'm seeing the same symptoms. 175% scaling. Yeah, deleted profile, same thing.

**Comment by colcrunch** [comment] 2019-12-01 09:44
I am having the same issue as this after an app update.

Feedback Hub link with Error Logs:
https://aka.ms/AA6q4df

**Comment by vuhg** [comment] 2019-12-02 00:29
Hey guys, several usages are fine with normal 125% scale.
But the Terminal crash when i use **custom scale** 138%.

**Comment by zhoupro** [comment] 2019-12-02 02:53
I disable advanced scale, Now It works fine.

**Comment by zhoupro** [comment] 2019-12-02 02:54
> Hey guys, several usages are fine with normal 125% scale.
> But the Terminal crash when i use **custom scale** 138%.

Thanks for your tips.

**Comment by gregmuellegger** [comment] 2019-12-02 08:45
Disabling custom scaling worked for me as well! Thanks so far.

**Comment by Viruslav** [comment] 2019-12-02 12:31
I'm not gonna change my custom scale factor. I'd rather not use this terminal. I'm sorry but this is not a solution. Everything else works just fine.

**Comment by VictorNanka** [comment] 2019-12-02 13:00
It’s working when I change the custom scale factor into default. Thanks a lot.

**Comment by DHowett-MSFT** [comment] 2019-12-02 20:43
This looks like a /dupe of #3749. Thanks!

**Closed by DHowett-MSFT** 2019-12-02 20:43 UTC
Labels: Issue-Bug, Needs-Attention, Needs-Tag-Fix, Needs-Triage, Product-Terminal, Severity-Crash
