### ISSUE TITLE
Need a commandline option like RemoveWorkingDirectoryTrailingCharacter like powershell

### ISSUE THREAD

**Issue by sushovan** [microsoft/terminal#5939] opened 2020-05-16 14:07 UTC
[Windows Terminal.reg.txt](https://github.com/microsoft/terminal/files/4638644/Windows.Terminal.reg.txt)

I have added "**Open here**" context menu for windows explorer. All working fine except open from any drive.

For this, we need to have a command-line option like RemoveWorkingDirectoryTrailingCharacter (it's in PowerShell context menu).

**Comment by DHowett-MSFT** [comment] 2020-05-16 18:18
Change your directory from `%V` to `%V\.`. This is a /dupe of #4571

**Closed by DHowett-MSFT** 2020-05-16 18:18 UTC
Labels: Needs-Tag-Fix, Needs-Triage
