### ISSUE TITLE
Ubuntu's Vim rerenders text permanetly to Windows Terminal after scrolling

### ISSUE THREAD

**Issue by hgulino** [microsoft/terminal#6379] opened 2020-06-05 22:53 UTC
# Environment

```none
Windows build number: Version 10.0.19041.264
Windows Terminal version (if applicable): Version: 1.0.1401.0

Any other software?
Ubuntu 20.04 LTS
```

# Steps to reproduce

1. Open Ubuntu Bash
2. Enter `vimtutor`
3. Enter `100 j`
_(Checking side of Windows Terminal shows the scroll bar has now altered position)_
4. Scroll up to see copied output from Vim

# Expected behavior

Opening the same file within the default Windows cmd shell runs correctly and doesn't print additional lines to the console. 

# Actual behavior

Vim's rendered text from scrolling isn't outputted to the console after being closed or scrolled through. 

![Screenshot_1](https://user-images.githubusercontent.com/47267453/83928304-2b0b5880-a744-11ea-9b79-45fa64a19356.png)

**Comment by skyline75489** [comment] 2020-06-08 04:23
Originally I was gonna say this is expected since the scrolling is supposed to happen in the perspective of text buffer. Then I checked iTerm2. It behaves differently in a way that I can not describe. It's better but still not perfect.

Still scrolling with scroll bar is supposed to be different than scrolling with `Ctrl+P`. I think this is the common ground we share, right?

**Comment by zadjii-msft** [comment] 2020-06-08 13:43
This is probably #381 - `vim` is using the alt buffer, which doesn't have a scrollback, but ConPTY doesn't quite yet inform the terminal that vim has requested that, so the Terminal is just letting output from vim scroll into the scrollback

**Comment by DHowett** [comment] 2020-06-10 01:02
Yep, looking at it this is a /dupe of #381. Sorry!

**Closed by DHowett** 2020-06-10 01:02 UTC
Labels: Needs-Tag-Fix, Needs-Triage
