### ISSUE TITLE
Text wrap issue with Azure cloud shell

### ISSUE THREAD

**Issue by muhammad-usman-anwar** [microsoft/terminal#3094] opened 2019-10-06 12:25 UTC
Windows 10 Home 1903

```none
Windows build number: 18362.356
Windows Terminal version: 0.5.2762.0
```

1. Open Azure cloud shell
2. resize the window horizontally, using mouse

Text should wrap according to the width of the window

Text disappears, which does not the window and disappears after reducing width and does not come back after increasing it.

**Comment by DHowett-MSFT** [comment] 2019-10-06 17:52
Thanks for the report. This is really a duplicate of #780 (weird enough.) /dup #780

**Closed by DHowett-MSFT** 2019-10-06 17:52 UTC
Labels: Needs-Tag-Fix, Needs-Triage
