### ISSUE TITLE
Feature request: Profile folders

### ISSUE THREAD

**Issue by Husqvik** [microsoft/terminal#6602] opened 2020-06-19 22:26 UTC
# Feature request: Profile folders

When number of profiles grows it would be good to have option to arrange the profiles into folders, like

![Example](https://user-images.githubusercontent.com/6512856/85183110-eecf1080-b28a-11ea-82b8-dc0c51fd5613.png)

**Comment by DHowett** [comment] 2020-06-20 00:23
Thanks for the request! This is a /duplicate of #1571. :smile:

**Closed by DHowett** 2020-06-20 00:23 UTC
Labels: Issue-Feature, Needs-Tag-Fix, Needs-Triage
