### ISSUE TITLE
Split panes vertically: the new panel closes immediately.

### ISSUE THREAD

**Issue by revz79** [microsoft/terminal#7519] opened 2020-09-03 13:13 UTC
# Environment

```none
Windows build number:  10.0.19042.487
Windows Terminal version: 1.2.2381.0

Linux distribution on WSL: Ubuntu 20.04 LTS (GNU/Linux 4.19.84-microsoft-standard x86_64)
```

# Steps to reproduce

1. Default profile set to "{07b52e3e-de2c-5db4-bd2d-ba144ed6c273}"
1. Open Windows Terminal
1. Split vertically the active pane (CTRL + SHIFT + '+')

# Expected behavior

Pane split

# Actual behavior

Pane split, then immediately closes.

It happens only with the WSL profile, with other profiles it behaves correctly.
Splitting panes horizontally works fine with all profiles.

**Comment by DHowett** [comment] 2020-09-03 18:42
I'm guessing you have `closeOnExit` set to `always`, so that if there is an error starting up that profile it will not get a chance to display anywhere?

**Comment by revz79** [comment] 2020-09-06 21:27
> I'm guessing you have `closeOnExit` set to `always`, so that if there is an error starting up that profile it will not get a chance to display anywhere?

You are right, i set it to `never` and now i can see this error:

`[process exited with code 0]`

The error occurs before executing the .bashrc script.
Sometimes i can open a second vertical pane without errors, but the third one fails (either vertical or horizontal). Other times i can't even open a second vertical pane.
Repeatedly splitting horizontally the first pane works like a charm.

**Comment by DHowett** [comment] 2020-09-10 01:20
This is very unusual!

If you open a vertical split with a different profile (like cmd or powershell) and then run `wsl` inside it, does it also exit immediately?

If so, we can start to debug why it's being terminated below a certain size.

**Comment by revz79** [comment] 2020-09-14 06:11
> This is very unusual!
> 
> If you open a vertical split with a different profile (like cmd or powershell) and then run `wsl` inside it, does it also exit immediately?
> 
> If so, we can start to debug why it's being terminated below a certain size.

I think you've got the point:

1. Start windows terminal with default profile
1. ALT + select powershell profile 
Pane splits vertically
1. ` > wsl`
Ubuntu bash opens and stays open
1. ALT + select powershell profile
Pane splits horizontally
1. ` >wsl`
Ubuntu bash opens and stays open
1. ALT + select powershell profile
Last pane splits vertically (that's the third vertical panel)
1. `> wsl`
Ubuntu bash opens  then exit immediately to powershell prompt

**Comment by DHowett** [comment] 2020-09-14 06:33
Great. Can you run `wsl -e /bin/bash -l -i -x` and share a copy of the log it produces? It will help us figure out why the shell is exiting immediately on startup.

If you don’t use bash as your shell inside WSL, substitute in the full Linux path to the shell instead.

**Comment by DHowett** [comment] 2020-09-14 06:33
Sorry, to be clear: run that in a pane that _cannot_ otherwise run WSL.

**Comment by revz79** [comment] 2020-09-14 06:58
Here you are:

```
+ '[' '\s-\v\$ ' ']'
+ '[' /bin/bash ']'
+ '[' /bin/bash '!=' /bin/sh ']'
+ '[' -f /etc/bash.bashrc ']'
+ . /etc/bash.bashrc
++ source /usr/sbin/start-systemd-namespace
++++ ps -ef
++++ grep '/lib/systemd/systemd --system-unit=basic.target$'
++++ grep -v unshare
++++ awk '{print $2}'
+++ SYSTEMD_PID=58
+++ '[' -z 58 ']'
+++ '[' 58 '!=' 1 ']'
+++ export 'PRE_NAMESPACE_PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/mnt/c/Program Files/AdoptOpenJDK/jdk-8.0.202.08/bin:/mnt/c/Perl64/site/bin:/mnt/c/Perl64/bin:/mnt/c/WINDOWS/system32:/mnt/c/WINDOWS:/mnt/c/WINDOWS/System32/Wbem:/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/:/mnt/c/Program Files/PostgreSQL/10/bin:/mnt/c/Program Files (x86)/Microsoft Visual Studio/Shared/Python36_64:/mnt/c/Program Files/Java/jdk1.8.0_162/bin:/mnt/c/WINDOWS/System32/OpenSSH/:/mnt/c/Program Files (x86)/Graphviz2.38/bin:/mnt/c/Program Files/kotlinc/bin:/mnt/c/Development/Android/git-repo:/mnt/c/ProgramData/chocolatey/bin:/mnt/c/Program Files/TortoiseGit/bin:/mnt/c/Program Files/MIT/Kerberos/bin:/mnt/c/Program Files/Git/cmd:/mnt/c/Users/AlbertoFedrici/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/AlbertoFedrici/jili:/mnt/c/Users/AlbertoFedrici/AppData/Local/Programs/Fiddler:/mnt/c/Program Files/Microsoft VS Code/bin:/mnt/c/Users/AlbertoFedrici/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/AlbertoFedrici/AppData/Local/Programs/Microsoft VS Code/bin'
+++ PRE_NAMESPACE_PATH='/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/mnt/c/Program Files/AdoptOpenJDK/jdk-8.0.202.08/bin:/mnt/c/Perl64/site/bin:/mnt/c/Perl64/bin:/mnt/c/WINDOWS/system32:/mnt/c/WINDOWS:/mnt/c/WINDOWS/System32/Wbem:/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/:/mnt/c/Program Files/PostgreSQL/10/bin:/mnt/c/Program Files (x86)/Microsoft Visual Studio/Shared/Python36_64:/mnt/c/Program Files/Java/jdk1.8.0_162/bin:/mnt/c/WINDOWS/System32/OpenSSH/:/mnt/c/Program Files (x86)/Graphviz2.38/bin:/mnt/c/Program Files/kotlinc/bin:/mnt/c/Development/Android/git-repo:/mnt/c/ProgramData/chocolatey/bin:/mnt/c/Program Files/TortoiseGit/bin:/mnt/c/Program Files/MIT/Kerberos/bin:/mnt/c/Program Files/Git/cmd:/mnt/c/Users/AlbertoFedrici/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/AlbertoFedrici/jili:/mnt/c/Users/AlbertoFedrici/AppData/Local/Programs/Fiddler:/mnt/c/Program Files/Microsoft VS Code/bin:/mnt/c/Users/AlbertoFedrici/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/AlbertoFedrici/AppData/Local/Programs/Microsoft VS Code/bin'
+++ set -o posix
+++ set
+++ grep -v '^BASH'
+++ grep -v '^DIRSTACK='
+++ grep -v '^EUID='
+++ grep -v '^GROUPS='
+++ grep -v '^HOME='
+++ grep -v '^HOSTNAME='
+++ grep -v '^HOSTTYPE='
+++ grep -v '^IFS='\''.*
'\'''
+++ grep -v '^LANG='
+++ grep -v '^LOGNAME='
+++ grep -v '^MACHTYPE='
+++ grep -v '^NAME='
+++ grep -v '^OPTERR='
+++ grep -v '^OPTIND='
+++ grep -v '^OSTYPE='
+++ grep -v '^PIPESTATUS='
+++ grep -v '^PS1='
+++ grep -v '^POSIXLY_CORRECT='
+++ grep -v '^SHELL='
+++ grep -v '^PS4='
+++ grep -v '^SHLVL='
+++ grep -v '^PPID='
+++ grep -v '^SYSTEMD_PID='
+++ grep -v '^UID='
+++ grep -v '^USER='
+++ grep -v '^_='
+++ grep -v '^SHELLOPTS='
+++ cat -
+++ echo 'PATH='\''/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/mnt/c/Program Files/AdoptOpenJDK/jdk-8.0.202.08/bin:/mnt/c/Perl64/site/bin:/mnt/c/Perl64/bin:/mnt/c/WINDOWS/system32:/mnt/c/WINDOWS:/mnt/c/WINDOWS/System32/Wbem:/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/:/mnt/c/Program Files/PostgreSQL/10/bin:/mnt/c/Program Files (x86)/Microsoft Visual Studio/Shared/Python36_64:/mnt/c/Program Files/Java/jdk1.8.0_162/bin:/mnt/c/WINDOWS/System32/OpenSSH/:/mnt/c/Program Files (x86)/Graphviz2.38/bin:/mnt/c/Program Files/kotlinc/bin:/mnt/c/Development/Android/git-repo:/mnt/c/ProgramData/chocolatey/bin:I/mnt/c/Program Files/TortoiseGit/bin:/mnt/c/Program Files/MIT/Kerberos/bin:/mnt/c/Program Files/Git/cmd:/mnt/c/Users/AlbertoFedrici/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/AlbertoFedrici/jili:/mnt/c/Users/AlbertoFedrici/AppData/Local/Programs/Fiddler:/mnt/c/Program Files/Microsoft VS Code/bin:/mnt/c/Users/AlbertoFedrici/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/AlbertoFedrici/AppData/Local/Programs/Microsoft VS Code/bin'\'''
+++ exec sudo /usr/sbin/enter-systemd-namespace ''
```

I forgot to mention that I enabled systemd following the steps described here:

https://forum.snapcraft.io/t/running-snaps-on-wsl2-insiders-only-for-now/13033

in order to use Docker inside WSL2 rather than using Docker Desktop

Thanks

**Comment by DHowett** [comment] 2020-09-14 21:27
Ah. That complicates things.

Do you have your own `~/.bashrc`? If so, can you add `set -x` to the top of it, and then launch another failing session?

If not, maybe `~/.bash_profile`?

**Comment by revz79** [comment] 2020-09-16 06:57
Ok, added.
The failing session does not show any debug log, unlike the succeeding ones.
The failing session shows only the MOTD and the "last login" log.

```
Welcome to Ubuntu 20.04 LTS (GNU/Linux 4.19.84-microsoft-standard x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

  System information as of Wed Sep 16 08:50:46 CEST 2020

  System load:                      0.04
  Usage of /:                       23.5% of 250.98GB
  Memory usage:                     1%
  Swap usage:                       0%
  Processes:                        39
  Users logged in:                  1
  IPv4 address for br-4ac2376b3521: <IP address>
  IPv4 address for br-4c160f2f4a9b: <IP address>
  IPv4 address for docker0:         <IP address>
  IPv4 address for eth0:            <IP address>

 * Kubernetes 1.19 is out! Get it in one command with:

     sudo snap install microk8s --channel=1.19 --classic

   https://microk8s.io/ has docs and details.

96 updates can be installed immediately.
5 of these updates are security updates.
To see these additional updates run: apt list --upgradable


Last login: Wed Sep 16 08:50:36 CEST 2020 on pts/2
```

**Comment by DHowett** [comment] 2020-10-23 02:47
I finally decided that I should install a clean Ubuntu 20.04 and set these scripts up so I could repro this, and I'm just _at a total loss_. `systemd` has changed since the scripts were written and it seems like it _made this specific use case much harder_.

Running things with systemd isn't really a supported scenario for WSL, although I do think that it should be, but... we can't really support something that's so off the beaten path here. I don't know why it's exiting when the window is too small, but I'm certain there isn't something Terminal is doing that is going to make that worse.

Might have to close this one for now until we get more info, or an archive that'll help us reproduce it :smile:

**Closed by DHowett** 2020-10-23 02:47 UTC
Labels: Issue-Bug, Needs-Attention, Needs-Tag-Fix, Product-Terminal

**Comment by revz79** [comment] 2020-10-23 06:38
Hi, thanks for your time. FYI I've side installed a second copy of the Ubuntu 20.04 distro, following the same steps for `systemd`.
