### ISSUE TITLE
Feature Request: Add a settings to keep Acrylic when it is unfocused.

### ISSUE THREAD

**Issue by quank123wip** [microsoft/terminal#1099] opened 2019-06-01 09:24 UTC
Just like the title.

**Comment by xa0082249956** [comment] 2019-06-01 15:38
It may be difficult due to the limitations of the OS.

https://docs.microsoft.com/en-us/windows/uwp/design/style/acrylic#usability-and-adaptability
>In addition, only background acrylic will **replace its translucency and texture with a solid color**:
>- When an app window on desktop deactivates
>- When the UWP app is running on phone, Xbox, HoloLens or tablet mode

**Comment by zadjii-msft** [comment] 2019-06-03 13:40
Yea this is a dupe of #593. As much as we'd love to add this, it's out of our control :/

**Closed by zadjii-msft** 2019-06-03 13:40 UTC
Labels: Issue-Feature, Needs-Tag-Fix, Needs-Triage
