### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by prayagsingh** [microsoft/terminal#2966] opened 2019-09-29 10:30 UTC
# Description of the new feature/enhancement
Add tab renaming feature. 

# Proposed technical implementation details (optional)
 Allow End-User to rename the tabs. This feature is required when a user opens more than 2 tabs and the path of PWD is large. Since the tab name is as same as PWD hence user unable to see the other tabs. PFA the snippet. In the snippet, I have opened 4 tabs but only 3 tabs are visible because of PWD path length. 
![Screenshot (47)](https://user-images.githubusercontent.com/8455114/65831001-30212980-e2d2-11e9-8d03-55d62d3ecde9.png)

**Comment by j4james** [comment] 2019-09-29 13:02
This sounds like a duplicate of #1079

**Comment by zadjii-msft** [comment] 2019-09-30 13:15
Yep, this is a little bit #1079 and a little bit #2304 

/dup #1079 #2304

**Closed by zadjii-msft** 2019-09-30 13:16 UTC
Labels: Issue-Feature, Needs-Tag-Fix, Needs-Triage
