### ISSUE TITLE
allow ctrl-v to be overriden

### ISSUE THREAD

**Issue by pm100** [microsoft/terminal#16280] opened 2023-11-07 21:09 UTC
# Description of the new feature/enhancement

Today regardless of any mode settings ctrl-v is always processed by terminal rather than passing it to the app. This is not convenient because:
- maybe ctrl-v means something else to the app
- asymmetry, ctrl-c is passed to the app if ENABLE_PROCESSED_INPUT is off but ctrl-v is not. If I have my own 'clipboard' then the ctrl-v will paste the wrong text
- with multi line pastes I get a popup dialog warning me (imagine if vs code did this on every paste)
- The paste comes in as separate keys strokes, not as one operation, so if I support undo then on a 50 char paste I have to press undo 50 times
- the ctrl-v paste is slow since the app sees it as multiple keystrokes rather than one large insert
- A large paste might even overflow my undo history stack so its not undoable at all

 Others have reported this issue and all the suggestions and proposed solutions are not really useful 
- change the keyboard settings. Problem is that I want ctrl-v to work elsewhere, on the command line say
- terminal detects the name of the executable (vim.exe), this is plainly not workable
- only needed for WSL - not enough

# Proposed technical implementation details (optional)

either 
 - ENABLE_PROCESSED_INPUT=0 should disable ctrl-v as well as ctrl-c. This is a theoretically breaking change
 - a new DONT_PASTE flag in console mode settings

**Comment by DHowett** [comment] 2023-11-07 21:11
> Today regardless of any mode settings ctrl-v is always processed by terminal
> Others have reported this issue and all the suggestions and proposed solutions are not really useful
> * change the keyboard settings. Problem is that I want ctrl-v to work elsewhere, on the command line say

Would you be able to elaborate on this? Deleting the <kbd>Ctrl+V</kbd> key binding from Windows Terminal's settings is quick and easy, and doesn't require you to change any keyboard configuration.

Thanks!

**Comment by pm100** [comment] 2023-11-07 21:17
I only want it for the app I am writing (just like vim, nano,... that have also complained about the same thing) not globally. ie the app needs to turn it on and off, just like I can turn ctrl-c on and off programmatically. It should not have to be :
- a global change
- done by the end user

**Comment by j4james** [comment] 2024-05-03 22:26
See also #11267

**Comment by zadjii-msft** [comment] 2024-06-06 10:09
You know what? You're absolutely right. This is a /dupe of #11267. We'll consolidate tracking there, thanks!

**Closed by zadjii-msft** 2024-06-06 10:09 UTC
Labels: Issue-Feature, Needs-Attention, Needs-Tag-Fix, Needs-Discussion

**Comment by MogHughson** [comment] 2024-08-24 04:49
This issue precisely articulates the problem I am seeing. Did this get fixed? How can an application turn off Ctrl-C and Ctrl-V being grabbed by the terminal while it is running without asking the user to change the settings in the Terminal?
