### ISSUE TITLE
[FR] New 'selectAll' shortcut action with default mapping ctrl+shift+a

### ISSUE THREAD

**Issue by iamGavinJ** [microsoft/terminal#3723] opened 2019-11-26 23:26 UTC
# Description of the new feature/enhancement
Create a new shortcut action to select all text in the buffer

# Proposed technical implementation details (optional)
ctrl+shift+a should select all text

**Comment by j4james** [comment] 2019-11-27 00:53
This is probably covered by #1469, which was also suggesting the need for a _Select All_ key binding.

**Comment by DHowett-MSFT** [comment] 2019-11-27 01:31
Yep, this is a /dupe of #1469.

**Closed by DHowett-MSFT** 2019-11-27 01:31 UTC
Labels: Issue-Feature, Needs-Tag-Fix, Needs-Triage

**Comment by iamGavinJ** [comment] 2019-11-27 03:38
@j4james, @DHowett thanks for finding the dupe.  I did do a brief search as I really didn't believe I would be the first to raise this but none of my search terms were turning anything up.
