### ISSUE TITLE
Black Background is either transparent or not rendered.

### ISSUE THREAD

**Issue by sp1ritCS** [microsoft/terminal#3462] opened 2019-11-06 19:46 UTC
# Environment

```none
Microsoft Windows [Version 10.0.18362.418]
Windows Terminal version (if applicable): 2019.1022.2157.0

Any other software?
(WSL)
```

I originaly asked this as a question on the unix stackexchange, because I thought this to be an issue with the WSL and not windows terminal. ([Original Question](https://unix.stackexchange.com/questions/550033/ansi-40-black-background-does-not-work-in-wsl-using-windows-terminal))

# Steps to reproduce

Add the following Color scheme (or any other, I tried It didn't matter) to the profiles.json
```json
{
    "background": "#ECF0F1",
    "black": "#2C3E50",
    "blue": "#3498DB",
    "brightBlack": "#95A5A6",
    "brightBlue": "#3498DB",
    "brightCyan": "#1ABC9C",
    "brightGreen": "#2ECC71",
    "brightPurple": "#9B59B6",
    "brightRed": "#E74C3C",
    "brightWhite": "#ECF0F1",
    "brightYellow": "#F1C40F",
    "cyan": "#1ABC9C",
    "foreground": "#7F8C8D",
    "green": "#2ECC71",
    "name": "Flat Light",
    "purple": "#9B59B6",
    "red": "#E74C3C",
    "white": "#e0e0e0",
    "yellow": "#F1C40F"
}
```
And enable it for any profile. (I tried WSL (Arch & Ubuntu) aswell as cmd)
Now if you try to get an black background of some sort. You'll get the background color.
![1](https://user-images.githubusercontent.com/31540351/68331725-c288ca00-00d5-11ea-88ae-a9b4f2f8c30c.png)

I tried `printf "\033[40;30mNot a black background"` on WSL aswell as `color 0f` on cmd.

# Expected behavior

The blackground is suposed to be black (grayish blue) on ASNI 40.

------------------

I assume that this is the result of my incompetence rather that an actual bug, but in this case the documentation should be updated.

**Comment by DHowett-MSFT** [comment] 2019-11-06 23:13
This is a /dupe of #293. Sorry for the confusion!

**Closed by DHowett-MSFT** 2019-11-06 23:13 UTC
Labels: Needs-Tag-Fix, Needs-Triage
