### ISSUE TITLE
[Terminal] VT Mouse Support

### ISSUE THREAD

**Issue by cerebrate** [microsoft/terminal#545] opened 2019-05-08 00:05 UTC
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)

10.0.18890.1000

* What you're doing and what's happening: (Copy & paste specific commands and their output, or include screen shots)

I routinely use mouse mode in tmux with WSL for window selection, pane resizing, and scrollback, enabled in tmux.conf thus:

```
  # -- mouse support ---------------------------------------------------------                                                                                                                                                                                        
  # Enable mouse control (clickable windows, panes, resizable panes)                                                                
  set -g mouse on
```

While this works perfectly in conhost, it does not work at all in Terminal; nothing happens, as if the mouse events were never reaching tmux.

* What's wrong / what should be happening instead:

tmux mouse support (and presumably other mouse-supporting applications) should work as they do in conhost.

**Comment by guibirow** [comment] 2019-06-25 13:09
Sadly this does not work, having the mouse events with TMUX would defer the need to have multiple panes.
I hope this feature get implemented before the panes, is much needed and will solve most of issues

**Comment by jgkawell** [comment] 2019-06-28 14:55
I would like to point out that the mouse support is also not supported in tmux within Docker (through Powershell). I know this is because the functionality simply isn't there in Terminal so of course it won't work in WSL or Docker, but thought I'd go ahead and mention it.

**Comment by guibirow** [comment] 2019-06-28 18:21
the mouse does work in WSL

**Comment by kumarharsh** [comment] 2019-06-28 21:05
Mouse works with wsltty: https://github.com/mintty/wsltty

**Comment by jgkawell** [comment] 2019-06-28 21:08
@guibirow Maybe it's an issue with Docker from within Terminal then.

**Comment by kumarharsh** [comment] 2019-06-28 21:14
No. It's not an issue with Docker. It's an issue with conpty (this repo). Try wsltty if you want mouse support.

**Comment by jgkawell** [comment] 2019-06-28 21:18
Are there plans to enable full mouse support in tmux for Docker in the future through Terminal?

**Comment by kumarharsh** [comment] 2019-06-28 21:24
I don't know about Docker specifically, but i sight see why it should be any different than a normal terminal. This issue is about that so keep an eye.

**Comment by jgkawell** [comment] 2019-06-28 22:13
So I just checked tmux through WSL 1 in Terminal and the mouse isn't supported there either. So my guess is that tmux itself just doesn't work in Terminal at this point and that it's not a Docker issue.

**Comment by guibirow** [comment] 2019-06-28 22:19
You have to run a command to enable it, isn't enabled by default.
I don't have it right now, but it is simple like this `set mouse on` 
I will have to confirm next week when I get my laptop

**Comment by jgkawell** [comment] 2019-06-28 22:27
Oh I gotcha. Yeah it works fine in the plain WSL window. It only fails to work when embedded within the new Windows Terminal.

**Comment by egmontkob** [comment] 2019-07-09 00:06
If you implement mouse support, please make sure to implement the SGR (1006) extension as well.

The legacy, byte-based protocol only allows row and column numbers up to 223, because 32 is added to this number and this is sent as a single byte. The column limit is not uncommon to be too small. (By the way, beginning at column 95 the generated data is not 7-bit clean and not valid UTF-8 which is a problem for encoding conversion layers such as luit.)

The SGR 1006 extension fixes these problems by encoding the numbers as decimal digits, and is supported by plenty of applications.

If this extension is not requested, please don't generate any event if the row or column exceeds 223. Otherwise an overflow could have nasty consequences. E.g. clicking on column 227 could generate the byte 32+227 = 259 = 3 = Ctrl+C which is typically the interrupt character sending a SIGINT to the running process.

**Comment by DHowett-MSFT** [comment] 2019-07-09 00:24
So! Conhost actually does support DECSET `1006`! Since we have this intervening layer (the pseudoconsole, which needs to talk to conhost), we get to choose what sort of mouse mode the pseudoconsole requests and supports. I see no reason that that shouldn't just be `1006` :smile: Thanks for the info!

**Comment by DHowett-MSFT** [comment] 2019-07-09 00:31
To clarify, because we have conhost in the middle, that would look like this:

```
                                      +-----------------+
                                      |                 |
                 DECSET 1002, 1005    | Windows conhost |
+-------------+                       |  (in PTY mode)  |
|             +----------------------->                 |
| Application |                       |                 |
|             <-----------------------+                 |
+-------------+                       |                 |
                 mouse information    |                 |
                 1002 in 1005 format  |                 |
                                      |                 |
                                      +---+---------^---+
                                          |         |
                                          |         | mouse information in
                              DECSET 1006 |         | SGR Extended Format
                                          |         | (1006)
                                          |         |
                                      +---v---------+---+
                                      |                 |
                                      | Windows         |
                                      |  Terminal       |
                                      |                 |
                                      |                 |
                                      |                 |
                                      |                 |
                                      +-----------------+
```

**Comment by egmontkob** [comment] 2019-07-09 11:21
Did you mean 1005 between the application and conhost, or is that a typo in this picture? Mouse extensions 1005 and 1015 also exist but they are hardly used (if at all) due to their flaws, it's not something that applications are interested in.

1005 (xterm's two-byte UTF-8), 1015 (urxvt) and 1006 (xterm SGR), in this chronological order, are three mutually exclusive extensions to address the limitation of the column number. See e.g. Midnight Commander issues [2662](https://midnight-commander.org/ticket/2662) and [2956](https://midnight-commander.org/ticket/2956) for technical description about the flaws of the first two. Note that this story is now 6-8 years old. I'm not aware of any application that supports the problematic 1005 and/or 1015 but not the okay 1006. As such, I don't see any point in implementing support for the first two (although it should be very easy to implement them).

**Comment by zadjii-msft** [comment] 2019-07-09 12:32
That very well could be a typo, right now, conhost actually supports [a bunch of different mouse modes](https://github.com/microsoft/terminal/blob/master/src/terminal/adapter/DispatchTypes.hpp#L82-L86), including, but not limited to 1005 and 1006.

**Comment by DHowett-MSFT** [comment] 2019-07-09 15:04
It’s not a typo. Sorry, this was intended to illustrate how the pseudoconsole system could support a bunch of mouse modes on the client end (an application requests 1005, 1015, legacy VT220, etc.) but present a unified mouse mode interface (1006) to the pty pipe holder.

**Comment by DHowett-MSFT** [comment] 2019-07-09 15:05
That diagram admittedly fits better in #376, which is the infrastructural part of this bug.

**Comment by egmontkob** [comment] 2019-07-09 15:17
@DHowett-MSFT Awesome, thanks for the clarification!

**Comment by rcarmo** [comment] 2019-08-03 12:06
I'm eagerly awaiting this to show up in a future release - I keep clicking on tmux panes in hopes the mouse will work :)

**Comment by sandric** [comment] 2019-12-16 08:32
Any progress on this?

**Comment by zadjii-msft** [comment] 2019-12-16 13:39
@sandric Not particularly - when there's something of note to share, we'll make sure to post in this thread 😜 

@carlos-zamora is starting this work this month (as you can see from the "assigned to" and "milestone" fields to the right). He's got a PR (#3963) out starting on work for #376, one of the prerequisites for this feature.

**Comment by fpqc** [comment] 2020-02-16 19:40
@zadjii-msft The PR you linked says it was merged Is that correct now?

**Comment by tjhowse** [comment] 2020-02-17 01:40
Based on the comment in the release notes:

> The pseudoconsole will now process mouse escapes, but it won't do much useful with them yet (#3963)
It seems not (yet). I'm staying tuned!

**Comment by zadjii-msft** [comment] 2020-02-18 14:49
@fpqc yep, that's correct, that one PR was merged. From that discussion, there's still a bunch of work needed before this will work fully in the Terminal:

> * [ ]  Conpty emits a [sequence] on entering any mouse mode to tell terminals that they should synthesize VT Mouse Mode input as SGR sequences (with hover, scroll, etc)
> * [ ]  Conhost translates Mouse input into VT from both conpty and the HWND the same way
> * [ ]  Terminal can consume [sequence] to synthesize VT mouse mode input

And then of course, this issue:
* [ ] Terminal synthesizes mouse input sequences

**Closed** 2020-03-13 00:44 UTC
Labels: Area-Input, Area-VT, In-PR, Issue-Feature, Product-Terminal

**Comment by giggio** [comment] 2020-03-17 01:42
How do we copy the text when VT Mouse is enabled? I couldn't do it on Vim or Tmux.

**Comment by DHowett-MSFT** [comment] 2020-03-17 01:47
Hold down shift to interact with the terminal itself instead of the application inside it.

**Comment by PetterS** [comment] 2020-03-17 07:21
This is so great! When will we see a preview of this in the Store?

**Comment by DHowett-MSFT** [comment] 2020-03-17 07:30
Stay tuned

**Comment by yveslange** [comment] 2020-03-18 07:13
Downloaded from the shop! The mouse is working great in VIM, htop and Tmux. Finally, time to move from all other WSL Terminal to the microsoft one ! Good job guys and thanks a lot !

**Comment by jsbarrett** [comment] 2020-03-21 23:56
Just came here looking for why mouse wasn't working ... read the most recent comment from @yveslange and then updated the app ... and now mouse works perfect.

Thanks guys!

**Comment by nicolus** [comment] 2020-03-29 13:04
@DHowett-MSFT : Mouse still doesn't work for me with Micro (https://github.com/zyedidia/micro), whereas both mouse and scrollwheel work flawlessly in the default powershell or cmd.exe terminal. Is mouse support only working in WSL for now ?

**Comment by zadjii-msft** [comment] 2020-03-30 14:31
@nicolus indeed, mouse input only works for WSL applications currently. If you're using the Win32 version of micro, I'd bet that it won't work quite yet. You could probably work around this by running the WSL version for now. #376 is the issue we're using for the Windows mouse input

**Comment by CodeMonkey90** [comment] 2020-05-11 18:19
@zadjii-msft 
Mouse events don't work for me with a custom profile with `"commandline": "ssh [...]"`. Is this also expected until #376 is resolved? Is there a good workaround?

**Comment by DHowett-MSFT** [comment] 2020-05-11 18:26
This is a result of https://github.com/PowerShell/Win32-OpenSSH/issues/1310, which is (mercifully) fixed in the 8.x series.

**Comment by CodeMonkey90** [comment] 2020-05-11 18:31
@DHowett-MSFT Thanks for the quick reply. In that case, is there a sane way to manually upgrade to a version with the fix right now or is it better to just wait?

**Comment by DHowett-MSFT** [comment] 2020-05-11 18:45
Sure, just download the latest release from their Releases page!

**Comment by rfc805** [comment] 2021-08-09 19:16
I don't see it here or in the documentation, but how do you turn this behavior off entirely?  It's incredibly annoying for people who don't want to have mouse interactions pass through.  Holding shift is not a good option.

**Comment by zadjii-msft** [comment] 2021-08-09 19:27
@rfc805 there isn't a setting to disable this entirely - I'm not sure I've heard anyone request that before. Typically this is something that's controlled per-client application on other platforms, within the app's own config. Is there some app (`vim`, `tmux`, etc) in particular that's requesting mouse mode that you can't disable mouse input for?

**Comment by rfc805** [comment] 2021-08-09 19:30
It's mostly vim (over ssh) but on a large variety of hosts which aren't related, which makes it non-trivial to globally disable in unlinked/unshared profiles across a few hundred different remote hosts.  A lot of it involves copying data from those hosts across each other, or to other Windows apps, etc - so I find myself holding shift down my whole life if I use terminal instead of putty/mintty.

**Comment by zadjii-msft** [comment] 2021-08-09 19:39
You know, this actually already _is_ on the backlog. I'd go upvote #4875 ☺️

**Comment by paukul** [comment] 2021-08-09 19:40
@rfc805 `:set mouse-=a` in vim will disable the mouse support for vim and should work around your issue until #4875 is merged

**Comment by rfc805** [comment] 2021-08-09 19:44
Thanks - I do know how to do it each time, just overall a productivity killer if you work in a large environment with a profile you do not control.
