### ISSUE TITLE
Wrong text size when running “sudo apt update”

### ISSUE THREAD

**Issue by win98se** [microsoft/terminal#3508] opened 2019-11-10 06:25 UTC
# Environment

```none
Windows build number: 10.0.18363.448
Windows Terminal version (if applicable): 0.6.2951.0

Any other software? None
```

# Steps to reproduce

Run `sudo apt update`.

# Expected behavior

The line with `‘apt list --upgradable’` should display with the correct text size, as in Windows Console:

![image](https://user-images.githubusercontent.com/11819816/68539913-1856be00-03c5-11ea-9128-bd2e8afc835b.png)

I'm using the Simplified Chinese language edition of Windows, and Windows Console uses SimSun, 12pt as default font.

# Actual behavior

The same line in Windows Terminal displays with the wrong text size:

![image](https://user-images.githubusercontent.com/11819816/68539917-2c9abb00-03c5-11ea-9050-c50e7fb808c6.png)

The font I use is Noto Sans Mono CJK SC, 12pt.

**Comment by etern** [comment] 2019-11-11 05:09
#2191

**Comment by zadjii-msft** [comment] 2019-11-11 13:55
Also related: #610, #900

I have a _feeling_ these will all come down to the same thing, but I'll leave this open just to make sure.

**Comment by miniksa** [comment] 2019-11-11 20:44
This looks just like a /dupe of #2191 to me, but it's probably related to all of them.

**Closed by miniksa** 2019-11-11 20:44 UTC
Labels: Area-Fonts, Area-Rendering, Issue-Bug, Needs-Triage, Product-Terminal
