### ISSUE TITLE
Windows Terminal Preview hangs on Windows 11

### ISSUE THREAD

**Issue by daxian-dbw** [microsoft/terminal#14476] opened 2022-12-01 22:29 UTC
### Windows Terminal version

 1.16.2642.0

### Windows build number

10.0.22621.819

### Steps to reproduce

There is no consistent reproduction. It happens often enough, usually after logged in Windows after logging out for a while or after waking up the machine from sleep.

**Dump file:** The dump file can be downloaded from https://1drv.ms/u/s!AvrzkkkRHNSrhic-ffAuUGxdtbc_?e=0LhRhk

When this happens, I cannot open another Windows Terminal, but have to forcefully close the one that is hanging.
Below is a screenshot of the Windows Terminal when it happens. Please note the small _close_ button highlighted in the red circle. This small _close_ button stays even after forcefully closing the Windows Terminal process, and I have to click on it to make that button disappear.

![image](https://user-images.githubusercontent.com/127450/205170446-72a7099b-a77f-41f1-a72d-d465be9c21e0.png)

### Expected Behavior

Windows Terminal should not hang

### Actual Behavior

It hangs from time to time.

**Comment by zadjii-msft** [comment] 2022-12-01 22:47
main thread is in `OnDwpSysCommand` north of DefWndProc

`message`, `wparam`, `lparam`= `0x112, 0x0f020, 0`


Never seen one of these before:

```
:013> k
 # Child-SP          RetAddr               Call Site
00 00000012`8d1ff658 00007ffc`9bf91b86     win32u!ZwUserGetMessage+0x14 [onecoreuap\windows\core\umode\moderncore\objfre\amd64\usrstubs.asm @ 189] 
01 00000012`8d1ff660 00007ffc`91035065     user32!GetMessageA+0x46 [onecoreuap\restricted\windows\inc\private\core\ntuser\client\ntcftxt.h @ 537] 
02 00000012`8d1ff6c0 00007ffc`9c71244d     winmm!mciwindow+0x135 [multimedia\media\winmm\mmwnd.cpp @ 457] 
03 00000012`8d1ff760 00007ffc`9d2cdfb8     kernel32!BaseThreadInitThunk+0x1d [clientcore\base\win32\client\thread.c @ 75] 
04 00000012`8d1ff790 00000000`00000000     ntdll!RtlUserThreadStart+0x28 [minkernel\ntdll\rtlstrt.c @ 1166] 

```


That small close button is a conhost process, with a window that _should not be visible_. Next time this happens, there should be an `openconsole.exe` in the Terminal process tree. Mind grabbing a dump of that?

**Comment by zadjii-msft** [comment] 2022-12-01 22:50
Wait there's an internal mail thread for this one already. This is a /dupe of #14134

**Closed by zadjii-msft** 2022-12-01 22:50 UTC
Labels: Issue-Bug, Needs-Triage
