### ISSUE TITLE
Add ability to restart a pane/tab

### ISSUE THREAD

**Issue by markdomansky** [microsoft/terminal#9178] opened 2021-02-15 19:22 UTC
# Description of the new feature/enhancement

I'd like to see the ability to restart a pane/tab without altering the order or arrangement of tabs/panes.
See ConEmu's "recreate active console" feature.  This allows you to restart a console pane/tab without closing it.  The chosen console is closed, then a new console started with the same command line.

PowerShell occasionally needs to be restarted (unrelated to WT, this happens in its own console as well) but I don't want to lose the arrangement of panes.

Please make it available via customizable keyboard shortcut.

**Comment by DHowett** [comment] 2021-02-15 19:24
Thanks for the request! This looks like a /duplicate of #3726 (except it says tab instead of pane; it was likely filed before pane knowledge was widespread.)

**Closed by DHowett** 2021-02-15 19:24 UTC
Labels: Issue-Feature, Needs-Tag-Fix, Needs-Triage
