### ISSUE TITLE
Paste from terminal to outlook comes out at really small font size

### ISSUE THREAD

**Issue by anilruia** [microsoft/terminal#15043] opened 2023-03-24 23:38 UTC
### Windows Terminal version

1.17.1023

### Windows build number

10.0.22621.1413

### Other Software

cmd

### Steps to reproduce

Configure terminal with Cascadia Mono font size 10, cut-n-paste some text from a command window to outlook. The text shows up in Cascadio Mono font size 5 instad.

### Expected Behavior

Text should paste with formatting in the same font size.

### Actual Behavior

Text pastes with formatting with much smaller font size.

**Comment by j4james** [comment] 2023-03-25 11:38
This sounds like a duplicate of #14762.

**Closed** 2023-03-27 16:44 UTC
Labels: Issue-Bug, Needs-Triage, In-PR
