### ISSUE TITLE
Can not type Chinese letter after update to version 0.10.781.0.

### ISSUE THREAD

**Issue by flying1020** [microsoft/terminal#5307] opened 2020-04-10 05:06 UTC
# Environment

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Windows Terminal version (if applicable):

Any other software?
```

# Steps to reproduce

# Expected behavior

# Actual behavior

**Comment by Domain** [comment] 2020-04-11 06:05
I can input Chinese at the beginning. But once I delete the input during composition, I cannot input Chinese anymore until starting a new tab.

**Comment by jdebp** [comment] 2020-04-11 10:02
This appears to be a duplicate of #5282 and #5054.

**Comment by zadjii-msft** [comment] 2020-04-13 14:01
Well, the original post in this thread doesn't actually give us any information to work with, so I'm gonna close this as a dupe of the aforementioned issues. If OP wants to come back in and provide more details as to what might be wrong, and why it's _not_ a duplicate, we can re-open.

Thanks!

/dupe #5282 #5054

**Closed by zadjii-msft** 2020-04-13 14:01 UTC
Labels: Needs-Tag-Fix, Needs-Triage
