### ISSUE TITLE
Allow making the cursor not to blink

### ISSUE THREAD

**Issue by joca-bt** [microsoft/terminal#10214] opened 2021-05-26 17:02 UTC
# Description of the new feature/enhancement

Add an option to allow the cursor not to blink. Right now it blinks all the time, expected when unfocused, which makes the cursor disappear.

**Comment by j4james** [comment] 2021-05-26 21:56
This is a duplicate of #1379.

**Comment by joca-bt** [comment] 2021-05-26 22:11
Closed as it's a duplicate.

**Closed** 2021-05-26 22:10 UTC
Labels: Issue-Feature, Needs-Tag-Fix, Needs-Triage
