### ISSUE TITLE
Links/URLs get offset when certain unicode characters are printed

### ISSUE THREAD

**Issue by Entrivax** [microsoft/terminal#8709] opened 2021-01-05 21:55 UTC
# Environment

```none
Windows build number: Windows 10 version 2004 (10.0.19041.0)
Windows Terminal version: Preview 1.5.3242.0
```

# Steps to reproduce

Print certain unicode characters like this one: `𝓐`

# Expected behavior

Links/URLs should be valid.

# Actual behavior

Links/URLs get offset and break with the presence of certain unicode characters.
For example, if the following text is printed:
```none
𝓐𝓐𝓐
https://microsoft.com/
```
![image](https://user-images.githubusercontent.com/1197915/103703785-77ec3180-4fa8-11eb-888f-536ac6a8271c.png)

The hoverable link, clickable link and opened link is `ps://microsoft.com/   `
If those unicode characters are not printed (if you scroll for example), the links work again.

https://user-images.githubusercontent.com/1197915/103703479-e54b9280-4fa7-11eb-9394-4d6bd81e952d.mp4

Note that the emoji doesn't cause the issue.
The code used in the video is:
```js
console.log(`𝓐𝓐𝓐𝓐𝓐𝓐 123 https://microsoft.com/

✨ https://google.com/
https://google.fr/
https://youtube.com/
https://aka.ms/`)
```

**Comment by zadjii-msft** [comment] 2021-01-06 14:03
Oh weird. I would have thought this was a dupe of #8121, but that one was fixed in 1.5.3142, so this must be it's own variation on the subject.

Those 𝓐 characters are really messing it up, huh.

**Comment by Entrivax** [comment] 2021-01-06 14:22
It looks a lot like it, going the other way from the screen of that issue.

> Those 𝓐 characters are really messing it up, huh.

Yeah, I found the problem when printing display usernames from an api. Not only the `𝓐` character, but also the rest of the alphabet written like that. Maybe there is more characters than that, I didn't try to find them all.

**Comment by skyline75489** [comment] 2021-01-09 03:10
The 𝓐 is considered as two wide chars because of #8124. Another place we might want to use a comprehensive Unicode width estimator .

**Comment by ZeddG93** [comment] 2021-05-10 08:19
![image](https://user-images.githubusercontent.com/7886856/117627966-39ab8c80-b1ab-11eb-9d8f-ed37eb510958.png)

**Comment by mas90** [comment] 2021-07-22 13:33
> Yeah, I found the problem when printing display usernames from an api. Not only the `𝓐` character, but also the rest of the alphabet written like that. Maybe there is more characters than that, I didn't try to find them all.

Definitely more characters than that, e.g. 🎟.

`echo -e '\xf0\x9f\x8e\x9f http://www.example.com/'` reproduces the bug on version 1.9.1445.0.

**Closed** 2021-12-09 18:42 UTC
Labels: Area-Rendering, Issue-Bug, Area-TerminalControl, Product-Terminal, In-PR, Priority-2

**Comment by DHowett** [comment] 2021-12-14 02:56
Clever quick fix -- thanks @Comzyh! I'm rolling this into the 1.11 and 1.12 servicing releases we're putting out to make Terminal more robust over the holidays. :)

**Comment by CerebralDatabank** [comment] 2024-03-28 19:19
I'm still having this issue with 5-digit Nerd Font Unicode characters on Windows 11…

![image](https://github.com/microsoft/terminal/assets/24465111/07adc65c-e3b8-4f06-ad58-80120f0a2662)

**Comment by DHowett** [comment] 2024-03-28 19:30
Which version of Terminal are you using? This issue was closed two years ago 🙂

**Comment by j4james** [comment] 2024-03-28 20:04
@DHowett I think this regressed recently, because I was able to reproduce the issue until I got the update from 3 days ago. I'm assuming it was fixed by this:
> Auto-detected URLs and search results are no longer pushed around by wide characters (oops) (https://github.com/microsoft/terminal/pull/16787)

@CerebralDatabank Bottom line is you probably just need to get the very latest update.

**Comment by DHowett** [comment] 2024-03-28 20:31
> thought replying here was better

you know what, that's totally fair! hah!

> will that mess up the ... link

Nope, you can install the `msixbundle` from here and it will still hook up to the store for future updates!
