### ISSUE TITLE
Bug Report: Space in commandline

### ISSUE THREAD

**Issue by jadedrip** [microsoft/terminal#1506] opened 2019-06-24 03:44 UTC
My config file:

{
            "acrylicOpacity" : 0.75,
            "closeOnExit" : false,
            "colorScheme" : "Campbell",
            "commandline" : "cmd.exe /k \"C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Auxiliary\\Build\\vcvars64.bat\"",
            "cursorColor" : "#FFFFFF",
            "cursorShape" : "bar",
            "fontFace" : "Consolas",
            "fontSize" : 12,
            "guid" : "{e319bb19-0ab7-4f16-a7a2-b76c321d50c2}",
            "historySize" : 9001,
            "name" : "x64 Native Tools Command Prompt for VS 2019",
            "padding" : "0, 0, 0, 0",
            "snapOnInput" : true,
            "useAcrylic" : true,
            "backgroundImage":"‪D:\\Pictures\\star.png"
}

Outout:
'C:\Program' 不是内部或外部命令，也不是可运行的程序

**Comment by DHowett-MSFT** [comment] 2019-06-24 04:50
This is a duplicate of #1090. Please make sure you search before reporting.

**Closed by DHowett-MSFT** 2019-06-24 04:50 UTC
Labels: Needs-Tag-Fix, Needs-Triage

**Comment by fcharlie** [comment] 2019-07-12 03:01
Fix by PR: https://github.com/microsoft/terminal/pull/1815
