### ISSUE TITLE
Make certain that the cursor can invert/not-occlude/display the character under it

### ISSUE THREAD

**Issue by DHowett** [microsoft/terminal#9610] opened 2021-03-25 00:38 UTC
> I've been using WSL for a while and it's been great, but using nvim with this issue still pending is at times unusable. Other terminals are not having this issue (see ConEmu or Hyper for example). I hope this issue gets re-opened.

_Originally posted by @n1ghtmare in https://github.com/microsoft/terminal/issues/1203#issuecomment-801461436_

> I'm with @n1ghtmare on this one. Most syntax highlighting colors in Vim have a wide array of colors that very much clash with the cursor color when the cursor color isn't able to be swapped to a contrasted color dynamically. This has been demonstrated in the few screenshots I uploaded before. It affects everyone using terminal Vim or another terminal based text editor.
>
> I know @pianocomposer321 said to pick a better color for the cursor but this doesn't make a difference in the end. If he adjusted his screenshot to be over a comment instead of the  keyword then the comment's character under the cursor would be invisible. Also in his current screenshot the contrast is very low, it would certainly not be good enough for a video recording or giving a talk.
>
> As good as the MS terminal is, I still tend to use wsltty (which dynamically sets its cursor color based on contrast calculations) in my day to day because having a block cursor in terminal Vim is much better than the vintage cursor in the MS terminal. Not just from a legibility POV, but it allows you to configure Vim so that your cursor shape changes from the block cursor to a line cursor depending on if you're in normal or insert mode.

_Originally posted by @nickjj in https://github.com/microsoft/terminal/issues/1203#issuecomment-801475389_

Subscribers, thumbs-uppers from that comment: @krage, @saurik, @krage

**Comment by zadjii-msft** [comment] 2021-03-25 11:03
I KNEW THERE WAS AN EXISTING ISSUE!

Part of the trick here is that when the `Renderer` is drawing runs of text, it doesn't know where the cursor is. So it needs to be able to split the run with the cursor in it, so it can draw {text left of the cursor, text where the cursor is, text to the right of the cursor }.

Presumably, if there's a way of doing it without doing all the work in #6193, that'd be cool. I had all these ideas before in #6151 for different ways of specifying how the text at the cursor should look. Something like `"cursorTextColor": null|"textForeground"|"#rrggbb"`.

**Comment by DHowett** [comment] 2021-03-26 16:50
The thing I was toying with, which initially made me think that this would be _easy_, was drawing a D2D "fill effect" (that is: a command buffer that produces a flood fill) through the image/effect drawing pipeline with the XOR composition mode. It was promising, but it only worked where we weren't already drawing a background. Everything goes pear-shaped when you _are_ drawing a background color. :smile:

**Comment by DHowett** [comment] 2021-03-26 20:29
However, it looks like we can use the 2-pass cursor renderer @zadjii-msft wrote to backplate the color for a destination-inversion cursor.

**Comment by DHowett** [comment] 2021-03-26 20:41
![it puts the cursor on its skin](https://user-images.githubusercontent.com/189190/112690422-bd065e00-8e49-11eb-9eb9-073828b45b3f.gif)

**Comment by nickjj** [comment] 2021-03-27 16:41
Looks like a really good start, nice work. Could this be something that gets backported into the current stable release as a hotfix once you're happy with its performance and stability? It feels like such a huge feature that it transforms the entire experience for anyone who might be using Vim.

**Comment by Pirastrino** [comment] 2021-03-29 10:56
Imo, there are 3 possible solution to this:
 * calculate contrast color from the current foreground
 * use terminal background color
 * define background and foreground color for the cursor

Calculated contrast color may not have enough contrast to the cursor's background color (even visible in the post above (purple cursor + inverted color - blue) and it may be distracting for some users. I agree it should be the default behavior but also, there should be a possibility to use a custom cursor foreground color defined by user or system background as default, something like: Cursor color = (contrast color | system background | custom cursor foreground) in profile settings.

But I see that the main issue here is the cursor position between renders so thank you for your work @DHowett!

**Comment by zadjii-msft** [comment] 2021-03-29 11:38
Well, what needs to happen now is for us to come up with a design that reconciles the current `cursorColor` with the proposed `cursorTextColor`, with the now possible `invertCursor` functionality. Once we've got a sensible way of expressing these options, it needs to make it into a PR, merge it, then selfhost it internally to make sure it feels right. That'll probably take right up to the next release _anyways_, so I'm not sure releasing as a hotfix would end up saving anyone any time 😄

**Comment by DHowett** [comment] 2021-03-30 21:35
For those of you who appreciate long commentary,

```
// CURSOR INVERSION
// We're trying to invert the cursor and the character underneath it without redrawing the text (as
// doing so would break up the run if it were part of a ligature). To do that, we're going to try
// to XOR the content of the screen where the cursor would have been.
//
// This renderer, however, supports transparency. In fact, in its default configuration it will not
// have a background at all (it delegates background handling to somebody else.) You can't XOR what
// isn't there.
//
// To properly invert the cursor in such a configuration, then, we have to play some tricks. Examples
// are given below for two cursor types, but this applies to all of them.
//
// First, we'll draw a "backplate" in the user's requested background color (with the alpha channel
// set to 0xFF). (firstPass == true)
//
// EMPTY BOX  FILLED BOX
// =====      =====
// =   =      =====
// =   =      =====
// =   =      =====
// =====      =====
//
// Then, outside of _drawCursor, the glyph is drawn:
//
// EMPTY BOX  FILLED BOX
// ==A==      ==A==
// =A A=      =A=A=
// AAAAA      AAAAA
// A   A      A===A
// A===A      A===A
//
// Last, we'll draw the cursor again in all white and use that as the *mask* for XORing the already-
// drawn pixels. (firstPass == false) (# = mask, a = inverted A)
//
// EMPTY BOX  FILLED BOX
// ##a##      ##a##
// #A A#      #a#a#
// aAAAa      aaaaa
// a   a      a###a
// a###a      a###a
```

**Comment by pianocomposer321** [comment] 2021-03-31 16:27
Just wanted to pipe up here for a second, specifically replying to @DHowett's last message. I always considered ligatures being drawn as their individual characters when the cursor is over them as a feature, not a bug. It's nice to be able to see what characters comprise the ligature if you need to, and have it display as a ligature otherwise.

That said, I can see it the other way too, but I'm just saying that if it was up to me I wouldn't jump through too many hoops to make ligatures display "correctly".

**Comment by DHowett** [comment] 2021-03-31 20:08
It took me an entire week to realize that what most people want is a _reverse video_ cursor (red on black text becomes black on red under the cursor), not a _literal XOR cursor_ (red on black text becomes cyan on white under the cursor).

You can guess which one I've been working on.

Anyway -- is that an acceptable stop-gap? Just to make sure it's visible.

We've got a plan now, at least, for how we'll implement reverse video.

**Comment by nickjj** [comment] 2021-03-31 20:13
> Anyway -- is that an acceptable stop-gap? Just to make sure it's visible.

Yes, as long as the cursor is easily visible in all cases then you can always iron out the details later.

When in doubt there's always wsltty's code too. I don't know what they do but as an end user the cursor was always very visible.

**Comment by j4james** [comment] 2021-03-31 21:29
> Anyway -- is that an acceptable stop-gap? Just to make sure it's visible.

Yeah, I didn't want to complain because I thought maybe this is what everyone else wanted, and it's definitely better than nothing, but I was rather hoping for a simple reverse video cursor (specifically for block cursors - underline cursors just match the text color). But that can wait.

**Comment by DHowett** [comment] 2021-04-12 15:15
Given the short runway we have for 1.8 and servicing changes into 1.7, I'm going to let this one sit for early entry into the 1.9 cycle. We had some disagreements as to how the setting should be represented, and coming to a conclusion on that takes precious cycles from release engineering.

Options-

1. `{scheme}.cursorColor` and `{profile}.cursorColor` gain support for `inverse` and (later) `reverse`
   * Eventually, this means `cursorColor` will support foreground+background, inverse, reverse.
   * This requires some UI work around pickable _things_ that are not colors. It is somewhat unclear: these are not colors.
   * _Color schemes are no longer color schemes; they are forced to decide the visual properties of the cursor_
2. `{profile}.cursorColor` becomes deprecated¹ (as well as `.foreground`, `.background`, and `.selectionColor`; it only seems right) and we add the **`{profile}.cursorStyle`** enum, which supports `color`, `inverse`, and `reverse`.
   * I am hesitant to introduce a new setting for 1.7, but it would be in our best interest to do so.
3. As yet unexplored option 3. Proposals welcome.

¹ **We should do these deprecations anyway.** These decisions were made before we fully split schemes and profiles; profiles used to be able to set the whole color table but we yanked that feature after we learned nobody was using it (because it had been broken for four releases and nobody noticed...)

**Comment by saurik** [comment] 2021-04-12 19:23
FWIW, I've never experienced a reverse video cursor (or, if I have, it was in the 80s/90s); I'm intrigued by it, and maybe would fall in love with it, but I'm concerned that I would personally (and this stuff is all so personal) find it to be extremely distracting while moving it across lines that have lots of colors and it starts flashing. The behavior I'd probably want (and I don't mind if you don't do it: I've been following all of these issues, and was mentioned in the top of this thread because of said interest on previous ones, but really only because I know some of the people involved and the cursor has in fact been a blocking issue for me even trying this app... but the reality is that I have a terminal that works just fine for me and I don't need a new one) is that the cursor has a fixed color (and very very importantly is just a solid block that *doesn't blink*) and then the text it is over also ends up with a fixed color, probably (as @Pirastrino described it, "the terminal background color"). My recent experiences are with mintty changing the text to black (which happens to be the terminal background color), with iTerm changing the text to white (which is ridiculous and sometimes almost unreadable, but wasn't unusable!... for all I know this is configurable and I never cared enough to check), and Apple Terminal just leaving the text color alone (the cursor was always a separate color from all the other colors).

**Comment by Leland-Kwong** [comment] 2021-05-02 23:55
I like what @saurik mentioned about a filled box with the text color being the terminal background color. Also checked VS code, and it looks like that is how it is being done there as well.

**Comment by nickjj** [comment] 2021-07-15 14:32
Hi,

I noticed a few versions shipped since this issue.

Not trying to rush anything but is this still being actively worked on? It's become more of an issue now if you happen to use zsh with fzf in Vim because fzf will change your cursor to a block cursor (unrelated bug it seems), but the end result is you're stuck with a block cursor where you can't see anything under it.

**Comment by zadjii-msft** [comment] 2021-07-15 14:36
At the moment this is kinda just in a holding pattern - @DHowett's a little swamped with other priorities at the moment. I know that it's on his personal vendetta sticky note on his desk, but alas, there's other business that needs dealing with as well. That's what you get when you try to have a team lead write code 😜

**Comment by SilverEzhik** [comment] 2021-10-16 15:57
Hi there, this has been bugging me a lot and I made a workaround that at least lets me have an inverted cursor in Neovim while having the shell and etc use the empty box.

# Vim

This is done in neovim using some autocmds - this probably will work in standard Vim as well and can also be simplified to have something like a black cursor with white text instead of inverted colors, but I haven't tried it.

```vim
" inverted cursor workaround for windows terminal
if !empty($WT_SESSION)
    " guicursor will leave reverse to the terminal, which won't work in WT.
    " therefore we will set bg and fg colors explicitly in an autocmd.
    " however guicursor also ignores fg colors, so fg color will be set
    " with a second group that has gui=reverse.
    hi! WindowsTerminalCursorFg gui=none
    hi! WindowsTerminalCursorBg gui=none
    set guicursor+=n-v-c-sm:block-WindowsTerminalCursorBg

    function! WindowsTerminalFixHighlight()
        " reset match to the character under cursor
        silent! call matchdelete(99991)
        call matchadd('WindowsTerminalCursorFg', '\%#.', 100, 99991)

        " find fg color under cursor or fall back to Normal fg then black
        let bg = synIDattr(synIDtrans(synID(line("."), col("."), 1)), 'fg#') 
        if bg == "" | let bg = synIDattr(synIDtrans(hlID('Normal')), 'fg#') | endif
        if bg == "" | let bg = "black" | endif
        exec 'hi WindowsTerminalCursorBg guibg=' . bg
        " reset this group so it survives theme changes
        hi! WindowsTerminalCursorFg gui=reverse
    endfunction

    function! WindowsTerminalFixClear()
        " hide cursor highlight
        silent! call matchdelete(99991)

        " make cursor the default color or black in insert mode
        let bg = synIDattr(synIDtrans(hlID('Normal')), 'fg#')
        if bg == "" | let bg = "black" | endif
        exec 'hi WindowsTerminalCursorBg guibg=' . bg
    endfunction

    augroup windows_terminal_fix
        autocmd!
        autocmd FocusLost * call WindowsTerminalFixClear()
        autocmd FocusGained * if mode(1) != "i" | call WindowsTerminalFixHighlight() | endif

        autocmd InsertEnter * call WindowsTerminalFixClear()
        autocmd InsertLeave * call WindowsTerminalFixHighlight()
        autocmd CursorMoved * call WindowsTerminalFixHighlight()
    augroup END
endif
```

# Shell

I also added this to my shell profile to have the cursor get reset after Vim closes:

```sh
if [ ! -z "$WT_SESSION" ]; then
    PS1="\[\e[0 q\e[?12l\]$PS1"
fi
```

There are a few things going on here:

* `\e[0 q` will reset to the default cursor (this is the only way I found to get the empty box cursor)
* `\e[?12l` will disable blinking (`\e[?12h` enables it)
* Wrapping it all in `\[` and `\]` helps with some visual artifacts in shell prompts (I do this with PS1 color sequences as well)

During all this I also found out that it's possible to set the cursor background color using both hex and X11 colors with this OSC escape sequence: `\e]12;#FF00FF\a`. Not sure if this is documented anywhere? 

# tmux 

I also added this line to my tmux configuration so that switching between panes correctly switches the cursor shape to the default:

 `set -ga terminal-overrides ',*:Ss=\E[%p1%d q:Se=\E[0 q\E[?12l'`

**Comment by phortonssf** [comment] 2021-10-20 01:04
@SilverEzhik Works pretty great, thank you. however it only worked once I ran **cursor+=** in my init.vim.
Once I had that, it was quite good. Great job with the color reverse. The cursor not resetting back in windows terminal seems to be a neovim issue they are working on. 
Also this line didnt seem to be working for me to set the cursor to blink or other modes etc.   

 ` set guicursor+=n-v-c-sm:block-WindowsTerminalCursorBg
` 
Same here worked with out it. 
`if [ ! -z "$WT_SESSION" ]; then
    PS1="\[\e[0 q\e[?12l\]$PS1"
fi`

For anyone else just add
`cursor+=` the snippet here.  Thank you again for your work

**Comment by Hasanabbas** [comment] 2021-12-01 16:41
Any update on when this could be implemented?

**Comment by zadjii-msft** [comment] 2021-12-01 16:45
Nope. We'll make sure to update this thread when there is. In the meantime, might I recommend the Subscribe button?
![image](https://user-images.githubusercontent.com/18356694/91237459-5cbb0c80-e700-11ea-9347-b9b1ec2813b1.png)
That way you'll be notified of any updates to this thread, without needlessly pinging everyone on this thread ☺️

DHowett did have a prototype he messed around with on the long weekend
![image](https://user-images.githubusercontent.com/18356694/144276083-30b3f16a-f3f0-4c42-a54b-a4d006f98869.png)

but it's a little far away from shipping ATM.

**Comment by DHowett** [comment] 2021-12-01 22:39
You're right to ask about the current state of this issue. Since my original work to enable cursor inversion (which we never put behind a setting -- ugh, I apologize¹) we learned in a series of issues that there's a much better way for us to draw text on the screen.

Right now, all text in Terminal is broken up by line and then by "attribute run" (foreground, background, etc.) into what we've called "clusters". Each cluster is then drawn individually, background and then foreground, at terrible expense. That we draw the background and foreground all at once is the crux of the difficulty here. To properly render ligatures and handle grayscale AA and stuff, we thought it would be important to _not break clusters down further_. However, to put a cursor/selection background and foreground down, we'd need to do exactly that.

We accomplished cursor inversion in that renderer by adding another (expensive) phase at the end of rendering where we draw down the cursor shape with an XOR mask.

¹ We got lost in discussing how best to expose this setting rather than making a decision and living with it for a little bit. That's on me.

---

In the "much better" rendering engine, color is deferred to a pixel shader that runs as the final step. Adding support for a split cursor color is a delta of around 5 lines of code and adds no additional complexity to the text gather/scatter pass.

My current proposal is: the new rendering engine will automatically render the cursor background in the requested color, and the character on top of it in either white or black depending on the perceived lightness of the cursor. No new settings, no dichotomy between inverse/reverse/obverse/transverse, and no separate customizable foreground. _For now._

**Comment by AbstractMayhem** [comment] 2021-12-31 18:11
Hi @DHowett ,

Thanks for the update. I have been following all the threads related with this issue. 

Will the feature be available in the next windows terminal preview release?

Thanks

**Comment by DHowett** [comment] 2022-01-03 23:41
Some version of this should be available under an experimental flag in the upcoming 1.13 preview release.

**Comment by nickjj** [comment] 2022-02-05 12:53
@[DHowett](https://github.com/DHowett) Hi, did this end up making it into the 1.13 preview release, if so which flag should we enable? I didn't see a reference back to this issue in the release notes.

**Comment by litesam** [comment] 2022-02-08 14:44
I see the issue is not in the Experimental renderer of terminal preview release: (with experimental renderer on)
![stuff below the cursor is visible in experimental renderer](https://user-images.githubusercontent.com/34811358/153009501-622f95df-3935-4b1d-8177-cf09e99baa0c.png)

But I see a issue with rendering certain glyphs, I use oh-my-zsh and the arrow renderer prompt has a issue: (with experimental renderer on)
![arrow is cutted](https://user-images.githubusercontent.com/34811358/153009853-d05f12a5-b2f0-4b46-a4cc-f9488cf6c333.png)

**Comment by Hasanabbas** [comment] 2022-02-08 16:10
The issue is that the invert color only happens if the cursor color on your theme is exactly white (#FFFFFF):
![image](https://user-images.githubusercontent.com/3653531/153027725-59b92344-3fb1-4ecc-9431-12d42d2666d5.png)

As soon as I change the cursor color to ##FFFFFE the inversion doesn't work:
![image](https://user-images.githubusercontent.com/3653531/153027894-a94e533d-6364-4a6d-a4d3-6d0c80d66484.png)

**Comment by chemPolonium** [comment] 2022-04-29 11:22
Turn the experimental render on fixes the issue under Campbell theme (cursor color #FFFFFF)
![image](https://user-images.githubusercontent.com/17716004/165934005-1920daad-1158-4b7b-ad50-461d20206bb1.png)
and Campbell Powershell theme (cursor color #FFFFFF)
![image](https://user-images.githubusercontent.com/17716004/165934273-2c70f3ca-849d-4e41-9eab-c1eda529c50d.png)
and One Half Dark theme (cursor color #FFFFFF)
![image](https://user-images.githubusercontent.com/17716004/165934342-0ae0bf96-ecb3-4099-8790-77349eeb2914.png)
but it seems not work well under Solarized Dark theme (cursor color #FFFFFF)
![image](https://user-images.githubusercontent.com/17716004/165934881-76618646-45c0-436c-a2fc-0568199e6f29.png)
and Solarized Light theme (cursor color #002B36)
![image](https://user-images.githubusercontent.com/17716004/165934545-5b453572-8e23-4336-be05-3c883ed6eee6.png)

**Comment by nickjj** [comment] 2022-04-29 11:25
Which option is the experimental renderer?

The only rendering options I see in the settings are to redraw the entire screen or use software rendering, neither are marked as experimental. I also don't see the word "experimental" in the JSON file except for the retroTerminalEffect setting.

**Comment by chemPolonium** [comment] 2022-04-29 11:30
@nickjj In the seprated profile (windows powershell, powershell, cmd etc.)
![image](https://user-images.githubusercontent.com/17716004/165936290-9261982a-49ad-482f-b2b7-fd7fe03d44d9.png)
高级 is advanced

**Comment by zadjii-msft** [comment] 2022-04-29 11:38
from the docs: [Experimental text rendering engine](https://docs.microsoft.com/en-us/windows/terminal/customize-settings/profile-advanced#experimental-text-rendering-engine-preview) ([Preview](https://aka.ms/terminal-preview))

**Comment by ftabaro** [comment] 2022-05-20 14:27
Thanks @DHowett for your work. What about having the char under the cursor take the background color? This ensures the contrast is high and maximum readability imo.

**Comment by kippesp** [comment] 2022-05-24 02:18
Black on white is definitely better that it was.  This announcement blog is pretty good elaborating on the setting: https://devblogs.microsoft.com/commandline/windows-terminal-preview-1-13-release/

**Comment by ToxicSmurf** [comment] 2022-06-06 09:24
I was looking around, hoping to find a solution for this. Little did I know, I just had to update! Thank you so much.

**Comment by nickjj** [comment] 2022-06-11 14:58
I don't see that option as being available in 1.13, you can see behind the about box there's no experimental option on the bottom:

![image](https://user-images.githubusercontent.com/813219/173192991-5d0ba15c-7e1c-4ab6-87c3-87450891e5de.png)

I also added the option manually to the JSON file and it had no effect (I restarted the terminal).

Is there something not mentioned in the docs that you need to do to show / allow experimental features?

**Comment by zadjii-msft** [comment] 2022-06-11 18:37
The experimental renderer is for now, only available in Preview builds of the Terminal. It's going to remain preview-only while we sort out some remaining bugs in it. The Preview builds are generally stable enough for daily usage, at least in my experience.

**Comment by paulharris** [comment] 2022-06-15 05:06
I just tried the preview.
Open settings, set any profile to enable experimental-renderer (I tried PoSH and git-bash),
Save,
Open the profile.
Win-Term just disappears (crash, I presume).

**Comment by broander** [comment] 2022-07-14 23:10
Trying the preview with experimental renderer enabled.  Seeing the same issue as above that the color invert only works with a #FFFFFF cursor color.

Also seeing a new issue with the rendering of italicized text which I have my comments render as:

![2022-07-14 17_07_09-Clipboard](https://user-images.githubusercontent.com/66220841/179115979-5442b8f6-72f3-4ece-b2ed-02fdc031eada.png)

You can see it's cutting of the edges of characters (see the phrase "TMUX and IOS using OSC52", which no doubt has something to do with how the new experimental renderer works based on the explanations above.  It is not an issue with the old engine, here's a screenshot of the old engine:

![image](https://user-images.githubusercontent.com/66220841/179116218-d53e09f6-102e-4c82-9269-d62b23981a3f.png)

**Comment by habamax** [comment] 2022-11-03 08:59
Indeed, latest preview with AtlasEngine on:

![image](https://user-images.githubusercontent.com/234774/199681164-de3c7508-a196-4251-aa46-caff1b471add.png)

If only there was a cursor foreground setting :)

**Comment by avih** [comment] 2022-11-15 10:42
> If only there was a cursor foreground setting :)

+1

This issue has been unsolved for years (together with #1203).

You're trying a million ways to automate a solution (render the block behind the font, contrast the fg to this or that, etc), but before automation, please allow the user to specify an explicit (block) cursor fg color.

Once the user can specify one, please go wild with automated solutions, but do let the user still specify one if they want.

**Comment by zhihaoy** [comment] 2023-02-03 11:21
#6337 made an assumption that foreground color is sufficiently different from the block cursor's background, which doesn't hold true. I still need a feature to change the TEXT color when the block cursor is over it. Inverting is too smart for me; I will set it to white in a light theme to distinguish the dark text from my dark block cursor if possible.

**Comment by james1236** [comment] 2023-02-23 02:22
This was first raised over 3 and a half years ago and I am still facing the issue today (even in the Preview!) where the character under the cursor is invisible if the text is white in WSL. The perfectly reasonable solution of introducing a `cursorColorText` setting has been mentioned multiple times, just implement that, then worry about fixing the greater issue here (given that fixing the greater issue has taken over two years!)

**Comment by james1236** [comment] 2023-02-23 02:26
Still an issue over 3 and a half years after first being raised, even in the preview version. 
![image](https://user-images.githubusercontent.com/32351696/220808367-4ff88bd5-7f1d-42bb-ab62-51bed9d5ab15.png)

**Comment by james1236** [comment] 2023-02-23 02:32
They fixed it in the preview version! Just enable the new AtlasEngine renderer:

![image](https://user-images.githubusercontent.com/32351696/220808776-86901e0a-024c-478c-8a48-985bf84862f8.png)

#### Before
![image](https://user-images.githubusercontent.com/32351696/220808367-4ff88bd5-7f1d-42bb-ab62-51bed9d5ab15.png)
#### After
![image](https://user-images.githubusercontent.com/32351696/220808811-0327e87c-27c7-4c82-b86e-fb05bbda2a7c.png)

**Comment by paulharris** [comment] 2023-03-13 06:23
This did not look the same for me, the cursor was white and the text was slightly not white - not inverted - so was very hard to see the text behind the cursor.

**Comment by sitompul** [comment] 2023-03-19 11:46
@MustafaFayez https://github.com/microsoft/terminal/issues/9610#issuecomment-1441144003

**Comment by lhecker** [comment] 2023-05-03 19:11
It's a little difficult for me to say whether I should close this issue with the PR that I've just opened... If I'm not misunderstanding the original issue description at the top, then it'll fix the issue. The PR uses an algorithm to determine the contrast between the cursor and the underlying background and the text on top of it, and ensure it always remains "distinguishable".

In other words: After that PR, if you use AtlasEngine, no matter whether you use inversed cursors or if you use colored cursors, the text will always remain visible.

The discussion however has drifted away quite a bit since then, which I can fully understand, given that our cursors are kinda... meh. But I feel like that these issues are not part of the original issue anymore. They're also much more easily to address. Among those are suggestion to allow users to configure the cursor background and foreground color individually, as well as to implement reversed cursors. I hope to get to that in the near term, although community contributions for that would be greatly appreciated, because I'm not sure if I'll have time myself.

On that note, it might be interesting to mention that the new colored cursors will be sort of "semi-reverse" cursors and look like this (this is when I set my cursor to `#ff0000`):
![image](https://user-images.githubusercontent.com/2256941/234496444-0583f3ec-fc14-43f9-b901-a6ae36cfd3fc.png)

**Comment by 3N4N** [comment] 2023-05-04 18:13
Thank you! @lhecker.  I hope to soon use block cursor like god intended (I'm currently using vintage shape because of this indistinguishable-character issue).

> [The other issues/feature-requests] are also much more easily to address. Among those are suggestion to allow users to configure the cursor background and foreground color individually.

This really seems like a no-brainer.  Since it's easier to address, as you say, why not implement that before the automated inversion solutions?  I am repeating [@avih][1] here, I know, but this easy-to-address feature could help me use Vim with proper `guicursor`, instead of having to use the boring vintage cursor.


[1]: https://github.com/microsoft/terminal/issues/9610#issuecomment-1315124732

**Comment by lhecker** [comment] 2023-05-04 19:24
> Since it's easier to address, as you say, why not implement that before the automated inversion solutions?

The "automated" mode is ~4 lines of code and took me <5min to write and test, whereas the other issues/feature-requests require a lot more work. Given that I'm technically already 110% booked out with work for months on end, I think you can see why I've picked the easy option for now. 🥲

> I hope to soon use block cursor like god intended (I'm currently using vintage shape because of this indistinguishable-character issue).

You could try god's intended cursors right now, if you're curious. 😏
[Here](https://blob.hecker.io/sharex/Microsoft.WindowsTerminalPreview_1.18.1241.0_8wekyb3d8bbwe.msixbundle) is a preview build based on that PR. I put it on my own host for convenience (and because the file will automatically expire in a week that way), but it's a proper built and digitally signed by Microsoft.

**Comment by 3N4N** [comment] 2023-05-05 03:39
> > I hope to soon use block cursor like god intended (I'm currently using vintage shape because of this indistinguishable-character issue).
> 
> You could try god's intended cursors right now, if you're curious. 😏 [Here](https://blob.hecker.io/sharex/Microsoft.WindowsTerminalPreview_1.18.1241.0_8wekyb3d8bbwe.msixbundle) is a preview build based on that PR.

Awesome!  Been using for a few hours.  Works great!  Thanks a bunch.

**Comment by avih** [comment] 2023-05-06 13:32
IMHO, if you insist on choosing the FG color yourself and not letting the user specify it, then just pick either black or white - whichever has the better contrast to the chosen cursor BG color.

IMO it would pretty much gurante to look better than any attempt to preserve the underlaying FG color but still modifying it so that it has some contrast to the BG.

Just see how many failed atempts there were at that, to realise that it's not as simple as you think to do what the user prefer automatically.

**Comment by nickjj** [comment] 2023-05-06 13:59
I think if we stick with setting it manually then we're not going to address the root issue where characters are invisible based on syntax highlighting in terminal based editors such as Vim.  You're going to have a wide range of dark and light text based on any variant of color themes.

**Closed** 2023-05-08 19:16 UTC
Labels: Issue-Feature, Area-Rendering, Product-Terminal, In-PR

**Comment by habamax** [comment] 2023-05-08 23:46
> I think if we stick with setting it manually then we're not going to address the root issue where characters are invisible based on syntax highlighting in terminal based editors such as Vim. You're going to have a wide range of dark and light text based on any variant of color themes.

I have used vim for a long time in different terminals that allow setting `bg` and `fg` for a cursor -- never had an issue with syntax highlighting and cursor. If your terminal background is black, set cursor colors to white and black, do the opposite if terminal background is light/white. It always worked, it would have worked in windows terminal too.

But anyway, if that new implementation would let us distinguish what is under cursor, I am all for it.

**Comment by gaoqiangks** [comment] 2023-06-24 16:00
So, what's the solution? Many issues are closed but I still cann't find a solution.

**Comment by lhecker** [comment] 2023-06-24 16:35
Did you try Windows Terminal Preview 1.18 yet? If that doesn’t work for you it’d be great if you could open a new issue with a screenshot showing the problem and I‘ll try to fix it ASAP. 🙂

If you’re asking about setting individual foreground and background colors for the cursor, I don’t think we have an issue tracking specifically that yet, but I‘ve already made it my goal to implement that for 1.19 anyways.

**Comment by gaoqiangks** [comment] 2023-06-25 03:55
> 

WT Preview 1.18 is much better.   Thank you!

**Comment by weibeld** [comment] 2023-07-26 23:23
This is now being discusses in #15766.
