### ISSUE TITLE
cmd.exe start /d not working with /min

### ISSUE THREAD

**Issue by eeflores** [microsoft/terminal#874] opened 2019-05-17 10:17 UTC
# Environment

```none
Windows build number: 10.0.17763.475

Other software: Elasticsearch 6.7.0 using Java 1.8.0_172, but the behavior was 
confirmed with a test batch file and executable.
```

# Steps to reproduce

When testing the functionality of the `start` command within the `cmd.exe` shell, I found that having the `/min` parameter would affect the `/d` parameter: the path provided to the `/d` parameter did not seem to be acknowledged, and the command passed to the `start` command would not be found.

Test example:
* Command shell with prompt at `C:\temp`
* A test batch file at `C:\temp\testdir\test.bat`, with the content
 ```
@echo hello
pause
```
* Running the following command would succeed:
`C:\temp>start /d c:\temp\testdir test.bat`
* The following command would not succeed:
`C:\temp>start /min /d c:\temp\testdir test.bat`
* If the path is set to `C:\temp\testdir` the following command would succeed:
`C:\temp\testdir>start /min test.bat`

The use of the `/d` and `/min` parameter together was previously working, and was required functionality for a commercial product.

I'm wondering if this problem is related to #271 .

# Expected behavior

The `/d` parameter to be parsed when the `/min` parameter is also included to the `start` command.

# Actual behavior

If the `/min` parameter is used with the `/d` parameter, the path used with the `/d` parameter does not seem to be used, and the program contained in the path referenced by the `/d` parameter is not found.

**Comment by DHowett-MSFT** [comment] 2019-05-17 15:29
This is a duplicate of #271.

**Closed by DHowett-MSFT** 2019-05-17 15:29 UTC
Labels: Product-Cmd.exe, Resolution-Duplicate
