### ISSUE TITLE
All the tabs will be quite slow when one of the tab is running under high CPU load 

### ISSUE THREAD

**Issue by jackyzhujiale** [microsoft/terminal#5519] opened 2020-04-24 03:43 UTC
# Environment

```none
Windows build number: 18363.778
Windows Terminal version (if applicable): 0.10.781.0

Any other software?
```

# Steps to reproduce
Open a powershell tab, run some high load commands (In my case it's running a node.js server service)
Then user would see other Tabs under the same terminal window running quite slow, typing is dragging and UI display will slow down as well. But If I open a new terminal, though the high load process is still running, it won't get affected.

# Expected behavior
I expected other tabs shall not be affected. They should be independent, but seems they are not.

# Actual behavior
Looks the tabs under the same terminal's UI thread seem would be affected by other tabs. While create a new terminal won't get affected by this

**Comment by zadjii-msft** [comment] 2020-04-24 14:04
Okay so largely, this is a duplicate of #1311, which is actually also a dupe of #778. Unfortunately, the fix for #778 didn't make the 0.11 cut, but should be fighting at some point in the near future, or in 1.0.

There's a whole mess of PRs and issues related to this: #5345, #3515, #5320, #1064

For post-1.0 perf issues, I think we're using #3075 to track them.

Since #1311 is the _closest_ dupe, I'm gonna close this one as a dupe of that one. Thanks!

/dup #1311

**Closed by zadjii-msft** 2020-04-24 14:04 UTC
Labels: Needs-Tag-Fix, Needs-Triage
