### ISSUE TITLE
nvim 0.7.0 + windows terminal preview, [[0 escape sequence is inserted upon exit

### ISSUE THREAD

**Issue by zeroxia** [microsoft/terminal#13401] opened 2022-06-30 06:53 UTC
### Windows Terminal version

Windows Terminal Preview
1.14.1451.0

### Windows build number

10.0.19044.0

### Other Software

neovim 0.7.0, 0.8.0

### Steps to reproduce

Both the following neovim versions demo the same issue:

* neovim 0.7.0 installed with scoop.
* neovim 0.8.0 is portable version extracted to C:\usr\local

With Windows Terminal (preview), when exiting from `nvim.exe`, there is always a escape sequence `[0` inserted at command prompt. There is no difference for `cmd.exe`, `pwsh`, `powershell` inside Windows Terminal.

If run `nvim.exe` in `cmd.exe`, there is no such issue. In `cmd.exe`, I can run `pwsh` or `powershell`, and then execute `nvim.exe`, still no issue after exiting.

![animation showing the issue](https://i.imgur.com/DW0JG6X.gif)

### Expected Behavior

No `[0` sequence is inserted after exiting `nvim.exe`

### Actual Behavior

`[0` is inserted after exiting `nvim.exe`.

**Comment by DHowett** [comment] 2022-06-30 16:47
Indeed! This is a /dupe of #13238.

**Closed** 2022-06-30 16:47 UTC
Labels: Issue-Bug, Needs-Triage, Needs-Tag-Fix
