### ISSUE TITLE
How to force Windows Terminal to open maximized?

### ISSUE THREAD

**Issue by xmha97** [microsoft/terminal#6352] opened 2020-06-04 15:14 UTC
Hello,
How to force Windows Terminal to open maximized?

**Comment by xmha97** [comment] 2020-06-04 15:21
I added the below line but it is not launched as maximized:
```
"launchMode": "maximized"
```
![Windows Terminal](https://user-images.githubusercontent.com/23485114/83775830-a87b8e00-a69c-11ea-92fc-a2a2db83f977.gif)

**Comment by xmha97** [comment] 2020-06-04 19:39
> Where did you add it?

On the `settings.json`

![image](https://user-images.githubusercontent.com/23485114/83801865-120c9400-a6bf-11ea-981e-f6e4048be245.png)

# Problem:
Windows Terminal runs at large size but is not maximized!

---

You can see that the program is running normally but with the large size.

![image](https://user-images.githubusercontent.com/23485114/83802514-29984c80-a6c0-11ea-9e40-dc1e7f6540d1.png)


It is correct to see the `Restore Down` button, instead of the` Maximize` button.

![image](https://user-images.githubusercontent.com/23485114/83802256-a676f680-a6bf-11ea-9bd0-8dc414b65a68.png)

**Comment by DHowett** [comment] 2020-06-05 01:33
I think this is actually a /dupe of #3440, which was recently fixed and should be coming out soon.

**Closed** 2020-06-05 13:14 UTC
Labels: Issue-Feature, Resolution-Duplicate
