### ISSUE TITLE
Open terminal from folder explorer

### ISSUE THREAD

**Issue by jrahma** [microsoft/terminal#2287] opened 2019-08-06 10:57 UTC
Hi,

When the user clicks inside file explorer and types **cmd**, they should be able to also type **terminal** to start the Windows Terminal in the selected folder

Thanks,
[Jassim](https://maxmon.softnames.com)

**Comment by CatTheHacker** [comment] 2019-08-06 12:34
Dupe of https://github.com/microsoft/terminal/issues/2286
Launching from File Explorer relies on `PATH` and `terminal` alias.

**Comment by zadjii-msft** [comment] 2019-08-06 13:02
This is actually a dupe of #607 & #878.

**Closed by zadjii-msft** 2019-08-06 13:02 UTC
Labels: Issue-Feature, Needs-Tag-Fix, Needs-Triage
