### ISSUE TITLE
Terminal displays as "DesktopWindowXaml..." when it's starting

### ISSUE THREAD

**Issue by KotlinIsland** [microsoft/terminal#11706] opened 2021-11-07 22:47 UTC
### Windows Terminal version (or Windows build number)

Microsoft Windows [Version 10.0.19043.1288]

### Steps to reproduce

Open wt

### Expected Behavior

window displays as "Terminal" or something with the terminal icon.

### Actual Behavior

"DesktopWindowXaml..." with a broken icon.

![image](https://user-images.githubusercontent.com/65446343/140664670-04d26def-8a43-4075-9234-11745b090b5e.png)

Once it loads it's back to normal.

**Comment by zadjii-msft** [comment] 2021-11-08 11:21
Which version of the Terminal is this? Do you have WSL installed? 

My theory is that we're hitting the very slow path of the old WSL distro lookup, which is hanging during the creation of the window, so we don't actually update the window title to something sensible. 

<hr>

I suppose this is something we could fix _regardless_ of if it's fixed already. Like, we could always we the title and icon of the window, even before we load the settings. Should be easy enough to repro, just slap a `Sleep(10000)` in the `WslDistroGenerator`

**Comment by KotlinIsland** [comment] 2021-11-09 00:34
I've seen this on every version of Terminal I've used, and yes WSL 2 with wsl as default shell.

**Comment by Rosefield** [comment] 2021-11-09 02:59
I also noticed this when I was working on all of the saved layout / quit features. It can be fairly reliably reproduced by having window layout saying enabled and quitting/reloading half a dozen or so windows, resulting in a process list like this (dev/main not updated since the 1.12 release cut)

![image](https://user-images.githubusercontent.com/6185249/140853664-a38d3538-be22-4762-9bb8-f1288a89fac8.png)

**Comment by Link1J** [comment] 2022-01-10 19:59
The two `DesktopWindowXamlSource` is created by `C:\Windows\System32\Windows.UI.dll`. So I am going to guess they are what make XAML Islands work. My guess on why one of them appears (I don't know which) is that the window isn't configured to be hidden, but Windows makes it disappear when it has a parent. I have seen it appear when closing apps using XAML Islands, probably because it loses it parent window before it is closed.

Making it not appear may need an OS level fix, if it is even possible to fix.

**Closed** 2022-08-22 11:30 UTC
Labels: Help Wanted, Issue-Bug, Product-Terminal, Needs-Tag-Fix, Priority-3, Area-Windowing
