### ISSUE TITLE
scrolling in the settings moves slightly to the left and back again

### ISSUE THREAD

**Issue by Poopooracoocoo** [microsoft/terminal#10742] opened 2021-07-21 10:13 UTC
### Windows Terminal version (or Windows build number)

1.9.1942.0

### Steps to reproduce

150% scale
1920 x 1980

open settings, go to profiles or somewhere, and scroll

### Actual Behavior

moves left then back again as per recording

https://user-images.githubusercontent.com/51363864/126472778-29d410d0-e8e7-4ca2-81bc-cd58a889fb47.mp4

**Comment by zadjii-msft** [comment] 2021-07-21 10:26
Are you scrolling with a mouse wheel, or a trackpad?

**Comment by Poopooracoocoo** [comment] 2021-07-21 10:28
With a mouse wheel. It's a Logitech MX Master. Doesn't happen with (precision) touchpad.

**Comment by zadjii-msft** [comment] 2021-07-21 12:37
Out of curiosity, does this repro in the [XAML Controls Gallery](https://www.microsoft.com/en-us/p/xaml-controls-gallery/9msvh128x2zt) app? That's a good sample app for checking if UI bugs are Terminal-specific, or WinUI specific. In that app you should be able to go to the "NavigationView" page, which should have some samples of UI like the Terminal settings.

**Comment by Poopooracoocoo** [comment] 2021-07-21 13:02
@zadjii-msft nope, doesn't repro in XCG.

**Comment by DHowett** [comment] 2021-07-22 19:49
This might be due to the ScrollViewer introduced to constrain the bounds of the settings and reverted in #10716.

Tentatively closing as a /duplicate of #10664.

**Closed by DHowett** 2021-07-22 19:49 UTC
Labels: Needs-Attention, Needs-Tag-Fix, Needs-Triage
