### ISSUE TITLE
Bug Report: PowerShell in 1903 cursor ghosting

### ISSUE THREAD

**Issue by fgimian** [microsoft/terminal#1128] opened 2019-06-03 22:18 UTC
# Environment

```none
Microsoft Windows [Version 10.0.18362.30]
Windows Terminal version (if applicable): N/A
```

# Steps to reproduce

1. Open a PowerShell (5.1) window with default settings
2. Hit enter while the cursor is showing (you'll need to be quick to get it between blinks)

Note that this seems to happen intermittently but was very easy to reproduce (noticed it within seconds of upgrading last night).

# Expected behavior

The cursor from the previous line should dissappear after you hit Enter.

# Actual behavior

The cursor stays drawn on the previous line:

e.g.

![Screenshot (1)](https://user-images.githubusercontent.com/1811813/58838184-55de4f00-86a1-11e9-970e-1870fab22e94.png)

**Comment by DHowett-MSFT** [comment] 2019-06-04 00:56
I also think we have an internal issue tracking this, so I'll mark this one as triaged.

**Comment by fgimian** [comment] 2019-06-04 01:19
Thanks a lot @DHowett-MSFT, are you aware of any workarounds at this stage?

Kindest Regards
Fotis

**Comment by zadjii-msft** [comment] 2019-06-11 20:53
This is actually a dupe of #804, though I couldn't blame anyone for being unable to decipher what @miniksa meant with that issue. I'm closing this one as a dupe

**Closed** 2019-06-11 20:53 UTC
Labels: Area-Rendering, Issue-Bug, Product-Conhost, Resolution-Duplicate
