### ISSUE TITLE
Exit from dialog command leads to overriding output above

### ISSUE THREAD

**Issue by ihor-sviziev** [microsoft/terminal#5762] opened 2020-05-06 06:10 UTC
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18363.815]
Windows Terminal version (if applicable): 0.11.1251.0
```

# Steps to reproduce
1. Open WSL Ubuntu 18.04
2. Run command
```bash
HEIGHT=0
WIDTH=0
dialog \
    --backtitle "System Information" \
    --title "Menu" \
    --clear \
    --cancel-label "Exit" \
    --menu "Please select:" $HEIGHT $WIDTH 4 \
    "1" "Display System Information" \
    "2" "Display Disk Space" \
    "3" "Display Home Space Utilization"
```
3. Press CTRL + C on your keyboard
4. Try to see output that was shown before dialog
5. Connect to ubuntu 18.04 machine via ssh, execute the same command
6. Try to see output that was shown before dialog

# Expected behavior
 **After step 4:**
- you should have a scroll
- you should see commands that were above:
example from Ubuntu 20.04: 
![image](https://user-images.githubusercontent.com/1873745/81142592-bc867f80-8f78-11ea-8483-e267cc5cacf7.png)

I would say on Ubuntu 20.04 new line appeared in the center of dialog, not the best experience, but much better than on Windows Terminal.

On Ubuntu 18.04 windows app it looks like this:
- you should have a scroll
- you should see commands that were above:
![image](https://user-images.githubusercontent.com/1873745/81143434-83e7a580-8f7a-11ea-8bb1-c5686f4e524e.png)

**After step 6:**
- you should have a scroll
- you should see commands that were above:
example from Ubuntu 20.04: 
![image](https://user-images.githubusercontent.com/1873745/81142752-1be48f80-8f79-11ea-8d24-6871c8c4f282.png)

In this case new line appeared just below the dialog.

On Ubuntu 18.04 Windows APP we have following:
- you should have a scroll
- you should see commands that were above:
![image](https://user-images.githubusercontent.com/1873745/81143528-b72a3480-8f7a-11ea-9099-028be01057f8.png)

# Actual behavior

**After step 4:** 
- no scroll at all
- you can't see commands that were above
![image](https://user-images.githubusercontent.com/1873745/81142383-3cf8b080-8f78-11ea-9b2b-0ab433f343fb.png)

**After step 6:**
- scroll is present
- you still can't see commands that were above (only ssh command you can see)
![image](https://user-images.githubusercontent.com/1873745/81142494-7e895b80-8f78-11ea-93cd-f9368daf7471.png)

Note: this issue also appeared on earlier versions. Hope it could be fixed before release 1.0 as it's really hard to use Windows Terminal in combination with scripts that using dialogs.

**Comment by DHowett-MSFT** [comment] 2020-05-07 01:01
Thanks for the robust issue report! I think this is, unfortunately, a side effect of us not propagating the alternate buffer state to the terminal. That would make this a /dupe of #381.

(The alternate buffer would give Dialog a sandbox to kick around in that would get cleared/deleted when it was dismissed.)

**Closed by DHowett-MSFT** 2020-05-07 01:01 UTC
Labels: Needs-Tag-Fix, Needs-Triage
