### ISSUE TITLE
No telnet in cmd.exe pane

### ISSUE THREAD

**Issue by chris-elvidge** [microsoft/terminal#6735] opened 2020-06-30 19:00 UTC
# Environment

```none
Windows build number: 10.0.18363.900]
Windows Terminal version (if applicable): 1.0.1811.0

Any other software?
```

# Steps to reproduce

type telnet in cmd.exe pane
# Expected behavior

telnet prompt
# Actual behavior

Microsoft Windows [Version 10.0.18363.900]
(c) 2019 Microsoft Corporation. All rights reserved.

30/06/2020@19:47:44.00 C:\Users\celvi
> telnet
'telnet' is not recognized as an internal or external command,
operable program or batch file.

30/06/2020@19:47:51.46 C:\Users\celvi
> dir C:\Windows\System32\te*.*
 Volume in drive C is System64
 Volume Serial Number is E0EC-BBF1

 Directory of C:\Windows\System32

15/05/2018  16:55    <DIR>          te-IN
19/03/2019  05:46           107,520 telephon.cpl
19/03/2019  05:45            70,656 TempSignedLicenseExchangeTask.dll
10/06/2020  12:26           361,472 termmgr.dll
19/03/2019  05:45            61,440 tetheringclient.dll
12/09/2019  11:45           531,464 TextInputFramework.dll
12/09/2019  11:45         1,101,312 TextInputMethodFormatter.dll
               6 File(s)      2,233,864 bytes
               1 Dir(s)  439,855,341,568 bytes free

30/06/2020@19:48:14.31 C:\Users\celvi

In windows command prompt:

Microsoft Windows [Version 10.0.18363.900]
(c) 2019 Microsoft Corporation. All rights reserved.

30/06/2020@19:58:24.77 C:\Users\celvi
> dir C:\Windows\System32\te*.*
 Volume in drive C is System64
 Volume Serial Number is E0EC-BBF1

 Directory of C:\Windows\System32

15/05/2018  16:55    <DIR>          te-IN
19/03/2019  05:45           109,056 telephon.cpl
13/05/2020  18:57           138,240 TelephonyInteractiveUser.dll
21/03/2020  16:38             2,560 TelephonyInteractiveUserRes.dll
14/06/2019  03:34           130,560 telnet.exe
19/03/2019  05:44            73,728 TempSignedLicenseExchangeTask.dll
10/11/2015  07:31            85,120 tepeqapo64.dll
10/06/2020  12:26           426,496 termmgr.dll
13/05/2020  18:59         1,060,352 termsrv.dll
10/10/2019  10:47            75,264 tetheringclient.dll
10/10/2019  10:47            52,224 tetheringconfigsp.dll
19/03/2019  05:43            13,312 TetheringIeProvider.dll
21/03/2020  16:38           231,936 TetheringMgr.dll
10/10/2019  10:47           236,032 tetheringservice.dll
19/03/2019  05:43           222,208 TetheringStation.dll
21/03/2020  16:38           642,216 TextInputFramework.dll
12/02/2020  12:16         1,841,152 TextInputMethodFormatter.dll
              16 File(s)      5,340,456 bytes
               1 Dir(s)  439,851,257,856 bytes free

30/06/2020@19:58:47.27 C:\Users\celvi
>

Notice: telnet.exe is there.

In powershell pane, telnet works

**Comment by DHowett** [comment] 2020-06-30 19:19
Can you share the output of `echo %PROCESSOR_ARCHITECTURE%` in a working and non-working window?

**Comment by chris-elvidge** [comment] 2020-06-30 19:32
Command Prompt (working) says AMD64
Windows Terminal cmd.exe (telnet not there) says x86

I've put a new pane in WT with "telnet.exe" as the "commandline"  - that works

**Comment by chris-elvidge** [comment] 2020-06-30 19:33
OIC WT is running 32 bit cmd.exe

**Comment by DHowett** [comment] 2020-06-30 19:34
Wow, okay, this is really strange. 1.0.1811 switched to hardcoding the location of CMD in such a way as to make this impossible.

Can you share...

1. your settings.json (in a [gist](https://gist.github.com))
2. the output of (powershell) `get-appxpackage microsoft.windowsterminal`
3. the output of (powershell) `$Env:PATH`?

**Comment by DHowett** [comment] 2020-06-30 19:35
> OIC

yeah, that's the weird part. That shouldn't be happening by default! :grin:

**Comment by chris-elvidge** [comment] 2020-06-30 19:43
PS C:\Users\celvi> get-appxpackage microsoft.windowsterminal


Name              : Microsoft.WindowsTerminal
Publisher         : CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US
Architecture      : X64
ResourceId        :
Version           : 1.0.1811.0
PackageFullName   : Microsoft.WindowsTerminal_1.0.1811.0_x64__8wekyb3d8bbwe
InstallLocation   : C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_1.0.1811.0_x64__8wekyb3d8bbwe
IsFramework       : False
PackageFamilyName : Microsoft.WindowsTerminal_8wekyb3d8bbwe
PublisherId       : 8wekyb3d8bbwe
IsResourcePackage : False
IsBundle          : False
IsDevelopmentMode : False
NonRemovable      : False
IsPartiallyStaged : False
SignatureKind     : Store
Status            : Ok



PS C:\Users\celvi> $Env:PATH
C:\Program Files\ImageMagick-7.0.7-Q16;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Vim\vim80;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Calibre2\;C:\Program Files (x86)\Windows Live\Shared;C:\Program Files\dotnet\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\get_iplayer;c:\cygwin64\bin;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\PuTTY\;;C:\Program Files (x86)\NTP\bin;C:\Users\celvi\AppData\Local\Microsoft\WindowsApps;C:\Users\celvi\Program Files;C:\WinNMP\bin;C:\Program Files (x86)\Nmap;C:\Program Files\Multipass\bin
PS C:\Users\celvi>

**Comment by DHowett** [comment] 2020-06-30 20:09
Thanks! So, this might be weird, but can you delete `commandline: cmd.exe` from your settings file? Just that one -- keep the rest.

**Comment by chris-elvidge** [comment] 2020-06-30 20:15
telnet now works. 

Welcome to Microsoft Telnet Client                                                                                                                                                                                                              Escape Character is 'CTRL+]'                                                                                                                                                                                                                    Microsoft Telnet> exit                                                                                                  Invalid Command. type ?/help for help                                                                                   Microsoft Telnet> quit                                                                                                  
30/06/2020@21:11:46.19 C:\Users\celvi
> echo %PROCESSOR_ARCHITECTURE%
AMD64                                                                                                                                                                                                                                           30/06/2020@21:12:31.10 C:\Users\celvi

> dir c:\windows\system32\te*.*
 Volume in drive C is System64
 Volume Serial Number is E0EC-BBF1                                                                                                                                                                                                               Directory of c:\windows\system32                                                                                                                                                                                                               15/05/2018  16:55    <DIR>          te-IN
19/03/2019  05:45           109,056 telephon.cpl
13/05/2020  18:57           138,240 TelephonyInteractiveUser.dll
21/03/2020  16:38             2,560 TelephonyInteractiveUserRes.dll
14/06/2019  03:34           130,560 telnet.exe
19/03/2019  05:44            73,728 TempSignedLicenseExchangeTask.dll
10/11/2015  07:31            85,120 tepeqapo64.dll
10/06/2020  12:26           426,496 termmgr.dll
13/05/2020  18:59         1,060,352 termsrv.dll
10/10/2019  10:47            75,264 tetheringclient.dll
10/10/2019  10:47            52,224 tetheringconfigsp.dll
19/03/2019  05:43            13,312 TetheringIeProvider.dll
21/03/2020  16:38           231,936 TetheringMgr.dll
10/10/2019  10:47           236,032 tetheringservice.dll
19/03/2019  05:43           222,208 TetheringStation.dll
21/03/2020  16:38           642,216 TextInputFramework.dll
12/02/2020  12:16         1,841,152 TextInputMethodFormatter.dll
              16 File(s)      5,340,456 bytes
               1 Dir(s)  439,845,892,096 bytes free          

And the dir command now finds 16 files - OK

**Comment by chris-elvidge** [comment] 2020-06-30 20:21
That line "commandline" : "cmd.exe" doesn't  get refreshed when terminal closes

**Comment by DHowett** [comment] 2020-06-30 20:26
Unfortunately, yeah, we have a bit of a blind spot there. I can't determine why Terminal was finding a 32-bit `cmd.exe` before any others, but... hm

Can you run (from powershell): `get-command cmd.exe -all`? It will report all of the CMDs it finds.

**Comment by chris-elvidge** [comment] 2020-06-30 20:29
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6

PS C:\Users\celvi> get-command cmd.exe -all

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Application     cmd.exe                                            10.0.18... C:\WINDOWS\system32\cmd.exe


PS C:\Users\celvi>

**Comment by chris-elvidge** [comment] 2020-06-30 20:40
I have a 32-bit installation of Win10 on D: drive. Running D:\Windows\System32\cmd.exe gives processor architecture  = x86
But it shouldn't find that, anyway.

**Comment by DHowett** [comment] 2020-07-02 23:21
Thanks for all the info. I'm gonna close this as a /dupe of #6684 (PR) with a note that we need to figure out how to migrate people who are missing the updated locations.

**Closed by DHowett** 2020-07-02 23:21 UTC
Labels: Needs-Attention, Needs-Tag-Fix, Needs-Triage
