### ISSUE TITLE
Blank tabs, unusable terminal

### ISSUE THREAD

**Issue by arjun-msft** [microsoft/terminal#3557] opened 2019-11-13 17:45 UTC
# Environment

```none
Windows build number: 18362.418
Windows Terminal version (if applicable): 0.6.3121
```
Any other software?
no

# Steps to reproduce

I'm not sure how I'm in this state, I was in [issue 3446](https://github.com/microsoft/terminal/issues/3446) with a debugger attached and terminal crashed, the entire process disappeared, after which if I launch, terminal is unusable, blank tabs, see screenshot, I have 4 "tabs" open.

![image](https://user-images.githubusercontent.com/20304470/68789350-204b7380-05fa-11ea-9a3b-8074fdde133a.png)

# Expected behavior

Tabs to open with usable cmd window.

# Actual behavior

Tabs open but not usable.

**Comment by DHowett-MSFT** [comment] 2019-11-13 17:56
Hey, does this reproduce with 0.6.3161.0?

**Comment by DHowett-MSFT** [comment] 2019-11-13 19:29
If 3161 fixes this one (specifically), it's a dupe of #3548

**Comment by arjun-msft** [comment] 2019-11-14 01:27
I'm not seeing this on 3161.

**Comment by DHowett-MSFT** [comment] 2019-11-14 01:56
K, I'm going to close as no-repro. Let me know if it comes back!

**Closed by DHowett-MSFT** 2019-11-14 01:56 UTC
Labels: Area-TerminalConnection, Issue-Bug, Needs-Attention, Product-Terminal, Severity-Blocking
