### ISSUE TITLE
Windows Terminal bug

### ISSUE THREAD

**Issue by masud4** [microsoft/terminal#11699] opened 2021-11-06 16:15 UTC
### Windows Terminal version (or Windows build number)

Microsoft Windows [Version 10.0.22000.282]

### Other Software

windows 11 wsl

### Code of Conduct

windows 11

### What happened?

This bug goes away when I use the clear command and keyboard enter key. How to solve the problem?

### Version

install official website

### Theme

ohmyposhv3-v2.json

### What OS are you seeing the problem on?

Windows, Linux

### Which shell are you using?

bash

### Expected Behavior

![image](https://user-images.githubusercontent.com/56246849/140616328-0e99593d-bf9c-4b21-8937-29d17a3be0d1.png)

### Actual Behavior

![image](https://user-images.githubusercontent.com/56246849/140613686-a92e2078-5703-4a6d-9656-4677093c56d9.png)

**Comment by elsaco** [comment] 2021-11-06 17:47
@masud4 this looks like a duplicate of https://github.com/microsoft/terminal/issues/8341

**Comment by zadjii-msft** [comment] 2021-11-08 10:53
It sure is! /dup #8341

**Closed by zadjii-msft** 2021-11-08 10:54 UTC
Labels: Needs-Triage, Needs-Tag-Fix
