### ISSUE TITLE
Better translation for the context menu entry in Spanish 

### ISSUE THREAD

**Issue by rubenalamina** [microsoft/terminal#11534] opened 2021-10-19 04:21 UTC
### Windows Terminal version (or Windows build number)

1.10.2714

### Steps to reproduce

Right click on desktop. Notice the context menu entry name in Spanish.

### Expected Behavior

Abrir en Windows Terminal instead of Abrir en Terminal Windows.

### Actual Behavior

Product names are not usually translated so it doesn't sound right to use **Terminal Windows**. It seems like machine translation. The store lists it as **Windows Terminal** which is what everyone would expect in my opinion. The about section uses Windows Terminal so there's inconsistencies with the context menu entry.

[Store listing screenshot](https://i.imgur.com/FhbLXS8.png).

[About screenshot](https://user-images.githubusercontent.com/18356694/137809341-d4f4719a-9d84-4a47-bd7c-3467f62f2b37.png).

Even if the context menu localization is found to be appropriate, it would be better to use **Terminal de Windows** instead, as that implies it's literally Windows' terminal and not a literal translation of Windows Terminal.

**Comment by zadjii-msft** [comment] 2021-10-19 10:58
Thanks for the tip, I believe @lhecker knows how to port translation issues over to the internal loc team, so over to him. Thanks!

**Comment by lhecker** [comment] 2022-02-09 21:43
We've renamed "Windows Terminal" to "Terminal" recently.
I've checked the current app store name and surprisingly it's "Terminal Windows" now. However the context menu entry has been fixed, which is now translated as "Abrir en Terminal". This will be released some time later this week in 1.12.10393.0. I'm going to mark this as a duplicate of #11197 so that we can discuss this in a single place, if you don't mind (this issue seems to be closely related after all).

/dup 11197

**Closed** 2022-02-09 21:43 UTC
Labels: Issue-Bug, Needs-Triage, Product-Terminal, Priority-3, Area-Localization, Area-ShellExtension
