### ISSUE TITLE
Anacona Prompt Add

### ISSUE THREAD

**Issue by JinZhuXing** [microsoft/terminal#3345] opened 2019-10-27 07:28 UTC
Hi,
Please add Anaconda prompt to list.
I installed anaconda, but I can't see it in terminal list.
Please help me.

**Comment by Chen-Zhe** [comment] 2019-10-27 15:30
you can add the following section under "profiles" key in profiles.json to add Anaconda into the list. You might need to change the paths depending on where you installed Anaconda. (the following example is for Anaconda3 installed on the default location)
```json
{
    "acrylicOpacity" : 0.9,
    "closeOnExit" : true,
    "colorScheme" : "Campbell",
    "commandline" : "cmd.exe /K %USERPROFILE%\\Anaconda3\\Scripts\\activate.bat %USERPROFILE%\\Anaconda3",
    "cursorColor" : "#FFFFFF",
    "cursorShape" : "bar",
    "fontFace" : "Consolas",
    "fontSize" : 14,
    "guid" : "{0caa0dad-35be-5f56-a8ff-afceeeaa6100}",
    "historySize" : 9001,
    "icon" : "%USERPROFILE%/Anaconda3/Menu/anaconda-navigator.ico",
    "name" : "Anaconda3",
    "padding" : "0, 0, 0, 0",
    "snapOnInput" : true,
    "startingDirectory" : "%USERPROFILE%",
    "useAcrylic" : true
}
```

**Comment by JinZhuXing** [comment] 2019-10-28 01:33
Thank you for your reply.
I want to if the anaconda is installed on my system, terminal recognize it and add above script automatically.
Thank you.

**Comment by DHowett-MSFT** [comment] 2019-10-29 20:11
This is a /dupe of #2283. Thanks for the request!

**Closed by DHowett-MSFT** 2019-10-29 20:12 UTC
Labels: Issue-Feature, Needs-Tag-Fix, Needs-Triage
