### ISSUE TITLE
"Open in Terminal" option in the Desktop context menu not visible on Windows 10 LTSC 2021

### ISSUE THREAD

**Issue by knownbyfew** [microsoft/terminal#16605] opened 2024-01-26 16:26 UTC
### Windows Terminal version

1.18.3181.0

### Windows build number

19044.3930

### Steps to reproduce

Install Windows 10 LTSC 2021

Get MS Store and install Windows Terminal from there

Restart the PC or restart explorer.exe from the taskbar for everything to load up as an extra measure

Right click on the desktop and you'll notice there's no "Open in Terminal" option but if you right click on a folder on the desktop or in Explorer then the option is visible.

### Expected Behavior

![How-to-Restore-the-Old-Windows-10-Context-Menu-in-Windows-11-Step-by-step-Guide](https://github.com/microsoft/terminal/assets/94841287/27d1042d-29aa-41c2-9d88-f1a47e35977e)

### Actual Behavior

![explorer_Wu61TIhZlk](https://github.com/microsoft/terminal/assets/94841287/3eb3dd22-f6c1-4f7d-8bab-bca51ce85b11)

**Comment by lhecker** [comment] 2024-01-26 16:57
Hey! I believe #14979 is very similar to what you're describing and was closed as a duplicate of #10694, #10496 and #10119. I think we should close this issue as a duplicate as well then. @zadjii-msft Would you agree?

**Comment by knownbyfew** [comment] 2024-01-26 17:20
> Hey! I believe #14979 is very similar to what you're describing and was closed as a duplicate of #10694, #10496 and #10119. I think we should close this issue as a duplicate as well then. @zadjii-msft Would you agree?

Yes, I've seen them before and I still went ahead and made another one thinking their issues are probably fixed by now because 1) These issues were posted a few years ago and a lot of variables come into play such as a software update to the application itself, maybe even an OS update or to top it off maybe even an OS reinstall might have fixed it and 2) They were using the consumer edition of Windows and I'm not.

Adding to that all these issues just seem to have someone providing a workaround and not an actual fix, I was hoping to get something concrete that'll work, maybe reverse engineering the scoop .reg file of adding and removing the Windows Terminal context menu and modifying it to work with the one from Microsoft Store might do the trick? I don't know.

**Comment by the9655a** [comment] 2024-02-04 16:32
I am also having this issue on LTSC, specifically Windows 10 IoT Enterprise LTSC 2021, though it might be an issue across all editions. Installing Terminal application should add "open in terminal" to the context menu.

More info: after installing Terminal from MS Store, you have to restart explorer.exe for the context menu to update. After, you will notice the context menu item missing when trying to right click in the current working directory, like the desktop, or by opening a folder and right clicking in the empty space. However, when right clicking a folder, "Open in Terminal" appears.

**Comment by zadjii-msft** [comment] 2024-02-06 22:42
I'm pretty sure this just goes over with the rest of the fire in https://github.com/microsoft/terminal/issues/14185#issuecomment-1324144884. There's definitely known issues in Windows 10 with the "packaged" context menu entries. Issues that we suspect were fixed in Windows 11, but without necessarily being backported to Windows 10 😕 

/dup #14185

**Closed by zadjii-msft** 2024-02-06 22:42 UTC
Labels: Issue-Bug
