### ISSUE TITLE
Having many tabs means that some of them (on the right) will disappear

### ISSUE THREAD

**Issue by FriskyDev** [microsoft/terminal#2812] opened 2019-09-19 16:14 UTC
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18362.356]
Windows Terminal version (if applicable): Windows Terminal (Preview) Version: 0.4.2382.0
```

# Steps to reproduce

1. Open many terminal tabs -or- a small number with long titles
1. Note that at some point, depending on the width of the screen, new tabs do not appear on the tab bar at the top.
1. The tab is there, and you can `Ctrl+Tab` -or- `Ctrl+Shift+Tab` to cycle the tabs.

# Expected behavior

1. Current tab is **always** shown when on that tab.
1. Tab bar can scroll left or right to make the current tab show in the tab bar.
1. Current tab shows as much of title bar from left to right as possible, still allowing other tabs to have enough space to be clickable.
1. Cycling through tabs does not show hidden tabs even when landing on one of the hidden tabs.
1. Would really like to have the **option** as in VS Code to not have and `X` to close, but instead *right-click* `Close` menus item. This will be important as you apply making items smaller that are not the current tab-item, as it will be easy to click the close box by accident. Or, you can make the close box `X` only visible for the currently highlighted tab, but this seems overly complicated.
1. If there are too many items in the list, the last item should be `...`, and clicking it should list all the tabs in order.
1. Tabs should be able to be moved to a different position in the list.
1. Hovering over a tab that has been shortened due to screen real estate should show a popup indicating the full title. (Bonus points for showing other information about the tab (date it was opened, how long the session has been opened, what type of prompt it is such as PowerShell, CMD, Linux, etc.)

# Actual behavior

1. If you `Ctrl+Tab` to a tab that is not in the list at the top, the tab is still not shown. There is no way to verify which tab you are on, except based on what was in the window as you left it.
1. The current tab is not highlighted to indicate which tab is the current tab.
1. The tab bar shows a static list of the first few items, each at their full width until space runs out.
1. All tabs are shown at full width, even though they are not the currently selected tab.
1. There is no UI for accessing the full list of all open terminals.
1. There is no way to scroll through the list of tabs. Usually down with `<` and `>` buttons appearing when the list becomes to big to display fully in the tab bar.

**Comment by DHowett-MSFT** [comment] 2019-09-19 21:47
Hey, thanks for the in-depth analysis here! This is largely a duplicate of /dup #857, and will be fixed by #1896.

**Closed by DHowett-MSFT** 2019-09-19 21:47 UTC
Labels: Needs-Tag-Fix, Needs-Triage
