### ISSUE TITLE
[1.17] Launch Params in SUI needs a little cleanup

### ISSUE THREAD

**Issue by carlos-zamora** [microsoft/terminal#14558] opened 2022-12-14 23:30 UTC
# Bug 1: Launch Params resizes as you type X/Y val

<details>
<summary>Duped to  #13495</summary>

<img width="358" alt="image" src="https://user-images.githubusercontent.com/11050425/207737443-104ee2c6-c331-4fe6-b369-0c8232c059eb.png">

Then when you click off of it, it looks like the num box buttons appear over the text? Weird. 
<img width="93" alt="image" src="https://user-images.githubusercontent.com/11050425/207737476-59c3a7cc-5828-4933-a8e5-89d28dba7d9a.png">

</details>

# Bug 2: rework Launch Params preview
I still feel like "Default,Default" should be something like… 

"Let system position window" or "system position" or whatever 

Should "Use system default" be renamed to "Let system position window"

**Comment by ianjoneill** [comment] 2022-12-15 08:39
I think bug 1 may be a dupe of #13495 - the history size input does exactly the same thing.

**Comment by zadjii-msft** [comment] 2022-12-15 12:28
> I think bug 1 may be a dupe of https://github.com/microsoft/terminal/issues/13495

Yes it is

> Should "Use system default" be renamed to "Let system position window"

absolutely yes

**Comment by carlos-zamora** [comment] 2022-12-15 17:39
@zadjii-msft  Hmm... Since #13495 is tracking upgrading to WinUI 2.8 (which would fix the bug, of course, but it's a lot of extra work). How do we feel about changing the `SpinButtonPlacementMode` from `Inline` to `Compact`? I assume that fixes the problem and it would be super simple.

**Comment by zadjii-msft** [comment] 2022-12-15 18:33
> How do we feel about changing the SpinButtonPlacementMode from Inline to Compact? I assume that fixes the problem and it would be super simple.

I mean, _would it_? I'm honestly fine leaving that half of the bug as is (and waiting for eventually figuring out winui 2.8), it only happens with huge numbers anyways, yea?

**Comment by carlos-zamora** [comment] 2022-12-15 18:39
> > How do we feel about changing the SpinButtonPlacementMode from Inline to Compact? I assume that fixes the problem and it would be super simple.
> 
> I mean, _would it_? I'm honestly fine leaving that half of the bug as is (and waiting for eventually figuring out winui 2.8), it only happens with huge numbers anyways, yea?

I did the thing: #14569

**Closed** 2022-12-16 21:00 UTC
Labels: Issue-Bug, Product-Terminal, In-PR, Area-Settings UI
