### ISSUE TITLE
Code Health: Deps - Update all dependencies prior to v2.

### ISSUE THREAD

**Issue by WSLUser** [microsoft/terminal#5297] opened 2020-04-09 17:49 UTC
# Description of the new feature/enhancement

We should try to ship with the least amount of bugs possible, this includes updating dependencies that haven't been touched since Terminal was first released into the wild such as WinAppDriver
# Proposed technical implementation details (optional)

We should enable the dependabot from github but for now we just need to import the newest releases and verify nothing has changed. I did already review CLI11 based on their release notes and believe we can update it with no code changes to Terminal.

**Comment by DHowett-MSFT** [comment] 2020-04-09 18:20
> dependencies that haven't been touched since Terminal was first released into the wild such as CLI11

to be fair, this dependency was added in _November_, and it was the newest available version in November. It's not factual to state that it hasn't been touched since Terminal was first released into the wild.

**Comment by WSLUser** [comment] 2020-04-10 12:46
I was basing it off the version history of the deps. If I have time, I plan on submitting a PR for some of the more trivial updates.

**Comment by WSLUser** [comment] 2020-04-10 19:55
Yeah I think most of the stuff in deps is being managed by Nuget but with the private feed not entirely sure how to get them updated. The only 2 that could get updated easily if they ever needed updates are `wil `and `gsl `due to using git submodules. I was starting to look into using submodules for the rest of the deps and that was when I realized Nuget is being used.

**Comment by carlos-zamora** [comment] 2020-05-12 18:22
@DHowett-MSFT just realized that this one seems weird to be in the v1.x milestone. Any reason this one's blocked? Maybe we could resolve it fairly quickly?

**Comment by zadjii-msft** [comment] 2020-05-12 21:11
IMO at this point, there might be subtle regressions in our deps that we won't have enough runway to catch, and we might as well go with the known issues we currently have. Take for example the seemingly safe update to MUX 2.4 (in #5778). That secretly regressed `AccentButtonStyle`. I think at this point we'd rather the devil you know. 

That's my 2¢

**Comment by WSLUser** [comment] 2020-05-13 00:39
I noticed a 2 line change in Chrome math seems to break things. But I was also testing it with other dep updates. Some seemed benign though

**Comment by WSLUser** [comment] 2020-05-13 00:42
for example, we should update wil. It would be nice if gsl could be as well but I saw why we can't. Alot of the deps could be made into git submodules. I think that would be the route to go to help update more easily.

**Comment by DHowett-MSFT** [comment] 2020-05-13 00:47
So, many of the deps are transcluded instead of imported as submodules because this repository is ingested into the Windows build system (and the Windows repository) where we cannot use submodules. Packages that aren't part of Windows, but which we still need, are in `/oss`.

**Comment by WSLUser** [comment] 2020-05-13 00:54
So that leaves nugey as the other option if possible.

**Comment by zadjii-msft** [comment] 2020-08-18 17:58
You know what, we've bumped almost all our deps since this issue was originally filed in April, so I think we can close this out. I don't really think we need an open-ended generic work item for "bump our deps" 😄

**Closed by zadjii-msft** 2020-08-18 17:58 UTC
Labels: Area-CodeHealth, Issue-Task, Product-Terminal
