### ISSUE TITLE
Windows terminal does not show missing dll popup

### ISSUE THREAD

**Issue by codec-abc** [microsoft/terminal#9788] opened 2021-04-12 15:31 UTC
### Windows Terminal version (or Windows build number)

1.6.10571.0

### Steps to reproduce

When opening a program that lack a dll from Windows Terminal, the usual popup that reveal the problem is not shown. For example, today I wanted to test the 0.3 version of [Mun](https://github.com/mun-lang/mun). To do this, I downloaded the release, extracted it somewhere and launched Windows Terminal into the extracted directory. Then running commands, nothing particular happened giving me the impression the program ran fine but without doing anything. You can find the Mun issue I opened [here](https://github.com/mun-lang/mun/issues/322) about this. The thing is that I don't have the Visual Studio 2019 runtime installed. While this is a Mun distribution issue, the problem is not reported with Windows Terminal while it is with other terminals.

### Expected Behavior

The expected behavior would be the the one when using ``cmd.exe`` or Cmder where a popup appear revealing the underlying issue. See screenshot below for their respective behavior.

![image](https://user-images.githubusercontent.com/1208646/114420330-843de700-9bb4-11eb-9df1-da20990023e4.png)

![image](https://user-images.githubusercontent.com/1208646/114420397-93bd3000-9bb4-11eb-97bd-65047cb0d1f6.png)

### Actual Behavior

In the tested version, no popup appear which make finding the underlying problem harder.

![image](https://user-images.githubusercontent.com/1208646/114420851-fe6e6b80-9bb4-11eb-8a04-1f50e8401746.png)

**Comment by DHowett** [comment] 2021-04-12 15:37
Curious. The only difference between a standard console host and Terminal is that there is no console window handle.

**Comment by zadjii-msft** [comment] 2021-04-12 15:41
Does the popup appear, but somewhere else in the z-order? Like, is the popup still in the alt-tab list of windows somewhere?

**Comment by codec-abc** [comment] 2021-04-12 15:46
@zadjii-msft : No popup nor the error sound. Same thing goes for Powershell (though I am not sure how to run a program with Powershell). Funny fact, git bash terminal does not have the popup nor the sound alert but report the problem as text.

![image](https://user-images.githubusercontent.com/1208646/114422947-016a5b80-9bb7-11eb-983c-395d95b60fe5.png)

**Comment by zadjii-msft** [comment] 2021-04-12 15:48
I wonder if cmd.exe is calling [`GetConsoleWindow`](https://docs.microsoft.com/en-us/windows/console/getconsolewindow) to pop that messagebox on top of conhost 😨

**Comment by DHowett** [comment] 2021-04-12 18:19
It's not. This error message seems to be generated via `NtRaiseHardError` which is handled by _csrss_ (as far as I can tell...)

**Comment by DHowett** [comment] 2021-04-13 18:09
I'm going to close this one as a /dup of #2988 -- I think us not having a real window on-screen prevents the dialog from being displayed.

Thanks!

**Closed by DHowett** 2021-04-13 18:09 UTC
Labels: Needs-Attention, Needs-Tag-Fix, Needs-Triage

**Comment by codec-abc** [comment] 2021-04-13 18:19
This is might be true only if you want to display a dialog. But if going the git bash way could be enough to fix this in my opinion. Arguably it could be even better because popup are kind of annoying in this case and the git bash error message is clearer (the issue might be poorly named since the complain is more about the lack of feedback about missing dll rather than the popup itself)

Also is it sure that it is linked to some real windows on-screen issue? Since the behavior nor the error message is not the same between git bash and other there might be something else than the windowing issue.

**Comment by zadjii-msft** [comment] 2021-04-13 19:08
Clearly, git bash and cmd.exe are deciding to display the error in different ways. We can't modify the way cmd.exe works unfortunately. Since the behavior in cmd.exe seems to be linked to the missing console HWND, that's the best we can do for bringing that dialog back.

**Comment by codec-abc** [comment] 2021-04-13 22:27
So  you are saying there is no easy workaround for this? My guess is that #2988 is rather hard to fix and might not be fixed soon. So being pragmatic here, if somehow there is an easy way to catch this error it might be worth trying to print a message (dunno Windows internal but there might be  a way to catch the ``NtRaiseHardError`` event) . Otherwise if it is as hard (or even harder) it makes sense to close this and wait for the resolution of 2988. What's your opinion on this?

**Comment by zadjii-msft** [comment] 2021-04-14 12:10
* Yes, there's no easy workaround for this
* #2988 is going to be hard to do right. There's no good plan for that one, but a lot of _bad_ plans.
* It would be even _harder_ to fix cmd.exe. I'd rather wait for heat death of the universe than touch cmd.exe.

Given the above, we're gonna leave this closed as a duplicate of #2988 and hope that's figured out
