### ISSUE TITLE
Add open in Terminal context menu to Windows explorer

### ISSUE THREAD

**Issue by gabog** [microsoft/terminal#2063] opened 2019-07-22 17:13 UTC
# Summary of the new feature/enhancement

It would be nice if it was possible to right click on a folder in Windows Explorer and select "Open in Terminal" sort of like you can do with PowerShell 6.0. 

![image](https://user-images.githubusercontent.com/12264946/61650501-dcff7a80-ac81-11e9-9cce-2e6a3f3d8d79.png)

It would also be nice to be able to type "terminal" on the windows explorer address bar and have terminal open on that folder (like powershell does).

For example:
1. Go to a folder in Windows Explorer (i.e. c:\temp)
![image](https://user-images.githubusercontent.com/12264946/61650634-23ed7000-ac82-11e9-8140-74b839c2fc2c.png)

2. Type pwsh in the address bar and hit enter
![image](https://user-images.githubusercontent.com/12264946/61650665-3667a980-ac82-11e9-8a6e-3a61f0187e69.png)

3. A powershell 6.0 terminal window opens on the C:\temp folder:
![image](https://user-images.githubusercontent.com/12264946/61650734-58f9c280-ac82-11e9-8607-796612bbc4d5.png)

**Comment by DHowett-MSFT** [comment] 2019-07-22 17:59
this is a duplicate of #1060; please make sure to search before reporting a new issue!

**Closed by DHowett-MSFT** 2019-07-22 17:59 UTC
Labels: Issue-Feature, Needs-Tag-Fix, Needs-Triage

**Comment by gabog** [comment] 2019-07-22 18:03
OK, by bad, I searched for it but didn't find it.
Thanks

**Comment by sundowatch** [comment] 2020-03-29 19:06
[Here](https://windowsloop.com/add-open-windows-terminal-here-option-to-right-click-menu/) is a solution.
