### ISSUE TITLE
Open "popup" consoles in a new tab or pane (e.g. if a script runs `start cmd`)

### ISSUE THREAD

**Issue by Danation** [microsoft/terminal#3906] opened 2019-12-10 22:33 UTC
# Description of the new feature/enhancement

Some scripts open new consoles to run multiple tasks concurrently.  For example, a script might run a web server while also running a watch command on source files.

Right now if something like `start cmd` is called, a new window is popped up.  It would be nice to contain that inside Windows Terminal and open it in a new tab or new pane.

# Proposed technical implementation details (optional)

It seems like it would be convenient to have a global setting for how to handle popups.  The default could retain current behavior, but a user could choose "new tab" or "new horizontal pane" or something along those lines.

(Forgive me if this has already been asked. I looked around quite a bit for this, but I could have missed it.)

**Comment by DHowett-MSFT** [comment] 2019-12-10 22:34
This is, fundamentally, a /dupe of #492... but I wouldn't expect anybody to know that :smile:

**Closed by DHowett-MSFT** 2019-12-10 22:34 UTC
Labels: Issue-Feature, Needs-Tag-Fix, Needs-Triage

**Comment by Danation** [comment] 2019-12-10 22:41
Fair enough, thanks!
