### ISSUE TITLE
Double-click selection in vim doesn't wrap onto next line (although Terminal understands it's a single line)

### ISSUE THREAD

**Issue by vadimkantorov** [microsoft/terminal#14263] opened 2022-10-20 09:40 UTC
### Windows Terminal version

1.15.2713.0 (btw would be nice if wt -v dialog window allowed copy of text)

### Windows build number

10.0.22621.674

### Steps to reproduce

Have a long line (url) in vim wrapping on multiple lines. It gets highlighted/underscored as a URL, so Terminal understands that it's a single line. But double-click for select/copy-on-select doesn't wrap around.

![image](https://user-images.githubusercontent.com/1041752/196913810-49b350c6-4741-4698-b8cb-7649edd474f0.png)

### Actual Behavior

Not the full line is selected

**Comment by lhecker** [comment] 2022-10-20 15:05
I believe this is a /duplicate of #6178.

**Closed** 2022-10-20 15:05 UTC
Labels: Issue-Bug, Needs-Triage

**Comment by DHowett** [comment] 2022-10-20 17:13
This may be like the bash issue, though, if vim is hard-wrapping its text. The URL detector strings together every line (which is also a problem, but in the other direction: it ignores hard wraps)!

**Comment by DHowett** [comment] 2022-10-20 17:43
> btw would be nice if wt -v dialog window allowed copy of text

Funny enough, it does! All win32 dialogs/message boxes can be copied to the clipboard with Ctrl+C! They even get a fun hard copy rendition:

```
---------------------------
Help
---------------------------
Windows Terminal Preview
1.17.2842.0
---------------------------
OK   
---------------------------
```

**Comment by vadimkantorov** [comment] 2022-10-20 20:16
> Funny enough, it does!

Wow! It probably should be explicitly added to a dialog window title or window text. I bet that no more than 1000 people on the globe know about this win32 feature :)

**Comment by vadimkantorov** [comment] 2022-10-20 20:18
> This may be like the bash issue, though, if vim is hard-wrapping its text.

Bash can interfere into vim? My problem was specifically with vim.

But bash seems to have the same problem: 
![image](https://user-images.githubusercontent.com/1041752/197049648-c452306e-dac5-4246-96f1-b649813df833.png)

**Comment by DHowett** [comment] 2022-10-20 21:56
> Bash can interfere into vim?

Sorry, what I mean is this.

bash does hard line wrapping.
Maybe vim does hard line wrapping too.

(It may be "like" the bash issue you'd filed. 🙂)

**Comment by vadimkantorov** [comment] 2022-10-20 22:14
Maybe at least for the case of URLs, the hard-wrap merging could be enabled... it's very strange that uncerscoring and selection do not match
