### ISSUE TITLE
Add a releases link with ready to download versions of windows terminal

### ISSUE THREAD

**Issue by memtech3** [microsoft/Terminal#517] opened 2019-05-07 15:31 UTC
Add a github releases page so that users can download without having to compile on their own

**Comment by zadjii-msft** [comment] 2019-05-07 15:32
Dupe of #468.
### There are no binaries to download quite yet. 

The Windows Terminal is in the _very early_ alpha stage, and not ready for the general public quite yet. If you want to jump in early, you can try building it yourself from source. 

Otherwise, you'll need to wait until Mid-June for an official preview build to drop.

**Closed by zadjii-msft** 2019-05-07 15:32 UTC

**Comment by memtech3** [comment] 2019-05-07 15:34
ok thanks! can you pin the original issue so no one else submits a dupe
