### ISSUE TITLE
PowerShell Keyboard Shortcuts CTRL+SPACE missing

### ISSUE THREAD

**Issue by lenihan** [microsoft/terminal#4590] opened 2020-02-14 16:31 UTC
# Environment

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Windows Terminal version (if applicable):

Any other software?
```
Microsoft Windows NT 10.0.18363.0
Windows Terminal (Preview) 0.9.433.0

# Steps to reproduce

Open PowerShell
Type "ls -" and the press CTRL+SPACE

# Expected behavior

See a list of parameter options for ls

# Actual behavior

No output

**Comment by DHowett-MSFT** [comment] 2020-02-14 17:47
Thanks! This is a /dupe of #879.

**Closed by DHowett-MSFT** 2020-02-14 17:47 UTC
Labels: Needs-Tag-Fix, Needs-Triage

**Comment by omril1** [comment] 2020-07-13 08:22
Reproducing only on `Windows Powershell`, `Powershell Core` seems to work fine.
