### ISSUE TITLE
"Shift-Tab" and "Tab" insert the same character in MSYS2

### ISSUE THREAD

**Issue by matteocoder** [microsoft/terminal#12488] opened 2022-02-14 18:33 UTC
### Windows Terminal version

1.12.10393.0

### Windows build number

Microsoft Windows [Version 10.0.22000.493]

### Other Software

GNU bash, version 4.4.23(2)-release (x86_64-pc-msys), Git for Windows 2.35.1.windows.2

### Steps to reproduce

Prerequisites: install Git for Windows, then set up Git Bash in Windows Terminal as follows:
```
{
                "commandline": "C:\\Program Files\\Git\\bin\\bash.exe -i -l",
                "guid": "{763c51e6-3ab8-413c-b51c-2fd2abf9fba8}",
                "icon": "C:\\Program Files\\Git\\mingw64\\share\\git\\git-for-windows.ico",
                "name": "Git-Bash",
                "startingDirectory": "%USERPROFILE%",
                "tabTitle": "Git Bash"
            }
```
Also, make sure that `ctrl-v` is unbound in Windows Terminal.
Open Git Bash in Windows Terminal, then press `ctrl-v`, and finally `shift-tab`.

### Expected Behavior

The escape code `^[[Z` should be displayed on the screen.

### Actual Behavior

Pressing `shift-tab` inserts a tab character anyway.

**Comment by DHowett** [comment] 2022-02-14 19:21
This seems to be an issue with Git Bash (or, more likely, the Cygwin-based MSYS2 runtime it is using):

<img width="479" alt="image" src="https://user-images.githubusercontent.com/189190/153931603-764f1477-f4c1-490d-a2cf-49cab039af0a.png">

Above, <kbd>Shift+Tab</kbd> working in WSL.

**Comment by DHowett** [comment] 2022-02-14 19:21
What is the value of `$TERM` in your shell?

**Comment by matteocoder** [comment] 2022-02-14 19:33
@DHowett it is `xterm-256color`. `shift-tab` works as it should in Git Bash launchet through mintty.
> This seems to be an issue with Git Bash (or, more likely, the Cygwin-based MSYS2 runtime it is using)

In that case, should I report the issue to them?

**Comment by DHowett** [comment] 2022-02-14 19:38
Curiously, I can't reproduce this inside Terminal _or inside_ the traditional console host.

<img width="459" alt="image" src="https://user-images.githubusercontent.com/189190/153934138-1d5a5c4b-bf04-4080-a75b-5d4113ee9048.png">

<img width="246" alt="image" src="https://user-images.githubusercontent.com/189190/153934178-a397dc34-9822-40c3-873f-d49ea86540c3.png">


What happens if you launch GIt Bash outside Terminal but using the old console window? FWIW: MSYS2 has a special contract with mintty that means it avoids a bunch of the Windows input APIs, so it good for "right behavior" testing but bad for "is this Terminal's fault, Console's fault, or Windows' fault" testing :smile:

**Comment by matteocoder** [comment] 2022-02-14 19:50
@DHowett Unfortunately it does not work in conhost either.

> FWIW: MSYS2 has a special contract with mintty that means it avoids a bunch of the Windows input APIs, so it good for "right behavior" testing but bad for "is this Terminal's fault, Console's fault, or Windows' fault" testing 😄

I see... I'll keep that in mind if I find other issues in the future 😅.

**Comment by matteocoder** [comment] 2022-02-14 19:59
@DHowett Thank you for your help!

**Comment by DHowett** [comment] 2022-02-14 23:38
Sure thing! I'm gonna close this one as external. If you don't mind following up with a link to the bug you file on their end, I'd appreciate it :)

**Closed by DHowett** 2022-02-14 23:38 UTC
Labels: Issue-Bug, Needs-Triage, Needs-Attention, Needs-Tag-Fix

**Comment by matteocoder** [comment] 2022-02-14 23:54
@DHowett Sure, [here is the link](https://github.com/msys2/MSYS2-packages/issues/2861#issue-1137985473).
Also, how do you insert a literal control character inside conhost?
