### ISSUE TITLE
Holding a specific area at the top of the window does not achieve dragging

### ISSUE THREAD

**Issue by freewangba** [microsoft/terminal#1516] opened 2019-06-24 07:28 UTC
![image](https://user-images.githubusercontent.com/37213113/59999479-a93a3080-9694-11e9-900f-ee5f3b111cf0.png)

**Comment by Shorotshishir** [comment] 2019-06-24 07:32
please refer to issue  #1375 
thank you

**Comment by merlinfrombelgium** [comment] 2019-06-24 08:07
+1

**Comment by HBelusca** [comment] 2019-06-24 11:01
Duplicate of #1500, #1412, #1395 ; issue encompassed in #1375.

**Comment by DHowett-MSFT** [comment] 2019-06-24 16:10
That's right. Thanks @HBelusca!

**Closed by DHowett-MSFT** 2019-06-24 16:10 UTC
Labels: Needs-Tag-Fix, Needs-Triage
