### ISSUE TITLE
Portable Release

### ISSUE THREAD

**Issue by arontsang** [microsoft/terminal#10705] opened 2021-07-19 10:09 UTC
In enterprise environments, package managers and application stores are typically locked down.

Applications that we can use need to go through a vetting and packaging process before being allowed onto dev boxes.

A portable release would make it much easier for enterprises to deploy using existing channels.

**Comment by zadjii-msft** [comment] 2021-07-19 12:51
Thanks for asking. This is a /duplicate of #1386.

**Closed by zadjii-msft** 2021-07-19 12:51 UTC
Labels: Needs-Tag-Fix, Needs-Triage
