### ISSUE TITLE
Great tool! The tool should able to save workspace when it is closed.

### ISSUE THREAD

**Issue by dinhanhvo** [microsoft/terminal#9046] opened 2021-02-05 07:30 UTC
# Environment

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Windows Terminal version (if applicable):

Any other software?
```

# Steps to reproduce

# Expected behavior

# Actual behavior

**Comment by skyline75489** [comment] 2021-02-05 08:41
See #766

**Comment by zadjii-msft** [comment] 2021-02-05 12:29
Yea, this _sounds_ like a dupe of #766, though it's impossible to say for sure with a blank issue like this. 

/dup #766

**Closed by zadjii-msft** 2021-02-05 12:29 UTC
Labels: Needs-Tag-Fix, Needs-Triage

**Comment by Poopooracoocoo** [comment] 2021-02-15 02:47
By workspace, I think you mean virtual desktop. Funnily enough, Microsoft has a service called Virtual Desktop. I don't agree that it should only open on one virtual desktop. It should open on the desktop it was opened from. Microsoft Office used to have a _bug_ where it would switch desktops because it would open the last instance of an app. It _still_ opens the last instance of an app, but doesn't switch desktops anymore.
