### ISSUE TITLE
send alt-space to terminal instead of capture it

### ISSUE THREAD

**Issue by shelper** [microsoft/terminal#10068] opened 2021-05-10 14:59 UTC
currently when i press alt+space, the keybinding causes the terminal window to popup a window as below
![image](https://user-images.githubusercontent.com/546163/117679854-a197ae00-b17e-11eb-851c-7c920b3facac.png)

It would be useful if this alt+space keybinding can be sent to terminal directly, cus something l am running terminal apps like emacs which uses this keybinding for certain function

**Comment by DHowett** [comment] 2021-05-13 19:55
Thanks for the request! Looks like this is a /duplicate of #7125. We should probably let you unbind that (but keep it bound by default to the system menu.)

**Closed by DHowett** 2021-05-13 19:55 UTC
Labels: Issue-Feature, Needs-Tag-Fix, Needs-Triage
