### ISSUE TITLE
Feature Request: ZModem support

### ISSUE THREAD

**Issue by onovotny** [microsoft/terminal#2229] opened 2019-08-04 00:51 UTC
# Description of the new feature/enhancement
Terminal should support ZModem upload/download. ZModem is a friction-free way to transfer files up to 4GB in size in a terminal session without using other tools.

# Proposed technical implementation details (optional)
Add support for ZModem

**Comment by bfayers** [comment] 2019-08-04 10:25
What's wrong with SCP?

**Comment by DHowett-MSFT** [comment] 2019-08-05 04:49
This is actually a duplicate of #1602

**Closed by DHowett-MSFT** 2019-08-05 04:49 UTC
Labels: Issue-Feature, Needs-Tag-Fix, Needs-Triage

**Comment by therevoman** [comment] 2020-12-07 23:09
SCP is great.  but rz and sz can be used when inside a nested ssh session.  

in secure environments its often the case that one needs to ssh into a bastion/jumphost.   from there, ssh into the next layer and finally to the box you need to work on.   rz and sz can be initiated straight to/from that 3rd layer terminal direct from the users terminal, avoiding the need to scp/ssh/scp/ssh/scp....

**Comment by lonnywong** [comment] 2023-08-04 01:11
https://trzsz.github.io/ssh supports [trzsz](https://github.com/trzsz/trzsz)  ( trz / tsz ), similar to rz / sz.

**Comment by sysxtreme** [comment] 2025-05-07 10:55
It's very annoying when you ask for a specific feature and someone responds by offering features you already know about, and that don't solve the problem. SCP and SFTP are tedious, they work in some scenarios, but when you just want to download a file directly from your already logged-in session, it's impossible to achieve efficiently.

Zmodem-like functionality would speed up tasks and optimize management. Tools like trzsz and trzsz-ssh handle this well, but it would be great to have such functionality built into Windows Terminal, so there's no need to install additional software.
