### ISSUE TITLE
Is there a way to open Terminal in Quake mode by default?

### ISSUE THREAD

**Issue by amithegde** [microsoft/terminal#12150] opened 2022-01-12 20:45 UTC
I have looked around but could not find, is there a way to open Terminal in Quake mode?

- Provide a Setting to open terminal in quake mode by default.

Currently, I open terminal in Admin mode, by finding it on the start menu and hitting `Ctrl+Shift+Enter` and then hit Ctrl+` to open quake mode and continue with my work. I manually have to close one instance of the terminal since I continue with quake mode from that point.

When I was using ConEmu, there was a setting which allowed opening it in Quake Mode by default which improves workflow.

**Comment by bzzrak** [comment] 2022-01-14 16:29
You can run `wt --window "_quake"` instead

**Comment by amithegde** [comment] 2022-01-14 19:08
> You can run `wt --window "_quake"` instead

This is a great tip, though I need to have another cmd open to run the above command it seems. The terminal doesn't provide a way to pin to task bar, then right click to change properties where we can make it run in admin mode and provide additional parameters.

**Comment by bzzrak** [comment] 2022-01-15 16:43
@amithegde you don't have to. RIght click the desktop --> new --> Shortcut, then put the command in there, and you have a shortcut that opens a quake window. Zou can then pin this shortuct to the taskbar

**Comment by zadjii-msft** [comment] 2022-01-18 15:32
Yea, there's not a _great_ way to achieve what you're looking for today. Especially not elevated. #12142 might make this a little easier. I suspect #9992 will do a lot of this ask, by allowing you to set the Terminal to open the `_quake` window by default.

For tracking sake, I'm gonna close this as a /duplicate of #9992. That should get you close enough (whenever that lands)

**Closed by zadjii-msft** 2022-01-18 15:32 UTC
Labels: Issue-Feature, Needs-Triage, Needs-Tag-Fix

**Comment by eggbean** [comment] 2023-11-21 00:48
I find that a reliable way to do this is to launch Windows Terminal through the PowerToys Run launcher.

**Comment by orsnaro** [comment] 2026-07-07 15:30
also if  the profile `Run this profile as Adminstrator` option was on  the new window will not open in quake mode
