### ISSUE TITLE
Autodetected WSL profiles do not appear if Terminal opened too soon after login

### ISSUE THREAD

**Issue by cerebrate** [microsoft/terminal#9169] opened 2021-02-15 16:26 UTC
# Environment

```none
Windows build number: 10.0.21313.0
Windows Terminal version (if applicable): 1.6.10412.0 or earlier

Any other software?

WSL, any distribution(s) installed
```

# Steps to reproduce

1. Log on to Windows.
2. _Immediately_ open Windows Terminal.
3. Observe that the WSL distributions are not listed on the '+' drop-down menu.
4. Close Terminal and wait for a short time.
5. Reopen Terminal.
6. Observe that the WSL distributions are now properly listed.

It may be necessary for the machine to be heavily loaded on logon to trigger the issue.

# Expected behavior

The WSL distributions installed on the machine/listed in the profile to be displayed always.

# Actual behavior

WSL distributions installed on the machine, even those whose profile has been customized in the Terminal settings, do not appear in the '+' drop-down menu until the machine has passed a certain stage of the logon process. While this can be worked around by opening Settings and making a null edit, or by closing and reopening Terminal, it does effectively render the "Launch on machine startup" setting useless for its intended purpose.

**Comment by Don-Vito** [comment] 2021-02-15 19:21
@cerebrate - please review if https://github.com/microsoft/terminal/issues/7199 covers your ask.

**Comment by DHowett** [comment] 2021-02-15 19:22
Thanks for the report! This looks like a /duplicate of #7199

**Closed by DHowett** 2021-02-15 19:22 UTC
Labels: Needs-Tag-Fix, Needs-Triage
