### ISSUE TITLE
Support linux paths for `startingDirectory` of WSL distros

### ISSUE THREAD

**Issue by tackyunicorn** [microsoft/terminal#592] opened 2019-05-08 18:32 UTC
* Your Windows build number:  `Microsoft Windows [Version 10.0.18362.86]`

* What you're doing and what's happening:  
Setting the starting directory for wsl in `profiles.json` doesn't make it point to the right directory.  
1. Take the config below :-  
```json
{
        "startingDirectory": "C:/Users/joshj/AppData/Local/Packages/CanonicalGroupLimited.Ubuntu16.04onWindows_79rhkp1fndgsc/LocalState/rootfs/home/tackyunicorn",
        "guid": "{a2785f8e-72c9-4550-b406-697388644902}",
        "name": "Ubuntu",
        "colorscheme": "MonokaiVivid",
        "historySize": 9001,
        "snapOnInput": true,
        "cursorColor": "#FFFFFF",
        "cursorHeight": 25,
        "cursorShape": "vintage",
        "commandline": "wsl.exe",
        "fontFace": "Inconsolata for Powerline",
        "fontSize": 10,
        "acrylicOpacity": 1,
        "useAcrylic": true,
        "closeOnExit": true,
        "padding": "10, 10, 10, 10",
        "icon": "ms-appdata:///roaming/ubuntu.png"
}
```  
This results in wsl starting up in the root folder  
![issue1](https://user-images.githubusercontent.com/26558907/57397677-d9179c80-71ea-11e9-9f35-a1176a5368d8.png)

2. In this config :-  
```json
{
        "startingDirectory": "/home/tackyunicorn",
        "guid": "{a2785f8e-72c9-4550-b406-697388644902}",
        "name": "Ubuntu",
        "colorscheme": "MonokaiVivid",
        "historySize": 9001,
        "snapOnInput": true,
        "cursorColor": "#FFFFFF",
        "cursorHeight": 25,
        "cursorShape": "vintage",
        "commandline": "wsl.exe",
        "fontFace": "Inconsolata for Powerline",
        "fontSize": 10,
        "acrylicOpacity": 1,
        "useAcrylic": true,
        "closeOnExit": true,
        "padding": "10, 10, 10, 10",
        "icon": "ms-appdata:///roaming/ubuntu.png"
}
```  
This results in wsl starting up in the Windows user folder  
![issue2](https://user-images.githubusercontent.com/26558907/57398045-ba65d580-71eb-11e9-9109-79a9ad601e12.png)

* What's wrong / what should be happening instead:  
The `startingDirectory` profile setting is not being applied correctly on a wsl profile

**Comment by caksoylar** [comment] 2019-05-08 19:03
it looks like it expects Windows paths but passing the WSL fs paths under AppData directly doesn't work. Using the new UNC path works for me:
`"startingDirectory":"//wsl$/Ubuntu/home/cem/src"` -> `~/src`

So does regular Windows locations:
`"startingDirectory":"C:/wd"` -> `/mnt/c/wd`

**Comment by zadjii-msft** [comment] 2019-05-08 19:19
Hmm. We should maybe add a setting to suggest that the startingDirectory is a wsl path. Right now we're just manually setting the working directory of the client app we're starting, so we'd have to specifically know that the profile was trying to be wsl, and adjust our logic for passing in a working directory.

**Comment by sandeepkv93** [comment] 2019-05-19 22:35
one easy hack would be inside ~/.bashrc file of wsl, add the line
`cd ~`

Problem solved.

**Comment by DHowett-MSFT** [comment] 2019-05-20 19:30
> one easy hack would be inside `~/.bashrc` file of wsl, add the line
> `cd ~`
> 
> Problem solved.

This is also a great way to get weird and unexpected behaviour in everything else that uses bash on your machine. :smile:

**Comment by JBanks** [comment] 2019-06-09 13:20
This method is a little bit of work.  We could parse out the distribution name from the command in the profile so that `wsl.exe -d Ubuntu` gives us "Ubuntu", and then pass that to `Profile::EvaluateStartingDirectory`.  Then, if it fails, before setting it to `%userprofile%` we can evaluate `\\WSL$\[distributionName][directory]` and see if that is a valid directory path.

Or we could make the method a non-static method and draw the value from `_commandline`.

**Comment by benc-uk** [comment] 2019-06-22 08:27
@sandeepkv93 - That hack isn't the best. When working in say VS Code and you want your WSL terminal to open inside your project directory, this will prevent that. Definitely going to cause other problems too

**Comment by jkugiya** [comment] 2019-06-24 10:09
My workaround
```
"commandline" : "wsl.exe ~  -d WLinux"
```

**Comment by jasonNXP** [comment] 2019-06-26 15:49
> 
> 
> My workaround
> 
> ```
> "commandline" : "wsl.exe ~  -d WLinux"
> ```

simple and works. Thanks for this!

**Comment by mxplusb** [comment] 2019-08-30 20:09
I just edited my `/etc/passwd` after creating a new user to be my Windows' user's home directory `/c/Users/MikeLloyd` and set `startingDirectory` to `~` in my profile.json. It works for me as expected on 18965.1005.

**Comment by nanjj** [comment] 2019-09-02 01:18
> My workaround
> 
```
"commandline" : "wsl.exe ~"
```

**Comment by matt-FFFFFF** [comment] 2019-09-03 10:55
> > My workaround
> 
> ```
> "commandline" : "wsl.exe ~"

> ```

For those specifying a distribution, use this syntax:

```
"commandline": "wsl.exe ~ -d DISTRONAME"
```

**Comment by LeoLozes** [comment] 2019-10-29 09:25
What if I want to set the default directory to a directory in C:?
I tried `"commandline" : "wsl.exe /mnt/c/Programming -d Ubuntu-18.04"` and other directories, with or without `/mnt/c/`, with or without singlequotes and no luck.

**Comment by Herohtar** [comment] 2019-11-03 00:59
@LeoLozes The second post in this thread shows how to do exactly what you want.

**Comment by anikishov** [comment] 2019-11-14 22:03
in my case, it works this way
`"startingDirectory": "//wsl$/Ubuntu-18.04/home/username"`

**Comment by pluma** [comment] 2019-12-13 16:05
Both the `wsl.exe ~ -d <distro>` and `//wsl$/home/<username>` workarounds worked for me, but it would be nice if the `startingDirectory` were interpreted by WSL rather than Windows. E.g. `"startingDirectory": "$HOME/projects"` should just work.

**Comment by mr-cn** [comment] 2020-01-24 10:37
It will be nice if Windows Terminal could convert the path. I followed #1060 expecting to start my wsl quickly, but it doesn't work, because Windows Explorer always pass the original path to Terminal.

**Comment by mattdamon108** [comment] 2020-01-25 10:44
I fix this issue with

`"startingDirectory": "//wsl$/Ubuntu-18.04/home/myname"`

in `Microsoft Windows [Version 10.0.18363.592]`, ver 0.8.100910.0

**Comment by casperx** [comment] 2020-02-26 18:34
> My workaround
> 
> ```
> "commandline" : "wsl.exe ~  -d WLinux"
> ```

Can anyone explained me how it works? I couldn't figure out how "~" can work in these command. I know that ~ is home directory shorthand but when i tried `wsl.exe -- ~`. It didn't work.

**Comment by xianleon** [comment] 2020-03-02 02:56
My way to always start WSL on $HOME:
    Create the link of wt.exe, 
    C:\Users\YOURNAME\AppData\Local\Microsoft\WindowsApps\wt.exe wsl.exe ~ -d Ubuntu
and just pin it on my start menu, and keep "startingDirectory" in profile as null

If you don't pass the "starting directory" to "wsl.exe", it will always start from your current directory.

**Comment by baoanhng** [comment] 2020-03-03 05:38
My solution is to create a new profile with starting command line `wsl.exe ~`.

```
{
            "acrylicOpacity" : 1,
            "closeOnExit" : true,
            "colorScheme" : "Campbell",
            "commandline" : "wsl.exe ~",
            "cursorColor" : "#FFFFFF",
            "cursorShape" : "bar",
            "fontFace" : "Consolas",
            "fontSize" : 12,
            "guid" : "{*********************************}",
            "historySize" : 9001,
            "icon" : "ms-appx:///ProfileIcons/{0caa0dad-35be-5f56-a8ff-afceeeaa6101}.png",
            "name" : "Ubuntu home",
            "padding" : "0, 0, 0, 0",
            "snapOnInput" : true,
            "startingDirectory" : "%USERPROFILE%",
            "useAcrylic" : true
},
```

**Comment by troy-mac** [comment] 2020-03-17 20:18
Easy fix
"startingDirectory": "//wsl$/Ubuntu/home/<YOUR USERNAME>",

**Comment by antoineco** [comment] 2020-03-17 21:32
@troy-mac that will literally start in the "home" directory, not _your_ home directory. Please see above answers for countless working solutions.

**Comment by andrewunifei** [comment] 2020-03-17 22:07
Where profiles.json file is located?

**Comment by Acris** [comment] 2020-03-18 07:52
I use Ubuntu and my workaround is:
`"commandline" : "wsl.exe ~  -d WLinux"`

**Comment by mhtvsSFrpHdE** [comment] 2020-04-05 03:31
> 
> 
> Easy fix
> "startingDirectory": "//wsl$/Ubuntu/home/",

I don't even know why they give 👎🏻

**Comment by troy-mac** [comment] 2020-04-05 04:13
Thanks I figured it out... next thing that needs resolving is the /etc/resolv.conf file getting overwritten. Tried a few work arounds non work

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by leemun1** [comment] 2020-04-09 16:18
How do I start WSL at a specific directory?

For instance, If I want to start at `~/dev` what do I write in the `commandline` property?

I tried `"commandline": "wsl.exe ~/dev"`, but got an error like below:

```
/bin/bash: /home/myname/Dev: Is a directory

[process exited with code 126]
```

**Comment by tegvr** [comment] 2020-04-17 10:03
> in my case, it works this way
> `"startingDirectory": "//wsl$/Ubuntu-18.04/home/username"`

**Comment by codinronan** [comment] 2020-04-26 04:59
With the latest release a couple of days ago (profile.json renamed to settings.json), `startingDirectory` now doesn't work at all. Not one single variation in this thread works at all for me, is anyone else seeing the same?

**Comment by max-arias** [comment] 2020-04-30 13:12
Setting `startingDirectory` worked for me, but it seems that you have to place it in the profile you're using. So for example, Ubuntu:

```
            {
                "guid": "{2c4de342-38b7-51cf-b940-2309a097f518}",
                "hidden": false,
                "name": "Ubuntu",
                "source": "Windows.Terminal.Wsl",
		"startingDirectory":"//wsl$/Ubuntu/home/me/dev"
            },
```

**Comment by saadanerdetbare** [comment] 2020-05-01 19:05
I have 4 wsl distros installed, Ubuntu, Debian, Kali-Linux and CentOS. When I use the setting `"startingDirectory": "\\\\wsl$\\<distroname>\\home\\jakob"` For the most part Debian respect the starting directory but not always, the others do not. However, when I open a second tab with one the other 3 distos they always open in ~ It seems that using `"startingDirectory": "//wsl$//<distroname>/home/jakob"` makes no difference but using `\\` is more reliable

**Comment by blacklightpy** [comment] 2020-05-15 09:07
> > Easy fix
> > "startingDirectory": "//wsl$/Ubuntu/home/",
> 
> I don't even know why they give 👎🏻

It should be /home/username not /home

**Comment by antoineco** [comment] 2020-05-15 10:30
Just to repeat something that was [already said](https://github.com/microsoft/terminal/issues/592#issuecomment-565498910), this is how you set your starting directory for a given WSL instance:
```jsonc
    "profiles": [
        {
            "guid": "{2c4de342-38b7-51cf-b940-2309a097f518}",
            "hidden": false,
            "name": "Ubuntu",
            "source": "Windows.Terminal.Wsl",
            "fontFace": "Cascadia Code",
            "fontSize": 12,

            // THIS                 vvvvvvvvvvvv
            "commandline": "wsl.exe ~ -d Ubuntu"
        }
    ],
```

Replace "Ubuntu" with the name of your distro.

**Comment by blacklightpy** [comment] 2020-05-15 13:03
> I have 4 wsl distros installed, Ubuntu, Debian, Kali-Linux and CentOS. When I use the setting `"startingDirectory": "\\\\wsl$\\<distroname>\\home\\jakob"` For the most part Debian respect the starting directory but not always, the others do not. However, when I open a second tab with one the other 3 distos they always open in ~ It seems that using `"startingDirectory": "//wsl$//<distroname>/home/jakob"` makes no difference but using `\\` is more reliable
> 
> Edit: I am running Insider preview build 19619 and wsl2. It seems that when the VMs is up and running they respect the startingDirectory setting. If the VMs are stopped and has to start when opening a tab they do not.

This is because //wsl$/ folder is not initialized until a wsl instance is started. So the first instance wont start in ~, but the others will start in ~ because the first instance initialized the //wsl$/ folder

**Comment by troy-mac** [comment] 2020-05-15 14:01
> @troy-mac that will literally start in the "home" directory, not _your_ home directory. Please see above answers for countless working solutions ([example](https://github.com/microsoft/terminal/issues/592#issuecomment-565498910))

@antoineco I am using Ubuntu (not sure if that matters) but It does put me in _my_ home directory /home/troymac so for me I get the results I was looking for...

**Comment by antoineco** [comment] 2020-05-15 14:10
@troy-mac I just tried on Ubuntu, and it doesn't. You probably have another directive, either in your settings file, or your bashrc file, but this alone does _not_ put you in your home directory.

Anyway, my main point was that we should keep this thread free of erroneous information. A working solution was proposed, let's encourage users to use that instead of sharing inaccurate alternative tricks.

**Comment by sanyer** [comment] 2020-07-16 10:26
For me (perhaps because of zsh), [workaround ](https://github.com/microsoft/terminal/issues/592#issuecomment-504947429)`"commandline": "wsl.exe /mnt/d/workspace -d Debian"` doesn't work:
```
zsh:1: permission denied: /mnt/d/workspace

[process exited with code 126]
```

but `"startingDirectory": "D:/workspace"` without any `"commandline"` works just fine, as was [suggested ](https://github.com/microsoft/terminal/issues/592#issuecomment-490610943)in the very beginning.

**Comment by DHowett** [comment] 2020-07-16 17:32
There no world in which specifying the directory by doing `wsl /directory` will work. That will _always_ (not just when using zsh!) result in the shell attempting to _execute the directory_ and then exit. That's never what you want.

**Comment by maximgeerinck** [comment] 2020-09-08 10:45
any update on this?

**Comment by zadjii-msft** [comment] 2020-09-08 13:08
@maximgeerinck Nope. We'll make sure to update this thread when there is. In the meantime, might I recommend the Subscribe button?
![image](https://user-images.githubusercontent.com/18356694/91237459-5cbb0c80-e700-11ea-9347-b9b1ec2813b1.png)
That way you'll be notified of any updates to this thread, without needlessly pinging everyone on this thread ☺️

**Comment by troy-mac** [comment] 2020-10-02 16:40
Hi all I know I got a few thumbs down for this suggestion that I posted earlier, but I just installed WSL and Ubuntu-20.04 on a new system and all I did was add the below lines to my settings.json file and it 100% worked for dropping me into my home directory.  I am not saying it will work for everyone as I am not sure the thumbs down users actually tested this or not, but it has worked for me on 2 different systems both with Ubuntu-20.04 and 18.04. I think it is the easiest thing to try first and if it does not work for you then try a couple other suggestions on this thread.  

"startingDirectory": "//wsl$/Ubuntu-20.04/home/troy-mac"
"startingDirectory": "//wsl$/Ubuntu-18.04/home/troy-mac"

**Comment by antoineco** [comment] 2020-10-02 17:15
@troy-mac I'm speaking for myself here, but the thumb down was a way to say _"Warning, reader. The solution suggested in this message doesn't work for everyone, please refer to the accepted solution instead"_. It wasn't an attempt to dismiss you. 

Like you said, `"commandline": "wsl.exe ~ -d <distro_name>"` (https://github.com/microsoft/terminal/issues/592#issuecomment-504947429) works in pretty much any case, so let's make sure this solution is visible to people who go through this issue, instead of trying to come up with new, approximate solutions.

**Comment by mslot** [comment] 2020-10-13 07:41
When installing Ubuntu, can use

`"startingDirectory":"\\\\wsl$\\[DISTRONAME]\\home\\[USERNAME]"`

If not certain what is, do:
1. Win+R
2. \\\\wsl$
3. Hit enter

Now you will get the fileshare in an explorer. 

Simply follow the path to where you want to start from when opening a new tab in Windows Terminal. Remember:
1. four back slashes at the start and
2. two back slashes in between the folder names

when construcing the `startingDirectory`. Restart Windows Terminal, and you are good to go.

**Comment by Ratismal** [comment] 2021-01-21 20:08
I feel like I must be missing something obvious here. Everything I've read in this issue indicates that if you set your startingDirectory to `//wsl$/ubuntu/whatever/path/you/want`, it will start in that directory. But that's not the case for me? No matter what I set startingDirectory, it always _always_ takes me to my home directory. This is not what I want.

I've tried making new profiles, and I've tried updating the existing ubuntu profile. I've tried forward slashes, back slashes, `~`, everything has the same result. See:
![image](https://user-images.githubusercontent.com/1059362/105406381-9594da00-5be9-11eb-9948-0bec6e2bcd1a.png)

Is it intentional that you're essentially locked into starting at the home directory, or am I missing something?

**Comment by zadjii-msft** [comment] 2021-01-21 20:21
You might _need_ to use backslashes (instead of forward slashes), because it definitely works:

![image](https://user-images.githubusercontent.com/18356694/105407821-caa62a00-5bf3-11eb-9557-eac9ae509918.png)


Is there anything else in your `.bashrc` that might be changing directories?

**Comment by mariusstrom** [comment] 2021-01-21 20:47
> I feel like I must be missing something obvious here. Everything I've read in this issue indicates that if you set your startingDirectory to `//wsl$/ubuntu/whatever/path/you/want`, it will start in that directory. But that's not the case for me? No matter what I set startingDirectory, it always _always_ takes me to my home directory. This is not what I want.

@Ratismal 
What's the output of `wsl.exe -l`? Make sure the `startingDirectory` path matches the name of the WSL distro from `wsl.exe -l` exactly. If case sensitivity is required there, I'm guessing yours should be Ubuntu, and not ubuntu. Some distros include the LTS version in the distro name (like you can see in @zadjii-msft's post above with Ubuntu-18.04).

```json
"startingDirectory": "//wsl$/Ubuntu/home/cat/proj"
```

I think it's case-sensitive to the distro name.

**Comment by mariusstrom** [comment] 2021-01-21 20:48
@zadjii-msft forward slashes unescaped work for me:

![image](https://user-images.githubusercontent.com/22438813/105410546-ee16a800-5be6-11eb-9519-d00651f1242b.png)

**Comment by Ratismal** [comment] 2021-01-22 00:47
@mariusstrom 
> What's the output of `wsl.exe -l`? Make sure the `startingDirectory` path matches the name of the WSL distro from `wsl.exe -l` exactly. If case sensitivity is required there, I'm guessing yours should be Ubuntu, and not ubuntu.

You were exactly right, thank you! I think there might be a bug somewhere in there, though? Did some experimenting.
- `//wsl$/ubuntu/path/that/does/exist` - brings me to my home directory
- `//wsl$/ubuntu/path/that/doesnt/exist` - brings me to my home directory in the C: drive
- `//wsl$/Ubuntu/path/that/does/exist` - brings me to that directory
- `//wsl$/Ubuntu/path/that/doesnt/exist` - brings me to my home directory in the C: drive

I would expect that case sensitivity would cause `/ubuntu/` to always bring me back to the home directory, since its an invalid path. But that doesn't seem to be the case. Is that... intended behaviour?

**Comment by zadjii-msft** [comment] 2021-01-22 11:34
Frankly, I have no idea how the WSL filesystem driver works. The best place to ask would be over at https://github.com/microsoft/WSL

**Comment by stephenmartindale** [comment] 2021-02-05 16:40
> My workaround
> 
> ```
> "commandline" : "wsl.exe ~  -d WLinux"
> ```

This seems to be the commonly accepted solution but it has one fatal flaw: if you use `wsl.exe ~` as the `commandline`, then the `--startingDirectory` (or `-d`) parameter to `wt.exe` ceases to function, properly.

I use the Windows Subsystem for Linux for spinning up sand-boxes for developer experiments, using `wsl.exe --export` and `--import` to load up and pack away these sand-boxes as required. At any given time, my default WSL distribution is the one that contains the tool-chain that I'm currently using for my work. For this reason, I've created a WT profile that always spawns whatever the default WSL distribution happens to be:

```
            {
                "guid": "{75155ba1-aebb-4196-af68-117807257cff}",
                "commandline": "%systemroot%\\System32\\wsl.exe",
                "name": "Windows Subsystem for Linux",
                "icon": "ms-appx:///ProfileIcons/{9acb9455-ca41-5af7-950f-6bca1bc9722f}.png",
            },
```

This works great because I can use commands like `wt.exe --profile "{75155ba1-aebb-4196-af68-117807257cff}" --startingDirectory "D:\Project1"`. However, as soon as I append ` ~`, then `~` overrides any and all paths passed to `wt` via the `--startingDirectory` command-line parameter.

**Comment by dark-swordsman** [comment] 2021-04-19 23:10
Using the new UNC path as suggested by caksoylar worked great for me, but just a note to others that, for example, if you have "Ubuntu", it may not just be "Ubuntu". Mine was actually `Ubuntu-20.04`.

I was able to confirm this by opening up VSCode and using "reveal in explorer" on a file, to which it then opened `\\wsl$\Ubuntu-20.04\...`. 

You can also just do `\\wsl$` in the address bar and see it there, I had just forgotten that Windows paths use `\`, not `/`, lol.
![image](https://user-images.githubusercontent.com/7909209/115314315-2b30fe80-a132-11eb-8091-2c3daabcd801.png)

**Comment by saadanerdetbare** [comment] 2021-05-28 17:01
This works for me: cd into the directory where I want to start and type `wslpath -w .`
Example output: `\\wsl.localhost\Ubuntu-20.04\home\bob`
Put that in the `"startingDirectory":` and escape any `\` with another `\`

**Comment by ednl** [comment] 2021-07-19 09:39
> This is because //wsl$/ folder is not initialized until a wsl instance is started. So the first instance wont start in ~, but the others will start in ~ because the first instance initialized the //wsl$/ folder

Is this still true?? I seems to be, it is for me. So is there no way to *always* (even the first time) start up a WSL instance in the Linux home directory? That seems really strange, especially in WSL2 where the division between file systems is greater because of performance differences.

**Closed** 2021-08-02 20:39 UTC
Labels: Area-Settings, Area-TerminalControl, Help Wanted, In-PR, Issue-Feature, Product-Terminal

**Comment by Seefer** [comment] 2021-09-17 23:59
> one easy hack would be inside `~/.bashrc` file of wsl, add the line
> `cd ~`
> 
> Problem solved.

I've recently discovered that having `cd ~` in the `.bashrc` or `.zshrc` file of a Linux distro, it breaks VS Code's integrated terminal behaviour. With `cd ~ ` in one of these shell script files, if you are in a project folder in VS Code and open the terminal, the terminal directory does not point to the project directory. It always opens at `~` .

Is there some other way via WSL to specify the working directory for the distro instead of it always pointing at `/mnt/c/Users/<username>`?
