### ISSUE TITLE
Resizing window with mouse does weird things to text

### ISSUE THREAD

**Issue by hfqq** [microsoft/terminal#1641] opened 2019-06-26 15:12 UTC
# Environment
Microsoft Windows [version 10.0.18362.175] 

Terminal Version：0.2.17150

```none
Windows build number: [run "ver" at a command prompt]
Windows Terminal version (if applicable):

Any other software?
```

# Steps to reproduce

# Expected behavior

# Actual behavior

After the cmd window is dragged to change the size, some of the text positions inside can be restored without being restored, such as the SET command.

**Comment by hfqq** [comment] 2019-06-26 15:13
![图片](https://user-images.githubusercontent.com/13845212/60192151-ffab9880-9867-11e9-91e0-185f1e99607c.png)

**Comment by adiviness** [comment] 2019-06-26 17:53
In the future we would prefer a more descriptive title for the bug report, it makes it easier for everyone to find and track. I've updated this one for now, as best I understand the bug.

**Comment by Shorotshishir** [comment] 2019-06-27 00:17
Duplicate of #1465

**Comment by DHowett-MSFT** [comment] 2019-06-27 00:40
Yep! Thanks!

**Closed by DHowett-MSFT** 2019-06-27 00:40 UTC
Labels: Needs-Tag-Fix, Needs-Triage
