### ISSUE TITLE
Arrows don't have consistent width

### ISSUE THREAD

**Issue by phuclv90** [microsoft/terminal#714] opened 2019-05-12 08:31 UTC
* **Your Windows build number:** (Type `ver` at a Windows Command Prompt): Microsoft Windows [Version 10.0.18894.1000]
* **What you're doing and what's happening: (Copy & paste specific commands and their output, or include screen shots):** Arrows in the [arrow unicode block](https://en.wikipedia.org/wiki/Arrows_(Unicode_block)) have different widths and sizes. Some take twice the width and  some appear bigger than the others

    I checked with the command `for ($i = 0x2190; $i -le 0x21F0; $i += 16) { for ($j = 0; $j -lt 16; $j++) { Write-Host -NoNewline $([char]($i + $j)); }; echo "" }` and here's the output

    ![image](https://user-images.githubusercontent.com/9285512/57579664-8f200680-74c9-11e9-869c-24051fe708a9.png)

    As you can see, some vertical arrows take 2 cells and some horizontal arrows lie in a single cell width. That breaks the table layout like this

    ![wttr in](https://user-images.githubusercontent.com/9285512/57579534-86c6cc00-74c7-11e9-97be-e12bd1913885.png)

* **What's wrong / what should be happening instead:** They should have at least the same point size and width. I think all of them should be in a square (i.e. double width)

FWIW here's the above wttr.in output on Linux

![image](https://user-images.githubusercontent.com/9285512/57579713-2a18e080-74ca-11e9-8767-19c6af6a105f.png)

**Comment by oising** [comment] 2019-05-12 18:06
@miniksa font fallback issue?

**Comment by zadjii-msft** [comment] 2019-05-13 13:57
Probably a dupe of #455

**Comment by DHowett-MSFT** [comment] 2020-02-20 20:14
I think this was actually fixed by #2928.

![image](https://user-images.githubusercontent.com/14316954/74974701-94a46880-53da-11ea-8cfb-5cca2a850120.png)

![image](https://user-images.githubusercontent.com/14316954/74974716-9a9a4980-53da-11ea-9c05-d516532978a3.png)

**Closed by DHowett-MSFT** 2020-02-20 20:14 UTC
Labels: Area-Rendering, Issue-Bug, Priority-2, Product-Terminal, v1-Scrubbed
