### ISSUE TITLE
Convert line breaks when pasting

### ISSUE THREAD

**Issue by sinnlosername** [microsoft/terminal#1195] opened 2019-06-10 17:19 UTC
# Environment

```none
Windows build number: 10.0.18362.145
Windows Terminal version (if applicable): Not sure where to find, it's compiled from the master branch with the commit 2da5b0b
```

# Steps to reproduce
Copy texts with different line endings into wsl opened in windows terminal

# Expected behavior
Line endings should be converted to the correct ones for the given environment (LF for Linux subsystem, CRLF for cmd/powershell)

# Actual behavior
Different based on what line endings the copied text contains.

Here are images of all possible scenarios pasted into WSL in Terminal: https://imgur.com/a/HYFrznJ

**Comment by DHowett-MSFT** [comment] 2019-06-10 17:54
This is a duplicate of #1073 #1091.

**Closed by DHowett-MSFT** 2019-06-10 17:54 UTC
Labels: Needs-Tag-Fix, Needs-Triage
