### ISSUE TITLE
Application terminates when windows store wants to update it

### ISSUE THREAD

**Issue by aaroneg** [microsoft/terminal#9152] opened 2021-02-13 20:25 UTC
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.19042.804]
Windows Terminal version (if applicable):

Any other software?
```

# Steps to reproduce

Leave the app running a process overnight when an update is available

# Expected behavior

The application does not terminate to update, and only updates when the user closes the app.

# Actual behavior

The application seems to have terminated overnight to run an update.

**Comment by RowdyChildren** [comment] 2021-02-13 20:26
+1 I am also seeing this issue.

**Comment by j4james** [comment] 2021-02-13 20:31
See issue #3915.

**Comment by DHowett** [comment] 2021-02-13 21:08
Alas, this is a /duplicate of #3915.

**Closed by DHowett** 2021-02-13 21:08 UTC
Labels: Needs-Tag-Fix, Needs-Triage

**Comment by tovine** [comment] 2023-04-04 08:08
@MSFT: I'm commenting on this one because my own issue (the one that this is marked as a duplicate of) was limited to collaborators because it was "being too heated".

Any updates on roadmaps or ideas to fix this? I've disabled auto updates, but it seems to somehow have been enabled again without my consent - I just came back to the office to see all my WSL sessions terminated because WSL had been updated via the Store...
In my opinion: until this issue is resolved, the Microsoft Store really isn't suitable to distribute productivity applications like WSL or the Terminal. Can you give us some insight into what you're planning to do about this, or if you just recommend us installing the Terminal and WSL outside the Store instead (potentially losing the easy access to updates altogether)?

**Comment by zadjii-msft** [comment] 2023-04-04 14:51
I can't officially share any updates, but we're in touch with folks from the Store team and the App Catalog team, and we're working on a solution. We'll make sure to update that thread when there's something to share. Since this requires OS-side work, the work moves a little slower - the solution can't just be scoped to the Terminal, it's got to be something that provides a potential solution for any app that wants it (but doesn't break apps that _don't_).

**Comment by tovine** [comment] 2023-04-04 16:40
Thanks for the quick response @zadjii-msft, good to hear that things are happening at least - that gives some hope for the future ❤️
