### ISSUE TITLE
Integrated Terminal in File Explorer

### ISSUE THREAD

**Issue by alannt777** [microsoft/terminal#8221] opened 2020-11-11 07:54 UTC
# Description of the new feature/enhancement

Integrated Terminal in Explorer that opens the same folder. Kind of like VS Code's terminal

# Proposed technical implementation details (optional)

Sync with PowerToys for https://github.com/microsoft/PowerToys/issues/2555

**Comment by zadjii-msft** [comment] 2020-11-11 08:19
Okay so for my own future reference, this is not "the explorer context menu", which is #1060, this is "I want to embed a Terminal control within explorer.exe".

Even more, this is "let's ember a Windows Terminal, terminal control within explorer.exe". That distinction is important because it wouldn't be _that hard_ to ship a control that could be embedded within explorer.exe, but it'd definitely be trickier to hook up the Terminal keybindings, settings, etc. to it. Especially considering most of the keybindings, actions, wouldn't apply to just one single control instance.   In general, that part is being tracked by #4572

There's an almost exact dupe of this request in #5591, so I'm gonna close this one in favor of the older one. /dup #5591

There's some other thread about re-parenting HWNDs floating around somewhere - IIRC in that thread, Dustin embedded gvim inside of notepad or something crazy like that. That's certainly simpler than rolling our won control, but definitely hackier.

**Comment by alannt777** [comment] 2020-11-11 08:20
Oops

**Closed by zadjii-msft** 2020-11-11 08:19 UTC
Labels: Issue-Feature, Needs-Tag-Fix, Needs-Triage
