### ISSUE TITLE
Opening new PS tab using the Plus button freezes the app

### ISSUE THREAD

**Issue by cl-ement05** [microsoft/terminal#9391] opened 2021-03-05 14:26 UTC
# Environment

```none
Windows build number: Microsoft Windows NT 10.0.19042.0
Windows Terminal version : 1.7.572.0 (Beta preview)
```

# Steps to reproduce
1. Have PowerShell set as your default profile
2. Start the app and check you only have one PowerShell tab open
3. Click on the "+" button to open a new tab in your default profile
4. And the app not responds from now

# Expected behavior
A PS tab opening normally

# Actual behavior
App freezes for a few seconds and it automatically quits
Moreover, PS prompt does not show up
![image](https://user-images.githubusercontent.com/64481347/110128556-353baf80-7dc7-11eb-8a18-9b3ea4ffcf55.png)

# Enabled customizations
![image](https://user-images.githubusercontent.com/64481347/110155547-0d0f7900-7de6-11eb-8d51-174f4224b23c.png)
![image](https://user-images.githubusercontent.com/64481347/110155640-2dd7ce80-7de6-11eb-8999-a916081b98c0.png)

**Comment by WSLUser** [comment] 2021-03-05 16:40
Unable to reproduce under same versions for OS and Windows Terminal. Try restarting your computer or checking Task Manager to see what resource usage is there including for Powershell and Terminal. Also check your profile settings. Is there anything there besides the defaults? If there is customizations to the profile, was it configured with the Settings UI or the settings.json?

**Comment by cl-ement05** [comment] 2021-03-05 18:08
Sorry, I just updated my issue

**Comment by skyline75489** [comment] 2021-03-05 23:11
"App freezes for a few seconds and it automatically quits" this sounds a lot like the app crashes.

God I wish the bot listen to me. Can you try the steps in https://github.com/microsoft/terminal/issues/8287#issuecomment-733893742 ?

**Comment by cl-ement05** [comment] 2021-03-06 13:19
My Windows Feedback is here : https://aka.ms/AAbfjxq

**Comment by cl-ement05** [comment] 2021-03-06 13:20
> 
> 
> "App freezes for a few seconds and it automatically quits" this sounds a lot like the app crashes.
> 
> God I wish the bot listen to me. Can you try the steps in [#8287 (comment)](https://github.com/microsoft/terminal/issues/8287#issuecomment-733893742) ?

yeah clearly this is a crash

**Comment by zadjii-msft** [comment] 2021-03-08 12:04
@DHowett I'm assigning you because I can't open feedback hub links anymore 😕

**Comment by zadjii-msft** [comment] 2021-03-26 17:25
Okay I finally got access again. Feedbacks f583dce3-8df8-4cf4-992f-583b0f588591 and fa4c67a1-8881-4238-bc85-e7ac9d6a5230. Unfortunately those are bucketing to some garbage `utc_feedbacc_diagtrack.dll` bucket that doesn't have relevant stack info. I did manage to find:

```
 "lineNumber": "430",
 "fileName": "E:\\BA\\1\\s\\src\\cascadia\\TerminalSettingsModel\\CascadiaSettingsSerialization.cpp",
 "hresult": "2147942402",
 "message": "Dynamic Profile Namespace: \"Windows.Terminal.Wsl\" -- E:\\BA\\1\\s\\src\\cascadia\\TerminalSettingsModel\\WslDistroGenerator.cpp(66)\\Microsoft.Terminal.Settings.Model.dll!00007FFD8C3E9960: (caller: 00007FFD8C3D03B1) Exception(1) tid(3364) 80070002 The system cannot find the file specified.\r\n",
 "module": "Microsoft.Terminal.Settings.Model.dll"
```

it's `ERROR_FILE_NOT_FOUND`'ing... `wsl.exe`? When opening a new tab? That doesn't make any sense. Maybe those logs are just the expected "couldn't load WSL, whatever, log it and move on" messages.

@cl-ement05 Could you share your whole `settings.json`? Do you have WSL installed? Or maybe any other PowerShell Core instances?


But then there's also a `ERROR_BAD_FORMAT` but there's no other context on that other than `Terminal.Settings.Model.dll`. Maybe there's a x64 powershell installed on a `x86` machine? The first tab loads fine, so that's probably not it.

**Comment by cl-ement05** [comment] 2021-03-26 17:41
> 
> @cl-ement05 Could you share your whole `settings.json`? 
>
Yes of course so here is my entire settings.json (I just removed the color schemes otherwise this file is 190 lines long) :
```
{
    "$schema": "https://aka.ms/terminal-profiles-schema",
    // Add custom actions and keybindings to this array.
    // To unbind a key combination from your defaults.json, set the command to "unbound".
    // To learn more about actions and keybindings, visit https://aka.ms/terminal-keybindings
    "actions": 
    [
        // Copy and paste are bound to Ctrl+Shift+C and Ctrl+Shift+V in your defaults.json.
        // These two lines additionally bind them to Ctrl+C and Ctrl+V.
        // To learn more about selection, visit https://aka.ms/terminal-selection
        {
            "command": 
            {
                "action": "copy",
                "singleLine": false
            },
            "keys": "ctrl+c"
        },
        {
            "command": "paste",
            "keys": "ctrl+v"
        },
        // Press Ctrl+Shift+F to open the search box
        {
            "command": "find",
            "keys": "ctrl+shift+f"
        },
        {
            "command": "exit",
            "keys": "ctrl+d"
        },
        // Press Alt+Shift+D to open a new pane.
        // - "split": "auto" makes this pane open in the direction that provides the most surface area.
        // - "splitMode": "duplicate" makes the new pane use the focused pane's profile.
        // To learn more about panes, visit https://aka.ms/terminal-panes
        {
            "command": 
            {
                "action": "splitPane",
                "split": "auto",
                "splitMode": "duplicate"
            },
            "keys": "alt+shift+d"
        }
    ],
    "copyFormatting": "none",
    "copyOnSelect": false,
    "defaultProfile": "{574e775e-4f2a-5b96-ac1e-a2962a402336}",
    "profiles": 
    {
        "defaults": 
        {
            "acrylicOpacity": 0.6,
            "cursorShape": "underscore",
            "useAcrylic": true
        },
        "list": 
        [
            {
                "commandline": "powershell.exe",
                "guid": "{61c54bbd-c2c6-5271-96e7-009a87ff44bf}",
                "hidden": true,
                "name": "Windows PowerShell"
            },
            {
                "commandline": "cmd.exe",
                "guid": "{0caa0dad-35be-5f56-a8ff-afceeeaa6101}",
                "hidden": false,
                "name": "Command Prompt"
            },
            {
                "guid": "{b453ae62-4e3d-5e58-b989-0a998ec441b8}",
                "hidden": false,
                "name": "Azure Cloud Shell",
                "source": "Windows.Terminal.Azure"
            },
            {
                "guid": "{574e775e-4f2a-5b96-ac1e-a2962a402336}",
                "hidden": false,
                "name": "PowerShell",
                "source": "Windows.Terminal.PowershellCore"
            }
        ]
    },
    "schemes": 
    [
        {
            someColorScheme
        },
        {
            anotherColorScheme...
        }
    ],
    "tabSwitcherMode": "mru",
    "tabWidthMode": "equal",
    "theme": "system"
}
```

>
> Do you have WSL installed? Or maybe any other PowerShell Core instances?
>
Well I have installed the [WSL 2 update package](https://docs.microsoft.com/en-us/windows/wsl/install-win10#step-4---download-the-linux-kernel-update-package)
However I didn't enable neither WSL neither VM platform in Windows features (because I realized this would not be useful for me). So no WSL is not *enabled* but WSL2 pkg installed.

About PowerShell Core I don't releally understand you mean by this but I installed PS 7 (and I use it as my default profile)

**Comment by zadjii-msft** [comment] 2021-03-26 17:47
> About PowerShell Core I don't releally understand you mean by this but I installed PS 7 (and I use it as my default profile)

That's exactly what I meant. Interesting though. Does this bug repro with Windows Powershell, or PowerShell 7? Does it still repro if you remove the `"commandline": "powershell.exe",` from your Windows Powershell profile?

**Comment by cl-ement05** [comment] 2021-03-26 17:58
> 
> > About PowerShell Core I don't releally understand you mean by this but I installed PS 7 (and I use it as my default profile)
> >
> Does this bug repro with Windows Powershell, or PowerShell 7?
>
This bug happens with both Powershell and newer PowerShell 7. 

And well if I remove `"commandline": "powershell.exe",` from the Powershell profile (not the 7 one) PS simply does not start.. of course because of the missing commandline parameter. So I get an error code.

**Comment by zadjii-msft** [comment] 2021-03-26 18:41
Well, that's weird though. `defaults.json` has the full path to powershell.exe in it, so removing it from your "Windows Powershell" profile should fall back to using that one. 

What if you manually set the commandline to:

```
"commandline": "%SystemRoot%\\System32\\WindowsPowerShell\\v1.0\\powershell.exe",
```
?

Or maybe, a weird theory, what happens when you run `wsl.exe`? I know it's not actually set up, but I _think_ the exe should still be in `C:\Windows\system32`

**Comment by cl-ement05** [comment] 2021-03-26 19:37
# PowerShell
> 
> Well, that's weird though. `defaults.json` has the full path to powershell.exe in it, so removing it from your "Windows Powershell" profile should fall back to using that one.
> 
Oh I am sorry actually yes when I remove the commandline parameter, PS still starts. 

> 
> And well if I remove `"commandline": "powershell.exe",` from the Powershell profile (not the 7 one) PS simply does not start.. of course because of the missing commandline parameter. So I get an error code.
>
This was happening because I thought I had *removed* the commandline parameter by leaving the field blank in Settings. Now I truly removed it from the JSON file so yes `defaults.json` is loaded and PS prompt appears as expected.

Also, when setting commandline to `"commandline": "%SystemRoot%\\System32\\WindowsPowerShell\\v1.0\\powershell.exe",` PS successfully starts

# WSL
> 
> Or maybe, a weird theory, what happens when you run `wsl.exe`? I know it's not actually set up, but I _think_ the exe should still be in `C:\Windows\system32`
>
I didn't try to do this but you can be 100% sure it won't work since
1. No actually there is `wsl.exe` in system32. There is only a `DLL` named `wslapi`
2. wsl is not recognized by PS as command

**Comment by zadjii-msft** [comment] 2022-07-08 15:46
First off, sorry we never looped back on this one earlier.

> Also, when setting commandline to `"commandline": "%SystemRoot%\\System32\\WindowsPowerShell\\v1.0\\powershell.exe",` PS successfully starts

Well, seems to me that the issue here was that whatever `powershell.exe` that was on your path was _not actually `powershell.exe`. Whatever bad exe it was, it was getting started instead of the main system one. 

If I'm reading this whole thread right, seems like this is fixed now, so I'm gonna close this out. Thanks!

**Closed by zadjii-msft** 2022-07-08 15:46 UTC
Labels: Severity-Crash, Needs-Triage, Needs-Attention, Product-Terminal, Needs-Tag-Fix
