### ISSUE TITLE
Windows terminal WSL doesn't release bash process.

### ISSUE THREAD

**Issue by YasinLaw** [microsoft/terminal#2425] opened 2019-08-14 08:36 UTC
I opened Ubuntu window in windows terminal, task manager showed one bash process. But I after windows terminal closed, bash process never die. What matters is that how many bash process depends on how many time I opend wsl window in windows terminal, it never ends the bash processes.

**Comment by zadjii-msft** [comment] 2019-08-14 12:19
This is either a dupe of #2232 or #1603. Thanks!

**Closed by zadjii-msft** 2019-08-14 12:19 UTC
Labels: Needs-Tag-Fix, Needs-Triage
