### ISSUE TITLE
Accessibility regressions in the 21H1 inbox console

### ISSUE THREAD

**Issue by codeofdusk** [microsoft/terminal#9239] opened 2021-02-21 20:25 UTC
# Environment

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd] 19043.844
Windows Terminal version (if applicable): inbox conhost

Any other software? NVDA
```

# Steps to reproduce

1. Open inbox conhost.
2. Press NVDA+control+z to open the Python console.
3. Enter `nav.is21H1Plus`

# Expected behavior
`True` is returned, as in OpenConsole commit 12b12d5b078bb1ff2e7b3a1fd190cad889ef4225.

# Actual behavior
`False` is returned, as in 20H2 inbox, indicating a regression from #4495.

# Additional context
For testing, I've replaced conhost with OpenConsole on my system, but reverted to inbox before applying the 21H1 update. Perhaps Windows Update didn't install the new inbox conhost on my system?

**Comment by codeofdusk** [comment] 2021-02-21 20:26
Cc @carlos-zamora.

**Comment by DHowett** [comment] 2021-02-22 00:14
Can you check the file version (right click, properties) for conhost.exe?

I am not sure how NVDA’s `is21H1` function determines whether it is in fact 21H1... but I didn’t believe we had control over that.

Certainly we have made 0 changes to conhost in 21H1. I wasn’t even aware there _was_ a 21H1 yet publically available.

**Comment by codeofdusk** [comment] 2021-02-22 00:21
See the implementation of `is21H1Plus` [here](https://github.com/nvaccess/nvda/blob/master/source/NVDAObjects/UIA/winConsoleUIA.py#L351).

21H1 inbox on my system is acting as if #4495 was never merged (obviously false) or regressed between the above-linked commit and shipment in Windows.

**Comment by codeofdusk** [comment] 2021-02-22 00:23
Version number is 10.0.19641.746

**Comment by DHowett** [comment] 2021-02-22 00:48
That doesn’t seem right. I’ll need to check the build when I get back to the office tomorrow, but 19641 corresponds to a version of Windows from two development cycles ago, numerically, and would not contain any of our recent UIA fixes. 

Just so you know: 21H1 is a patch release from the servicing team, and they did not contact us about releasing any conhost changes. I have no reason to believe that the code in conhost 21H1 is any different from _20H1_, which was the last non-patch upgrade that brought in a whole new tree of Windows code indiscriminately.

**Comment by DHowett** [comment] 2021-02-22 00:51
The versions of Windows that take your computer down for 10-75 minutes and reboot three times tend to contain the entire development tree from the OS repository before they’re snapped. The builds that increment the UBR or patch version, or the ones that increment the main version by 1 (so, from 19041 to 19042 or 19043) are servicing updates that have hand-selected features backported into them. Since we were not hand-selected for those releases, no conhost changes are present in 20H2 or 21H1.

**Comment by DHowett** [comment] 2021-02-22 20:23
Discussed this with @codeofdusk off GitHub. The changes we were targeting for "21H1" did not get selected for the build that was released in the early half of 2021. We'll regroup here, but there's no _regression_ per se. Just a lack of ... progression? I guess?

**Closed by DHowett** 2021-02-22 20:23 UTC
Labels: Needs-Tag-Fix, Needs-Triage
