### ISSUE TITLE
Launch from context menu

### ISSUE THREAD

**Issue by Wagnerp** [microsoft/terminal#2776] opened 2019-09-16 18:36 UTC
I don't know if this can be done already, but can we have an option to launch the terminal as an normal/elevated user from the context menu in explorer, similar to what you can already do with CMD/Powershell?

**Comment by zadjii-msft** [comment] 2019-09-16 19:40
Please search before filing new issues. This is a duplicate of a ton of issues that were _already_ closed as duplicates of the following:

/dupe #1060

**Closed** 2019-09-16 19:40 UTC
Labels: Issue-Feature, Needs-Tag-Fix, Needs-Triage

**Comment by Wagnerp** [comment] 2019-09-17 06:15
Hi @zadjii-msft 

Thanks, will post ideas about this particular issue on the referenced thread.
