### ISSUE TITLE
WindowsConsoleHost doesn't delete completely

### ISSUE THREAD

**Issue by SJang1** [microsoft/terminal#1200] opened 2019-06-11 12:59 UTC
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18912.1001]
Windows Terminal version (if applicable): If I remember correctly, all commits, even now(commit b9d83ba)
```

# Steps to reproduce

Remove Windows Console (Preview) at Settings app

# Expected behavior

All files and folders delete correctly.

# Actual behavior

Microsoft.WindowsConsoleHost\RoamingState folder still stays in Apps package folder like this
`C:\Users\UserName\AppData\Local\Packages\Microsoft.WindowsConsoleHost_8wekyb3d8bbwe` and cannot deploy again (new version) with Visual Studio error code `0x80073D05` before deleting this folder manually. It was able to delete folder with IObit unlocker, or like those programs. Getting permmision error when deleting using delete button of explorer.

BTW when deleting Windows Terminal, Terminal app is removed correctly.

**Comment by zadjii-msft** [comment] 2019-06-11 13:16
I've had VS sometime struggle with re-deploying packages - usually just hitting deploy again fixes them though.

**Comment by SJang1** [comment] 2019-06-11 13:25
This problem I am saying about is not a VS problem, ConsoleHost folder doesn't delete and manually deleting is required for now (at least for me). I had tried deploying again, having error of 0x80073D05 for ConsoleHost and have to manually delete WindowsConsoleHost folder in Packages folder to do anything with ConsoleHost when I delete from Settings app.

**Comment by zadjii-msft** [comment] 2019-06-11 14:17
Is there any chance you still had a conhost window from the ConsoleHost app that was still running on your machine?

**Comment by SJang1** [comment] 2019-06-11 22:02
Windows console app shuts down when deleting console at settings. So that I think there is no chance something is running as ConsoleHost.

**Comment by DHowett-MSFT** [comment] 2019-06-13 21:40
Have you been able to delete this directory? None of us have any idea how to fix this, otherwise. Just to make sure, you're:

1. "uninstalling" the package from the start menu or the Apps/Features control panel
2. trying to delete the directory?

**Comment by SJang1** [comment] 2019-06-14 04:10
It was not from control panel, it was from apps menu at Settings app. I haven't tried at control panel yet, try it later.
After that uninstalling process is done, WindowsConsoleHost directory is still there with RoamingState folder inside, found out that I can't access to RoamingState folder, and can't delete RoamingState folder. Used IOBit unlocker to delete the WindowsConsoleHost directory, it said explorer.exe is in used, and I could unlock and delete the directory.

**Comment by DHowett-MSFT** [comment] 2019-06-18 21:48
So it looks like you got it deleted by using IOBit unlocker. Fascinating! Unfortunately, since it looks like Explorer was taking the lock, that's .. not exactly within our control. I'll close this issue here, but please feel free to file feedback that explorer is being too aggressive with file locking.

**Closed by DHowett-MSFT** 2019-06-18 21:48 UTC
Labels: Area-Build, Issue-Bug, Needs-Attention, Product-Conhost

**Comment by irafaz** [comment] 2020-03-19 12:14
I think I'm having a similar issue (at least I've got the same error code).

I can't install/update Terminal, since every single way of installing Terminal (Store, .MSIX, Choco, Powershell etc.) gives me error code 0x80073D05.

A couple of times, I'm able to see the installed files in the WindowsApps-folder and the start menu, but I'm unable to start the program, and the Store still say it couldn't install Terminal.

I think I have some leftover files from an earlier installation of Terminal that hinders me from installing Terminal "again". But I have no idea how to find those files and delete them.

Can I reproduce the problem and give you a log somehow? Maybe you can find where the installation halts?

Opening Terminal by unzipping the .MSIX works flawlessly, but I want the "Store"-version with automatic updates etc.
