### ISSUE TITLE
Environment given to profiles?

### ISSUE THREAD

**Issue by vefatica** [microsoft/terminal#7465] opened 2020-08-29 22:22 UTC
Terminal's TEMP environment variable has the value z:\.  That's the same for Explorer.exe and shells running in consoles.  And that's as desired.

For any (Windows) shell running in Terminal, TEMP=C:\Users\vefatica\AppData\Local\Temp.

How and why?

If this is a duplicate, please give a brief lesson in searching issues.

**Comment by DHowett** [comment] 2020-08-30 01:49
Please do not delete the bug template.

We made a change in #7243 to make sure clients of Terminal always received the newest possible environment variables available for your user. That practically means that it inherits directly from the same source as Explorer.

How are you setting `TEMP` such that it is not available to the user’s environment block?

**Comment by vefatica** [comment] 2020-08-30 02:16
I'm not sure what you mean ... "bug template".  I have been opening blank issues.  Should I open a bug report (and leave the canned stuff there) even if I'm only curious?

My login script sets TEMP and TMP in explorer.exe and two other apps from which I launch almost everything.  I do that with my own app which uses CreateRemoteThread after injecting some code and data.  I could make the change in HKCU\Envoronment and broadcast WM_SETTINGSCHANGE but I'm not sure who's listening.  Does explorer.exe honor that message by updating its environment?

**Comment by vefatica** [comment] 2020-08-31 17:25
Yes, explorer.exe responds to WM_SETTINGSCHANGE (lParam = "Environment") by updating its environment.

**Comment by DHowett** [comment] 2020-09-02 23:15
(Gonna close this one by design. The reason I asked about the bug template -- which you don't have to use (!) -- is because sometimes the behaviors folks are asking about were changed and we like to know what version they're using. it helps us tailor the answer to the question more appropriately.)

**Closed by DHowett** 2020-09-02 23:15 UTC
Labels: Needs-Attention, Needs-Tag-Fix, Needs-Triage

**Comment by vefatica** [comment] 2020-09-10 17:09
Just curious ... does WT create that fresh environment with its bare hands (read all the registry environment keys) or are there API functions to do it ?

**Comment by DHowett** [comment] 2020-09-10 17:29
It depends on whether you are asking so as to determine which API to patch at runtime.

**Comment by vefatica** [comment] 2020-09-10 17:32
I'm not going to do any patching (I don't know how).  As I said, I'm just curious.  I just discovered CreateEnvironmentBlock() and I'm about to try it.

**Comment by DHowett** [comment] 2020-09-10 17:33
In that case: Yep, that’s the one we use!

**Comment by vefatica** [comment] 2020-09-10 17:38
Thanks!
