### ISSUE TITLE
a white screen occurs when I drag the windows terminal

### ISSUE THREAD

**Issue by kqkdChen** [microsoft/terminal#3689] opened 2019-11-25 02:01 UTC
**It is normal to open the terminal window first, but once I drag the window, it will turn white.My Windows version 1909**

**Comment by Sir-kaze** [comment] 2019-11-25 04:20
I got the same problem. Then when I maximized window and turned it back, it seems OK. Next I try to drag, but it turns to white screen again. To fix it, I've tried many ways. Finally, I try to resize the windows, then I find it won't white again however I drag it. I guess the problem may related to window size.

**Comment by DHowett-MSFT** [comment] 2019-11-25 20:08
This looks like a /dupe of #3446

**Closed by DHowett-MSFT** 2019-11-25 20:08 UTC
Labels: Needs-Tag-Fix, Needs-Triage
