### ISSUE TITLE
Horizontal Scrolling for Tabs

### ISSUE THREAD

**Issue by grock90** [microsoft/terminal#1542] opened 2019-06-24 16:27 UTC
As a user, when I open more than two tabs in the default terminal size, I must maximize\resize the window to access the nth tab.  There is no horizontal scrolling support.  

# Proposed technical implementation details (optional)
This is a feature that is supported within VS Code and should be extended to windows terminal. 

When more tabs are open than what is supported by the current view, provide horizontal scrolling of the tabs to allow the user to select the nth terminal tab.

**Comment by DHowett-MSFT** [comment] 2019-06-24 16:29
> there is no horizontal scrolling support

well, it scrolls when you use the mouse wheel on it

regardless, this is a duplicate of #857 (title keywords: *tab*, *scroll*). please make sure you search or use github's cool automatic suggestion feature before you file a new issue.

**Closed** 2019-06-24 16:29 UTC
Labels: Needs-Tag-Fix, Needs-Triage, Resolution-Duplicate
