### ISSUE TITLE
Add emoji support to Windows Console

### ISSUE THREAD

**Issue by HLFH** [microsoft/terminal#190] opened 2018-05-23 12:21 UTC
Please support emoji within Windows Console. 

Very useful when you code in `vim` newsletters for startups or when you categorize stuff by emoji.

---

Maintainer notes:

```[tasklist]
### Input
- [ ] #1503
- [ ] #7777
```

```[tasklist]
### Output
- [ ] #8000
- [ ] #1472
```

**Comment by zadjii-msft** [comment] 2018-05-23 15:39
Already on the backlog :)

**Comment by mikemaccana** [comment] 2018-05-24 13:53
Sweet! Another use case: I have a command line app that outputs warnings using ⚠.

**Comment by mqudsi** [comment] 2018-05-26 04:51
@zadjii-msft will this include support for non-latin unicode characters? i.e. can Arabic or Japanese characters not found in the currently deployed console font be displayed with a different font face?

**Comment by zadjii-msft** [comment] 2018-05-26 05:04
Hypothetically, yes. 

Arabic is kinda it's own problem though - there's pretty much no chance we'll be implementing left to right language support any time soon, bt the characters might be able to render correctly.

@adiviness can speak more on the topic if there's more to share.

**Comment by adiviness** [comment] 2018-05-26 15:12
Arabic is a difficult one because of the additional support required for bidirectional text and ligatures. As far as I’m aware not many terminal emulators currently support it. 

There is also a difference between the console being able to render emoji and supporting font fallback in the case of the current font not having a glyph. They are both items on our backlog.

**Comment by SidShetye** [comment] 2018-06-05 17:48
+1 Our build and CI scripts have emojis for success ✔️, warning ⚠ and errors ❌ for quick, productive eyeballing of logs.

**Comment by miniksa** [comment] 2018-06-05 17:50
Can we please not +1 issues? Please use reactions or subscribe to notifications.

**Comment by bitcrazed** [comment] 2018-06-07 20:19
@SidShetye - appreciate your comment - your use-case is not unusual, but is useful to hear about.

In general, we ask people not to +1 because we'd like to avoid people +1-ing (esp. with no further comment), which just ends up as noise, and makes threads more difficult to parse and manage.

Sharing additional comments, context, observations, issues, etc. is FAR more valuable than a +1 ;)

**Comment by destructive-dragon** [comment] 2018-08-30 09:05
Weird that nobody mentioned it, but the Yarn package manager uses Emoji's and it's a bit annoying that they are only displayed as squares :/

**Comment by bitcrazed** [comment] 2018-08-30 16:43
Thanks @destructive-dragon - there are many tools that contain/emit emoji, but the Console is not yet able to render them.

**Comment by kavdev** [comment] 2018-10-17 18:09
@bitcrazed You mentioned [in this twitter thread on the conpty release](https://twitter.com/toubia_a/status/1029840238246539266) that we still need to wait for a new buffer and a new renderer (DirectWrite). Are those the only two major blockers left?

**Comment by bitcrazed** [comment] 2018-10-17 20:39
@kavdev Essentially, yes. To display emoji glyphs, we first have to be able to store (potentially compound) Unicode code-points for each glyph (E.g. Ninjacats), but we also have to be able to render them, which requires font-fallback, which GDI doesn't support.

We'll be working on improvements to both the Console's text buffer implementation, and also the Renderer in future releases.

**Comment by cup** [comment] 2018-12-11 19:35
@bitcrazed technically font-fallback **isnt** required. even if:

1. current font has glyphs for some 4 byte characters
2. is monospace
3. your input data is using glyphs that the font has

it **still** wont work, because of legacy GDI renderer

**Comment by be5invis** [comment] 2019-01-02 17:38
@bircrazed
Many Emoji are composites, i.e., having multiple code points joined together (using ZWJ or VS, or whatever), and in most cases they do not fit in one Console cell. So your problem is not "1 cell to n characters" but "m cells to n characters"...

**Comment by sedwards2009** [comment] 2019-01-02 21:35
FWIW, my terminal emulator and iTerm2 both render emoji by basically treating them as "full width" (2 cell) CJK style characters. I don't know about iTerm2 but I don't make any attempt to support unicode "modifiers" on emoji or any other characters. Each character has to be one unicode code point although it may be normal width or full width.

**Comment by be5invis** [comment] 2019-01-02 22:16
@sedwards2009 
The ultimate solution should be a Unicode or whatever specification that tell us how to handle complex script on a character grid.

**Comment by be5invis** [comment] 2019-01-02 22:20
The closest idea may be applying some concepts from justification (like inserting spaces between East Asian characters, and inserting Kashida when fitting Arabic characters into the grid), but justification implementation is a total mess. AFAIK DWRITE does the best job so far, but some implementations (like Kashida) is still very hacky.

**Comment by benc-uk** [comment] 2019-01-09 11:22
Just one comment which might be useful - certain emoji and unicode symbols *used to work*, I'd display some on my WSL login banner, e.g. 🍰 (U+1F370), since 1809 update they no longer display in any terminal (WSL bash, Hyper, VS Code)  
Some symbols do work however, such as ☕ (U+2615) but I think they are in a different parts of the Unicode spectrum i.e. much lower codepoints

**Comment by noxabellus** [comment] 2019-01-15 19:06
October update seems to bring a regression in this regard rather than progress. I was previously able to use all unicode symbols I have tested in VS Code integrated terminal (Which uses powershell), however after the October update all emoji and certain foreign language characters do not render correctly.

**Comment by MartinMa** [comment] 2019-02-07 15:46
@Ben-Hope @noxabellus are saying Same here.

I updated Windows 10 to 1809 and

**Comment by benc-uk** [comment] 2019-02-07 17:31
Yeah I miss that little rocket when starting the vue-cli 😢

**Comment by mqudsi** [comment] 2019-03-04 01:19
@bitcrazed @zadjii-msft is there an issue tracking the regression found in 1809? I'm not talking about full-on emoji support, just getting back the basic foreign language/unicode glyphs that were supported under previous releases. Do you know if the issue persists in later beta releases?

**Comment by fz568573448** [comment] 2019-03-17 04:36
Same here. I updated my Win10 from 1803 to 1809 several days ago, and now all characters >= U+10000 (UTF-8 with 4 bytes or more) no longer display. I have also tried the newest insider version(Windows 10 Insider Preview 18358.1 (19h1_release)), unfortunately, this bug still exists.

Since 19H1 will be released soon, could you please fix it, or report it because it could be a bug in other project?

**Comment by dmitweb** [comment] 2019-03-29 21:07
Same =(

**Comment by MartinMa** [comment] 2019-05-23 11:34
Emoji rendering seems to have improved.

I tried a recent build of `CascadiaPackage` (Windows; x64) and get this (see image):

![terminal](https://user-images.githubusercontent.com/123297/58249130-53552e80-7d5e-11e9-8d75-3b684c5189ed.png)

Running Windows 10, Build 1903.

**Comment by mdtauk** [comment] 2019-05-23 12:11
Is there any merit to having an option to disable colour font emoji?

So any emoji used will be single colour using the font colour settings?

**Comment by zadjii-msft** [comment] 2019-05-23 13:13
@mdtuak yep, in fact thats a setting @miniksa and I have previously discussed adding. I just filed #956 to track that work :)

**Comment by sylveon** [comment] 2019-05-24 02:50
@MartinMa that's an entirely different thing than the existing conhost.exe, if you tried to run OpenConsolePackage (which is the OSS conhost) you should still have the issue.

**Comment by DHowett-MSFT** [comment] 2019-05-24 03:11
> 
> 
> @MartinMa that's an entirely different thing than the existing conhost.exe, if you tried to run OpenConsolePackage (which is the OSS conhost) you should still have the issue.

Don't be so sure! The DirectWrite renderer that's used in Windows Terminal _is also part of OpenConsole!_ You just need to set a registry key (`HKCU\Console\UseDx`=`DWORD(1)`) before it'll use it.

**Comment by ysc3839** [comment] 2019-05-24 09:27
@DHowett-MSFT The console throws an exception when pasting an emoji string.
It's here.
https://github.com/microsoft/terminal/blob/2fdcb679ab1f1f1edc542e3b86327dacea78f7ac/src/buffer/out/CharRowCellReference.cpp#L15

**Comment by miniksa** [comment] 2019-05-24 16:45
> @DHowett-MSFT Dustin Howett FTE The console throws an exception when pasting an emoji string.
> It's here.
> https://github.com/microsoft/terminal/blob/2fdcb679ab1f1f1edc542e3b86327dacea78f7ac/src/buffer/out/CharRowCellReference.cpp#L15

I am 80-90% sure that either @adiviness or I have a bug covering that already somewhere around here.

**Comment by adiviness** [comment] 2019-05-24 17:04
Yeah, the work I'm doing on the `/dev/austdi/NewCookedRead` probably affects the crash there. We don't support emoji's being pasted (or typed) quite yet in all shells.

**Comment by fcharlie** [comment] 2019-07-19 06:16
> > @MartinMa that's an entirely different thing than the existing conhost.exe, if you tried to run OpenConsolePackage (which is the OSS conhost) you should still have the issue.
> 
> Don't be so sure! The DirectWrite renderer that's used in Windows Terminal _is also part of OpenConsole!_ You just need to set a registry key (`HKCU\Console\UseDx` = `DWORD(1)`) before it'll use it.

I didn't even know that I was going home to try it. But does this registry affect the default conhost?

**Comment by DHowett-MSFT** [comment] 2019-07-22 07:10
Yes, it's almost certainly because of #2053.

**Comment by fcharlie** [comment] 2019-07-22 07:16
@DHowett-MSFT Will my commit fix be appropriate, if there is no problem, I will create a PR. 

https://github.com/fcharlie/terminal/commit/4c6280ca35fff9eac0041c94385574bedc5f2a27

**Comment by innovoix** [comment] 2019-11-20 10:34
Is this fixed? I saw this [Youtube video](https://www.youtube.com/watch?v=UxWN1BBr1bM) where @cinnamon-msft showed emojis support.

**Comment by ExE-Boss** [comment] 2019-11-20 10:51
@innovoix That’s&nbsp;the&nbsp;**Windows&nbsp;Terminal**, this&nbsp;is&nbsp;about the&nbsp;**Windows&nbsp;Console**.

**Comment by innovoix** [comment] 2019-11-20 10:53
@ExE-Boss Ah OK, my bad. Thanks.

**Comment by jasonhargrove** [comment] 2019-12-06 20:11
![image](https://user-images.githubusercontent.com/285708/70353014-6df27f00-183a-11ea-8b67-9ead2d355a8d.png)

When I setup a Windows workstation for the first time in 10 years, now very used to OSX, I was very disturbed to lose the beloved and also extremely useful emojis. Sort of funny it's not already a long ago default

**Comment by DHowett-MSFT** [comment] 2019-12-06 20:46
@jasonhargrove thanks for the feedback. You may want to check out _Windows Terminal_, which is (incidentally) also built out of this repository. It does support the things you're looking for.

![image](https://user-images.githubusercontent.com/14316954/70355189-60cb9500-1826-11ea-8e95-0c42b58e4c6b.png)

**Comment by bitcrazed** [comment] 2019-12-06 20:46
@jasonhargrove We do plan on integrating many of the improvements to the core engine underlying both Windows Terminal, and Windows Console back into Windows Console in the future. Such areas include the internal text buffer, text rendering engine, etc. - things that won't generally impact backward-compatibility. 

Why the "backward compat'" caveat? Windows Console's job (along with Cmd), is to remain backward-compatible wherever possible. Thus, there will be many features (e.g. tabs, split panes, etc.) that will only be available in Windows Terminal, and will never make it back into Console. 

We strongly recommend that users start using and testing Windows Terminal, file any unexpected issues here so that we can triage and fix them as quickly as possible as we drive Terminal towards v1.0 (~Q2 2020).

FWIW, Windows Terminal DOES support emoji, split panes, a huge number of configuration options, etc.

**Comment by jsilvermist** [comment] 2019-12-07 01:01
One thing that drives me crazy is the inability to Shift+Insert paste in the Windows Terminal.

**Comment by DHowett-MSFT** [comment] 2019-12-07 01:02
@jsilvermist you can add `shift+ins` as a key binding in your Terminal settings.

**Comment by bitcrazed** [comment] 2019-12-07 01:03
@jsilvermist Polite request - please keep issues to relevant threads. The issue you describe relates to key-bindings, not emoji ;)

**Comment by jsilvermist** [comment] 2019-12-07 01:07
@bitcrazed True, my bad! Also, thanks @DHowett-MSFT!

**Comment by bitcrazed** [comment] 2019-12-07 01:08
@jsilvermist No problem - we all do it now and again - many thanks :)

**Comment by jasonhargrove** [comment] 2019-12-07 01:19
![image](https://user-images.githubusercontent.com/285708/70366290-34cf0480-1864-11ea-9996-a73b8d16e8cd.png)

Ok Christmas comes early! Great start to this and what a major leap forward, congrats. And thanks for letting me know about it 📈

**Comment by jasonhargrove** [comment] 2019-12-07 01:27
![image](https://user-images.githubusercontent.com/285708/70366290-34cf0480-1864-11ea-9996-a73b8d16e8cd.png)

Ok Christmas comes early! Great start to this and what a major leap forward, congrats. And thanks for letting me know about it 📈

**Comment by AmericanY** [comment] 2020-01-03 15:20
![Capture](https://user-images.githubusercontent.com/27644047/71731374-384ab100-2e4d-11ea-8e29-34c12d3af1aa.PNG)

is it normal to see `??` if i paste the emoji. please confirm. thanks in advance.

**Comment by DHowett-MSFT** [comment] 2020-01-03 18:58
@AmericanY yeah, this is an issue with PowerShell 5.1.

**Comment by AmericanY** [comment] 2020-01-04 08:13
@DHowett-MSFT that's happens on CMD, PowerShell and windows new terminal .

**Comment by Vikr-182** [comment] 2020-01-23 07:13
My WSL is printing some unusual characters after it has rendered the unicode string. I was trying to build an interactive game and wasn't able to display the characters due to this. Looks like I have to restrict myself to 128-bit ASCII 
![image](https://user-images.githubusercontent.com/44745884/72963713-f5da1b80-3ddd-11ea-8314-9d832cd0e3fc.png)

**Comment by DHowett-MSFT** [comment] 2020-01-24 02:48
I just want to say, with apologies, that this looks hilarious.

**Comment by luke1961** [comment] 2020-04-11 05:02
Is the src code for fmt_test.exe available somewhere? (screenshot by @fcharlie earlier in this thread)

**Comment by fcharlie** [comment] 2020-04-11 05:05
@luke1961 see https://github.com/fcharlie/bela/blob/master/test/fmt/main.cc

**Comment by luke1961** [comment] 2020-04-11 05:29
Thanks!

**Comment by remidebette** [comment] 2020-04-11 10:13
Hi,
To add on the comment of @AmericanY , what pasting in the **Windows Terminal** an emoji (say from a preexisting output) it is broken in the input and correct in the output.
Also if doing an up arrow right after, then it is correct in the input this time.

Is this expected ?

![image](https://user-images.githubusercontent.com/16523229/79041047-f750fe00-7bec-11ea-861b-5e66630e8d15.png)

Windows Terminal
Powershell Core 6.2.1
Meslo LG M for Powerline

**Comment by am11** [comment] 2020-04-11 12:04
> @AmericanY yeah, this is an issue with PowerShell 5.1.

Besides that one, the space between two emojis get converted to linefeed in posh 5.1, but not in other shells like ash, bash and so on:

<img src=https://user-images.githubusercontent.com/3840695/79043019-1cea0180-7c05-11ea-963f-ef1c5c01a2b7.png width="50%"/>

**Comment by zadjii-msft** [comment] 2020-04-13 13:49
@remidebette You'll want to see #1503

**Comment by remidebette** [comment] 2020-04-13 13:57
@zadjii-msft , this seems hard, but will be really nice once you crack it.
Hang in there!

**Comment by gund** [comment] 2020-05-01 06:22
I've tested emoji on a few shells under Windows Terminal (Version: 0.11.1191.0) and here are results:
- CMD
  ![image](https://user-images.githubusercontent.com/3644678/80786480-17d4fe00-8b84-11ea-8e8d-83374aa6bee3.png)
- Powershell
  ![image](https://user-images.githubusercontent.com/3644678/80786509-2cb19180-8b84-11ea-81a3-a2912a5d1faf.png)
- Cmder
  ![image](https://user-images.githubusercontent.com/3644678/80786548-44891580-8b84-11ea-8cab-e0b2915ea922.png)
- WSL with ZSH
  ![image](https://user-images.githubusercontent.com/3644678/80786586-5ec2f380-8b84-11ea-9772-ef5b054442ef.png)
- Cygwin with ZSH
  ![image](https://user-images.githubusercontent.com/3644678/80786610-726e5a00-8b84-11ea-877c-11c5a1b2cca8.png)

Looks like the only shell that works perfectly so far is WSL (both bash and zsh)...

**Comment by adiviness** [comment] 2020-05-01 13:47
I’m working with an old set of information, but it at least used to be that the console stores the prompt line in a separate buffer from the output buffer and that it didn’t support more than ucs2 encoding. WSL works bc it’s encoded in utf8. I was working on a branch at one point that fixed this, if I find the time this weekend I’ll take a peek. Hmm

**Comment by louanbastos** [comment] 2020-05-23 12:23
How can i fix the emoji?
https://i.imgur.com/cOx12WA.png

**Comment by hwongbaul** [comment] 2020-05-24 12:21
I'm encountering the same problem; it seems no an up-to-date solution afaik.

![image](https://user-images.githubusercontent.com/8535390/82753856-b6f3bb00-9dfb-11ea-82d9-bd04e53e4a2f.png)

**Comment by schuelermine** [comment] 2020-06-29 00:09
> 
> 
> Sweet! Another use case: I have a command line app that outputs warnings using ⚠.

*Output* of Emoji works fine in my experience.

**Comment by Raibows** [comment] 2020-08-27 04:50
So it can be sure that the problem is input characters not rendering correctly in windows terminal. I have tried Git Bash(one kind fo shell), It works well with Git Bash GUI, but not working with windows terminal same as the bugs mentioned as others.

1. Git Bash GUI
![pic08-27-12-45-00](https://user-images.githubusercontent.com/37944786/91385277-22b64b80-e863-11ea-960a-6330ffb5c308.png)
2. Git Bash with Windows Terminal
![pic08-27-12-46-35](https://user-images.githubusercontent.com/37944786/91385403-5e511580-e863-11ea-9f99-d2aa6a580dd7.png)

My windows terminal version is 1.1.2233.0.
Hope could fix it as soon as possible! 👍 And is there an estimated schedule?

**Comment by DHowett** [comment] 2020-08-27 05:03
Please file a separate bug for this issue and include the contents of your Windows Terminal settings file.

**Comment by mamayadi** [comment] 2020-09-23 08:06
> Please file a separate bug for this issue and include the contents of your Windows Terminal settings file.

I have the same issue:
`{
        "guid": "{00000000-0000-0000-ba54-000000000002}",
        "acrylicOpacity": 0.75,
        "closeOnExit": true,
        "colorScheme": "Campbell",
        "commandline": "\"%PROGRAMFILES%\\git\\usr\\bin\\bash.exe\" -i -l",
        "cursorColor": "#FFFFFF",
        "cursorShape": "bar",
        "fontFace": "Consolas",
        "fontSize": 10,
        "historySize": 9001,
        "icon": "%PROGRAMFILES%\\Git\\mingw64\\share\\git\\git-for-windows.ico",
        "name": "Bash",
        "padding": "10, 0",
        "snapOnInput": true,
        "startingDirectory": "%USERPROFILE%",
        "useAcrylic": true
      },`
Windows Terminal: v1.3.2651.0
Git: v2.16.2.windows.1

**Comment by rymnc** [comment] 2021-03-02 11:41
Emoji's dont show up in an ssh session as well, not sure if you know about it.

**Comment by thiagocavalcanti** [comment] 2021-04-28 13:46
Any update on this?

**Comment by zadjii-msft** [comment] 2021-04-28 13:51
Nope. We'll make sure to update this thread when there is. In the meantime, might I recommend the Subscribe button?
![image](https://user-images.githubusercontent.com/18356694/91237459-5cbb0c80-e700-11ea-9347-b9b1ec2813b1.png)
That way you'll be notified of any updates to this thread, without needlessly pinging everyone on this thread ☺️

**Comment by Codingpowerx** [comment] 2021-08-14 11:54
Emojis😊😋🥵 works very well on VS CODE Terminal!

**Comment by miniksa** [comment] 2021-08-17 17:39
Did #10478 improve this for the console? I think it did. Everything except the cooked edit line itself should probably work with the Uniscribe flows/fallback that `ExtTextOutW` offers.

**Comment by lloydjatkinson** [comment] 2022-01-16 18:11
Is this still on the backlog? Unicode 13 was released in March 2020...

**Comment by paul-at** [comment] 2022-01-16 18:19
> Is this still on the backlog? Unicode 13 was released in March 2020...

Seems to work for me at the moment in Windows Terminal Preview 1.12.3472.0 in both PS 5.1 and WSL2/Ubuntu, although #1472 bug still there.

**Comment by parktheredcar** [comment] 2022-05-02 13:32
Under profile settings > advanced, 'Enable experimental text rendering engine' has significantly improved things for me like the garbled text in ncurses applications that were rendering certain emojis. Running Preview 1.13.10983.0

**Comment by brupelo** [comment] 2022-12-10 20:59
Hey guys, is this the official thread about emoji support?

I've just tried `Version: 1.15.2874.0` running a simple python script that uses [rich](https://pypi.org/project/rich/):

```
from rich._emoji_codes import EMOJI
from rich.console import Console

if __name__ == "__main__":
    console = Console()
    for k, v in EMOJI.items():
        console.print(f":{k}:")
```

And everything has rendered correctly on win10... Problem comes if I try to add emojis manually by pressing `win+.`,
in that case I'll just get an incorrect render, ie:

![image](https://user-images.githubusercontent.com/18058492/206874928-bf7a20ea-e451-4786-9790-65a5216be7e8.png)

Anyway, is this one already reported? Is this the right backlog work-item to suscribe to? I've read another ones pinging to this one so I'm assuming it's the "official" one... 🙄

Evolving really nicely the software btw, congrats guys!

**Comment by zadjii-msft** [comment] 2022-12-13 20:11
To clarify:

* _Outputting_ emoji to the Terminal generally works quite well today. Especially in an environment like WSL, where everything is already in UTF-8. 
  - There's a long tail of bugs remaining here. Some sizing issues. 
  - Then, there's also the case of emoji made from **m a n y** codepoints, which we're tracking in #8000 (more or less).
* _Inputting_ emoji really what's missing here. That's the visible part of "trying to type an emoji into CMD.exe". We're largely tracking that in https://github.com/microsoft/terminal/issues/7777, and the many threads linked to that. 

This has kinda become the mega thread for _both_, though, most of the remaining work remains in #7777.

**Comment by brupelo** [comment] 2022-12-18 14:44
@zadjii-msft Hey Mike, thanks, cool stuff. So I guess the issue happening when copy/pasting emojis from other software such as SublimeText and not being rendered properly is also a related work-item from this one, ie:

![WindowsTerminal_2022-12-18_15-33-43](https://user-images.githubusercontent.com/18058492/208304564-a67ec830-e8c5-48c4-b24c-7e7155d50758.png)

You can see how in SublimeText the emojis are rendered properly, similar in the good old `clipbrd.exe` software but when i copy/paste into `wt` the render will be broken.

You can find the emojis.txt file attached 
[here](https://github.com/microsoft/terminal/files/10254038/emojis.txt)

**Comment by o-sdn-o** [comment] 2023-01-03 14:52
It seems to me that cmd.exe does not play any role here. Between cmd.exe and Windows Terminal there is conhost.exe (openconsole.exe), it is responsible for such handling of emoji. If we replace it with something of our own, then there will be the expected result

https://user-images.githubusercontent.com/11535558/210380863-d8061bd5-c4e0-4a3a-963f-cb245e8e845b.mp4

**Comment by marklit** [comment] 2023-06-02 06:41
Will there be support for country flags at some point?

![image](https://github.com/microsoft/terminal/assets/359316/e976ba9d-53da-4cc5-b0ba-88d4cfd16484)

**Comment by TheDecryptor** [comment] 2023-06-02 07:33
That's outside of Terminal's control, the Segoe UI Emoji font just doesn't include flags.

#2664 would allow customising the fonts Terminal tries to use, you could then include something like "Noto Color Emoji", which does include graphical flags.

**Comment by marklit** [comment] 2023-06-04 16:01
Has anyone here tried to edit the Segoe UI Emoji font file and add in / replace the country flag emojis from another font? The Terminal doesn't support images so printing out GIFs or SVGs is a non-starter.

**Comment by Welding-Torch** [comment] 2024-04-05 22:23
When will we get Nerd Font Icons(Glyphs) support in conhost.exe?

**Comment by DHowett** [comment] 2024-04-05 22:37
> When will we get Nerd Font Icons(Glyphs) support in conhost.exe?

You should be able to install a "nerd font" font and set it as your font _today._ Also last year, and perhaps some years prior to that one.

**Comment by lhecker** [comment] 2024-07-22 13:00
With #16916 merged and with all the work that led up to it, support for complex Unicode, including Emoji, is effectively done. There are some smaller issues left to clean up, but I expect them to be a rare encounter. As such I'll close this issue for now.

This will ship in Windows Terminal 1.22 this year. If you want to try it out right now, please feel free to download our Canary (nightly) build here: https://github.com/microsoft/terminal/discussions/16121

Please note that PowerShell does not have support for complex Unicode yet, but that's expected to change in the foreseeable future (no exact date yet).

I'll keep this issue locked since a lot of people are subscribed to it and would get notifications every time someone posts here. If find any issues with our implementation, [please report a new issue](https://github.com/microsoft/terminal/issues/new/choose). If you have any other feedback, [please feel free to start a new discussion](https://github.com/microsoft/terminal/discussions/new/choose).

**Closed by lhecker** 2024-07-22 13:00 UTC
Labels: Issue-Feature, Product-Conhost, Area-Rendering
