### ISSUE TITLE
conhost.exe crashes when inserting emoji

### ISSUE THREAD

**Issue by savatia** [microsoft/terminal#788] opened 2019-05-14 18:27 UTC
Steps to repro:

1. Open cmd.exe or Powershel.exe
2. Press Win+. in order to open the Emoji Picker overlay
3. Click on any emoji, multiple times, until the console crashes

**Comment by oising** [comment] 2019-05-14 18:35
Duplicate of #678

**Comment by miniksa** [comment] 2019-06-03 23:06
I actually need to un-dupe this. I have a solution to the conhost emoji-picker part, but not the terminal hang part.

Reactivating this so I can fix it (along with the internal crash bug MSFT: 20990158 that has been reported)

**Closed** 2019-06-04 22:22 UTC
Labels: Area-Output, Issue-Bug, Product-Conhost, Severity-Crash
