### ISSUE TITLE
Incorrect tab resizing

### ISSUE THREAD

**Issue by spixy** [microsoft/terminal#3583] opened 2019-11-14 20:59 UTC
# Environment

```none
Windows build number: 10.0.18363.0
Windows Terminal version: 0.6.2951.0
```

# Steps to reproduce

Setwindow width to its minimum size.
Tabs are not visible now.
Restore window to its previous size .

# Expected behavior

![image](https://user-images.githubusercontent.com/4542110/68895067-e5942900-0728-11ea-9828-d5e28d6422e4.png)

# Actual behavior

![tabs2](https://user-images.githubusercontent.com/4542110/68894883-846c5580-0728-11ea-9a62-b785ee256ca6.png)

Tabs are now only partialy visible or not visible at all.
Also terminal content is gone (when I change booth width and height), but that could be related to #3446.

**Comment by DHowett-MSFT** [comment] 2019-11-14 21:03
This is a /dupe of #3300, which is pinned to the top of the issues list. Please make sure you're searching before filing new issues!

**Closed by DHowett-MSFT** 2019-11-14 21:03 UTC
Labels: Needs-Tag-Fix, Needs-Triage

**Comment by spixy** [comment] 2019-11-14 21:56
> Please make sure you're searching before filing new issues!

I was searching, but I was using wrong keywords (like `tabs disappearing`, `tabs hidden`) or results contained too many pages so I gave up with the searching. Anyway thanks for fast response and have a nice day.
