### ISSUE TITLE
Dropdown list inside settings UI when kept open and section is scrolled, dropdown list goes outside the window

### ISSUE THREAD

**Issue by rajan-31** [microsoft/terminal#10488] opened 2021-06-22 16:54 UTC
### Windows Terminal version (or Windows build number)

Windows Terminal 1.7.1033.0

### Steps to reproduce

- Open settings UI and inside the "Startup" section click on the "Default Profile" dropdown menu
- Try to scroll the entire section
- Dropdown list goes outside the window

![image](https://user-images.githubusercontent.com/62245685/122967717-63f68980-d3a8-11eb-862b-16e24a2e1e4f.png)
---

- Inside the "Color Schemes" section click on the colors dropdown menu
- Try to scroll the entire section
- Dropdown list goes outside the window

![image](https://user-images.githubusercontent.com/62245685/122967830-84264880-d3a8-11eb-8ce7-4f8e2cabe9c9.png)

### Expected Behavior

When the section is scrolled the dropdown list should not be visible outside the "Windows Terminal" window

### Actual Behavior

When the section is scrolled the dropdown list is visible outside the "Windows Terminal" window

**Comment by DHowett** [comment] 2021-06-22 17:31
Thanks for the report! This is a /duplicate of #9320.

Curiously, you're using an older version of Terminal than the current stable version (1.8).

**Closed by DHowett** 2021-06-22 17:31 UTC
Labels: Needs-Tag-Fix, Needs-Triage
