### ISSUE TITLE
Terminal does not run on N SKU after latest Windows Feature Update 22H2

### ISSUE THREAD

**Issue by Ceffas84** [microsoft/terminal#14104] opened 2022-09-30 08:40 UTC
Windows version
Windows 11 Education N, 22H2

Windows build number
22621.521

Windows Feature Experience Pack
1000.22634.1000.0

Windows Terminal version
1.15.2713.0

Steps to reproduce
Update Windows to Version 22H2
Install Windows Terminal using the Windows Store;
Open Windows Terminal;

Expected Behavior
Windows Terminal should open a window.

Actual Behavior
Windows Terminal does not open a window.

What I have done, so far:
Re-installed the Windows Terminal

Remarks:
It was working fine before de Windows update, so I assume, the problem it's related to modifications made by the update.

**Comment by RiteshChepuri** [comment] 2022-09-30 10:59
It works just fine for me after the update.

**Comment by drakonien** [comment] 2022-10-02 19:18
Same problem, it was working fine but now fails.
Here is a trace from the Event Viewer:

`Nombre de la aplicación con errores: WindowsTerminal.exe, versión: 1.16.2209.21001, marca de tiempo: 0x632b96ad
Nombre del módulo con errores: Windows.UI.Xaml.dll, versión: 10.0.22621.608, marca de tiempo: 0xbb1317fb
Código de excepción: 0xc000027b
Desplazamiento de errores: 0x00000000005b2e90
Identificador del proceso con errores: 0x0x1F24
Hora de inicio de la aplicación con errores: 0x0x1D8D6917089F60B
Ruta de acceso de la aplicación con errores: C:\Program Files\WindowsApps\Microsoft.WindowsTerminalPreview_1.16.2641.0_x64__8wekyb3d8bbwe\WindowsTerminal.exe
Ruta de acceso del módulo con errores: C:\Windows\System32\Windows.UI.Xaml.dll
Identificador del informe: 8e211333-e387-4009-829e-bea2dafd29bf
Nombre completo del paquete con errores: Microsoft.WindowsTerminalPreview_1.16.2641.0_x64__8wekyb3d8bbwe
Identificador de aplicación relativa del paquete con errores: App`

It fails the same with Windows Terminal and Windows Terminal Preview

**Comment by RiteshChepuri** [comment] 2022-10-03 05:27
I think this problem occurs in terminal preview. Try resetting or reinstalling the app.

**Comment by drakonien** [comment] 2022-10-03 10:14
> I think this problem occurs in terminal preview. Try resetting or reinstalling the app.

For me it fails in the "Preview" version and also in the "Standard". I tried reparing, resetting and reinstalling both versions to no avail, same problem.

**Comment by Ceffas84** [comment] 2022-10-03 10:33
Same here. Reparing, resetting and reinstalling does not solve the problem.

**Comment by zadjii-msft** [comment] 2022-10-03 12:01
@drakonien Can you submit feedback via the feedback hub? Make sure to start a recording then try to launch the Terminal. That should get us a stack trace for whatever the root cause is here. 

As an aside, are you running the N SKU of Windows by any chance?

Thanks!

/feedback

**Comment by drakonien** [comment] 2022-10-03 12:23
> @drakonien Can you submit feedback via the feedback hub? Make sure to start a recording then try to launch the Terminal. That should get us a stack trace for whatever the root cause is here.
> 
> As an aside, are you running the N SKU of Windows by any chance?
> 
> Thanks!
> 
> /feedback

In fact I am running a Windows N, but I have just installed the Media Feature Pack, and installed again the Windows Terminal from the Store, and now is working!!

**Comment by zadjii** [comment] 2022-10-03 12:27
@carlos-zamora @lhecker someone should check which version of the MIDI code is in the inbox build. We're getting a lot of these, and idk if we can even service that 😨

**Comment by lhecker** [comment] 2022-10-03 13:00
@zadjii I'm not sure it's related... The reports are mostly about 1.15/1.16 and those don't use the MIDI code. `0xc000027b` is `STATUS_STOWED_EXCEPTION`, which means we could wait and see what the debug logs (if anyone posts them here) or ETW traces show as the original exception.

**Comment by relcodedev** [comment] 2022-10-03 14:30
Installing the Media Feature Pack, reboot and install of Windows Terminal fixed my issue.  Thank you!
FYI: Media Feature Pack failed to install until I uninstalled Windows Terminal first. I don't know if it was the cause of failure.

**Comment by Ceffas84** [comment] 2022-10-03 15:23
> Installing the Media Feature Pack, reboot and install of Windows Terminal fixed my issue. Thank you! FYI: Media Feature Pack failed to install until I uninstalled Windows Terminal first. I don't know if it was the cause of failure.

It worked for me aswell.

**Comment by j4james** [comment] 2022-10-04 13:44
> someone should check which version of the MIDI code is in the inbox build

@zadjii I think the original MIDI code was always behind a velocity flag (PR #13258), so that shouldn't have been available outside dev/preview builds. This might be an issue with the DirectSound implementation though. @DHowett mentioned that there were versions of Windows that didn't have DirectSound included, and recently updated the code to load the dsound.dll on demand (see PR #14005). I suspect that fix hasn't been released though.

If this is my fault - which seems quite likely - I sincerely apologise to everyone affected.

**Comment by j4james** [comment] 2022-10-04 14:11
FYI, #13751 also has a 0xc000027b exception listing Windows.UI.Xaml.dll as the faulting module.

**Comment by DHowett** [comment] 2022-10-04 18:13
I'm quite horrified (also, worried?) that my local testing in the N sku _did not uncover this issue._ We set up Windows N VMs for this express purpose :smile:

Fortunately, we can fix this in time for Nickel+1 (since that's where we live-check-in new versions), and the issue doesn't exist in Nickel (it's stuck on 1.12).

**Comment by j4james** [comment] 2022-10-12 22:16
@hmartinez82 As mentioned above, you may be able to resolve the issue by installing the [Media Feature Pack](https://support.microsoft.com/en-us/topic/media-feature-pack-list-for-windows-n-editions-c1c6fffa-d052-8338-7a79-a4bb980a700a).

**Comment by happybaby8882** [comment] 2022-10-17 01:14
> Installing the Media Feature Pack, reboot and install of Windows Terminal fixed my issue. Thank you! FYI: Media Feature Pack failed to install until I uninstalled Windows Terminal first. I don't know if it was the cause of failure.

Mine maybe have the same issue. but I could't install media feature pack through Opional feature. It reports an error 0x80070490. Could you help me with that?
![2022-10-17_085252](https://user-images.githubusercontent.com/70244073/196069381-18b2f944-affb-4e15-a9ed-94851f0e5813.png)

**Comment by DHowett** [comment] 2022-10-17 17:10
FWIW this should be fixed with Terminal 1.15.2874 and 1.15.2875, which are rolling out via the store as of Friday evening.

**Closed by DHowett** 2022-10-17 17:10 UTC
Labels: Area-VT, Severity-Crash, Product-Terminal, Needs-Tag-Fix, Severity-Blocking, Priority-0
