### ISSUE TITLE
Unable to view Unicode on CMD or PowerShell

### ISSUE THREAD

**Issue by AmericanY** [microsoft/terminal#4074] opened 2019-12-29 10:31 UTC
I do have a `Centos 7` server which i access it via `CMD` or `PowerShell`.

But it's displaying the Unicode characters as `?`

[![enter image description here][1]][1]

But if i accessed it via `putty` it's displayed correctly.

[![enter image description here][2]][2]

  [1]: https://i.stack.imgur.com/nju1p.png
  [2]: https://i.stack.imgur.com/sIaHV.png

**Comment by j4james** [comment] 2019-12-29 13:00
See issue #190.

**Comment by DHowett-MSFT** [comment] 2020-01-06 20:46
Yep, this is a /dupe of #190. Thanks!

**Closed by DHowett-MSFT** 2020-01-06 20:46 UTC
Labels: Needs-Tag-Fix, Needs-Triage
