### ISSUE TITLE
there are still white spaces on the right side of the windows while padding is set to 0

### ISSUE THREAD

**Issue by ethan-enhe** [microsoft/terminal#12069] opened 2021-12-30 10:21 UTC
### Windows Terminal version

1.11.3471.0

### Other Software

NVIM v0.4.3 in WSL

### Steps to reproduce

relevant configurations
```json
"defaults": 
{
    "acrylicOpacity": 0.69999999999999996,
    "backgroundImage": null,
    "backgroundImageOpacity": 0.29999999999999999,
    "bellStyle": 
    [
        "window",
        "taskbar"
    ],
    "closeOnExit": "graceful",
    "colorScheme": "Gruvbox Dark",
    "cursorColor": "#657B83",
    "cursorShape": "filledBox",
    "font": 
    {
        "face": "FiraCode NF",
        "size": 13
    },
    "historySize": 9001,
    "padding": "0",
    "scrollbarState": "hidden",
    "snapOnInput": true,
    "useAcrylic": true
},
```
```json
{
    "commandline": "wsl",
    "guid": "{2c4de342-38b7-51cf-b940-2309a097f518}",
    "hidden": false,
    "name": "Ubuntu",
    "source": "Windows.Terminal.Wsl",
    "startingDirectory": "\\\\wsl$\\Ubuntu\\home\\ethan"
},

```

### Expected Behavior

no padding should appear on the side of the windows

### Actual Behavior
there are white spaces on the right of the windows

![image.png](https://s2.loli.net/2021/12/30/rGskzmg1FUK2QpM.png)![image.png](https://s2.loli.net/2021/12/30/iFdhomTHfC2EwxQ.png)

**Comment by j4james** [comment] 2021-12-30 18:09
I believe the area on the right is reserved for the scrollbar. If you don't like that gap, you can always hide the scrollbar.
https://docs.microsoft.com/en-gb/windows/terminal/customize-settings/profile-appearance#scrollbar-visibility

**Comment by ethan-enhe** [comment] 2021-12-31 02:01
> I believe the area on the right is reserved for the scrollbar. If you don't like that gap, you can always hide the scrollbar. https://docs.microsoft.com/en-gb/windows/terminal/customize-settings/profile-appearance#scrollbar-visibility
i have already hide it in my config (shown above)
```json
"scrollbarState": "hidden",
```

**Comment by j4james** [comment] 2021-12-31 18:47
Sorry. I missed that. But if it's not the scrollbar, I have no idea. The only way I can reproduce a gap is if I make the terminal fullscreen (which doesn't appear to the case in your screenshot) or if I change the font without resizing (once you resize the window it should "jump" to an exact multiple of the cell size).

Is it possible that this only happens in NVIM? For example, if you just start typing a load of text on the command line until it wraps, does that also leave the last column of the screen blank, or does the text go all the way up to the edge?

**Comment by ethan-enhe** [comment] 2022-01-01 09:08
> Sorry. I missed that. But if it's not the scrollbar, I have no idea. The only way I can reproduce a gap is if I make the terminal fullscreen (which doesn't appear to the case in your screenshot) or if I change the font without resizing (once you resize the window it should "jump" to an exact multiple of the cell size).
> 
> Is it possible that this only happens in NVIM? For example, if you just start typing a load of text on the command line until it wraps, does that also leave the last column of the screen blank, or does the text go all the way up to the edge?

Actually there are no blank in the last column when I make it full screen...

![image.png](https://s2.loli.net/2022/01/01/ruQYxdOZ9kELnUV.png)

Also, it's not just in nvim, the same thing happend to the command prompt too.

![image.png](https://s2.loli.net/2022/01/01/c1zE6UoCadrblBs.png)

I've failed to reproduce that on other computers too😰

**Comment by j4james** [comment] 2022-01-01 11:00
In your Windows display settings, do you have the scaling set to something odd like 175%?

**Comment by 237dmitry** [comment] 2022-01-01 12:41
Can you try to run bash or powershell with default prompt?
```
powershell -noprofile
bash --noprofile --norc
```

**Comment by ethan-enhe** [comment] 2022-01-02 11:32
> In your Windows display settings, do you have the scaling set to something odd like 175%?

my scaling is set to 150%

**Comment by ethan-enhe** [comment] 2022-01-02 11:33
> Can you try to run bash or powershell with default prompt?
> 
> ```
> wt -w 0 nt powershell -noprofile
> wt -w 0 nt bash --noprofile --norc
> ```

I've tried these, it doesn't help 😅

**Comment by j4james** [comment] 2022-01-03 01:05
> my scaling is set to 150%

OK, that probably means this is a duplicate of issue #4175. On my system the gap doesn't show at 200%, but I can reproduce it (at least some of the time) at 175% and 150%.

If you temporarily set your scaling to 100% does that solve the problem? Not suggesting you should have to do that permanently - just to confirm that the scaling is the cause of the gap.

**Comment by ethan-enhe** [comment] 2022-01-03 12:08
> > my scaling is set to 150%
> 
> OK, that probably means this is a duplicate of issue #4175. On my system the gap doesn't show at 200%, but I can reproduce it (at least some of the time) at 175% and 150%.
> 
> If you temporarily set your scaling to 100% does that solve the problem? Not suggesting you should have to do that permanently - just to confirm that the scaling is the cause of the gap.

That does solve the problem

**Comment by zadjii-msft** [comment] 2022-01-20 13:33
Wow good find with #4175. Totally forgot about that one. Good eye!

/dup #4175

**Closed by zadjii-msft** 2022-01-20 13:33 UTC
Labels: Needs-Triage, Needs-Tag-Fix
