### ISSUE TITLE
Frames and special characters from bitmap TTF font are not visible

### ISSUE THREAD

**Issue by atlka** [microsoft/terminal#7927] opened 2020-10-15 07:10 UTC
<pre>
Windows 10 Pro

Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.19041.0 Microsoft Windows NT 10.0.19041.0

Windows Terminal
Version: 1.3.2651.0
</pre>

# Steps to reproduce

Use TTF font containing only embeded bitmaps, for example https://www.pg.gda.pl/~atlka/fonts/terminusa.ttf with 12pt size and 96DPI (no scaling) screen settings.
In the profile settings.json insert:
<pre>
"fontFace": "Terminusa",
"fontSize": 12,
</pre>
# Expected behavior

All bitmap glyphs form bitmap font are displayed on the terminal like in the cmd.exe window.
# Actual behavior

You can see  letters and digits but no special chars and frames - they are just blanks.

**Comment by zadjii-msft** [comment] 2020-10-15 07:18
>  no special chars and frames

What characters are you trying to output exactly? The exact UTF-8 encoding of the characters would help here immensely, or even just copy-pasting the character into github

**Comment by atlka** [comment] 2020-10-15 07:27
An example bleow:

**Comment by atlka** [comment] 2020-10-15 07:38
far with Windows Terminal example:
![far-windows-terminal](https://user-images.githubusercontent.com/52749958/96091516-fe253a00-0ec9-11eb-8788-317a498d15af.png)

far with Cmd.exe example:
![far-cmd](https://user-images.githubusercontent.com/52749958/96091535-04b3b180-0eca-11eb-9088-7077040b0247.png)

**Comment by DHowett** [comment] 2020-10-16 01:25
_oh my gosh, you're totally right_!

/cc @miniksa for fun

When we get the _geometries_ from the font for the box-drawing characters, there aren't any. This is obvious in retrospect. I totally forgot that TTF files with bitmap strikes were a thing.

**Comment by miniksa** [comment] 2020-10-16 17:42
Man, fonts are hard. We just need to realize these are bitmap strikes and not use the scaling thing I guess.

**Comment by tidux** [comment] 2021-02-16 02:21
TTF/OTF fonts provide embedded bitmaps for regular number/letter characters as well, which is still missing.  Perhaps expose a "use embedded bitmaps in font" toggle to settings.json?  That's how FreeType Fontconfig does it on Linux.

**Comment by wolf99** [comment] 2021-05-27 17:14
Just came from #10038.
I'm not familiar with the labels and milestones, do the current ones mean that this is intended to be fixed for WT v2.0 (i.e. Winter 2021) ?

**Comment by zadjii-msft** [comment] 2021-05-27 17:21
Yep

**Comment by atlka** [comment] 2021-06-04 09:35
Dnia 16 lutego 2021 03:22:14 CET, Tidux ***@***.***> napisał(a):
>TTF/OTF fonts provide embedded bitmaps for regular number/letter
>characters as well, which is still missing.  Perhaps expose a "use
>embedded bitmaps in font" toggle to settings.json?  That's how FreeType
>Fontconfig does it on Linux.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/microsoft/terminal/issues/7927#issuecomment-779539655

What You should know this feature was working correctlty with old terminal releases. Besides normal letters and characters from a bitmap truetype font are rendered ok with current releases. Only specjal graphical characters - frames and blocks are rendered as blanks.

So I find it to be rather a bug which need to be fixed in the current version and not a some kind of a feature for the next version.
Regards

-- 
Adam Tlałka

**Comment by wolf99** [comment] 2021-06-04 15:46
I would tend to agree with @atlka.
I have noticed this when using tig (https://jonas.github.io/tig/). The git graph therein no longer shows any lines.
This worked just fine in previous versions so this is a regression rather than a feature IMHO.

**Comment by tsu-kunn** [comment] 2021-09-08 01:42
I would tend to agree with @atlka.
I don't have this problem with VSCode or Git Bash, and I hope it will be fixed.

**Comment by atlka** [comment] 2021-09-30 10:44
Hello,
what is more important this feature worked quite well with previous terminal releases.

Generally bitamp TTF font works properly with terminal in case of normal chars and powerline symbols too, but not for box drawing nad block elements and this should be fixed.

I vote for an option which switches between getting this range of glyphs from font (so it works as in the past) or generating bit perfect bitmaps by program itself as in the new VSCode.

**Comment by miniksa** [comment] 2021-10-06 17:50
I hear what you're saying. We just only have so many folks to go around on fixing issues. We'd happily welcome a community submission here if someone knows how to detect a font with bitmaps embedded here in our DirectX engine route and make it do the old behavior.

From our perspective, this likely remains a priority 3 just because it's a graphical glitch that can be self-serviced by the user through changing to a different font. That's not to say it isn't important, but it is ranking lower than all the accessibility and crash and default application bugs and such that we've been juggling as of late. I'm sorry it's taking so long.

**Comment by miniksa** [comment] 2021-11-03 22:53
I have a feeling like this might be enabled by #11623 in the future.

**Comment by lhecker** [comment] 2023-05-03 14:21
Sorry for taking such a long time, but I believe this issue has been fixed in #14959. Here's how it looks like now:

![image](https://user-images.githubusercontent.com/2256941/235943706-dcbabd37-3ac1-47e3-9e59-02dfcd7b250d.png)

Other bitmap fonts, like Terminus TTF also work much better now (although that one in particular requires you to manually adjust the "cellHeight" - see #14255). This change will ship in 1.18 later this month.

**Closed by lhecker** 2023-05-03 14:21 UTC
Labels: Help Wanted, Area-Fonts, Issue-Bug, Product-Terminal, Priority-3

**Comment by atlka** [comment] 2023-05-04 08:49
I am using Ms Terminal Version 1.16.10261.0 now and I can confirm that 
special chars are displayed correctly with AtlasEngine text renderer in 
Win 10 and Win 11. So problem appears only with default text renderer.

Regards

-- 
Adam Tlałka
System & Network Administration Group
IT Service Center, Gdańsk University of Technology, Poland
