### ISSUE TITLE
The app will crash when dragged to another screen.

### ISSUE THREAD

**Issue by AlQuraian** [microsoft/terminal#3435] opened 2019-11-04 17:06 UTC
# Environment

```none
Windows build number: 
Win32NT             10.0.18362.0 Microsoft Windows NT 10.0.18362.0
Windows Terminal version (if applicable):
0.6.2951.0
```

Feedback Hub link:
https://aka.ms/AA6gvsu

# Steps to reproduce

Open Windows Terminal in one screen then move the window to another screen, the app will crash.

Here's the error log from the Event Viewer:
```
Faulting application name: WindowsTerminal.exe, version: 1.0.1910.22001, time stamp: 0x5daf7ab2
Faulting module name: Windows.UI.Xaml.dll, version: 10.0.18362.449, time stamp: 0xb90db728
Exception code: 0xc000027b
Fault offset: 0x0000000000712ec0
Faulting process id: 0x3f4c
Faulting application start time: 0x01d59330b1915a64
Faulting application path: C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_0.6.2951.0_x64__8wekyb3d8bbwe\WindowsTerminal.exe
Faulting module path: C:\Windows\System32\Windows.UI.Xaml.dll
Report Id: 135f8f3c-f6b8-4100-a6a8-448f12eb7247
Faulting package full name: Microsoft.WindowsTerminal_0.6.2951.0_x64__8wekyb3d8bbwe
Faulting package-relative application ID: App
```

**Comment by DHowett-MSFT** [comment] 2019-11-04 19:19
This seems like a /dupe of #2277 #3303

**Closed by DHowett-MSFT** 2019-11-04 19:19 UTC
Labels: Needs-Tag-Fix, Needs-Triage
