### ISSUE TITLE
Terminal crashes on launch in Windows.UI.Xaml.dll

### ISSUE THREAD

**Issue by jghal** [microsoft/terminal#3381] opened 2019-10-30 22:11 UTC
# Environment

OS: 
```none
Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.18362.0 Microsoft Windows NT 10.0.18362.0
```

Terminal:
```none
> get-appxpackage Microsoft.WindowsTerminal

Name              : Microsoft.WindowsTerminal
Publisher         : CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US
Architecture      : X64
ResourceId        :
Version           : 0.6.2951.0
PackageFullName   : Microsoft.WindowsTerminal_0.6.2951.0_x64__8wekyb3d8bbwe
InstallLocation   : C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_0.6.2951.0_x64__8wekyb3d8bbwe
IsFramework       : False
PackageFamilyName : Microsoft.WindowsTerminal_8wekyb3d8bbwe
PublisherId       : 8wekyb3d8bbwe
IsResourcePackage : False
IsBundle          : False
IsDevelopmentMode : False
NonRemovable      : False
Dependencies      : {Microsoft.VCLibs.140.00_14.0.27323.0_x64__8wekyb3d8bbwe,
                    Microsoft.VCLibs.140.00.UWPDesktop_14.0.27629.0_x64__8wekyb3d8bbwe}
IsPartiallyStaged : False
SignatureKind     : Store
Status            : Ok
```

I suspect I'm seeing the crash mentioned in PR #3027. While I can't recall the specific build number for Terminal that I first installed on this particular machine, it was one of the 0.5 releases. all versions I've tried from that first one to the version listed above by `get-appxpackage` have failed this same way (though I can't faithfully recall if it's been the same Event Viewer entry as reported below). I have used Feedback hub twice, I believe with different versions.

# Steps to reproduce

Click `Windows Terminal (Preview)` in Start menu

# Expected behavior

Application launches

# Actual behavior

Empty Window frame is drawn, then closes. This is in _Event Viewer_ under _Windows Logs > Application_

```none
Faulting application name: WindowsTerminal.exe, version: 1.0.1910.22001, time stamp: 0x5daf7ab2
Faulting module name: Windows.UI.Xaml.dll, version: 10.0.18362.356, time stamp: 0x0825b5b0
Exception code: 0xc000027b
Fault offset: 0x0000000000712cf0
Faulting process id: 0x2b68
Faulting application start time: 0x01d58f6c56566369
Faulting application path: C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_0.6.2951.0_x64__8wekyb3d8bbwe\WindowsTerminal.exe
Faulting module path: C:\Windows\System32\Windows.UI.Xaml.dll
Report Id: 86621d0f-a0dd-4c17-9530-85a0b42ed873
Faulting package full name: Microsoft.WindowsTerminal_0.6.2951.0_x64__8wekyb3d8bbwe
Faulting package-relative application ID: App
```

**Comment by DHowett-MSFT** [comment] 2019-10-30 22:16
Thanks for the report! The crash from #3027 was in TerminalControl.dll, not Windows.UI.Xaml.dll.

Would you mind sharing feedback, and your `profiles.json` (from `%LOCALAPPDATA%\packages\Microsoft.WindowsTerminal_8wekyb3d8bbwe\LocalState\profiles.json`)?

/feedback

**Comment by chayanbaner** [comment] 2019-10-31 10:49
I am facing the same issue....
please check https://aka.ms/AA6fsnn

**Comment by jghal** [comment] 2019-10-31 12:53
ere's the two I filed in Feedback Hub

https://aka.ms/AA6g4mf
https://aka.ms/AA6f8wz

GitHub won't let me attach a json file, so here it is zipped. It should be the default one.

[profiles.zip](https://github.com/microsoft/terminal/files/3793787/profiles.zip)

I've tried using the _App Settings > Repair/Reset_ and also deleting the whole `%LOCALAPPDATA%\Packages\Microsoft.WindowsTerminal_*` directory, with no effect.

**Comment by DHowett-MSFT** [comment] 2019-11-04 20:49
This looks like a /dupe of #2277 (even though this doesn't involve resizing.)

**Closed by DHowett-MSFT** 2019-11-04 20:49 UTC
Labels: Needs-Attention, Needs-Tag-Fix, Needs-Triage
