### ISSUE TITLE
There is a blank at the bottom of the window when the hidden taskbar is enabled.

### ISSUE THREAD

**Issue by 2283572185** [microsoft/terminal#15633] opened 2023-06-30 08:24 UTC
### Windows Terminal version

1.17.11461.0

### Windows build number

10.0.22621.1848

### Other Software

None.

### Steps to reproduce

1.Enable the auto hide taskbar option.
2.Open the Windows Terminal.
3.Maximize the window.

### Expected Behavior

At maximization, the window should cover the entire screen.

### Actual Behavior

<img width="1280" alt="image" src="https://github.com/microsoft/terminal/assets/63223769/6c6044dd-90e7-4354-a9f3-207395045ff1">

There is a blank at the bottom of the window when the hidden taskbar is enabled.

**Comment by lhecker** [comment] 2023-06-30 10:37
I believe this has always been like that on Windows. See here: https://github.com/microsoft/terminal/issues/12959#issuecomment-1337588535
I've updated the title of #12959 to make it easier to find in the future. I'll mark this issue as a duplicate of it, so that we can continue to use it to track this issue, even if we likely cannot properly fix it. /dup #12959

**Closed** 2023-06-30 10:37 UTC
Labels: Issue-Bug, Needs-Triage
