### ISSUE TITLE
Unable to pasteC1 control characters

### ISSUE THREAD

**Issue by NightFurySL2001** [microsoft/terminal#11283] opened 2021-09-20 15:21 UTC
### Windows Terminal version (or Windows build number)

Microsoft Windows [Version 10.0.19043.1237]

### Steps to reproduce

Copy and paste the following text:

```
A9§9
```

Additional steps: run `py` and then copy paste the following:

```
"A9§9".encode("latin1").decode("gb18030")
```

There should be one control character (U+0081) between `A` and `9`.

### Expected Behavior

A missing character (U+0081) should appear in between `æ` and `9` which appeared in Command Prompt and Windows PowerShell. Running the Python command should output `A・` (A followed by U+30FB).

![image](https://user-images.githubusercontent.com/33471049/134027920-fdf3570b-b1ad-4048-b0c9-fd3c0f221408.png)

![image](https://user-images.githubusercontent.com/33471049/134028030-1476ff45-89a1-4434-9372-04115b153ac5.png)

### Actual Behavior

The C1 control character did not get pasted and resulted in error.

![image](https://user-images.githubusercontent.com/33471049/134028250-827b939e-1c21-4398-8f6c-f5d52d545780.png)

**Comment by zadjii-msft** [comment] 2021-09-20 15:24
What happens if you run `chcp 65001` before running python?

**Comment by NightFurySL2001** [comment] 2021-09-20 15:59
I'm on 65001. The problem stems from pasting the string into Terminal, not with Python.

**Comment by DHowett** [comment] 2021-09-20 18:12
So, Terminal operates under the assumption that the text on the clipboard is well-formed UTF-16 and strips all C0 and C1 controls from it, by design.

What compelling use case do you have for pasting `U+0081` that wouldn't be resolved by including `\x81` or `\u0081` in the text from which you're copying? It is arguably more correct and safer for transit.

**Comment by NightFurySL2001** [comment] 2021-09-27 15:45
I copied the text from a program that was spitting error code and messing around with the text. I am not sure if it counts as a reasonable use case but this behaviour is significantly different from Command Prompt and Windows Powershell.

**Comment by oniony** [comment] 2021-11-12 23:10
I hit this same problem. I had a telnet session with Redis, went to paste a compound key that is separated with the Unit Separator character (`0x1f`) and the control character gets stripped from my key.

If I do the same thing from `cmd.exe` it pastes just fine.

**Comment by carlos-zamora** [comment] 2022-12-14 22:39
Hi @NightFurySL2001. We talked about this as a team today. As @DHowett mentioned earlier, we strip C0 and C1 control sequences be design for security reasons. Though Command Prompt and Windows Powershell (via ConHost) still support this scenario, we've decided that we do not want to support this feature in Windows Terminal moving forward.

Closing as by design. Thanks for your patience.

**Closed by carlos-zamora** 2022-12-14 22:39 UTC
Labels: Needs-Triage, Needs-Attention, Needs-Tag-Fix
