### ISSUE TITLE
Unable to start the terminal from the start screen

### ISSUE THREAD

**Issue by zhikeye** [microsoft/terminal#15393] opened 2023-05-21 02:41 UTC
### Windows Terminal version

1.16.10261.0

### Windows build number

10.0.19044.2965

### Other Software

[Window Title]
C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_1.16.10261.0_x64__8wekyb3d8bbwe\WindowsTerminal.exe

[Content]
C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_1.16.10261.0_x64__8wekyb3d8bbwe\WindowsTerminal.exe

参数错误。

[确定]

### Steps to reproduce

从开始屏幕点击启动没反应；
从Store里点击打开，就提示参数错误。
已经卸载、重新安装了好几次了。

### Actual Behavior

[Window Title]
C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_1.16.10261.0_x64__8wekyb3d8bbwe\WindowsTerminal.exe

[Content]
C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_1.16.10261.0_x64__8wekyb3d8bbwe\WindowsTerminal.exe

参数错误。

[确定]

**Comment by o-sdn-o** [comment] 2023-05-21 13:10
Possible translation:

Unable to start the terminal from the start screen. [parameter error] message when starting from the Store.

### Windows Terminal version
1.16.10261.0

### Windows build number
10.0.19044.2965

### Steps to reproduce

Tapping Start from the start screen does not respond;
Click to open from the Store, it will prompt the parameter error.
Uninstalled and reinstalled several times.

### Actual Behavior

Message:
```
  Parameter error
       [OK]
```

**Comment by lhecker** [comment] 2023-05-22 11:14
This seems to be the same as #12986. It contains reference to more related issues and also seems to contain a potential solution. If it's due to bad permissions in the `WindowsApps` I'd suggest reinstalling Windows. It's not something that can be trivially fixed.

**Comment by zhikeye** [comment] 2023-05-23 07:21
> If it's due to bad permissions in the `WindowsApps` I'd suggest reinstalling Windows. It's not something that can be trivially fixed.

Reinstall Windows will be more difficult, can only see if there is a way to solve, or replace other terminal tools.
I tried the fix and reset in the app Settings, but nothing worked.

**Comment by lhecker** [comment] 2023-06-07 21:54
Have you found anything that would fix your issue in the pile of issues linked here? https://github.com/microsoft/terminal/issues/12986#issuecomment-1110859507

I don't think we can resolve this issue unfortunately, as evident by all the related issue having been closed as well. It appears to be a known platform bug.

**Closed** 2023-07-17 18:47 UTC
Labels: Issue-Bug, Needs-Author-Feedback, Needs-Triage, No-Recent-Activity
