### ISSUE TITLE
Text Wrapping with ConPTY 

### ISSUE THREAD

**Issue by davidhewitt** [microsoft/terminal#405] opened 2019-04-02 21:06 UTC
It seems to me that output is line-wrapped by conhost before being sent through the ConPTY stdout pipe. This makes sense, though it has the unfortunate downside that in [Alacritty](https://github.com/jwilm/alacritty) we can't do the line-wrapping ourselves.

This wouldn't matter that much, but when selecting and copying text in Alacritty which has been line-wrapped by conhost, Alacritty isn't aware that the text was originally a single line and inserts a newline into the content placed on the clipboard.

Is it possible to disable the line wrapping by conhost?

(Perhaps this would be something that would naturally be in the "passthrough" mode I've seen mentioned elsewhere in this issue tracker?)

**Comment by zadjii-msft** [comment] 2019-04-03 15:00
I'm sure there's another issue tracking this lying around somewhere...

There was actually a prototype of doing this for a few insider's builds but that caused some other regressions in behavior late in RS5. (For internal reference, see task 16485846 and bug 18123777).

This is definitely something we need to figure out how to get right.

**Comment by davidhewitt** [comment] 2019-04-04 07:58
Thanks for the notes!

I did have a search for an existing issue before opening though didn't spot one. Please do close this issue if a duplicate turns up!

**Comment by jzabroski** [comment] 2019-04-16 18:40
Interesting.  This feature request dovetails nicely with my recent remarks on MSBuild supporting colors but intermediary programs like PowerShell blocking colors: https://github.com/Microsoft/msbuild/issues/4299

I am still wrapping my head around all of this, so apologies to those who don't see the same connection I see, which is that API consumers don't control output, API providers do.  I think this is a fundamental problem.

**Comment by Tyriar** [comment] 2019-05-31 02:06
This is one of the major issues VS Code has with ConPTY as we have to guess which lines wrap (based on a [naive heuristic](https://github.com/xtermjs/xterm.js/blob/32d6613811e403b3693d004b86c8a664553eaa59/src/WindowsMode.ts#L11-L29)) to try to avoid issues like https://github.com/microsoft/vscode/issues/43664

**Comment by ExE-Boss** [comment] 2019-05-31 02:19
Well, that heuristic doesn’t work well at&nbsp;all with [a&nbsp;PowerLine&nbsp;prompt](https://github.com/Jaykul/PowerLine/blob/master/README.md) that&nbsp;has [right&#x2011;aligned blocks](https://github.com/Jaykul/PowerLine/blob/master/README.md#right-aligned-blocks).

**Comment by Tyriar** [comment] 2019-05-31 02:22
@ExE-Boss its primary uses are link detection and error detection so that doesn't matter too much. Problems arise for example when errors have unfortunately placed spaces at the end of a wrapped line, leading to flaky detection.

**Comment by Tyriar** [comment] 2019-05-31 02:23
winpty acts in the same way as conpty, the workaround is for both.

**Comment by wolf99** [comment] 2019-10-01 16:34
Per https://github.com/microsoft/vscode/issues/81328, this is breaking problem matchers in VS Code in the case where the user has not already opened the terminal.

**Comment by jzabroski** [comment] 2019-10-01 16:46
API Consumers need to control output formatting, not API Producers.

**Comment by zadjii-msft** [comment] 2019-10-01 16:54
Okay, we're not disagreeing that this should be fixed. However, no one on the team has had the time to get to it quite yet. If a particularly passionate community member is interested in contributing, we'd be happy to review a PR.

**Comment by Biswa96** [comment] 2019-10-01 17:10
Which source file or project or function handle the text wrapping in normal CMD + ConHost combo?

**Comment by zadjii-msft** [comment] 2019-10-01 19:36
@Biswa96 this is probably less about the wrapping within conhost itself, but more about how ConPTY renders wrapped text. I'd probably take a look at `XtermEngine::PaintBufferLine`, which is where conpty draws a particular run of text. Currently, whenever we reach the end of a line, we're always going to emit a `\n` to move the cursor to the next line. We probably shouldn't, because that's causing hard line breaks. 

In my original prototype, I believe I added a flag `wasWrapped`, which the Renderer passes to the various `IRenderEngine`s, including the `VtEngine`s. What we'd need to do is make sure that when a run of text is painted that was wrapped, we don't move the cursor (with `_MoveCursor`) immediately following that. Instead, we should just _assume_ the subsequent text we need to render was on the next line.

**Closed** 2020-02-27 16:40 UTC
Labels: Area-Interaction, Area-Interop, In-PR, Issue-Feature, Priority-1, Product-Conpty, Work-Item, v1-Scrubbed

**Comment by Tyriar** [comment] 2020-02-27 17:51
@zadjii-msft in what Windows version should this be expected? I think I'll need to disable the special compatibility mode in VS Code that guesses wrapped lines based on the build number.

**Comment by DHowett-MSFT** [comment] 2020-02-27 18:03
@Tyriar the version what comes after 19041.

**Comment by davidhewitt** [comment] 2020-02-27 18:18
Thanks very much! Thrilled to see this. I guess until stable release I'll also be able to enjoy it on insiders ;)

**Comment by andrewvaughanj** [comment] 2021-04-21 20:33
@davidhewitt in case you're interested, I implemented the xterm.js (== VS Code) "[naïve heuristic](https://github.com/xtermjs/xterm.js/blob/32d6613811e403b3693d004b86c8a664553eaa59/src/WindowsMode.ts#L11-L29)" in Alacritty here:

- [https://github.com/andrewvaughanj/alacritty/commit/dc24686f5b9f327b8beb5e5cb7beeac759a8660a](https://github.com/andrewvaughanj/alacritty/commit/dc24686f5b9f327b8beb5e5cb7beeac759a8660a)
- [https://github.com/andrewvaughanj/alacritty/tree/windows_copy_long_lines](https://github.com/andrewvaughanj/alacritty/tree/windows_copy_long_lines)

This change resolves the issue with copying (e.g.,) `~/.ssh/id_rsa.pub` but also preserves the newlines when copying files that do have genuine `\n` (e.g., `cat ~/.zshrc`).

**Comment by wesley800** [comment] 2022-11-25 23:53
@DHowett-MSFT Hi, I wonder if the fix (#4415) applies to conhost.exe on Windows newer than 19041? I've tested it on 19044 with ConPty APIs, and got `\r\n`s between segments of wrapped lines (output by sending `echo LONG...LINE\r` to powershell). I've placed my test code snippet at https://github.com/wesley800/rust-conpty-test .

I've briefly checked the code of #4415 and it seems that all changes relates to the WindowsTerminal part, rather than the conhost part. But I'm not familar with the whole architecture of the source tree. So if it does changed the behaviour of conhost, what sould I do if I want to decide whether a line is wrapped, or just happens to holds a line with same width to the window and a following hard break?

Actually this is a call from https://github.com/alacritty/alacritty/issues/2093 . I also tested with latest alacritty on 19044 and found it still gives breaked lines when copying content from the window, such as ssh public keys.

**Comment by aytey** [comment] 2022-11-27 18:32
@wesley800:

> Update: this seems to be already fix on Win11. Output files are attached to https://github.com/wesley800/rust-conpty-test/tree/master/output .
>

How did you perform this test? Just using a latest Alacritty build on stock Windows 11? What version of Windows 11?

**Comment by wesley800** [comment] 2022-11-27 18:35
> How did you perform this test? Just using a latest Alacritty build on stock Windows 11? What version of Windows 11?

I don't know, probably the latest one. I don't have access to that machine in face. I've confirmed that both latest Alacritty and [rust-conpty-test](https://github.com/wesley800/rust-conpty-test/tree/master/output) shows no CR or LF at line wrapping points.

**Comment by wesley800** [comment] 2022-12-04 08:52
@zadjii-msft In case no one is still watching this issue...

**Comment by wesley800** [comment] 2022-12-07 13:25
Thank you for your time and detailed replies to my each question and hope I didn't break your vacation much.

Actually I ran the test on Win10 LTSC 2022 which is 19044 by `winver` but don't know if the SKU matters.

Also I might be wrong in the expectation of #4415, which seems to be mainly focused on rendering (as you've stated). From my perspective, changes are mostly among adding `lineWrapped` flag into the state storage of ConPty, but nowhere relating to dismiss the "fake" line breaks at line wrapping points when ConPty writes to it's output pipe. I assume that's because I have not complete insight of the whole repo though.

**Comment by zadjii-msft** [comment] 2022-12-07 15:58
> hope I didn't break your vacation much

Nah it's fine, I'm just still slow coming back off paternity and only working like, half time. It's generally the holidays, so things are just slow here 😅 sorry for any delays!

<hr>


You might have something here. We should probably take a look through the history here. Why is `performedSoftWrap` never used? #5181 might be relevant here.

<hr>

That also being said - it looks like on windows 11 the test works fine? Perhaps the fixes I'm thinking of didn't actually land till 22000. This might just be another point in favor of having a proper ConPTY nuget package, that folks can use to consume the updated ConPTY version (regardless of OS version).

**Comment by std-move** [comment] 2023-07-14 18:53
@zadjii-msft Any chance this could get fixed in Win10 19044/19045? The regular editions are supported at least till 2025-10-14, with IoT Enterprise (for which volume licencing is newly available) supported until 2032-01-13.

It seems like a bug that should be fixed as part of a cumulative update.

**Comment by DHowett** [comment] 2023-07-14 23:23
> It seems like a bug that should be fixed as part of a cumulative update.

I agree with you! Unfortunately, the Windows organization doesn't necessarily agree. Changes like this -- especially ones that are in vanishingly rare cases that come with a high likelihood of destabilizing a working product -- are very difficult to get into a servicing update without a strong "business justiciation."

The way we're tackling getting ConPTY bug fixes out to people on a quicker cadence than Windows releases is over in #15065: a NuGet package for folks to depend upon. :smile:

**Comment by Walms** [comment] 2024-06-20 02:49
> > It seems like a bug that should be fixed as part of a cumulative update.
> 
> I agree with you! Unfortunately, the Windows organization doesn't necessarily agree. Changes like this -- especially ones that are in vanishingly rare cases that come with a high likelihood of destabilizing a working product -- are very difficult to get into a servicing update without a strong "business justiciation."
> 
> The way we're tackling getting ConPTY bug fixes out to people on a quicker cadence than Windows releases is over in #15065: a NuGet package for folks to depend upon. 😄

I'm hitting problems using the Alacritty terminal. https://github.com/alacritty/alacritty/issues/4993

Is there anyway I can get the latest version to make that bug go away?

**Comment by j4james** [comment] 2024-06-20 09:37
> Is there anyway I can get the latest version to make that bug go away?

There's an [invisible entry](https://github.com/alacritty/alacritty/compare/d8761f286742d61376b4ae0212aabb9bd51f5c77..472db811262384fbed7860e16e78e3b9fa1d8cf8) in the Alacritty FAQ that explains what you need to do.

And if you search the Alacritty repo for [conpty.dll openconsole.exe](https://github.com/search?q=repo%3Aalacritty%2Falacritty+conpty.dll+openconsole.exe&type=issues) you'll find several comments from users explaining how they've got it to work. Here is one recent example: https://github.com/alacritty/alacritty/issues/6704#issuecomment-2145945778
