### ISSUE TITLE
cannot open source file "winrt/Microsoft.Terminal.Settings.h" in Terminal.cpp

### ISSUE THREAD

**Issue by RefundGarbage** [microsoft/Terminal#613] opened 2019-05-09 07:11 UTC
Tried install vcix packages,
tried to reclone everything and start from the start
tried everything, but all of them do not work

Please tell me how to fix this problem. I really want to try Windows Terminal.
Thanks

**Comment by dybb8999** [comment] 2019-05-09 07:17
Whether to restart Windows after installing Microsoft.Windows.CppWinRT.vsix？
你在安装完Microsoft.Windows.CppWinRT.vsix后，是否重启了Windows？

**Comment by RefundGarbage** [comment] 2019-05-09 07:24
@dybb8999 of course, it still shows the same error though

**Comment by zadjii-msft** [comment] 2019-05-09 13:52
Please search before opening a new issue. This is a dupe of #520.

> There are some mysterious issues with build order and that project, and there always have been.
> If you manually build that project (TerminalSettings) first, then the rest of the solution will build fine.

**Closed by zadjii-msft** 2019-05-09 13:52 UTC
