### ISSUE TITLE
Color of buttons of GUI are buggy

### ISSUE THREAD

**Issue by abbychau** [microsoft/terminal#13382] opened 2022-06-26 12:16 UTC
### Windows Terminal version

1.13

### Other Software

Windows 10

### Steps to reproduce

Open Windows terminal

### Expected Behavior

Color of buttons are displayed correctly

### Actual Behavior

Buttons and text on buttons are barely visible

![image](https://user-images.githubusercontent.com/350283/175813616-495e91ba-771d-459e-9aca-e9fbb2fe2cd7.png)
![image](https://user-images.githubusercontent.com/350283/175813632-1920f764-a3aa-490f-8c1e-efffcbe0b956.png)
![image](https://user-images.githubusercontent.com/350283/175813672-ec9ecdbc-71b4-4eab-a848-4a953b30ee41.png)

**Comment by zadjii-msft** [comment] 2022-07-05 09:58
Wow the XAML looks super messed up here. Have you done anything to modify the XAML resources on your system at all/? Does this persist if you change the Terminal to use Dark theme instead of Light (or "Use Windows theme", which is the default)? Does this repro for any other apps on your system, like maybe PowerToys?

I've never seen anything like this before, so I have little to no idea what might have caused that.

**Comment by abbychau** [comment] 2022-07-09 05:36
> Have you done anything to modify the XAML resources on your system at all/? 
I don't know. How can I check it?

> Does this persist if you change the Terminal to use Dark theme instead of Light (or "Use Windows theme", which is the default)? 
Yes. It persists in Dark, Light, or default windows themes.

Does this repro for any other apps on your system, like maybe PowerToys?

![image](https://user-images.githubusercontent.com/350283/178093124-8fa7e15f-5742-4cb8-b80e-f958013122e9.png)

it looks ok in powertoys, but I remember a similar flaw in powertoys before. they seem fixed it in new versions.

**Comment by abbychau** [comment] 2022-07-12 03:25
I was setting dark for windows mode and light for application mode.
If I set them both to dark modes, the color shows on the setting page

![image](https://user-images.githubusercontent.com/350283/178400928-df9152cf-09bf-443f-9095-e3ffc087e419.png)

but the confirm button on the bottom right-hand corner is still messed up.

also, there are unexpected shadows when I hover on the 3 buttons on the top.
https://youtu.be/d9xyPo1pcis

**Comment by cniggeler** [comment] 2022-08-10 00:31
I cannot replicate the issue in Windows 11 Pro. However, I can confirm it occurs in Windows 10:

If I match the Windows mode and default application mode to dark, the colors show up in the buttons. However, the "Close all" button on the "Do you want to close all tabs dialog" remains unreadable. Light/light is the worst, and for light/dark, the "Close all" button shows up, but the Save button on any Terminal dialog becomes unreadable.

**Comment by carlos-zamora** [comment] 2023-03-29 21:34
Thanks for confirming that this is fixed in Windows 11. It looks like this is a Windows 10 issue that is external to our code. I don't think there is anything we can do on our side to fix it. So, unfortunately, we're going to close this one as resolution-external.

**Closed by carlos-zamora** 2023-03-29 21:34 UTC
Labels: Issue-Bug, Needs-Triage, Needs-Attention, Needs-Tag-Fix

**Comment by zadjii-msft** [comment] 2023-05-30 18:13
Huh, this looks a lot like https://github.com/microsoft/microsoft-ui-xaml/issues/5670. That never got a resolution, but just x-linking for reference.

**Comment by lexthedev** [comment] 2023-09-07 20:34
> Thanks for confirming that this is fixed in Windows 11. It looks like this is a Windows 10 issue that is external to our code. I don't think there is anything we can do on our side to fix it. So, unfortunately, we're going to close this one as resolution-external.

Win 11 pro has this issue - [transparent buttons](https://answers.microsoft.com/en-us/windows/forum/windows_11-performance/strange-buttons-colors-behaviour-pale-or/b85bf0da-e34f-4331-8f2f-0628892e82dc)

**Comment by fschmied** [comment] 2023-11-28 09:13
@carlos-zamora I, too, am seeing the same issue on Windows 10 22H2 (19045.3693) - I cannot read the text on any of the buttons displayed by Windows Terminal. I haven't seen this issue in any other application.

![image](https://github.com/microsoft/terminal/assets/139564/9caed8bd-5b91-46f5-8666-39ca6fb25182)

Any idea what I can do?
