### ISSUE TITLE
Changing desktop wallpaper doesn't change Terminal background

### ISSUE THREAD

**Issue by helpimnotdrowning** [microsoft/terminal#11677] opened 2021-11-03 05:00 UTC
### Windows Terminal version (or Windows build number)

1.11.2921.0

### Other Software

Noticed problem with my [helpimnotdrowning/wallpaper_changer.py](https://github.com/helpimnotdrowning/random-py3/blob/master/wallpaper_changer.py), but bug works when changing wallpaper manually.

### Steps to reproduce

1. Set Terminal background image to use desktop wallpaper, apply
3. Go to a tab that isn't the settings pane
4. Change Windows wallpaper

### Expected Behavior

I expected the Terminal background to change with the desktop wallpaper.

### Actual Behavior

Background stayed the same while the wallpaper changed.

**Comment by zadjii-msft** [comment] 2021-11-03 10:38
You know, this is similar enough that I'm gonna call this a /duplicate of #8231

**Closed by zadjii-msft** 2021-11-03 10:38 UTC
Labels: Needs-Triage, Needs-Tag-Fix
