### ISSUE TITLE
Page up/Page down scrolling in WSL shell doesn't work

### ISSUE THREAD

**Issue by Xjs** [microsoft/terminal#237] opened 2018-08-20 08:02 UTC
The page up/page down keys don't scroll in the WSL console (installed Debian from Windows store), neither do any combinations with Ctrl, Shift, etc. and those keys. They do scroll in PowerShell, so maybe the shell intercepts them? 

(In bash, PgUp does nothing and PgDn outputs a `~`; in zsh, the PgUp/PgDn keys cycle through the recent commands)

Build: Microsoft Windows [Version 10.0.17134.228]

**Comment by zadjii-msft** [comment] 2018-08-20 16:02
That definitely sounds like something that powershell implemented themselves.

It's already on the backlog to add support for keyboard shortcuts for scrolling :)

**Comment by adamwadesmith** [comment] 2018-12-17 20:55
A test case: For Ubuntu 18.4 in Vi readline mode, Shift+PageUp and Shift+PageDown do not currently work on Windows version 17763.194. Those shortcuts work on Ubuntu 18.4 in a VM in gnome-terminal.

**Comment by tovine** [comment] 2019-01-02 09:53
Please consider upping the priority of this one a bit - I'm sure it's a simple task for talented engineers as yourselves, and it's such a dealbreaker that I'll have to stick with Cygwin (or a VM) until it's implemented.

It's nice to have a native Debian terminal and all, but it's too painful to use if I can't effortlessly scroll the terminal output with keyboard shortcuts...

**Comment by arobertn** [comment] 2019-01-18 12:48
I too find this a small thing that makes a big difference, and was led off on a goose chase through various third-party Windows terminal window apps to try to fix it.  I also notice many places where people are asking about this (Stackoverflow, the WSL repo, etc.) so the votes you get here are likely an underestimate of how much this feature would be appreciated by users.

**Comment by rp-pedraza** [comment] 2019-03-02 17:40
It would be nice if this enhancement would be readily adaptable to third-party terminal emulators like ConEmu as well.

**Comment by thisisnotmyrealname** [comment] 2019-03-03 03:08
I also have this problem and would like it fixed.

Having a terminal app to use with WSL that is functional sure would be nice.

**Comment by tukusejssirs** [comment] 2019-03-18 17:38
I hate bumping, however this is a must for many Linux users who for many different reasons need to use a Windows machine. Do make it real in the next release, please!

**Comment by thefreereed** [comment] 2019-04-01 09:09
page up/down pretty essential for anyone who wants to use the command line. please fix!

**Comment by miniksa** [comment] 2019-05-18 04:24
@zadjii-msft, is this superceded by the bindable keys and the paging PRs I saw go by recently? If so, close. Resolution-Won't Fix (in regards to Product-Conhost).

**Comment by zadjii-msft** [comment] 2019-05-20 13:53
Yea, this is something that'll be solved in Windows Terminal.

**Closed by zadjii-msft** 2019-05-20 13:53 UTC
Labels: Area-Interaction, Issue-Feature, Product-Conhost

**Comment by LordWolfenstein** [comment] 2019-09-13 12:26
Putty have keyboard scrolling and it almost made me not switch to WSL.

**Comment by zadjii-msft** [comment] 2019-09-13 15:18
@LordWolfenstein The new Windows Terminal has support for scrolling with the keyboard as well 😉 You can set keybindings for scrolling a single line at a time, a page at a time, and you can easily change which keys these actions are bound to. I'd recommend giving it a try!

**Comment by jeff-zone** [comment] 2020-05-06 18:22
This issue is still happening.

**Comment by gmckeown** [comment] 2020-05-20 17:26
@jeff-zone Add the following to your Windows Terminal config under the "keybindings" section:

```
{ "command": "scrollUpPage", "keys": "shift+pageup" },
{ "command": "scrollDownPage", "keys": "shift+pagedown" },
```

**Comment by bpesics** [comment] 2020-08-04 14:23
but why on earth is this not a default setting?

**Comment by zadjii-msft** [comment] 2020-08-04 14:51
This _is_ a default setting:

https://github.com/microsoft/terminal/blob/d29be591a8ffd74777b3d3d0e417434981ceee58/src/cascadia/TerminalApp/defaults.json#L334-L338

**Comment by chrispy-snps** [comment] 2020-12-24 16:49
I installed Windows Terminal in early December 2020. There were no scrollback settings in the default .json file; I had to copy them from this discussion.

**Comment by DrChr** [comment] 2020-12-30 10:09
As @chrispy-snps, I had to modify my settings.json.  I am using versauib 1.4.3243.0. To help others, this is what I added:

	// - Add keys to scroll, defaults assume e.g. shift+ctrl+pgup
        { "command": "scrollUpPage", "keys": "shift+pgup" },
        { "command": "scrollDownPage", "keys": "shift+pgdn" }

I mention this as the example by @gmckeown uses e.g. "pageup" (instead of "pgup"), which didn't seem to work for me.

Note: @zadjii-msft  is correct that e.g. ctrl+shift+down is in defaults.json. However, when testing in PowerShell it at first didn't seem to work. I think I was fooled by PowerShell having small scrollback buffer or something.
Finally, I much prefer shift+pgup rather than shift+ctrl+pgup as the former is what's used by e.g. the standard terminal in Ubuntu etc.

**Comment by gmckeown** [comment] 2020-12-30 11:33
@DrChr Odd that "pageup" doesn't work for you. The official Microsoft modifier key list has both forms, and both work fine for me:

https://docs.microsoft.com/en-us/windows/terminal/customize-settings/actions#accepted-modifiers-and-keys

🤷‍♂️

**Comment by Kein** [comment] 2021-01-03 13:28
That's funny, took me a second to figure out why it wasnt just plain PgUP/PgDown keys for scrolling but with extra modifiers. Apparently some terminal providers (default Command Line) would cycle between history of commands on PgUP/PgDown. The joke is that despite putting these behind modifiers, Cmd does not give a single carb and still cycles through command history, it just registers that Pg* key was pressed and does its own thing.

**Comment by DrChr** [comment] 2021-01-04 11:27
@gmckeown  I was unable to reproduce the "pageup" issue, so I've updated my comment above accordingly.

**Comment by mailinglists35** [comment] 2021-10-01 12:41
shift-page up/down does not work for me. I mean the defaults. have not tried customizing.

Windows Terminal Preview
Version: 1.11.2421.0

Microsoft Windows [Version 10.0.19042.1237]

**Comment by mailinglists35** [comment] 2023-02-01 20:58
on a new installation where I did not have access to my settings.json I've had a hard time inserting the keybindings suggested in comment https://github.com/microsoft/terminal/issues/237#issuecomment-631615841

if anyone else seeks this via search engines, insert the following at the end, between the last `]` and the last `}` (the defaults end with a `"schemes"` section)

````
,
    "keybindings":
    [
        { "command": "scrollUpPage", "keys": "shift+pageup" },
        { "command": "scrollDownPage", "keys": "shift+pagedown" }
    ]
````

so the last lines would now looks like this:

```
    ],
    "keybindings":
    [
        { "command": "scrollUpPage", "keys": "shift+pageup" },
        { "command": "scrollDownPage", "keys": "shift+pagedown" }
    ]
}
````
