### ISSUE TITLE
The window stands out when maximized

### ISSUE THREAD

**Issue by Erableto** [microsoft/terminal#3264] opened 2019-10-20 13:07 UTC
# Environment

```none
Windows build number: Microsoft Windows [Versión 10.0.18999.1]
Windows Terminal version (if applicable): 0.5.2762.0

Any other software?
No
```

# Steps to reproduce

Just maximize Terminal.

# Expected behavior

The window shouldn't stand out.

# Actual behavior

The window stands out.

![1](https://user-images.githubusercontent.com/22452997/67159918-3fcce480-f34b-11e9-88fd-9a74171f5e0c.png)

![2](https://user-images.githubusercontent.com/22452997/67159920-422f3e80-f34b-11e9-9cc6-816bf5e5ad62.png)

![3](https://user-images.githubusercontent.com/22452997/67162039-b4f6e480-f360-11e9-99f4-5dea3f0ed90f.png)

**Comment by DHowett-MSFT** [comment] 2019-10-21 19:40
This is a /dupe of #2268. Thanks!

**Closed by DHowett-MSFT** 2019-10-21 19:40 UTC
Labels: Needs-Tag-Fix, Needs-Triage
