### ISSUE TITLE
PowerShell colors weird after update to 1.22.2408.23002 (preview)

### ISSUE THREAD

**Issue by vefatica** [microsoft/terminal#17854] opened 2024-09-03 19:46 UTC
I have changed nothing here except for installing the latest WT builds, WindowsTerminal 1.21.2408.23001 and WindowsTerminal 1.22.2408.23002 (preview).  The following is new behavior.  It only happens in the 1.22 preview (not in 1.21 or in previous releases of any kind).

Whenever text on a command line in progress is erased (backspace, Esc, when scrolling through the history) the background color is replaced by black.

Before pressing Esc:

![image](https://github.com/user-attachments/assets/bf8295af-a287-4058-83df-8217de26e2e5)

After pressing Esc:

![image](https://github.com/user-attachments/assets/e16f2518-7b3c-4700-9dc5-c3427e549abc)

**Comment by zadjii-msft** [comment] 2024-09-03 21:27
Which version of PowerShell are you using? 
How do you have your prompt customized/?

**Comment by vefatica** [comment] 2024-09-03 21:33
It's the built-in one called "PowerShell" (not PWSH); I'm on Windows 10.

In the user environment I have `prompt=$e]9;9;"$P"$e\$e[91m$p$g$s$e[0m`

**Comment by lhecker** [comment] 2024-09-04 01:17
This is an intentional regression we introduced to make many other major improvements possible, including sixels.

It happens because Windows 10 ships with PSReadLine that contains a bug where the attributes are incorrect. The issue is fixed in Windows 11.

You can fix the issue by running `Install-Module -Name PowerShellGet -Force` and restarting all of your PowerShell tabs.

(I'll update this comment tomorrow with more details / links after catching some sleep.)

**Comment by vefatica** [comment] 2024-09-04 01:26
Thanks for the info.  It's no big deal to me.  I'm no fan of PowerShell (in any form) and I do have an up-to-date (?) PWSH which does not exhibit the behavior in question.  If I hide WT's "PowerShell" profile, I won't be tempted to run the old one.

**Comment by lhecker** [comment] 2024-09-04 13:44
I've updated my comment with relevant links. I'll close this issue for now since I broke it intentionally (see #17666).

(Side note: It can theoretically be fixed by adding a new `InjectionType` but I don't think we should, because these injections go against the fundamental concept of VT passthrough.)

**Closed by lhecker** 2024-09-04 13:44 UTC
Labels: Needs-Triage, Needs-Attention, Needs-Tag-Fix
