### ISSUE TITLE
Experimental Shaders also render on Tabs that aren't active / Minimized Windows

### ISSUE THREAD

**Issue by TsengSR** [microsoft/terminal#15440] opened 2023-05-25 16:49 UTC
### Windows Terminal version

1.18.1421.0

### Windows build number

10.0.22621.0

### Other Software

crt.hlsl shader from https://github.com/Hammster/windows-terminal-shaders

### Steps to reproduce

Set crt (or any other shader) shader as experimental

```
    "profiles": 
    {
        "defaults": 
        {
            "experimental.pixelShaderPath": "C:\\Projekte\\repos\\windows-terminal-shaders\\crt.hlsl",
            "font": 
            {
                "face": "MesloLGS NF"
            }
        },
        "list": 
```

and open multiple tabs. With 7 tabs I have constant GPU usage of 20%. With 20-30 its close to 100 %, even when minimized.

### Expected Behavior

Tabs that are not actively selected or visible (or Terminal windows which are minimized) shouldn't render shaders all the time. 

### Actual Behavior

With each new tab GPU CPU grows up, even when minimized or not active. 

![image](https://github.com/microsoft/terminal/assets/10427430/b583107c-81ba-48a2-a8b4-0df1a0f501c8)

With 20+ tabs
![image](https://github.com/microsoft/terminal/assets/10427430/2b4dd7eb-f7b2-4787-8199-dfc697565c02)

**Comment by zadjii-msft** [comment] 2023-05-25 17:11
I'm gonna reckon this should be marked as a /duplicate of #1989. Not only should we stop rendering the shaders, we should just do _nothing at all_ for hidden tabs

**Closed** 2023-05-25 17:11 UTC
Labels: Issue-Bug, Needs-Triage
