### ISSUE TITLE
Windows Terminal Preview Version: 1.0.1402.0 - Azure Cloud Shell won't open

### ISSUE THREAD

**Issue by devopsmyth** [microsoft/terminal#6109] opened 2020-05-21 20:31 UTC
# Environment

```none
Windows build number:  Win32NT 10.0.18362.0 Microsoft Windows NT 10.0.18362.0

Windows Terminal version (if applicable): Preview Version: 1.0.1402.0

Any other software? None
```

# Steps to reproduce

1. Open Windows Terminal
2. Select drop-down arrow to choose shell
3. select Azure Cloud Shell

# Expected behavior

Expect Azure Cloud Shell to open without error or hindrance

# Actual behavior

![image](https://user-images.githubusercontent.com/8546107/82603181-32e1cf00-9b80-11ea-9c5b-4b94dd387089.png)

Errors out and is unusable

``` IXMLHttpRequest2Callback::OnError: -2146697211: The system cannot locate the resource specified.

[process exited with code 1]
```

**Comment by x509cert** [comment] 2020-05-30 02:33
FWIW, I cannot get into an Azure Shell, but I have a different error. I have tried setting up a new connection, and tried two existing connections, but I always get:

VERBOSE: Authenticating to Azure ...
WARNING: Azure Authentication failed.

**Comment by x509cert** [comment] 2020-06-02 22:58
![image](https://user-images.githubusercontent.com/1674552/83577754-a8dc2380-a4fa-11ea-9245-88218bc921e2.png)

**Comment by devopsmyth** [comment] 2020-06-03 21:49
My issue seems to have resolved itself. I managed to setup Azure Cloud Shell in Windows Terminal, non-preview edition, and it's now working the Preview edition as well. Sorry I can't provide more specifics.

**Comment by DHowett** [comment] 2020-06-03 22:21
Thanks for following up! At its core, this is a /dupe of #2371 :smile:

**Closed by DHowett** 2020-06-03 22:21 UTC
Labels: Area-AzureShell, Issue-Bug, Priority-2, Product-Terminal
