### ISSUE TITLE
Alt + Mouse Click to move cursor to mouse position - Same functionality already in VSCode integrated Terminal

### ISSUE THREAD

**Issue by con-dog** [microsoft/terminal#12132] opened 2022-01-11 00:44 UTC
# Description of the new feature/enhancement
For speedy programming and UI friendliness, implement cursor movement based off mouse position + click

Problem: The cursor can currently only move via arrow keys. This can slow productivity and make navigating TUI's slower and more limiting.

This feature could open up new opportunities for Terminal-User-Interface or Terminal only applications such as RICH for Python, where users can use this feature to click options fast, rather than using arrow keys. I myself would leverage this feature to build my ideal Click and Place Electronic Circuit App for Bash

# Proposed technical implementation details (optional)

Implement the exact same ALT + Mouse Click functionality that already exists in Visual Studio Code, and on ALT + mouse movement turn the mouse into a crosshair

**Comment by 237dmitry** [comment] 2022-01-11 07:51
Wouldn't this contradict the selection of a block of text? `Alt+mouse`

**Comment by zadjii-msft** [comment] 2022-01-11 12:22
This sounds like a /dupe of #8573 - let's keep all the discussion in one place (as best as possible)

FWIW I couldn't get alt+click to work in vscode at all, not in `bash`, nor `cmd` or `pwsh`, even with 
![image](https://user-images.githubusercontent.com/18356694/148941786-06134745-83aa-473a-be92-026399506bcc.png)

**Closed by zadjii-msft** 2022-01-11 12:22 UTC
Labels: Issue-Feature, Needs-Triage, Needs-Tag-Fix
