### ISSUE TITLE
Feature Request : Open Profile from right click taskbar

### ISSUE THREAD

**Issue by eddydu44** [microsoft/terminal#2970] opened 2019-09-29 12:21 UTC
# Description of the new feature/enhancement

Add user profiles inside the right click taskbar menu of terminal app.
It should launch the terminal with chosen profile instead of default. Or, if terminal is already opened, open a new tab / new window...

**Comment by j4james** [comment] 2019-09-29 22:29
Is this not a duplicate of #576?

**Comment by zadjii-msft** [comment] 2019-09-30 13:11
This is _definitely_ #576.

/dupe #576

**Closed** 2019-09-30 13:12 UTC
Labels: Issue-Feature, Needs-Tag-Fix, Needs-Triage
