### ISSUE TITLE
DEC double-height ANSI sometimes not rendered

### ISSUE THREAD

**Issue by ClaireCJS** [microsoft/terminal#15838] opened 2023-08-16 13:36 UTC
### Windows Terminal version

1.17.11461.0

### Windows build number

Windows 10 [Version 10.0.19045.3208]

### Other Software

TCC.exe (take command command line)

### Steps to reproduce

I know I'm a bit strange in my ways, but I pipe my copy  and move commands through a postprocessor ("copy-move-post.py") in python to make them more visually appealing and more "screamy" because of the way my attention works as well as my aesthetic tastes.   

The file copies/moves end up with a summary that I repurpose into double-height (DEC) ansi.  Really helps when watching stuff happen from across the room.

Sometimes this just....... doesn't render. I don't know why. 

I feel like it's something I'm doing, but I also feel like this shouldn't happen regardless of what I'm doing.   So I feel like it's a dual-ended bug.

Here's an example:

![image](https://github.com/microsoft/terminal/assets/789591/b13c2ca5-245e-4985-8737-cb98eac0040e)

Oops, I deleted a FLAC I wanted to keep.  I will undelete it to show what proper output looks like:

![image](https://github.com/microsoft/terminal/assets/789591/d3f13c8a-ef84-437f-9ecc-148e0db4f011)

So yeah, normally it renders just fine.

But sometimes it doesn't.

I'll provide the code in comments.

### Expected Behavior

I would expect it to render properly, like this:
![image](https://github.com/microsoft/terminal/assets/789591/623a4468-7c49-4de1-a1ed-f592256d2cfe)

### Actual Behavior

It renders improperly, like this:
![image](https://github.com/microsoft/terminal/assets/789591/db6ec0db-7253-4b2a-bc80-885229ff921e)

**Comment by DHowett** [comment] 2023-08-16 16:31
Interesting, thanks for sharing!

<img width="77" alt="image" src="https://github.com/microsoft/terminal/assets/189190/64fa3106-35c1-4e0a-bc01-4f5907be6385">

This always means that somebody turned off `ENABLE_VIRTUAL_TERMINAL_PROCESSING` using `SetConsoleMode` on the output handle. This often happens when multiple processes are attached to the same console: one terminates and tries to restore the console mode (often directly, by opening the special handle `CONOUT$` regardless of redirection (!)) before the other is done printing text in the mode that it had requested.

This will largely be solved by making the console mode "per-process" inheritable state, but we're not quite prepared for that today.

**Comment by ClaireCJS** [comment] 2023-08-16 17:28
> Interesting, thanks for sharing!

But of course :) 




> This always means that somebody turned off `ENABLE_VIRTUAL_TERMINAL_PROCESSING` using `SetConsoleMode` on the output handle. 

Well, "somebody" seems like a strong word, haha :)

I mean, it happens sometimes, and it doesn't happen other times, but this is just me piping through Python.  I suppose the colorama autoreset option could have some interplay?


>This often happens when multiple processes are attached to the same console: one terminates and tries to restore the console mode (often directly, by opening the special handle `CONOUT$` regardless of redirection (!)) before the other is done printing text in the mode that it had requested.

Is that what happens with piping?  That sounds suspiciously like what happens with piping.  My command finishes before the postprocessor finishes -- it would have to by definition.

Hmm, very compelling.


> This will largely be solved by making the console mode "per-process" inheritable state, but we're not quite prepared for that today.


Any idea how I can fix it within the context of my usage here?   Because it only happens sometimes. So it's a timing issue I think?

**Comment by zadjii-msft** [comment] 2023-08-22 16:07
So, usually I'd drop this at the start of all the python scripts I run: https://github.com/zadjii/win-py-vt/blob/master/enable.py

but since this seems to be a timing thing, I'd just sprinkle in `enable_vt_support` before wherever you output VT and it isn't working 🤷‍♂️

**Comment by ClaireCJS** [comment] 2023-08-25 13:12
> So, usually I'd drop this at the start of all the python scripts I run: https://github.com/zadjii/win-py-vt/blob/master/enable.py
> 
> but since this seems to be a timing thing, I'd just sprinkle in `enable_vt_support` before wherever you output VT and it isn't working 🤷‍♂️

OMG Thank you very much for this arcane voodoo!  I'll have no way of knowing if it fixed things other than if the problem doesn't seem to manifest over the next few weeks.

I wonder if anyone else is piping their move/copy commands to a postprocessing script like weird-ol'-me.

> 
> ninja: this might be worthy of just moving to a Discussion thread

**Comment by lhecker** [comment] 2023-08-30 21:38
I'm glad it seems better now! I'll mark this issue as a /duplicate of #4954, as fixing #4954 would fix your issue permanently and in a more robust manner.

**Closed** 2023-08-30 21:38 UTC
Labels: Issue-Question, Issue-Bug, Needs-Triage, Needs-Attention
