### ISSUE TITLE
Closing a tab in focus mode causes terminal to become unresponsive

### ISSUE THREAD

**Issue by zadjii-msft** [microsoft/terminal#7916] opened 2020-10-13 12:02 UTC
```
Windows Terminal Preview
Version: 1.5.2831.0
```

1. Open the Terminal
2. Enter focus mode
3. Run a command that opens a bunch of tabs/panes. I'm using 
```json
        { "command": { "action": "wt", "commandline": "new-tab --title OpenConsole cmd.exe /k #work 15 ; split-pane --title OpenConsole cmd.exe /k #work 15 ; split-pane -H cmd.exe /k media-commandline ; new-tab --title \"Symbols Script\" powershell dev\\symbols.ps1 ; new-tab -p \"Ubuntu 18.04\" ; new-tab -p \"microsoft/Terminal\" ; sp -V -p \"microsoft/Terminal\" ; sp -H -p \"microsoft/Terminal\" ; focus-tab -t 0" }, "name": "Good Morning" },
```
But it probably repros for something simpler
4. Close the first tab

### expected

The tab closes, and the terminal works as usual

### actual

The tab stays open, and now the terminal is seemingly hung. The focus has left the original control, but hasn't gone anywhere. There's no tab strip to be able to manually focus another tab. Clicking the control also doesn't focus it. Since the focused control is responsible for routing keyboard events, the terminal won't respond to any KB shortcuts, since there's no focused control

**Comment by Don-Vito** [comment] 2020-11-11 00:49
@zadjii-msft - there is an "event handling catastrophe here" 😄.  
I never tried to tested, just reading the code - please join my journey:

Closing the tab triggers two actions - shutting the existing tab down and moving the focus to the next tab.
Shutting down the tab, causes shutting down of all the panes that causes shutting down of all terminal controls, that causes closing the panes, that results in closing child panes and asynchronously setting them to nullptr.

And then comes a _MoveFocus that invokes _UnzoomIfNeeded that in the focus mode calls activeTab->ExitZoom(), that invokes activePane->Restore, that access _firstChild and _secondChild that might be null already

**Comment by DHowett** [comment] 2020-11-11 00:53
Oh yeah, we have a number of event handling catastrophies in our code.

**Comment by Don-Vito** [comment] 2020-11-11 00:53
@zadjii-msft  - and if this is not enough there are a lot of "funny" races. E.g.,

Exit Zoom might be called twice. From one hand it is called from _MoveFocus->_UnzoomIfNeeded
```
void TerminalPage::_UnZoomIfNeeded()
    {
        if (auto focusedTab = _GetFocusedTab())
        {
            if (auto activeTab = _GetTerminalTabImpl(focusedTab))
            {
                if (activeTab->IsZoomed())
                {
                    // Remove the content from the tab first, so Pane::UnZoom can
                    // re-attach the content to the tree w/in the pane
                    _tabContent.Children().Clear();
                    // In ExitZoom, we'll change the Tab's Content(), triggering the
                    // content changed event, which will re-attach the tab's new content
                    // root to the tree.
                    activeTab->ExitZoom();
                }
            }
        }
    }
```
On the other hand it might get called from 
```
pane->Closed([weakThis](auto&& /*s*/, auto && /*e*/) -> winrt::fire_and_forget {
            if (auto tab{ weakThis.get() })
            {
                if (tab->_zoomedPane)
                {
                    co_await winrt::resume_foreground(tab->Content().Dispatcher());

                    tab->Content(tab->_rootPane->GetRootElement());
                    tab->ExitZoom();
                }
            }
        });
```
This is funny because the co_await in the last one will allow both functions to enter ExitZoom

**Comment by Don-Vito** [comment] 2020-11-11 00:57
I am not sure where to start from. The immediate mitigation that will hopefully help is to check all pointers against nulls in the Restore method (zommedPane,  firstChild and secondChild).

**Comment by Don-Vito** [comment] 2020-11-11 08:02
In any case the issue I described is irrelevant for this one. Here the closed tab is not multipane, and it should be something else.

**Comment by CornCobs** [comment] 2020-11-20 08:00
Hi! I was about to post a new issue but I think this issue is similar so I thought I would add it here instead.

Windows details:
```
Major  Minor  Build  Revision
-----  -----  -----  --------
10     0      19041  610
```

Problem description:

I've set focus mode to be my default. My default profile is powershell but often I open wt for WSL. My natural workflow would thus be:

1. Open wt
2. Open WSL (Ctrl+Shift+3)
3. Switch back to powershell (Alt+Tab)
4. Exit powershell (use the exit command)

Expected behavior: Tab 1 (PS) closes, Tab 2 (WSL) remains open

Actual behavior: The whole app closes silently. I am not sure if it crashes or the program simply exits.

**Closed** 2020-12-11 18:58 UTC
Labels: Area-User Interface, Issue-Bug, Priority-1, Product-Terminal, Resolution-Fix-Committed
