### ISSUE TITLE
Select profile from task bar by right clicking

### ISSUE THREAD

**Issue by jahpola** [microsoft/terminal#6592] opened 2020-06-19 09:08 UTC
# Description of the new feature/enhancement

Right clicking terminal icon in the task bar brings up the profiles so I can select another profile easily.

# Proposed technical implementation details (optional)

So I have Ubuntu 18.04,Ubuntu-20.04, Debian, Azure Cloud Shell, Powershell and command prompt profiles.  I would like to select the profile by right clicking the terminal short cut in the task bar. My use cases

1. If the terminal is not running clicking the icon will bring the default up which is nice but what if I would like to open another profile instead?
2. Terminal is already running and profile A is active. But I need profile B for something. I need to click the terminal open, select the profile. 

In both use cases if the right click on the terminal short cut would bring the profile list it would be really helpful.

**Comment by electronic-dk** [comment] 2020-06-19 11:28
I think this is a dupe of https://github.com/microsoft/terminal/issues/576
Here's the corresponding spec draft: https://github.com/microsoft/terminal/pull/5350

**Comment by zadjii-msft** [comment] 2020-06-19 11:29
Thanks for the suggestion! Please make sure to [search for duplicates](https://github.com/microsoft/terminal/issues?q=is%3Aissue+jumplist+is%3Aclosed) when filing new issues. This is already being tracked by another issue on our repo - please refer to #576 for more discussion.

/dup #576

**Closed by zadjii-msft** 2020-06-19 11:29 UTC
Labels: Issue-Feature, Needs-Tag-Fix, Needs-Triage
