### ISSUE TITLE
The cursor doesn't move in vim when I scroll up or down.

### ISSUE THREAD

**Issue by enzezhang** [microsoft/terminal#5032] opened 2020-03-20 08:32 UTC
# Environment

```none
Windows build number: 10.0.18362.720
Windows Terminal version (if applicable): 0.9.433.0

Any other software? 
NO
```

# Steps to reproduce

 Using vim in windows terminal, and scrolling up or down the wheel of my mouse.

I have tried to use "set mouse=a" in VIM. It doesn't help.
# Expected behavior

The cursor will move as I scroll up or down
# Actual behavior

The Cursor doesn't move.

**Comment by zadjii-msft** [comment] 2020-03-20 14:09
> Any other software? 
> NO

> Using vim

You gotta pick one of those two 😜 Which version of vim are you using? `vim.exe` or the WSL `vim`? 

If it's the WSL vim, then this should be fixed in 0.10 (which is available now). If not, then this will probably end up being a dupe of #376

**Closed** 2020-03-27 19:00 UTC
Labels: Needs-Author-Feedback, Needs-Tag-Fix, Needs-Triage, No-Recent-Activity
