### ISSUE TITLE
.

### ISSUE THREAD

**Issue by XA2005** [microsoft/terminal#16644] opened 2024-02-01 17:21 UTC
# Description of the new feature/enhancement

# Proposed technical implementation details (optional)

Now you can use Ctrl+D to close this terminal, or press Enter to restart. Which setting is this and how do I change it.

**Comment by zadjii-msft** [comment] 2024-02-01 17:31
* [`closePane`](https://learn.microsoft.com/en-us/windows/terminal/customize-settings/actions#close-pane)
* [`restartConnection`](https://learn.microsoft.com/en-us/windows/terminal/customize-settings/actions#restart-a-pane)

Though, I'd guess you want the actual text to change ala #16581 /?

**Comment by XA2005** [comment] 2024-02-01 18:09
> * [`closePane`](https://learn.microsoft.com/en-us/windows/terminal/customize-settings/actions#close-pane)
> * [`restartConnection`](https://learn.microsoft.com/en-us/windows/terminal/customize-settings/actions#restart-a-pane)
> 
> 不过，我猜你希望实际文本改变 ala #16581 /？


Thank you for your suggestion. My idea is to use the Enter key to close the terminal or to adjust the closing state so that it only closes when the program fails or crashes. By the way, are you a developer? (If you have any doubts, I apologize, I do not speak English, this is from a machine translation.)

**Comment by zadjii-msft** [comment] 2024-02-01 20:00
> are you a developer?

Yes, I'm one of the core maintainers for the Terminal project. 

> My idea is to use the Enter key to close the terminal or to adjust the closing state so that it only closes when the program fails or crashes

Then yea, I'd say this counts as a duplicate of #16581. Thanks!

/dup  #16581

**Closed by zadjii-msft** 2024-02-01 20:00 UTC
Labels: Issue-Feature, Needs-Triage, Needs-Tag-Fix

**Comment by DHowett** [comment] 2024-02-01 20:16
You can also change the "Close On Exit" setting if you want to avoid this message completely.
