### ISSUE TITLE
Colortool is not working

### ISSUE THREAD

**Issue by karthikrathinavelu** [microsoft/terminal#812] opened 2019-05-15 02:13 UTC
OS Build Version : Microsoft Windows [Version 10.0.17763.475]

I've download Apr 2019 Colortool and it is not able to load the schemes

![image](https://user-images.githubusercontent.com/15039437/57743972-e51cc600-76e4-11e9-83c9-58add736cd7c.png)

I've tried Oct 2018 release. It's able to load the schemes, but colors are not set

![image](https://user-images.githubusercontent.com/15039437/57743990-fc5bb380-76e4-11e9-851f-94e2c919e39a.png)

After moving to the initial release version, it's able to load the schemes and set the color as well

![image](https://user-images.githubusercontent.com/15039437/57744009-109fb080-76e5-11e9-859d-9c70d63e516c.png)

**Comment by zadjii-msft** [comment] 2019-05-15 14:02
Looks to be a dupe of #770

**Closed by zadjii-msft** 2019-05-15 14:02 UTC
