### ISSUE TITLE
Extend key patterns and modifiers for command actions

### ISSUE THREAD

**Issue by ridhwaans** [microsoft/terminal#18279] opened 2024-12-03 07:08 UTC
### Description of the new feature

source: https://learn.microsoft.com/en-us/windows/terminal/customize-settings/actions#accepted-modifiers

currently, the accepted modifiers allow for `ctrl+`, `shift+`, `alt+` followed by a single func or alphanumeric key  
in settings.json, if i want to perform an action with the keys ctrl+t+n or win+t+q+q, I cannot do that because of  the error "String does not match pattern{...}"

I ask for modifier key followed by a combination of function/alphanumeric keys pattern to work on actions 

Also,  can you make `space+`  an accepted modifier so patterns like space+g+g can be used? 

thanks in advance!

### Proposed technical implementation details

 make `space+`  an accepted modifier. allow for an expression with multiple fn/letter/number keys associated with a terminal action

**Comment by zadjii-msft** [comment] 2024-12-03 17:20
So, you're asking for two things here:
*  part the first: "I want to combine multiple key chords to activate a keybinding" I think that's a /dupe of #1334
* part the second: "I want to treat <kbd>space</kbd>" as a modifier key: That's probably not reasonably feasible. There's a material API difference in the way Windows thinks about something like Ctrl/Alt/Shift/Win, vs actual keys like space. It would be a non-trivial amount of work for us to treat space as a modifier key. There's a lot of gnarly edge cases there. When is the user pressing space as the start of a keychord vs just pressing and holding space to enter a lot of whitespace?

**Closed** 2024-12-03 17:20 UTC
Labels: Issue-Feature, Needs-Triage, Needs-Tag-Fix

**Comment by o-sdn-o** [comment] 2024-12-03 18:00
> - part the second: "I want to treat space" as a modifier key: That's probably not reasonably feasible. There's a material API difference in the way Windows thinks about something like Ctrl/Alt/Shift/Win, vs actual keys like space. It would be a non-trivial amount of work for us to treat space as a modifier key. There's a lot of gnarly edge cases there. When is the user pressing space as the start of a keychord vs just pressing and holding space to enter a lot of whitespace?

In fact, it is not impossible, and may even be quite feasible. Just relying on the standard system window messages WM_KEYUP/WM_KEYDOWN it is quite possible to distinguish between different key combinations outside the Ctrl/Alt/Shift-modifiers concept.

You can play around with this in vtm by assigning any keyboard chords available to your keyboard device. For example, you can run the following command to use the `Space+C` key chord to print a "<Space+C Action>" message in terminal:
```
vtm -c "<config><hotkeys><terminal><key='Space+C'><action=TerminalSendKey data='<Space+C Action>'/></key></terminal></hotkeys></config>" -r term
```

https://github.com/user-attachments/assets/d71a8383-0902-416a-a67e-3e57989fdf15

You can get the available chords experimentally on the Info-page which is accessible by clicking on the bottom right of the vtm desktop.
