### ISSUE TITLE
Lines are not wrapping but writing over themselves

### ISSUE THREAD

**Issue by sbatten** [microsoft/terminal#3293] opened 2019-10-22 21:36 UTC
# Environment

```none
Windows build number: 10.0.18363.0
Windows Terminal version (if applicable): 0.6.2911.0

Any other software?
I use PowerToys FancyZones to size my window.
```

# Steps to reproduce

1. Launch Windows Terminal with PowerShell Core as the current tab's shell
2. Resize the window to slightly small width to trigger line wraps
3. Run something that prints long lines of output. In my case, I was running `scoop update`. 

# Expected behavior

Lines are wrapped correctly.

# Actual behavior

Lines are not wrapping but rather writing over themselves.

![image](https://user-images.githubusercontent.com/6561887/67335638-e5618e80-f4d8-11e9-9cd8-28a3350b4990.png)

**Comment by DHowett-MSFT** [comment] 2019-10-22 23:37
+@SteVen Batten<mailto:sbatten@microsoft.com>
Heyo,
Does this repro with 0.6.2951.0? Here’s the bundle:
"\\scratch2\scratch\duhowett\Microsoft.WindowsTerminal_0.6.2951.0_8wekyb3d8bbwe.msixbundle"

**Comment by DHowett-MSFT** [comment] 2019-10-23 00:00
Ran a few watch tasks and so far it seems to be resolved. Is this the commit that is expected to have fixed the issue? https://github.com/microsoft/terminal/commit/d6790c023fce438161c05af9ccfd49cd2f04cfc9

Thanks,
SteVen

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

From: Dustin Howett<mailto:duhowett@microsoft.com>
Sent: Tuesday, October 22, 2019 16:36
To: microsoft/terminal<mailto:reply@reply.github.com>; microsoft/terminal<mailto:terminal@noreply.github.com>; SteVen Batten<mailto:sbatten@microsoft.com>
Cc: Subscribed<mailto:subscribed@noreply.github.com>
Subject: RE: [microsoft/terminal] Lines are not wrapping but writing over themselves (#3293)

+@SteVen Batten<mailto:sbatten@microsoft.com>
Heyo,
Does this repro with 0.6.2951.0? Here’s the bundle:
"\\scratch2\scratch\duhowett\Microsoft.WindowsTerminal_0.6.2951.0_8wekyb3d8bbwe.msixbundle"

**Comment by carlos-zamora** [comment] 2019-10-23 17:00
That's not good. I gave it a try with `git log --pretty=oneline --abbrev-commit` on this repo's history and it seems to wrap just fine. What version of Powershell Core are you running?

**Comment by DHowett-MSFT** [comment] 2019-10-23 17:35
Sorry, I already confirmed with @sbatten that this is a /dupe of #3277.

**Closed by DHowett-MSFT** 2019-10-23 17:35 UTC
Labels: Needs-Author-Feedback, Needs-Tag-Fix, Needs-Triage
