### ISSUE TITLE
when I try to open the settings, it opens the Affinity Photo Editor, which uses the same shortcut.

### ISSUE THREAD

**Issue by joltar** [microsoft/terminal#8240] opened 2020-11-12 10:30 UTC
# Environment

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Windows Terminal version (if applicable):

Any other software?
```

# Steps to reproduce

# Expected behavior

# Actual behavior

**Comment by PhMajerus** [comment] 2020-11-12 13:18
Sounds to me like Affinity Photo Editor highjacked the .json file extension. Windows Terminal uses your default app associated with .json files to open the settings file.
JSON files are a standard human-readable data exchange format, they should be associated with a text editor or a code editor.

You can change the association in Settings > Apps > Default apps > "Choose default apps by file type" (near the bottom of the page), then, on the Choose default apps by file type page, scroll until you find the .json extension and choose the default app you want to associate with it. If you don't have any code editor, Notepad works fine.

**Comment by zadjii-msft** [comment] 2020-11-12 13:39
Yea, we've had this discussion countless times before on this repo. There's not a master dupe for it, but there is:

#6642 #8004 #7975 #7481 #7355

and those were all on the first page of [is:issue settings editor is:closed ](https://github.com/microsoft/terminal/issues?q=is%3Aissue+settings+editor+is%3Aclosed+)

Oh wait, more specifically, this is a /duplicate of #7696 
_which you filed..._

**Closed by zadjii-msft** 2020-11-12 13:39 UTC
Labels: Needs-Tag-Fix, Needs-Triage

**Comment by joltar** [comment] 2020-11-14 03:38
I apologize for doing this twice,  Thanks for the work you do to keep all this going.  I didn't intend to make more work
