### ISSUE TITLE
Title bar buttons aren't working (PowerToys)

### ISSUE THREAD

**Issue by Ronkiro** [microsoft/terminal#3325] opened 2019-10-25 15:02 UTC
# Environment

```none
Windows build number: 10.0.18362.295
Windows Terminal version (if applicable): 0.6.2951.0

Any other software?
```

# Steps to reproduce

Open terminal and click on close/minimize/maximize/edit environment.

# Expected behavior

It should work

# Actual behavior

It shows weird cursor and doesn't work.

[Printscreen](https://prnt.sc/po3cf9)

**Comment by zadjii-msft** [comment] 2019-10-25 15:29
This is super weird. I bet it has to do with our `WM_NCHITTEST` code in `NonClientIslandWindow`. If I had to go out on a limb, it's almost as if the entire titlebar area is being treated as `HTTOP`, which would cause the area to be treated as the "top drag region".

Unfortunately, I can't really repro this myself :/

@Ronkiro if you click and drag while the mouse is like that, does it resize the window? If so, that would probably confirm my suspicion. Also, does it act like that for the entire height of the titlebar area? 

<hr>

P.S. 

protip: you can actually just paste images directly into the input box on github, and it'll automatically uplod them to github and embed them inline. It's pretty neat
![image](https://user-images.githubusercontent.com/18356694/67583946-3a3c1980-f712-11e9-8b37-5b1343a4a396.png)

**Comment by Ronkiro** [comment] 2019-10-25 16:14
@zadjii-msft 
I tried adding the image but it was failing... It was creating github's link but it was a wrong link lol  i think i was missing something.

Back to the terminal, holding click doesn't resizes window. But, when moving to the non-button area of the title bar (The middle area) the cursor goes to default one again.

![image](https://user-images.githubusercontent.com/27526023/67586680-9316ac80-f728-11e9-8626-f2fbcce8a246.png)

Still in the default cursor, i can't click close/minimize/etc. ALT+F4 works though.
Testing a bit, i also noticed that i cannot do any mouse actions in terminal (Like marking a text, right clicking to paste/open menu, etc). But shortcuts like CTRL+V works. The only exceptions are double clicking the middle area (it maximizes the screen properly) and resizing the window.

Also, the image the cursor sticks with is the last one i hovered. I mean, if i move to the "Resize left" area and then move to title bar, the mouse will be with the "Resize left" icon.

![image](https://user-images.githubusercontent.com/27526023/67587028-59927100-f729-11e9-96e6-541bb9d8d898.png)

**Comment by JohnFNovak** [comment] 2019-10-25 19:47
I also had this issue (Microsoft Windows [Version 10.0.18362.418]), but restarting the machine fixed it.

**Comment by DHowett-MSFT** [comment] 2019-10-31 19:48
@Ronkiro Does restarting fix it for you? @JohnFNovak indicates that it may. :smile:

**Comment by Ronkiro** [comment] 2019-11-02 01:31
Nope @DHowett-MSFT. I mean, i already had restarted many times until i really create the issue here, but it didn't help.

Also noting that it's an enterprise W10, not sure if this can help anyhow.

**Comment by LuanVSO** [comment] 2019-12-29 22:12
this happens to me randomly too, exiting powertoys process seen to fix it.
in a related problem trying to drag the wt window with shift pressed freeze the window in place
but it start moving when you release it

**Comment by Ronkiro** [comment] 2020-01-02 12:43
> this happens to me randomly too, exiting powertoys process seen to fix it.
> in a related problem trying to drag the wt window with shift pressed freeze the window in place
> but it start moving when you release the shift key

Seems related to PowerToys for me too.

**Comment by zadjii-msft** [comment] 2020-01-02 13:04
Excellent to hear. Summoning @crutkas if he's got any ideas on the matter

**Comment by crutkas** [comment] 2020-01-02 17:12
What version of PowerToys are you on

**Comment by crutkas** [comment] 2020-01-02 18:36
I'm trying to repo this but can't.  I'm on PowerToys 0.14.1 and here are my steps to reproduce.  You may need to share your FancyZone settings.

We do stuff with shift to make you aware we're going to snap to your zones.

My system info currently:
- PowerToys 0.14.1
- Terminal: 0.7.3451.0
- Win10: 18363.535, Version 1909

1. Launch power toys.  
2. Launch Terminal.
3. click minimize, maximize (they all work)
4. added PowerShell tab
5. Added Cmd Tab
6. Remove new PowerShell tab with X
7. Hold Shift and go to FancyZone zone

**Comment by Ronkiro** [comment] 2020-01-03 13:44
Win10: Ver 1903, build 18362.295 (Enterprise)
PowerToys: 0.11.0

![image](https://user-images.githubusercontent.com/27526023/71726405-c145f600-2e15-11ea-9dd0-bf7f0b3793f5.png)

I also have "Use new zone editting experience" enabled, not sure if this has any relationships.

BTW, i can't reproduce the problem again now. Would be good if anyone that also had the problem could keep helping with info. But i didn't change any of the versions, just did the workaround fix.

**Comment by LuanVSO** [comment] 2020-01-03 17:35
powertoys 0.14.1
win10 insider slow ring : 2004, build 19041.1
wt:0.7.3451.0

the bug happened when i was collecting the version of wt,
it also seen to affect the power toys settings
i connected a display and moving wt window to it made the buttons work
though only on the 2nd display
 used the step recorder to capture it:
[powertoys bug.zip](https://github.com/microsoft/terminal/files/4020110/powertoys.bug.zip)
[powertoys bug 2.zip](https://github.com/microsoft/terminal/files/4020107/powertoys.bug.2.zip)

**Comment by LuanVSO** [comment] 2020-01-24 19:28
so any news on this?

**Comment by crutkas** [comment] 2020-01-27 19:49
I can recreate this but i think it is with the terminal as i can repo this behavior with PowerToys fully off.  Note this is the only way i can recreate this.

I'm on Terminal 0.8.10091.0

**What i'm doing to recreate**
1. launch terminal 
2. Left-Click on title bar
3. Hold shift
4. Drag mouse downward and into the console screen itself
5. Release mouse

**Actual behavior:**
Window freezes for about 3 seconds, can't drag it or min/max/close buttons won't respond to clicking or hovering as well

**Comment by LuanVSO** [comment] 2020-01-28 14:32
>Window freezes for about 3 seconds, can't drag it or min/max/close buttons won't respond to clicking or hovering as well

does the buttons on the window stay unresponsive when you release shift?
>I can recreate this but i think it is with the terminal as i can repo this behavior with PowerToys fully off

but when the bug happens the powertoys settings is also affected

**Comment by crutkas** [comment] 2020-01-28 15:36
Yes, window is unresponsive but comes back after about three seconds. The fact I can do this without PT running means something is going on with terminal, not PT. 

Step recorder was helpful but a bit confusing due to everything was in Portuguese and hand to be manually translated. For showing unresponsive stuff, a video may be more impactful here. Gamebar (win+g) can do this. 

So if what my steps to cause a freeze is a different thing, please let’s do the step by step.

**Comment by LuanVSO** [comment] 2020-01-28 16:43
>everything was in Portuguese

sorry about that, I should have tried harder to edit the file so i could translate it.

>Gamebar (win+g) can do this. 

yeah but it only captures the window not the whole screen. will try it when it happens again if it is going to be helpful

>Yes, window is unresponsive but comes back after about three seconds
>running means something is going on with terminal, not PT.

i reported that behavior here [#3325(comment)](https://github.com/microsoft/terminal/issues/3325#issuecomment-569546479)

**Comment by crutkas** [comment] 2020-01-28 16:58
@LuanVSO 
1. never be sorry for having something in your native language. 
2. if you could do a step by step like i did above, maybe that could help.

**Comment by gokulyc** [comment] 2020-02-13 09:23
title bar buttons are not working even after reinstalling the application.

**Comment by LuanVSO** [comment] 2020-03-03 23:41
so here we go, just installed powertoys v0.15 rebooted the machine and opened windows terminal
![20200304023637-7c011ad592 gif-2-mp4 com](https://user-images.githubusercontent.com/43626415/75830211-f11a6700-5d8e-11ea-904e-97ca4471f307.gif)
it also affect pt settings:
![20200304023343-0b6a9d442f gif-2-mp4 com](https://user-images.githubusercontent.com/43626415/75830046-80734a80-5d8e-11ea-985a-6e3d1c4d2c3a.gif)
here is the original video clips:
[bug-videos.zip](https://github.com/microsoft/terminal/files/4284138/bug-videos.zip)

**Comment by crutkas** [comment] 2020-03-11 21:28
@LuanVSO does this happen without PowerToys running?

**Comment by LuanVSO** [comment] 2020-03-11 21:34
no, when i stop pt it goes back to normal behavior

**Comment by crutkas** [comment] 2020-03-11 21:47
Can you create a step by step and where you are clicking?

**Comment by LuanVSO** [comment] 2020-03-12 19:01
1. launch terminal (it is pinned on my task bar so i press win +2)
2. right-click on minimize button (doesn't work)
3. right-click on split-button(doesn't work)
4. hover mouse over edges of the window to show how the pointer behave (resizing the window does work, but it would stop the recording so i didn't)

**Comment by crutkas** [comment] 2020-03-12 19:35
for the life of me, i can't repo this.  can you email me and maybe lets do a teams sync where we can screen share?  crutkas@microsoft.com

**Comment by LuanVSO** [comment] 2020-03-12 19:43
ok, i mean i can't repo this every time neither, it is very finicky

**Comment by crutkas** [comment] 2020-03-12 19:44
if it follows the pattern i outlined above, that is outside powertoys and i can repo this without PT running.

**What i'm doing to recreate**
1. launch terminal 
2. Left-Click on title bar
3. Hold shift
4. Drag mouse downward and into the console screen itself
5. Release mouse

**Comment by LuanVSO** [comment] 2020-03-12 20:56
i think i found out whats happening.

1. pin win terminal to taskbar
2. hold win key down
3. just before the shorcut guide comeup press the # corresponding to win term and release quicly
4. try interacting with the controls on win term

**Comment by LuanVSO** [comment] 2020-03-12 21:08
also, shortcut guide doesn't comes up anymore after doing these steps

**Comment by Druko** [comment] 2020-03-26 08:14
For me, the title bar is working, the issue I am having is with Drop Down for profiles and setting. While using the VS2019 debug, it causes an exception.
I can open a new terminal in debug mode with "ctrl+shift+ 2,3,4", but if a select the drop-down button.

![image](https://user-images.githubusercontent.com/4297751/77624406-c21b8f00-6f0f-11ea-8b35-4e4704266448.png)

**Comment by DHowett-MSFT** [comment] 2020-03-27 01:17
Unfortunately, _that_ is a platform bug (which seems to have been fixed in 19041+). Sorry :smile:

**Comment by ipatalas** [comment] 2020-04-24 20:44
I've got the same on my machine but it gets even trickier.
It only happens on my primary screen. When I move WT window to the other screen everything goes back to normal. Same symptoms, window not receiving mouse events, even the cursor freezes over WT window. Max/Min/Close does not work, have to move the window to the other screen for it to work.
I am PT user as well and apparently turning it off helps immediately. 
However @crutkas repro steps work as well without PT running.

@DHowett-MSFT is this supposed to be funny? That's still on Insiders only... Well, luckily WT still can't compete with my current setup so no worries.. 
I'll just wait that through and get back in half a year or so.

**Comment by DHowett-MSFT** [comment] 2020-04-24 20:45
> @DHowett-MSFT is this supposed to be funny? 

Just so I'm clear: you think that this bug that _nobody on my team can reproduce, and we're in discussion with the input team about_ is a joke we're playing on you? That's cool.

**Comment by threkk** [comment] 2020-05-03 21:09
I had the same issues at https://github.com/microsoft/terminal/issues/5724 and I don't have any issue after updating PowerToys to version 0.17.0

**Comment by DHowett-MSFT** [comment] 2020-05-03 21:10
Those of you who were seeing this issue with PowerToys, can you check whether it's still a problem as of [PowerToys v0.17.0](https://github.com/microsoft/PowerToys/releases/tag/v0.17.0)? Thanks.

**Comment by LuanVSO** [comment] 2020-05-05 15:37
it is still happening, @threkk did you disable shortcut guide?

**Comment by threkk** [comment] 2020-05-05 20:01
No, I didn't have to disable it to get it work. I closed PowerToys, updated, and opened it again. It is important to mention that I used Scoop to install PowerToys.

**Comment by LuanVSO** [comment] 2020-05-07 21:50
it is not happening anymore for me too

**Comment by fquinner** [comment] 2020-05-21 15:27
> Those of you who were seeing this issue with PowerToys, can you check whether it's still a problem as of [PowerToys v0.17.0](https://github.com/microsoft/PowerToys/releases/tag/v0.17.0)? Thanks.

Came here the first time I spotted this - yeah powertoys 0.17.0 has the same issue (the only version I ever installed in face). It just happened to me. In fact when the issue is exhibiting itself, the mouse doesn't even work *within* powertoys either. Nor do I even really use powertoys tbh I was just trying it out. When I restart powertoys the issue is still not present, so assuming that this is related to some sort of deadlock that locks up both apps :(. I'll try and pay closer attention to any preceding events next time it happens but I pity you trying to troubleshoot this one.

**Comment by pie314159265** [comment] 2020-05-21 19:09
Just happened to me with PowerToys 0.18.0, restarting PowerToys seems to have fixed the issue.

**Comment by LuanVSO** [comment] 2020-05-23 04:51
found out a sure way to repro this on powertoys 0.18.1:
here is the step record file i did (now it is in the right language 😅 ):[powertoys unresponsive window bug.zip](https://github.com/microsoft/terminal/files/4671153/powertoys.unresponsive.window.bug.zip)

**Comment by bigyihsuan** [comment] 2020-06-12 22:47
I managed to reproduce this bug, as reported in [PowerToys #4287](https://github.com/microsoft/PowerToys/issues/4287). If Fancy Zones is turned off, PowerToys restarted, and Fancy Zones turned on, it works as expected.

**Comment by crutkas** [comment] 2020-06-12 23:45
I disagree this is PT directly, i can recreate this bug without powertoys running.  the terminal window rendering freezes.  FancyZones amplifies the issue due to the hotkey

What i'm doing to recreate

1. launch terminal
2. Left-Click on title bar
3. Hold shift
4. Drag mouse downward and into the console screen itself
5. Release mouse
6. type

you'll see the cursor stop and all input stop coming in.

**Comment by LuanVSO** [comment] 2020-06-13 02:25
does it behave like this
![terminal](https://user-images.githubusercontent.com/43626415/84557754-0135d100-ad04-11ea-9651-8dab0a21ad8a.gif)
 when shift is released?

**Comment by crutkas** [comment] 2020-06-13 02:33
Yup

**Comment by LuanVSO** [comment] 2020-06-13 02:41
k,
 so there are 2 bugs here:
1. is that shift dragging wt causes it to hang
2. is  this


> found out a sure way to repro this on powertoys 0.18.1:
> here is the step record file i did (now it is in the right language 😅 ):
> [powertoys unresponsive window bug.zip](https://github.com/microsoft/terminal/files/4671153/powertoys.unresponsive.window.bug.zip)
> it has to be the first time that shortcut guide is triggered, otherwise it wont repro

**Comment by LuanVSO** [comment] 2020-06-13 02:51
here is a gif showing the process:
![terminal](https://user-images.githubusercontent.com/43626415/84558188-60e1ab80-ad07-11ea-936a-a0387f43555e.gif)
when i released the win key i could no longer interact with the buttons on pt settings

**Comment by LuanVSO** [comment] 2020-06-16 17:02
I managed to repro the bug in a debug buid of pt, and when i paused the execution it droped me in this file
![image](https://user-images.githubusercontent.com/43626415/84804972-e603e380-afd9-11ea-9954-c5fc64ccb8cc.png)

**Comment by LuanVSO** [comment] 2020-06-16 17:41
this seen to be happening when the d2doverlaywindow is being created, as the bug only happens if it is the first time it is being displayed

**Comment by enricogior** [comment] 2020-06-17 09:30
@LuanVSO 
the bug you fund when long pressing the Win key while remapping a key is unrelated to the Terminal bug when shift dragging it.

**Comment by roddolf** [comment] 2020-07-21 18:18
This happened to me with Terminal version **1.0.1811.0**

Looked like a conflict with PowerShell:
I had version **7** installed, and also I had **.Net** which also installed PowerShell but version **6**. Uninstalling the PowerShell from **.Net** seemed to fix the issue for me.

**Comment by vhawk19** [comment] 2020-08-16 19:39
@DHowett I get the same issue on Powertoys 0.18, not able to use the mouse to click on power toys or the windows terminal

**Comment by enricogior** [comment] 2020-08-17 09:01
Can someone confirm that quitting PowerToys is not enough to prevent this bug and it requires to uninstall it? 

@DHowett-MSFT 
this is a very interesting (and weird) discovery:
https://github.com/microsoft/PowerToys/issues/5944
Terminal, for some unknown reason, is using a window class defined in PowerToys.
The steps recorder shoes the UI element that is "stealing" the input, is part of Terminal, not PowerToys.exe.
Not clear what is going on here, is Terminal actively creating this UI element or is PowerToys that is somehow injecting this into Terminal?

**Comment by zadjii-msft** [comment] 2020-08-17 13:51
@enricogior Good catch. The Terminal certainly isn't creating that window class - the only window we create manually is our `CASCADIA_HOSTING_WINDOW_CLASS` (see [IslandWindow.cpp#L18-L68](https://github.com/microsoft/terminal/blob/master/src/cascadia/WindowsTerminal/IslandWindow.cpp#L18-L68)).

Technically, we're also creating a XAML Island - maybe that's somehow interacting with the shortcut guide somehow?

When this occurred for me, I was simply able to restore functionality by disabling the "Shortcut Guide" powertoy. Uninstalling would _also_ work, but might be a tad bit excessive 😄

**Comment by zadjii-msft** [comment] 2020-08-17 13:59
I'm just realizing that #6120 also has a ton more info about this issue and a bunch of other repros in it.

**Comment by enricogior** [comment] 2020-08-17 15:27
@zadjii-msft 
the Shortcut Guide is a pure C++ app, the fact that the window class defined in Shortcut Guide ends up in Terminal is quite surprising.

**Comment by DHowett** [comment] 2020-08-17 15:49
@enricogior terminal is a native C++ app too. The language in use has no bearing on the window classes that are possible.

**Comment by enricogior** [comment] 2020-08-17 18:09
@DHowett 
I meant pure Win32, no XAML, the only thing I've found so far that can be a potential entry point for the problem is described here
https://github.com/microsoft/PowerToys/issues/5944#issuecomment-674981994
I suggested to build a debug version of Terminal to monitor that class name to verify if the Steps recorder is correctly identifying the UI element as child of the Terminal process, it would confirm that there is an injection of the class object from outside.

**Comment by aharpervc** [comment] 2020-08-19 16:23
This has now happened to me as well, but actually a hybrid of this and https://github.com/microsoft/terminal/issues/4448 where I can't type nor can I click on title bar buttons or scroll or use any UI element (I can resize the window, though). This has happened more than once.

- I am using PowerToys v0.20.1
- I am not using the shortcut guide
- resizing and snapping the windows (win+arrow) works
- clicking into the window (titlebar, tab bar, min/max/exit) doesn't work
- typing into the window has no effect
- the shell is powershell (and then running wsl inside that), and the process tree is still alive
- I am running 150% DPI scaling, but I only have 1 monitor plugged in
- I started the app yesterday, and the computer has slept/woken since then. I only noticed the problem after waking the computer

**Comment by enricogior** [comment] 2020-08-20 08:05
@aharpervc 
> I am not using the shortcut guide

Is Shortcut Guide turned off in the PowerToys settings or simply you are not invoking it?

**Comment by aharpervc** [comment] 2020-08-20 13:17
It's turned off:

![image](https://user-images.githubusercontent.com/441085/90774773-ff6d2880-e2c5-11ea-8a16-1d91898aa064.png)

**Comment by enricogior** [comment] 2020-08-20 15:49
@aharpervc 
thank you.

That seems to exclude the possibility that the bug is caused directly by Shortcut Guide, since it's not running and therefore it can't be what is injecting the `PToyD2DPopup` class in the Terminal process.

**Comment by crutkas** [comment] 2020-08-20 17:32
@aharpervc what graphic chipset are you running?  NVidia?

**Comment by aharpervc** [comment] 2020-08-20 20:43
> @aharpervc what graphic chipset are you running? NVidia?

AMD Radeon Pro 560

**Comment by jimmyff** [comment] 2020-09-28 13:54
I was also experiencing this issue (Cannot interact with Power Shell window bar other than drag it around). Restarting windows & killing the 'Windows Terminal' app in the task manager do not fix it for me. 

Power toys version 0.19.1
Windows 10 Pro 19042.541

I just opened Power Toys to check if my shortcut guide was enabled as suggested above but I couldn't interact with that UI either. I then killed the 'Powertoys runner' process using task manager and it fixed both issues for now at least.

**Comment by chr1573r** [comment] 2020-10-19 12:46
Good thing I found this on Google!
After updating to Windows 10 feature release 2004 last week, I could not click anywhere on the titlebar of the Windows Terminal App (neither tab controls or minimize/maximize/close).
Was not possible to select text in the terminal window either.
Problem disappeared immediately when closing Power Toys in the tray 👍

**Comment by girlandhercode** [comment] 2020-11-25 23:29
In my case, this happens to both Windows Terminal (`Version: 1.4.3243.0`) and Windows Terminal Preview (`Version: 1.5.3242.0`) whether or not PowerToys (`Version: 0.25.0`) is running. My Windows 10 version is `1909` and OS Build is `18363.1198`.

This is probably useless information, but using WindowSpy (Autohotkey inspection component), I've noticed there is a difference between the class name/instance number (ClassNN in WindowSpy) of the controls involved.

When I **_can_** interact with the mouse hovering over the New Tab button or any of the minimize/maximize etc buttons:
```cmd
ClassNN:  Windows.UI.Composition.DesktopWindowContentBridge1
Text:	  DesktopWindowXamlSource
```
![image](https://user-images.githubusercontent.com/2183606/100290843-48c6b700-2f4a-11eb-9f36-3be8351d5464.png)


---

When I **_can not_** interact with the mouse on these controls this changes to:
```cmd
ClassNN: Windows.UI.Core.CoreWindow1
Text:        DesktopWindowXamlSource
```
![image](https://user-images.githubusercontent.com/2183606/100290869-5419e280-2f4a-11eb-9c63-47555776a6d0.png)

**Comment by zadjii-msft** [comment] 2021-01-29 15:46
For future readers: there's plenty more investigation that's been done in #6120. My last working theory was that toggling the "Shortcut Guide" off should fix this. 

There were also the related:
* microsoft/PowerToys#4360
* microsoft/PowerToys#3833
* microsoft/PowerToys#3250
* microsoft/PowerToys#3090

**Comment by enricogior** [comment] 2021-01-29 16:11
@zadjii-msft 
the main issue in the PowerToys repo to track this weird bug is https://github.com/microsoft/PowerToys/issues/5944

**Comment by zadjii-msft** [comment] 2021-08-09 10:37
Is anyone still seeing this? There's been a decent number of PowerToys and Terminal releases since this was filed, but there hasn't been any reports in quite some time. Seems like this was potentially fixed.

**Closed** 2021-08-16 16:00 UTC
Labels: Issue-Bug, Area-User Interface, Needs-Author-Feedback, Product-Terminal, Tracking-External

**Comment by b-hayes** [comment] 2022-10-22 02:48
Im having the same issues as @mcdonamw and I do not use power toys. Can only type comamnds and close the terminal nothing elseworks.

**Comment by DHowett** [comment] 2022-10-24 18:01
@b-hayes _hmm_, do you happen to have more than one monitor? Can you remember whether Terminal was on the primary display or not? If not, was it to the left?

**Comment by b-hayes** [comment] 2022-10-26 20:31
I was using RDP which changes the display to match the remote client. I RDP in from two other machines so the display can change 3 times in a single day. I rebooted the system and the problem hasn't come back again so 🤷🏼‍♂️

**Comment by Ulrar** [comment] 2025-04-03 07:48
Same here, I don't have power toys but this happens to me very often.
I only have one screen active, but I just tested opening and closing the laptop lid (to enable then disable a second screen) which did fix it for this instance
