### ISSUE TITLE
Double click maximization of window on TitleBar

### ISSUE THREAD

**Issue by KoditkarVedant** [microsoft/terminal#1582] opened 2019-06-25 06:55 UTC
# Summary of the new feature/enhancement
In Preview build, I can maximize terminal window by double clicking on title bar area (white colored tittle bar area) next to minimize button. As you can see in below image if I double click on the highlighted area it doesn't maximize the window.

![QRUlRxAdEb](https://user-images.githubusercontent.com/18693839/60075260-86665580-9742-11e9-8a18-080f577ec8fa.png)

It doesn't feel natural as I need to go all the way to the right almost near to the maximize button to double click to toggle size of window. If I need to go all the way to the right then I can click maximize button instead. It ultimately reduce the usability of toggling the window using double click.

It would be really great if I can double click on blank area anywhere on the title bar to toggle the window.

**Comment by antoineco** [comment] 2019-06-25 07:03
Candidate for #1375

**Comment by JannesStroehlein** [comment] 2019-06-25 10:47
pls let me drag this title bar area to move the window

**Comment by JushBJJ** [comment] 2019-06-25 10:59
Im sure you can also disable the tabs being inside the titlebar in profiles
.json which is locate above the profiles

**Comment by carlos-zamora** [comment] 2019-06-25 23:23
Use the gap between the drop down and the minimize button.
This is a duplicate of #564

**Closed by carlos-zamora** 2019-06-25 23:23 UTC
Labels: Area-User Interface, Issue-Bug, Product-Terminal, Resolution-Duplicate
