### ISSUE TITLE
Selection Issue

### ISSUE THREAD

**Issue by satyampathak223** [microsoft/terminal#4069] opened 2019-12-28 07:59 UTC
Keyboard shortcut used for highlighting text for selection  ( SHIFT + ←,→,↑,↓ ) behaving 
unexpectedly .
Shift +↑  produces A
Shift +↓  produces B
Shift +→ produces C
Shift +←  produces D

Windows Version 1909 (OS Build 18363.535 )
Windows Terminal (Preview) Version:  0.7.3451.0

**Comment by DHowett-MSFT** [comment] 2019-12-28 20:38
This may be a /dupe of #715

**Closed by DHowett-MSFT** 2019-12-28 20:38 UTC
Labels: Needs-Tag-Fix, Needs-Triage
