### ISSUE TITLE
Spaces added to prompt on shell launch (PowerShell/pwsh)

### ISSUE THREAD

**Issue by yooakim** [microsoft/terminal#8341] opened 2020-11-20 08:23 UTC
# Environment

```none
Win32NT 10.0.19042.0 Microsoft Windows NT 10.0.19042.0
Windows Terminal Version: 1.4.3141.0

https://github.com/justjanne/powerline-go

```

# Steps to reproduce

Add the following to your PowerShell $PROFILE (adjust the path to the powerline-go exectuable to your local environment)

```PowerShell
Function global:prompt {
    $pwd = $ExecutionContext.SessionState.Path.CurrentLocation
    $startInfo = New-Object System.Diagnostics.ProcessStartInfo
    $startInfo.FileName = "$ENV:OneDriveConsumer\Util\powerline-go.exe"
    $startInfo.Arguments = "-shell bare"
    $startInfo.Environment["TERM"] = "xterm-256color"
    $startInfo.CreateNoWindow = $true
    $startInfo.StandardOutputEncoding = [System.Text.Encoding]::UTF8
    $startInfo.RedirectStandardOutput = $true
    $startInfo.UseShellExecute = $false
    $startInfo.WorkingDirectory = $pwd
    $process = New-Object System.Diagnostics.Process
    $process.StartInfo = $startInfo
    $process.Start() | Out-Null
    $standardOut = $process.StandardOutput.ReadToEnd()
    $process.WaitForExit()
    $standardOut
}
```

Start a PowerShell (classic) or PowerShell terminal window via Windows Terminal. The first time the prompt function is called there are spaces inserted between the different prompt parts. Pressing `Enter` makes these disappear and the prompt works fine.

If I use the same profile without Windows Terminal launching PowerShell.exe directly it works fine. So I suspect this is related to Windows Terminal.

Here's an animated GIF that shows what is going on:

![powerline-spaces](https://user-images.githubusercontent.com/862546/99776375-013ac800-2b11-11eb-8c05-48a7c3f953ed.gif)

# Expected behavior

I expect to see the prompt formatted correctly as follows:
<img width="720" alt="powerline-go-expected" src="https://user-images.githubusercontent.com/862546/99776755-9c33a200-2b11-11eb-9cbe-441844632c51.png">

# Actual behavior

This is what the prompt looks like when the PowerShell is first started:

<img width="720" alt="powerline-go-actual" src="https://user-images.githubusercontent.com/862546/99776660-70182100-2b11-11eb-963f-c907c4c9ffa0.png">

**Comment by zadjii-msft** [comment] 2020-11-20 14:05
This might sound crazy, but if you highlight that first prompt line, the one with the spaces, then dismiss the selection, does it re-render correctly?

**Comment by DHowett** [comment] 2020-11-20 17:36
It looks like you've customized your powershell profile somewhat? I can't reproduce this, but I am not using `-NoLogo` or have otherwise suppressed the startup banner. 🤔

**Comment by DHowett** [comment] 2020-11-20 17:40
Yeah, this only happens with `-NoLogo`. Interesting!

@zadjii-msft this is coming out of conpty with additional `\e[1C` in it, but only on the first-ever print to the screen. _Everything else_ comes out fine.

First run

```
␛[38;5;250m␛[48;5;240m␛[H␣REDMOND\duhowett␛[38;5;240m␛[48;5;238m␛[1C␛[38;5;250m␛[1Cdhowett-sl␛[38;5;238m␛[48;5;31m␛[1C␛[38;5;15m␛[1C~␛[38;5;31m␛[48;5;236m␛[1C␛[38;5;15m␛[1C$␛[38;5;236m␛[49m␛[1C␛[1C␛
```

After Clear

```
␛[38;5;250m␛[48;5;240m␣REDMOND\duhowett␣␛[38;5;240m␛[48;5;238m␣␛[38;5;250mdhowett-sl␣␛[38;5;238m␛[48;5;31m␣␛[38;5;15m~␣␛[38;5;31m␛[48;5;236m␣␛[38;5;15m$␣␛[38;5;236m␛[49m␣␛[m
```

**Comment by zadjii-msft** [comment] 2020-11-20 17:43
well that's batty. Thanks for investigating! @DHowett any chance you've got a oneliner repro for me that I can turn into a test? (if not that's cool too, this is probably enough to work off of)

**Comment by DHowett** [comment] 2020-11-20 17:47
Nah, it's even easier!

### `test_8341.ps1`

```
"`e[38;5;250m`e[48;5;240m REDMOND\duhowett `e[38;5;240m`e[48;5;238m `e[38;5;250mdhowett-sl `e[38;5;238m`e[48;5;31m `e[38;5;15m~ `e[38;5;31m`e[48;5;236m `e[38;5;15m$ `e[38;5;236m`e[49m `e[m"
sleep 100
```

###

```
wt nt pwsh -c test_8341.ps1
```

**Comment by DHowett** [comment] 2020-11-20 17:47
Just so long as it's the first thing printed to the screen. I used the powershell core escape escape, so it won't work in Windows PowerShell (sorry)

**Comment by yooakim** [comment] 2020-12-03 14:54
I've been off-line for a while but thanks for the looking into this :-)

**Comment by ntaken** [comment] 2021-01-21 02:54
hmm.. Have the same thing happening to me with Windows terminal Version: 1.4.3243.0 but with Ubuntu wsl after following this guide [https://docs.microsoft.com/sv-se/windows/terminal/tutorials/powerline-setup] .
Works fine with wsl.exe.

Resizing the window or open any file and close it will fix the stripes.

**Comment by brunovieira97** [comment] 2021-09-11 22:44
My Windows Terminal was updated yesterday and this started happening for me. Even though I always use up to date versions of everything (or did so until 2 months ago), this never happened before.

Any update on this?

**Comment by squidtopus** [comment] 2021-09-12 14:45
I can confirm that this happens with the `-NoLogo` option, and only on the first prompt:

![image](https://user-images.githubusercontent.com/63101447/132992092-7bba28df-d230-46fd-95dc-01b27e278cba.png)

As a workaround, I've added a `cls` to my PS profile, which had no impact on launch time:

```powershell
Import-Module posh-git
Import-Module oh-my-posh
Set-PoshPrompt Paradox
Clear-Host
```

**Comment by DHowett** [comment] 2021-09-13 18:27
How strange! Would you be willing to try and capture this with the [debug tap](https://github.com/microsoft/terminal/wiki/Enabling-the-debug-tap)?

**Comment by DHowett** [comment] 2021-09-13 18:28
Wait, I forgot that we already had a repro for this. You can ignore that request!

**Comment by brunovieira97** [comment] 2021-09-13 22:30
@DHowett if you need any assistance in reproducing, or more information on it, count on me! I'm interested in helping in any way I can ;)

**Comment by zzttdd** [comment] 2021-09-16 04:58
ah, I have the same problem. But it perfoms normally before, just becomes like this when I accidentally change the cmd profile. Then my wsl looks like this.

**Comment by zzttdd** [comment] 2021-09-16 05:02
> My Windows Terminal was updated yesterday and this started happening for me. Even though I always use up to date versions of everything (or did so until 2 months ago), this never happened before.
> 
> Any update on this?

Maybe because of the update? Me too. It jumps out recently.

**Comment by zzttdd** [comment] 2021-09-16 05:04
It happens only start up, and has nothing to do with the logo, I think.
![image](https://user-images.githubusercontent.com/59756623/133552671-6a588059-5f49-413a-bd9b-6efa65881ad9.png)

**Comment by zzttdd** [comment] 2021-09-16 05:11
If there's anything before prompt, it works fine, even print some space before the prompt.
![image](https://user-images.githubusercontent.com/59756623/133553267-fd5bbda6-2c00-4c1a-a866-2302bfc90c0f.png)

**Comment by ayalon** [comment] 2021-09-16 12:18
I am also affected.

**Comment by zzttdd** [comment] 2021-09-16 14:15
Also, when split the window, it will look like this:
![image](https://user-images.githubusercontent.com/59756623/133628181-c2404aa1-752c-4ef1-a34d-891a745d4c17.png)

**Comment by chevtek** [comment] 2021-09-27 02:05
Same issue for me. I'm using powerline-shell in Ubuntu. This issue only occurs in Windows Terminal and not in any other terminal.

![image](https://user-images.githubusercontent.com/874394/134835167-8211168d-c185-4ee3-8af4-264d33611516.png)

**Comment by chevtek** [comment] 2021-09-27 02:12
> I can confirm that this happens with the `-NoLogo` option, and only on the first prompt:
> 
> ![image](https://user-images.githubusercontent.com/63101447/132992092-7bba28df-d230-46fd-95dc-01b27e278cba.png)
> 
> As a workaround, I've added a `cls` to my PS profile, which had no impact on launch time:
> 
> ```powershell
> Import-Module posh-git
> Import-Module oh-my-posh
> Set-PoshPrompt Paradox
> Clear-Host
> ```

I just did the equivalent in my `.bashrc` for Ubuntu by putting a `clear;` at the bottom and this does "fix" the issue! So thanks for that. At least there's a workaround. It's a minor issue I know but it was annoying me lol

**Comment by chevsunrun** [comment] 2021-10-12 05:35
Oh wow thanks for the link. Happy to see WSL progressing into a stand-alone app!

**Comment by PilotBob** [comment] 2022-01-07 17:09
Just to be complete, this also happens when I open the Ubnutu / WSL2 / Bash shell in Terminal.

**Comment by floatingrain** [comment] 2022-01-31 10:53
This problem still happens in Windows Terminal 1.12.3472.0

**Comment by DHowett** [comment] 2022-02-01 20:48
HA! We finally have a root cause for this. I ran into a different issue, where the "version update" notification was losing the background color around the edged, and it all started to fall into place.

<img width="496" alt="image" src="https://user-images.githubusercontent.com/189190/152048335-123fbc32-56ed-45a1-b066-f970f2dec9de.png">

If we are painting the first frame or any frame after you clear the entire screen, as an optimization[^1] we don't send a bunch of space characters. We neglected to check whether those space characters were _meaningful_ (had background colors, underlines, other attributes...)

Proximal area of failure:

https://github.com/microsoft/terminal/blob/27de97bf9325d02c6e5bf13e005e2c805ac963a3/src/renderer/vt/paint.cpp#L448-L462

I wonder if we can use this function to help:

https://github.com/microsoft/terminal/blob/27de97bf9325d02c6e5bf13e005e2c805ac963a3/src/buffer/out/TextAttribute.hpp#L135-L137

[^1] The ConPTY API tries very hard to pretend that it is not translating a buffer of 120x30 cells into VT . . . so it lies, cheats and steals sometimes. The buffer contains 3900 empty spaces on startup, so we try not to send them to apps.

**Comment by DHowett** [comment] 2022-02-17 00:39
<img width="278" alt="image" src="https://user-images.githubusercontent.com/189190/154380486-d4ee12af-7b9f-4c69-adf9-c8ab30728a20.png">

It's testable!
I am not certain the right way to fix it, but it's fixable too. The test passes as of https://github.com/microsoft/terminal/commit/c9e206997106eeecbaa287d9f41e4ccdd6f835e1, but the attribute math is not correct (to which I suspect @j4james will attest)

**Closed** 2022-08-08 11:48 UTC
Labels: Area-Rendering, Product-Conpty, Issue-Bug, In-PR, Priority-3

**Comment by OldWorldOrdr** [comment] 2022-12-01 01:22
i seem to have a similar issue
![Screenshot (4) edit](https://user-images.githubusercontent.com/57970114/204942696-1762b32a-3c02-4487-9580-d3ba6ec93301.png)

It's different on different font sizes.  The above screenshot is with a font size of 12, but with a font size of 13 the gaps disappear.

**Comment by zadjii-msft** [comment] 2022-12-05 15:28
@OldWorldOrdr Nah, that's more like, well, one of these: https://github.com/microsoft/terminal/issues?q=is%3Aissue+is%3Aopen+line+drawing

There's a few of those, so it's hard to point the finger at just one.
