### ISSUE TITLE
Cannot run WindowsTerminal.exe as other user from the Windows Store version

### ISSUE THREAD

**Issue by yllekz** [microsoft/terminal#3534] opened 2019-11-12 13:40 UTC
# Environment

```none
Windows build number: 10.0.18362.387
Windows Terminal version (if applicable): 0.6.2951.0

Any other software?
```

# Steps to reproduce
When I try to either engage "runas" on C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_0.6.2951.0_x64__8wekyb3d8bbwe\WindowsTerminal.exe or shift right click and "run as another user" on WindowsTerminal.exe, it gives me an error.

Can this be fixed? Or alternately, can a feature be built into Windows Terminal where you can relaunch as a different user?

# Expected behavior
App launches as the user I specify

# Actual behavior
The application will either a) reject my perfectly valid credentials (which work in other prompts), or b) give me an access denied error.

Runas:
Attempting to start C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_0.6.2951.0_x64__8wekyb3d8bbwe\WindowsTerminal.exe as user "domainname\otherusername" ...
RUNAS ERROR: Unable to run - C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_0.6.2951.0_x64__8wekyb3d8bbwe\WindowsTerminal.exe
5: Access is denied.

"Run as other user" GUI:
"Windows cannot access the specified device, path, or file. You may not have the appropriate permissions to access the item."

Unsure if this same issue happens on the non-Store version.

**Comment by DHowett-MSFT** [comment] 2019-11-14 20:40
Thanks for the report. This looks like a /dupe of #1032.

**Closed by DHowett-MSFT** 2019-11-14 20:40 UTC
Labels: Needs-Tag-Fix, Needs-Triage

**Comment by jflattery** [comment] 2020-02-14 13:34
> 
> 
> Thanks for the report. This looks like a /dupe of #1032.

I would argue this is not a dupe of #1032 as #1032 does not imply that the user account requesting the elevated window/tab is different than the admin user account. In my case, I have two accounts on my system. One account is my daily driver which is a standard user, the other is my admin account. With the current setup I am unable to elevate a tab or window in the terminal app, and need to revert to using powershell or cmd directly, which defeats the purpose of terminal.

**Comment by dejandjuranovic** [comment] 2020-05-08 12:50
> > Thanks for the report. This looks like a /dupe of #1032.
> 
> I would argue this is not a dupe of #1032 as #1032 does not imply that the user account requesting the elevated window/tab is different than the admin user account. In my case, I have two accounts on my system. One account is my daily driver which is a standard user, the other is my admin account. With the current setup I am unable to elevate a tab or window in the terminal app, and need to revert to using powershell or cmd directly, which defeats the purpose of terminal.
-----
I use the same scenario, two accounts on the same machine, one of them admin. Elevation works as long as the same profiles have the same version of Windows Terminal.
