### ISSUE TITLE
[FEATURE REQ:] - Would like to be able to screenshot a TAB into an image file.

### ISSUE THREAD

**Issue by RobFosterNYC** [microsoft/terminal#15147] opened 2023-04-09 19:18 UTC
As the title says.
I am requesting a feature for Terminal.

To be able to right click a TAB of my choosing and screenshot the tab into an image file.

Thank you.
😋

**Comment by j4james** [comment] 2023-04-10 10:09
See also #1084.

**Comment by zadjii-msft** [comment] 2023-04-10 14:21
I mean, yea I'm inclined to call this a dupe of 1084. Would you want this to screenshot the whole buffer? Or just the visible viewport?

There's also the "Export Buffer" action, for just exporting as .txt, and #469 for asciinema recordings

**Comment by RobFosterNYC** [comment] 2023-04-10 15:23
Just the part that is visible in the current tab being shown when using the Terminal,
to be saved as an image (.png)(.jpg)(.svg) NOT as text  please.

**Comment by lhecker** [comment] 2023-04-10 21:34
Coincidentally, I wrote all the code we need for saving a swap chain (the terminal contents) as a PNG in #14959. However, I don't think I personally will have any time soon to hook it up as a feature like this (nor any other team member most likely). If you or anyone else would like to see this through though, I'd be more than happy to guide them and explain how it could be done. 🙂

**Comment by jamespack** [comment] 2023-04-16 13:42
The code in wic.h? Cant seem to find that file in the current repo.

**Comment by j4james** [comment] 2023-04-16 21:06
> The code in wic.h? Cant seem to find that file in the current repo.

@jamespack That file was added in PR #14959, but that hasn't been merged into the main branch yet. You'll need to checkout the branch `dev/lhecker/atlas-engine-remastered`.

**Comment by jamespack** [comment] 2023-04-16 21:07
Ahh. Thanks.

**Comment by zadjii-msft** [comment] 2023-04-17 20:42
Alrighty thanks for the elaboration here. I'm gonna combine this with the feature request we're already tracking in /dup #1084, since they're largely the same idea. Thanks for the discussion all!

**Closed by zadjii-msft** 2023-04-17 20:42 UTC
Labels: Issue-Feature, Needs-Triage, Needs-Attention, Needs-Tag-Fix
