### ISSUE TITLE
Not working with chinese character input 

### ISSUE THREAD

**Issue by fengzhao** [microsoft/terminal#4097] opened 2020-01-02 15:06 UTC
Windows 10 2004

WSL2  ubuntu18.04 

Windows Terminal (Preview)
Version: 0.7.3451.0

I using WSL2 ubuntu18.04 on windows terminal , When i type ` with chinese character input . The windows terminal will auto appear many  .... 

just like this:

```
root@fengzhao-laptop:~# ············································································································································································································································^C
root@fengzhao-laptop:~#
root@fengzhao-laptop:~#
```

**Comment by zadjii-msft** [comment] 2020-01-02 15:50
Thanks for reporting this! This looks like it's a /dupe of #3706.

**Closed by zadjii-msft** 2020-01-02 15:50 UTC
Labels: Needs-Tag-Fix, Needs-Triage
