### ISSUE TITLE
Click on tab ... focus ...?

### ISSUE THREAD

**Issue by vefatica** [microsoft/terminal#8662] opened 2020-12-26 17:46 UTC
# Environment
Microsoft Windows 10 Pro for Workstations
10.0.19042.685 (2009, 20H2)
WindowsTerminalPreview_1.5.3242.0_x64
```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Windows Terminal version (if applicable):

Any other software?
```

# Steps to reproduce

When working in a shell in WT, left-click on the desktop, then left-click on the tab of the shell you were working in.

# Expected behavior

The shell in the clicked tab should have input focus; i.e., you can continue working there.

# Actual behavior
That shell does not get input focus.  

In contrast, if, after clicking the desktop, you click the tab of another shell in WT (one you were not working in) the shell of the clicked-on tab does get input focus.

It's annoying, especially since I consider the tab to be **THE** way to select the shell in which to work.

I figure this must be a duplicate.  I searched a little and came up with nothing.

**Comment by KalleOlaviNiemitalo** [comment] 2020-12-26 19:23
Perhaps <https://github.com/microsoft/terminal/issues/3609>.

**Comment by DHowett** [comment] 2020-12-26 21:00
Yes, this is a /dupe of #3609 and a second issue titled something like "focus moves weirdly ..."

**Closed by DHowett** 2020-12-26 21:00 UTC
Labels: Needs-Tag-Fix, Needs-Triage
