### ISSUE TITLE
Emoji displayed as "�" when inputted by the user

### ISSUE THREAD

**Issue by Jpe230** [microsoft/terminal#1565] opened 2019-06-24 21:49 UTC
# Environment
Microsoft Windows [Version 10.0.18362.175]
Windows Terminal 0.2.1715.0

# Steps to reproduce
Invoke the emoji panel with Win+. 
Click on desired emojis
Emojis are displayed as '�'

# Expected behavior

Emojis should not be displayed as '�'

# Actual behavior

Emojis are actually being rendered but if the user wants to type them is shows '�' 

![Annotation 2019-06-24 165106](https://user-images.githubusercontent.com/6202305/60054476-49498700-96a0-11e9-8a17-860c922dd5b3.png)

**Comment by ibuioli** [comment] 2019-06-24 22:37
Same version here, Its seem like a Bug with the codification, but its strange, depends the type of terminal. In WSL this work fine. In PowerShell the emojis just works when you print. In CMD some work others don't, and if you try to delete it sometimes the character is corrupt (fail the scale, or even print). Here a screenshot with the comparison:

![emoji_terminal](https://user-images.githubusercontent.com/7343538/60056486-735a7380-96b7-11e9-8fd9-466713ee02e0.png)

**Comment by Shorotshishir** [comment] 2019-06-25 05:05
### **64(+/-)  consecutive emoji crashes the terminal app.** 

32 ( 🐛🐛🐛🐛🐛🐛🐛🐛🐛🐛🐛🐛🐛🐛🐛🐛🐛🐛🐛🐛🐛🐛🐛🐛🐛🐛🐛🐛🐛🐛🐛 )

**try pasting or adding emojis to the terminal ,** 
- cmd doesn't render properly until a little nudge in the sizing.
- WSL renders properly
- Powershell Doesn't render at all

**hit Enter**

- cmd renders emojis, a little bit of resizing of the app crashes the app itself
- WSL renders properly, a little bit of resizing of the app crashes the app itself
- Powershell renders emojis, a little bit of resizing of the app crashes the app itself

**Comment by Shorotshishir** [comment] 2019-06-25 07:26
### Powershell Doesn't render first 32 ascii characters.
`Alt+1` to `Alt+32` and `Alt+127` (the control character set )renders �
rest of the ASCII characters render properly

**Comment by chrish619** [comment] 2019-06-25 10:48
When wrapping git bash, I encounter similar issues:
Git log output renders correctly
![image](https://user-images.githubusercontent.com/2427358/60092436-eb1fb100-973e-11e9-8afc-738ebf42b1c8.png)

But I cannot enter any emojis from the command line, seems to be an encoding, pass through problem..
![image](https://user-images.githubusercontent.com/2427358/60092518-1c987c80-973f-11e9-825f-71e715d39fa9.png)

**Comment by miniksa** [comment] 2019-06-27 22:26
Dupe of #1503

**Closed by miniksa** 2019-06-27 22:26 UTC
Labels: Needs-Tag-Fix, Needs-Triage
