### ISSUE TITLE
Prevent scrolling when scrolled up

### ISSUE THREAD

**Issue by mnpenner** [microsoft/terminal#4527] opened 2020-02-11 05:13 UTC
# Description of the new feature/enhancement

When running a long-running script, I sometimes scroll up to see something that whizzed by. Windows terminal keeps scrolling down by an amount equivalent to the new lines written (does not scroll all the way down to the bottom). I'd like it to not scroll at all if I've scrolled up even a little bit.

# Proposed technical implementation details (optional)

Not sure. You'll have to detect when we're scrolled all the way to the bottom to engage autoscroll, and then disable autoscroll when scrolled up.

Alternatively, a readily discoverable scroll-lock option would be acceptable. Perhaps by right-clicking the tab? I was so desperate I tried the "Scroll Lock" button on my keyboard hoping it would do something useful for the first time in my life (no luck).

**Comment by j4james** [comment] 2020-02-11 12:39
This sounds like a duplicate of #3863.

**Comment by zadjii-msft** [comment] 2020-02-11 18:34
Yea I'd definitely say that this is a /dup of #3863. Thanks!

**Closed by zadjii-msft** 2020-02-11 18:34 UTC
Labels: Issue-Feature, Needs-Tag-Fix, Needs-Triage
