### ISSUE TITLE
run as adminstrator

### ISSUE THREAD

**Issue by khoshroomahdi** [microsoft/terminal#3152] opened 2019-10-11 11:25 UTC
when i pin windows terminal to taskbar, i would like to have access to adminstrator mode.
please add run as aminstrator in right click on icon in taskbar
![Annotation 2019-10-11 145506](https://user-images.githubusercontent.com/20259070/66647956-29ca7000-ec37-11e9-841f-9e604c2d98ee.png)

**Comment by DHowett-MSFT** [comment] 2019-10-11 15:39
This is a /dupe of #1032. Also, right-click on Windows Terminal (Preview) again.

![image](https://user-images.githubusercontent.com/14316954/66665052-924b2a00-ec02-11e9-97c7-ece1c94dbfc9.png)

**Closed by DHowett-MSFT** 2019-10-11 15:39 UTC
Labels: Issue-Feature, Needs-Tag-Fix, Needs-Triage

**Comment by khoshroomahdi** [comment] 2019-10-11 15:51
No this is different.i said right click on taskbar.look at the picture.

**Comment by DHowett-MSFT** [comment] 2019-10-11 16:02
Regardless, if you right-click the name of the application again you’ll be able to access “run as administrator.”

**Comment by rewted** [comment] 2019-10-30 19:30
@khoshroomahdi 
Right click icon in taskbar -> Right click Windows Terminal (Preview) -> Left click run as administrator.

**Comment by xmha97** [comment] 2020-02-01 16:17
![Untitled](https://user-images.githubusercontent.com/23485114/73595251-4b43b600-44cb-11ea-9411-303e1e117d9e.png)
