### ISSUE TITLE
Identify new path without closing and reopening terminal

### ISSUE THREAD

**Issue by ghost1372** [microsoft/terminal#6882] opened 2020-07-12 10:31 UTC
If the terminal program is open and we install a command line software like NodeJS,
After installation, the commands of that program do not work Until we close the terminal program and open it again.

steps to reproduce
1.Open the terminal
2.Download and install the NodeJS application
3.In the terminal that is open, write the following command
`npm install hexo-cli -g`
4.As you can see, the NPM command Is not recognized
5.Close the terminal and open it again. Everything is working fine now

It would be great if new apps could be detected automatically, And there is no need to close and reopen the terminal.

**Comment by DHowett** [comment] 2020-07-12 21:01
Thanks for the report! This is a /dupe of #1125

**Closed by DHowett** 2020-07-12 21:01 UTC
Labels: Issue-Feature, Needs-Tag-Fix, Needs-Triage
