### ISSUE TITLE
Bug Report. Cannot type korean language to the console.

### ISSUE THREAD

**Issue by JuhoKang** [microsoft/terminal#2402] opened 2019-08-12 09:43 UTC
English is good but I can't type anything with Korean. I can copy and paste the text, but cannot type it. It feels like it just doesn't support Korean input. I can see text output so maybe it would not be a problem with fonts.

# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18362.267]
Windows Terminal version (if applicable): Windows Terminal (Preview) 0.3.2171.0
```

The font was Consolas.

# Steps to reproduce

1. Open any type of terminal. 
2. change system language like usual
  1. (with 한/영 key (language change key), or click the language change button on the taskbar)
3. write some text.

# Expected behavior

I can write Korean text to the terminal

# Actual behavior

I cannot write Korean text to the terminal

**Comment by fangjue** [comment] 2019-08-12 11:51
Duplicate of issue #2213.

**Comment by zadjii-msft** [comment] 2019-08-12 12:25
I'm inclined to agree this is a dupe of #2213, save for one bit: 

> 1. Open any type of terminal.

@JuhoKang does this not work with conhost (`cmd.exe`, `powershell.exe`, `wsl.exe`)? Or is this only happening with the Windows Terminal?

I _believe_ this scenario should work in conhost, and shouldn't have regressed recently.

**Comment by CookieHCl** [comment] 2019-08-12 15:44
@zadjii-msft I'm not author, but I have same issue.

**Comment by DHowett-MSFT** [comment] 2019-08-12 18:30
Okay, so this is #2213.

**Closed by DHowett-MSFT** 2019-08-12 18:30 UTC
Labels: Issue-Bug, Needs-Author-Feedback, Needs-Tag-Fix, Needs-Triage
