### ISSUE TITLE
Pasting text while in ssh session drops special characters

### ISSUE THREAD

**Issue by VitalyArtemiev** [microsoft/terminal#8398] opened 2020-11-25 11:56 UTC
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18363.1198]
Windows Terminal version: Windows Terminal Preview 1.5.3242.0 
OR 
Windows Terminal 1.4.3243.0
```
# Steps to reproduce
I expect this bug to be difficult to reproduce since I cannot find any mention of this behaviour anywhere despite being seemingly obvious on my machine. I can provide a video demonstration and necessary system config files if needed.

0. (Have a second language/keyboard layout installed? - not sure, but I have Russian lang and kb layout installed and have encountered similar issues in the past which seemed to be related to that )
1. Open Windows Terminal (freshly installed from MS Store)
2. ssh to remote linux server (tried both Ubuntu 16 and Raspbian on several machines)
3. Copy the following string:
> a{b}c[d]e-f*g/h~i`j%k^l$m#n@o"p'q\<r\>s
4. Paste the string into Terminal via right-click or Shift-Insert or Ctrl-Shift-V
5. Observe as the string turns into the following, losing a bunch of characters:

> abcde-f*g/hij%klmno"pqrs

# Expected behavior

I expect the text to remain the same.

# Actual behavior

Pasted text loses brackets, curly braces, single quotation marks, and other symbols, such as `<>^$#&~`.
Symbols can still be typed manually (even though I have encountered a bug in Terminal in the past where this was not the case).
Copy-pasting symbols from terminal works fine. 
Repeating the same steps in stand-alone cmd or powershell also works fine.

**Comment by DHowett** [comment] 2020-11-25 18:39
Thanks for the report! This looks like a /duplicate of https://github.com/PowerShell/Win32-OpenSSH/issues/1505, which is an issue in windows' ssh.exe. It's been fixed and the release is available on their github page.

**Closed by DHowett** 2020-11-25 18:39 UTC
Labels: Needs-Tag-Fix, Needs-Triage
