### ISSUE TITLE
Scrolling down in VIM scrolls up duplicated vim status lines

### ISSUE THREAD

**Issue by 0xd4d** [microsoft/terminal#5161] opened 2020-03-28 12:26 UTC
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18363.720]   
Windows Terminal version (if applicable): 0.10.781.0

vim for Windows (official git build): VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Jan 16 2020 08:26:10)
```

# Steps to reproduce

- Start vim: `vim` (the one that comes with `git version 2.26.0.windows.1`)
- Press `i`
- Press `ENTER` until it starts scrolling the screen
- (to exit vim): `ESC` and then type `:q!` and then `ENTER` 😄

# Expected behavior

The status line stays where it's supposed to be, at the bottom of the screen.

# Actual behavior

Every time a the screen is scrolled down, the last line (white status line) is scrolled up, and a new white status line is printed at the bottom. This results in two white lines, then 3, etc...

This does not reproduce if I use the old cmd.exe (started by eg. Explorer, not wt.exe)

**Comment by avysk** [comment] 2020-03-29 10:24
I can reproduce this with vim which comes with git; if I use vim-tux build from chocolatey, it works normally.

**Comment by 0xd4d** [comment] 2020-03-31 17:26
Does vim-tux have a status line with a white background? If it's the same color as the background, you won't see it.

**Comment by avysk** [comment] 2020-03-31 17:47
> Does vim-tux have a status line with a white background?

Yes.

![image](https://user-images.githubusercontent.com/130091/78058330-cec93880-7390-11ea-9dfc-104746c30bf6.png)

**Comment by avysk** [comment] 2020-03-31 17:48
...and here's git vim (notice that it's broken in some other way as well):
![image](https://user-images.githubusercontent.com/130091/78058456-fddfaa00-7390-11ea-866a-d7338e7cbfb3.png)

**Comment by DHowett-MSFT** [comment] 2020-04-03 05:47
Well would you look at that, it reproduces immediately.

The behavior is slightly different on 0.11-pre: the line occasionally flickers, or the cursor jumps below the line, but it doesn't get copied onto the screen repeatedly. It's probably impacted by #5181.

Idly, I wonder if this bug will go away when git-for-windows updates to cygwin >3.1, which changes how VT is parsed.

**Comment by DHowett-MSFT** [comment] 2020-04-03 05:56
@zadjii-msft this is one to keep an eye on: Git Vim isn't _using_ vt, but this seems like another deferred newline issue. It looks like it's fixed with #5181, but I only have your not-latest changes and we need to make sure it doesn't regress.

Simple repro: run `\program files\git\bin\bash -li` then `vim`. press `i` and hit enter until it goes off the bottom of the screen.

0.10 pty tap on top, 0.11 on bottom

```
                                       BAD LF HERE, no other diff
                                       V
␛[m␛[?25l␛[30;1H␛[?25h␛[?25l␛[30m␛[107m␊␛[m␛[28;1H␛[30m␛[107m␍␊[No␣Name][+]␣[unix]␣(15:59␣31/12/1969)␣␣␣␣␣␣␣␣␣␣␣␣30,1␣Bot␛[97m␛[49m--␣INSERT␣--␛[K␛[28;1H␛[?25h
␛[m␛[?25l␛[30;1H␛[?25h␛[?25l␛[30m␛[107m␛[m␛[28;1H␛[30m␛[107m␍␊[No␣Name][+]␣[unix]␣(15:59␣31/12/1969)␣␣␣␣␣␣␣␣␣␣␣␣30,1␣Bot␛[97m␛[49m--␣INSERT␣--␛[K␛[28;1H␛[?25h
```

weird thing is, it prints the lf before it goes and strikes the status line again...

**Comment by zadjii-msft** [comment] 2020-04-03 15:12
Oh shoot this isn't fixed in my latest changes, but I'll try and make a repro case for this.

**Comment by PistachioCake** [comment] 2020-04-03 18:10
I'm so glad I found this here, I've been trying to solve this for weeks and am new to the whole open-source thing 😅

To add: I could not reproduce this issue using Ubuntu WSL and its associated vim (version 8.0.1453), but it does occur in git bash with its associated vim (version 8.1.2292). It does not occur when either are run as individual processes, not through Windows Terminal.

**Closed** 2020-04-09 00:06 UTC
Labels: Area-Output, In-PR, Issue-Bug, Product-Conpty
