### ISSUE TITLE
Providing command-line arguments to a profile makes the terminal crash

### ISSUE THREAD

**Issue by ClementNerma** [microsoft/terminal#9536] opened 2021-03-18 10:31 UTC
# Environment

```none
Windows build number: 19042.868
Windows Terminal version (if applicable): 1.7.572.0
```

# Steps to reproduce

```bash
wt -p "PowerShell" # Works

wt -p "PowerShell" pause # Closes immediatly
wt -p "PowerShell" -- pause # Same
wt -p "PowerShell" "-- pause" # Same
```

# Expected behavior

The `pause` command provided to PowerShell should be executed normally, according to the documentation.

# Actual behavior

The window closes immediatly if an additional argument is provided to the selected profile.

**Comment by zadjii-msft** [comment] 2021-03-18 11:24
Interesting. Could you share your settings? I'm interested on the `closeOnExit` setting specifically - I'm betting that commandline isn't valid and the connection is closing immediately, which is causing the tab to close immediately, which is then closing the window.

**Comment by ClementNerma** [comment] 2021-03-18 13:25
Indeed, I set it to `closeOnExit: "always"`. When I remove it, I get an error `0x80070002`.

Seems like it's caused by the fact PowerShell cannot launch commands but only executables files directly. When I replace `read` with `cmd.exe` everything works fine.

Maybe there could be a quick mention in the docs?

**EDIT :** That being said running `wt -p "<ProfileName>"` works fine but `wt -p "<ProfileName>" "binary"` does not launch the binary inside the requested profile (I get the same error if I put `/bin/ls` with my WSL profile)

**Comment by DHowett** [comment] 2021-03-18 14:54
So, this is more on Terminal’s side. We take the new commandline to be _the path to an executable, plus its arguments_ to be run inside the terminal (incidentally, this is why /bin/ls isn’t valid). There isn’t currently a way to specify “run the thing identified by the profile, but tell it to run the following command”... because the way to do that differs between shells. I believe we have a workitem tracking this. We need to figure out a way to make this possible, as it keeps biting people.

**Comment by zadjii-msft** [comment] 2021-03-18 15:00
So the "Add support for appending a commandline to a profile's commandline" is trackeed over in #5528. I suppose this thread has generally become a duplicate of that discussion, so we can merge the two. 

/dup #5528

**Closed by zadjii-msft** 2021-03-18 15:00 UTC
Labels: Needs-Attention, Needs-Tag-Fix, Needs-Triage
