### ISSUE TITLE
White line at the bottom of the frame in dark mode

### ISSUE THREAD

**Issue by Stanzilla** [microsoft/terminal#3302] opened 2019-10-23 21:55 UTC
# Environment

```none
Windows build number: [Version 10.0.19002.1002]
Windows Terminal version (if applicable): Version: 0.6.2951.0

Any other software?
```

# Steps to reproduce

Use the dark theme of Windows Terminal

# Expected behavior

No white line at the bottom of the window

# Actual behavior

a small white line at the bottom of the window

![image](https://user-images.githubusercontent.com/75278/67437108-5f386b80-f5f0-11e9-8a68-ec62edc0d2c1.png)

**Comment by DHowett-MSFT** [comment] 2019-10-23 22:10
Thanks! This is a /dupe of #3064

**Closed by DHowett-MSFT** 2019-10-23 22:10 UTC
Labels: Needs-Tag-Fix, Needs-Triage

**Comment by Stanzilla** [comment] 2019-10-23 22:13
Dangit, I swear I searched https://github.com/microsoft/terminal/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+white+line Doesn't list it, I blame GitHub! :)
