### ISSUE TITLE
Pane navigation focuses the wrong pane

### ISSUE THREAD

**Issue by sinapis** [microsoft/terminal#5744] opened 2020-05-04 23:35 UTC
# Environment

```none
Windows build number: 10.0.19041.0
Windows Terminal version: 0.11.1191.0
```

# Steps to reproduce

Create a 4 pane layout, like this:
![image](https://user-images.githubusercontent.com/15230040/81022963-aa70e800-8e77-11ea-8fbc-3498ea6801b0.png)

try to navigate from left bottom pane to right bottom pane with the shortcut alt+right arrow

# Expected behavior
focus moves to bottom right pane

# Actual behavior
focus moves to top-right pane.

same weird behavior also happens when you try to navigate from bottom-right to bottom-left using alt+left arrow. I took a recording of the issue:
![2020-05-05 02-18-04](https://user-images.githubusercontent.com/15230040/81023364-c6c15480-8e78-11ea-8220-a8843003289b.gif)

**Comment by DHowett-MSFT** [comment] 2020-05-05 01:01
Thanks for the report! This is a /dupe of #2398. :smile:

**Closed by DHowett-MSFT** 2020-05-05 01:02 UTC
Labels: Needs-Tag-Fix, Needs-Triage
