### ISSUE TITLE
Clicking on a tab that's already active loses focus

### ISSUE THREAD

**Issue by warpdesign** [microsoft/Terminal#616] opened 2019-05-09 08:06 UTC
Repro:
1. click `+` to open a new tab
2. type something: it's written in the console (as expected)
3. click on the tab that's already active
4. type something

Nothing is written: keyboard focus has been lost.

**Comment by warpdesign** [comment] 2019-05-09 08:08
Also: if the terminal window is inactive, clicking on the active tab to activate it exhibits the same problem: typing won't work.

**Comment by Paul-Weisser** [comment] 2019-05-09 13:18
dupe of #528

**Comment by zadjii-msft** [comment] 2019-05-09 14:29
Yea, I'm inclined to agree this is a dupe of #528.

**Closed by zadjii-msft** 2019-05-09 14:29 UTC
