### ISSUE TITLE
Snapping window to left side of right screen loses part of first character column

### ISSUE THREAD

**Issue by patridge** [microsoft/terminal#3528] opened 2019-11-11 20:41 UTC
# Environment

```none
Windows build number: 10.0.18362.0
Windows Terminal version (if applicable): 0.6.2951.0

Display setup:
Left: Surface Book 1, 3000x2000 @ 200%
Right: Ultrawide, 3440x1440 @ 100%
```

# Steps to reproduce

1. Launch Terminal, move to right display
1. Maximize on right display with Win+Up
1. Set to left half of right display with Win+Left

# Expected behavior

The Terminal window should be completely contained within the left half of the right display.

# Actual behavior

The Terminal window will have the left-most chrome border and some of the console output on the left screen.

A screenshot of this is tough, but notice that the border is overlapping the adjacent scroll bar that is maximized on the left display here.

![Screenshot of overlap between a Terminal window set to use the left half of a right-hand display and the window adjacent to the left that is maximized to take up the full left display](https://user-images.githubusercontent.com/713665/68619303-78626880-0488-11ea-93d0-433818562cfc.png)

## Workaround hack

Once the window is consuming half the screen, you can send it to the other displays left half with Win+Shift+Left/+Right. Then, sending it back to the original, right display with Win+Shift+Left/+Right will cause it to fit where expected.

Here is that same section of adjacent windows after the workaround, showing no overlap on the scrollbar.

![Screenshot showing no overlap between Terminal and left-adjacent window after following workaround steps](https://user-images.githubusercontent.com/713665/68619424-b3649c00-0488-11ea-929a-5d36608b0a73.png)

**Comment by miniksa** [comment] 2019-11-11 20:51
This looks like a /dupe of #3394. A bunch of stuff related to the border and the pixel counts around the edge was fixed there. If this still happens against `master` or against v0.7 when it comes out, please reactivate then.

**Closed by miniksa** 2019-11-11 20:51 UTC
Labels: Needs-Tag-Fix, Needs-Triage
