### ISSUE TITLE
Terminal output missing (beyond upper left 1/4) - when fullscreen over RDP and disconnect/connect - leave fullscreen usually fixes output

### ISSUE THREAD

**Issue by g0t4** [microsoft/terminal#11336] opened 2021-09-26 11:22 UTC
### Windows Terminal version (or Windows build number)

10.0.22000.194, 1.11.2421.0

### Other Software

I've tried this with different shells:
PowerShell (desktop edition)
PowerShell (core) 7.1 and 7.2 preview
WSL - Official Ubuntu distro

Doesn't seem to matter what shell is running inside the terminal tab. 

My machine is Win 11 (latest build) 

I've tested both latest stable Windows Terminal 1.10.2383.0 and Preview 1.11.2421.0

### Steps to reproduce

1. Connect over RDP (haven't tested a local connection) - from a mac in my case
2. Open Windows Terminal
3. Enter Fullscreen window size (alt+enter)
4. (optional) run a command that produces output (beyond just the upper left quadrant of screen)
5. Disconnect RDP (in my case I use Cmd+W on my Mac)
6. Connect RDP (right away is fine, no need to wait)
7. Only top left quadrant of content shows
- Even new running commands--after RDP reconnect, when only the top left quadrant shows--don't show output beyond top left quadrant
8. Leave fullscreen and re-enter fullscreen to fix this, sometimes I have to change window size too (after leaving fullscreen and before reentering fullscreen).

This doesn't happen with other window sizes in my experience (ie maximized but not fullscreen doesn't trigger the issue). 

### Expected Behavior

Windows Terminal Output would remain the same. Like it does when the window is maximized (not fullscreen).

### Actual Behavior

Only the top left quadrant shows until I leave/reenter fullscreen (alt+enter).

Before RDP disconnect: (Preview 1.11)
![image](https://user-images.githubusercontent.com/180189/134805383-d750de0d-9ed9-4b08-8b43-d775036f76c8.png)

After RDP reconnect: (Preview)
![image](https://user-images.githubusercontent.com/180189/134805475-3194fcce-d647-489b-bd78-37f4914627d5.png)

WSL - After RDP reconnect: (Preview)
![image](https://user-images.githubusercontent.com/180189/134805510-b830fc19-cd30-40e5-bac1-1be1fbf618d1.png)

WSL - After fixing (leave/re-enter fullscreen): (Preview)
![image](https://user-images.githubusercontent.com/180189/134805538-51ab28b6-4f2a-419e-ab46-b07fb39a8980.png)

Stable Windows Terminal build - After RDP reconnect:
![image](https://user-images.githubusercontent.com/180189/134805567-3c1d3bbf-479a-4e56-a7f7-54f6f71f3bf2.png)

**Comment by mkke** [comment] 2021-09-27 09:02
I have the same effect on my machine, I'm also connecting via RDP from a Mac.
For me it's also happening with windows that aren't full-screen.
Enabling full-screen updates or software rendering makes no difference.
I'm on Windows 10 20H2 19042.1237. Terminal 1.11.2421.0.

**Comment by DanielNesbitt** [comment] 2022-01-20 12:16
The issue does seem to be DPI scaling related. I was able to reproduce this just by changing the DPI scaling.

At 150%:
![image](https://user-images.githubusercontent.com/377432/150336447-b55be5a9-ce67-49cf-aa9f-d2fa43c386dc.png)

At 200%
![image](https://user-images.githubusercontent.com/377432/150336549-80a5700b-2aa3-472a-80ce-0485c0101e30.png)

The output that is missing seems to depend on the difference in scaling. I suspect that RDP goes through a DPI switch even if the scaling factor on both machines is the same. In my case, I noticed this problem when using RDP between two Windows 10 machines with 150% scaling.

**Comment by zadjii-msft** [comment] 2022-02-17 15:07
I'm putting this in 1.14 cause it looks like it's just a variation on https://github.com/microsoft/terminal/issues/11317. Any chance you could share your [settings.json file](https://github.com/microsoft/terminal/wiki/Frequently-Asked-Questions-(FAQ)#where-can-i-find-the-settings-file)? Seemingly, this has to do with certain font sizes & faces, so more data can't hurt.

**Comment by DanielNesbitt** [comment] 2022-02-17 15:32
Here is my [profile](https://github.com/microsoft/terminal/files/8089921/settings.txt). I am using a custom font style.

**Comment by DHowett** [comment] 2022-02-17 20:17
(Thanks for all the info!)

I'm gonna tentatively call this a duplicate of #11317 and concentrate our DPI bugs over there. I'm alarmed that this regressed. :smile:

**Closed** 2022-02-18 17:39 UTC
Labels: Area-Rendering, Issue-Bug, Product-Terminal, Priority-3
