### ISSUE TITLE
Slow memory leak in Windows Terminal

### ISSUE THREAD

**Issue by Treit** [microsoft/terminal#14588] opened 2022-12-21 00:22 UTC
### Windows Terminal version

 1.16.3464.0

### Windows build number

10.0.25272.0

### Other Software

There appears to be a slow memory leak in Windows Terminal.

I was running my small [Terminal Stress](https://github.com/Treit/TerminalStress) app that I have used to find other bugs in the past. I accidentally left it running overnight and when I came in the next morning I found WindowsTerminal was consuming a large amount of memory.

This appears to be reproducible by simply running the Terminal Stress app (a simple .NET console application) and letting it run.

### Steps to reproduce

1. Build [Terminal Stress](https://github.com/Treit/TerminalStress) and run it from a terminal window.

2. Let it run for a long time.

3. Observe that the memory usage for Windows Terminal climbs slowly.

4. Eventually stop the program from running.

5. Note that the memory usage (commit size) remains high.

### Expected Behavior

Memory usage should remain relatively flat as the test program simply prints random characters to random positions on the screen.

### Actual Behavior

The memory increases, quite slowly but surely.

In my most recent case I found the memory usage was more than 3GB after the stress program had run for about 20 hours.

**Comment by aqc-carlodri** [comment] 2023-01-26 09:38
I'm stumbling into a very similar issue, I have some applications running inside Windows Terminal and a see a very slow but steady increase in memory usage

**Comment by HaroldStruwig** [comment] 2023-03-20 13:45
I also experienced this - unusable for me until fixed - normal powershell does not have this issue

**Comment by zadjii-msft** [comment] 2023-04-04 21:38
Guh, my debugging tools are proving pretty useless. Me testing on 1.16, with atlas disabled:

Of the 5300 allocations, 2000 were attributed to useless nvwgf frames. 

![Image](https://user-images.githubusercontent.com/18356694/229927333-8cf5036b-f24c-4fdf-bdf8-19002f61f0e5.png)

A bunch more in d2d1:


![Image](https://user-images.githubusercontent.com/18356694/229927891-7e99ea4c-319e-48d6-bef3-ab1f67846cab.png)



Presumably that's all due to the DxEngine being enabled, not the Atlas engine. I wonder if Atlas has the same issue...


<hr>

There also were a smaller number of allocations in the path for `CodepointWidthDetector::_lookupGlyphWidthWithCache`. That kinda makes sense - we're allocating new cache entries for the glyph widths. TerminalStress just generates random codepoints, so it kinda makes sense that would grow the cache size. That would be pretty slow I'd imagine...

**Comment by lhecker** [comment] 2023-04-17 12:31
At the default font size on a 4K display you get an upper bound of pretty much exactly 3000 glyphs in the texture atlas of the text renderer. Beyond that I don't really see a persistent memory growth, but I get the feeling that we might be seeing the effects of severe memory fragmentation because the LRU hashmap in AtlasEngine is crudely built around a linked lists where each item is heap allocated. With TerminalStress we get up to hundreds of thousands of such allocations per second.

**Comment by dglee42** [comment] 2023-06-21 19:10
I've had this memory leak problem in Terminal for months on a fully updated (OS and Store apps) Windows 10 Dell. I routinely run a WSL tab and one or two cmd+ssh tabs, but the problem occurs even with just one active tab.

Perhaps interesting though: I use a screen reader, being a blind Windows user. I usually use JAWS (https://www.freedomscientific.com) but have also used NVDA and Narrator. Experiments today seem to indicate, though not solidly yet, that the Terminal expansion is fastest with JAWS, next slower with Narrator, and slowest with NVDA. This makes me wonder if there's a relationship between the memory leak and support for assistive technology for blind users. The relative infrequency of complaints I see about this leak, coupled with the popularity of Terminal and my complete lack of success preventing the expansion, also makes me wonder this.

It is very uncommon for me to go a full day of Terminal use without my Terminal instance needing a restart because of its size exceeding 1 or 1.5 gig of memory.

Unfortunately, it would likely be hard for me to provide a memory dump because I process many things in terminal windows that might be considered private (mail, development projects, research, etc.).

**Comment by zadjii-msft** [comment] 2023-09-18 21:19
This might just be fixed in 1.18. @lhecker double check me?

**Comment by lhecker** [comment] 2023-09-18 21:29
Yeah, the memory allocations in the new AtlasEngine are much much simpler. It can still grow fairly large when you have a 500x200 terminal with 100k unique glyphs, but it's much less likely to leak now. There'll be more improvements in 1.20 on top of that (https://github.com/microsoft/terminal/tree/dev/lhecker/atlasengine-cleanup-drawglyph).

**Comment by HaroldStruwig** [comment] 2023-09-20 09:14
> This might just be fixed in 1.18. @lhecker double check me?

Any idea when 1.18 will be released as latest stable version?

**Comment by zadjii-msft** [comment] 2023-09-20 11:33
> Any idea when 1.18 will be released as latest stable version

Probably later this month, though, preview builds are usually quite stable too (if this is affecting you acutely)

**Comment by lhecker** [comment] 2023-09-20 16:18
I can't reproduce a leak in either 1.17.12191.0 or 1.19.2412.0 after letting it run for about 1h, but the memory usage both fluctuates and rises much faster in 1.17 compared to 1.18/1.19 with the new renderer.

Probably fixed in at least 1.18? I'll close it for now. It's difficult to be certain about this though without a consistent/immediate repro. 😥

**Closed by lhecker** 2023-09-20 16:18 UTC
Labels: Area-Output, Issue-Bug, Product-Terminal

**Comment by greatquux** [comment] 2025-07-10 20:26
Memory leaks for me in the latest 1.22 version on Server 2025 but only if I leave it open with Get-Content and -Wait following a log file.  No idea why!

**Comment by DHowett** [comment] 2025-07-10 21:41
@greatquux Can you collect a dump, and please file a new issue? This one is from almost three years ago, and it is unlikely that it shares a root cause.
