### ISSUE TITLE
Random text glitches when using WSL1 

### ISSUE THREAD

**Issue by BitTheByte** [microsoft/terminal#5838] opened 2020-05-11 04:47 UTC
# Environment

```none
Windows build number: Version 10.0.19041.207
Windows Terminal version (if applicable): Version: 0.11.1251.0
GPU0: Intel UHD Graphics 630 | Driver: 26.20.100.7637
GPU1: Nivida GTX 1060 6GB | Driver: 445.87
```

# Steps to reproduce
1) Open a new tab with "Ubuntu" on WSL1
2) Type any command e.g(ls)
3) Wait for 2 or 3 seconds

# Behavior
The text starts to break and glitch out. I've had this problem before with VS CODE and was fixed by disabling GPU acceleration  
![](https://i.ibb.co/tBXsrWc/image.png)

**Comment by DHowett-MSFT** [comment] 2020-05-11 05:42
Thanks for the report! This looks like a /dupe of #5759.

Do you have "Conservative Morphological Anti-Aliasing" turned on in the Intel driver settings?

**Closed by DHowett-MSFT** 2020-05-11 05:42 UTC
Labels: Needs-Tag-Fix, Needs-Triage

**Comment by BitTheByte** [comment] 2020-05-11 06:13
Thanks @DHowett-MSFT for the fast response. this was actually fixed by disabling `Image sharpening` at Nivida control panel
