### ISSUE TITLE
v0.11.1121.0 starts powershell by default

### ISSUE THREAD

**Issue by nabieasaurus** [microsoft/terminal#5512] opened 2020-04-23 21:20 UTC
# Environment

```none
Microsoft Windows [Version 10.0.19037.1]
Windows Terminal version (if applicable): v0.11.1121.0
```

# Steps to reproduce

Just launch the new version after update from store

# Expected behavior

Should open the default shell in my case it is set to cmd.exe

# Actual behavior

Open the powershell tab. What is surprising is that it open the powershell tab even when I remove the powershell from my settings.json profiles.

**Comment by DHowett-MSFT** [comment] 2020-04-23 21:30
Thanks! This is a /dupe of #5458

**Closed by DHowett-MSFT** 2020-04-23 21:30 UTC
Labels: Needs-Tag-Fix, Needs-Triage
