### ISSUE TITLE
Maximized/Fullscreen terminal window doesn't fully fill screen when Windows Taskbar is hidden

### ISSUE THREAD

**Issue by edytzaler** [microsoft/terminal#16336] opened 2023-11-18 08:17 UTC
### Windows Terminal version

1.18.2822.0

### Windows build number

10.0.22621.2715

### Steps to reproduce

With the Windows taskbar set to automatically hide and "Hide The Title Bar" enabled in appearance settings, the terminal window doesn't fill the entire screen when fullscreen or maximized. This does not happen when either the windows taskbar or the terminal title bar are enabled.

I also recommend having something high contrast in the background when reproducing as it's hard to spot without.

### Expected Behavior

Terminal window fully covers screen in fullscreen (screenshot with terminal in fullscreen with "Hide The Title Bar" off and hidden Windows taskbar)
![image](https://github.com/microsoft/terminal/assets/124898629/12e7cebb-23cf-4166-ba01-ffd29776fe2c)

### Actual Behavior

Terminal window has a gap at the bottom where part of my desktop background can be seen (screenshot with terminal in fullscreen with "Hide The Title Bar" on and hidden Windows taskbar)
![image](https://github.com/microsoft/terminal/assets/124898629/a26c648c-ddde-4407-8497-d3a1aec8fa27)

**Comment by j4james** [comment] 2023-11-25 15:44
I believe this is a duplicate of #12959 (see also #15145 and #15633).

**Comment by lhecker** [comment] 2023-11-27 16:14
Thanks for linking the issue! I agree that this is effectively the same as #12959 and I'll mark this issue as a duplicate. /dup #12959

**Closed** 2023-11-27 16:14 UTC
Labels: Issue-Bug
