### ISSUE TITLE
Powerline arrow color and acrylic transparency

### ISSUE THREAD

**Issue by ksawerykarwacki** [microsoft/terminal#2418] opened 2019-08-13 10:51 UTC
It is probably not a bug but just needs some workaround. I'm using latest fast ring windows 10 with latest terminal and latest preview of powershell core.

If I set background color for Write-Host as black it is treated as transparency. Foreground is treated as pure black and ignores transparency. I am not sure how to set transparency of foreground in Powershell Core but this but this makes powerline arrow black instead of background color (grayish transparent). This works correctly on old opacity of conhost and conemu so there should be some way to make foreground transparent.

**Comment by zadjii-msft** [comment] 2019-08-13 14:03
I'm almost certain this is a dupe of #293

**Closed by zadjii-msft** 2019-08-13 14:03 UTC
Labels: Needs-Tag-Fix, Needs-Triage
