### ISSUE TITLE
Profiles should be available from task bar hover, start menu

### ISSUE THREAD

**Issue by fitzgeraldsteele** [microsoft/terminal#5106] opened 2020-03-24 19:35 UTC
# Description of the new feature/enhancement
Profiles that I have created should show up in the Terminal task bar context menu. 

When I right click on the Terminal icon I have pinned to the taskbar, I would like to see a menu that shows either profiles I have used recently, or all my profiles. Similar to how when I right click on the Word icon in the task bar, I get a list of my most recent documents.

Similar for the start menu

# Proposed technical implementation details (optional)

**Comment by DHowett-MSFT** [comment] 2020-03-24 19:36
This is a /dupe of #576; please make sure to search before filing a new issue!

**Closed by DHowett-MSFT** 2020-03-24 19:36 UTC
Labels: Issue-Feature, Needs-Tag-Fix, Needs-Triage
