### ISSUE TITLE
Needs to input twice to insert a single Chinese symbol

### ISSUE THREAD

**Issue by hez2010** [microsoft/terminal#3745] opened 2019-11-27 14:00 UTC
# Environment

```none
Windows build number: 18363.476
Windows Terminal version (if applicable): 0.7.3291.0
```

# Steps to reproduce
1. switch to Microsoft Chinese Input Method
2. press `shift` + `/` to insert a Chinese `？`

# Expected behavior
`？` successfully inserted

# Actual behavior
I have to press `shift` + `/` twice to insert a single `？`

Same problem with other Chinese symbols, such as `《`, `》`, `【`, `】` and etc.

**Comment by spindensity** [comment] 2019-11-28 01:43
Same problem here, need to press the corresponding key twice to input one Chinese punctuation.

Windows terminal 0.7.3291.0

**Comment by mkitzan** [comment] 2019-11-30 21:41
I found an interesting pattern when repro-ing this issue. The double-input behavior can be repro-ed with any character by performing the following:
- Set language to Chinese
- Open new WT instance
- Enter question mark (this first question mark should print to screen fine)
- Enter any character (this character will not be printed to screen)
- Enter any character (this character will be printed to screen)

Based off this behavior, it appears that after entering certain characters (like question mark), WT is in a buggy state which on transition out of that state the character is consumed and not printed. I wonder if the issue is in one of the `StateMachine` classes. Interesting to note that this is not a problem with the Japanese language package.

**Comment by mkitzan** [comment] 2019-11-30 22:59
The "？" using the Chinese language package is "wide" (take two grid cells to print), and I've been able to repro the behavior of this issue by initiating the process with another wide character like "。". An out-of-bounds exception is thrown which seems to be causing the text not to print. Make me think the wide characteristic of the symbol is causing the issue.
```
Exception thrown at 0x00007FFB872CA839 in WindowsTerminal.exe: Microsoft C++ exception: std::out_of_range at memory location 0x0000005CE78FE150.
Exception thrown at 0x00007FFB872CA839 in WindowsTerminal.exe: Microsoft C++ exception: [rethrow] at memory location 0x0000000000000000.
C:\GitHub\terminal-fork\src\cascadia\TerminalControl\TSFInputControl.cpp(328)\TerminalControl.dll!00007FFB46C165CD: (caller: 00007FFB46BE1CAD) LogHr(1) tid(42cc) 8000000B The operation attempted to access data outside the valid range
    Msg:[std::exception: invalid string position] 
```

**Comment by mkitzan** [comment] 2019-12-01 21:18
The actual call to [`NotifyTextChanged`](https://github.com/microsoft/terminal/blob/master/src/cascadia/TerminalControl/TSFInputControl.cpp#L227) appears malformed because the first argument should be the modified range ie the entire `_inputBuffer` range. However, the corrected function call still doesn't update the `CoreTextEditContext` server. I wonder if `NotifyTextChanged` can only be called outside of a `CoreTextEditContext` handler.

**Comment by mkitzan** [comment] 2019-12-02 02:55
Because `CoreTextEditContext` is not behaving as expected, could just implement the Caret and Selection ourselves and use the `CoreTextEditContext` events to receive text and composition start/complete signals. It would be pretty hacky, but I haven't been able to find a clean fix. Maybe someone who has more experience with UWP custom text input would have some insight into a solution.

**Comment by zadjii-msft** [comment] 2019-12-02 14:56
@mkitzan thanks for the investigation! I'm pretty sure that @philnach might be interested in your findings

**Comment by lhecker** [comment] 2020-01-06 23:55
@zadjii-msft If you change this: https://github.com/microsoft/terminal/blob/488291749994822ef54ba5140c7726b6d984116f/src/cascadia/TerminalControl/TSFInputControl.cpp#L227-L228
...into this:
```cpp
_editContext.NotifyFocusLeave();
_editContext.NotifyTextChanged(emptyTextRange, 0, emptyTextRange);
_editContext.NotifyFocusEnter();
```

...this issue and #3706 (and others?) should be fixed. 🙂 And #3645 is probably void too, because it seems to work even if you comment this out: https://github.com/microsoft/terminal/blob/488291749994822ef54ba5140c7726b6d984116f/src/cascadia/TerminalControl/TSFInputControl.cpp#L107

Would you like me to submit a PR tomorrow?

**Comment by zadjii-msft** [comment] 2020-01-07 13:43
@lhecker I would _love_ a PR from you 😄

**Comment by lhecker** [comment] 2020-01-07 13:56
Oh I just noticed that `NotifyTextChanged` is being used incorrectly anyways. The first argument is supposed to be the range that's modified. In this case it would be `[0, the_previous_buffer_length]` instead of `[0, 0]`. I'll try fixing this later today.

**Comment by zadjii-msft** [comment] 2020-01-08 18:11
Wait though we're not sure this is fixed, but the others were

**Comment by spindensity** [comment] 2020-01-14 17:22
The problem is still here.

Windows terminal v0.8.10091.0

**Comment by zadjii-msft** [comment] 2020-01-14 17:29
Welp the bot got confused here.

**Comment by lhecker** [comment] 2020-01-14 18:05
Sorry for your troubles @zadjii-msft. And I'm sorry for causing this confusion.
I commited [my changes](https://github.com/microsoft/terminal/pull/4140) as "Fixes/Closes #3745", as I was unable to reproduce this issue with my changes.
It turned out though that this issue simply doesn't happen anymore in an upcoming Windows version - Windows 20H1 - set to be released in spring this year and a version I'm already using on my PC (through the Windows Insiders Program). Older versions still have this issue, which is why it was reopened.

**Comment by leonMSFT** [comment] 2020-03-04 19:36
I'd be curious to see if this still repros considering #4688 and #4796 should have alleviated this issue (I think). I personally can't seem to repro it anymore, so I'll ask others to try it out and if this doesn't seem to occur anymore, I'll close the issue!

**Comment by zyy1998** [comment] 2020-03-05 00:29
> I'd be curious to see if this still repros considering #4688 and #4796 should have alleviated this issue (I think). I personally can't seem to repro it anymore, so I'll ask others to try it out and if this doesn't seem to occur anymore, I'll close the issue!

Actually when I upgraded my system to 10.0.19564.0 preview version， this issue disappeared.

**Comment by leonMSFT** [comment] 2020-03-12 15:28
Thanks for the confirmation! I've also checked on one of my machines running an older version of windows and I can repro, but once I'm on a newer build, it doesn't repro anymore. I've also checked with some other members of the team and they can't repro either, so I'll go ahead and close this one.

**Closed by leonMSFT** 2020-03-12 15:28 UTC
Labels: Area-TerminalControl, Help-Wanted, Issue-Bug, Priority-1, Product-Terminal, v1-Scrubbed

**Comment by Lemmingh** [comment] 2020-03-19 10:53
After upgrading Terminal to version 0.10.761.0, the problem also disappears on Windows Version 1909.

---

```
Windows build number: 10.0.18363.720
Windows Terminal version: 0.10.761.0

IME: Microsoft Pinyin
```
