### ISSUE TITLE
Windows Terminal window becomes unstable after loss/restore of display

### ISSUE THREAD

**Issue by riverar** [microsoft/terminal#3648] opened 2019-11-21 00:27 UTC
Windows 10, 1909 10.0.18363.476
Windows Terminal 0.6.2951.0

Repro steps:
1. Open Windows Terminal on display 1
2. Unplug display 1 and replug
3. Observe:
    * Windows Terminal dimensions have changed
    * Windows Terminal titlebar, control box, and window border are transparent/missing
    * Windows Terminal tab overflow no longer works correctly (i.e. starts overflowing before reaching the end of the titlebar)

This affects users in KVM scenarios.

![image](https://user-images.githubusercontent.com/475132/69289661-1c978e00-0bb2-11ea-9c78-fd1b978ec962.png)

**Comment by j4james** [comment] 2019-11-21 11:20
This might be related to #3446. The exact effect is not the same, but it's also caused by the monitor be unplugged and plugged in again.

**Comment by zadjii-msft** [comment] 2019-11-21 13:31
I've got a feeling this was maybe improved by #3394, though I can't really be sure. I'll leave this open just in case it does end up being different, though @j4james you're definitely right about the unplugging repro being similar.

🤞 hopefully this just goes away in 0.7 🤞

**Comment by riverar** [comment] 2019-11-21 17:40
I'm now running a dev build to reproduce, will take a few hours/days to crop back up (if present) as a reboot resolves this issue temporarily.

I suspect this bug is an artifact the longstanding system compositor bug dealing with resize synchronization (@clarkezone has more details).

The system compositor has a workaround to prevent this from happening:
![remember](https://user-images.githubusercontent.com/475132/69362124-c3c40600-0c42-11ea-8465-b6c9cb31a3e3.gif)

But perhaps it's affecting Windows Terminal in another way.

**Comment by zadjii-msft** [comment] 2019-12-04 14:04
@riverar Is there any chance this was fixed by v0.7 (which should be available now)?

**Comment by riverar** [comment] 2019-12-05 18:20
@zadjii-msft Am monitoring. If this is the bug I think it is, it will take an indeterminate amount of time to reproduce. Will follow up as soon as I can.

**Closed** 2020-01-31 01:00 UTC
Labels: Area-User Interface, Issue-Bug, Needs-Author-Feedback, No-Recent-Activity, Priority-3, Product-Terminal, v1-Scrubbed
