### ISSUE TITLE
Title bar is sized incorrectly when switching monitor with different scaling

### ISSUE THREAD

**Issue by abarani** [microsoft/terminal#3619] opened 2019-11-18 17:33 UTC
# Environment

```none
Windows build number: 10.0.18362.0
Windows Terminal version (if applicable): 0.6.2951.0

Monitor 1: 3840x2160 (225%)
Monitor 2 (new default): 2560x1440 (125%)
```

# Steps to reproduce

1. Open Terminal and maximize its window
2. Attach a new default monitor to the device with a different scaling percentage from the previous one (the window is moved to the new monitor retaining its maximized state)
3. 💥 

It's easier to notice this if the new default monitor is placed on the left of the previous one.

# Expected behavior

The title bar is sized correctly.

![image](https://user-images.githubusercontent.com/2650264/69074447-ae2ac280-0a2f-11ea-85f7-d7e5c097b4f4.png)

# Actual behavior

The title bar is wider than the actual window by 9px.
Resizing the window fixes the width.

This is a little annoying because the 9px grey area goes on to the next monitor and it does nothing when you click on it.

![image](https://user-images.githubusercontent.com/2650264/69074384-8c314000-0a2f-11ea-9d74-353e7a0c9993.png)

**Comment by DHowett-MSFT** [comment] 2019-11-18 17:36
I believe this is a /dupe of #2268

**Closed by DHowett-MSFT** 2019-11-18 17:36 UTC
Labels: Needs-Tag-Fix, Needs-Triage
