### ISSUE TITLE
Cannot create a second WSL profile

### ISSUE THREAD

**Issue by pottereric** [microsoft/terminal#3298] opened 2019-10-23 14:49 UTC
I've added several profiles for various work scenarios. As long as I'm using cmd as the command line it works fine. But if I try to add a second profile using the WSL tools, it won't show up in the new terminal dropdown list.

I want to have 2 WSL profiles, one with the normal font for my standard work and one with a larger font for presentations. I copied the default profile, changed the GUID and the font size. 

```
    {
      "guid": "{2c4de342-38b7-51cf-b940-2309a097f518}",
      "hidden": false,
      "name": "Ubuntu",
      "source": "Windows.Terminal.Wsl", 
      "fontSize": 12
    },
     {
      "guid": "{e6dd8b9a-fbeb-430c-a3cb-3b95ed4cc707}",
      "hidden": false,
      "name": "UbuntuBig",
      "source": "Windows.Terminal.Wsl", 
      "fontSize": 24
    },
```
 With this saved in my profiles.json, the "Ubuntu" option shows up in the dropdown list, but not "UbuntuBig". 

Am I misunderstanding how the profile layer works? Is there something different I need to do in order to have a 2nd profile based on a dynamic profile? Is there some other way to create a profile that uses WSL?

**Comment by Biswa96** [comment] 2019-10-23 14:54
There should be a distribution installed with `UbuntuBig` name.

**Comment by DHowett-MSFT** [comment] 2019-10-23 15:14
Yeah, this is something our documentation can do better at explaining. To add a new profile based on a dynamic one, add a new entry with a new guid, give it a ”commandline”, and any other options you want. Remove the “source”.

In your case, drop source and add commandline = `wsl-d Ubuntu`.

I realize that that profile isn’t, at that point, even “based on” the original dynamic profile. It’s just a new one that is inspired by it.

**Comment by carlos-zamora** [comment] 2019-10-23 16:29
Even though this is by design, should we make it such that a scenario like above is supported? I think it would make more sense that way. Think "abstract classes" where source just means this is what this is based off of?

**Comment by DHowett-MSFT** [comment] 2019-10-23 20:05
We should probably consider something like that. I'd prefer it to be filed in a separate followup issue, though, so I'm going to close this one as "by design, sorry, our docs could be better."

**Closed by DHowett-MSFT** 2019-10-23 20:05 UTC
Labels: Needs-Tag-Fix, Needs-Triage

**Comment by pottereric** [comment] 2019-10-23 21:20
It works exactly as I want it to when, as suggested, I replace the source with:

"commandline": "wsl -d Ubuntu",

Thanks for the clarification.

**Comment by darkvertex** [comment] 2021-04-13 19:27
_Just a helpful tip for the next person coming here from Google search results for WSL secondary profiles in Windows Terminal..._ 👀

So I had just installed an off-Windows-Store [WSL distro of CentOS8](https://github.com/mishamosher/CentOS-WSL) and was searching how to configure a second WSL profile, which brought me here.

`"commandline": "wsl -d Ubuntu",` works but I wanted to share this also worked:
```
"name": "CentOS8",
"source": "Windows.Terminal.Wsl"
```

It seems that when the source is `Windows.Terminal.Wsl`, the `name` key is the distro name. 💡🤔

**Comment by DHowett** [comment] 2021-04-13 19:40
I must recommend that you do not do this :wink:

If you tell us the "source" is "Windows.Terminal.Wsl", we will _ask WSL if it knows anything about this profile_. This is entirely based on an internal ID that is generated based on the name, or the `guid` _if you provide one_. For the vast majority of people, the WSL generator will have no idea what profile we're asking about. When we get that reply back, we'll just silently delete the profile.

**Comment by DHowett** [comment] 2021-04-13 19:40
To make a custom WSL profile, set commandline and name. Delete source. That's it.

**Comment by darkvertex** [comment] 2021-04-13 20:32
Ha, duly noted then! Appreciate the explanation. Sorry for my misleading tip and thank you for correcting me. 🤐 I've scratched off my original comment.
