### ISSUE TITLE
Option to disable HTML copy

### ISSUE THREAD

**Issue by msmigiel** [microsoft/terminal#5035] opened 2020-03-20 11:58 UTC
# Description of the new feature/enhancement

There was a feature request to add the ability to copy text as HTML. This is very handy but I don't see a way to disable this - meaning to only copy as text. Please consider adding a flag to disable copying text as full HTML.

# Proposed technical implementation details (optional)

Maybe introduce a boolean like copyTextAsHtml in the global properties section.

**Comment by zadjii-msft** [comment] 2020-03-20 13:53
Out of curiosity, what application are you pasting into that's requesting the HTML content from the clipboard when you'd like the text content? The Terminal copies both text and HTML to the clipboard, it's usually the responsibility of the _receiving_ application to take what content they're capable of using.

See also #2690

**Comment by msmigiel** [comment] 2020-03-20 14:28
I'm pasting into Microsoft Word (Office 365) and the pasted text has full HTML markup. Most of the time when I am copying from a terminal I only want to plain text.

**Comment by zadjii-msft** [comment] 2020-03-20 14:39
You can use this button right here:

![image](https://user-images.githubusercontent.com/18356694/77174165-a2f3ac00-6a8e-11ea-992b-364aeaeb06b6.png)

To choose to paste only the text content

**Comment by msmigiel** [comment] 2020-03-20 15:31
Thank you - that suggestion does work, however it is one extra step. In Word, when I press CTRL+V it defaults to HTML and then in the tooltip I can choose plain text. This is minor, but still an extra step. 

I see this also has been brought up in 2690 as you mention and also 4191. Personally, when I work with the terminal, I want all of my copied text to be pure text only with no HTML markup.

**Comment by DHowett-MSFT** [comment] 2020-03-24 01:21
Thanks for the use case :smile: this is a /dupe of #4191

**Closed by DHowett-MSFT** 2020-03-24 01:21 UTC
Labels: Area-Settings, Issue-Question, Needs-Attention, Needs-Triage, Product-Terminal
