### ISSUE TITLE
Add input synchronization between panes so we can type same command into multiple panes at same time

### ISSUE THREAD

**Issue by arslanastral** [microsoft/terminal#8198] opened 2020-11-09 07:03 UTC
# Description of the new feature/enhancement

I come from Konsole & Tmux Terminal where you have the option to sync your input to multiple panes (or between your pre-selected panes in konsole). It's real handy when you ssh into more than one machine and want to run same commands on all of them. So, something like that would be nice in windows terminal.

**Comment by Don-Vito** [comment] 2020-11-09 10:59
@arslanastral - this one looks like a duplicate of https://github.com/microsoft/terminal/issues/2634.

**Comment by zadjii-msft** [comment] 2020-11-09 11:06
Sure is, thanks for finding the dupe!


/dup #2634

**Closed by zadjii-msft** 2020-11-09 11:06 UTC
Labels: Issue-Feature, Needs-Tag-Fix, Needs-Triage

**Comment by Don-Vito** [comment] 2020-11-09 11:27
@arslanastral - please follow the original ticket: https://github.com/microsoft/terminal/issues/2634. 
This will be resolved one day!

@zadjii-msft  - I am still trying to understand whether we are waiting for the plugin infra for it or not :blush:

**Comment by zadjii-msft** [comment] 2020-11-09 11:33
Nah, that one's been requested enough times that it seems sensible to just ship in-box with the Terminal.

**Comment by tekkitan** [comment] 2022-10-20 19:33
> Nah, that one's been requested enough times that it seems sensible to just ship in-box with the Terminal.

That is unfortunate. Having a suitable replacement for iTerm2 in macOS is what is keeping my company from making the swap from macOS to Windows. iTerm2 has the split panes and all that as well as the ability to input to all panes at once. It makes it incredibly useful when you manage hundreds of Linux systems and have to do maintenance on a bunch of them at once where you have to input the same commands on multiple systems.

**Comment by zadjii-msft** [comment] 2022-10-20 20:44
I think you misunderstood that comment - I meant it as, "nah, we don't need to wait to ship an extensibility framework to be implemented before we implement this. We should just do this."
