### ISSUE TITLE
Can't use SSH with Powershell

### ISSUE THREAD

**Issue by kuzi-moto** [microsoft/terminal#4682] opened 2020-02-21 17:10 UTC
# Environment

```none
Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.18363.0 Microsoft Windows NT 10.0.18363.0

Windows Terminal version (if applicable): 0.9.433.0
```

# Steps to reproduce

1. Open Windows Terminal Preview
2. Run `ssh`

# Expected behavior

```none
usage: ssh [-46AaCfGgKkMNnqsTtVvXxYy] [-B bind_interface]
           [-b bind_address] [-c cipher_spec] [-D [bind_address:]port]
           [-E log_file] [-e escape_char] [-F configfile] [-I pkcs11]
           [-i identity_file] [-J [user@]host[:port]] [-L address]
           [-l login_name] [-m mac_spec] [-O ctl_cmd] [-o option] [-p port]
           [-Q query_option] [-R address] [-S ctl_path] [-W host:port]
           [-w local_tun[:remote_tun]] destination [command]
```

# Actual behavior

```none
ssh : The term 'ssh' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the
spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ ssh
+ ~~~
    + CategoryInfo          : ObjectNotFound: (ssh:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

# Additional Information

Something that's interesting, is that I can't even view the OpenSSH directory...

```none
PS C:\Users\kuzi-moto> Get-Item "C:\Windows\System32\OpenSSH"
Get-Item : Cannot find path 'C:\Windows\System32\OpenSSH' because it does not exist.
At line:1 char:1
+ Get-Item "C:\Windows\System32\OpenSSH"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Windows\System32\OpenSSH:String) [Get-Item], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetItemCommand
```

But when using a normal PowerShell prompt, works just fine:

```none
PS C:\Users\kuzi-moto> Get-Item "C:\Windows\System32\OpenSSH"


    Directory: C:\Windows\System32


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----        3/19/2019   1:21 AM                OpenSSH

**Comment by greg904** [comment] 2020-02-21 17:16
windows settings > apps > apps & features > optional features > add a feature > openssh client

**Comment by kuzi-moto** [comment] 2020-02-21 17:17
> windows settings > apps > apps & features > optional features > add a feature > openssh client

Already installed!

![image](https://user-images.githubusercontent.com/17068090/75056052-cd584680-549b-11ea-80fe-8e204cd25cad.png)

**Comment by zadjii-msft** [comment] 2020-02-21 17:32
This sounds a lot like x86/x64/System32/SysWOW trickery. @kuzi-moto do you know what architecture you're running on your PC?


This sounds a lot like how when I run Terminal from VS after building it, it can't find WSL on the path (because it's not 32-bit), but running it normally, WSL works fine.

Are you running something like:
`C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe`

or

`C:\\Windows\\SysWOW64\\WindowsPowerShell\\v1.0\\powershell.exe`

**Comment by kuzi-moto** [comment] 2020-02-21 17:39
> This sounds a lot like x86/x64/System32/SysWOW trickery. @kuzi-moto do you know what architecture you're running on your PC?

```none
PS C:\Users\kuzi-moto> $ENV:PROCESSOR_ARCHITECTURE
AMD64
```

> This sounds a lot like how when I run Terminal from VS after building it, it can't find WSL on the path (because it's not 32-bit), but running it normally, WSL works fine.
> 
> Are you running something like:
> `C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe`
> 
> or
> 
> `C:\\Windows\\SysWOW64\\WindowsPowerShell\\v1.0\\powershell.exe`

Looks like my standard PowerShell prompt runs from `%SystemRoot%\system32\WindowsPowerShell\v1.0\powershell.exe`. I opened the one from the SysWOW64 directory, and it is has the same issue with SSH as well.

**Comment by DHowett-MSFT** [comment] 2020-02-21 20:32
That's really unusual. From inside WT, can you also share `$env:PATH`?

**Comment by kuzi-moto** [comment] 2020-02-21 21:25
> That's really unusual. From inside WT, can you also share `$env:PATH`?

```none
PS C:\Users\kuzi-moto> $env:PATH
C:\Python38\Scripts\;C:\Python38\;C:\Python37\Scripts\;C:\Python37\;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\iCLS\;C:\Program Files\Intel\Intel(R) Management Engine Components\iCLS\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\ProgramData\chocolatey\bin;C:\Program Files\dotnet\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\GNU\GnuPG\pub;C:\Program Files\Symantec.cloud\PlatformAgent\;C:\tools\php73;C:\ProgramData\ComposerSetup\bin;C:\ProgramData\ngrok-stable-windows-amd64;C:\tools\php74;C:\Program Files\PuTTY\;C:\Program Files\Docker\Docker\resources\bin;C:\ProgramData\DockerDesktop\version-bin;C:\Program Files\Git\cmd;C:\Go\bin;C:\Program Files\nodejs\;C:\Program Files (x86)\Microsoft SQL Server\150\DTS\Binn\;C:\Users\kuzi-moto\AppData\Local\Microsoft\WindowsApps;C:\Users\kuzi-moto\AppData\Local\Programs\Microsoft VS Code\bin;C:\tools\mysql\current\bin;C:\Users\kuzi-moto\AppData\Roaming\Composer\vendor\bin;C:\Users\kuzi-moto\AppData\Local\Box\Box Edit\;C:\Users\kuzi-moto\go\bin;C:\Users\kuzi-moto\AppData\Roaming\npm
```

**Comment by DHowett-MSFT** [comment] 2020-02-21 22:08
`C:\Windows\system32\openssh` is definitely in there.

If you run it from WT as `c:\windows\sysnative\openssh\ssh.exe`, does it work? (key being _sysnative_)

**Comment by kuzi-moto** [comment] 2020-02-24 15:30
> `C:\Windows\system32\openssh` is definitely in there.
> 
> If you run it from WT as `c:\windows\sysnative\openssh\ssh.exe`, does it work? (key being _sysnative_)

Yes, that does appear to work.

**Comment by DHowett-MSFT** [comment] 2020-02-25 21:27
This is fascinating. Everything on your system is acting as though you're in WoW/using powershell x86 on an x64 machine/possibly on an ARM64 machine where it doesn't ship arm64 powershell by default.

Did you install Terminal from the store, or from our downloads page?

Can you share your profiles.json _and_ the defaults.json from your terminal distribution?

Would you also mind sharing the output of `Get-AppxPackage Microsoft.WindowsTerminal*`?

Sorry for all the questions!

**Comment by kuzi-moto** [comment] 2020-02-26 16:31
> Did you install Terminal from the store, or from our downloads page?

I initially installed it via chocolatey a while ago. On seeing these issues I uninstalled it, then re-installed via the store.

> Can you share your profiles.json and the defaults.json from your terminal distribution?

`profiles.json`:

```

**Comment by DHowett-MSFT** [comment] 2020-03-24 00:34
So, I've been thinking about this for a while, and I just can't dig up a single idea as to why it's happening.

Would you mind running [Process Monitor](https://docs.microsoft.com/en-us/sysinternals/downloads/procmon)?

If you create a filter for `Process name` `is` `powershell.exe` `Include` (screenshot below), and then `Event Class` `is` `File System` `Include`, it'll be a pretty small trace.

### filter

![image](https://user-images.githubusercontent.com/14316954/77375929-2ed63400-6d2c-11ea-8fab-016cdec0929b.png)

### files only

![image](https://user-images.githubusercontent.com/14316954/77375944-385f9c00-6d2c-11ea-8512-e743091fdb98.png)

### ssh filter, possibly:

![image](https://user-images.githubusercontent.com/14316954/77376047-85dc0900-6d2c-11ea-8e87-dda923161f2d.png)

I'd love to see what powershell is _doing_ when you try to run `ssh`!

When I run it, I get this:

![image](https://user-images.githubusercontent.com/14316954/77376068-91c7cb00-6d2c-11ea-997d-12266a614902.png)

it shows powershell searching for ssh in `$PATH` :smile:

**Comment by kuzi-moto** [comment] 2020-03-24 19:15
I'm not sure what's wrong, but I get a bit of 2,000 events when running `ssh` with the suggested filters.

Here is a screenshot of the filters:
![image](https://user-images.githubusercontent.com/17068090/77467141-75359c80-6dd9-11ea-80d4-b0059a450244.png)

I have uploaded a spreadsheet of the results for your perusal: [Logfile.xlsx](https://github.com/microsoft/terminal/files/4377198/Logfile.xlsx)

**Comment by DHowett-MSFT** [comment] 2020-03-24 19:39
If you add this filter, it should cut down on the noise significantly:

![image](https://user-images.githubusercontent.com/14316954/77376047-85dc0900-6d2c-11ea-8e87-dda923161f2d.png)

**Comment by kuzi-moto** [comment] 2020-03-24 21:10
You're right, now there are only 92 events that match. 

[Logfile.xlsx](https://github.com/microsoft/terminal/files/4377680/Logfile.xlsx)

**Comment by DHowett-MSFT** [comment] 2020-03-24 22:04
Alright! This is crazy, but powershell is _only_ searching the 32-bit system root.

```
C:\Windows\SysWOW64\ssh.*
C:\Windows\ssh.*
C:\Windows\SysWOW64\wbem\ssh.*
C:\Windows\SysWOW64\WindowsPowerShell\v1.0\ssh.*
C:\Windows\SysWOW64\OpenSSH
```

I've never heard of such a widespread failure of wow64... huh.

**Comment by kuzi-moto** [comment] 2020-03-26 17:58
Hmm, so what seems to be the best way forward? It must be some sort of an issue though, since a standalone Powershell prompt seems to work fine, see attached trace: [Logfile.xlsx](https://github.com/microsoft/terminal/files/4388977/Logfile.xlsx)

**Comment by DHowett-MSFT** [comment] 2020-03-26 18:18
Alright, how about this set of filters:

![image](https://user-images.githubusercontent.com/14316954/77682001-71c62080-6f53-11ea-917d-47d63a8581a6.png)

when you launch a new powershell tab with WT, it should spit out some events.

**Comment by DHowett-MSFT** [comment] 2020-03-31 20:37
I've got really great and terrible news for you. You have a stray copy of `powershell.exe`, 32-bit, sitting in `C:\Windows`. That's not really a normal or expected location for PowerShell to live. . .

**Comment by DHowett-MSFT** [comment] 2020-04-01 00:10
Closing as a question -- root caused to powershell living somewhere it shouldn't, still on $PATH. Fix by identifying why that powershell's there (and removing it) or changing the commandline of Windows PowerShell so that it points to the one living in System32\WindowsPowerShell\v1.0 :smile:

**Closed** 2020-04-01 00:10 UTC
Labels: Issue-Question, Needs-Author-Feedback, Needs-Tag-Fix, Needs-Triage, Resolution-Answered

**Comment by DHowett** [comment] 2020-06-26 01:02
Hey @kuzi-moto -- did you ever end up figuring out where that copy of PowerShell came from? :smile:

**Comment by kuzi-moto** [comment] 2020-06-26 01:10
> Hey @kuzi-moto -- did you ever end up figuring out where that copy of PowerShell came from? 😄

Actually I never did! Couldn't figure out how it got there, so I think I just deleted it and all was well.

**Comment by DHowett** [comment] 2020-06-26 02:17
Excellent.

I thought of you because of #6684 -- I can't believe it took me literally six months to think of this solution ;P

**Comment by kuzi-moto** [comment] 2020-06-26 03:16
Well, hindsight is always 20/20! I'm just glad I got it working, been happy using it this far.

**Comment by shalin51** [comment] 2020-08-17 15:47
Add **C:\Program Files\Git\usr\bin** to **PATH** system variable

**Comment by DHowett** [comment] 2020-08-17 17:12
Probably don't do that, just use the system's built-in SSH client once you figure out which architecture you're on.
