### ISSUE TITLE
[0.8.10261.0 x64] MsixBundle installed Terminal but Crash at startup / Can't uninstall (Weird "Network Error" / Access Denied)

### ISSUE THREAD

**Issue by tebeco** [microsoft/terminal#4424] opened 2020-01-31 12:13 UTC
# Environment

Windows build number: `Microsoft Windows [Version 10.0.18363.592]` 
Windows Terminal version (if applicable): `Microsoft.WindowsTerminal_0.8.10261.0_x64__8wekyb3d8bbwe`

Any other software?
I currently have a Manual build + self signed installation of the `version 0.6`, that's the only one i could install here.

# Steps to reproduce
* Update to 1909 by using Windows10Upgrade Assistant
* Make sure you are using a Corporate network that is desesperate to block the windows store and enforce it with a firewall.
  Basically, unplug your network i guess and try to disable the store as much as you can
* Download and install [Desktop Bridge VC++ v14 Redistributable Package](https://www.microsoft.com/en-us/download/details.aspx?id=53175)
* Download and install [v0.8.10261.0 msix bundle](https://github.com/microsoft/terminal/releases/download/v0.8.10261.0/Microsoft.WindowsTerminal_0.8.10261.0_8wekyb3d8bbwe.msixbundle)
* Run it, crash on start :

```
[Window Title]
Network Error

[Main Instruction]
Windows cannot access C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_0.8.10261.0_x64__8wekyb3d8bbwe\WindowsTerminal.exe

[Content]
Check the spelling of the name. Otherwise, there might be a problem with your network. To try to identify and resolve network problems, click Diagnose.

[^] Hide details  [Diagnose] [Cancel]

[Expanded Information]
Error code: 0x800704cf
The network location cannot be reached. For information about network troubleshooting, see Windows Help.

```

# Expected behavior

App should be running

# Actual behavior

Crash on start :
```
[Window Title]
Network Error

[Main Instruction]
Windows cannot access C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_0.8.10261.0_x64__8wekyb3d8bbwe\WindowsTerminal.exe

[Content]
Check the spelling of the name. Otherwise, there might be a problem with your network. To try to identify and resolve network problems, click Diagnose.

[^] Hide details  [Diagnose] [Cancel]

[Expanded Information]
Error code: 0x800704cf
The network location cannot be reached. For information about network troubleshooting, see Windows Help.
```

Not sure i found relevant information in `Event Viewer`
I could not even open the explorer in the folder `C:\Program Files\WindowsApps` (I got a UAC prompt / Admin local, but still denied

**Comment by tebeco** [comment] 2020-01-31 12:34
I wonder how i can uninstall it 

![image](https://user-images.githubusercontent.com/2266487/73539708-54327a00-442e-11ea-8f9f-98a15e55ab8e.png)

![image](https://user-images.githubusercontent.com/2266487/73539661-36651500-442e-11ea-8ff2-2f648847ed72.png)

**Comment by tebeco** [comment] 2020-02-05 12:08
@DHowett 

Thx for the improuvment over the `msixbundle` as it not install, and start to run.
Can you tell me how i can get info on WHY it crash when running so I can create a proper issue for potentially addressing it in later version ?

I can see the border appear for half a second, then crash and this :

![image](https://user-images.githubusercontent.com/2266487/73839990-828dcc00-4817-11ea-8195-f74f7cc91993.png)

if i open fast enought the `Start Menu` i can see that there is probably some sort of `MS Store Post Action`  (the progress bar):
![image](https://user-images.githubusercontent.com/2266487/73840495-8e2dc280-4818-11ea-82c6-22c797d9e39b.png)


How can i help ?
I wonder where the Logs are to diagnose this.
I not sure where to look at in the `EventViewer` (i tried to check but did not found anything that look like the crash)

**Comment by DHowett-MSFT** [comment] 2020-02-06 18:28
This is probably an artifact of a missing store license... and I'm not sure how exactly to work around that. You might be able to get it working for now by un-zipping the msixbundle and the x64 msix inside it, and just using WindowsTerminal.exe.

Please note that this isn't supported, but it does _work._

**Comment by DHowett-MSFT** [comment] 2020-02-06 18:28
I'm going to mark this as a /dupe of #1386. Sorry!

**Closed by DHowett-MSFT** 2020-02-06 18:28 UTC
Labels: Needs-Tag-Fix, Needs-Triage
