### ISSUE TITLE
Feature Request - Copy with newline

### ISSUE THREAD

**Issue by philippeller** [microsoft/terminal#1621] opened 2019-06-25 19:37 UTC
# Summary of the new feature/enhancement

As had been an issue with later versions of the WSL terminal, also in the new windows terminal selecting and copying multiple lines does not preserve newline characters, but instead is filled up with trailing whitespace to match the terminal width.

# Proposed technical implementation details (optional)

Separate lines should result in clipboard text _with_ newlines, wrapped lines without.

# Example

Copying some output from the terminal and pasting here:

Expected behavior:
```
$ ll /usr/lib
total 206M
lrwxrwxrwx   1 root root   23 Oct  8  2012 libqimageblitz.so.4 -> libqimageblitz.so.4.0.0
-rw-r--r--   1 root root  99K Oct  8  2012 libqimageblitz.so.4.0.0
-rw-r--r--   1 root root 6.0K Feb  2  2013 libporttime.so.0.0.0
lrwxrwxrwx   1 root root   20 Feb  2  2013 libporttime.so.0 -> libporttime.so.0.0.0
-rw-r--r--   1 root root  36K Feb  2  2013 libportmidi.so.0.0.0
lrwxrwxrwx   1 root root   20 Feb  2  2013 libportmidi.so.0 -> libportmidi.so.0.0.0
lrwxrwxrwx   1 root root   20 Jan  4  2014 libmsgpackc.so.2 -> libmsgpackc.so.2.0.0
-rw-r--r--   1 root root  23K Jan  4  2014 libmsgpackc.so.2.0.0
lrwxrwxrwx   1 root root   15 Feb 28  2014 libfam.so.0 -> libfam.so.0.0.0
-rw-r--r--   1 root root  35K Feb 28  2014 libfam.so.0.0.0
...
```
Actual behavior:
```
$ ll /usr/lib                                                                                                              total 206M                                                                                                                                lrwxrwxrwx   1 root root   23 Oct  8  2012 libqimageblitz.so.4 -> libqimageblitz.so.4.0.0                                                 -rw-r--r--   1 root root  99K Oct  8  2012 libqimageblitz.so.4.0.0                                                                        -rw-r--r--   1 root root 6.0K Feb  2  2013 libporttime.so.0.0.0                                                                           lrwxrwxrwx   1 root root   20 Feb  2  2013 libporttime.so.0 -> libporttime.so.0.0.0                                                       -rw-r--r--   1 root root  36K Feb  2  2013 libportmidi.so.0.0.0                                                                           lrwxrwxrwx   1 root root   20 Feb  2  2013 libportmidi.so.0 -> libportmidi.so.0.0.0                                                       lrwxrwxrwx   1 root root   20 Jan  4  2014 libmsgpackc.so.2 -> libmsgpackc.so.2.0.0                                                       -rw-r--r--   1 root root  23K Jan  4  2014 libmsgpackc.so.2.0.0                                                                           lrwxrwxrwx   1 root root   15 Feb 28  2014 libfam.so.0 -> libfam.so.0.0.0                                                                 -rw-r--r--   1 root root  35K Feb 28  2014 libfam.so.0.0.0                                                                                
```

**Comment by carlos-zamora** [comment] 2019-06-25 23:03
Wow. This is weird. Turns out this is a bug. Here's a repro:
1. Open a Windows Terminal instance (trust me, close the one you have and open a new one)
2. `dir` (or `ls`)
3. make a selection of multiple lines
4. right click to copy
5. paste to notepad
6. (this is where things get weird) THIS PASTE SHOULD BE FINE
7. `cls` (or `clear`)
8. repeat steps 2 - 5
9. THIS PASTE SHOULD BE A MIX OF NEW SAME LINE AND NEW LINE TEXT

I did a bit of investigating. If you set a breakpoint on `TermControl::CopySelectionToClipboard()`s `_terminal->ClearSelection();`, use a debugger to take a look at the contents of `copiedData`.

On step 4 (both times you do it), you should hit this breakpoint. `copiedData` is different both times. I guess the problem is in `Terminal::RetrieveSelectedTextFromBuffer()`

**Comment by carlos-zamora** [comment] 2019-06-25 23:05
Assigning myself but happy if anybody wants to take it off my plate :)

**Comment by DHowett-MSFT** [comment] 2019-06-27 22:51
Isn't this a duplicate of #1073?

**Closed by DHowett-MSFT** 2019-06-27 22:51 UTC
Labels: Area-Interaction, Issue-Bug, Needs-Triage, Product-Terminal

**Comment by 89z** [comment] 2021-04-23 13:01
https://github.com/microsoft/terminal/issues/1073
https://github.com/microsoft/terminal/issues/1126

https://github.com/microsoft/terminal/issues/1621
https://github.com/microsoft/terminal/issues/2275
https://github.com/microsoft/terminal/issues/2278
https://github.com/microsoft/terminal/issues/2324
https://github.com/microsoft/terminal/issues/2395
https://github.com/microsoft/terminal/issues/2717
https://github.com/microsoft/terminal/issues/52
