### ISSUE TITLE
Unable to use copy and paste backslash on command line

### ISSUE THREAD

**Issue by mhagnumdw** [microsoft/terminal#3242] opened 2019-10-18 01:24 UTC
# Environment

```none
Windows build number: 10.0.18362.0
Windows Terminal version: 0.5.2762.0
Terminals: Ubuntu WSL, git-bash, cygwin
```

# Steps to reproduce

Copy and paste the command below into the terminal:
```shell
echo \
'backslash test'
```

# Expected behavior

Be interpreted as a single command.

# Actual behavior

It is being interpreted as two commands.

![image](https://user-images.githubusercontent.com/17688846/67058537-a378c700-f12b-11e9-85fa-abc1c277e7f6.png)

# More Information

If you copy and paste the code below, it works fine.

```bash
echo 'line 1' && \
echo 'line 2'
```

![image](https://user-images.githubusercontent.com/17688846/67058623-fce0f600-f12b-11e9-8dd7-f73454149e1f.png)

**Comment by DHowett-MSFT** [comment] 2019-10-21 19:52
This looks like a /dupe of #1091. Thanks!

**Closed by DHowett-MSFT** 2019-10-21 19:52 UTC
Labels: Needs-Tag-Fix, Needs-Triage
