### ISSUE TITLE
Font Glyphs are cut off by the Windows Terminal

### ISSUE THREAD

**Issue by DoCode** [microsoft/terminal#5095] opened 2020-03-24 02:13 UTC
# Environment

```none
Windows build number: 10.0.18363.0
Windows Terminal version (if applicable): 0.10.781.0
```

# Steps to reproduce

Some Unicode glyphs are cut off, ONLY in Windows Terminal.

# Expected behavior

**ConEmu:**

![image](https://user-images.githubusercontent.com/1489133/77381002-0a567800-6d7d-11ea-93e5-bc3a42f6aef0.png)

**PowerShell Core:**

![image](https://user-images.githubusercontent.com/1489133/77381010-0e829580-6d7d-11ea-8c8c-5ed7a96322db.png)

**PowerShell:**

![image](https://user-images.githubusercontent.com/1489133/77381027-1b9f8480-6d7d-11ea-824b-53be50c14c84.png)

# Actual behavior

**Windows Terminal:**

![image](https://user-images.githubusercontent.com/1489133/77380976-f14dc700-6d7c-11ea-87cd-4208b4964d67.png)

**Comment by fabienheureux** [comment] 2020-03-24 11:01
Maybe related to https://github.com/microsoft/terminal/issues/4974 ?

**Comment by DoCode** [comment] 2020-03-24 12:06
No ligatures, but oversized glyphs. But I preserve space for it with one empty char as postfix for each oversized glyph.

But why only Windows Terminal struggled with this?

**Comment by fabienheureux** [comment] 2020-03-24 12:11
Well, I honestly don't know...but as the v1.0 is not yet released, this is understandable.

**Comment by skyline75489** [comment] 2020-03-24 13:37
@DoCode How do you print this kind of 'oversized' glyph, though. I've tried `echo -e '\U0001f602'` it only gives me a regular sized folder.

**Comment by DoCode** [comment] 2020-03-24 14:17
@fabienheureux - ok thanks.
So I hope MS would address this issue for the 1.0 milestone.

**Comment by DoCode** [comment] 2020-03-24 14:25
> @DoCode How do you print this kind of 'oversized' glyph, though. I've tried `echo -e '\U0001f602'` it only gives me a regular sized folder.

@skyline75489 - I print this kind with simple following a whitespace, like `echo -e '\uF07C'' '` to preserve overlapping.
> This works on all platforms and terminals, except the new Windows Terminal!

**Comment by zadjii-msft** [comment] 2020-03-24 14:30
@DoCode could you share what font you're using as well?

**Comment by DoCode** [comment] 2020-03-24 14:39
@zadjii-msft yes, `\uF07C`, that's the glyph I want. It's ported from powerleve10k and this used larger icons. Works like a charm as I said.

[Here's](https://github.com/microsoft/terminal/files/4375852/cascadia-nerd-font-complete.zip) the font I used.

**Comment by DoCode** [comment] 2020-03-24 15:01
FYI, also the integrated VS Code terminal works like a charm:

![image](https://user-images.githubusercontent.com/1489133/77440470-a2d61200-6de8-11ea-864a-fb7c79c2f507.png)

**Comment by jdebp** [comment] 2020-03-24 18:21
U+F07C is in the Unicode Private Use Area.  Powerline, and ["nerd fonts"](https://github.com/ryanoasis/nerd-fonts/wiki/Glyph-Sets-and-Code-Points), fill this up with a whole bunch of stuff.  Their users are sometimes surprised, in my experience, to learn that Private Use Area _really does mean_ something that does not work the same everywhere.  In this case, Windows Terminal is treating the character as a narrow character.  The whole Private Use range is marked as "ambiguous" width in the Unicode standard.

U+1F5C1 is a standard character, with narrow width.  Amusingly, Unicode version 13 now gives you U+1FBB9 and U+1FBBA for making a wide folder icon in a text display, in the way that computer people used to.  (-:

**Comment by DoCode** [comment] 2020-03-24 18:53
@jdebp thanks for the detailed explanation.
I will try your suggestions about unicode version 13.
However, I don't think it's okay that Windows Terminal doesn't behave like all other terminals. This will annoy many users. Windows Terminal is not the first and primary terminal on the market and should and should be as compatible as possible.

**Comment by waltermaldonado** [comment] 2020-03-24 23:52
I can confirm the same behavior here, but it is not present only in the Windows Terminal app. If Iuse WSL with the default terminal app, I get the icons from lsd cut off too.

Look closely to the folder's icons.

![image](https://user-images.githubusercontent.com/8573950/77487419-302d5c80-6e11-11ea-853f-412a765cdf6c.png)

![image](https://user-images.githubusercontent.com/8573950/77487464-49cea400-6e11-11ea-82b9-713c00eb55e7.png)

**Comment by DHowett-MSFT** [comment] 2020-03-26 01:07
It's a very unfortunate situation that we've been put into by the ill-defined use of the private use area. We may need to fix this as part of a holistic look at how we handle ambiguous-width characters.

**Comment by dtasev** [comment] 2020-04-22 10:34
It would be good to collaborate on this with the VSCode team. They have already solved it for the terminal rendering there, and their solution(to me) seems to work just as well as any `bash` terminal.

BTW this bad rendering behaviour seems to be consistent across `cmd`/`PowerShell`/`Windows Terminal` and, afaik, it has never worked. It would be a miracle if it all gets fixed.

**Comment by DHowett-MSFT** [comment] 2020-04-24 18:54
So, I've just installed one of these "fonts for nerds" and I cannot reproduce this issue in 0.11. There's an _overlap_ problem, but I'm not seeing your folder glyph cut off _if appropriate space is left for it_.

![image](https://user-images.githubusercontent.com/14316954/80246143-ca570f00-8620-11ea-8d28-efde70232c97.png)

If appropriate space _isn't_ left for it, there's not much we can do.

At the end of the day, this glyph is reported as being "ambiguous" width and we've decided that ambiguous glyphs are one cell wide. Sorry.

For the record, this seems to be very close to _xterm's_ behavior (xterm-344 pictured below).

![image](https://user-images.githubusercontent.com/14316954/80246734-c1b30880-8621-11ea-88d9-018a69d8ce8a.png)

_and gnome-terminal_

![image](https://user-images.githubusercontent.com/14316954/80247104-60d80000-8622-11ea-88c3-fc6ed27db594.png)

**Comment by DHowett-MSFT** [comment] 2020-04-24 18:55
Yes, we don't let the font outside of its bounding box if we're about to put another character right up against it. The result of striking the C or < down over the right side of the folder is visually offensive and cannot possibly be clearer than curring it off.

**Closed by DHowett-MSFT** 2020-04-24 18:54 UTC
Labels: Area-Fonts, Area-Rendering, Issue-Bug, Priority-1, Product-Terminal
