### ISSUE TITLE
Opening a hyperlink can cause the Terminal to hang

### ISSUE THREAD

**Issue by zadjii-msft** [microsoft/terminal#7994] opened 2020-10-21 17:00 UTC
I originally posted this in #7691, but it turns out the hang wasn't even introduced there - it was already in `main` before that.

<hr>

Blocking based off the hang discussion we're currently having on teams. Turns out the main thread is grabbing the write lock twice:

Once in 
```
[0x4f] TerminalControl!winrt::Microsoft::Terminal::TerminalControl::implementation::TermControl::_PointerPressedHandler + 0x593
```

then again in
```
[0x6]   TerminalControl!winrt::Microsoft::Terminal::TerminalControl::implementation::TermControl::_TrySendKeyEvent + 0x116   
```

because WinUI somehow routes a `KeyDownEvent` to TermControl _during the `PointerPressed`???_

<hr>

Suggested fix:

```c++
if (point.Properties().IsLeftButtonPressed())
{
    const auto cursorPosition = point.Position();
    const auto terminalPosition = _GetTerminalPosition(cursorPosition);
    {
        // handle ALT key
        auto lock = _terminal->LockForWriting();
        _terminal->SetBlockSelection(altEnabled);
        // Release the write lock
    }
    // Re-grab the read lock
    auto lock = _terminal->LockForReading();
    ...
}
```

**Comment by DHowett** [comment] 2020-10-28 22:40
So here's a thought.

We're holding the write lock while calling `_HyperlinkHandler`.

We should _never_ call a user callback under our lock. That could give the user the ability to hold us up indefinitely.

We should get the hyperlink out of the buffer ASAP, release the lock, and then call the handler.

Problem is, this is tangled up with the selection code.

**Comment by DHowett** [comment] 2020-10-28 22:45
Oh you clearly figured that out ;P

**Comment by miniksa** [comment] 2020-10-28 23:04
I just had this here on my machine and the issue is that `ShellExecute` is pumping the message queue during its operation which is then servicing the `TermControl::_CursorTimerTick` as it runs around the queue looking for whatever it's looking for.

`TermControl::_CursorTimerTick` attempts to take the lock for writing because it's going to adjust the cursor blink state. But the `ShellExecute` call it is being serviced off of is a result of `TermControl::_HyperlinkHandler` which is called from `TermControl::_PointerPressedHandler` which is already holding a write lock.

So somehow the connection needs to be broken because `_HyperlinkHandler` first only really needs a read lock to fill its parameter. It doesn't actually need to have anything locked at all after it starts running as it already has all the state it needs.

@DHowett says that really we should probably condense the selection stuff down a layer since a lot of this is duplicated between WPF and XAML.... but that's bigger than this fix.

I think we just need to either:
1. Edit `_HyperlinkHandler` to coroutine off somewhere so it can return into `_PointerPressedHandler` and unlock the write lock allowing the `ShellExecute` call to potentially pump messages with write locks in them like the `_CursorTimerTick` one.
2. Change the top of `_PointerPressedHandler` to not take a write lock for everything. I bet that was relevant in the past, but now with the hyperlink handler, it first off really only needs a read lock and second could give that up after retrieving the URI data and before calling down further to `_HyperlinkHandler`, resolving the situation.

**Comment by DHowett** [comment] 2020-10-28 23:04
Yep. Do number 1. It's easy.

**Closed** 2020-10-29 14:03 UTC
Labels: Area-TerminalControl, In-PR, Issue-Bug, Priority-0, Product-Terminal, Severity-Blocking, Severity-Crash
