### ISSUE TITLE
A hidden profile is included in the default profile choice list in Settings

### ISSUE THREAD

**Issue by olliefr** [microsoft/terminal#16242] opened 2023-10-30 15:17 UTC
### Windows Terminal version

1.18.2822.0

### Windows build number

10.0.22621.0

### Steps to reproduce

Do one of: 

- Enable `Hide profile from dropdown` in the profile's configuration UI.
- Edit Terminal's JSON configuration file to set `hidden` to `true` for the selected profile.

### Expected Behavior

- The profile disappears from the list in the Terminal window heading. 
- The profile is not available for selection as the default one.

### Actual Behavior

- The profile disappears from the list in the Terminal window heading. This is OK.
- But the profile is still available for selection in Settings, Startup, Default profile select box. Is this intentional?

**Comment by olliefr** [comment] 2023-10-30 15:24
Adding some screenshots for visual clarity.

## Hide a profile

![image](https://github.com/microsoft/terminal/assets/967105/8f0f4f0c-a617-4183-a89c-2b76e35ec290)

## Profile list in the title bar correctly displays only visible profiles

![image](https://github.com/microsoft/terminal/assets/967105/b2568c2d-5004-4618-9ceb-9b3ff28fd7e7)

## Hidden profile still included in the default profile selection

![image](https://github.com/microsoft/terminal/assets/967105/3a9da50f-5f5f-4f70-9672-73b4a6a29c66)

**Comment by 237dmitry** [comment] 2023-10-30 18:02
It would be interesting to know how to restore the visibility of a hidden profile if it is not in the settings? Should the user manually edit the settings.json file? The profile is hidden from the dropdown menu so that it does not interfere there.

In [documentation](https://learn.microsoft.com/en-us/windows/terminal/customize-settings/profile-general) this option was named `Hide profile from dropdown`

**Comment by carlos-zamora** [comment] 2023-11-01 21:55
Thanks for filing! We chatted about this as a team and here's some of the things that came out of it:
- `hidden` is actually working as intended! Historically, it was used to remove dynamic profiles and hide profiles from the dropdown. With a bugfix to delete dynamic profiles and the "new tab dropdown customization" feature, those needs are already met in a better way. Today, "hidden" still affects the `remainingProfiles` entry in the "new tab dropdown customization" list, so it still has some value there.
- With regards to the future of `hidden`, we want to deprecate it. However, a big hold up right now is that the "new tab dropdown customization" feature can only be done through the JSON. Once that goes into the settings UI, there really shouldn't be much of a reason to keep it around. We just need to actually design and implement the settings UI part. We're tracking that over in #8914.

Hope that answers your question and provides some insight on what's going on. I'm going to close this as a /dup of #8914 and make sure the deprecation for `hidden` is tracked over there.

**Closed** 2023-11-01 21:55 UTC
Labels: Issue-Bug

**Comment by olliefr** [comment] 2023-11-04 07:23
Thank you for the detailed explanation and for this work, @carlos-zamora! The future looks bright, indeed 😊
