### ISSUE TITLE
Unexpected Ctrl-D keystroke on Alt+Left

### ISSUE THREAD

**Issue by david50407** [microsoft/terminal#3185] opened 2019-10-14 10:16 UTC
# Environment

Windows build number: 10.0.18363.418
Windows Terminal version (if applicable):  0.5.2762.0

# Steps to reproduce

In WSL session, press `Alt+Left` and release `Left` key then `Alt` key.

# Expected behavior

This should not input `Ctrl+D`

# Actual behavior

The terminal will execute `Alt+Left` keystroke and unexpected `Ctrl+D` keystroke (when releasing `Alt` key).

# More info

I'm using tmux in my WSL session and bind `Alt+Left` to switch tmux window.
I found this problem when I'm switching windows, my windows get switched and also get `Ctrl-D` keystroke (and this closes my session...).
And I tried to input `Alt+Left` without tmux but with a keystroke recorder, that it shows I inputed `Ctrl-D` after `Alt-Left` (`\e[1;3D\cD`).

Keybinding part of my profiles.json:
```json
"keybindings": [
        // Unbound all keybindings
        { "command": "unbound", "keys": ["ctrl+shift+w"] },
        { "command": "unbound", "keys": ["alt+f4"] },
        { "command": "unbound", "keys": ["ctrl+shift+c"] },
        { "command": "unbound", "keys": ["ctrl+shift+d"] },
        { "command": "unbound", "keys": ["ctrl+shift+t"] },
        { "command": "unbound", "keys": ["ctrl+shift+1"] },
        { "command": "unbound", "keys": ["ctrl+shift+2"] },
        { "command": "unbound", "keys": ["ctrl+shift+3"] },
        { "command": "unbound", "keys": ["ctrl+shift+4"] },
        { "command": "unbound", "keys": ["ctrl+shift+5"] },
        { "command": "unbound", "keys": ["ctrl+shift+6"] },
        { "command": "unbound", "keys": ["ctrl+shift+7"] },
        { "command": "unbound", "keys": ["ctrl+shift+8"] },
        { "command": "unbound", "keys": ["ctrl+shift+9"] },
        { "command": "unbound", "keys": ["ctrl+tab"] },
        { "command": "unbound", "keys": ["ctrl+shift+space"] },
        { "command": "unbound", "keys": ["ctrl+,"] },
        { "command": "unbound", "keys": ["ctrl+shift+v"] },
        { "command": "unbound", "keys": ["ctrl+shift+tab"] },
        { "command": "unbound", "keys": ["ctrl+shift+down"] },
        { "command": "unbound", "keys": ["ctrl+shift+pgdn"] },
        { "command": "unbound", "keys": ["ctrl+shift+up"] },
        { "command": "unbound", "keys": ["ctrl+shift+pgup"] },
        { "command": "unbound", "keys": ["ctrl+alt+1"] },
        { "command": "unbound", "keys": ["ctrl+alt+2"] },
        { "command": "unbound", "keys": ["ctrl+alt+3"] },
        { "command": "unbound", "keys": ["ctrl+alt+4"] },
        { "command": "unbound", "keys": ["ctrl+alt+5"] },
        { "command": "unbound", "keys": ["ctrl+alt+6"] },
        { "command": "unbound", "keys": ["ctrl+alt+7"] },
        { "command": "unbound", "keys": ["ctrl+alt+8"] },
        { "command": "unbound", "keys": ["ctrl+alt+9"] },
        { "command": "unbound", "keys": ["alt+left"] },
        // Customization here
        { "command": "closePane", "keys": ["ctrl+shift+w"] },
        { "command": "newTab", "keys": ["ctrl+shift+t"] },
        { "command": "paste", "keys": ["ctrl+shift+v"] },
        { "command": "openNewTabDropdown", "keys": ["ctrl+shift+space"] },
        { "command": "nextTab", "keys": ["ctrl+tab"] },
        { "command": "nextTab", "keys": ["ctrl+alt+right"] },
        { "command": "prevTab", "keys": ["ctrl+shift+tab"] },
        { "command": "prevTab", "keys": ["ctrl+alt+left"] },
        { "command": "switchToTab0", "keys": ["ctrl+alt+1"] },
        { "command": "switchToTab1", "keys": ["ctrl+alt+2"] },
        { "command": "switchToTab2", "keys": ["ctrl+alt+3"] },
        { "command": "switchToTab3", "keys": ["ctrl+alt+4"] },
        { "command": "switchToTab4", "keys": ["ctrl+alt+5"] },
        { "command": "switchToTab5", "keys": ["ctrl+alt+6"] },
        { "command": "switchToTab6", "keys": ["ctrl+alt+7"] },
        { "command": "switchToTab7", "keys": ["ctrl+alt+8"] },
        { "command": "switchToTab8", "keys": ["ctrl+alt+9"] }
    ]
```

**Comment by DHowett-MSFT** [comment] 2019-10-14 19:40
Hey, thanks! This is a /dupe of #3101

**Closed** 2019-10-14 19:40 UTC
Labels: Needs-Tag-Fix, Needs-Triage

**Comment by david50407** [comment] 2019-10-15 05:02
@DHowett-MSFT oh, my fault

**Comment by DHowett-MSFT** [comment] 2019-10-15 05:03
Nah, some of our issues are pretty hard to discover. :smile:
