### ISSUE TITLE
Chinese Localization for ShellExtension

### ISSUE THREAD

**Issue by Joe1921567817** [microsoft/terminal#10440] opened 2021-06-17 04:08 UTC
# Description of the new feature/enhancement

Please add Chinese translation for the shell extension
for Chinese Traditional:"在此處開啟 Windows Terminal"
for Chinese Simplified:"在此处打开 Windows Terminal"
# Proposed technical implementation details (optional)

**Comment by DHowett** [comment] 2021-06-17 19:43
Thanks for the request! This is a /duplicate of #6112.

**Closed by DHowett** 2021-06-17 19:43 UTC
Labels: Issue-Feature, Needs-Tag-Fix, Needs-Triage
