### ISSUE TITLE
Mouse / system lag when terminal is focused

### ISSUE THREAD

**Issue by Cry0nicS** [microsoft/terminal#3735] opened 2019-11-27 08:52 UTC
Windows build number: Microsoft Windows [Version 10.0.18362.476]  
Windows Terminal version (if applicable): 0.7.3291.0 (but also the previous one)

# Steps to reproduce

Opening the terminal (regardless of how this is done) and trying to use the system while the Terminal is focused (or moving the mouse around).

# Expected behavior

Expected behavior is for the Terminal to not affect the system and work just like any other window

# Actual behavior

Once the Terminal is focused, moving the mouse around is very laggy (even if the mouse is on another screen). This keeps happening until any other window is getting focused.

The system is laggy overall while the terminal  is focused. But typing is _not_.

Worth to mention: I tried installing the Terminal both via the Windows Store as well as scoop. I tried using it with the default (empty) config file, I tried personalizing it. The behavior was always the same, from the moment I installed the first time the Terminal (starting with v 0.6xx and continuing into the new 0.7xxx)

**Comment by zadjii-msft** [comment] 2019-11-27 14:59
Out of curiosity, are you using acrylic with the Terminal? Does the behavior go away if you disable acrylic? You'll want to edit the following two settings for your profile:
```json
            "acrylicOpacity" : 0.85,
            "useAcrylic" : true
```

**Comment by Cry0nicS** [comment] 2019-11-27 15:21
@zadjii-msft You are correct! Setting `"useAcrylic" : false` fixed the problem.  (I guess removing the property altogether has the same effect).

**Comment by DHowett-MSFT** [comment] 2019-11-30 00:40
There isn't such a list. Sorry!

This is likely among the reasons that the platform team keeps warning us about using acrylic on large surfaces. :smile:

**Comment by Cry0nicS** [comment] 2019-12-05 10:45
@zadjii-msft Can I re-open this? The issue still persists, the only difference is that now behavior disappears if I focus out of the terminal and back on it.

The only changes I made in profiles.json are the following:

```json
    "profiles":
    [
        { 
	     "guid" : "{14ad203f-52cc-4110-90d6-d96e0f41b64d}", 
            "name" : "Git Bash", 
            "commandline" : "C:/Program Files/Git/bin/bash.exe --login", 
            "hidden": false,
            "startingDirectory" : "d:/Projects/GosuGamers/development-environment/environments",
            "closeOnExit": true,
            "colorScheme" : "MaterialOcean",
            "fontFace" : "Source Code Pro", 
            "fontSize" : 13, 
            "icon": "C:\\Program Files\\Git\\mingw64\\share\\git\\git-for-windows.ico",
            "padding" : "20, 20, 20, 20",
            "useAcrylic": false
        }
    ],

    // Add custom color schemes to this array
    "schemes": [
		{
			"name":  "MaterialOcean",
			"black":  "#546e7a",
			"red":  "#ff5370",
			"green":  "#c3e88d",
			"yellow":  "#ffcb6b",
			"blue":  "#82aaff",
			"purple":  "#c792ea",
			"cyan":  "#89ddff",
			"white":  "#ffffff",
			"brightBlack":  "#546e7a",
			"brightRed":  "#ff5370",
			"brightGreen":  "#c3e88d",
			"brightYellow":  "#ffcb6b",
			"brightBlue":  "#82aaff",
			"brightPurple":  "#c792ea",
			"brightCyan":  "#89ddff",
			"brightWhite":  "#ffffff",
			"background":  "#0f111a",
			"foreground":  "#8f93a2"
		}
	]
```

**Comment by zadjii-msft** [comment] 2019-12-05 15:31
@Cry0nicS Sure, if disabling acrylic didn't seem to fix your problem then there must be something else at work here.

**Comment by DHowett-MSFT** [comment] 2019-12-05 20:33
This is curious. Would you mind sharing some more information about your system? What sort of graphics hardware have you got, what's your display size and topology, etc.?

**Comment by Cry0nicS** [comment] 2019-12-05 21:52
@DHowett I have a tri-monitor setup. 2x 23" Dell (1080p) + main 27" Dell (1440p). These are powered by an nVidia RTX2080 (driver: 8.1.940.0), one SSD, and 32GB Ram.

The issue seems to be much more significant on the 27" monitor.
On the other two, smaller, monitors everything seems almost fine.

**Comment by zadjii-msft** [comment] 2019-12-05 22:39
@Cry0nicS Any chance the dell monitor is at a different framerate than the other monitors?

**Comment by Cry0nicS** [comment] 2019-12-05 22:40
@zadjii-msft yes it is. 144hz (compared to the 59 for the other two)

**Comment by zadjii-msft** [comment] 2019-12-05 22:42
I'm not psychic I swear, #3857 just came in suggesting the same thing was responsible 😜

**Comment by DHowett-MSFT** [comment] 2019-12-09 20:38
This looks like it might be a /dupe of #649. Thanks for the report!

**Closed by DHowett-MSFT** 2019-12-09 20:38 UTC
Labels: Area-Performance, Issue-Bug, Needs-Attention, Needs-Repro, Priority-3, Product-Terminal

**Comment by haug1** [comment] 2021-04-07 15:28
What do I need to do if I'm still experiencing this ?
