### ISSUE TITLE
Part of Tab Row turns darker when close all tab opens

### ISSUE THREAD

**Issue by Chips1234** [microsoft/terminal#5412] opened 2020-04-19 04:22 UTC
# Environment

```none
Windows build number: 19608.1006 (v 2004, Windows Insider Home)
Windows Terminal version (if applicable): 0.10.781.0
```

# Steps to reproduce
Just open more than one tab, then close the application. A dialogue will pop up. 

# Expected behaviour
Tab row to not change colour.

# Actual behaviour
![Terminal Dialog Error](https://user-images.githubusercontent.com/47545798/79679409-ad52b400-81ba-11ea-8b2e-3925f821624c.jpg)

If you look at Tab row, it will become darker.

**Comment by electronic-dk** [comment] 2020-04-20 10:12
Duplicate of https://github.com/microsoft/terminal/issues/2100

**Comment by zadjii-msft** [comment] 2020-04-20 11:48
Thanks for the help triaging @electronic-dk!

/dup #2100

**Closed by zadjii-msft** 2020-04-20 11:48 UTC
Labels: Needs-Tag-Fix, Needs-Triage
