### ISSUE TITLE
The blinking caret in Terminal should stop blinking after a while to improve battery life

### ISSUE THREAD

**Issue by dmachaj** [microsoft/terminal#12303] opened 2022-01-31 19:33 UTC
### Windows Terminal version

1.11.3471.0

### Windows build number

10.0.22000

### Steps to reproduce

1) Launch Terminal
2) Ensure Terminal has foreground
3) See caret blinking
4) Wait 30+ seconds
5) It is still blinking

### Expected Behavior

Windows OS components stop the blinking after a short period of delay (something like 10 seconds).  If I remember correctly XAML/WinUI edit boxes will behave this way automatically.

This indefinite blinking is harmful to battery life.  The CPU must remain awake to blink the caret continuously.  It would be much better if it could go to idle after a while.  If I have Terminal open in the foreground, and go get coffee, it should stop blinking and using battery while I'm away.  Just going to a solid caret so the CPU can sleep would be appropriate.

### Actual Behavior

The cursor blinks forever so long as Terminal is in the foreground.  (Or at least it doesn't stop until after my patience of staring at it has run out so the delay should be shortened).

**Comment by DHowett** [comment] 2022-01-31 19:39
Thanks for the request! This is a /duplicate of #5318.

**Closed by DHowett** 2022-01-31 19:39 UTC
Labels: Needs-Triage, Needs-Tag-Fix

**Comment by dmachaj** [comment] 2022-01-31 19:41
Bah I searched for `caret` issues but not `cursor` 🤦
