### ISSUE TITLE
Feature Request：Consider supporting toogle fullscreen

### ISSUE THREAD

**Issue by cjp715711877** [microsoft/terminal#1178] opened 2019-06-08 17:11 UTC
like powershell,use 'ctrl + enter' can enter/exit fullscreen mode（hide top bar）

**Comment by DHowett-MSFT** [comment] 2019-06-09 03:26
Thanks for suggesting a feature! This is a duplicate of #533. Please make sure you’re searching for existing issues when you submit a new one!

**Closed by DHowett-MSFT** 2019-06-09 03:26 UTC
Labels: Issue-Feature, Needs-Tag-Fix, Needs-Triage
