### ISSUE TITLE
Guidance

### ISSUE THREAD

**Issue by DavidA2014** [microsoft/terminal#1774] opened 2019-07-02 11:18 UTC
Where are simple operations such as  how to do clipboard copy and paste documented?

Does Windows Terminal support ssh sessions to remote hosts?

Is there a FAQ for such questions?

**Comment by bitcrazed** [comment] 2019-07-02 21:10
Dupe of #1576. PR #1577 is in progress.

**Closed by bitcrazed** 2019-07-02 21:10 UTC
Labels: Issue-Docs, Resolution-Duplicate
