### ISSUE TITLE
Official Ubuntu theme for theme marketplace

### ISSUE THREAD

**Issue by sirredbeard** [microsoft/terminal#8058] opened 2020-10-27 15:43 UTC
This is a feature request for an official Ubuntu theme in the Windows Terminal theme gallery, which is currently priority 2 [on the roadmap for Windows Terminal 2.0](https://github.com/microsoft/terminal/blob/main/doc/terminal-v2-roadmap.md).

We would like to engage with our Design Team at Canonical to develop a delightful theme for users using [all available](https://docs.microsoft.com/en-us/windows/terminal/customize-settings/profile-settings) and [planned theme features](https://github.com/microsoft/terminal/pull/5772) to be available when the theme gallery launches.

A concept:

![image](https://user-images.githubusercontent.com/33820650/97325408-56085d00-1849-11eb-9bdd-bdb19b49a5e4.png)

**Comment by zadjii-msft** [comment] 2020-10-27 15:53
@sirredbeard have you been in contact with @cinnamon-msft? I'm pretty sure the whole reason we're jumping on the proto-extensions thing (#7632) is so that Canonical can ship customizations for the Ubuntu distros that we auto detect.

**Comment by cinnamon-msft** [comment] 2020-10-27 17:04
Hey @sirredbeard, we're shipping proto-extensions in our next release, which will let Ubuntu ship their own Terminal theme inside the Ubuntu package. Does this work as a solution for you? We have a loose timeline for the theme marketplace.

**Comment by DHowett** [comment] 2020-10-27 17:30
@sirredbeard we’d love your feedback on fragment extensions (#7584).

**Comment by alannt777** [comment] 2020-10-28 14:47
Will these extensions work on imported Ubuntu profiles?

**Comment by zadjii-msft** [comment] 2020-10-28 17:51
Yep! Something like

```json
{
    "profiles": [
        {
			// This is the GUID for Ubuntu-18.04
            "updates" : "{c6eaf9f4-32a7-5fdc-b5cf-066e8a4b1e40}",

            "background" : "#2C001E",
            "useAcrylic" : true,
            "acrylicOpacity" : 0.9,
            "icon" : "C:\\path\\to\\ubuntu-icon.png",
            "padding" : "4",
            "cursorColor" : "#FFaf00",
            "fontFace" : "Ubuntu Mono",
            "fontSize" : 14,
            "cursorShape" : "emptyBox"
        }
    ]
}
```

Would modify the auto-generated "Ubuntu-18.04" profile, so Canonical can change the appearance of distros that we auto-detect.

**Comment by sirredbeard** [comment] 2020-10-29 15:21
> Does this work as a solution for you?

Yes, it does. I will get with Patrick on WSL to talk about ways we could integrate it into our Store app. 

I will also highlight this for the Multipass team.

**Comment by sirredbeard** [comment] 2020-10-29 15:40
Being able to [declare an extension and bundle the assets](https://github.com/microsoft/terminal/blob/dev/pabhoj/proto_spec/doc/specs/Proto%20extensions-spec.md#for-apps-installed-through-microsoft-store-or-similar) in the UWP app is going to be super helpful for us through the Store. Very excited about this.

**Comment by zadjii-msft** [comment] 2020-11-02 11:55
Okay thanks for confirming! I'm gonna call this a dupe of proto-extensions / "settings fragments" for now, I'd go follow those issues/PRs for updates.

/dup #1690 
/dup #7632

Thanks!

**Closed by zadjii-msft** 2020-11-02 11:56 UTC
Labels: Issue-Feature, Needs-Attention, Needs-Tag-Fix, Needs-Triage, Product-Terminal

**Comment by sirredbeard** [comment] 2020-11-02 15:30
That is fine. This was intended to just be a placeholder for the theme marketplace feature which was suggested we file but I will defer to your team.
