### ISSUE TITLE
REP corrupts some Unicode characters (emoji)

### ISSUE THREAD

**Issue by dgl** [microsoft/terminal#15751] opened 2023-07-24 06:45 UTC
### Windows Terminal version

1.18.1462.0

### Windows build number

10.0.25300.1000

### Steps to reproduce

Repeating some emoji with an escape sequence results in mojibake. In WSL or any Linux:

```console
$ printf '\e[6n💓\e[1b\e[6n\n';cat
💓�
^[[4;1R^[[4;4R^C
```

### Expected Behavior

On a recent xterm (run with `xterm -fa Mono -fs 14`, to get TrueType fonts) the output is:

```console
$ printf '\e[6n💓\e[1b\e[6n\n';cat
💓💓
^[[4;1R^[[4;5R^C
```

Windows Terminal also behaves as expected for ✅, this only affects some emoji characters.

### Actual Behavior

As above, the second character is corrupted, see screenshot too.

<img width="550" alt="image" src="https://github.com/microsoft/terminal/assets/5385/bd4a08a3-8d1a-4d2f-806f-30546633342d">

**Comment by lhecker** [comment] 2023-07-24 13:20
Hey! This issue is a duplicate of #15390. 🙂 I believe #15541 made it possible to fix the issue for this particular escape sequence. I'm not entirely sure which part in our code base doesn't handle surrogate pairs, etc., but I suspect it can be discovered by setting a breakpoint on `AdeptDispatch::_FillRect`.

/dup #15390

**Closed** 2023-07-24 13:21 UTC
Labels: Issue-Bug, Needs-Triage
