### ISSUE TITLE
How to delete "Open in Windows Terminal" in the right-click menu of a folder

### ISSUE THREAD

**Issue by oyealex** [microsoft/terminal#8426] opened 2020-11-27 16:09 UTC
I have too many right-click menus, and I want to clean up some infrequently used items. For me, this right-click menu is not very useful. How to clean it up?

![image](https://user-images.githubusercontent.com/40209815/100467671-d9012980-310d-11eb-92c7-571362409a3e.png)

**Comment by KalleOlaviNiemitalo** [comment] 2020-11-27 16:28
This seems a duplicate of <https://github.com/microsoft/terminal/issues/8105>, in which a workaround was posted.

**Comment by oyealex** [comment] 2020-11-27 16:37
> This seems a duplicate of #8105, in which a workaround was posted.

thx, that works for me!

**Closed** 2020-11-27 16:37 UTC
Labels: Needs-Tag-Fix, Needs-Triage
