### ISSUE TITLE
black lines in background when using midnight commander or neovim

### ISSUE THREAD

**Issue by ducaale** [microsoft/terminal#3626] opened 2019-11-19 13:09 UTC
# Environment

```none
Windows build number: 10.0.18363.476
Windows Terminal version (if applicable): 0.6.2951.0
```

# Steps to reproduce

Run midnight commander `mc` with fontSize equal to 12 and with `cascadia code` or `consolas` font.
It is worth noting that with fontSize 14 or 10 the background renders correctly without black lines.

# Expected behavior

Background should be blue with no black lines
![Screenshot (29)](https://user-images.githubusercontent.com/16341131/69148356-03b4ad00-0acc-11ea-95ac-49948d6b1e0a.png)

# Actual behavior

Background has black lines
![Screenshot (31)](https://user-images.githubusercontent.com/16341131/69148364-09aa8e00-0acc-11ea-9774-b53cb50f3990.png)

**Comment by j4james** [comment] 2019-11-19 19:15
I suspect this is a duplicate of #455.

**Comment by egmontkob** [comment] 2019-11-19 21:51
I don't think it's a duplicate. Although that bug also has two screenshots equivalent to the one here, one of them also showing `mc` in particular, that bug talks about the line drawing characters (i.e. the foreground) not touching each other.

This bug is here talks about the background color (blue) not filling the entire cell, leaving a gap.

In this screenshot over here, the period (from the top of a black line to the top of the next black line) is 57 pixels. Also if you magnify and look closely at some repeated piece of text (e.g. all those "4096"s), you'll see that antialiasing goes differently in every second row. In the upper row of each blackline-separated area, horizontal lines (e.g. the ones of digits `2`, `4`, the serif of `1`, `i`, `r` etc.) are 2 pixels tall and super crispy. In every lower row these are uglier 1 pixel half-blue-half-white antialiased + 1 pixel white + 1 pixel half-blue-half-white antialiased.

So a row's height is 28.5 pixels, each text row is presumably 28.5 pixels below the previous one, and here and there (e.g. when rendering the background) rounding to integers kicks in.

Totally sounds like a HiDPI related story.

**Comment by egmontkob** [comment] 2019-11-19 22:10
... although the screenshot of the entire desktop is 1920x1080, which is not HiDPI, unless the screenshot taking software downscaled it in which case who knows what other nasty things it did :) @ducaale What's your monitor's resolution?

A few other things to note:

Those black lines aren't really black, just something darker than desired. It depends based on the neighboring two background colors. It's different between cyan and blue (under "Command Options Right"), between blue and cyan (under "Name Size Modify time") [yup the order of colors also seems to matter], cyan and white (under "Left File Command") etc.

There are _some_ such vertical lines, too, namely either before or after(\*) the vertical line drawing chars. (\*)Presumably according to the parity, I haven't verified.

**Comment by j4james** [comment] 2019-11-19 22:27
You can see the same sort of DPI scaling issues in #2496, #2779, and #2790, all of which were marked as duplicates of #455. I think the title of #455 is a bit misleading, and isn't necessarily a good indication of the underlying cause of the problem.

**Comment by ducaale** [comment] 2019-11-19 22:33
@egmontkob yes the resolution is 1920x1080 with 150% scaling

**Comment by egmontkob** [comment] 2019-11-19 22:44
> You can see the same sort of DPI scaling issues in #2496, #2779, and #2790

Indeed those three bugs are the same as this one.

> I think the title of #455 is a bit misleading

Or rather let's say: #455 is two technically different issues squeezed into one.

> with 150% scaling

How does 150% scaling result in every second row being different? I have no idea :D

**Comment by DHowett-MSFT** [comment] 2019-11-21 20:46
I'm guessing that this is one of those classic D2D 0.5-pixel offset issues :grin:

**Comment by ihor-sviziev** [comment] 2019-11-27 07:17
I have the same issue, workaround - press "ctrl -" one time (decrease font size), and this issue is getting fixed.

Also font size by default looks too big, for instance on Ubuntu it's usually smaller.

**Comment by phelps-matthew** [comment] 2019-12-29 17:39
Scaling via ```ctrl +``` or ```ctrl -``` does not affect line issue for me.

> I have the same issue, workaround - press "ctrl -" one time (decrease font size), and this issue is getting fixed.
> 
> Also font size by default looks too big, for instance on Ubuntu it's usually smaller.

Scaling via ```ctrl +``` or ```ctrl -``` does not affect line issue for me.

**Comment by ducaale** [comment] 2019-12-30 18:09
@phelps-matthew have tried fontSize of 10 or 14.

**Comment by phelps-matthew** [comment] 2019-12-31 02:54
@ducaale Yes I've tried a large range of sizes. There is one particular font and size combination (Delugia Nerd Font at size 10) that did not result in lines, but this would seem to be a special case.

**Comment by george-tsiros** [comment] 2020-01-15 07:06
please, someone tell me i'm not weird for thinking this shouldn't be happening. We've been rendering text for more than three decades now. Certainly it's expected that we've figured it out by now? Please

**Comment by michalwidera** [comment] 2020-01-29 22:10
> I have the same issue, workaround - press "ctrl -" one time (decrease font size), and this issue is getting fixed.
> 
> Also font size by default looks too big, for instance on Ubuntu it's usually smaller.

This workaround does not help.

**Comment by PhilDim1** [comment] 2020-02-15 17:20
Same exact issue here. Changing fonts and font size does nothing. What DOES fix this (for me) is to ensure your 'Scale and Layout' setting under Settings/Display is at 100%. Not really a solution, but perhaps someone brighter than I can fix this. This is pretty much the one issue keeping me from leaving mintty/wsltty and solely using WT.
![image](https://user-images.githubusercontent.com/40040659/74592263-8080f580-4fed-11ea-9250-71d651f3c618.png)

**Closed** 2020-03-28 00:15 UTC
Labels: Area-Rendering, In-PR, Issue-Bug, Priority-2, Product-Terminal, v1-Scrubbed

**Comment by sHAsHiLx** [comment] 2020-04-24 11:51
Lol! Black lines goes out but font's still have line breaks. Tried to change to different fonts - it still breaks vertical lines with [space lines](https://paste.pics/75380426de4ac976e96f5e41c454e60c)

**Comment by PhilDim1** [comment] 2020-04-24 17:38
Same here.From: Roman PapushaSent: Friday, April 24, 2020 7:51 AMTo: microsoft/terminalCc: PhilDim1; CommentSubject: Re: [microsoft/terminal] black lines in background when using midnight commander or neovim (#3626) Lol! Black lines goes out but font's still have line breaks. Tried to change to different fonts - it still breaks vertical lines with space lines—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.
