### ISSUE TITLE
Feature Request: opache with readable text 

### ISSUE THREAD

**Issue by bittin** [microsoft/terminal#1277] opened 2019-06-15 13:17 UTC
Hello!

I am at the Insider Dev Tour in Stockholm, Watching Simon Wåhlin speak right now, would be cool if you could use the opache function without getting text blurred, so you could read whats on the Visual Studio Code, Atom or browser or something like that, that is under the console to easier see what to type from a StackOverflow post, some kind of guide or code that you are working with

**Comment by DHowett-MSFT** [comment] 2019-06-18 00:38
This'll be a duplicate of #603.

**Closed by DHowett-MSFT** 2019-06-18 00:38 UTC
Labels: Issue-Feature, Needs-Tag-Fix, Needs-Triage
