### ISSUE TITLE
Possibility to send Alt + Space to the terminal.

### ISSUE THREAD

**Issue by kpalatzky** [microsoft/terminal#7534] opened 2020-09-04 13:31 UTC
# Environment

```none
Windows build number: Microsoft Windows NT 10.0.18363.0
Windows Terminal version (if applicable): 1.2.2381.0
```

# Steps to reproduce

1. Open Windows Terminal
2. Open WSL / ssh (or PowerShell)
3. Press `Alt + Space`

# Expected behavior

`Alt + Space` should be sent as key to the shell. If a keybinding is stored in the shell, it should work (ZSH / TMUX & co) 

# Actual behavior

`Alt + Space` opens the default Windows RMB on Title Bar Dialog.

**Comment by DHowett** [comment] 2020-09-09 00:14
Thanks for the request! This is a /duplicate of #7125.

**Closed by DHowett** 2020-09-09 00:14 UTC
Labels: Needs-Tag-Fix, Needs-Triage
