### ISSUE TITLE
Feature Request:  Friendly Names For Tabs

### ISSUE THREAD

**Issue by michelforget** [microsoft/terminal#1177] opened 2019-06-08 16:19 UTC
It would be really nice if we could show the name of the shell in the tab title instead of the full path to it.  It would make the tab titles shorter, and allow for easier visual recognition of which tabs are what.  Ideally, if there is more than one tab with the same name it should append "-1", "-2", etc. to the tab name.

**Comment by Summon528** [comment] 2019-06-08 16:25
Probably duplicate of #608

**Comment by DHowett-MSFT** [comment] 2019-06-08 16:57
Yep, that’s a duplicate. Thanks!

**Closed by DHowett-MSFT** 2019-06-08 16:57 UTC
Labels: Needs-Tag-Fix, Needs-Triage

**Comment by keserwan** [comment] 2019-08-06 13:02
it is still not friendly name on my side.
Windows OS
Windows Terminal (Preview)
Version: 0.3.2171.0

**Comment by zadjii-msft** [comment] 2019-08-06 13:06
@keserwan Try adding a `tabTitle` to your profile, with whatever friendly name you'd like.
