### ISSUE TITLE
Terminal crashes when WSL tab tries to display some characters.

### ISSUE THREAD

**Issue by MichaelWalsh** [microsoft/terminal#4145] opened 2020-01-07 23:25 UTC
Terminal (0.7.3451.0) crashes every time I try to cat or curl a html file containing a certain tweet. The entire terminal frame hangs, white out, goes to (Not Responding).
This happens only with the WSL Ubuntu tab and not when I try to cat the same file with powershell in Terminal. It does not crash with WSL under the older 'Ubuntu' launcher from the Windows Store.

# Environment
Windows 10 Pro 1909
Win32NT	10.0.18363.0	Microsoft Windows NT 10.0.18363.0

Windows Terminal (Preview) Version: 0.7.3451.0 from the Windows Store
Ubuntu 18.04.3 LTS installed from the Windows Store

# Steps to reproduce
WSL Ubuntu from the Windows Store installed, Terminal from Windows Store installed
Launch Windows Terminal
Window chrome down arrow: Ubuntu

curl 'https://twitter.com/EU_Commission/status/1213399676201734146' -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:71.0) Gecko/20100101 Firefox/71.0'

curl starts to display the html from that url, but doesn't complete as the whole window frame hangs at some point during the output 

# Expected behavior
I expected the whole output from curl to be displayed, and return to the bash prompt

# Actual behavior
curl starts displaying html output, but then the whole app frame including all tabs becomes unresponsive.

Although Windows displayed the "sending data to Microsoft" from the crash, I don't have a link to share as this computer has no Microsoft Account associated with it, and the feedback tool appears to require one to view crash data.

**Comment by zadjii-msft** [comment] 2020-01-08 14:33
Well yep, that's a pretty easy repro. 

I had to change the command to include `https`, but yea it happens every time.
```
curl 'https://twitter.com/EU_Commission/status/1213399676201734146' -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:71.0) Gecko/20100101 Firefox/71.0'
```

Unfortunately, just `cat`'ing the file _doesn't_ repro this.

**Comment by DHowett-MSFT** [comment] 2020-01-09 20:54
Thanks for the report! This is, largely, a /dupe of #1360.

**Closed by DHowett-MSFT** 2020-01-09 20:54 UTC
Labels: Area-TerminalConnection, Area-TerminalControl, Issue-Bug, Needs-Triage, Priority-1, Product-Terminal, Severity-Crash
