### ISSUE TITLE
WindowsTerminal.exe leak (never exit) after the `wtd.exe new-tab ...` command line process exits.

### ISSUE THREAD

**Issue by ShenHongFei** [microsoft/terminal#16456] opened 2023-12-12 13:55 UTC
### Windows Terminal version

latest commit of main branch

### Windows build number

10.0.22631.0

### Steps to reproduce

Execute the following command on the command line:
```
wtd.exe new-tab ping.exe localhost
```

### Expected Behavior

There is only one WindowsTerminal.exe process after the ping command ends

### Actual Behavior

Each time the above command is executed, there will be one more WindowsTerminal.exe process.

I debugged the redundant WindowsTerminal.exe process and found that it was stuck on the line highlighted in the picture below.
`D:\1\winterm\packages\Microsoft.Windows.ImplementationLibrary.1.0.230824.2\include\wil\filesystem.h`

![image](https://github.com/microsoft/terminal/assets/15074472/ffed717b-3d10-466c-83cd-ede1950cbdfd)

I guessed it might be related to `Microsoft.Windows.ImplementationLibrary`, and then revert this PR https://github.com/microsoft/terminal/pull/16120
After recompiling and building, the problem disappeared and there were no redundant leaking processes.

**Comment by zadjii-msft** [comment] 2023-12-12 15:38
Thanks for filing this!

I noticed this a few weeks back and totally forgot to file or investigate it. I'm guessing we're starting up the settings file watcher as we do the handoff to the monarch, but then never closing.

**Comment by DHowett** [comment] 2023-12-12 23:42
Oh, @zadjii-msft, this is the one that was caused by https://github.com/microsoft/wil/pull/326.

It may have been fixed in https://github.com/microsoft/wil/pull/386

Which we should ingest!

**Comment by DHowett** [comment] 2023-12-12 23:43
(it hasn't been shipped to the nuget feed yet)

**Closed** 2024-01-31 00:01 UTC
Labels: Issue-Bug, Product-Terminal, In-PR, Area-Remoting, Area-Windowing
