### ISSUE TITLE
Crash when selecting some Chinese output

### ISSUE THREAD

**Issue by huoyaoyuan** [microsoft/terminal#1865] opened 2019-07-08 08:11 UTC
# Environment

```none
Windows build number: 10.0.18362.207
Windows Terminal version (if applicable): 0.2.1831.0, Windows Store Build

Any other software?
.Net Core SDK 3.0.100-preview6-012264
Powershell Core 6.2.1
```

# Steps to reproduce

0. The crash reproduces on both cmd and PSCore.
1. Invoke some program that outputs Chinese. I used `dotnet --info`.
2. Drag on the output text for selection.

# Expected behavior

Chinese text can be selected normally. (using conhost)
![image](https://user-images.githubusercontent.com/5644458/60793006-5c2c8300-a199-11e9-92c3-65d5c23b2935.png)

# Actual behavior

As soon as the drag covers or starts at Chinese character, the Terminal crashes.
![image](https://user-images.githubusercontent.com/5644458/60793116-9ac23d80-a199-11e9-9f6a-a84355a046ca.png)
(Dragging over the dual-width `（` character)

# Note

This does not reproduce on output of Powershell `echo` command, and some others.
![image](https://user-images.githubusercontent.com/5644458/60793246-e248c980-a199-11e9-9c9c-ce0315eaff61.png)
Seems not directly caused by certain executables. (Some output of `dotnet.exe` can be selected.)
![image](https://user-images.githubusercontent.com/5644458/60793431-4b304180-a19a-11e9-8f53-bacab05bc094.png)
Not aware of whether Chinese starts with new line.
![image](https://user-images.githubusercontent.com/5644458/60793605-964a5480-a19a-11e9-93a4-08783567a6ba.png)

### My system setting:
Display language = Simplified Chinese
Code page = Simplified Chinese, UTF8 enabled (Active Code Page: 65001)

**Comment by zadjii-msft** [comment] 2019-07-08 14:35
I'm fairly certain this is a dupe of #1549

**Comment by DHowett-MSFT** [comment] 2019-07-08 21:54
Sure is!

**Closed by DHowett-MSFT** 2019-07-08 21:54 UTC
Labels: Needs-Triage, Resolution-Duplicate
