### ISSUE TITLE
Allow multiple default tabs at startup

### ISSUE THREAD

**Issue by Tal128** [microsoft/terminal#3570] opened 2019-11-14 00:20 UTC
![image](https://user-images.githubusercontent.com/29495914/68815814-716d6d00-06b7-11ea-8d42-cf1443b7a825.png)

Allow the default pofile parameter to open multiple tabs when starting the application

**Comment by DHowett-MSFT** [comment] 2019-11-14 01:58
This is a /dupe of #756. Please use the templates, and please search before you report! Thanks!

**Closed by DHowett-MSFT** 2019-11-14 01:58 UTC
Labels: Needs-Tag-Fix, Needs-Triage
