### ISSUE TITLE
Process terminated Error if cancel Write-Progress after opening third pane

### ISSUE THREAD

**Issue by Seekatar** [microsoft/terminal#6428] opened 2020-06-09 11:23 UTC
# Environment

```none
Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.18363.0 Microsoft Windows NT 10.0.18363.0

Windows Terminal
Version: 1.0.1401.0

Any other software? 
PowerShell 7
Name                           Value
----                           -----
PSVersion                      7.0.1
PSEdition                      Core
GitCommitId                    7.0.1
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```

# Steps to reproduce
1. Open a new tab in PS7
2. Split horizontally with Shift+Alt+_
3. Run this in the lower pane
```PowerShell
(0..1000) | % { write-progress -Activity "Testing" -CurrentOperation $_; Start-Sleep -Seconds .5 }
```
4. Split horizontally again under the lower pain with Shift+Alt+_
5. In the second pane, running the progress, do Ctrl+C to stop it

# Expected behavior
The progress should stop

# Actual behavior
Get the following error message and that pane is hung.  You have to close the tab.
```none
Process terminated. Cannot process the operation because the supplied coordinate is not valid. Specify a coordinate within the buffer area of 183,11. (Parameter 'value.Y')
Actual value was 14.
   at System.Environment.FailFast(System.String, System.Exception)
   at Microsoft.PowerShell.UnmanagedPSEntry.Start(System.String, System.String[], Int32)
   at Microsoft.PowerShell.ManagedPSEntry.Main(System.String[])
System.Management.Automation.PSArgumentOutOfRangeException: Cannot process the operation because the supplied coordinate is not valid. Specify a coordinate within the buffer area of 183,11. (Parameter 'value.Y')
Actual value was 14.
   at Microsoft.PowerShell.ConsoleHostRawUserInterface.CheckCoordinateWithinBuffer(Coordinates& c, CONSOLE_SCREEN_BUFFER_INFO& bufferInfo, String paramName)
   at Microsoft.PowerShell.ConsoleHostRawUserInterface.set_CursorPosition(Coordinates value)
   at Microsoft.PowerShell.ProgressPane.Hide()
   at Microsoft.PowerShell.ConsoleHostUserInterface.ResetProgress()
   at Microsoft.PowerShell.Executor.ExecuteCommandHelper(Pipeline tempPipeline, Exception& exceptionThrown, ExecutionOptions options)
   at Microsoft.PowerShell.Executor.ExecuteCommand(String command, Exception& exceptionThrown, ExecutionOptions options)
   at Microsoft.PowerShell.ConsoleHost.InputLoop.Run(Boolean inputLoopIsNested)
   at Microsoft.PowerShell.ConsoleHost.InputLoop.RunNewInputLoop(ConsoleHost parent, Boolean isNested)
   at Microsoft.PowerShell.ConsoleHost.EnterNestedPrompt()
   at Microsoft.PowerShell.ConsoleHost.DoRunspaceLoop(String initialCommand, Boolean skipProfiles, Collection`1 initialCommandArgs, Boolean staMode, String configurationName)
   at Microsoft.PowerShell.ConsoleHost.Run(CommandLineParameterParser cpp, Boolean isPrestartWarned)
   at Microsoft.PowerShell.ConsoleHost.Start(String bannerText, String helpText, String[] args)
   at Microsoft.PowerShell.ConsoleShell.Start(InitialSessionState initialSessionState, String bannerText, String helpText, String[] args)
   at Microsoft.PowerShell.UnmanagedPSEntry.Start(String consoleFilePath, String[] args, Int32 argc)
[process exited with code 2148734499]
```

**Comment by DHowett** [comment] 2020-06-10 00:52
This is a /duplicate of https://github.com/PowerShell/PowerShell/issues/12485

**Closed by DHowett** 2020-06-10 00:52 UTC
Labels: Needs-Tag-Fix, Needs-Triage
