### ISSUE TITLE
Allow users to remove Powershell if Powershell Core or Powershell Preview is installed

### ISSUE THREAD

**Issue by wgyt** [microsoft/terminal#10547] opened 2021-07-02 15:33 UTC
# Description of the new feature/enhancement

If the user has Powershell Core or Powershell Preview installed, allow them to remove the built in Windows Powershell profile. I would use this because I don't want to use the built in Windows Powershell, I would rather use Powershell Preview.

**Comment by KalleOlaviNiemitalo** [comment] 2021-07-02 16:54
Windows Terminal already lets you hide the profile.

![image](https://user-images.githubusercontent.com/46201428/124306611-504cdf00-db6f-11eb-9689-d4100cbdfc7d.png)

**Comment by DHowett** [comment] 2021-07-02 17:01
We're working on a couple things to actually let you delete these. Sorry about that :smile:

I'm gonna mark this one as a /dupe of #5482. When combined with #8324, it'll (1) generate the profile one time and (2) let you delete it without resurrecting it every time

**Closed by DHowett** 2021-07-02 17:01 UTC
Labels: Issue-Feature, Needs-Tag-Fix, Needs-Triage

**Comment by wgyt** [comment] 2021-07-02 18:13
> Windows Terminal already lets you hide the profile.
> 
> ![image](https://user-images.githubusercontent.com/46201428/124306611-504cdf00-db6f-11eb-9689-d4100cbdfc7d.png)

@KalleOlaviNiemitalo Whenever I do that and save it, It reverts itself :|


> We're working on a couple things to actually let you delete these. Sorry about that 😄
> 
> I'm gonna mark this one as a /dupe of #5482. When combined with #8324, it'll (1) generate the profile one time and (2) let you delete it without resurrecting it every time

Thanks for letting me know!

**Comment by KalleOlaviNiemitalo** [comment] 2021-07-02 18:27
> Whenever I do that and save it, It reverts itself :|

Huh, that's not what happens here with Windows Terminal 1.8.1521.0. Which version are you using?

**Comment by wgyt** [comment] 2021-07-02 18:30
> > Whenever I do that and save it, It reverts itself :|
> 
> Huh, that's not what happens here with Windows Terminal 1.8.1521.0. Which version are you using?

I use Terminal Preview 1.9.1523.0, but I found a workaround in https://github.com/microsoft/terminal/issues/6016#issuecomment-631228170

**Comment by DaveEM** [comment] 2021-07-20 20:49
@DHowett - Do #5482 and #8324 really resolve this issue?  While those will keep the profile from being restored if it is deleted from the config file, the Settings UI as of Windows Terminal version 1.9.1942.0 won't let you delete the Windows PowerShell profile.  The "Delete Profile" button is greyed out and it says, "This profile cannot be deleted because it is included by default."

**Comment by wgyt** [comment] 2021-07-21 11:30
While removing them using the config file is good enough for me, I think
that we should be able to remove all default profiles using the UI as that
would make it much easier to do.
