### ISSUE TITLE
Inconsistent/incorrect translations in Spanish localization for settings

### ISSUE THREAD

**Issue by florelis** [microsoft/terminal#12665] opened 2022-03-10 21:05 UTC
### Windows Terminal version

1.13.10395.0

### Windows build number

10.0.22572.0

### Steps to reproduce

Use Terminal in Spanish, then go to Configuración -> Acciones (Settings -> Actions)

### Actual Behavior

Some items are translated inconsistently or incorrectly.
* Most actions use infinitive verbs, but some use imperative: "Cierre la ventana" should be "Cerrar ventana", "Desplácese hacia arriba una página" should be "Desplazarse hacia arriba una página" (likewise for "abajo").
* Some ambiguous words are translated as nouns instead of verbs:
  - "Panel dividido" (as in 'a split panel') should be "Dividir panel" (as in 'do split panel').
  - "Citación de la ventana Quake" ('summon Quake window') should be something like "Invocar ventana de Quake", likewise for "Citación de la ventana de terminal", which also doesn't have Terminal capitalized.
  - "abajo panel de intercambio" should be "Intercambiar panel hacia abajo" (capitalize first word, and change noun by verb), same for all other three directions.
  - "Zoom del panel de alternancia" should probably be "Alternar zoom del panel".

  I would suggest adding notes for the localization team on all items like these that can be understood in multiple ways.
* Next/Previous Tab are translated as "Pestaña anterior" and "Siguiente pestaña" (different order); I'd prefer "Pestaña siguiente" for consistency.

I also noticed that the sorting of the list for picking actions puts the lowercase items at the bottom, so it goes A...Za..z. I would expect it to be Aa...Zz.

**Comment by lechacon** [comment] 2022-03-10 21:08
I like nit-picking at Spanish localizations. I would go through all the strings, but I couldn't find the resources file.

**Comment by zadjii-msft** [comment] 2022-04-13 19:30
Thanks for these suggestions! If you want to go through and nitpick more, the English strings are all listed in [`Resources.resw`](https://cs.github.com/microsoft/terminal?q=path%3A*%2Fresources.resw) files, but there's unfortunately not a good place on the repo that lists all the localized versions of those strings.

**Comment by lhecker** [comment] 2023-05-08 21:54
When filing these as an issue I need to file them as "English source string with key X (was translated as Y but) should be translated as Z". While it's extremely valuable that you brought up these issues, to be entirely frank, I'm unable to effectively submit them to the localization team.

That aside, you also brought up two issues that are unrelated to the localization and need to be fixed by us independently:
* Actions are sorted A-Za-z and not Aa-Zz
* .resw comments are often way too rudimentary and not helpful for human translators

I'll try to address them both in the near term. But I'm not sure what to do about the localization though...

**Comment by florelis** [comment] 2023-05-09 17:11
> When filing these as an issue I need to file them as "English source string with key X (was translated as Y but) should be translated as Z" (see #14293 for instance).

If you can point me to the localized .resw file, I can do that. I know it's not checked in, but maybe it's an artifact in some internal pipeline?

**Comment by lhecker** [comment] 2023-05-10 21:49
Here's a dump of the latest localization as of yesterday: [LocOutput.zip](https://github.com/microsoft/terminal/files/11446252/LocOutput.zip)
It contains all languages, but if you search for "es-ES" you should find all those relevant to you. Specifically, these two files contain almost all relevant strings:
* `src\cascadia\TerminalApp\Resources\en-US\es-ES\Resources.resw` (general UI)
* `src\cascadia\TerminalSettingsModel\Resources\en-US\es-ES\Resources.resw` (settings UI)

At this point I should probably mention that we've been wishing for a way where we could properly accept community translations via GitHub. Unfortunately we haven't had time to further pursue this and internally there's no real support for this either (nor is support planned by the localization team).

**Comment by florelis** [comment] 2023-05-10 22:09
> Here's a dump of the latest localization as of yesterday: [LocOutput.zip](https://github.com/microsoft/terminal/files/11446252/LocOutput.zip)

Thanks. I'll go through it when I have some time :)

> At this point I should probably mention that we've been wishing for a way where we could properly accept community translations via GitHub. 🥲 Unfortunately we haven't had time to further pursue this and internally there's no real support for this either (nor is support planned by the localization team).

On winget-cli what we do is that we have the localized resource files checked in on the repository, so when someone has a suggestion they usually make a PR with the changes. We can't accept them there, but when we file a bug against the localization team to consider, we can just point them to the PR and there it's clear which string IDs are replaced by what text

**Comment by lhecker** [comment] 2023-05-10 22:17
> On winget-cli what we do is that we have the localized resource files checked in on the repository, so when someone has a suggestion they usually make a PR with the changes. We can't accept them there, but when we file a bug against the localization team to consider, we can just point them to the PR and there it's clear which string IDs are replaced by what text

Oh... and you automatically merge any changes coming from the localization team into the repository? That's clever! I think we should do this too...

**Comment by florelis** [comment] 2023-05-10 22:21
> you automatically merge any changes coming from the localization team into the repository?

Well, not automatically. We have a loc pipeline that we run manually to query the loc changes and produces a git patch. We then apply it and send the changes as a PR. Not sure why it was set up that way, maybe to avoid noise from frequent PRs.

I think we only have to run that pipeline twice per release, once to send the new strings and once to get the updated translations.

**Comment by zadjii-msft** [comment] 2023-05-11 14:05
@florelis You have a link to how that works? We've been _very_ curious about this topic, see: https://github.com/microsoft/terminal/issues/10667#issuecomment-1095579029

If we had the localizations from the pipeline just... checked in, then we'd be able to accept community translations? This might be a BIG deal

**Comment by florelis** [comment] 2023-05-12 00:26
Checked in resources in winget-cli repo: https://github.com/microsoft/winget-cli/tree/master/Localization/Resources

Localization pipeline definition: https://github.com/microsoft/winget-cli/blob/master/azure-pipelines.loc.yml
The actual pipeline is internal - can't remember why, maybe TDBuild task wasn't installed in the AzDO project we wanted. From time to time someone runs it manually to submit the strings, then some time later again to get the LocalizedStrings.patch. It is applied and sent as a PR. For example microsoft/winget-cli#2264

We do get suggestions for translation improvements from the community, like microsoft/winget-cli#3044
Then we reference the PR in the internal work item, like https://task.ms/43701445

**Comment by florelis** [comment] 2023-05-12 00:34
> Here's a dump of the latest localization as of yesterday: [LocOutput.zip](https://github.com/microsoft/terminal/files/11446252/LocOutput.zip)

Maybe you already know, but there's some weirdness in the paths there. The resources for each locale seem to be inside the en-us folder, when they probably should be next to it. For example, there is `src\cascadia\TerminalApp\Resources\en-US\es-ES` instead of `src\cascadia\TerminalApp\Resources\es-ES`

**Comment by DHowett** [comment] 2023-05-12 03:31
> > Here's a dump of the latest localization as of yesterday: [LocOutput.zip](https://github.com/microsoft/terminal/files/11446252/LocOutput.zip)
> 
> Maybe you already know, but there's some weirdness in the paths there. The resources for each locale seem to be inside the en-us folder, when they probably should be next to it. For example, there is `src\cascadia\TerminalApp\Resources\en-US\es-ES` instead of `src\cascadia\TerminalApp\Resources\es-ES`

Ohhhhh yes, this is by design according to the TDBuild folks.

We have a build phase to move them about :|

**Comment by florelis** [comment] 2023-05-12 17:54
> When filing these as an issue I need to file them as "English source string with key X (was translated as Y but) should be translated as Z"

@lhecker 

 | String ID | Current | Suggestion | Reason | Comment to dev | 
 | --- | --- | --- | --- | --- | 
 | CloseWindowCommandKey | Cierre la ventana | Cerrar ventana | String is not an instruction to user, but a label for keyboard shortcut. Also for consistency with ClosePaneCommandKey and others | Maybe add a comment that it is a label for a keyboard shortcut | 
 | ScrollDownPageCommandKey ScrollUpPageCommandKey |  | Replace "Desplácese" by "Desplazarse" | Same; should be consistent with ScrollDownCommandKey and ScrollToTopCommandKey | Same | 
 | ScrollDownCommandKey ScrollDownSeveralRowsCommandKey ScrollUpCommandKey ScrollUpSeveralRowsCommandKey |  | Replace "Desplazar" by "Desplazarse" | Consistency across all Scroll*CommandKey strings |  | 
 | SplitPaneCommandKey | Panel dividido | Dividir panel | String does not refer to an object but to an action as it is the label for a keyboard shortcut | Maybe add a comment that it is a label for a keyboard shortcut | 
 | TogglePaneZoomCommandKey | Zoom de panel de alternancia | Zoom de panel de alternancia | Same | Same | 
 | SwapPaneCommandKey | Panel de intercambio | Intercambiar panel | Same; should be consistent with SwapPaneToLastUsedPane | Same | 
 | Mostrar u ocultar ventana Desastre | {0} panel de intercambio | Intercambiar panel hacia {0} | Same; should be consistent with SwapPaneToLastUsedPane. The full string would be something like "Intercambiar panel hacia abajo" or "Intercambiar panel hacia la derecha" | I saw the string as "abajo panel de intercambio". Even if the translation was correct, there was an assumption on the code that the direction would be in lowercase, which may not always be the case.  If this is the only place you use the direction strings, maybe you could add the context where they are used as comments. Another issue is that "DirectionRight" would probably be translated as just "derecha" but the way it would be used in this sentence would be as "la derecha". Same as would happen in English if the sentence had been "Swap panel to the right" or "Swap panel up"; the strings for each direction is different | 
 | QuakeModeCommandKey | Mostrar u ocultar ventana Desastre | Mostrar u ocultar ventana Quake | Quake is the name of a videogame, and doesn't seem to have been translated to Spanish there | Maybe add {locked} comment for Quake | 
 | NextTabCommandKey | Siguiente pestaña | Pestaña siguiente | Consistency with PrevTabCommandKey |  |

**Comment by lhecker** [comment] 2024-05-17 15:32
Internally filed as 553438 in the `GlobalCollaborationService` project.

**Closed** 2024-05-28 18:04 UTC
Labels: Issue-Bug, Product-Terminal, Priority-3, Area-Localization
