### ISSUE TITLE
Terminal's scroll bar disappeared

### ISSUE THREAD

**Issue by qianbenhyu** [microsoft/terminal#15036] opened 2023-03-23 03:23 UTC
### Windows Terminal version

up to date

### Windows build number

10.0.22000.1455

### Steps to reproduce

When I try the default cmd, the scroll bar is normal, but when I use “Terminal”, when I enter a command like “ipconfig”, the scroll bar disappears,  What is the problem?
powershell does not have a problem like this.
![image](https://user-images.githubusercontent.com/32768810/227093542-92191350-eea0-4f50-8330-1e93c0b13fe5.png)
![image](https://user-images.githubusercontent.com/32768810/227093953-ce3ad345-a0aa-4892-86c1-4f453e44abe7.png)

### Actual Behavior

Terminal's scroll bar disappeared

**Comment by zadjii-msft** [comment] 2023-03-23 13:20
Could you share your [settings.json file](https://github.com/microsoft/terminal/wiki/Frequently-Asked-Questions-(FAQ)#where-can-i-find-the-settings-file)/?

**Comment by j4james** [comment] 2023-03-24 00:30
I think this is just the result of having a light color scheme (i.e. you've got a whitish background color), with a dark theme (which gives you a light scrollbar). The scrollbar is rendered with a level of transparency, so the underlying background color shows through, but when both the scrollbar and the background are light, the result is essentially invisible.

**Comment by qianbenhyu** [comment] 2023-03-24 00:50
Thank you for your attention, but what I want to express is not that my scroll bar is invisible, but that I can't turn the page up or down. The problem doesn't seem to be related to the "setting.json" file, I have the same problem with similar terminal software, except the native console of cmd.

**Comment by j4james** [comment] 2023-03-24 00:59
@qianbenhyu If you move your mouse to the right edge of the window, the scrollbar should appear, and then you can move the page up and down exactly as you do in the native console.

**Comment by qianbenhyu** [comment] 2023-03-24 01:02
it seems to be related to the buffer size, I can't turn the page with the mouse, I can't turn the page even if I modify the buffer size of cmd.

**Comment by j4james** [comment] 2023-03-24 01:04
It really would help if you shared your settings file.

**Comment by qianbenhyu** [comment] 2023-03-24 01:19
[settings.zip](https://github.com/microsoft/terminal/files/11057614/settings.zip)

**Comment by j4james** [comment] 2023-03-24 01:36
I can't reproduce the issue with your settings, but I wonder if maybe something you've run has switched to the alt buffer. If that's the case, you can try switching it back like this (assuming you're using the cmd shell):

1. Type `echo ` (with a space)
2. Press <kbd>Ctrl</kbd>+<kbd>[</kbd> (which should show up as `^[`).
3. Type `[?1049l`
4. Press <kbd>Enter</kbd>

**Comment by qianbenhyu** [comment] 2023-03-24 01:58
thank twice for you, Maybe I can only use powershell in the future, not a big problem.
I try commands below, and this problem is solved in the current console, but reopening cmd appears again.
`mode con cols=120 lines=400`

**Comment by zadjii-msft** [comment] 2023-03-27 12:13
That somehow makes... less sense? `mode` shouldn't be able to affect the buffer size of a Terminal tab - nor should it be changable by any CLI application...

Is there anything in `HKEY_CURRENT_USER\Software\Microsoft\Command Processor`? (or, `HKEY_LOCAL_MACHINE\Software\Microsoft\Command Processor\AutoRun`?)

Does the same thing happen if you run the same command from a PowerShell tab? 

If you've already got text in the buffer, like doing a `dir c:\windows\system32`, then run `ipconfig`, does the same behavior repro? 

Really just trying to narrow down who is causing this.

**Comment by zadjii-msft** [comment] 2023-04-13 21:14
Hey all, our bot's been acting up the last few weeks. This issue has been marked as requiring author feedback, but hasn't had any activity in the last week. We're gonna close it to tidy up. Feel free to continue the discssion in the comments - we can always reopen if new information comes to light. Thanks!

**Closed** 2023-04-13 21:18 UTC
Labels: Issue-Bug, Needs-Author-Feedback, Needs-Triage
