### ISSUE TITLE
No taskbar icon visible, taskbar buttons jumping

### ISSUE THREAD

**Issue by ygoe** [microsoft/terminal#15402] opened 2023-05-23 09:35 UTC
### Windows Terminal version

1.16.10261.0

### Windows build number

10.0.19045.0

### Steps to reproduce

Open the app.

### Expected Behavior

A single taskbar button should appear and stay there. It should have an icon that makes the button distinguishable.

### Actual Behavior

When the app starts, I see two taskbar buttons. The first has no icon (empty space), the second has the terminal app icon. The second then slides over the first button. After that, the icon vanishes and the single remaining button has an empty space with no icon.

When closing the window, the taskbar button instantly duplicates. The first has the terminal app icon, the second is empty. then both disappear as the app closes.

**Comment by lhecker** [comment] 2023-05-23 10:20
Thanks for the report! But given your description, I believe this is effectively a duplicate of #6507 which got fixed in #15165. The fix has not shipped yet (it's slated for 1.18).

/dup #6507

**Closed** 2023-05-23 10:20 UTC
Labels: Issue-Bug, Needs-Triage
