### ISSUE TITLE
Allow more granular font size settings

### ISSUE THREAD

**Issue by schffp** [microsoft/terminal#4135] opened 2020-01-07 16:18 UTC
# Description of the new feature/enhancement

I would love to see the ability to adjust the font size in a more granular fashion. Every terminal/text editor seems to render the same font size a little differently. For example: Sublime text at font size 11, is optimal for me, with the font I use. Windows Terminal at 11 is a little to small, but 12 is way to large.

# Proposed technical implementation details (optional)

I'm not sure if this is technically possible, but it would be great if you could allow float values for the font size. Like 11.1, 11.2, etc.

**Comment by DHowett-MSFT** [comment] 2020-01-09 20:53
Thanks for the request! I'd rather approach this from the side of figuring out _why_ rendering is different and whether there's something we can do to make it better rather than by adding support for floating-point font sizes.

**Comment by edoardoc** [comment] 2020-11-30 09:22
this is useful for old fonts, such as [Terminus](https://files.ax86.net/terminus-ttf/)  just read the paragraph "Recommended font sizes" which has a nice explanation of this

**Comment by kayzzen01** [comment] 2021-09-05 22:06
@DHowett-MSFT

I don't understand almost anything about font rendering, for me it's a bit confusing. For example using Sublime Text setting the font to size 10 is the same as size 16 in Windows command prompt 😄

Basically if an improvement is possible, I would like the Windows Terminal fonts to be rendered the same way as the command prompt, powershell or cmder.
The fonts from these terminals I mentioned seem to be a little sharper and a little thinner (the inner outline of the fonts looks better). I for example could not make the font size of Windows Terminal equal to the command prompt. It must be what I mentioned about the contour being a little different (maybe I'm talking about antializing).
Here in the documentation there is even an example, the letter "e" the inner outline almost closes the letter.
https://docs.microsoft.com/en-us/windows/terminal/customize-settings/profile-advanced

I'm starting to use Windows Terminal and I'm really enjoying it. This was really missing for Windows.
If you have any tips I appreciate it.

This issue here is closed, it is recommended that I open a new one to a new analysis?

**Comment by jeffrson** [comment] 2021-09-16 17:52
I have an issue that may be related.

I use Iosevka (https://github.com/be5invis/Iosevka), one of the "fixed" variants. The strange thing is, that sizes of 10 and 11 appear to be the same actual size. There are other values that result in equal size.

That happens for other fonts as well, eg Meslo (https://github.com/andreberg/Meslo-Font), however, the "twin values" are different (12 and 13, if memory serves).

So I thought I could use some floating value , but it's not possible yet. But maybe you can find why the problem occurs in the first place.

**Comment by zadjii-msft** [comment] 2021-12-09 16:21
Looks like #6678 is a dupe of this one! However, this one was open first, but it looks like #6678 has more upvotes, so I'm going to defer to that one. That should more correctly reflect the community interest in the underlying issue here. Thanks all!

/dup #6678

**Closed by zadjii-msft** 2021-12-09 16:21 UTC
Labels: Issue-Feature, Needs-Triage, Needs-Tag-Fix

**Comment by kayzzen01** [comment] 2021-12-18 15:34
I don't understand almost anything about font rendering, for me it's a bit confusing. For example using Sublime Text setting the font to size 10 is the same as size 16 in Windows command prompt 😄

Basically if an improvement is possible, I would like the Windows Terminal fonts to be rendered the same way as the command prompt, powershell or cmder.
The fonts from these terminals I mentioned seem to be a little sharper and a little thinner (the inner outline of the fonts looks better). I for example could not make the font size of Windows Terminal equal to the command prompt. It must be what I mentioned about the contour being a little different (maybe I'm talking about antializing).
Here in the documentation there is even an example, the letter "e" the inner outline almost closes the letter.
https://docs.microsoft.com/en-us/windows/terminal/customize-settings/profile-advanced

I'm starting to use Windows Terminal and I'm really enjoying it. This was really missing for Windows.
If you have any tips I appreciate it.
