### ISSUE TITLE
"Tasks" in start menu take ~20 seconds to load

### ISSUE THREAD

**Issue by Fadexz** [microsoft/terminal#9641] opened 2021-03-28 08:07 UTC
Using "Tasks" in the start menu when right-clicking to open takes a long time to open like 20 seconds and I end up opening too many because it isn't very responsive.

**Comment by DHowett** [comment] 2021-03-28 19:25
I don't believe this is a duplicate of #9644 -- this looks like it's about the jump list taking a long time to open.

@Fadexz how many profiles do you have?

**Comment by Fadexz** [comment] 2021-03-28 22:49
> I don't believe this is a duplicate of #9644 -- this looks like it's about the jump list taking a long time to open.
> 
> @Fadexz how many profiles do you have?

The tasks (windows) themselves that takes a long time to appear. Accident opened like 12 different ones because they were so delayed so I clicked on all of them a few times. It was just after I installed the app.
I just tried again now and just opening one 'task' takes about 5 seconds (still a bit long) but multiple windows will take like 10 to 15 seconds, maybe even slightly longer for a lot.

**Comment by zadjii-msft** [comment] 2021-03-29 11:29
Okay I concur this isn't #9644 - @Fadexz could you look at #9524 and see if that's the same thing as you're reporting? They sure do sound similar...

**Comment by Fadexz** [comment] 2021-03-29 11:53
Same issue as #9524.

the #9644 issue sounds like some weird window focus issue and I don’t know if that’s related. However for my context menu I do have open in command prompt instead of the default powershell. I forgot how I changed it but I remember doing it. If that is the cause then I guess you know.

**Comment by zadjii-msft** [comment] 2021-03-29 12:51
Okay super, thanks for confirming!

/dup #9524

**Closed by zadjii-msft** 2021-03-29 12:51 UTC
Labels: Needs-Attention, Needs-Triage
