### ISSUE TITLE
SSH session in Ubuntu terminal slows down, hangs, and eventually disconnects

### ISSUE THREAD

**Issue by alexqfredrickson** [microsoft/terminal#7829] opened 2020-10-05 17:48 UTC
# Environment

```none
Windows build number: Microsoft Windows NT 10.0.18362.0
Windows Terminal version: 1.3.2651.0
Any other software? No
```

# Steps to reproduce

1. Open a Ubuntu terminal using Windows Terminal
2. SSH into some Linux machine (perhaps create an AWS EC2 free-tier Ubuntu instance)
3. Enter commands into the terminal (it doesn't matter which), for example:

```
$ sudo apt-get update
$ sudo apt-get install docker-ce docker-ce-cli containerd.io
```

# Expected behavior

The commands execute.

# Actual behavior

The first few commands work fine, but the overall terminal performance quickly degrades. It becomes sluggish at first - then it outright hangs. Executing commands doesn't work; pasting commands into the console doesn't work; Control+C/X do not help. Terminal cursor keeps blinking. Windows Terminal memory usage is fine. The whole thing just hangs until the SSH session is disconnected from inactivity - then Windows Terminal kind of wakes back up. This happens consistently and occurs during every SSH session, independent of the commands executed during that session. For me, it is rendering SSH impossible.

```
alex@desktop:/mnt/c/Users/alex$ ssh_ubuntu
Welcome to Ubuntu 18.04.5 LTS (GNU/Linux 5.3.0-1034-aws x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

  System information as of Mon Oct  5 17:23:43 UTC 2020

  System load:  0.0               Processes:           94
  Usage of /:   30.8% of 7.69GB   Users logged in:     0
  Memory usage: 28%               IP address for eth0: 172.31.42.156
  Swap usage:   0%

 * Kubernetes 1.19 is out! Get it in one command with:

     sudo snap install microk8s --channel=1.19 --classic

   https://microk8s.io/ has docs and details.

 * Canonical Livepatch is available for installation.
   - Reduce system reboots and improve kernel security. Activate at:
     https://ubuntu.com/livepatch

5 packages can be updated.
0 updates are security updates.

New release '20.04.1 LTS' available.
Run 'do-release-upgrade' to upgrade to it.


*** System restart required ***
Last login: Mon Oct  5 17:05:18 2020 from 96.58.56.48

ubuntu@ip-123-45-67-891:~$ sudo apt-get update
Hit:1 http://us-east-1.ec2.archive.ubuntu.com/ubuntu bionic InRelease
Hit:2 http://us-east-1.ec2.archive.ubuntu.com/ubuntu bionic-updates InRelease
Hit:3 http://us-east-1.ec2.archive.ubuntu.com/ubuntu bionic-backports InRelease
Hit:4 http://security.ubuntu.com/ubuntu bionic-security InRelease
Hit:5 https://download.docker.com/linux/ubuntu bionic InRelease
Hit:6 http://ppa.launchpad.net/ansible/ansible/ubuntu bionic InRelease
Reading package lists... Done

ubuntu@ip-123-45-67-891:~$ sudo apt-get install docker-ce docker-ce-cli containerd.ioclient_loop: send disconnect: Connection reset by peer

alex@desktop:/mnt/c/Users/alex$ ssh_ubuntu ^C
```

**Comment by DHowett** [comment] 2020-10-05 17:54
So.. I work through ssh from WT probably equally as often as I'm working locally. I've not seen anything like this.

To start isolating variables:
Does it repro if you run ssh _outside of Terminal_?

**Comment by alexqfredrickson** [comment] 2020-10-05 19:13
Nope, PuTTY works fine.

**Comment by DHowett** [comment] 2020-10-05 19:13
I mean _using the same SSH client, just outside of terminal_... not a totally different SSH client. :smile:

**Comment by alexqfredrickson** [comment] 2020-10-05 19:23
Sorry - not clear on the question.  How would one use Windows Terminal to SSH into a machine, but outside of the terminal per se?

**Comment by zadjii-msft** [comment] 2020-10-05 19:26
@alexqfredrickson Try using ssh directly from a `conhost.exe` window. For ex, try <kbd>Win+R</kbd>, "wsl.exe", then run `ssh` in that console window that appears.

**Comment by alexqfredrickson** [comment] 2020-10-05 19:28
I believe my issue is exclusively related to Windows Terminal - both WSL and PuTTY are unaffected.

**Comment by jdebp** [comment] 2020-10-06 07:02
There are well-known problems that act like this.  They aren't anything to do with the local terminal.  They aren't even really anything to do with the local SSH client (which is *not* Windows Terminal, by the way).  [They are to do with Path MTU Discovery.](https://unix.stackexchange.com/q/124946/5132)  Such problems can have various causes, such as network administrators erroneously blocking ICMP.

**Comment by alexqfredrickson** [comment] 2020-10-06 15:29
@jdebp How would I confirm that, and if confirmed, how would I fix that? PuTTY seems to be working fine - I'm only running up against this issue with WSL and Windows Terminal.

**Comment by jdebp** [comment] 2020-10-06 18:34
The fact that Windows Terminal merrily keeps on working as soon as there's an application program performing I/O again, rather than the SSH client doing no terminal I/O because the network connection is hung, tells you that you aren't hitting a problem in Windows Terminal.

The procedure for diagnosing this is to manually reduce the MTU, which one can do with `netsh` in native Windows NT. You'd also possibly end up fiddling with the `EnablePMTUBHDetect` and `EnablePMTUDiscoveryregistry` settings.  On Linux-based operating systems one fiddles with `ifconfig` or `ip`, and some of the kernel's runtime tunables.  I couldn't tell you what you'd do with WSL in the mix, as it depends from whether you are using WSL1 or WSL2.  See also Microsoft/WSL#3957 .

**Comment by alexqfredrickson** [comment] 2020-10-06 18:58
Thanks @jdebp.  Do you know if manual MTU configuration is required for the majority of Windows 10 Professional users, in order to use Windows Terminal?  Also - I'm not a professional network engineer - are there any risks or trade-offs in reducing one's MTU?  Would changing my MTU potentially compromise PuTTY's performance?

**Comment by zadjii-msft** [comment] 2020-10-07 11:29
Thanks for chiming in on this thread @jdebp - I didn't know anything about MTU before this, so I wouldn't have even known where to begin debugging this. It _sounds_ like this is an issue with a root cause outside the Terminal codebase, so I'm gonna close it as external, but please feel free to continue the conversation for future readers.

Thanks!

**Closed by zadjii-msft** 2020-10-07 11:29 UTC
Labels: Needs-Attention, Needs-Tag-Fix, Needs-Triage

**Comment by jdebp** [comment] 2020-10-08 13:03
For what it's worth, this is something that has a strong dependence from exactly what machines you are communicating with over what network.  It _shouldn't_ be required _at all_ in the usual case, but then in the usual case network administrators shouldn't be configuring their routers and firewalls to drop all ICMP traffic.  Yet they sometimes do.

And Path MTU Discovery problems aren't really a Windows Terminal thing, as the locus of the problem is in the TCP connection that is underlying the SSH protocol.  In this scenario what happens is that the SSH client or SSH server end effectively becomes unable to transmit queued-up I/O because the amount of I/O to be transmitted ends up transmitting a large IP packet that gets silently lost (because no ICMP packet comes back to report this).  The net _appearance_ is that the terminal isn't doing anything, but the actual problem is that one or other program at the ends of the SSH connection is stuck trying to transmit stuff.  The SSH programs are stuck.  The _terminal emulator_ program is fine, albeit in a mode where special characters won't interrupt the running SSH program (because that's how SSH clients work, as they need special character processing to happen on the remote host, not at the local end).

I know this, by the way, from years of experiencing [questions like this](https://unix.stackexchange.com/q/412192/5132).  There's a lot of literature on this, far too much for me to collate, including Microsoft's own doco on those registry settings and a vast number of people writing about it.  See, for just three fairly random examples, [this Q&A](https://networkengineering.stackexchange.com/q/28984/70828), [this Microsoft doco](https://support.microsoft.com/en-gb/help/900926/), and [this web log entry](https://blog.securityevaluators.com/icmp-the-good-the-bad-and-the-ugly-130413e56030).

**Comment by alexqfredrickson** [comment] 2020-10-08 15:09
I think this information is potentially helpful for users in a professionally managed network environment - I definitely appreciate @jdebp's comments and expertise here and I'd be willing to concede that the issues I'm seeing may be a red herring - not problems with Windows Terminal _per se._

I do want to be clear though: the behavior is occurring on a pretty-much-out-of-the-box Windows 10 Professional installation, while SSHing into a definitely-out-of-the-box AWS Ubuntu EC2 instance, on a network (consisting of a single user 😉) upon which none of the network administrators have ever performed any sort of bespoke router, firewall, ICMP, nor MTU configurations (none of my network admins are accredited, paid, or even qualified 😉). SSH seemed to me to be a pretty basic use-case; I hope readers can understand my confusion/frustration that this operation doesn't just work (and may require special MTU configuration).

I'd still like to investigate potential MTU issues, but I'm a little paranoid that messing around with `netsh` may disrupt my ~~home network~~ non-virtualized production network environment.

And I'm having a hard time reproducing the issues - they seem to happen sporadically, and the sluggishness always eventually culminates in a `client_loop: send disconnect: Connection reset by peer` error.
