### ISSUE TITLE
Bug Report - window draggable only in small section

### ISSUE THREAD

**Issue by mkontsek** [microsoft/terminal#1581] opened 2019-06-25 06:24 UTC
# Environment

```[Version 10.0.18362.175]```

# Steps to reproduce

1. Install from store
2. Open program
3. Hover with mouse on red section, try to drag and move
4. Fail.

# Expected behavior

Dragging window with mouse works in the red section and green section

![image](https://user-images.githubusercontent.com/2892242/60074097-6a52bc00-9722-11e9-8d6f-3b68beaf3304.png)

# Actual behavior

Dragging window with mouse does not work in the red section, can be dragged only by hover and mouse press on the green section.

**Comment by Shorotshishir** [comment] 2019-06-25 06:40
Duplicate of #1375

**Comment by carlos-zamora** [comment] 2019-06-25 23:24
Megathread on #1375 
Duplicate of #564

**Closed by carlos-zamora** 2019-06-25 23:24 UTC
Labels: Area-User Interface, Issue-Bug, Product-Terminal, Resolution-Duplicate
