### ISSUE TITLE
I can't select Ubuntu sometimes.

### ISSUE THREAD

**Issue by liyu0310** [microsoft/terminal#7557] opened 2020-09-08 01:45 UTC
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18363.1016]
Windows Terminal version (if applicable):1.2.2381.0

Any other software?
Ubuntu 20.04 LTS

# Steps to reproduce
1,Open Windows Terminal.
2,Select the down arrow next to [+].
3,Sometimes the Ubuntu 20.04 LTS shows, sometimes it didn't.
<!-- A description of how to trigger this bug. -->

# Expected behavior

<!-- A description of what you're expecting, possibly containing screenshots or reference material. -->
I want the Ubuntu 20.04 LTS shows every time.
# Actual behavior

<!-- What's actually happening? -->

**Comment by KalleOlaviNiemitalo** [comment] 2020-09-08 07:46
May be a duplicate of <https://github.com/microsoft/terminal/issues/7199>.

**Comment by DHowett** [comment] 2020-09-08 16:21
Indeed! /dup #7199

**Closed by DHowett** 2020-09-08 16:21 UTC
Labels: Needs-Tag-Fix, Needs-Triage
