### ISSUE TITLE
ColorTool does not work on Linux distributions

### ISSUE THREAD

**Issue by Aylexx** [microsoft/terminal#5718] opened 2020-05-03 11:36 UTC
**ColorTool** does not work on **Linux distributions**.

**- Windows Terminal Version: 0.11.1191.0**

**- Microsoft Windows [Version 10.0.18363.815]**

**Comment by DHowett-MSFT** [comment] 2020-05-03 17:33
What happens? How are you running it?

**Comment by Aylexx** [comment] 2020-05-03 19:53
When running `ColorTool.exe SCHEMENAME` without extension, there is no problem.
But when I run ColorTool.exe SCHEMENAME.EXTENSION with extension, an error occurs. 
@DHowett

**Comment by Aylexx** [comment] 2020-05-03 19:53
Sorry for the late answer

**Comment by DHowett** [comment] 2020-05-03 20:16
> Sorry for the late answer

No need to apologize!

**Comment by DHowett-MSFT** [comment] 2020-05-03 22:31
Thanks for the info! Looks like this is a /dupe of #5326.

**Closed by DHowett-MSFT** 2020-05-03 22:31 UTC
Labels: Needs-Tag-Fix, Needs-Triage
