### ISSUE TITLE
Rendering problem, blurry text

### ISSUE THREAD

**Issue by fahadabdulaziz** [microsoft/terminal#5759] opened 2020-05-05 23:54 UTC
# Environment
Microsoft Windows [Version 10.0.18363.778]

# Steps to reproduce

I got this bug on last update!

# Expected behavior

Text should be clear.

# Actual behavior

I get blurry text then renders good then bad, weird rendering!
As you see first 5 lines are good, the rest are blurry. the good lines came after scrolling.
Mean the whole screen goes blurry then when scrolling it renders good!
![WindowsTerminal](https://user-images.githubusercontent.com/5483584/81126668-b1196100-8f44-11ea-97a5-befc24d9137f.jpg)

I use CMD by the way I don't know about PS

**Comment by zadjii-msft** [comment] 2020-05-06 13:21
@fahadabdulaziz Is this the legacy console or the new Windows Terminal? (If you're just running "Command Prompt" or `cmd.exe` directly, it's the legacy console.) If this is the Windows Terminal, could you share which version?

Are you using anything like remote desktop? This _looks_ like it's mpeg compression or something gone wrong, but it's hard to be sure.

**Comment by fahadabdulaziz** [comment] 2020-05-06 18:42
@zadjii-msft I'm using Windows Terminal Version 0.11.1251.0
I'm not using remote desktop.

I tried disabling ClearType but nothing happened.

Ass you can see in this attachment all lines are blurry and if I scroll up or down the lines re-render ok. the last line is rendered normally.

![WT](https://user-images.githubusercontent.com/5483584/81215547-2f781080-8fe2-11ea-9303-32cf806d052e.png)

**Comment by bazilious** [comment] 2020-05-07 12:58
I have the same. It started since the last update (version 0.11.1251.0). When I first return to the window or tab, everything is clear, but then everything, except from the current command line, becomes rapidly more and more blurry until it gets such blurry as in the screenshots. That happens in seconds. Every result is blurry and it happens to every profile, PowerShell, Command Prompt, WSL, everywhere, no matter what aliasing method I use, greyscale or cleartype.

![WindowsTerminal_idOoSjQk7U_cropped_01](https://user-images.githubusercontent.com/17430026/81296806-20916c80-907b-11ea-9832-f47b704f1028.png)

![WindowsTerminal_ncd5KGlw1n_cropped_01](https://user-images.githubusercontent.com/17430026/81296797-1e2f1280-907b-11ea-9a56-d04eb470323e.png)

![WindowsTerminal_1FIamCdL9Z_cropped_01](https://user-images.githubusercontent.com/17430026/81296808-212a0300-907b-11ea-905f-78a15eb1c1d7.png)

**Comment by DHowett-MSFT** [comment] 2020-05-07 14:52
I’m hoping to find a common thread between the two of you. 

What hardware-display, GPU, etc.-are you using?

What font are you using? What size?

Are you using display scaling? What factor?

**Comment by reli-msft** [comment] 2020-05-07 16:22
Are you enabled "Conservative Morphological Anti-Aliasing" in Intel's graphics driver?
There are some old bugs about this: https://bugzilla.mozilla.org/show_bug.cgi?id=1145987

**Comment by bazilious** [comment] 2020-05-07 16:34
> 
> 
> I’m hoping to find a common thread between the two of you.
> 
> What hardware-display, GPU, etc.-are you using?
> 
> What font are you using? What size?
> 
> Are you using display scaling? What factor?

Intel Core i5-4460
No external GPU
16GB RAM
1680x1050 22'' monitor (Samsung 2232BW)
100% scale
Windows 10, build 19041.208

It happens both on default font (Cascadia Mono 12pt) and Consolas 10pt.

**Comment by fahadabdulaziz** [comment] 2020-05-07 17:42
Processor: Intel(R) Core(TM) i7-4790T CPU @ 2.70GHz
Display: Intel HD Graphics 4600, nVidia GeForce 830A
Ram: 16GM
Scale: 100%
Resolution: 1920*1080
OS: Microsoft Windows [Version 10.0.18363.778]

BTW I have the same problem with Edge and had it Azure Data Studio, with Azure DS I solve it by adding --disable-gpu.
As I know this problem exists in some apps the based on chromium. Chrome browser work fine with me!

**Comment by bazilious** [comment] 2020-05-07 18:10
> 
> 
> Processor: Intel(R) Core(TM) i7-4790T CPU @ 2.70GHz
> Display: Intel HD Graphics 4600, nVidia GeForce 830A
> Ram: 16GM
> Scale: 100%
> Resolution: 1920*1080
> OS: Microsoft Windows [Version 10.0.18363.778]
> 
> BTW I have the same problem with Edge and had it Azure Data Studio, with Azure DS I solve it by adding --disable-gpu.
> As I know this problem exists in some apps the based on chromium. Chrome browser work fine with me!

I have the same problem on Edge too.

**Comment by DHowett-MSFT** [comment] 2020-05-11 05:51
Thoughts; @miniksa suggested that we might need to offer a feature to disable hw acceleration like Chrome/Edge do. If there's no way for us to get the Intel driver to back off, we need a software solution.

**Comment by miniksa** [comment] 2020-05-11 05:54
> Thoughts; @miniksa suggested that we might need to offer a feature to disable hw acceleration like Chrome/Edge do. If there's no way for us to get the Intel driver to back off, we need a software solution.

I also have the terrible idea of detecting this one bad Intel chipset and turning off diff rendering for it...

**Comment by DHowett-MSFT** [comment] 2020-05-11 06:17
Somebody reported that for _nVidia cards_, they could get this fixed by turning off "Image Sharpening".

**Comment by fahadabdulaziz** [comment] 2020-05-11 08:16
BTW I have two card on my machine nVidia & Intel.
I tried disabling all intel driver options but nothing changed, I didn't find "Image Sharpening" in the settings.

**Comment by sbwiecko** [comment] 2020-05-11 11:45
I have the same issue, either looking at the integrated (laptop) or external screen. The thing is that it worked fine before the current version of Windows Terminal (0.11.1251.0). I also noticed that the tab of Terminal are somehow 'blinking', not sure if these are linked.

**Comment by msopko81** [comment] 2020-05-11 12:24
I have the same issue with an nvidia card. I searched for image sharpening in my 3d settings, but it is not there. Also, when I plug my laptop into an external display, everything looks great. This issue only comes up when using the laptop's display.

**Comment by miniksa** [comment] 2020-05-11 16:52
> > Thoughts; @miniksa suggested that we might need to offer a feature to disable hw acceleration like Chrome/Edge do. If there's no way for us to get the Intel driver to back off, we need a software solution.
> 
> I also have the terrible idea of detecting this one bad Intel chipset and turning off diff rendering for it...

> I have the same issue with an nvidia card. I searched for image sharpening in my 3d settings, but it is not there. Also, when I plug my laptop into an external display, everything looks great. This issue only comes up when using the laptop's display.

Okay so that dumb idea is out then.

I'll just add a global toggle to turn off differential rendering as that's the big thing that I think changed.

**Closed** 2020-05-11 21:54 UTC
Labels: Area-Rendering, In-PR, Issue-Bug, Priority-0, Product-Terminal

**Comment by DHowett-MSFT** [comment] 2020-05-12 00:20
If one of you would be willing to test the rendering options introduced in #5853, would you please reach out via e-mail? My address is in my profile.

**Comment by DHowett-MSFT** [comment] 2020-05-12 19:29
@bazilious reached out and is testing. Thanks!

@fahadabdulaziz just to be 100% sure, can you copy the version number from our _About_ dialog?

---

I managed to reproduce this as well. Here's, roughly, what I did.

**This requires running Terminal unpackaged!**

1. Install the latest [DCH driver from Intel](https://downloadcenter.intel.com/download/29557) (hope you have a card that supports it)
2. Run WindowsTerminal.exe
3. Observe that all non-active text blurs slowly.
4. Go into the "Intel Graphics Command Center"... Manage your game library:
   * Manually Select
   * WindowsTerminal.exe
5. Make sure that WindowsTerminal has antialiasing set to "Always Off"
   * (Make sure you hit "Save")
6. Relaunch WT
7. Try to repro
8. Set it to Always On, CMAA (Save)
9. Relaunch WT
10. Observe.

**Comment by bazilious** [comment] 2020-05-12 20:03
> 
> 
> @bazilious reached out and is testing. Thanks!
> 
Both `experimental.rendering.forceFullRepaint` and `experimental.rendering.software` fix it, but with the latter the rendering is noticeably better. Have a look:

`experimental.rendering.forceFullRepaint = true`
![WindowsTerminal_OdNlhuRxvl](https://user-images.githubusercontent.com/17430026/81739719-7ebbb680-94a4-11ea-97c5-c3e5eca55fc5.png)

`experimental.rendering.software = true`
![WindowsTerminal_7QoXHEWw8Z](https://user-images.githubusercontent.com/17430026/81739431-06ed8c00-94a4-11ea-907a-de7aed370f5f.png)

**Comment by DHowett-MSFT** [comment] 2020-05-12 21:51
That's really helpful. Thank you!

**Comment by fahadabdulaziz** [comment] 2020-05-12 22:15
@DHowett-MSFT Thank you for your help, 
The problem is fixed for, after altering the card options it needs for restart, or disable and re-enable the intel card from device manager.

Looks like I don't need to wear glasses anymore 😁

**Comment by LuKePicci** [comment] 2020-05-27 13:31
Same here, Venue 11 Pro, Intel HD 4200 i5-4300Y, two screens, both 1080p, the internal one is an HiDPI display (125% scaling), the external one is not HiDPI (100% scaling). The problem only affects the external monitor. If I move the Terminal window to the HiDPI monitor it renders just fine.

That's exactly the same issue affecting Chromium/Edge/Electron-based garbage.
It worked just fine in 0.11.1121.0, so if there was gpu acceleration in there that was worked fine.

I can't live with GPU acceleration disabled as my ULP i5-Y cpu is too short in TDP to handle cpu-based rendering.

Will try to disable differential rendering only to see if it helps.

**Comment by LuKePicci** [comment] 2020-05-27 14:06
Test results.
`experimental.rendering.forceFullRepaint: true` fixed it.
`experimental.rendering.software: true` made it over 9000 times slower

I would really consider to ship with forceFullRepaint enabled until you get a better idea of what is causing this issue. Better to ship a sub-optimal rendered which can be faster enabling that experimental partial redraw feature than shipping something which simply doesn't work for an unspecified class of users.

**Comment by zadjii-msft** [comment] 2020-05-27 14:34
I mean we know exactly what's causing this, and that it's out of our control:

> "Conservative Morphological Anti-Aliasing" in Intel's graphics driver?
> There are some old bugs about this: [bugzilla.mozilla.org/show_bug.cgi?id=1145987](https://bugzilla.mozilla.org/show_bug.cgi?id=1145987)


There's not much we can do ourselves about a 5 years old drivers bug, except provide an escape hatch for users affected by it to work around it.

Differential drawing gets us such a [dramatic performance increase](https://github.com/microsoft/terminal/issues/1064#issuecomment-618024330) that we're not about to revert that for the majority of our userbase without evidence that this "melting text" bug affects the _majority_ of users.

**Comment by LuKePicci** [comment] 2020-05-27 14:41
Sure, but how you would explain my main screen not being affected by this? Are you 100% sure it does not relate to HiDPI, external HDMI or something else? Are you 100% sure it does only affect 5-years old hardware? If the answer is yes, then I perfectly agree on your point.

**Comment by mic345** [comment] 2020-07-10 19:07
Hi guys,

I am too suffering from smudge fonts and I tend to believe LuKePicci is right. On any of the external monitors, which are not HiDPI the fonts look smudge. On the laptop monitor the fonts looks crystal sharp.

Hardware:
```
$ cat /proc/cpuinfo | grep CPU
model name      : Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz
model name      : Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz
model name      : Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz
model name      : Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz
model name      : Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz
model name      : Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz
model name      : Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz
model name      : Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz

> wmic path win32_VideoController get name
Name
Intel(R) UHD Graphics 620
```

I tried everything on this thread including the below but non fixed the issue.
- `experimental.rendering.forceFullRepaint: true`
- `experimental.rendering.software: true`
- various fonts and sizes (see screenshot)

I also wanted to try to disable scaling on high DPI on the app settings, but couldn't find how to do it for an app from the store. If you know how can this be done, I would gladly test and report the results.

https://www.thewindowsclub.com/fonts-appear-blurred-windows-8/

Please advise.

Thanks for the help :-)
Mic.

![Desktop_screenshot (2)](https://user-images.githubusercontent.com/36601023/87189692-b2ee0080-c2b6-11ea-82e4-136feeb77e68.png)

**Comment by fahadabdulaziz** [comment] 2020-07-10 19:50
For reference I found out there is a relation between the blurry problem and AnyDesk app after using it for a remote session, a similar problem happens with Visual Studio, the solution I found is killing DWM.exe process (which is a windows process responsible managing app windows).

**Comment by mic345** [comment] 2020-07-23 18:38
Guys, is there any official way to stop smoothing fonts on this app? I believe this is the issue.

Thanks!
Mic.

**Comment by DHowett** [comment] 2020-07-23 18:42
@mic345 there was an entire discussion above the comment field on this issue that contains information on disabling font smoothing in your display adapter's configuration _or_ in the terminal settings. It's even on [our troubleshooting page](https://docs.microsoft.com/en-us/windows/terminal/troubleshooting).

**Comment by mic345** [comment] 2020-07-23 19:00
@DHowett, thanks for the quick reply!!

If you mean `experimental.rendering.forceFullRepaint: true` or `experimental.rendering.software: true` -- both are not helping in my case. See my [comment above](https://github.com/microsoft/terminal/issues/5759#issuecomment-656841640). If you have other ideas I can try, I'd be very grateful if you share them.

Take care!
Mic.

**Comment by DHowett** [comment] 2020-07-23 21:13
So, it looks like your complaint is actually about subpixel rendering? Your screenshot looks pretty much like any other windows application that's primarily text has over the past 15 years. :smile:

Disable that by setting `"antialiasingMode": "aliased"` in your settings file. You'll get your nice sharp pixels.

**Comment by mic345** [comment] 2020-07-23 21:24
> So, it looks like your complaint is actually about subpixel rendering? Your screenshot looks pretty much like any other windows application that's primarily text has over the past 15 years. 😄
> 
> Disable that by setting `"antialiasingMode": "aliased"` per-profile in your settings file. You'll get your nice sharp pixels.

THANK YOU!!! 🙏🙏🙏

**Comment by mic345** [comment] 2020-07-23 21:52
BTW, an idea -- for people who disable the smooth edge fonts through Microsoft OS options (or in general on the OS level), maybe it makes sense to set the default antialiasingMode to aliased? In a way it's like obeying the dark mode user setting on the OS level.

Anyway, it's just an idea, thanks a lot for the help!
Mic.

**Comment by DHowett** [comment] 2020-07-24 00:20
I'm actually somewhat surprised that we _don't_ automatically follow that setting. Thanks for noticing!

**Comment by thedailycommute** [comment] 2020-09-09 08:40
I know this is an old thread, but I have had the same blurry text problem since the earliest releases.

_However_, the reply (https://github.com/microsoft/terminal/issues/5759#issuecomment-625357069) by reli-msft about "Conservative Morphological Anti-Aliasing" finally allowed me to fix the problem.

My computer uses an Intel HD Graphics 4600 card - what may not be obvious to some is that the above-mentioned anti-aliasing option is located in the settings for **3D**. In my case the option was set to "Override Application Settings". The other choices are "Enhance Application Settings" and "Turn Off", and the latter _finally_ fixed the problem! I can now use Windows Terminal in all its glory :-)

It seems strange (to me, anyway) that a 3D rendering option should affect a text terminal (especially since Windows Terminal is the _only_ app that seems to be affected, and I've been using the same machine for coding for over 4 years), but at least it works now.

For anyone else still battling with fuzzy fonts, check the 3D rendering options of your graphics cards. As counterintuitive as it seems, there's a good chance a 3D option is affecting text rendering.

**Comment by dcharlespyle** [comment] 2021-06-13 20:57
> BTW I have two card on my machine nVidia & Intel.
> I tried disabling all intel driver options but nothing changed, I didn't find "Image Sharpening" in the settings.

On my system, it's here:

![image](https://user-images.githubusercontent.com/5110398/121821621-511ce000-cc57-11eb-8b96-5ef299784b99.png)

Another setting to watch out for is this one:
![image](https://user-images.githubusercontent.com/5110398/121821660-917c5e00-cc57-11eb-90c9-fb63a1669606.png)

**Comment by yiyuechen** [comment] 2022-06-07 07:39
Hi everyone. I'm using an intel card and an Nvidia card.

I disabled the CMAA feature in the 3D tab in the intel card and the font is clear now.

(The CMAA can be set to disabled, overlap application settings, and enhance application settings.)
![image](https://user-images.githubusercontent.com/17523520/172323463-71f59e92-aa58-49d8-8274-d28629a3c231.png)
