### ISSUE TITLE
NativeScript QR Code not fully rendered

### ISSUE THREAD

**Issue by JCKodel** [microsoft/terminal#4431] opened 2020-01-31 19:32 UTC
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18362.592]
Windows Terminal version (if applicable): Windows Terminal (Preview) [Version 0.8.10261.0]

Any other software?

NodeJS, NPM and NativeScript.
```

# Steps to reproduce

1) Install NativeScript, following their quick setup (it requires node and npm): https://docs.nativescript.org/start/quick-setup (basically, `npm install -g nativescript`, just needing NodeJS and npm, does NOT need Android SDK or any of the other dependencies, AFAIK)

2) Create some project with `tns create`

3) In the result folder, type `tns preview`.

# Expected behavior

The text should be rendered 100% equal on both consoles (not missing entire rows of text).

# Actual behavior

Old Windows console:
![image](https://user-images.githubusercontent.com/379339/73568134-8d76e400-4446-11ea-8d03-afa198f54992.png)

(the NativeScript playground app requires the reading of this qr-code to preview the app on the phone).

New Windows Terminal:
![image](https://user-images.githubusercontent.com/379339/73568189-af706680-4446-11ea-9b5f-4093f153517e.png)

(notice that the last row are missing from the QR-Code, so the preview app won't recognize the QR-Code).

The only difference between those screenshots are the terminal app (so it is NOT a NativeScript bug or something like that)

**Comment by DHowett-MSFT** [comment] 2020-02-06 18:33
Thanks for the report! I think that, at the end of the day, this is a /dupe of #2089. The name probably doesn't seem correct, but it refers to how we determine the "right" side of the screen.
Since the QR code is made of _colored space characters_, and we think spaces are not meaningful sometimes, `*boom*`

**Closed by DHowett-MSFT** 2020-02-06 18:33 UTC
Labels: Needs-Tag-Fix, Needs-Triage

**Comment by xXGoziXx** [comment] 2020-06-28 13:13
I had the same problem and I discovered it was due to the fact that the font I was using was not a monospaced font(equally sized characters)
