### ISSUE TITLE
Add Clear the previous output shortcut action

### ISSUE THREAD

**Issue by 3axap4eHko** [microsoft/terminal#5954] opened 2020-05-17 20:09 UTC
# Clear the previous output shortcut action

Different terminals use different commands to clear output: `cls`, `Clear-Host`, `clear` and etc.
It would be great to clear the previous output by the same hotkey at any terminal.
Currently `Ctrl+K` does not work properly

**Comment by DHowett** [comment] 2020-05-17 22:36
Thanks for the request! This is a /dupe of #1882, which requires #1193

**Closed by DHowett** 2020-05-17 22:36 UTC
Labels: Issue-Feature, Needs-Tag-Fix, Needs-Triage
