### ISSUE TITLE
Experimental tab-in-window-bar feature breaks window styling

### ISSUE THREAD

**Issue by haydennyyy** [microsoft/Terminal#594] opened 2019-05-08 19:12 UTC
* Your Windows build number:  (Type `ver` at a Windows Command Prompt) `Microsoft Windows [Version 10.0.18890.1000]`

* What you're doing and what's happening: (Copy & paste specific commands and their output, or include screen shots) 
![image](https://user-images.githubusercontent.com/22327045/57401393-7663d800-71cd-11e9-9338-d7397e4c4088.png)

* What's wrong / what should be happening instead: The tabs (albeit with the experimental feature enabled) causes the border to be completely visible, and the dragging area between the tabs and the buttons isn't working.

**Comment by zadjii-msft** [comment] 2019-05-08 19:26
This is effectively a dupe of #564.

Since we can't use the tab row to drag the window, we didn't make it take the entire width of the titlebar, because that'd not only mean the window couldn't be dragged, but the min/max/close buttons wouldn't work either.

Styling of the tab row is something we hope to actively improve in the near future.

**Closed** 2019-05-08 19:26 UTC
Labels: Resolution-Duplicate
