### ISSUE TITLE
1.13.10336.0 breaks Far Manager's output

### ISSUE THREAD

**Issue by vblazhkun** [microsoft/terminal#12399] opened 2022-02-06 16:34 UTC
### Windows Terminal version

1.13.10336.0

### Windows build number

19044.1466

### Other Software

Far Manager 3.0.5800.0 x64

### Steps to reproduce

Just run the application inside the terminal:

`PS C:\Program Files\Far Manager> .\Far.exe`

![Screenshot 2022-02-06 192509](https://user-images.githubusercontent.com/7956686/152691037-d81cc725-32f8-46d2-bb3f-0e4ad70de073.png)

### Expected Behavior

![Screenshot 2022-02-06 193122](https://user-images.githubusercontent.com/7956686/152690930-a6d8abe2-bdf8-4ddd-877a-bfdf920f2d08.png)

### Actual Behavior

Corrupted output on the terminal.

**Comment by 237dmitry** [comment] 2022-02-06 17:25
It's good that the mouse and custom hotkeys have started working... Almost a/an year ago I already asked [#9921](https://github.com/microsoft/terminal/issues/9921#issue-865188104). This is the only reason I use FAR in the standard Windows console. The same story with micro editor.

**Comment by DHowett** [comment] 2022-02-06 17:57
It looks like somebody disabled `ENABLE_VIRTUAL_TERMINAL_PROCESSING`. What else is running in that terminal window?

We haven't changed the code here in quite some time, as it presents a significant compatibility risk.

/cc @alabuzhev for FAR

**Comment by alabuzhev** [comment] 2022-02-06 18:34
@DHowett it's a duplicate of #11780.
@vblazhkun either update Far or turn off virtual terminal in interface settings.

**Comment by vblazhkun** [comment] 2022-02-06 19:16
> It looks like somebody disabled `ENABLE_VIRTUAL_TERMINAL_PROCESSING`. What else is running in that terminal window?
> 
> We haven't changed the code here in quite some time, as it presents a significant compatibility risk.
> 
> /cc @alabuzhev for FAR

I am not sure what has happened as the given application was working fine just before a recent update of the Windows Terminal. The second screenshot attached is from the stable version of the  Windows Terminal [1.11.3471.0] with the exact same Far Manager and its settings.

**Comment by vblazhkun** [comment] 2022-02-06 19:23
> @DHowett it's a duplicate of #11780. @vblazhkun either update Far or turn off virtual terminal in interface settings.

Turning off the "Use Virtual Terminal for rendering" helped, but I do not get why was it working fine with the given knob ON just before the recent update of the Windows Terminal?

**Comment by vblazhkun** [comment] 2022-02-06 19:28
Is the issue related to #11690 committed to 1.13.10336.0?

**Comment by 237dmitry** [comment] 2022-02-06 21:48
> Turning off the "Use Virtual Terminal for rendering" helped

It doesn't help in any way. FAR has completely changed the colors, and in the editor, as it was -- if you paste text with spaces, it moves out.

Rendering Turned On
![far1](https://user-images.githubusercontent.com/78153320/152702649-eb06229c-6902-4410-b880-781f98fcb283.png)

Turned Off
![far2](https://user-images.githubusercontent.com/78153320/152702584-b945c5f5-5836-43e1-ad3a-00cf27d394d6.png)

Copy-Paste in editor. The same copy-paste in micro editor.
![far3](https://user-images.githubusercontent.com/78153320/152702587-2e7f4579-88ae-4af0-a51b-5df19d8679dc.png)

**Comment by zadjii-msft** [comment] 2022-02-07 11:59
Yea, this is a /dup of #11780. Far was relying on some ill-defined terminal behavior. That behavior we clarified in 1.13, at the cost of breaking older FAR versions. They've since patched on their side, so people up-to-date on both should have a working experience again. Sorry for the confusion!

**Closed by zadjii-msft** 2022-02-07 11:59 UTC
Labels: Needs-Triage, Needs-Tag-Fix
