### ISSUE TITLE
Text rendering issues in 1.1

### ISSUE THREAD

**Issue by wackoisgod** [microsoft/terminal#6603] opened 2020-06-20 01:11 UTC
So I have updated to the latest 1.1 version of the terminal, and I am now seeing some weird text rendering issues when running a console application. Worked fine in 1.0. 
V1.1:
![image](https://user-images.githubusercontent.com/92770/85187919-46a05400-b258-11ea-988d-0fc18e085179.png)

V1.0
![image](https://user-images.githubusercontent.com/92770/85187959-7baca680-b258-11ea-924a-563ff26b1933.png)

**Comment by greg904** [comment] 2020-06-20 19:52
Might be #6488.

**Comment by latipun7** [comment] 2020-06-20 23:02
Some same fonts rendered differently in my case.

V1.0 (good)
![good](https://i.imgur.com/aa6K3iC.png)

V1.1 (bad)
![bad](https://i.imgur.com/V8k9aNZ.png)

**Comment by hongooi73** [comment] 2020-06-21 04:43
@latipun7 I'm not seeing the difference...?

**Comment by latipun7** [comment] 2020-06-21 05:32
@hongooi73 see at the end, I thought it's pretty noticeable. There's gap in v1.1, Although it's same font and same ansi code, but v1.1 has some gaps in the end of line
![](https://i.imgur.com/Tlzh56f.png)

**Comment by hongooi73** [comment] 2020-06-21 05:43
Oh right, I thought it was meant to be a blown-up example. I see it now.

**Comment by DHowett** [comment] 2020-06-21 06:01
Thanks for the reports, everyone. I'm gonna close this as a /dupe of #6488.

**Closed by DHowett** 2020-06-21 06:01 UTC
Labels: Needs-Tag-Fix, Needs-Triage
