### ISSUE TITLE
Vim cursor can't be changed

### ISSUE THREAD

**Issue by eduardoarandah** [microsoft/terminal#4335] opened 2020-01-22 18:15 UTC
# Environment

```
Windows build number: 10.0.19041.21
Windows Terminal version : 0.8.10091.0
```

# Steps to reproduce

- Open vim
- Set options:

```
set background=dark
colorscheme desert
highlight Cursor guifg=white guibg=black
```

# Expected behavior

In old terminal you know when you're in normal mode

![image](https://user-images.githubusercontent.com/4065733/72921318-aed22480-3d10-11ea-85dd-8ab570b2f7e0.png)

# Actual behavior

Cursor can't be changed, so it's hard to work

![image](https://user-images.githubusercontent.com/4065733/72921414-d2956a80-3d10-11ea-8e4f-aaf69558fad9.png)

**Comment by DHowett-MSFT** [comment] 2020-01-22 19:21
It appears that Vim doesn't do this unless it's been explicitly configured to do so: [vimwiki/Configuring the cursor](https://vim.fandom.com/wiki/Configuring_the_cursor). When I set the options for changing the cursor shape, it works properly.

![image](https://user-images.githubusercontent.com/14316954/72926396-3a47b780-3d09-11ea-9926-b3029be54160.png)

![image](https://user-images.githubusercontent.com/14316954/72926420-42075c00-3d09-11ea-97d1-08be8afdffcc.png)

Can you confirm the part of your vim config that exchanges the cursor options?

**Comment by DHowett-MSFT** [comment] 2020-01-22 19:22
For what it's worth, I can't reproduce this issue even outside of Windows Terminal.

**Comment by eduardoarandah** [comment] 2020-01-22 19:44
- I removed all my .vimrc confguration 
- copied [the example config](https://vim.fandom.com/wiki/Configuring_the_cursor)
- closed vim and opened again in bash and powershell


# Bash

![image](https://user-images.githubusercontent.com/4065733/72927297-8dc30100-3d1b-11ea-9fc5-3773494e923e.png)

# Powershell

![image](https://user-images.githubusercontent.com/4065733/72927799-79333880-3d1c-11ea-8622-4bd3630be1a7.png)

# Vim information
In case something's wrong with vim:

:version output
![image](https://user-images.githubusercontent.com/4065733/72927992-cd3e1d00-3d1c-11ea-94f5-01de8497e717.png)

# In the old terminal
in the old terminal `C:\Windows\System32\wsl.exe` cursor is like this:

![image](https://user-images.githubusercontent.com/4065733/72928257-42115700-3d1d-11ea-8780-46116d6a148a.png)


What other info might be useful?

**Comment by DHowett-MSFT** [comment] 2020-01-22 19:48
Ah, it looks like the documentation here is confusing. The `guicursor` settings are for _GUI vim_ (gvim, xvim, mvim, etc.). You'll want the ones at the bottom that mention `xterm` and `rxvt`, with the `t_SI` and `t_EI` control sequences.

There may be an issue in the regular expression. My configuration looks like this:

```viml
if &term =~ '^xterm'
  " solid underscore
  let &t_SI .= "\<Esc>[4 q"
  " solid block
  let &t_EI .= "\<Esc>[2 q"
  " 1 or 0 -> blinking block
  " 3 -> blinking underscore
  " Recent versions of xterm (282 or above) also support
  " 5 -> blinking vertical bar
  " 6 -> solid vertical bar
endif
```

**Comment by DHowett-MSFT** [comment] 2020-01-22 19:50
And lastly, Windows vim (the one you're using from powershell) uses a different system to set the cursor. I think there's an open duplicate bug for that one not working 100% with Terminal. :smile:

**Comment by eduardoarandah** [comment] 2020-01-22 20:15
It worked, thanks!

I'm leaving this code for the lost souls that might search it

# How to change cursor in vim in windows terminal 

Works for vim in wsl (not powershell)

In this example, normal mode is a block, insert mode is a vertical bar

```
  " Cursor in terminal
  " https://vim.fandom.com/wiki/Configuring_the_cursor
  " 1 or 0 -> blinking block
  " 2 solid block
  " 3 -> blinking underscore
  " 4 solid underscore
  " Recent versions of xterm (282 or above) also support
  " 5 -> blinking vertical bar
  " 6 -> solid vertical bar
    
  if &term =~ '^xterm'
    " normal mode
    let &t_EI .= "\<Esc>[0 q"
    " insert mode
    let &t_SI .= "\<Esc>[6 q"
  endif

```

**Comment by DHowett-MSFT** [comment] 2020-01-22 21:48
Thanks for following up! I'm going to close this one since it's answered.

**Closed by DHowett-MSFT** 2020-01-22 21:48 UTC
Labels: Needs-Attention, Needs-Tag-Fix, Needs-Triage

**Comment by lllama** [comment] 2020-02-26 09:53
So the config posted by @eduardoarandah works in vim but appears to have the side effect of leaving the cursor in whatever state it was when Vim exited (most likely a block in normal mode), so the terminal ends up with a block cursor rather than the default.

(This is in ubuntu running in WSL)

**Comment by heaths** [comment] 2020-03-09 19:15
Confirmed what @lllama is seeing: when I exit vim from normal mode, the Terminal cursor is not a block cursor.

This works fine in conhost consoles (cmd, powershell, pwsh).

**Comment by iovuio** [comment] 2020-03-15 18:22
Please reopen.

I have the following cursors:
- in the console: horizontal bar (underscore)
- in vim normal mode: block
- in vim insert mode: vertical bar

**Problem 1**
1. Start a new wsl window -> cursor is underscore
2. start vim -> vim starts in normal mode.

Expected:  Cursor should be block
Actual: Cursor is underscore.

**Problem 2** (as reported by @lllama and @heaths 
1. start new terminal, start vim
2. exit vim (:q) -> we're back in the console.

Expected result: cursor should be vertical bar
Actual result: cursor is block.

**Comment by dennisjlee** [comment] 2020-06-22 16:13
Here's a workaround for resetting the cursor to a vertical bar after exiting vim. 

Add this to your .bashrc so that it will set the cursor to a blinking bar every time it renders a prompt. (Other styles are listed in [this StackOverflow answer](https://stackoverflow.com/a/17100535))

`export PROMPT_COMMAND='echo -e -n "\x1b[\x35 q"'`

**Comment by chadmoore** [comment] 2020-08-04 18:03
Closing this as solved is kind of frustrating, as the original issue was reported for Powershell sessions, while the "solution is" basically, "don't use powershell, use linux", which isn't reaaally the answer I'd hope for. Ideally running vim in a powershell session would be comfortable without having to use WSL.

**Comment by heaths** [comment] 2020-08-05 17:51
@chadmoore while I agree with you, just wanted to add that you can do something similar in PowerShell if you overwrite your `prompt` function, but then that means taking responsibility for what it outputs.

The default is:

```powershell
"PS $($executionContext.SessionState.Path.CurrentLocation)$('>' * ($nestedPromptLevel + 1)) "
```

Based on <https://docs.microsoft.com/windows/console/console-virtual-terminal-sequences#simple-cursor-positioning> and using \`e (PowerShell Core; see [about_Special_Characters](https://docs.microsoft.com/powershell/module/microsoft.powershell.core/about/about_special_characters?view=powershell-7)), something like this should work in your $profile:

```powershell
function prompt {
"PS $($executionContext.SessionState.Path.CurrentLocation)$('>' * ($nestedPromptLevel + 1)) `e[?12h"
}
```

I say *should*, but in testing the cursor didn't blink in Windows Terminal. Other cursor sequences worked, so this appears to be a bug in Windows Terminal.

**Comment by zadjii-msft** [comment] 2020-08-05 19:19
@chadmoore for the record, this thread was specifically tracking "setting the cursor in the _WSL_ vim", _not_ `vim.exe`.  As @DHowett-MSFT mentioned above:

> And lastly, Windows vim (the one you're using from powershell) uses a different system to set the cursor. I think there's an open duplicate bug for that one not working 100% with Terminal. 😄

I'm actually _not_ sure that there's a duplicate for that issue, since I couldn't find it from some trivial searching. That should probably be moved out to it's own issue (which will likely end up as a bug on `vim.exe`)

**Comment by robertsk50** [comment] 2020-08-08 01:07
I had the same problem @lllama and @heaths had (cursor stuck as block in terminal). The code below from [stackoverflow](https://stackoverflow.com/a/43398487/1265657) allowed me to recover the cursor without modifying my .bashrc as @dennisjlee suggested.

`autocmd VimLeave * silent !echo -ne "\e[6 q"`

**Comment by gao-lex** [comment] 2020-10-10 06:51
so this is the best solution:
```bash
if &term =~ '^xterm'
  " enter vim
  autocmd VimEnter * silent !echo -ne "\e[3 q"
   " oherwise
  let &t_EI .= "\<Esc>[3 q"
  " insert mode
  let &t_SI .= "\<Esc>[5 q"
 " 1 or 0 -> blinking block
  " 2 -> solid block
  " 3 -> blinking underscore
  " 4 -> solid underscore
  " Recent versions of xterm (282 or above) also support
  " 5 -> blinking vertical bar
  " 6 -> solid vertical bar
  " leave vim
  autocmd VimLeave * silent !echo -ne "\e[5 q"
endif
```

**Comment by nickjj** [comment] 2020-10-18 13:10
To follow up on this is there any way to have Vim use the MS Terminal vintage thick underline instead of the thin underline?

In practice I've found the block cursor in Vim with the MS Terminal to be not usable because The MS Terminal doesn't invert the color of the character under the block cursor so you often get into situations where you can't read the character under the block.

For now I've been using the vintage thick underline cursor but I haven't been able to find a code to set that. The thin underline is a bit too hard to see, especially when recording video tutorials.

**Comment by ngmy** [comment] 2020-10-23 11:38
I encountered the problem that an escape sequence is output at starting Vim.
I also encountered the problem that the terminal cursor even changed after suspending Vim with Ctrl+Z.
I solved these problems by adding the following to previous solutions.

```vim
" HACK: Work around the problem that an escape sequence is output at startup.
"       https://vi.stackexchange.com/questions/19748
autocmd VimEnter * normal :startinsert
" suspend and resume vim
nnoremap <silent> <C-z> :execute 'silent !echo -en "\e[5 q"'<CR>:suspend<Bar>:execute 'silent !echo -en "\e[0 q"'<CR>
```

**Comment by zeroxia** [comment] 2020-12-07 02:54
The solution pasted by @gao-lex does is not work for me, is it only for WSL?

I'm using PowerShell and cmd.exe:
Windows version: Windows 10 Version 2004 (OS Build 19041.630)
Windows Terminal version: Version: 1.4.3243.0
Vim is the official one for windows: 8.2, and I'd like to run vim inside the console, by typing `vim.bat FILE`

In PowerShell or cmd.exe, normal mode cursor is block, insert mode cursor is underscore.
But even when I paste the content to my `.vimrc`, the cursor inside Windows Terminal is always a vertical bar. This is very confusing in Vim normal mode.

I can be sure that `.vimrc` is correctly located, and sourced by Vim when it launches.

**Comment by coldspark29** [comment] 2020-12-10 23:05
For me also none of the solutions work. This is the last issue I have with Vim on Windows (and well maybe that pasting from clipboard is not in line).

**Comment by lk-hang** [comment] 2021-01-01 22:34
I should note that for whatever reason using option 0 does not give blinking block in wsl and still outputs a vertical bar. So replace `let &t_EI .= "\e[0 q"` by `let &t_EI .= "\e[1 q" ` and similarly when you exit vim. Here is the snippet that works for me.

```
if &term =~ '^xterm'
	" Cursor in terminal:
	" Link: https://vim.fandom.com/wiki/Configuring_the_cursor
	" 0 -> blinking block not working in wsl
	" 1 -> blinking block
	" 2 -> solid block
	" 3 -> blinking underscore
	" 4 -> solid underscore
	" Recent versions of xterm (282 or above) also support
	" 5 -> blinking vertical bar
	" 6 -> solid vertical bar

	" normal mode
	let &t_EI .= "\e[1 q" 	
	" insert mode
	let &t_SI .= "\e[5 q"	

	augroup windows_term
		autocmd!
		autocmd VimEnter * silent !echo -ne "\e[1 q" 
		autocmd VimLeave * silent !echo -ne "\e[5 q" 
	augroup END
endif
```

**Comment by KalleOlaviNiemitalo** [comment] 2021-01-02 03:05
> I should note that for whatever reason using option 0 does not give blinking block in wsl and still outputs a vertical bar.

There was a long discussion about cursor style 0 vs. 1 vs. empty, in <https://github.com/microsoft/terminal/issues/1604>.

**Comment by coldspark29** [comment] 2021-01-02 12:04
> I should note that for whatever reason using option 0 does not give blinking block in wsl and still outputs a vertical bar. So replace `let &t_EI .= "\e[0 q"` by `let &t_EI .= "\e[1 q" ` and similarly when you exit vim. Here is the snippet that works for me.
> 
> ```
> if &term =~ '^xterm'
> 	" Cursor in terminal:
> 	" Link: https://vim.fandom.com/wiki/Configuring_the_cursor
> 	" 0 -> blinking block not working in wsl
> 	" 1 -> blinking block
> 	" 2 -> solid block
> 	" 3 -> blinking underscore
> 	" 4 -> solid underscore
> 	" Recent versions of xterm (282 or above) also support
> 	" 5 -> blinking vertical bar
> 	" 6 -> solid vertical bar
> 
> 	" normal mode
> 	let &t_EI .= "\e[1 q" 	
> 	" insert mode
> 	let &t_SI .= "\e[5 q"	
> 
> 	augroup windows_term
> 		autocmd!
> 		autocmd VimEnter * silent !echo -ne "\e[1 q" 
> 		autocmd VimLeave * silent !echo -ne "\e[5 q" 
> 	augroup END
> endif
> ```

Doen't work for me :(

**Comment by Apreche** [comment] 2021-01-05 21:17
Sometimes I use wsl with VcXsrv, and that means everything works fine. Sometimes I use wsl inside of Windows Terminal. It's the same vimrc either way. I can't use `if &term =~ '^xterm'` to enable the cursor fix because it's always true. That will mess up my cursor that works perfectly when using a Linux terminal emulator under VcXsrv. I need some way to detect Windows Terminal specifically. Like maybe is there a way to put an environment variable like `WINDOWS_TERMINAL=true` or something like that? 

My vim has a light color scheme, and it fails to change the color or shape of the Windows terminal cursor. So the cursor becomes literally 100% invisible when using vim. The situation is pretty dire.

**Comment by CRTejaswi** [comment] 2021-01-18 21:31
> 
> # Environment
> 
> ```
> Windows build number: 10.0.19041.21
> Windows Terminal version : 0.8.10091.0
> ```
> 
> # Steps to reproduce
> 
>     * Open vim
> 
>     * Set options:
> 
> 
> ```
> set background=dark
> colorscheme desert
> highlight Cursor guifg=white guibg=black
> ```
> 
> # Expected behavior
> 
> In old terminal you know when you're in normal mode
> 
> ![image](https://user-images.githubusercontent.com/4065733/72921318-aed22480-3d10-11ea-85dd-8ab570b2f7e0.png)
> # Actual behavior
> 
> Cursor can't be changed, so it's hard to work
> 
> ![image](https://user-images.githubusercontent.com/4065733/72921414-d2956a80-3d10-11ea-8e4f-aaf69558fad9.png)

I had the same issue. The easiest workaround is to set `cursorShape` under required profile inside `settings.json`. See [this](https://docs.microsoft.com/en-us/windows/terminal/customize-settings/profile-settings#cursor-shape).

**Comment by devhashtag** [comment] 2021-02-09 21:40
> The solution pasted by @gao-lex does not work for me, is it only for WSL?
> 
> I'm using PowerShell and cmd.exe:
> Windows version: Windows 10 Version 2004 (OS Build 19041.630)
> Windows Terminal version: Version: 1.4.3243.0
> Vim is the official one for windows: 8.2, and I'd like to run vim inside the console, by typing `vim.bat FILE`
> 
> In PowerShell or cmd.exe, normal mode cursor is block, insert mode cursor is underscore.
> But even when I paste the content to my `.vimrc`, the cursor inside Windows Terminal is always a vertical bar. This is very confusing in Vim normal mode.
> 
> I can be sure that `.vimrc` is correctly located, and sourced by Vim when it launches.

This worked for me, I'm using PowerShell:
https://github.com/microsoft/terminal/issues/68#issuecomment-418438517

**Comment by younger-1** [comment] 2022-02-15 02:50
> > The solution pasted by @gao-lex does not work for me, is it only for WSL?
> > I'm using PowerShell and cmd.exe:
> > Windows version: Windows 10 Version 2004 (OS Build 19041.630)
> > Windows Terminal version: Version: 1.4.3243.0
> > Vim is the official one for windows: 8.2, and I'd like to run vim inside the console, by typing `vim.bat FILE`
> > In PowerShell or cmd.exe, normal mode cursor is block, insert mode cursor is underscore.
> > But even when I paste the content to my `.vimrc`, the cursor inside Windows Terminal is always a vertical bar. This is very confusing in Vim normal mode.
> > I can be sure that `.vimrc` is correctly located, and sourced by Vim when it launches.
> 
> This worked for me, I'm using PowerShell: [#68 (comment)](https://github.com/microsoft/terminal/issues/68#issuecomment-418438517)

It works, but vim does not attempt to restore cursor shape on exit.
neovim could restore cursor shape on exit by `autocmd VimLeave * set guicursor=a:ver25`.
How about vim?

**Comment by ABD-01** [comment] 2022-06-17 13:58
> so this is the best solution:
> 
> ```shell
> if &term =~ '^xterm'
>   " enter vim
>   autocmd VimEnter * silent !echo -ne "\e[3 q"
>   " oherwise
>   let &t_EI .= "\<Esc>[3 q"
>   " insert mode
>   let &t_SI .= "\<Esc>[5 q"
>   " 1 or 0 -> blinking block
>   " 2 -> solid block
>   " 3 -> blinking underscore
>   " 4 -> solid underscore
>   " Recent versions of xterm (282 or above) also support
>   " 5 -> blinking vertical bar
>   " 6 -> solid vertical bar
>   " leave vim
>   autocmd VimLeave * silent !echo -ne "\e[5 q"
> endif
> ```

Thanks a Lot for this One 🫂

**Comment by ABD-01** [comment] 2022-06-17 13:59
> so this is the best solution:
> 
> ```shell
> if &term =~ '^xterm'
>   " enter vim
>   autocmd VimEnter * silent !echo -ne "\e[3 q"
>   " oherwise
>   let &t_EI .= "\<Esc>[3 q"
>   " insert mode
>   let &t_SI .= "\<Esc>[5 q"
>   " 1 or 0 -> blinking block
>   " 2 -> solid block
>   " 3 -> blinking underscore
>   " 4 -> solid underscore
>   " Recent versions of xterm (282 or above) also support
>   " 5 -> blinking vertical bar
>   " 6 -> solid vertical bar
>   " leave vim
>   autocmd VimLeave * silent !echo -ne "\e[5 q"
> endif
> ```

@gao-lex  Thanks a Lot for this One 🫂

**Comment by eggbean** [comment] 2022-09-06 14:22
> And lastly, Windows vim (the one you're using from powershell) uses a different system to set the cursor. I think there's an open duplicate bug for that one not working 100% with Terminal. 😄

I've been looking for the setting for Vim for Windows (cmd.exe and powershell version) but cannot find them. Could somebody tell me?

I have this set for Vim on Linux/WSL, and it works, but not on Windows Terminal cmd.exe or powershell.

```
" Change cursor depending on mode, like in nvim
let &t_SI = "\<Esc>[6 q"
let &t_SR = "\<Esc>[4 q"
let &t_EI = "\<Esc>[2 q"
```

**Comment by iovuio** [comment] 2022-09-07 07:01
> I've been looking for the setting for Vim for Windows (cmd.exe and powershell version) but cannot find them. Could somebody tell me?

The use case permutations are very vast and most posters report on one instance only.
Everybody posting solution is driven by good intention. However, please do bother to state what environment the solution you offer pertains to to save a brother an hour.

Solution
---------
The following solution pertains to:
- Windows OS
- vim, not neovim
- text interface, not gvim
- windows process (vim.exe)
- vim started with powershell 7.2.6, not cmd. Powershell standalone or through Windows Terminal (known problem for the latter, mentioned below)
- assuming powershell cursor is vertical bar blinking
- assumming the cursors you want in vim are normal:block, insert:vertical bar, replace:horizontal bar. None blinking
- assumming Vim 9.0.0392 install, vim.exe available under C:\Program Files\Vim\vim90\vim.exe
- assumming your username is Elmo and your home directory is C:\Users\Elmo

Create a file called .vimrc in your home directory C:\Users\Elmo with following content
```
let &t_SI = "\<Esc>[6 q"
let &t_SR = "\<Esc>[4 q"
let &t_EI = "\<Esc>[2 q"
```
6:vert-bar,4:underscore,2:block are the non-blinking cursors for the three vim modes.

This will make vim use the mode dependent cursors.
Problem: upon exiting vim, the cursor you end up with in the Powershell prompt is block non-blinking. If that's not what you want, edit your profile
> notepad $profile
or edit C:\Users\Elmo\Documents\PowerShell\Microsoft.PowerShell_profile.ps1

Add the following function
```
function vim {
    & "C:\Program Files\Vim\vim90\vim.exe" $args && echo "`e[5 q"
}
```
That echo is a command to tell powershell to set the cursor to 5:blinking-vertical-bar in this case. Save. Exit.

Known Problem
------------------
When starting vim from Powershell through Windows Terminal the initial cursor should be block, non-blinking, however it's the vertical bar blinking (whatever came from the prompt). Once you change modes, the expected vim cursors will be used.
That is not the case if you use the standalone Powershell app.

Already Tried, Don't Bother
------------------
Using the VimLeave event in .vimrc to execute set cursor
```
autocmd VimLeave * :!echo "`e[5 q"
```

Like to mark this useful.

**Comment by eggbean** [comment] 2022-09-08 18:46
@iovuio Thank you for this information, but adding the following to my `.vimrc` doesn't change the behavior of the cursor on vim for Windows.

   let &t_SI = "\<Esc>[6 q"
   let &t_SR = "\<Esc>[4 q"
   let &t_EI = "\<Esc>[2 q"

It does change the cursor on gvim though.

**Comment by eggbean** [comment] 2022-09-08 18:59
@iovuio Thank you for this information, but adding the following to my `.vimrc` doesn't change the behavior of the cursor on Vim for Windows (run from cmd.exe or powershell).

    let &t_SI = "\<Esc>[6 q"
    let &t_SR = "\<Esc>[4 q"
    let &t_EI = "\<Esc>[2 q"

It **does** change the cursor on Vim on Linux/WSL though (I had already had it set).

I just thought that my setup may differ because I use [clink](https://github.com/chrisant996/clink). Maybe this is having an effect? I can't think of any reason why this setting wouldn't work for me if it is the correct one to be used on Vim for Windows when using Windows Terminal.

**Comment by eggbean** [comment] 2022-09-08 19:41
I had a specific setting for Command Prompt in Windows Terminal to use a Bar cursor. With this set the cursor in Vim for Windows was also always a vertical bar. I have now changed that setting to 'Filled Box'. Now while the cursor is a flashing square block in the shell, in Vim for Windows it's the same in Normal Mode and in Insert Mode it has changed to a flashing underscore. Not quite what it is set as (both modes flashing and underscore instead of vertical bar in Insert Mode), but at least there is a difference and this will do, as I don't often use this version of vim anyway.

**Comment by haakuya** [comment] 2024-02-18 03:45
> I had a specific setting for Command Prompt in Windows Terminal to use a Bar cursor. With this set the cursor in Vim for Windows was also always a vertical bar. I have now changed that setting to 'Filled Box'. Now while the cursor is a flashing square block in the shell, in Vim for Windows it's the same in Normal Mode and in Insert Mode it has changed to a flashing underscore. Not quite what it is set as (both modes flashing and underscore instead of vertical bar in Insert Mode), but at least there is a difference between Normal and Insert modes. This will do, as I don't often use this version of vim anyway.

According to the [Vim documentation](https://vimhelp.org/term.txt.html), it should be applied after executing `set termguicolors` or `set t_Co=256`:

```vim
let &t_SI = "\e[6 q"
let &t_SR = "\e[4 q"
let &t_EI = "\e[2 q"
" when entering vim
let &t_ti ..= "\e[2 q"
" when leaving vim
let &t_te ..= "\e[5 q"

```
