### ISSUE TITLE
`:set mouse=a` does not enable scrolling in Powershell + vim

### ISSUE THREAD

**Issue by cbartondock** [microsoft/terminal#13113] opened 2022-05-16 15:28 UTC
### Windows Terminal version

1.12.10983.0

### Windows build number

10.0.22000.0

### Other Software

Output of `vim --version`:
```
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Dec  5 2021 23:04:03)
MS-Windows 64-bit console version
Included patches: 1-3750
Compiled by appveyor@APPVYR-WIN
Huge version without GUI.  Features included (+) or not (-):
+acl                +ex_extra           +multi_lang         -tag_any_white
+arabic             +extra_search       +mzscheme/dyn       +tcl/dyn
+autocmd            -farsi              -netbeans_intg      +termguicolors
+autochdir          +file_in_path       +num64              +terminal
+autoservername     +find_in_path       +packages           -termresponse
-balloon_eval       +float              +path_extra         +textobjects
+balloon_eval_term  +folding            +perl/dyn           +textprop
-browse             -footer             +persistent_undo    -tgetent
++builtin_terms     +gettext/dyn        +popupwin           +timers
+byte_offset        -hangul_input       -postscript         +title
+channel            +iconv/dyn          +printer            -toolbar
+cindent            +insert_expand      +profile            +user_commands
+clientserver       +ipv6               +python/dyn         +vartabs
+clipboard          +job                +python3/dyn        +vertsplit
+cmdline_compl      +jumplist           +quickfix           +virtualedit
+cmdline_hist       +keymap             +reltime            +visual
+cmdline_info       +lambda             +rightleft          +visualextra
+comments           +langmap            +ruby/dyn           +viminfo
+conceal            +libcall            +scrollbind         +vreplace
+cryptv             +linebreak          +signs              +vtp
+cscope             +lispindent         +smartindent        +wildignore
+cursorbind         +listcmds           -sodium             +wildmenu
+cursorshape        +localmap           +sound              +windows
+dialog_con         +lua/dyn            +spell              +writebackup
+diff               +menu               +startuptime        -xfontset
+digraphs           +mksession          +statusline         -xim
-dnd                +modify_fname       -sun_workshop       -xpm_w32
-ebcdic             +mouse              +syntax             -xterm_save
+emacs_tags         -mouseshape         +tag_binary
+eval               +multi_byte_ime/dyn -tag_old_static
   system vimrc file: "$VIM\vimrc"
     user vimrc file: "$HOME\_vimrc"
 2nd user vimrc file: "$HOME\vimfiles\vimrc"
 3rd user vimrc file: "$VIM\_vimrc"
      user exrc file: "$HOME\_exrc"
  2nd user exrc file: "$VIM\_exrc"
       defaults file: "$VIMRUNTIME\defaults.vim"
Compilation: cl -c /W3 /GF /nologo  -I. -Iproto -DHAVE_PATHDEF -DWIN32  -DFEAT_CSCOPE -DFEAT_TERMINAL -DFEAT_SOUND  -DFEAT_JOB_CHANNEL -DFEAT_IPV6        -DWINVER=0x0501 -D_WIN32_WINNT=0x0501 /source-charset:utf-8 /MP -DHAVE_STDINT_H /Ox /GL -DNDEBUG  /Zl /MT /D_CRT_SECURE_NO_DEPRECATE /D_CRT_NONSTDC_NO_DEPRECATE -DFEAT_MBYTE_IME -DDYNAMIC_IME -DDYNAMIC_ICONV -DDYNAMIC_GETTEXT -DFEAT_TCL -DDYNAMIC_TCL -DDYNAMIC_TCL_DLL=\"tcl86t.dll\" -DDYNAMIC_TCL_VER=\"8.6\" -DFEAT_LUA -DDYNAMIC_LUA -DDYNAMIC_LUA_DLL=\"lua54.dll\" -DFEAT_PYTHON -DDYNAMIC_PYTHON -DDYNAMIC_PYTHON_DLL=\"python27.dll\" -DFEAT_PYTHON3 -DDYNAMIC_PYTHON3 -DDYNAMIC_PYTHON3_DLL=\"python310.dll\" -DFEAT_MZSCHEME -I "C:\racket\include" -DMZ_PRECISE_GC -DDYNAMIC_MZSCHEME -DDYNAMIC_MZSCH_DLL=\"libracket3m_da32rk.dll\" -DDYNAMIC_MZGC_DLL=\"libracket3m_da32rk.dll\" -DFEAT_PERL -DPERL_IMPLICIT_CONTEXT -DPERL_IMPLICIT_SYS -DDYNAMIC_PERL -DDYNAMIC_PERL_DLL=\"perl532.dll\" -DFEAT_RUBY -DDYNAMIC_RUBY -DDYNAMIC_RUBY_DLL=\"x64-msvcrt-ruby300.dll\" -DRUBY_VERSION=30 -DFEAT_HUGE /Fd.\ObjCULYHTRZAMD64/ /Zi
Linking: link  /nologo /opt:ref /LTCG:STATUS oldnames.lib kernel32.lib advapi32.lib shell32.lib gdi32.lib  comdlg32.lib ole32.lib netapi32.lib uuid.lib /machine:AMD64   libcmt.lib  user32.lib  /nodefaultlib:lua54.lib  /STACK:8388608  /nodefaultlib:python27.lib /nodefaultlib:python310.lib   "C:\Tcl\lib\tclstub86.lib" winmm.lib WSock32.lib Ws2_32.lib /PDB:vim.pdb -debug
```

Powershell: `C:\Program Files\PowerShell\7\pwsh.exe`

### Steps to reproduce

```
vim longfile.txt
:set mouse=a // in VIM
//scroll mousewheel
```

### Expected Behavior

VIM should scroll

### Actual Behavior

Nothing happens

### Reference
Previously mentioned this issue in [issue 376](https://github.com/microsoft/terminal/issues/376).

**Comment by zadjii-msft** [comment] 2022-05-16 15:33
Note to self, this isn't the `ttymouse=sgr` thing.

I suspect this is a variation on https://github.com/microsoft/terminal/issues/10321#issuecomment-855083607, case 2. @DHowett to confirm, as our resident pwsh&vim expert.

**Comment by zadjii-msft** [comment] 2022-05-17 10:46
Yea I'm gonna mark this up as a /dupe of #10321, though, mouse scrolling in vim.exe doesn't even work in conhost, so I'd suspect there's work that'll be needed on their side. 

Thanks for taking the time to file the report! I did really want to make sure that your specific report was the same as that, not _something new_ that's regressed 😅

**Closed by zadjii-msft** 2022-05-17 10:46 UTC
Labels: Issue-Bug, Needs-Triage, Needs-Tag-Fix
