### ISSUE TITLE
Cannot start after updating to 1.16 - likely due to `elevate:true`

### ISSUE THREAD

**Issue by z4668640** [microsoft/terminal#14729] opened 2023-01-25 03:51 UTC
### Windows Terminal version

1.16.10232.0

### Windows build number

windows 11 OS: 25281.1000

### Steps to reproduce

Double clicking on the icon does nothing. Nothing is displayed.

### Actual Behavior

Couldn't launch today after Microsoft Store updated with the latest version. Double clicking on the icon does nothing. Nothing is displayed.

**Comment by Robo210** [comment] 2023-01-25 05:45
I have yet to debug what is going on, but on my machine something similar started happening as soon as I got the update to 1.16, except that after 10 minutes or more the window suddenly appears. I can see the process is running the whole time in Task Manager.

Hitting "Save" in the settings also triggers a 10+ minute hang.

**Comment by zadjii-msft** [comment] 2023-01-25 11:50
quick sanity check: are you using `elevate:true`/? 

> Hitting "Save" in the settings also triggers a 10+ minute hang.

This seems like a different issue. Actually, @Robo210 your whole post sounds like a different issue - mind filing a new thread? I just want to make sure we track all these regressions to their individual root causes, and not conflate them.

**Comment by educatedpork** [comment] 2023-01-25 14:34
I'm also encountering this problem - as soon as I installed 1.16.10232.0 (Windows 11) attempts to launch Terminal failed in the way described. 

> quick sanity check: are you using `elevate:true`/?

I am using 'elevate:true' here - and editing my settings.json to remove that results in me being able to launch Terminal again. But unfortunately without Administrator privilege, which isn't great. As soon as I re-enable "Run this process as Administrator" again, save, and re-launch - well.. it doesn't launch again.

Dean

**Comment by zadjii-msft** [comment] 2023-01-25 15:09
Okay well that's some sane confirmation, even if it's mysterious and confusing. 

For the record, if you really need `elevate:true`, we think 1.17 Preview should work for you. Based on the reports here, this sounds like #14501 which seems to be fixed by #14637. 

I still don't understand how this regressed in 1.16 in the first place... The list of https://github.com/microsoft/terminal/commits/release-1.16 ~doesn't have anything I'd immediately peg as dangerous. #14123 is maybe the spiciest title, but that seems... mundane.~

I guess the original issue repro'd in `1.15.2875.0`, which seems to imply that this would have regressed in a 1.15 version. But that doesn't _really_ make sense - then we would have gotten way more reports about this before the 1.15->1.16 release. 

I TAKE THAT BACK, #14520 is in 1.16 release. That's sus for sure.

**Comment by educatedpork** [comment] 2023-01-25 15:18
> **It might be valuable to know what Windows builds folks are on**. 

Sure, I'm seeing this on Windows 11 21H2 (22000.1455). I can also confirm that I'm **_not_** seeing any (obvious) problems with elevation using the latest 1.17 preview build.

Dean

**Comment by z4668640** [comment] 2023-01-28 03:29
I noticed that the program has been updated to version 1.16.10262.0. The log shows that the problem is fixed, and the program can run normally after my test. I think it's time to close this issue. What do you think?

**Comment by DHowett** [comment] 2023-01-28 04:04
Ah, you're totally right. Thanks!

**Closed** 2023-01-28 04:04 UTC
Labels: Issue-Bug, Severity-Crash, Needs-Triage
