### ISSUE TITLE
Unhandled exception. System.InvalidOperationException: Cannot read keys when either application does not have a console or when console input has been redirected

### ISSUE THREAD

**Issue by SergioMorchon** [microsoft/terminal#4981] opened 2020-03-18 09:26 UTC
# Environment

```
Windows build number: Win32NT, 10.0.18363.0, Microsoft Windows NT 10.0.18363.0:
```
# Steps to reproduce

Using:
* pwsh `v7.0.0`.
* [yarn|https://yarnpkg.com/] `v1.22.0`.
* [node|https://nodejs.org/en/] `v12.16.1`.
* [webpack dev server|https://webpack.js.org/configuration/dev-server/] `3.9.0`.

1. I start the dev server and leave it run in this terminal.
1. After some time of working between vscode and the web browser.
1. I come back to the console and hit `Ctrl+C` to stop the process and do other stuff.

# Expected behavior

To behave as a normal `Ctrl+C`, and continue using the same terminal tab.

# Actual behavior

It shows an exception:
```
PS C:\Users\smorchon\dev\webapp\web>
An error has occurred that was not properly handled. Additional information is shown below. The PowerShell process will
exit.
Unhandled exception. System.InvalidOperationException: Cannot read keys when either application does not have a console
or when console input has been redirected. Try Console.Read.
   at System.ConsolePal.ReadKey(Boolean intercept)
   at System.Console.ReadKey(Boolean intercept)
   at Microsoft.PowerShell.Internal.VirtualTerminal.ReadKey()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadOneOrMoreKeys()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadKeyThreadProc()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object
state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object
state)
   at System.Threading.ThreadHelper.ThreadStart()

[process exited with code 3762504530]
```
And after that, I can only close that terminal tab and continue un a new one.

**Comment by DHowett-MSFT** [comment] 2020-03-18 18:17
How did you install PowerShell?

**Comment by SergioMorchon** [comment] 2020-03-19 11:26
It is using `Windows.Terminal.PowershellCore`. I don't see Powershell in the settings application list (not _Powershell_ nor _pwsh_ there)
Here's the setting for the terminal:
```
      {
        "guid": "{574e775e-4f2a-5b96-ac1e-a2962a402336}",
        "hidden": false,
        "name": "PowerShell",
        "source": "Windows.Terminal.PowershellCore",
        "startingDirectory": "%USERPROFILE%/dev"
      },
```

**Comment by DHowett-MSFT** [comment] 2020-03-19 15:28
Okay, that’s powershell core. How did you install it?

**Comment by SergioMorchon** [comment] 2020-03-19 15:30
Maybe through dotnet core:
```
Users/smorchon/.dotnet/tools/.store/powershell/7.0.0/powershell/7.0.0/tools/netcoreapp3.1/any/win/pwsh.exe
```

**Comment by DHowett-MSFT** [comment] 2020-03-19 23:51
This looks like another version of https://github.com/PowerShell/PowerShell/issues/11314 -- but it really looks like node or yarn or something is closing the console handle and PowerShell is crashing because of it.

Does this happen _outside_ of Terminal?

**Comment by SergioMorchon** [comment] 2020-03-24 15:50
Sorry, but I cannot reproducet it anymore after installing PowerShell 7 from the repo (the `.msi` file).
Looks like after a day using the same dev server but on that powershell installation works as expected, without the Ctrl+C issue I mentioned.

**Comment by DHowett-MSFT** [comment] 2020-03-24 19:04
That's very strange. Thanks for following up!

**Closed by DHowett-MSFT** 2020-03-24 19:04 UTC
Labels: Needs-Attention, Needs-Repro, Needs-Tag-Fix, Needs-Triage

**Comment by EmperorRXF** [comment] 2021-03-21 14:30
I believe I'm having this same issue, and have managed to setup a reproducible scenario for it. It also only happens with the combination of `yarn v1` & `powershell core`. If I happen to use `cmd` or `windows powershell`, then the issue doesn't happen.

### Using:

windows OS - Microsoft Windows 10.0.19042
powershell core - v7.1.3
windows powershell - v5.1.19041.610
node - v14.15.0
yarn - v1.22.10

### Steps to reproduce:

1. ensure `node` & `yarn` is installed.
2. clone the repo from - `https://github.com/EmperorRXF/pscore-yarn-error`
3. from the cloned root, run `yarn`
4. run `yarn dev` (this will make node execute a long-running task, and log to the console)
5. while the task is running, hit CTRL+C to terminate the yarn process, and you'll notice the following error and the pscore process will crash
![image](https://user-images.githubusercontent.com/8752394/111908539-aa71da80-8a7f-11eb-9a56-e74ab4eb2232.png)

**Comment by lokinmodar** [comment] 2022-02-14 00:03
> I believe I'm having this same issue, and have managed to setup a reproducible scenario for it. It also only happens with the combination of `yarn v1` & `powershell core`. If I happen to use `cmd` or `windows powershell`, then the issue doesn't happen.
> 
> ### Using:
> windows OS - Microsoft Windows 10.0.19042 powershell core - v7.1.3 windows powershell - v5.1.19041.610 node - v14.15.0 yarn - v1.22.10
> 
> ### Steps to reproduce:
> 1. ensure `node` & `yarn` is installed.
> 2. clone the repo from - `https://github.com/EmperorRXF/pscore-yarn-error`
> 3. from the cloned root, run `yarn`
> 4. run `yarn dev` (this will make node execute a long-running task, and log to the console)
> 5. while the task is running, hit CTRL+C to terminate the yarn process, and you'll notice the following error and the pscore process will crash
>    ![image](https://user-images.githubusercontent.com/8752394/111908539-aa71da80-8a7f-11eb-9a56-e74ab4eb2232.png)

did you manage to solve this?

**Comment by alfawal** [comment] 2022-04-08 10:58
@DHowett-MSFT I believe that this error is occurring again, can you reopen the issue?
NOTE: This is happening sometimes only when pressing <kbd>CTRL</kbd>+<kbd>C</kbd> while using `nodemon`.

**Comment by zadjii-msft** [comment] 2022-04-08 11:17
@alfawal this was originally root caused to a PowerShell issue: https://github.com/PowerShell/PowerShell/issues/11314

I might recommend following up with them, since it seems to be an issue with the way they're handling ^C
