### ISSUE TITLE
Feature Request - Enable access to all the open tabs on the menu bar (alternative to ctrl+shift+tab)

### ISSUE THREAD

**Issue by dash-mode** [microsoft/terminal#1262] opened 2019-06-14 14:54 UTC
# Summary of the new feature/enhancement
Enable scrolling on the menu bar to be able to access all the open tabs in the windows terminal.

At the moment, after I open (say) 5 new tabs in the terminal, I am unable to access the tabs after the first few open tabs without closing a few tabs (so that the tab that I am looking for is  available on the menu bar)
<img width="960" alt="terminal_issue" src="https://user-images.githubusercontent.com/32212134/59517882-89d02600-8e92-11e9-8c0b-197f52208094.png">
I have 5 tabs open, but, as you can see in the image, I can only access three tabs through the menu bar.

I am aware that one can change tabs using ctrl+shift+tab. But I feel this would be an integral feature, as it is a basic option available in most applications.

# Proposed technical implementation details (optional)
To add an option of showing all the open tabs when the drop down button is clicked. Right now, it shows all the profiles available.
<img width="198" alt="terminal_issue" src="https://user-images.githubusercontent.com/32212134/59518353-7c676b80-8e93-11e9-8d13-0da2a503e4eb.png">

# Details
Microsoft Windows [Version 10.0.18917.1000]
Tools - VS2017 and VS2019

**Comment by zadjii-msft** [comment] 2019-06-14 16:14
You can scroll the tabs with the mouse:
![scroll-tabs-000](https://user-images.githubusercontent.com/18356694/59522573-9e152280-8e94-11e9-8b75-3cba9c077dd8.gif)

You might need to resize the window once first - we're using a VERY early prelease version of the TabControl.

@cinnamon-msft is working on a spec for how tabs should be sized, and the various different settings to control them.

This looks to me like it could be a dupe of either of: #857 #597

**Comment by dash-mode** [comment] 2019-06-14 16:18
I am unable to scroll with trackpad. But it might be an issue on my laptop only.
Any suggestions on how I can fix this on my laptop?

**Comment by zadjii-msft** [comment] 2019-06-14 16:30
I believe that's #444. Again, it's a _very_ early prerelease of the tab control, and there'll be lots of improvements in this space soon<sup>tm</sup>

**Closed** 2019-06-14 16:32 UTC
Labels: Issue-Feature, Needs-Tag-Fix, Needs-Triage

**Comment by Summon528** [comment] 2019-06-14 17:53
Technically you can scroll it with a trackpad, though you have to swipe the pad from up to down to simulate mouse scroll. I know that super ultra counter intuitive 🤣

**Comment by dash-mode** [comment] 2019-06-14 18:30
Oh you are right. Can it be changed in the settings?

**Comment by zadjii-msft** [comment] 2019-06-14 19:30
@dash-mode not currently, I'm presuming this is a bug in the tab control implementation. @teaP can call me out though if this is expected behavior

**Comment by teaP** [comment] 2019-06-14 23:41
That's a little odd since there is support for < and > scroll buttons in tabview right now. Terminal may be able to update their version and get better behavior. If that doesn't work let me know!

**Comment by dash-mode** [comment] 2019-06-16 03:51
Could someone tell me where I can seethe tab control implementation in the project folder?

**Comment by DHowett-MSFT** [comment] 2019-06-16 04:06
@dash-mode you can find the TabView implementation in the Microsoft/microsoft-ui-xaml repo [here](https://github.com/microsoft/microsoft-ui-xaml/tree/master/dev/TabView). Be wary, @teaP is actively working on it and it's got a spec review going on [here](https://github.com/microsoft/microsoft-ui-xaml-specs/pull/28).
If you've got input on features the tab control needs to support please feel free to weigh in on the spec. No promises that it'll get them for version 1, though.
