### ISSUE TITLE
Process exited with code 3221225477 (0xc0000005)

### ISSUE THREAD

**Issue by cdwmhcc** [microsoft/terminal#15973] opened 2023-09-16 16:06 UTC
### Windows Terminal version

1.17.11461.0

### Windows build number

10.0.22621.0

### Other Software

nodejs: 18.17.1

### Steps to reproduce

This error appears when I open the terminal. I'm pretty sure my memory isn't corrupted. It doesn't generate this error every time, it only happens occasionally.

### Actual Behavior

```
未经处理的异常:  System.AccessViolationException: 尝试读取或写入受保护的内存。这通常指示其他内存已损坏。
   在 System.Management.Automation.CommandProcessor.IsHelpRequested(String& helpTarget, HelpCategory& helpCategory)
   在 System.Management.Automation.PipelineOps.AddCommand(PipelineProcessor pipe, CommandParameterInternal[] commandElements, CommandBaseAst commandBaseAst, CommandRedirection[] redirections, ExecutionContext context)
   在 System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput, CommandParameterInternal[][] pipeElements, CommandBaseAst[] pipeElementAsts, CommandRedirection[][] commandRedirections, FunctionContext funcContext)
   在 System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame)
   在 System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   在 System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   在 System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
   在 System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
   在 System.Management.Automation.DlrScriptCommandProcessor.RunClause(Action`1 clause, Object dollarUnderbar, Object inputToProcess)
   在 System.Management.Automation.DlrScriptCommandProcessor.Complete()
   在 System.Management.Automation.CommandProcessorBase.DoComplete()
   在 System.Management.Automation.Internal.PipelineProcessor.DoCompleteCore(CommandProcessorBase commandRequestingUpstreamCommandsToStop)
   在 System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
   在 System.Management.Automation.Runspaces.LocalPipeline.InvokeHelper()
   在 System.Management.Automation.Runspaces.LocalPipeline.InvokeThreadProc()
   在 System.Management.Automation.Runspaces.PipelineThread.WorkerProc()
   在 System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   在 System.Threading.ThreadHelper.ThreadStart()

[已退出进程，代码为 3221225477 (0xc0000005)]
现在可以使用Ctrl+D关闭此终端，或按 Enter 重新启动。
```

**Comment by cdwmhcc** [comment] 2023-09-16 16:10
The windows 11 iso file I downloaded from the windows official website. The ssd is a brand new Samsung 990 pro 2TB. I just installed the system, only Nodejs 18.17.1 was installed, and no other applications were installed. I updated the terminal through the microsoft store.

**Comment by cdwmhcc** [comment] 2023-09-17 03:58
```
PS E:\01.web> git clone https://github.com/*****.git
Cloning into 'app'...
Username for 'https://github.com': *****
Password for 'https://*****@github.com':

未经处理的异常:  System.AccessViolationException: 尝试读取或写入受保护的内存。这通常指示其他内存已损坏。
   在 System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseParseDirective>b__0>d.MoveNext()
   在 System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   在 System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<UseParseDirective>b__0(InvocationContext context, Func`2 next)
   在 System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_2.<BuildInvocationChain>b__3(InvocationContext c)
   在 System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__5_0>d.MoveNext()
   在 System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   在 System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<RegisterWithDotnetSuggest>b__5_0(InvocationContext context, Func`2 next)
   在 System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_2.<BuildInvocationChain>b__3(InvocationContext c)
   在 System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<UseEnvironmentVariableDirective>b__6_0(InvocationContext context, Func`2 next)
   在 System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_2.<BuildInvocationChain>b__3(InvocationContext c)
   在 System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass8_0.<<UseExceptionHandler>b__0>d.MoveNext()
   在 System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   在 System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass8_0.<UseExceptionHandler>b__0(InvocationContext context, Func`2 next)
   在 System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_2.<BuildInvocationChain>b__3(InvocationContext c)
   在 System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass8_0.<<UseExceptionHandler>b__0>d.MoveNext()
   在 System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   在 System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass8_0.<UseExceptionHandler>b__0(InvocationContext context, Func`2 next)
   在 System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_2.<BuildInvocationChain>b__3(InvocationContext c)
   在 System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<CancelOnProcessTermination>b__1_0>d.MoveNext()
   在 System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   在 System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<CancelOnProcessTermination>b__1_0(InvocationContext context, Func`2 next)
   在 System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_1.<BuildInvocationChain>b__2(InvocationContext ctx, Func`2 next)
   在 System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_1.<BuildInvocationChain>b__2(InvocationContext ctx, Func`2 next)
   在 System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_1.<BuildInvocationChain>b__2(InvocationContext ctx, Func`2 next)
   在 System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_1.<BuildInvocationChain>b__2(InvocationContext ctx, Func`2 next)
   在 System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_1.<BuildInvocationChain>b__2(InvocationContext ctx, Func`2 next)
   在 System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_1.<BuildInvocationChain>b__2(InvocationContext ctx, Func`2 next)
   在 System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_1.<BuildInvocationChain>b__2(InvocationContext ctx, Func`2 next)
   在 System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_1.<BuildInvocationChain>b__2(InvocationContext ctx, Func`2 next)
   在 System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_1.<BuildInvocationChain>b__2(InvocationContext ctx, Func`2 next)
   在 System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_1.<BuildInvocationChain>b__2(InvocationContext ctx, Func`2 next)
   在 System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_1.<BuildInvocationChain>b__2(InvocationContext ctx, Func`2 next)
   在 System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_1.<BuildInvocationChain>b__2(InvocationContext ctx, Func`2 next)
   在 System.CommandLine.Invocation.InvocationPipeline.<<InvokeAsync>g__FullInvocationChainAsync|2_0>d.MoveNext()
   在 System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   在 System.CommandLine.Invocation.InvocationPipeline.<InvokeAsync>g__FullInvocationChainAsync|2_0(InvocationContext context)
   在 System.CommandLine.Invocation.InvocationPipeline.InvokeAsync(IConsole console)
   在 System.CommandLine.Parsing.ParseResultExtensions.<InvokeAsync>d__0.MoveNext()
   在 System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   在 System.CommandLine.Parsing.ParseResultExtensions.InvokeAsync(ParseResult parseResult, IConsole console)
   在 System.CommandLine.Parsing.ParserExtensions.<InvokeAsync>d__3.MoveNext()
   在 System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   在 System.CommandLine.Parsing.ParserExtensions.InvokeAsync(Parser parser, String[] args, IConsole console)
   在 GitCredentialManager.Application.<RunInternalAsync>d__7.MoveNext()
   在 System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   在 GitCredentialManager.Application.RunInternalAsync(String[] args)
   在 GitCredentialManager.ApplicationBase.RunAsync(String[] args)
   在 GitCredentialManager.Program.AppMain(Object o)
   在 System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   在 System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   在 System.Threading.ThreadHelper.ThreadStart(Object obj)
remote: Enumerating objects: 511, done.
remote: Counting objects: 100% (511/511), done.
remote: Compressing objects: 100% (417/417), done.
remote: Total 511 (delta 74), reused 508 (delta 74), pack-reused 0
Receiving objects: 100% (511/511), 1.17 MiB | 4.33 MiB/s, done.
Resolving deltas: 100% (74/74), done.
```

**Comment by cdwmhcc** [comment] 2023-09-17 04:03
``` bash
PS E:\01.web\app> pnpm dev

> @mh/app@0.0.1 dev E:\01.web\app
> nuxt dev

Nuxt 3.7.0 with Nitro 2.6.2                                                                                   12:02:05
                                                                                                              12:02:05
  ➜ Local:    http://127.0.0.1:3000/
  ➜ Network:  use --host to expose



#
# Fatal error in , line 0
# Check failed: fixed_size_above_fp + (stack_slots * kSystemPointerSize) - CommonFrameConstants::kFixedFrameSizeAboveFp + outgoing_size == result.
#
#
#
#FailureMessage Object: 000000FAE49FC6E0
 1: 00007FF6363B07BF node_api_throw_syntax_error+175823
 2: 00007FF6362C630F v8::CTypeInfoBuilder<void>::Build+12559
 3: 00007FF637183732 V8_Fatal+162
 4: 00007FF636CF2841 v8::internal::BasicBlockProfilerData::ResetCounts+35681
 5: 00007FF636CF6C7F v8::internal::Deoptimizer::GetDeoptimizedCodeCount+1279
 6: 00007FF636DF3B20 v8::internal::SetupIsolateDelegate::SetupHeap+288
 7: 000000FAE49FCBC8
 ELIFECYCLE  Command failed with exit code 2147483651.
```

**Comment by cdwmhcc** [comment] 2023-09-17 04:04
```
PS E:\01.web\app> pnpm dev

> @mh/app@0.0.1 dev E:\01.web\app
> nuxt dev

Nuxt 3.7.0 with Nitro 2.6.2                                                                                   12:03:53
                                                                                                              12:03:53
  ➜ Local:    http://127.0.0.1:3000/
  ➜ Network:  use --host to expose

 ELIFECYCLE  Command failed with exit code 3221225477.
```

**Comment by cdwmhcc** [comment] 2023-09-17 04:05
![image](https://github.com/microsoft/terminal/assets/8030134/793e2866-8274-4e8d-be33-1d73e4f70a41)

**Comment by cdwmhcc** [comment] 2023-09-18 08:03
I set the `CPU c-status` to off in `bios` and the issue has been resolved for now, but I need a little more time to test.

**Comment by lhecker** [comment] 2023-09-18 09:35
Yep, this is most likely an issue with your hardware. We don't really have much influence over the applications that run in the terminal themselves. I'll close this issue for now, but please feel free to reopen it if you find any indication that it is due to Windows Terminal.

Disabling C states to fix the issue is not the best idea. C states are very useful to reduce the power draw of your CPU, which reduces temperature and (apart from a few exceptions) improves performance quite a bit by allowing some cores to boost higher. Try these:
* Upgrade your mainboard to the latest available UEFI version from your vendor
* Try booting it after resetting all UEFI settings to factory defaults (F9 usually)
  Afterwards reapply any timing/voltage adjustments if necessary (including XMP)
* Refund, return, or exchange your CPU - if the above didn't work and disabling C states helped, then the CPU is most likely faulty

**Closed by lhecker** 2023-09-18 09:35 UTC
Labels: Issue-Bug, Needs-Triage

**Comment by cdwmhcc** [comment] 2023-09-18 10:06
@lhecker Disable c-status and the system will work normally. This should be a fault caused by the CPU. thank you for your reply!
