### ISSUE TITLE
[BUG] Tabs not visible if created outside of visible area of tab bar

### ISSUE THREAD

**Issue by harzerj** [microsoft/terminal#2392] opened 2019-08-11 08:14 UTC
# Environment

```
Windows build number: Microsoft Windows [Version 10.0.18362.10012]
Windows Terminal version (if applicable): Version: 0.3.2171.0

Any other software?
No
```

# Steps to reproduce

1. Create tabs until they get created outside of the visible area of the tab bar

# Expected behavior

After scrolling the created tabs should be visible

# Actual behavior

After scrolling only empty space is visible instead of the tabs
See attached screenshot with empty tab bar
![Empty Tab Bar](https://user-images.githubusercontent.com/53991697/62831515-f1032000-bc20-11e9-8545-6a814541c13e.png)

**Comment by harzerj** [comment] 2019-08-11 08:16
![Empty Tab Bar](https://user-images.githubusercontent.com/53991697/62831515-f1032000-bc20-11e9-8545-6a814541c13e.png)

**Comment by krzysdz** [comment] 2019-08-12 08:35
It's probably a duplicate of #875

**Comment by zadjii-msft** [comment] 2019-08-12 13:22
Certainly a dupe of that issue. Thanks!

**Closed by zadjii-msft** 2019-08-12 13:22 UTC
Labels: Needs-Tag-Fix, Needs-Triage
