### ISSUE TITLE
ANSI sequence rendered differently: `\u001b[0m\u001b[7m\u001b[1m\u001b[32m PASS \u001b[39m\u001b[22m\u001b[27m\u001b[0m`

### ISSUE THREAD

**Issue by be5invis** [microsoft/terminal#3201] opened 2019-10-15 04:31 UTC
# Environment

```none
Windows build number: 18362.418
Windows Terminal version: 0.5.2762.0
```

# Steps to reproduce

- Install Node.js
- Run this command in Node.js repl: `console.log('\u001b[0m\u001b[7m\u001b[1m\u001b[32m PASS \u001b[39m\u001b[22m\u001b[27m\u001b[0m')`

# Expected behavior

A `PASS` is shown in black text and green background.

# Actual behavior

In Windows terminal, `PASS` is shown in dark gray text rather than black. In the old console it is shown in black.

![image](https://user-images.githubusercontent.com/240091/66800393-dde32980-eec9-11e9-8cf0-a309a7f8a68f.png)

**Comment by DHowett-MSFT** [comment] 2019-10-15 04:56
I believe this is a version of #293 or #2661. More likely 2661, but I can't get my debug tap working at the moment.

**Comment by j4james** [comment] 2019-10-15 11:57
Looking at this in the debugger, I can see the attributes coming through as:

    \x1b[1m\x1b[30m\x1b[102m

So in one sense it has got the colors correct, sending through a black foreground with a bright green background, but it also includes the bold attribute, which then ends up making the foreground bright as well.

**Comment by DHowett-MSFT** [comment] 2019-10-17 19:25
Really, this should come out of ConPTY as `1;7;40;92` instead of `30;102` (#2661)... but it looks like we should at the very least suppress the brightness of the foreground when we make the bright foreground the background.

Since we don't support separate bold and bright, that'll also knock the bold attribute off ☹️

**Comment by DHowett-MSFT** [comment] 2019-10-21 20:00
More I think about this the closer I am to calling it a /dupe of #2661. Thanks again!

**Closed by DHowett-MSFT** 2019-10-21 20:00 UTC
Labels: Area-VT, Issue-Bug, Needs-Triage, Product-Conpty
