### ISSUE TITLE
opening csi.exe in Terminal isnt letting me use the Up key to view previous commands

### ISSUE THREAD

**Issue by hexbinoct** [microsoft/terminal#4514] opened 2020-02-09 18:16 UTC
# Environment

Windows build number: 10.0.18363.628
Windows Terminal version (if applicable):  0.8.10261.0

Any other software?
Visual Studio 2015
```

# Steps to reproduce

So Open Windows Terminal and open a cmd tab. Type the following:
"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" amd64
adjust the path to whatever is valid for you, I am using Visual Studio 2015. After the above executes, 
now type "csi.exe" (without the quotes) and hit Enter, you will be in the c# interactive console for c# scripting. 
Now write anything which is a valid c# expression, for example:
int x =0;
which does nothing but sets variable "x" to zero. Now use the keyboard Up arrow key so that you can use that same expression you just wrote, you wont get anything, which should not be the case.

# Expected behavior

When you press the Up key, you should be able to go through the history of everything you have written before one by one.

# Actual behavior

Up key doesnt give you anything that you wrote in the csi.exe before

**Comment by DHowett-MSFT** [comment] 2020-02-10 20:11
I'm guessing this is a /dupe of #2397

**Comment by DHowett-MSFT** [comment] 2020-02-10 20:13
Interesting. CSI is actually using cooked read, _and_ I cannot reproduce this on my machine.

What keyboard layout are you using? What locale is your machine set to?

If you press <kbd>F7</kbd> after entering a command, do you get a purple-on-white popup (behind an annoying caret browsing dialog) that contains `hello`?

**Comment by hexbinoct** [comment] 2020-02-11 20:20
its working now and I have no idea why now and why wasnt it working yesterday, I had a normal cmd.exe running csi and a Terminal running cmd running csi (side by side) and the up key wasnt working in the Terminal. I followed my instructions above and it did work now, tried it twice and its working. So I will close this issue.

**Closed** 2020-02-11 20:20 UTC
Labels: Needs-Attention, Needs-Tag-Fix

**Comment by DHowett-MSFT** [comment] 2020-02-11 20:22
Thanks for following up!
