### ISSUE TITLE
Start a certain tab of shell directly in the Start menu

### ISSUE THREAD

**Issue by yihuajack** [microsoft/terminal#4919] opened 2020-03-14 05:14 UTC
I notice that a new certain tab of shell other than the default shell could only be opened inside the Terminal. Could there be some additional options in the right-click menu of the Terminal in the Start menu? The current right-click menu of the Terminal in the Start Menu is

![2020-03-14_130228](https://user-images.githubusercontent.com/23608500/76675419-40189580-65f4-11ea-9593-bf6737fab34e.png)

I think it will be more convenient like this
![2020-03-14_125429](https://user-images.githubusercontent.com/23608500/76675436-6c341680-65f4-11ea-8e70-20acdd85e2bc.png)
so that users can directly start a certain tab they want directly from the Start menu.

**Comment by DHowett-MSFT** [comment] 2020-03-14 05:34
Thanks for the feature request! It’s a /dupe of #576

**Closed by DHowett-MSFT** 2020-03-14 05:34 UTC
Labels: Issue-Feature, Needs-Tag-Fix, Needs-Triage
