### ISSUE TITLE
Single terminal window option

### ISSUE THREAD

**Issue by perneky** [microsoft/terminal#8314] opened 2020-11-18 10:17 UTC
Hello,

There could be an option if I open a new terminal, open a new tab inside an already running terminal window if there is any, instead of opening a new window. It would make sense to have a global option and be able to override it from the command line as well.

Laci

**Comment by Don-Vito** [comment] 2020-11-18 11:10
@perneky - this seems to be a duplicate of https://github.com/microsoft/terminal/issues/2227, which is handled as a part of terminal process model overhaul: https://github.com/microsoft/terminal/issues/5000

**Comment by zadjii-msft** [comment] 2020-11-18 11:54
Sure is, and is also covered heavily in the spec over in #8135. Thanks!

/dup #2227

**Closed by zadjii-msft** 2020-11-18 11:54 UTC
Labels: Issue-Feature, Needs-Tag-Fix, Needs-Triage
