### ISSUE TITLE
Feature Request: Remember history

### ISSUE THREAD

**Issue by codemwnci** [microsoft/terminal#1924] opened 2019-07-11 10:02 UTC
# Summary of the new feature/enhancement
Following a restart of the terminal app, whether that is within an active session, or after windows restart, it would be useful to pick up where I left off...which would include
1. The previously opened tabs
2. The previously buffered outputs
3. The previously run commands in the command history

Basically, try to make it behave more like a multi-tab browser would behave.

**Comment by zadjii-msft** [comment] 2019-07-11 12:28
This is _mostly_ a dupe of #961. 

Unfortunately, restoring the command history is something the _shell_ (`cmd.exe`, `powershell`, `bash`) would be responsible for. Powershell and bash both already persist command history, but cmd.exe doers not. Unfortunately, we'll never be able to change that about cmd.exe either, as it's a parked codebase.

**Closed by zadjii-msft** 2019-07-11 12:28 UTC
Labels: Issue-Feature, Needs-Tag-Fix, Needs-Triage
