### ISSUE TITLE
Cursor changing to block

### ISSUE THREAD

**Issue by RiteshChepuri** [microsoft/terminal#14321] opened 2022-11-02 07:11 UTC
### Other Software

NVIM v0.7.2

PowerShell 7.2.7

### Steps to reproduce

Quitting NVIM

### Expected Behavior

I Normally use Bar as my cursor in PowerShell. When I open vim or NVIM which normally has cursor block as cursor in normal mode and when I quit the vim the cursor should be bar in the PowerShell. 
![Uploading Screenshot 2022-11-02 123910.png…]()

### Actual Behavior

After quitting the vim the bar cursor changes to block cursor .
![Screenshot 2022-11-02 124056](https://user-images.githubusercontent.com/81766942/199423349-e7b8d2bf-76bf-4899-91b3-29a6e9cd73c9.png)

**Comment by lhecker** [comment] 2022-11-02 17:29
This appears to be a /duplicate of #9081. Let me know if I got that wrong! 🙂

**Closed** 2022-11-02 17:30 UTC
Labels: Issue-Bug, Needs-Triage
