### ISSUE TITLE
UNPACKAGED WindowsTerminal.exe no longer runs as of v1.9

### ISSUE THREAD

**Issue by 89z** [microsoft/terminal#10662] opened 2021-07-14 17:29 UTC
### Windows Terminal version (or Windows build number)

v1.9

### Steps to reproduce

I am currently using this and everything works fine:

https://github.com/microsoft/terminal/releases/tag/v1.8.1444.0

However if I download and extract this:

https://github.com/microsoft/terminal/releases/tag/v1.9.1942.0

and double click `WindowsTerminal.exe`

### Actual Behavior

nothing happens

**Comment by DHowett** [comment] 2021-07-14 20:14
Huh, that's unexpected. Would you mind sharing a copy of your unpackaged settings file? `%LOCALAPPDATA%\Microsoft\Windows Terminal\settings.json`

Thanks!

**Comment by 89z** [comment] 2021-07-14 20:22
Here:

~~~json
{
    "$schema": "https://aka.ms/terminal-profiles-schema",
   "copyOnSelect": true,
   "multiLinePasteWarning": false,
   "profiles": {
      "defaults": {},
      "list": [
         {
            "commandline": "C:/PowerShell/pwsh.exe -NoLogo",
            "fontSize": 11,
            "guid": "{61c54bbd-c2c6-5271-96e7-009a87ff44bf}"
         },
         {
             "guid": "{b453ae62-4e3d-5e58-b989-0a998ec441b8}",
             "hidden": false,
             "name": "Azure Cloud Shell",
             "source": "Windows.Terminal.Azure"
         }
      ]
   },
   "keybindings": [
      { "command": {"action": "copy", "singleLine": false }, "keys": "ctrl+c" }
   ]
}
~~~

**Comment by WSLUser** [comment] 2021-07-14 22:41
To add data point: I tried this and works fine on 1.9 Preview. Need to test 1.10 Preview. I have a suspicion its dependency related though due to trying master earlier before the 1.10 release and noticing a couple libs were missing

**Comment by 89z** [comment] 2021-07-14 22:51
I dont like how Windows 10 programs just silently fail. In the past with Windows 7 and similar, youd get a missing DLL warning, so you at least knew how to fix the problem. Now, nothing.

**Comment by K2ouMais** [comment] 2021-07-15 08:43
We had this problem already in the past and it was fixed.

Now it doesnt work again. The terminal just fails on start without any errors.

Because I cant install anything on my PC (no admin rights), I rely on unpaking the terminal and use the *.exe file.

**Comment by zadjii-msft** [comment] 2021-07-15 13:31
@89z what OS version are you on? Are there any events being logged in Event Viewer when you launch the Terminal?

**Comment by 89z** [comment] 2021-07-15 13:42
> @89z what OS version are you on?

Windows 10

> Are there any events being logged in Event Viewer when you launch the Terminal?

~~~
Faulting application name: WindowsTerminal.exe, version: 1.9.2107.13002, time stamp: 0x60edf3e3
Faulting module name: ucrtbase.dll, version: 10.0.18362.1110, time stamp: 0xb4cacc38
Exception code: 0xc0000409
Fault offset: 0x000000000006dace
Faulting process id: 0x32bc
Faulting application start time: 0x01d7797eb9a2b61c
Faulting application path: C:\Microsoft.WindowsTerminal_1.9.1942.0_8wekyb3d8bbwe\CascadiaPackage_1.9.1942.0_x64\WindowsTerminal.exe
Faulting module path: C:\Windows\System32\ucrtbase.dll
Report Id: ab4dd69b-8945-4c2b-b7e6-0188e3009150
Faulting package full name: 
Faulting package-relative application ID: 
~~~

**Comment by zadjii-msft** [comment] 2021-07-15 13:57
> > what OS version are you on?
> 
> Windows 10

Oh, I meant what specific build number are you on? `winver` should have that info

**Comment by 89z** [comment] 2021-07-15 14:00
> Oh, I meant what specific build number are you on? `winver` should have that info

Windows 10 version 1909

**Comment by K2ouMais** [comment] 2021-07-15 18:25
> > Oh, I meant what specific build number are you on? `winver` should have that info
> 
> Windows 10 version 1909
> 
> Which seems to be fine per this https://github.com/microsoft/terminal#installing-and-running-windows-terminal

I am on the same windows 10 build.

**Comment by oleksis** [comment] 2021-07-16 22:44
> > Oh, I meant what specific build number are you on? `winver` should have that info
> 
> Windows 10 version 1909
> 
> Which seems to be fine per this https://github.com/microsoft/terminal#installing-and-running-windows-terminal

I have the same build and the same problem. Unpacking the msixbundle run the `WindowsTerminal.exe` and not work 😢

**Comment by 89z** [comment] 2021-07-16 22:46
I am unsubscribing from this, with all due respect, I dont want to be notified everytime someone wants to say "me too". If you need anything from me, please just "at" me directly, thanks

**Comment by WSLUser** [comment] 2021-07-19 15:20
I've tested out 1.10 Preview and it works just fine. No dependencies missing.

**Comment by oleksis** [comment] 2021-07-19 21:51
> I've tested out 1.10 Preview and it works just fine. No dependencies missing.

You test in the same platform **winver 1909 (18363.1198)** ?

I try there I get errors missing depending

**Comment by zadjii-msft** [comment] 2021-07-19 21:53
> I try there I get errors dependencies missing.

What errors specifically? Are there any events in Event Viewer that might clue us into _which_ dependency is missing?

**Comment by DHowett** [comment] 2021-07-19 23:07
Oh no.

> Msg:[winrt::hresult_error: WindowsXamlManager and DesktopWindowXamlSource are supported for apps targeting Windows version 10.0.18226.0 and later.  Please check either the application manifest or package manifest and ensure the MaxTestedVersion property is updated.]

I didn't realize that the issue fixed by https://github.com/microsoft/terminal/pull/10370 was already present in the 1.9 release branch. 😦 

I'll backport that.

**Comment by DHowett** [comment] 2021-07-19 23:09
Confirming: the manifest embedded in WindowsTerminal.exe specifies that it was tested in 10.0.19041. While this should be sufficient for 10.0.1836x, it is not.

**Comment by oleksis** [comment] 2021-07-19 23:15
> Confirming: the manifest embedded in WindowsTerminal.exe specifies that it was tested in 10.0.19041. While this should be sufficient for 10.0.1836x, it is not.

When is fixed and released i can check 🤞🏾

**Comment by 89z** [comment] 2021-09-03 14:50
Just tried this with v1.10:

https://github.com/microsoft/terminal/releases/tag/v1.10.2383.0

and seems to be fixed

**Comment by zadjii-msft** [comment] 2021-09-14 15:14
Thanks for confirming!

**Closed by zadjii-msft** 2021-09-14 15:14 UTC
Labels: Issue-Bug, Area-Build, Product-Terminal, Severity-Blocking, Priority-0, zStable-Service-Consider, zPreview-Service-Consider

**Comment by oleksis** [comment] 2021-09-14 18:00
> Thanks for confirming!

Just confirmed the version `1.10.2383.0` work in Windows 10 (1909 - SO 18363.1198)

🙏🏾

**Comment by miniksa** [comment] 2021-09-27 17:25
I just ran this unpackaged to test some of Carlos's fixes, so I'm pretty confident it's been ported around appropriately.
