### ISSUE TITLE
Windows Terminal crashes when icon contains %USERPROFILE%

### ISSUE THREAD

**Issue by fpintos** [microsoft/terminal#1650] opened 2019-06-26 20:43 UTC
# Environment

```none
Windows build number: 10.0.18362.175
Windows Terminal version (if applicable): 0.2.1715.0
```

# Steps to reproduce

Create a profile with an icon property like this, where the icon file exists:
```json
            "icon": "%USERPROFILE%\\AppData\\Local\\IconsForEnlistments\\Substrate.ico",
``` 

# Expected behavior

For Windows Terminal to show the new profile and its icon.

# Actual behavior

Windows Termial crashes on startup.

# Workaround

Update the icon property so that it does not use environment variables makes things work.

**Comment by DHowett-MSFT** [comment] 2019-06-26 20:49
I bet that we don't expand environment variables when we load icons, and that technically means it's a dupe of #1468

**Closed by DHowett-MSFT** 2019-06-26 20:49 UTC
Labels: Needs-Tag-Fix, Needs-Triage
