### ISSUE TITLE
Terminal window not scrollable.

### ISSUE THREAD

**Issue by utkkarsh** [microsoft/terminal#1463] opened 2019-06-23 09:21 UTC
# Environment
Microsoft Windows [Version 10.0.18362.30]

# Steps to reproduce

Just type any command that will fill your terminal window.
eg.  C:\Users\Microsoft>dir

# Expected behavior
I should be able to scroll to top of the page to see previous results using mouse/touch pad.

# Actual behavior
I am not able to scroll to the top in the new Windows Terminal but I am able to scroll in the old command prompt.

**Comment by JushBJJ** [comment] 2019-06-23 10:52
What's your historySize in your profiles.json file? (In what ever profile you're using in that session)

**Comment by varungupta3009** [comment] 2019-06-23 13:40
> # Environment
> Microsoft Windows [Version 10.0.18362.30]
> 
> # Steps to reproduce
> Just type any command that will fill your terminal window.
> eg. C:\Users\Microsoft>dir
> 
> # Expected behavior
> I should be able to scroll to top of the page to see previous results using mouse/touch pad.
> 
> # Actual behavior
> I am not able to scroll to the top in the new Windows Terminal but I am able to scroll in the old command prompt.

Just use Ctrl+Shift+Up/Down Arrow to scroll Up or Down. Customize it in the settings file (profiles.json)

**Comment by utkkarsh** [comment] 2019-06-24 20:01
> What's your historySize in your profiles.json file? (In what ever profile you're using in that session)

"historySize" : 9001,

**Comment by utkkarsh** [comment] 2019-06-24 20:05
> > # Environment
> > Microsoft Windows [Version 10.0.18362.30]
> > # Steps to reproduce
> > Just type any command that will fill your terminal window.
> > eg. C:\Users\Microsoft>dir
> > # Expected behavior
> > I should be able to scroll to top of the page to see previous results using mouse/touch pad.
> > # Actual behavior
> > I am not able to scroll to the top in the new Windows Terminal but I am able to scroll in the old command prompt.
> 
> Just use Ctrl+Shift+Up/Down Arrow to scroll Up or Down. Or customize the shortcuts in the settings file (profiles.json)

Hi @varungupta3009 , I know the keyboard shortcuts that's why I mentioned that I am not able to scroll the terminal window using laptop touchpad ( Synaptics Touchpad) while I am able to scroll using an external mouse.

**Comment by DHowett-MSFT** [comment] 2019-06-24 20:27
This seems like a duplicate of #979 ("touchpad scrolling not possible")

**Closed by DHowett-MSFT** 2019-06-24 20:27 UTC
Labels: Needs-Tag-Fix, Needs-Triage
