### ISSUE TITLE
Crash on RDP connection

### ISSUE THREAD

**Issue by shuffle2** [microsoft/terminal#10417] opened 2021-06-13 00:23 UTC
### Windows Terminal version (or Windows build number)

1.8.1521.0

### Other Software

Microsoft Windows [Version 10.0.19042.1055]

### Steps to reproduce

Start Terminal (either from local session or RDP)
Connect a new RDP session
Observe Terminal (and any child processes) is no longer running.

### Expected Behavior

Terminal continues running across RDP connects/disconnects.

### Actual Behavior

I see the following crash logs in Event Viewer:
```
Faulting application name: WindowsTerminal.exe, version: 1.8.2106.1001, time stamp: 0x60b64ad3
Faulting module name: Microsoft.UI.Xaml.dll, version: 2.5.2012.2003, time stamp: 0x5fc87886
Exception code: 0xc0000005
Fault offset: 0x00000000000df4af
Faulting process id: 0x502c
Faulting application start time: 0x01d75fde99430238
Faulting application path: C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_1.8.1521.0_x64__8wekyb3d8bbwe\WindowsTerminal.exe
Faulting module path: C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_1.8.1521.0_x64__8wekyb3d8bbwe\Microsoft.UI.Xaml.dll
Report Id: 6cd58efd-60b4-47ca-a0fd-f325706fc589
Faulting package full name: Microsoft.WindowsTerminal_1.8.1521.0_x64__8wekyb3d8bbwe
Faulting package-relative application ID: App
```

```
Fault bucket 2238112546877327133, type 5
Event Name: MoAppCrash
Response: Not available
Cab Id: 0

Problem signature:
P1: Microsoft.WindowsTerminal_1.8.1521.0_x64__8wekyb3d8bbwe
P2: praid:App
P3: 1.8.2106.1001
P4: 60b64ad3
P5: Microsoft.UI.Xaml.dll
P6: 2.5.2012.2003
P7: 5fc87886
P8: c0000005
P9: 00000000000df4af
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER904C.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER9157.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER9167.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER9175.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER9195.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Microsoft.Window_ea24f84bb2ad8ddcd6855a771669148aa5dbf98_60528276_beebf310-482c-4636-b3a3-9d972986f8ca

Analysis symbol: 
Rechecking for solution: 0
Report Id: 6cd58efd-60b4-47ca-a0fd-f325706fc589
Report Status: 268435456
Hashed bucket: d56910dc0d52099aaf0f5f80dbf7c71d
Cab Guid: 0
```

**Comment by zadjii-msft** [comment] 2021-06-15 14:13
Okay this might be insane, but could you repro this with the Feedback Hub? That'll get us a stack trace we can use to actually identify the root cause here. 

/feedback

**Comment by shuffle2** [comment] 2021-06-16 00:19
I don't have WER uploads enabled on that machine. 
I tried to build a debug build of Terminal and reproduce, but now the issue doesn't even happen on the build from the Store, either 🤔
Oh well, can probably close this until it happens again.

**Comment by shuffle2** [comment] 2021-06-30 09:05
My crash stack is the same as https://github.com/microsoft/terminal/issues/10520

**Comment by shuffle2** [comment] 2021-07-29 20:18
Going to reopen as it still occurs (now on Version: 1.9.1942.0), and is very frustrating :/

**Comment by Dan-Albrecht** [comment] 2021-08-17 06:13
Hitting this as well. Can we use this issue to track pulling in the latest Microsoft.UI.Xaml.dll which should include https://github.com/microsoft/microsoft-ui-xaml/pull/5201 and allegedly fix this?

**Comment by zadjii-msft** [comment] 2021-08-17 15:14
Since this is fixed in https://github.com/microsoft/microsoft-ui-xaml/pull/5201, which is in MUX 2.6.1, then I think we can just use the existing issue we have for "update to 2.6". Thanks all (sorry this dropped out of the triage queue)

/dup #10508

**Closed by zadjii-msft** 2021-08-17 15:14 UTC
Labels: Needs-Triage, Needs-Attention, Needs-Tag-Fix
