### ISSUE TITLE
inserting a complex emoji in a wsl instance results in some strange interactions with the arrow keys

### ISSUE THREAD

**Issue by LuanVSO** [microsoft/terminal#3754] opened 2019-11-27 21:25 UTC
# Environment

```none
Windows build number: [10.0.18363.476]
Windows Terminal version (if applicable): 0.7.3291.0

Any other software?
 no
```

# Steps to reproduce
1-insert a complex emoji (🐱‍👤 for example) in a wsl tab on terminal
2-try navigating backward and forward with the arrow keys
# Expected behavior
navigate backward an forward with the cursor

# Actual behavior
it  duplicates "🐱" on the screen.
[visual glitch?]
![image](https://user-images.githubusercontent.com/43626415/69760327-073ada80-1143-11ea-8cb7-718a332f924b.png)

**Comment by DHowett-MSFT** [comment] 2019-11-28 00:44
This is fundamentally a /dupe of #1472. Thanks! Emoji composed of combining characters are not well-supported.

**Closed by DHowett-MSFT** 2019-11-28 00:44 UTC
Labels: Needs-Tag-Fix, Needs-Triage
