### ISSUE TITLE
When opening a new window tab titles don't resize, and so the new window gets lost

### ISSUE THREAD

**Issue by blowdart** [microsoft/terminal#2221] opened 2019-08-03 16:19 UTC
# Environment

Windows: 10.0.18362.267
Windows Terminal version:  0.3.2142.0

# Steps to reproduce

Have terminal at a small-ish size.
Keep opening new terminals

# Expected behavior

Tabs should resize titles so all windows are viewable, like browsers do.

# Actual behavior

Tabs do not resize, so eventually new terminals get lost to the right;

This window has four terminals open, but you can only see three

![Annotation 2019-08-03 091544](https://user-images.githubusercontent.com/796298/62414406-9e49b880-b5cf-11e9-87c8-2fa2d8c844d5.jpg)

You have to resize to see the fourth;

![Annotation 2019-08-03 091558](https://user-images.githubusercontent.com/796298/62414416-abff3e00-b5cf-11e9-9253-98f2e270f598.jpg)

**Comment by TayYuanGeng** [comment] 2019-08-03 17:29
This looks something similar to #1205

**Comment by zadjii-msft** [comment] 2019-08-05 12:37
I'm going to say that this is a dupe of either 

"When the window is smaller than the sum of the width of the tabs, the tabs are cut off, without indication to scroll"

or 

"Without using tabs don't shrink/expand like browser tabs / I want to set a min width for my tabs / I want a fixed width for my tabs / I want tabs to expand to split the available space / any other possible tab sizing"


Both within #1375.

**Closed by zadjii-msft** 2019-08-05 12:37 UTC
Labels: Needs-Tag-Fix, Needs-Triage
