### ISSUE TITLE
focus-pane command line option

### ISSUE THREAD

**Issue by eronnen** [microsoft/terminal#5678] opened 2020-04-30 21:52 UTC
# Description of the new feature/enhancement

When opening the terminal with multiple panes in a tab, with a command line like "wt.exe split-pane -V; split-pane -H", the focus in the tab will always be on the last opened pane.
 
I think it would be useful to add a command line option of "focus-pane", similar to the existing option "focus-tab", so I could choose which pane will have the focus right after the tab is opened.

**Comment by DHowett-MSFT** [comment] 2020-04-30 23:40
Thanks for the request! This is a /dupe of #5464.

**Closed by DHowett-MSFT** 2020-04-30 23:40 UTC
Labels: Issue-Feature, Needs-Tag-Fix, Needs-Triage
