### ISSUE TITLE
question about other processes stealing focus from WT

### ISSUE THREAD

**Issue by rodrymbo** [microsoft/terminal#8569] opened 2020-12-12 14:03 UTC
From time to time when working in WT, some other program will steal focus. This is particularly annoying when I am entering a password. Am I missing something or is there a way to keep that from happening? (Yes, part/most of the problem is the other process thinking it needs focus when it clearly just wants to let me know about something and doesn't even want a response ... in at least one case focus returns to WT after the other process closes without input from me.)

I could first make sure nothing else is running or likely to run, but that's boring.

I think I can come up with examples if someone wants to see it happen.

Sometimes I think a solution is some sort of "secure desktop" that could be triggered by a terminal control code, e.g. when prompting for a password, then switch back again once the password is entered.

**Comment by skyline75489** [comment] 2020-12-14 02:13
I think [focus mode](https://docs.microsoft.com/en-us/windows/terminal/customize-settings/actions#toggle-focus-mode) might help but I'm not entirely positive.

**Comment by zadjii-msft** [comment] 2020-12-14 02:44
So like, this isn't just a Terminal problem though, right? Maybe I'm misunderstanding, but to me this sounds like "some times I'm in _an app_, and _another app_ steals focus". Not really specific to the Terminal, but a broader problem in a windowed desktop environment. 

IMO the problem is probably with the other application stealing focus when you're not expecting it. I know VS does this all the time, and it's just the worst, but that's a VS problem. 

I'm not sure there's any way for an app to tell the OS "please don't focus other windows until I tell you okay?" Because immediately, that would get abused by apps that _never_ tell the OS it's okay to start focusing other windows again.

**Comment by KalleOlaviNiemitalo** [comment] 2020-12-14 07:46
SystemParametersInfo SPI_SETFOREGROUNDLOCKTIMEOUT is a bit like that.

**Comment by rodrymbo** [comment] 2020-12-15 18:25
@zadjii-msft 

Exactly right. The same would happen with the old console. 

If I knew how to fix or replace the offending programs I would, or even how to identify them. Sigh.

If I identify Microsoft products that are behaving badly like this, I'll let you know.

**Comment by DHowett** [comment] 2020-12-17 01:12
Thanks for the report. Unfortunately, it's not actionable from our side (I'd like to enable that suppression flag, but I know that that's just entering into an arms race.)

For now, I'm gonna close this out.

**Closed by DHowett** 2020-12-17 01:12 UTC
Labels: Issue-Question, Resolution-Answered
