### ISSUE TITLE
Add Profile shortcuts to taskbar right click menu

### ISSUE THREAD

**Issue by rwilliams** [microsoft/terminal#3787] opened 2019-11-30 16:11 UTC
Add Profile shortcuts to task bar right click menu. When i right click the taskbar icon i am only presented with the option to launch Window Terminal. 

![image](https://user-images.githubusercontent.com/29144/69902967-61f15380-1348-11ea-902e-f02147e8e783.png)

I would be cool if I could right click the menu and get a list of my non-hidden profiles to launch and this would override launching the default profile. Something like this where it has recent sessions but instead lists the profiles.

![image](https://user-images.githubusercontent.com/29144/69902985-a41a9500-1348-11ea-8db2-3e8f22a0e867.png)

**Comment by rafrdz** [comment] 2019-11-30 23:04
👍

**Comment by DHowett-MSFT** [comment] 2019-11-30 23:20
This is a /dupe of #576. Thanks for the request! :smile:

**Closed by DHowett-MSFT** 2019-11-30 23:20 UTC
Labels: Issue-Feature, Needs-Tag-Fix, Needs-Triage
