### ISSUE TITLE
Powershell 6 resizing issues

### ISSUE THREAD

**Issue by sbenalohm** [microsoft/terminal#4100] opened 2020-01-02 22:15 UTC
# Environment

```none
Windows build number: Microsoft Windows 10.0.18363
Windows Terminal version (if applicable): 0.7.3451.0

Any other software?
PowerShell Core 6.2.3
```

# Steps to reproduce
Run PowerShell Core 6.2.3 in Windows Terminal, resize the window in any manner.

# Expected behavior
The terminal prompt and existing printed text will be resized (i.e. line wrapping) and realigned to put the active prompt at the bottom of the window or at the lowest line if there aren't enough history lines to fill up the window.

All profiles other than PS6 (WSL, CMD, original PowerShell, Azure Cloud Terminal) are working fine in this regard, as well as the default PS6 terminal (not running it in Windows Terminal).

# Actual behavior
The text stays in the same place relative to the border dimensions that the terminal/tab was instantiated with.

When the window is enlarged, all visible text remains inside the smaller original borders.  See that in the 2nd image the output of the top command is cut off even though there is empty space below the last prompt line.  Prompt lines will never fill this empty space.
![InitialSizeFull](https://user-images.githubusercontent.com/47365418/71695689-bc2a6d80-2d67-11ea-8d0c-28e68eb3a5c8.jpg)
![FirstResizeCutsOutput](https://user-images.githubusercontent.com/47365418/71695693-bcc30400-2d67-11ea-83d0-96d1edc69aa9.jpg)

 If a new tab is opened once the window is larger, these new dimensions are accurately rendered with the new terminal tab.  See how there is now no empty space below the last prompt.
![FirstResizeNewTabMoreOutputNoScrollbar](https://user-images.githubusercontent.com/47365418/71695688-bb91d700-2d67-11ea-995d-43b3a76e7e63.jpg)

When the window is made smaller, the printed text remains in the larger original borders making the current line (the cursor/new text) not visible as it remains outside the new smaller bounds.  In the first image below I've typed a bogus command into the prompt, but it is not visible as it is a few lines below the bottom of the resized window.  After hitting enter a few times, the 2nd image shows that the command ran, but was not visible in the terminal until enough new lines pushed it up into the view of the resized window.
![SecondResizeUndersizePromptNotVisible](https://user-images.githubusercontent.com/47365418/71695690-bc2a6d80-2d67-11ea-98b0-18f53ea1c5c2.jpg)
![SecondResizeUndersizePromptNotVisibleStartOutput](https://user-images.githubusercontent.com/47365418/71695692-bcc30400-2d67-11ea-8410-e49747331d2d.jpg)

**Comment by DHowett-MSFT** [comment] 2020-01-02 22:26
Thanks for the detailed report! This seems like a /dupe of #1465

**Closed by DHowett-MSFT** 2020-01-02 22:26 UTC
Labels: Needs-Tag-Fix, Needs-Triage
