### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by lcshub** [microsoft/terminal#1610] opened 2019-06-25 16:27 UTC
# Environment

```none
Windows build number: 10.0.18362.175
```

# Steps to reproduce

Even installing Ubuntu and Ubuntu 16LTS, the New Windows terminal does not recognize, does not appear the options to open the them in the tools menu, only appears PowerShell and the old Windows CMD.

# Expected behavior

It is expected that the options of Ubuntu or any other system appear when choosing the terminal.

![Alt Text](https://i.imgur.com/wZstazu.png)

# Actual behavior

The terminals of the systems simply do not appear in the new terminal.

**Comment by Shorotshishir** [comment] 2019-06-25 16:57
Duplicate of #1449
please follow the solution provided. thank you

**Closed** 2019-06-25 18:06 UTC
Labels: Area-Settings, Issue-Question, Product-Terminal, Resolution-Answered, Resolution-Duplicate
