### ISSUE TITLE
Feature request: export console history as txt

### ISSUE THREAD

**Issue by mdtauk** [microsoft/terminal#642] opened 2019-05-09 21:17 UTC
Perhaps this is a right click option within the console itself, or a setting to save and export on exit/closing tab.

But the option to save/export the console output and input into a txt file

**Comment by zadjii-msft** [comment] 2019-05-09 21:22
This is a *good idea*

**Comment by SjoerdNijboer** [comment] 2019-05-10 20:33
There could also be a secondary right click option that only saves the output of the last run command to reduce file size and only capture what is relevant.

**Comment by ChristophePichaud** [comment] 2019-05-25 08:56
Two options:
- save the commands list
- save the last command output

All with a right-click in a popup menu two items choice ? 
I would be happy to implement that features. 
I am looking at the source code to see where to impl it...

**Comment by oising** [comment] 2019-05-28 02:05
@SjoerdNijboer @ChristophePichaud 

The terminal can't distinguish between what a command is, nor what is strictly a result of its execution (its output.) All the terminal "sees" is the keys typed (raw input) and the screen buffer (raw output.) The decision as to what comprises a command can only be performed by the application handling it (cmd, bash, powershell etc.) So ultimately all the terminal can do is to save the output buffer for the current session (tab.)

**Comment by zadjii-msft** [comment] 2019-10-03 13:44
From @19317362 in #3044

> 
> # I've tried WSL2 + docker + Windows Terminal. It's very good for developing.
> 
> It will be better if some features in SecureCRT & ConEmu can be introduced,
> ## Save or redirect the output text in the terminal to some file with this feature
> 
>     1. The format of the filename can be generated like yyyy-mm-dd_HH_MM_SS.log
>        (like SecureCRT).
>        This is very useful while using something like adb logcat etc.
> 
>     2. Can change a new file while day changing.
> 
>     3. File name has session name (just like SecureCRT & ConEmu

**Comment by 19317362** [comment] 2019-10-07 08:18
> Perhaps this is a right click option within the console itself, or a setting to save and export on exit/closing tab.
> 
> But the option to save/export the console output and input into a txt file

Here is the setting of log file related

![CRT_20191007161704](https://user-images.githubusercontent.com/13182253/66295462-f5e10900-e91d-11e9-938c-7d8d8be51680.png)

**Comment by 19317362** [comment] 2019-10-07 08:23
> Perhaps this is a right click option within the console itself, or a setting to save and export on exit/closing tab.
> 
> But the option to save/export the console output and input into a txt file

The menu item to Start/Stop logging in SecueCRT
![CRT_2](https://user-images.githubusercontent.com/13182253/66295815-bf57be00-e91e-11e9-85e2-acba7e58f053.png)

**Comment by 19317362** [comment] 2019-10-07 08:26
The similar feature of ConEmu.
![ConEmu](https://user-images.githubusercontent.com/13182253/66295997-2f664400-e91f-11e9-8b95-ce3094500247.png)

**Comment by yellow-starburst** [comment] 2020-01-18 10:35
Why has this not been pushed out yet as mentioned with conemu or cmder? Terminal would be great once this is fixed :)

**Comment by ChristophePichaud** [comment] 2020-01-23 11:44
I can handle it if you want.
Let me know if you are interested in.
Chris.

**Comment by ChristophePichaud** [comment] 2020-01-23 11:46
I have the ability to develop this feature.
Let me know if you are interested in.

Christophe

**Comment by zadjii-msft** [comment] 2020-01-23 14:26
@ChristophePichaud I think we'd love your contribution 😄 

I think it'd be important to scope the work here, to try and get a handle on what could be accomplished in 1.0 vs 1.1+. IMO, just exporting the current buffer to a text file seems like something that could be accomplished in the 1.0 timeframe pretty reasonably, but more elaborate logging features like ComEmu might be harder to manage. Automatically logging the output to a file is what might require a more fully fledged spec. But I think it wouldn't be terribly hard to add a "Export to file" keybinding, or possibly even an action to the right click menu that's being added in #3789. That hardest part might be the file picker UI tbh 😝 

If you really wanted to work on the more elaborate logging feature too, we'd certainly welcome that, but we'd probably want some sort of [spec](https://github.com/microsoft/terminal/blob/master/doc/specs/spec-template.md) written up first 😉 

As far as implementing the "export to file" action - I'd probably start by copying the Copy keybinding implementation - that's something similar that gets the text content from `TermControl` and attempts to handle it somehow in `TerminalPage`. I'd make the `TermControl` and `Terminal` figure out the string of text to report back as "the whole buffer", and then have `TerminalPage` figure out how to save that string of text. I'm happy to help with any questions you might have along the way

**Comment by ChristophePichaud** [comment] 2020-01-27 20:17
---
author: christophe pichaud christophepichaud/christophepichaud@hotmail.com<mailto:christophepichaud/christophepichaud@hotmail.com>
created on: 2020-01-27
last updated: 2020-01-27
issue id: #642
---

# Save History in a text file

## Abstract

The history of the command should be able to be saved in a text file

## Inspiration

I want that. No inspiration.

## Solution Design


Using the Commands History vector, a combination of CTRL^S can open the common file dialog and save the history of commands in a text file.

It’s easy to do. Next, we could use a dialog to put the setting and the format of the logs.

But first, let’s save as raw text the various commands.

The problem of the setting UI is that it should be in XAML and I am not comfortable with that. But I can do the plumbing.

Let me know.

## UI/UX Design

No XAML UI for the moment. In a second phase may be.

## Capabilities


### Accessibility


### Security

Some password could be (it’s an example) dumped in the text file…

### Reliability


### Compatibility

No problem

### Performance, Power, and Efficiency

none

## Future considerations

A future settings UI in XAML for dedicated format of the logging

## Resources

none

**Comment by ChristophePichaud** [comment] 2020-01-27 20:18
Here is a small spec (md file).

## Solution Design


Using the Commands History vector, a combination of CTRL^S can open the common file dialog and save the history of commands in a text file.

It’s easy to do. Next, we could use a dialog to put the setting and the format of the logs.

But first, let’s save as raw text the various commands.

The problem of the setting UI is that it should be in XAML and I am not comfortable with that. But I can do the plumbing.

Let me know.

**Comment by ChristophePichaud** [comment] 2020-01-28 02:34
It could be something like this:
InteractivityWin32 - WindowsIO.cpp

        if (VirtualKeyCode == VK_F10 &&
            bKeyDown &&
            inputKeyInfo.HasNoModifiers() &&
            ShouldTakeOverKeyboardShortcuts())
        {
            auto& cookedReadData = ServiceLocator::LocateGlobals().getConsoleInformation().CookedReadData();
            auto history = cookedReadData.History();
            size_t commandCount = history->GetNumberOfCommands();
            std::wstring all_command;
            for (SHORT i = 0; i < commandCount; ++i)
            {
                std::wstring_view str = history->GetNth(i);
                all_command += str;
                all_command += std::wstring(L"\r\n");
            }
            ::MessageBox(NULL, all_command.c_str(), NULL, MB_OK);
            // replace MsgBox by file i/o writefile and hop its done with the date_time.log
            // then later, provide an UI for cutsom stuff logging format
            return;
        }

**Comment by ChristophePichaud** [comment] 2020-01-28 03:47
There is also another solution... Log every time we have a new command:

        if (FoundCR)
        {
            if (_commandHistory)
            {
                // add to command line recall list if we have a history list.
                CONSOLE_INFORMATION& gci = ServiceLocator::LocateGlobals().getConsoleInformation();
                LOG_IF_FAILED(_commandHistory->Add({ _backupLimit, StringLength / sizeof(wchar_t) },
                                                   WI_IsFlagSet(gci.Flags, CONSOLE_HISTORY_NODUP)));

                // It's dirty but it works
                std::wofstream ofs(L"c:\\temp\\log.txt", std::ios_base::app);
                wchar_t buffer[1024];
                wcsncpy_s(buffer, _backupLimit, StringLength);
                buffer[StringLength] = 0;
                ofs << buffer << std::endl;
                ofs.close();
            }

            // check for alias
            ProcessAliases(LineCount);
        }
    }

**Comment by zadjii-msft** [comment] 2020-01-28 14:02
Ah so there might be a bit of a miscommunication here - I think we're each thinking of a different thing as the "console history". 

I'm thinking of the entirety of the output that's been emitted to the console. So for a console that looks like:
![image](https://user-images.githubusercontent.com/18356694/73269590-baa36800-41a2-11ea-9191-baadbf966b71.png)

I'm thinking of the entire text:
```
Microsoft Windows [Version 10.0.19552.1001]
(c) 2020 Microsoft Corporation. All rights reserved.

[ 7:48:55.94]>C:\Users\migrie>
migrie@MIGRIE-SLAPTOP>echo "Foo"
"Foo"

[ 7:49:01.24]>C:\Users\migrie>
migrie@MIGRIE-SLAPTOP>dir | $ grep foo
01/27/2020  02:32 PM                 8 #foo#
09/03/2019  09:52 AM                 8 foo
11/14/2019  11:59 AM                12 foo.txt

[ 7:49:12.43]>C:\Users\migrie>
migrie@MIGRIE-SLAPTOP>
```

It sounds to me like you want _just the command history_. So in the above case, it would be just the following:
```
echo "Foo"
dir | $ grep foo
```

I think there might be some challenges in saving just the second one. Windows Terminal is fundamentally just a _terminal emulator_, it doesn't really know what's going on behind the scenes with whatever client application (`cmd`, `powershell`, `bash`, `vim`) that is connected to it. WT doesn't know when the user is typing in commands to the shell, or if the user is just typing in text in `emacs` or something. There's no way for the terminal to know that. It's _typically_ the client application's responsibility to save it's own command history. `bash` and `powershell` bot do a pretty good job of saving this to another file to restore across sessions, while `cmd.exe` doesn't.

Of course, Windows is a messy world and this model gets a little tricky here. `cmd.exe` isn't actually managing it's own command history _at all_ - as you've noticed, `conhost` is doing that work on behalf of the client applications. Some long time ago someone thought it would be a good idea to have the `readline` functionality baked directly into the console host. Whether that was a good idea or not remains to be seen - it's certainly made things like `python.exe`'s REPL easier to implement, since they don't need to maintain their own history buffer, but it makes it hard to de-tangle behavior like this from the console itself. 

I'm not sure how it would be possible to add a keybinding to the Windows Terminal that would be able to save the console's _command_ history. Especially considering the Terminal might _not_ be connected to a console host session at all. If the Windows Terminal were directly running a `wsl` instance (something that's not possible today, but something we've considered adding in the future), then there wouldn't be a `conhost` in the process tree at all, and now requesting the command history from the console wouldn't work _mysteriously_. 

I still think that writing the _entire buffer history_ to a file is something that's _very_ possible, since that's something that's entirely known by the Terminal.

**Comment by eryksun** [comment] 2020-01-31 16:56
> it's certainly made things like `python.exe`'s REPL easier to implement, since they don't need to maintain their own history buffer, but it makes it hard to de-tangle behavior like this from the console itself.

It's easy, but it makes the Windows implementation of Python the odd man out. Without support for Python's readline extension module, it can't use the REPL's ".python_history" file. There's a third-party pyreadline package, but it's poorly maintained and based on a ctypes FFI wrapper for the console API. 

For saving just the input command history (as opposed to the entire session history of the terminal), it's better to use a Readline library that supports the Windows console. In that regard what I'd really want is for Microsoft to provide a C API for Readline support in console applications. It could support Windows, Emacs, and Vi modies, like PSReadLine in PowerShell.

Barring rewriting a console app to support readline (a la PowerShell), the console API could at least provide a more complete and documented implementation of its command history. It could document the functions for reading and clearing the session command history (i.e. `GetConsoleCommandHistoryLengthW`, `GetConsoleCommandHistoryW`, and `ExpungeConsoleCommandHistoryW`), which doskey.exe has used for almost 30 years. Plus extend the API with the ability to overwrite the command history -- e.g. `SetConsoleCommandHistoryW(lpCommands, dwLength, lpExename)`.

**Comment by jamesbtate** [comment] 2020-06-09 12:19
Has anyone taken on this feature request? Is there anything someone new to the project with no C++ experience can do to help it along?

My use case is mainly system administration with the ability to look back at commands and output from hours/days/weeks ago.

**Comment by buscseik** [comment] 2020-07-04 07:09
Also, time stamping each logged line in log file would be a very usueful option

**Comment by brettus78** [comment] 2020-07-08 01:55
Would be very useful to have sessions always and continuously log - with options for different files per session or per profile list item with the custom options of append, overwrite, new file (with some options for formatting with date/time/profile list item name, etc.), and an ability to not log certain sessions - so per profile list item would swell. Maybe option to start a new file each time the sesssion opens
Something like PuTTY/MobaXTerm/TeraTerm. 

```
{
    "guid": "{b453ae62-4e3d-5e58-b989-0a998ec441b8}",
    "hidden": false,
    "name": "Azure Cloud Shell",
    "source": "Windows.Terminal.Azure",
    "logfile_location":"C:\\Users\\myuser\\logs\\",
    "logfile_format":"%name%_%date%_%time%.log",
    "logfile_type":"new_file"/"append_existing"/"etc.",
}
```

**Comment by Mayhem93** [comment] 2020-09-16 19:16
I think what most people want is to save the whole console's buffer into a file, I've came across this issue while googling if such a thing is possible.

So here's my 👍 for this feature. Instead of having right-click do the paste action we could have a context menu where this paste action and "save terminal output" options would be available (not to mention, the menu can be expanded easily). Other option is to have this request feature as an option in the context menu of the tab (when right-clicking)

**Comment by rmutchler** [comment] 2020-10-02 19:59
Leaving my vote on here for this feature too.  I use this with PuTTY and MobaXterm to automatically log every session to a new file.  It is useful when I configure a SAN or switch.  I can save the files if there is a dispute on the work performed or go back and review if there is an issue during a session.

**Comment by chadministratorwastaken** [comment] 2020-12-17 06:08
This is the only feature keeping me from switching to WT.  Literally the only one.
Just sayin'
It's the only one.
Just. one.

**Comment by ChristophePichaud** [comment] 2020-12-17 06:34
It is decided, I run into the study to implement a decent contrition for implementing thios feature.
@zadjii-msft Do you agree to give me green light ?
I can do it in less than 1 month or 6 weeks maximum. UI ahve already studied it before....
Regards, Christophe | www.windowscpp.com

**Comment by zadjii-msft** [comment] 2020-12-17 13:08
Sure, go right ahead. I think starting with just an action to export the current buffer contents to a file would be a good enough place to start. We can work on building things like auto-logging to a file, or hooking that action up to the tab context menu, etc. after that.

Also as a heads up, it is about to be the holidays here, so we might not be super responsive until the new year, but I'll try answering any questions you might have. Looking forward to the PR!

**Comment by alainza** [comment] 2020-12-18 16:05
Right click inside the console window might be assigned to "Paste" like in cmd's window: why not add the "Save" command to the popup menu on the tab header ?

**Comment by ChristophePichaud** [comment] 2020-12-19 06:12
I tell you all that this feature will be done by me and my young Infeeny Expert Kevin ANSARD, a student working with me. See our blog at blog.infeeny.com... Consulting Services. .NET and Azure... Microsoft ecosystem of Partners. See www.Infeeny.com. 
We are in Paris, France.

**Comment by chadministratorwastaken** [comment] 2021-01-07 18:20
@ChristophePichaud @zadjii-msft I would be very happy to test this new feature when it is available.  Thank you very much for working on it!

**Comment by fischerdouglas** [comment] 2021-01-22 12:24
This is a Mus-Have!
For those who work with IT support, this is a powerful shield against unfair complaints of errors on the operations of systems.

And what is needed is the FULL TEXT of the session, in live mode... Including backspaces and retyping.

And is needed ALSO for the remote sessions like remote Powershell, or remote ssh/telnet.

**Comment by ChristophePichaud** [comment] 2021-01-22 13:26
Hello Douglas,

Keep calm 😳😎, I implement it on cmd, then we discuss and then, we do a UI for settings and next, last but not last, we do it also for PowerShell and bash....
Every command prompt has a low level filter and a common one for all.
It's not so easy it is supposed to be.
I release on next Friday, the 29 January for testing.

Chris

Get Outlook for Android<https://aka.ms/ghei36>

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by zadjii-msft** [comment] 2021-01-22 17:17
Hey I just wanted to make sure there wasn't a miscommunication here - how exactly are you going about doing this?

IMO, there's probably 4 steps to this PR:
1. Create a new Action that can be bound by the user in `TerminalApp`/`Terminal.Settings.Model`, that will call some function in `TermControl`. #8522 is a good example of a PR that wires up all the things you'd need for the action, and calls down to the active control. The `Copy` action might be another good example, since that gets some text from the control, and returns it up to the app layer.
2. In the function added to `TermControl` query the buffer for all the lines of text. I believe `TextBuffer` exposes a way to get all the text from a row - should just be a matter of iterating over the entire contents of the buffer. 
3. Return those buffer contents up to the `TerminalApp` layer. 
4. In `TerminalApp`, open up a file picker dialog to chose a file to write those contents to. 

At that point, the user should be able to execute the "exportHistory" action (either with a keybinding or the command palette), and be prompted with a file picker, which should let them write the buffer contents to a file. We can work on other settings like auto logging, or logging keystrokes, etc. in the future, but this should be good enough for the 90% use case for now. 

I don't _think_ this needs to do anything different depending on which shell the user's interacting with, so that gives me pause...

**Comment by ChristophePichaud** [comment] 2021-01-22 22:25
Ok I understand. No problem about the issue.

Chris.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by chadministratorwastaken** [comment] 2021-01-22 22:46
@zadjii-msft @ChristophePichaud The way I read the request was that automatic logging was a key part of this feature. Manually exporting the history via the command palette is no more easier than manually copying and pasting the text myself. Automatic logging is critical to my use case since I know it captures everything, even if I forget to export, and is not affected by any limitations of printed history.

If a comparison is helpful, I currently use the logging feature in PuTTY, which is the functionality I hope to see in wt.

**Comment by zadjii-msft** [comment] 2021-01-25 13:39
See, I'm very much a "steady, small incremental improvement" kinda person. I'd much rather work on what I've laid out first, then do keystrokes too, then add auto-logging, rather than try to accomplish all three at once and have it land sometime on the other side of _never_. Doing this first little bit will make the other parts easier in the future. 

One step at a time 😄

**Comment by chadministratorwastaken** [comment] 2021-01-25 13:41
Fair enough.  I'm just glad there's movement!  Thanks again for your attention to this :)

**Comment by fischerdouglas** [comment] 2021-01-25 21:53
I didn't understand the complexity behind the scenes...
But I'm not a developer, so I even try to do it(srsrs).

But to be clear, I don't believe that any type of treatment should be done to the text.
Nothing like splitting what is a command and what is an output of the commando...

Simple real-time piping of all the characters presented on the screen > $LogFile

And when I say Real-time, I do not care about being pretty on the output file...

For example, if you look to and output a file of a session where the "htop" was used, it will be craziness... With characters been rewritten every second...
No issues with that! That's exactly what I need.
Including writing and backspacing characters...

Exactly as it happens on iTerm2 or even on SecureCRT as mentioned by our colleague earlier.

> > Perhaps this is a right click option within the console itself, or a setting to save and export on exit/closing tab.
> > But the option to save/export the console output and input into a txt file
> 
> This is a snap from SecueCRT. It's very useful for everything.
> 
> ![CRT_20191007161704](https://user-images.githubusercontent.com/13182253/66295462-f5e10900-e91d-11e9-938c-7d8d8be51680.png)

**Comment by ChristophePichaud** [comment] 2021-02-03 02:53
OK, it seems pretty cool locally OK. 
I have worked disconnected since 3 weeks and I have most of the feature that seemz working.
I write "mosté and "seems" because it's not so easy it's look from the outside of the c++ code...
I need to do some additionnal quality and checks before releasing the code online in the PR and doing the code review step check.
Let me some hours/few days before completing the job. 
I go online and I ask you for review but I think it's good.

Christophe

**Comment by WSLUser** [comment] 2021-02-08 14:48
So I should mention that the built-in Hyperterminal from XP had this feature. See this old article from Cisco on how it worked: https://www.cisco.com/c/en/us/support/docs/routers/2500-series-routers/17521-capture-text-hyperterminal.html. When I was still administering network devices, this was such a useful tool. I'm sure the source code still exists somewhere in the Windows repository  and could be ported/refactored/modernized to work in conhost and/or Windows Terminal at least.

**Comment by miniksa** [comment] 2021-02-08 17:05
> So I should mention that the built-in Hyperterminal from XP had this feature. See this old article from Cisco on how it worked: [cisco.com/c/en/us/support/docs/routers/2500-series-routers/17521-capture-text-hyperterminal.html](https://www.cisco.com/c/en/us/support/docs/routers/2500-series-routers/17521-capture-text-hyperterminal.html). When I was still administering network devices, this was such a useful tool. I'm sure the source code still exists somewhere in the Windows repository and could be ported/refactored/modernized to work in conhost and/or Windows Terminal at least.

I'm 95% sure that HyperTerminal was a product that Microsoft licensed to include in previous editions of Windows, not something that is built out of the Windows repository with source code. Kinda like the 3D Pinball thing.

Having a source code example isn't really what's stopping us from getting this done anyway. It's just time, priority, and resources. (And pandemic fatigue.)

**Comment by WSLUser** [comment] 2021-02-08 18:31
I did see something that made me wonder if that was the case. Still, by now that license should of expired. I haven't seen it used outside of older Windows so it ought to be able to be acquired by Microsoft and/or OSSed. I just would love to see this feature pop up even on conhost appearing similar to how it does in HyperTerminal (because nolstagia and it's conhost). I of course would expect something more prettified for Windows Terminal due to a different UI framework being used.

**Comment by ChristophePichaud** [comment] 2021-02-12 05:59
I have a question for you @zadjii-msft ... I was releasing my code from offline to connected GitHub and I realized that when I was reading one of your last comment that I made it the wrong way.
Let me explain:
- I was dealiong with the CMD command prompt and I was handling string buffer from InteractivityWin32 - WindowsIO.cpp and host - readDataCooked.cpp line 1000 in _handlePostCharInputLoop...
=> THE Problem is that is only handling CMD.
Your last coments told me to handle the string buffer from the XAML Main Window, correct ?
handling events from XAML Foundation Windows stuff ? Correct ???
Christophe

-
-
<<
ChristophePichaud commented on Jan 28, 2020
It could be something like this:
InteractivityWin32 - WindowsIO.cpp

    if (VirtualKeyCode == VK_F10 &&
        bKeyDown &&
        inputKeyInfo.HasNoModifiers() &&
        ShouldTakeOverKeyboardShortcuts())
    {
        auto& cookedReadData = ServiceLocator::LocateGlobals().getConsoleInformation().CookedReadData();
        auto history = cookedReadData.History();
        size_t commandCount = history->GetNumberOfCommands();
        std::wstring all_command;
        for (SHORT i = 0; i < commandCount; ++i)
        {
            std::wstring_view str = history->GetNth(i);
            all_command += str;
            all_command += std::wstring(L"\r\n");
        }
        ::MessageBox(NULL, all_command.c_str(), NULL, MB_OK);
        // replace MsgBox by file i/o writefile and hop its done with the date_time.log
        // then later, provide an UI for cutsom stuff logging format
        return;
    }

AND 
 
ChristophePichaud commented on Jan 28, 2020 • 
There is also another solution... Log every time we have a new command:
host - readDataCooked.cpp line 1000 in _handlePostCharInputLoop()

    if (FoundCR)
    {
        if (_commandHistory)
        {
            // add to command line recall list if we have a history list.
            CONSOLE_INFORMATION& gci = ServiceLocator::LocateGlobals().getConsoleInformation();
            LOG_IF_FAILED(_commandHistory->Add({ _backupLimit, StringLength / sizeof(wchar_t) },
                                               WI_IsFlagSet(gci.Flags, CONSOLE_HISTORY_NODUP)));

            // It's dirty but it works
            wchar_t tempPath[MAX_PATH];
            DWORD dwPath = MAX_PATH;
            ::GetTempPath(dwPath, tempPath);

            std::wstring wpath = tempPath + std::wstring(L"WindowsTerminal.log");

            std::wstring_view buffer(_backupLimit, StringLength / sizeof(wchar_t));
            std::wofstream ofs(wpath, std::ios_base::app);
            ofs << buffer << std::endl;
            ofs.close();
        }

        // check for alias
        ProcessAliases(LineCount);
    }
>>

**Comment by zadjii-msft** [comment] 2021-02-12 11:59
@ChristophePichaud Yea, don't mess with _any_ of that. `readData`, interactivity, `WindowsIO` - all that's conhost-specific code. We don't care about adding this to conhost right now (and that's certainly much harder). We're not trying to log each individual _command_ as they come in, because that's not as useful, and doesn't work for powershell, bash, etc. 

It's more useful, and easier to start with, just writing the _entire_ buffer contents to a file. I think this can be done in just the Terminal, in TerminalControl, TerminalApp and TerminalSettingsModel. That's where we're generally adding new UX features.

**Comment by ChristophePichaud** [comment] 2021-02-12 12:09
Yes, thanks for you support.
I have deep dived in TermApp and TermControl 7 days ago and I saw the IDL and winrt/cpp generated code stuff in CPP files.
I looked at some Winrt samples to catch the "Copy" Command. I can't see the light. Can't realize how to declare this kind of Foundation events methods IDL winrt stuff in the code.
I have the code sniper for getting the buffer.
I have got the code for appending the buffer into the rolling daily log file using log4cpp...
But the XAML UI handling with Foundation hurt me.

I search but would be really appreciated to see where to declare the WinUI plumbing to handle this mouse handlers...

@Alain Zanchetta<mailto:alainza@hotmail.com>, you can give me an advice ???

Regards to all..
Chris

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by zadjii-msft** [comment] 2021-02-12 12:22
@ChristophePichaud Try taking a look at #8917. That's a PR that has a good example of plumbing an action from TerminalApp down into the TermControl.

**Comment by alainza** [comment] 2021-02-12 14:32
@ChristophePichaud You don't need to change idl.

Just register your code in `void TerminalTab::_CreateContextMenu() `in https://github.com/microsoft/terminal/blob/main/src/cascadia/TerminalApp/TerminalTab.cpp

i.e. right click in the body of the tab is already used for "paste" => don't mess up with this
right click on a tab header is where you already have a menu and adding "save tab content as text" would make sense.
This is done in `void TerminalTab::_CreateContextMenu()`

**Comment by ChristophePichaud** [comment] 2021-02-12 15:54
Thank Alain. I try this asap.
Damn XAML Foundation stuff.....
I hope God bless Frogs. 😳😘😎
Chris, from Paris,  France.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by ChristophePichaud** [comment] 2021-02-12 15:55
Thanks Mike.
I will go into this.
I can do it.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by chadministratorwastaken** [comment] 2021-03-17 13:14
Are there any updates on this?  Is there anything I can do to assist?

**Comment by ChristophePichaud** [comment] 2021-03-17 15:05
Hello,

I am busy on track.
It was hard to find the plumbing _CreateCOntext from my friend Alain Zanchetta.
It’s still under development on local branch.
I may be still be busy this coming days few hours but I’am near the end.
The XAML was a problem for me.
Do you want to fix a final deadline to be on track ?

Christophe

De : chadministratorwastaken ***@***.***>
Envoyé : Wednesday, March 17, 2021 2:15 PM
À : microsoft/terminal ***@***.***>
Cc : Christophe Pichaud ***@***.***>; Mention ***@***.***>
Objet : Re: [microsoft/terminal] Feature request: export console history as txt (#642)


Are there any updates on this? Is there anything I can do to assist?

**Comment by jonascollen** [comment] 2021-05-19 14:01
Hi, any updates regarding this?

**Comment by zadjii-msft** [comment] 2021-05-19 14:22
Nope. We'll make sure to update this thread when there is. In the meantime, might I recommend the Subscribe button?
![image](https://user-images.githubusercontent.com/18356694/91237459-5cbb0c80-e700-11ea-9347-b9b1ec2813b1.png)
That way you'll be notified of any updates to this thread, without needlessly pinging everyone on this thread ☺️

**Comment by kczx3** [comment] 2021-05-24 20:01
This would be very useful as I work in some apps that produce a lot of output and I can't always direct it to a file on the remote server to then grab via SCP.  So being able to start terminal output logging, run a command, and then view that output locally is immensely helpful (and quicker).

**Comment by konarx** [comment] 2021-06-10 07:02
+1 about the importance and needing of this feature

**Comment by chadministratorwastaken** [comment] 2021-07-19 20:02
Has this request been reduced in priority?  It's been four months since we've heard from the last person to agree to take it on.

**Comment by zadjii-msft** [comment] 2021-07-19 20:06
FWIW @ChristophePichaud is an external contributor - it's entirely reasonable that _life happened_ and they never got around to finishing this.

**Comment by fischerdouglas** [comment] 2021-09-01 12:15
First-> I need to say that I'm pretty happy seem some movements ( #11090 ) to solve this demand...

And I Agree with @Don-Vito and @buscseik when they say that "exporting is not the same as logging".
But I also need to reinforce that both are needed...

Just to exemplify, in some tools(like iTerm2) real time logging means that if you type "wrod" and press backspace 3 times end write "ord", is exactly those 10 chars that will be at the log.
And on export you will see only "word"...

This may sound silly, but just with that level of logging will be possible to have registered "CTRL+C" or "CTRL+A" sent to remote terminals...

Another side effect of logging (this one is annoying) is when you access CLI apps that draw on screen and refresh every second. Most apps done with ncurses on linux do that... Examples of what I'm saying are "top" "sngrep" on linux, or the old "edit" from msdos.
When you see that on the log file, it looks a mess... But is an acceptable downside of being safe and having the logs of what you did on some one else server or equipment.

**Comment by zadjii-msft** [comment] 2021-09-01 12:30
Just to be clear - no one thinks that exporting and logging are the same thing. This is just a nice stepping stone towards full logging. I encourage anyone with thoughts on the matter to go check out #11090.

**Comment by oising** [comment] 2021-09-01 18:41
Blergh... this is gonna be fun. Personally I believe that exporting is fine, but logging responsibility belongs to the shell, not the terminal. Do I really want to know if someone typo'd 67 times before successfully executing `sudo rm -Rf /` ? Maybe if I was Sherlock Holmes and wanted hints about the perpetrator... ;)

**Comment by BEEDELLROKEJULIANLOCKHART** [comment] 2021-09-06 21:34
This has been a feature of http://github.com/kde/konsole since many years before now, and is equally important as it is basic, so this should be added soon.

**Comment by zadjii-msft** [comment] 2021-09-06 21:54
> so this should be added soon.


Well great news, #11062 was just merged last week!

**Comment by BEEDELLROKEJULIANLOCKHART** [comment] 2021-09-07 18:12
> http://github.com/microsoft/terminal/issues/642#issuecomment-913865402

Thus, [this issue](http://github.com/microsoft/terminal/issues/642) probably should be closed.

**Comment by zadjii-msft** [comment] 2021-09-07 20:20
In retrospect, this should have been kept two separate issues - one for export, and one for logging. But, we ended up merging a bunch of threads into this one, and now it's all confusing. 

Yea, I think we can close this one with #11062, and track the remaining logging work over in #9700. That's roughly the same process we've done with other features like this.

**Comment by starhound** [comment] 2021-09-09 02:45
As a software dev trying to switch to using Windows Terminal completely, I require full terminal logging for some activities. 

I know this feature request was for command history, but this would be a much more effective tool for my team should it have complete logging features.

Other than the lack of said feature above, this terminal has been one of the best I've ever had to interact with.

**Closed** 2021-09-09 12:50 UTC
Labels: Issue-Feature, Resolution-Fix-Committed, Help Wanted, Area-User Interface, Product-Terminal, Easy Starter
