### ISSUE TITLE
Window size should snap to a multiple of font width/height

### ISSUE THREAD

**Issue by randomascii** [microsoft/terminal#4918] opened 2020-03-14 04:05 UTC
The window size should snap to a multiple of the font width/height

I find it annoying and aesthetically displeasing when the cmd.exe window is not a multiple of the font height, leaving black pixels at the bottom. The new terminal is a chance to fix this issue by clamping the window sizes to multiples of the font size. Right now the behavior is arguably worse because not only is no clamping to logical sizes done, there is also a significant border between the text and the window edge, wasting even more space.

# Proposed technical implementation details (optional)

The message handler for WM_SIZE can detect and reject invalid sizes either during live dragging or after dragging finishes so that the window is always a good size.

**Comment by DHowett-MSFT** [comment] 2020-03-14 05:31
So! I’ve got good news on this one.

1. We shipped grid snapping resize in 0.9, off by default, behind a setting named `snapToGridOnResize` (PR #3181).
   * It’ll be on by default in 0.10 (Issue #4349)

2. You can configure the `padding` of any profile; you can even set it to `0` if you’re concerned about us wasting space. 

Since we’ve already got this covered, I’m going to call this one a /dupe of #4349 (the issue for turning snapping on by default) since that’ll have the desired behavior.

**Closed by DHowett-MSFT** 2020-03-14 05:31 UTC
Labels: Issue-Feature, Needs-Tag-Fix, Needs-Triage
