### ISSUE TITLE
Add option for semi-transparent cursor, like in most other terminals

### ISSUE THREAD

**Issue by schffp** [microsoft/terminal#3500] opened 2019-11-09 12:02 UTC
# Description of the new feature/enhancement

As far as I can see, there is no option to make the cursor see through, like in Mintty, for example. There is the "emptyBox" cursor shape, but that one feels very unfamiliar when editing text.

# Proposed technical implementation details (optional)

Either allow rgba (like in css) in "cursorColor" or add a "cursorOpacity" option.

**Comment by j4james** [comment] 2019-11-09 21:00
This sounds like a duplicate of #1203.

**Closed** 2019-11-11 20:48 UTC
Labels: Issue-Feature, Needs-Tag-Fix, Needs-Triage
