### ISSUE TITLE
Terminal not responding after switching users/resuming from sleep

### ISSUE THREAD

**Issue by echo6ix** [microsoft/terminal#14483] opened 2022-12-02 17:18 UTC
### Windows Terminal version

1.15.2875.0

### Windows build number

10.0.22621.819

### Other Software

ssh
wsl

### Steps to reproduce

Start terminal
ssh into any location
Switch to a different user account on Windows
Switch back to the original user account

### Expected Behavior

Terminal app will be responsive

### Actual Behavior

The terminal app is unresponsive and hangs

**Comment by zadjii-msft** [comment] 2022-12-02 20:48
When the Terminal is frozen like this, could you grab a dump with Task Manager and send it to us/? 

![image](https://user-images.githubusercontent.com/18356694/135876584-e48514d6-26c0-49da-ae28-b8c5d66dc2a3.png)

I'm guessing this is a dupe of (one of the many other variations on this recently (esp #14134)), but the only way to be sure is with a stack trace.

**Comment by echo6ix** [comment] 2022-12-02 23:19
> When the Terminal is frozen like this, could you grab a dump with Task Manager and send it to us/?

@zadjii-msft https://drive.google.com/file/d/1JbpZRc3RqaweISMuLeTHPKVgDd7l66wq/view?usp=share_link

**Comment by lhecker** [comment] 2022-12-05 22:04
The dump only shows 2 threads. The main thread is stuck here:
```
0:000> kc
 # Call Site
00 win32u!ZwGdiDdDDIEscape
01 d3d11!CallAndLogImpl<long (__cdecl*)(_D3DKMT_ESCAPE const *),_D3DKMT_ESCAPE *>
02 d3d11!CallAndLog
03 d3d11!NDXGI::CDevice::EscapeCB
04 atiuxp64!OpenAdapter10_2
05 atiuxp64!OpenAdapter10_2
06 atiuxp64!OpenAdapter10_2
07 d3d11!CResource<ID3D11Texture2D1>::CLS::FinalRelease
08 d3d11!TCLSWrappers<CTexture2D>::CLSDestroy
09 d3d11!CCLSFinalReleaseSentinel<CContext>::{dtor}
0a d3d11!CLayeredObjectWithCLS<CTexture2D>::{dtor}
0b d3d11!CLayeredObjectWithCLS<CTexture2D>::Release
0c d3d11!ATL::AtlComPtrAssign
0d d3d11!ATL::CComPtr<ID3D11LayeredUseCounted>::operator=
0e d3d11!CD3D11LayeredChild<ID3D11DeviceChild,NDXGI::CDevice,64>::FinalRelease
0f d3d11!NDXGI::CDeviceChild<IDXGIResource1,IDXGISwapChainInternal>::FinalRelease
10 d3d11!NDXGI::CResource::FinalRelease
11 d3d11!CLayeredObject<NDXGI::CResource>::{dtor}
12 d3d11!CLayeredObject<NDXGI::CResource>::Release
13 d3d11!ATL::AtlComPtrAssign
14 d3d11!ATL::CComPtr<ID3D11LayeredUseCounted>::operator=
15 d3d11!NOutermost::CDeviceChild::FinalRelease
16 d3d11!CDelegatingUseCountedObject<NOutermost::CDeviceChild>::FinalRelease
17 d3d11!CDelegatingUseCountedObject<NOutermost::CDeviceChild>::~CDelegatingUseCountedObject<NOutermost::CDeviceChild>
18 d3d11!CDelegatingUseCountedObject<NOutermost::CDeviceChild>::`scalar deleting destructor'
19 d3d11!CDelegatingUseCountedObject<NOutermost::CDeviceChild>::Delete
1a d3d11!CDelegatingUseCountedObject<NOutermost::CDeviceChild>::UCDestroy
1b dxgi!CDXGISwapChain::DestroyOwnedBuffer
1c dxgi!CDXGISwapChain::DestroyBackBuffers
1d dxgi!CDXGISwapChain::FinalRelease
1e dxgi!CDXGISwapChainApplicationClass::FinalRelease
1f dxgi!CMTUseCountedObject<CDXGISwapChainApplicationClass>::FinalRelease
20 dxgi!CMTUseCountedObject<CDXGISwapChainApplicationClass>::~CMTUseCountedObject<CDXGISwapChainApplicationClass>
21 dxgi!CMTUseCountedObject<CDXGISwapChainApplicationClass>::`scalar deleting destructor'
22 dxgi!CMTUseCountedObject<CDXGISwapChainApplicationClass>::Delete
23 dxgi!CMTUseCountedObject<CDXGISwapChainApplicationClass>::UCReleaseUse
24 d3d11!CDelegatingUseCountedObject<NOutermost::CDeviceChild>::UCReleaseUse
25 d3d11!CLockOwnerChild<CDevice,0>::UCReleaseUse
26 d3d11!CView<ID3D11RenderTargetView1>::{dtor}
27 d3d11!CRenderTargetView::{dtor}
28 d3d11!CLayeredObjectWithCLS<CRenderTargetView>::{dtor}
29 d3d11!CLayeredObjectWithCLS<CRenderTargetView>::Release
2a d3d11!ATL::AtlComPtrAssign
2b d3d11!ATL::CComPtr<ID3D11LayeredUseCounted>::operator=
2c d3d11!NOutermost::CDeviceChild::FinalRelease
2d d3d11!CUseCountedObject<NOutermost::CDeviceChild>::FinalRelease
2e d3d11!CUseCountedObject<NOutermost::CDeviceChild>::{dtor}
2f d3d11!CUseCountedObject<NOutermost::CDeviceChild>::`scalar deleting destructor'
30 d3d11!CUseCountedObject<NOutermost::CDeviceChild>::Delete
31 d3d11!CUseCountedObject<NOutermost::CDeviceChild>::UCDestroy
32 d3d11!NOutermost::CDevice::FlushDeletionPool
33 d3d11!CContext::PerformAmortizedRenderOperations
34 d3d11!TOptImmediateContext::AcquireDevCtxIfaceNoSync
35 d3d11!CContext::AcquireDevCtxIfaceNoSync
36 d3d11!CDevCtxInterface::CDevCtxInterface<CContext>
37 d3d11!CContext::TID3D11DeviceContext_OMSetRenderTargets_Amortized<1>
38 Microsoft_Terminal_Control!DllGetActivationFactory
39 Microsoft_Terminal_Control
3a Microsoft_Terminal_Control
3b Microsoft_Terminal_Control!DllCanUnloadNow
3c Microsoft_Terminal_Control!DllCanUnloadNow
3d Microsoft_Terminal_Control!DllGetActivationFactory
3e Microsoft_Terminal_Control!DllCanUnloadNow
3f Microsoft_Terminal_Control!DllCanUnloadNow
40 Microsoft_Terminal_Control!DllCanUnloadNow
41 Microsoft_Terminal_Control!DllCanUnloadNow
42 Microsoft_Terminal_Control!DllCanUnloadNow
43 Microsoft_Terminal_Control!DllGetActivationFactory
44 Windows_UI_Xaml!ctl::ComPtr<DirectUI::DependencyObject>::InternalRelease
45 Windows_UI_Xaml!ctl::ComPtr<DirectUI::DependencyObject>::{dtor}
46 Windows_UI_Xaml!TryUnpegManagedPeer
47 Windows_UI_Xaml!CDependencyObject::UnpegManagedPeer
48 Windows_UI_Xaml!CRoutedEventArgs::{dtor}
49 Windows_UI_Xaml!CRoutedEventArgs::`scalar deleting destructor'
4a Windows_UI_Xaml!CEventArgs::Release
4b Windows_UI_Xaml!xref_ptr<CEventArgs>::DecrementRefCount
4c Windows_UI_Xaml!xref_ptr<CEventArgs>::{dtor}
4d Windows_UI_Xaml!CEventInfo::{dtor}
4e Windows_UI_Xaml!CXcpDispatcher::OnScriptCallback
4f Windows_UI_Xaml!CXcpDispatcher::OnWindowMessage
50 Windows_UI_Xaml!CXcpDispatcher::ProcessMessage
51 Windows_UI_Xaml!CXcpDispatcher::WindowProc
52 Windows_UI_Xaml!CDeferredInvoke::DispatchQueuedMessage
53 Windows_UI_Xaml!CXcpDispatcher::MessageTimerCallback
54 Windows_UI_Xaml!CXcpDispatcher::MessageTimerCallbackStatic
55 CoreMessaging!Microsoft::CoreUI::Dispatch::TimeoutHandler::ImportAdapter$::__l2::<lambda_654db17c35df07198786f0867aa10de6>::operator()
56 CoreMessaging!CFlat::SehSafe::Execute<<lambda_654db17c35df07198786f0867aa10de6> >
57 CoreMessaging!Microsoft::CoreUI::Dispatch::TimeoutHandler::ImportAdapter$
58 CoreMessaging!CFlat::DelegateImpl<Microsoft::CoreUI::Dispatch::TimeoutHandler,0,void __cdecl(void),long __cdecl(void *),0>::Invoke
59 CoreMessaging!Microsoft::CoreUI::Dispatch::Timeout::CallHandler
5a CoreMessaging!Microsoft::CoreUI::Dispatch::TimeoutManager::Callback_OnDispatch
5b CoreMessaging!Microsoft::CoreUI::Dispatch::Dispatcher::Callback_DispatchNextItem
5c CoreMessaging!Microsoft::CoreUI::Dispatch::Dispatcher::Callback_DispatchLoop
5d CoreMessaging!Microsoft::CoreUI::Dispatch::EventLoop::Callback_RunCoreLoop
5e CoreMessaging!Microsoft::CoreUI::Dispatch::UserAdapter::DrainCoreMessagingQueue
5f CoreMessaging!Microsoft::CoreUI::Dispatch::UserAdapter::OnUserDispatch
60 CoreMessaging!Microsoft::CoreUI::Dispatch::UserAdapter::OnUserDispatchRaw
61 CoreMessaging!Microsoft::CoreUI::Dispatch::UserAdapter::DoWork
62 CoreMessaging!Microsoft::CoreUI::Dispatch::UserAdapter::WindowProc
63 user32!UserCallWinProcCheckWow
64 user32!DispatchClientMessage
65 user32!__fnDWORD
66 ntdll!KiUserCallbackDispatcherContinue
67 win32u!ZwUserGetMessage
68 user32!GetMessageW
69 WindowsTerminal
6a WindowsTerminal
6b kernel32!BaseThreadInitThunk
6c ntdll!RtlUserThreadStart
```

**Comment by echo6ix** [comment] 2023-02-09 20:59
Since posting this I'm not sure this is a Windows Terminal issue. Visual Studio Code and Google Chrome also become non-responsive after resuming from hibernation or returning to a user account after switching accounts. It's not isolated to Windows Terminal.

**Comment by zadjii-msft** [comment] 2023-02-09 21:26
Oh oh oh this might be MSFT:37461145 or MSFT:27403842 - there's an internal mail thread titled "RDP disconnects lead to unresponsive apps" that seems relevant

**Comment by echo6ix** [comment] 2023-02-15 17:18
> Oh oh oh this might be [MSFT:37461145](https://task.ms/37461145) or [MSFT:27403842](https://task.ms/27403842) - there's an internal mail thread titled "RDP disconnects lead to unresponsive apps" that seems relevant

Unfortunately MS doesn't seem to like my account and I cannot view those links (long winded error message omitted). 🫤

Is there any way to view them without requiring a MS account?

**Comment by zadjii-msft** [comment] 2023-02-15 18:39
> I cannot view those links 

Ah that's _very much_ by design - those link to the Windows-wide internal bug tracker. Those should be locked down so only Windows engineers should be able to see them 😜 

They are more of a note to ourselves that this is already something being investigated by another team. I'm _really_ hoping that's what it is.

**Comment by echo6ix** [comment] 2023-02-15 18:42
> > I cannot view those links
> 
> Ah that's _very much_ by design - those link to the Windows-wide internal bug tracker. Those should be locked down so only Windows engineers should be able to see them 😜
> 
> They are more of a note to ourselves that this is already something being investigated by another team. I'm _really_ hoping that's what it is.

Ok, I understand. Well, is there any mention in those threads as to how to resolve the issue? Disable RDP maybe (not that I ever use it)?

**Comment by lhecker** [comment] 2023-04-12 21:56
This will most likely be fixed by #14959 because it doesn't call any graphics APIs while the console lock is being held.

**Comment by zadjii-msft** [comment] 2023-09-27 18:52
Anyone still seeing this on 1.18 Stable & 1.19 Preview/?

**Comment by zoredache** [comment] 2023-09-29 00:18
> Anyone still seeing this on 1.18 Stable & 1.19 Preview/?

I haven't been seeing this since 1.17, and I was having problems with it all the time back on 1.15.  Haven't tested with 1.19 specifically.

**Comment by zadjii-msft** [comment] 2023-09-29 10:59
I'll count that ☺️ Thanks!

**Closed by zadjii-msft** 2023-09-29 10:59 UTC
Labels: Area-Rendering, Issue-Bug, Severity-Crash, Needs-Author-Feedback, Product-Terminal, Priority-1
