### ISSUE TITLE
Shift-Insert, Ctrl-Insert Support

### ISSUE THREAD

**Issue by saltatory** [microsoft/terminal#3978] opened 2019-12-17 00:18 UTC
# Description of the new feature/enhancement

As a developer, I would like insert and deletion hot-keys to match what I use in other applications. Specifically, I would like to be able to use Ctrl-Insert and Shift-Insert for Copy and Paste respectively. I do not use the currently supported Ctrl-Shift-V and Ctrl-Shift-C in any other application that I can think of and therefore these "feel" unnatural.

# Proposed technical implementation details (optional)

See above. I think it's self explanatory.

**Comment by DHowett-MSFT** [comment] 2019-12-17 01:00
This is a /dupe of #3162, and, broadly, you can bind these keys to whatever you'd like :smile:

**Closed by DHowett-MSFT** 2019-12-17 01:00 UTC
Labels: Issue-Feature, Needs-Tag-Fix, Needs-Triage
