### ISSUE TITLE
The one thing that keeps me away from using it

### ISSUE THREAD

**Issue by mrwnmonm** [microsoft/terminal#4049] opened 2019-12-23 14:34 UTC
If you have the taskbar auto-hidden, and you are in the terminal (Maximized), the taskbar won't show up when you move the mouse at the bottom of the screen. 

This happens for all versions.

**Comment by j4james** [comment] 2019-12-24 10:47
This is a duplicate of #1438.

**Comment by zadjii-msft** [comment] 2019-12-30 14:47
@j4james thanks for the early triage finding the dupe for this!

/dup #1438

**Closed by zadjii-msft** 2019-12-30 14:47 UTC
Labels: Needs-Tag-Fix, Needs-Triage
