### ISSUE TITLE
Bug Report: links are not clickable

### ISSUE THREAD

**Issue by wolf99** [microsoft/terminal#2478] opened 2019-08-19 21:42 UTC
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18362.295]
Windows Terminal version (if applicable): Version: 0.3.2171.0
```

# Steps to reproduce

1. Open any shell (tried with WSL [bash, Ubuntu 18.04.3 LTS], cmd, PwoerShell PowerShell Core)
2. Run some command that produces output containing a URL e.g. `echo http://www.github.com`

# Expected behavior

The URL is clickable, i.e. the console recognises that the text is a web link and allows it to be handled as such.

# Actual behavior

The URL is not clickable - it's just text

This works in terminal in VSCode

**Comment by DHowett-MSFT** [comment] 2019-08-19 21:49
Dupe of #574. Thanks!

**Closed by DHowett-MSFT** 2019-08-19 21:49 UTC
Labels: Needs-Tag-Fix, Needs-Triage

**Comment by wolf99** [comment] 2019-08-19 21:59
Whoops, thanks!
