### ISSUE TITLE
WT: Load profile icons from executables

### ISSUE THREAD

**Issue by alabuzhev** [microsoft/terminal#11733] opened 2021-11-11 16:01 UTC
# Description of the new feature/enhancement

It's nice that WT supports custom profile icons.
It's nice that it can load jpg, png, bmp, gif, tiff and ico.

However, why doesn't it support loading icons from executables?
If I'm creating a new profile and setting its icon, usually I want it to have exactly the same icon as the underlying executable has, but I can't load it directly, so I have to either play with the <kbd>Print Screen</kbd> and Paint (ugh) or look for a 3rd party tool to extract an icon from the exe, because _usually_ apps don't come with separately packaged icons, because every shortcut in Windows allows to load icons from exe, dll, etc. directly since 1995 or so.

Are there any technical limitations for that?

**Comment by zadjii-msft** [comment] 2021-11-11 16:11
There's mostly _engineering time_ limitations for that 😋. In general, this is a dupe of:
* #1504 - for being able to manually set an exe as the icon
* #705 - for automatically grabbing the icon from an exe if no icon is set.

I'm also tempted to just close out #705, because that probably will work less often than the user would hope. Being explicit about the icon is probably a better idea.

So, /dup #1504

**Closed by zadjii-msft** 2021-11-11 16:11 UTC
Labels: Issue-Feature, Needs-Triage, Needs-Tag-Fix

**Comment by alabuzhev** [comment] 2021-11-11 16:20
Thanks.

> I'm also tempted to just close out #705, because that probably will work less often than the user would hope

Please don't - machines should work and it's a nice thing if the code can load the icon automatically and save the user some clicks, even if not in 100% of cases.
