### ISSUE TITLE
Emacs delete-other-windows causes some lines to be hidden on widescreen monitor with hardware rendering

### ISSUE THREAD

**Issue by vmiheer** [microsoft/terminal#8454] opened 2020-12-01 19:45 UTC
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.19042.630]
Windows Terminal version (if applicable): 1.5.3142.0
Emacs version: GNU Emacs 26.3
Ubuntu wsl: Ubuntu 20.04.1 LTS
Display resolution: 3440x1440
nvidia driver: 457.30 RTX 2060 super
```

# Steps to reproduce
## Fail case
1. Maximize terminal, open wsl, start emacs. Press (C-x 1) (Ctrl+x followed by 1).
2. Notice some lines are hidden
3. Press C+g (Ctrl+g) to force repaint of emacs.
4. Lines appear back

## Pass case 1
1. Reduce window size so that window is around 1440x1440.
2. Follow steps 1 and 2 and observe there are no hidden lines

## Pass case 2
1. Enable software rendering in terminal settings:  `"experimental.rendering.software": true`.
2. Follow steps 1 and 2 and observe there are no hidden lines

# Expected behavior

Even when terminal is fullscreen there shouldn't be hidden lines

# Actual behavior

Some lines are hidden.

# Screenshots

## Pass:
![pass](https://user-images.githubusercontent.com/535650/100788861-ea2e8c80-33d2-11eb-85f8-5c072e6b44de.gif)

## Fail:
![fail](https://user-images.githubusercontent.com/535650/100788864-eac72300-33d2-11eb-9a07-3189ed2b9b6f.gif)

**Comment by zadjii-msft** [comment] 2020-12-02 22:49
Well that's sure bizarre. This isn't the first bug report we've had this month about the RTX 20* cards. See also #8371. 

Makes one think that there's a bug in the driver, rather than the Terminal...

(I'm just musing, I have no idea what's causing this or how to debug. @miniksa might have an idea.)

**Comment by vmiheer** [comment] 2020-12-02 22:58
Well given that software rendering is working, might be best to push to nvidia. And add this as test in WHQL 😂.

**Comment by DHowett** [comment] 2020-12-03 02:00
How strange! I'm gonna mark this one a /dupe of #8371 because of the similar invalidation symptoms. That's quite strange.

**Closed by DHowett** 2020-12-03 02:00 UTC
Labels: Needs-Tag-Fix, Needs-Triage
