### ISSUE TITLE
Ctrl-mousewheel causes crash

### ISSUE THREAD

**Issue by MarkPflug** [microsoft/terminal#5687] opened 2020-05-01 15:47 UTC
# Environment

```none
Windows build number: 10.0.18363.0
Windows Terminal version: 0.11.1191.0

```

# Steps to reproduce

Zooming the text size with ctrl+mousewheel rapidly causes Terminal to crash. This is easily reproducible on my machine, though sometimes it takes a several seconds on rapidly zooming in/out before it happens.

# Expected behavior

No crash.

# Actual behavior

Terminal window disappears.

The event log contains the following crash information:

```xml
- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="Application Error" /> 
  <EventID Qualifiers="0">1000</EventID> 
  <Level>2</Level> 
  <Task>100</Task> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2020-05-01T15:44:37.293990200Z" /> 
  <EventRecordID>64933</EventRecordID> 
  <Channel>Application</Channel> 
  <Computer>REDACTED</Computer> 
  <Security /> 
  </System>
- <EventData>
  <Data>WindowsTerminal.exe</Data> 
  <Data>0.11.2004.28001</Data> 
  <Data>5ea883f8</Data> 
  <Data>ntdll.dll</Data> 
  <Data>10.0.18362.778</Data> 
  <Data>0c1bb301</Data> 
  <Data>c0000374</Data> 
  <Data>00000000000f9229</Data> 
  <Data>2848</Data> 
  <Data>01d61fcf67548955</Data> 
  <Data>C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_0.11.1191.0_x64__8wekyb3d8bbwe\WindowsTerminal.exe</Data> 
  <Data>C:\WINDOWS\SYSTEM32\ntdll.dll</Data> 
  <Data>75b423bb-49b9-44f2-818b-cbb1f32fddce</Data> 
  <Data>Microsoft.WindowsTerminal_0.11.1191.0_x64__8wekyb3d8bbwe</Data> 
  <Data>App</Data> 
  </EventData>
  </Event>


```

**Comment by DHowett-MSFT** [comment] 2020-05-01 16:23
I think this is a /dupe of #5479

**Closed by DHowett-MSFT** 2020-05-01 16:23 UTC
Labels: Needs-Tag-Fix, Needs-Triage
