### ISSUE TITLE
"Open with Windows Terminal" context menu not display on desktop (or right click without selected folder)

### ISSUE THREAD

**Issue by ikas-mc** [microsoft/terminal#11839] opened 2021-11-29 05:35 UTC
### Windows Terminal version

v1.11.2921.0

### Windows build number

22000.384 and dev

### Steps to reproduce

It is difficult to reproduce, until found the association with onedrive

clean install 22000.194 and delete onedrivesetup.exe before oobe
install Windows Terminal 

### Expected Behavior

"Open with Windows Terminal" context menu display 

### Actual Behavior

![27](https://user-images.githubusercontent.com/65895428/143813779-50acf97c-2095-4058-98a4-2067b009cdb1.gif)

but after install onedrive , the menu working properly

test result is:
22000.194 without onedrive = ok
update to 384 without onedrive = not display
384 with onedrive installed= ok

![29](https://user-images.githubusercontent.com/65895428/143814229-8f80d163-a6e8-4005-bad2-67b3f7394b46.gif)

**Comment by EdiWang** [comment] 2021-11-29 07:17
I have OneDrive installed.

**Comment by ikas-mc** [comment] 2021-11-29 07:57
@EdiWang 
my windows(dev) had this problem before, I uninstalled onedrive, installed the latest 64-bit version... and then fixed the problem

**Comment by zadjii-msft** [comment] 2021-11-29 22:10
@ikas-mc Wait, so, is this still an issue? If it is, I reached out to someone on the explorer team, and they told me how to get some advanced diagnostics that might help.

You should be able to take an advanced trace on in the Feedback Hub, on the bottom page:
![image](https://user-images.githubusercontent.com/18356694/143950454-cb16798d-808d-40b6-bd33-440f6ab22695.png)

then, file feedback on the File Explorer path as usual, and make sure to include the zip file from the advanced diagnostics trace. Add the "Share my feedback" link here, and I can make sure it gets promoted to the right folks.

Of course, if this isn't an issue anymore, we can just close this out without the trace ☺️

**Comment by EdiWang** [comment] 2021-11-30 03:45
@ikas-mc 

Thanks for the tip. But for me, uninstall and reinstall OneDrive didn't help. Sad...

**Comment by ikas-mc** [comment] 2021-11-30 06:22
@zadjii-msft 
This is still an issue, we just happened to find that this problem can be reproduced with onedrive

If it is determined that it is a system problem(api), then it can be closed..

**Comment by zadjii-msft** [comment] 2021-11-30 12:12
Okay great, this was promoted internally to MSFT:37214068. There's not much for us to do here - this seems like a bug firmly in the explorer team's codebase. So, I'm gonna close this one out for now. I'm following the internal bug, and I'll give you an update once there's something to share. Thanks!

**Closed by zadjii-msft** 2021-11-30 12:12 UTC
Labels: Needs-Triage, Needs-Attention, Needs-Tag-Fix, Area-ShellExtension

**Comment by Yannik** [comment] 2021-12-19 00:14
I can confirm that this bug occurs after removing the `OneDriveSetup` automatic startup from `SOFTWARE\Microsoft\Windows\CurrentVersion\Run`.

**Comment by danieldaeschle** [comment] 2022-01-26 18:20
Is there at least a workaround?

**Comment by zadjii-msft** [comment] 2022-01-26 18:44
The File Explorer team hasn't provided one, unfortunately. @danieldaeschle do you also not have OneDrive installed? That might help narrow the problem space for the explorer team

**Comment by danieldaeschle** [comment] 2022-01-26 18:47
I have Onedrive installed

**Comment by danieldaeschle** [comment] 2022-01-27 06:59
But it also does not get displayed in context menu

**Comment by danieldaeschle** [comment] 2022-01-27 07:12
> @EdiWang my windows(dev) had this problem before, I uninstalled onedrive, installed the latest 64-bit version... and then fixed the problem

this helped for me

**Comment by eddiezato** [comment] 2022-02-06 04:02
I can confirm. Installed OneDrive x64, restarted File Explorer, context menu entry returned, uninstalled OneDrive, menu entry still remained.

Win 22000.469, WT 1.13.10336.0

**Comment by EdiWang** [comment] 2022-02-09 12:45
@eddiezato 

I uninstalled OneDrive, and install 64 bit version from `https://oneclient.sfx.ms/Win/Insiders/21.139.0711.0001/amd64/OneDriveSetup.exe`, restart my computer. It didn't work. Windows Terminal is still missing from context menu. Sad :( 

![image](https://user-images.githubusercontent.com/3304703/153203503-d4917605-4da2-4eb6-bda5-57f61e996edd.png)

![image](https://user-images.githubusercontent.com/3304703/153203630-fae6cc91-72bf-46cc-a303-3bde953611d5.png)

However, I do have Windows Terminal menu if I right click on a folder instead of in a folder

![image](https://user-images.githubusercontent.com/3304703/153203729-eff7beb6-490b-493b-9842-cf7e7a49eaf0.png)

I am also curios how can Windows Terminal menu be related to OneDrive, they seems to be two completely different things.

**Comment by iGattreX** [comment] 2022-02-26 15:51
This issue seems to still exist as of today. It is observed that the "Open in Windows Terminal" menu appears on the Desktop Context Menu just by restarting the "Windows Explorer" from Task Manager. May be someone else can also confirm this behavior? This being the case, I am not sure if it is related to OneDrive. As mentioned earlier in this thread, it looks like a bug in the Windows Explorer code base. @zadjii-msft Did the Windows Explorer team acknowledge and any indication of what could be the potential fix? 

It is still unclear why it happens only in some Windows machines and not all.

**Comment by zadjii-msft** [comment] 2022-02-28 12:09
They haven't been able to find a repro unfortunately. More ["advanced traces"](https://github.com/microsoft/terminal/issues/11839#issuecomment-982070290) might be helpful here, if it's happening consistently for you.

**Comment by iGattreX** [comment] 2022-02-28 12:58
Yes, it is happening consistently. While all seems okay when I restart my PC, the item from the "Open in Windows Terminal" Context Menu disappears every time I log off from my ID and login to Windows (using same ID or another ID). I have also observed that the context menu issue gets fixed when I restart the Windows Explorer task in Task Manager. I have reported the bug with Steps Recorder screenshots and diagnostics log in the Feedback App. Refer: [https://aka.ms/AAfyhpg](https://aka.ms/AAfyhpg). Hope this helps @zadjii-msft.

**Comment by shashwata27** [comment] 2022-03-12 10:18
I hate this, I reset my windows today using cloud restore. And my "open in windows terminal" option was gone. I tried editing the regedit to add it but there was not blocked folder inside it also. 

![image](https://user-images.githubusercontent.com/60866496/158014093-28097c1a-1e5e-46ee-8a9b-fb1ffa30dc6c.png)
![image](https://user-images.githubusercontent.com/60866496/158014110-9219bc69-58f7-4629-819d-a562f58552c5.png)

**Comment by zadjii-msft** [comment] 2022-03-21 13:24
I believe this was fixed last Friday and should be flowing out to Insiders builds soon<sup>TM

**Comment by iGattreX** [comment] 2022-04-16 04:05
In which build is this issue expected to be fixed?

**Comment by ashfaqnisar** [comment] 2022-04-20 08:34
Hey @iGattreX, it seems the issue was fixed in the 22598.200 build version

**Comment by CrypticCus** [comment] 2022-04-24 10:17
Finally its been months

**Comment by omeilick** [comment] 2022-05-14 19:28
I think I found the solution!! 

So its an application called "terminal" created by Microsoft and can be found in the Microsoft Store. Re-downloaded the application and the right-click menu pops up with the "open in terminal" option. If anyone else could verify that this works that would be amazing.

Wish I took a screenshot before because it was 100% not there before I re-downloaded the application but see pics below for the after screenshots where the options menu is working again.

![open in terminal desktop](https://user-images.githubusercontent.com/93002943/168445538-b5096312-ea2e-4e0f-9ed9-c9e1d507d5da.png)

![open in terminal explorer](https://user-images.githubusercontent.com/93002943/168445636-3a53e127-cd74-451d-ba59-09336219baa3.png)

![open in terminal](https://user-images.githubusercontent.com/93002943/168445657-34a6132e-8438-4603-bb90-c7a87b5ea564.png)

Hope this helps! Happy coding 😄

**Comment by MainEditor** [comment] 2022-08-25 04:55
I'm found that the problem starts after installing the MS PowerToys. And it fixes after uninstalling the PowerToys and rebooting your PC but I'm reinstalled Windows 11 because I'm pollutws thw registry while tried fix problem. Is anyone who ran into a problem has been installed MS PowerToys on their PC's?

**Comment by MainEditor** [comment] 2022-08-25 04:57
I'm found that the problem starts after installing the MS PowerToys. And it fixes after uninstalling the PowerToys and rebooting(or just log out) your PC but I'm reinstalled Windows 11 because I'm pollutws thw registry while tried fix problem. Is anyone who ran into a problem has been installed MS PowerToys on their PC's?

**Comment by DannySauval** [comment] 2022-09-08 14:53
I had PowerToys installed, I tried to remove it and reboot but it didn’t show me the Open In Terminal, even after reinstalling Windows Terminal. Too bad, as I used this shortcut a lot on Windows 10.

**Comment by zadjii-msft** [comment] 2022-09-08 15:13
There actually was a regression our side. The thread over at https://github.com/microsoft/terminal/issues/13523#issuecomment-1219393733 has the details. It was a combo of us changing a thing, and Windows 11 also changing a thing. There are more details in https://github.com/microsoft/terminal/issues/12578#issuecomment-1238859062 also.

**Comment by weiqi-chen** [comment] 2022-12-20 13:58
Same Issue at Windows 10

Gif:
![terminal_issue](https://user-images.githubusercontent.com/6562920/208683618-c32f41c7-9da4-4c10-95f6-b5b96eedb9ce.gif)

Terminal version
![image](https://user-images.githubusercontent.com/6562920/208683497-147ff2cb-4614-49d9-b810-91e870d2ce21.png)

Windows 10 version
![image](https://user-images.githubusercontent.com/6562920/208683578-9df8ebb4-0c63-4065-ba90-46e2b9ddab0f.png)

**Comment by 4ndyDufresne** [comment] 2023-05-23 11:31
> Same Issue at Windows 10
> 
> Gif: ![terminal_issue](https://user-images.githubusercontent.com/6562920/208683618-c32f41c7-9da4-4c10-95f6-b5b96eedb9ce.gif) [ ](https://user-images.githubusercontent.com/6562920/208683618-c32f41c7-9da4-4c10-95f6-b5b96eedb9ce.gif) ![terminal_issue](https://user-images.githubusercontent.com/6562920/208683618-c32f41c7-9da4-4c10-95f6-b5b96eedb9ce.gif) [ ](https://user-images.githubusercontent.com/6562920/208683618-c32f41c7-9da4-4c10-95f6-b5b96eedb9ce.gif)
> 
> Terminal version ![image](https://user-images.githubusercontent.com/6562920/208683497-147ff2cb-4614-49d9-b810-91e870d2ce21.png)
> 
> Windows 10 version ![image](https://user-images.githubusercontent.com/6562920/208683578-9df8ebb4-0c63-4065-ba90-46e2b9ddab0f.png)

I have the exact same issue.

**Comment by v2piyuk** [comment] 2023-06-14 17:13
Hi @omeilick , 
I think **the workaround works.** Unfortunately I couldn't get the screenshot of before but captured the workflow when it works. 
https://github.com/microsoft/terminal/assets/99791294/23ecde69-bd2b-4e7b-8450-37ab201977e7

**Comment by bmSgithub** [comment] 2023-10-23 05:33
> This issue seems to still exist as of today. It is observed that the "Open in Windows Terminal" menu appears on the Desktop Context Menu just by restarting the "Windows Explorer" from Task Manager. May be someone else can also confirm this behavior? This being the case, I am not sure if it is related to OneDrive. As mentioned earlier in this thread, it looks like a bug in the Windows Explorer code base. @zadjii-msft Did the Windows Explorer team acknowledge and any indication of what could be the potential fix?
> 
> It is still unclear why it happens only in some Windows machines and not all.

this worked for me
