### ISSUE TITLE
Initial Position Partly Off Screen

### ISSUE THREAD

**Issue by nurbles** [microsoft/terminal#4681] opened 2020-02-21 12:47 UTC
# Environment

```none
Windows build number: 1903  Build 18362.657
Windows Terminal version (if applicable):  0.9.433.0

Any other software?
```

# Steps to reproduce

1. Change the settings to have a large number of lines, but a number that _will_ fit on your screen, but only by an inch or so.
2. Start Windows Terminal repeatedly, noting that,eventually, the bottom of the terminal window goes beyond the bottom of the screen.  This may take several attempts before the 'default' start position is too close to the bottom of the screen.

# Expected behavior

I expect (hope?) that modern programs either save/restore the previous window size & position **OR** that the programs ensure that their entire window is visible when started. 

If the window is larger than the screen, I would expect either
- The top,left corner of the window to be at the top,left corner of the monitor
- Optionally, the window size adjusted to fit on the screen automatically or, in the case of a terminal window, perhaps the font size adjusted downward until the window fits on the screen.

# Actual behavior

I had my terminal configured to a rather large font and 50 lines at startup.  This morning when I started it, the bottom 1/4 to 1/3 (I'm guessing) of the terminal window was below the bottom of the screen.  There was more than enough space on screen _ABOVE_ the terminal and it was easy enough to move, but the code should not **require** me to move it in order to see the whole window when it first loads!

**Comment by DHowett-MSFT** [comment] 2020-04-03 06:03
Hey @nurbles, sorry for taking so long to triage this one. You've raised a totally valid concern, and I've let the backlog get ahead of me. This looks like a /dupe of #3187. I migrated your notes over there.

**Closed by DHowett-MSFT** 2020-04-03 06:03 UTC
Labels: Needs-Tag-Fix, Needs-Triage
