### ISSUE TITLE
Mouse presses not registering in windows-curses in terminal, but do in standalone CMD

### ISSUE THREAD

**Issue by jwlodek** [microsoft/terminal#8682] opened 2020-12-30 20:54 UTC
# Environment

```none
E:\>ver

Microsoft Windows [Version 10.0.18363.1256]

E:\>py --version
Python 3.7.0

E:\>pip freeze | grep curses
windows-curses==2.1.0
```

# Steps to reproduce

Install windows curses:

```
pip install windows-curses
```

Run the following script:

```Python
import curses

screen = curses.initscr()
#curses.noecho()
curses.curs_set(0)
screen.keypad(1)
curses.mousemask(1)

screen.addstr("This is a Sample Curses Script\n\n")

while True:
    event = screen.getch()
    if event == ord("q"): break
    if event == curses.KEY_MOUSE:
        _, mx, my, _, _ = curses.getmouse()
        y, x = screen.getyx()
        screen.addstr(f"Mouse location:{mx}, {my}\n\n")

curses.endwin()
```

in command prompt, and then in windows terminal.

Click the mouse in random locations around the screen.

# Expected behavior

Mouse presses detected and printed to screen (see screenshot from CMD):
![image](https://user-images.githubusercontent.com/29227305/103380500-1105de80-4ab7-11eb-8689-5b35275b0913.png)

# Actual behavior

No mouse presses detected and nothing printed to screen.

**Comment by DHowett** [comment] 2021-01-01 22:01
Thanks for the report! This is a /duplicate of #376. The PTY infrastructure here supports passing through VT mouse events (for Windows and WSL applications), but not Win32 mouse events. Windows-curses is using native win32 mouse events.

**Closed by DHowett** 2021-01-01 22:02 UTC
Labels: Needs-Tag-Fix, Needs-Triage
