### ISSUE TITLE
Terminal couldn't be opened if default profile can't be opened.

### ISSUE THREAD

**Issue by SJang1** [microsoft/terminal#1404] opened 2019-06-22 11:34 UTC
# What's Happening?

When (somehow) which "defaultProfile" is not able to run like miss-typing "commandline" goes like "powershell.ex" (no e) so there is no program to run it, windows terminal just shuts down when opening terminal, (or not the command line program, like office program WINWORD.EXE => opens word program and terminal shuts down.) and never can be opened before finding profiles.json and change wrong thing manually or change defaultProfile to which it can be run on windows terminal.

# Proposed technical implementation details

So, If something that (Cannot use Windows terminal because of profiles.json) happens, Opening a popup "Can't load Terminal" with button open profiles.json **before Windows Terminal shuts down** like the image
![image](https://user-images.githubusercontent.com/29011440/59963221-eb476300-952a-11e9-9393-0a2d9830b270.png)

 or just not load any kind of commandline and **make a select screen** which profile to load for user like this image
![image](https://user-images.githubusercontent.com/29011440/59963201-b1765c80-952a-11e9-8f13-b348df6e2ebf.png)

_BTW I just made image using mspaint_

**Comment by SJang1** [comment] 2019-06-22 14:43
...or not closing windows terminal if all tabs are closed and show up select screen could be great too.

**Comment by DHowett-MSFT** [comment] 2019-06-24 21:37
Most of this is a duplicate of #1348.

**Closed by DHowett-MSFT** 2019-06-24 21:37 UTC
Labels: Needs-Tag-Fix, Needs-Triage
