### ISSUE TITLE
Cannot start WT elevated 

### ISSUE THREAD

**Issue by teobugslayer** [microsoft/terminal#3615] opened 2019-11-18 10:56 UTC
Issue: Cannot start elevated Windows Terminal using the "WT" shortcut

# Environment

Windows [Version 10.0.18363.449]
WT Version: 0.6.2951.0

# Steps to reproduce

 - open start menu
 - type "wt" (without quotes)
 - on the search results, right-click and select Run as administrator

# Expected behavior

Start Windows Terminal elevated

# Actual behavior

The following error appears:

[Window Title]
C:\Users\user\AppData\Local\Microsoft\WindowsApps\wt.exe

[Content]
C:\Users\user\AppData\Local\Microsoft\WindowsApps\wt.exe

The file cannot be accessed by the system.

[OK]

**Comment by DHowett-MSFT** [comment] 2019-11-18 20:49
This is a /dupe of #3145, which we're tracking internally as a platform issue. Thanks for the report!

**Closed by DHowett-MSFT** 2019-11-18 20:49 UTC
Labels: Needs-Tag-Fix, Needs-Triage
