### ISSUE TITLE
Error 0x8007010b could display a more expressive error message - mention the actual  starting directory?

### ISSUE THREAD

**Issue by erichiller** [microsoft/terminal#9114] opened 2021-02-11 12:17 UTC
# Environment

```none
Windows build number:  Win32NT             10.0.19042.0 Microsoft Windows NT 10.0.19042.0
Windows Terminal version (if applicable):  Version: 1.6.10272.0
```

I've had this happen on the both the windows computers I use, but the above is from the machine I use most. This did use to work, and I haven't changed anything in my setup recently (besides the windows version though normal updates and terminal versions). Unknown how long this has been broken for me, but at least 1.5 weeks.

`profiles` in `settings.json`:
```json

            {
                "guid": "{61c54bbd-c2c6-5271-96e7-009a87ff44ff}",
                "name": "Windows PowerShell 7.2-preview",
                "commandline": "pwsh.exe",
                "hidden": false,
                "background": "#000000",
                "colorScheme": "Tango Dark",
                "cursorColor": "#FFFFFF",
                "cursorShape": "bar",
                "fontSize": 8,
                "icon": "C:\\Program Files\\PowerShell\\7-preview\\assets\\Powershell_av_colors.ico",
                "historySize": 9999,
                "startingDirectory": "~/",
                "snapOnInput": true
            }
```

# Steps to reproduce

Use the `duplicateTab` command for a hotkey.
eg.
```json
        {
            "command": "duplicateTab",
            "keys": [
                "ctrl+up"
            ]
        },
```

# Expected behavior

A tab to open of the same type as the current tab.

# Actual behavior

I receive an error like
```
[error 0x8007010b when launching `pwsh.exe']
```
![image](https://user-images.githubusercontent.com/5379325/107635229-08610600-6c28-11eb-8d07-7fb0b2213546.png)

**Comment by zadjii-msft** [comment] 2021-02-11 13:08
I'm betting something in your prompt is emitting OSC 9;9 to "set the current directory", and we're failing to find that directory. This might be the same root cause as  #8930, which was fixed by #8934. Could you do a `gc function:/Prompt` and share what that outputs? We might be able to find the offending quotes in that output.

We might also be able to surface this particular error better. @DHowett thoughts on having this specific error cause the connection to tell the user _which directory_ wasn't found?

**Comment by JasonWThompson** [comment] 2021-02-11 18:44
I noticed my issue that I logged is similar to this one. Here is what I get when I run that command.

```
 gc function:/Prompt

        $lastCommandFailed = ($global:error.Count -gt $sl.ErrorCount) -or -not $?
        $sl.ErrorCount = $global:error.Count

        #Start the vanilla posh-git when in a vanilla window, else: go nuts
        if(Test-IsVanillaWindow) {
            Write-Host -Object ($pwd.ProviderPath) -NoNewline
            Write-VcsStatus
        }

        Reset-CursorPosition
        $prompt = (Write-Theme -lastCommandFailed $lastCommandFailed)

        if($sl.Options.ConsoleTitle) {
            $location = Get-Location
            $folder = (Get-ChildItem | Select-Object -First 1).Parent.BaseName
            $prompt += "$([char]27)]2;$($folder)$([char]7)"
            if ($location.Provider.Name -eq "FileSystem") {
                $prompt += "$([char]27)]9;9;`"$($location.Path)`"$([char]7)"
            }
        }

        $prompt
```

I set this custom prompt months ago from a tutorial. I'll see if I can find the tutorial and undo the change.

**Comment by DHowett** [comment] 2021-02-11 18:45
There's a build of Terminal about to come out that should fix this. Sorry for the issue! :smile:

**Comment by DHowett** [comment] 2021-02-11 18:45
>thoughts on having this specific error cause the connection to tell the user which directory wasn't found?

I would love to have more expressive error messages !

**Comment by zadjii-msft** [comment] 2021-02-11 18:54
I'm gonna leave this open then and re-purpose this as "we need a more expressive message in this case".

**Comment by DHowett** [comment] 2021-02-11 19:49
As an aside,

> "startingDirectory": "~/",

I'm surprised that this doesn't _on its own_ cause trouble.

(Also, doesn't the powershell generator detect this specific instance of powershell preview?)

**Comment by erichiller** [comment] 2021-02-13 11:44
Here's my output for `gc function:/Prompt`:

```
$lastCommandFailed = ($global:error.Count -gt $sl.ErrorCount) -or -not $?
$sl.ErrorCount = $global:error.Count                                                                                                                                                                                                                                                                                                                #Start the vanilla posh-git when in a vanilla window, else: go nuts
if(Test-IsVanillaWindow) {
    Write-Host -Object ($pwd.ProviderPath) -NoNewline
    Write-VcsStatus
}

Reset-CursorPosition
$prompt = (Write-Theme -lastCommandFailed $lastCommandFailed)

if($sl.Options.ConsoleTitle) {
    $location = Get-Location
    $folder = (Get-ChildItem | Select-Object -First 1).Parent.BaseName
    $prompt += "$([char]27)]2;$($folder)$([char]7)"
    if ($location.Provider.Name -eq "FileSystem") {
        $prompt += "$([char]27)]9;9;`"$($location.Path)`"$([char]7)"
    }
}

$prompt
```

Also, I will note that I've just **updated to 1.6.10412.0 and the issue has been fixed**. But I agree that a more expressive error message would be nice. Thanks for the fix!

**Closed** 2021-05-12 17:36 UTC
Labels: Area-TerminalConnection, Easy Starter, Help Wanted, In-PR, Issue-Task, Product-Terminal
