### ISSUE TITLE
Font settings not working for WSL apps that draw over the entire screen

### ISSUE THREAD

**Issue by KireinaHoro** [microsoft/terminal#177] opened 2018-05-15 07:50 UTC
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)

Microsoft Windows [Version 10.0.17134.48]

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)

  * Launch WSL console
  * Set default font to something other than the default font (e.g. on a system with MS Gothic as the default 
font, choose Source Code Pro instead in Default Values), then reopen the window;
  * Install and launch apps that redraws the entire screen (e.g. mosh, tmux, vim, etc.)
  * Exit from the app

One should not experience font change in the process

* What's wrong / what should be happening instead:

The font gets reverted to the default font (in my case MS Gothic) as soon as tmux gets started, and sometimes the font reverts back to the font I selected when it exits (either finishes executing and exits or detaches), sometimes it doesn't. Setting the font in "Properties" does change the font, but the setting doesn't get preserved.

On exit, the font gets reverted to the default one shortly, and then the window closes.

![image](https://user-images.githubusercontent.com/7804730/40042667-bf6e221e-5854-11e8-811f-ed1e598746c6.png)
![image](https://user-images.githubusercontent.com/7804730/40042685-cf98aede-5854-11e8-956e-9a190aa9afac.png)

**Comment by dacapoday** [comment] 2018-05-19 06:14
same with you

**Comment by alex-liao** [comment] 2018-06-02 04:02
I have the same issue

**Comment by mikelu** [comment] 2018-07-05 18:44
having the same issue.

workaround is changing TERM=xterm-256color to TERM=xterm-color in registry DefaultEnvironment

**Comment by Tantalus13A98B5F** [comment] 2018-07-06 00:51
Same here. Microsoft Windows [Version 10.0.17134.112]. The font also changes when the window is loading or quitting. Both setting the default values and properties still cannot work.

**Comment by themis0888** [comment] 2018-10-08 10:38
Same here. By the way, is this issue about WSL? or just an issue that I can solve with the application setting?

**Comment by Shlopp** [comment] 2018-10-11 00:45
Same here on Windows [Version 10.0.17134.345]. 
I changed default font to Ubuntu Mono but it gets reverted to its original setting when I run applications like vim or man.

**Comment by zadjii-msft** [comment] 2018-10-11 16:02
Filed a bug internally to investigate. I think I know why this might be happening, for whatever reason the alt-buffer used by tmux and vim (et al) either isn't getting the font setting or the codepage setting. My guess is it's not getting the codepage, and then it's re-calculating the font it should use, and defaulting to the default codepage instead of the utf-8 codepage.

**Comment by windtoostrong** [comment] 2018-11-27 14:44
not sure if it's the same problem with my WSL. I've configured my console default font successfully, but i can't change my vim font setting, no change even with :set guifont=Consolas\ h12 inside vim.

**Comment by DHowett-MSFT** [comment] 2018-11-27 21:39
@windtoostrong 

If you're using vim in the console, `guifont` doesn't do anything (and cannot do anything.)
If you're using gvim/xvim, you need to say `Consolas:h12` (`:` instead of ` `.)

**Comment by windtoostrong** [comment] 2018-11-28 15:56
It's vim in the console, it just go with my console configuration. Don't know why Consolas doesn't seem to work for me. I switched to use Microsoft Yahei Mono, my vim and console now shares the same font and works fine.

**Comment by zadjii-msft** [comment] 2019-01-04 18:32
I've tried reproing this internally for a bit now and I can't get this behavior to repro. I've tried on a VM with MS Gothic as the default font, and I can't get the alt buffer to revert back to the default font in any scenario. 

It's entirely possible that this was fixed in RS5 (the November 2018 Update). There was also a decent amount of code delta in that area since RS5, which could have also mitigated the issue. Without being able to repro it, I won't be able to track the fix down.

If someone can confirm that this is still occurring on a recent Insider's build, I'll reopen the investigation, but until then I'm marking it as not repro.

**Comment by felixmario** [comment] 2019-01-10 09:32
I also encountered a problem with resetting fonts. It is recommended to use **Xshell** with ssh to temporarily replace the default console.

**Comment by jacobsun** [comment] 2019-02-14 07:01
As soon as  vim or tmux is started, the font will be fallbacked to the default font, and will be my terminal font after the programs quite.

**Comment by jacobsun** [comment] 2019-02-14 12:48
**It works!**

Like @zadjii-msft said, the problem is Windows can not change the cmd.exe code page permanently, WSL/Bash use utf8 code page which different from cmd.exe usually, so we need to find a font that both supports utf8 and your current default code page of cmd.exe.  

The font that @lnyng pointed out works for me.

**Comment by musma21** [comment] 2019-02-17 04:31
Not sure if this bug has been fixed already, anyway, in my case, just changing the code page of command prompt works : 

Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Nls\CodePage]
"ACP"="1252"
"MACCP"="10000"
"OEMCP"="437"

**Comment by crowbar-d** [comment] 2019-02-28 02:59
> 
> 
> Not sure if this bug has been fixed already, anyway, in my case, just changing the code page of command prompt works :
> 
> Windows Registry Editor Version 5.00
> 
> [HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Nls\CodePage]
> "ACP"="1252"
> "MACCP"="10000"
> "OEMCP"="437"

that works for my vim, thanks!

**Comment by miniksa** [comment] 2019-05-18 04:36
Looks like this solved itself. Resolving.

**Closed by miniksa** 2019-05-18 04:36 UTC
Labels: Area-Fonts, Issue-Bug, Needs-Repro, Product-Conhost, Resolution-Answered

**Comment by Po-wei** [comment] 2019-05-22 13:12
The bug reproduce in 1903 clean install.
The default font is MingLiU. Then I change it to consolas.
Open htop or vim, change back to consolas.

SO I use wsltty as a workaround.

**Comment by hzhangxyz** [comment] 2019-07-05 00:17
use regedit and add CodePage=65001 in HKCU\Console\C:.....Debian....exe\ solve my problem.
after this launch full screen program won't reset font again.

**Comment by lshghkh** [comment] 2019-07-22 11:07
> Not sure if this bug has been fixed already, anyway, in my case, just changing the code page of command prompt works :
> 
> Windows Registry Editor Version 5.00
> 
> [HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Nls\CodePage]
> "ACP"="1252"
> "MACCP"="10000"
> "OEMCP"="437"

This worked for my Vim and Tmux after a reboot! Thx!

**Comment by jingkungao** [comment] 2020-02-16 00:19
> 
> 
> having the same issue.
> 
> workaround is changing TERM=xterm-256color to TERM=xterm-color in registry DefaultEnvironment

This fixes my problem. Thanks!

**Comment by Cl1p** [comment] 2021-03-07 12:32
> This fixes my problem. Thanks!

**Comment by Cl1p** [comment] 2021-03-07 12:33
> having the same issue.
> 
> workaround is changing TERM=xterm-256color to TERM=xterm-color in registry DefaultEnvironment

This works just fine on my terminal, thanks !
