### ISSUE TITLE
SSHing from WSL2 to Windows 10 OpenSSH server to WSL 2 shell (Ubuntu 18.04) conflicts with vim keyboard input

### ISSUE THREAD

**Issue by carlosvsilva** [microsoft/terminal#8263] opened 2020-11-13 15:56 UTC
# Environment

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]: Microsoft Windows [Version 10.0.19042.630]
Windows Terminal version (if applicable): 1.4.3141.0

Any other software?
```
vim 2:8.0.1453-1ubuntu1.4
Ubuntu 18.04

# Steps to reproduce

In Windows Terminal, from a Ubuntu 18.04.5 LTS shell with all latest updates applied, I ssh to my Windows 10 20H2 (10.0.19042.630) with latest native Microsoft OpenSSH installed and start the session in a WSL2 Ubuntu 18.04.5 LTS with all latest updates applied. I then vi a terraform textfile in vim 2:8.0.1453-1ubuntu1.4 and as soon as I press the down arrow key to navigate the document, vi goes into Insert mode an deletes some lines all at once.

# Expected behavior

I expect to navigate the text document normally and have the cursor go down a line every time I press the down arrow like when I do the same action from a cmd.exe terminal/native Ubuntu WSL2 terminal in Windows.

# Actual behavior

Pressing the down arrow key deletes some lines and enters insert mode in vim instead of navigating normally.

**Comment by DHowett** [comment] 2020-11-13 18:07
I believe that this is a /duplicate of #1637. OpenSSH uses the version of the Windows console that comes with the OS, which means it'll be a little slower to update. Sorry about that!

**Comment by carlosvsilva** [comment] 2020-11-13 18:34
The workaround doesn't work for me:
Workaround: Adding set t_u7= or set ambw=double to your vimrc should fix the problem

Isn't this about Windows Terminal itself, since from cmd.exe nothing wrong seems to happen? Thanks

**Comment by DHowett** [comment] 2020-11-13 18:51
Hmm. Have to think about this a little more.

**Comment by PlayCodeStudios** [comment] 2020-11-14 06:23
It seems that wsl2 does not work even with build 20H2 19042.630, I just updated my windows to that version and I can't install wsl2 and I don't know why.

**Comment by DHowett** [comment] 2020-11-15 08:00
Sorry about the bot. I forgot to clear the tag!

**Comment by DHowett** [comment] 2020-11-20 04:21
Sorry that WSL2 stopped working for you. I hope that you got it sorted out.

What version of Windows is running on the _SSH server_?

**Comment by carlosvsilva** [comment] 2020-11-20 10:04
The SSH server is running Microsoft Windows [Version 10.0.19042.630]. Thanks

**Comment by DHowett** [comment] 2020-12-17 01:52
Okay, I hit this every day as well. Vim deletes a huge chunk of my file.

This is a definite /duplicate of #1637, but I cannot explain why the workaround doesn't help. I'm sorry about that.

**Closed by DHowett** 2020-12-17 01:52 UTC
Labels: Area-Input, Issue-Bug, Needs-Attention, Needs-Triage, Priority-2, Product-Terminal
