### ISSUE TITLE
Add the possibility to pin profile or current terminal state as secondary tile

### ISSUE THREAD

**Issue by mveril** [microsoft/terminal#6411] opened 2020-06-08 12:59 UTC
# Add the possibility to pin profile as secondary tile

UWP and Desktop Bridge apps have the possibility to [pin secondary tile](https://docs.microsoft.com/windows/uwp/design/shell/tiles-and-notifications/secondary-tiles) on the start menu in order to allow quick access to a specific part of the app (and optionally send tile notification). It can be interesting to allow Windows Terminal users to pin a profile to the start menu or eventually a terminal state (currently open tabs and panes). By this way the user can open the terminal directly where he wants just like he can do manually when he create a shortcut that target wt.exe with custom arguments.

# Proposed technical implementation details (optional)

A "pin to start" button could be added for profiles, in a context menu on the TabItem or on the profile dropdown item. For the terminal states it could be pinned using a context menu item on the title bar blank area. Or with a specific item in the Windows Terminal dropdown menu.

An example of where is it in the settings app:
![right-click-on-page-name-and-select-pin-to-start](https://user-images.githubusercontent.com/15073055/84031656-5dac8f80-a996-11ea-8829-b6e1f61e6abe.png)

**Comment by zadjii-msft** [comment] 2020-06-08 13:22
Thanks for the suggestion! There's already #576 tracking adding profiles to the jumplist, but this seems sufficiently different to me. 

One thought: How will we reconcile this UI with #5888/#1571? Do we only let people pin profiles to the start menu? What if someone wants to pin an action that opens a sequence of [new-tab with this profile, split-pane with another one] to the Start Menu? Do we need to validate that the action they're pinning is one of `newTab` or `executeCommandline`?

**Comment by zadjii-msft** [comment] 2021-02-09 15:57
You know what, after crawling through the backlog this morning, it looks like this is a pretty close duplicate of #2339. I'm gonna close this one as a dup to try and keep the discussion as centralized as possible. Thanks!

/dup #2339

**Closed by zadjii-msft** 2021-02-09 15:57 UTC
Labels: Area-User Interface, Issue-Feature, Product-Terminal
