### ISSUE TITLE
Cloud Shell reports 400 Client Error

### ISSUE THREAD

**Issue by ningweinw** [microsoft/terminal#6067] opened 2020-05-21 03:47 UTC
# Environment

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Windows Terminal version (if applicable):

Any other software?
```
Microsoft Windows [Version 10.0.18363.836]
WT Version: 1.0.1401.0

# Steps to reproduce

- Open Cloud Shell in WT
- Run command: az group list, the following error is reported:
```
The command failed with an unexpected error. Here is the traceback:

400 Client Error: Bad Request for url: http://localhost:50342/oauth2/token
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 215, in invoke
    cmd_result = self.invocation.execute(args)
...
```
- Open Cloud Shell in a browser, run the same command, ok
- Go back to WT's Cloud Shell,  run the same command, now it's working

# Expected behavior

# Actual behavior

**Comment by DHowett** [comment] 2020-05-21 03:49
This seems like a /dupe of #2371.

**Closed by DHowett** 2020-05-21 03:49 UTC
Labels: Needs-Tag-Fix, Needs-Triage
