### ISSUE TITLE
Unable to move Windows Terminal window (No way to grab title bar)

### ISSUE THREAD

**Issue by marknn3** [microsoft/terminal#13548] opened 2022-07-20 16:27 UTC
### Windows Terminal version

1.13.11432.0

### Windows build number

10.0.22622.290

### Steps to reproduce

- Start Windows Terminal (opens a tab)
- Move the Windows Terminal window as far as possible to the right side and outside of the desktop, by dragging the window title bar.
- Open a new tab by clicking the [+]

Alternative:
- Right click the Windows Terminal title bar and select Move
- Move the window as far as possible to the right side and outside of the desktop

Now there is no way anymore to grab the window, because the title bar is completely covered by 'tabs'.

### Expected Behavior

It should always be possible to move the Windows terminal window.

### Actual Behavior

There is no way to grab or move the Windows Terminal window when only the tabs are visible.

**Comment by zadjii-msft** [comment] 2022-07-20 17:13
Ultimately, this is a /dupe of #12616.

As a workaround, you can hit <kbd>alt+space</kbd>, then any arrow key (important), then move the window with the mouse that way.

**Closed by zadjii-msft** 2022-07-20 17:13 UTC
Labels: Issue-Bug, Needs-Triage, Needs-Tag-Fix
