### ISSUE TITLE
Support instant visibility of characters over high latency SSH connections

### ISSUE THREAD

**Issue by gakio12** [microsoft/terminal#8490] opened 2020-12-04 00:45 UTC
# Description of the new feature/enhancement

In the later versions of VSCode, the terminal has a feature where the text you type will show up immediately as a slightly greyer font and will become the standard color when the remote SSH server calls back confirming the key press. This makes working on servers across the globe much better. Unfortunately I don't have the specific commit to VSCode's terminal to enable this, but I was hoping we could get this implemented in Windows Terminal as well.

For example, the following sequence is painful over a connection with 500 ms latency:
> "foodis good" -> press right arrow key until between food and is -> " "

In the latest VSCode terminal, this all shows up as if it is being typed on a local running terminal as a slightly greyer font, and the font slowly turns the correct color as the remote server calls back. Basically the only time the user is waiting for the remote callback is when pressing a key that needs a response, such as TAB or ENTER.

**Comment by DHowett** [comment] 2020-12-04 00:49
Thanks for the request! This is a /duplicate of #8178.

**Closed by DHowett** 2020-12-04 00:49 UTC
Labels: Issue-Feature, Needs-Tag-Fix, Needs-Triage
