### ISSUE TITLE
Integrate into File Explorer like KDE Dolphin File Explorer

### ISSUE THREAD

**Issue by sungle3737** [microsoft/terminal#8509] opened 2020-12-06 14:51 UTC
# Integrate into File Explorer like KDE Dolphin File Explorer

![image](https://upload.wikimedia.org/wikipedia/commons/f/f7/Dolphin-default-view.png)
- Dolphin File Explorer in KDE has awesome terminal integration like this image
- **Only Terminal** or only **file explorer** is not enough to get extreme productivity for developer
- I use KDE because of this feature - **dolphin users will agree**
- Another Terminal Software can't accomplish this feature, but ms official terminal can
- Is there any plan or conversation to support that feature?

# Proposed technical implementation details (optional)

- In my short knowledge, file explorer's  `alt + p` (preview pane) will be a similar (`alt + t` for terminal pane)

**Comment by Don-Vito** [comment] 2020-12-06 16:09
@sungle3737 - Please review https://github.com/microsoft/terminal/issues/5591 to see if it already covers all the aspects of your idea.

**Comment by DHowett** [comment] 2020-12-07 05:43
Yep, this appears to be a /duplicate of #5591. Thanks

**Closed by DHowett** 2020-12-07 05:43 UTC
Labels: Issue-Feature, Needs-Tag-Fix, Needs-Triage
