### ISSUE TITLE
(Not Bug) How to make the width of " "(space) consistent with other font glyphs when toggle fake bold.

### ISSUE THREAD

**Issue by clzoc** [microsoft/terminal#12234] opened 2022-01-24 12:22 UTC
My favorite monospace font is published wih only the "Light" fontweight. Therefore, i set the value of fontweight as "bold" in settings.json to get more attractive display performance. However, it active the fake bold function, the width of characters are stretched to larger except the " "(space). The inconsistency between these characters disturb my neovim display. As far as i know, the directwrite(direct2d) based text render engine is responsible for the phenomenon. I suppose that stretch the width of " "(space) will solve this problem. Would you mind tell me how can i do that. Thanks for your patience and kindness.

**Comment by zadjii-msft** [comment] 2022-01-25 11:50
Sorry, could you help clear one thing up? By

>  The inconsistency between these characters disturb my neovim display

Do you mean something like #10678, where the "bold" text ends up getting cut off?

**Comment by clzoc** [comment] 2022-01-25 12:11
> Do you mean something like #10678, where the "bold" text ends up getting cut off?
Yes, you are right. I am sorry to my ambiguous description. Fortunately, you are so professional to understand it. Besides, my neovim behavior is just like [https://github.com/microsoft/terminal/issues/9381#issuecomment-1004445152](url) after changing the value of fontweight as "bold" in settings.json.

**Comment by zadjii-msft** [comment] 2022-01-25 12:16
No worries, I see a bunch of these every week so you learn to read between the lines 😅 

I'm gonna mark this as a /duplicate of #10678 for tracking purposes. Thanks for confirming!

**Closed by zadjii-msft** 2022-01-25 12:16 UTC
Labels: Needs-Triage, Needs-Attention, Needs-Tag-Fix
