### ISSUE TITLE
error dialogs do not show infront of the window

### ISSUE THREAD

**Issue by jtnord** [microsoft/terminal#5197] opened 2020-03-31 19:05 UTC
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18363.720]
Windows Terminal version 0.10.781.0


Any other software?
```

# Steps to reproduce

start a terminal with a cmd.exe (not powershell) session
move the terminal window to the center of the screen
at the cmd prompt run `start thisdoesnotexist`

# Expected behavior

a dialog is shown **in front** of the terminal window
![image](https://user-images.githubusercontent.com/494726/78064962-78f19200-738a-11ea-94b0-3c2a63c8df6a.png)

# Actual behavior

the dialog is shown **behind** the window.
there is no visible feedback that this has happened (there is an audio error queue but without sound you do not hear this)
this makes it appear as though the cmd session has hung.

contrast this to what happens when running cmd.exe in its "legacy" window (ie not in terminal)

**Comment by DHowett-MSFT** [comment] 2020-03-31 19:20
Thanks! This is a /dupe of #2988

**Closed by DHowett-MSFT** 2020-03-31 19:20 UTC
Labels: Needs-Tag-Fix, Needs-Triage
