### ISSUE TITLE
"persistedWindowLayout" bug when starting with arguments

### ISSUE THREAD

**Issue by alex-jitbit** [microsoft/terminal#16452] opened 2023-12-10 23:23 UTC
### Windows Terminal version

1.18.3181.0

### Windows build number

10.0.22631.2715

### Steps to reproduce

I have `"firstWindowPreference": "persistedWindowLayout"`

Also "new instance behavior" is set to "Attach to most recently used"

* When starting Windows Terminal from command prompt via `wt` - all godd
* When starting by clicking a pinned taskbar icon - all good.
* When starting via `wt -d .` to start in current directory and the terminal is already running - all good.
* ***When starting via `wt -d .` when no termonal instance is running yet - it opens in a weird random location.***

### Actual Behavior

* ***When starting via `wt -d .` when no termonal instance is running yet - it opens in a weird random location.***

**Comment by zadjii-msft** [comment] 2023-12-11 15:03
What "weird random location", _exactly_/? 

I'd expect, with your settings, that if you're cold starting the terminal with `wt -d .`, that the Terminal should spawn either {one} or {two or more} tabs:
* **one** tab, if you closed out the last tab when closing the terminal previously, so that there was nothing for the terminal to restore from the previous session.
* **two or more**, if you just closed the terminal with lots of tabs before. In this case, the terminal should open your previous tabs, and a _new_ tab for the `new-tab -d .` request.

**Comment by alex-jitbit** [comment] 2023-12-11 15:53
Also saving the current position only works when closing the window by clicking the top-right "X" window icon.

Closing the last open tab should do the same, but nope, after that the new terminal windows starts at a random position again.

But that's another bug...

Do you want me to record a video so you see how broken it is?

**Comment by zadjii-msft** [comment] 2023-12-13 22:54
Okay, we're a little bit psychic debugging here. I think what you're seeing here is a bit of a weird combo of "things that are mostly by design":

* There's slightly different behavior for persisted layouts, depending on how you close things. If you close the tab, then we take that as a signal of "I don't want this to be persisted". If you close the _window_ with one tab - then we'll persist that tab. 
  * when you close the tab (so there's no tab left to persist), the _next_ window will use the position from your settings
* Depending on what your `initialPosition` is in the settings, that probably accounts for the "random position" you're seeing. The default value will let the system position the window, which is behavior that seems apparently random


#12633 is the dupe around here for "I want to persist window positions but not really the tabs".

Does that clear things up/?

**Comment by alex-jitbit** [comment] 2023-12-14 20:27
TL;RD
* press `WIN + R`, type `wt` - correct location. Close terminal window
* press `WIN + R`, type `wt` - _again_ correct location. Close terminal window
* press `WIN + R`, type `wt -d .` - I get two separate Terminal windows, one at random location, one at correct

**Comment by zadjii-msft** [comment] 2024-01-10 22:28
So, yea that does kinda explain it. When you do the `wt -d .` command (with no open windows), what you get is 
* the last window you closed, at the size and position you closed it at
* a brand new window, at the random location

It's kinda wacky, but ultimately, it's the same thing that browsers do in the case of a cold launch with `edge.exe github.com` (or similar)

and ultimately, I think what you're expecting here is the behavior that we'd add with /dup #12633.

**Closed** 2024-01-10 22:28 UTC
Labels: Issue-Bug, Needs-Triage, Needs-Attention
