### ISSUE TITLE
Environment variables are not being refreshed

### ISSUE THREAD

**Issue by trajano** [microsoft/terminal#2477] opened 2019-08-19 21:35 UTC
I use a program called `scoop` to install software which modifies the PATH.

# Environment

```none
PS C:\Users\trajano> [Environment]::OSVersion

Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.18947.0 Microsoft Windows NT 10.0.18947.0

Terminal Version: 0.3.2171.0

```

# Steps to reproduce

1. `scoop install maven`
2. start up a new tab
3. run `mvn`

# Expected behavior

Maven should run

# Actual behavior

Maven does not run because it is not found in path
Close Terminal (all tabs and windows)
Start up Terminal again
run `mvn` works again.

**Comment by DHowett-MSFT** [comment] 2019-08-19 21:50
This is a duplicate of #1125. Thanks!

**Closed by DHowett-MSFT** 2019-08-19 21:50 UTC
Labels: Needs-Tag-Fix, Needs-Triage
