### ISSUE TITLE
Request: Smooth+Pixel Precise Scrolling

### ISSUE THREAD

**Issue by slopra** [microsoft/terminal#8548] opened 2020-12-10 20:03 UTC
# Description of the new feature/enhancement

I would absolutely die and go to heaven if smooth _and_ precise (i.e. animated and pixel-by-pixel) scrolling were implemented. One of the top reasons I started using Edge Chromium over Chrome was due to the slightly better smooth scrolling implementation.

Being able to easily read text while scrolling smoothly and precisely is a game... changer...! Especially, if you have a free scroll wheel like the MX Master 3 and/or a 120Hz+ monitor.

# Proposed technical implementation details (optional)

Implementing something like this is outside of my wheelhouse, but I found some great information on the topic here: https://pavelfatin.com/scrolling-with-pleasure/

I understand that the pure intent of a terminal emulator is to display single lines as quickly and efficiently as possible. But from a UX perspective, smooth/precise scrolling feels sooo good with the right peripherals.

Let me know your thoughts please! 😁

**Comment by j4james** [comment] 2020-12-10 22:03
I think this is probably a duplicate of #1400 and #1980.

**Comment by slopra** [comment] 2020-12-10 22:34
It sure is a dupe. I searched and everything...sigh. My Google-Fu wasn't strong enough today.
Thanks for the tags; if this feature is considered I hope my description and linked resource may still come in handy to whomever. The guy knows his scrolling... he links a repo of related code examples too https://github.com/pavelfatin/scrolling-with-pleasure

**Comment by j4james** [comment] 2020-12-10 23:50
It's not my call to make, but personally I prefer related issues like these to be closed as dupes, so whoever takes on the feature will be aware of the various use cases that could affect the design. If it turns out that a PR is only going to address one part of the problem, we can always raise follow-up issues, or reopen the ones that had previously been closed as dupes.

**Comment by DHowett** [comment] 2020-12-11 02:06
I'm inclined to call it a duplicate -- not exactly because we'll fix them both, but because they require the same underpinnings and we would be remiss in doing one of them but not the other.

Thanks for the discussion(, and the quick duplicate, James :smile:)

/dup #1400

**Comment by DHowett** [comment] 2020-12-11 02:06
I copied your description to 1400!

**Closed by DHowett** 2020-12-11 02:06 UTC
Labels: Issue-Feature, Needs-Tag-Fix, Needs-Triage
