### ISSUE TITLE
Default quake terminal keybinding is no longer working.

### ISSUE THREAD

**Issue by H4M5TER** [microsoft/terminal#12867] opened 2022-04-08 21:41 UTC
### Windows Terminal version

1.11.3471.0

### Windows build number

10.0.19044.1620

### Steps to reproduce

I was using the default keybinding [win+\`] for quake terminal and felt good with it.
But it's no longer working.
Current shortcut became `win+sc(41)` and can't be change to other keys including `win`.
So this might be a problem with the way windows treat its reserved win keybindings.

Recent windows update log:
```
0407: KB5011543 （03 cumulative）
0405: KB4023057 （04）
0318: KB5011487 （03 cumulative）
0310: KB4023057 （03）
0310: KB5012418 （.net core）
0310: KB5012416 （.net）
0310: KB890830  （msrt）
```

The problem happened not earlier than March.

### Actual Behavior

As above.
Maybe use another default keybinding for quake terminal.
But I'd like the [win+`] one, any idea?

**Comment by zadjii-msft** [comment] 2022-04-13 17:55
Hmm. Only reason I can think of that this wouldn't work is if something else stole the hotkey first. My guesses would be that maybe there's a Terminal window running as Admin somewhere? Or I think there was some PowerToy that bound itself to <kbd>Win+`</kbd> in the past. Any of those apply here? Unfortunately, there's no way for the Terminal to know _who_ already registered that hotkey.

You may have a good point that <kbd>Win+key</kbd> can't be set in the SUI, probably mainly because almost all <kbd>Win+key</kbd> shortcuts were already reserved by the OS. You should be able to set it in the `settings.json` file by hand though.

**Comment by H4M5TER** [comment] 2022-04-13 19:56
### more information

The shortcut (with Win key) of my Ditto (a clipboard) stoped not working either (it worked now), so I assumed that it's a Win key related problem.
They are both UWP (idk if this correct) from Microsoft Store but I don't have another software support keybinding with Win.
I had tried changing the keybinding in the json file but it not worked.
I looked through the [PowerToys](https://github.com/microsoft/PowerToys) settings and found nothing.

### the problem disappeared

It's weird that the problem disappeared but I didn't change anything.
Maybe I disabled the `wt -w _quake` startup task? But it worked before and I don't think it would be relate with Ditto.
I had reboot before (with a Windows update) but the problem remained.

**Comment by zadjii-msft** [comment] 2022-04-13 20:06
Yea, we should probably close it out. These kinds of bugs do often go away with a reboot - not really helpful for us getting to the root cause, but definitely and easy enough workaround.

I'll close this out, thanks for the follow up!

**Closed by zadjii-msft** 2022-04-13 20:06 UTC
Labels: Issue-Bug, Needs-Triage, Needs-Attention, Needs-Tag-Fix
