### ISSUE TITLE
Pasting into Linux...

### ISSUE THREAD

**Issue by 4k3or3et** [microsoft/terminal#3417] opened 2019-11-02 09:31 UTC
Hi All

i dont't know if there is something wrong with my confing or it is a bug but in WSL and linux boxes connected via ssh when pasting clear text from notepad, Windows Terminal after each line, leaves one empty line. I am pasting using right click.

It does not happen on cmd.exe or PowerShell

Anybody know how to resolve that?

Thanks

**Comment by j4james** [comment] 2019-11-02 14:17
Sounds like a duplicate of #1091.

**Comment by DHowett-MSFT** [comment] 2019-11-02 22:50
Yep! This is a  /dupe of #1091. Thanks!

**Closed by DHowett-MSFT** 2019-11-02 22:51 UTC
Labels: Needs-Tag-Fix, Needs-Triage
