### ISSUE TITLE
Ubuntu Not Opening

### ISSUE THREAD

**Issue by Sameer2307** [microsoft/terminal#1449] opened 2019-06-23 00:58 UTC
Ubuntu doesn't show up in the terminal. Its installed on my machine but the new terminal is recognizing it.

**Comment by Sameer2307** [comment] 2019-06-23 01:05
The command  wsl -l    
gives me following                                                                                                                                                                                               Windows Subsystem for Linux Distributions:                                                                                                                                                                                  Ubuntu-18.04 (Default)

**Comment by scottwmwork** [comment] 2019-06-23 01:48
Also Having this problem. Installed ubuntu. wsl -l gives me
Windows Subsystem for Linux Distributions:                                                                                                                                                                                Ubuntu (Default)

**Comment by Sh4d** [comment] 2019-06-23 02:39
Same here, window spawns momentarily but immediately quits. Launching wsl from a command prompt tab works fine. Also on ubuntu 18.04

**Comment by KalyanVem** [comment] 2019-06-23 05:08
Same here, wsl -l lists Ubuntu as default. But the terminal is not showing it.

**Comment by DHowett-MSFT** [comment] 2019-06-23 05:12
If you installed and launched terminal before installing WSL/ubuntu, it doesn't currently autodetect outside of first launch. You can, of course, add a custom profile.

**Comment by Sameer2307** [comment] 2019-06-23 05:15
How to add a custom profile

**Comment by Shorotshishir** [comment] 2019-06-23 05:50
I am trying to add a custom profile for my kali WSL, I tried `kali.exe` as the 'commandline' parameter of the profile, it didn't work. I think it has something to do with the `guid` or the 'commandline' parameter itself. the profile shows itself in the dropdown but doesn't work as linux terminal.

**Comment by weems** [comment] 2019-06-23 06:53
Confirmed that re-installing the application adds WSL Installed Distros to the list.

**Comment by Shorotshishir** [comment] 2019-06-23 08:24
if reinstalling doesn't find the installed WSL (for some reason) , open `appdata` (windows+r, then type appdata, hit enter ) then go to `Local>Packages>Microsoft.WindowsTerminal_8wekyb3d8bbwe>RoamingState` and delete the package.json file. reopen the Terminal app. This will reset the settings to default and load all available terminals.

**Comment by kn0rki** [comment] 2019-06-23 11:18
Doenst work for Powershell core that is not installed on default path :(

> if reinstalling doesn't find the installed WSL (for some reason) , open `appdata` (windows+r, then type appdata, hit enter ) then go to `Local>Packages>Microsoft.WindowsTerminal_8wekyb3d8bbwe>RoamingState` and delete the package.json file. reopen the Terminal app. This will reset the settings to default and load all available terminals.

**Comment by Shorotshishir** [comment] 2019-06-23 11:49
@kn0rki for not default location installations, u need to add a custom profile. 
just make a duplicate of the **default PowerShell profile** and use the **complete path of the .exe** in the **'commandLine'**: parameter. It should work just fine.

**Comment by DHowett-MSFT** [comment] 2019-06-24 22:36
This seems solved?

**Closed by DHowett-MSFT** 2019-06-24 22:36 UTC
Labels: Needs-Attention, Needs-Tag-Fix, Needs-Triage

**Comment by Sh4d** [comment] 2019-06-28 05:40
I'm still impacted by this on version 0.2.1715.0. Trying to launch ubuntu from the dropdown does nothing but wsl is fine.
