### ISSUE TITLE
Bug Report (Settings Does Not Work)

### ISSUE THREAD

**Issue by LeeThompson** [microsoft/terminal#1786] opened 2019-07-03 02:50 UTC
When using Terminal Preview if I pull down the menu and select "Settings" it tries to launch a third party game utility on my system (GW2Command.exe).  

If I uninstall that, Terminal Preview's "settings" option just tries to run a json file.   I'm guessing GW2Command was associated with json.

# Environment

```none
Windows build number: 10.0.18362.207
Windows Terminal version: 0.2.1715.0

```

# Steps to reproduce

Use Terminal Preview's "Setting" menu command on a system without json files associated.

# Expected behavior

A GUI would've been nice, but it should at least launch it with notepad or something.

# Actual behavior

No ability to configure Terminal preview.

**Comment by joandrsn** [comment] 2019-07-03 06:50
Currently it just opens the json file and lets windows handle it. 
For settings UI, see #1564

**Comment by zadjii-msft** [comment] 2019-07-03 12:56
This is a dupe of #1460.

**Closed by zadjii-msft** 2019-07-03 12:56 UTC
Labels: Needs-Tag-Fix, Needs-Triage
