### ISSUE TITLE
curses.A_UNDERLINE doesn't render an underline

### ISSUE THREAD

**Issue by Utshaan** [microsoft/terminal#13266] opened 2022-06-10 14:43 UTC
### Windows Terminal version

1.13.11432.0

### Windows build number

10.0.25131.1000

### Other Software

windows-curses 2.3.0

### Steps to reproduce

Run the following code using Python 3.10.4

```
import curses
from curses import wrapper


def main(stdscr):
    stdscr.clear()

    stdscr.addstr("Text 2" , curses.A_UNDERLINE)

    stdscr.refresh()
    stdscr.getch()

wrapper(main)
```

### Expected Behavior

![image](https://user-images.githubusercontent.com/69788046/173090977-5d7408b7-1122-4ffc-8420-fad02afdf60f.png)

### Actual Behavior

![image](https://user-images.githubusercontent.com/69788046/173091097-de358657-60d6-4042-a6f6-bae990bdae40.png)

**Comment by DHowett** [comment] 2022-06-10 17:14
If I had to guess, this is because the curses-windows library is using `COMMON_LVB_UNDERSCORE` (Windows-specific flag, supported only by Windows) instead of `SGR 4` (VT underline, supported by everyone). `LVB` was originally intended for use with CJK locales...

We have work tracked to get the LVB attributes working/passed over to Terminal in a reasonable way, so on this hunch I'm going to close this as a /duplicate of #8037.

**Closed** 2022-06-10 17:14 UTC
Labels: Issue-Bug, Needs-Triage, Needs-Tag-Fix

**Comment by Utshaan** [comment] 2022-06-10 17:18
> If I had to guess, this is because the curses-windows library is using `COMMON_LVB_UNDERSCORE` (Windows-specific flag, supported only by Windows) instead of `SGR 4` (VT underline, supported by everyone). `LVB` was originally intended for use with CJK locales...
> 
> We have work tracked to get the LVB attributes working/passed over to Terminal in a reasonable way, so on this hunch I'm going to close this as a /duplicate of #8037.

Alright thanks.

**Comment by DHowett** [comment] 2022-06-10 17:22
Thank _you_, for the report!
