### ISSUE TITLE
Windows Terminal freezes after typing a particular character

### ISSUE THREAD

**Issue by Zhu-Panda** [microsoft/terminal#12772] opened 2022-03-28 10:54 UTC
### Windows Terminal version

1.13.10733.0

### Windows build number

10.0.19044.1526

### Steps to reproduce

1. Open a prompt
2. Type a particular character
3.  Windows Terminal just freezes

Affected Prompts:
* Command Prompt
* Windows PowerShell
* PowerShell
* VS Developer PowerShell (17.0.5)
* Git Bash

Unaffected Prompts:
* VS Developer Command Prompt (17.0.5)

### Expected Behavior

The particular character gets typed

### Actual Behavior

Windows Terminal freezes

### Notes

This issue only affects one tab at a time.
The particular character is different every time.

**Comment by OfekShilon** [comment] 2022-03-28 21:00
Same for me. Terminal version 1.12.10393.0 - I *think* this started with the latest windows insider build (22581)

**Comment by ScottESanDiego** [comment] 2022-03-28 21:02
I see it in 1.13.10734.0.  It's any character, and the freeze isn't just terminal input - the window is not responsive (no dragging, drop-down, etc.) as well.

**Comment by OfekShilon** [comment] 2022-03-28 21:16
Unlike @ScottESanDiego, I see the same window freeze even when I 'run as admin'.

**Comment by justinledwards** [comment] 2022-03-28 22:00
I get the freeze running as admin as well.  Mine started on build 22581.100 just like @OfekShilon

**Comment by zadjii-msft** [comment] 2022-03-28 22:19
@ebadger Here's another thread, with another 4 reports. This might be a broad issue. 

If anyone who's hitting this is willing, could you uninstall the Terminal and install a _much_ older version, like, 1.10? and just sit with that for a few days to check if it repros there? I'm 99% sure that this is an OS bug, not a Terminal one, so having a repro on a much older Terminal verison might help ID that it's not a Terminal regression.

See also #12746 (which I very well may close this as a dupe of)

**Comment by OfekShilon** [comment] 2022-03-28 22:41
@zadjii-msft I just installed Terminal 1.10.2714 from the github release (https://github.com/microsoft/terminal/releases/tag/v1.10.2714.0)  and can verify that the same freeze happens there.  On Windows 11 build 22581.

**Comment by OfekShilon** [comment] 2022-03-29 06:21
I can also verify that rebooting solved it (or at least made it go away for a while).

**Comment by zadjii-msft** [comment] 2022-03-29 10:52
@OfekShilon Thanks for the diligence on that one. Makes me sleep at night a bit easier 😆 

I'm gonna combine this discussion with #12746 just for tracking purposes. Thanks all!

/dup #12746

**Closed by zadjii-msft** 2022-03-29 10:52 UTC
Labels: Issue-Bug, Needs-Triage, Needs-Tag-Fix
