### ISSUE TITLE
Extra space in the beginning of each lines with icon on vim(WSL)

### ISSUE THREAD

**Issue by hexh250786313** [microsoft/terminal#5947] opened 2020-05-17 05:24 UTC
Window Terminal version: 0.11.1333.0
WSL version: Ubuntu 18.04
Vim version: neovim 0.5.0

--

After I updated the Terminal today, I found a display error on vim(WSL) like this:

![2020-05-17_130835](https://user-images.githubusercontent.com/26080416/82136590-078a7780-9842-11ea-848c-c57e8bdb172f.png)

Look at the line 7, 8 or 11. The lines with warning icon have extra spaces at the beginning. And it doesn't happen in previous versions or my other terminal tools.

**Comment by DHowett** [comment] 2020-05-17 05:35
This is a /dupe of #5941 (which will be fixed by #5934)

**Closed by DHowett** 2020-05-17 05:35 UTC
Labels: Needs-Tag-Fix, Needs-Triage
