### ISSUE TITLE
Resizing the windows terminal issue

### ISSUE THREAD

**Issue by NicolasArias** [microsoft/terminal#8031] opened 2020-10-24 15:07 UTC
Windows build number: 10 19041
Windows Terminal version (if applicable): 1.3.2651.0

I'm getting weird behavior after use VIM or do something in the terminal.
At the beginning worked so good when I resized the window, but then, it had a strange behavior as I show below:

![2020-10-24_09-18-11](https://user-images.githubusercontent.com/30639530/97085018-594ce000-15e0-11eb-9432-0b7fa0096ccf.gif)

**Comment by j4james** [comment] 2020-10-24 19:58
This sounds like the same problem as described in issue #7466, which has been marked as a duplicate of #3088.

**Comment by DHowett** [comment] 2020-10-24 20:35
Thank you, @j4james! /dup #3088.

**Closed by DHowett** 2020-10-24 20:35 UTC
Labels: Needs-Tag-Fix, Needs-Triage
