### ISSUE TITLE
Vim cursror is always set to the one of Windows Terminal

### ISSUE THREAD

**Issue by stephane-archer** [microsoft/terminal#11112] opened 2021-09-01 17:04 UTC
### Windows Terminal version (or Windows build number)

1.9.1942.0

### Other Software

VIM - Vi IMproved 8.1 in WLS

### Steps to reproduce

just open vim and you will see the cursor is not showing properly

### Actual Behavior

I don't see the right cursor when I open vim.

Please note, I'm not reporting a problem with vim and looking for a way to configure it properly.

I'm reporting a bug for this app because vim is working properly with all the other terminal emulators. 

Is there a reason why this app doesn't support vim like all the others?  Is it expected behavior? Can you explain why you made that decision?

**Comment by zadjii-msft** [comment] 2021-09-01 17:14
Wow, this is a word-for-word /dupe of #8560, _including the typo_. Please make sure to search before filing new issues.

**Closed by zadjii-msft** 2021-09-01 17:14 UTC
Labels: Needs-Triage, Needs-Tag-Fix

**Comment by stephane-archer** [comment] 2021-09-01 19:32
I think you missed the important part of the issue/question:

> Is there a reason why this app doesn't support vim like all the others? Is it expected behavior? Can you explain why you made that decision?

the issue you mention is looking for a way to configure Vim to adapt to this app, this is not what I'm looking for

**Comment by aguevara** [comment] 2021-09-27 19:04
I agree, that other issue was closed with no resolution, this is a bug in WT, vim works properly in any other terminal, it only fails to work properly in WT.

**Comment by zadjii-msft** [comment] 2021-09-27 21:44
It's not valuable to the community to have multiple instances of the same discussion occurring in multiple places around the repo. It's generally better to consolidate discussion into one place, so people can both identify root causes and workarounds while we work on fixes to the root causes. I literally only just closed #8560 minutes ago, because the root cause of _that_ issue is actually being tracked in #7382. Dup'ing these all to the same bucket help us identify the root cause of issues like this.

**Comment by zadjii-msft** [comment] 2023-09-21 16:17
This thread was duped to #8560, which if you'll read, was eventually duped to #7382, which is still open. 

_as I said in literally the last comment_
