### ISSUE TITLE
The scroll event went completely wrong in some apps like vim

### ISSUE THREAD

**Issue by aeilot** [microsoft/terminal#6758] opened 2020-07-02 07:23 UTC
# Environment

```none
Windows build number:  10.0.19042.0
Windows Terminal version (if applicable): 1.0.1811.0
VIM: 8.2
```

# Steps to reproduce

I opened up Vim and scrolled down. Then nothing happened. 

The terminal UI was scrolled up but the vim was almost the same.

# Expected behavior

The text should be scrolled down.

# Actual behavior

Nothing.

# Way to solve
I have used apps like iTerm2 on Mac.

How it solve the problem is that use App-specific key to scroll down and up.
For example, when using vim, the scroll event turns into `j` and `k`.

**Comment by KalleOlaviNiemitalo** [comment] 2020-07-02 18:52
Is this a duplicate of <https://github.com/microsoft/terminal/issues/3321>?

**Comment by DHowett** [comment] 2020-07-02 18:56
Yes, and if you `:set mouse=a` scrolling _will_ work.

If you're using vim over Windows SSH 7.7, _no mouse interaction will work_

/dup #3321.

**Closed by DHowett** 2020-07-02 18:56 UTC
Labels: Needs-Tag-Fix, Needs-Triage
