### ISSUE TITLE
WT command in Windows Explorer does not work anymore

### ISSUE THREAD

**Issue by TechWatching** [microsoft/terminal#7188] opened 2020-08-05 07:24 UTC
# Environment

```none
Windows build number: Win32NT 10.0.19041.0 Microsoft Windows NT 10.0.19041.0
Windows Terminal version (if applicable): 1.1.2021.0

Any other software?
```

# Steps to reproduce

Open Windows Explorer in any directory. Enter wt in the "adress bar", and press "Enter".

# Expected behavior

The Windows Terminal opens in the current directory.

# Actual behavior
An error message appears "Windows cannot access the specified device, path, or file. You may not have the appropriate permissions to access the item".
When looking in the Windows App directory, there is no path corresponding to the error title, instead ther is a folder `Microsoft.WindowsTerminalPreview_2020.720.2337.0_neutral_~_8wekyb3d8bbwe`.
Maybe there is an error in the directory name.

![image](https://user-images.githubusercontent.com/15186176/89383428-bed5b280-d6fc-11ea-82e2-4476d8b9e9bd.png)

**Comment by snalexp** [comment] 2020-08-05 08:02
I had the same issue using the Win-R run box.

It only occurred for me when _both_ Windows Terminal and Windows Terminal Preview are installed.

Removing the Preview allows `wt` to work again.

**Comment by KalleOlaviNiemitalo** [comment] 2020-08-05 08:04
I can reproduce with Windows Terminal Preview 1.2.2022.0. However, if I rename the following Registry keys, then it works OK.

* HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths\wt.exe
* HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths\wt.exe

Those keys are automatically created by AppXSvc when I install Windows Terminal Preview. Seems related to <https://github.com/microsoft/terminal/issues/6748> and <https://github.com/microsoft/terminal/pull/6860>.

**Comment by DHowett** [comment] 2020-08-06 01:08
@KalleOlaviNiemitalo, thanks for the investigation. I'm gonna feed this straight into the app deployment team's hands :smile:

**Comment by DHowett** [comment] 2020-08-06 01:13
Tracking MSFT:28217948

**Comment by vadimkantorov** [comment] 2020-08-12 09:58
Same issue with Win+R when running "wt" ("wt" works when typing into cmd.exe)

**Comment by long-nguyenxuan** [comment] 2020-08-20 06:37
> * If I enable the `wt.exe` app execution alias of Windows Terminal Preview, then `wt` in File Explorer starts Windows Terminal Preview. ✔

I only need to quickly start Windows Terminal, Can you show me how to "enable the `wt.exe` app execution alias of Windows Terminal Preview"?

**Comment by PrOF-kk** [comment] 2020-08-20 14:03
I cannot reproduce in 1.1.2233.0, **but** Windows Terminal always opens in `C:\Users\%USERNAME%` directory regardless of where explorer is opened  
Note: cmd.exe set as default profile

**Comment by zadjii-msft** [comment] 2020-08-20 14:26
@long-nguyenxuan 
![image](https://user-images.githubusercontent.com/18356694/90784532-fcbf0300-e2c6-11ea-95c1-b538b480fe11.png)
![image](https://user-images.githubusercontent.com/18356694/90784644-1b24fe80-e2c7-11ea-8164-ec9442042f0e.png)

<hr>

@PrOF-kk you'll need to use `wt -d .` to get `wt` to start in the current working directory.

**Comment by ntindle** [comment] 2020-08-24 14:57
@zadjii-msft that doesn't appear to be documented here: 
![image](https://user-images.githubusercontent.com/8845353/91060065-1d9d9600-e5f0-11ea-86b3-617819518c85.png)

Should I open an issue for that?

**Comment by zadjii-msft** [comment] 2020-08-24 14:59
@ntindle  Nope, no need. That flag is technically part of the `new-tab` command:
![image](https://user-images.githubusercontent.com/18356694/91060346-73723e00-e5f0-11ea-8000-6b40e0895fdb.png)


when no command is explicitly passed to `wt`, it assumes the command to be `new-tab`.

**Comment by haydenmc** [comment] 2020-08-28 20:24
I do not have Windows Terminal Preview installed, just Windows Terminal, and I started running into this.

![wt launch error](https://user-images.githubusercontent.com/5422053/91612061-71321b80-e931-11ea-892d-d2b1ea95025f.png)

![App execution aliases](https://user-images.githubusercontent.com/5422053/91612116-958df800-e931-11ea-8459-03dff307104d.png)

```
PS C:\Users\Hayden> Get-AppPackage -Name "*terminal*"


Name              : Microsoft.WindowsTerminal
Publisher         : CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US
Architecture      : X64
ResourceId        :
Version           : 1.1.2233.0
PackageFullName   : Microsoft.WindowsTerminal_1.1.2233.0_x64__8wekyb3d8bbwe
InstallLocation   : C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_1.1.2233.0_x64__8wekyb3d8bbwe
IsFramework       : False
PackageFamilyName : Microsoft.WindowsTerminal_8wekyb3d8bbwe
PublisherId       : 8wekyb3d8bbwe
IsResourcePackage : False
IsBundle          : False
IsDevelopmentMode : False
NonRemovable      : False
IsPartiallyStaged : False
SignatureKind     : Store
Status            : Ok
```

**Comment by AltitudeApps** [comment] 2020-08-29 16:47
> FWIW I do not see a wt.exe key under `HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths`, but I do see one under `HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths`.

^^ this was quite a helpful clue, @haydenmc 

I have both  Windows Terminal Preview  and  Windows Terminal, both installed via the store.

`wt -d .` from the address bar in Windows Explorer was broken completely, with the same error dialog from Windows Terminal Preview in the original post.  I have the preview installed, but I'm not using it at the moment.  I was trying to invoke vanilla Windows Terminal.

The settings in the "App Execution Aliases" panel looked right.  The one for Windows Terminal was turned on, and the one for Windows Terminal Preview was turned off.

But when I checked under  
`HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths` , and
`HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths`,

I saw that Windows Terminal Preview was "hogging the spotlight" by having it configured under HKEY_CURRENT_USER.  So, I renamed it from `wt.exe` to `wtp.exe` , just so that it wouldn't interfere with my use of `wt -d .` from the Windows Explorer address bar to invoke  vanilla Windows Terminal.   (Windows Terminal Preview is still broken in this regard, but I just wanted to be able to get working again).

The existing entry for Windows Terminal under HKEY_LOCAL_MACHINE was working fine, so I left it where it was.  I guess these are supposed to be under HKCU now?

```
    Hive: HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths
Name                           Property
----                           --------
wtp.exe                        (default) : C:\Program Files\WindowsApps\Microsoft.WindowsTerminalPreview_1.3.2382.0_x64__8wekyb3d8bbwe\wt.exe
^^ was wt.exe                  Path      : C:\Program Files\WindowsApps\Microsoft.WindowsTerminalPreview_1.3.2382.0_x64__8wekyb3d8bbwe

    Hive: HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths
Name                           Property
----                           --------
wt.exe                         (default) : C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_1.2.2381.0_x64__8wekyb3d8bbwe\wt.exe
                               Path      : C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_1.2.2381.0_x64__8wekyb3d8bbwe
```

Caveat:   `wt new-tab -d .`  is broken for me; it simply launches a new copy of Windows Terminal instead of creating a new tab in an existing instance.  (Perhaps it requires a single instance for the `new-tab` functionality to work?)

**Comment by haydenmc** [comment] 2020-08-30 06:55
Received a store update for Windows Terminal today and things seem happy again for my situation.

**Comment by stmax82** [comment] 2020-09-09 21:51
When I enter wt in the address bar of Windows Explorer it opens wt, but in the wrong directory (C:\Users\<username>). Expected behavior: The Windows Terminal opens in the current directory, like powershell and cmd do.

**Comment by AltitudeApps** [comment] 2020-09-09 22:04
@stmax82    You might already know this, but to get the behavior you want, you can do one of:

-  `wt -d .`  
- `wt --startingDirectory .`
- `wt new-tab -d .`   
- `wt new-tab --startingDirectory .`

These all mean exactly the same thing.

`-d` is an alias for `-startingDirectory`, and `new-tab` is the default argument to `wt.exe`, when the user does not provide an argument.

**Comment by chiniara** [comment] 2020-10-21 03:29
Im having this problem but a different error and nothing in this issue solved it.

![image](https://user-images.githubusercontent.com/6012227/96669824-65147a00-1334-11eb-8470-9eeb7efa9ab1.png)

Any ideas?

**Comment by KyleCrowley** [comment] 2020-11-11 18:04
As I mentioned [here](https://github.com/microsoft/terminal/issues/7081#issuecomment-724972410), I'm also running into the same issue, and it seems many others are as well.

I installed Windows Terminal via chocolatey (I can't install via the Windows Store due to organization restrictions) a few months ago and it had been working fine until recently, as it fails to launch with the [same error message](https://github.com/microsoft/terminal/issues/7188#issuecomment-713273826) that @chiniara received.

I've tried reinstalling and resetting permissions on `C:\Program Files\WindowsApps`, but nothing seems to be working.

**Comment by xal1983** [comment] 2021-01-20 22:33
I agree, being able to run "wt" and open in the current directory would be ideal. This works if you run cmd or powershell.

**Comment by zadjii-msft** [comment] 2021-01-20 22:43
@xal1983 You're looking for `wt -d .`, and #878. This issue is tracking a totally other issue where the OS seemingly invokes the wrong thing, and causes some other unexpected failures. _Generally_, `wt -d .` in the explorer address bar _should_ work.

**Comment by junschoi** [comment] 2021-03-07 23:42
> Im having this problem but its a different error and nothing in this issue solved it. I don't have preview installed
> 
> ![image](https://user-images.githubusercontent.com/6012227/96669824-65147a00-1334-11eb-8470-9eeb7efa9ab1.png)
> 
> Any ideas?
> 
> When i run from the start menu it works fine, its just when i try to run using `wt.exe`
> It also ran fine before, it started doing that a few days ago

Not sure if this will work for you, but what I did was I removed this path under System Variables `C:\Windows\system32\config\systemprofile\AppData\Local\Microsoft\WindowsApps` and added `%USERPROFILE%\AppData\Local\Microsoft\WindowsApps` under User Variables. 0xc0000022 error went away and I was able to use wt command in Windows Explorer.

**Comment by blackrek** [comment] 2021-03-08 05:48
previously I fixed it by uninstalling from store and installing via choco. after installing the preview, the problem appeared again

**Comment by DHowett** [comment] 2021-03-11 20:35
I believe that this is, _in part_, due to #9452. If any of you are still running into this issue, would you mind following the reporting steps over there?

@KalleOlaviNiemitalo - I reported your app paths findings to the app deployment team as mentioned above and have not heard back in some time. Discussions still unfolding I guess.

**Comment by junksheng** [comment] 2021-05-29 14:09
when I write `wt` in win+r or directory, it warning me "the system can't find the wt.exe", but the wt.exe exist.  and i can turn on in menu.

**Comment by viceice** [comment] 2021-05-30 09:41
I need to disable and enable alias after latest terminal update, because it couldn't find when running wt from explorer path input 😕

**Comment by JorgenSmith** [comment] 2021-05-31 03:30
> I need to disable and enable alias after latest terminal update, because it couldn't find when running wt from explorer path input 😕

Can confirm; that did the trick for me. (Thanks for posting about App Execution Aliases, Kalle). 

I have a bat file running it linked up as Streamdeck shortcut (they're a brilliant macro launcher for dev!) and couldn't figure out why it stopped working; a reboot actually resolved it temporarily last week, then it stopped working again today.

**Comment by jogerj** [comment] 2021-06-06 02:24
> I need to disable and enable alias after latest terminal update, because it couldn't find when running wt from explorer path input 😕

This fixed my issue. 

[As referenced above by Kalle](https://github.com/microsoft/terminal/issues/7188#issuecomment-669046854), the path is defined in the registry keys for "App Paths". There was a discrepancy where the path pointed to a previously installed version of wt `C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_1.8.1444.0_x64__8wekyb3d8bbwe>` when actually the app was updated so the correct path would be `C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_1.8.1521.0_x64__8wekyb3d8bbwe>`. Re-enabling wt.exe under 'App execution aliases' settings fixed it.

**Comment by jogerj** [comment] 2021-06-06 02:28
> I need to disable and enable alias after latest terminal update, because it couldn't find when running wt from explorer path input 😕

Also experienced this from a recent update and this solution worked for me.

[As explained above by Kalle](https://github.com/microsoft/terminal/issues/7188#issuecomment-669046854), the path is defined in the registry keys for "App Paths". There was a discrepancy where the path pointed to a previously installed version of wt `C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_1.8.1444.0_x64__8wekyb3d8bbwe>` when actually the app was updated so the correct path would be `C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_1.8.1521.0_x64__8wekyb3d8bbwe>`. Re-enabling wt.exe under 'App execution aliases' settings fixed it.

So most likely somehow the update was installed without updating the correct path.

**Comment by viceice** [comment] 2021-06-07 06:47
For me the store updated it in background while an older version was running. Then I found this issue and tried the re-enable which works.

**Comment by jogerj** [comment] 2021-06-07 08:39
> For me the store updated it in background while an older version was running. Then I found this issue and tried the re-enable which works.

This might've been the cause for me. I've been running some scripts on wt non-stop for a couple of days until i closed wt and suddenly can't open it from run again

**Comment by Jaiganeshkumaran** [comment] 2021-06-22 09:25
wt works for me but it doesn't seem to launch in the current working directory but the Open in Windows Terminal option opens in the current working directory.

**Comment by jnyanez** [comment] 2021-08-09 15:24
Toggling "Windows Terminal" under Application Aliases as @zadjii-msft pointed out fixed my issue of not being able to launch wt.exe.

**Comment by liudonghua123** [comment] 2022-03-12 07:36
Maybe you can try and check the steps on https://github.com/microsoft/terminal/issues/7081#issuecomment-1065833836.

**Comment by zadjii-msft** [comment] 2022-07-28 15:07
notes from internal bug: This should have been fixed in OS build 21307, which I think should have been released in Windows 11 RTM (alas, build numbers got confusing right around then)

**Comment by zadjii-msft** [comment] 2022-07-28 15:12
Anyone who was seeing this before on Windows 10, and has since updated to Windows 11 - are you still seeing this?

**Closed** 2022-08-04 19:03 UTC
Labels: Needs-Author-Feedback, No-Recent-Activity, Product-Terminal, Tracking-External, Culprit-Centennial

**Comment by Welding-Torch** [comment] 2023-10-28 00:18
Typing `wt` does not work for me in Run (Start+R) or Windows Explorer, but it does work when I type `wt` in cmd. Disabling and enabling the alias in alias settings had no effect.
