### ISSUE TITLE
[Feature ] Missing Hotkeys? Navigation between split-views ⌨️

### ISSUE THREAD

**Issue by martinandersen3d** [microsoft/terminal#5507] opened 2020-04-23 19:56 UTC
# Description of the new feature/enhancement
There are nice hotkeys to split view
```    
{ "command": "splitVertical", "keys": ["alt+shift+v"] },
{ "command": "splitHorizontal", "keys": ["alt+shift+h"] },
``` 

**Feature:** 
After a split, we need a way to toggle or switch between the two splits. Currently the "next tab" hotkey does not work. I have not found a way to tab/navigate between two split-views.

**Suggestion: Add hotkeys to tab between a split view**
 
# Proposed technical implementation details (optional)

```    
{ "command": "focusNextSplitview", "keys": ["alt+shift+n"] }
{ "command": "focusPrevSplitview", "keys": ["alt+shift+p"] }
```    

Maybe later:
```    
{ "command": "focusSplitview1", "keys": ["alt+shift+1"] }
{ "command": "focusSplitview2", "keys": ["alt+shift+2"] }
{ "command": "focusSplitview3", "keys": ["alt+shift+3"] }
```    
maybe and option to just use the ctrl+tab.. and cycle through splits and "tabs" with the same hotkey..

Suggestions for better naming is very welcome, maybe some more consistent with other names in the application? And maybe also hotkeys suggestions..

**Comment by zadjii-msft** [comment] 2020-04-23 20:03
So there are already the following to move focus in a particular direction:
https://github.com/microsoft/terminal/blob/6ac6c875535989113d53fda89a9897fc065edb2e/src/cascadia/TerminalApp/defaults.json#L315-L318

and there's #2871 for `nextPane` and `prevPane` keybindings. I'm gonna resolve this issue as a dupe of that thread for now - let me know if that's not what you were looking for.

/dup #2871

**Closed by zadjii-msft** 2020-04-23 20:03 UTC
Labels: Issue-Feature, Needs-Tag-Fix, Needs-Triage
