### ISSUE TITLE
Terminal Preview Hangs after Reconnecting to DevBox

### ISSUE THREAD

**Issue by wmmc88** [microsoft/terminal#17545] opened 2024-07-10 22:44 UTC
### Windows Terminal version

1.21.1772.0

### Windows build number

10.0.26120.0

### Other Software

On Host:
Windows App Version 1.3.252.0

### Steps to reproduce

1. Use Windows App to connect to a [Windows Dev Box](https://devbox.microsoft.com/)
2. Open a Windows Terminal
3. Close the Dev Box Session (click X)
4. Use Windows App to reconnect to the Dev Box
5. Terminal is now not responding/hung.

### Expected Behavior

This should just work and not hang. This currenlty works with non-preview Windows Terminal (Version: 1.20.11781.0). This also used to work with preview version until recently. This makes me believe that this is a regression in a recent preview build

### Actual Behavior

Terminal is not responding. Requires Task Manager to kill process and restart it.

**Comment by lhecker** [comment] 2024-07-11 19:42
> This also used to work with preview version until recently.

Do you have an approximate guess how recently? (To narrow down the versions that may have regressed this.)

**Comment by lhecker** [comment] 2024-07-17 21:54
We'll close this as a duplicate of #17202 for now, which is effectively the same bug. If you find anything else about this, please feel free to comment in that other issue! 🙂

/dup #17202

**Closed** 2024-07-17 21:54 UTC
Labels: Issue-Bug
