### ISSUE TITLE
Extra space cell inserted after unicode character

### ISSUE THREAD

**Issue by willmcgugan** [microsoft/terminal#6162] opened 2020-05-23 13:51 UTC
# Environment

```none
Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.18363.0 Microsoft Windows NT 10.0.18363.0

Terminal v1.0.1401.0
```

# Steps to reproduce

Write the following string to the terminal (Python):

```
>>> print("│\x1b[33m\U0001F862\x1b[0m│")
```

This string is a unicode box char,  followed by a foreground yellow escape, a [unicode arrow](https://www.fileformat.info/info/unicode/char/1f862/index.htm), a reset escape, and another box character. 

# Expected behavior

The string should render three characters: a vertical line, yellow arrow, vertical line.

# Actual behavior

There is an extra space after the arrow. 

<img width="424" alt="Screen Shot 2020-05-23 at 14 45 16" src="https://user-images.githubusercontent.com/554369/82732307-503fa600-9d04-11ea-868c-b041aab85d5f.png">

Note that this only occurs with that particular unicode character. If I replace that unicode arrow with any other character then it renders as expected.

**Comment by DHowett** [comment] 2020-05-23 19:14
This is _wild_. Through-and-through, the infrastructure believes this to be a single-cell glyphs. We're doing the right thing by the UCD, but then _when the pseudoconsole emits it_ it emits it with an additional cursor move.

```
␛[?25h|␛[33m🡢␛[m␛[1C|␍␊
                 ^^^^
                 here
```

**Comment by DHowett** [comment] 2020-05-23 19:24
(And of course, only when there's a color run break. This sound ominously related to our attribute run splitter and how it thinks the cursor moves when it splits runs.)

**Comment by j4james** [comment] 2020-05-24 01:07
I think this is actually a conhost problem - you'll see the same issue there. The conpty sequence is just trying to reproduce the state of the conhost buffer which is already incorrect.

And the color change isn't really what's triggering it - any control character will do. The state machine splits up runs of text separated by control characters. And once a run of text is written, the cursor position is moved forward the expected number of columns (which in this case is off by 1). The next run of text is then starting in the wrong position, so you get a gap.

And the reason why it's off by 1 is because the character is processed as a surrogate pair, which the `WriteCharsLegacy` function sees as two characters, thus moving forward two columns.

**Comment by lb28** [comment] 2020-12-21 12:14
I have another arrow example which I believe is related:

The [robbyrussell](https://github.com/oh-my-fish/theme-robbyrussell) prompt for zsh and fish uses the "➜" (U+279C) character.

It renders nicely (i.e. two characters wide) in the VS Code integrated terminal (irrespective of the font setting). Here I selected the first character for illustration:
![image](https://user-images.githubusercontent.com/13033130/102775266-c84e7700-438c-11eb-8984-9bcfc4c07406.png)

In MS Terminal however, it renders as a single arrow followed by space (again, with first char selected):
![image](https://user-images.githubusercontent.com/13033130/102775354-f9c74280-438c-11eb-92ed-b12d269e4dcb.png)

FWIW:
* When copying the single-character arrow from MS Terminal, I get `➜`.
* When copying the *first part* of the double-character arrow (i.e. the "stem") from VS Code, I get `➜`.
* When copying the *second part* of the double-character arrow (i.e. the "tip") from VS Code, I get ` `. (Seems to be a plain old space?)

**Comment by thchr** [comment] 2022-01-05 16:39
There's a similar issue with the `𝑝` character: sometimes, a space will be inserted after 𝑝, sometimes it won't.
Similarly, even typing `𝑝` in WSL displayed on Terminal will basically garble that whole line.

**Closed** 2023-01-18 20:26 UTC
Labels: Product-Conhost, Help Wanted, Product-Conpty, Area-Output, Issue-Bug, In-PR, Priority-2
