### ISSUE TITLE
[Feature Request] Add log support for console output

### ISSUE THREAD

**Issue by yongzhang** [microsoft/terminal#5574] opened 2020-04-26 03:12 UTC
Hi, 

MS terminal is a wonderful tool, and it would be nice to log the console output, thanks.

**Comment by j4james** [comment] 2020-04-26 09:18
If I've understood you correctly, this is probably a duplicate of #642.

**Comment by yongzhang** [comment] 2020-04-27 03:46
I think it's more like https://github.com/microsoft/terminal/issues/3044, although 3044 is also marked as duplicated.

**Comment by zadjii-msft** [comment] 2020-04-27 13:20
Largely, this is the same feature as #642. When we get around to designing and implementing #642, we'll make sure that it also covers scenarios like the one described in #3044.

Thanks!

/dup #642

**Closed by zadjii-msft** 2020-04-27 13:20 UTC
Labels: Issue-Feature, Needs-Tag-Fix, Needs-Triage
