### ISSUE TITLE
Some key combinations are missing (PowerShell)

### ISSUE THREAD

**Issue by mcx808** [microsoft/terminal#4331] opened 2020-01-22 10:28 UTC
# Description of the new feature/enhancement
Support the same key combinations as the PowerShell console: e.g. **Ctrl + Space** for autocomplete options, **Ctrl + Backspace** to delete strings

Feature parity with existing console

# Proposed technical implementation details (optional)
If the commands were added so they could be mapped it would dover the issue, but it would be better to have these as defaults.
https://github.com/microsoft/terminal/blob/master/doc/cascadia/SettingsSchema.md#implemented-commands

**Comment by zadjii-msft** [comment] 2020-01-22 14:01
So this is a  bit of a complicated problem, but it's not the Terminal's fault _entirely_ that these key combos don't work. These are both actually tracked by other discussions with more details, so I'm going to close this as a duplicate of those threads.
* <kbd>ctrl+space</kbd>: /dup #2865 
* <kbd>ctrl+bksp</kbd>: /dup #755

**Closed by zadjii-msft** 2020-01-22 14:02 UTC
Labels: Issue-Feature, Needs-Tag-Fix, Needs-Triage
