### ISSUE TITLE
Experenced visual lag when upgrade to Win 10 v2004

### ISSUE THREAD

**Issue by jasl** [microsoft/terminal#4925] opened 2020-03-15 12:43 UTC
# Environment

Win32NT 10.0.19041.0 Microsoft Windows NT 10.0.19041.0

Windows Terminal (Preview) installed from Microsoft Store, version: 0.9.433.0

Intel Core i9 9900K and Nvidia Geforce 2080 Ti (with latest driver), hardwares are powerful enough and well maintained.

# Steps to reproduce

- Upgrade to Win10 v2004 from v1909
- Open Windows Terminal

# Expected behavior

Windows Terminal should smoothy all the time

# Actual behavior

When the terminal window is the active window, I experienced a visual lag, especially when mouse moving and draging the terminal window, not smoothy clearly.

When draging the Terminal window, in TaskMgr I can see the power consumption status of Windows Terminal process from very low changing to very high quickly.

When the Terminal not the active window (e.g switch to other window or open Start menu), the lag disappeared.

This problem ONLY occured on Window Terminal, I don't see other application or Windows bundled have this problem.

**Comment by DHowett-MSFT** [comment] 2020-03-16 17:36
Are you using acrylic transparency?

**Comment by jasl** [comment] 2020-03-16 18:20
> Are you using acrylic transparency?

I guess this originally, then I tried to set transparency to 1.0 (I think this should disable acrylic effect), but lag still

**Comment by DHowett-MSFT** [comment] 2020-03-16 18:21
Unfortunately, `useAcrylic` still applies even if the opacity is `1.0`; can you try setting useAcrylic to false?

**Comment by jasl** [comment] 2020-03-16 18:26
> Unfortunately, `useAcrylic` still applies even if the opacity is `1.0`; can you try setting useAcrylic to false?

just confirmed I already set `useAcrylic` to `false`

**Comment by DHowett-MSFT** [comment] 2020-03-17 23:51
Thanks for confirming. Until proven otherwise, I'm going to call this one a /dupe of #778. Once we've optimized how many pixels we push through the GPU (which right now is "the whole screen, every single time even one of them changes"), we can talk about individual performance issues.

Thanks!

**Closed by DHowett-MSFT** 2020-03-17 23:51 UTC
Labels: Needs-Attention, Needs-Tag-Fix, Needs-Triage

**Comment by Nikita240** [comment] 2020-04-09 18:47
+1

Just upgraded Windows to 2004 insiders preview. Terminal is completely unusable now. Awful stutter and lag. 

i7-8750H and RTX 2080 Max-Q

**Comment by brian316** [comment] 2021-03-31 04:59
Lags with or without acrylic mode. Using dev version of windows insider

**Comment by alexcochran** [comment] 2021-06-29 14:38
+1

Windows Terminal stutters and lags pretty badly for me (Ryzen 9 3900X, NVIDIA 2060S, Windows 10.0.19041). GPU usage notification from NVIDIA always shows up when I start the program. I tried altering the 3D settings for the Terminal application in the NVIDIA Control Panel to only use "Fixed Refresh" (this has worked for other applications) but to no avail.
