### ISSUE TITLE
windows.h's MoveWindow() function wont resize window

### ISSUE THREAD

**Issue by fluffy-git** [microsoft/terminal#16102] opened 2023-10-05 06:46 UTC
### Windows Terminal version

1.17.11461.0

### Windows build number

10.0.22621.1992

### Other Software

A simple c programm using windows.h

```c
#include <stdio.h>
#include <stdlib.h>
#include <windows.h>

int main(){

    SetConsoleTitle("  - c2048 -  ");

    HWND wh = GetConsoleWindow();
    MoveWindow(wh, 0, 0, 340, 180, TRUE);

    return 0;

}
```

### Steps to reproduce

call the MoveWindow() function and it wont change the size

### Expected Behavior

when i call the MoveWindow() function and obviously want it to change the window size and move the window

### Actual Behavior

it didn't change the window size

**Comment by lhecker** [comment] 2023-10-05 10:56
I believe this issue could be considered a duplicate of #5094 and so I'll close it if you don't mind. /dup #5094
If you can, please leave an upvote on #5094. This helps us set our priorities.

**Comment by zadjii-msft** [comment] 2023-10-05 11:03
It might actually be more specifically /dup #13525

We really should have a list of "`GetConsoleWindow` considered harmful" somewhere 😝

**Comment by zadjii-msft** [comment] 2023-10-05 11:04
(apparently the bot is acting up)

Hi! We've identified this issue as a duplicate of another one that already exists on this Issue Tracker. This specific instance is being closed in favor of tracking the concern over on the referenced thread. Thanks for your report!

**Closed by zadjii-msft** 2023-10-05 11:04 UTC
Labels: Resolution-Duplicate, Issue-Bug, Needs-Triage
