### ISSUE TITLE
Not supposed to be able to draw a character on top of another like this!

### ISSUE THREAD

**Issue by ClaireCJS** [microsoft/terminal#18145] opened 2024-11-04 02:38 UTC
### Windows Terminal version

1.21.2911.0

### Other Software

Cygwin's echo, merely because it's an easy way to produce ANSI sequences from the command-line

### Steps to reproduce

```
c:\cygwin64\bin\echo.exe -e "❤️❤️❤️❤️❤️\033[3Dhi"
```

### Expected Behavior

I would not expect the h and the ❤ to both be rendered in the same space like that

![Image](https://github.com/user-attachments/assets/adfbd6a9-259a-48fb-8e1b-863ba14bbadc)

### Actual Behavior

never seen a character drawn over another like this in my life?

![Image](https://github.com/user-attachments/assets/49260fe3-38d3-4c0f-b055-9bc2af01db7f)

**Comment by ClaireCJS** [comment] 2024-11-04 02:39
(Possible duplicate of #18143 if they are caused by the same issue)

**Comment by lhecker** [comment] 2024-11-04 13:46
Yes, they're caused by the same "issue". I'll explain it over there, in the other issue and close this one.

**Closed by lhecker** 2024-11-04 13:46 UTC
Labels: Issue-Bug, Needs-Triage
