### ISSUE TITLE
Vim in Tmux shows extra space in the line marked with icon

### ISSUE THREAD

**Issue by desperadoshi** [microsoft/terminal#6236] opened 2020-05-28 11:14 UTC
# Environment

Windows build number:

```
Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.19041.0 Microsoft Windows NT 10.0.19041.0
```

Windows Terminal version: `1.0.1401.0`

OpenSSH version:

```
OpenSSH_for_Windows_8.1p1, LibreSSL 2.9.2
```

Vim version:

```
VIM - Vi IMproved 8.1 (2018 May 18, compiled Nov 14 2019 10:34:09)
```

Tmux version:

```
2.9
```

# Steps to reproduce

1. Open Windows Terminal
2. ssh to a CentOS 7 server
3. start tmux
4. Inside tmux, start vim
5. Use vim plugin vim-bookmark to mark a line. The marker is an Emoji. The Unicode of this Emoji is U+1F4CC.
6. You can see strange rendering of this marked line.

# Expected behavior

Use Vim to open a file without Tmux. Marking a line gives the expected behavior.

![expected](https://user-images.githubusercontent.com/9106886/83134412-e7e33100-a116-11ea-8e66-9dd47b025778.jpg)

# Actual behavior

![bug](https://user-images.githubusercontent.com/9106886/83134432-ef0a3f00-a116-11ea-9dac-2a1dca21e1bb.jpg)

Look at the line 801 and 834. The word do is changed to doo. The work vol_all is changed to vol_alll.

A similar issue was reported in #5947 . But without Tmux.

**Comment by jdebp** [comment] 2020-05-28 18:10
The [default sign in the VIM bookmarks extension](https://github.com/MattesGroeger/vim-bookmarks/blob/3adeae10639edcba29ea80dafa1c58cf545cb80e/plugin/bookmark.vim#L23) is U+2691, which clearly this is not.  You will help the Microsoft people by telling them what character you have customized your bookmark sign to.  This is not least so that they can determine who is disagreeing with whom about character widths.

**Comment by desperadoshi** [comment] 2020-05-29 03:10
> The [default sign in the VIM bookmarks extension](https://github.com/MattesGroeger/vim-bookmarks/blob/3adeae10639edcba29ea80dafa1c58cf545cb80e/plugin/bookmark.vim#L23) is U+2691, which clearly this is not. You will help the Microsoft people by telling them what character you have customized your bookmark sign to. This is not least so that they can determine who is disagreeing with whom about character widths.

After changing to the default sign U+2691, it looks good. The sign U+1F4CC is the key.

**Comment by ankitbhatia** [comment] 2020-05-29 21:39
- `nvim --version`: 0.4.3
- `vim -u DEFAULTS` (version: ) behaves differently?
no
- Operating system/version: Windows 10/WSL2 -- Ubuntu 20.04
- Terminal name/version:
- `$TERM`: Microsoft Terminal Version: 1.0.1402.0

### Steps to reproduce using `nvim -u NORC`
[test.txt](https://github.com/neovim/neovim/files/4665273/test.txt)
load this file with nvim -u NORC test.txt in any wsl terminal on windows. 
```
nvim -u NORC

```

### Actual behaviour
When the cursor moves inside the parenthesis, the text shifts by one character. 
![image](https://user-images.githubusercontent.com/3687273/82616099-47cb5c00-9b9a-11ea-9111-3b13da7e2159.png)
![image](https://user-images.githubusercontent.com/3687273/82616166-747f7380-9b9a-11ea-89db-385d5f172bd7.png)


### Expected behaviour
Text should not shift by one character. 

This is not a problem when running on an actual ubuntu distribution.

**Comment by DHowett** [comment] 2020-06-02 00:51
This is an unfortunate side effect of the application and the terminal disagreeing on how wide a character should be. Our character widths are reasonably up-to-date as of Unicode 13.0, so I'm just going to have to close this one by design with a hat tip to the terminal working group discussion about character widths[1] :smile:

[1] https://gitlab.freedesktop.org/terminal-wg/specifications/-/issues/9

**Closed by DHowett** 2020-06-02 00:51 UTC
Labels: Needs-Attention, Needs-Tag-Fix, Needs-Triage
