### ISSUE TITLE
splitpane does not inherit parent environment variables.

### ISSUE THREAD

**Issue by 9527KGG** [microsoft/terminal#5624] opened 2020-04-28 17:51 UTC
# Environment

```none
Windows build number: 10.0.18363.778
Windows Terminal version (if applicable): latest 

Any other software? VS.
```

# Steps to reproduce
Add these setting to settings.json
        { "command": { "action": "splitPane", "split": "horizontal"}, "keys": "alt+," },
        { "command": { "action": "splitPane", "split": "vertical"}, "keys": "alt+." },

Press "alt+." to split

# Expected behavior

The split pane should inherit parent environment variables.

# Actual behavior

splitpane does not inherit parent environment variables.

Notes:

I think this is a bug because "alt-shift-d" split can inherit parent environment variables.

So 
        { "command": { "action": "splitPane", "split": "horizontal"}, "keys": "alt+," },
        { "command": { "action": "splitPane", "split": "vertical"}, "keys": "alt+." },

should inherit parent environment variables too.

**Comment by DHowett-MSFT** [comment] 2020-04-28 17:54
> I think this is a bug because "alt-shift-d" split can inherit parent environment variables.

We haven't written any code to make this happen, so I don't think it does.

I think this is a /dupe of #4259.

**Closed by DHowett-MSFT** 2020-04-28 17:54 UTC
Labels: Needs-Tag-Fix, Needs-Triage
