### ISSUE TITLE
Some of the extended Unicode characters are rendered with incorrect size and placement

### ISSUE THREAD

**Issue by vblazhkun** [microsoft/terminal#6738] opened 2020-06-30 22:18 UTC
# Environment

```none
Windows build number: 10.0.18363.0
Windows Terminal version (if applicable): 1.1.1671.0

Any other software?

- WSL Ubuntu 20.04 LTS

- The font is PragmataPro Mono Liga v.0.828.
```

# Steps to reproduce

Some of the extended Unicode characters are rendered with incorrect size and placement (i.e. the lower-left corner of the cell). As an example the char `✽` (0xE29CBD).

# Expected behavior

![image](https://user-images.githubusercontent.com/7956686/86181751-4a28ba80-bb37-11ea-8d65-2d52770595dc.png)

# Actual behavior

![image](https://user-images.githubusercontent.com/7956686/86182045-db982c80-bb37-11ea-931f-03746b2116bf.png)

**Comment by DHowett** [comment] 2020-06-30 22:23
According to Unicode 13.0, `U+273D HEAVY TEARDROP-SPOKED ASTERISK` is ambiguous width, non-emoji, non-emoji-presentation -- that means that it is narrow, and will always be narrow, in compliant terminals. If your font specifies that it is larger than one monospaced cell in width, it is time to fix your font. :smile:

**Comment by DHowett** [comment] 2020-06-30 22:25
(as an example, this behaviour is not recapitulated in the font I have set right now:

![image](https://user-images.githubusercontent.com/189190/86183008-eb872080-bae5-11ea-817f-5061bc5a1f00.png)

)

**Comment by vblazhkun** [comment] 2020-06-30 22:27
> According to Unicode 13.0, `U+273D HEAVY TEARDROP-SPOKED ASTERISK` is ambiguous width, non-emoji, non-emoji-presentation -- that means that it is narrow, and will always be narrow, in compliant terminals. If your font specifies that it is larger than one monospaced cell in width, it is time to fix your font. 😄

It occupies exactly one cell (i.e. it is narrow). But, the Notepad and other terminals render it correctly (within a single cell as demonstrated on the initial picture).

**Comment by vblazhkun** [comment] 2020-06-30 22:32
@DHowett Actually, even the earlier releases of the WT demonstrated the correct rendering behavior. I believe it is a bug.

**Comment by vblazhkun** [comment] 2020-06-30 22:37
A quick snip from ConEmu:

![image](https://user-images.githubusercontent.com/7956686/86183744-5dd62000-bb3b-11ea-87d0-7d5cfac9ce6d.png)

**Comment by DHowett** [comment] 2020-06-30 22:38
fair enough

**Comment by lhecker** [comment] 2022-09-14 13:34
This appears to be fixed with AtlasEngine:
![image](https://user-images.githubusercontent.com/2256941/190168169-ba2ea695-14c4-4c21-be62-5044d772b292.png)

Please let me know if this issue still appears for you in Windows Terminal Preview 1.16.

**Closed by lhecker** 2022-09-14 13:34 UTC
Labels: Area-Rendering, Area-Fonts, Issue-Bug, Product-Terminal, Priority-3

**Comment by vblazhkun** [comment] 2022-09-14 20:41
> This appears to be fixed with AtlasEngine: ![image](https://user-images.githubusercontent.com/2256941/190168169-ba2ea695-14c4-4c21-be62-5044d772b292.png)
> 
> Please let me know if this issue still appears for you in Windows Terminal Preview 1.16.

The original issue is fixed however there is a new one. The given character `U+273D HEAVY TEARDROP-SPOKED ASTERISK` is always rendered with `white` foreground color despite the WT color scheme or surrounding ANSI escape sequences (such is actually visible on your screenshot as well). I will open a new issue describing that.

![Screenshot 2022-09-14 234030](https://user-images.githubusercontent.com/7956686/190257972-fbfa4581-d76d-4900-9bf2-b95fb8ecb24c.png)

**Comment by lhecker** [comment] 2022-09-14 20:48
Thanks! Coincidentally I was just talking about this exact issue elsewhere like 5 minutes ago. 😅
It is caused by this code:
https://github.com/microsoft/terminal/blob/71fc4b1b0aee812bc7368c0b62a96018cb9fce86/src/renderer/atlas/AtlasEngine.cpp#L1506-L1530

Thank you for opening another issue! I'll try to fix it... somehow. 🥲

**Comment by Zx-EvM** [comment] 2022-09-15 09:30
In the previous version of terminal the icons definitely were larger (more proportional) than now:

![WT_Screenshot](https://user-images.githubusercontent.com/20873402/190368307-cbcff590-0f2c-4153-b4a9-cd08f88044d9.png)

WT 1.16.2523.0

**Comment by vblazhkun** [comment] 2024-11-20 20:01
> This appears to be fixed with AtlasEngine: ![image](https://user-images.githubusercontent.com/2256941/190168169-ba2ea695-14c4-4c21-be62-5044d772b292.png)
> 
> Please let me know if this issue still appears for you in Windows Terminal Preview 1.16.

It seems, there is a regression with the wide characters rendering (WTP Version: 1.22.3232.0). Right side of the double-width character collides with the next one. Attaching the example (tested with both Grapheme clusters and wcwidth):

![Image](https://github.com/user-attachments/assets/585ae090-153f-427b-a5ea-99c7a3298e7f)

**Comment by DHowett** [comment] 2024-11-20 20:17
Indeed we have determined that -- for proper support of all languages -- glyphs that extend outside the boundaries of their cells *must* be preserved and not shrunk.

That's a very nice font you're using. The folks who made it might be willing to add a right-sized glyph for that character. :)

**Comment by vblazhkun** [comment] 2024-11-20 21:16
Thank you for the prompt response! I am not really sure what you mean by "making right-sized glyph" as the given character occupies 2 cells exactly and fits their boundaries:

![Image](https://github.com/user-attachments/assets/2a67b366-a9f6-41bc-983d-6b57bf5636f6)

Also, Word renders it correctly:

![Image](https://github.com/user-attachments/assets/a8ad1b99-c0f6-418d-8150-60e7b57ba016)

**Comment by DHowett** [comment] 2024-11-20 23:07
> According to Unicode 13.0, `U+273D HEAVY TEARDROP-SPOKED ASTERISK` is ambiguous width, non-emoji, non-emoji-presentation -- that means that it is narrow, and will always be narrow, in compliant terminals. If your font specifies that it is larger than one monospaced cell in width, it is time to fix your font. 😄

What I mean is this. The glyph is effectively _required_ in all terminal emulators to _physically occupy_ one cell, even if the rendering shows it as taking more than one cell.

We've learned a lot since this issue was originally created, but the result is the same.

The glyph can be larger than a single cell (and if the font says it must be, it must be, for the aforementioned language reasons) but the text in the cells next to it also have to go in _their own_ cells too.

A terminal is strictly grid-based.
If the fancy star occupies cell 0,0 and spills over into cell 0,1 it can't just push the character from cell 0,1 over to the right. Those cells are used for exact cursor positioning, and applications running inside a terminal can target them specifically.

A word processor is designed for proportional text, and has no requirements about cells - so Word and Notepad and every other non-grid-based editor will just nudge the characters over based on the physical rendered size of the glyph.

We just don't have that luxury, because CLI applications cannot handle that.

**Comment by vblazhkun** [comment] 2024-11-20 23:45
I see. Would it be possible to implement some (per font) mapping table assigning ambiguous-width characters to desired cell widths, so the terminal handles the positioning correctly? That is: force ✽ -- 2 cells wide, ❄ -- 3 cells wide, etc. without altering the actual rendering. This way the terminal knows the actual character width and does not skew the output thinking the cell is not occupied.

As the characters are ambiguous-width per the Unicode specification it is not fixable with the font itself as another application might not be cell-based and will render the output in an ugly fashion.

There is an option to use some escape sequences for such purpose as an alternative.

I have just found that 'mintty' tries implementing something similar: [ambiguous-width-setting](https://github.com/mintty/mintty/wiki/Tips#ambiguous-width-setting).
