### ISSUE TITLE
Nerd fonts overlap incorrectly

### ISSUE THREAD

**Issue by TheGamer1002** [microsoft/terminal#15594] opened 2023-06-23 15:09 UTC
### Windows Terminal version

1.17.11461.0

### Windows build number

10.0.22621.0

### Other Software

Technically, this can be reproduced in literally anything, but I first experienced it in the [powerlevel10k](https://github.com/romkatv/powerlevel10k) installer in wsl.

### Steps to reproduce

1. Use a nerd font that is dynamic (i.e. not mono)
2. Paste the following (gotten from powerlevel10k initialization screen): XXXXXXXXX
3. Notice that the icons do not fit between the crosses

### Expected Behavior

According to the initialization script, the icons should be very close to the crosses, but there should be no overlap.

### Actual Behavior

The icons overlap with the crosses. 
![image](https://github.com/microsoft/terminal/assets/48131223/33397c43-cd27-4448-b794-f714635b09b7)

**Comment by 237dmitry** [comment] 2023-06-23 22:59
In other terminals is the same. Tested on linux in Tilix, xfce4-terminal and alacritty.

**Comment by TheGamer1002** [comment] 2023-06-24 00:04
That's odd. I've had success with WezTerm in the past.

**Comment by lhecker** [comment] 2023-06-24 00:30
But did you use the same non-Mono (non-NFM) font in WezTerm? Because those glyphs are 2 columns wide and WezTerm defaults to simply cutting their right half off (see `allow_square_glyphs_to_overflow_width`). Most terminals I know draw these non-NFM glyphs either the way it looks like in your screenshot or cut them off to only occupy 1 column. This is why many powerline setups append a single whitespace after such glyphs. This will allow these wide glyphs to be drawn in 2 columns without any apparent overlap. If you use the NF variant, responding with "No. Some icons overlap neighbouring crosses." is completely fine and expected as far as I know.

**Comment by TheGamer1002** [comment] 2023-06-24 01:09
Hm, I suppose I stand corrected. Maybe my Linux box is using the NL variation, though in that I saw that the icons fit snugly into the crosses (the end of one X came just after the start of an icon). I might be going crazy 🙃

**Comment by lhecker** [comment] 2023-06-24 10:08
I'm fairly certain that the above rendering is expected for the non-Mono variant. I'll close the issue, but please let me know if you find any reproducible issues with it after all. 🙂

**Closed by lhecker** 2023-06-24 10:08 UTC
Labels: Issue-Bug, Needs-Triage
