### ISSUE TITLE
Unicode box drawing interline gap is visible and too sparse

### ISSUE THREAD

**Issue by vblazhkun** [microsoft/terminal#2006] opened 2019-07-17 17:35 UTC
# Environment

```none
Windows build number: [Version 10.0.18362.239]
Windows Terminal version (if applicable): 0.2.1831.0

Any other software?

WSL Ubuntu: [1804.2019.521.0]
```

# Steps to reproduce

1. Install Pragmata Pro Mono Liga 0.827 font (any other Unicode font should work as well).
2. Open the Windows Terminal with WSL Ubuntu tab.
3. Download and display the [`UTF-8 Demo Text`](https://www.cl.cam.ac.uk/~mgk25/ucs/examples/UTF-8-demo.txt).
    `$ curl https://www.cl.cam.ac.uk/~mgk25/ucs/examples/UTF-8-demo.txt`

# Expected behavior

No visible interline gap (the screenshot is from `Cmder 180626` with WLS Ubuntu):

![terminal-bug-06-1](https://user-images.githubusercontent.com/7956686/61397094-d663b280-a8d1-11e9-8e53-5c61f06459a3.png)

# Actual behavior

Visible sparse interline gap:

![terminal-bug-06-2](https://user-images.githubusercontent.com/7956686/61397038-b0d6a900-a8d1-11e9-917c-b50089e68d01.png)

**Comment by DHowett-MSFT** [comment] 2019-07-17 17:42
This is somewhat of a duplicate of #455. I'm going to move your comment over there. Thanks!

**Closed by DHowett-MSFT** 2019-07-17 17:42 UTC
Labels: Needs-Tag-Fix, Needs-Triage
