### ISSUE TITLE
Shift+Copy don't copy line break

### ISSUE THREAD

**Issue by horseinthesky** [microsoft/terminal#5222] opened 2020-04-02 15:16 UTC
# Environment
PS C:\Users\horseinthesky> [Environment]::OSVersion

Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.18363.0 Microsoft Windows NT 10.0.18363.0

Windows Terminal
Version: 0.10.781.0

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Windows Terminal version (if applicable):

Any other software?
```

# Steps to reproduce

I have the following text in my terminal window:
```
Huawei Versatile Routing Platform Software
VRP (R) software, Version 8.190 (NE40E V800R011C10SPC100)
Copyright (C) 2012-2019 Huawei Technologies Co., Ltd.
HUAWEI NE40E-F1A-14H24Q uptime is 1 day, 3 hours, 55 minutes
Patch Version: V800R011SPH021
```

If I select all of it with my mouse then copy and paste it to notepad/vscode/whatever, it will look exactly the same.

If I select a part (for example a beginning) of it with my mouse then press Shift and click a mouse to the end of the text to select then copy and paste it, it will look like this:
![image](https://user-images.githubusercontent.com/19948672/78266047-eaa61900-750d-11ea-850a-26760fc1edd2.png)

# Expected behavior

To copy line breaks.

# Actual behavior

Terminal just don't copy like breaks in this case!

**Comment by carlos-zamora** [comment] 2020-04-02 16:23
This is by design. Shift + Right Click copies the buffer without any newlines, whereas just Right Click includes the newlines.

#1553 will allow you to customize this behavior to match your liking. However, for now, you can customize `copy` keybindings to copy in the format you like ([docs here](https://github.com/microsoft/terminal/blob/master/doc/cascadia/SettingsSchema.md)).

**Comment by DHowett-MSFT** [comment] 2020-04-02 16:40
Sorry, I’m overriding on this one. It’s a real issue: the reporter is using shift+left click, not right click, to expand the selection. When copyOnSelect is enabled, shift+release strips newlines.  We have a duplicate lying around somewhere, which I’ll dig up when I get to the office.

**Comment by horseinthesky** [comment] 2020-04-02 16:45
Binding some keys for `copy` is a fine solution.
It just would be great to have it just as Shift+Left click like Putty or SecureCRT has it.
Should I close this?

**Comment by DHowett-MSFT** [comment] 2020-04-03 00:41
If you're using `copyOnSelect`, this is a /dupe of #4737

**Closed by DHowett-MSFT** 2020-04-03 00:41 UTC
Labels: Needs-Tag-Fix, Needs-Triage
