### ISSUE TITLE
Windows Terminal crashes after trying to close tabs

### ISSUE THREAD

**Issue by Qantex** [microsoft/terminal#5245] opened 2020-04-05 05:13 UTC
# Environment

```none
Windows build number: 10.0.18363.752
Windows Terminal version (if applicable): 0.10.781.0

Any other software?
```

# Steps to reproduce

- Start Windows Terminal
- Start more than 40+ tabs by pressing Ctrl and Shift + T
- Now try to close the tabs as soon as possible

# Expected behavior

- **Windows Terminal should not crash**

# Actual behavior

- **Windows Terminal crashes**

![ezgif-5-fcd68b503139](https://user-images.githubusercontent.com/47790579/78531333-81602780-77e5-11ea-8a25-3229e42c48da.gif)

**Comment by zadjii-msft** [comment] 2020-04-06 13:19
Hey could you file feedback using the Feedback hub so we could get a stack trace to investigate?

/feedback

**Comment by Qantex** [comment] 2020-04-06 17:40
@zadjii-msft Should I include the link in the comment?

**Comment by zadjii-msft** [comment] 2020-04-06 17:42
@Qantex yes please, it's basically impossible for us to find it without the link ☺️

**Comment by Qantex** [comment] 2020-04-06 17:43
https://github.com/microsoft/terminal/issues/5245

**Comment by zadjii-msft** [comment] 2020-04-06 17:51
@Qantex That's just the link to this issue, not to the feedback 😄

**Comment by Qantex** [comment] 2020-04-06 18:04
@zadjii-msft I thought you meant this section.

**Comment by DHowett-MSFT** [comment] 2020-04-06 18:08
My dude, can you do this on your feedback?

![](https://user-images.githubusercontent.com/18221333/62478649-6de55400-b760-11e9-806e-5aab7e085a9f.png)

That will make a `aka.ms` link, and then you can send that aka.ms link to us. :smile:

**Comment by Qantex** [comment] 2020-04-06 18:13
@DHowett Sure, I will now send a feedback via the feedback application.

**Comment by Qantex** [comment] 2020-04-06 18:22
@zadjii-msft Is it sufficient if I add a link in the description of the feedback application?

**Comment by DHowett-MSFT** [comment] 2020-04-06 18:27
@Qantex ...

You need to

1. Write a feedback item
2. Copy the link FROM the feedback item
3. Paste the link INTO github
4. Submit the link TO github so that we can receive the link

**Comment by Qantex** [comment] 2020-04-06 18:30
>     3\. Paste the link INTO github

@DHowett What do you mean?

**Comment by DHowett-MSFT** [comment] 2020-04-06 18:33
![image](https://user-images.githubusercontent.com/14316954/78592711-56cc9980-77fa-11ea-8947-978b0a1411a5.png)

![image](https://user-images.githubusercontent.com/14316954/78592728-5df3a780-77fa-11ea-8fe4-985b5e71ac53.png)

**Comment by Qantex** [comment] 2020-04-06 18:35
@DHowett I did it, but the other employee said I had to include it in the feedback application.

**Comment by Qantex** [comment] 2020-04-06 18:46
The feedback application **shows that the message cannot be tracked without registration**. Do I need to create a Microsoft account?
 **I will send the message tomorrow and add the link in the comments section.**

**Good night**

**Comment by Qantex** [comment] 2020-04-07 10:31
https://aka.ms/AA84d4u

**Comment by Qantex** [comment] 2020-04-07 10:35
@zadjii-msft @DHowett I have now added the link in a comment and sent it.

**Comment by DHowett-MSFT** [comment] 2020-04-07 22:17
Thank you. We will continue the investigation.

**Comment by DHowett-MSFT** [comment] 2020-04-08 00:55
I can't reproduce this in v0.11, and it looks like it might have been a /dupe of #4613.

**Comment by Qantex** [comment] 2020-04-08 07:01
@DHowett I have looked at the alleged duplicate and must say that my report is not a duplicate in my view.

> I can't reproduce this in v0.11

To see the error from its own perspective, you need to train your timing.

**Comment by DHowett-MSFT** [comment] 2020-04-08 07:34
#4613 fixed 13 different places where we would crash during the startup and shutdown of individual terminals. It is very likely, but not 100% certain, that it fixed this issue. 😄

**Closed** 2020-04-09 08:00 UTC
Labels: Product-Terminal, Resolution-Duplicate, Severity-Crash
