### ISSUE TITLE
Background color not set when paging through a document with ANSI escape sequences

### ISSUE THREAD

**Issue by ahuggel** [microsoft/terminal#5565] opened 2020-04-25 15:11 UTC
# Environment
Windows build number: Microsoft Windows [Version 10.0.18363.778]
Windows Terminal version (if applicable): 0.11.1121.0

# Steps to reproduce

Page through the attached [pentomino.txt](https://github.com/microsoft/terminal/files/4533212/pentomino.txt) file, e.g., `less -R pentomino.txt` in WSL Debian or `more pentomino.txt` in cmd. 

The file contains simple graphical representations of the solutions of a puzzle, drawn with spaces and ANSI escape sequences to vary the background color, like this:

```
ESC[105m        ESC[100m  ESC[101m        ESC[106m  ESC[49m
ESC[105m  ESC[41m  ESC[43m    ESC[100m    ESC[101m  ESC[103m  ESC[106m    ESC[49m
ESC[41m      ESC[43m    ESC[100m  ESC[103m    ESC[106m    ESC[49m
ESC[47m  ESC[41m  ESC[47m  ESC[44m  ESC[43m  ESC[100m  ESC[45m  ESC[103m    ESC[46m  ESC[49m
ESC[47m      ESC[44m      ESC[45m      ESC[46m  ESC[49m
ESC[102m          ESC[44m  ESC[45m  ESC[46m      ESC[49m
```

# Expected behavior

The horizontal bar at the beginning of the last line of the field (`ESC[102m          `) should be green.

![correct-color](https://user-images.githubusercontent.com/972802/80283023-57948380-8747-11ea-9afd-77713164118f.png)

# Actual behavior

When paging through the file, the bar is most of the time drawn in the background color instead of green. When scrolling through the file slowly with the arrow down key, the issue does not show. It only seems to happen for the green bar piece, when it is horizontal and starts in the first column.

![wrong-color](https://user-images.githubusercontent.com/972802/80283025-595e4700-8747-11ea-8822-725ccab78f26.png)

**Comment by Sandra2001** [comment] 2020-04-25 15:35
@ahuggel Good error found! 😁
### (●'◡'●) your @Sandra2001

**Comment by DHowett-MSFT** [comment] 2020-04-25 17:54
So, I got to see this with `40. Solution`; based on the debugging tap output:

```
40.␣Solution:␍␊Sat␣Apr␣25␣15:31:02␣2020␍␊␊␛[47m␣␣␣␣␣␣␛[101m␣␣␣␣␣␣␣␣␛[106m␣␣␣␣␣␣␛[m␛[K␍␊␛[47m␣␣␛[41m␣␣␛[47m␣␣␛[44m␣␣␣␣␛[101m␣␣␛[103m␣␣␛[106m␣␣␣␣␛[43m␣␣␛[m␛[K␍␊␛[41m␣␣␣␣␣␣␛[44m␣␣␛[100m␣␣␛[103m␣␣␣␣␣␣␛[43m␣␣␣␣␛[m␛[K␍␊␛[105m␣␣␛[41m␣␣␛[44m␣␣␣␣␛[100m␣␣␛[103m␣␣␛[46m␣␣␛[43m␣␣␣␣␛[45m␣␣␛[m␛[K␍␊␛[105m␣␣␣␣␣␣␣␣␛[100m␣␣␣␣␛[46m␣␣␛[45m␣␣␣␣␣␣␛[m␛[K␍␊␛[102m␛[100m␛[10C␣␣␛[46m␣␣␣␣␣␣␛[45m␣␣␛[m␛[K␍␊␊␊
```

this is a /dupe of #5502.

We're incorrectly optimizing runs of spaces that differ only in background color; evidenced by the "␛[102m␛[100m␛[10C" ("set background color to 2, 0, move 10 cells right").

**Comment by DHowett-MSFT** [comment] 2020-04-25 17:54
Thanks for the report!

**Closed by DHowett-MSFT** 2020-04-25 17:54 UTC
Labels: Needs-Tag-Fix, Needs-Triage
