### ISSUE TITLE
"copyOnSelect": false has confusing behavior when people use right click to CLEAR (nor COPY) selection?

### ISSUE THREAD

**Issue by garth** [microsoft/terminal#3053] opened 2019-10-04 10:13 UTC
# Environment

```
Microsoft Windows [Version 10.0.18995.1]
Windows Terminal version (if applicable): 0.5.2681.0

```

# Steps to reproduce

set copyOnSelect to false

# Expected behavior

1. select text
2. remove selection
3. clipboard remains unchanged

# Actual behavior

1. select text
2. remove selection
3. clipboard is overwritten with previously selected text

**Comment by zadjii-msft** [comment] 2019-10-04 13:02
@garth Can you share your `profiles.json`?

**Comment by garth** [comment] 2019-10-04 13:54
```json
{
  "$schema": "https://aka.ms/terminal-profiles-schema",
  "globals": {
    "alwaysShowTabs": true,
    "copyOnSelect": false,
    "defaultProfile": "{2c4de342-38b7-51cf-b940-2309a097f518}",
    "initialCols": 140,
    "initialRows": 40,
    "keybindings": [
      {
        "command": "closePane",
        "keys": ["ctrl+shift+w"]
      },
      {
        "command": "copy",
        "keys": ["ctrl+shift+c"]
      },
      {
        "command": "duplicateTab",
        "keys": ["ctrl+shift+d"]
      },
      {
        "command": "newTab",
        "keys": ["ctrl+shift+t"]
      },
      {
        "command": "newTabProfile0",
        "keys": ["ctrl+shift+1"]
      },
      {
        "command": "newTabProfile1",
        "keys": ["ctrl+shift+2"]
      },
      {
        "command": "newTabProfile2",
        "keys": ["ctrl+shift+3"]
      },
      {
        "command": "newTabProfile3",
        "keys": ["ctrl+shift+4"]
      },
      {
        "command": "newTabProfile4",
        "keys": ["ctrl+shift+5"]
      },
      {
        "command": "newTabProfile5",
        "keys": ["ctrl+shift+6"]
      },
      {
        "command": "newTabProfile6",
        "keys": ["ctrl+shift+7"]
      },
      {
        "command": "newTabProfile7",
        "keys": ["ctrl+shift+8"]
      },
      {
        "command": "newTabProfile8",
        "keys": ["ctrl+shift+9"]
      },
      {
        "command": "nextTab",
        "keys": ["ctrl+tab"]
      },
      {
        "command": "openNewTabDropdown",
        "keys": ["ctrl+shift+space"]
      },
      {
        "command": "openSettings",
        "keys": ["ctrl+,"]
      },
      {
        "command": "paste",
        "keys": ["ctrl+shift+v"]
      },
      {
        "command": "prevTab",
        "keys": ["ctrl+shift+tab"]
      },
      {
        "command": "scrollDown",
        "keys": ["ctrl+shift+down"]
      },
      {
        "command": "scrollDownPage",
        "keys": ["ctrl+shift+pgdn"]
      },
      {
        "command": "scrollUp",
        "keys": ["ctrl+shift+up"]
      },
      {
        "command": "scrollUpPage",
        "keys": ["ctrl+shift+pgup"]
      },
      {
        "command": "switchToTab0",
        "keys": ["ctrl+alt+1"]
      },
      {
        "command": "switchToTab1",
        "keys": ["ctrl+alt+2"]
      },
      {
        "command": "switchToTab2",
        "keys": ["ctrl+alt+3"]
      },
      {
        "command": "switchToTab3",
        "keys": ["ctrl+alt+4"]
      },
      {
        "command": "switchToTab4",
        "keys": ["ctrl+alt+5"]
      },
      {
        "command": "switchToTab5",
        "keys": ["ctrl+alt+6"]
      },
      {
        "command": "switchToTab6",
        "keys": ["ctrl+alt+7"]
      },
      {
        "command": "switchToTab7",
        "keys": ["ctrl+alt+8"]
      },
      {
        "command": "switchToTab8",
        "keys": ["ctrl+alt+9"]
      }
    ],
    "requestedTheme": "system",
    "showTabsInTitlebar": true,
    "showTerminalTitleInTitlebar": true,
    "wordDelimiters": " ./\\()\"'-:,.;<>~!@#$%^&*|+=[]{}~?\u2502"
  },
  "profiles": [
    {
      "closeOnExit": true,
      "colorScheme": "Nova",
      "commandline": "powershell.exe",
      "cursorColor": "#FFFFFF",
      "cursorShape": "bar",
      "fontFace": "Fira Code Retina",
      "fontSize": 11,
      "guid": "{61c54bbd-c2c6-5271-96e7-009a87ff44bf}",
      "historySize": 9001,
      "icon": "ms-appx:///ProfileIcons/{61c54bbd-c2c6-5271-96e7-009a87ff44bf}.png",
      "name": "Windows PowerShell",
      "padding": "10, 5, 10, 5",
      "snapOnInput": true,
      "startingDirectory": "%USERPROFILE%",
      "useAcrylic": false
    },
    {
      "closeOnExit": true,
      "colorScheme": "Nova",
      "commandline": "cmd.exe",
      "cursorColor": "#FFFFFF",
      "cursorShape": "bar",
      "fontFace": "Fira Code Retina",
      "fontSize": 11,
      "guid": "{0caa0dad-35be-5f56-a8ff-afceeeaa6101}",
      "historySize": 9001,
      "icon": "ms-appx:///ProfileIcons/{0caa0dad-35be-5f56-a8ff-afceeeaa6101}.png",
      "name": "cmd",
      "padding": "10, 5, 10, 5",
      "snapOnInput": true,
      "startingDirectory": "%USERPROFILE%",
      "useAcrylic": false
    },
    {
      "closeOnExit": false,
      "colorScheme": "Nova",
      "commandline": "Azure",
      "connectionType": "{d9fcfdfa-a479-412c-83b7-c5640e61cd62}",
      "cursorColor": "#FFFFFF",
      "cursorShape": "bar",
      "fontFace": "Fira Code Retina",
      "fontSize": 11,
      "guid": "{b453ae62-4e3d-5e58-b989-0a998ec441b8}",
      "historySize": 9001,
      "icon": "ms-appx:///ProfileIcons/{b453ae62-4e3d-5e58-b989-0a998ec441b8}.png",
      "name": "Azure Cloud Shell",
      "padding": "10, 5, 10, 5",
      "snapOnInput": true,
      "startingDirectory": "%USERPROFILE%",
      "useAcrylic": false
    },
    {
      "closeOnExit": true,
      "colorScheme": "Nova",
      "commandline": "wsl.exe -d Arch",
      "cursorColor": "#FFFFFF",
      "cursorShape": "bar",
      "fontFace": "Fira Code Retina",
      "fontSize": 11,
      "guid": "{a5a97cb8-8961-5535-816d-772efe0c6a3f}",
      "historySize": 9001,
      "icon": "ms-appx:///ProfileIcons/{9acb9455-ca41-5af7-950f-6bca1bc9722f}.png",
      "name": "Arch",
      "padding": "10, 5, 10, 5",
      "snapOnInput": true,
      "startingDirectory": "%USERPROFILE%",
      "useAcrylic": false
    },
    {
      "closeOnExit": true,
      "colorScheme": "Nova",
      "source": "Windows.Terminal.Wsl",
      "cursorColor": "#FFFFFF",
      "cursorShape": "bar",
      "fontFace": "Fira Code Retina",
      "fontSize": 11,
      "guid": "{2c4de342-38b7-51cf-b940-2309a097f518}",
      "historySize": 9001,
      "icon": "ms-appx:///ProfileIcons/{9acb9455-ca41-5af7-950f-6bca1bc9722f}.png",
      "name": "Ubuntu",
      "padding": "10, 5, 10, 5",
      "snapOnInput": true,
      "startingDirectory": "%USERPROFILE%",
      "useAcrylic": false
    }
  ],
  "schemes": [
    {
      "background": "#293238",
      "black": "#0C0C0C",
      "blue": "#83AFE5",
      "brightBlack": "#899BA6",
      "brightBlue": "#83AFE5",
      "brightCyan": "#7FC1CA",
      "brightGreen": "#A8CE93",
      "brightPurple": "#D18EC2",
      "brightRed": "#DF8C8C",
      "brightWhite": "#E6EEF3",
      "brightYellow": "#DADA93",
      "cyan": "#7FC1CA",
      "foreground": "#C5D4DD",
      "green": "#A8CE93",
      "name": "Nova",
      "purple": "#9A93E1",
      "red": "#DF8C8C",
      "white": "#C5D4DD",
      "yellow": "#DADA93"
    },
    {
      "background": "#0C0C0C",
      "black": "#0C0C0C",
      "blue": "#0037DA",
      "brightBlack": "#767676",
      "brightBlue": "#3B78FF",
      "brightCyan": "#61D6D6",
      "brightGreen": "#16C60C",
      "brightPurple": "#B4009E",
      "brightRed": "#E74856",
      "brightWhite": "#F2F2F2",
      "brightYellow": "#F9F1A5",
      "cyan": "#3A96DD",
      "foreground": "#CCCCCC",
      "green": "#13A10E",
      "name": "Campbell",
      "purple": "#881798",
      "red": "#C50F1F",
      "white": "#CCCCCC",
      "yellow": "#C19C00"
    },
    {
      "background": "#000000",
      "black": "#000000",
      "blue": "#000080",
      "brightBlack": "#808080",
      "brightBlue": "#0000FF",
      "brightCyan": "#00FFFF",
      "brightGreen": "#00FF00",
      "brightPurple": "#FF00FF",
      "brightRed": "#FF0000",
      "brightWhite": "#FFFFFF",
      "brightYellow": "#FFFF00",
      "cyan": "#008080",
      "foreground": "#C0C0C0",
      "green": "#008000",
      "name": "Vintage",
      "purple": "#800080",
      "red": "#800000",
      "white": "#C0C0C0",
      "yellow": "#808000"
    },
    {
      "background": "#282C34",
      "black": "#282C34",
      "blue": "#61AFEF",
      "brightBlack": "#5A6374",
      "brightBlue": "#61AFEF",
      "brightCyan": "#56B6C2",
      "brightGreen": "#98C379",
      "brightPurple": "#C678DD",
      "brightRed": "#E06C75",
      "brightWhite": "#DCDFE4",
      "brightYellow": "#E5C07B",
      "cyan": "#56B6C2",
      "foreground": "#DCDFE4",
      "green": "#98C379",
      "name": "One Half Dark",
      "purple": "#C678DD",
      "red": "#E06C75",
      "white": "#DCDFE4",
      "yellow": "#E5C07B"
    },
    {
      "background": "#FAFAFA",
      "black": "#383A42",
      "blue": "#0184BC",
      "brightBlack": "#4F525D",
      "brightBlue": "#61AFEF",
      "brightCyan": "#56B5C1",
      "brightGreen": "#98C379",
      "brightPurple": "#C577DD",
      "brightRed": "#DF6C75",
      "brightWhite": "#FFFFFF",
      "brightYellow": "#E4C07A",
      "cyan": "#0997B3",
      "foreground": "#383A42",
      "green": "#50A14F",
      "name": "One Half Light",
      "purple": "#A626A4",
      "red": "#E45649",
      "white": "#FAFAFA",
      "yellow": "#C18301"
    },
    {
      "background": "#002B36",
      "black": "#073642",
      "blue": "#268BD2",
      "brightBlack": "#002B36",
      "brightBlue": "#839496",
      "brightCyan": "#93A1A1",
      "brightGreen": "#586E75",
      "brightPurple": "#6C71C4",
      "brightRed": "#CB4B16",
      "brightWhite": "#FDF6E3",
      "brightYellow": "#657B83",
      "cyan": "#2AA198",
      "foreground": "#839496",
      "green": "#859900",
      "name": "Solarized Dark",
      "purple": "#D33682",
      "red": "#DC322F",
      "white": "#EEE8D5",
      "yellow": "#B58900"
    },
    {
      "background": "#FDF6E3",
      "black": "#073642",
      "blue": "#268BD2",
      "brightBlack": "#002B36",
      "brightBlue": "#839496",
      "brightCyan": "#93A1A1",
      "brightGreen": "#586E75",
      "brightPurple": "#6C71C4",
      "brightRed": "#CB4B16",
      "brightWhite": "#FDF6E3",
      "brightYellow": "#657B83",
      "cyan": "#2AA198",
      "foreground": "#657B83",
      "green": "#859900",
      "name": "Solarized Light",
      "purple": "#D33682",
      "red": "#DC322F",
      "white": "#EEE8D5",
      "yellow": "#B58900"
    }
  ]
}
```

**Comment by DHowett-MSFT** [comment] 2019-10-07 23:13
Interesting. Nothing out of the ordinary there.

So that we can better reproduce this bug, can you help us out by telling us exactly how you're performing the "remove selection" operation?
Thanks!

**Comment by garth** [comment] 2019-10-07 23:24
Using a right click (two finder tap):

- click on a char, right click, char was copied to clipboard.
or
- select a number of chars, right click, selected chars are copied to clipboard.

A right click, when there is no selection, will also paste what's on the clipboard, but this is not so critical is it's not usually a destructive operation.

**Comment by DHowett-MSFT** [comment] 2019-10-07 23:33
Oh! In that case! Sorry, this is somewhere our documentation is quite lacking.

Right clicking when a selection is active is the premier way to activate _copy_. We've talked a bit about supporting mouse rebinding (#1553), but it's not in scope for version 1.

**Comment by DHowett-MSFT** [comment] 2019-10-07 23:33
(A good way to clear the selection is <kbd>Esc</kbd>, but that's also not terrifically discoverable.)

**Comment by garth** [comment] 2019-10-07 23:38
With copyOnSelect set to false, I would expect this to be disabled. I am constantly loosing critical content from from clipboard due to accidentally tapping on the touch pad.

This is even more of an issue when a single tap will select a single char or even white space.

**Comment by DHowett-MSFT** [comment] 2019-10-07 23:44
`copyOnSelect` controls whether the selection is stored to the clipboard _when it is selected_, as opposed to making it require affirmative assenting action (right clicking, <kbd>Ctrl+Shift+C</kbd>). 
I agree with you about single character selection making this worse, but we get shouted at on the regular when we try to take away _that_ specific feature. ☹️

**Comment by garth** [comment] 2019-10-07 23:50
OK, but coming from a MacOS/Linux background, trying out windows with WSL2, this is just not expected behaviour.

I even went so far as to try out Hyper terminal to avoid this issue, but whilst it doesn't have this problem is has other issues.

**Comment by DHowett-MSFT** [comment] 2019-10-23 20:43
Thanks for the feedback about your expected behavior. We're happy to continue the discussion about our boundary between expected/desired and how that plays off of users' understanding of the legacy Windows console here, but I'm going to close the issue since it seems like it was resolved.

Sorry :smile:

**Closed** 2019-10-28 14:17 UTC
Labels: Needs-Attention, Needs-Tag-Fix, Resolution-By-Design
