### ISSUE TITLE
Terminal gets blank after dragging somewhere

### ISSUE THREAD

**Issue by 0warning0error** [microsoft/terminal#2220] opened 2019-08-03 14:18 UTC
# Environment

```none
Windows build number: win10 1903(18362.239)
Windows Terminal version (if applicable): 0.3.2142.0(from Microsoft Store)

```

# Steps to reproduce

Start this application and drag it somewhere

# Expected behavior

Nothing happened

# Actual behavior

this window got blank and can't be input
![image](https://user-images.githubusercontent.com/42114116/62412999-98d68780-b63c-11e9-9eaf-0784f6374089.png)

**Comment by TayYuanGeng** [comment] 2019-08-03 17:31
This is the same as #2217

**Comment by zadjii-msft** [comment] 2019-08-05 12:24
This is definitely a dupe of #2217. Let's pile in there and try to get this figured out.

**Closed by zadjii-msft** 2019-08-05 12:24 UTC
Labels: Needs-Tag-Fix, Needs-Triage
