### ISSUE TITLE
Black powerline / nerd font glyphs

### ISSUE THREAD

**Issue by withinboredom** [microsoft/terminal#15489] opened 2023-05-31 19:25 UTC
### Windows Terminal version

1.18.1462.0

### Windows build number

10.0.22621.0

### Other Software

Zsh -- powerlevel10k theme (WSL): https://github.com/romkatv/powerlevel10k

Font: MesloLGS NF

### Steps to reproduce

Between 1.16.10262.0 and the reported version, something changed in the renderer causing fonts to render differently. This appears to be minor, though perhaps could make other languages (with non-latin alphabets) harder to read.

Previous:

<img width="841" alt="image" src="https://github.com/microsoft/terminal/assets/1883296/bd325456-344d-4367-884f-bb02d26ecdba">

Current:

<img width="860" alt="image" src="https://github.com/microsoft/terminal/assets/1883296/6b474900-4f75-47e8-91dc-625f8f287341">

Note the cutoff on the slashed characters.

The best way to reproduce this is to start the `p10k configure` command to have it present many different renderings with a strange font.

### Expected Behavior

For characters to be rendered as expected.

### Actual Behavior

Some characters appear to be rendered incorrectly.

**Comment by withinboredom** [comment] 2023-05-31 19:26
Originally reported in a comment: https://github.com/microsoft/terminal/issues/15416#issuecomment-1570783205

**Comment by lhecker** [comment] 2023-05-31 19:39
Like this?
![image](https://github.com/microsoft/terminal/assets/2256941/f37903e5-cfca-4127-8eb8-0a91b457b48e)

That doesn't seem wrong to me. Can you please describe what font family and what order of 1234/y/n presses I have to use to arrive at a prompt in `p10k configure` that reproduces the issue?

**Comment by DHowett** [comment] 2023-05-31 20:02
I think it's this: 
<img width="38" alt="image" src="https://github.com/microsoft/terminal/assets/189190/ae94fca3-6070-4484-9a24-c9d57b763854">

Can you try turning off "Adjust lightness of indistinguishable text"?

**Comment by thijsputman** [comment] 2023-06-02 09:01
It appears I'm running into a related issue (either to this, or #15416) when rendering this character in the terminal:

```
▔ (U+2594)
```

When trying to display this character, nothing is shown. Worked fine in the past; noticed the issue a couple days ago.

When I _disable_ the `AtlasEngine`, the character shows up as intended.

The issue only occurs when using `Cascadia Code PL`, _not_ with (for example) `Consolas`. Not sure if it matters, but my font size is set to 10 and line height to 1.2.

Running the latest preview build ([v1.18.1462.0](https://github.com/microsoft/terminal/releases/tag/v1.18.1462.0)).

**Comment by DHowett** [comment] 2023-06-02 16:41
That is definitely not the same issue, but I do know what it is.

@lhecker `U+2594` is completely outside the cell _in Cascadia Code_.

This could be argued to be a font bug.

<img width="51" alt="image" src="https://github.com/microsoft/terminal/assets/189190/f679638c-f200-4b73-bcd6-e20cc8abaeb0">

The lighted cell is a selection (1x cell height); `U+2594` is to the left of it.

We're clipping all box drawing glyphs to keep them inside the cell. . . and deleting the glyph completely in so doing.

**Comment by withinboredom** [comment] 2023-06-02 21:48
Turns out it is a relatively easy fix, @DHowett suggested:

<img width="747" alt="image" src="https://github.com/microsoft/terminal/assets/1883296/5bd9d374-cbcf-4eef-8b32-5792c5bebe27">

Things still look a little off, but iff it isn't on the first line:

<img width="110" alt="image" src="https://github.com/microsoft/terminal/assets/1883296/c58ac29c-133a-4d0e-8bfb-38030141ae5b">

If it is on the very first line of the terminal, the prompt looks correct.

**Comment by zadjii-msft** [comment] 2023-07-12 11:58
Hey, to go clean up this thread: 
* The issue in the OP was solved by turning off "Adjust lightness of indistinguishable text", yea? 
* There's a related issue about "clipping box drawing characters" which we may or may not want to keep doing. But that we should track in #15359 (et al)


So, I _think_ we can close this now? Sound good?

**Comment by lhecker** [comment] 2023-07-12 12:23
Yep, I think we can close this now. 🙂
The small inconsistency in the glyph height (https://github.com/microsoft/terminal/issues/15489#issuecomment-1574353691) is most certainly due to rounding errors, etc., caused by the font and font size and not something we have any big influence over.

**Closed by lhecker** 2023-07-12 12:23 UTC
Labels: Issue-Bug, Needs-Triage, Needs-Attention
