### ISSUE TITLE
more “question marks” on emoj string end than hope

### ISSUE THREAD

**Issue by chuanjiao10** [microsoft/terminal#3270] opened 2019-10-21 09:37 UTC
# Environment

powershell 5.1 on win10-1903 ,powershell 6.2.3 on  win10-1903
Windows Terminal (Preview) Version: 0.5.2762.0

# Steps to reproduce
powershell code, 
```
Write-Host '🀎'
```

# Expected behavior
no '?' end of '🀎'

# Actual behavior
**file 'a.ps1'   is utf16le char with BOM**
powershell 5.1 on win10-1903 ,
![image](https://user-images.githubusercontent.com/8968667/67193865-9fe58880-f428-11e9-82ad-b44b96140239.png)

powershell 6.2.3 on  win10-1903
![image](https://user-images.githubusercontent.com/8968667/67193934-bee41a80-f428-11e9-95f2-568a8fbf041f.png)

**no this bug in powershell 6.2.3 on linux**
![image](https://user-images.githubusercontent.com/8968667/67195053-d6bc9e00-f42a-11e9-8fc6-125b80c0b0d0.png)

**Comment by j4james** [comment] 2019-10-21 13:20
There was a very similar case reported in issue #3141, which was identified as a duplicate of #900, so I suspect this is a duplicate too.

**Comment by DHowett-MSFT** [comment] 2019-10-21 19:36
I'm inclined to agree. Thanks! /dup #900

**Closed by DHowett-MSFT** 2019-10-21 19:36 UTC
Labels: Needs-Tag-Fix, Needs-Triage
