### ISSUE TITLE
Deleting text after typing CJK words removes directory path

### ISSUE THREAD

**Issue by NDelt** [microsoft/terminal#3766] opened 2019-11-28 17:04 UTC
# Environment

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd] 10.0.18363.476
Windows Terminal version (if applicable): 0.7.3291.0


Any other software? No
```

# Steps to reproduce

Write any Korean words, and remove it again.

# Expected behavior

Caret has to stop before `>`.

# Actual behavior

![Honeycam 2019-11-29 02-02-31](https://user-images.githubusercontent.com/46282492/69823507-689aa080-124c-11ea-807d-721f0397fa4d.gif)

**Comment by DHowett-MSFT** [comment] 2019-11-30 00:31
Looks like a disagreement about the width of the characters you've typed. Can you share which characters you are typing?

**Comment by NDelt** [comment] 2019-11-30 02:51
I've typed '한글테스트', but this issue occurs while typing any Korean words.

**Comment by zadjii-msft** [comment] 2019-12-02 14:43
@NDelt Does this only repro with `clink`, or does it also repro in a plain-old unmodified `cmd.exe` profile as well?

**Comment by NDelt** [comment] 2019-12-03 04:40
@zadjii-msft I think I found the cause. After removing Clink, the issue has disappeared.

**Comment by zadjii-msft** [comment] 2019-12-03 13:51
Well that's good to know! Do you know if there's an upstream issue tracking this bug that other people can go follow?

Considering this is caused by Clink, I'll close this out of our repo.

**Closed by zadjii-msft** 2019-12-03 13:51 UTC
Labels: Area-Input, Area-TerminalControl, Issue-Bug, Priority-2, Product-Terminal
