### ISSUE TITLE
Windows Terminal 1.1 breaks remapped CapsLock key inside WSL

### ISSUE THREAD

**Issue by christianfosli** [microsoft/terminal#7120] opened 2020-07-29 21:18 UTC
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18363.959] (1909)
Windows Terminal version (if applicable): 1.1.2021.0

Any other software? PowerToys v0.19.2, Ubuntu 20.04 WSL fresh install from Microsoft Store with no custom config
```

# Steps to reproduce

* In Windows PowerToys, map "Caps Lock" key to "Ctrl" (left or right doesn't matter)
* Open Ubuntu WSL in Windows Terminal
* Open Vim or Neovim, go into Insert mode
* Press "Caps Lock" (which is mapped to "Ctrl")

# Expected behavior

"Caps Lock" should be treated as "Ctrl". No visible result.

# Actual behavior

"Caps Lock" is treated as "Control-Space", and tries insert any previously inserted text again.

---

## Work-Around

The issue goes away by adding this to settings.json

```json
"experimental.input.forceVT": true,
```

Therefore it is likely caused by #6309 

## More Details, Debugging info

I originally thought it was a bug in PowerToys, but since the work-around works, I figure the bug must be here.
It's a bit annoying, because I like to escape out of normal mode in vim by pressing `<CapsLock>-[` (which should be treated as `<Ctrl>-[`, which is again treated as `<esc>`). Now I instead insert the text i wrote twice.

If i input `<Ctrl-V><Caps-Lock>` in Vim insert mode, vim inserts `<C-Space>`. This is how I determined the remapped key is interpreted as `<C-Space>`.

* This happens only inside Windows-Subsystem for Linux (WSL1) inside windows terminal
* I tested with a new installation of Ubuntu from the Microsoft Store, with no customizations to Ubuntu, Vim or wslconf
* I tested inside and outside of tmux, which did not make any difference
* The issue is _not present_ running WSL from CMD or Powershell, i.e. not using windows terminal.
* The issue is _not present_ running Neovim directly from Powershell Core inside windows terminal
* The issue is _not present_ running vim in Linux (tested Alpine) inside windows terminal as a Docker container

**Comment by DHowett** [comment] 2020-07-29 22:01
So, I actually _can_ reproduce this in WSL outside of the Terminal. This is the result of pressing my remapped caps lock under `showkey -a` to dump what the tty driver is generating.

![image](https://user-images.githubusercontent.com/189190/88858029-3612c000-d1ac-11ea-8859-32ac7b3d2830.png)

This is an unfortunate casualty of the better (I know, it's ironic) keyboard support offered by #6309. There's two issues here:

1. PowerToys' remapped key doesn't generate a "scancode" like the normal control key does
2. WSL treats any key it receives with no character (<kbd>Ctrl</kbd> generates no character) _plus_ no scancode as valid input for `\0` (which roughly de-maps to <kbd>Ctrl+Space</kbd>, but is also the encoding for <kbd>Ctrl+Shift+2</kbd>)

This worked before #6309 because the remote app (here, WSL) was never made aware that somebody pressed control without a scancode.

This is most readily fixed by PowerToys, as once the event comes into us we have no way of determining whether the user actually pressed a scancode-less key and truly wanted a null byte or whether they pressed this somewhat broken remapped <kbd>Ctrl</kbd>. ☹️

**Comment by christianfosli** [comment] 2020-07-30 07:05
Thanks, @DHowett, for finding the root cause and describing in an easy to understand way!
In this case I will close this and create an issue in PowerToys instead.

**Comment by christianfosli** [comment] 2020-07-30 07:36
> debugging information
> real ctrl (left) key
> 
> ```
> ␛[17;29;0;1;8;1_
> ```
> 
> remapped
> 
> ```
> ␛[17;0;0;1;8;1_
> ```
> 
> second field is `29` in real and `0` in the remap

How do you find these?
If I open a new bug in PowerToys titled "Capslock -> Control map is missing "scancode".", I should probably include how to debug it properly.

**Closed** 2020-08-02 17:01 UTC
Labels: Needs-Tag-Fix, Needs-Triage

**Comment by DHowett** [comment] 2020-08-06 01:03
So, somebody else reported a similar bug and @lhecker investigated it pretty quickly. We think we can fix this on our side :smile: without requiring any powertoys changes.
