### ISSUE TITLE
Windows Terminal Crashes when hit arrow keys in command plate

### ISSUE THREAD

**Issue by musaugurlu** [microsoft/terminal#9241] opened 2021-02-22 01:18 UTC
# Environment

```none
Windows build number: Microsoft Windows NT 10.0.19042.0
Windows Terminal version (if applicable): 1.5.10411.0

Any other software?
```

# Steps to reproduce
- Open Windows Terminal
- hit Ctrl+Shift+P to open command plate
- hit backspace to delete ">"
- hit up arrow, down arrow, right arrow, left arrow
- Windows Terminal closes/crashes

# Expected behavior

windows terminal is supposed to stay running

# Actual behavior

windows terminal crashes/closes

# Video
https://user-images.githubusercontent.com/18178232/108645772-e2d2c880-7481-11eb-9c99-fbc3a1936ea9.mp4

**Comment by musaugurlu** [comment] 2021-02-22 01:23
Also submitted this with the same title through windows feedback hub

**Comment by DHowett** [comment] 2021-02-22 01:25
_I love your raven background¹_

Curious! I can't reproduce this in that mode in 1.6/1.7. Could you share a link to your feedback hub item? It'll help us get to it faster than just digging through the heaps. :smile:

Thanks!

¹ I see hackles, I say raven... but those beak bristles could be short and this could be a crow . . . which I still love as a background.

**Comment by musaugurlu** [comment] 2021-02-22 01:32
Not sure if it is only my PC. I'll try my other PC and see if it crashes there too.
here is the link to the feedback hub issue: https://aka.ms/AAb91qj

**Comment by musaugurlu** [comment] 2021-02-22 01:59
I tried that on my other Win 10 with the same version of Windows Terminal (1.5.10411.0). It crashed on that, too.

I downloaded WT Preview from Windows Store (version 1.6.10412.0). I was not able to reproduce this issue on that version.

I deleted settings.json file for the WT version 1.5, and let the WT re-create it again, then, launch the WT. I was able to reproduce the issue. So the issue seems to be specific to v1.5 if it is not my PCs.

**Comment by zadjii-msft** [comment] 2021-02-22 12:25
Weird. I immediately got a repro for this on 1.5 myself, but not on 1.7.501.0. So I'm guessing that this is something that's already fixed? @Don-Vito has been on an absolute tear on the command palette recently, I wouldn't be surprised if this was fixed with some other change in that area.

**Closed by zadjii-msft** 2021-02-22 12:25 UTC
Labels: Needs-Attention, Needs-Tag-Fix, Needs-Triage, Severity-Crash

**Comment by Don-Vito** [comment] 2021-02-23 05:21
@zadjii-msft - I believe it might be #8422
