### ISSUE TITLE
display current initialPosition/initialRows/initialCols

### ISSUE THREAD

**Issue by bruceoberg** [microsoft/terminal#4730] opened 2020-02-26 19:36 UTC
# Description of the new feature/enhancement

After the window position and size has been adjusted manually, I'd like to know exactly which numbers to set for `initialPosition`, `initialRows`, and `initialCols` in my profile. That is, I want to adjust my window by hand and then restore to that later.

# Proposed technical implementation details (optional)

Hard to say... I just want to see the numbers. Perhaps some text in the about box? Or some commented out text in `settings.json` so that I can uncomment it to restore the window?

(Note that this is related to #4620 where I want to set the numbers from the command line. I need a way to adjust the window and get the numbers for my command line parameters, if that is ever offered).

**Comment by DHowett-MSFT** [comment] 2020-04-10 00:15
Sorry for taking so long -- I've been deliberating about what the best thing to do with this feature request is. First off: thanks for filing it! I think it's worthwhile.

I feel like this is something we're going to tackle more holistically with the status bar (#3459), which could display things like the current window/pane size, and a floating drag indicator that shows where the window is/how big it is while you're moving it around. I'd prefer to use those as more natural affordances than finding somewhere in the UI to stick ephemeral data like this.

I toyed with a couple other ideas:

1. a way to copy a JSON blob for the active configuration
2. A way to commit the active settings as default (#1056)

At the end of the day, though, this'll be helped immensely by the settings UI (#1564) ... so I'm going to close it out.

In favor of one of those three bugs: this is either behavior that would be encompassed by, or a /dupe of #1056 #3459 and #1564.

Thanks!

**Closed by DHowett-MSFT** 2020-04-10 00:15 UTC
Labels: Issue-Feature, Needs-Tag-Fix, Needs-Triage
