### ISSUE TITLE
Auto-add a 'WSL' profile, linking to System32\wsl.exe

### ISSUE THREAD

**Issue by haydennyyy** [microsoft/Terminal#675] opened 2019-05-10 18:05 UTC
One of the features demo'd on the 'Introducing Windows Terminal' video was an automatic detection for WSL distributions. However, it's not yet been implemented.

I'm putting together a PR to fix this, but thus far, only for the default WSL distro (located by execution alias at `%WINDIR%\System32\wsl.exe`).

If anyone has a way to get a list of all possible linux distros installed locally, could they let me know so that I can add that as a feature too?

**Comment by ghvanderweg** [comment] 2019-05-10 19:54
From a prompt you can do `wslconfig /l`, but I'm not sure how you can get this list programmatically

**Comment by JBanks** [comment] 2019-05-10 21:53
>but I'm not sure how you can get this list programmatically

I just put some code in #441 that takes care of this.  I'm sure there's a more pleasant way to write it, but it works for a temporary solution.

**Comment by DHowett-MSFT** [comment] 2019-05-10 22:03
I’m gonna close this as a dupe of #441. Thanks for reporting!

**Closed by DHowett-MSFT** 2019-05-10 22:03 UTC
