### ISSUE TITLE
Terminal disappears (crashes?) and leaves child processes running (detached from any terminal)

### ISSUE THREAD

**Issue by NfNitLoop** [microsoft/terminal#9151] opened 2021-02-13 19:26 UTC
# Environment

```none
Windows build number: 10.0.19042.0

Windows Terminal version (if applicable): 1.5.10411.0

Any other software?
```

# Steps to reproduce

Unfortunately, I'm not yet able to reproduce this issue, but it's happened [twice].

[twice]: https://twitter.com/NfNitLoop/status/1355276568793235456

I don't remember the circumstances of the [first][twice] occurrence, but this time ~I noticed Terminal had disappeared after waking the machine from sleep.  (Update: I just tried putting the computer to sleep and waking it, and it did not trigger this issue.)~

I'm happy to try steps to reproduce, but I don't know where to begin here. Are there any logs I should investigate/attach?

# Expected behavior

Terminal should not disappear and leave CLI processes running without a terminal.

# Actual behavior

I'll have a terminal window open for development, running a couple long-running processes in 2+ tabs.  (One is running [a web server] via `cargo run`, and the other is running `snowpack watch`.)  

[a web server]: https://github.com/NfNitLoop/feoblog

Then, at some point, I'll notice that the Terminal application has stopped and disappeared from my task bar. (It is not on another virtual desktop. It is not listed in the task manager.)  I can start a new Terminal without any errors.

However, my old processes are still running ... somewhere? ... without an attached terminal. I can still access the web server that's running locally. If I want to continue development, I need to open task manager and kill the processes so I can run them fresh in a working Terminal.

**Comment by suarezzz** [comment] 2021-03-04 02:06
Exactly same here. 
This morning I logged into my remote machine and found no Windows Terminal window at all. Only those sub-processes starting in Windows Terminal is still alive in Task Manager yet unreachable. 
I have few long-running Windows Terminal window running, some running only one process, some running multiple processes. The first time happened one month ago but I didn't pay attention to it. The second time I came here and found I'm not the only one...

Windows Terminal version: 1.6.10571.0
Windows version: 10.0.19042.804

**Comment by zadjii-msft** [comment] 2021-03-04 11:56
My working theory is that this is caused by the Store forcibly killing the Terminal to update it. He actually had a similar issue on the previous release, with a similar analysis (https://github.com/microsoft/terminal/issues/7345#issuecomment-677956187). Looks like we're using #6726 to track that issue, so I'm gonna close this as a duplicate.

Thanks!

/duplicate #6726

**Closed by zadjii-msft** 2021-03-04 11:56 UTC
Labels: Needs-Tag-Fix, Needs-Triage
