### ISSUE TITLE
Windows Terminal integrate with the different menu improvement

### ISSUE THREAD

**Issue by Gaoyifei1011** [microsoft/terminal#5899] opened 2020-05-14 01:02 UTC
现在Windows Terminal已经快到了发布的阶段了，我们希望Windows Terminal能够与桌面右键菜单，Win+X右键菜单和文件管理器的文件菜单显示集成，这样能够提升应用的运行效率，如果未来能够预安装在Windows版本并作为预安装应用发布就更好了。

Now the release candidate of Windows Terminal is approaching. We hope that Windows Terminal can be integrated with the desktop right-click menu, Win+X right-click menu and the file menu display of the file explorer, so as to improve the operation efficiency of the application. It would be better if it could be pre-installed in the Windows version and released as a pre-installed application in the future

**Comment by DHowett-MSFT** [comment] 2020-05-14 01:28
Thank you! This is a /dupe of #1060. This will not be present in 1.0, but hopefully soon after.

The community has some ideas on how to do it.

**Closed by DHowett-MSFT** 2020-05-14 01:28 UTC
Labels: Issue-Feature, Needs-Tag-Fix, Needs-Triage
