### ISSUE TITLE
Right click Windows Terminal Icon to select terminal to launch (overrides default)

### ISSUE THREAD

**Issue by Midnex** [microsoft/terminal#5306] opened 2020-04-10 01:36 UTC
# Description of the new feature/enhancement
I would like to see the ability to right click the Application Icon and select any Terminals listed within settings. This way if we want to override the default terminal we can without having to Windows Terminal, then open a new terminal, then close the original.

# Proposed technical implementation details (optional)
Right clicking the Windows Terminal icon shows/allows starting of other defined Terminals listed in settings. Launching and bypassing the default terminal definition.

**Comment by DHowett-MSFT** [comment] 2020-04-10 02:03
Thanks for the request! This is a /dupe of #576

**Closed by DHowett-MSFT** 2020-04-10 02:04 UTC
Labels: Issue-Feature, Needs-Tag-Fix, Needs-Triage
