### ISSUE TITLE
Solarized colors dropping spaces, foreground gray seems wrong

### ISSUE THREAD

**Issue by zadjii-msft** [microsoft/terminal#1233] opened 2019-06-12 19:16 UTC
From MSFT:21253231

It  seems like Terminal Preview does something weird with color 7...  mapping it (I think) to the 'foreground' color in the scheme.  This is  confusing, because the default scheme (Campbell) has a different color  for 'foreground' than color 7.e.g., run &quot;color  7f&quot; and &quot;color f7&quot; commands in Terminal  Preview.  In both cases, the text color is lighter than the  background... but that shouldn't be possible.

**Comment by DHowett-MSFT** [comment] 2019-06-12 19:37
This is a duplicate of #293 actually!

**Closed by DHowett-MSFT** 2019-06-12 19:37 UTC
Labels: Area-TerminalControl, Issue-Bug, Product-Terminal
