### ISSUE TITLE
Weird square on the top left of the screen

### ISSUE THREAD

**Issue by trajano** [microsoft/terminal#14008] opened 2022-09-15 04:11 UTC
### Windows Terminal version

Windows Terminal Version: 1.14.2282.0

### Windows build number

Microsoft Windows [Version 10.0.22000.918]

### Steps to reproduce

Not sure what triggers it but I see this weird square when Windows Terminal is in the foreground and disappears when I minimize windows Terminal
![image](https://user-images.githubusercontent.com/110627/190312086-083ea7b9-ce6a-4887-843a-4d58b51ae3e3.png)

### Expected Behavior

nothing

### Actual Behavior

Weird square on the top left

**Comment by j4james** [comment] 2022-09-15 08:25
This looks like the same issue as #13800, #13790, and #13640. I'm not sure what the connection is, but the latter was ultimately closed as a duplicate of #13388.

It's also worth noting that some people in those threads said they were using [MicaForEveryone](https://github.com/MicaForEveryone/MicaForEveryone), and changing something in the config fixed the problem for them.

**Comment by zadjii-msft** [comment] 2022-09-15 11:09
Yep, that's right

/dup #13388.

**Closed by zadjii-msft** 2022-09-15 11:09 UTC
Labels: Issue-Bug, Needs-Triage, Needs-Tag-Fix
