### ISSUE TITLE
No built application for download

### ISSUE THREAD

**Issue by creotiv** [microsoft/Terminal#486] opened 2019-05-07 09:48 UTC
WTF guys, you can't make built version of app? so to use it i need to download huge amounts of not needed data and applications? That not how the Linux works.

**Comment by lol768** [comment] 2019-05-07 09:57
Mentioned in https://github.com/microsoft/Terminal/issues/428 a bit already

**Comment by creotiv** [comment] 2019-05-07 10:05
Im not the one)

**Comment by DavidDeSloovere** [comment] 2019-05-07 10:18
Have patience, if there is no release, then Terminal hasn't been released yet for preview. 
Also, doesn't hurt to be polite.

**Comment by creotiv** [comment] 2019-05-07 10:32
@DavidDeSloovere if it not released yet, then where i got the link to this repo?
Im very polite as it possible with MS brand.

And also polite mean to make installation for users, and not throwing in their faces some code and say "do it with it what you want". And really i don't see a problem to build executable installation, it's a task for few hours max for one dev.

**Comment by AndreasWebdev** [comment] 2019-05-07 10:41
@creotiv you are looking at the code of the new terminal. There is no official build available yet so you either build it yourself or wait until the first builds come in. It's really not that hard to understand...

**Comment by zchrissirhcz** [comment] 2019-05-07 10:46
Well, the **windows universal runtime's version** is also important.

>DEP3321: 要部署此应用程序，你的部署目标应运行 Windows Universal Runtime 版本 10.0.18362.0 或更>高版本。你当前运行的版本为 10.0.17134.706。请更新你的 OS 或将部署目标更改为具有合适版本的设>备。

**Comment by ZgblKylin** [comment] 2019-05-07 10:46
The generated ```.appx``` file does not contain any certificates, it couldn't be installed by double-click or powershell. The only way I found is select "Deploy Solution" in vs2017 IDE.

**Comment by creotiv** [comment] 2019-05-07 10:48
@AndreasWebdev so why there is no installer? is it so hard to make?

**Comment by cjim8889** [comment] 2019-05-07 11:06
Why don't you develop your own terminal instead of asking like you are the CEO of Microsoft?

**Comment by creotiv** [comment] 2019-05-07 11:16
@cjim8889 why i should?

**Comment by wayheming** [comment] 2019-05-07 11:16
@creotiv why should they?

**Comment by creotiv** [comment] 2019-05-07 11:21
@wayheming because they published it and advertise it

**Comment by wayheming** [comment] 2019-05-07 11:21
@creotiv So what?

**Comment by creotiv** [comment] 2019-05-07 11:23
@wayheming then maybe should think about that before start advertise it? or spent 1-2h and make installation. It's installation and not human like AI system

**Comment by wayheming** [comment] 2019-05-07 11:25
@creotiv you can always not use analog from the Internet if you don't have enough knowledge to install this terminal

**Comment by scottbilas** [comment] 2019-05-07 11:30
The sense of entitlement is strong with this one

**Comment by creotiv** [comment] 2019-05-07 11:32
@wayheming strange to hear this in MS repo which is "new era UX"))

**Comment by wayheming** [comment] 2019-05-07 11:33
@creotiv good luck with learning terminal installation

**Comment by 10jasper10** [comment] 2019-05-07 11:52
@creotive

Dear creorive,

I would like to leave you some words, I do mean to end the discussion and not advance it.

There will be a Windows store entry for early adopters sometime this summer. And the release date is set for this Winter.

They advertised this for developers to thinker and contribute, not for anyone to just press a build file or use an installer.

By enabling the current barrier you ensure that the people who are using it have the skills to do so the right way. And therefore are able to contribute correctly.

If there was a simple build file or installer, I, an everyday Joe, will thinker with it and I may screw things up on my computer or make excessive issues on this GitHub. (I would say, one like this.)

So i am convinced that this is the perfect way to tease this product. Mind you that this is a release but not a Launch of the product. This is like an alpha, not representative of the final product and thus not finished.

Would you complain the same way if Valve gave away the source for HL3 but wont give you an installer? No, you should be happy with what you got.

If you are un-able to build this yourself or find it too much of a hassle, this product is probably not made for you. (Sorry)

But I doubt that since I could get this to work and I dont know what i am doing.

I hope this gives you a different perspective on the discussion.

-Jasper

PS: if you really want to have an easy way to install this, fork it, fix it, make a pull request and contribute.

PPS: Some people shouldn't act like a ass just because they think different. @wayheming @scottbilas @cjim8889

**Comment by wayheming** [comment] 2019-05-07 11:57
@10jasper10 
I agree that @creotiv should not act like an ass

**Comment by 10jasper10** [comment] 2019-05-07 12:00
@wayheming
I didn't mean that but whatever floats your boat man. 🙃

**Comment by wayheming** [comment] 2019-05-07 12:02
@10jasper10 🐟🌊👴

**Comment by glen-84** [comment] 2019-05-07 12:57
Duplicate of #468.

**Comment by warpdesign** [comment] 2019-05-07 13:08
> Have patience, if there is no release, then Terminal hasn't been released yet for preview.
> Also, doesn't hurt to be polite.

Then why inviting people to `try it out`?

![image](https://user-images.githubusercontent.com/199648/57301696-e98c2200-70d9-11e9-99ad-b3f13ad79956.png)

**Comment by wayheming** [comment] 2019-05-07 13:36
@warpdesign Twitter account is called Windows Developer and implies that the person will be able to cope with the installation from GitHub

**Comment by notmike101** [comment] 2019-05-07 13:37
> Then why inviting people to `try it out`?

You're referencing that picture of a tweet, right?  The tweet poster by Windows **Developer**?  The Twitter account primarily followed by developers?  The one that says "Microsoft Developer is your resource for development tips, tricks, research, case studies...Everything you need to develop apps that users love."?   The tweet I'm assuming is targeted towards developers, not standard users?

You're talking about that one, right?

**Comment by wayheming** [comment] 2019-05-07 13:38
@notmike101 exactly!

**Comment by creotiv** [comment] 2019-05-07 14:04
3 month to make an installer for an app)) that's nice)

**Comment by creotiv** [comment] 2019-05-07 14:08
> > Then why inviting people to `try it out`?
> 
> You're referencing that picture of a tweet, right? The tweet posted by Windows **Developer**? The Twitter account primarily followed by developers? The one that says "Microsoft Developer is your resource for development tips, tricks, research, case studies...Everything you need to develop apps that users love."? The tweet I'm assuming is targeted towards developers, not standard users?
> 
> You're talking about that one, right?
> 
> Even then, my only real question to you is this:
> https://github.com/warpdesign/js-x86
> 
> Where's your binaries? Just because it's "early and incomplete" (just like this code on this repo is) shouldn't be an excuse.

Because its not a system app))) so it strange to have executable on it)

**Comment by wayheming** [comment] 2019-05-07 14:10
@creotiv this is open source project you always can create pull request with installer but you can only demand and scoff

**Comment by DHowett-MSFT** [comment] 2019-05-07 14:11
Hi there. Thanks for being so excited to jump in.

I'm going to lock this issue, and I'll have to ask you to _please remain civil_.

**Closed by DHowett-MSFT** 2019-05-07 14:11 UTC
