### ISSUE TITLE
Color issues when ClearType is used

### ISSUE THREAD

**Issue by acemod13** [microsoft/terminal#5705] opened 2020-05-02 17:55 UTC
# Environment

```none
Windows build number: 10.0.19041.208
Windows Terminal version (if applicable): 0.11.1191.0

Any other software?
This happens on Oh My Posh (Powershell) or Oh-My-Zsh (WSL) with some themes (for example, powerlevel9k)
```

# Steps to reproduce
- Install Oh My Posh or Oh My Zsh.
- Set the theme to powerleve9k (Zsh) or Paradox (Powershell)
- Set `useAcrylic` to `true`.
- Set the `antialiasingMode` to `cleartype`.

# Expected behavior
The color on the theme is rendered correctly.
![Στιγμιότυπο οθόνης (1133)](https://user-images.githubusercontent.com/10028592/80871801-b3668b80-8cb6-11ea-8f8a-84aa3420fb18.png)

# Actual behavior
If the Arcylic option is turned on, it will make some colors (in this case, the arrow in the right part of the text) to change color. In this case, it will turn the blue arrow glyph to a light blue. If acrylic is turned off or the window is minimized (or switching to another window) it will revert to the correct color.
![Στιγμιότυπο οθόνης (1134)](https://user-images.githubusercontent.com/10028592/80871851-ec9efb80-8cb6-11ea-80d5-0769f8454ed6.png)

**Comment by DHowett-MSFT** [comment] 2020-05-02 17:57
I believe this is a /dupe of #5098, the fix for which is due to be released soon.

**Comment by DHowett-MSFT** [comment] 2020-05-02 17:57
(Different symptom, same root cause: cleartype over a background is 'hard')

**Closed by DHowett-MSFT** 2020-05-02 17:57 UTC
Labels: Needs-Tag-Fix, Needs-Triage
