### ISSUE TITLE
Microsoft store version is too old, documentation is incorrect

### ISSUE THREAD

**Issue by Saya47** [microsoft/terminal#17952] opened 2024-09-23 06:54 UTC
![image](https://github.com/user-attachments/assets/264df2fd-ca54-42e1-b252-1a5b38f7b61d)

This is clearly incorrect since we are on Windows Terminal v1.21.2361.0 on Github but on Microsoft Store:
![image](https://github.com/user-attachments/assets/39dc4665-20a6-4e68-b537-85b7629c63b8)

![image](https://github.com/user-attachments/assets/69043dbc-8ce9-444f-83d4-8c51af03c12d)

So the documentation is misleading and should be changed.

The preferred method should be either the msixbundle installer or winget.

**Comment by lhecker** [comment] 2024-09-23 09:46
We've found an issue that causes Windows Terminal to freeze when using an IME on certain versions of Windows. The issue isn't caused by us, and we can't easily fix it on our side either. Because of this we're doing a slower rollout than usual for v1.21 as we're waiting for the bug fix to be released. I'll be closing this issue for now then. Please let me know if you have any other questions!

**Closed by lhecker** 2024-09-23 09:46 UTC
Labels: Issue-Docs, Needs-Triage, Needs-Tag-Fix
