### ISSUE TITLE
Background image broken without acrylic enabled

### ISSUE THREAD

**Issue by mikolertesx** [microsoft/terminal#5971] opened 2020-05-18 17:24 UTC
# Environment

```none
Windows build number: Microsoft Windows NT 10.0.18362.0
Any other software? No.
```

# Steps to reproduce

Add a background and use the Powershell for some time, the background will break at some point.

# Expected behavior

![imagen](https://user-images.githubusercontent.com/13491373/82241748-4d0e7980-9902-11ea-803f-08397ea0eb38.png)

It should work like this, but I dont want acrylic enabled because transparency makes the text a bit harder to read.

# Actual behavior

![imagen](https://user-images.githubusercontent.com/13491373/82241392-b0e47280-9901-11ea-92f1-13e9dbd74e6e.png)

When I enable Acrylic, it works as intended, but as soon as I disable it, it stops working after some time and I have to restart my PC in order for it to work for a little more.

It used to work before without any issues, so I assume it is meant to work without acrylic enabled.

Only the bottom and top parts of the background are visible.

**Comment by DHowett** [comment] 2020-05-19 00:05
>I have to restart my PC in order for it to work for a little more.

Wow, this is crazy. It's not sufficient to restart Terminal?

If you use the experimental rendering options documented [here](https://github.com/microsoft/terminal/releases/tag/v0.11.1333.0), do they help?

**Comment by mikolertesx** [comment] 2020-05-19 00:11
Doesn't seem to help.
![imagen](https://user-images.githubusercontent.com/13491373/82270732-5e27ac80-993b-11ea-9972-9388a9d3124b.png)

**Comment by DHowett** [comment] 2020-05-19 00:15
So, these ones don't hot reload; you did relaunch the Terminal after changing them, right?

You're not using `antialiasingType: cleartype`, right?

**Comment by mikolertesx** [comment] 2020-05-19 00:16
Relaunched it with that and it didn't work.
Then I took away antialiasingType and it immediately worked after relaunching it.

**Comment by DHowett** [comment] 2020-05-19 00:35
Outstanding. Thanks.

**Comment by DHowett** [comment] 2020-05-19 06:10
Now that I'm at my computer and can look at it: this looks like it might be a /dupe of #5703. Thanks!

**Closed by DHowett** 2020-05-19 06:10 UTC
Labels: Needs-Attention, Needs-Tag-Fix, Needs-Triage
