### ISSUE TITLE
ctrl + w sometimes crash 

### ISSUE THREAD

**Issue by 17Edwin** [microsoft/terminal#1575] opened 2019-06-25 03:00 UTC
# Steps to reproduce

ctrl + w sometimes crash unnormally, ctrl + , is also

# Expected behavior

shortcut keyboard run proper

# Actual behavior

**Comment by yodurr** [comment] 2019-06-25 04:49
Is there a particular shell you're using when ctrl+w crashes?
Is this with your local build or the Store version?

**Comment by 17Edwin** [comment] 2019-06-25 08:15
both power shell & cmd prompt, sometimes it not responding and slow, and i have to close and reopen

**Comment by antoineco** [comment] 2019-06-25 18:01
Happens to me in WSL2 (Ubuntu), consistently. CTRL+W is used to change splits in Vim, so this is particularly annoying.

**Comment by DHowett-MSFT** [comment] 2019-06-25 18:32
You know you can edit the bindings in the settings file, right?

**Comment by carlos-zamora** [comment] 2019-06-25 23:30
Probably a duplicate of #1380 since CTRL+W closes a tab. Closing and marking as duplicate.

**Closed by carlos-zamora** 2019-06-25 23:30 UTC
Labels: Area-Interaction, Issue-Bug, Product-Terminal, Resolution-Duplicate, Severity-Crash
