### ISSUE TITLE
blank screen when full screen on side screen

### ISSUE THREAD

**Issue by zhuangzhuang** [microsoft/terminal#3741] opened 2019-11-27 11:06 UTC
# Environment

```none
Windows build number: 10.0.18362.418]

Any other software? No

Harkware:  Intel Core i5-6500 CPU  only IGD

```

# Steps to reproduce
on side screen enter `Alt + Enter` to fullscreen

# Expected behavior

# Actual behavior

![捕获](https://user-images.githubusercontent.com/521058/69718123-7cf57500-1148-11ea-908f-45de8d243d07.PNG)

**Comment by encladeus** [comment] 2019-11-27 12:24
This is a duplicate of #3710.

**Comment by zadjii-msft** [comment] 2019-11-27 14:18
Thanks for the report! Yep, this does look like it is a dupe. Thanks for the early triage pass @encladeus!

/dup #3710

**Closed by zadjii-msft** 2019-11-27 14:18 UTC
Labels: Needs-Tag-Fix, Needs-Triage
