### ISSUE TITLE
vim cannot receive chinese punctuation when running in pwsh tab of windows terminal

### ISSUE THREAD

**Issue by LqkUWp** [microsoft/terminal#9601] opened 2021-03-24 14:56 UTC
I succeed in inputting chinese punctuation in 
- gvim
- vim running in pwsh

But after opening pwsh tab in wt and running vim in it, I fail in inputting chinese punctuation. 

Version detail
- wt v1.6.10571.0
- pwsh
  > Name                           Value
PSVersion                      7.1.3
PSEdition                      Core
GitCommitId                    7.1.3
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
- vim
  > VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Mar 20 2020 23:03:13)
MS-Windows 64-bit console version
包含补丁: 1-422
编译者 appveyor@APPVYR-WIN
巨型版本 无图形界面。  可使用(+)与不可使用(-)的功能:
+acl                +eval               +multi_byte_ime/dyn -tag_old_static
+arabic             +ex_extra           +multi_lang         -tag_any_white
+autocmd            +extra_search       +mzscheme/dyn       +tcl/dyn
+autochdir          -farsi              -netbeans_intg      +termguicolors
+autoservername     +file_in_path       +num64              +terminal
-balloon_eval       +find_in_path       +packages           -termresponse
+balloon_eval_term  +float              +path_extra         +textobjects
-browse             +folding            +perl/dyn           +textprop
++builtin_terms     -footer             +persistent_undo    -tgetent
+byte_offset        +gettext/dyn        +popupwin           +timers
+channel            -hangul_input       -postscript         +title
+cindent            +iconv/dyn          +printer            -toolbar
+clientserver       +insert_expand      +profile            +user_commands
+clipboard          +job                +python/dyn         +vartabs
+cmdline_compl      +jumplist           +python3/dyn        +vertsplit
+cmdline_hist       +keymap             +quickfix           +virtualedit
+cmdline_info       +lambda             +reltime            +visual
+comments           +langmap            +rightleft          +visualextra
+conceal            +libcall            +ruby/dyn           +viminfo
+cryptv             +linebreak          +scrollbind         +vreplace
+cscope             +lispindent         +signs              +vtp
+cursorbind         +listcmds           +smartindent        +wildignore
+cursorshape        +localmap           +sound              +wildmenu
+dialog_con         +lua/dyn            +spell              +windows
+diff               +menu               +startuptime        +writebackup
+digraphs           +mksession          +statusline         -xfontset
-dnd                +modify_fname       -sun_workshop       -xim
-ebcdic             +mouse              +syntax             -xpm_w32
+emacs_tags         -mouseshape         +tag_binary         -xterm_save
     系统 vimrc 文件: "$VIM\vimrc"
     用户 vimrc 文件: "$HOME\_vimrc"
 第二用户 vimrc 文件: "$HOME\vimfiles\vimrc"
 第三用户 vimrc 文件: "$VIM\_vimrc"
      用户 exrc 文件: "$HOME\_exrc"
  第二用户 exrc 文件: "$VIM\_exrc"
       defaults file: "$VIMRUNTIME\defaults.vim"
编译方式: cl -c /W3 /nologo  -I. -Iproto -DHAVE_PATHDEF -DWIN32  -DFEAT_CSCOPE -DFEAT_TERMINAL -DFEAT_SOUND  -DFEAT_JOB_CHANNEL      -DWINVER=0x0501 -D_WIN32_WINNT=0x0501 /source-charset:utf-8 /MP -DHAVE_STDINT_H /Ox /GL -DNDEBUG  /Zl /MT /D_CRT_SECURE_NO_DEPRECATE /D_CRT_NONSTDC_NO_DEPRECATE -DFEAT_MBYTE_IME -DDYNAMIC_IME -DDYNAMIC_ICONV -DDYNAMIC_GETTEXT -DFEAT_TCL -DDYNAMIC_TCL -DDYNAMIC_TCL_DLL=\"tcl86t.dll\" -DDYNAMIC_TCL_VER=\"8.6\" -DFEAT_LUA -DDYNAMIC_LUA -DDYNAMIC_LUA_DLL=\"lua53.dll\" -DFEAT_PYTHON -DDYNAMIC_PYTHON -DDYNAMIC_PYTHON_DLL=\"python27.dll\" -DFEAT_PYTHON3 -DDYNAMIC_PYTHON3 -DDYNAMIC_PYTHON3_DLL=\"python38.dll\" -DFEAT_MZSCHEME -I "C:\Program Files\Racket\include" -DMZ_PRECISE_GC -DDYNAMIC_MZSCHEME -DDYNAMIC_MZSCH_DLL=\"libracket3m_a36fs8.dll\" -DDYNAMIC_MZGC_DLL=\"libracket3m_a36fs8.dll\" -DFEAT_PERL -DPERL_IMPLICIT_CONTEXT -DPERL_IMPLICIT_SYS -DDYNAMIC_PERL -DDYNAMIC_PERL_DLL=\"perl528.dll\" -DFEAT_RUBY -DDYNAMIC_RUBY -DDYNAMIC_RUBY_DLL=\"x64-msvcrt-ruby240.dll\" -DRUBY_VERSION=24 -DFEAT_HUGE /Fd.\ObjCULYHTRZAMD64/ /Zi
链接方式: link  /nologo /opt:ref /LTCG:STATUS oldnames.lib kernel32.lib advapi32.lib shell32.lib gdi32.lib  comdlg32.lib ole32.lib netapi32.lib uuid.lib /machine:AMD64   libcmt.lib  user32.lib  /nodefaultlib:lua53.lib  /STACK:8388608  /nodefaultlib:python27.lib /nodefaultlib:python38.lib   "C:\Tcl\lib\tclstub86.lib" winmm.lib WSock32.lib /PDB:vim.pdb -debug

**Comment by zadjii-msft** [comment] 2021-03-24 15:07
@LqkUWp Are you using `ssh.exe`?

See also 
* https://github.com/microsoft/terminal/issues?q=is%3Aissue+chinese+punctuation+is%3Aclosed
* #9035

**Comment by skyline75489** [comment] 2021-03-25 03:07
I can actually repro this locally, without `ssh.exe`. Just I've been using pure English environment for so long that I didn't notice this before 😅 Will take a look later.

**Comment by skyline75489** [comment] 2021-03-30 22:29
Do we still need this issue opened? Or do we dup it with #9052 ?

**Comment by DHowett** [comment] 2021-03-30 22:31
Thank you! Yes, this is a /duplicate of #9052.

**Closed by DHowett** 2021-03-30 22:31 UTC
Labels: In-PR, Needs-Author-Feedback, Needs-Tag-Fix, Needs-Triage

**Comment by LqkUWp** [comment] 2021-04-02 16:57
@zadjii-msft Sorry for late reply. No, I'm not using ssh. 
BTW, with the last way to input CN punctuation, I get nothing.

**Comment by skyline75489** [comment] 2021-04-02 23:50
if you need this to work urgently , I suggest neovim.

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: 3jS4zk ***@***.***>
发送时间: Saturday, April 3, 2021 12:57:37 AM
收件人: microsoft/terminal ***@***.***>
抄送: Chester Liu ***@***.***>; Comment ***@***.***>
主题: Re: [microsoft/terminal] vim cannot receive chinese punctuation when running in pwsh tab of windows terminal (#9601)


@zadjii-msft<https://github.com/zadjii-msft> Sorry for late reply. No, I'm not using ssh.
BTW, with the last way to input CN punctuation, I get nothing.

―
