### ISSUE TITLE
custom environment variables in settings.json map

### ISSUE THREAD

**Issue by WanderLanz** [microsoft/terminal#13406] opened 2022-06-30 18:52 UTC
# Description of the new feature/enhancement

Adding a new settings.json mapping for extra environment variables injected by conpty initialization,
allowing for user-set environment variables to be handled directly by WindowsTerminal and passed to children as WT_SESSION and WT_PROFILE_ID are.

As it stands, using SETX to load custom environment variables into every terminal child invites cloberring of vars like WSLENV, since WindowsTerminal manually appends and prepends WT_SESSION and WT_PROIFLE_ID to WSLENV.

...
This stems from #7130 and modules wishing to find the equivalent of "$env:WT_SETTINGS". I could not find a similar request, but I apologize in advance if this is a superfluous suggestion.

# Proposed technical implementation details (optional)

Using internal "_environment" in ConptyConnection.cpp as external settings.json map "environment", if possible, since "_environment" seems to already handle injecting arbitrary* environment variables.

**Comment by j4james** [comment] 2022-07-02 21:51
If I've understood you correctly, I think this may be a duplicate of #2785.

**Comment by WanderLanz** [comment] 2022-07-03 01:07
@j4james Yes it would seem I might have done something unnecessary! 

My suggestion is specifically referring to global environment variables for every profile rather than profile-by-profile, because the way ConptyConnection.cpp adds both WT_SESSION and WT_PROFILE_ID made it seem like it would be easier.

I feel like I should leave this open for now unless #9287 also implements a global "environment" or the profile-by-profile solution is as far as custom environments directly from settings.json will go. 

Feel free to close this if you feel it is a duplicate, this is by no means a first-class priority.

**Comment by j4james** [comment] 2022-07-03 09:15
I haven't looked at PR #9287 in detail, but I think your use-case should be covered by the "Defaults" profile. If you set an environment variable in "Defaults", I assume that would be the equivalent of a "global" environment variable that would apply to all profiles. That's the way other profile settings work.

**Comment by WanderLanz** [comment] 2022-07-04 22:22
@j4james Thank you for the clarification, I'll go ahead and close this.

**Closed** 2022-07-04 22:22 UTC
Labels: Issue-Feature, Needs-Triage, Needs-Tag-Fix
