### ISSUE TITLE
Alt Gr key on AZERTY keyboard act as Alt key

### ISSUE THREAD

**Issue by 75002Benoit** [microsoft/terminal#1319] opened 2019-06-19 12:07 UTC
# Environment

```none
Windows build number: [version 10.0.18362.175]
Windows Terminal version (if applicable): 0.0.1.0

Any other software?
An AZERTY keyboard
```

# Steps to reproduce
Use any terminal, use `Alt Gr` + `6` to type `|`

# Expected behavior
A `|` 

# Actual behavior
A new line appears and prompt `digit-argument: -1` as i entered `Alt`+ `6`

**Comment by zadjii-msft** [comment] 2019-06-19 12:08
Please search before filing new issues. This is a dupe of #521

**Closed by zadjii-msft** 2019-06-19 12:08 UTC
Labels: Needs-Tag-Fix, Needs-Triage
