### ISSUE TITLE
Tab header width will decrease when resize the width of window.

### ISSUE THREAD

**Issue by shosatojp** [microsoft/terminal#3962] opened 2019-12-14 00:56 UTC
# Environment

```
Windows build number: 10.0.18362.0
Windows Terminal version (if applicable): 0.7.3451.0
```

# Steps to reproduce
1. Create several new tabs.
1. Resize the width of the window.
1. Restore the width.

# Expected behavior
The width of the area for tab headers should be kept.

# Actual behavior
The width of the area for tab headers will decrease.

![winterm](https://user-images.githubusercontent.com/40783705/70840765-f20abf00-1e57-11ea-8021-f0c431b4ad02.gif)

**Comment by mkitzan** [comment] 2019-12-14 01:28
Looking like a duplicate of #3300

**Comment by zadjii-msft** [comment] 2019-12-16 13:53
Yep this is absolutely a /dup of #3300.

Thanks!

**Closed by zadjii-msft** 2019-12-16 13:53 UTC
Labels: Needs-Tag-Fix, Needs-Triage
