### ISSUE TITLE
Inconsistent text antialiasing

### ISSUE THREAD

**Issue by jdknezek** [microsoft/terminal#6623] opened 2020-06-21 20:06 UTC
# Environment

```none
Windows build number: 10.0.18363.900
Windows Terminal version (if applicable): 1.1.1671.0

Any other software?
```

# Steps to reproduce

Unknown - colored text? Only occurs since upgrading to the 1.1.1671.0 preview.

# Expected behavior

Consistent font antialiasing

# Actual behavior

Some text is antialiased, some is not. I noticed this originally over RDP and thought it might be a bandwith conservation mechanism, but have since observed it locally as well. I have only noticed it with special text properties (like coloration or underline), so it may not be happening with regular text. Screenshot below:

![image](https://user-images.githubusercontent.com/1338/85234070-8be79180-b3d0-11ea-8541-297b0bc44a69.png)

**Comment by DHowett** [comment] 2020-06-21 20:27
This is a /dupe of #6488. Thanks!

**Closed by DHowett** 2020-06-21 20:27 UTC
Labels: Needs-Tag-Fix, Needs-Triage
