### ISSUE TITLE
vim/nvim: cursor foreground doesn't change when hovering a letter

### ISSUE THREAD

**Issue by ndavidpsi** [microsoft/terminal#8400] opened 2020-11-25 12:05 UTC
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.19042.630]
Windows Terminal version (if applicable): 1.3.2651.0

Any other software? Vim/Nvim
```

Example: If the cursor is white and it is hovering a white letter then the letter becomes invisible

In the old cmd the cursor foreground becomes the inverse color of the letter.

Is there a way around this problem?

**Comment by DHowett** [comment] 2020-11-25 18:39
Thanks for the report! This is a /duplicate of #7118 (which is part of a series on cursor colors)

**Closed by DHowett** 2020-11-25 18:39 UTC
Labels: Needs-Tag-Fix, Needs-Triage
