### ISSUE TITLE
folder name "[]" -> open in windows terminal -> instead opens C:\Windows\System32\WindowsPowerShell\v1.0>

### ISSUE THREAD

**Issue by jasonlohcy** [microsoft/terminal#9476] opened 2021-03-12 23:02 UTC
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.19042.804]
Windows Terminal version (if applicable): 1.6.105710.0

```

# Steps to reproduce

1. Create a folder named "[]"
2. context menu -> open in windows terminal
3. terminal will open to C:\Windows\System32\WindowsPowerShell\v1.0>

# Expected behavior

to open in windows terminal in this directory PS: \[]

# Actual behavior

go to C:\Windows\System32\WindowsPowerShell\v1.0> instead.

**Comment by DHowett** [comment] 2021-03-12 23:20
Can't reproduce this here:

![image](https://user-images.githubusercontent.com/189190/111008640-2b7df300-8357-11eb-9eab-e80a2c709f0b.png)

![image](https://user-images.githubusercontent.com/189190/111008649-2e78e380-8357-11eb-9ace-a3096e1b0298.png)

Do you have a `profile.ps1` (powershell profile) that overrides your starting directory?

**Comment by jasonlohcy** [comment] 2021-03-12 23:54
i don't have a powershell profile, i tried it with other shell it works.  Maybe it's cause of my powershell version.
![image](https://user-images.githubusercontent.com/62946715/111010233-db437700-83d0-11eb-9b28-442bb43fe229.png)

**Comment by DHowett** [comment] 2021-03-13 00:05
Oh. Hold up. I sorta remember something about this coming up before...

**Comment by DHowett** [comment] 2021-03-13 00:08
Okay. PowerShell 5 (windows powershell) can't be started up in a directory with special characters in its name -- EVEN outside of Terminal:

```
C:\Users\duhowett\AppData\Local\Temp\[]>powershell

Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Install the latest PowerShell for new features and improvements! https://aka.ms/PSWindows

PS C:\Windows\System32\WindowsPowerShell\v1.0>
```

Gonna close this one out as external, and they've already fixed it for powershell core
. Sorry!

**Closed by DHowett** 2021-03-13 00:08 UTC
Labels: Needs-Attention, Needs-Tag-Fix, Needs-Triage
