### ISSUE TITLE
A bug that caused posts to be deleted when the terminal window was reduced and then expanded again

### ISSUE THREAD

**Issue by Lee-Seong-Ju** [microsoft/terminal#3295] opened 2019-10-23 10:49 UTC
hello
I've found a bug that causes posts to be deleted when the terminal window is shrunk and stretched. Is there any way to fix this?
![캡처](https://user-images.githubusercontent.com/55746374/67385313-e2949580-f5cd-11e9-8266-4399bad99687.PNG)
this picture before I reduced the terminal window

![캡처2](https://user-images.githubusercontent.com/55746374/67385367-f93aec80-f5cd-11e9-85a7-e1b4c873602f.PNG)
this picture reduced the terminal window and expand again.

I can't speak English very well so please understand me.
and I'm first time to writing here, so if there's anything wrong, tell me!

thank you.

**Comment by DHowett-MSFT** [comment] 2019-10-23 20:07
I believe this is a /dupe of #1465.

**Closed by DHowett-MSFT** 2019-10-23 20:08 UTC
Labels: Needs-Tag-Fix, Needs-Triage
