### ISSUE TITLE
Text Doesn't Reflow Properly on Window Resize after Vim Opened and Closed

### ISSUE THREAD

**Issue by Jacob-Bishop** [microsoft/terminal#7466] opened 2020-08-30 02:04 UTC
# Environment

```none
Windows build number: 10.0.18362.0
Windows Terminal version: 1.2.2381.0
Vim: 8.1
```

# Steps to reproduce
1. Open Powershell in a Windows Terminal tab.
2. Launch Vim.
3. Close Vim.
4. Expand the terminal window on the right side (i.e., use the mouse to resize the window).

# Expected behavior
The beginning of each "PS" prompt should be anchored to the left-hand side of the window.

# Actual behavior
The second "PS" prompt wraps backward onto the first line
![image](https://user-images.githubusercontent.com/37914376/91649445-298ebb00-ea29-11ea-85c1-829c003abb1b.png)

# Notes
This might be a duplicate with @waf's report in #7232, although this is about resizing the terminal after vim has exited and his report was about resizing the terminal while vim was open.

**Comment by zadjii-msft** [comment] 2020-08-30 04:27
Is this vim.exe, or a vim from a wsl distro?

**Comment by Jacob-Bishop** [comment] 2020-08-30 04:50
Sorry, vim.exe.

**Comment by elhannah** [comment] 2020-08-30 20:47
I have similar and I think "same" problem.  When I open an Ubuntu tab in Windows Terminal, unless the terminal is exactly 50 lines and 140 columns, vim draws screen incorrectly (it's seemingly clear that vim thinks the dimensions are as above, 50x140).  

I can provide some debugging information that can help re-create.  If you use the "tput lines" and "tput cols" command, the window should print correspondingly the number of lines and columns:

> elhannah@office-win10:/mnt/c/Users/elhan$ tput lines
> **50**
> elhannah@office-win10:/mnt/c/Users/elhan$ tput cols
> **140**

After resizing with mouse, the window correctly reports the new sizes:

> elhannah@office-win10:/mnt/c/Users/elhan$ tput lines
> **38**
> elhannah@office-win10:/mnt/c/Users/elhan$ tput cols
> **102**

Now, if you execute "vim", the screen looks something like:

![image](https://user-images.githubusercontent.com/7785108/91669068-982a5200-ead7-11ea-8796-19ddf9fd7bf6.png)

and after exiting (since you can't really effectively edit :-(...

lines and cols are back to the default, and no longer represent the actual lines and cols of the window.

> elhannah@office-win10:/mnt/c/Users/elhan$ tput lines
> **50**
> elhannah@office-win10:/mnt/c/Users/elhan$ tput cols
> **140**

However, what's odd, is in some cases I have been able to initiate an Ubuntu tab and after using "tput lines" and "tput cols", the screen behavior is fine and remains consistent even with window resizing.  It seems once a tab is working, it continues to work fine.  This so far is random to me.  I've not been able to predict, nor coax a tab into good behavior, nor stop one that is working from going back to the incorrect behavior.

**Comment by j4james** [comment] 2020-09-02 23:02
@elhannah Is it possible you've got something like `set lines=50 columns=140` in your .vimrc file? Those are options that vim uses to set the default window size, but that resizing functionality is not yet supported by Windows Terminal (see issue #5094). The problem is that conhost does actually support resizing, so the conhost backend and the Terminal frontend get out of sync, and that results in everything rendering in the wrong place.

**Comment by elhannah** [comment] 2020-09-03 15:14
I wondered that too, but there are no references in .vimrc.

What's odd is that in one tab I *did* get size working, and it behaved
perfectly as I resized.  But it was not reliably reproducible.

A couple of other interesting additions to the conversation:

   1. I found that if I modified the json config file and instead of
   "source" for wsl, I changed the invoke to "commandline", much like the
   powershell configuration, and the commandline is simply the linux
   distribution of your choice.  I have Ubuntu, openSUSE-42, and kali-linux,
   and they all work fine with vi when defined that way.
   2. *However*, :-), regardless of whether I have vi window dimensions
   correctly matching the windows terminal, I find that when I start vi, about
   10 to 25% of the time it starts in "REPLACE" mode, meaning that any
   characters I enter are going into vi as input, but vi is supposed to start
   in "normal" mode.  This is easily overcome by hitting ESCAPE and continuing
   but it is confusing, and also leads me to wonder if in fact it's more than
   just a "first startup" idiosyncrasy, or if something else might be going on
   and that odd behaviors continue within the vi session.

I was happy that my configuration mod worked generally for window
dimensions and dynamic re-sizing, but I'm concerned enough about the other
issue and what is going on to continue to rely on the WSL command
window/terminal in the meantime.

Thanks for response, I will read #5094, and provide any additional feedback
if necessary.

Have a great day!

-E

**Comment by elhannah** [comment] 2020-09-03 17:21
further clarification:

*However*, :-), regardless of whether I have vi window dimensions correctly
> matching the windows terminal, I find that when I start vi, about 10 to 25%
> of the time it *starts in "REPLACE" mode*, meaning that any characters I
> enter are going into vi as input, but vi is supposed to start in "normal"
> mode.  This is easily overcome by hitting ESCAPE and continuing but it is
> confusing, and also leads me to wonder if in fact it's more than just a
> "first startup" idiosyncrasy, or if something else might be going on and
> that odd behaviors continue within the vi session.


to enter REPLACE mode in vi, user presses SHIFT-R.  So, somewhere between
initiating vi and user gaining terminal control, vi somehow thinks it's
received the "R" character.

**Comment by j4james** [comment] 2020-09-03 17:30
The REPLACE mode problem is probably issue #1637. One theory is that it's got something to do with vim sending a cursor position requestion, for which the response is an escape sequence ending with `R`. If something goes wrong with the parsing of that response it may be misinterpreted as an `R` keypress.

**Comment by Jacob-Bishop** [comment] 2020-09-04 05:01
@elhannah I think that might be a different problem -- I'm not seeing any problem with vim opening in replace mode, and resizing while Vim's open works fine. Maybe because I'm launching vim.exe from powershell rather than vim in an ubuntu terminal?

**Comment by elhannah** [comment] 2020-09-04 13:33
right, this happens from a tab running ubuntu in windows terminal.

from a powershell tab I've not been able to recreate the REPLACE mode bug.
I am invoking explicitly the vim.exe (I'm running vim 8.2).

You can see how many times I've invoked in this screen shot:

[image: image.png]

However, there is something odd with vim's behavior in the powershell
window.  as I type in input mode, random placement of characters appear, it
looks like it's mostly on the same line
that I'm typing.  I'll do more with this to see if I can get more specific
descriptions.

(As a side note, some of this is interesting and important to me as I'm in
the middle of writing the 8th Ed of the O'Reilly "Learning the vi and Vim
Editors
<https://www.amazon.com/Learning-Vim-Editors-Processing-Maximum/dp/059652983X/ref=cm_cr_arp_d_product_top?ie=UTF8>"
book.  I'm trying to describe and include as much landscape as possible
where vim runs  (under the heading of "vim is everywhere").)

**Comment by doesitblend** [comment] 2020-09-11 04:10
I believe I can reproduce the issue described @elhannah almost 100% in my environment.

From either a Powershell, or WSL2 tab I ssh to a remote machine, attach to a docker instance and then run vim. Before resizing the terminal, this operates normally as expected running Vim 7.4  on CentOS Linux release 7.8.2003 (Core). 

I usually just maximize my terminal window with the keyboard shortcut Windows+up arrow. After resizing the terminal, every time I run vim on that Docker container I am automatically in REPLACE mode for some reason. If return the terminal to default size with Windows+down arrow, the terminal behaves normally again. I can only replicate this in Windows Terminal. 

This also happens if I run a Linux VM in Hyper-V locally and SSH in to that machine. It's even worse if I run a FreeBSD VM and do the same.

This strange behavior is 100% reproducible in csh/tcsh on FreeBSD 12.1 running in a Hyper-V VM locally on the desktop. This runs Vim 8.2. No need to resize the window or anything. Just run Vim and you will start in REPLACE mode.

**Comment by DHowett** [comment] 2020-09-11 04:22
The REPLACE mode issue is being tracked elsewhere (#1637) and has been fixed pending release. If you don’t mind, I would like to keep this thread on the topic of text reflow issues. Thanks!

**Comment by zadjii-msft** [comment] 2020-10-01 17:35
Hey sorry for letting this go untriaged for so long - @Jacob-Bishop could you share your powershell profile? Have you done anything to your `.vimrc` that might change `lines` or `columns`? I can't get this to repro locally with a vim.exe v8.2 (but I'd _doubt_ that this was changed in between those two versions)

**Comment by elhannah** [comment] 2020-10-01 17:39
I know you're asking Jacob, but I had the same issue, and no reference in
.vimrc to setting lines and columns.

But!  The good news is I have the latest version of Terminal, and the issue
has been resolved.  It seems to be working perfectly now.

Thanks.

-E

**Comment by Jacob-Bishop** [comment] 2020-10-03 18:02
@zadjii-msft, thanks for looking into this:

1) I just successfully reproduced the issue in a Command Prompt tab, so it doesn't seem to be a powershell-specific issue. I also haven't created a powershell config file. That said, I am running an old version of powershell -- `5.1.18362.752`. I don't think that should matter?

2) I just updated Vim to 8.2 (the `gvim_8.2.0012_x86_signed.exe` installer recommended on vim.org), and I'm still seeing the issue. I can reproduce the issue with `vim --clean`, so it shouldn't be related to my Vim config either.

Current Windows Terminal version is 1.3.2651.0, the latest version on the Microsoft Store.

Let me know if there is other information that would be useful.

One additional note that I don't think I mentioned originally, which may be helpful in your attempts to reproduce- lines created after exiting Vim are correctly anchored to the left side of the terminal, but lines created before opening vim are not. 
![image](https://user-images.githubusercontent.com/37914376/94998414-802a7000-0566-11eb-9de7-f70893cf8c56.png)

**Comment by DHowett** [comment] 2020-10-23 02:02
So, I think that this is another instance of #3088. It's not titled correctly, but there's something that vim does when launches/exits that causes it to print out _every character that was on the screen_. After that happens, lines in the buffer are incorrectly marked as wrappable.

/dup #3088

**Closed by DHowett** 2020-10-23 02:02 UTC
Labels: Needs-Attention, Needs-Tag-Fix, Needs-Triage
