### ISSUE TITLE
Separate the Paste Clipboard and Paste Selection behaviors

### ISSUE THREAD

**Issue by chenzhiwei** [microsoft/terminal#10625] opened 2021-07-12 09:52 UTC
# Description of the new feature/enhancement

In all other terminals, such as gnome-terminal, kde-terminal, tillix, iterm2, the `Paste Clipboard` and `Paste Selection` are different behaviors.

Users can select some texts from the terminal and copy some texts from other places, then they can use `Paste Selection` and `Paste Clipboard` to paste two different text snippets.

This is a de-facto standard for Linux terminals, hope Windows Terminal can also implement this feature.

**Comment by zadjii-msft** [comment] 2021-07-12 13:09
Okay, so it's weird, but I guess it's a fair request. So to clarify: 
* user selects some text (without `copyOnSelect`)
* user can now press two different keybindings
  * one action can be used to paste what's on the clipboard to the Terminal (the behavior we currently support)
  * another action can be used to paste the text that's currently selected by the Terminal

Yea that doesn't sound too crazy. Thanks!

**Comment by chenzhiwei** [comment] 2021-07-12 13:57
@zadjii-msft Yes, using `shift+insert` to `Paste Selection` is a very useful feature in Linux terminals. There is even no doc about this, it is native behavior of Linux terminal, you can test with Gnome Terminal.

The steps can be:

1. Copy some text from a website
2. Open the Gnome Terminal, select some text
3. Then press `shift+insert` to paste the selected text, press `ctrl+shift+v` to paste the text you copied from the website

My frequent use case is:
1. Type `vim`, then `Shift+Insert` to paste the selection(a file name)
2. Enter into the file
3.  `Ctrl+Shift+v` to paste the copied file content

**Comment by chenzhiwei** [comment] 2021-07-12 14:02
https://unix.stackexchange.com/a/178401

> The only exception is gnome-terminal. After long debates, the devs have decided (for consistency with other terminals) that, in gnome-terminal, Shift+Insert should paste from PRIMARY and Ctrl+Shift+V should paste from CLIPBOARD (although you have the options to customize some shortcuts).

**Comment by DHowett** [comment] 2021-07-12 21:28
Thanks again for the request!

Reading this over, and trying to understand it, I've come to believe that it is a /duplicate of #6250.

Having a separate *select* and *copy* buffer would be an excellent enhancement, and I believe that "simulating X11's select buffer" gets us there!

**Closed by DHowett** 2021-07-12 21:28 UTC
Labels: Area-TerminalControl, Help Wanted, Issue-Task, Needs-Triage, Product-Terminal
