### ISSUE TITLE
A humble request for a Standard MSI or exe installer. 

### ISSUE THREAD

**Issue by matsmcp** [microsoft/terminal#9516] opened 2021-03-16 16:02 UTC
# Description of the new feature/enhancement
since #6010 was locked I'm creating this instead with a hope of a good discussion

I would like to ask/Query for the possibility for an Exe or MSI installer (not MSIx).
This would make life a lot easier for Policy or air gap restricted environments. 

There might be very good reasons for why this isn't doable but it would simplify a lot for many corp users

**Comment by DHowett** [comment] 2021-03-16 16:03
Thanks for asking. This is a /duplicate of #1386.

**Closed by DHowett** 2021-03-16 16:04 UTC
Labels: Issue-Feature, Needs-Tag-Fix, Needs-Triage
