### ISSUE TITLE
Add openning tabs with Admin Rights from dropdown menu

### ISSUE THREAD

**Issue by SasukeeUchiha** [microsoft/terminal#6534] opened 2020-06-16 17:11 UTC
Make it so that we can open a terminal tab with admin privileges from the dropdown menu.

When you open the drop-down menu,

1. You get a drop-down list where it is alternating as normal and admin. It would be great if you can make it so we can enable/disable this in settings as some may find this interfering. For example
> Windows Power Shell
> Administrator: Windows Power Shell
2. When you click on a selection of the drop-down menu holding, for example, <kbd>Shift</kbd> a terminal with admin privileges open.

**Comment by zadjii-msft** [comment] 2020-06-16 17:18
To support this, we'd need to first support opening new instances elevated 😉. A bunch of this work is being tracked in #5000, #1032, #1490, #632. I bet once #632 and #1571 are both implemented, you could manually add entries to the new tab dropdown for `{ "action":"openTab", "elevated":true }` or something similar (depending on how #632 shakes out).

For now, I'm gonna close this as a combo dupe of those two. Thanks!

/dup #632 #1571

**Closed by zadjii-msft** 2020-06-16 17:18 UTC
Labels: Issue-Feature, Needs-Tag-Fix, Needs-Triage
