### ISSUE TITLE
defaultProfile setting is no longer respected

### ISSUE THREAD

**Issue by zawor** [microsoft/terminal#5489] opened 2020-04-23 07:29 UTC
It seems like after upgrading to 0.11.1121.0 `defaultProfile` setting is no longer respected.

# Environment

```none
Windows build number: Microsoft Windows NT 10.0.19041.0
Windows Terminal version (if applicable): 0.11.1121.0

Any other software?
plenty but probably irrelevant ;)
```

# Steps to reproduce

1. Have a multiple profiles configured where `powershell.exe` is not default.
2. Start Windows terminal
3. You start always with `powershell.exe` one

alternatively
2. `ctrl` +`alt` + `-` causes always to load `powershell.exe` one regardless which one currently is active

# Expected behavior

`defaultProfile` gets loaded on startup 

# Actual behavior

`defaultProfile` is ignored

I attach settings file for reference:
[settings.zip](https://github.com/microsoft/terminal/files/4520837/settings.zip)

PS:
If you need more details simply let me know.

**Comment by mlewand** [comment] 2020-04-23 07:52
You need to move all your settings from `global` key (in your `settings.json`) outside of `global` key (to the root level).

Duplicate of #5458.

**Comment by zawor** [comment] 2020-04-23 08:26
this solves my problem... but damn... visibility of this breaking change is close to none if you are not tracking terminal changes eagerly

**Closed** 2020-04-23 08:26 UTC
Labels: Needs-Tag-Fix, Needs-Triage

**Comment by mlewand** [comment] 2020-04-23 08:54
@zawor agree, I also missed it myself, despite "reading" (or scanning, I should say) the changelog :smile:

**Comment by mdtauk** [comment] 2020-04-23 09:06
I was trying to update my settings to set the theme, and I was trying to put the entry in the defaults section, wondering why it wasn't working - until I moved it to root.

It feels quite odd using the JSON root for elements, but I guess once the Settings UI is added, it will become redundant to think too much about it. :)

**Comment by zawor** [comment] 2020-04-23 09:17
@mlewand mine was even worse... i run on windows store version, so today out of sudden i got caught with my pants down by this regression :P

personally i would love to have (opt in) possibility to get smacked in the face with release notes dialog/tab/view/whatever every time i get auto updated, lets say just like in VS Code

**Comment by mlewand** [comment] 2020-04-23 09:23
@zawor Sounds like a good feature request 🙂 what I'm doing is I subscribed to release-only on GH so that I get notification about the release, check the changelog and then upgrade it using [chocolatey](https://chocolatey.org/) (decent package manager, so the upgrade is as simple as typing `cup microsoft-windows-terminal /y` once I'm sure I want to upgrade).
