### ISSUE TITLE
Vb: conhost still crashes (disappears?) on resize in the alt buffer

### ISSUE THREAD

**Issue by joaobzrr** [microsoft/terminal#4308] opened 2020-01-21 00:08 UTC
```
Windows build number: 19013.1102
```

# Steps to reproduce

- Disable "Wrap text output on resize" console option.
- Compile the code below and run Visual Studio with the executable.

```cpp
#include <windows.h>
#include <stdio.h>

int main(int argc, char **argv)
{
    HANDLE con_out = CreateFile("CONOUT$", GENERIC_READ | GENERIC_WRITE, FILE_SHARE_WRITE, 0, OPEN_EXISTING, 0, 0);
    if (con_out != INVALID_HANDLE_VALUE)
    {
        DWORD con_out_mode;
        GetConsoleMode(con_out, &con_out_mode);
        con_out_mode |= ENABLE_VIRTUAL_TERMINAL_PROCESSING;
        SetConsoleMode(con_out, con_out_mode);

        printf("\x1b[?1049h");
        printf("\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n");
    }
}
```

- Put a breakpoint at the first line of main() then start debugging or just hit F10 to have the debugger stop at the beginning. When you break, maximize the console window.
- Step through until this line

```cpp
printf("\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n");
```

is executed.
- Restore the window to its previous size by clicking the restore button or double clicking the window title bar.

# Expected behavior

The console window should remain visible.

# Actual behavior

The program appears to crash, but it's actually still running. The console window disappears but the process is still visible in the task manager. You can't kill the process unless you close Visual Studio.

**Comment by DHowett-MSFT** [comment] 2020-01-21 20:38
This sounds like #1206, but I can't reproduce it here. Can you try again on 19041? 19013 is pretty old by insider standards (Oct 2019).

**Comment by x1bzzr** [comment] 2020-01-21 21:38
Sorry, but that won't be possible. You'll have to, if you want to, do that on your end.

**Comment by DHowett-MSFT** [comment] 2020-01-21 21:49
It is unusual that you are isolated on an insider's build that's going to be out of support very soon. Alas!

I can't reproduce this on 19011, 19013 or 19041.

**Comment by x1bzzr** [comment] 2020-01-22 00:54
Ignore my previous post. I'll try it on 19041 and let you know what happens as soon as possible.

**Comment by x1bzzr** [comment] 2020-01-22 02:43
Okay, I tried it on 19041 and the same thing is happening.

**Comment by DHowett-MSFT** [comment] 2020-01-23 23:38
Thanks for confirming!

**Comment by x1bzzr** [comment] 2020-01-24 18:01
@DHowett-MSFT Should I open a bug issue for this?

**Comment by DHowett-MSFT** [comment] 2020-01-24 18:19
You don't need to file a separate issue -- this is the issue we will use to track this problem. Thank you!

**Comment by x1bzzr** [comment] 2020-01-24 18:21
@DHowett-MSFT I'm really sorry, I meant to post that on another issue.

**Comment by zadjii-msft** [comment] 2021-12-09 15:16
Hey so it's been almost 2 years now - I just tried this on a conhost on windows 11, on 22510, and this looks fixed to me. @joaobzrr can you try reproing this again on a newer build? I think this may have gotten fixed in the last two years, but I haven't a clue as to what did it.

**Closed** 2021-12-16 19:01 UTC
Labels: Product-Conhost, Area-Server, Issue-Bug, Severity-Crash, Needs-Author-Feedback

**Comment by unxed** [comment] 2026-09-03 19:00
It turned out [f4](https://github.com/unxed/f4) is also affected. It's a good thing Fable 5.1 found this ticket. We were stumped for a long time on how to handle this problem. Let me know if you need any help with diagnostics!

**Comment by DHowett** [comment] 2026-09-03 22:03
Unfortunately, we lack the business justification to bring fixes to Windows 10 unless they are the most dire of cases.

**Comment by unxed** [comment] 2026-09-03 23:38
Not a problem, I will publish the link to workaround then it will be ready as a reference for everyone who needs it.

**Comment by DHowett** [comment] 2026-09-03 23:52
Thanks @unxed!

**Comment by unxed** [comment] 2026-09-04 05:46
Ok, fix is [confirmed](https://t.me/FarManager/27447/28396), so publishing.

Worked it around the way Far and mcwin32 do: on classic console window I stopped emitting DECSET 1049 and instead keep my own screen buffer via CreateConsoleScreenBuffer / SetConsoleActiveScreenBuffer ([unxed/vtui@6898db9](https://github.com/unxed/vtui/commit/6898db943f229fd34aec86eddbcccb9c95ea2856)), and, since my child is driven through ConPTY and can leave the cursor anywhere, I now pull the cursor and window inside the target before shrinking the buffer, avoiding the render-thread fault from #2366 ([unxed/vtui@3a64d25](https://github.com/unxed/vtui/commit/3a64d250029d7ca5931b4eaa5ceb2ecf3a53cd8c)).
