### ISSUE TITLE
Ghost window (DesktopWindowXamlSource) is shown again (see issue #6507)

### ISSUE THREAD

**Issue by TuxTom** [microsoft/terminal#16183] opened 2023-10-17 13:58 UTC
### Windows Terminal version

1.19.2831.0

### Windows build number

10.0.19045.0

### Steps to reproduce

- Open Windows Terminal

### Expected Behavior

Just one window being shown in the taskbar/window switcher list.

### Actual Behavior

Besides the actual application window, another dummy window with the name "DesktopWindowXamlSource" is shown. When the dummy window is closed, the actual window is also closed.

**Comment by TuxTom** [comment] 2023-10-17 13:59
I also tried this with Windows Terminal version 1.18.2822.0, I have the same effect.

**Comment by TuxTom** [comment] 2023-10-20 09:00
In most of the cases, the ghost window appears immediately when performing a "cold launch" of the terminal. Yet, in some rare cases the ghost window is not shown.

One more observation: I have the application window on the second display, it also appears there when it's launched. In most cases when the ghost window is shown, the window is opened on the second display and the ghost window is also shown in the taskbar of the second display. The taskbar entry for the actual window appears on the first display, though. When I move the application window to the first display and back, the taskbar entry is taken along to the second display.

I even had one case, where no ghost window was shown but the taskbar entry for the application window was still shown on the wrong display.

**Comment by TuxTom** [comment] 2023-10-26 07:01
Thanks for bringing this up, @fighur !

I'm also using FancyZones and can confirm that the issue goes away when I disable it. It even seems sufficient to disable the FancyZones option "Move newly created windows to their last known zone".

**Comment by Jonas1312** [comment] 2023-10-26 11:00
I have the same issue on Windows 10, using Terminal 1.18.2822.0, and I'm using FancyZones too

**Comment by BADF00D** [comment] 2023-11-10 05:46
> Thanks for bringing this up, @fighur !
> 
> I'm also using FancyZones and can confirm that the issue goes away when I disable it. It even seems sufficient to disable the FancyZones option "Move newly created windows to their last known zone".

I can confirm that behavior. Win10 22H2,  Window Terminal 1.18.2822.0, PowerToys 0.75.1

**Comment by guntern** [comment] 2023-11-10 21:13
> Thanks for bringing this up, @fighur !
> 
> I'm also using FancyZones and can confirm that the issue goes away when I disable it. It even seems sufficient to disable the FancyZones option "Move newly created windows to their last known zone".

I also have this issue and can confirm, that disabeling this single fancyzone option is enough to get rid of the ghost window.

**Comment by 4W5ZeZPMc** [comment] 2023-11-16 09:00
Yes, I can confirm that too. The extra window is gone after deactivating the FancyZone option

**Comment by warleygsantos** [comment] 2023-12-05 15:20
Updating FancyZone to Release v0.76.0 was enough for me

**Comment by erropix** [comment] 2024-01-02 15:24
Instead of turning off the Power Toys  Fancy Zones feature, I just added the terminal process name `WindowsTerminal.exe` in the excludes field.

![image](https://github.com/microsoft/terminal/assets/6576868/cb869cfe-a144-4aab-82a7-c6972c1501cc)

Or, you can just change the terminal window position or size to unpin it from the screen zones.

Both methods solve the issue.

**Comment by DejayRezme** [comment] 2024-01-03 01:40
> Both methods solve the issue.

Just to be clear, this does NOT solve the issue. It's a workaround, the bug is still there. Please fix it. I quite like my workflow with fancy zones.

**Comment by PinkPanther901** [comment] 2024-01-08 00:45
Also experiencing the exact same thing, FancyZones + WindowsTerminal.

**Comment by cprusprus** [comment] 2024-02-20 10:28
I think I have a workaround which can be used for now if someone can confirm. Close all Terminals. In FancyZones, uncheck "move newly created windows to their own zones", then in Excluded apps put (note no extension) exactly DeskopWindowXamlSource

Then recheck "move newly created windows to their own zones". I haven't had a repro since (I had a reliable one before this workaround where it appears when you open a terminal, then switch to another program in the same zone, then close the terminal, and finally launch a terminal [now it shows the ghost window - i.e. switching to a 2nd program before closing was significant for the repro]).

**Comment by albeec13** [comment] 2024-02-24 02:07
> I think I have a workaround which can be used for now if someone can confirm. Close all Terminals. In FancyZones, uncheck "move newly created windows to their own zones", then in Excluded apps put (note no extension) exactly DeskopWindowXamlSource
> 
> Then recheck "move newly created windows to their own zones". I haven't had a repro since (I had a reliable one before this workaround where it appears when you open a terminal, then switch to another program in the same zone, then close the terminal, and finally launch a terminal [now it shows the ghost window - i.e. switching to a 2nd program before closing was significant for the repro]).

Thanks for pointing this out! Just want to note 2 things about your procedure:
1) There is no box for "Move newly created windows to their own zones". Perhaps you mean, "Move newly created windows to their last known zone"? In any case, I did not uncheck this, and simply adding the exclusion and re-launching Terminal made the problem go away.

2) You have an important typo above where it says "exactly DeskopWindowXamlSource". Note missing 't' in "Deskop"

That said, simply adding the FancyZones exclusion for "DesktopWindowXamlSource" seems to have fixed the issue for me, but it would be better if it was fixed properly.

**Comment by dan-hampton** [comment] 2024-03-04 04:08
I have been plagued by this issue for many months. It takes up valuable taskbar space. 

PowerToys 0.77, Terminal 1.19.10573.0

![image](https://github.com/microsoft/terminal/assets/80153931/77da15ed-f7d3-4ab9-bca5-8bd16dd454bb)

**Comment by maaneeack** [comment] 2024-04-03 02:16
PowerToys 0.79.0, Terminal 1.19.10573.0, Windows 10 22H2 19045.4046
Adding DesktopWindowXamlSource to FancyZones exclusion seems to work for a workaround

The DesktopWindowXamlSource ghost opens when I launch Terminal fresh from a reboot or closing all other terminal windows/tabs.

**Comment by Svish** [comment] 2024-04-03 09:07
Same issue here, very annoying.

The workaround of adding `DesktopWindowXamlSource` to the Excluded apps of FancyZones seem to have removed it for me as well.

**Closed** 2024-12-12 21:21 UTC
Labels: Needs-Repro, Issue-Bug, Product-Terminal, In-PR, Area-Windowing
