### ISSUE TITLE
Ability to run tab 'As a different user'

### ISSUE THREAD

**Issue by glaisne** [microsoft/terminal#3331] opened 2019-10-25 19:09 UTC
# Description of the new feature/enhancement

The ability to create a new tab with 'Run as a different user' option would be nice. I often need to run shells as different users.

**Comment by zadjii-msft** [comment] 2019-10-25 20:19
Thanks for the feedback! This is actually a /dupe of #1032.

**Closed by zadjii-msft** 2019-10-25 20:19 UTC
Labels: Issue-Feature, Needs-Tag-Fix, Needs-Triage
