### ISSUE TITLE
[I want to work on] Improving Retro Effects & Enhancing Overall Framerate / Performance

### ISSUE THREAD

**Issue by assembly-guy** [microsoft/terminal#11581] opened 2021-10-22 18:17 UTC
Hello,

# Windows Terminal version (or Windows build number)

1.12.2931.0

I want to work (code it myself**Contributing.md suggestion)  on improving the **Retro terminal effects** and the general performance

#  Extending "Retro terminal effects":

## Customization
-> Option to have scanlines, glitches, noise or custom shader

## Improve the looks
Resources: https://github.com/Swordfish90/cool-retro-term
-> I WOULD LIKE the impact on my PC's resources to feel more lightweight
-> I WANT TO Add options for Frame rate configuration:
-> WITHOUT having shell dependencies that help me to optimize this
-> SO THAT  I am able to take it with me anywhere e.g. custom shells, WSL , SSH, VIM etc
-> ADD the following configurable esthetic options: 
     - Scan lines,
     - Burner effect
     - CRT Screen-like bezel

I would also like to address one issue which I would like to see in Microsoft's terminal as I've seen it implemented in other terminals, changes which did help:

Frame rate Limitation
-> Frame rate limitation option: Adaptive FPS based on the throughput ( Terminal's memory-shock usage intake from the command that was ran as opposed to reading the computer's resources which may feel more heavy weight)

Performance improvements that are worth trying:
-> Word wrap tends to not go well with terminals, especially when esthetic additions such as Retro mode.
-> Having the option to change to Character Mode so when it reaches the end of a line and searches for a place to break does not take a memory impact
-> The user's custom configuration related to EOL on his computer/terminal/shell may result in a significant performance issue
-> Intel graphics driver may mess with the terminal's performance when the computer that have the battery settings configuration for auto graphics switching, connecting to an external monitor solves the issues( because it forces discrete graphics ) so having an option to force discrete graphics could be of use for users that do not specifically want to optimize battery life

**Comment by assembly-guy** [comment] 2021-11-03 10:56
Hello @crutkas 

I was away for holidays hence my belated response.

Sorry if the wording's reader impact came up as unwelcoming as opposed to what I initially intended which was a friendly dev joke as I was excited to see all the openness from your team's side - I guess it's not the time and place to yet get into jokes.

Should there be anything I still need to revise on my initial post, please let me know. I'm still up to working on the before mentioned improvements.

All the best,
Alex

**Comment by zadjii-msft** [comment] 2021-11-03 11:09
> I'm still up to working on the before mentioned improvements.

Does #7013 and #7147 cover everything you're looking for? If so, then I'd start there

**Comment by zadjii-msft** [comment] 2021-11-03 11:18
Meh, #4000 is more for vscode-like extensions to the Terminal, whatever that might mean. At the time, I didn't think it would be so trivial to implement in the Terminal itself, so I was planning on relying on 3rd party code to handle that. Turns out, it was easier than we expected 😅 

I'm going to close this as a /duplicate of #7147, since that's the only real remaining open issue for now. If you do figure out a fun way to do cool-retro-term like effects, then we'd probably accept that as a PR to our [pixel shader samples](https://github.com/microsoft/terminal/tree/main/samples/PixelShaders).

**Closed by zadjii-msft** 2021-11-03 11:18 UTC
Labels: Issue-Question, Area-Rendering, Resolution-Answered, Needs-Triage, Needs-Attention, Needs-Tag-Fix
