### ISSUE TITLE
tab drag failure — console session becomes a ⬜white box⬜ if you drag a tab from one monitor to another

### ISSUE THREAD

**Issue by ClaireCJS** [microsoft/terminal#18178] opened 2024-11-11 19:38 UTC
### Windows Terminal version

1.21.2911.0

### Windows build number

10.0.19045.5011

### Other Software

TCC command line 31.0.15

### Steps to reproduce

Drag a tab from one monitor to another.

To be exact, have it partially obscure both monitors before relasing the mouse.

### Expected Behavior

tab drags to other window just like in chrome, opera, edge, or other multiwindow multitab applications

### Actual Behavior

This. You lose your console session. It still responds to keystrokes, but there's no way to see what's happening. Nothing brings it back.

![Image](https://github.com/user-attachments/assets/aae979d9-3660-4df8-95ce-e50dec265929)

**Comment by zadjii-msft** [comment] 2024-11-11 19:55
Just to be clear - does this repro with just a plain old `cmd.exe` or `powershell.exe` tab/?

Is there any indication what that HWND is? ([WinSpy](https://www.catch22.net/projects/winspy/) may be helpful for this)

**Comment by carlos-zamora** [comment] 2024-11-13 22:16
Thanks for filing. Looks like this is caused by TCC since it doesn't repro with any other shells, so we're going to close this as external.

We're still interested in which process owns that window and getting a dump bucket anyways. There's a guide for how to do that here: https://github.com/microsoft/terminal/wiki/Troubleshooting-Tips#capturing-and-sending-dumps

**Closed by carlos-zamora** 2024-11-13 22:16 UTC
Labels: Issue-Bug, Needs-Triage, Needs-Attention
