### ISSUE TITLE
White / blank screen on startup

### ISSUE THREAD

**Issue by valdisiljuconoks** [microsoft/terminal#823] opened 2019-05-15 15:21 UTC
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)

Microsoft Windows [Version 10.0.18362.113]

* What you're doing and what's happening: (Copy & paste specific commands and their output, or include screen shots)

Compiled Windows Terminal application using VS2019 16.0.3 targeted on x86.
When starting Terminal, all I can see is white / blank screen.

![image](https://user-images.githubusercontent.com/1767179/57787399-f645f100-773d-11e9-87a9-e973ab144e1b.png)

Which just terminates approx. after 2-3 minutes.
No CPU activity.
Couple threads:
![image](https://user-images.githubusercontent.com/1767179/57787509-30af8e00-773e-11e9-8ed6-273a7e9fad91.png)

* What's wrong / what should be happening instead:

Application should launch normally :)

**Comment by zadjii-msft** [comment] 2019-05-15 16:14
This is a dupe of #519. Please search and [read the readme](https://github.com/microsoft/terminal#i-built-and-ran-the-new-terminal-but-i-just-get-a-blank-window-app) before filing new issues.

**Closed by zadjii-msft** 2019-05-15 16:14 UTC

**Comment by valdisiljuconoks** [comment] 2019-05-15 18:12
tried search for various keywords.. sorry for duplicate
