### ISSUE TITLE
Resizing window too small breaks prompt line

### ISSUE THREAD

**Issue by davidhewitt** [microsoft/terminal#3889] opened 2019-12-09 06:30 UTC
# Environment

```none
Windows build number: 10.0.19033.0
Windows Terminal version (if applicable): master
```

# Steps to reproduce

1. Open a new windows terminal.
2. Fill the screen with output from a command, so that there is at least some history off-screen.
3. Resize the window horizontally to minimum width
4. Resize the window back to the original width

# Expected behavior

The text and prompt should all reflow so that after resizing back to original size, everything looks like it did before resizing down. After the resize back to full size, typing input should show on the prompt line.

(With one notable exception: the terminal will have scrolled up a bit.)

# Actual behavior

The input cursor is no longer on the prompt line, but instead one line below. Typing input shows at the cursor location, but this is now nowhere close to the prompt line.

Screens attached below

## Screen before resizing down:

![image](https://user-images.githubusercontent.com/1939362/70412475-cb5e1a00-1a4c-11ea-8274-b6119dfb8568.png)

## Screen after resizing down (***note cursor has now broken onto the line after the prompt***):

![image](https://user-images.githubusercontent.com/1939362/70412513-ddd85380-1a4c-11ea-9a0d-1e4361e27499.png)

## Screen after resizing back to original size:

![image](https://user-images.githubusercontent.com/1939362/70412581-07917a80-1a4d-11ea-8d41-6f43be63bd2c.png)

## Screen after typing some input:

![image](https://user-images.githubusercontent.com/1939362/70412656-31e33800-1a4d-11ea-8fd8-1946a217706c.png)

**Comment by DHowett-MSFT** [comment] 2019-12-09 06:32
Thanks for the comprehensive report! This is a /dupe of #1465.

**Closed by DHowett-MSFT** 2019-12-09 06:32 UTC
Labels: Needs-Tag-Fix, Needs-Triage
