### ISSUE TITLE
Erratic cursor in VIM(WSL)

### ISSUE THREAD

**Issue by blayz3r** [microsoft/terminal#5362] opened 2020-04-15 17:20 UTC
# Environment

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Windows Terminal version (if applicable):
```
![image](https://user-images.githubusercontent.com/12205650/79367175-685d2200-7f1b-11ea-9f24-83d1b37a4dc0.png)
![image](https://user-images.githubusercontent.com/12205650/79367188-727f2080-7f1b-11ea-9f8d-cd423d491d35.png)

```none
Any other software?
```
![image](https://user-images.githubusercontent.com/12205650/79367052-32b83900-7f1b-11ea-944a-983224531478.png)

# Steps to reproduce

**Open Vim in WSL and press j a few times**

# Expected behavior

**Cursor goes down without jumping**

# Actual behavior

![2020-04-15_13-11-23](https://user-images.githubusercontent.com/12205650/79367368-c558d800-7f1b-11ea-9b4e-f94697fc107e.gif)

**Comment by DHowett-MSFT** [comment] 2020-04-15 17:24
So it looks like you’re not using Windows Terminal, but you’re using the traditional console. What is the box that vim is running in? It looks like another piece of terminal-emulating software?

**Comment by blayz3r** [comment] 2020-04-15 17:32
That is correct I am starting WSL from a GVIM terminal buffer, the issue was not there in the Legacy bash on windows

**Comment by zadjii-msft** [comment] 2020-04-15 17:36
I'd say yea, if this bug doesn't repro in the legacy console (conhost.exe, the window you get by simply launching `wsl.exe` or `cmd.exe`), and this doesn't repro in the Windows Terminal, then this doesn't really belong on this repository.

Thanks!

**Comment by blayz3r** [comment] 2020-04-15 17:37
Thanks!

**Comment by DHowett-MSFT** [comment] 2020-04-15 18:01
It depends on your gvim terminal mode.

Can you run `:set termwintype` and report the value? If it's `conpty`, this may yet be our fault.

**Comment by blayz3r** [comment] 2020-04-15 18:25
termwintype = conpty

![image](https://user-images.githubusercontent.com/12205650/79373673-e7a32380-7f24-11ea-875f-826814108a30.png)

**Comment by DHowett-MSFT** [comment] 2020-04-15 18:27
Excellent.

**Comment by DHowett-MSFT** [comment] 2020-04-15 18:28
So just to confirm, can you give a detailed list of repro steps? I need to know what's running inside what, when and where and how.

It looks like vim on the _inside_, but also vim on the outside? Is that gvim, or vim? I don't know how to make gvim show a floating popup, so perhaps it's not just gvim?

**Comment by blayz3r** [comment] 2020-04-15 18:35
Sure the steps are below:
**Step 1:**  Start gvim.exe
S**tep 2 :** open wsl with 
``` vim
:term wsl
```

**Step 3:** Open a file with vi filename (press j a few times to move the cursor)

**Comment by DHowett-MSFT** [comment] 2020-04-15 18:42
Excellent, thanks for the info. This is a combination of a couple things:

1. we're reprinting far too much text, when we don't actually need to. there's a number of changes that fixed this after 19041 came out.
2. we were not properly hiding the cursor while we were moving it, so you got to see _all_ the ugly cursor jumping that we were doing during number one.

I'll close this one out as fix-committed, for now, because the core issue no longer reproduces (with the latest console bits in the next version of windows.)

Thanks for bearing with us!

**Closed by DHowett-MSFT** 2020-04-15 18:42 UTC
Labels: Needs-Attention, Needs-Tag-Fix

**Comment by blayz3r** [comment] 2020-04-15 19:10
Thanks for the quick turnaround. The Terminal App and WSL are awesome btw

**Comment by DHowett-MSFT** [comment] 2020-04-15 19:31
Thanks! :smile:

**Comment by blayz3r** [comment] 2020-05-13 17:44
What Windows10 build will the fix go in

**Comment by DHowett-MSFT** [comment] 2020-05-14 01:48
I cannot commit to the dates for any upcoming Windows releases. Sorry.

**Comment by blayz3r** [comment] 2020-05-14 01:50
No problem. Just curious

**Comment by blayz3r** [comment] 2020-07-12 01:06
I still have this issue
