### ISSUE TITLE
The color 0 is shown as transparent

### ISSUE THREAD

**Issue by subnut** [microsoft/terminal#6173] opened 2020-05-24 11:00 UTC
This issue seems to affect nearly all 256-bit color terminals. Windows Terminal, Fluent Terminal, Hyper, Terminus, etc. 

![report_to_win_terminal](https://user-images.githubusercontent.com/56714626/82752355-11c8ea80-9ddb-11ea-9a62-811fc06d00c6.png)
The places pointed with red arrows should have black backgrounds

The only exception I have found is the default windows terminal. Look at this:
![report_to_win_terminal_2](https://user-images.githubusercontent.com/56714626/82752384-48066a00-9ddb-11ea-81ff-f3d41cb7f9b3.png)

Not all blacks are affected, as it seems. The black text seem to be coming out fine. Also, the color code 16 (also black) is also fine. Only the color code 0 as a background seems to be affected.

**Comment by j4james** [comment] 2020-05-24 13:26
This is a duplicate of #2661 and/or #293.

**Comment by subnut** [comment] 2020-05-24 18:24
Just an update. VSCode also doesn't seem to be affected by this issue.

![report_to_win_terminal_03](https://user-images.githubusercontent.com/56714626/82761670-da2d6300-9e19-11ea-98fd-381bb09fc965.png)

**Comment by subnut** [comment] 2020-05-24 19:12
If anybody wants to look at the script I am using to print these outputs, [Here it is](https://raw.githubusercontent.com/subnut/dotfiles/master/linux/256-bit_color_checker.sh)

**Comment by DHowett** [comment] 2020-05-25 06:33
Unfortunately, this _is_ a /dupe of #293. Thanks @j4james :smile:

**Closed by DHowett** 2020-05-25 06:33 UTC
Labels: Needs-Tag-Fix, Needs-Triage
