### ISSUE TITLE
Crash when ctrl + mouse wheel scroll

### ISSUE THREAD

**Issue by jonathanpallant** [microsoft/terminal#5639] opened 2020-04-29 08:41 UTC
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18363.778]
Windows Terminal version (if applicable): Windows Terminal Version: 0.11.1191.0
```

# Steps to reproduce

1. Load Windows Terminal
2. Hold down Control key
3. Mouse wheel down, to reduce font size

# Expected behavior

1. Font size is decreased
2. Windows Terminal doesn't close

# Actual behavior

1. Font size decreases for the first few clicks
2. Windows Terminal closes

**Comment by jonathanpallant** [comment] 2020-04-29 08:44
Screen capture: https://42t-my.sharepoint.com/:v:/g/personal/jonathan_pallant_42technology_com/EXcV5BqIm2BMmQCygB5RU-MBSVW-oYuyhkOWB1Jq76F1Pw?e=M4TuPp

**Comment by jonathanpallant** [comment] 2020-04-29 08:44
Font is Fira Code, in case that makes a difference.

**Comment by jonathanpallant** [comment] 2020-04-29 08:45
Also crashes when zooming with other shells (WSL, cmd.exe), and when using Cascadia Code as the font.

**Comment by jonathanpallant** [comment] 2020-04-29 08:54
Ah, this looks like a dupe of https://github.com/microsoft/terminal/issues/5479

**Comment by zadjii-msft** [comment] 2020-04-29 13:31
You've got that right 😄 

/dupe of #5479

**Closed by zadjii-msft** 2020-04-29 13:32 UTC
Labels: Needs-Tag-Fix, Needs-Triage
