### ISSUE TITLE
QEMU -noconsole prints ANSI escape codes

### ISSUE THREAD

**Issue by rayzchen** [microsoft/terminal#12649] opened 2022-03-09 17:29 UTC
### Windows Terminal version

1.13.10395.0

### Windows build number

10.0.19042.1526

### Other Software

QEMU emulator version 6.2.0 (v6.2.0-11889-g5b72bf03f5-dirty)

### Steps to reproduce

qemu-system-x86_64 -nographic

### Expected Behavior

something similar to the output of this window:

![image](https://user-images.githubusercontent.com/54078384/157497181-769da504-21e1-4710-a5f0-1bb36b5d9947.png)

### Actual Behavior

```
←c←[?7l←[2J←[0mSeaBIOS (version rel-1.15.0-0-g2dd4b9b3f840-prebuilt.qemu.org)


iPXE (http://ipxe.org) 00:03.0 CA00 PCI2.10 PnP PMM+07F915B0+07EF15B0 CA00



Booting from Hard Disk...
Boot failed: could not read the boot disk

Booting from Floppy...
Boot failed: could not read the boot disk

Booting from DVD/CD...
Boot failed: Could not read from CDROM (code 0003)
Booting from ROM...
iPXE (PCI 00:03.0) starting execution...ok
iPXE initialising devices...ok
```

ANSI codes don't seem to render properly, for example `←[0;1miPXE` which should be `iPXE` in bold.

**Comment by zadjii-msft** [comment] 2022-03-09 17:36
Looks like QEMU isn't enabling `ENABLE_VIRTUAL_TERMINAL_PROCESSING` with [`SetConsoleMode`](https://docs.microsoft.com/en-us/windows/console/setconsolemode). If they want to use VT sequences, they'll need to set that flag. If this worked before, then it must be a recent regression in QEMU...

~unless... how are you launching QEMU? Via a Terminal profile, or just by running the exe directly (from like the start menu or run dialog)? Do  and I remember there being talk that Terminal should enable that flag by default for applications is spawns, but I don't kn~

Nevermind. I thought this might be a defterm bug but you're on Windows 10 so it can't be that. I bet this is a regression in QEMU, we haven't changed this in years.

**Comment by rayzchen** [comment] 2022-03-09 20:30
is there a way to force QEMU to enable that flag?

**Comment by zadjii-msft** [comment] 2022-03-11 17:14
See, that's the interesting part. If you're running QEMU in the Windows Terminal, then `ENABLE_VIRTUAL_TERMINAL_PROCESSING` should be set by default. Only way the above would happen is if they actually _disabled_ that mode explicitly. 

Can you post a screenshot of the Terminal with the (broken) QEMU output?

idly: I wonder if they ship like, mintty with QEMU to use that as their console window.

**Comment by hello-smile6** [comment] 2022-03-16 02:42
> reg key to force VT on by default

Is this it?
https://www.dostips.com/forum/viewtopic.php?t=9144

**Comment by zadjii-msft** [comment] 2022-03-16 13:07
Yep that's the one I was thinking of.

**Comment by hello-smile6** [comment] 2022-03-20 19:17
It seems reproducible with the latest npm in conhost.

**Comment by eryksun** [comment] 2022-03-21 12:25
> Only way the above would happen is if they actually _disabled_ that mode explicitly.

I'm sure lots of programs set a hard-coded value. After all, it's not as if the console API ever changes. ;-)

**Comment by hello-smile6** [comment] 2022-03-21 17:06
Could qemu be detected based on its hash or something? If so, maybe you could ignore its configuration.

**Comment by rayzchen** [comment] 2022-03-21 18:13
![image](https://user-images.githubusercontent.com/54078384/159337559-22e30b73-5425-42d3-b3af-956329e0b6c2.png)

Sorry for the absurdly late reply...

**Comment by hello-smile6** [comment] 2022-03-21 18:15
> ![image](https://user-images.githubusercontent.com/54078384/159337559-22e30b73-5425-42d3-b3af-956329e0b6c2.png)
> 
> > Can you post a screenshot of the Terminal with the (broken) QEMU output?
> 
> Sorry for the absurdly late reply...

I was hoping the issue wouldn't be automatically closed, so I kept commenting.

**Comment by YO4** [comment] 2022-03-23 09:41
I found how to reproduce.

cmd.exe on Windows Terminal, ```chcp 437``` and run msys's bash.exe. Then run qemu and it will reproduce.

```chcp 1252```, ```chcp 932``` or without msys bash, qemu works fine on Windows Terminal.

note: msys uses /c/ProgramData path notation.

**Comment by zadjii-msft** [comment] 2022-08-12 11:49
Huh, kinda surprised we never came back to this. The involvement with msys here makes me think this is a variation on #6634. @DHowett back me up?

**Comment by DHowett** [comment] 2022-08-12 20:28
Agreed, this looks like a /dupe of #6634, and it's something that the upstream application is going to need to handle better.

**Closed by DHowett** 2022-08-12 20:28 UTC
Labels: Issue-Bug, Needs-Author-Feedback, Needs-Triage, Needs-Tag-Fix
