### ISSUE TITLE
Being able to bind any key actions to other keys

### ISSUE THREAD

**Issue by mutageneral** [microsoft/terminal#5812] opened 2020-05-08 16:48 UTC
# Description of the new feature/enhancement

When I browse man pages I have to use the arrow keys to move up and down and it's slow. So I wanted to bind shift+mouceweelUP to arowkeyUP but you cannot bind keys to other keys. The command (referring to the command property of the keybindings, not a command entered in a cli) the arrow keys trigger when they are pressed is not available to be assigned to other keys. I also didn't find any way to bind something to the mouse-wheel in https://github.com/microsoft/terminal/blob/master/doc/cascadia/SettingsSchema.md#keys

# Proposed (not so)technical implementation "details"

Add all the commands/actions that keys can trigger and add all the keys (and other inputs like a mouse wheel) you could possibly bind things to.

**Comment by DHowett-MSFT** [comment] 2020-05-08 23:27
Thanks for the request! I think your _request_ will be solved by combining #1553 and #3799, when they're done.

However, I think your _actual bug_ is a /dupe of #381. The pager that `man` uses typically enables the alternate buffer mode, and then it enables a "mouse cursor keys" mode that translates your mouse wheel _automatically_ into up/down commands.

Because Terminal is not aware that the "alternate buffer" mode is turned on, it doesn't have the right mouse wheel behavior in the pager.

**Closed by DHowett-MSFT** 2020-05-08 23:27 UTC
Labels: Issue-Feature, Needs-Tag-Fix, Needs-Triage
