### ISSUE TITLE
Add keybindings for reordering tabs

### ISSUE THREAD

**Issue by BartXZX** [microsoft/terminal#7579] opened 2020-09-09 11:25 UTC
# Description of the new feature/enhancement
Provide two commands and/or keybindings for reordering tabs
* Move current tab to the left
* Move current tab to the right

I like reordering my tabs, and while the mouse action to move tabs is acceptable, it would be nice to reorder them by just using my keyboard.

**Comment by DHowett** [comment] 2020-09-10 00:47
Thanks for the request! This looks like a /duplicate of #3593.

**Closed by DHowett** 2020-09-10 00:47 UTC
Labels: Issue-Feature, Needs-Tag-Fix, Needs-Triage
