### ISSUE TITLE
[BUG] Switching to legacy console and back makes all text invisible

### ISSUE THREAD

**Issue by linuxandria** [microsoft/terminal#5499] opened 2020-04-23 15:39 UTC
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18363.778]

Any other software?
```

# Steps to reproduce

Switch to legacy console mode.
Restart cmd
Switch to new console.
Restart cmd
# Expected behavior

No user visible changes
# Actual behavior

Text is invisble.

**Comment by DHowett-MSFT** [comment] 2020-04-23 15:41
1. There’s no real reason to use legacy console mode; if you’re encountering a compatibility issue please let us know.
2. This is a /dupe of #2319

**Closed by DHowett-MSFT** 2020-04-23 15:41 UTC
Labels: Needs-Tag-Fix, Needs-Triage

**Comment by linuxandria** [comment] 2020-04-23 15:59
> 1. There’s no real reason to use legacy console mode; if you’re encountering a compatibility issue please let us know.
> 2. This is a /dupe of #2319

Tell an atom extension they need to update then

**Comment by linuxandria** [comment] 2020-04-23 16:00
> 1. There’s no real reason to use legacy console mode; if you’re encountering a compatibility issue please let us know.
> 2. This is a /dupe of #2319

Tell an atom extension they need to update then. They have explicitly refused to update for the new console, but ubuntu WSL refuses to work with legacy.

**Comment by DHowett-MSFT** [comment] 2020-04-23 16:06
If you could tell me which atom extension, I would be glad to. They’re forcing users to reconfigure a critical part of their OS because of some weird ideology when it’d be easier for them to just update? I’d _love_ to give them the what’s-what. Or, of course, if they _also_ have compatibility concerns I’d be glad to get them fixed.

**Comment by linuxandria** [comment] 2020-04-24 00:17
It's a terminal in the ide one, I don't have my laptop handy to check
