### ISSUE TITLE
Terminal closes itself

### ISSUE THREAD

**Issue by xobs** [microsoft/terminal#2655] opened 2019-09-04 04:37 UTC
# Environment

```none
Windows build number: Win32NT             10.0.18362.0 Microsoft Windows NT 10.0.18362.0
Windows Terminal version (if applicable): 0.4.2382.0

Any other software? WSL 16.04
```

# Steps to reproduce

Use Terminal

# Expected behavior

Terminal shouldn't close unless I tell it to close

# Actual behavior

Terminal will occasionally pause for a few seconds, then close, taking with it all of my sessions.  I am unsure whether this is a crash or not because it doesn't pop up a crash dialog box.  This happens once every day or two.

For example, this just happened while doing a `wget`

If this is expected behavior, it's not good.  If it's a crash, then it should present a dialog box indicating it's a crash, along with something such as a stack trace or crash reason.

**Comment by DHowett-MSFT** [comment] 2019-09-04 04:45
Yeah, that'll be a crash. Unfortunately, when we crash hard, it's somewhat out of our control as to whether we can pop up a dialog.

Would you mind collecting feedback hub info? (Following up with a tag that makes the bot tell you the good word.)

**Comment by xobs** [comment] 2019-09-04 04:48
How do I send feedback? If I click the down-arrow and go to Feedback, it opens a browser and takes me to https://github.com/microsoft/Terminal/issues

**Comment by DHowett-MSFT** [comment] 2019-09-04 04:50
You'll need to use the Feedback Hub application (sorry, it's a separate app!) It'll help capture diagnostic information that Windows Terminal can't.

**Comment by xobs** [comment] 2019-09-04 05:04
https://aka.ms/AA5zukj

**Comment by drichardson** [comment] 2019-09-05 15:20
@DHowett-MSFT the behavior OP reported (random disappearing windows... apparently crashes) happens to me somewhat frequently as well. Should I only report the issue to feedback hub or should I create github issues for the crashes as well?

**Comment by emc2314** [comment] 2019-09-08 15:47
Same here. Suddenly exit about once a day. Sometimes using vim, sometimes running python. Don't know what's happening. For WSL, terminal crash means power off. Hope it will be fixed soon.

**Comment by pcolmer** [comment] 2019-09-13 07:34
I'm experiencing Terminal just quitting on me at least once a day but, unfortunately, no particular pattern to it. My usage pattern is the default PowerShell terminal, a WSL terminal and then one or more SSH terminals.

More often than not, I think I have observed that quitting the SSH terminal with CTRL+D can trigger Terminal into dying.

**Closed** 2019-09-13 20:53 UTC
Labels: Area-Quality, Issue-Bug, Needs-Attention, Needs-Tag-Fix, Product-Terminal, Severity-Crash

**Comment by xobs** [comment] 2019-09-14 01:07
This seems different from #2248 -- that only happens when opening/closing tabs, whereas I'm experiencing this issue randomly.  For example, in the initial bug report I mentioned that it happened while `wget` was in the middle of transferring files.

**Comment by zadjii-msft** [comment] 2019-09-18 15:59
Well, that's certainly curious. If it crashes during a wget I'd assume that it's actually #2375, though when examining the feedback you sent, the stack was shockingly crashing in the same place as #2248. Maybe they're actually correlated with one another? Impossible to say for sure.

**Comment by xobs** [comment] 2019-10-05 07:30
@zadjii-msft I just had this happen again.  I was using `riscv64-unknown-elf-gdb` and I ran `bt` to get a backtrace.

**Comment by xobs** [comment] 2019-10-07 04:31
@zadjii-msft is there anything more I should do on this? If not, I'm going to stop using Terminal because having it close randomly when I'm typing characters is severely disruptive to working on terminal programs.

**Comment by jiaulislam** [comment] 2021-01-10 06:06
any solution for this issue yet... now a days I'm facing same issue more frequently.

**Comment by zadjii-msft** [comment] 2021-01-21 11:41
@jiaulislam The original bug that this issue was tracking was resolved more than a year ago. If you're still seeing the Terminal crash randomly on you, then there's probably something new that's the root cause of your issue. I'd recommend filing a new issue, and attaching a feedback hub link (like mentioned earlier in this thread).

**Comment by victoryhb** [comment] 2022-11-24 08:16
I can confirm that the same problem still persists in the the latest version of Windows Terminal (Version: 1.15.2875.0). The whole app just randomly disappears into nowhere after several hours in use.

**Comment by techierishi** [comment] 2023-03-05 10:53
Its still there in version `1.16.10262.0`. Even on just using powershell, it closes automatically.

**Comment by RodrigoSaezCea** [comment] 2023-11-17 19:00
Its still there in version 1.18.2822.0

**Comment by zadjii-msft** [comment] 2023-11-17 19:05
Please read the thread. The original bug that this issue was tracking was resolved more than 3 years ago. If you're still seeing the Terminal crash randomly on you, then there's probably something new that's the root cause of your issue. I'd recommend filing a new issue, and attaching a feedback hub link (like mentioned earlier in this thread).
