### ISSUE TITLE
Feature request: smooth scrolling

### ISSUE THREAD

**Issue by mikemaccana** [microsoft/terminal#3519] opened 2019-11-11 15:01 UTC
# Description of the new feature/enhancement

When watching logs, or build processes, similar lines being shown repeatedly can often make it hard to determine if anythings happening (as each new page of data looks the same as the previous one)

Smooth scrolling would help this.

**Comment by zadjii-msft** [comment] 2019-11-11 15:54
Thanks for the suggestion! This looks like it's a /dupe of #1400.

**Closed** 2019-11-11 15:54 UTC
Labels: Issue-Feature, Needs-Tag-Fix, Needs-Triage
