### ISSUE TITLE
Why the the new terminal closes when I run .bat script as admin and the old terminal runs the code?

### ISSUE THREAD

**Issue by shafayetejaman** [microsoft/terminal#16072] opened 2023-09-30 12:34 UTC
I set the cmd to run as admin but it does not work.

**Comment by zadjii-msft** [comment] 2023-10-02 11:20
Can you provide like, a lot more details here/? 

Do you have a minimal `bat` file that reproduces the issue? How are you running the .bat file (double clicking it, running it from your shell in an already running Terminal)? What version of the Terminal are you on? 

I'd also maybe recommend setting `"closeOnExit": "never"` in your Terminal settings. That might help debug why the Terminal is closing.

**Comment by shafayetejaman** [comment] 2023-10-02 12:14
@echo off

:: BatchGotAdmin
:-------------------------------------
REM  --> Check for permissions
    IF "%PROCESSOR_ARCHITECTURE%" EQU "amd64" (
>nul 2>&1 "%SYSTEMROOT%\SysWOW64\cacls.exe" "%SYSTEMROOT%\SysWOW64\config\system"
) ELSE (
>nul 2>&1 "%SYSTEMROOT%\system32\cacls.exe" "%SYSTEMROOT%\system32\config\system"
)

REM --> If error flag set, we do not have admin.
if '%errorlevel%' NEQ '0' (
    echo Requesting administrative privileges...
    goto UACPrompt
) else ( goto gotAdmin )

:UACPrompt
    echo Set UAC = CreateObject^("Shell.Application"^) > "%temp%\getadmin.vbs"
    set params= %*
    echo UAC.ShellExecute "cmd.exe", "/c ""%~s0"" %params:"=""%", "", "runas", 1 >> "%temp%\getadmin.vbs"

    "%temp%\getadmin.vbs"
    del "%temp%\getadmin.vbs"
    exit /B

:gotAdmin
    pushd "%CD%"
    CD /D "%~dp0"
:--------------------------------------    
    <YOUR BATCH SCRIPT HERE>

I'm using this script to get admin privilege from double-click.
Windows Terminal
Version: 1.18.2681.0

https://github.com/microsoft/terminal/assets/112795252/1dad0ae1-a428-4b80-81ae-12449ac5634e

**Comment by zadjii-msft** [comment] 2023-10-02 14:44
Ah yep okay that exactly explains it. This is #10276 - the "default terminal" handoff doesn't work for any elevated command-line sessions like this. So the script:
* starts a new elevated `cmd.exe`
* The OS spawns that in a `conhost` (the vintage console), because it can't hand off to an elevated Terminal instance.
* The original terminal exits, because the original script exited. 
* The command runs to completion in the elevated conhost. 

/dup #10276

**Closed by zadjii-msft** 2023-10-02 14:44 UTC
Labels: Needs-Triage, Needs-Attention, Needs-Tag-Fix
