### ISSUE TITLE
Find command doesn't reset search text if Find box is open

### ISSUE THREAD

**Issue by DavidKarlas** [microsoft/terminal#8671] opened 2020-12-28 19:18 UTC
# Environment

```none
Windows build number: 10.0.19042.0
Windows Terminal version (if applicable): 1.4.3243.0
```

# Steps to reproduce

Execute "find" command, default keybinding is "ctrl+shift+f".
Type "hello".
Execute "find" command again, default keybinding is "ctrl+shift+f".
Type "world".

# Expected behavior

Find box opened with text "world" in it.

# Actual behavior

Find box opened with text "helloworld" in it.

Why do I think this bug? Because this is behavior of most applications. e.g: Edge, Visual Studio, Visual Studio Code...

I think easiest and most correct fix would be to "select all" text when Find command in executed and FindBox is already opened.

**Comment by zadjii-msft** [comment] 2021-01-03 14:13
@Don-Vito will this also conveniently be fixed by #8521?

**Comment by Don-Vito** [comment] 2021-01-03 14:20
@zadjii-msft - welcome back man! :blush: 
Nope - it won't be fixed by this PR. I believe there is no flow today that cleanups the needle. We only override it if something was selected, we do not override with empty string.
I've seen this as a kind of a feature :smile: I can absolutely fix it. 
Pay attention that if hello was found in the text it will be selected and thus populated in any case.

**Comment by zadjii-msft** [comment] 2021-01-03 14:40
@Don-Vito Thanks!

I'm mostly thinking about the 

>  "select all" text when Find command in executed and FindBox is already opened.

solution. That's probably what we'd want to do here.

**Comment by Don-Vito** [comment] 2021-01-03 14:48
@zadjii-msft - wait... :smile: probably I don't know what select all means.. because we do select all the text in the searchbox when invoking the find command.

**Comment by DavidKarlas** [comment] 2021-01-03 15:04
Looks like if I click with mouse on terminal to move focus out of FindBox, and press FindCommand keys it focused FindBox again and selects all text, but if I never leave FindBox and press FindCommand keys again nothing happens.

**Comment by Don-Vito** [comment] 2021-01-03 15:08
@DavidKarlas - thanks! It make sense. We had a defect that when you are focusing on the FindBox the shortcuts are not executed. So when you press FindCommand keys for every command nothing happens (when focused on the FindBox try try to click ctrl-shift-p to see that the command palette is not open as well). We fixed it here: https://github.com/microsoft/terminal/pull/8586.

**Comment by zadjii-msft** [comment] 2021-01-03 15:10
Ahhhhh okay yep, that makes sense. I'll close this one as a dupe, since they had the same root cause. 

/dup #6679

Thanks!

**Comment by DavidKarlas** [comment] 2021-01-03 15:10
Yep its seems to be same issue, Ctrl+Shift+P also doesn't have effect... Is there any preview/internals channel that has this fix?

**Closed by zadjii-msft** 2021-01-03 15:10 UTC
Labels: Area-TerminalControl, Issue-Bug, Needs-Triage, Priority-3, Product-Terminal

**Comment by Don-Vito** [comment] 2021-01-03 15:22
@DavidKarlas - not that I am aware of (beyond building from source code)..
Probably @zadjii-msft  can help - I would also love to learn what and when gets released :smile:

**Comment by zadjii-msft** [comment] 2021-01-04 16:43
We don't really have a more specific timeline to share for 1.6 other than "later in January" - there's a longer release cycle here because of the long holidays. Otherwise it's _usually_ about once a month.
