### ISSUE TITLE
Consider customizing cursor blink

### ISSUE THREAD

**Issue by imkiva** [microsoft/terminal#4296] opened 2020-01-19 12:21 UTC
# Description of the new feature/enhancement
Allows the user to control whether the cursor should blink.

So we can write something like this in `profiles.json`:
```json
"cursorBlink": false,
```
to disable cursor blink (like other terminals: iTerm2, Konsole, etc.)

# Proposed technical implementation details (optional)

**Comment by j4james** [comment] 2020-01-19 13:56
Sounds like a duplicate of #1379.

**Comment by zadjii-msft** [comment] 2020-01-19 22:43
Yep this looks like a dupe to me. Thanks!

/dup #4296

**Closed by zadjii-msft** 2020-01-19 22:43 UTC
Labels: Issue-Feature, Needs-Tag-Fix, Needs-Triage
