### ISSUE TITLE
new command, assigneable to key binding

### ISSUE THREAD

**Issue by dmarinescu** [microsoft/terminal#5711] opened 2020-05-03 02:56 UTC
{
      "command": "cls",
      "keys": [ "ctrl+l" ]
    }

or whatever, more generic command syntax suits you

**Comment by DHowett-MSFT** [comment] 2020-05-03 03:04
Sorry, is this a request for a clear screen binding? That wasn’t clear from the title. 

If you’re using bash, zsh or PowerShell you can use Ctrl+L to clear the screen. Right now, it is the shell’s job to clear the screen. 

If you want the terminal to have a reset screen key binding, this is a duplicate of another request. I won’t close this bug until I am certain.

**Comment by dmarinescu** [comment] 2020-05-03 03:39
close it, it does not matter

**Comment by DHowett-MSFT** [comment] 2020-05-03 04:38
I’d like to understand your request :smile:

**Comment by dmarinescu** [comment] 2020-05-03 04:46
i would find it useful, regardless on who is handling this in bash, for
windows terminal, especially under cmd personality, to be able to set
ctrl-l to render into a certain string, injected into the input buffer, like
  "keybindings": [
    {
      "command": "closePane",
      "keys": [ "ctrl+d" ]
    },
    {
      "command": "cls",
      "keys": [ "ctrl+l" ]
    }
  ]

closePan is a member of shortcutactionname enum, but there is not
easy/obvious way to associate (short)keys with commands injected in the
input buffer, just like they were typed by the end looser (as you call them)

 "ShortcutActionName": {
      "enum": [
        "adjustFontSize",
        "closePane",
        "closeTab",
        "closeWindow",
        "copy",
        "decreaseFontSize",
        "duplicateTab",
        "moveFocus",
        "newTab",
        "nextTab",
        "openNewTabDropdown",
        "openSettings",
        "paste",
        "prevTab",
        "resetFontSize",
        "resizePane",
        "scrollDown",
        "scrollDownPage",
        "scrollUp",
        "scrollUpPage",
        "splitPane",
        "switchToTab",
        "toggleFullscreen",
        "find",
        "unbound",

        *"input"*

 ],
      "type": "string"
    }

would allow


  "keybindings": [
    {
      "command": "input:cls",
      "keys": [ "ctrl+l" ]
    }
  ]

where input would be the new enum member (ugly like hell as it is
statically defined) and cls as being the param...

no biggie

**Comment by dmarinescu** [comment] 2020-05-03 04:50
i would like to have an easy way (in settings) to associate a certain key
with a particular / custom design string to be injected in the input
buffer. so i can create (for example) a new keybinding
    {
      "command": "inject:cls\n",
      "keys": [ "ctrl+l" ]
    }

or something like that

let's not split hair on syntax semantics... did not look over the source
code

**Comment by dmarinescu** [comment] 2020-05-03 04:54
i would like to be able to define a keybinding with the result of replacing
my key (e.g. ctrl-l) with a certain string (e.g. "cls\n" or "cls<nl>" or
whatever, syntax is irrelevant)

this why, whatever i may need to be automated (as in i enter ctrl-C and i
get the speed of light in my terminal line buffer)

**Comment by dmarinescu** [comment] 2020-05-03 05:03
that makes two of us, actually.

what about having a new command, allowing, at any time during editing or
current line, if a certain (short) key is detected and if it is not
contradictory with higher order semantics, the key will be replaced by a
certain, configurable string, to be injected in current cursor position, in
the line editor buffer, like a c define? like a macro...

**Comment by dmarinescu** [comment] 2020-05-03 05:08
very hard to understand, indeed

what about this (now generalized, different feature, potentially)

you are at the end of a very long / ugly line, you press ctrl-f and you get
the long line nicely formatted with ^ line continuation characters for each
little line resulted from beautifying. just an example (not functionally
congruent as this is doing more than a string insertion, but could be
generalized to do both, etc)

**Comment by j4james** [comment] 2020-05-03 09:27
This sounds similar to #5273.

**Comment by DHowett-MSFT** [comment] 2020-05-03 22:34
Thanks for explaining! I think this is captured in #3799 already -- it's a feature request for a key binding that can send any input into the terminal.

It would probably look something like...

```jsonc
{
    "command": {
        "action": "sendInput",
        "input": "cls\n"
    }
    "keys": "ctrl+shift+l"
}
```

/dup #3799.

**Closed by DHowett-MSFT** 2020-05-03 22:34 UTC
Labels: Issue-Feature, Needs-Tag-Fix, Needs-Triage

**Comment by dmarinescu** [comment] 2020-05-03 22:36
ok, perfect, thanks bro
