### ISSUE TITLE
Duplicated Ubuntu WSL profiles on fresh install

### ISSUE THREAD

**Issue by mwisnicki** [microsoft/terminal#15560] opened 2023-06-15 19:56 UTC
### Windows Terminal version

1.17.11461.0

### Windows build number

10.0.19045.3086

### Steps to reproduce

1. Install wsl ubuntu
2. Install terminal

### Expected Behavior

Single Ubuntu profile for WSL

### Actual Behavior

Two Ubuntu profiles for wsl Ubuntu distro:
- `wsl.exe -d Ubuntu` and penguin icon
- `ubuntu.exe` and ubuntu icon.

**Comment by lhecker** [comment] 2023-06-19 11:06
Could you comment the outputs of `wsl --version` and `wsl --list --verbose`? Additionally a screenshot of `HKCU\Software\Microsoft\Windows\CurrentVersion\Lxss` in regedit would be helpful - something like this:
![image](https://github.com/microsoft/terminal/assets/2256941/d192eb54-1816-4c75-8e68-39d74511fce7)

**Comment by zadjii-msft** [comment] 2023-06-19 11:21
Oh this is surely the fact that Canonical ships a separate profile for Ubuntu, rather than a fragment that updates the existing one we generate. This has caused no end of confusion for everyone involved. 

see #12961 et al

**Comment by carlos-zamora** [comment] 2023-06-21 21:47
Hi @mwisnicki. Thanks for filing. This is the same root cause as #12961. We need a holistic solution for all of them. Marking as a /dup of #12961

**Closed** 2023-06-21 21:47 UTC
Labels: Issue-Bug, Needs-Triage
