### ISSUE TITLE
Emojis still crashing conhost.exe

### ISSUE THREAD

**Issue by amoldeshpande** [microsoft/terminal#17948] opened 2024-09-22 04:43 UTC
### Windows Terminal version

1.20.11781.0

### Windows build number

Microsoft Windows [Version 10.0.22631.4169]

### Other Software

tcsh (https://github.com/amoldeshpande/tcsh/releases/tag/20240612.2)

### Steps to reproduce

1. start tcsh-x64.exe -f
2. paste 🐧🔐 into the shell

### Expected Behavior

https://github.com/microsoft/terminal/issues/8663 was closed as fixed in 2022, so I'm not sure if this is new or not.

Terminal does not update to a newer version than above if I go into  the "About" box. Will updating to 1.21 manually give me the fix  ?

### Actual Behavior

conhost.exe crashes.

If I do the same thing after starting tcsh in Terminal,  weird things happen that I haven't debugged yet.

**Comment by j4james** [comment] 2024-09-23 00:06
If you're using the inbox conhost (i.e. the version that comes preinstalled with Windows), I suspect it just doesn't have that fix included. Installing a new version of Windows Terminal isn't going to change that.

I know I can reproduce the crash in the conhost that's bundled with version 10.0.19041.4894 of Windows, but not in the latest version of OpenConsole built from source, so I don't think the #8663 fix has regressed (or if it did regress, it has since been fixed again).

That said, the emoji don't actually get pasted successfully - tcsh just outputs three "Command not found" errors - but at least nothing is crashing.

**Comment by lhecker** [comment] 2024-09-23 09:43
The good news is that the fix (#14745) is part of Windows 11 24H2 (build 26100+) and so it'll be publicly available as the next stable version soon. I'll be closing the issue then.

**Closed by lhecker** 2024-09-23 09:43 UTC
Labels: Issue-Bug, Needs-Triage
