### ISSUE TITLE
Font size does not match the settings in default Powershell

### ISSUE THREAD

**Issue by kneelesh48** [microsoft/terminal#6797] opened 2020-07-06 13:03 UTC
# Description of the new feature/enhancement
My laptop has a 15.6" 1920px1080p display.
I'm using font Consolas at size 16 in the default PowerShell and that has been the perfect size for my use.

But Windows Terminal font size does not match PowerShell. So I'm using font Consolas at size 11 in WT. Which is a bit bigger than Consolas at size 16 in default PowerShell and size 10 is a little too small.

This is the only reason I keep switching to default PowerShell. Some terminal outputs don't fit like they should in WT on font Consolas at size 11 and size 10 is too small to read. In my specific case, the command is `docker ps -a`.

# Proposed technical implementation details
I propose using the same font sizes as in the default PowerShell. Might be easier to implement than writing a new sizing scheme.

**Comment by DHowett** [comment] 2020-07-06 17:03
The traditional win32 console host measures fonts in _pixel sizes_. Unfortunately, we're not going to be changing either system to align with the other. The one the console host used was old and wrong and bad, and the one WT uses is in line with all other applications.
Somebody recently asked for fractional font sizes, so I'm going to close this one out as a /dupe of #6678. That would help with the issue where 10 is too small and 11 is too large.

**Closed by DHowett** 2020-07-06 17:03 UTC
Labels: Issue-Feature, Needs-Tag-Fix, Needs-Triage

**Comment by SharakPL** [comment] 2021-11-28 17:17
> The traditional win32 console host measures fonts in _pixel sizes_. Unfortunately, we're not going to be changing either system to align with the other. The one the console host used was old and wrong and bad, and **the one WT uses is in line with all other applications**. Somebody recently asked for fractional font sizes, so I'm going to close this one out as a /dupe of #6678. That would help with the issue where 10 is too small and 11 is too large.

@DHowett are you sure about that? Looks to me Terminal font size are a lot bigger than they should be. For example here's the Cascadia Mono PL at the same font size on:

**Windows Terminal**
![obraz](https://user-images.githubusercontent.com/5007456/143778513-b1a564c7-fde6-439f-bf7b-5a4f104ca3da.png)

**Visual Studio Code**
![obraz](https://user-images.githubusercontent.com/5007456/143778642-ddb1b519-a83b-4bb3-9ac7-6dab70038cea.png)

Both apps have the same default zoom level.

**Comment by DHowett** [comment] 2021-11-29 17:29
@SharakPL I am pretty sure :smile:

I have overlaid a transparent Terminal window on top of Notepad and Chromium displaying the same font size.

![image](https://user-images.githubusercontent.com/189190/143914675-2dcc76ac-ac00-4f8b-b5cd-c986b8bdf719.png)

![image](https://user-images.githubusercontent.com/189190/143914984-57542897-9e0d-4970-b7eb-52bed49ca472.png)

It appears as though _VS Code_ is the odd one out. Did you specify the font size in points?

**Comment by SharakPL** [comment] 2021-11-29 17:48
Terminal doesn't specify the unit. I suspect it's in points and that's why it's much bigger. VSCode uses pixels.

**Comment by DHowett** [comment] 2021-11-29 17:51
Indeed, that's the central thesis of this issue :)

Terminal specifies font size in points, as do most text editors, terminals, web browsers and IDEs.

The traditional windows console used pixels (really "device independent pixels", which were scaled for the display's scaling factor.)

**Comment by SharakPL** [comment] 2021-12-15 10:32
> Terminal specifies font size in points, as do most text editors, terminals, web browsers and IDEs.

Really? I would say points are good only for printers and maybe designs made to be printed, but for anything else (including editors and [especially browsers](https://css-tricks.com/css-font-size/)) pixels should be used.
