### ISSUE TITLE
Press F11 to Make the Current Tab Go Fullscreen

### ISSUE THREAD

**Issue by ShiromMakkad** [microsoft/terminal#3688] opened 2019-11-24 22:33 UTC
# Description of the new feature/enhancement

A lot of windows applications use F11 to go fullscreen. Try it on your browser, it will probably work. In many cases, I just want to use a single terminal tab in full screen, so I can run tmux inside it. Being able to go fullscreen gives me just a bit more screen area that is really helpful. 

I saw #2577, but that only involves opening full screen on startup. This was merged into #1043 which is setting an initial position for the terminal, but that doesn't really encompass having a button to open a window in fullscreen.

# Proposed technical implementation details (optional)

The user should be able to press F11 and the current tab will go fullscreen. If F11 is taken, CTRL+F11 or CTRL+SHIFT+F11 is a good pattern to use because it aligns with the opening and closing of tabs shortcuts. Also, ALT+ENTER would be a good key combination because it works on both CMD and Powershell. F11 only works on CMD

**Comment by DHowett-MSFT** [comment] 2019-11-24 22:42
You're probably talking about the feature that merged with #3408 ... so this is a /dupe of #531, #3411

**Comment by DHowett-MSFT** [comment] 2019-11-24 22:42
(Thanks for the thoughtful writeup!)

**Closed by DHowett-MSFT** 2019-11-24 22:42 UTC
Labels: Issue-Feature, Needs-Tag-Fix, Needs-Triage

**Comment by ShiromMakkad** [comment] 2019-11-24 23:11
Yea, sorry for not spotting the duplicate. I'm excited to see the feature come out!
