### ISSUE TITLE
cannot start Windows Terminal from Run diaglog

### ISSUE THREAD

**Issue by long-nguyenxuan** [microsoft/terminal#7312] opened 2020-08-17 04:38 UTC
# Environment

```none
Windows build number: [Version 10.0.19041.450]
Windows Terminal version (if applicable): 1.1.2233.0

```

# Steps to reproduce

1. Install Windows Terminal from msixbundle `Microsoft.WindowsTerminalPreview_1.2.2234.0_8wekyb3d8bbwe.msixbundle`
2. Win+R to open Run diaglog
3. `wt` -> `enter` 

# Expected behavior

Windows Terminal got executed and showed up 

# Actual behavior

Error message throw 

```
[Window Title]
C:\Program Files\WindowsApps\Microsoft.WindowsTerminalPreview_1.2.2234.0_x64__8wekyb3d8bbwe\wt.exe

[Content]
Windows cannot access the specified device, path, or file. You may not have the appropriate permissions to access the item.

[OK]
```

# Futher notice 

In step 2, if I open it with `Ctrl+Shift+Enter` combo (open in Administrator mode), then Windows Terminal showed up successfully in Administrator mode, but on some system, I don't have Administrator role to run it.

**Comment by KalleOlaviNiemitalo** [comment] 2020-08-17 10:44
This looks similar to <https://github.com/microsoft/terminal/issues/7188>. The workaround is to enable the `wt.exe` app execution alias of Windows Terminal Preview (not Windows Terminal).

**Comment by DHowett** [comment] 2020-08-18 19:37
Yes, this is effectively a /duplicate of #7188 

Once both package versions have the same alias structure, this bug should go away.

**Closed by DHowett** 2020-08-18 19:37 UTC
Labels: Needs-Tag-Fix, Needs-Triage
