### ISSUE TITLE
Invoking profiles from command line even if profile is hidden.

### ISSUE THREAD

**Issue by 4k3or3et** [microsoft/terminal#4762] opened 2020-03-01 11:57 UTC
Hi all

i would like to propose a feature/ability to invoke profiles from command using `wt --profile HIDDEN_PROFILE` even if profile is hidden by parameter `hidden": true`.

For now, when profile is hidden, Windows Terminal starts with default profile when using `wt --profile HIDDEN_PROFILE`

Do you think it is possible?

Thank you.

**Comment by DHowett-MSFT** [comment] 2020-03-02 19:18
Thanks! This is a /dupe of #4139

**Closed by DHowett-MSFT** 2020-03-02 19:19 UTC
Labels: Issue-Feature, Needs-Tag-Fix, Needs-Triage
