### ISSUE TITLE
Unable to launch WSL Ubuntu - The system cannot find the file specified.

### ISSUE THREAD

**Issue by SeeJayEmm** [microsoft/terminal#12474] opened 2022-02-11 19:51 UTC
### Windows Terminal version

1.13.10336.0

### Windows build number

10.0.19043.0

### Other Software

WSL
Ubuntu-20.04

### Steps to reproduce

Attempt to open a new Ubuntu 20.04 tab.

### Expected Behavior

Opens a WSL Ubuntu 20.04 tab.

### Actual Behavior

The system cannot find the file specified.

[process exited with code 4294967295 (0xffffffff)]

**Comment by SeeJayEmm** [comment] 2022-02-11 19:54
The command line on the profile is:
`C:\WINDOWS\system32\wsl.exe -d Ubuntu-20.04`

I am able to run this command line successfully without error. I have also tried creating a new profile from scratch with the same command line and it fails.

```
PS> wsl -l -v
  NAME            STATE           VERSION
* Ubuntu-20.04    Stopped         1
```

If I create a profile that just launches wsl with no parameters it works fine.
`C:\WINDOWS\system32\wsl.exe`

**Comment by DHowett** [comment] 2022-02-11 20:00
Can you share a copy of that profile (from profiles.json?)

What processor architecture are you using?

**Comment by SeeJayEmm** [comment] 2022-02-11 22:04
I can't find a profiles.json but I'm attaching my settings.json.
x64
[settings.json.txt](https://github.com/microsoft/terminal/files/8051896/settings.json.txt)

**Comment by uptownbrown** [comment] 2022-02-14 22:23
I've also received this error.

**Comment by zadjii-msft** [comment] 2022-02-14 22:32
Hmm. Settings are basically totally unmodified:

```jsonc

            {
                "colorScheme": "Tango Dark",
                "guid": "{07b52e3e-de2c-5db4-bd2d-ba144ed6c273}",
                "hidden": false,
                "name": "Ubuntu-20.04",
                "source": "Windows.Terminal.Wsl"
            },
```

Is this because we promoted the startingDirecotry to `~`, but then left that as the actual directory to start `wsl.exe` in? It shouldn't be... wait unless Ubuntu is shipping a fragment that starts `ubuntu.exe`. That might be a ruh roh.

**Comment by fourpastmidnight** [comment] 2022-02-14 23:08
I reported over on the WSL GitHub project.

I can confirm this is a problem with Windows Terminal because:

1. I have had no Windows Updates in over a year (a Windows Update in late 2019, and twice more in early 2020 _DELETED_ **ALL** of my personal user data on my work laptop&mdash;so yeah, I no longer allow my laptop to update at this time) and the last time I used my distribution, only a few weeks ago, it was working just fine inside of Windows Terminal.
2. The very same distribution works just fine if I start it from the Start menu tile inside the standard CMD console host window instead of using WT.

According to the [bug report on the WSL project](https://github.com/microsoft/WSL/issues/5906), one user set the starting directory to `%USERPROFILE%` and then it worked. I did the same and it did work inside of Windows Terminal, On a whim, I then set the starting directory to `/home/my-wsl-username` as opposed to the default `~`. And I still got the error. So it would appear that there's nothing special about `%USERPROFILE%`, per se, but that setting a starting directory that exists _inside the WSL distribution_ is what is currently not working in recent versions of WT. Again, everything _just works_ if starting from the Start menu tile in the standard conhost.

| Component | Version |
|:-|:-|
| Windows | Windows 10 20H2, Feature Exp Pack 120.2212.551.0 |
| Windows Terminal (Preview) | 1.13.10395.0 |

**Comment by fourpastmidnight** [comment] 2022-02-14 23:17
Just by way of update, just in case, using the Start tile entry for Ubuntu, I just updated the distribution, just in case there was something within the distro that _might_ be causing this issue, especially since I haven't updated it in a bit. Still no dice.

Also, the distro is:

![image](https://user-images.githubusercontent.com/6895593/153962956-58e438cc-3df5-4820-a54b-5d5990556460.png)

**Comment by DHowett** [comment] 2022-02-15 22:09
Would you mind grabbing a screenshot of that profile in the Settings UI? We'd like to see what the "final" command line is set to (which might not be reflected in your personal settings file, given that Ubuntu is known to ship a Terminal plugin :))

**Comment by fourpastmidnight** [comment] 2022-02-16 19:10
@DHowett Apologies for the delay...

![image](https://user-images.githubusercontent.com/6895593/154338090-4ca23c8c-fd6a-48eb-a2d8-3712ed2b5fa5.png)

Let me know if you need to see the JSON or anything. Thanks.

**Comment by fourpastmidnight** [comment] 2022-02-20 22:26
@DHowett Just checking in to see if you require any additional information to help with resolving this issue.

**Comment by fl** [comment] 2022-02-20 22:44
seeing comparable behavior here after upgrading from 21H1 to 21H2. Now on 21H2, after the upgrade, my "Debian" Terminal profile refuses to start with the error message

```
"Das System kann die angegebene Datei nicht finden.
[process exited with code 4294967295 (0xffffffff)]"

```
_(never mind the german Windows, that's a corporate artefact)._

the setting "Starting Directory" is set to "~". When I change it to either

- `/home/fl` or
- `%USERPROFILE%`

then Debian starts up with no errors displayed.

**Comment by SeeJayEmm** [comment] 2022-02-22 16:16
> Would you mind grabbing a screenshot of that profile in the Settings UI? We'd like to see what the "final" command line is set to (which might not be reflected in your personal settings file, given that Ubuntu is known to ship a Terminal plugin :))

I changed the starting directory to the work around of %USERPROFILE% since that works and I couldn't just sit around and wait for a fix.

![image](https://user-images.githubusercontent.com/788552/155173410-ef4ae557-bbac-443b-ad6a-4bea0c7d4279.png)

**Comment by phil-blain** [comment] 2022-02-22 16:27
@SeeJayEmm my workaround is to change the commandline to `wsl.exe ~ -d Ubuntu`. This is with Windows Terminal 1.11.3471, Windows 1909. I have not yet upgraded to WT 1.12.

**Comment by supersu097** [comment] 2022-02-24 06:02
> @SeeJayEmm my workaround is to change the commandline to `wsl.exe ~ -d Ubuntu`. This is with Windows Terminal 1.11.3471, Windows 1909. I have not yet upgraded to WT 1.12.

It works for me on Windows Terminal  1.12.10393.0 and Win10 20H2, thanks a lot~

**Comment by AlistairHardy** [comment] 2022-02-25 14:27
I've tried the above 1.12.10334 on Win10 Enterprise version 2004 and it has not worked

**Comment by fourpastmidnight** [comment] 2022-03-05 23:53
I have new information. On a whim, I opened a new WSL Ubuntu tab in Windows Terminal on my _home_ computer, and it worked!!

My home computer is also running Windows Terminal v1.13.10395.0. So what's different?

The starting directory setting is different.

On my work laptop, the starting directory was set to `~`. This value exhibits the problem described in this issue.
On my home laptop, the starting directory is set to `//wsl$/Ubuntu/<my-username>/home`. This setting is working under the very same version of Windows Terminal.

Not sure why my work laptop is using a different Starting directory setting, as I never changed it.

**Comment by fourpastmidnight** [comment] 2022-03-29 14:29
So, I tried updating my work computer's Windows Terminal profile for Ubuntu to the path being used by my home computer. No dice. Every time I change the Home directory path, Windows Terminal continues to change it back `~`. Since I originally posted, Windows Terminal has updated to v1.13.10733.0. So this is still an issue. BUT, it _seems_ like it could be _computer_ related, i.e. not necessarily Windows Terminal?

**Comment by Trinovantes** [comment] 2022-04-05 14:44
Been also having this issue for the past few days. Changing the starting directory to `\\wsl$\Ubuntu-20.04\home\{name}\` fixed it for me

This might be caused by `1.13.10336` update where it sets the default starting directory to `~` if the [Windows build is 19041 or higher](https://github.com/microsoft/terminal/pull/12315/files#diff-5e9c1a502c638d38b8faa6fc82b884b3208d39a93d2ebc3c8d5a8fc504c82a3aR31) but I'm currently on 19043

**Comment by fourpastmidnight** [comment] 2022-04-06 18:57
**UPDATE**

OK, I tried _again_ to update the Starting Directory of my WSL Ubuntu Windows Terminal profile. This time, the change I made "stuck" and I was able to use Windows Terminal again to start Ubuntu.

The starting directory I used was `\\wsl$\<wsl-distro-name>\home\<distro-username>`. So, I'm using the "evergreen" Ubuntu distro, so that would be `\\wsl$\Ubuntu\home\<my-distro-username>`.

This is now working for me. My version of Windows Terminal since my last update has **not** changed. So I no longer believe this to be a Windows Terminal issue. It may have been a WSL Ubuntu issue, or an issue local to my machine (though, it seems many others also experience a similar issue).

Bottom line: WOMM.

**Comment by WowSuchRicky** [comment] 2022-04-10 07:00
Hello,

I had this same issue and changing the starting directory in my Windows Terminal profile for WSL from ``` to `%USERPROFILE%` worked perfectly.

**Comment by isaacgr** [comment] 2022-04-11 16:02
> The command line on the profile is: `C:\WINDOWS\system32\wsl.exe -d Ubuntu-20.04`
> 
> I am able to run this command line successfully without error. I have also tried creating a new profile from scratch with the same command line and it fails.
> 
> ```
> PS> wsl -l -v
>   NAME            STATE           VERSION
> * Ubuntu-20.04    Stopped         1
> ```
> 
> If I create a profile that just launches wsl with no parameters it works fine. `C:\WINDOWS\system32\wsl.exe`

Adding this line to the settings.json for the ubuntu profile file worked for me
` "commandline": "wsl.exe ~ -d Ubuntu",`

**Comment by EvanMcEwen** [comment] 2022-04-14 17:18
> seeing comparable behavior here after upgrading from 21H1 to 21H2. Now on 21H2, after the upgrade, my "Debian" Terminal profile refuses to start with the error message
> 
> ```
> "Das System kann die angegebene Datei nicht finden.
> [process exited with code 4294967295 (0xffffffff)]"
> ```
> 
> _(never mind the german Windows, that's a corporate artefact)._
> 
> the setting "Starting Directory" is set to "~". When I change it to either
> 
>     * `/home/fl` or
> 
>     * `%USERPROFILE%`
> 
> 
> then Debian starts up with no errors displayed.

This fixed my issues thank you.

**Comment by tydemeadows** [comment] 2022-04-25 14:50
Fixed My Issue with This by going to

-  Terminal Settings
-  Defaults (Just Under Profile Header)
-  Starting Directory 
-  !!!! Uncheck "Use Parent Process Directory"

![Capture](https://user-images.githubusercontent.com/59396897/165114429-8fa303e0-8928-4515-8293-e4ba21b663fc.JPG)

**Comment by zadjii-msft** [comment] 2022-05-02 16:38
Okay there's a lot of reports here, I'm gonna try and distill this down 

 
Seems like the whole "default to `~` for WSL's [on <= 19041](https://github.com/microsoft/terminal/pull/12315/files#diff-5e9c1a502c638d38b8faa6fc82b884b3208d39a93d2ebc3c8d5a8fc504c82a3aR31)" doesn't work for folks. Reports that this doesn't work on:
* [21H2](https://github.com/microsoft/terminal/issues/12474#issuecomment-1046337276) (`19044`)
* [19043](https://github.com/microsoft/terminal/issues/12474#issuecomment-1088800417)  (`19043`)
* [1909](https://github.com/microsoft/terminal/issues/12474#issuecomment-1047977717)  (`18363`) 
* [20H2](https://github.com/microsoft/terminal/issues/12474#issuecomment-1049522652)  (`19042`)
* [Win10 Enterprise version 2004](https://github.com/microsoft/terminal/issues/12474#issuecomment-1050899689) (`19041`)

For people affected by this, changing to `%USERPROFILE%` works as a workaround. 

I coulda swore that #12437 should have fixed this, which is in `Windows Terminal v1.12.10393.0` / `Windows Terminal Preview v1.13.10395.0`. I need to dig out a win10 machine to be able to validate though.

**Closed** 2022-05-02 17:01 UTC
Labels: Needs-Repro, Issue-Bug, Area-TerminalConnection, Needs-Attention, Product-Terminal, Priority-2

**Comment by Gerschel** [comment] 2022-06-02 17:41
I landed on this thread after I had this issue. So I'm going to leave a comment for those that come across this because of a different reason.  
In my scenario, once upon a time I setup a connection to debian using "net use" and setting it up as the z drive.

At another point when I decided to give windows terminal a whirl, it decided to use that setup for the startup directory.

For some reason, it happened a few times, where my z drive didn't connect properly on a fresh boot, and I would get this error.
The solution then was reestablishing that z drive using net use.
After coming across this thread, I tried changing it to use ~, and it worked fine.

**Comment by sandeepDevJs** [comment] 2022-06-02 19:18
> seeing comparable behavior here after upgrading from 21H1 to 21H2. Now on 21H2, after the upgrade, my "Debian" Terminal profile refuses to start with the error message
> 
> ```
> "Das System kann die angegebene Datei nicht finden.
> [process exited with code 4294967295 (0xffffffff)]"
> ```
> 
> _(never mind the german Windows, that's a corporate artefact)._
> 
> the setting "Starting Directory" is set to "~". When I change it to either
> 
> * `/home/fl` or
> * `%USERPROFILE%`
> 
> then Debian starts up with no errors displayed.

Worked Out!! Thanks mate!

**Comment by hubertsvk** [comment] 2022-07-02 07:51
Hello,
any solutions doesn`t work for me, even if I changed ~ to %USERPROFILE% or /home/fl

w11 21H2 with Windows Subsystem for Linux Preview from this  https://aka.ms/wslstorepage explained [here](https://devblogs.microsoft.com/commandline/a-preview-of-wsl-in-the-microsoft-store-is-now-available/)
`wsl --version`
`WSL version: 0.61.8.0`
`Kernel version: 5.10.102.1`
`WSLg version: 1.0.39`
`MSRDC version: 1.2.3213`
`Direct3D version: 1.601.0`
`DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp`
`Windows version: 10.0.22000.778`

**Comment by sandeepDevJs** [comment] 2022-07-02 07:59
> Hello, no solutions doesn`t work for me, even if I changed ~ to %USERPROFILE% or /home/fl
> 
> w11 21H2 with Windows Subsystem for Linux Preview from this https://aka.ms/wslstorepage explained [here](https://devblogs.microsoft.com/commandline/a-preview-of-wsl-in-the-microsoft-store-is-now-available/) `wsl --version` `WSL version: 0.61.8.0` `Kernel version: 5.10.102.1` `WSLg version: 1.0.39` `MSRDC version: 1.2.3213` `Direct3D version: 1.601.0` `DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp` `Windows version: 10.0.22000.778`

Manually change the home directory in general setting

**Comment by hubertsvk** [comment] 2022-07-02 08:02
> > Hello, no solutions doesn`t work for me, even if I changed ~ to %USERPROFILE% or /home/fl
> > w11 21H2 with Windows Subsystem for Linux Preview from this https://aka.ms/wslstorepage explained [here](https://devblogs.microsoft.com/commandline/a-preview-of-wsl-in-the-microsoft-store-is-now-available/) `wsl --version` `WSL version: 0.61.8.0` `Kernel version: 5.10.102.1` `WSLg version: 1.0.39` `MSRDC version: 1.2.3213` `Direct3D version: 1.601.0` `DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp` `Windows version: 10.0.22000.778`
> 
> Manually change the home directory in general setting

didnt helped even if i changed from ~ to %USERPROFILE% or /home/username

**Comment by sandeepDevJs** [comment] 2022-07-02 08:40
> > > Hello, no solutions doesn`t work for me, even if I changed ~ to %USERPROFILE% or /home/fl w11 21H2 with Windows Subsystem for Linux Preview from this https://aka.ms/wslstorepage explained [here](https://devblogs.microsoft.com/commandline/a-preview-of-wsl-in-the-microsoft-store-is-now-available/) `wsl --version` `WSL version: 0.61.8.0` `Kernel version: 5.10.102.1` `WSLg version: 1.0.39` `MSRDC version: 1.2.3213` `Direct3D version: 1.601.0` `DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp` `Windows version: 10.0.22000.778`
> > 
> > 
> > Manually change the home directory in general setting
> 
> didnt helped even if i changed from ~ to %USERPROFILE% or /home/username

Change it to other directories like c:/users/<your-username-here>

**Comment by hubertsvk** [comment] 2022-07-02 08:53
> > > > Hello, no solutions doesn`t work for me, even if I changed ~ to %USERPROFILE% or /home/fl w11 21H2 with Windows Subsystem for Linux Preview from this https://aka.ms/wslstorepage explained [here](https://devblogs.microsoft.com/commandline/a-preview-of-wsl-in-the-microsoft-store-is-now-available/) `wsl --version` `WSL version: 0.61.8.0` `Kernel version: 5.10.102.1` `WSLg version: 1.0.39` `MSRDC version: 1.2.3213` `Direct3D version: 1.601.0` `DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp` `Windows version: 10.0.22000.778`
> > > 
> > > 
> > > Manually change the home directory in general setting
> > 
> > 
> > didnt helped even if i changed from ~ to %USERPROFILE% or /home/username
> 
> Change it to other directories like c:/users/

no, didnt helped, still the same. I changed it to C:\Users\hubertsvk\Documents

**Comment by sandeepDevJs** [comment] 2022-07-02 09:05
Did u resatrt

> > > > > Hello, no solutions doesn`t work for me, even if I changed ~ to %USERPROFILE% or /home/fl w11 21H2 with Windows Subsystem for Linux Preview from this https://aka.ms/wslstorepage explained [here](https://devblogs.microsoft.com/commandline/a-preview-of-wsl-in-the-microsoft-store-is-now-available/) `wsl --version` `WSL version: 0.61.8.0` `Kernel version: 5.10.102.1` `WSLg version: 1.0.39` `MSRDC version: 1.2.3213` `Direct3D version: 1.601.0` `DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp` `Windows version: 10.0.22000.778`
> > > > 
> > > > 
> > > > Manually change the home directory in general setting
> > > 
> > > 
> > > didnt helped even if i changed from ~ to %USERPROFILE% or /home/username
> > 
> > 
> > Change it to other directories like c:/users/
> 
> no, didnt helped, still the same. I changed it to C:\Users\hubertsvk\Documents

Did you restart the terminal?  See if it helps .. I don't seem to figure it out

**Comment by hubertsvk** [comment] 2022-07-02 09:19
> Did u resatrt
> 
> > > > > > Hello, no solutions doesn`t work for me, even if I changed ~ to %USERPROFILE% or /home/fl w11 21H2 with Windows Subsystem for Linux Preview from this https://aka.ms/wslstorepage explained [here](https://devblogs.microsoft.com/commandline/a-preview-of-wsl-in-the-microsoft-store-is-now-available/) `wsl --version` `WSL version: 0.61.8.0` `Kernel version: 5.10.102.1` `WSLg version: 1.0.39` `MSRDC version: 1.2.3213` `Direct3D version: 1.601.0` `DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp` `Windows version: 10.0.22000.778`
> > > > > 
> > > > > 
> > > > > Manually change the home directory in general setting
> > > > 
> > > > 
> > > > didnt helped even if i changed from ~ to %USERPROFILE% or /home/username
> > > 
> > > 
> > > Change it to other directories like c:/users/
> > 
> > 
> > no, didnt helped, still the same. I changed it to C:\Users\hubertsvk\Documents
> 
> Did you restart the terminal? See if it helps .. I don't seem to figure it out

no, still the same

**Comment by sandeepDevJs** [comment] 2022-07-03 14:34
> > Did u resatrt
> > > > > > > Hello, no solutions doesn`t work for me, even if I changed ~ to %USERPROFILE% or /home/fl w11 21H2 with Windows Subsystem for Linux Preview from this https://aka.ms/wslstorepage explained [here](https://devblogs.microsoft.com/commandline/a-preview-of-wsl-in-the-microsoft-store-is-now-available/) `wsl --version` `WSL version: 0.61.8.0` `Kernel version: 5.10.102.1` `WSLg version: 1.0.39` `MSRDC version: 1.2.3213` `Direct3D version: 1.601.0` `DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp` `Windows version: 10.0.22000.778`
> > > > > > 
> > > > > > 
> > > > > > Manually change the home directory in general setting
> > > > > 
> > > > > 
> > > > > didnt helped even if i changed from ~ to %USERPROFILE% or /home/username
> > > > 
> > > > 
> > > > Change it to other directories like c:/users/
> > > 
> > > 
> > > no, didnt helped, still the same. I changed it to C:\Users\hubertsvk\Documents
> > 
> > 
> > Did you restart the terminal? See if it helps .. I don't seem to figure it out
> 
> no, still the same

That's it, dude, that's all I knew.

**Comment by hubertsvk** [comment] 2022-07-03 14:44
> > > Did u resatrt
> 
> > > > > > > > Hello, no solutions doesn`t work for me, even if I changed ~ to %USERPROFILE% or /home/fl w11 21H2 with Windows Subsystem for Linux Preview from this https://aka.ms/wslstorepage explained [here](https://devblogs.microsoft.com/commandline/a-preview-of-wsl-in-the-microsoft-store-is-now-available/) `wsl --version` `WSL version: 0.61.8.0` `Kernel version: 5.10.102.1` `WSLg version: 1.0.39` `MSRDC version: 1.2.3213` `Direct3D version: 1.601.0` `DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp` `Windows version: 10.0.22000.778`
> 
> > > > > > > 
> 
> > > > > > > 
> 
> > > > > > > Manually change the home directory in general setting
> 
> > > > > > 
> 
> > > > > > 
> 
> > > > > > didnt helped even if i changed from ~ to %USERPROFILE% or /home/username
> 
> > > > > 
> 
> > > > > 
> 
> > > > > Change it to other directories like c:/users/
> 
> > > > 
> 
> > > > 
> 
> > > > no, didnt helped, still the same. I changed it to C:\Users\hubertsvk\Documents
> 
> > > 
> 
> > > 
> 
> > > Did you restart the terminal? See if it helps .. I don't seem to figure it out
> 
> > 
> 
> > no, still the same
> 
> 
> 
> That's it, dude, that's all I knew.

thanks, I hope that someone will resolve it soon, or the next update will resolve this issue 🙂

**Comment by zadjii-msft** [comment] 2022-07-06 11:42
@hubertsvk can you file a new issue, and make sure to include your Terminal version, OS version, and `settings.json` file? This was tracking a very specific issue about `~` as a `startingDirectory`, but if you're seeing this error with another path, then you're likely seeing a totally separate issue.

**Comment by wexwitalo** [comment] 2022-08-18 17:32
> @SeeJayEmm my workaround is to change the commandline to `wsl.exe ~ -d Ubuntu`. This is with Windows Terminal 1.11.3471, Windows 1909. I have not yet upgraded to WT 1.12.

This worked for me as well, i use Debian. thanks.
OS Version:                10.0.19044 N/A Build 19044

{
    "commandline": "wsl.exe ~ -d debian",
    "guid": "{58ad8b0c-3ef8-5f4d-bc6f-13e4c00f2530}",
    "hidden": false,
    "name": "Debian",
    "source": "Windows.Terminal.Wsl"
}

**Comment by imPrashik** [comment] 2022-09-07 13:21
This worked for me:

wsl --unregister <Distro>

wsl --unregister Ubuntu

**Comment by f2xiao** [comment] 2022-11-08 01:52
for ppl still have this problem after usimg the above steps to troubleshoot, check if your linux distro is actually running, if not check if your motherboard has the virtualization enabled. i have my wsl2 running fine and one day this error code randomly, and i found out because the virtualization is not enabled on the motherboard. It was possibly randomly default to be disabled by driver update.

**Comment by alexmndzdev** [comment] 2023-03-08 22:50
> This worked for me:
> 
> wsl --unregister `<Distro>`
> 
> wsl --unregister Ubuntu
> 
> The relaunch Ubuntu from the Microsoft Store

This is going to delete all the files?

**Comment by marcelo-r** [comment] 2023-05-08 11:37
> wsl.exe -d DISTRO_NAME

I had a different problem, but this solved it. After Windows and WSL updated, my Windows Terminal could not keep 2 sessions/tabs of the same distro open, opening a new one permanently closed the previous tab, it was using the default `Ubuntu-22.04.exe` as command, changing to start with `wsl.exe` solved this problem.
