### ISSUE TITLE
Arrow keys seem to feed different key-codes than in cmd or powershell.

### ISSUE THREAD

**Issue by jwlodek** [microsoft/terminal#3596] opened 2019-11-15 16:05 UTC
# Environment

```none
Windows build number:  10.0.18362.0
Windows Terminal version (if applicable): 0.6.2951.0
```

Using a windows port of ncurses to work with a TUI application.

# Steps to reproduce

Print key code received on key press to terminal. Specifically the issue is with key codes for arrow keys. In `cmd` and `powershell` these are in the range 258 to 261, while when using windows terminal is in the 450-456 range with each being an even number in that range, inclusive. Most other keys seem to retain the same key values.

# Expected behavior

It would be nice to have the same key code for arrow keys so that TUI applications can work in windows terminal, if not, then is there documentation for the keycodes for each key and their differences with those found in cmd or powershell?

**Comment by DHowett-MSFT** [comment] 2019-11-18 20:40
this looks like a /dupe of #2397

**Closed by DHowett-MSFT** 2019-11-18 20:40 UTC
Labels: Needs-Tag-Fix, Needs-Triage
