### ISSUE TITLE
Position of chinese word choice box fault

### ISSUE THREAD

**Issue by L-Hugh** [microsoft/terminal#1820] opened 2019-07-04 11:33 UTC
When I type in Chinese, the word choice box is alway stay in the top left corner of the screen instead of following the cursor.

**Comment by liaojieliang** [comment] 2019-07-05 00:11
I met this issue too. 
Is it a bug or misuse? There is a workaround?

**Comment by DHowett-MSFT** [comment] 2019-07-05 00:15
Duplicate of #459.

**Closed by DHowett-MSFT** 2019-07-05 00:15 UTC
Labels: Needs-Tag-Fix, Needs-Triage
