### ISSUE TITLE
Not enough space between Non-ASCII(Japanese) characters

### ISSUE THREAD

**Issue by mst8000** [microsoft/terminal#195] opened 2018-05-29 16:37 UTC
* Windows build number:  `Version 10.0.17677.1000` (Insider Preview Skip Ahead)

* Windows Calture: ja-jp

* What you're doing and what's happening: 

1. Open New PowerShell Window.
1. Run `Update-Help` Command.
1. Start updating PowerShell help documents and display progress TUI(Text User Interface) like below image.  
<img width="500" alt="Show in PowerShell" src="https://user-images.githubusercontent.com/9160337/40670548-88dc6386-63a4-11e8-8c04-443faab810bb.png">

* What's wrong / what should be happening instead:

On above image, Not enough spaces between Japanese characters in progress TUI "ヘルプ コンテンツをダウンロードしています...".
The sentence should be displayed like this image.

<img width="400" alt="Correct Output" src="https://user-images.githubusercontent.com/9160337/40670559-9091b4d2-63a4-11e8-94e3-5a2b7c2e0c60.PNG">

and also, run `Invoke-WebRequest` and start downloading a file, progress TUI are display as following image.

<img width="500" alt="invokewebreq" src="https://user-images.githubusercontent.com/9160337/40671514-0ff7dc22-63a7-11e8-8c9f-1d95b614203f.png">

It's also lack space around "ストリーム".

* Additional Information:

  - PowerShell's Code page is `932 (ANSI/OEM- 日本語 Shift-JIS)`

  - Enabled beta WIndows setting "Use Unicode UTF-8".  
<img width="350" alt="utf8en" src="https://user-images.githubusercontent.com/9160337/40672208-10fa8244-63a9-11e8-9e18-8a335aefa52f.PNG">

**Comment by zadjii-msft** [comment] 2018-05-29 16:40
This is a dupe of #192

**Closed as completed by zadjii-msft** 2018-05-29 16:40 UTC
Labels: Resolution-Duplicate, Product-Conhost
