### ISSUE TITLE
Feature Request: Single-instance mode

### ISSUE THREAD

**Issue by mkielar** [microsoft/terminal#2379] opened 2019-08-09 23:00 UTC
# Description of the new feature/enhancement
Implement single-instance mode as an option, so that multiple executions of `wt.exe` would add new tabs to already running instance of WT, instead of opening new windows.

# Proposed technical implementation details (optional)
When I run `wt.exe` multiple times, I get a new Windows Terminal window every time. I do that quite often when navigating folders in Total Commander. I just type `wt` and expect the new tab to be opened with the directory I'm currently in in TC. Instead, I'd prefer to have a new tab in existing window.

Similarly, when running a shell (wsl.exe) inside Windows Terminal, if I type `wt.exe` I'd expect another tab to be opened. Currently nothing happens in this scenario (not even new WT window is opened).

I think, this could be managed with a single setting in `profile.json`:
`"mode": "single-window|multiple-window"` or sth similar.

**Comment by j4james** [comment] 2019-08-09 23:36
This sounds like a duplicate of #2227.

**Comment by DHowett-MSFT** [comment] 2019-08-09 23:39
sure is! thanks

**Closed by DHowett-MSFT** 2019-08-09 23:39 UTC
Labels: Issue-Feature, Needs-Tag-Fix, Needs-Triage
