### ISSUE TITLE
Add portable (stand alone) build for releases

### ISSUE THREAD

**Issue by yekanchi** [microsoft/terminal#7587] opened 2020-09-10 08:23 UTC
# add a portable release alongside with `msixbundle`

- This is useful so people can put terminal on their USB stick with their custom profile. 
- Now that `PowerShell Core` (version 7 ) also provide a stand alone version so a portable `terminal` can be used with it.
- Other terminals like `cmder` and `ConEmu` provide such capability which is very useful.

**Comment by skyline75489** [comment] 2020-09-10 10:53
Somewhat related to #7492

**Comment by DHowett** [comment] 2020-09-10 15:55
Thanks! this is a /duplicate of #1386

**Closed by DHowett** 2020-09-10 15:55 UTC
Labels: Issue-Feature, Needs-Tag-Fix, Needs-Triage
