### ISSUE TITLE
[WSL] Newlines when copying from console

### ISSUE THREAD

**Issue by strarsis** [microsoft/terminal#52] opened 2018-01-23 23:35 UTC
* Your Windows build number: Microsoft Windows [Version 10.0.16299.192]

* What you're doing and what's happening:
Select text in a (WSL/Bash on Windows) console using the mouse and 
copying it using right mouse button.

* What's wrong / what should be happening instead:
The resulting text (when pasted) got no newlines but lots of whitespace between the lines instead.

**Comment by FilipBB** [comment] 2019-07-25 15:04
Is there are workaround for this? It makes copying from the terminal very difficult, and I'm finding myself opening WSL directly just to copy text out.

**Comment by strarsis** [comment] 2019-07-25 18:10
@FilipBB: There are some workarounds:
1. Pipe the command output into a text file, open the text file in a Windows editor to copy its contents.
2. Copy the tmux (or screen or whatever terminal multiplexer is used) buffer into clipboard using a shortcut/built-in command.

**Comment by FilipBB** [comment] 2019-07-31 17:40
Thanks, unfortunately it's a little cumbersome for remote work, you'd have to copy the file back to your local machine, and I can't get tmux buffer copy on the remote side to work. Hopefully this issue gets fixed in the near future.

**Comment by CzBiX** [comment] 2019-09-04 12:48
Is there any plan to fix it?

**Comment by zadjii-msft** [comment] 2019-09-04 13:12
Looks like this bug fell under the radar.

@strarsis are you holding shift while you're copying (via right click)? In conhost, when the user holds shift while copying, we won't "trim whitespace", leaving the space at the end of the line as part of the copied text. This also applies to using <kbd>ctrl+shift+c</kbd> for copying from conhost.

Additionally, what are you pasting into? Notepad, or some other commandline application running in the console?

Also cc'ing @carlos-zamora

**Comment by CzBiX** [comment] 2019-09-04 13:38
Just left click and drag to select multiline text, then right click to copy, then Ctrl+V to paste in notepad will get single line text include a lots of space without newline.

And paste to another place will get the same result.
But the same operations works well in the original WSL terminal without issue.

example result:
```
server {                                                                                                                  listen 443 ssl http2;                                                                                                   server_name example.com;                                                                                                                                                                                                                   include snippets/log.conf;                                                                                              include snippets/auth.conf;                                                                                                                                                                                                                     location / {                                                                                                              include proxy_params;                                                                                                   proxy_pass http://10.8.1.1:8888;                                                                                      }                                                                                                                     }
```

**Comment by strarsis** [comment] 2019-09-04 14:49
@zadjii-msft: Damn, I have indeed holding the `shift` key down while right clicking (for copying).
I need to hold down the `shift` key for the initial multiline text selection, but when I right click I have to release the `Shift` key first.

**Comment by CoskunSunali** [comment] 2019-10-05 12:03
I have the `copyOnSelect` feature enabled so I don't have the `shift` key pressed at any given time. Following are the results from copying text from different profiles. WSL and git bash profiles seem to have problems.

`dotnet --info` from PS:

```ps
PS C:\Users\Coskun> dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100
 Commit:    04339c3a26

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100\

Host (useful for support):
  Version: 3.0.0
  Commit:  7d57652f33

.NET Core SDKs installed:
  2.2.402 [C:\Program Files\dotnet\sdk]
  3.0.100 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

`dotnet --info` from cmd:

```cmd
C:\Users\Coskun>dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100
 Commit:    04339c3a26

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100\

Host (useful for support):
  Version: 3.0.0
  Commit:  7d57652f33

.NET Core SDKs installed:
  2.2.402 [C:\Program Files\dotnet\sdk]
  3.0.100 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

`dotnet --info` from git bash:

```bash
Coskun@CS:~ $ dotnet --info                                                                                             .NET Core SDK (reflecting any global.json):                                                                              Version:   3.0.100                                                                                                      Commit:    04339c3a26                                                                                                                                                                                                                          Runtime Environment:                                                                                                     OS Name:     Windows                                                                                                    OS Version:  10.0.18362                                                                                                 OS Platform: Windows                                                                                                    RID:         win10-x64                                                                                                  Base Path:   C:\Program Files\dotnet\sdk\3.0.100\                                                                                                                                                                                              Host (useful for support):                                                                                                Version: 3.0.0                                                                                                          Commit:  7d57652f33                                                                                                                                                                                                                           .NET Core SDKs installed:                                                                                                 2.2.402 [C:\Program Files\dotnet\sdk]                                                                                   3.0.100 [C:\Program Files\dotnet\sdk]                                                                                                                                                                                                         .NET Core runtimes installed:                                                                                             Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]                               Microsoft.AspNetCore.All 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]                                Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]                               Microsoft.AspNetCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]                                Microsoft.AspNetCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]                                Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]                                     Microsoft.NETCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]                                      Microsoft.NETCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]                                      Microsoft.WindowsDesktop.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]                                                                                                                                              To install additional .NET Core runtimes or SDKs:                                                                         https://aka.ms/dotnet-download
```

`lsb_release -a` from WSL:

```sh
coskun@CS:~$ lsb_release -a                                                                                             No LSB modules are available.                                                                                           Distributor ID: Ubuntu                                                                                                  Description:    Ubuntu 19.04                                                                                            Release:        19.04                                                                                                   Codename:       disco
```

**Comment by gitfool** [comment] 2019-10-05 19:57
I have `copyOnSelect` disabled, using mouse right-click for copy paste, not holding shift key.
- `dotnet --info` output in cmd and PowerShell pastes correctly into VS Code
- `dir` output in cmd and PowerShell pastes incorrectly into VS Code
  - trailing whitespace, no newlines; same issue as with WSL

This makes copy paste from Microsoft Terminal useless.

**Comment by hteibler** [comment] 2019-10-11 07:32
still not working properly in Version: 0.5.2762.0
copying a text from WSL console when using scroll-back is loosing CR or LF

**Comment by giggio** [comment] 2019-11-27 16:12
Copying with <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>C</kbd> will result in a single line in either PowerShell or WSL.

Copying with right click will not result a single line in either WDL or PowerShell.

Tested on the latest version on master and on the latest from the store (0.7).

**Comment by adamncasey** [comment] 2020-04-23 12:58
It seems the text is copied as a table instead of text with new line characters. Pasting into something like MS Excel and copying back out again to my text editor produces the expected result.

**Comment by jan-glx** [comment] 2020-04-28 14:35
For me, copying from Windows terminal - WSL - ssh - tmux to Windows with correct white spaces works (only) by:
select text with the mouse while holding <kbd>shift</kbd> and copy with <kbd>Ctrl</kbd>+ <kbd>Insert</kbd>

**Comment by fendis0709** [comment] 2020-11-02 16:56
Same issue happens to me.
I can Copy - Paste from WSL Terminal, but when Paste, it doesn't has new line.
It's just inline text. No new line.
Any update on this issue? Is there any work around so I can copy - paste with new line (not inline)?
![image](https://user-images.githubusercontent.com/16249274/97895807-d73e8300-1d66-11eb-9248-6fa1fadcc2c9.png)


P.S:
I have enough experience using Linux and currently moving to Windows. I have habit of using `Ctrl + Shift + C` for Copy and `Ctrl + Shift + V` for Paste.

**Comment by strarsis** [comment] 2020-11-02 19:43
@fendis0709: Right, currently one has to just drag and select the text, while _not_ holding the Shift key to avoid this line endings issue.

**Comment by lukeschlather** [comment] 2020-12-18 19:36
So, is there an intention to fix this or is using ctrl-shift-c for copy functioning as designed? Because this is annoying.

**Comment by Don-Vito** [comment] 2020-12-23 13:17
@lukeschlather - not sure if addresses your needs, but the behavior of copy is configurable (see here: https://docs.microsoft.com/en-us/windows/terminal/customize-settings/actions#copy).
Among the settings, you can decide where the new lines should be preserved or not.

**Comment by lukeschlather** [comment] 2020-12-23 18:44
@Don-Vito where is the settings.json file located? The docs are somewhat vague.

Regardless, stripping newlines when copying seems like a bad default. Is that even a feature people want?

**Comment by DHowett** [comment] 2020-12-23 19:36
> by default

if we are doing that by default, it is a bug.

**Comment by lukeschlather** [comment] 2020-12-23 19:39
Isn't that what this bug is? I just installed WSL2 Ubuntu for the first time and I am seeing this bug. Which has been open for two years and seems like it ought to be a fairly straightforward fix.

**Comment by DHowett** [comment] 2020-12-23 19:49
You’d be surprised. There’s a lot of factors here- our shared code with the traditional windows console, its support for line wrapping, it supporting different modes of newline deferral (which directly impact wrapping behavior), and users using prompts that extend to the right column of the screen making us think that the text has wrapped. Nobody on the team hits this with any regularity, and that makes it hard to track down.

**Comment by DHowett** [comment] 2020-12-23 19:49
There’s a bug in our tracker that mentions “exact wrap”; this is another likely source of issues here. At its heart, this is a misdetection of an application’s intent to wrap or not.

**Comment by lukeschlather** [comment] 2020-12-24 01:44
That makes sense. I was reacting to the suggestion that this is a configurable option that was set this way by design. It seems everyone agrees that not copying newlines here is a bug that should be fixed, even if the fix is not obvious.

**Comment by 89z** [comment] 2021-04-23 13:02
https://github.com/microsoft/terminal/issues/1073
https://github.com/microsoft/terminal/issues/1126
https://github.com/microsoft/terminal/issues/1621
https://github.com/microsoft/terminal/issues/2275
https://github.com/microsoft/terminal/issues/2278
https://github.com/microsoft/terminal/issues/2324
https://github.com/microsoft/terminal/issues/2395
https://github.com/microsoft/terminal/issues/2717

https://github.com/microsoft/terminal/issues/52

**Comment by JeremyCCHsu** [comment] 2021-04-26 09:18
I encounter the same when I was working with a remote Ubuntu machine. I found a workaround:
Although direct pasting (ctrl+shift+v or shift+right_click) resulted in a single line, send a **signal** before pasting somehow works:

## tmux
`ctrl+B` then `ctrl+v`
![tmux](https://user-images.githubusercontent.com/16027371/116058635-9d658e00-a6b2-11eb-9644-b415188fcc75.png)


## VS Code terminal
`ctrl+v` then `ctrl+shift+v`
![vscode](https://user-images.githubusercontent.com/16027371/116058665-a5253280-a6b2-11eb-8142-ec7ae391e831.png)


The text I copied is the following
```python
# empty line 
from pathlib import Path
import numpy as np
x = np.zeros([3, 2])  
 
  
```
**The leading and the trailing empty line(s) are necessary.** (The two trailing lines are empty instead of a space, but I have to put a space there for Markdown to display them. Note that when the pasted content is a single-line, it gets white backgrounds.)

Not sure whether the above is useful, but this has become my workaround recently...

**Comment by wpater** [comment] 2021-04-27 08:13
Try to copy text with `ctrl c` instead of `ctrl shift c`.

**Comment by dyipon** [comment] 2021-07-02 20:29
Same issues with mcview :/

**Comment by joeycumines** [comment] 2021-07-27 22:25
Thanks @wpater, ctrl+c worked....

Why does it work if ctrl+shift+c doesn't, though?

**Comment by wpater** [comment] 2021-08-05 10:17
@joeycumines
> 
> 
> Thanks @wpater, ctrl+c worked....
> 
> Why does it work if ctrl+shift+c doesn't, though?

I think that CTRL+SHIFT+C interprets selection as one line. All trailing spaces at the end of visual lines are copied instead of end of line characters.

**Comment by rdeforest** [comment] 2021-10-17 20:06
This issue is more-or-less resolved for me in that the problem was The Nut Behind The Wheel. That is, PEBCAK.

What had confused me was that it was working the way I expected for a while, and until I read this issue I didn't know what I had done to change the copy behavior. In my case I had mis-understood the setting "Text format when copying". It defaults to something other than "Plain text only" and when I had encountered that setting I assumed I would never want rich text of any kind coming from or going to my terminal, so I changed it. When I switched it to HTML I got the behavior I expected: multiple lines pasted as multiple lines.

So for me the bug is that the setting is poorly documented and doesn't make sense to me. I still don't understand what it means for the plain text I copy out of a terminal to be formatted as "Both HTML and RTF". In what sense is the content I'm copying "formatted" when I execute the copy action? Shouldn't formatting be happening at a higher/lower protocol layer, depending on which way you think is up? That is, if I were using some (as far as I know non-existent) WebKit-based terminal program and I selected several lines of output from a command, I wouldn't expect the clipboard to contain `<span>command output</span>` or `command output<br/>` unless that was literally the output I had copied.

The behavior we're talking about feels to me a lot like the tool (in this case Windows Terminal) is trying too hard to anticipate users' needs instead of just doing The Simplest Thing That Could Possibly Work and letting us figure out how to do the more complex but less frequently needed things with additional tooling and such. I'm more than a little curious what the use case for the single-line-of-text behavior might be. When would I ever want that?

**Comment by zadjii-msft** [comment] 2021-11-23 22:13
Hey so, this issue's been open for a WHILE now and has drifted in root cause over the years. 

Part of this is some unintentional confusion that's definitely _my_ fault. Then the propsheet says "Use Ctrl+Shift+C/V as copy/paste", that was written erroneously. At the time I added that, I actually just added support for `Ctrl+Shift+V` paste, because it seemed to me that `Ctrl+Shift+C` for copy seemingly _always worked_. Turns out, yes, it did always work, with the caveat: `Ctrl+Shift+C` to copy in the vintage console copies **as a single line**. I'm not sure when that was added, probably before my tenure here.

So really, that checkbox should say "Use Ctrl+Shift+V as paste". #174 is here for tracking either changing that text, or changing that behavior in conhost. Neither we're particularly inclined to do, since we're largely only focusing on UX enhancements for the Terminal at this point. 

In general, to help avoid this, **DONT USE `Ctrl+Shift+C` TO COPY FROM CONHOST**.

The Console handles copy-pasting just terribly, and we've done a lot of things better with the Terminal. Including things like allowing `Ctrl+C` to copy a selection, but not send a `^C` when there's a selection. Not to forget, the keybindings are entirely customizable.

At this point, this thread is full of folks on different versions, with unclear reports of how they've got the console & terminal configured, and how they're precisely copying, and the thread isn't really discretely actionable. If you're still having trouble, it's probably best to open a new thread.

**Closed by zadjii-msft** 2021-11-23 22:13 UTC
Labels: Product-Conhost, Area-Interaction, Issue-Bug

**Comment by ultranaco** [comment] 2022-04-09 03:17
You can copy stdout with clip.exe triming new line using the following instructions

Append alias into .bash_aliases
`echo "alias clip='tr -d '\''\n'\''' | clip.exe" >> ~/.bash_aliases`

Restart your shell
`bash`

Enjoy your new clip command with pipe
`pwd | clip`

**Comment by tms320** [comment] 2024-12-14 08:49
I run command 'wsl -l -v' from pyhton script and trying to split it's output to strings.
And this is a problem.
Console output (if I run 'wsl' manually in Windows terminal) looks fine:  
![Image](https://github.com/user-attachments/assets/3f5ce8de-bb0b-481f-b46a-ad248508c353)  
But there is no new line symbols in real output. In python script I get this bytes:  
![Image](https://github.com/user-attachments/assets/8968c15d-458e-43af-bd15-8c672ff3f21f)  
So parsing the output is difficult.
