### ISSUE TITLE
Scrolling up in 'less' is very slow.

### ISSUE THREAD

**Issue by henniss** [microsoft/terminal#398] opened 2019-03-27 17:32 UTC
> Please use this form and describe your issue, concisely but precisely, with as much detail as possible

> * Your Windows build number:  (Type `ver` at a Windows Command Prompt)

Microsoft Windows [Version 10.0.17763.379]

> * What you're doing and what's happening: (Copy & paste specific commands and their output, or include screen shots)

In less, scrolling down (f) is instantaneous, but scrolling up (u) is extremely slow.  For example, if I open `man man` and hold `f`, it takes about 1 second to scroll to the end, but if I hold `u`, it will take about 10 seconds to scroll back to the top.

Behavior is similar if I run `less` on a remote system through SSH, although in that case scrolling up gives the appearance of being 'jerkier'.

**Comment by miniksa** [comment] 2019-03-27 19:54
I'm relatively certain this is a duplicate of #339. Can you (or someone) please check it with an insider build to see if it's resolved?

**Closed** 2019-05-25 04:00 UTC
Labels: Area-Performance, Help-Wanted, Issue-Bug, Needs-Author-Feedback, Needs-Repro, No-Recent-Activity, Product-Conhost
