### ISSUE TITLE
Hyperlink support

### ISSUE THREAD

**Issue by xmha97** [microsoft/terminal#5567] opened 2020-04-25 16:03 UTC
Hi, Please support the hyperlink. (Like Linux terminal)
![image](https://user-images.githubusercontent.com/23485114/80284459-d7b0ee00-8733-11ea-9b02-b8136b274f90.png)

**Comment by DHowett-MSFT** [comment] 2020-04-25 17:18
Thanks for the request! This is a /dupe of #574.

**Closed by DHowett-MSFT** 2020-04-25 17:18 UTC
Labels: Issue-Feature, Needs-Tag-Fix, Needs-Triage
