### ISSUE TITLE
Mouse scroll input for WSL linux apps like less, vim, nano etc.

### ISSUE THREAD

**Issue by nofunatall** [microsoft/terminal#9165] opened 2021-02-14 23:33 UTC
If this  feature doesn't already exist I would suggest the following where by default mouse scroll would scroll terminal applications and say something like Shift + Scroll would scroll the terminal window itself.

Much like the Linux terminals Guake or Gnome terminal (Or even cmder I believe) there would be detection of such running apps like vim and less where if these are open and in the foreground the terminal app knows to pass scroll input to the running app rather than scroll the window.

Currently all mouse scrolling does is scroll the Terminal window which is less then ideal when you're inside vim or less etc.

I've read the documentation on configurable options and I couldn't see anything applicable?

**Comment by DHowett** [comment] 2021-02-15 19:27
This looks like a /duplicate of #381. These applications are using the "most basic" mouse mode, which is "when I am a fullscreen application, send mouse scroll events to me as arrow key events." WT cannot fully detect that they're fullscreen applications, so it doesn't know to send the arrow key events on scroll.

For vim, `set mouse=a` will enable "full" mouse mode (which supports scroll, click, select, drag, etc.). For `less` there is not currently a mouse mode option.

**Closed by DHowett** 2021-02-15 19:27 UTC
Labels: Issue-Feature, Needs-Tag-Fix, Needs-Triage

**Comment by nofunatall** [comment] 2021-02-15 23:26
@DHowett-MSFT 
> This looks like a /duplicate of #381. These applications are using the _most basic_ mouse mode, which is "when I am a fullscreen application, send mouse scroll events to me as arrow key events." WT cannot fully detect that they're fullscreen applications, so it doesn't know to send the arrow key events on scroll.

If it can't detect it like a Linux console can then add a toggle to manually input mouse scroll as up arrow like I mentioned such as < shift + mouse scroll >
Or allow people to bind that to whatever they want in settings.

**Comment by DHowett** [comment] 2021-02-16 00:42
It’s more worthwhile to just fix the underlying issue :)

we do, however, have “mouse bindings” on our roadmap which would allow you to set wheel actions to send data.

**Comment by tocker** [comment] 2021-06-13 11:55
FWIW, adding the `--mouse` argument to less works for me.

```
less --mouse the_file.txt
```

Use the following commands to enable scrolling for the whole session. (Optionally add the following to your `.bashrc` | `.zshrc`):

```
[[ "${LESS}" != *--mouse* ]] && export LESS="${LESS} --mouse"
```

<details><summary>Version details</summary>

```
C:\>wsl -l -v
  NAME      STATE           VERSION
* Ubuntu    Running         2
```

```
╰─$ uname -s -r -m -p -i -o
Linux 4.19.128-microsoft-standard x86_64 x86_64 x86_64 GNU/Linux
```

```
╰─$ lsb_release -r -c -i -d
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.2 LTS
Release:        20.04
Codename:       focal
```

</details>

**Comment by smartbit** [comment] 2023-01-20 10:44
@tocker regretfully `less --mouse` disables _Automatically copy selection to clipboard_  in Microsoft Terminal
![Automatically_copy_selection_to_clipboard](https://user-images.githubusercontent.com/16225624/213674061-2b968ac8-90ed-498e-855a-f82aad12ea9f.png)
A workaround is [pressing SHIFT](https://unix.stackexchange.com/a/163724) which does seem to work in `tmux` too. Then you have a _workaround_ for a _workaround_.:cry:

**Comment by Slapbox** [comment] 2023-08-08 21:45
This workaround breaks even selecting text for me. Any advice?
