### ISSUE TITLE
Cant type. Shortcuts dont work.

### ISSUE THREAD

**Issue by Bobcruise** [microsoft/terminal#6531] opened 2020-06-16 10:55 UTC
# Environment

Windows build number:  10.0.19041.329
Windows Terminal version: 1.0.1401.0 (Microsoft Store version)

# Actual behavior
It's like the keyboard doesn't work. Cant use shortcuts(ex. switch shell) I can paste commands with the mouse right click.

**Comment by zadjii-msft** [comment] 2020-06-16 14:50
Any chance you're using PowerToys?

If you manually click in the "terminal" part of the window, can you type again?

Could you share your `settings.json`?

**Comment by Bobcruise** [comment] 2020-06-16 15:07
In the past i used the PowerToys but i deleted.

**If you manually click in the "terminal" part of the window, can you type again?**
- No.

I tried reinstall the app, and reboot, but no help.
Settings file (i deleted the comments):
```
{
  "$schema": "https://aka.ms/terminal-profiles-schema",

  "defaultProfile": "{0caa0dad-35be-5f56-a8ff-afceeeaa6101}",

  "copyOnSelect": false,

  "copyFormatting": false,

  "profiles": {
    "defaults": {
      
    },
    "list": [

      {      
        "guid": "{0caa0dad-35be-5f56-a8ff-afceeeaa6101}",
        "name": "Command Prompt",
        "commandline": "cmd.exe",
        "hidden": false
      },

      {      
        "guid": "{61c54bbd-c2c6-5271-96e7-009a87ff44bf}",
        "name": "Windows PowerShell",
        "commandline": "powershell.exe",
        "hidden": false
      },

      {
        "guid": "{b453ae62-4e3d-5e58-b989-0a998ec441b8}",
        "hidden": false,
        "name": "Azure Cloud Shell",
        "source": "Windows.Terminal.Azure"
      }
    ]
  },

  "schemes": [],
 
  "keybindings": [
   
    {
      "command": {
        "action": "copy",
        "singleLine": false
      },
      "keys": "ctrl+c"
    },
	
    {
      "command": "paste",
      "keys": "ctrl+v"
    },
	
    {
      "command": "find",
      "keys": "ctrl+shift+f"
    },
   
    {
      "command": {
        "action": "splitPane",
        "split": "auto",
        "splitMode": "duplicate"
      },
      "keys": "alt+shift+d"
    }
  ]
}
```

**Comment by Refactoring** [comment] 2020-06-16 15:47
I have the same problem. Is it due to a system update? I installed system updates(KB4557957, KB4560366) on June 12。

**Comment by DHowett** [comment] 2020-06-16 18:57
This seems like a /dupe of #4448

**Closed by DHowett** 2020-06-16 18:57 UTC
Labels: Needs-Attention, Needs-Tag-Fix, Needs-Triage, Product-Terminal
