### ISSUE TITLE
Color code may cause terminal crash in some cases

### ISSUE THREAD

**Issue by Foair** [microsoft/terminal#4320] opened 2020-01-21 15:21 UTC
# Environment

```none
# Windows Version:

Platform ServicePack Version      VersionString                    
-------- ----------- -------      -------------                    
 Win32NT             10.0.18363.0 Microsoft Windows NT 10.0.18363.0

# Terminal Version: 0.8.10091.0
```

Terminal config:

```jsonc

// To view the default settings, hold "alt" while clicking on the "Settings" button.
// For documentation on these settings, see: https://aka.ms/terminal-documentation

{
    "$schema": "https://aka.ms/terminal-profiles-schema",

    "defaultProfile": "{574e775e-4f2a-5b96-ac1e-a2962a402336}",

    "profiles":
    [
        {
            // Make changes here to the powershell.exe profile
            "guid": "{61c54bbd-c2c6-5271-96e7-009a87ff44bf}",
            "name": "Windows PowerShell",
            "commandline": "powershell.exe",
            "hidden": false
        },
        {
            // Make changes here to the cmd.exe profile
            "guid": "{0caa0dad-35be-5f56-a8ff-afceeeaa6101}",
            "name": "cmd",
            "commandline": "cmd.exe",
            "hidden": false
        },
        {
            "guid": "{574e775e-4f2a-5b96-ac1e-a2962a402336}",
            "hidden": false,
            "name": "PowerShell Core",
            "source": "Windows.Terminal.PowershellCore"
        },
        {
            "guid": "{2c4de342-38b7-51cf-b940-2309a097f518}",
            "hidden": false,
            "name": "Ubuntu",
            "source": "Windows.Terminal.Wsl",
            "fontFace": "Cascadia Mono PL",
            "fontSize": 18,
            "cursorShape": "filledBox",
            "acrylicOpacity": 0.2,
            "colorScheme": "One Half Dark",
            "useAcrylic": true
        },
        {
            "guid": "{b453ae62-4e3d-5e58-b989-0a998ec441b8}",
            "hidden": false,
            "name": "Azure Cloud Shell",
            "source": "Windows.Terminal.Azure"
        }
    ],

    // Add custom color schemes to this array
    "schemes": [],

    // Add any keybinding overrides to this array.
    // To unbind a default keybinding, set the command to "unbound"
    "keybindings": [],
    "copyOnSelect": true
}
```

# Steps to reproduce

Connect to CentOS server with SSH in WSL. Run `neofetch`, then the terminal crashed without any warnings or errors.

![image](https://user-images.githubusercontent.com/22188789/72814184-95dd5b00-3c9f-11ea-862f-c97709b250e6.png)

# Expected behavior

It's fine with `cmd.exe`.

![image](https://user-images.githubusercontent.com/22188789/72814347-df2daa80-3c9f-11ea-8457-7ccda3028e09.png)

# Actual behavior

![terminal crashes](https://user-images.githubusercontent.com/22188789/72814776-96c2bc80-3ca0-11ea-88c5-115cfa7ae6a3.gif)

![terminal crashes](https://user-images.githubusercontent.com/22188789/72815223-48fa8400-3ca1-11ea-9550-ac796a81ca69.gif)

`cmd.exe` + PowerShell Core (Normal)

![image](https://user-images.githubusercontent.com/22188789/72816548-47ca5680-3ca3-11ea-9ba9-e9a3aa638bb9.png)

Windows Terminal + PowerShell Core (Crashes)

![image](https://user-images.githubusercontent.com/22188789/72816741-9677f080-3ca3-11ea-875c-8813c1f0433a.png)

It crashes without any prompt.

---

Here is test file `info.txt`:

[info.txt](https://github.com/microsoft/terminal/files/4091678/info.txt)

Thanks for your listening! 😸 😸

**Comment by zadjii-msft** [comment] 2020-01-21 15:28
Thanks for the very detailed bug report! It's not every day you get one with this level of detail 😆 

This is actually a /dupe of #4254

**Closed by zadjii-msft** 2020-01-21 15:28 UTC
Labels: Needs-Tag-Fix, Needs-Triage
