### ISSUE TITLE
Terminal will not show completely in fullscreen mode when i use two monitors.

### ISSUE THREAD

**Issue by CannedFish** [microsoft/terminal#3912] opened 2019-12-11 09:13 UTC
# Environment

```none
Windows build number: Microsoft Windows  10.0.18362.476
Windows Terminal version (if applicable): 0.7.3382.0
```

# Steps to reproduce

Toggle into fullscreen mode.

# Expected behavior

The terminal enters into fullscreen mode without any tabs, no matter how many monitors used.
If I configure to use all monitors, it should show on all monitors.
On the other way, if I set to use only one monitor, it should show completely on the original monitor.

# Actual behavior

The terminal entered into fullscreen mode without any tabs, but not complete with two monitors.
Half of terminal will show in the original monitor's screen, and the other will not show.

![image](https://user-images.githubusercontent.com/4979748/70607246-0886ff80-1c39-11ea-8006-2e04f4c38e8c.png)
![image](https://user-images.githubusercontent.com/4979748/70607319-2f453600-1c39-11ea-929f-057c45d2077e.png)

**Comment by zadjii-msft** [comment] 2019-12-11 14:45
Huh. I guess that's correct, we don't expand to fill all the available monitors - we only take up the monitor the window is on.

Is there any application where fullscreen mode fills all the available monitors?

I'd think that supporting this style of fullscreen-ing would be incredibly challenging, since the window wouldn't necessarily have a rectangular bounds anymore. Instead, the window would be two rectangular regions (or N regions for N monitors).

**Comment by CannedFish** [comment] 2019-12-11 15:36
@zadjii-msft Thanks for replying. 

Actually what I concern is that terminal now seems recognize two monitors already but only show contents on one. That causes me losing information in fullscreen mode.

**Comment by kid1412621** [comment] 2019-12-12 13:38
same here

**Comment by DHowett-MSFT** [comment] 2019-12-12 20:43
This looks like a /dupe of #3710. There's an open pull request #3721 we're evaluating that may help this (and it looks like it solves the buffer size issue where terminal thinks it can put stuff off on your other monitor but not display it.)

**Closed by DHowett-MSFT** 2019-12-12 20:43 UTC
Labels: Needs-Attention, Needs-Tag-Fix, Needs-Triage, Product-Terminal
