### ISSUE TITLE
Print period unlimited in Chinese input method

### ISSUE THREAD

**Issue by Discreater** [microsoft/terminal#4142] opened 2020-01-07 20:22 UTC
# Environment

```none
Windows build number: 10.0.19041.0
Windows Terminal version (if applicable): 0.7.3451.0
```

# Steps to reproduce
1. Open the terminal (`powershell`)
2. **Use Chinese input method**
3. Type `c` `d` or any other characters
4. Type comma `,` or period `.`

# Expected behavior
In the default powershell, it behaves normally. It printed “成都。” or something other else.
![powershellNoBug](https://user-images.githubusercontent.com/41231596/71926258-de8c1300-31cd-11ea-94e8-42b6142d1c19.gif)

# Actual behavior
But in this Terminal. It printed "成都。。。。。。。。。。...". The period `。` after "成都“ was printed **unlimited** and I can't delete or change input method with keyboard until I changed
 the input method with mouse.
![terminalBug](https://user-images.githubusercontent.com/41231596/71925998-4beb7400-31cd-11ea-8d18-cc5657764ff1.gif)

# Addition
The same thing happened to `wsl`. And in `cmd`, after I did the same thing, it print nothing but any character typed later wasn't displayed until I change the input method.

**Comment by j4james** [comment] 2020-01-07 20:28
I think this could be a duplicate of #3706.

**Comment by zadjii-msft** [comment] 2020-01-07 20:49
Sure looks like a dupe to me. Thanks @j4james!

/dup #3706

**Closed by zadjii-msft** 2020-01-07 20:50 UTC
Labels: Needs-Tag-Fix, Needs-Triage
