### ISSUE TITLE
When i minimize and restore terminal window while running apt upgrade in wsl  last line duplicates.

### ISSUE THREAD

**Issue by kotenok2000** [microsoft/terminal#14376] opened 2022-11-12 01:55 UTC
### Windows Terminal version

1.15.2875.0

### Windows build number

10.0.22621.819

### Other Software

apt upgrade (inside wsl)
loda-rust 
https://github.com/loda-lang/loda-rust

### Steps to reproduce

1.Install WSL
2. Run sudo apt update
3. run sudo apt upgrade
4. when green progress bar shows at the bottom of the screen minimize and restore window.

### Actual Behavior

https://user-images.githubusercontent.com/8822292/201452085-21a323c0-07e2-4d56-b4f5-b1d291a0c4fe.mp4

**Comment by zadjii-msft** [comment] 2022-11-18 19:33
This harkens back to #3088. Maybe this is just a variation on that?

**Comment by carlos-zamora** [comment] 2023-02-13 21:57
Marking this as a duplicate of #3088 then. Sounds like it's the same (if not similar), so the work needed to fix it should be tracked over there.

/dup #3088

**Closed** 2023-02-13 21:57 UTC
Labels: Issue-Bug, Needs-Tag-Fix
