### ISSUE TITLE
Logging all commands that are run

### ISSUE THREAD

**Issue by Rand-o** [microsoft/terminal#6829] opened 2020-07-08 16:06 UTC
What would be the best way to automatically log every session, all the commands that were run and outputs, to its own log file?

**Comment by DHowett** [comment] 2020-07-08 20:43
Thanks for the request! We've got a similar request for transcription support, so I'm going to mark this one up as a duplicate of that.

/dup #642

**Closed by DHowett** 2020-07-08 20:43 UTC
Labels: Needs-Tag-Fix, Needs-Triage

**Comment by jantari** [comment] 2020-07-22 07:43
fyi, PowerShell has this functionality built-in:

https://www.fireeye.com/blog/threat-research/2016/02/greater_visibilityt.html
