### ISSUE TITLE
Manual install is failing to install dependencies

### ISSUE THREAD

**Issue by oullah** [microsoft/terminal#4410] opened 2020-01-30 15:22 UTC
Trying to manually install Terminal is failing with the error "App Installer failed to install package dependencies. Ask the developer for  package." I've installed the Desktop Bridge already, as well as the VC++ redistributable (https://aka.ms/vs/16/release/vc_redist.x86.exe). There is a progress bar that says "installing required frameworks" which gets about 20% or so before I get the error. 

Is there any way I can get around this? This machine is locked down so I cannot use the MS Store. Thanks

**Comment by DHowett-MSFT** [comment] 2020-01-31 06:50
This is a /dupe of #3097. Sorry about that!

**Closed by DHowett-MSFT** 2020-01-31 06:50 UTC
Labels: Needs-Tag-Fix, Needs-Triage
