### ISSUE TITLE
Emojis got question marks and shrinked in size

### ISSUE THREAD

**Issue by vazome** [microsoft/terminal#5543] opened 2020-04-24 17:46 UTC
# Environment

```none
Windows build number: 18363
Windows Terminal version: 0.11.1121.0

I have "Oh My Posh" module and Cascadia Code PL set as default font
```

# Steps to reproduce

Windows key + Period key. Type in some emoji

# Expected behavior

I do expect that when you type in some emoji it will actually show them in the line without any question markings and they all be in the same size.  Further you will see the screenshot about the subject.

# Actual behavior

![image](https://user-images.githubusercontent.com/46573198/80240519-a15b6c00-866a-11ea-8b62-009bc771213e.png)

1. Most of the emojis are question marked in the line;
2. Particular emojis are clearly smaller than other.

**Comment by vazome** [comment] 2020-04-24 18:06
It's PowerShell 5.1

**Comment by DHowett-MSFT** [comment] 2020-04-24 18:34
This looks like a /dupe of #900 and https://github.com/PowerShell/PSReadLine/issues/1329

**Closed by DHowett-MSFT** 2020-04-24 18:34 UTC
Labels: Needs-Tag-Fix, Needs-Triage
