### ISSUE TITLE
Crash opening settings dialog

### ISSUE THREAD

**Issue by skeept** [microsoft/terminal#10255] opened 2021-05-28 14:31 UTC
### Windows Terminal version (or Windows build number)

1.9.1445.0

### Steps to reproduce

Opening the setting menu, either by clicking from the menu or using `ctrl-,` shortcut

### Expected Behavior

Settings dialog is opened.

### Actual Behavior

terminal window is closed. if I have more than one terminal open only current one is closed.

**Comment by DHowett** [comment] 2021-05-28 16:37
Thanks for the report! This seems like a /duplicate of #10186, which we have a fix for waiting to be released. :smile:

**Closed by DHowett** 2021-05-28 16:37 UTC
Labels: Needs-Tag-Fix, Needs-Triage

**Comment by skeept** [comment] 2021-05-28 17:24
Thanks. I did search before opening this but didn't came up with that one.
