### ISSUE TITLE
Windows Magnifier causes dropdown to enlarge disproportionately and appear and wrong location

### ISSUE THREAD

**Issue by szilvasidave** [microsoft/terminal#11553] opened 2021-10-20 18:53 UTC
### Windows Terminal version (or Windows build number)

1.11, 1.12

### Other Software

Windows Magnifier on Windows 10

### Steps to reproduce

Start Windows Terminal
Start Windows Magnifier 
Set Magnifier type to "Full Screen"
Zoom in and open any dropdown in Windows Terminal.

### Expected Behavior

Dropdowns and its items should appear as they do when zoom is at 100%

### Actual Behavior

The dropdown and its items will appear out of place - or even outside of the viewport - and will be enlarged.

This was mentioned in issue #1548 and then #2954 but they got closed and no workaround was given and issue wasnt fixed.

This seems to be a Windows Terminal specific issue because dropdowns in literally any other application appear properly

**Comment by zadjii-msft** [comment] 2021-10-20 19:17
Sorry, that one never got linked properly to the upstream issue. The root cause is being tracked in https://github.com/microsoft/microsoft-ui-xaml/issues/1875, which I just linked back to in #1548.

/dup #1548 

re: 
> This seems to be a Windows Terminal specific issue because dropdowns in literally any other application appear properly

This is more specifically a XAML Islands issue. Just so happens that there's not a whole ton of apps that are using XAML Islands quite yet, so that's why it seems like everything else works. 

It also seems like this was fixed in Windows 11, so maybe we can get that fix backported to Windows 10.

**Closed by zadjii-msft** 2021-10-20 19:17 UTC
Labels: Needs-Triage, Needs-Tag-Fix
