### ISSUE TITLE
Resizing WT window with nvim causes flickering.

### ISSUE THREAD

**Issue by flyingcat** [microsoft/terminal#17036] opened 2024-04-10 11:13 UTC
### Windows Terminal version

1.19.10573.0

### Windows build number

10.0.22631.0

### Other Software

nvim 0.9.0

### Steps to reproduce

Open nvim, then resize the window.

### Expected Behavior

It should redraw the content smoothly.

### Actual Behavior

Flickering.

Also tried Helix, same.

**Comment by carlos-zamora** [comment] 2024-04-10 21:26
Thanks for filing! This is caused by the alt buffer whenever it resizes. This is something that will require an ecosystem change to move towards synchronized updates. We're tracking this over in #8331. 

Marking as /dup of #8331

**Closed** 2024-04-10 21:26 UTC
Labels: Issue-Bug, Needs-Triage

**Comment by flyingcat** [comment] 2024-04-10 23:50
@carlos-zamora Thanks for your reply.

But I don't think it is dup. The classic CMD, Ubuntu and Linux Mint default terminal do not suffer from this.

It's more like a rendering issue. If nvim set to a colorscheme with background, it's very obvious. Not drawing in an intermediate state but just flickering, like the old GDI without double buffering on a slow computer.

Sorry to post a new comment on a closed issue.
