### ISSUE TITLE
Font Selection Not Persisting on Launch / Requires Saving Settings for Change to Take Effect

### ISSUE THREAD

**Issue by JanusDC** [microsoft/terminal#16711] opened 2024-02-14 12:46 UTC
### Windows Terminal version

1.18.10301.0

### Windows build number

Windows 11 Pro 23H2 (build number 22631.3085)

### Other Software

Droid Sans Mono for Powerline font version 1.00 build 113.

### Steps to reproduce

1. Install the "Droid Sans Mono for Powerline" font (verify installation in the Windows Fonts folder).
2. Open Windows Terminal settings.
3. Under either the "Defaults" profile or a custom profile, set the fontFace property to "Droid Sans Mono for Powerline".
4. Save settings and close Windows Terminal.
5. Reopen Windows Terminal and observe the font error.
6. Open settings again and without making changes, press "Save." The font loads correctly.

### Expected Behavior

Upon launching Windows Terminal, the configured default font or profile-specific font should load correctly without any additional actions.

### Actual Behavior

The selected font is not recognized at launch, displaying an error message similar to "The selected font 'Droid Sans Mono for Powerline' cannot be found." To make the font work, I must open the Windows Terminal settings and press "Save", even though no actual changes were made.

**Comment by JanusDC** [comment] 2024-02-14 12:47
![image](https://github.com/microsoft/terminal/assets/640837/852e42a7-1ebb-47e2-9d7d-1d866a541bd8)
Screenshot of the error, in Spanish.

**Comment by carlos-zamora** [comment] 2024-02-14 22:37
Thanks for filing. If you choose to install this font for all users (which might require using the more options context menu) does this issue go away /?

**Comment by JanusDC** [comment] 2024-02-14 23:08
Yes! I just installed it for all users, and the issue went away.

**Comment by lhecker** [comment] 2024-02-15 16:49
Thanks for letting us know. It's a /duplicate of #3257 in that case. It's one of the most common bug reports we get, but we probably won't see a fix any time soon (it's outside of our control). 😕

**Closed** 2024-02-15 16:52 UTC
Labels: Issue-Bug, Needs-Attention, Product-Terminal
