### ISSUE TITLE
New hotkey bindings are not reflected in dropdown UI

### ISSUE THREAD

**Issue by daniel-norris** [microsoft/terminal#8272] opened 2020-11-14 14:53 UTC
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.19042.630]
Windows Terminal version (if applicable): 1.4.3141.0
```

# Steps to reproduce

Open `settings.json` in your text editor and follow the instructions in the documentation (found [here](https://docs.microsoft.com/en-us/windows/terminal/customize-settings/actions)) to change the default bindings. In the screenshots below I have changed the bindings from `ctrl+shift+1`, `ctrl+shift+2`, etc... to `alt+1`. 

Save and then restart your Windows Terminal client and use the default hotkey (`ctrl+shift+space`) to access the dropdown or click the caret to open.

# Expected behavior

The dropdown should accurately reflect the new hotkeys set in `settings.json` for new tabs. 

# Actual behavior

After the `settings.json` file is updated and hotkeys are set for actions to open a new tab in a desired profile, the dropdown UI does not accurately reflect the new bindings. 

![image](https://user-images.githubusercontent.com/58988735/99149851-737e5900-2688-11eb-96b6-8b0edd80b242.png)

![image](https://user-images.githubusercontent.com/58988735/99149862-8002b180-2688-11eb-8956-97c33a3bba49.png)

**Comment by daniel-norris** [comment] 2020-11-14 14:54
I would love to have a go at helping to produce a fix for this if possible?

**Comment by LuanVSO** [comment] 2020-11-15 01:09
you need to "unbound" the default key bindings, otherwise they are still bound to the same action adding:
```Json
{"keys": "ctrl+shift+1", "command": "unbound"},
```
in the key bindings should do the trick.
although maybe that menu should prefer to show the user key binding if it is set?

**Comment by DHowett** [comment] 2020-11-15 06:23
Thanks for the report! This is a /dupe of #2991 :smile: and if you're interested in working on it, there should be more info over there.

**Closed by DHowett** 2020-11-15 06:24 UTC
Labels: Needs-Tag-Fix, Needs-Triage
