### ISSUE TITLE
ctrl+c in gitbash on windows terminal kills ssh remote sessions

### ISSUE THREAD

**Issue by avasant21** [microsoft/terminal#12431] opened 2022-02-08 18:01 UTC
### Windows Terminal version

1.11.3471.0

### Windows build number

10.0.19043.0

### Other Software

Gitbash - mintty 3.5.2

### Steps to reproduce

1. Added the gitbash as default profile in Windows Terminal
2. Logged into ssh remote systems
3. Pressing ctlr+c(keyboard interrupt) kills the remote sessions and brings the prompt back to git bash

This behavior is not observed when directly running on Gitbash terminal

### Expected Behavior

ctlr+c should just interrupt the current process not the sessions

### Actual Behavior

Pressing ctlr+c(keyboard interrupt) kills the remote sessions and brings the prompt back to git bash

**Comment by fredrik-corneliusson** [comment] 2022-02-10 15:50
Bug is also discussed in git for windows:
https://github.com/git-for-windows/git/issues/3657#issuecomment-1024020071

**Comment by akulbe** [comment] 2022-02-17 19:06
Okay, I thought this issue was with my keyboard. This is happening here multiple times per day, and it's making me crazy. 🤪

**Comment by poonsakn** [comment] 2022-04-08 10:47
This also happen to me when using puTTY via plink command.

```
Windows Terminal
Version: 1.11.3471.0
```

**Comment by zadjii-msft** [comment] 2022-04-08 11:21
huh, so this is like the _opposite_ of #8034

**Comment by aschaepper** [comment] 2022-04-12 11:27
Got the same behavior but also with the older Git Version:
git version 2.35.1.windows.2
It only hapens in the git shell, other shells like powershell work.

Also the keyboard buttons home and end seem to behave weird, but only on some kind of target machines (ARM/Yoctolinux/Busybox in my case) on Ubuntu 20 home and end works. but Ctrl-c also closes the connection.

Running windows Terminal 1.12.10733.0 from the store on:
Windows 11:
21H2
OSBuild: 22000.593
Windows Feature Experience Pack 1000.22000.593.0

Reinstalled Windows Terminal, Reset the settings nothing worked so far.

**Comment by WereCatf** [comment] 2022-04-14 15:54
I noticed this bug a while ago already and haven't found a fix for it. So far I've stuck to 2.34.1, because I really need SSH and ctrl+c to work.

Would be nice to know, if the issue is caused by Windows Terminal or Gitbash, though.

**Comment by kennyhyun** [comment] 2022-04-16 13:22
ssh in Command Prompt (on Windows Terminal) has no such issue

**Comment by joaommartins** [comment] 2022-04-26 00:03
Seems to be fixed in git version 2.36.0.windows.1, running on Windows Terminal build 1.12.10982.0.

**Comment by zadjii-msft** [comment] 2022-04-26 09:57
@joaommartins that's great to hear! I had a sneaking suspicion this was a git bash issue, but I was having a hard time tracking this down.

Can any other folks confirm/? Hopefully we can just close this one out ☺️

**Comment by WereCatf** [comment] 2022-04-26 10:52
I can confirm, works fine with 2.36.0 again.

**Closed** 2022-04-26 10:54 UTC
Labels: Resolution-External, Issue-Bug, Needs-Author-Feedback, Needs-Triage, Needs-Tag-Fix

**Comment by Throbac-Labs** [comment] 2022-04-30 15:01
im runnning git version 2.36.0.windows.1 and still seeing this issue. Should i attempt a rollback? or uninstall and re-install git?

**Comment by ijin82** [comment] 2022-05-09 11:44
Same for me. That's awfull.

**Comment by jeefs** [comment] 2022-05-18 10:46
marked

**Comment by izeroo** [comment] 2022-06-06 15:37
> im runnning git version 2.36.0.windows.1 and still seeing this issue. Should i attempt a rollback? or uninstall and re-install git?

git for windows is really awfull, uninstalling wont even revert the anonying bug.

**Comment by MiguelBamberino** [comment] 2022-07-11 11:24
I am on 2.36.1.windows.1 and still getting issue,

**Comment by ijin82** [comment] 2022-07-12 11:51
> I am on 2.36.1.windows.1 and still getting issue,

just upgraded (chocolatey) to **microsoft-windows-terminal 1.14.1861.0** + **git 2.37.0** 
forks fine (resolved)

**Comment by OrlinAlvarado** [comment] 2022-07-13 14:11
I'm having the same issue, but only when using Git Bash. In the PowerShell and CMD, it works correctly.

Any idea?

**Comment by boly38** [comment] 2022-07-13 14:37
@OrlinAlvarado not sure that everyone noticed the **workaround** quoted in git-for-windows/git/issues/3657  and that worked for me 
>export MSYS=enable_pcon

**Comment by OrlinAlvarado** [comment] 2022-07-13 14:56
> @OrlinAlvarado not sure that everyone noticed the **workaround** quoted in [git-for-windows/git/issues/3657](https://github.com/git-for-windows/git/issues/3657) and that worked for me
> 
> > export MSYS=enable_pcon

Hi, @boly38 I added what you suggested, but CTRL+C, exit my ssh session.

**Comment by Shenmin-Z** [comment] 2022-07-21 08:39
> @rdoering it's not in the store, but if you are asking when will an official Git for Windows be available with this fix: It is now. https://github.com/git-for-windows/git/releases/tag/v2.36.0.windows.1

@OrlinAlvarado  2.36.0 works.

**Comment by rdoering** [comment] 2022-07-23 11:08
@Shenmin-Z thanks

**Comment by 0xaead** [comment] 2022-08-14 20:41
I rolled back till https://github.com/git-for-windows/git/releases/tag/v2.32.0.windows.1 to solve this issue. What a long and winding road.

**Comment by 83leej** [comment] 2022-08-25 14:27
reverted back to 2.30.0 to get this to work again

**Comment by OrlinAlvarado** [comment] 2022-08-25 14:31
I decided to use a different terminal for windows.
https://conemu.github.io/

**Comment by aschaepper** [comment] 2022-10-30 09:31
Perfect, works with new Version of Git! 2.38

**Comment by Eugene-Melbourne** [comment] 2022-11-06 23:22
It really depends on the SSH connection. For example

The latest one (gitbash  v2.38.1) is working fine with SSH connections to AWS EC2 instances.

But it does not work with Vagrant (Oracle VM).
To work with Vagrant (Oracle VM) the working options would be

- gitbash v2.32.0.windows 
- Windows PowerShell

**Comment by matthiasbannach** [comment] 2022-11-11 09:59
For me it happen when I have X-Forwarding enabled (e.g. -Y or -X) or the equivalent setting in .ssh/config.

Without it - no problems.

**Comment by zehawki** [comment] 2022-12-02 11:19
This issue made Windows terminal quite useless for me, and I always thought this was a Win Term issue. This thread made me realise that the culprit could be git bash. Problem seems to have gone away for SSH to AWS EC2 (my usecase) with gitbash v2.38.1.

**Comment by sanviler** [comment] 2022-12-29 09:56
still happening in version 2.39.0.windows.1 using vagrant

**Comment by robert-lill-tie** [comment] 2023-01-10 07:29
Had the same issue with 2.35.0, updated to 2.39.0(2), now it's working fine.

**Comment by karmendra** [comment] 2023-01-13 13:01
I have fresh windows 10  installations and fresh git version 2.39.0.windows.2 install and see this behavior (am using vagrant)

**Comment by karmendra** [comment] 2023-01-13 13:05
I had new installation of windows 10 and updated it. Installed `git version 2.39.0.windows.2` and it is not working as expected Ctrl+C exits me out of the ssh session and returns to git-bash prompt. vagrant is running the guest machine on virtualbox in my case.

**Comment by rai-streamline** [comment] 2023-02-03 09:29
2.39.1 still happening

**Comment by yuvaramachandran-gurusamy** [comment] 2023-02-03 13:18
This issue still observed in Git-2.39.0.

**Comment by milkpirate** [comment] 2023-02-26 19:25
Dito, really annoying! 😭

**Comment by blakeduffey** [comment] 2023-04-28 13:25
This still seem to be an issue on git 2.40.0, OpenSSH_9.2.p1

This also happens with these versions of git/OpenSSH using a vanilla powershell window.  after connecting via ssh, issuing a CTRL-C (which is muscle memory to end interrupt the remote task) results in

**client_loop: send disconnect: Broken pipe**

**Comment by xiaolitongxue666** [comment] 2023-05-11 02:51
git --version
git version 2.39.2.windows.1

**Comment by blakeduffey** [comment] 2023-05-11 13:14
OpenSSH_for_Windows_9.2p1, LibreSSL 3.7.2 does NOT have this problem

The ssh client bundled with git does

To work around it I installed OpenSSH Beta Microsoft.OpenSSH.Beta 9.2.2.0 and updated the path to prefer that version.

**Comment by karmendra** [comment] 2023-05-11 13:45
@blakeduffey Please share more details like, where did you download the OpenSSH Beta Microsoft.OpenSSH.Beta 9.2.2.0 for windows 10 host and what file you updated the path to prefer that version. Thanks.

**Comment by blakeduffey** [comment] 2023-05-12 13:38
The OpenSSH Beta 9.2.2.0 is available via winget

winget install Microsoft.OpenSSH.Beta

Since this default install requires admin (it installs the server component as well) - I use this instead:

`msiexec /a https://github.com/PowerShell/Win32-OpenSSH/releases/download/v9.2.2.0p1-Beta/OpenSSH-Win64-v9.2.2.0.msi /qb TARGETDIR="$env:LOCALAPPDATA\Programs\OpenSSH"`

This will extract the zip into a user profile directory in $env:LOCALAPPDATA

I generally add that path to the USERS path

`[Environment]::SetEnvironmentVariable("PATH", $Env:PATH + ";$env:LOCALAPPDATA\Programs\OpenSSH\program files\openssh", [EnvironmentVariableTarget]::User)`

That way that version can be invoked from any directory.  

If you restart Terminal, you should be able to issue

`ssh -V`

and get **OpenSSH_for_Windows_9.2p1, LibreSSL 3.7.2**

If I ssh to a remote linux system, run top, and issue CTRL-C - I get the linux prompt back (it doesn't terminate the ssh session)

-B

**Comment by blakeduffey** [comment] 2023-06-02 21:53
So to followup on this...

The version of OpenSSH included with git 2.41 reports as:
**OpenSSH_9.3p1, OpenSSL 1.1.1u  30 May 2023**

The version of OpenSSH available from https://github.com/PowerShell/Win32-OpenSSH/releases reports as:
**OpenSSH_for_Windows_9.2p1, LibreSSL 3.7.2**

If I connect to server X with the first client, run top, and issue CTRL-C - I get
**client_loop: send disconnect: Broken pipe**

if I connect to server X with the second client, run top, and issue CTRL-C...
it ends top and the connection remains

Both of these are the latest version available.  Obviously this isn't an issue with Terminal - but rather a certain version of the OpenSSH client.

**Comment by hkodavid** [comment] 2023-07-03 12:29
After a year of suffering, I have a solution.

Reinstall it with "Use external OpenSSH" option.

**Comment by kennyhyun** [comment] 2023-07-18 14:40
I was mainly using `cmd` instead of Gitbash when I use `ssh`

But I haven't had this symptom for a while even in Gitbash.

Using `1.16.10261.0` and git version `2.39.2.windows.1` BTW

I found today,

```
vagrant ssh
```

`^c` killed the session ONLY in Gitbash

It didn't happen when 

```
ssh -F ssh.config default
```

where `ssh.config` was generated by

```
vagrant ssh-config > ssh.config
```

It's weird but I think it's happening only in limited situation.


BTW, for external OpenSSH, can we also use `/c/Windows/System32/OpenSSH/ssh.exe`? I think that's the ssh used in cmd

**Comment by poshest** [comment] 2023-08-24 14:36
I have side by side two PCs using Windows as a host, Rocky Linux as a guest, with Vagrant + VirtualBox.  The use case is issuing a vagrant up and vagrant ssh using the git bash, and then hitting Ctrl + C

- Win7 SP1, git version 2.35.1.windows.2, vagrant version 2.2.19: Ctrl+C working fine, prints ^C only
- Win10 22H2, git version 2.42.0.windows.1, vagrant version 2.3.7: Not working, closes terminal :(
