### ISSUE TITLE
Windows Terminal title bar non clickable/interactable 

### ISSUE THREAD

**Issue by Sov3rain** [microsoft/terminal#6784] opened 2020-07-04 12:45 UTC
# Environment

```none
Microsoft Windows [Version 10.0.18363.900]
Windows Terminal 1.0.1811.0
```

# Steps to reproduce

1. Open terminal

# Expected behavior

I should be able to use the buttons on the title bar to close / expand / reduce the app, or even add new tabs.

# Actual behavior

Buttons are "dead", they don't receive clicks.

**Comment by Neo-Desktop** [comment] 2020-07-04 18:37
### Environment
```
Microsoft Windows [Version 10.0.19041.264]
Windows Terminal 1.0.1811.0
```

I have the same issues as described in https://github.com/microsoft/terminal/issues/6784#issue-650885581
Furthermore, I am unable to select/copy text.
It seems that the terminal is not responding to mouse input at all

I have also confirmed the same behavior on `Windows Terminal Preview v1.1.1812.0`

**Comment by Neo-Desktop** [comment] 2020-07-04 18:43
### Environment
```
Microsoft Windows [Version 10.0.19041.264]
Windows Terminal 1.0.1811.0
```

I have the same issues as described in https://github.com/microsoft/terminal/issues/6784#issue-650885581
Furthermore, I am unable to select/copy text.
It seems that the terminal is not responding to mouse input at all
The hover color change events for the UI buttons ( new tab, close tab, tab menu, minimize, maximize, exit ) do not fire when in the error state

I have also confirmed the same behavior on `Windows Terminal Preview v1.1.1812.0`

Restarting the computer fixes the issue in both builds.

**Comment by Sov3rain** [comment] 2020-07-05 12:55
> ### Environment
> ```
> Microsoft Windows [Version 10.0.19041.264]
> Windows Terminal 1.0.1811.0
> ```
> 
> I have the same issues as described in [#6784 (comment)](https://github.com/microsoft/terminal/issues/6784#issue-650885581)
> Furthermore, I am unable to select/copy text.
> It seems that the terminal is not responding to mouse input at all
> The hover color change events for the UI buttons ( new tab, close tab, tab menu, minimize, maximize, exit ) do not fire when in the error state
> 
> I have also confirmed the same behavior on `Windows Terminal Preview v1.1.1812.0`
> 
> Restarting the computer fixes the issue in both builds.

I did not try with the Preview, but restarting seems to fix the bug for now.

**Comment by KalleOlaviNiemitalo** [comment] 2020-07-05 21:20
<https://github.com/microsoft/terminal/issues/6120> describes similar symptoms.

**Comment by zadjii-msft** [comment] 2020-07-06 13:03
@Sov3rain Are you using PowerToys at all? If so:

* Are you using the Terminal on a high DPI display? 
  - If so, and if possible, does dragging the window to a 100% scaling display magically restore mouse functionality to the Terminal?
* Similarly, are you using the Terminal on your primary display? 
  - If so, and if possible, does dragging the window to another display magically restore mouse functionality to the Terminal?
* Does the PowerToys settings app similarly not respond to mouse input?
* Do you have the Shortcut Guide enabled in PowerToys?
  - If so, does it actually work if you long press <kbd>Win</kbd>?
* By any chance, did you recently uninstall any sort of IME (like a Chinese/Japanese/Korean language IME)?

If you're experiencing this, and you can interact with the PowerToys settings app (you might need to drag it to another monitor), then
* can you fix the issue by disabling "Shortcut Guide" in PowerToys?

**Comment by Sov3rain** [comment] 2020-07-08 18:42
@zadjii-msft 

>Are you using PowerToys at all?

Yes I do.

> * Are you using the Terminal on a high DPI display?

No, just a regular full HD 1080p monitor.

> * Similarly, are you using the Terminal on your primary display?

I only got one display.
   
>   * If so, and if possible, does dragging the window to another display magically restore mouse functionality to the Terminal?
> * Does the PowerToys settings app similarly not respond to mouse input?

I didn't encounter the bug again for now, I'll try that if it goes wrong.

> * Do you have the Shortcut Guide enabled in PowerToys?

Yes I do.

>   * If so, does it actually work if you long press Win?

Yes it does.

> * By any chance, did you recently uninstall any sort of IME (like a Chinese/Japanese/Korean language IME)?

No I didn't.

> If you're experiencing this, and you can interact with the PowerToys settings app (you might need to drag it to another monitor), then
> 
> * can you fix the issue by disabling "Shortcut Guide" in PowerToys?

As I said, I didn't encounter the issue again in my recent use of the terminal. I'll let you know if it happens again.

**Comment by DHowett** [comment] 2020-07-10 01:44
Thanks for all the info. After all that, I'm gonna mark this as a /duplicate of #6120.
Cheers, all, and thanks for playing!

**Closed by DHowett** 2020-07-10 01:44 UTC
Labels: Needs-Attention, Needs-Tag-Fix, Needs-Triage, Product-Terminal
