### ISSUE TITLE
Maximized button tooltip should show Restore Down instead of Maximize, following Windows UI consistency

### ISSUE THREAD

**Issue by pratikone** [microsoft/terminal#7856] opened 2020-10-08 00:15 UTC
# Environment

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Windows Terminal version (if applicable):


Any other software?
```
Microsoft Windows [Version 10.0.20231.1000]
Terminal version : Version: 1.3.2651.0
Any other software? No
# Steps to reproduce
1. Mouse over maximize button to notice tooltip which says Maximize
2. Click on the button to maximize Terminal. The icon changes to maximized but the tooltip remains *Maximize*

# Expected behavior
Following UI consistency of Win32 apps like cmd and powershell, a maximized window's maximize/restore button should have tooltip *Restore Down*. 

# Actual behavior
Tooltip shows *maximize* even on maximized Terminal window

**Comment by alannt777** [comment] 2020-10-08 12:49
duplicate of #5693

**Comment by pratikone** [comment] 2020-10-08 18:02
aah, it didn't come up when I searched. Maybe because I searched for maximize or something. Feel free to dupe or close it

**Comment by DHowett** [comment] 2020-10-08 18:15
Good find, @alannt777!

/dup #5693.

**Closed by DHowett** 2020-10-08 18:15 UTC
Labels: Needs-Tag-Fix, Needs-Triage
