### ISSUE TITLE
Environment changes are only picked up upon full restart

### ISSUE THREAD

**Issue by vsviridov** [microsoft/terminal#7239] opened 2020-08-10 21:50 UTC
# Environment

```none
Windows build number: Microsoft Windows NT 10.0.18362.0
Windows Terminal version (if applicable): 1.1.2021.0
```

# Steps to reproduce

* Launch Windows terminal
* Modify environment (e.g. via `Win+Pause` -> Advanced System Settings -> Environment variables)
* Open a new tab in the existing instance

# Expected behavior

* Should see environment change in the new tab

# Actual behavior

* Environment change only becomes available if the entire Terminal instance is restarted completely

**Comment by DHowett** [comment] 2020-08-11 01:54
Thanks for the report! This is a duplicate of #1125, but I decided to just leave it open in PR #7243.

**Closed** 2020-08-11 23:58 UTC
Labels: Area-TerminalConnection, In-PR, Issue-Bug, Priority-2, Product-Terminal
