### ISSUE TITLE
Feature Request: Update fontFace to support multiple fonts

### ISSUE THREAD

**Issue by anjc** [microsoft/terminal#5634] opened 2020-04-29 06:34 UTC
# Description of the new feature/enhancement

I would like to be able to list multiple fonts in `settings.json`'s `fontFace` property, so if the first font isn't available Terminal can attempt to choose from a series of fallbacks - which is what web developers [and VS Code users] do when storing multiple fonts in the [`font-family`](https://developer.mozilla.org/en-US/docs/Web/CSS/font-family) property.

This would be useful for people who sync Windows Terminal's settings across multiple devices (in my case, by [`fsutil`](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/fsutil-hardlink) hardlinking settings.json to a file in OneDrive) or share their configs with others, so the end-user can experience the modifications as-intended.

This would also allow Windows Terminal to have multiple fallbacks, like `fontFace: "Cascadia Mono, Consolas"`, when a user enters an invalid font-name.

# Proposed technical implementation details (optional)

I would recommend mirroring VS Code's implementation of this in their `settings.json` file: font names are separated by commas, with priority going from left-to-right.

**Comment by DHowett-MSFT** [comment] 2020-04-29 06:44
Thanks for the request! This is a /dupe of #2664.

**Closed by DHowett-MSFT** 2020-04-29 06:44 UTC
Labels: Issue-Feature, Needs-Tag-Fix, Needs-Triage
