### ISSUE TITLE
Stucked if type "\" in Chinese input method

### ISSUE THREAD

**Issue by szj186** [microsoft/terminal#3775] opened 2019-11-29 03:28 UTC
# Environment
Microsoft Windows [版本 10.0.19025.1]
```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Windows Terminal version (if applicable):

Any other software?
```

# Steps to reproduce
1、input method Chinese
2、press \

# Expected behavior
input 、

# Actual behavior
keep inputing "、" endlessly. cannot be interupted by ctrl+c.

**Comment by dotSlashLu** [comment] 2019-11-29 16:10
A little background for contributors: 、is the character generated for the \ key when using Chinese IMEs.

For my environment(Microsoft Windows [版本 10.0.18362.476], Terminal: 0.7.3291.0, IME: Microsoft Pinyin), the first 、 can be inputted normally, but unlike OP's behaviour, it doesn't keep outputting、, instead the consecutive 、s need to push \ twice to appear.

**Comment by dotSlashLu** [comment] 2019-11-29 16:16
Might be related to #3745

**Comment by DHowett-MSFT** [comment] 2019-11-30 00:52
Looks like a /dupe of #3706

**Closed by DHowett-MSFT** 2019-11-30 00:52 UTC
Labels: Needs-Tag-Fix, Needs-Triage
