### ISSUE TITLE
Feature request: add option to disable background transparency/acrylic when in fullscreen mode

### ISSUE THREAD

**Issue by lorenzobilli** [microsoft/terminal#6845] opened 2020-07-09 01:40 UTC
# Description of the new feature/enhancement

It would be very nice to have an option to automatically disable background trasparency (if enabled in the profile) when entering in a fullscreen terminal window (something like a "useAcrylicWithFullscreen" setting). That's because an user may want to completely isolate from other activities without the distraction of the wallpaper/other background content visible. Currently the only way to achieve this is to manually disable transparency with the CTRL+SHIFT+mouse wheel/trackpad scroll, or get rid of the transparency entirely profile-wise. An additional, separated option would be much more straightforward and useful.

# Proposed technical implementation details (optional)

**Comment by DHowett** [comment] 2020-07-10 00:06
Thanks for the request! I'm gonna mark this one as a /duplicate of #2531, even though it isn't totally the same thing. Here's why:

We're moving towards composable actions. That would be something like, "I want <kbd>F21</kbd> to enter fullscreen mode, set background color to light gray, and disable acrylic". Being able to run a set of commands in response to an action is going to give folks more flexibility, I think, than we ever could on our own by adding one-off if-this-then-that settings.

**Closed by DHowett** 2020-07-10 00:06 UTC
Labels: Issue-Feature, Needs-Tag-Fix, Needs-Triage
