### ISSUE TITLE
Configure rxvt cutchars 

### ISSUE THREAD

**Issue by andb0t** [microsoft/terminal#1174] opened 2019-06-08 12:10 UTC
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.17134.765]
Windows Terminal version (if applicable): don't know

Any other software? WSL, tmux
```

# Description of problem

 I have the problem described in this [stack exchance thread](https://superuser.com/questions/692988/is-there-a-way-to-set-margins-paddings-in-tmux) and in [my issue on WSL](https://github.com/microsoft/WSL/issues/4087): I use tmux as terminal multiplexer. It has vertical bars `|` as window separators, which appear in the WSL ubuntu 18.04 shell as normal `|` characters. When I want to copy&paste a word by double clicking, which touches the border, i.e. the `|` char, the `|` char is also selected. I would like to exclude `|` from double-click selections and make them a cutchar. This can be done on linux like this in some rxvt config file (which one?):

   ```
   URxvt*.cutchars: "()*,;<>[]{}|`\"'#│"'`"
   ```
   How do I configure this in WSL (or in cmd.exe or powershell.exe, which as I understand use the windows console as well)?

# Steps to reproduce

 Simply type a string including `|` (e.g. left|right) and double click it. It will highlight the entire string instead of just the left or right side of the `|` where you were clicking. In your browser, most likely, double clicking the string will work as I would like to have it in the WSL as well.

# Expected behavior

 I would like to only highlight (and copy&paste) one side of the `|`.

# Actual behavior

It highlights the whole string.

**Comment by zadjii-msft** [comment] 2019-06-10 13:12
I believe this is a dupe of #988.

**Closed by zadjii-msft** 2019-06-10 13:12 UTC
Labels: Needs-Tag-Fix, Needs-Triage
