### ISSUE TITLE
NOT DISPLAYING ALL OPENED TABS IN TAB LAYOUT.

### ISSUE THREAD

**Issue by elecsomk10** [microsoft/terminal#3068] opened 2019-10-05 06:27 UTC
# Environment

Windows build number: Version 10.0.18362.356
Windows Terminal version: Version: 0.5.2762.0

# Actual behavior:
**Maximize window view** : In maximize view of windows terminal, All tabs are displaying in tab layout.In this image I have opened 6 tabs in terminal.

![terminal1](https://user-images.githubusercontent.com/37346017/66250562-149aa080-e762-11e9-9082-dfaf9a2b33ef.PNG)

**Minimize window view** : But after minimizing the window view of windows terminal. Tab layout is not displaying all the 6 opened tabs. It is displaying only 3 tabs but actually 6 tabs are opened.It is hiding the remaining tabs which are not able to fit in tab layout.

![terminal2](https://user-images.githubusercontent.com/37346017/66250564-18c6be00-e762-11e9-9ddd-edda5420f7ea.PNG)

Same behavior getting for Maximize windows view also.

# Expected behavior

For this issue we expect to accomplish the space of single tab layout by multiple tabs.

**Example 1:** Microsoft Edge browser
For multiple opened tabs Microsoft Edge browser provides 'scroll tab list forward' and 'scroll tab list backward' options to scroll over all the tabs and indicates the presence of multiple tabs.

![terminal3](https://user-images.githubusercontent.com/37346017/66250567-211ef900-e762-11e9-98cd-9d80113481cb.PNG)

**Example 2:** Google Chrome browser
For multiple opened tabs Google Chrome browser squeeze all the opened tabs in single tab layout.

![terminal4](https://user-images.githubusercontent.com/37346017/66250599-b4582e80-e762-11e9-9acf-638e8a02712b.PNG)

# Steps to reproduce

To resolve this issue we can add 'scroll tab list forward/backward' options or squeeze all the opened multiple tabs in tab layout.

**Comment by j4james** [comment] 2019-10-05 08:19
The looks like a duplicate of #857 and/or #444.

**Comment by elecsomk10** [comment] 2019-10-05 08:34
Oh sorry! Would I close this issue ?

**Comment by DHowett-MSFT** [comment] 2019-10-06 03:45
Yep! Thanks for the comprehensive write-up though. /dup #857 #444 and will be fixed by #1896 (in PR at #3027)

**Closed by DHowett-MSFT** 2019-10-06 03:45 UTC
Labels: Needs-Tag-Fix, Needs-Triage
