### ISSUE TITLE
Invalid Title after opening new tab via command line

### ISSUE THREAD

**Issue by kraaden** [microsoft/terminal#9576] opened 2021-03-22 01:40 UTC
### Windows Terminal version (or Windows build number)

10.0.19042.0

### Other Software

Installed WSL Version 2 with Ubuntu Disto

### Steps to reproduce

1. Install WT, WSL2 and Ubuntu as Disto
2. Set Ubuntu as Default for WT in settings.json
3. Open a new tab with Powershell and enter the following command:

     wt --% new-tab powershell

### Expected Behavior

The first tab in the new window should be called "Windows Powershell", because it is a powershell console

### Actual Behavior

It shows that Ubuntu is started and that's not the case. The icon is also wrong.

![WT-bug](https://user-images.githubusercontent.com/16059078/111929847-cf823f80-8ab7-11eb-9d0d-021d88fdf04e.gif)

**Comment by DHowett** [comment] 2021-03-22 01:55
This is just another instance of "the provided commandline _replaces the commandline from the default profile". I believe we have an issue tracking this elsewhere on the repository.

The "right" way (today, and until we get executable->profile mapping) to launch this profile is to run `wt -p "Windows PowerShell"` (or whatever you've named the _profile_ for powershell). Otherwise, your request is "take my default profile, with all of its options like color, title, icon, name, etc. and run powershell inside it."

**Comment by DHowett** [comment] 2021-03-22 01:58
Found it! This is a /duplicate of #7552. Thanks!

**Closed by DHowett** 2021-03-22 01:58 UTC
Labels: Needs-Tag-Fix, Needs-Triage
