### ISSUE TITLE
Feature Request: report errors that occur when starting a new tab

### ISSUE THREAD

**Issue by pcolmer** [microsoft/terminal#2745] opened 2019-09-13 07:55 UTC
# Description of the new feature/enhancement

When launching a new tab, if any error occurs during the startup of the tab (e.g. an error from the command being run), Terminal needs to display the error rather than just close the tab.

This would help the user to better understand why the tab hasn't successfully opened.

An example of where this is useful is SSH terminal connections. The ssh command can fail for a number of reasons, e.g. ssh-agent isn't running, connection to server timed out, etc. At the moment, Terminal just closes the newly opened tab without any explanation.

**Comment by zadjii-msft** [comment] 2019-09-13 15:59
I'm pretty sure this is related to:

/dupe #1364 #2039 #2091 #982  #2563

I'm resolving it as a dupe of that collection of issues.

@DHowett-MSFT Is there a master issue for all those? They all seem very closely related, but there's no master "Add `graceful` closeOnExit setting, and display errors on ungraceful exits" issue

**Closed** 2019-09-13 15:59 UTC
Labels: Issue-Feature, Needs-Tag-Fix, Needs-Triage
