### ISSUE TITLE
can not load vs2019 vsvcvarall.bat

### ISSUE THREAD

**Issue by xspeed1989** [microsoft/terminal#1076] opened 2019-05-31 08:58 UTC
{
            "startingDirectory": "%USERPROFILE%",
            "guid": "{cda12610-a377-4bf2-ab27-d25594581ae4}",
            "name": "VS2019_X64",
            "colorScheme": "One Half Dark",
            "historySize": 9001,
            "snapOnInput": true,
            "cursorColor": "#FFFFFF",
            "cursorShape": "bar",
            "commandline": "%comspec% /k \"D:\\Software\\Microsoft Visual Studio\\2019\\Community\\VC\\Auxiliary\\Build\\vcvarsall.bat\" x64",
            "fontFace": "YaHei Consolas Hybrid",
            "fontSize": 10,
            "acrylicOpacity": 0.75,
            "useAcrylic": true,
            "closeOnExit": true,
            "padding": "0, 0, 0, 0",
            "icon": "ms-appx:///ProfileIcons/{0caa0dad-35be-5f56-a8ff-afceeeaa6101}.png"
        }

**Comment by zadjii-msft** [comment] 2019-05-31 12:39
I think you'll need to escape the commandline one more time, try:
```
"%comspec% /k \\\"D:\\Software\\Microsoft Visual Studio\\2019\\Community\\VC\\Auxiliary\\Build\\vcvarsall.bat\\\" x64",
```

**Comment by DHowett-MSFT** [comment] 2019-06-03 21:14
This is a duplicate of #1090; preferring 1090 because it's more robust.

**Closed by DHowett-MSFT** 2019-06-03 21:14 UTC
Labels: Area-Settings, Issue-Question, Needs-Author-Feedback, Needs-Triage, Product-Terminal
