### ISSUE TITLE
Text selection does not work when mouse starting dragging from leftmost pixel

### ISSUE THREAD

**Issue by vadimkantorov** [microsoft/terminal#5722] opened 2020-05-03 19:44 UTC
There is a little padding (a few pixels) between window left border and text. If I start text selection / dragging on the left-most pixel (I want to select all text, so it's natural to move mouse to left screen border and starting dragging). I have to measure mouse position in order to be sure to hover over the first letter, left to the first letter.

This is especially acute when running Terminal in full screen, since it's so convenient to throw mouse to left screen border.

**Comment by vadimkantorov** [comment] 2020-05-03 19:45
Unfortunately it's hard to make screenshots, since mouse is excluded from screenshots when PrintScreen

**Comment by DHowett-MSFT** [comment] 2020-05-03 20:18
Good find. This is a /dupe of #5626

**Closed by DHowett-MSFT** 2020-05-03 20:18 UTC
Labels: Needs-Tag-Fix, Needs-Triage

**Comment by vadimkantorov** [comment] 2020-05-03 21:51
@DHowett-MSFT Oops, sorry for not searching
