### ISSUE TITLE
Synchronized terminal renderers causes text buffer corruption

### ISSUE THREAD

**Issue by javierdlg** [microsoft/terminal#7831] opened 2020-10-05 21:21 UTC
# Environment

```none
Windows build number: (2004) 19041.508
Windows Terminal version (if applicable): Latest Master

Any other software?
Visual Studio 2019
```

# Steps to reproduce

1. Install the attached Terminal and UseTerm extensions to Visual Studio 2019:
http://gofile.me/6Ji0B/gkt4dnnxa

2. Open VS
3. Activate repro command under Tools -> New Terminal
    This will open two terminal windows `Main Terminal` and `Secondary Terminal`. Wait for them to initialize before continuing.
4. Undock and resize `Main Terminal` tool window to a smaller terminal size than `Secondary Terminal` tool window like so:
![image](https://user-images.githubusercontent.com/2334756/95132825-3cc23400-0715-11eb-87b9-75f4ee5a71c3.png)

5. Write `dir` or any other commands into `Main Terminal` that output large amounts of text and lines (wrong commands also work like `asdf`)

# Expected behavior
Both terminals are kept in sync and content is displayed correctly

# Actual behavior
`Secondary Terminal` suffers from text buffer corruption that makes certain lines invisible until you force the text buffer to update for those characters.

# Testing a Fix
If you'd like to patch a new Terminal.WPF.dll or PublicTerminalCore.dll files, you can find them under `%localappdata%\Microsoft\VisualStudio\16.0_<instance_ID>\Extensions\<ExtensionID>`

**Comment by DHowett** [comment] 2020-10-05 21:45
Judging by the repro here, it looks like the backing console (conhost) is being resized, but the secondary terminal is never being told about it.

Just so we're clear: _conhost in PTY mode was not designed to have two heads visible at the same time_. You'll need to communicate any viewport changes to all connected terminals yourself, if at all possible.

**Comment by DHowett** [comment] 2020-10-05 21:46
This is, at its heart, the same thing that happens when an application resizes the console's backing buffer without telling Windows Terminal.

**Comment by DHowett** [comment] 2020-10-05 21:51
One last point of note: _no PTY was designed to have two heads visible at the same time_. This is uncommon enough that coordination is required between all hosts. Screen/tmux handle this well, but they handle it _themselves_.

Closing as by design for now.

**Closed by DHowett** 2020-10-05 21:51 UTC
Labels: Needs-Tag-Fix, Needs-Triage
