### ISSUE TITLE
Weird grey text background rendering in VS Code integrated terminal using bash

### ISSUE THREAD

**Issue by HymanZHAN** [microsoft/terminal#121] opened 2018-02-25 01:28 UTC
* Windows build number:  10.0.16299.248

* Problem: I just enabled WSL on my desktop and installed Ubuntu from the Microsoft Store. I didn't like the default color scheme (which is terrible to read btw) so I made use of the [colortool](https://blogs.msdn.microsoft.com/commandline/2017/08/11/introducing-the-windows-console-colortool/) and switched to solarized_dark. Everything looked great on bash and cmd. I also made use of [ansi-dark theme](https://github.com/seebi/dircolors-solarized) to further polish text rendering. 

<img width="559" alt="ubuntubash" src="https://user-images.githubusercontent.com/26806995/36637010-61170386-19a0-11e8-8f20-15e02ae292ff.PNG">

However, when I tried to use it within VS Code as the integrated terminal, there was something strange. 

<img width="523" alt="vscode_terminal" src="https://user-images.githubusercontent.com/26806995/36636971-8da8a41e-199f-11e8-9cd3-67f864babf3b.PNG">

P.S. I am using the One Dark Pro theme extension on VS Code.
* What should be happening instead: Actually I have used bash as my integrated terminal in VS Code for the past month on my laptop. Same use of colortool and the ansi-dark theme. I was expecting the same rendered result as on my laptop, which looks like this:

<img width="362" alt="vscode_terminal_laptop" src="https://user-images.githubusercontent.com/26806995/36637027-b0e3cffc-19a0-11e8-8122-09a06f9330db.PNG">

**Comment by sethrr** [comment] 2019-01-24 15:35
Did you ever resolve this? I am having the same issue with my bash integrated terminal

**Comment by HymanZHAN** [comment] 2019-01-27 11:21
@sethrr Sorry, I cannot reproduce this problem anymore. I reinstalled the whole Win10 on my machine a few months ago. I just tried and did not observe anything abnormal.

**Comment by DHowett-MSFT** [comment] 2019-02-06 04:36
This looks like it was either fixed by us or a problem in _winpty_, the library VSCode uses on all versions of windows below 19H1.
@sethrr What versions of Windows and VSCode are you using? Have you set any unusual color schemes on _the windows console_ (outside of VSCode?)

**Comment by sethrr** [comment] 2019-02-06 18:14
Windows 10, VS Code 1.30.2

I haven't changed anything except for some Powershell profile colors which
don't seem to conflict. CMD and Powershell display fine in the Integrated
Terminal.

**Comment by miniksa** [comment] 2019-05-29 17:46
This appears to be a dupe of #85. Closing.

**Closed by miniksa** 2019-05-29 17:46 UTC
Labels: Area-Output, Issue-Bug, Product-Conhost, Resolution-Duplicate
