### ISSUE TITLE
Atlas Engine ignores Cleartype and defaults to GrayScale

### ISSUE THREAD

**Issue by qgates** [microsoft/terminal#15957] opened 2023-09-11 21:02 UTC
### Windows Terminal version

1.18.1462.0

### Windows build number

10.0.19045.3324

### Steps to reproduce

* Enable ClearType AA
* Use background transparency
* Launch `vim` or any other application which fills the entire viewport with an opaque color

### Expected Behavior

Cleartype antialising to be in effect.

### Actual Behavior

Grayscale antialiasing is still in effect.

Launching with Atlas Engine disabled, Cleartype antialising works.

**Comment by lhecker** [comment] 2023-09-11 22:32
ClearType doesn't work if you use background transparency of any kind (ClearType requires opaque backgrounds). Do you happen to use that?

**Comment by qgates** [comment] 2023-09-11 23:54
Thanks for clarifying. I do indeed have partial transparency on the terminal.

However, there is still an edge-case bug. With transparency on the terminal window, if I run vim with a non-transparent theme, ie. solid background filling the terminal window, then:
- with AtlasEngine off, cleartype works but only while vim is running with solid background. The moment I quit vim cleartype reverts to grayscale
- with AtlasEngine on, cleartype never works, even if an application (vim) has a solid background and fills the terminal screen

This edge-case discrepancy may or may not be acceptable.

**Comment by lhecker** [comment] 2023-09-12 11:25
Ah, thanks for clarifying this! I've updated the description with your description. 🙂

Thinking about it, I'd like to not address this issue at the moment, even if I realize that this is an annoying issue, in particular at 100% display scale. AtlasEngine allows glyphs to "overhang" outside of their cells, and we intend to allow this for the margins/gutters around the terminal viewport as well. In other words, glyphs can then overhang into these transparent areas:
![image](https://github.com/microsoft/terminal/assets/2256941/ce776fac-1799-4cc5-a5aa-501faa639b7e)

Making this work properly with ClearType would be rather annoying.

**Comment by carlos-zamora** [comment] 2023-09-20 22:03
Thanks for the feedback. We took some time to discuss this as a team. This issue has actually been around for a while and @zadjii-msft wrote up a conclusion on it [here](https://github.com/microsoft/terminal/issues/5098#issuecomment-610451748).

As such, we're closing this as "by design".

**Closed by carlos-zamora** 2023-09-20 22:03 UTC
Labels: Area-Rendering, Issue-Bug, Product-Terminal
