### ISSUE TITLE
Stretch background across all split panes (feature request)

### ISSUE THREAD

**Issue by IgnusG** [microsoft/terminal#7704] opened 2020-09-23 05:55 UTC
# Description of the new feature/enhancement

Stretching the background across all panes would be nice "eye candy" when there's a main image and lots of different tabs.
Specifically I saw this background used in the blogpost about the new release features (links):

![image](https://user-images.githubusercontent.com/6438760/93971681-04177780-fd71-11ea-8e88-5174921e53f5.png)

And tried it myself with a similar image, however when I started creating panes the look was a bit more unpleasant:

![image](https://user-images.githubusercontent.com/6438760/93971800-48a31300-fd71-11ea-94b4-11defe817121.png)

Imagine having this background span across all split panes:
![image](https://user-images.githubusercontent.com/6438760/93972113-f57d9000-fd71-11ea-93e4-04acb2b096db.png)

# Proposed technical implementation details (optional)

I'm unsure as to how to approach the different profile options though - since a split can have a different profile applied to it.
Maybe there should be a global background image property and then individual background image properties (currently the profile) which would be rendered on top?

> Just brainstorming ideas. I don't have enough knowledge about the internals to validate them unfortunately 😔

**Comment by DHowett** [comment] 2020-09-23 06:22
Thanks for the request! This looks like a /duplicate of #6028

**Closed by DHowett** 2020-09-23 06:22 UTC
Labels: Issue-Feature, Needs-Tag-Fix, Needs-Triage
