### ISSUE TITLE
Option menus in settings move in an unexpected behavior

### ISSUE THREAD

**Issue by AutoRip** [microsoft/terminal#10012] opened 2021-05-02 09:16 UTC
### Windows Terminal version (or Windows build number)

10.0.21370.1, 1.7.1033.0

### Steps to reproduce

1. Open the launch settings (or any other settings page contains an option menu).  
2. Click on the options menu of default config.  
3. Scroll your mouse wheel and the pop-up will move as the whole page is scrolling.  
4. The menu will not disappear if click on the blank space.  

### Actual Behavior

The pop-up menu will move as the whole page is scrolling and will not disappear when click on the blank space.  

![动画](https://user-images.githubusercontent.com/22536147/116808037-32f89600-ab69-11eb-81a1-537d973a4c7d.gif)

**Comment by j4james** [comment] 2021-05-02 10:22
This looks like duplicate of issue #9320.

**Comment by zadjii-msft** [comment] 2021-05-03 12:26
Sure is!

/dup #9320

**Closed by zadjii-msft** 2021-05-03 12:26 UTC
Labels: Needs-Tag-Fix, Needs-Triage
