### ISSUE TITLE
Command Palette should have the MRU command selected when opened

### ISSUE THREAD

**Issue by Sidneys1** [microsoft/terminal#6710] opened 2020-06-29 11:45 UTC
# Description of the new feature/enhancement

The Command Palette should keep a list of most recently used commands, and show those items first in the dropdown when opened (and before any text is entered). This would match the Command Palette feature in Visual Studio Code:

![image](https://user-images.githubusercontent.com/1771233/86000929-2dc43b00-b9dc-11ea-9136-d310dca3ccb2.png)

# Proposed technical implementation details (optional)

A first iteration would probably not need to persist this MRU list between session, however down the line this would be nice. The MRU could be persisted through a JSON file adjacent to `settings.json` that is written atomically on terminal exit (new terminals would copy the MRU from the most recently exited terminal).

**Comment by DHowett** [comment] 2020-06-29 18:08
Thanks for the request! This is a /dupe of #6647

**Closed by DHowett** 2020-06-29 18:08 UTC
Labels: Issue-Feature, Needs-Tag-Fix, Needs-Triage

**Comment by Sidneys1** [comment] 2020-06-29 18:09
Oh man, and I looked so hard for an existing issue! Thanks anyways!

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
