### ISSUE TITLE
Terminal suddenly can't find the font Cascadia Mono

### ISSUE THREAD

**Issue by johan-byggtjanst** [microsoft/terminal#11648] opened 2021-10-29 06:26 UTC
### Windows Terminal version (or Windows build number)

10.0.19043.1288

### Steps to reproduce

Just starting the Terminal on Windows 10. Not running as admin.

### Expected Behavior

A new terminal window

### Actual Behavior

Got this error

`Unable to find the selected font "Cascadia Mono".

"Consolas" has been selected instead.

Please either install the missing font or choose another one.`

**Comment by Mindfulplays** [comment] 2021-10-30 00:10
Same issue: Windows Terminal automatically closed due to Windows Update (no restarts). 
Opening Terminal again resulted in "Could not find Cascadia Code" issue that OP raised.

On 21H1 19043.1288

(The other problem is that Terminal arbitrarily closes even if Windows Update is configured to restart at a later date: All other apps function properly)

**Comment by zadjii-msft** [comment] 2021-11-01 10:39
### this is the thread

We've tracked this in other threads in the past, and we've done work to mitigate this before, but we didn't get all of it. Every time we push an update, more folks start running into this again. We've got an idea of what's wrong here - one of the code paths does the right thing for the SxS font lookup, and the other path _doesn't_, and that leads to this warning. 

In the past, we used #9375 to track this. #9734 attempted to mitigate. #10305 tracked the version of this that caused a crash on startup. 

So this was the first thread for the issue during this update, congrats. 

# IF YOU'RE HITTING THIS

Try "Repairing" the Terminal app, by going to "Settings > Apps > {whatever Terminal Install you have} > Advanced Options > Repair". This shouldn't delete your settings. (But "Reset" will, so be careful!)

<hr>

<sub>If you comment some variation of "me too" in this thread, ~you will be removed from the selfhost program~ your comment will be minimized as spam, thanks. </sub>

**Comment by Mindfulplays** [comment] 2021-11-01 23:32
I worked around by installing Cascadia manually. (Hopefully this message isn't marked as spam :)
I searched for this issue before (opening a new one ) / commenting here btw. So if possible please sticky this. 
Also I wasn't sure if it was a Terminal issue or a Cascadia issue, so juggling between those two github repos as well.
This could avoid unintentional 'spam' comments.

**Comment by barkermn01** [comment] 2021-11-02 19:42
I would also like to confirm this issue is now present in the Windows 11 Version after a windows update but I'm not sure if that is related or not I did not have this issue until a couple of days ago after a windows update, I'm currently running version 1.11.2921.0, I'm on the Insider program on the Beta Channel, so whatever this issue is it's now coming through to Windows 11 versions...

Currently on:
Edition	Windows 11 Pro
Version	21H2
Installed on	‎27/‎08/‎2021
OS build	22000.258
Experience	Windows Feature Experience Pack 1000.22000.258.0

I do have a Windows Update pending will update this message if this update resolves the problem for me...

**Comment by zadjii-msft** [comment] 2021-11-02 19:47
_In general_: We don't really need to know anything more about OS version and Terminal version for this one. We've got a good idea of what's causing this.

The Windows 11 data point is a little interesting, we thought that the underlying bug in the OS for migrating the font files from one version to the next was fixed, but alas, it seems it also regressed since when it was first fixed in Windows 11. So this will _continue_ to plague users at random till we fix this.

**Comment by miniksa** [comment] 2021-11-03 22:14
#11032's mitigation will likely mitigate this too.

**Comment by DHowett** [comment] 2021-12-14 18:22
This is still an issue and will continue to be an issue until we nail nearby font loading.

Notes from discussion:

> But the heart of the issue is that our system collection contains a pointer to a font that is locked for deletion, because the app platform locked it for deletion since it's part of our package
> We needed to do fallback when we failed to actually load the font, to a collection that doesn't have the issue

**Comment by ilor** [comment] 2022-02-07 08:44
Happened to me again on 1.13.10336.0 (current preview version in the store afaict)

**Comment by srdjanjovcic** [comment] 2022-04-13 11:54
This is not fixed on Windows 10 in 1.13.10983.0

**Comment by lhecker** [comment] 2022-04-14 00:38
Reopening because I found a flaw in my implementation.
In case people wonder how we're failing so hard at fixing this: We're simply unable to repro this issue. All fixes are purely theoretic. Even my new fix is just made on an assumption (a pretty good one this time if I may say so).

**Comment by tylerszabo** [comment] 2022-04-14 00:47
I'm not sure if it helps but the issue seems to be system-wide when it happens. This causes crashes in gVim when attempting to load "Cascadia Code" after Windows Terminal has updated on my Windows 11 box. I worked around using @Mindfulplays' suggestion to install manually.

I suspect the issue is less with loading the font incorrectly and something to do with installing the font incorrectly. I tend to be using the font somewhere at all times so perhaps there's some kind of issue with replacing it when it's being used in some way.

**Comment by lhecker** [comment] 2022-04-14 00:49
@tylerszabo Yes, we know that the actual underlying issue certainly isn't our fault. I'm not sure what the current state of an fix for that is (I can faintly remember hearing it's fixed in a newer Windows 11 build?), but in the meantime we'd of course want to fix it ourselves as quickly as possible.

**Comment by ilor** [comment] 2022-04-14 14:25
Happened for me again on 1.13.10983.0 on Windows 10 21H2, making for roughly the fourth time in a year I had this. Some additional data points:
* I've rebooted a few hours ago to install Windows updates
* This didn't break right on startup. In fact I have two shell tabs open where the font is okay, and only now (a few hours later) opening a new tab of the same type complains about the Cascadia Mono being MIA.

**Closed** 2022-04-14 22:05 UTC
Labels: Area-Fonts, Issue-Bug, Product-Terminal, In-PR, Priority-1

**Comment by michiel-sunweb** [comment] 2023-02-25 07:52
@lhecker You wrote:

> because we're simply unable to repro this issue

Perhaps the 3 steps below will help reproduce the issue. (Although @zadjii-msft mentioned you don't really need to know anything more about OS version, I should say I use Windows 11 ARM in Parallels on an M1 Mac).

**STEP 1**: Download and unzip Cascadia Mono PL:

```PowerShell
# Download the archive file
$downloadsPath = "$Env:USERPROFILE\Downloads"
$zipFileName = "CascadiaCode-2111.01.zip"
$zipFilePath = "$downloadsPath\$zipFileName"
$url = "https://github.com/microsoft/cascadia-code/releases/download/v2111.01/$zipFileName"
Invoke-WebRequest -Uri $url -OutFile $zipFilePath

# Expand, then delete, the archive file
$expandedDirectoryPath = "$downloadsPath\CascadiaCode-2111.01"
Expand-Archive -Path $zipFilePath -Destination $expandedDirectoryPath
Remove-Item -Force -Path $zipFilePath
```

**STEP 2**: Copy and register the font such that it causes the issue in Windows Terminal:

```PowerShell
# Ensure destination directory exists
$fontsDirectoryPath = "$Env:LOCALAPPDATA\Microsoft\Windows\Fonts"
if (-not (Test-Path $fontsDirectoryPath))
{
    $directory = New-Item -Force -ItemType Directory -Path $fontsDirectoryPath
}

# Copy font file
$fontFileName = "CascadiaMonoPL.ttf"
$fontFileSourcePath = "$Env:USERPROFILE\Downloads\CascadiaCode-2111.01\ttf\$fontFileName"
$fontFileDestinationPath = "$fontsDirectoryPath\$fontFileName"
Copy-Item -Path $fontFileSourcePath -Destination $fontFileDestinationPath

# Ensure the registry key exists
$fontsKey = "HKCU:\Software\Microsoft\Windows NT\CurrentVersion\Fonts"
if (-not (Test-Path -Path $fontsKey))
{
    $key = New-Item -Force -ItemType Directory -Path $fontsKey
}

# Add the registry key for the font file
$value = New-ItemProperty -Force -Name "Cascadia Mono PL Regular (TrueType)" -Path $fontsKey -PropertyType $type -Value $fontFileDestinationPath
```

**STEP 3**: Verify that Windows Terminal is unable to find the font.

**STEP 4**: Properly install the font such that it does not cause the issue in Windows Terminal:

(The Windows Shell should ask if you want to replace the 'Cascadia Mono PL Regular' font when you run the script below. You should answer Yes.)

```PowerShell
# Create the Windows Shell's automation object and use the fonts namespace
$shell = New-Object -ComObject "Shell.Application"
$fonts = $shell.Namespace(0x14)

# Copy font file
$fontFileName = "CascadiaMonoPL.ttf"
$fontFileSourcePath = "$Env:USERPROFILE\Downloads\CascadiaCode-2111.01\ttf\$fontFileName"
$fonts.CopyHere($fontFileSourcePath, 20)
```

**STEP 5**: Verify that Windows Terminal is able to find the font.

Hope this helps!

**Comment by cmschlenke** [comment] 2023-08-16 19:24
If any poor soul has found their way here wondering why Windows Terminal can't find their font, let me assure you that this is actually not a Windows Terminal bug, or even a Windows bug. This behavior is caused by not having the font installed for all users. Follow these steps to remedy the problem... https://answers.microsoft.com/en-us/windows/forum/all/solution-installed-fonts-disappearing-after/146f4039-47c3-4017-a9b1-76f72badce39

**Comment by psxlover** [comment] 2023-10-23 17:06
I just run into this issue. Version 1.18.2822.0. Windows 10. According to the Microsoft Store Terminal was updated today.

The previous comment does not apply in my case, there is no Fonts folder in %appdata%\..\Local\Microsoft\Windows.

What's even more confusing is that in "Fonts" they are "there" but are invisible until I hove over them with the mouse in  which case only the names appear:
![image](https://github.com/microsoft/terminal/assets/1429524/79156cf0-a39b-44df-bb9a-9afed26e887e)
![image](https://github.com/microsoft/terminal/assets/1429524/d65ae2e1-5f58-4219-a4a8-d6f0867221e2)

**Comment by DHowett** [comment] 2023-10-23 17:07
This was an issue on Windows 10 that Terminal had worked around. We recently (accidentally) broke our workaround. Stay tuned. :smile:

**Comment by psxlover** [comment] 2023-10-23 18:20
Glad to hear it is a known issue and not just something wrong with my PC.

**Comment by barkermn01** [comment] 2023-11-07 20:06
@DHowett i believe there is a specific term for that it's called a Regression :D

**Comment by stevenwong** [comment] 2023-11-30 09:27
If anyone needs a temporary fix, uninstalling then reinstalling the Terminal app solved it for me.

**Comment by IMB11** [comment] 2024-09-07 12:34
I fixed this issue by making sure that the font being used was installed for all users instead of locally just for my user.
