### ISSUE TITLE
Scaling artifacts in Far Manager and Midnight commander

### ISSUE THREAD

**Issue by iovuio** [microsoft/terminal#5240] opened 2020-04-04 19:56 UTC
# Environment

```none
Windows build number: Microsoft Windows NT 10.0.19041.0
Windows Terminal version: microsoft-windows-terminal 0.10.781.0

Any other software?
Chocolatey
Far
```

# Steps to reproduce

1. Install Far Manager. (e.g. with Chocolatey in an admin-enabled pwsh `choco install far`).
2. Change your Display scaling to 125%.  (Settings -> System -> Display -> Scale and layout -> 'Change the size of text...')
3. Open Windows terminal. Open a Cmd, PowerShell or PowerShell Core tab.
4. Start Far Manager. Type `far`.

# Expected behavior
No unwanted artifacts due to scaling.

# Actual behavior
Unwanted artifacts as black horizontal lines when scaling other than 100%, 200%. (c.f. [PNG screenshot](https://i.imgur.com/41Z9q3F.png))

# Note
PowerShell and PowerShell Core in their own windows behave correctly with all scaling settings(c.f. [PNG screenshot](https://i.imgur.com/n7NLh8T.png))
Issue pertains to midnight commander in WSL instances (`sudo apt install mc`) (c.f. [PNG screenshot](https://i.imgur.com/NljhbT3.png))

**Comment by j4james** [comment] 2020-04-04 20:25
This is probably #3626, which has recently has a PR merged, so it should hopefully be fixed soon.

**Comment by DHowett-MSFT** [comment] 2020-04-05 23:10
This definitely is a /dupe of #3626! Thanks, as always, James.

**Closed by DHowett-MSFT** 2020-04-05 23:10 UTC
Labels: Needs-Tag-Fix, Needs-Triage
