### ISSUE TITLE
Add/Replace shortcut to Windows Terminal in Windows+X context menu

### ISSUE THREAD

**Issue by fredrikhr** [microsoft/terminal#5942] opened 2020-05-16 14:36 UTC
# Description of the new feature/enhancement

It would be great if Windows Terminal offered the possibility to add a shortcut to the Win+X context menu (the context menu that appears when right-clicking on the start menu, or when hitting Windows key + X).

In that case, the Windows Terminal could even replace the Command Prompt or Windows PowerShell shortcuts in that menu.

# Proposed technical implementation details

It would be nice if Windows Terminal did this automatically when installed, but the safe approach might be to add a new option to the `wt.exe` that enabled registration into the WinX context menu. (And also the removal, and replacing existing Command Prompt / PowerShell shortcuts).

# Manual registration

Since I am really used to the Win+X then hit C (the mnemonic character for the Command Prompt shortcut) keyboard combination, I investigated how this could be done manually. I published my results and reproduce-steps in a Gist: https://gist.github.com/fredrikhr/0994a6e81443c439659db1d9763365d7

# Note

If this feature is added, special care must be taken to ensure that the shortcut's chosen mnemonic does not interfere/overlap with the existing shortcuts in the menu. E.g. `T` cannot be chosen as a Windows Terminal shortcut mnemonic, since `T` already is chosen for the `Task Manager` shortcut.

**Comment by DHowett** [comment] 2020-05-18 21:49
Thanks for writing this up! Yeah, it's quite a pain to get the shortcut registered. I'd ... love to do away with that burden.

Right now, I think you'll be best served by #492 -- it'll make questions like this unnecessary once we land it.

Until we land that, we can't really do anything from where we stand: we're a packaged application that doesn't get an "installer" and therefore can't offer any options, and I'd be wary about having the application do this on startup. We've run afoul of user expectations before by writing things they didn't want to disk.

Marking this as a spiritual /dupe of #492

**Comment by DHowett** [comment] 2020-05-18 21:50
(Before we started this project we joked that we could use <kbd>Win+/</kbd> as a global shortcut because of how prominently it features in paths. It never came to fruition.)

**Closed by DHowett** 2020-05-18 21:49 UTC
Labels: Issue-Feature, Needs-Tag-Fix, Needs-Triage
