### ISSUE TITLE
profiles.json formatting lost on save

### ISSUE THREAD

**Issue by thnk2wn** [microsoft/Terminal#709] opened 2019-05-11 19:34 UTC
Code as of 6088134832b851c553af791ee17a9b5c0d808385

* Your Windows build number:  Microsoft Windows [Version 10.0.18362.86]

* What you're doing and what's happening: 
1. Clicked the dropdown in the upper right corner
2. Clicked Settings
3. Code launched with profiles.json in a compact form
4. Formatted the JSON so I could more easily read and edit it
5. Saved the file
6. File is immediately reloaded and put back into compact, unformatted form, making it difficult to edit again.

* What's wrong / what should be happening instead:
1. Expect formatting to persist after saving a change or if the app needs to modify it after detecting a change to at least format it with indentation / beautify / formatter

**Comment by DHowett-MSFT** [comment] 2019-05-11 20:46
This'll be a duplicate of #475. Thanks!

**Closed by DHowett-MSFT** 2019-05-11 20:46 UTC
Labels: Resolution-Duplicate
