### ISSUE TITLE
I do not like the new text rendering engine

### ISSUE THREAD

**Issue by henrijuk** [microsoft/terminal#18118] opened 2024-10-28 07:46 UTC
### Windows Terminal version

1.21.2911.0

### Windows build number

10.0.22631.4317

### Steps to reproduce

Use the (default) Cascadia Mono font (size 12) and compare the appearance of text in the terminal between the old renderer (possible to still use in versions prior to 1.21) and the new renderer.

I mostly use 2560x1440 display resolution but this happens on any display resolution with Windows' rendering scale set to default 100%.

(Option to use the old renderer was removed in 1.21.2361.0 as per the release notes.)

(I was still using the option to use the old renderer and now the option to use it is gone. I'm assuming the reason is that 1.21 was recently pushed to all users, including me. I don't know exactly on what version I was before; I was hit by the changed rendering on Oct 25th and then noticed I had 1.21 and the old option was gone.)

### Expected Behavior

Expecting to see the same well-proportioned font as before (and not this vertically elongated abnormity).

### Actual Behavior

The new engine renders the font differently. Most noticeably tall characters (e.g. capital letters, numbers, lowercase L, etc.) are vertically elongated (pixel or two taller than before), distorting the font proportions. The font also looks generally thicker.

New renderer (1.21, distorted font):
![Image](https://github.com/user-attachments/assets/704871f1-4bf6-423c-b676-85825b473d4b)

Old renderer (preferred):
![Image](https://github.com/user-attachments/assets/74cb301b-6c59-47fc-9de6-39c2d35e5b5f)

The most noticeable difference in the above attached screenshots are the numbers, especially the zeros, and the capital A letter.
Other changes are a lot easier to notice when comparing the images in-place one after the other (center them on full screen with 100% image scale and hit arrows or some other key to switch between them).

For some, this may seem like a minuscule problem but for me this is a big deal. I look at the terminal a lot and a change like this is distracting. The new taller and thicker rendering is more "restless" to me.

**Comment by Foo-x** [comment] 2024-10-28 12:33
Confirmed at 1920x1080 resolution in 1.21.2911.0 too.

**Comment by lhecker** [comment] 2024-10-28 20:21
Can you try and decrease your font size ever so slightly by 0.1 steps until the appearance changes? E.g. something like 11.5?

**Comment by mcnameej** [comment] 2024-10-28 20:23
I don't use Cascadia Mono as my terminal font. But I'm seeing rendering problems with it in other places. The problem may be the font, not WT.

I have both VS 2017 and VS 2022 installed on my laptop, and I updated both of them on Friday. Today (Monday) I noticed that VS and VS Code both looked wrong. I suspect one of the VS updates broke it.

It looks to me like all the font weight variants of Cascadia Mono are rendering as ExtraLight.

**Comment by DHowett** [comment] 2024-10-28 20:49
FWIW, the difference in your screenshots just looks like hinting.

Fonts often contain instructions on how to snap to crisp pixel boundaries at specific point sizes. Those instructions are designed to reduce blurriness when presented at 100% scale on LCD monitors from before the industrial era. :)

For comparison, this is what ExtraLight actually looks like (150% scale)

![Image](https://github.com/user-attachments/assets/6608e3eb-251d-4c42-8209-011aa812efb8)

cf. Regular

![Image](https://github.com/user-attachments/assets/1e805554-56f8-4353-b200-7eb906e3c28e)

This is what ExtraLight looks like at 100% scale:

![Image](https://github.com/user-attachments/assets/fb467afd-6d4d-4404-9a77-f19ee139e4b5)

I do not think that you are seeing ExtraLight. Just properly-hinted Regular. You can bust the hinting by using a fractional font size (as Leonard points out, but with more explanation.)

**Comment by DHowett** [comment] 2024-10-28 20:50
(I have also de-editorialized your title.)

**Comment by lhecker** [comment] 2024-10-29 00:06
I've just had a chance to test this and a font size of 11.5 indeed restores the look of the previous text renderer. I've updated my comment above accordingly. Please give it a try and let us know if that works for you!

As an aside, I strongly recommend enabling ClearType (unless you dislike it). You can enable it in the settings when you click on the "Defaults" profile, then on "Advanced" at the bottom. The second item will be "Text antialiasing". If you set it to ClearType, it'll significantly improve the text clarity. I've been meaning to make it the default on low-DPI displays but haven't gotten to it yet.

What DHowett said above matches my understanding of how DirectWrite works. In the old text renderer when you'd ask for a font size of 12, you'd actually get 11.749232428 or some other fractional number due to workarounds that aren't relevant anymore. The new text renderer on the other hand will render the text at the exact font size you tell it. This is the reason why I don't want to change the behavior, even though I fully get what you mean.

But... I think we can take another potential solution from this issue: We currently unconditionally enable hinting for text rendering and disable vertical anti-aliasing (this is the default under Windows for small font sizes). It would be very easy for us to add a "disable hinting" setting (= `DWRITE_RENDERING_MODE_OUTLINE`) and a "enable vertical AA" setting (= `DWRITE_RENDERING_MODE_NATURAL_SYMMETRIC`). The former would solve your issue similar to using the 11.5 font size. It would also have the benefit that text will be rendered just like on MacOS/iOS. I feel like we already have an issue for that somewhere though...

**Comment by Foo-x** [comment] 2024-10-29 04:14
Looks like changing the font size to 11.5 works.
Thank you!

I'm using Fira Mono.
12
![Image](https://github.com/user-attachments/assets/b4040d58-eb2f-4116-94ff-a62ed15fa052)

11.5
![Image](https://github.com/user-attachments/assets/8ca41b43-f8fc-4e1b-8483-581f15d9814c)

**Comment by henrijuk** [comment] 2024-10-29 07:36
> I don't use Cascadia Mono as my terminal font. But I'm seeing rendering problems with it in other places. The problem may be the font, not WT.
> 
> I have both VS 2017 and VS 2022 installed on my laptop, and I updated both of them on Friday. Today (Monday) I noticed that VS and VS Code both looked wrong. I suspect one of the VS updates broke it.
> 
> It looks to me like all the font weight variants of Cascadia Mono are rendering as ExtraLight.

I noticed my problem already in March 1st 2024, when the default option for renderer was changed to the new renderer.

(Back then I found the option for old renderer and it solved my problems. I did not have time to make an issue about it, sorry, and I did not expect the option for the old renderer to disappear.)

**Comment by henrijuk** [comment] 2024-10-29 07:50
> (I have also de-editorialized your title.)

That's ok, the old title was a little unprosessional anyway but it seems to have served it's purpose, hehe. 😁 Thanks for the fast responses, I really appreciate them!

I understand that the new renderer is probably better in many aspects and it is preferred. So the new title is only partially true (for me). 
I have really enjoyed the Terminal and it looked just lovely. I just don't like how the font changed.

**Comment by henrijuk** [comment] 2024-10-29 08:08
> As an aside, I strongly recommend enabling ClearType (unless you dislike it). You can enable it in the settings when you click on the "Defaults" profile, then on "Advanced" at the bottom. The second item will be "Text antialiasing". If you set it to ClearType, it'll significantly improve the text clarity. I've been meaning to make it the default on low-DPI displays but haven't gotten to it yet.

I enabled ClearType in the Settings of WT and did not notice any difference. The text in WT looks sharp and clear with both ClearType and Grayscale.

(I do have ClearType enabled in Windows already, I dunno if this affects it.)

(Also, the screenshots I posted look a bit blurry when viewed in this page. When viewed separately with 100% image scale they look sharp. However, AFAIK ClearType only affects how the display shows pixels on the screen so it should not affect screenshots?)

**Comment by henrijuk** [comment] 2024-10-29 08:12
> I've just had a chance to test this and a font size of 11.5 indeed restores the look of the previous text renderer. I've updated my comment above accordingly. Please give it a try and let us know if that works for you!

I did not know fractional font sizes were supported. (The Settings won't let me enter 11.5, which I had tried before.) Now I found out it can be changed in the `settings.json`.

I tried 11.5pt and it indeed works, thanks! (That is, the font looks now the same as with the old renderer and 12pt in the settings.)
I tried also 11.6pt and the result was identical to 11.5pt. Also, 11.7pt looked the same as 12.0pt (bad).

Here are some screenshots:

New renderer (v1.21) with 12.0pt in `settings.json`: (BAD)
![Image](https://github.com/user-attachments/assets/ab5e4c76-b176-40ee-a0ed-39557d2b3c00)

New renderer (v1.21) with 11.5pt in `settings.json`: (GOOD)
![Image](https://github.com/user-attachments/assets/8d1bba8c-d552-4dd7-a2bd-cd6ee0747058)

Old renderer with 12pt in Settings: (GOOD)
![Image](https://github.com/user-attachments/assets/399e1fcb-dcf2-499a-b7e3-29eb9fa5742b)

**Comment by henrijuk** [comment] 2024-10-29 09:01
> I do not think that you are seeing ExtraLight. Just properly-hinted Regular. You can bust the hinting by using a fractional font size (as Leonard points out, but with more explanation.)

Does this mean that I actually prefer the unhinted 11.5pt version of the font, and it is the properly-hinted 12.0pt that is giving me gray hair?

**Comment by lhecker** [comment] 2024-10-29 13:37
> I have heard of hinting, mostly in the context of LaTeX and there it usually resulted in better appearance and usually not the whole looks of the font changing. (Although poorly hinted fonts were known to have issues.)

LaTex does not use hinting - that's the job of your PDF viewer or printer. You may be thinking of "kerning", e.g. via the `microtype` package, which makes the letter spacing more uniform.

> However, AFAIK ClearType only affects how the display shows pixels on the screen so it should not affect screenshots? Is this true?

ClearType will affect screenshots as well. You can recognize it by the red/blue shift on the edges (these are screenshots taken directly from Windows Terminal):
![Image](https://github.com/user-attachments/assets/407d7197-d766-4f75-8b47-5d3a22a2d0a5)

> I did not know fractional font sizes were supported. (The Settings won't let me enter 11.5, which I had tried before.)

It should just work:
![Image](https://github.com/user-attachments/assets/62001b96-2279-4415-a70b-9d3b856118ee)

> I tried also 11.6pt and the result was identical to 11.5pt. Also, 11.7pt looked the same as 12.0pt (bad).

DirectWrite uses pixel snapping and has no vertical anti-aliasing and so there's only a limited amount of decimal precision during rendering. But even if the appearance doesn't change in an obvious way, the font size still affects numerous other things, like the cell width and line height.

> There is still maybe some tiny difference with line spacing but it doesn't matter. :)

Below the font size setting is a "Line height" setting. Try changing it to something around 1.2.

> Does this mean that all this time I actually preferred the unhinted 11.5pt version of the font, and it is the properly-hinted 12.0pt that is now giving me gray hair?

I did some more tests. It took a while because I need to pull out Microsoft Visual TrueType for that as well as the old text renderer. 😅 In your particular case it's not actually because hinting got circumvented, but rather because 11.5 happens to trigger DirectWrite to rasterize the glyph at 11pt, while it just so happened to trigger the old text renderer to draw the line height as if it was 12pt (due to fractional rounding). Roughly the same thing happens with the new text renderer but at 11.5pt.
Put differently, you liked the appearance of 11pt Cascadia Mono with an increased line height. 🙂

**Comment by henrijuk** [comment] 2024-10-29 17:17
> LaTex does not use hinting - that's the job of your PDF viewer or printer. You may be thinking of "kerning", e.g. via the `microtype` package, which makes the letter spacing more uniform.

Ah yes, you are correct. I meant that LaTeX distributions usually come with some font packages, and some of the fonts had better hinting than others which is then visible in the produced pdf file.
 
> ClearType will affect screenshots as well. You can recognize it by the red/blue shift on the edges

Thanks for correcting this!

> > I did not know fractional font sizes were supported. (The Settings won't let me enter 11.5, which I had tried before.)
> It should just work: ![Image](https://github.com/user-attachments/assets/62001b96-2279-4415-a70b-9d3b856118ee)

I guess there is (another) funny little bug: when the Settings show the default value, it shows it with a decimal point. But if I want to use a fractional value it only accepts the input with a decimal comma (probably due to my locale settings, we use a decimal comma around here).

> Below the font size setting is a "Line height" setting. Try changing it to something around 1.2.

Now that I could successfully change it (because of the comma/period thing), it looks like font size 11.0 with line height ~1.27--1.32 gives the look I want. Same with font size 11.6 and line height 1.2. (Font size 11.0--11.5 and line height 1.2 gives tighter line spacing, and font size 11.7 gives the 12pt font which I apparently hate :D)

> I did some more tests. It took a while because I need to pull out Microsoft Visual TrueType for that as well as the old text renderer. 😅 In your particular case it's not actually because hinting got circumvented, but rather because 11.5 happens to trigger DirectWrite to rasterize the glyph at 11pt, while it just so happened to trigger the old text renderer to draw the line height as if it was 12pt (due to fractional rounding). Roughly the same thing happens with the new text renderer but at 11.5pt. Put differently, you liked the appearance of 11pt Cascadia Mono with an increased line height. 🙂

Thanks for your efforts, this really helped! :)

**Comment by carlos-zamora** [comment] 2024-10-30 21:37
Glad it worked! Closing!

**Closed by carlos-zamora** 2024-10-30 21:37 UTC
Labels: Issue-Question, Area-Fonts, Resolution-Answered, Needs-Triage
