### ISSUE TITLE
Cannot Use doublequotes on settings.json (even escaped)

### ISSUE THREAD

**Issue by G3NSVRV** [microsoft/terminal#11206] opened 2021-09-12 17:23 UTC
### Windows Terminal version (or Windows build number)

10.0.18363.0

### Other Software

cmd.exe

### Steps to reproduce

On **settings.json** use the following:

```json
"commandline": "powershell.exe Start-Process cmd.exe '/c wt.exe -p \"Windows PowerShell\"' -verb runAs",
```
Double quotes is required since the name has an space character.

[settings.json.txt](https://github.com/microsoft/terminal/files/7150019/settings.json.txt)

### Expected Behavior

If you ran the same on powershell or cmd directly, you can get the expected result which is open the Windows Terminal with a Desired Profile:

PowerShell
```powershell
Start-Process cmd.exe '/c wt.exe -p "Windows PowerShell"' -verb runAs
```

Command Prompt
```cmd
powershell.exe Start-Process cmd.exe '/c wt.exe -p \"Windows PowerShell\"' -verb runAs```
```

![image](https://user-images.githubusercontent.com/11720535/132996925-9b5ae5e7-6de7-4d18-bc95-aeb8e21cec78.png)

### Actual Behavior

This configuration is not being taken, instead opens the default profile.

![image](https://user-images.githubusercontent.com/11720535/132996931-ec38c452-85fd-4812-a20b-3a4eeaa12997.png)

**Comment by elsaco** [comment] 2021-09-12 18:19
Not sure what version of WT you're running but here version 1.10.2383.0 doesn't have a "-p" option. I guess that would be for selecting a profile. My take is WT uses GUIDs for selecting profiles not profile names, and it defaults to PS.

Sample WT help:

![wt_help](https://user-images.githubusercontent.com/3933920/132998306-13e66191-3ab2-430a-895a-b12cdf3ff123.png)


Run "wt.exe -h" to see WT help.

**Comment by G3NSVRV** [comment] 2021-09-12 18:23
@elsaco you are wrong, it is documented and work just fine directly from the command line **(I though that was clear that on the "expected behaviour" section it works)**

https://docs.microsoft.com/en-us/windows/terminal/command-line-arguments?tabs=windows#open-a-new-profile-instance

**Comment by elsaco** [comment] 2021-09-12 19:32
@G3NSVRV true, I'm wrong sometimes!

I've changed your command to:

`"commandline": "powershell.exe Start-Process cmd.exe '/c wt.exe -p Windows PowerShell' -verb runAs",
`

and it launches a new windows with admin privileges:

![wt_some_command](https://user-images.githubusercontent.com/3933920/133000338-00f6dfba-1c5d-466f-8563-6249e9966c4b.png)

**Comment by G3NSVRV** [comment] 2021-09-12 19:53
@elsaco Still didn´t work. I think in your case you got that result because your default profile is powershell, mine is ubuntu:

![image](https://user-images.githubusercontent.com/11720535/133000928-18d2c3f2-c479-4644-a1a4-74268e262909.png)

**Comment by elsaco** [comment] 2021-09-12 20:02
This should do it:

`"commandline": "powershell start-process wt.exe '-p \"Windows PowerShell\"' -verb runAs",`

I tried with a Bash profile and it worked. Also there's no need to have powershell launch cmd to launch a powershell session with admin privileges. Too many chained commands, IMO.

**Comment by G3NSVRV** [comment] 2021-09-12 20:07
@elsaco that is what I tried first time, but didn't work, I got this error:
![image](https://user-images.githubusercontent.com/11720535/133001268-d9ad416c-30ff-4032-8897-4d4a53b2c32b.png)

**Comment by elsaco** [comment] 2021-09-12 20:24
Hi,

I'm not sure why it is not working for you. I've changed my default profile
to launch Ubuntu and then use a profile with the command mentioned before.
The only funny thing is that the color scheme seems to be inherited from
Ubuntu, at least the background.

Sample screenshot with new profile. I did edit the settings.json directly,
but it shouldn't matter:

[image: ubuntu_ps-admin_launch.png]

Looking at the error message there might be a file access issue at
your end. Hope this helps!

**Comment by G3NSVRV** [comment] 2021-09-12 20:28
@elsaco same happened to me, that means that does not load the "Powershell" profile properly.

I did this workaround and works flawlessly:

settings.json
```json
"commandline": "powershell D:\\elevated-wt.ps1",
```

elevated-wt.ps1
```powershell
Start-Process cmd.exe '/c wt.exe -p "Windows PowerShell"' -verb runAs
```

**Comment by G3NSVRV** [comment] 2021-09-12 20:37
so that means that is possible to configure it is just that by default from the JSON config something happened with the quoting and you got weird behaviours.

**Comment by zadjii-msft** [comment] 2021-09-13 14:13
Yea, something weird is going on with the quote escaping here, but it's hard to tell exactly what because there are just so many layers of commandline escaping here. I'm sure someone with more time than me could figure it out. 

At the end of the day though, looks like what you're looking for is #632 😉 


I'm gonna close this for now since you've seemed to figure it out for yourself, though if anyone else finds the right way to escape the commandlines here, feel free to share it!

**Closed by zadjii-msft** 2021-09-13 14:13 UTC
Labels: Needs-Triage, Needs-Tag-Fix

**Comment by G3NSVRV** [comment] 2021-09-13 16:24
> I'm sure someone with more time than me could figure it out. 

That means that all the team will not be able to resolve this? the case is closed, and should be open.

> At the end of the day though, looks like what you're looking for is #632 😉 

Yes and no, I don't have issues with the escalation privileges persé, I have issues with the quoting and because of that I believe that this case should remain open.

> I'm gonna close this for now since you've seemed to figure it out for yourself, though if anyone else finds the right way to escape the commandlines here, feel free to share it!

A workaround does not mean that is a permanent solution, the quoting issue is still present.

**Comment by DHowett** [comment] 2021-09-13 16:45
> A workaround does not mean that is a permanent solution, the quoting issue is still present.

Unfortunately, this issue is going to remain until somebody (not us!) figures out shell quoting rules. The problem is that we're passing your commandline directly to `CreateProcess` (the main engine of process creation on Windows), and whatever happens after that is utterly out of our control. We don't change, quote, de-quote or re-quote the command line in any way before we do that.

In short, there are at least three programs handling your commandline, and each getting different subsets of it based on the way you quote it.

```
"commandline": "powershell.exe Start-Process cmd.exe '/c wt.exe -p \"Windows PowerShell\"' -verb runAs",
```

Terminal processes this into (this should be no surprise):

```
powershell.exe Start-Process cmd.exe '/c wt.exe -p "Windows PowerShell"' -verb runAs
```

PowerShell processes this into (hopefully?)

```
Start-Process cmd.exe '/c wt.exe -p "Windows PowerShell"' -verb runAs
```

**However, it does not.**

It actually turns it into this:

```
Start-Process cmd.exe '/c wt.exe -p Windows PowerShell' -verb runAs
```

Note the missing quotes.

This spawns...

```
cmd /c wt.exe -p Windows PowerShell
```

Which causes Terminal to look for a profile called `Windows`.

**Comment by elsaco** [comment] 2021-09-13 16:57
@DHowett  adding profiles without space in the profile name would take care of the issue? How about using profile's UUID instead of name?

**Comment by DHowett** [comment] 2021-09-13 17:03
Both of those should work!

You can definitely use the profile's guid!

```
wt -p "{61c54bbd-c2c6-5271-96e7-009a87ff44bf}"
```

should work for the Windows PowerShell profile.

**Comment by G3NSVRV** [comment] 2021-09-13 17:06
@DHowett @elsaco @zadjii-msft Far as I tested, this does not works too:

```json
"commandline": "wt.exe -p \"Windows Powershell\"",
```

But this works:
```json
"commandline": "wt.exe -p {61c54bbd-c2c6-5271-96e7-009a87ff44bf}",
```

So it is clearly an issue with the space, and as you see I'm not using any other layer like powershell or cmd, just wt.exe.

**Comment by G3NSVRV** [comment] 2021-09-13 17:11
ok, I tried again, I forget that `commandline` is case sensitive, I replaced `Powershell` to `PowerShell` and that works fine, so as @zadjii-msft and @DHowett pointed out, it might be an issue with another layer like powershell or cmd.

**Comment by G3NSVRV** [comment] 2021-09-13 17:15
this works perfectly fine, so yeah, I think it is good to have it closed, I will reference this issue on the elevation issue if someone tries to configure a profile with spaces:

```json
"commandline": "powershell Start-Process cmd.exe '/c wt.exe -p {61c54bbd-c2c6-5271-96e7-009a87ff44bf}' -verb runAs",
```

**Comment by ofsaleem** [comment] 2021-09-14 00:03
came here via the email (presumably) you sent out from the other long, locked thread, and using the guid for the profile solved it!! i get a new window that is properly elevated and colored and is in powershell and not bash and everything. excellent work, thank you so much
