### ISSUE TITLE
Feature Request：Consider Supporting quick start shortcut key

### ISSUE THREAD

**Issue by cjp715711877** [microsoft/terminal#1179] opened 2019-06-08 17:19 UTC
like cmder or other terminal,can set a shortcut key,this shortcut key can hide or show terminal window.
and if enable this setting ,the terminal do not show in taskbar.
: )

**Comment by DHowett-MSFT** [comment] 2019-06-09 03:28
Thanks for suggesting a feature! This is a duplicate of #653. Please make sure you’re searching for existing issues when you submit a new one!

**Closed by DHowett-MSFT** 2019-06-09 03:28 UTC
Labels: Issue-Feature, Needs-Tag-Fix, Needs-Triage
