### ISSUE TITLE
Ability To Save The Current Session

### ISSUE THREAD

**Issue by portexe** [microsoft/terminal#7574] opened 2020-09-08 23:38 UTC
# Description of the new feature/enhancement

Suppose a user has several tabs open at different locations on the files system. For example:

Tab 1: `C:\Users\UserName\FolderA`

Tab 2: `C:\Users\UserName\FolderB`

Tab 3: `C:\Users\UserName\FolderC`

It would be fantastic if the user could be able to save the session so that they could easily return to the state they were in after a reboot, or after closing/re-opening the application. Saving the state to a config file, and then being able to open it through a command such as `terminal-load saved_config_name` or via the GUI would be incredibly helpful.

**Comment by portexe** [comment] 2020-09-08 23:41
I will gladly do the work if I can be pointed in the proper direction, Unfortunately my C++ knowledge is very limited, but I will learn it for this feature, because it would be extremely helpful.

**Comment by skyline75489** [comment] 2020-09-09 02:40
We have received similar requests. There is #961 which is the thread you may want to subscribe.

**Comment by DHowett** [comment] 2020-09-10 00:46
Thanks all! I'm gonna mark this one as a /duplicate of #961 just so we can keep our discussions all in the same place. We're not in a great place to take code for this feature right now, but the places to look at would be TerminalApp's startup (WindowsTerminal main, AppHost) and the text buffer (which we would want to save.)

**Closed by DHowett** 2020-09-10 00:46 UTC
Labels: Issue-Feature, Needs-Tag-Fix, Needs-Triage
