### ISSUE TITLE
[Terminal]: Narrator is staying silent on hovering mouse over the editor by turning 'Mouse mode' on.

### ISSUE THREAD

**Issue by Saiteja341** [microsoft/terminal#15101] opened 2023-04-04 12:22 UTC
### Windows Terminal version

1.16.10262.0

### Windows build number

23031.1000

### Other Software

Test environment: 
OS: Version 22H2 (OS build 23031.1000)
Application: Windows Terminal
Screen reader: Narrator

### Steps to reproduce

Pre-requisite:
User have to turn on the 'Read & interact with the content using mouse' toggle button from 'Settings>Accessibility>Narrator'.

Repro steps:

1. Open the 'windows terminal' application.
2. Log in with valid credentials.
3. Follow the above-mentioned pre-requisite step.
4. Execute around two or three commands.
5. Turn on narrator using 'Ctrl+Windows+Enter' keys.
6. Now, hover mouse over the editor & observe the screen reader narration.

User Experience:
Users who rely on screen reader will not be able to utilize the mouse mode functionality of narrator, if narrator stays silent on hovering mouse over the editor.

Guideline reference:
https://www.w3.org/TR/WCAG21/#info-and-relationships

Attachment:
[Narrator is staying silent on hovering mouse over the editor using Narrator mouse mode..zip](https://github.com/microsoft/terminal/files/11148415/Narrator.is.staying.silent.on.hovering.mouse.over.the.editor.using.Narrator.mouse.mode.zip)

### Expected Behavior

Screen reader should narrate the context present in the editor, on hovering mouse by turning mouse mode of narrator on.

### Actual Behavior

Narrator is staying silent, on hovering mouse over the editor by hovering mouse by turning mouse mode of narrator on.

**Comment by carlos-zamora** [comment] 2023-07-25 22:54
Hi @Saiteja341.

This is a duplicate of #7766 on our repo.
More importantly, this is actually a bug on XAML Islands: https://github.com/microsoft/microsoft-ui-xaml/issues/2182.

Since this is an external bug, can we close this? Any way you'd like us to tag this up?

**Comment by carlos-zamora** [comment] 2023-08-02 16:22
Discussed with a11y team offline. Told to close it and they'll take care of tagging it up appropriately.

**Closed by carlos-zamora** 2023-08-02 16:22 UTC
Labels: Issue-Bug, Area-Accessibility, Product-Terminal, Tracking-External, HCL-E+D, A11yWCAG, HCL-WindowsTerminal, A11ySev2
