### ISSUE TITLE
Launch console here not in context menu

### ISSUE THREAD

**Issue by NicTanghe** [microsoft/terminal#8641] opened 2020-12-23 16:17 UTC
# Environment
```
Windows build number:  Win32NT 10.0.19042.0 Microsoft Windows NT 10.0.19042.0
Windows Terminal version (if applicable): preview from store
```

# Steps to reproduce

right click in explorer

# Expected behaviour
launch Terminal here is in the context menu.

# Actual behaviour
![image](https://user-images.githubusercontent.com/13624265/103016611-9848d480-4542-11eb-9856-2fc861b6111a.png)

It might be between keyboard and chair.

**Comment by KalleOlaviNiemitalo** [comment] 2020-12-24 13:29
Duplicate of <https://github.com/microsoft/terminal/issues/6414>, blocked by a bug in Windows.

**Comment by zadjii-msft** [comment] 2021-01-03 14:05
Yep, sure is. Thanks!

/dup #6414

**Closed by zadjii-msft** 2021-01-03 14:05 UTC
Labels: Needs-Tag-Fix, Needs-Triage
